### PR TITLE
Mark the qt5 interactive test as xfail.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

will selfmerge if passes to unbreak the build
probably worth using strict xfail later too

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Can we use the old version of Qt instead of xfail?

**Comment by anntzer** [comment]
dunno if it's a qt version problem or something else, feel free to investigate and close this if your solution works.

**Comment by jklymak** [comment]
Yeah it was a qt version change.  5.9 works fine.

**Comment by anntzer** [comment]
closed in favor of #10316

**Pull request closed without merging**
