### PR TITLE
Fix example's BasicUnit array conversion.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

The unit examples are broken in NumPy < 1.20. This fixes a bug that was exposed by #19415 ~~, but does not fix the examples fully. `radian_demo` is fixed by this change, but `ellipse_with_units` is still broken. I do not understand the NumPy subclassing methods enough to fix it short of reverting #19415..~~

A unit is a scalar, not a length-1 array. Though `BasicUnit` implements `__rmul__`, if multiplying by an array, the NumPy implementation will call `__array__` instead. If the LHS is an array, everything is fine, but if the LHS is a scalar, the previous code would incorrectly cause it to be upcast to a 1D array. When `__getitem__` was added in #19415, `np.atleast_1d` started iterating each (now 1D, not scalar) `TaggedValue`, seeing it was length 1, and made the x/y arrays into (N, 1) instead of (N,).

## PR Checklist

- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
The remaining failure is:
```
$python examples/units/ellipse_with_units.py 
Traceback (most recent call last):
  File "examples/units/ellipse_with_units.py", line 34, in <module>
    x += xcenter
TypeError: unsupported operand type(s) for +: 'TaggedValue' and 'float'
```

I am using NumPy 1.18.1/1.18.5.

**Comment by tacaswell** [comment]
It seems that our attempts to use a minimum version of numpy is getting failed on cricle and we are running the minimum version docs build with np 1.20 :facepalm: .

**Comment by QuLogic** [comment]
Good catch; hopefully this should work to fix that.

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
> I looked to see what this example does, but it doesn't do anything except register itself?

It's imported by all the other examples in this directory.

**Comment by QuLogic** [comment]
With other backports done, I hope this will work now.

@meeseeksdev backport to v3.4.x

**Pull request merged**
