### PR TITLE
Unify fig.delaxes(ax) and ax.remove().

### PR DESCRIPTION
**Pull request by anntzer**
fig.delaxes(ax) and ax.remove() are subtly different because the former
fails to correctly reset locators and formatters when removing shared
axes.  Fix that by putting the logic in delaxes and making ax.remove()
just map to it.

(We could even consider deprecating delaxes as Artist.remove() is the standard, generic way to remove any artist -- but let's not get into that discussion here :p)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Added a second commit that switched the docs to use ax.remove() rather than delaxes(ax), too -- if a user learns artist.remove(), they know how to remove any artist, whereas if he learns delaxes(), they only know how to remove an axes.

**Comment by timhoffm** [comment]
+/-0. This way, you have to know that the Axes is an Artist, which I also consider advanced knowledge. You already have my vote, so you may keep it including the new change.

**Comment by story645** [comment]
Agree on ax.remove() being cleaner than delaxes/better way to document that functionality. (And as an aside, learned about this feature from this PR and already had a use case for it today. :smile:

**Comment by anntzer** [comment]
@story645 good to go? :)

**Comment by story645** [comment]
Sorry am on phone & trying to at least not merge from mobile version of site anymore. Should this get milestoned to something?

**Comment by anntzer** [comment]
No worries 🙂

**Pull request merged**
