### PR TITLE
Pin dependencies to fix CI

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by jklymak — APPROVED** [review]
... assuming it works

**Comment by QuLogic** [comment]
Circle seems good; not sure what's up with AppVeyor yet, it's just not running pytest at all.

**Comment by QuLogic** [comment]
Might be `pip`; let's see how that goes.

**Comment by QuLogic** [comment]
Ugh, 22.0.2 is already installed

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.5.x

**Pull request merged**
