### PR TITLE
DOC/MNT install docs with dev version of sphinx theme

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Try and install mpl-sphinx-theme from git.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
I guess circle doesn't run the PR's version of the config.

The first page had some hard-coded light styling in the cards that didn't work with the dark theme.  Maybe there is a way to style them light/dark?  I don't think the default styling looks terrible.

**Comment by jklymak** [comment]
oooh, interestingly, the dark theme _is_ darkening the backgrounds of images in sphinx gallery.  The cards that the images sit on, however are stark white, so we can' should look at that.

**Comment by jklymak** [comment]
Note this really needs the dev version of mpl-sphinx-theme to look OK, and preferably after https://github.com/matplotlib/mpl-sphinx-theme/pull/37 is merged....

**Review by timhoffm — APPROVED** [review]
Let's try this.

**Comment by jklymak** [comment]
Does anyone understand why the new .circleci/config.yml is not being used on new jobs?

**Pull request merged**
