### PR TITLE
Support usetex in date Formatters

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

And some small cleanup.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
So currently, this just blanket modifies the resulting string to work in TeX mode, but I wonder if it should be more nuanced and change the formatters for only the numbers?

**Comment by jklymak** [comment]
This seems reasonable, but the tests aren't passing....

**Comment by QuLogic** [comment]
Ooops, that's because I set the default to `True` instead of `None`.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
I am inclined to merge this as-is because people still have the option of specifying the format strings as they wish (and not relying on us to auto-tex-ify them) and we can down down the route of trying to parse the dateformats and decide which should be strings and which are numbers that should be texified when someone asks for it.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
Thanks for the nudge - I forgot about this....

**Pull request merged**
