### PR TITLE
More figure-related doc updates

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Docstring updates.

### CODE REVIEW

**Comment by timhoffm** [comment]
Is there a description somewhere how to do a manual backport?

**Comment by dstansby** [comment]
https://matplotlib.org/devdocs/devel/coding_guide.html#backports

**Comment by timhoffm** [comment]
Manually backported to v2.2.2-doc
68beb9abf43ef137eb9e3b69809cb0d05ee85fae

**Comment by QuLogic** [comment]
For the future, the `-doc` branch is only for .rst file changes.

**Comment by timhoffm** [comment]
Ok, should I backport it to 2.2.x as well or is it tolerable as it is now this one time?

**Comment by QuLogic** [comment]
v2.2.2-doc will be merged into v2.2.x, so there's no need to do any more cherry-picking.

**Comment by tacaswell** [comment]
This should not have been backported to -doc, I am going to revert that commit.

To build the published docs you install the stable version and then build the docs from the -doc branch so these changes will not reflected in the built docs (see https://matplotlib.org//devel/release_guide.html#build-and-deploy-documentation).

Sorry for not being clearer about this.

Given the discussion at https://github.com/matplotlib/matplotlib/pull/10822 I am not sure if we want to be backporting docstring changes to 2.2.x.

**Comment by tacaswell** [comment]
Reverted in a8ac10d36482ce494c45de1c470e15aca17f3230

**Comment by timhoffm** [comment]
Since the 2.2.x release will probably be the last one for Python 2, it will be around for some time, even after 3.0 is out. I would welcome backporting docstring improvements there.

**Pull request merged**
