### PR TITLE
DOC: Organize colormap list and remove synonyms

### PR DESCRIPTION
**Pull request by endolith**
I did this in colormaps_reference.py but didn't notice there were more copies of the list in other files.

https://github.com/endolith/matplotlib/commit/4279e562db94fa852e2cef16952c994181e14b91
https://github.com/endolith/matplotlib/commit/38690652137356b62e453fa82215f1cde8792890

### CODE REVIEW

**Comment by endolith** [comment]
Oh wait, the files don't work now.  Some numbers need to be adjusted or something.  I will fix it some other time.

**Comment by endolith** [comment]
Sorry for posting this and then disappearing.  I've pushed the fix to lightness.py: https://github.com/endolith/matplotlib/commit/5296ceb77ce546f2814e8d6ff76fe8e0855d9160

I also have similar plots here comparing similar colormaps, by the way: https://secure.flickr.com/photos/56868697@N00/tags/luminance/  https://gist.github.com/endolith/2885984

**Comment by tacaswell** [comment]
@endolith Is that commit in a PR someplace?

**Comment by endolith** [comment]
it's on this branch, but it was merged already, so isn't showing up here?

**Comment by tacaswell** [comment]
You will probably have to make a new PR.

I bet gh stops tracking the source branch once it thinks it is
merged/closed which is probably a good thing so if you re-use a branch name
later old PRs don't go crazy.

**Pull request closed without merging**
