### PR TITLE
[MRG+1] Style typos fixes

### PR DESCRIPTION
**Pull request by mherkazandjian**

### CODE REVIEW

**Comment by anntzer** [comment]
(A large chunk of these functions (`dict_delall`, `reverse_dict`, etc.) seem completely unused and are probably ripe for deprecation too...)

**Comment by mherkazandjian** [comment]
yea, there is also some dead code!

**Comment by NelleV** [comment]
Thanks!

**Comment by QuLogic** [comment]
Backported to v2.x via 723f889e9bf2a60e6da06be49cc815504ac4ff4f.

**Pull request merged**
