### PR TITLE
Fix displayed 3d coordinates showing gibberish

### PR DESCRIPTION
**Pull request by scottshambaugh**
## PR Summary

Closes https://github.com/matplotlib/matplotlib/issues/22775 and closes https://github.com/matplotlib/matplotlib/issues/4334. Also gets rid of the annoying helper function at cause in https://github.com/matplotlib/matplotlib/pull/23430. Some previous discussion in https://github.com/matplotlib/matplotlib/issues/22624.

As the first issue shows, the displayed coordinates under the mouse cursor are currently meaningless. The calculation in this PR shows the x, y, z point on the displayed plane at the mouse location. For example, ignoring the broken Z coordinate for now, the mouse here is at the circled location and the coordinates displayed are on the x-z plane (the y coordinate is fixed at any point on this plane).
image

TODO: 
* Coordinates for x and y are working, z is not. Need to figure out why, likely not passing in the right z view coordinates. [This page](https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/projection-matrices-what-you-need-to-know-first) might help
* https://github.com/matplotlib/matplotlib/pull/23449/files replaces `self.vvec` with `self._view_w`, need to switch that over depending on which is merged first. The signs are flipped between those two variables but we multiply twice so it cancels out and can be directly replaced.
* Tests

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [x] New features are documented, with examples if plot related.
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
I don't understand how such a number can ever have meaning unless you arbitrarily assign a surface to project onto.  That seems of super limited value to me and I think we should just not show a cursor coordinates in 3D.

**Comment by scottshambaugh** [comment]
The surfaces we are projecting onto here are not so arbitrary - they’re the three axis panes which are visible in every 3D plot that is created. My use case which these are extremely useful for is looking at 3D data from each of the xy, yz, xz directions, and the coordinates as proposed here would be accurate in each of those “2D” views.

**Comment by scottshambaugh** [comment]
I *think* it should be pretty discoverable by waving the mouse around? With one coordinate always being fixed on each plane, the transitions when crossing the primary axes are pretty noticeable. Lemme fix the Z coordinate issue and y'all can play around with it and see if it makes sense. Open to suggestions on documentation that would make this explicit.

**Comment by scottshambaugh** [comment]
This is going to take some more effort than I thought, will require writing up proper inverse projections and I've got to do some learning on that. Leaving open for now, will try to get back to it when I have time.

**Comment by timhoffm** [comment]
Before further work goes into this, I would like to state that I'm also not convinced of this. The planes themselves are not very much of interest for the user. Data locations would be. While one can rotate and pan so that coordinates of a desired data point can be inferred from the displayed pane coordinates, this is an ugly hack at best:

1. Usually I don't want to change my view to infer a data coordinate. Yes I can to that and then undo.
2. As @jklymak stated, the behavior is not obvious, and likely surprising to users.

In my opinion, providing 3D coordinates for a 2D cursor position without additional context* is fundamentally flawed, and we should not do this (In the face of ambiguity, refuse the temptation to guess).

*The only reasonable way for returning 3D coordinates is some additional visual feedback and guidance. Something like a 3D snapping crosshair (i.e. the 3D version of https://matplotlib.org/stable/gallery/event_handling/cursor_demo.html#snapping-to-data-points) would work. Unfortunately, I'm afraid, Matplotlib is not well designed for this as you would have to redraw the image when moving the crosshair, which is quite costly and thus would not be very responsive.

**Comment by scottshambaugh** [comment]
I'd support removing the coordinates entirely right now since they're worse than useless at the moment, but I still see a lot of utility in having us show the backing plane coordinates. Let me see if I can get it working and then I can demo it which I think will show that it's not so unintuitive.

**Comment by timhoffm** [comment]
> Let me see if I can get it working and then I can demo it which I think will show that it's not so unintuitive.

Fair. To set expectations right: As I see currently see it, this should not be a default behavior in Matplotlib. It might be an example, or a third-party package.

**Comment by scottshambaugh** [comment]
This is working now for all projection types and is ready for review / discussion. 

I think the below video demonstrates the behavior well, as well as the utility of this. When looking at data with an ortho view along one of the primary view planes, the behavior is exactly the same as 2D plots. Otherwise the main utility I see is if a user projects an image onto one of the backing panes and wants to read off coordinates from that. It's also a nice quick way to grab the axis limits visually.

It would be nice to have lines along the backing planes to show the cursor location, somewhat analogous to what [plotly ](https://plotly.com/python/3d-scatter-plots/) does, but as @timhoffm points out above the redraw would be prohibitively costly. But I don't think you need this for the behavior to be discoverable - IMO the "fixed" coordinate as you move around on one of the backing panes makes what is happening obvious fairly quickly.

https://user-images.githubusercontent.com/14363975/219981857-e53c51ff-ff9d-4e77-835d-165339308110.mp4

The alternative is removing these hover coordinates altogether. If that end up as the consensus then I'll open another MR with that change (I think there's some good refactoring that can carry over from here). Will bring up in the dev call this week.

**Comment by scottshambaugh** [comment]
I update the video above to better show some use cases.

**Comment by scottshambaugh** [comment]
In the dev call today the consensus was that this is useful, but we should explicitly tell the user in the UI that these are coordinates from the axis panes to avoid confusion. I changed it to the below as a maximally compact way of conveying this information, but am open to revising this if it seems unclear.

```python
if pane_idx == 0:
    coords = f'x pane={xs}, y={ys}, z={zs}'
elif pane_idx == 1:
    coords = f'x={xs}, y pane={ys}, z={zs}'
elif pane_idx == 2:
    coords = f'x={xs}, y={ys}, z pane={zs}'
```

**Comment by scottshambaugh** [comment]
This is good to go btw.

**Review by oscargus — APPROVED** [review]
Looks good! 

I agree lines on the pane would be nice, but then they should also be optional.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
I'm squashing your commits...

Thanks for your patience!

**Pull request merged**
