### PR TITLE
FIX: callback for subfigure uses parent

### LINKED ISSUE #22804: [Bug]: Quiver not working with subfigure?
### Bug summary

There seems to be an issue when trying to plot quivers in the axes created within subfigures.

### Code for reproduction

```python
import matplotlib.pyplot as plt
fig = plt.figure()
subfigs = fig.subfigures(1, 2)
axsLeft = subfigs[0].subplots(1, 2)
axsLeft[0].quiver(1,1,1,1)
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5117, in quiver
    q = mquiver.Quiver(self, *args, **kw)
  File "/home/hyzhou/.local/lib/python3.8/site-packages/matplotlib/quiver.py", line 510, in __init__
    self._cid = ax.figure.callbacks.connect('dpi_changed', on_dpi_change)
AttributeError: 'SubFigure' object has no attribute 'callbacks'

### Expected outcome

Expect the same outcome as

```python
fig, ax = plt.subplots(1, 2,)
ax[0].quiver(1,1,1,1)
```

### Additional information

_No response_

### Operating system

Ubuntu

### Matplotlib Version

3.4.3

### Matplotlib Backend

_No response_

### Python version

3.8.5

### Jupyter version

_No response_

### Installation

_No response_

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #22804 

Not clear that SubFigures shouldn't get their own callback - @anntzer  and @greglucas  better understand how these work or what the right scope should be.  

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by anntzer** [comment]
Does this really help #22804 (other than hiding the AttributeError)?  I don't think dpi_changed will be correctly called on the subfigure, right?

**Comment by jklymak** [comment]
I'm not sure.  I thought this just updated the artist if the dpi changes.  That can be handled at the parent level I think.  However I didn't too carefully trace this through and the original issue wasn't clear on how big the arrow should be etc.   Testing on the fly dpi changes is not easy I think.

**Comment by jklymak** [comment]
I think this is still OK for #22804, though I prefer you removing the callback for quiver #22807.   The only callback we allow is `dpi_changed` (and it was only used in quiver) so I think its correct to just fallback to the parent figure callback if someone else has used this callback for something.

**Comment by anntzer** [comment]
Ah, sorry I misread. Yes this looks good (even if we may want to deprecate this later).

**Review by anntzer — APPROVED** [review]

**Review by greglucas — APPROVED** [review]

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.5.x

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.5.x

**Comment by QuLogic** [comment]
meeseeksdev backport to v3.5.x

**Pull request merged**
