### PR TITLE
Update some wx examples

### PR DESCRIPTION
**Pull request by DietmarSchwertberger**
## PR Summary
`embedding_in_wx4.py`: remove unnecessary `EVT_PAINT` handler

`fourier_demo_wx.py`:
 - remove unnecessary `EVT_PAINT` and `EVT_SIZE` handlers
 - make things clearer: use a more standard wx structure (`wx.Frame` -> `wx.Panel` -> `wx.BoxSizer`-> `FigureCanvasWxAgg`)  for easier understanding and correct background colours

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by DietmarSchwertberger** [comment]
Just noticed this at the start of the fourier example when using it for testing the Cairo PR code:
```
matplotlib.interactive(False)
matplotlib.use('WXAgg')
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg
```
I would think that the first two lines can be removed, right?

**Comment by tacaswell** [comment]
If `pyplot` is not imported, those should be effectively no-ops.

**Comment by DietmarSchwertberger** [comment]
I will remove them also from the other examples.

**Comment by tacaswell** [comment]
Thanks @DietmarSchwertberger !

**Pull request merged**
