### PR TITLE
Improve tkagg icon resolution

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/matplotlib/matplotlib/issues/13891. This works locally for me, but someone else might know better, including:

- What a `.ppm` file is, and why it was previously used over a `.png` file
- Where docs for `PhotoImage` can be found, to check how far back `.png` support goes
- What our minimum `tk` requirement is (I couldn't find it in our docs)

### CODE REVIEW

**Comment by dstansby** [comment]
The travis failure is real; for some reason the `OSX` test doesn't like the image file, which is odd because it's working fine for me locally on macos.

**Comment by timhoffm** [comment]
Maybe try making a new one using https://matplotlib.org/devdocs/gallery/misc/logos2.html and see if that's accepted?

**Comment by dstansby** [comment]
Tried making a new one, if it works will have a think about the best way to organise the icons in the image folder.

**Comment by dstansby** [comment]
To be safe I've just made a new `.ppm` file, and appended the resolution (128px square) to the filename which I think would be a good convention going forward.

**Pull request merged**
