### PR TITLE
Fixed AttributeError bug on animation/random_walk.py example and added description

### PR DESCRIPTION
**Pull request by daguito81**
## PR Summary
Fixed a bug in the example animation/random_walk.py related to #13778 by and added the description for the example for issue #8921

## PR Checklist

- [ ] Has Pytest style unit tests
- [ X] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Thanks for the PR, but I don't think there's anything to be changed here.

**Comment by ImportanceOfBeingErnest** [comment]
I guess if you restrict this PR to adding a description, it would still be an improvement.

**Comment by daguito81** [comment]
I was planning on tackling a couple of excercises missign descriptions as stated on #8921. Would it be better to close this PR and then do a new one with only the descriptions but add more of them?

**Comment by ImportanceOfBeingErnest** [comment]
Sure, whatever suits you better. 
While walking through examples, you can also add references as discussed in https://github.com/matplotlib/matplotlib/issues/10974.

**Comment by PredatorFeesh** [comment]
I'm having the same issue, I'm wondering why this wasn't merged in yet

**Comment by daguito81** [comment]
@PredatorFeesh the problem was that I was using the stable version of matplotlib which is the version you get from doing your pip install. But this example is done on the dev branch (master) which is further ahead with some functionality that changed how the examples behave. 

You need to either checkout the branch of the version you are using locally and get the examples from there, or download and build the dev branch and then run the examples with that branch.

If you use the matplotlib 3.0+ examples with matplotlib 2.4 for example, then this example won't run

**Comment by story645** [comment]
@PredatorFeesh you can check your version of Matplotlib using 
```Python
import matplotlib
matplotlib.__version__
```
in the environment in which you're running the example. Sorry, completely forgot about that check (sometimes the installs of the dev version don't stick).

**Comment by PredatorFeesh** [comment]
I'm running version 3.0.3, which is what pip installs.

**Comment by story645** [comment]
Sorry, missed that - you need to install off your branch. Instructions at https://matplotlib.org/devel/gitwash/set_up_fork.html

**Pull request closed without merging**
