### PR TITLE
Path fast verts bug fix

### PR DESCRIPTION
**Pull request by tacaswell**
Re-introduces changes from #3681 and fixes bug.

~~merge this after #4007~~

~~Expect this to be currently failing tests~~

semi_log_with_zero

### CODE REVIEW

**Comment by tacaswell** [comment]
If this passes, I will do some history re-writing to get rid of both the reversion and re-introduction of @jbmohler 's commit.

**Comment by tacaswell** [comment]
attn @pelson I changed some docs in `Path` that you were the last person to touch.

**Comment by pelson** [comment]
Seems reasonable. :+1:

**Comment by mdboom** [comment]
Sorry I missed this the first time around.  In seeing #4049, I had a slightly different solution: to do the check for masked arrays in `_fast_from_vertices_and_codes` itself.  Doing this revealed another code path where masked arrays were not getting properly converted to NaNs that caused a test to fail because cf43d57f8765e7499730 didn't get merged onto master properly...  But that does suggest to me it's safer to fix this at a lower level.  I also think we should fix the log scaling to just set invalid to NaNs rather than create a masked array (along will all of the overhead involved).  I think that code dates from before NaNs were handled correctly in all of the backends and all the cool kids were using masked arrays.  I should have a PR shortly.

**Comment by tacaswell** [comment]
The reason I didn't do the mask checking in the `_fast_from_verticies_and_codes` was to try and keep it fast ;)

**Comment by mdboom** [comment]
> The reason I didn't do the mask checking in the _fast_from_verticies_and_codes was to try and keep it fast ;)

Yeah -- I get that.  But there's only 3 call sites of that function anyway, and this PR fixed two of them, and the third one it turns out also needs updating.  So it's a net wash -- might as well just do it in the function in one place.

**Comment by mdboom** [comment]
Maybe we should rename the method to "sorta_fast"?

**Comment by tacaswell** [comment]
@mdboom Can you also cherry-pick 8d5fb93b52c5449dd63c483e2907b1fdb10ee484 ?

**Comment by mdboom** [comment]
Sure thing.

**Pull request closed without merging**
