### PR TITLE
Fix: bottom and left text appearance in colorbar

### LINKED ISSUE #23595: [Bug]: `CbarAxesBase.toggle_label` doesn't seem to work properly
### Bug summary

It appears as if `CbarAxesBase.toggle_label` and therefore, maybe, `SimpleAxisArtist.toggle` and possibly something else does not work as expected.

Probably related to the colorbar rewrite?

### Code for reproduction

https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_grid.html

### Actual outcome

The two middle figures have visible tick labels for the color bar.

### Expected outcome

No visible tick labels.

### Additional information

There seems to be some sort of mismatch between the `_axisnum` property and the location of the labels. It seems to work if the labels are located at the same side as the colorbar, i.e., right and bottom.

### Operating system

Arch

### Matplotlib Version

3.5.2 and `main`

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

git checkout

### PR DESCRIPTION
**Pull request by xtanion**
## PR Summary
This PR fixes `CbarAxes.toggle_label` inconsistency as mentioned in issue https://github.com/matplotlib/matplotlib/issues/23595
closes #23595 
## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by oscargus** [comment]
It is a bit hard to say what it actually should do as there is no doc-string, but I am not sure this is the right fix.

1. Passing `toggle_label(True)` should switch them back on.
2. This only covers half of the possible cases.

(It is a bit strange that `orientation` is actually what one would think is `location`.)

I think a better solution is to make a dict that picks the "opposite" axis name and then uses that. (If that is now the solution.)

**Comment by oscargus** [comment]
Looking at https://matplotlib.org/3.3.4/gallery/axes_grid1/demo_axes_grid.html#sphx-glr-gallery-axes-grid1-demo-axes-grid-py (which probably shows the "correct" behaviour), it seems that maybe the solution is to put the ticks and the labels on the top when "orientation" is "top" etc. In this way `toggle_label` will work as expected.

**Comment by xtanion** [comment]
Hi @oscargus, I updated the code as you suggested, and It looks like the correct result now : 
image

**Comment by timhoffm** [comment]
> edit: Should the colorbar show ticks when `set_labels` is set to `False`. It is visible in [this](https://matplotlib.org/3.3.4/gallery/axes_grid1/demo_axes_grid.html#sphx-glr-gallery-axes-grid1-demo-axes-grid-py) example, But this PR currently removes the ticks as well is `set_labels` is False.

If there are no tick labels, ticks don't have a meaning. So, whether or not to remove them is a purely aesthetic decision. IMHO it's fine to remove them.

**Comment by xtanion** [comment]
> If there are no tick labels, ticks don't have a meaning. So, whether or not to remove them is a purely aesthetic decision. IMHO it's fine to remove them.

Thanks for confirming @timhoffm, Is there any additional changes needed?

**Comment by rcomer** [comment]
Hi @xtanion, thank you for your work on this and sorry it has taken a while to get back to you.

It’s great that you have confirmed locally that the method now has the correct behaviour.  Could you simplify the code you checked with and make it an [image comparison test](https://matplotlib.org/devdocs/devel/testing.html#writing-an-image-comparison-test)?  Simplify because it just needs enough to prove the desired behaviour is happening with the ticks (so e.g. no need for the annotations).

The documentation build check has failed due to a problem that I think has been fixed on `main`.  So could you also rebase your branch to pick up that fix?  That would allow us to see how your change affects the original example from the issue.

**Comment by anntzer** [comment]
Will that work if the colorbars are on the bottom or the left side? I'm not so sure...

**Comment by anntzer** [comment]
Superseded by https://github.com/matplotlib/matplotlib/pull/25884.  Thanks for the PR!

**Pull request closed without merging**
