### PR TITLE
Restore cbook.report_memory, which was deleted in d063dee.

### PR DESCRIPTION
**Pull request by efiring**
There was no deprecation process, and having something like this
available as an import is very valuable to users suspecting a
memory leak, or simply needing to track memory usage.

### CODE REVIEW

**Comment by efiring** [comment]
As an example of why we need this, or a good replacement, see #6940.

**Comment by tacaswell** [comment]
It looks like the loop from https://github.com/matplotlib/matplotlib/pull/5360/files#diff-84d254616071e10903ac389d05d109deR36 should be exposed as a cbook function as well?

**Comment by tacaswell** [comment]
re-milestoned as 2.1 because this has only been removed on master (https://github.com/matplotlib/matplotlib/blob/v2.x/lib/matplotlib/cbook.py#L1439)

**Comment by efiring** [comment]
@tacaswell, yes, it would be nice to have the whole `run_memleak_test()` function available as an import, but it relies on a python 3.4+ import, and psutil.  We could put it in cbook within a try-except block beginning with the tracemalloc and psutil imports.

**Comment by tacaswell** [comment]
Merging this as-is as the alternative is much more work than I anticipated due to py3 only imports.

**Pull request merged**
