### PR TITLE
Remove logic for optionally building Agg and TkAgg.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

They are actually not optional (that's the `force = True` setting which
overrides the OptionalBackendPackage logic), so just make them
SetupPackages and remove the corresponding (outdated) comments in
setup.cfg.template.

Builds on top of https://github.com/matplotlib/matplotlib/pull/13074 as the prose in setup.cfg.template is only true if we also remove windowing from there. [edit: that PR has been merged]

(The OptionalBackendPackage logic was also previously useful back when the default backend was selected at build time, but that's no longer the case.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Would it be better to actually make tkagg optional?

**Comment by anntzer** [comment]
It's been non-optional for years and no one complained; what would be the use case? Note that the build doesn't depend on any external headers or libraries.

**Comment by anntzer** [comment]
(In fact I'm tempted to *also* make the OSX backend non-optional if someone can verify whether the cocoa headers are always installed with xcode...)

**Comment by tacaswell** [comment]
punting to 3.2 as it has conflicts, in non-critical, and the fiddly to make sure we got it right.

**Comment by anntzer** [comment]
Rebased.  Once again, note that always forcing the build of tkagg (which does *not* depend on the tk headers) has been the actual behavior for years now.

**Comment by QuLogic** [comment]
It seems that moving Travis means I can't restart the broken build, so you'll have to rebase.

**Comment by anntzer** [comment]
rebased

**Comment by WeatherGod** [comment]
I remember something about someone having problems building matplotlib
against a python that didn't have Tk. Could that be the reason why the code
is this way for TkAgg?

**Comment by anntzer** [comment]
The tkagg build doesn't interact with tk at build time whatsoever since #6442.  Quoting from that PR:
> It is one way of building a manylinux wheel that can build on a basic Manylinux docker image (i.e. without tk -- this comment is mine), and then run with the TCL / Tk library installed on the installing user's machine.

**Pull request merged**
