### PR TITLE
Rely on generalized * and ** unpackings where possible.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I don't mind much for the matrix multiplication PR, but for this case I do believe `{**foo, "a": b}` is **way** more readable than `tmp = foo.copy(); tmp["a"] = b`.  For the list case it's not as big a difference but I still prefer `[*a, *b]` to `list(a) + list(b)`.

**Comment by anntzer** [comment]
bump.

**Comment by dopplershift** [comment]
On a microbenchmark, the `[*a, *b]` is twice as fast (at least for combining dictionary keys). It's not as familiar since we haven't been able to use such syntax widely, and that might be currently hindering readability a little. My programmer sensibilities like it a lot better than `list(a) + list(b)` because I know the latter is creating 3 lists, vs. whatever the first looks like at an implementation level.

**Comment by anntzer** [comment]
Basically, the whole unpacking is implemented as a single opcode which optimizes for list creation:
```
In [1]: dis.dis(lambda a, b: [*a, 1, *b])
  1           0 LOAD_FAST                0 (a)
              2 LOAD_CONST               2 ((1,))
              4 LOAD_FAST                1 (b)
              6 BUILD_LIST_UNPACK        3
              8 RETURN_VALUE

In [2]: dis.dis(lambda a, b: list(a) + [1] + list(b))
  1           0 LOAD_GLOBAL              0 (list)
              2 LOAD_FAST                0 (a)
              4 CALL_FUNCTION            1
              6 LOAD_CONST               1 (1)
              8 BUILD_LIST               1
             10 BINARY_ADD
             12 LOAD_GLOBAL              0 (list)
             14 LOAD_FAST                1 (b)
             16 CALL_FUNCTION            1
             18 BINARY_ADD
             20 RETURN_VALUE

In [3]: dis.dis(lambda a, b: a + [1] + b)
  1           0 LOAD_FAST                0 (a)
              2 LOAD_CONST               1 (1)
              4 BUILD_LIST               1
              6 BINARY_ADD
              8 LOAD_FAST                1 (b)
             10 BINARY_ADD
             12 RETURN_VALUE
```
(and similarly for dicts) so it's not surprising that it's faster.  Even in the case where we "know" that a and b are lists (case 3) and thus don't need the function calls, going through `build_list_unpack` can probably(?) use some more specialized stuff than going through `binary_add`.

**Pull request merged**
