### PR TITLE
Fixes #7742 - axhline rescale issue

### LINKED ISSUE #7742: plot_date() after axhline() doesn't rescale axes
If I plot an `axhline` first, and then two points with `plot_date`, the x-axis is not rescaled to the two new data points:

```python
import matplotlib.pyplot as plt
from datetime import datetime

fig, axs = plt.subplots(2, 1)

axs[0].axhline(1.5)
axs[0].plot([datetime(2016, 1, 1, 0, 0, 0), datetime(2016, 1, 2, 0, 0, 0)], [1, 2])

axs[1].plot([datetime(2016, 1, 1, 0, 0, 0), datetime(2016, 1, 2, 0, 0, 0)], [1, 2])
axs[1].axhline(1.5)

plt.show()
```
figure_1-1

I would expect the two plots to be the same, and the plotting order not to matter.

Present on current master (2.0.0rc2.post2912+g015d8d5) and on 1.5

### PR DESCRIPTION
**Pull request by sughandj**
Fixes #7742
Modified axhline() function to save state of ignoring limits and restore after plotting the line

### CODE REVIEW

**Comment by phobson** [comment]
This appears to be a duplicate of https://github.com/matplotlib/matplotlib/pull/8205

**Comment by sughandj** [comment]
@phobson check my comment in #7742
Was I not supposed to create a new PR for it? I am new to this.

**Comment by phobson** [comment]
I think the other PR fully addresses the issue. If it doesn't, I would prefer that more work be added to do so.

**Comment by sughandj** [comment]
Ahh I see, I think the test I have written in my commit won't work with the other PR's fix
(Also suggested by @Shang-Jia in the issue)

I guess we help the other PR in that case?

**Comment by efiring** [comment]
There have been a lot of changes since this, so even if the bug is still present (which is unclear--see #17925), I don't think the approach used here will be the right one.

**Pull request closed without merging**
