### PR TITLE
Ensure valid path mangling for ContourLabeler

### LINKED ISSUE #26971: [Bug]: plt.clabel raises exception at very low DPI: `ValueError: 'codes' must be a 1D list or array with the same length of 'vertices'. Your vertices have shape (2, 2) but your codes have shape (1,)`
### Bug summary

This worked up to and including Matplotlib 3.7.3 and broke in Matplotlib 3.8.0.

Data files for sample code below:
[x.txt](https://github.com/matplotlib/matplotlib/files/12782405/x.txt)
[y.txt](https://github.com/matplotlib/matplotlib/files/12782406/y.txt)
[z.txt](https://github.com/matplotlib/matplotlib/files/12782407/z.txt)

### Code for reproduction

```python
import matplotlib
matplotlib.rcParams['figure.dpi'] = matplotlib.rcParams['savefig.dpi'] = 4

from matplotlib import pyplot as plt
import numpy as np

# See data files attached above: x.txt, y.txt, z.txt
x = np.loadtxt('x.txt')
y = np.loadtxt('y.txt')
z = np.loadtxt('z.txt')

ax = plt.axes()
contourset = ax.contour(x, y, z, levels=[90.0], linewidths=0.5)
ax.clabel(contourset)
plt.savefig('test.pdf')
```

### Actual outcome

```
Traceback (most recent call last):
  File "/private/tmp/test.py", line 13, in <module>
    ax.clabel(contourset)
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/matplotlib/axes/_axes.py", line 6550, in clabel
    return CS.clabel(levels, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/matplotlib/contour.py", line 222, in clabel
    self.labels(inline, inline_spacing)
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/matplotlib/contour.py", line 622, in labels
    rotation, path = self._split_path_and_get_label_rotation(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/matplotlib/contour.py", line 436, in _split_path_and_get_label_rotation
    return angle, Path(xys, codes)
                  ^^^^^^^^^^^^^^^^
  File "/Users/lpsinger/Library/Python/3.11/lib/python/site-packages/matplotlib/path.py", line 135, in __init__
    raise ValueError("'codes' must be a 1D list or array with the "
ValueError: 'codes' must be a 1D list or array with the same length of 'vertices'. Your vertices have shape (2, 2) but your codes have shape (1,)
```

### Expected outcome

[test.pdf](https://github.com/matplotlib/matplotlib/files/12782396/test.pdf)

### Additional information

I discovered this regression in the CI pipeline from one of my own projects, in a test that sets DPI to an extremely low value for performance purposes. https://git.ligo.org/lscsoft/ligo.skymap/-/jobs/2961694

### Operating system

macOS

### Matplotlib Version

3.8.0

### Matplotlib Backend

MacOSX

### Python version

3.11.5

### Jupyter version

N/A

### Installation

pip

### LINKED ISSUE #27062: [Bug]: ContourLabeler.clabel with manual != False breaks unconnected contours
### Bug summary

When adding contour label positions manually (either via clicking or specifying an iterable of positions), contours with disconnected parts are not handled correctly, but sometimes rejoined seemingly arbitrarily.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
x, y = np.mgrid[-1:1:21j, -1:1:21j]

cs = ax.contour(x, y, 1/np.sqrt(0.01+(x+0.3)**2+y**2) + 1/np.sqrt(0.01+(x-0.3)**2+y**2), levels=[7])
cs.clabel(manual=[(0.2, 0.1)])
```

### Actual outcome

image

### Expected outcome

As it looked in matplotlib 3.7.3:
image

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.8.0

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

conda

### PR DESCRIPTION
**Pull request by ksunden**
## PR summary

Closes #26971
Closes #27062

As noted in the comment and the discussion on the linked issue, this is actually technically "wrong", but is provided as a stopgap so that a more proper fix can be made.

In particular, the original sin here is, in my opinion, that the padding is specified in pixels, rather than either a scale-independent metric (e.g. points) or a value relative to the fontsize.
Using pixels especially does not make sense when saving to vector based formats. (As is actually done in the issue as reported)

Changing that behavior, however is a much larger api change, especially since this should be backported to the 3.8 series.

As it stands, the original calculation would actually indicate that the entire contour should be eliminated, but that leaves a label with _no_ contour, which I also think is undesireable.
Perhaps as a slightly larger change it could e.g. return `angle=np.nan`, `<the path as input>` to indicate that no label should be added and keep the contour.
That much is a larger behavior change than I really want to introduce here (as I intend this to be backported)

Current `main` behavior retains the two end points but then only has one code, so it produces an invalid PATH and fails.

This PR ends up drawing a single line segment between the two identified endpoints, and ignores any points that may be between them.
But this appears to be the behavior of mpl 3.7 anyway, and is a relatively rare edgecase, brought on by either really large padding or really low DPI (with the test case in the issue it was 4 dpi, and even 5 dpi avoided problems).

So personally, I'm okay with just minimally avoiding invalid paths being generated and not worrying about too much more than that for the initial fix.

I could add a test case, but I think that may be better as part of moving towards a non-dpi dependent padding.

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [x] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by oscargus** [comment]
> I could add a test case, but I think that may be better as part of moving towards a non-dpi dependent padding.

I'd say go with a smoke test at least. Who knows when the "correct" solution shows up...

**Comment by ksunden** [comment]
Test added, I chose a slightly different presentation where instead of changing the dpi, I changed the inline_spacing argument, because that felt like a more direct way of triggering the behavior (I did check that the test failed on `main`, first, still with the same error).

Also adjusted to use calculated x/y/z values instead of reading from text files.

Here is the image the test code would produce (though it is not an image test, just a smoke test):

test

The main difference between proposals from #26971 is what would happen to the yellow 0.8 contour. My first proposal would have drawn the curve there, @anntzer's proposal would have not drawn a line at all (but kept the label), and this PR/the last proposal retains mpl 3.7 behavior where a single line segment is drawn.

**Comment by ksunden** [comment]
I have added a commit which fixes #27062, which is editing the same method, though is a different bug presentation

**Comment by ksunden** [comment]
Nudge for review

**Review by QuLogic — APPROVED** [review]
LGTM; maybe we also want a test for the second fix?

**Comment by ksunden** [comment]
Well, in implementing the test I discovered that our test mechanism for enabling the fallback of using collections only ever triggers _after_ calling clabel and the behavior is different between the two... So sorting that out now...

**Comment by ksunden** [comment]
Okay, what was happening was that it was "invalidating" the old style split collections, but not removing them from being drawn (or turning the new style ones that it is manipulating visible again)

I guess there is some worry that if people were modifying the old-style paths that those changes are lost, but that seems to be intended by the implementation, this just completes the task.

**Comment by QuLogic** [comment]
Do we need all 3 formats for the test?

**Comment by ksunden** [comment]
Updated to remove the additional formats (I had just copied the decorator from a similar test)

I also removed the tolerance, though depending on why it was added to the previous test, it may need to be added back.

**Review by tacaswell — APPROVED** [review]

**Pull request merged**
