### PR TITLE
Backport PR #12617 on branch v3.0.x (Set up CI with Azure Pipelines)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12617: Set up CI with Azure Pipelines

### CODE REVIEW

**Comment by dstansby** [comment]
I guess this needs merging for the branch to pick it up?

**Comment by tacaswell** [comment]
Hmm, maybe I was confused and it is not turned on for any branches but master?

**Comment by QuLogic** [comment]
Seems to be working now that it's merged; cf #12731.

**Comment by tacaswell** [comment]
I changed settings on the azure side.

On my to-do list is to sort out how to get more people access to that admin.

**Pull request merged**
