### PR TITLE
DOC: colormap manipulation tutorial update

### PR DESCRIPTION
**Pull request by ImportanceOfBeingErnest**
## PR Summary

Update the colormap manipulation tutorial with two main points:

* There is an important difference between ListedColormaps and LinearSegmentedColormaps which was not at all apparent from the tutorial
* The pretty useful `LinearSegmentedColormap.from_list` method wasn't mentionned at all.

Link to [the proposed tutorial](https://679-100939689-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/tutorials/colors/colormap-manipulation.html#sphx-glr-tutorials-colors-colormap-manipulation-py).

## PR Checklist

- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] Old features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by jklymak** [comment]
Agree w the general idea of this change because when I wrote the tutorial I didn’t understand that listed colormap behave differently.  From list looks pretty useful.   My main concern w this tutorial was to show how to paste existing colormaps together or make new ones from rgb arrays.  If from list is a better way to do that than listed colormaps maybe modify or add new examples?

**Comment by ImportanceOfBeingErnest** [comment]
I'm not sure if any more examples are needed, but of course feel free to suggest something. The main benefit of `LinearSegmentedColormap.from_list(list)` compared to `LinearSegmentedColormap(dict)` is just the reduced number of headaches for beginners creating that dictionary. But both aren't in competition with `ListedColormap`, I'd say.

**Comment by jklymak** [comment]
Thanks, this clarifies quite a few things...

**Comment by jklymak** [comment]
This is helpful, but I don't think critical to back port unless you want to do it @ImportanceOfBeingErnest ?

**Comment by ImportanceOfBeingErnest** [comment]
No, I guess we can leave it like this.

**Pull request merged**
