### PR TITLE
Fix legend color comparisions

### PR DESCRIPTION
**Pull request by dstansby**
Alternative to #10030 - Matplotlib colors can be lots of different types, so convert them to rgba arrays before comparing.

### CODE REVIEW

**Comment by jklymak** [comment]
Given that we had bug reports when this  as changed, yet the changes passed all the tests, either the tests are incomplete or this is accommodating undocumented use of colours.  Can we add a test and or document whatever this is supposed to fix?

**Comment by dstansby** [comment]
The problem is the original 'color comparison' code didn't allow for colors to be numpy arrays. Long term I think this should be avoided by a general function for comparing colors, which I've put in #10032

**Comment by jklymak** [comment]
Yeah, the problem is that this code didn't *change* in 2.1.1, it just got applied to `Figure.legend()` as well as `axes.legend()`.  So we broke things by making them more consistent.  But I'm still not understanding the use-case.

If in master I do

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.plot(np.arange(10), color=np.array([0.1, 0.3, 0.4]), label='boo')
fig.legend()
plt.show()
```

That works fine.  So 1-D numpy arrays work OK in master.  

The error comes when the user specifies a 2-D array

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.plot(np.arange(10), color=np.array([[0.1, 0.3, 0.4]]), label='boo')
fig.legend()
plt.show()
```

```
ValueError: Invalid RGBA argument: array([[ 0.1,  0.3,  0.4]])
```

I'd argue specifying a 2-D array is not correct, and if it worked before, that was just a fortunate happenstance. OTOH, `plot` lets you put a 2-D array in, so I agree legend should as well. 

Anyway, upshot is we should add a test to test for 2-D arrays being allowed.

**Comment by jklymak** [comment]
OK, I take it back; the above 2-D array test fails in 2.1.0 and 2.0.2 as well.  So I'm not clear what the failure case is here.  What color spec failed in 2.1.1 that this fixes?

**Comment by skirpichev** [comment]
@jklymak, sorry.  I can't provide better failing test yet.

**Comment by jklymak** [comment]
OK< let us know.  

I can reproduce 
```
ValueError: Invalid RGBA argument: array([[ 0.12156863,  0.46666667,  0.70588235,  1.        ]])
```
but I get that all the way back to 2.0.2, so I don't think this every worked?  

If you could just print c before its passed to legend, that would help clarify things.  

@dstansby's fix above seems to work for you, but the minimal test I put in above *doesn't* work on @dstansby's change.  So I am mystified.  Most importantly we should make sure we have a test that covers your case and the case that is breaking for https://github.com/sympy/sympy/issues/13730

**Comment by skirpichev** [comment]
> Most importantly we should make sure we have a test that covers your case and the case that is breaking for sympy/sympy#13730

Probably, these testcases should be same, as Diofant and Sympy share some codebase.

**Comment by jklymak** [comment]
See here for a link to their efforts: https://github.com/sympy/sympy/issues/13730#issuecomment-352544164

**Comment by jklymak** [comment]
I'll put in a TST PR for this.

**Pull request merged**
