### PR TITLE
Added .editorconfig

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by jklymak** [comment]
I'm not sure if its a good idea to make this the actual `.editorconfig` or a template for the user to explicitly set.  I don't think that we should tell the user's editor what to do by default.  https://editorconfig.org

**Comment by KOLANICH** [comment]
> I don't think that we should tell the user's editor what to do by default. 

But if someone created a PR with tabs, would you require him to replace them with spaces before the PR is merged?

**Comment by jklymak** [comment]
Yes, and then they could tell their editor to do the right thing.  But I don't think we should do this by default, unless its a really common open-source thing to do that folks would be expecting.  As I said `.editorconfig.template` would be fine w/ me, and then a user could copy to `.editorconfig`.

**Comment by KOLANICH** [comment]
> As I said .editorconfig.template would be fine w/ me, and then a user could copy to .editorconfig.

It is not meant to be used this way. It is meant to be automatic. I just clone the repo, open the file and edit it. The settings are applied only to the files in the folder where the fike lies and to the subfolders of it.

**Comment by jklymak** [comment]
I understand how it works, I just don't think it's something we should do without active participation of the user unless its so common everyone knows to look for the `.editorconfig` file if their editor isn't doing what they expect when editing the `matplotlib/` tree.

**Comment by KOLANICH** [comment]
>its so common

it's used in some python projects (and in some non-pythkn too), but unfortunately currently there are less python projects using it than the ones not using it.

>unless its so common everyone knows to look for the .editorconfig file if their editor

Good point. Some apps require a plugin to be explicitly installed. Some apps need a setting to be activated. I cannot say for all apps, I have used only Notepad++ (instslled plugin manually), old Visual Studio (installed plugin manually), QTCreator (enabled preinstalled plugin manually, if I remember right), TortoiseGitMerge (enabled the feature manually) with it. GitHub, as far as I know, has no switch whether to use it or not.

**Comment by KOLANICH** [comment]
I use tabs instead of spaces for indentation.

**Comment by anntzer** [comment]
Do you contribute to any other open-source Python projects?  Do you plan to PR such an editorconfig to each and every one of them?  (I know no project that uses tabs.)
I am not necessarily opposed to adding such a config file, but am a bit puzzled by the general strategy here...

**Comment by KOLANICH** [comment]
>Do you contribute to any other open-source Python projects? 

When I contribute to them, if a project has no that file, I usually create a PR to add one. These PRs are often accepted. 

In my own projects I use an own file with `indent_style = tab`. The hard requirement of using spaces was set because different editors render a tab with different count of character widths, which can disrupt alignment. `.editorconfig` solves this problem, it prescribes editors to use the configured amount. So no need to use bloaty, semantically incorrect and troublesome (backspace works incorrectly on them) spaces instead of tabs for indentation.

**Comment by tacaswell** [comment]
I am :-1:  on this.  I do not think this is a wide-spread convention yet and do not want Matplotlib to be on the leading edge of `.*` configuration file fads. 

None of those arguments in favor of tabs are compelling.

Using spaces for indentation is the mainstream behavior (it is what cpython does).  If people want to diverge from standard practices in some projects, the burden should be on those projects to deal with that rather on projects using main-stream conventions to assert they are using main stream conventions.

Did you open PRs against the rest of the scipy stack with this file as well?

**Comment by KOLANICH** [comment]
>Using spaces for indentation is the mainstream behavior

not an argument for me.

>Did you open PRs against the rest of the scipy stack with this file as well?

GitHub shows who is the author of PRs. And I have expected (don't know why though, my former experience shows that this kind of PRs are usually accepted) that there may be some problems with accepting this kind of PRs.

**Comment by jklymak** [comment]
@KOLANICH thanks for the PR ands interest in matplotlib, but closing for the reasons above.  OTOH, no matter what editor you use, we always welcome PRs that improve matplotlib (so long as your tabs end up spaces before we see the diff :wink:)

**Comment by KOLANICH** [comment]
>Did I understand correctly, that the editorconfig file specifies that tabs should be replaced by spaces (which is what most of us use anyway, in our text editor configuration)?

Not quite.

It specifies which characters are used by editor for indentation (a tab and how many characters it consumes or which count of spaces to use instead of a tab) and some other things (you can read the website and try yourself if you are really interested). If you hit `tab` with `indent_style = space`, the editor would insert spaces, but if you set `indent_style = tab` it would insert a tab. If you also set `indent_size = 3` a tab would take the same space as 3 spaces.

**Comment by matthew-brett** [comment]
Right - but I meant *this* `.editorconfig` file - which has:

```
indent_style = space
indent_size = 4
```

From what you said above, this is what I was expecting, the tab key leading to four spaces.

**Pull request closed without merging**
