### PR TITLE
Properly hide __has_include to support C++<17 compilers.

### LINKED ISSUE #14370: gcc error when building matplotlib dev from source
### Bug report

**Bug summary**

Failed to build dev version of `matplotlib` from source. Example log: https://travis-ci.org/astropy/astropy/jobs/538721543

```
set build/lib.linux-x86_64-3.7/matplotlib/_version.py to '3.1.0+955.ge2b581abb'
    running build_ext
    building 'matplotlib.ft2font' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/src
    gcc -DNDEBUG -g -fwrapv -O3 -Wall -std=c99 -fPIC -DFREETYPE_BUILD_TYPE=system -DPY_ARRAY_UNIQUE_SYMBOL=MPL_matplotlib_ft2font_ARRAY_API -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -D__STDC_FORMAT_MACROS=1 -Iextern/agg24-svn/include -I/home/travis/miniconda/envs/test/lib/python3.7/site-packages/numpy/core/include -I/home/travis/miniconda/envs/test/include/python3.7m -c src/checkdep_freetype2.c -o build/temp.linux-x86_64-3.7/src/checkdep_freetype2.o -I/usr/include/freetype2
    src/checkdep_freetype2.c:1:45: error: missing binary operator before token "("
     #if defined __has_include && ! __has_include(<ft2build.h>)
                                                 ^
    src/checkdep_freetype2.c:15:11: note: #pragma message: Compiling with FreeType version 2.5.2.
       #pragma message("Compiling with FreeType version " \
               ^
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/travis/miniconda/envs/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-cbwrywg3/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hmjgqamm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-cbwrywg3/matplotlib/
```

We did not see this error when CI ran 20 hours ago; https://travis-ci.org/astropy/astropy/jobs/538455547 failed with something else that was unrelated to `matplotlib`. But definitely was happening 4 hours ago (https://travis-ci.org/astropy/astropy/jobs/538718110).

**Code for reproduction**

Here is how our CI pick up dev version of `matplotlib`:

https://github.com/astropy/ci-helpers/blob/d9cd38228f30cf939bb47ef5e07175421f87ac33/travis/setup_dependencies_common.sh#L605-L617

**Actual outcome**

See logs posted in summary above.

**Expected outcome**

Successful build of `matplotlib` dev.

**Matplotlib version**

  * Operating system: Ubuntu 4.8.4-2ubuntu1~14.04.3
  * Matplotlib version: 3.1.0+955.ge2b581abb
  * Matplotlib backend (`print(matplotlib.get_backend())`): Agg (https://github.com/astropy/astropy/blob/62f1ac1726e57facf922eab9fa3ee36b03aa8a2d/astropy/conftest.py#L37)
  * Python version: 3.6 and 3.7
  * Jupyter version (if applicable): N/A
  * Other libraries: https://github.com/astropy/astropy/blob/62f1ac1726e57facf922eab9fa3ee36b03aa8a2d/.travis.yml#L38

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

likely fixes #14370, attn @pllim @astrofrog 

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Why is this just showing up now though?

**Comment by pllim** [comment]
Let me run Astropy CI against this branch and report back. Thank you! 🙏 🤞

**Comment by pllim** [comment]
Update: I can confirm that this patch fixed the failure seen on Astropy CI; e.g., https://travis-ci.org/astropy/astropy/builds/539034990 (the failure now is something unrelated to `matplotlib`)

Thank you for the quick fix!

**Comment by pllim** [comment]
> Why is this just showing up now though?

Could it be that the `gcc` that Astropy CI uses is just old enough for this to show up? 🤷‍♀

**Comment by jklymak** [comment]
> Why is this just showing up now though?

Because #13067 was just merged?    Though it *is* confusing because GitHub claims those files are 5 months old.  Its annoying that it lists when the PR was authored, not when the PR was merged.

**Comment by tacaswell** [comment]
Ah, that makes sense :sheep: .

**Comment by jklymak** [comment]
Not quite sure why codecov is mad about the tests.  Don't think its this PR as I've seen it on a few other PRs, so I'm merging

**Pull request merged**
