### PR TITLE
DOC: center footer

### LINKED ISSUE #15306: Footer off centre
Why is our footer off centre?  Noted when reviewing #15305

Untitled 2

_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/pull/15305#issuecomment-533224063_

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary
Closes #15306  The footer is right-justified, and at least to me, looks weird considering the text above has a 240pt margin.  Not sure this is the right solution.  Maybe the footer needs a margin as well, in which case right justification may be OK

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I dunno.  I think this looks better, but I still think its funny that the light blue part extends through the margin but doesn't cover the whole bottom of the site.  

https://circleci.com/gh/matplotlib/matplotlib/25224/artifacts/0//home/circleci/project/doc/build/html/index.html

Screen Shot 2019-09-19 at 12 35 31

**Comment by timhoffm** [comment]
Center is also a bit awkward. Anyway, this will be replaced in the website redesign, and I trust Dora will find a good looking solution.

**Comment by jklymak** [comment]
OK, so leave as is?  I'm fine w/ that, but when I reviewed the other PR I really thought the PR must have broken something....

**Comment by timhoffm** [comment]
+/-0 I don't really care. If you feel this is an improvement, you can have my vote.

**Comment by tacaswell** [comment]
attn @dorafc

**Comment by dorafc** [comment]
I do think the centered text is an improvement

**Pull request merged**
