### PR TITLE
Let the left axis and right axis be aligned

### PR DESCRIPTION
**Pull request by Genlovy-Hoo**
Let the left axis and right axis be aligned at the specified position in twin coordinate axis

## PR summary
Let the position `v_left` on `ax_left` and the position `v_right` on `ax_left` be aligned

**before twinxalign**:
image

**after twinxalign**:
image

## PR checklist

- [&check;] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)

### CODE REVIEW

**Comment by ksunden** [comment]
Thank you for your interest in improving matplotlib!

However, I do have some concerns here that at the very least may require some additional justification:

API design:

- I'm not sure a new top-level module is the right choice for this method
   - I don't necessarily have a location in mind where I _want_ it, would have to think longer on that, but a new public/top level module for a single function seems likely to be a point of confusion
- I find the lack of a `twiny` version of this method to be confusing (and the name of the module would indicate that only `x` will be included there)

Implementation:

- Not sure scales are the tool to use for this... it won't work, e.g. if someone wants to use log scales for one or both of the twinned axes, this seems limiting in ways that need to be made _very_ clear or implemented in a way that will work with other scales.

Documentation/maintenance:

- We use [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) format for our docstrings
- New features should include a [What's new](https://matplotlib.org/stable/devel/coding_guide.html#pull-request-guidelines) entry (though I think perhaps that should wait until it is clarified whether this feature will be included)
- There are no unit tests of the new feature to ensure that it continues to work as expected

**Comment by oscargus** [comment]
I am sure that one can do this using `secondary_axes`, but is there a *simple* way to align two arbitrary points as is done here? I cannot really figure out another way than to recompute the scales manually? Which I guess is exactly what this code does? 

So it could work as an example?

**Comment by oscargus** [comment]
@jklymak what about an example with the robust way?

**Comment by jklymak** [comment]
Is https://matplotlib.org/stable/gallery/subplots_axes_and_figures/secondary_axis.html not what is being asked for?

**Comment by oscargus** [comment]
"I am sure that one can do this using secondary_axes, but is there a simple way to align two arbitrary points as is done here? I cannot really figure out another way than to recompute the scales manually?"

**Comment by oscargus** [comment]
On second thought,  I do not really this is a secondary axes problem.

To me, it looks like aligning locations on twinned axes.

**Comment by jklymak** [comment]
Ah OK, fair enough - these are meant to be twinned axes with two different curves.  Sorry for misreading it. 

I guess an example like this would be fair enough - it's just a tiny bit of math and knowing how to get the current limits.  Of course the two axes would not be linked in any dynamic way.

**Comment by Genlovy-Hoo** [comment]
> Ah OK, fair enough - these are meant to be twinned axes with two different curves. Sorry for misreading it.
> 
> I guess an example like this would be fair enough - it's just a tiny bit of math and knowing how to get the current limits. Of course the two axes would not be linked in any dynamic way.

I'm Sorry for not clearly describing the function of `twinxalign` in the PR description.

In some data, a point on the left axis and another point on the right axis have the same meaning, so they should be aligned.

For example, we draw the netvalue curve of a portfolio on the left axis and the profit ratio curve on the right axis. A netvalue of 1.0 and a profit ratio of 0.0 represent the same meaning, that is, the state of the account at beginning, so they should be aligned in the left axis and right axis.

Thanks very much for your discussion and suggestions. And can I submit another new PR to add this case into `/galleries/examples/Subplots, axes and figures`?

**Comment by jklymak** [comment]
The problem with automating this, is that it is not really clear how you will handle the gain on the right hand axes.  In your case you want to have the zero track a value on the other axes, and achieve that by having the righthand yaxis expand so it still encompasses all your second set of data.  Thats fine, but what happens when you zoom?  What happens when you zoom, and your anchor point is no longer on the left hand plot?  

Ideally there would be a mathematical mapping between the left- and right-hand axes.  However, if there is a mapping like that, then the data that you are plotting on the right hand axes could be expresses in the units of the lefthand axes, and you could use `secondary_yaxis`.   Thats still what I would do here, and then you have an interactive plot that works properly.

**Pull request closed without merging**
