### PR TITLE
DOC: reorder examples and fix top level heading

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This re-roders the examples primarily to not have pyplot at the top, removes `../examples/API` from the list since its gone, and tries to fix the "Gallery" heading to have the correct heading level (higher than all the subsections)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This is better, but it puts a huge space after the first section for some reason...

https://12057-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/index.html

**Comment by jklymak** [comment]
Huh, still a huge space under the title of the page.  Anyone know what causes this?

https://12060-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/index.html

**Comment by jklymak** [comment]
The big space is caused by a `<div style='clear:both'></div>`, but its in versions of the docs that work, so I'm not clear what changed here that caused this.

**Comment by jklymak** [comment]
OK, this works locally now.  I think I may have been missing a carriage return after an anchor 🙄

**Comment by timhoffm** [comment]
The enormous space is still there https://12103-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/index.html

It's caused by `<div style="clear:both"></div>` which is there for some reason I don't see.

**Comment by jklymak** [comment]
Huh, its the darnedest thing.  I played around with 1000 things, but it turned out to fail if I made the title `Examples` instead of `Gallery`.  So.... Hopefully this finally works.

**Pull request merged**
