### PR TITLE
MNT: Remove dummy_threading because threading is always available

### PR DESCRIPTION
**Pull request by greglucas**
## PR Summary

With Python 3.7 and above, the threading module is always available.
https://docs.python.org/3.7/library/dummy_threading.html

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [X] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by QuLogic — APPROVED** [review]

**Comment by tacaswell** [comment]
Are we sure this will not break pyiodide?

**Comment by greglucas** [comment]
Not positive, but it looks like they've removed their dummy_threading patches?
https://github.com/pyodide/pyodide/pull/796
https://github.com/pyodide/pyodide/issues/144#issuecomment-725326733

Ping @rth for comment on whether this will break Pyodide because it looks like you did some of the threading work over in Pyodide.

**Comment by tacaswell** [comment]
I also side-banded @mdboom , we are good to go here!

Merging over the OSX failures which are due to tk installation issues.

**Comment by rth** [comment]
For Pyodide it should be OK, since indeed lately importing `threading` no longer raised an `ImportError` there, even though threads could still not be created. 

I think the only thing that could be improved is to add
```py
try:
    timer.start()
except RuntimeError:
    pass
```
in the FontManager init, as otherwise starting that thread would fail [in Pyodide](https://pyodide.org/en/stable/console.html),
```py
>>> timer = threading.Timer(1, lambda x: print('a'))
>>> timer.start()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
This would allow us to remove the following patch https://github.com/pyodide/pyodide/blob/main/packages/matplotlib/patches/fix-threading.patch

**Comment by greglucas** [comment]
Would changing the warning timer to `signal.alarm` work with pyodide here?

I don't see a major issue with adding the try/except either, the only minor issue is that someone else will come along again next time and say it isn't necessary because the CPython docs say it should be available :)

**Comment by tacaswell** [comment]
I would rather try...except than go down the signal path.   

I think of this is a secondary feature (it is warning that building the font cache is going slow which if you have oodles of fonts can take a long time and look like a process hang) so if it is degraded on pyodide that is OK and we should un-break them as simply as possible on our side.

**Pull request merged**
