### PR TITLE
[MRG+1] Convert remaining tests to pytest

### PR DESCRIPTION
**Pull request by QuLogic**
Also delete the `nose` bit at the end of some other tests.

### CODE REVIEW

**Comment by phobson** [comment]
I've haven't dug into why, but this is the line currently giving you trouble:
https://github.com/matplotlib/matplotlib/blob/master/conftest.py#L71

**Comment by QuLogic** [comment]
Ah yes, pytest runs pep8 already; we can drop that test eventually, but for now I'll just remove that line.

**Comment by phobson** [comment]
Maybe this as well?
https://github.com/matplotlib/matplotlib/blob/master/tests.py#L30

**Comment by QuLogic** [comment]
Bleh, should be fixed now. Can't wait till we can drop this set of tests.

**Pull request merged**
