### PR TITLE
removing sgskip

### PR DESCRIPTION
**Pull request by choldgraf**
fingers crossed that the tests magically pass...

### CODE REVIEW

**Comment by anntzer** [comment]
looks like you need to remove the coding utf8 line

**Comment by choldgraf** [comment]
hmm - let's see if removing that line solves the problem and I can look into whether this is an issue elsewhere too

**Comment by anntzer** [comment]
The other files that could be affected are userdemo/pgf_*.py, but they probably need to be modified a little bit: they use a noninteractive backend, even though they do ultimately generate a png file so at least in theory s-g may be able to handle them...  I guess a workaround is to indeed write their output, but then add a line that reads the png and displays it using an interactive backend.

**Comment by choldgraf** [comment]
how could I test this out on my computer? last night I tried building sphinx gallery w/ both python 2 and 3 on my machine and it worked OK, so it made things a bit hard to debug. Did you figure out how to make this error on your computer?

**Comment by anntzer** [comment]
test what?  right now python2 examples/userdemo/pgf_fonts_sgskip.py just errors out, but works with py3

**Comment by choldgraf** [comment]
huh - it was working for me on python2 that's what was confusing me

**Comment by choldgraf** [comment]
oops sorry, not pgf_fonts_skip, I was talking about `demo_text...`...lemme try this one

**Comment by choldgraf** [comment]
ok I reproduced the error on my end too. So I have two questions about these examples:

1. If we move the encoding to the top line, it works, but won't that make SG error similarly to the original example in this PR?
2. I tried adding a call to `mpl.use` but got errors since pyplot had already been imported with a backend. Is there a way to do switch the backend on the fly without creating an error?

**Comment by anntzer** [comment]
1. I think this is really a bug in s-g, they need something like https://github.com/ipython/ipython/pull/3662.
2. I thought you could switch between noninteractive backends, or from a noninteractive to an interactive backend?  If not I dunno.

**Comment by choldgraf** [comment]
@anntzer so it'd be fixed if s-g stripped the encoding line before trying to do anything? I can open an issue though it's unclear whether I've got my head wrapped around this problem totally...encoding w strings always confuses me

**Comment by anntzer** [comment]
I think so.

**Pull request merged**
