### PR TITLE
ffmpeg is available on default ubuntu packages now.

### PR DESCRIPTION
**Pull request by anntzer**
... whereas ppa:jonathonf/ffmpeg-3 has gone offline.

will selfmerge yada yada

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Looks like selfmerge is not possible anymore?

**Comment by timhoffm** [comment]
@meeseeksdev backport to v3.1.x

**Comment by timhoffm** [comment]
@meeseeksdev backport to v3.2.x

**Comment by tacaswell** [comment]
@anntzer hmm, interesting side effect of requiring at least one approval to merge...

**Pull request merged**
