### PR TITLE
Backport PR #14295: Fix bug in SymmetricalLogTransform.

### PR DESCRIPTION
**Pull request by efiring**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by efiring** [comment]
Why does this commit show up as authored by @NelleV?  I basically followed the directions in the meeseeksdev bot message for manually backporting.

**Comment by NelleV** [comment]
I merged the PR?

**Comment by efiring** [comment]
Yes, that must be it; it's just not what I was expecting to see, especially since there were conflicts I had to resolve in the backport, so I'm the one who should be blamed if I messed it up.

**Comment by NelleV** [comment]
We both are authors, so comes to it, we'll share the blame 🙂

**Comment by QuLogic** [comment]
The instructions from meeseeksbot are for cherry-picking the merge commit, as it doesn't backport a multi-commit PR individually (which may or may not work so easily).

**Pull request merged**
