### PR TITLE
Fix3483

### LINKED ISSUE #3483: Cannot properly reload figure that was previously pickled
Dear all,
I just figure out that matplotlib does not have apparently a simple way to save interactive plots as MATLAB "fig" figures. I sincerely hope the "experimental" pickling will be soon consolidated because it would be of great benefit for users imho.

Briefly, I followed the simple procedure outlined here in order to pickle and reload figures:
http://stackoverflow.com/questions/7290370/store-and-reload-matplotlib-pyplot-object

It seems that I am able to pickle the figure indeed, but not to reload it properly.
This is what I get:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 299, in resizeEvent
    self.draw()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 154, in draw
    FigureCanvasAgg.draw(self)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 451, in draw
    self.figure.draw(self.renderer)
  File "/usr/lib64/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/figure.py", line 1031, in draw
    dsu = [row for row in dsu if not row[1].get_animated()]
  File "/usr/lib64/python2.7/site-packages/matplotlib/artist.py", line 612, in get_animated
    return self._animated
AttributeError: 'AxesSubplot' object has no attribute '_animated'
```

Any suggestion? Shall I bother about this?
I am using matplotlib 1.3.1 on Fedora 20 with QtAgg backend.

Thanks for your time,

Maurizio

### PR DESCRIPTION
**Pull request by XxdvijxX**
Fixed #3483.
Added pickle_save() function for consistency. 

pickle_save() function combines pickle.dump(obj, file[, protocol]) and pickle.dumps(obj[, protocol]). 

pickle_load() function combines pickle.load(file) and pickle.loads(string).

Both functions were created using a similar format to java overloading.

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for this contribution, however I am not really clear on how this address #3483.  It also looks like your commit history is a bit confused.

@matplotlib/developers Thoughts?  I am :-1: on this on principle due to the many issues with pickles.  I don't think we should provide a top-level function that implicitly endorses the usage of pickles to store or exchange figures.  

As part of the export functionality in MEP23 we should be able to have real serialize/deserialize functionality for the next minor point release which would supersede this.

**Comment by efiring** [comment]
@tacaswell I think it does address #3483, by implementing a suggestion I made.  The problem in #3483 is that unpickling runs into trouble in interactive mode by triggering draw() operations too soon.  The solution here is to turn off interactive mode while unpickling.

Apart from that, though, I agree that pickles are problematic. Given that you have grand plans for a superior serialization scheme, it is better not to introduce pickle wrappers now.

**Comment by fariza** [comment]
@tacaswell did you really mean MEP23?

**Comment by tacaswell** [comment]
No, I meant some combination of MEP25 and MEP26

**Comment by efiring** [comment]
This can be reopened if there is sufficient disagreement; but I am closing it now on the grounds that we don't want to commit to supporting a pickle-based API.  I have also closed #3483.

**Pull request closed without merging**
