### PR TITLE
copy to clipboard and icon for QT

### PR DESCRIPTION
**Pull request by pepe78**
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

Adding icon next to save figure to file and copying figure to clipboard. Tested on linux with QT environment.

### CODE REVIEW

**Comment by pepe78** [comment]
copytoclipboard

**Comment by oscargus** [comment]
Thanks for this PR! Looks like a good idea!

The test failures are, as you may have realized, unrelated. However, is there a way to test this? Maybe add a test that copies an image and then check that the clipboard content has the correct type?

Also, please see #22503 which aims at deprecating qApp. Probably safest to replace it with `QtWidgets.QApplication.instance()` already now.

**Comment by oscargus** [comment]
Probably the documentation for NavigationToolbar2 should be updated as well (as I think this will be required to implement for the other backends as well). Maybe one should also add a keyboard short-cut (ctrl+c)?

**Comment by pepe78** [comment]
this is in one of the files - matplotlibrc: 

#keymap.copy: ctrl+c, cmd+c     # copy figure to clipboard

though it does not work for me... that is why I was trying to add icon. I will try to figure out how to create a test + how to update documentation as well.

**Comment by oscargus** [comment]
After reading up a bit more (I have not looked that much into the backend code), I believe that there is an easier way to do it. It seems like there is already support for copying and that it is maybe enough to add 'copy' here (if it should be default, although there may be an earlier decision that it should not):
https://github.com/matplotlib/matplotlib/blob/53c5f88f8d0fcf3832274558f454dee7c5b7091c/lib/matplotlib/backend_tools.py#L993-L995

(Using an icon would be nice though.)

There is also 
https://github.com/matplotlib/matplotlib/blob/53c5f88f8d0fcf3832274558f454dee7c5b7091c/lib/matplotlib/backends/backend_qt.py#L1000-L1004

which I assume should be triggered by ctrl+c (or pressing the icon). I'm wondering if it may be that SIGSEGV is sent instead of ctrl+c when ctrl+c is pressed on Linux?

**Comment by oscargus** [comment]
It should be possible to just add `image = 'copyfigure'` as a member to this class to get an icon:

https://github.com/matplotlib/matplotlib/blob/53c5f88f8d0fcf3832274558f454dee7c5b7091c/lib/matplotlib/backend_tools.py#L962-L970

**Comment by pepe78** [comment]
yes, I found this as well:
ToolCopyToClipboardBase

though I have no idea how to call it. I tried to use it, but wasn't successful.

**Comment by pepe78** [comment]
I am just going to close this as I am not really sure what would be "the right way" solution. Maybe I will start with some easier contribution to matplotlib. Thanks for the comments though!

**Comment by pepe78** [comment]
Also, I tried this:

default_toolbar_tools = [['navigation', ['home', 'back', 'forward']],
                         ['zoompan', ['pan', 'zoom', 'subplots']],
                         ['io', ['save', 'help', 'copy']]]

but it did not show the copy thing when tried to test it out...
doesntwork

**Comment by pepe78** [comment]
I think I will leave this one to someone else. I took it as an exercise and now I have a new PR for different fix of matplotlib. Hopefully that one goes through. Thanks

**Comment by oscargus** [comment]
OK! Do you mind if I take the icon, attribute the commit with the icon to you and create a PR?

**Comment by pepe78** [comment]
Please go ahead - I just want my first PR to go smoothly (the other one) to learn how you guys do things. In future, I might be more adventurous and have more PRs at the same time. In meantime, just go ahead.

**Pull request closed without merging**
