### PR TITLE
Test 2.0.x on released python 3.6

### PR DESCRIPTION
**Pull request by dstansby**
...instead of -dev

### CODE REVIEW

**Comment by dopplershift** [comment]
My only question is whether we should leave the build against pre-releases and the dev version of 3.6 as well--in theory the dev version is a snapshot for a future 3.6 release.

**Comment by dstansby** [comment]
TIL that editing files via the web interface opens a new branch in the project and not your own account, sorry...

**Comment by QuLogic** [comment]
We've got a nightly build, so maybe it'll be fine (I realize that's 3.7.. though).

**Comment by tacaswell** [comment]
upstream cpython is very good about not breaking things on mircos (I can only think of 1 issue in the last 4 years that is related to a micro-release and it has to do with fixing critical bugs in later micros).

Testing on 3.7-nightly more than covers the 3.6 dev channel, we only had both because at some point before 3.6 came out, the nightly moved to 3.7 and we needed the 3.6-dev to get the betas/rcs.

**Comment by dopplershift** [comment]
Ok. That's a 👍  from me then.

**Comment by QuLogic** [comment]
We can ignore the failing push part of CI.

**Pull request merged**
