### PR TITLE
Remove versionadded notes; correct doc link

### PR DESCRIPTION
**Pull request by kentcr**
## PR Summary

Remove unmaintained version notes/annotations from axes3d.py. This also corrects an inline markup escape sequence to generate a doc link properly.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [X] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [X] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [X] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by tacaswell** [comment]
I am weakly :-1:  on removing the `.. versionadded: ` notes.  Although we do not plan to provide bug-fix releases for any of the old versions, there is definitely a lot of use of older versions in the wild.

**Comment by jklymak** [comment]
We don't use `.. versionadded::`  anywhere else, and have not used it consistently in this toolbox.  Does it really make sense to keep it?

**Comment by WeatherGod** [comment]
I added it back then because we were starting to use it in some other
places. I don't know why it was removed elsewhere, but I have always valued
these sorts of documentation notes.

**Comment by timhoffm** [comment]
versionadded is generally a helpful concept. However, only having it for very few functions is not a great help. It's rather making me wonder why I don't see that info on other functions and if that missing tag means they are older than any explicitly mentioned version.

Since we don't have it and nobody wants to take the effort of adding it for large parts of the library, I'm +0.5 on removing the entries for consistency.

**Comment by QuLogic** [comment]
My thought is that since 2.0 made default changes, you probably don't want to go any older than that, so any `versionadded` before that is noise. But anything newer than 2.0 probably has a What's new? entry, so probably doesn't need the tag either.

**Comment by QuLogic** [comment]
Oops, misclick there.

**Comment by kentcr** [comment]
The effect of these is just to include a "what's new" or "changed in" note to the documentation. Including such notes for things added in 2011 does not make any sense to me unless the intention is to do that for the entire API. Having these for new things does make sense, but I was asked to remove such a note in my recent PR, so consistency is already a problem.

Consistency would also be important because if I saw a "what's new in 3.3.5", I'd be led to believe all such additions to 3.3.5 would say so. So it should then be another thing to require and check in every new PR.

Then the question becomes how long you keep them. Not that I've looked closely, but Python docs seem to keep them for the current major version number (see https://docs.python.org/3/library/hashlib.html for examples) and I've been happy with that.

**Review by QuLogic — APPROVED** [review]

**Comment by QuLogic** [comment]
I think overall we're in favour here, and I'd rather fix CI. One can always revert if strongly feel like adding those everywhere.

**Pull request merged**
