### PR TITLE
Document legend best slowness

### PR DESCRIPTION
**Pull request by kbrose**
## PR Summary

Document the slowness of legend's default axis behavior with large amounts of data. Ref #12120.

## PR Checklist

- [ ] Documentation is sphinx and numpydoc compliant

------------------

p.s. Congrats on 3.0!

### CODE REVIEW

**Comment by kbrose** [comment]
For "Documentation is sphinx and numpydoc compliant" is there a way I can verify that? Do the circle CI runs check that? Maybe there will be a build of the docs I could look at to make sure it looks correct?

**Comment by jklymak** [comment]
You can check the output in the CircleCI logs for the location of the built documentation, follow that link and see that it looks OK.

**Comment by ImportanceOfBeingErnest** [comment]
The documentation build of your PR is available at https://circleci.com/gh/matplotlib/matplotlib/13683/artifacts/0//home/circleci/project/doc/build/html/index.html You find this link via he "Details"-Button on the checks.

**Comment by ImportanceOfBeingErnest** [comment]
This is only a minor point, but in general the documentation mostly uses a passive style, like "A parameter can be set." instead of "You may set a parameter."

**Comment by kbrose** [comment]
Should I change to passive? I thought it may be but I did a ctrl-f "you" in https://matplotlib.org/users/legend_guide.html and found examples so I thought it'd be fine.

**Comment by jklymak** [comment]
My vote is for active voice most of the time.

**Comment by ImportanceOfBeingErnest** [comment]
Nevermind, even the `Axes.legend` docstring addressed the reader in person before this change.

**Pull request merged**
