### PR TITLE
Backport PR #21833: Enforce backport conditions on v*-doc branches

### PR DESCRIPTION
**Pull request by tacaswell**
Merge pull request #21833 from QuLogic/clean-doc-backports

CI: Enforce backport conditions on v*-doc branches

### CODE REVIEW

**Comment by tacaswell** [comment]
This is failing on the changes in float results due to the SIMD instructions that numpy now ships with in their wheel.  We need to do one of:
 - backport the tolerance increase
 -  pin back numpy
 - use the envs variables to turn off the SIMD instructions
 - turn off everything but doc building and publishing on these branchs


I lean towards the last option (turn off tests on the docs branch).

**Comment by QuLogic** [comment]
They're already supposed to be off, but this only covers direct pushes, and not PR targets.

**Comment by QuLogic** [comment]
See #22256

**Comment by QuLogic** [comment]
Ah, even though it appears that test were run here, they are the original ones from the last time. Since they didn't run again, the old statuses were not removed.

**Pull request merged**
