### PR TITLE
DOC: Update description of properties of Line2D in 'plot' documentation.

### LINKED ISSUE #14720: Line2D properties should state units
Right now `Line2D` `linewidth` parameter is a `float`.  That is nice to know, but it would be helpful to know that the float is points.  Same with `markersize`, and probably other kwargs.

### PR DESCRIPTION
**Pull request by sameshl**
Line2D properties on plot documentation had only mentioned property value to be float and had not given any info on unit used.
Added info on unit used for properties is points.

closes #14720

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Note this does not close #14720 which is for the kwarg list that gets repeated in other methods that use Line2d

**Comment by sameshl** [comment]
I see. My bad. Can you help me understand where I would have to make changes so I can fix it for other methods that use Line2D

**Comment by timhoffm** [comment]
See lines.py l.1528 and the methods used therein for the docstring generation mechanism. 
~~~
docstring.interpd.update(_Line2D_docstr=artist.kwdoc(Line2D))
~~~

**Comment by sameshl** [comment]
@timhoffm I looked into https://github.com/matplotlib/matplotlib/blob/master/doc/devel/documenting_mpl.rst#keyword-arguments . And by the given code example there, it looks like any changes made in the docstrings of Line2D will get reflected in all the methods use Line2D

**Comment by sameshl** [comment]
@dstansby Thank you! Looking forward to more contributions to this organization. :smiley:

**Comment by timhoffm** [comment]
Thanks, and congratulations on your first contribution to Matplotlib! Hope to see you back sometime. :smile:

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.1.x

**Pull request merged**
