### PR TITLE
Start testing on Python 3.11

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by QuLogic** [comment]
`pikepdf` does not have 3.11 wheels, due to https://github.com/python/cpython/issues/96046, so I skipped the extra requirements for now.

**Comment by QuLogic** [comment]
Also moving to 3.6 as we are already releasing 3.11 wheels for it and those should be tested.

**Review by timhoffm — APPROVED** [review]

**Comment by QuLogic** [comment]
`certifi` put out a new release to fix the warning, so I restarted the job and it's passing now.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
Feel free to merge on green...

**Pull request merged**
