### PR TITLE
Skip svg tex test if tex is not installed

### PR DESCRIPTION
**Pull request by jenshnielsen**
This should fix failure on the 2.x branch after the merge of #5766 

This should be merged asap to make the 2.x branch pass again

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Unfortunatly this doesn't seem to fix the issue

**Comment by mdboom** [comment]
Does the baseline image need to be updated?

Beyond that, I wonder if OrdereredDict isn't enough for the issue if things still come in from TeX in a non-deterministic order.  We may need to forcibly sort...

**Comment by ksemb** [comment]
The test currently seems to fail because of the error
`RuntimeError: In select_charmap: Could not set the charmap`
I think this is a latex issue unrelated to determinism / randomness.

**Comment by ksemb** [comment]
The tests seem to fail because of the error
`RuntimeError: In select_charmap: Could not set the charmap`
This might be a LaTeX error that is unrelated to determinism / randomness

**Comment by jenshnielsen** [comment]
Yes thats true, Not completely sure what happens but this is only an issue on 2.x so presumably ti requires something which is not backported to 2.x

**Comment by jenshnielsen** [comment]
The real reason this fails is that #5677 wasn't backported. That changes the exception in textpath.py to catch Runtime errors too. It's not obvious from #5677 why that is needed by @mdboom might remember

**Comment by mdboom** [comment]
The exception changed in the rewrite of the C++ extensions last year, but none of that was in the test suite (since we didn't have TeX+SVG tests until this one).

I say we just apply 

```diff
diff --git a/lib/matplotlib/textpath.py b/lib/matplotlib/textpath.py
index c063c3a..b694619 100644
--- a/lib/matplotlib/textpath.py
+++ b/lib/matplotlib/textpath.py
@@ -345,7 +345,7 @@ class TextToPath(object):
                                                     1094995778)]:
                     try:
                         font.select_charmap(charmap_code)
-                    except ValueError:
+                    except (ValueError, RuntimeError):
                         pass
                     else:
                         break
```

here, and not backport all of #5677 -- it turns out there are few issues with it and we may end up reverting it in the long run.

**Comment by jenshnielsen** [comment]
@mdboom makes sense I have applied the error change here but I guess we should backport that change (16698e8dfa1ca084982042a4e7518900e969973f) all the way to 1.5.x? 

I think the other change here should go in to since this test really needs tex to run, But that is against 2.x

**Comment by mdboom** [comment]
I agree on all points.  Not sure if it matters too much how we do it -- we can always make another PR against v1.5.x with 16698e8 cherry-picked in it.

**Pull request merged**
