### PR TITLE
Improve nbAgg & WebAgg toolbars

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This tweaks the nbAgg and WebAgg toolbars to look a little better. Using button groups, we can emulate the spacer setup that other GUIs have. For WebAgg, start using Matplotlib's icons and try to move away from jQuery UI's CSS. Additionally, implement `set_history_buttons`, so the back/forward buttons disable themselves, and add a style for active button, to show pan/zoom state.

Previously, nbAgg looked like:
Screenshot_2020-04-09 Untitled
and now it looks like:
Screenshot_2020-04-20 Untitled

Previously, WebAgg looked like:
Screenshot_2020-04-09 matplotlib
and now it looks like:
Screenshot_2020-04-20 matplotlib

~~Waiting for #17053.~~

## PR Checklist

- [N/A] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
Can the dropdown box in webagg be centered again?

**Comment by QuLogic** [comment]
I'm not sure if it was aligned before, or just coincidence. It's easiest if we use flexbox, looks like it's [available almost everywhere](https://caniuse.com/#feat=flexbox).

**Comment by QuLogic** [comment]
Oh, I checked again, and it's actually just `vertical-align:middle;` on everything, which is pretty easy to do.

**Comment by timhoffm** [comment]
@QuLogic when using the "Waiting for other PR" label, can you please cross-link the other PR, so that one can find out what has to be reviewed before this?

**Comment by QuLogic** [comment]
Updated to be vertically aligned.

Additionally, I implemented `set_history_buttons`, so the back/forward buttons disable them selves, and added a style for active button, to show pan/zoom.

For nbAgg, it uses 'active' & disabled style in Bootstrap:
Screenshot_2020-04-20 Untitled

For WebAgg, there are new styles to colorize the active image to approximately tab:blue, and a disabled style:
Screenshot_2020-04-20 matplotlib

**Comment by QuLogic** [comment]
Rebased and updated the original description with the new screenshots.

**Comment by QuLogic** [comment]
Looks like this broke the non-embedded WebAgg, so don't merge until I re-check this.

**Comment by QuLogic** [comment]
OK, it was just crossed PRs with #17135 and an errant slash.

**Pull request merged**
