### PR TITLE
[MRG] Defaults: change animation codec to h264

### PR DESCRIPTION
**Pull request by efiring**

### CODE REVIEW

**Comment by efiring** [comment]
This was discussed in http://matplotlib.1069221.n5.nabble.com/Matplotlib-devel-switch-default-to-h264-td47382.html.  Looking back at that I see that I had forgotten the reason I didn't do it right away, which is that a check for an odd number of pixels is needed with h264 regardless of whether it is the default.

**Comment by efiring** [comment]
What a mess! As far as I can see, mencoder doesn't handle h264 at all.  It isn't among the listed labavcodecs in the current documentation, and those are the only ones available in my homebrew mencoder. @dopplershift, is there any reason to support mencoder at all?  Does it have any advantages? Any platforms where it is readily available and neither ffmpeg nor avconv is?  
The even number of pixels requirement for h264 can be handled in ffmpeg via either cropping or scaling.

**Comment by NelleV** [comment]
And it seemed so simple :)

**Comment by dopplershift** [comment]
I think years ago mencoder might have had a comparable install base. Personally, I'm fine with ffmpeg only since that's the only one with conda-forge packages--though I'd like to hear some more voices on this.

**Comment by efiring** [comment]
The docs build initially fails with this:

Warning, treated as error:

/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/matplotlib-2.0.0b4+224.gaad576f-py2.7-linux-x86_64.egg/matplotlib/animation.py:docstring of matplotlib.animation.MencoderFileWriter:5: WARNING: Explicit markup ends without a blank line; unexpected unindent.

It looks to me like it might be a problem related to this part of the `deprecated` decorator in cbook:
```python
        if not old_doc:
            # This is to prevent a spurious 'unexected unindent' warning from
            # docutils when the original docstring was blank.
            new_doc += r'\ '
```
I'm trying to work around it by adding docstrings.

**Comment by efiring** [comment]
Trying again: I now think the problem is that the message argument to the deprecated decorator must be a single line.

**Pull request merged**
