### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by taehoonlee**
This PR fixes some typos: `redunant`, `flippped`, `plottted`, `overrride`, `connnect`, and `entires `.

### CODE REVIEW

**Comment by anntzer** [comment]
qhull fixes should really go to https://github.com/qhull/qhull.

**Comment by taehoonlee** [comment]
The changes on `qhull` have been reverted, thank you @anntzer!

**Comment by tacaswell** [comment]
@taehoonlee The email on the commit is not one github knows about, is it the one you intend it to be?

**Comment by taehoonlee** [comment]
After deleting old emails and registering new one, I had a problem with Github authentication. Now the problem is resolved.

**Pull request merged**
