### PR TITLE
Don't convert vmin, vmax to floats.

### PR DESCRIPTION
**Pull request by anntzer**
They may be float128's in which case precision would be lost; this can
result in `Normalize` returning values (barely) outside of `[0, 1]`.

(The cast to `float` was introduced in 28e1d2, referring to bug 2997687
on SF; it may be worth checking what it was about.)

See #6698.

### CODE REVIEW

**Comment by efiring** [comment]
I suspect it would make more sense to just convert the float128 input to float64 at an early stage.  The conversion will occur sooner or later anyway; we have no mechanism for maintaining float128 throughout the pipeline, and that level of precision makes no sense for plotting anyway.

**Comment by WeatherGod** [comment]
Eventually, everything needs to become float-like. The purpose of casting
to float was most likely to avoid integer division. Unfortunately, the
issue tracker is no longer up on sourceforge, so it is going to be hard to
find out what that particular issue was.

**Comment by anntzer** [comment]
See also #6677 for @efiring's suggestion (which I agree with -- similar bugs with handling float128's probably occur at a bunch of other places).  However I'd rather keep this simple solution for now and have a separate discussion for making the switch to float64 (or even float32, which is certainly enough for plotting purposes) everywhere at the same time.

**Comment by anntzer** [comment]
Apparently not... https://mail.scipy.org/pipermail/scipy-dev/2008-March/008562.html
A quick test tells me that longdouble is float64 on Windows.  Still, that seems good enough for the tests.  Updated.

**Comment by tacaswell** [comment]
It looks like the single value branch of the `process_value` method needs the same sort of logic as the array branch.  I think it will currently cast a single float128 to a possibly shorter float leading to the same issue.

**Comment by anntzer** [comment]
Actually both branches probably need it, right?
I think we should cast `result` to `np.promote_types(result.dtype, np.float32)` (i.e. at least `float32` but not smaller than the actual size).

**Comment by tacaswell** [comment]
The array branch only casts to it if it is not a float type, otherwise we just copy.

**Comment by anntzer** [comment]
I see.  I guess the whole `process_value` method could be simplified to
```
def process_value(value):
    is_scalar = not cbook.iterable(value)
    if is_scalar:
        value = [value]
    dtype = np.min_scalar_type(value)
    dtype = (np.float32 if dtype.itemsize <= 2
             else np.promote_types(dtype, float))
    result = np.ma.array(value, dtype=dtype, copy=True)
    return result, is_scalar
```
right?

**Comment by tacaswell** [comment]
Yes, I think so.

**Comment by anntzer** [comment]
done.

**Comment by tacaswell** [comment]
:+1: LGTM pending appveyor

**Comment by anntzer** [comment]
Appveyor failure seems spurious?
Also, note that the parent issue (#6698) is milestoned to 2.0 (and this bug was revealed by #6382, which is also in 2.0).

**Comment by jenshnielsen** [comment]
Regarding float128 it's not actually 128 bytes but a long double which is padded to 128 bits http://docs.scipy.org/doc/numpy-dev/user/basics.types.html 

On Linux and OSX long doubles are normally 80 bits but on windows (MSVC) they are equivalent to doubles. They may have more precision on other less common platforms.

**Comment by tacaswell** [comment]
backported to v2.x as c7d7d19

**Comment by anntzer** [comment]
@efiring @WeatherGod @tacaswell 
Following the discussion in #6825 I will probably need to revert that PR for a more comprehensive solution instead, which is unlikely to be ready by 2.0 (any timeline btw?).  However, we still need a fix for #6698 for 2.0.  I *think* we can probably get away with giving a bit of tolerance to the 0-1 range (i.e. clip values between -1e-8 and 0 to 0 and values between 1 and 1+1e-8 to 1).  Thoughts?

**Pull request merged**
