### PR TITLE
FIX: qt recursive draw

### LINKED ISSUE #9134: segfault ("recursive repaint") with Qt5Agg
### Bug report

**Bug summary**

As of master,
```
$ python examples/images_contours_and_fields/plot_streamplot.py
QWidget::repaint: Recursive repaint detected
Fatal Python error: Segmentation fault
```
(Qt5Agg backend)

**Code for reproduction**

See above.

**Actual outcome**

NA

**Expected outcome**

Don't crash.

**Matplotlib version**

  * Operating System: Arch Linux
  * Matplotlib Version: master
  * Python Version: 3.6
  * Jupyter Version (if applicable):
  * Other Libraries: Qt5.9 from pypi in a venv.  *does not occur with Arch repo PyQt5* (recursive repaint message occurs sometimes, but does not crash even then)

bisects back to d0eeddb92 which is the merge commit for #9103; however, interestingly, the tip of that commit does *not* crash so something went wrong during the merge.

### PR DESCRIPTION
**Pull request by tacaswell**
- put draw_idle in the base canvas resize event
 - re-order our resize handling and Qt's resize handling (let Qt go
   first)
 - do not call processEvents from inside of the paint event (this
   maybe the critical fix)

closes #9134 

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
LGTM (and thanks for the patch!), although you may want to check whether this means we should remove a now extraneous draw_idle in other backends?  (not that it would really matter as the draw_idles should get compressed into a single one).

**Comment by tacaswell** [comment]
This now fails the Qt5 DPI test... yay!

**Comment by tacaswell** [comment]
@dopplershift This also fixes the flicker you noticed.

**Comment by anntzer** [comment]
thanks

**Pull request merged**
