### PR TITLE
FIX: ticks filtered by Axis, not in Tick.draw

### PR DESCRIPTION
**Pull request by tacaswell**
Replaces #6647

### CODE REVIEW

**Comment by tacaswell** [comment]
@anntzer Corrected the tests and re-worded your commit message a bit to add a note about where the tick-in-view-limit filtering is actually accruing.

**Comment by anntzer** [comment]
Thanks for taking over, I've been a bit busy recently.

**Comment by efiring** [comment]
I merged because I didn't see any point in waiting for Appveyor for this one; Travis passed.

**Comment by efiring** [comment]
Pushed to v2.x as 9bc745c.

**Pull request merged**
