### PR TITLE
Fix errorbar extension arrows

### PR DESCRIPTION
**Pull request by mdboom**
The arrows on errorbar extensions are currently "centered" at the tip of the arrow.  This means that if the errorbar line width becomes larger it sticks out from underneath the arrow head, looking quite odd.

This adds new triangle markers that are centered at the base on the arrow head rather than the tip and uses those for errorbar extensions.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
pep8 :(

/home/travis/build/matplotlib/matplotlib/lib/matplotlib/lines.py:37:1: E302 expected 2 blank lines, found 1

**Comment by QuLogic** [comment]
I assume these are unrelated, but the scatter markers don't seem quite so centred and one of the axes in `test_axes/errorbar_mixed.png` is in the wrong colour.

**Comment by mdboom** [comment]
The markers looking slightly off center is due to 37927b2228c9e46bcbba8d6df97002b8978ab06e.  It makes the markers look more round, but it also no longer centers them around 0.  I'll see if there's a better middle ground in a separate PR.

Good point about the update of the color in `test_axes/errorbar_mixed.png`.  The test is explicitly asking for green there -- I'll have to get to the bottom of why that isn't being obeyed.

**Comment by mdboom** [comment]
> The test is explicitly asking for green there -- I'll have to get to the bottom of why that isn't being obeyed.

I think this was just due to a mistake on my part.  It's been corrected here.

**Comment by tacaswell** [comment]
Do we want to revert 37927b2 ? It did fix a problem, but seems to have created another one which is just as bad.

**Comment by mdboom** [comment]
> Do we want to revert 37927b2 ? It did fix a problem, but seems to have created another one which is just as bad.

I'm wondering if it can be addressed by snapping only the end points and not the control points of the Bézier curve.  I plan to experiment with that today when I get a chance.  If that doesn't yield better results then, yes, maybe reverting is the best option.

**Comment by mdboom** [comment]
See #5306 for a possible solution to the off-centered marker issue.

**Comment by mdboom** [comment]
Let's hold on this one until #5603 is merged.

**Comment by tacaswell** [comment]
I kicked to restart on current master, but @mdboom needs to re-regenerate the images anyway.

**Comment by mdboom** [comment]
I've redone the baseline images here after #5603.  Once Travis passes, I'd say this is good to go.

**Comment by jenshnielsen** [comment]
The superscript changes in errorbar_mixed.png are not for the better but I assume they are unrelated?

**Comment by mdboom** [comment]
I think that might be fixed in master already.  I'll rebase and see what happens locally.

**Comment by mdboom** [comment]
I think the new superscript placement is fine -- I realize it's not as high, but with respect to all of the other combinations that sub/super can find themselves in, I think it's the best choice for the DejaVu font -- anything else has negative consequences in other dimensions.  See #4873.

**Comment by mdboom** [comment]
Rebased to test this in zero-tolerance mode.

**Comment by jenshnielsen** [comment]
backported as ebf81db3b7f356e90e703d86c559ae3baba9c252

**Comment by QuLogic** [comment]
Backport to v2.x is actually via 4f40a9da031908b96b92f05de9da38ad1b3c06be.

**Pull request merged**
