### PR TITLE
Fixed zero args to make_compound_path.

### PR DESCRIPTION
**Pull request by pelson**

### CODE REVIEW

**Comment by efiring** [comment]
Looks reasonable, but I think you want this against master, not 1.4.x, don't you?

**Comment by tacaswell** [comment]
Merged to master as 30f9def2737e894b07a51c1ad61d4c8ce74e76a5 

We can cherry-pick back to `color-overhaul` if needed.

**Comment by pelson** [comment]
> Looks reasonable, but I think you want this against master, not 1.4.x, don't you?

Had v1.4.3 not gone out of the door, no - I would have seen this hitting v1.4.3 - but as it has, it makes no difference if we target 1.4.x or not, so yes, master would be the target.

**Comment by pelson** [comment]
Thanks for merging @tacaswell.

**Pull request closed without merging**
