### PR TITLE
Add rcParams support for markers' fillstyle prop

### PR DESCRIPTION
**Pull request by nkoep**
This registers the `markers.fillstyle` option with the `rcParams` dict to allow configuring the default fillstyle of plot markers via rc files.

I noticed in the diff that the commit also removes trailing whitespaces in a few places. It's stated in the coding guidelines that trailing whitespace should be avoided. However, if this change isn't desired after all or shouldn't be mixed with actual code changes, I'll split the changes into two separate commits.

### CODE REVIEW

**Comment by nkoep** [comment]
I just rebased this PR on top of master so that it can be merged without conflicts if there's still interest in the change.

**Comment by tacaswell** [comment]
Thank you

**Comment by tacaswell** [comment]
@nkoep Sorry for the slow response on our end.  Any chance you can add a section to https://github.com/matplotlib/matplotlib/blob/master/doc/users/whats_new/rcparams.rst ?

**Comment by nkoep** [comment]
Will do

**Comment by nkoep** [comment]
I rebased the PR again and added a short note to the rcparams.rst file in d0d9fa3. Hope the explanation is sufficient.

**Comment by WeatherGod** [comment]
Looks good to me. Merging...

**Pull request merged**
