### PR TITLE
Make setup.py clean a noop command that prints a warning

### LINKED ISSUE #6911: freetype build won't become local
I have a git checkout of matplotlib on which I would like to run the tests. In order to do so I have set `local_freetype=True` in setup.cfg and ran the following in a virtual environment:

	(matplotlib) matplotlib$ python3.5 setup.py build
	============================================================================
	Edit setup.cfg to change the build options

	BUILDING MATPLOTLIB
		    matplotlib: yes [2.0.0b3+1919.g2dfef6a]
		        python: yes [3.5.1+ (default, Mar 30 2016, 22:46:26)  [GCC
		                5.3.1 20160330]]
		      platform: yes [linux]

	REQUIRED DEPENDENCIES AND EXTENSIONS
		         numpy: yes [version 1.11.1]
		           six: yes [using six version 1.10.0]
		      dateutil: yes [using dateutil version 2.5.3]
		   functools32: yes [Not required]
		  subprocess32: yes [Not required]
		          pytz: yes [using pytz version 2016.6.1]
		        cycler: yes [using cycler version 0.10.0]
		       tornado: yes [tornado was not found. It is required for the
		                WebAgg backend. pip/easy_install may attempt to
		                install it after matplotlib.]
		     pyparsing: yes [using pyparsing version 2.1.5]
		        libagg: yes [pkg-config information for 'libagg' could not
		                be found. Using local copy.]
		      freetype: yes [Using local version for testing]
		           png: yes [version 1.2.54]
		         qhull: yes [pkg-config information for 'qhull' could not be
		                found. Using local copy.]

	OPTIONAL SUBPACKAGES
		   sample_data: yes [installing]
		      toolkits: yes [installing]
		         tests: yes [using nose version 1.3.7 / using unittest.mock]
		toolkits_tests: yes [using nose version 1.3.7 / using unittest.mock]

	OPTIONAL BACKEND EXTENSIONS
		        macosx: no  [Mac OS-X only]
		        qt5agg: yes [installing, Qt: 5.7.0, PyQt: 5.7.0; PySide2 not
		                found]
		        qt4agg: yes [installing, Qt: 5.5.1, PyQt: 5.5.1; PySide not
		                found]
		       gtk3agg: no  [Requires pygobject to be installed.]
		     gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
		        gtkagg: no  [Requires pygtk]
		         tkagg: yes [installing; run-time loading from Python Tcl /
		                Tk]
		         wxagg: no  [requires wxPython]
		           gtk: no  [Requires pygtk]
		           agg: yes [installing]
		         cairo: no  [cairocffi or pycairo not found]
		     windowing: no  [Microsoft Windows only]

	OPTIONAL LATEX DEPENDENCIES
		        dvipng: yes [version 1.15]
		   ghostscript: yes [version 9.18]
		         latex: yes [version 3.14159265]
		       pdftops: yes [version 0.41.0]

	OPTIONAL PACKAGE DATA
		          dlls: no  [skipping due to configuration]

	running build
	running build_py
	copying lib/matplotlib/mpl-data/matplotlibrc -> build/lib.linux-x86_64-3.5/matplotlib/mpl-data
	UPDATING build/lib.linux-x86_64-3.5/matplotlib/_version.py
	set build/lib.linux-x86_64-3.5/matplotlib/_version.py to '2.0.0b3+1919.g2dfef6a'
	running build_ext
	(matplotlib) matplotlib$ PYTHONPATH=build/lib.linux-x86_64-3.5/ python3.5 tests.py --nocapture
	Python byte-compilation optimization level: 0
	/home/herbert/Repositories/matplotlib/build/lib.linux-x86_64-3.5/matplotlib/__init__.py:1580: UserWarning: matplotlib is not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg and rebuild. Expect many image comparison failures below. Expected freetype version 2.6.1. Found freetype version 2.6.1. Freetype build type is not local
	  "" if ft2font.__freetype_build_type__ == 'local' else "not "

as you can see, the build command reports that the used freetype should be local, but when running the tests, they are not local as reported by the error. Why is this the case?

### PR DESCRIPTION
**Pull request by jenshnielsen**
Closes #6911

We could also try to reimplement it to do something useful

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I am not convinced that we want to do this so any feedback is appreciated

**Comment by QuLogic** [comment]
It seems to work well enough for my needs (e.g., switching between 1.5 and master), so I don't really feel like disabling it.

**Comment by jenshnielsen** [comment]
Interesting. I would never ever risk using it due to issues such as #6911 but then again I don't really care because I almost always do `pip install .` anyway

**Comment by QuLogic** [comment]
I also use `pip`, but with `-e`, so I need to clean the `.so` that are left in the source directory.

**Comment by jenshnielsen** [comment]
Yes, I prefer to use `git clean` which I trust to do what I want for that

**Comment by jenshnielsen** [comment]
closing since this does not seem to be the way to go

**Pull request closed without merging**
