### PR TITLE
Unsixification

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Die, Py2, die... :p 
(Tried to keep this to the "trivial" cases.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Should we concerned by the drop in tests codecov?  I've heard thats bad news...

**Comment by anntzer** [comment]
That's because we're removing a bunch of "import six" which were covered...

**Comment by tacaswell** [comment]
If you clean up test_basic.py you will be able to push your test coverage back up by removing some un-tested py2 only paths.

**Comment by anntzer** [comment]
tests will have their own PR... some day if no one else beats me to it.

**Pull request merged**
