### PR TITLE
FIX: cancel pending autoscale on manually setting limits

### LINKED ISSUE #17331: Surprising/changed axis limit (autoscale) behavior
### Bug report

**Bug summary**

The interaction of setting axis limits and autoscaling changed in 3.2 with little guidance, introducing unexpected behavior that doesn't always make sense.

**Code for reproduction**

Here is a plot that looks very different on 3.1.2 and 3.2.1

```python
import numpy as np
import matplotlib.pyplot as plt
f, ax = plt.subplots()
x = np.arange(100)
y = np.random.uniform(-.1, .1, 100)
ax.scatter(x, y)
assert ax._autoscaleYon
ax.set_ylim((-.5, .5), auto=None)
```

**Actual outcome**

On 3.2.1

image

**Expected outcome**

On 3.1.2

image

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): pylab inline
  * Python version: 3.7

### PR DESCRIPTION
**Pull request by tacaswell**
closes #17331

## PR Summary
Applies patch suggested by @anntzer  in https://github.com/matplotlib/matplotlib/issues/17331#issuecomment-624109727

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant

### CODE REVIEW

**Comment by QuLogic** [comment]
#17331 says that `auto=True`  also changed, but there's no test for that here. Is that also fixed by this?

**Comment by tacaswell** [comment]
Not, sure will look at that tomorrow.

**Comment by tacaswell** [comment]
The `auto` keyword is about what state the autoscale is left in after setting the ylim, not if autoscaling should be merged with the current limits. That is, it controls if the next time you add an artist it will re-scale of if the limits are now fixed.

It is orthogonal to the bug, but I added a test for it while we are thinking about it (and added a symmetrical test of set_xlim)

**Comment by WeatherGod** [comment]
I think you need to do the same for the set_zlim() for mplot3d? (or maybe it is taken care of through inheritance?)

**Comment by tacaswell** [comment]
The zlim does not participate in the lazy view lim setting :man_shrugging: so it was unaffected by this bug.

**Pull request merged**
