### PR TITLE
Fix tk icon loading.

### PR DESCRIPTION
**Pull request by anntzer**
Accidentally broke this for no good reason in #8773.  Milestoning as 2.2 as it's fixing a bug introduced in 2.1.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Is the best way to test this just open a plot in a tk window?

**Comment by anntzer** [comment]
Yes

**Comment by dstansby** [comment]
Hmm, I don't get an icon with the fix, but that might be an OSX thing.

**Comment by QuLogic** [comment]
It works again, but it's kind of low resolution.

**Pull request merged**
