### PR TITLE
Fix test  docs build on Travis with Sphinx 1.3.0 Edit (Lock travis on 1.2.3 for now)

### PR DESCRIPTION
**Pull request by jenshnielsen**
Sphinx 1.3 was just released. This introduced a number of new warnings which caused a test failure and our docs to stop building since we treat warnings as errors.  

The test failed due to a renamed theme. So I have changed the config to set the theme name depending on the Sphinx version. (This might need a backport to the color overhaul branch)

The docs fail with:

```
WARNING: the config value 'html_domain_indices' has type `list', defaults to `bool.'
```

Which is treated as an error. This looks like a bug in Sphinx it self since according to http://sphinx-doc.org/config.html?highlight=html_domain_indices#confval-html_domain_indices a list should be fully legal

In the interest of having a functional Sphinx build I have disabled the warnings as errors until we can get to the bottom of this.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I asked a question about this at the Sphinx group https://groups.google.com/forum/#!forum/sphinx-users
(may still be held for moderation)

**Comment by jenshnielsen** [comment]
This is not enough, There is also an issue with our plot directive 

https://api.travis-ci.org/jobs/54071025/log.txt?deansi=true

Perhaps it is better to nail Sphinx to 1.2.3 for the time being?

**Comment by tacaswell** [comment]
:+1: for nailing to sphinx 1.2.3 for now

**Comment by jenshnielsen** [comment]
That is done now. I have added #4215 to track getting it working with Sphinx 1.3.0

**Pull request merged**
