### PR TITLE
FIX: testings.nose was not installed

### PR DESCRIPTION
**Pull request by NelleV**
I am not sure how the tests work on any platform right now… testing.nose was not installed, so the tests could not run.

### CODE REVIEW

**Comment by Kojoley** [comment]
Thanks for fixing my mistake!

**Comment by NelleV** [comment]
My humble opinion is that this shows an underlying problem on the way travis runs the tests (and in general how brittle matplotlib's tests are). At some point, it might be worth doing major reorganization of the repository to have it follow a more traditional organization.
I just hope this hasn't been around for too long, as this show that people don't run the tests on their laptop :)

**Comment by tacaswell** [comment]
The tests will run correctly if you install via `python setup.py develop` / `pip install -e .` (which is how I do it).

**Comment by NelleV** [comment]
appveyor seems unhappy for a font problem. That seems quite unrelated to this PR. Is there a way to relaunch it?

**Comment by afvincent** [comment]
@NelleV Closing the PR and reopening it usually does the trick.

**Comment by jenshnielsen** [comment]
The appveyor issue is unrelated and hopefully fixed by https://github.com/matplotlib/matplotlib/pull/7063

**Comment by NelleV** [comment]
@jenshnielsen I saw the PR and I'll wait until it is merged to rebase.

**Comment by NelleV** [comment]
I guess I won't rebase! Thanks!

**Comment by jenshnielsen** [comment]
I didn't want to hold back your work since this is a serious bug and the failure clearly unrelated

**Pull request merged**
