### PR TITLE
Added an entry for mpl-scatter-density in the third-party tools page

### PR DESCRIPTION
**Pull request by astrofrog**
As suggested in https://github.com/astrofrog/mpl-scatter-density/issues/10

### CODE REVIEW

**Comment by anntzer** [comment]
I was trying to keep the packages in alphabetical order (and yes that means that Decida should be moved up too).  Can you fix that?  Otherwise lgtm.

**Comment by astrofrog** [comment]
@anntzer - done! I think the Travis failure was unrelated btw.

**Comment by tacaswell** [comment]
pandas 0.21 broke one of our tests.

**Comment by anntzer** [comment]
@astrofrog do you mind if I push a (losslessly) [pngcrush](https://en.wikipedia.org/wiki/Pngcrush)'ed version of the image?  that chops off half of the image size, from 300K to 150K... (useful not only for not bloating the history but also for viewing the docs over slow connections...)
(would also squash merge to remove the previous image from the history)

**Comment by astrofrog** [comment]
@anntzer - please feel free to do this!

**Comment by anntzer** [comment]
@astrofrog I'll let you squash out the old png from the history (and check that the new one suits you -- they should be exactly identical).

**Comment by astrofrog** [comment]
@anntzer - done, thanks!

**Comment by anntzer** [comment]
Thanks!

**Pull request merged**
