### PR TITLE
DOC: update axes_demo to directly manipulate fig, ax

### PR DESCRIPTION
**Pull request by Carreau**
## PR Summary

Directly call method on each individual axis; instead of the global
``plt.`` one, same to create inset; directly refer to the figure on
which wee create an inset.

I also use some more explicit renaming for each axis,
and remove assignments on the LHS when those were unused as it seem like
a distraction on the subject at hand.

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by Carreau** [comment]
> make reference to

You mean Just refer to it in the leading text ? Or use them in the code. Can we use ":ref:" with examples ?

**Comment by Carreau** [comment]
To answer myself likely [yes](https://sphinx-gallery.github.io/advanced.html#know-your-gallery-files)

> Our namespace convention is to prefix everything with sphx_glr and change path separators with underscores. This is valid for cross-references labels, and images.

**Comment by anntzer** [comment]
Prefer :doc: to :ref:, per https://github.com/matplotlib/matplotlib/pull/11312.

**Comment by Carreau** [comment]
> Can this PR also make reference to `ax.inset_axes` and the axes grid one, just so folks have the other ways to do this automagically?

> Prefer :doc: to :ref:, per #11312.

Done.

**Comment by Carreau** [comment]
Thanks.

**Pull request merged**
