### PR TITLE
Add ridge_map to third party packages documentation

### PR DESCRIPTION
**Pull request by ColCarroll**
## PR Summary

This adds the `ridge_map` library (https://github.com/ColCarroll/ridge_map) to https://matplotlib.org/thirdpartypackages/index.html . I tried to make the example image as small as possible while still looking nice, but it still weighs 286kb. I can try some more tricks if that is too big!

Also no problem if this is a bad fit -- the other mapping libraries in here are very impressive and scientifically useful, while this is closer to an art project (which is important, but different!)

### CODE REVIEW

**Comment by QuLogic** [comment]
If you run optipng on it (no specific optimization level), you can save 40%. Also, cropping the outer white border might help a little (though perhaps not as much after optimization.)

**Comment by jklymak** [comment]
Thats a pretty cool package.  :+1: for putting it on the list.

**Comment by ColCarroll** [comment]
Thanks for advice -- you were eerily correct on how much space it saved! 

```
Output IDAT size = 173418 bytes (118839 bytes decrease)
Output file size = 173580 bytes (119260 bytes = 40.73% decrease)
```

**Comment by anntzer** [comment]
you'll want to squash the first commit too, so that the old version doesn't stay in the git history.

**Comment by QuLogic** [comment]
We can squash merge it, and I might push an even smaller image too.

Can you make a release on PyPI too?

**Comment by QuLogic** [comment]
I shrunk it down some more by simply re-creating it closer to the size it would end up being on the page (364 ~= 400 px, anyway.)

**Comment by jklymak** [comment]
That'll look pretty fuzzy on high-dpi displays.

**Comment by QuLogic** [comment]
We don't really have double-size for any other example plots.

**Comment by jklymak** [comment]
> We don't really have double-size for any other example plots.

True - it actually looks kind of bad that we don't do this.  All our figures look pretty fuzzy in our docs.

**Comment by QuLogic** [comment]
Let's handle that in a separate PR then.

**Comment by ColCarroll** [comment]
Thanks for the prompt and friendly review! Added some CI and cut a release on PyPI last night: https://pypi.org/project/ridge-map/

**Pull request merged**
