### PR TITLE
Reword subplot() doc.

### LINKED ISSUE #9740: doc infelicities on subaxes
https://matplotlib.org/2.0.1/api/pyplot_api.html#matplotlib.pyplot.subplot

sometimes writes "subaxes" and sometimes "sub-axes".  This makes it hard to search.

Also, it uses expressions like "Return a subplot axes" which is ungrammatical because "axes" is a plural noun.   I think it should be something like "Return a pair of subplot axes".

### PR DESCRIPTION
**Pull request by anntzer**
Closes #9740.
Feel free to directly push additional edits.
I intentionally replaced "typical call signature" by "call signature" for simplicity.

### CODE REVIEW

**Comment by anntzer** [comment]
The previous wording had "across rows first" which I guess is kind of ambiguous.
Reworded to "row-major order", which is perhaps a bit technical but definitely standard terminology (https://en.wikipedia.org/wiki/Row-_and_column-major_order).

**Comment by phobson** [comment]
If I'm still up when the CI finishes, I'll merge

**Comment by jklymak** [comment]
"...increasing along rows, (row-major order)."?  Small point, but I find "row-major" too jargony and ambiguous w/o looking it up

**Comment by anntzer** [comment]
What I worded as "increasing along rows" you thought should be worded "increasing along columns", which I think clearly indicates that that phrase is not well-defined...

**Comment by jklymak** [comment]
Well, I think you worded it as "across rows" which is the *opposite* of "along rows" in my mind ;-)

**Comment by anntzer** [comment]
The *previous* version also had *across*...

**Pull request merged**
