### PR TITLE
Remove uninformative entries from glossary.

### PR DESCRIPTION
**Pull request by anntzer**
Remove some entries in the glossary which are only referred to once, in
the usage tutorial (note that the usage tutorial explitictly explains
the terms "raster" and "vector" graphics just before the renderer table.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
I'm unsure about this. What is the criterion for "uninformative"? IMHO it doesn't hurt to have e.g. AGG in the glossary.

I cannot judge the real value of the glossary. It's difficult to find navigating the website and does only pop up in the search below code documentation (so is typically off-screen). OTOH why not leave it?

**Comment by anntzer** [comment]
It's not as if the current entry for AGG really provides much information.

I was thinking of starting to use the glossary to document some matplotlib-specific jargon (e.g. the anatomy of matplotlib tutorial).

**Comment by timhoffm** [comment]
> I was thinking of starting to use the glossary to document some matplotlib-specific jargon (e.g. the anatomy of matplotlib tutorial).

This is a very good idea. Something like this is really missing.

We should agree what should be contained in the glossary and what not. IMO image formats and python libraries can really go. I would still keep AGG, Cairo and FreeType for now. In particular the former two are difficult to google.

**Comment by anntzer** [comment]
feel free to push a partial revert, then.

**Comment by timhoffm** [comment]
My only contribution here is to undo some changes of the original commit. Since what goes in is only a subset of the original commit, I feel that I'm still legitimated for formal approval.

**Pull request merged**
