### PR TITLE
Delayed import of pyparsing for fontconfig pattern matching

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

This PR aims at speeding up the matplotlib import by lazily importing pyparsing. See #11546.

Essentially this has two parts:
- Move the pyparsing import into `FontconfigPatternParser.__init__` so that it's only imported when needed.
- The parser is needed to parse the rc settings. Thus it would always be instantiated and the pyparsing import would still be needed at matplotlib import time. However, at least the default rc settings do only contain very simple patterns. The PR uses a static cache of these simple patterns to prevent instantiating the full `FontConfigParser`.

This yields at least a 10% faster matplotlib import for standard settings. See the import timing in #11546.

I also did the timing myself, which I don't fully understand since the import without the modification of this PR has some additional import delay directly in the matplotlib base package. Anyway, the `rcsetup` und thus `pyparsing` have vanished as expected.

before:
image

after:
image

***Note:***
The `_SIMPLE_PATTERN_CACHE` may be expanded if you know other simple and common fontconfig patterns.

### CODE REVIEW

**Comment by QuLogic** [comment]
> I also did the timing myself, which I don't fully understand since the import without the modification of this PR has some additional import delay directly in the matplotlib base package.

If you've recently modified some files (editing or switching branches, etc.), then be careful to run the test at least twice. The first import can be slowed down by updating of the bytecode files.

**Comment by jklymak** [comment]
This looks good.   If pyparsing is such a heavy lift is there something lighter than can be imported?

**Comment by anntzer** [comment]
I'd like to ultimately get rid of fontconfig patterns altogether (#10249), but incremental improvements are fine in the meantime.
I don't think this really helps with any realistic import time though, as you'll also import mathtext (through e.g. backend_agg, or any other backend) which also imports pyparsing?  IOW you need to also delay the import in mathtext to get useful import-time benefits I think?

**Comment by tacaswell** [comment]
:+1: in principle, agree that incremental improvements are worth doing, but also agree with @anntzer that this may be un-done by the mathtext import.  It maybe better to time importing pyplot (with Agg as the backend)?

**Comment by timhoffm** [comment]
Ok, here's the import timing of 

~~~
python3.7 -X importtime -c "import matplotlib.pyplot as plt; plt.use('agg')" 2> matplotlib.log
~~~

image

As one can see, there's still no pyparsing import. Of course, this PR is "just" a 5% improvement, but it works as is.

Really wondering what the big gap in `matplotlib` is doing.

**Comment by anntzer** [comment]
I don't know why it doesn't show up in -Ximporttime output, but pyparsing is actually still being imported: this can be checked by printing out sys.modules; or one can just also check that backend_agg imports mathtext, which imports pyparsing...

**Comment by timhoffm** [comment]
Does this mean, this PR will have no effect despite the importtime results?

**Comment by anntzer** [comment]
What's exactly happening is a bit mysterious to me too, but I'm just reporting my observations...

**Comment by timhoffm** [comment]
No idea how to investigate this further.

So, either we merge this and hope that it has some effect, or we simply close the PR. Both would be fine for me.

**Comment by anntzer** [comment]
I would prefer we figure out what's happening before taking further action...

**Comment by timhoffm** [comment]
Do you have any idea what to check?

**Comment by anntzer** [comment]
nothing right now

**Comment by anntzer** [comment]
Added the needs revision tag based on the discussion above as I'm not actually convinced this works, but again I'm not really sure what's exactly happening here.

**Comment by QuLogic** [comment]
I just rebased this on `master` and tried it out, but it does not seem to have any effect on overall import time. The `rcsetup` -> `fontconfig_pattern` part of the tree is indeed faster, but the overall `matplotlib` section remains the same.

**Comment by timhoffm** [comment]
Rebased so that it's easier to look into this further.

**Comment by timhoffm** [comment]
AFAICS there are the following additional ways we import pyparsing:

- in `_check_versions()`. IMHO this could be delayed (or dropped? - we ensure at least 2.0.1, which was released in 2013).
- via the following import sequence
  ~~~
  import matplotlib.pyplot as plt
  -> import matplotlib.colorbar
  -> import matplotlib.contour as contour
  -> import matplotlib.text as text
  -> from .textpath import TextPath
  -> from matplotlib.mathtext import MathTextParser
  -> from pyparsing import (
  ~~~

**Comment by timhoffm** [comment]
I still get a significant contribution (27%) from pyparsing 3.0.6. But my dev environment is a bit older overall. Maybe I should test with a fresh setup.

grafik

OTOH, I likely won't come back to this any time soon.

**Comment by anntzer** [comment]
FTR this is what I get as of master:
tuna

**Comment by timhoffm** [comment]
Interestingly, your timings and import sequence is completely different from mine.

Did you use `python3.7 -X importtime -c "import matplotlib.pyplot as plt; plt.use('agg')" 2> matplotlib.log` like the old examples? I did.

What's more disturbing is that were now 0.1-0.2s slower overall. But execution timing is a difficult topic and I don't want to go that rabbit hole here for now.

**Pull request closed without merging**
