### PR TITLE
CI: add ppc64le to travis build matrix

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
:tada: the ppc64le tests passed out of the box!

**Comment by anntzer** [comment]
looks fine, but is there a specific reason to support this architecture? any other architectures we want to support?

**Comment by Kojoley** [comment]
I do not much about PowerPC architecture, but `le` seems to indicate that it is little endian, like x86/amd64.

> any other architectures we want to support?

I think arm64 is a must. It is popular, big endian, strict about unaligned memory access. Unfortunately there is no wheels on PyPI for NumPy, and building it from sources crashes the system-default GCC on Travis.

**Comment by tacaswell** [comment]
Debian builds on ppc64 and has reported some bugs.  I know that powerpc is used in some science contexts (ex at the ESRF) and historically everytime we have fixed a not-portable bug, it has been an actual bug that just happened to work on intel/amd.

Agree about arm and that we should wait until numpy has wheels up or travis provides it in the base image before we worry about it too much.

**Comment by QuLogic** [comment]
I guess we shouldn't bother with this now that Travis appears dead for open source.

**Pull request closed without merging**
