### PR TITLE
BUG: Fix implementation of marginals in pyplot.hexbin

### PR DESCRIPTION
**Pull request by adeak**
The existing implementation of marginal densities in `pyplot.hexbin` is such that it gives a constant 1 density (interspersed with nans) when the `C` optional keyword is not passed to `hexbin`. This PR attempts to implement the `C is None` case.

Example of the old behaviour using a simplified version [of the hexbin example](https://matplotlib.org/examples/pylab_examples/hexbin_demo.html):

```
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
n = 100000
x = np.random.standard_normal(n)
y = 2.0 + 3.0 * x + 4.0 * np.random.standard_normal(n)

fig, axs = plt.subplots(ncols=2)
ax = axs[0]
hb = ax.hexbin(x, y, gridsize=50, cmap='inferno')
#ax.axis([xmin, xmax, ymin, ymax])
cb = fig.colorbar(hb, ax=ax)
cb.set_label('counts')

ax = axs[1]
hb = ax.hexbin(x, y, gridsize=50, cmap='inferno', marginals=True)
#ax.axis([xmin, xmax, ymin, ymax])
cb = fig.colorbar(hb, ax=ax)
cb.set_label('counts')

plt.show()
```

The left subplot shows only the histogram with automatic limits, the right subplot adds the marginal densities. The current implementation produces the following figure:
hexbin_bug_original

Note the black bands (with a short white stripe each) that appear on the right plot: those are the buggy marginals. The bug is that the bands are all black (corresponding to `count == 1`), but the white stripes (due to `nan`s) are also suboptimal in the context of marginal densities.

The bugfix in this PR produces the following figure:
hexbin_bug_properfix

Notes concerning the implementation:
 - the new `C is None` case still uses the raw inputs
 - the marginal densities are rescaled such that their maximum is equal to the maximum of the 2d histogram; this is necessary to have a reasonable color mapping for the marginals
 - zeros are kept as zeros (rather than `nan`s) in the marginal densities when there are no data points in a given marginal bin
 - implemented missing logarithmic bin scaling
 - the only change in the `C is not None` case should be the aforementioned logarithmic scaling

There are some additional minor style edits that I made along the way, namely using `0.0` float literals consistently, renaming the arguments of an auxiliary function from `y` to `C` for clarity, and skipping irrelevant steps for `nan` density points in the loops during marginal setup.

### CODE REVIEW

**Comment by adeak** [comment]
I'm not sure whether I should open an issue for the bug. It would probably only be useful if anyone ran into the same bug before a fix was out in a new release, but the git blame suggests that this bug has been around since 2009.

**Comment by dstansby** [comment]
This looks like a nice fix! We should probably add an image test to check that marginals are working. Do you think you could add your example to `lib/matplotlib/tests/test_axes.py`?

**Comment by adeak** [comment]
@dstansby thanks. I don't have any testing experience (planning to learn), but I think I'll be able to add a test along the lines of the existing hexbin ones. I'll let you know if I have any difficulties.

**Comment by adeak** [comment]
@dstansby I'm not sure you get a notification for commits to PRs, so: I added the test. Codecov seems much happier too. Please let me know if anything's off.

**Comment by tacaswell** [comment]
I keep saying that there are PRs / bug reports to which my first reaction is "wait, the library does what?", this is one of them :stuck_out_tongue_winking_eye: 

I'm not a huge fan of re-scaling the marginals as it looks ok, but is wrong as the color it maps to is in almost all cases too low of a value.  On the other hand, the current behavior is also broken and the proposed behavior is less wrong.  Could you add a note to the docstring warning about this?

I think that this use case is better handled by have 2 parasite axes that show lines of the marginals rather than shoe horning it into the image.

**Comment by jklymak** [comment]
Yeah, I strongly agree w/ @tacaswell.  a) these "marginals" deserve their own axis, and b) I'd think a line would be much more appropriate.  As plotted, the logical expectation is that they are keyed to the colorbar that is shown, but that is likely not the case.  I think this would get a rough ride in most scientific publications, but maybe there is a community out there who would use it regularly enough that they don't mind...

**Comment by adeak** [comment]
Thanks @tacaswell and @jklymak for the feedback! I perfectly agree with you, it just hadn't crossed my mind to touch the basic functionality beyond fixing the bug:)

I believe the problem stems from the unhandled `C is None` case. When `C` is provided and we're averaging `C` values (rather than counting bin hits) by default, the marginals fully correspond to the main histogram values, so everything's meaningful. However, when we're actually computing a histogram in the classical sense the 2d histogram is in "count" units while the marginals are in "1/bin" units, so to speak, so there's no way to represent both in a scientifically accurate way in the same axes. My notion was that the marginals are mainly guides to the eye.

I'm all for making good use of this functionality rather than making it only _less broken_ and putting signposts in the docs. I have two questions:

1. We should always use separate axes for the marginals for consistency, right? Even for the `C is not None` case, which would probably be prettier/clearer in the current implementation (as long as the accumulating function is the default `np.mean`).
2. Should I close this PR and submit a new one when it's ready? That's what seems straightforward to me now.

**Comment by tacaswell** [comment]
If this behavior makes sense in the `C is not None` case, then we should not _break_ it.  I propose the following:

 - raise an error if marginals are asked for in the `C is None` case (sorry, this junks the work you have done :disappointed: )
 - add an example like adds the marginals on new axes (like http://pythagon.blogspot.com/2013/11/slicing-and-histogramming.html) .

One API problem that this touches on is that to do this 'right' we need to add artists to more than one Axes object which is a case where our abstractions break down a bit....

**Comment by jklymak** [comment]
First, sorry if that sounded negative about the PR.  I was speaking in general about the idea of additions to axes artists like this kwarg to `hexbin` supplies.   I think the bug fix is OK for backwards compatibility, though I haven't tested it. 

I don't think you need new `hexbin` functionality to do this "properly".  

```python

gs = GridSpec(2, 2, width_ratio=[1., 6.], height_ratio=[6., 1.])
ax = fig.add_subplot(gs[0,0])
ax.plot(Data.sum(axis=1), y)
ax = fig.add_subplot(gs[1,1])
ax.plot(x, sum.sum(axis=0))
ax = fig.add_subplots(gs[0, 1])
ax.hexbin(x, y, Data)
```

basically does what you want, plus or minus whatever indexing issues I haven't checked carefully, and any changes to padding and labelling you'd want.  If you wanted to wrap this in a one-call function or method to `figure` that would likely be OK, though frankly I think that the use cases for the above are so varied that most folks would want to do it themselves manually.

**Comment by adeak** [comment]
@tacaswell I believe that the `C is not None` case indeed makes sense most of the time (see also  [hexbin_demo2](http://matplotlib.org/2.0.0b2/examples/pylab_examples/hexbin_demo2.html)). You're right that this case shouldn't be broken. So going forward with your suggestion we should basically disable the broken `C is None` case altogether. I guess a remark along these lines should also be added to the documentation of `hexbin`. Adding an example instead is a good compromise, also in line with @jklymak's note about variability in use cases. While I _think_ I understand your remark concerning the API problem, even if "doing it right" would be on the table it would probably be too big of a fish for me :)

@jklymak it did sound negative, but only as much as it needed to. I'm not a fan of sugarcoating in technical matters ;)

Considering how the course of action is completely different from the original intent, I think I should close this PR and refer back to it in a new one that handles the above points (unless told otherwise).

**Comment by jklymak** [comment]
I'm closing as per @adeak 's comment above.  Sorry for the churn @adeak!  If you wanted to work more on implimenting marginals, please do submit a PR, or re-open this one....

**Pull request closed without merging**
