### PR TITLE
ci: Enable testing on Python 3.13

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

It works locally mostly, but let's see how things go on CI.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
Surprised that the only failures are a couple minor RMS differences. I wonder if the contour-related tests are because we end up building `contourpy` from source and use some slightly different options than the release wheels somehow. We also end up building `numpy` from source as well. I might trying pull those from nightly temporarily.

**Comment by QuLogic** [comment]
Ah, I should have checked which tests first; those all have some increased tolerance on `aarch64`, so just added `arm64` as well to catch Apple Cilison.

**Review by oscargus — APPROVED** [review]

**Comment by neutrinoceros** [comment]
> Surprised that the only failures are a couple minor RMS differences on one platform only.

Looks suprising at first given the documentation explicitly states that matplotlib isn't thread safe https://matplotlib.org/stable/users/faq.html#work-with-threads
... but if there are no tests *exercising* multi-threading, it is maybe not so surprising.

From my downstream point of view, it is still desirable that matplotlib be tested on 3.13t, even with no specific tests, but it will take more work to properly define which use cases are to be supported (thread-safe) and which are not.

To anyone this may interest, I recommend reading through https://py-free-threading.github.io/

**Comment by QuLogic** [comment]
> > Surprised that the only failures are a couple minor RMS differences on one platform only.
> 
> Looks suprising at first given the documentation explicitly states that matplotlib isn't thread safe https://matplotlib.org/stable/users/faq.html#work-with-threads ... but if there are no tests _exercising_ multi-threading, it is maybe not so surprising.

Those were failures on 3.13, not 3.13t, so threads are unrelated.

**Comment by neutrinoceros** [comment]
Ow. My bad ! I don't know why I thought matplotlib was already testing (regular) 3.13. Don't mind me 😅

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
What is not thread safe is updating the same figure from multiple threads (e.g. updating data in one and drawing in another) because, even with the GIL the methods are not atomic and artists can be in invalid states before the methods return.

However, because we do already drop the GIL in a bunch of places in the extension code we already have low-level locks on the non-Python global state (which is the main thing that the GIL could have been protecting you from because) so I expect that already-thread-safe usage we will continue to be safe with free threading.

**Review by timhoffm — APPROVED** [review]

**Comment by QuLogic** [comment]
@backport to v3.9.x

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.9.x

**Pull request merged**
