### PR TITLE
DOC: fix radial increase of size & OO style in polar_scatter_demo

### LINKED ISSUE #6687: Small issues with the example `polar_scatter_demo.py`
_mpl v2.x_

In the example [polar_scatter_demo.py](http://matplotlib.org/devdocs/examples/pie_and_polar_charts/polar_scatter_demo.html), I guess that the line
```python
area = 200 * r**2 * np.random.rand(N)
```
should be
```python
area = 200 * r**2
```
to be consistent with the header docstring which states “Size increases radially…”.

Besides, if I understood correctly, one wants to promote the OO style in the examples. If it's correct, shouldn't `plt.scatter` be replaced with `ax.scatter`?

### PR DESCRIPTION
**Pull request by afvincent**
Should fix #6687

I also tweaked the header docstring to wrap it slightly before col. 79.

### CODE REVIEW

**Comment by afvincent** [comment]
Additional question because I've seen both in the example gallery: when using a colormap in an example, is it preferred to simply call `plt.cm.*colormap_name*` or to first `import matplotlib.cm as cm` and then call the colormap where it is needed with `cm.*colormap_name*`?

**Comment by NelleV** [comment]
Both are fine. I have a slight preference for the latter, but it is personal.
Thanks for the patch!

**Comment by afvincent** [comment]
@NelleV Thank you for the explanations about calling a colormap.

**Comment by QuLogic** [comment]
Backported to v2.x via 70b851fef0ca4044c16f2802090a2a1c1f059f01.

**Pull request merged**
