### PR TITLE
Cleanup clang warnings

### PR DESCRIPTION
**Pull request by jenshnielsen**
This fixes a bunch of warnings that I am seeing with clang on OSX 10.11

@mdboom Some of these seems to be in the code from the new image rewrite

### CODE REVIEW

**Comment by QuLogic** [comment]
I noticed these as well and was planning to fix them, but I think for 32/64-bit compatibility, you should use [NumPy's macros](https://docs.scipy.org/doc/numpy/reference/c-api.dtype.html#printf-formatting) instead of the hard-coded format specifiers.

**Comment by mdboom** [comment]
Looks good.  I agree with @QuLogic: I didn't know about numpy's macros for this, but they seem like a good thing to use.

**Comment by jenshnielsen** [comment]
@QuLogic Good point about the Numpy macros. I have updated to use those.

**Comment by tacaswell** [comment]
@jenshnielsen This needs a rebase.

**Pull request merged**
