### PR TITLE
Add codespaces configuration

### PR DESCRIPTION
**Pull request by melissawm**
## PR summary

This pull request adds a [GitHub codespaces](https://docs.github.com/en/codespaces) configuration for Matplotlib. With this PR, contributors can open a pre-configured development environment and get started with contributing to Matplotlib right away from their browser. I'm not sure if you can test it as it is, as I believe this needs to be merged to main before anyone is able to open a codespace from the Matplotlib repo.

Once this is merged, it will enable users to go to matplotlib/matplotlib or their own fork and choose "Create codespaces on `<branch>`":
Screenshot_20230616_155713

This will open a browser window with a VSCode interface and a pre installed development environment built over an Ubuntu image. Users can then do

```
$ conda activate mpl-dev
$ python -m pip install -e .
```

After that you can run tests, build the documentation and run other commands.

This configuration also includes a [lightweight fluxbox environment](https://github.com/devcontainers/features/tree/main/src/desktop-lite)

To be done in a follow-up: documentation on how to use it and current features (like connecting to the fluxbox desktop to see plots).

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by melissawm** [comment]
Argh, sorry I've messed up the labels.

**Comment by jklymak** [comment]
I'd be happy to merge just so you can make progress testing it in situ, with the understanding you will keep an eye on it and field questions in the unlikely event someone jumps on this before it's fully baked.

**Comment by melissawm** [comment]
That's the plan, I'd also like to get some feedback from potential users on the configuration and I'll be also drafting the docs in the meantime.

**Review by jklymak — APPROVED** [review]

**Comment by tacaswell** [comment]
This is mind-blowingly good!

How to getflux box up needs a bit of documentation.

If we can not auto-activate the right conda env, we should drop a `/etc/issue` to print out instructions to do that (and a link to fluxbox docs).

Lets see if I can do this from inside a codespace....

**Pull request merged**
