### PR TITLE
Fix incorrect window_extent of AxesImage

### PR DESCRIPTION
**Pull request by leejjoon**
## PR Summary

`AxesImage` can take a transform parameter. However,  `AxesImage.get_window_extent` does not respect its value and simply use the hardcoded value of `transData` (the `draw` method does respect the transform parameter).
The PR makes the `get_window_extent` method to use the return value of `get_transfrom`.

## PR Checklist

**Documentation and Tests**
- [N/A] Has pytest style unit tests (and `pytest` passes)
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] New plotting related features are documented with examples.

**Release Notes**
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by oscargus** [comment]
Would be good to have a test to make sure that this is not broken later.

**Comment by tacaswell** [comment]
👍🏻 to this fix and to the request for a test.

**Comment by leejjoon** [comment]
I have added a simple test in `test_image.py::test_get_window_extent_for_AxisImage`. The test is only for `transAxes`.
Any suggestion for other tests?

**Review by oscargus — APPROVED** [review]
There may be more tests, but I think that this is enough (and/or I do not really know what else to test...).

**Pull request merged**
