### PR TITLE
bug fix - set_facecolors not working for 3D scatter

### PR DESCRIPTION
**Pull request by xiaoshiqi**
## PR Summary
fixed set_facecolor(set_facecolors), set_edgecolor(set_edgecolors), and set_color not working for scatter patch in 3D #9725
_facecolor3d, _edgecolor3d should be updated alone with color changes.
## PR Checklist

- [X] Has Pytest style unit tests
- [X] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by phobson** [comment]
@xiaoshiqi thanks for the patch! I think this will be a very useful addition. Could you add a test that confirms that this works as expected? 

I'm not sure if you need to make a full-on image comparison test for this, but a test should at least create a 3D artist with a certain face and edge color, set them to something different, and the confirm that the changes stick as a expected.

The mplot3d tests are here:
https://github.com/matplotlib/matplotlib/blob/master/lib/mpl_toolkits/tests/test_mplot3d.py

**Comment by xiaoshiqi** [comment]
no problem, I will work on it asap

**Comment by WeatherGod** [comment]
I am not quite understanding the code design here. Why wasn't this added to the Patch3DCollection class directly?

**Comment by xiaoshiqi** [comment]
@WeatherGod I'm afraid that other artists may be affected if I modify Patch3DCollection.

**Comment by xiaoshiqi** [comment]
@WeatherGod I have attempted another fix. Could you please review this?
I have not yet push the test cases, currently I am having a little issue with image comparison RMS != 0
Will push them soon once I fix the image comparison tests.

**Comment by xiaoshiqi** [comment]
@WeatherGod it's now fixed

**Comment by WeatherGod** [comment]
why is this closed? did another PR fix the problem? Sorry I have been quiet lately, multiple snowstorms and sicknesses have eaten up my free time.

**Comment by xiaoshiqi** [comment]
@WeatherGod I'm sorry, I thought this PR is rejected, so I started another one #10797

**Comment by WeatherGod** [comment]
sorry for that impression. sometimes responses get a little slow around
here. I'll review your other PR tomorrow.

**Comment by xiaoshiqi** [comment]
@WeatherGod thanks

**Pull request closed without merging**
