### PR TITLE
API: only shrink hist bars if not stacked

### PR DESCRIPTION
**Pull request by tacaswell**
Partially addresses #6876 

so

```python
from matplotlib import pyplot as plt

x1 = [ 0.1, 0.2, 0.3, 0.5, 0.75, 1.1, 1.5, 1.9, 2.5, 2.9 ]
x2 = list(x1)
x2.extend([ 1.75, 1.8, 2.2, 2.4, 2.7, 2.8 ])

x1.extend([ -x for x in x1 ])
x2.extend([ -x for x in x2 ])

print("unstacked datasets, explicit bin sequence:")
plt.subplot(221)
plt.minorticks_on()
n, bins, patches = plt.hist([x1, x2], bins=[-3,-2,-1,0,1,2,3])
print("bins: ({}, {})".format(min(bins), max(bins)))
print("datalim: {}".format(plt.gca().dataLim))
print()

print("unstacked datasets, automatic bins:")
plt.subplot(222)
plt.minorticks_on()
n, bins, patches = plt.hist([x1, x2])
print("bins: ({}, {})".format(min(bins), max(bins)))
print("datalim: {}".format(plt.gca().dataLim))
print()

print("stacked datasets, explicit bin sequence:")
plt.subplot(223)
plt.minorticks_on()
n, bins, patches = plt.hist([x1,x2], bins=[-3,-2,-1,0,1,2,3], stacked=True)
print("bins: ({}, {})".format(min(bins), max(bins)))
print("datalim: {}".format(plt.gca().dataLim))
print()

print("stacked datasets, automatic bins:")
plt.subplot(224)
plt.minorticks_on()
n, bins, patches = plt.hist([x1,x2], stacked=True)
print("bins: ({}, {})".format(min(bins), max(bins)))
print("datalim: {}".format(plt.gca().dataLim))

```

### CODE REVIEW

**Comment by QuLogic** [comment]
Is it just me, or is the first bar a half-pixel off compared with the rest?

**Comment by tacaswell** [comment]
@QuLogic it is not just you :disappointed:

**Comment by jenshnielsen** [comment]
The fix in 9a6ec8f should close also close #4212 and 4602 in addition to #6959

**Comment by jenshnielsen** [comment]
Unfortunatly a lot of tests now need to be regenerated

**Pull request merged**
