### PR TITLE
Add washing machine to Axes3D

### PR DESCRIPTION
**Pull request by r-barnes**
## PR Summary

Seeing the structure of 3D plots can be challenging if the plots are stationary. This PR adds a "washing machine" perturbation that gently and continuously moves the 3D axes to help reveal the 3d structure of the data.

A movie of this in action is [here](https://rbarnes.org/misc/washing_machine.mkv) (pause the video to see the difficulty of interpreting the data sans the animation) and a gif is [here](https://imgur.com/a/O8TgkhX).

The animation is toggled by pressing the "z" key.

This PR doesn't (yet!) include all the features of a good PR as I expect there might be some discussion regarding how best to execute this feature.

Note that the motion could also be made smoother and I haven't figured out how to pin the motion to, say, the back corner of the axes, which might provide better depth cues than the current motion which, I think, is pinned more to the center of the axes cube.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by story645** [comment]
Hi, any chance you can convert the movie into a gif that you can then post here?  At least on my phone, the link redirects to a download.

**Comment by r-barnes** [comment]
Sure, @story645.

Still image:

Still image

With the washing machine:

Washing machine effect

Also available [here](https://imgur.com/a/O8TgkhX).

**Comment by r-barnes** [comment]
Some studies relating motion to 3D data comprehension are [here](https://ccom.unh.edu/sites/default/files/publications/Ware_1996_TOG_Evaluating_stereo_motion_cues_visualizing_info_nets_in_3D.pdf) and [here](https://www.researchgate.net/publication/221282979_Reevaluating_stereo_and_motion_cues_for_visualizing_graphs_in_three_dimensions). I'm looking for others.

**Comment by timhoffm** [comment]
I like the idea of adding motion to help understand 3D information. Some comments/suggestions/information:

- Our current 3D camera view model is limited to the degrees azimuth and elevation, which are aound the center of the view. You cannot rotate around a back-corner.
- More generally, this could be any closed path in the (azimuth, elevation)-space; e.g. I imagine that full azimuth rotation can also be quite desireable.
- A similar effect can be achieved with animations (see example below). Compared to the current approach this has the advantage that (i) you can also save the animation to file (ii) you can use it in juypyter notebooks. On the downside, AFAIK we currently don't have a way to pause animations in a GUI window, but that could be added.
- I'm not clear if this needs additional API or if an example would be enough.

### Example with animation:
```
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np


# Fixing random state for reproducibility
np.random.seed(19680801)


def random_walk(length):
    start_pos = np.random.random(3)
    steps = np.random.uniform(-0.05, 0.05, size=(length, 3))
    walk = start_pos + np.cumsum(steps, axis=0)
    return walk
    

def update_view(frame):
    azim = frame * (360/72)
    ax.view_init(azim=azim)


fig = plt.figure()
ax = fig.add_subplot(projection="3d")

for _ in range(50):
    ax.plot(*random_walk(25).T)

ax.set(xlim3d=(0, 1), ylim3d=(0, 1), zlim3d=(0, 1))

ani = animation.FuncAnimation(
    fig, update_view, 72, interval=50)
plt.show()
```

Use `anim.save('test.gif')` for saving instead or for embedding into jupyter notebooks:
```
from IPython.display import HTML
HTML(ani.to_jshtml(fps=20))
```

For illustration: (The written gif still has a clipping problem, that's not present in the other output formats, but that's an unrelated issue)
test

**Comment by r-barnes** [comment]
Thanks, @timhoffm .

> More generally, this could be any closed path in the (azimuth, elevation)-space

In the push I just made, I've switched to using a sin-cos combo which I think produces a nicer view.

> A similar effect can be achieved with animations (see example below).

I've seen that; thank you for providing an example. The downside to relying solely on the existing animation framework is that you have to either have an example bookmarked or type everything out each time you need this. Having it built in means I can create 3d plots for quick analysis without having to think too much about this aspect of visualization. Later, if I wanted something smoother or reproducible, I would build an animation. So I think there are distinct use cases here.

**Comment by timhoffm** [comment]
We could certainly come up with an API that does not need much typing, e.g. `ax.animate_view('washingmachine')` / `ax.animate_view('azim_rotation')`.

Or with more degrees of freedom: `ax.animate_view(ViewAnimation(elev=30, azim=np.arange(0, 360, 73), interval=100))`

**Comment by r-barnes** [comment]
But, if I understand correctly, the animation approach you propose would run continuously in a way that would prevent or interfere with a user doing custom zooms, rotations, or freezes?

**Comment by anntzer** [comment]
@timhoffm Side point: I can't repro the gif clipping failure, but do you want to open a separate issue for that?

**Comment by tacaswell** [comment]
:+1: This is a cool idea!

**Comment by r-barnes** [comment]
I've moved the rotation keys to "z" and "x". "z" does a washing machine and "x" performs a continuous azimuthal rotation.

**Comment by jklymak** [comment]
@r-barnes We discussed this one on the dev call this week.  For now, we think this would be best as a third-party package.  We are updating our third party package page, but in the meantime you would be welcome to link you package on our third-party page.

Thanks for the cool idea!

**Comment by jklymak** [comment]
BTW the third-party page is https://github.com/matplotlib/mpl-third-party.  Thanks for the interesting idea!

**Pull request closed without merging**
