### PR TITLE
Text rotation patch

### PR DESCRIPTION
**Pull request by Alex-Carter01**
## PR Summary
Resolves issue #13044. Fixing calculation error of Y-offset for specific rotation mode of text. This pull also includes a proposed minimal test (based off the original bug report).

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks a lot for the pull request!  Unfortunately this broke some existing tests in `test_text.py`, so this isn't compatible with the existing behaviour.  So you will either have to change the old tests and argue that they were wrong, or modify this....

**Comment by story645** [comment]
hey @Alex-Carter01, do you have any bandwidth to finish up this PR?

**Comment by WeatherGod** [comment]
Oh, and we should double-check with the Cairo renderer, although I suspect it might have the same bug if this is happening at a layer above AGG/Cairo?

**Comment by dstansby** [comment]
Thanks for opening this PR. Unfortunately I don't think this is the correct fix. `ymax1 - baseline / 2.0` seems to be the correct logic, putting the offset halfway between the baseline and ymax, so I think subtracting ymin1 is incorrect. As such I'm going to close this PR - if I've missed something feel free to comment and I will open it up again, and thanks again for the contribution.

**Pull request closed without merging**
