### PR TITLE
add __repr__ to GridSpecBase

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

While playing around with gridspecs I found it convenient to have the repr of GridSpec show the number of columns and rows.

### CODE REVIEW

**Comment by jklymak** [comment]
`test_interactive_backend[qt5agg]` seems to be throwing a fit.  Also there is a PEP8 error in `gridspec.py`, though I don't see that this PR added that...  Mysterious!

**Comment by timhoffm** [comment]
@jklymak Since the string is quite short, it's ok to put it in `__repr__`.

**Comment by timhoffm** [comment]
@anntzer I was just too lazy :smile: . But you are right, if we write make the repr an `eval`-able expression, it should be complete. Done.

**Comment by anntzer** [comment]
anyone can merge after CI

**Pull request merged**
