### PR TITLE
[WIP] Add the ability for unit converters to convert back to data with units

### PR DESCRIPTION
**Pull request by dstansby**
Inspired by #7462, and not-so-recent units discussions on the mailing list, I have made a minimal implementation of having an `un_convert` method for `ConversionInterface` classes. The benifit of this is that Matplotlib can re-convert from "axis coordinates" to "data/unit coordinates", and return data with units. This is particularly useful for things like `ginput`.

I will write this up more in the future, but for to keep a paper trail this is a pre-requisite for a `accepts_units` decorator (see https://github.com/matplotlib/matplotlib/pull/10411 for an attempt at this) that would automatically catch issues such as https://github.com/matplotlib/matplotlib/issues/15332 ,

### CODE REVIEW

**Comment by dstansby** [comment]
Can you give an example of the different date units?

The way I've set it up, doing how the back-conversion is done is entirely up to the implementation of the `ConversionInterface`. If needed, what is returned can depend on the `units` attribute of the axis, which can change from e.g. `m` to `cm`.

Although that is potentially a good idea, it doesn't cover cases where the conversion back is not being done on a data point, e.g. `xlim`/`ylim` are almost never the same as an actual data point passed in.

**Comment by jklymak** [comment]
The date converter will accept `datetime.datetime`, `datetime.date` and `numpy.datetime64` right now. If we convert to ordinal (days since epoch) as we do now, how will we know the correct inversion?  Practically this could have an effect if the user overrides the datetime64 conversion, but not the datetime.datetime, and converts, but then the inversion puts the date back in datetime units.  

More to the point, if we change the units of the axis, inverting and then re-converting is not garaunteed to be correct if we don't get the original data. 

I'm not sure I follow the xlim/ylim issue.  I don't see any reason xlim/ylim can't be wrapped in the same way as other data.

**Comment by dstansby** [comment]
That makes sense; we can just make different copies of each `ConversionInterface`, that inherit everything from a `DateConverter`, but just have different methods to convert the units back.

**Comment by dstansby** [comment]
Still needs:

- API changes (or what's new?)
- Separate un-converters for each of the date types

**Comment by jklymak** [comment]
@dstansby, I think this should be discussed more before more work is done.  As I understand it, the plan for 4.0 is to have a new way of carrying the data around inside Matplotlib.  That may be a pipe dream, in which case something like this may be a good half measure, but we should make sure this fits in the roadmap?  @dopplershift @tacaswell were particularly interested in better units support.

**Comment by dstansby** [comment]
Thanks for pointing that out - is there a roadmap for 4.0 or anything written down anywhere about the changes to data-carrying? Either way I'm kind of happy to carry on playing with this and writing it up on a zero-merge-expectation basis.

**Comment by jklymak** [comment]
That seems reasonable.  There is a paper document.  https://paper.dropbox.com/doc/Matplotlib-4.0-WTYwd0NQaSHTjtLUZwkNx

**Comment by dstansby** [comment]
I think there's another version of this kicking around somewhere, and it's clear that something like this needs some more careful thought and design, so I'm going to close this.

**Pull request closed without merging**
