### PR TITLE
TST: Fix tests with older versions of ipython

### LINKED ISSUE #28202: [Bug]: Qt test_ipython fails on older ipython
### Bug summary

I have an older conda environment with ipython 8.8.0, and this test seems to be failing. Also when building on Fedora Rawhide with ipython 8.24.0, I see the failure as well. I'm not sure why this passes (but fails with my environments) with the minimum versions in CI.

cc @ianthomas23 

### Code for reproduction

```Python
$ pytest lib/matplotlib/tests/test_backend_qt.py::test_ipython
```

### Actual outcome
```
________ test_ipython ________

    def test_ipython():
        from matplotlib.testing import ipython_in_subprocess
>       ipython_in_subprocess("qt", "QtAgg", "qtagg")

lib/matplotlib/tests/test_backend_qt.py:381: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

requested_backend_or_gui_framework = 'qt', expected_backend_old_ipython = 'QtAgg', expected_backend_new_ipython = 'qtagg'

    def ipython_in_subprocess(
        requested_backend_or_gui_framework,
        expected_backend_old_ipython,  # IPython < 8.24
        expected_backend_new_ipython,  # IPython >= 8.24
    ):
        import pytest
        IPython = pytest.importorskip("IPython")
    
        if sys.platform == "win32":
            pytest.skip("Cannot change backend running IPython in subprocess on Windows")
    
        if (IPython.version_info[:3] == (8, 24, 0) and
                requested_backend_or_gui_framework == "osx"):
            pytest.skip("Bug using macosx backend in IPython 8.24.0 fixed in 8.24.1")
    
        if IPython.version_info[:2] >= (8, 24):
            expected_backend = expected_backend_new_ipython
        else:
            # This code can be removed when Python 3.12, the latest version supported by
            # IPython < 8.24, reaches end-of-life in late 2028.
            expected_backend = expected_backend_old_ipython
    
        code = ("import matplotlib as mpl, matplotlib.pyplot as plt;"
                "fig, ax=plt.subplots(); ax.plot([1, 3, 2]); mpl.get_backend()")
        proc = subprocess_run_for_testing(
            [
                "ipython",
                "--no-simple-prompt",
                f"--matplotlib={requested_backend_or_gui_framework}",
                "-c", code,
            ],
            check=True,
            capture_output=True,
        )
    
>       assert proc.stdout.strip() == f"Out[1]: '{expected_backend}'"
E       AssertionError

lib/matplotlib/testing/__init__.py:217: AssertionError
```

### Expected outcome

The test passes.

### Additional information

If I print out the `proc.stdout`, then I get `Out[1]: 'Qt5Agg'`; the test appears to be looking for 'qtagg', instead?

### Operating system

Fedora 39/Rawhide

### Matplotlib Version

main (3ee509d14f5a624f1d99c3a1727810e9c4989258)

### Installation

git checkout

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

I only went back as far as 7.0.0, as due to #16263, we probably don't want to be supporting all the way back to IPython 1.

I believe that this only affected the test, as on IPython <8.24, we use the code from IPython anyway. But I've pinned the tests to IPython 7 so we should see if everything's good.

Closes #28202

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, perhaps IPython 7.0.0 is a bit too old for Python 3.9 which was release Oct 5, 2020. Based on release dates, it seems like we should aim for _at least_ IPython 7.19, released Oct 30, 2020?

**Comment by ianthomas23** [comment]
Thanks for doing this, I didn't look very far back when I added these tests.

Locally I've tried this branch on Python 3.9 on a mac (to run both the `qt` and `osx` tests) with progressively older ipython, and it works (as in the tests pass) for ipython >= 7.3.0 but fails for ipython < 7.3.0. Ipython 7.3.0 was released in February 2019 so pre-dates Python 3.9 by a good year and a half but still seems to work with it. So officially covering >= 7.19 seems good to me as it is rule-based on the Python 3.9 release date.

**Review by ianthomas23 — APPROVED** [review]
I'm approving as is but it would good to include the `endswith` change even though that line isn't yet changed by this PR and is only a problem when running tests locally rather than in CI.

For the failing `test_backend_inline.py::test_ipynb` I would be inclined just to skip the test on Python 3.9. It relies on some of the Jupyter infrastructure working with a combination of old and new packages, and I don't think we should spend any time chasing that down when we have proved that IPython is OK here.

**Comment by QuLogic** [comment]
Err, that was a bit premature as tests weren't passing yet.

**Comment by tacaswell** [comment]
🤦🏻 Sorry, I only saw the coverage failure and missed the real failure.

**Pull request merged**
