### PR TITLE
round to nearest integer

### PR DESCRIPTION
**Pull request by Wlodarski**
https://github.com/matplotlib/matplotlib/issues/16631

## PR Summary

Solution for https://github.com/matplotlib/matplotlib/issues/16631

### CODE REVIEW

**Comment by jklymak** [comment]
The test failures are real, so you will have to reconcile what the tests think the right answer is with what you think it is.  Also, if possible, please improve the description of the PR above!

**Comment by Wlodarski** [comment]
Sorry but I don't understand what you, @jklymak , are expecting from me. I explained the bug. You agreed it's a bug. I proposed the solution. You asked my to create a pull request. I did one. Now you are complaining it's not enough!? 

A value (``i`` in ``IndexFormatter.___call___``) was **truncated instead of being rounded** as expected. I changed line 325, in ticker.py, ``i = int(x + 0.5)`` for `` i = int(round(x))``.

**Comment by jklymak** [comment]
When we submit a PR, our test suite is run on the PR, and those tests have to pass.  If the tests have a bug in them, then that needs to be fixed.  If the tests are correct, then our understanding of the solution is incorrect, and we need to reconsider.

**Comment by Wlodarski** [comment]
Corrected the test and submitted a new pull request : https://github.com/matplotlib/matplotlib/pull/16634 

Still failing the tests. From my limited understanding, they seem to complain the bug is not present anymore. 

This is too much hassle for a beginner like me. I regret submitting a solution.

**Comment by timhoffm** [comment]
@Wlodarski sorry for your inconvenience.

As you see from the discussion in #16634, this is somewhat complicated. Even for core developers, sometimes not all implications of a change are obvious. And we may encourage to provide a what we think simple fix, even though it turns out it is not that simple in the end.

This is certainly not by intention. We only encourage new people contributing when we think the PR is easily managable. But sometimes we fail in our judgement.

**Pull request closed without merging**
