### PR TITLE
TST: make E402 a universal flake8 ignore

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

#11613 made flake8 exceptions explicit, but the whole examples directory was ignoring E402 before via a glob.

This PR makes E402 ignored everywhere...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
As noted in https://github.com/matplotlib/matplotlib/pull/11613#issuecomment-403957732, I'd prefer if we leave these and `# noqa` any new References sections. And ideally, sphinx-gallery would do it all for us.

**Comment by jklymak** [comment]
Note https://github.com/sphinx-gallery/sphinx-gallery/issues/205

**Comment by ImportanceOfBeingErnest** [comment]
Just a more general view here: I think examples are meant to teach how to acomplish something with the library at hand. They do not need to be PEP8 compatible. Of course one should not teach bad style, but the reason for E402 does not really apply to any examples anyways. For the sake of understandability, it might make perfect sense to import certrain things late in an example or a tutorial, close to the place where it is actually needed, such that the reader does not need to scroll all the way up to a place where all imports live.

**Comment by tacaswell** [comment]
Is there a way to over-lapping constraints like that?

I like @ImportanceOfBeingErnest 's suggestion that we only skip this test on the examples.

**Comment by jklymak** [comment]
Thats how it was before #11613, but @QuLogic doesn't like the globs....

**Comment by jklymak** [comment]
BTW< I don't care about this PR at all - please set up flake8 the way you'd like it.  I just use it from the command line so however experts want it set up is fine w/ me...

**Pull request closed without merging**
