### PR TITLE
Raise minimum WX version to 2.9.

### PR DESCRIPTION
**Pull request by anntzer**
2.9 was released in 2010; in fact, *before*
2.8.12 (the previous min version), see
https://github.com/wxWidgets/wxPython/releases?after=wxPy-2.9.2.1

Remove some conditional code.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
There are also a bunch of version checks in `examples/user_interface/embedding_in_wx*.py` that should probably just be removed.

**Comment by anntzer** [comment]
done, if I understood your suggestion correctly.

**Comment by dstansby** [comment]
Does this need a note in what's new? (happy for someone to decide not and merge!)

**Comment by tacaswell** [comment]
@dstansby I think updating the install docs is enough here.

**Pull request merged**
