### PR TITLE
partial fix for issue #7712

### PR DESCRIPTION
**Pull request by ParagBh**
Partial fix for issue #7712 where text was overlapping due to too many ticks so I reduced the default number of ticks which takes care of the overlapping issue. Also added an automated testcase under test_dates.py. I have also never contributed ever to an open source project so if I did something wrong please let me know.

### CODE REVIEW

**Comment by tacaswell** [comment]
This is an API change (as the output images for identical input changes), but that does not immediately rule it out.  If we do make this change it will need an entry in https://github.com/matplotlib/matplotlib/tree/master/doc/api/api_changes 

We apparently have some tests that exercise this code path 😺 .  We either need to re-generate those tests or make this an rcparam we can patch over in the tests.

How did you pick these numbers?

Tagged a 2.0.1 as it is a style change and we are already planning to ship a number of other small style changes for 2.0.1.

**Comment by ParagBh** [comment]
@tacaswell 

When playing around for the numbers for DAILY, I realized that the datetime values start overlapping when there are 7 or more ticks so I simply reduced it to 6. I did something similar for MONTHLY.

**Comment by tacaswell** [comment]
@ParagBh Are you still interested in working on this?

I am nominally :+1: on this, but a number of the existing tests will need to be updated.

**Comment by jklymak** [comment]
I think some of this is probably obsolete at this point, but feel free to re-open if I'm mistaken.  Thanks a lot for the PR!

**Pull request closed without merging**
