### PR TITLE
BUG: Add a newline separator in fc-list call

### LINKED ISSUE #7906: font_manager.get_fontconfig_fonts() reports a single item of all fonts concatenated
as reported on Debian as http://bugs.debian.org/852060:

```
While using matplotlib to list installed files in a python3 script:
font_manager.get_fontconfig_fonts(),
the list I get has only one element, that contains all fonts names concatenated.

I've tried replacing
out = subprocess.check_output([str('fc-list'), '--format=%{file}'])
on line 284 by:
out = subprocess.check_output([str('fc-list'), '--format=%{file}\\n'])
and that works.
```

I can confirm this happens on both py2 and py3

do you think that's the right approach or is there a better way to fix this issue? thanks!

### PR DESCRIPTION
**Pull request by jkseppan**
Fixes #7906.

### CODE REVIEW

**Comment by tacaswell** [comment]
Does this mean our font finding is broken in 2.0?

**Comment by anntzer** [comment]
- Sorry for breaking this.
- The test needs to be skipped on Windows.
- We need to see why this did not break the Travis tests and wasn't more widely reported as this should a priori be a huge issue for any linux users.

**Comment by jkseppan** [comment]
It's not widely reported because of the setting `USE_FONTCONFIG = False` in `font_manager.py` so we don't really use fontconfig. In #7906 someone is using the functions directly.

**Comment by anntzer** [comment]
What are (or would be) the reasons to use it or not to use it?

**Comment by jkseppan** [comment]
The fontconfig stuff is experimental code from ca. 2007 and is behind a
flag to allow experimentation by interested parties. Probably it was
felt to be risky for some reason - perhaps there are reports in the
mailing list archives? Fontconfig is probably better at finding the
system fonts on Linux systems than our custom code. @mdboom had some
bigger font-related plans (MEP14) and I don't know if they conflict with
fontconfig.

**Comment by anntzer** [comment]
- If fontconfig is not used by default, I don't understand why people were seeing the fc-list "slow" warning before.
- In general, I'd say experimental code from 10 years ago should either be turned on by default (on Arch Linux, the ttf-dejavu package (providing the new default font, I guess?) depends on fontconfig, so at least here it's effectively not an extra dependency) or removed...

**Comment by QuLogic** [comment]
I think that `USE_FONTCONFIG` setting works the opposite way. Setting it to `True` will use `fc-match` to find fonts, whereas setting it `False` (or on Windows) will use `FontManager` and trigger the `fc-list` call modified herein.

Has the Travis cache been working _too well_, and we've just been reloading the correct font list all this time?

If we need to trigger a cache rebuild, we should probably bump `FontManager.__version__` at this point as well.

**Comment by QuLogic** [comment]
OK, I think I have an idea; in `findSystemFonts`, we also do a [recursive search through some default directories](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py#L341). The line right after that discards any non-existent files (meaning the `fc-list` result is discarded.)

So we're essentially looking for fonts twice, once via `fc-list` and once in some default directory. Apparently, no-one puts fonts elsewhere.

**Comment by tacaswell** [comment]
I agree with @QuLogic 's analysis of what is gonig on and why this still appears to work.

This should still be backported to 2.0.x (even if it is not as critical as it first appears).

**Comment by tacaswell** [comment]
The backport is annoying because `skipif` is not defined on 2.0.x.  I'll deal with this tomorrow.

**Comment by anntzer** [comment]
@QuLogic Regardless of why this was not an issue, one of the builds of the matrix could start with a removal of ~/.config/matplotlib/fontList.* so that font-finding is tested at least once.

**Comment by jkseppan** [comment]
I think several of the jobs do have the setting DELETE_FONT_CACHE=1
which is supposed to do that.

**Comment by anntzer** [comment]
Indeed, my bad.

**Comment by jkseppan** [comment]
I wouldn't worry about backporting the skipif, just make the test do
`assert sys.platform=='win32' or len(...)>1`.

**Comment by QuLogic** [comment]
Backported to `v2.0.x` as 70c9d0681291b263bebb40f7164cc2f7d92f962b.

**Pull request merged**
