### PR TITLE
Remove zip_safe=False flag from setup.py.

### PR DESCRIPTION
**Pull request by anntzer**
The flag only matters when installing from eggs
(https://setuptools.readthedocs.io/en/latest/setuptools.html#setting-the-zip-safe-flag)
which are mostly unused nowadays, and setuptools will still correctly
infer that matplotlib is not "zip_safe" based on the presence of
extension modules even when zip_safe=False is not explicitly set.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
What is the harm in keeping this flag?

**Comment by WeatherGod** [comment]
yeah, I don't see the harm in keeping it. Explicit is better than implicit.

Personally, I keep that flag in all of my setup.py's because of some weird
interaction between setuptools and NFS mounts.

**Comment by anntzer** [comment]
It's just a noop that requires 3 lines of comments to explain what it's doing, which goes against my objective of bringing matplotlib's build script (setup+setupext) from something ridiculously complex down to something more reasonable (it was 2582 (physical) total lines as of 1.5, it is 1521 lines now, and I have patches that bring it down to less than 1000 lines (in case it wasn't obvious I'm slowly publishing the PRs one at a time to keep things reviewable...)).

Again, manually inspecting the egg created by python setup.py bdist_egg shows that even after this patch, the `EGG-INFO/not-zip-safe` marker file is still present, which corresponds to the documented setuptools behavior.

**Comment by tacaswell** [comment]
power cycled to run against current master.

**Pull request merged**
