### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by szemek**
Tiny fix: antialised => antialiased

https://github.com/matplotlib/matplotlib.github.com/pull/13

### CODE REVIEW

**Comment by szemek** [comment]
To provide more info for reviewer. When I tried following code:
```python
import matplotlib
import matplotlib.pyplot

matplotlib.pyplot.plot([1,2,3], [1,2,3], 'go-', antialised=False)
```
I got
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-6412c83c6710> in <module>()
      4 import matplotlib.pyplot
      5 
----> 6 matplotlib.pyplot.plot([1,2,3], [1,2,3], 'go-', antialised=False)

/opt/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.pyc in plot(*args, **kwargs)
   3097         ax.hold(hold)
   3098     try:
-> 3099         ret = ax.plot(*args, **kwargs)
   3100         draw_if_interactive()
   3101     finally:

/opt/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in plot(self, *args, **kwargs)
   1371         lines = []
   1372 
-> 1373         for line in self._get_lines(*args, **kwargs):
   1374             self.add_line(line)
   1375             lines.append(line)

/opt/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _grab_next_args(self, *args, **kwargs)
    302                 return
    303             if len(remaining) <= 3:
--> 304                 for seg in self._plot_args(remaining, kwargs):
    305                     yield seg
    306                 return

/opt/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _plot_args(self, tup, kwargs)
    290         ncx, ncy = x.shape[1], y.shape[1]
    291         for j in xrange(max(ncx, ncy)):
--> 292             seg = func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
    293             ret.append(seg)
    294         return ret

/opt/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _makeline(self, x, y, kw, kwargs)
    242                             **kw
    243                             )
--> 244         self.set_lineprops(seg, **kwargs)
    245         return seg
    246 

/opt/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in set_lineprops(self, line, **kwargs)
    182             funcName = "set_%s" % key
    183             if not hasattr(line, funcName):
--> 184                 raise TypeError('There is no line property "%s"' % key)
    185             func = getattr(line, funcName)
    186             func(val)

TypeError: There is no line property "antialised"
```

Changing it to:

```
import matplotlib
import matplotlib.pyplot

matplotlib.pyplot.plot([1,2,3], [1,2,3], 'go-', antialiased=False)
```

solved a problem.

**Comment by WeatherGod** [comment]
Well, it is a good thing nobody would ever have code that directly depended upon the documentation (cough) https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/artist.py#L1043 (cough). That would have been disastrous!

**Comment by WeatherGod** [comment]
@tacaswell, do we continue to backport stuff to 1.5.x?

**Comment by jenshnielsen** [comment]
According to the discussion in the new gitter channel we should backport that

**Comment by mdboom** [comment]
I think for clear simple bugfixes like this, yes.  Milestone as 1.5.1.  Then periodically that will flow up to 2.0.x.

**Comment by mdboom** [comment]
Backported to v1.5.x as bd5f8461714f

**Comment by mdboom** [comment]
Backported to v1.5.0-doc as 09ee788

**Pull request merged**
