### PR TITLE
Add a third party package in the doc: matplotlib-scalebar

### PR DESCRIPTION
**Pull request by ppinard**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ppinard** [comment]
PR in response to ppinard/matplotlib-scalebar#21

**Comment by ppinard** [comment]
@timhoffm I was able to reduce the size by ~5. I decreased the resolution by 2 and using Gimp I converted the image to greyscale and applied the highest compression.

**Comment by ppinard** [comment]
The original image is from Wikipedia Commons and it is in in the Public Domain: https://commons.wikimedia.org/wiki/File:Gold_on_Carbon.jpg

**Comment by tacaswell** [comment]
Thanks @ppinard !

**Comment by timhoffm** [comment]
@tacaswell I'm afraid the merge was a bit too fast.

- The image is not optimal:
  - JPG would be more suited for such an image.
  - The image has not gone through a compressor. (There are optimizations to reduce image size apart from the compression level).

  A visually equivalent (compressor post-processed) JPG would be 13kb instead of 33kb.
- The ReST code forces an image height of 200px while the actual image is just 150px. This upscaling degrades quality visibly. We should show the image in it's original size. So either use a larger image or make it smaller in the docs.

Given that this is already merged, how do we proceed from here?

**Comment by tacaswell** [comment]
Push a new PR to fix those things and once that is merged add it to the backport PR.

**Comment by ppinard** [comment]
I will make a new PR today.

**Pull request merged**
