### PR TITLE
FIX: make MaxNLocator only follow visible ticks for order of magnitude

### LINKED ISSUE #12072: `MaxNLocator` changes the scientific notation exponent with different number of tick labels
### Bug report

**Bug summary**

`MaxNLocator` changes the scientific notation with different number of tick labels.

**Code for reproduction**

I encountered this unexpected behavior when I changed the y-ticklabel size. Going from size 13 to 14 changes the scientific notation from 1e9 to 1e10, and adds an decimal offset to all the ticklabels.

```python
import matplotlib.pyplot as plt

sci_nums = [10**9, 8*10**9]
plt.rcParams['ytick.labelsize'] = 13
fig, ax = plt.subplots()
ax.scatter(range(len(sci_nums)), sci_nums)
```

image

```python
plt.rcParams['ytick.labelsize'] = 14
fig, ax = plt.subplots()
ax.scatter(range(len(sci_nums)), sci_nums)
```
image

This is related to that the larger font size reduces the number of tickslabels. `MaxNLocator` apparently adjusts the scientific notation depending on the number of ticklabels.

```python
plt.rcParams['ytick.labelsize'] = 13
fig, ax = plt.subplots()
ax.scatter(range(len(sci_nums)), sci_nums)

import matplotlib.ticker as ticker
ax.yaxis.set_major_locator(ticker.MaxNLocator(4))
```
image

I dont' quite understand the rule that `MaxNLocator` uses. Setting 1, 2, 4 or 5 ticklabels results in `1e10`. Setting 3, 6, 7, 8, or 9 ticklabels results in `1e9`.

**Expected outcome**
I would expect that changing the number of ticklabels (either directly or via another parameter such as the font size) would not result in a change in the formatting of the scientific notation. In this case, I would expect it to remain `1e9` for all the examples above.

**Matplotlib version**

  * Operating system: `Linux`
  * Matplotlib version: `2.2.2`
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: `3.6.6` (conda-forge)
  * Jupyter version (if applicable): `jupyterlab=0.34.3`, jupyter_core=`4.4.0`
  * Other libraries:

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #12072

Order of magnitude for tick formatting in ScalarFormatter was using invisible ticks.  This changes to just use visible.  

Probably obviated by #11004 but won't hurt anything. 

## Before:

figure_2

## After

figure_1

## Code

```python

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

sci_nums = [10**9, 8*10**9]
plt.rcParams['ytick.labelsize'] = 13
fig, ax = plt.subplots(1, 2)
ax[0].scatter(range(len(sci_nums)), sci_nums)
ax[1].scatter(range(len(sci_nums)), sci_nums)

ax[1].yaxis.set_major_locator(ticker.MaxNLocator(4))
plt.show()


```

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Seems to have broken some docs when there are no visible ticks.

**Comment by jklymak** [comment]
Ha, it passes all of `test_axes` and `test_ticker`...

**Comment by anntzer** [comment]
Modulo the docs...

**Comment by jklymak** [comment]
@anntzer I think the docs are OK (they say it'll just key off the data, not the data plus one tick on either side).  It does need tests, which I'll do now. I actually don't understand why `test_ticker` passes all the tests...  It should have failed some of them.  Of course the test for this is all parameterized etc, so it'll take me a bit to grok what is going on..

**Comment by jklymak** [comment]
Added test that fails master but passes this PR...

**Comment by NelleV** [comment]
Thanks @jklymak !
I agree that the docs don't need changing on that one, so I'll go ahead and merge.

**Pull request merged**
