### PR TITLE
[DO NOT MERGE]: maybe fix crossed keybindings in ipython 4.1

### PR DESCRIPTION
**Pull request by tacaswell**
Possibly fixes https://github.com/jupyter/notebook/issues/949

attn @ericdill

### CODE REVIEW

**Comment by tacaswell** [comment]
This 'fixes' the jupyter problem by removing all the interaction with the jupyter keyboard manager. 

attn @Carreau

**Comment by Carreau** [comment]
Ping @takluyver, @minrk and @jdfreder I'll try to have a look, but that will be hard in the next few days. @parleur you recently looked at the keyboard shortcut for vim/emacs/sublime keybindings.

**Comment by tacaswell** [comment]
Any progress on this?  Does the new widget fix this?

**Comment by jenshnielsen** [comment]
I believe it's fixed by the new widget but it would be good to fix this on 1.5.x/2.x too

**Comment by tacaswell** [comment]
Do we have any idea what the underlying problem is?  I am not even sure if this needs to be fixed on our side or the jupyter side.

**Comment by tacaswell** [comment]
@Carreau Did you make any progress on this from the ipython side?

**Comment by tacaswell** [comment]
replaced by #6752

**Pull request closed without merging**
