### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### matplotlib/matplotlib now has a Chat Room on Gitter

@tacaswell has just created a chat room. You can visit it here: [https://gitter.im/matplotlib/matplotlib](https://gitter.im/matplotlib/matplotlib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/matplotlib/matplotlib?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by tacaswell** [comment]
Lets see if we find it useful before we add a badge.

**Comment by JanSchulz** [comment]
I think one thing which would make this usefull if more people would know about it (i.e. I didn't) :-)

IMO this should be merged (I just saw that there is content in there) and, if it is not useful in the long run, simple be removed again.

**Comment by WeatherGod** [comment]
I'd be fine with it. It being in the readme is a bit weird, but when one lands on github's matplotlib page, that's what they see, so it kinda makes sense there.

**Comment by tacaswell** [comment]
backported to v2.x as 320be9ee9238d493a67afdc676bfd27f0f518da2

**Pull request merged**
