### PR TITLE
Line2d traitlets dev

### PR DESCRIPTION
**Pull request by katierose1029**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
@katierose1029 did you mean to delete this?

**Comment by katierose1029** [comment]
@tacaswell  yes i did. i have two branches with the same name but i havent contributed to this branch in almost a month. the other branch with this same name is the one i have been working on

**Comment by katierose1029** [comment]
@tacaswell i forgot that I made a pull req on this branch

**Comment by katierose1029** [comment]
@tacaswell  https://github.com/katierose1029/matplotlib/commits/line2D-traitlets-dev is the current branch

**Comment by tacaswell** [comment]
just cheking :)

**Comment by katierose1029** [comment]
@tacaswell  thank you =] i would have panicked otherwise thinking i deleted the branch that I have been working on

**Pull request closed without merging**
