### PR TITLE
Add quotes around [dev] in environment.yml

### LINKED ISSUE #29241: [Bug]: Instructions for setting up conda dev environment in environment.yml give issues with MacOS/zsh
### Bug summary

The comment on how to set up the dev environment using conda in environment-yml says: 
`pip install -e .[dev]`
This causes issues with zsh (see also https://github.com/mu-editor/mu/issues/852) 

### Code for reproduction

```Python
matplotlib % pip install -e .[dev]
```

### Actual outcome

zsh: no matches found: .[dev]

### Expected outcome

Expected to install the build dependencies successfully 

### Additional information

Propose to update the comment to: 
`pip install -e .'[dev]'`
, which was also used to fix here https://github.com/mu-editor/mu/issues/852 

### Operating system

MacOS

### Matplotlib Version

9d1a393d48bfd767ec10397bd8366fa75124761e

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

conda

### PR DESCRIPTION
**Pull request by aishling-scilifelab**
Closes #29241 by improving the comment which explains how to up the dev environment using conda. 

Update comment describing conda dev set up

- Update commented commands in environment.yml to match
 the command in development_setup.rst
- This version of the command does not cause issues with
zsh (due to the quotation marks).

## PR checklist

- [X] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [X] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
Hi @aishling-scilifelab thank you for your contribution!  The command required to install in editable mode has changed since this was written.  If you could update it to match the one described here, that would be great.
https://matplotlib.org/devdocs/devel/development_setup.html#install-matplotlib-in-editable-mode

**Comment by aishling-scilifelab** [comment]
@rcomer Hey! Thanks - is the now pushed change what you mean?

**Comment by rcomer** [comment]
@aishling-scilifelab looks good :+1:

**Review by QuLogic — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Thanks @aishling-scilifelab and congratulations on your first contribution to matplotlib! 🎉

**Pull request merged**
