### PR TITLE
Updated doc in images.py by adding direct link to 24-bit stink bug png

### PR DESCRIPTION
**Pull request by majorwitty**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
@majorwitty I changed the target of your PR to master.  By targeting 3.1.1-doc you were trying to backport everything on master to that branch!  We have a very helpful bot that backports individual PRs from master to the maintenance branches.

**Comment by tacaswell** [comment]
Thanks for this @majorwitty !  It looks good to me, but going to wait for CI to finish before merging.

**Comment by timhoffm** [comment]
Do we need an explicit link?

Options how to proceed:

- Do nothing.
- Add a comment that the image can be downloaded via the context menu "Save image as"
- Add a proper [html download link](https://www.w3schools.com/howto/howto_html_download_link.asp) via sphinx``.. raw:: html``.

**Comment by timhoffm** [comment]
Related: #11296

**Comment by QuLogic** [comment]
The link just needed to end with `_. I pushed a rebase and added that.

**Pull request merged**
