### PR TITLE
Update qhull to 2015.2

### PR DESCRIPTION
**Pull request by ianthomas23**
This PR updates the qhull source code that we ship with matplotlib to be the latest version, 2015.2.  There is no change in functionality.

I was going to change it to use the new reentrant version of qhull which is somewhat more thread safe.  However, in trying this I unearthed a bug in debian-based distributions which ship the reentrant header files but not the shared library (libqhull_r.so).  I have reported this to debian many weeks ago (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841168), but there hasn't even been an acknowledgement of the bug yet never mind a fix.  Shipping mpl using the reentrant version whilst this bug still exists would result in lots of failed installs, so I have stuck to the original non-reentrant version and will write another PR when debian fix the bug.

Assuming this passes the tests and everyone is happy with it, it will close issue #6791.

### CODE REVIEW

**Comment by tacaswell** [comment]
Restarted the 2 failed tests (look transient to me).

I see no reason not to do this.

**Comment by tacaswell** [comment]
@ianthomas23 Can you add a note to whats_new or api_changes (which ever you think is better) noting we bumped the vendored version.

**Comment by ianthomas23** [comment]
@tacaswell I've added an entry to api_changes, and squashed that commit.

**Comment by NelleV** [comment]
Thanks @ianthomas23 !

**Pull request merged**
