### PR TITLE
Fix logic error in ScalarMappable.to_rgba

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

This fixes the logic error described in #10890.

### CODE REVIEW

**Comment by tacaswell** [comment]
I think this is a candidate for backport because it fixes a un-workaroundable bug in 2.2.2.  I am not 100% on that, if someone else agrees merge away!

**Comment by jklymak** [comment]
I actually am 98.5% sure its *not* a followed code path because of the new clipping for imshow (#10220).   0% codecov isn't very good ;-)

**Comment by tacaswell** [comment]
This is (for better or worse) a public function, I think the clipping happens when we set the data so using the 'standard' path this won't be hit, but using `im.to_rgba(my_data)` can still hit it.

**Comment by efiring** [comment]
This is the sort of bugfix that I think does *not* warrant a test.

**Pull request merged**
