### PR TITLE
Added print feature

### PR DESCRIPTION
**Pull request by tirthsh**
## PR Summary
This PR works with the ability to print the plot displayed on the GUI. Based on the operating system of the user, it will correctly save the file, print it from the local computer, and delete the file once the printing job is finished. On the GUI, a new print button is added; so by click so, it will print the corresponding plot. 

printexample

## PR Checklist

- [x] Code is PEP 8 compliant
- [x] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I’d vote this as too specific to the users needs

There will be a toolbar manager someday that will allow users to populate buttons On the GUI in 3.0. I think that’s a better place for this.

**Comment by tirthsh** [comment]
Hi @jklymak , so is there a way this PR can be on hold until the implementation of the GUI 3.0 is in place? Or is it better to close the PR and re-open it in the future?

**Comment by jklymak** [comment]
My *vote* is that this is just too specific to your set up to be of general use, and I'd be against adding such a feature in any case because supporting a print dialogue is a cross-platform maintenance chore that is beyond our scope.  

The point about the toolbox, is that it'd easily let you as a user add this functionality if you want.

**Comment by tirthsh** [comment]
Understood. Thanks a lot for your feedback!

**Comment by anntzer** [comment]
Thanks for the PR, but I agree with @jklymak's sentiment here.

**Pull request closed without merging**
