### PR TITLE
set_fontstretch documentation: it's unimplemented

### PR DESCRIPTION
**Pull request by mlbileschi**
It's mentioned [here](https://matplotlib.org/stable/tutorials/introductory/customizing.html) that the property is unimplemented, but I had to dig a while to find that.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Is it actually not implemented?  I'm not super familiar w/ the font code, but there seems to be a lot of code around stretch in `font_manager.py`...

**Comment by anntzer** [comment]
I believe that it is implemented and that it's the matplotlibrc file that's outdated.

**Comment by mlbileschi** [comment]
well, to be honest I'm not 100% sure, but I also see mentions of incompleteness here:
https://github.com/matplotlib/matplotlib/blob/b5a206e494c216a11e1d71e5cc00462f233952b5/lib/matplotlib/font_manager.py#L20

**Comment by jklymak** [comment]
Its not tested in `test_font_manager` so maybe a todo is to add tests and fix the documentation to reflect the state of the feature?

**Comment by dstansby** [comment]
Thanks for opening this PR - since it looks like font stretch is implemented I'm giong to close this.  A PR to open an outdated documentation in matplotlibrc would be very welcome though!

**Pull request closed without merging**
