### PR TITLE
Fix punctuation in doc.

### PR DESCRIPTION
**Pull request by pankajchetry1168**
## PR Summary

- Replace the open bracket with a comma, following the rest of the sentence's structure, i.e., in that section the number of open and closing parenthesis was of the unequal number as one of the commas might have been typed as "(".

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by jklymak — DISMISSED** [review]
Thanks for the contribution, but you cannot just drop one of two brackets, and I'm not sure there is any improvement making this a comma.

**Comment by pankajchetry1168** [comment]
Thank you for your response. The improvement is not that big. In the section,
the number of open and closing parentheses was unequal as one of the commas
might have been typed as '(. '

 Please, close the pull request if the change doesn't make any improvement.

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Thanks @pankajchetry1168, and congratulations on your first contribution to Matplotlib. We hope to see you again some time.

**Comment by jklymak** [comment]
My apologies, you are correct... Thanks for the contribution.

**Pull request merged**
