### PR TITLE
Rework checks for old macosx

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This tweaks the checks to use some slightly more modern macros, and updates the documentation URL. It also changes the compatibility `#define`s to be enabled when using an older SDK minimum, instead of when not allowing a new maximum. This seems to not trigger any deprecations, yet allows us to _not_ raise minimum requirements.

cc @efiring @dstansby @jkseppan 

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
This works on MacStadium, and [would fix wheel CI builds](https://github.com/QuLogic/matplotlib/runs/1212965615?check_suite_focus=true).

**Review by dopplershift — APPROVED** [review]

**Review by dstansby — APPROVED** [review]
Works well for me and changes look good, thanks a lot.

**Review by dstansby — DISMISSED** [review]
Hmm, looks like the travis build is failing on building the maxos extension.

**Comment by QuLogic** [comment]
Is it? What's the error? All I see is a truncated log in the middle of building FreeType.

**Comment by QuLogic** [comment]
I figured it out; older SDKs don't define newer `__MAC_OS_#_#`, so Apple's advice to use the numbers still stands. I mostly reverted bba75cc0022c9c9b21f89341d593f1a7e21b53f3, which should fix it.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
@dopplershift if you still are OK w/ this, go ahead and merge....

**Pull request merged**
