### PR TITLE
[MRG+1] Fix image watermark example where image was hidden by axes (#7265)

### PR DESCRIPTION
**Pull request by AndersonDaniel**
Hi!

I'm new to matplotlib and would be happy to contribute if I can.
Did as @anntzer  suggested in the issue (only with `zorder=3` like in the Text class) and of course it worked:
ex

I was also wondering why FigureImage has `zorder=0` by default, doesn't that mean images drawn on figures will always be hidden by the axes (unless the `zorder` argument is explicitly set)?

Another thing that could be a bit confusing is that the example passes the `zorder` keyword argument to `figimage` even though it's only intercepted by the constructor of Artist class (and thus doesn't appear in `figimage`'s docs)... Then again maybe it's only confusing for new people :)

Thanks!

### CODE REVIEW

**Comment by NelleV** [comment]
Hi @AndersonDaniel 
Thanks for the patch! It looks good.

There's a lot of things that are confusing in matplotlib, whether you are advanced or a beginner. A lot of the choices where made a very long time ago and the context was different 10 - 15 years ago than it is now.

I was wondering if you had a little more courage and if you could also add a bit of documentation to this example, using a docstring at the top of the file to be [sphinx-gallery](http://sphinx-gallery.readthedocs.io/en/latest/) compatible. It's  just a docstring with a title and a small text description, with a blank line between the title and the description.

**Comment by NelleV** [comment]
Note: this closes #7265

**Comment by AndersonDaniel** [comment]
@NelleV Thanks for the quick response!
Added a title (that's what I understood is missing), is that what you meant?

**Comment by NelleV** [comment]
Thanks! That looks good!

**Comment by tacaswell** [comment]
@AndersonDaniel Thanks and congratulations on your first mpl contribution :tada: 

Did you find this issue via the 'new-contributor-friendly' label?

**Comment by tacaswell** [comment]
backported to v2.x as 421327d

**Comment by AndersonDaniel** [comment]
Thanks @tacaswell ! Yes, I found it through both that label and "Difficulty: Easy"

**Pull request merged**
