### PR TITLE
Disable clipping in Agg resamplers.

### PR DESCRIPTION
**Pull request by anntzer**
I chose to add macro guards directly in the agg source as that seemed easier than copy-pasting the whole code.

I chose to bump the tolerance on test_rgba_antialias (as that's also getting bumped by the interpolation_stage antialias PR) and to test_pngsuite (which is not particularly relevant), and to update the other baselines.

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by greglucas** [comment]
Wow, this looks like a really nice simplification and should fix some of the high dynamic range issues where we ran into problems around the 0.1/0.9 floating point representation creating incorrect under/over values.

Is this waiting on #28061 ?

**Review by greglucas — APPROVED** [review]

**Comment by anntzer** [comment]
Apologies for the slow reply, I have basically no time to work on this these days (just a temporary thing).
I think this is actually fairly independent of #28061 (the rebase seems to work directly except for the fact that both PRs bump the tolerance on the same test), so they can probably(?) be merged in either order, except perhaps(?) if one wants to optimize baseline image weight in the git history?
If #28061 gets merged first, feel free to push a rebase of this PR to get it in if I don't do it quickly.

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
TBH, I've not followed the relation with #28061, so I'm not clear whether we can just merge or whether we should wait. The change itself is good to go.

**Review by jklymak — COMMENTED** [review]
I think this is likely correct and certainly doesn't need to wait on #28061.  But maybe @tacaswell should weigh in as the previous method was his.

**Comment by tacaswell** [comment]
Thank you for getting this done!

**Pull request merged**
