### PR TITLE
Add cheatsheet link to main doc page

### LINKED ISSUE #18019: Add cheatsheets to docs
We have official very nice cheatsheets at https://github.com/matplotlib/cheatsheets and it'd be nice to prominently link them out from the homepage and possibly embed them in the docs. 

attn @timhoffm & @rougier

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Closes #18019.

Preview:
grafik

Draft:

- [ ] The image has 1x resolution. Do we want to 2x oversample to have nicer images on retina? By that the file size would go up from 12kB to 33kB (could we serve different images depending on the screen scaling).
- [ ] Do we want some text there? If so what?
- [ ] Linking to the cheatsheet repo is probably not the best. - Create a subpage with all Cheat sheets in our docs and link there?

Feedback welcome.

### CODE REVIEW

**Comment by jklymak** [comment]
Great.  I'd serve the 2x version.

**Comment by story645** [comment]
I love it so so much, but I think we should link to the sheets in their repo since that's the most updated version. I don't think it needs text if it has altext explaining what it is.

Maybe @rougier has a preference?

**Comment by jklymak** [comment]
I think the idea was that the cheatsheets should be linked to versions and updated Matplotlib versions change....

**Comment by QuLogic** [comment]
>     * could we serve different images depending on the screen scaling).

This is done with [`srcset`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/srcset).

**Review by QuLogic — APPROVED** [review]

**Review by story645 — APPROVED** [review]

**Pull request merged**
