### PR TITLE
MNT: updates for python 3.7

### PR DESCRIPTION
**Pull request by tacaswell**
Did not do appveyor as I am not sure if there is a miniconda available yet.

### CODE REVIEW

**Comment by dopplershift** [comment]
I don't think Travis has 3.7 yet. See travis-ci/travis-ci#9815.

**Comment by tacaswell** [comment]
we probably want to backport all of this to 2.2.x as well.

**Comment by tacaswell** [comment]
This are reproducible which is odd given that nightly is passing...


```
__________________________ test_contour_colorbar[svg] __________________________
[gw0] linux -- Python 3.7.0 /home/travis/virtualenv/python3.7.0/bin/python
expected = '/home/travis/build/matplotlib/matplotlib/result_images/test_axes/contour_colorbar-expected.svg'
actual = '/home/travis/build/matplotlib/matplotlib/result_images/test_axes/contour_colorbar.svg'
tol = 0
    def _raise_on_image_difference(expected, actual, tol):
        __tracebackhide__ = True
    
        err = compare_images(expected, actual, tol, in_decorator=True)
    
        if not os.path.exists(expected):
            raise ImageComparisonFailure('image does not exist: %s' % expected)
    
        if err:
            for key in ["actual", "expected"]:
                err[key] = os.path.relpath(err[key])
            raise ImageComparisonFailure(
                'images not close (RMS %(rms).3f):\n\t%(actual)s\n\t%(expected)s '
>                % err)
E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 0.002):
E           	result_images/test_axes/contour_colorbar_svg.png
E           	result_images/test_axes/contour_colorbar-expected_svg.png
lib/matplotlib/testing/decorators.py:148: ImageComparisonFailure
___________________________ test_tight_layout4[svg] ____________________________
[gw1] linux -- Python 3.7.0 /home/travis/virtualenv/python3.7.0/bin/python
expected = '/home/travis/build/matplotlib/matplotlib/result_images/test_tightlayout/tight_layout4-expected.svg'
actual = '/home/travis/build/matplotlib/matplotlib/result_images/test_tightlayout/tight_layout4.svg'
tol = 0
    def _raise_on_image_difference(expected, actual, tol):
        __tracebackhide__ = True
    
        err = compare_images(expected, actual, tol, in_decorator=True)
    
        if not os.path.exists(expected):
            raise ImageComparisonFailure('image does not exist: %s' % expected)
    
        if err:
            for key in ["actual", "expected"]:
                err[key] = os.path.relpath(err[key])
            raise ImageComparisonFailure(
                'images not close (RMS %(rms).3f):\n\t%(actual)s\n\t%(expected)s '
>                % err)
E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 0.006):
E           	result_images/test_tightlayout/tight_layout4_svg.png
E           	result_images/test_tightlayout/tight_layout4-expected_svg.png
lib/matplotlib/testing/decorators.py:148: ImageComparisonFailure
```

**Comment by tacaswell** [comment]
Now just 

```python

___________________________ test_tight_layout4[svg] ____________________________
[gw1] linux -- Python 3.7.0 /home/travis/virtualenv/python3.7.0/bin/python
expected = '/home/travis/build/matplotlib/matplotlib/result_images/test_tightlayout/tight_layout4-expected.svg'
actual = '/home/travis/build/matplotlib/matplotlib/result_images/test_tightlayout/tight_layout4.svg'
tol = 0
    def _raise_on_image_difference(expected, actual, tol):
        __tracebackhide__ = True
    
        err = compare_images(expected, actual, tol, in_decorator=True)
    
        if not os.path.exists(expected):
            raise ImageComparisonFailure('image does not exist: %s' % expected)
    
        if err:
            for key in ["actual", "expected"]:
                err[key] = os.path.relpath(err[key])
            raise ImageComparisonFailure(
                'images not close (RMS %(rms).3f):\n\t%(actual)s\n\t%(expected)s '
>                % err)
E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close (RMS 0.006):
E           	result_images/test_tightlayout/tight_layout4_svg.png
E           	result_images/test_tightlayout/tight_layout4-expected_svg.png
lib/matplotlib/testing/decorators.py:148: ImageComparisonFailure
=========================== short test summary info ============================
```

I can not reproduce this locally using 3.7.0 from anaconda.

**Comment by tacaswell** [comment]
@ImportanceOfBeingErnest Can you take a look at this?  The test that is failing is https://github.com/matplotlib/matplotlib/blob/70e7850c7676faced2e3ff6641df14bdf69dc22e/lib/matplotlib/tests/test_figure.py#L386-L409

which does not have an image we can re-generate like we discussed on the call.

Looking at the diff locally it looks like difference is the ordering of non-overlapping artists (before or after all of the bits of Axes).  

The version of inkscape on the passing travis instances is 0.48, on the failing travis is 0.91 and on my local system is 0.92.

I strongly suspect this is a bug/instability in inkscape....

<details> 

```diff
--- result_images/test_figure/test_add_artist-expected.svg      2018-08-04 23:59:15.377137248 -0400
+++ result_images/test_figure/test_add_artist.svg       2018-08-04 23:59:15.350471240 -0400
@@ -26,24 +26,6 @@
 z
 " style="fill:#ffffff;"/>
    </g>
-   <g id="C2">
-    <path clip-path="url(#p4c8e7e0101)" d="M 403.2 237.6 
-C 410.837849 237.6 418.1639 235.324088 423.564675 231.273506 
-C 428.96545 227.222925 432 221.728387 432 216 
-C 432 210.271613 428.96545 204.777075 423.564675 200.726494 
-C 418.1639 196.675912 410.837849 194.4 403.2 194.4 
-C 395.562151 194.4 388.2361 196.675912 382.835325 200.726494 
-C 377.43455 204.777075 374.4 210.271613 374.4 216 
-C 374.4 221.728387 377.43455 227.222925 382.835325 231.273506 
-C 388.2361 235.324088 395.562151 237.6 403.2 237.6 
-z
-" style="fill:#0000ff;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
-   <g id="l1">
-    <path clip-path="url(#p4c8e7e0101)" d="M 115.2 129.6 
-L 403.2 129.6 
-" style="fill:none;stroke:#0000ff;stroke-linecap:square;"/>
-   </g>
    <g id="patch_3">
     <path d="M 72 388.8 
 L 72 43.2 
@@ -490,8 +472,9 @@
      </g>
     </g>
    </g>
-   <g id="C1">
-    <path d="M 20 512 
+  </g>
+  <g id="C1">
+   <path d="M 20 512 
 C 46.52031 512 71.957987 501.463369 90.710678 482.710678 
 C 109.463369 463.957987 120 438.52031 120 412 
 C 120 385.47969 109.463369 360.042013 90.710678 341.289322 
@@ -502,9 +485,22 @@
 C -31.957987 501.463369 -6.52031 512 20 512 
 z
 " style="fill:#0000ff;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
-   <g id="C3">
-    <path d="M 324 414 
+  </g>
+  <g id="C2">
+   <path d="M 403.2 237.6 
+C 410.837849 237.6 418.1639 235.324088 423.564675 231.273506 
+C 428.96545 227.222925 432 221.728387 432 216 
+C 432 210.271613 428.96545 204.777075 423.564675 200.726494 
+C 418.1639 196.675912 410.837849 194.4 403.2 194.4 
+C 395.562151 194.4 388.2361 196.675912 382.835325 200.726494 
+C 377.43455 204.777075 374.4 210.271613 374.4 216 
+C 374.4 221.728387 377.43455 227.222925 382.835325 231.273506 
+C 388.2361 235.324088 395.562151 237.6 403.2 237.6 
+z
+" style="fill:#0000ff;stroke:#000000;stroke-linejoin:miter;"/>
+  </g>
+  <g id="C3">
+   <path d="M 324 414 
 C 334.502043 414 344.575363 409.827494 352.001429 402.401429 
 C 359.427494 394.975363 363.6 384.902043 363.6 374.4 
 C 363.6 363.897957 359.427494 353.824637 352.001429 346.398571 
@@ -515,12 +511,11 @@
 C 303.424637 409.827494 313.497957 414 324 414 
 z
 " style="fill:#dc143c;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
+  </g>
+  <g id="l1">
+   <path d="M 115.2 129.6 
+L 403.2 129.6 
+" style="fill:none;stroke:#0000ff;stroke-linecap:square;"/>
   </g>
  </g>
- <defs>
-  <clipPath id="p4c8e7e0101">
-   <rect height="345.6" width="446.4" x="72" y="43.2"/>
-  </clipPath>
- </defs>
 </svg>

```

</details>

**Comment by tacaswell** [comment]
The relative z-order of non-overlapping artists should not matter, I think this is a perfectly valid test.  The reason we do the svg testing through inkscape rather than direct text comparison is that we want to be insensitive to permutations like this.  If inkscape is rendering different raster output for swapping around the definition order of non-overlapping vectors, then I think that is a bug in inkscape.

Tweaking the test a bit more we can get the diff down too: 

```diff
--- result_images/test_figure/test_add_artist-expected.svg      2018-08-05 17:44:11.678082858 -0400
+++ result_images/test_figure/test_add_artist.svg       2018-08-05 17:44:11.658083381 -0400
@@ -472,8 +472,9 @@
      </g>
     </g>
    </g>
-   <g id="C1">
-    <path d="M 20 512 
+  </g>
+  <g id="C1">
+   <path d="M 20 512 
 C 46.52031 512 71.957987 501.463369 90.710678 482.710678 
 C 109.463369 463.957987 120 438.52031 120 412 
 C 120 385.47969 109.463369 360.042013 90.710678 341.289322 
@@ -484,9 +485,9 @@
 C -31.957987 501.463369 -6.52031 512 20 512 
 z
 " style="fill:#0000ff;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
-   <g id="C2">
-    <path clip-path="url(#p4c8e7e0101)" d="M 403.2 237.6 
+  </g>
+  <g id="C2">
+   <path d="M 403.2 237.6 
 C 410.837849 237.6 418.1639 235.324088 423.564675 231.273506 
 C 428.96545 227.222925 432 221.728387 432 216 
 C 432 210.271613 428.96545 204.777075 423.564675 200.726494 
@@ -497,9 +498,9 @@
 C 388.2361 235.324088 395.562151 237.6 403.2 237.6 
 z
 " style="fill:#0000ff;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
-   <g id="C3">
-    <path d="M 324 414 
+  </g>
+  <g id="C3">
+   <path d="M 324 414 
 C 334.502043 414 344.575363 409.827494 352.001429 402.401429 
 C 359.427494 394.975363 363.6 384.902043 363.6 374.4 
 C 363.6 363.897957 359.427494 353.824637 352.001429 346.398571 
@@ -510,17 +511,11 @@
 C 303.424637 409.827494 313.497957 414 324 414 
 z
 " style="fill:#dc143c;stroke:#000000;stroke-linejoin:miter;"/>
-   </g>
-   <g id="l1">
-    <path clip-path="url(#p4c8e7e0101)" d="M 115.2 129.6 
+  </g>
+  <g id="l1">
+   <path d="M 115.2 129.6 
 L 403.2 129.6 
 " style="fill:none;stroke:#0000ff;stroke-linecap:square;"/>
-   </g>
   </g>
  </g>
- <defs>
-  <clipPath id="p4c8e7e0101">
-   <rect height="345.6" width="446.4" x="72" y="43.2"/>
-  </clipPath>
- </defs>
 </svg>

```

which is: 
  - indentation differences because the artists are at different scopes
  - an extra clip path (that the artists do not intersect with)

Lets see if that passes....

**Comment by tacaswell** [comment]
self-merged based on reviews from @efiring and @dopplershift

**Pull request merged**
