### PR TITLE
WIP: Add boxplot params to rctemplate

### LINKED ISSUE #5441: boxplot rcParams are not in matplotlibrc.template
The boxplot rcParams added in #4218 are not included in matplotlibrc.template

### PR DESCRIPTION
**Pull request by phobson**
Also flailing here.

Part of the work that goes with #5523.

Aims to close #5441

### CODE REVIEW

**Comment by WeatherGod** [comment]
Don't forget to add them to the classic style, if they aren't there already.

**Comment by mdboom** [comment]
They are already in the classic style, though I discovered a bug in them yesterday.  `boxplot.flierprops.linestyle` was copied incorrectly from the old default in `rcsetup.py`.  This causes tests to fail when you decrease the tolerance down to 0.

@phobson: Maybe you could make this change here as well?

```diff
diff --git a/lib/matplotlib/mpl-data/stylelib/classic.mplstyle b/lib/matplotlib/mpl-data/stylelib/classic.mplstyle
index 0f61a53..86b4c22 100644
--- a/lib/matplotlib/mpl-data/stylelib/classic.mplstyle
+++ b/lib/matplotlib/mpl-data/stylelib/classic.mplstyle
@@ -322,11 +322,11 @@ boxplot.capprops.color: k
 boxplot.capprops.linestyle: -
 boxplot.capprops.linewidth: 1.0
 boxplot.flierprops.color: b
-boxplot.flierprops.linestyle: -
+boxplot.flierprops.linestyle: none
 boxplot.flierprops.linewidth: 1.0
 boxplot.flierprops.marker: +
 boxplot.flierprops.markeredgecolor: k
```

**Comment by phobson** [comment]
@mdboom done! that explains why my result images in default boxplot style PR were so o_0

**Comment by phobson** [comment]
Ok, I've confirmed that #5523 depends on this to produce meaningful test images

**Comment by tacaswell** [comment]
back-ported to v2.0.x as 071fc5c38293c9ae91a968be09cae6a197ac79e0

**Pull request merged**
