### PR TITLE
Homepage: add code snippet and link to tutorial

### PR DESCRIPTION
**Pull request by iosonofabio**
The current matplotlib homepage is missing any reference to the tutorial and any example code for newbies.

I propose to add those in this PR.

@WeatherGod

### CODE REVIEW

**Comment by iosonofabio** [comment]
Here a screenshot: http://picpaste.com/kTbywhbt.png

**Comment by WeatherGod** [comment]
Those buttons seem very out of place, especially since we don't have such buttons anywhere else. Plus, three of the four buttons are for the same links that are available at the top. Why not add a Tutorial link to that list? I also wonder if the font size for those links are too small, making them easy to ignore.

**Comment by tacaswell** [comment]
This conflicts with #3350 (which should be revived)

**Comment by iosonofabio** [comment]
@Ben: "out of place" sounds a lot like "visible". That stands in
contrast with the current links which are, I think, not visible at all.
But they look ugly, agreed. Then I'd suggest to make the top menu a lot
bigger and more contrasted (orange on white??). Again, see golang for an
example.

@Thomas: #3350 is closed and I can't find an image to what it looks
like. What is your concrete suggestion here?

From what I can tell from the code, #3350 is complementary to my proposal:

- what I do: tune top part of the page only, adding a link and a snippet
- what 3350 does: reorganized the rest of the page, adding sections and
subsections and lists and questions and so on. Very text-heavy, not
suitable for the "impact" first sight of the home, IMHO.

F

**Comment by WeatherGod** [comment]
Yeah, I see them as complementary. This is meant to give a better "first
impression", while the other was meant to help keep users from getting
mired down.

And yes, orange on white has been a thorn in my side (especially since I
wear tinted glasses). The links definitely need to be more prominent. Look
at just about every single other project page out there, and their
top-level menus are huge. Heck, look at just about every single other major
website! I would say that I would like to see it be twice as tall as it is
now, if not even turning it into a more button-like interface at the top.

**Comment by tacaswell** [comment]
This has had no traffic for 2 years and has rebase conflicts, closing.

@iosonofabio Thank you for you work and sorry it did not get merged.

**Pull request closed without merging**
