### PR TITLE
Improve error reporting for scatter c as invalid RGBA.

### LINKED ISSUE #11919: Wrong Error Message
### Bug report

Affects: commit 7b5ff33   (master, 23 Aug 2018)

An attempt to plot a single point at coords (2,3) with RGB color (120,130,140) throws an error message remarking about argument shapes mismatching. Message should be about RGB values outside range 0 to 1.

**Code for reproduction**

```python
ax.scatter(np.array([2]), np.array([3]), c=np.array([[120,130,140]]))
```
```
ValueError: c of shape (1, 3) not acceptable as a color sequence for x with size 1, y with size 1
```

This is ok:

```python
ax.scatter(np.array([2]), np.array([3]), c=np.array([[120,130,140]]) / 255.0 )
```

**Actual outcome**

See above.

**Expected outcome**

Suggestion: error message could be about RGB values outside of 0 to 1 range.

**Trace**

```python
  File "/home/d/code/matplotlib/lib/matplotlib/axes/_axes.py", line 4223, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 3 elements, which is not acceptable for use with 'x' with size 1, 'y' with size 1.

```

python 2 gives slightly different trace:
```python
/home/d/.conda/envs/py2_dp/lib/python2.7/site-packages/matplotlib-2.2.2-py2.7-linux-x86_64.egg/matplotlib/axes/_axes.pyc in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4277                 raise ValueError("c of shape {} not acceptable as a color "
   4278                                  "sequence for x with size {}, y with size {}"
-> 4279                                  .format(c.shape, x.size, y.size))
   4280         else:
   4281             colors = None  # use cmap, norm after collection is created

ValueError: c of shape (1, 3) not acceptable as a color sequence for x with size 1, y with size 1
```

**Matplotlib version**

  * Operating system: Ubuntu 16.04
  * Matplotlib version: commit 7b5ff33   (master, 23 Aug 2018)
  * Matplotlib backend (`print(matplotlib.get_backend())`):  <object object at 0x7f8885d87190>
  * Python version: 3.5.5
  * Jupyter version (if applicable): none
  * Other libraries: numpy

How I installed matplotlib:

1. Create new conda env with python 3.5.5
2. git clone matplotlib master
3. pip install -e /path/to/cloned-repo

### PR DESCRIPTION
**Pull request by efiring**
Closes #11919.

## PR Checklist

- [x] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I don't think this really improves the situation?  With this PR
```
scatter(np.array([1, 2, 3]), np.array([3, 4, 5]), c=np.array([[120,130,140]]))
```
gives
```
ValueError: 'c' argument must be a color, a sequence of colors, or a sequence of numbers, not [[120. 130. 140.]]
```
but this value of `c` *is* a sequence of number in the sense of `scatter` (which will flatten them): for example
```
scatter(np.array([1, 2, 3]), np.array([3, 4, 5]), c=np.array([[120,130,140]]))
```
works just fine.

**Comment by efiring** [comment]
If you look at the docstring, in particular the note section, you will find that in the example in question, and in the test I added, c is not supposed to be flattened, and indeed it isn't.  Therefore the change I made brings the error message into sync with the docstring and its intent, which is that if c is a 2-d array, and it's first dimension matches x.size, then it will be treated as a sequence of RGB or RGBA--or at least the attempt will be made. At that point, color mapping is out of the question, and the failure is not a color mapping size mismatch.

**Comment by anntzer** [comment]
Right now the docstring reads
```
         c : color, sequence, or sequence of colors, optional
            The marker color. Possible values:

            - A single color format string.
            - A sequence of colors of length n.
            - A scalar or sequence of n numbers to be mapped to colors using
              *cmap* and *norm*.
            - A 2-D array in which the rows are RGB or RGBA.
```
but that's not really true: something like
```
scatter(range(6), range(6), c=np.array([[10, 20, 30], [40, 50, 60]]))
```
and there `c` is 2D and gets flattened.

Thus, if we take the docstring at its word, for the purposes of scatter, "sequence of n numbers" (to be mapped to colors) includes 2d-arrays that get flattened.  I don't agree with this choice, but that's irrelevant here.

But then the error message "'c' argument must be a color, a sequence of colors, or a sequence of numbers, not [[120. 130. 140.]]" doesn't make sense, because [[120. 130. 140.]] is such a "sequence".

Or you need to fix third item of the docstring...

**Comment by efiring** [comment]
This isn't worth any more time.

**Pull request closed without merging**
