### PR TITLE
DOC: fix autoscale docstring

### LINKED ISSUE #18662: Inconsistent setting of axis limits with autoscale=False
### Bug report

**Bug summary**

When setting `ax.set_autoscaley_on(False)` before a call to `ax.get_ylim()`, y-limits are set to the default [0, 1] despite data already being drawn outside this range while without setting autoscale to False all data would be displayed properly. Matplotlib appears to mix up the order of the given instructions.

**Code for reproduction**

```python
_, axes = plt.subplots(2, 1, sharex=True)

for ax, pdata in zip(axes, [data[:, :3], data[:, 3:]]):
    ax.plot(pdata, lw=1)
    ax.set_autoscaley_on(False)
    l, = ax.plot([500, 500], ax.get_ylim(), 'k')
    
_ = ax.set_ylim(-3, 3)
```

**Actual outcome**
grafik

**Expected outcome**
(without `_ = ax.set_ylim(-3, 3)`)
grafik

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.3.1, 3.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): notebook, qt5, inline
  * Python version: 3.8, 3.7
  * Jupyter version (if applicable): 1.0.0, notebook 6.1.4

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

The previous versions made it sound like this would be applied per plot command, whereas the autoscale_on really is applied at draw time.

Closes #18662

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Render: https://47103-1385122-gh.circle-artifacts.com/0/doc/build/html/api/_as_gen/matplotlib.axes.Axes.set_autoscale_on.html#matplotlib.axes.Axes.set_autoscale_on

**Review by dopplershift — APPROVED** [review]

**Comment by QuLogic** [comment]
This only changed because it was made lazy; maybe we _want_ it to re-scale when disabling it?

**Comment by jklymak** [comment]
Oh, hmmm.  If we do:

```
import matplotlib.pyplot as plt
import numpy as np

fig, axes = plt.subplots(2, 1, sharex=True)

for i in range(2):
    ax = axes[i]
    ax.plot(np.random.randn(1000), lw=1)
    #fig.canvas.draw()
    l, = ax.plot([500, 500], ax.get_ylim(), 'k')
    # ax.autoscale_view()
    ax.set_autoscaley_on(False)

ax.set_ylim(-3, 3)
plt.show()
```
Then the limits are correct.  So I think `get_ylim` calls the autolim machinery.  

I don't think that we want to have `set_autoscale_on` do anything other than tell `auto

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
@dopplershift @jklymak If you think that there is an issue with the auto scaling behavior, please open a separate issue\PR. I've merged this as a doc improvement.

**Pull request merged**
