### PR TITLE
Fix empty plot with drawstyle="steps"

### LINKED ISSUE #9597: Plot with `drawstyle="steps"` fails if x and y are empty
### Bug report

**Bug summary**

Occasionally, when I call `plot(x,y)`, I pass in lists or arrays of size zero with the expectation that this is a blank plot. When I call `plot(np.array([]), np.array([]))`, I get an empty plot as desired. When I call `plot(np.array([]), np.array([]), drawstyle="steps")`, I get an exception instead.

**Code for reproduction**

```python
plot(np.array([]), np.array([]), drawstyle="steps")
```

**Actual outcome**

```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-0dd20fbcfdd7> in <module>()
----> 1 plot(np.array([]), np.array([]), drawstyle="steps")

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.pyc in plot(*args, **kwargs)
   3238                       mplDeprecation)
   3239     try:
-> 3240         ret = ax.plot(*args, **kwargs)
   3241     finally:
   3242         ax._hold = washold

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/__init__.pyc in inner(ax, *args, **kwargs)
   1708                     warnings.warn(msg % (label_namer, func.__name__),
   1709                                   RuntimeWarning, stacklevel=2)
-> 1710             return func(ax, *args, **kwargs)
   1711         pre_doc = inner.__doc__
   1712         if pre_doc is None:

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.pyc in plot(self, *args, **kwargs)
   1436 
   1437         for line in self._get_lines(*args, **kwargs):
-> 1438             self.add_line(line)
   1439             lines.append(line)
   1440 

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in add_line(self, line)
   1757             line.set_clip_path(self.patch)
   1758 
-> 1759         self._update_line_limits(line)
   1760         if not line.get_label():
   1761             line.set_label('_line%d' % len(self.lines))

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/axes/_base.pyc in _update_line_limits(self, line)
   1779         Figures out the data limit of the given line, updating self.dataLim.
   1780         """
-> 1781         path = line.get_path()
   1782         if path.vertices.size == 0:
   1783             return

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/lines.pyc in get_path(self)
    949         """
    950         if self._invalidy or self._invalidx:
--> 951             self.recache()
    952         return self._path
    953 

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/lines.pyc in recache(self, always)
    682         else:
    683             interpolation_steps = 1
--> 684         xy = STEP_LOOKUP_MAP[self._drawstyle](*self._xy.T)
    685         self._path = Path(np.asarray(xy).T,
    686                           _interpolation_steps=interpolation_steps)

/Users/redoubts/anaconda/lib/python2.7/site-packages/matplotlib/cbook/__init__.pyc in pts_to_prestep(x, *args)
   2183     >> x_s, y1_s, y2_s = pts_to_prestep(x, y1, y2)
   2184     """
-> 2185     steps = np.zeros((1 + len(args), 2 * len(x) - 1))
   2186     # In all `pts_to_*step` functions, only assign *once* using `x` and `args`,
   2187     # as converting to an array may be expensive.

ValueError: negative dimensions are not allowed
```

**Expected outcome**

```python
plot(np.array([]), np.array([]))
>>> [<matplotlib.lines.Line2D at 0x124f79f10>]
```

**Matplotlib version**

  * Operating system: OS X 10.13
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version:  2.7.14 |Anaconda, Inc. (5.0.1) | 

Using a stock anaconda 5.0.1 meta package w/ p2.7 install.

### PR DESCRIPTION
**Pull request by timhoffm**
Fixes #9597 as suggested there in the comments.

### CODE REVIEW

**Comment by jklymak** [comment]
@timhoffm Can you add a test so this doesn't break in the future?  Could probably just check that the call doesn't error...

**Comment by jklymak** [comment]
@timhoffm Does this make it through to `plot`, and can a test be added to `test_axes.py`?  

```
plot(np.array([]), np.array([]), drawstyle="steps")
```

**Comment by timhoffm** [comment]
Yes it does. I've intentionally only added unit tests for the `pts_to_*step` functions. These were the ones failing. We shouldn't add full integration tests for all possible inputs. This really slows the test suite down.

**Comment by jklymak** [comment]
Ok I’m not sure what the testing philosophy is/should be.  To me if it broke once it’ll break again and having a test will stop that. If you can make the test a non-image test I don’t think it takes very long.

**Comment by timhoffm** [comment]
The things that was broken, were the `pts_to_*step` functions. And they are tested now, so they can't break again.

Unfortunately, every axes instantiation is quite slow #6664. For a single plot, this doesn't take too long, but it really adds up for several thousand tests.

**Comment by jklymak** [comment]
Just to carry on this discussion:  to me, its the user-facing features that need to keep working.  Someone could decide to do away with `pts_to_pre` etc, and implement `steps=` in a different way, but the user-experience in `plot` shouldn't change (or at least we should know it breaks a test).

**Comment by anntzer** [comment]
I think the test is fine.
Thanks!

**Pull request merged**
