### PR TITLE
Force html4 writer for sphinx 2

### LINKED ISSUE #13591: Style issues when building the docs with (future) Sphinx 2.0
### Bug report

I've just build the matplotlib docs with sphinx master (future 2.0) and some of the styling has gone bad:

***Edit:* Let's collect all the doc rendering problems in this issue, so that we know what we have to fix later on:**

#### List of issues:

- [x] Numpydoc parameters section title rendered incorrectly (see below in this comment, @dstansby: fixed in sphinx 2.1.2)
- [x] No space between parameter names and types in numpydoc parameters sections (see below in this comment, upstream bug: https://github.com/numpy/numpydoc/issues/215, , fix in #14105).
- [x] Some headlines broken (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478238632, fixed in sphinx 2.1)
- [x] Wrapping after bullet points in table of contents (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478263720, fix in #14105)
- [ ] Table rendering (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478264291)
- [ ] Rendering of list of methods (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478264615)
- [x] Search is broken (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478306881, fixed in sphinx 2.0.1)

### Issue: Numpydoc parameters section

image

[ ] Need to check if there will style changes in sphinx 2.0 and possibly adapt mpl.css.

### PR DESCRIPTION
**Pull request by dstansby**
Sphinx 2 by default uses a `html5` writer, that changes the outputted html, causing the issues mentioned in #13591. In order to allow the use of sphinx 2, without having to change our CSS,  makes sphinx 2 use the `html4` writer that sphinx 1 also uses.

Possibly we will want to migrate/upgrade to the `html5` writer, but changing the CSS to match is a pain (see #14105  for my aborted attempt to do this) so this provides a solution to use sphinx 2 in the medium term.

Fixes #13591

### CODE REVIEW

**Comment by timhoffm** [comment]
Could you please give a little more context? Does the patch fix all sphinx 2 issues? Do we want/need a strategy to migrate to html5 later on?

**Comment by dstansby** [comment]
Sorry, have updated the original comment above. I've also re-targeted this to `3.3.0`, since I think we should give it a bit of time for any potential issues to be discovered on `devdocs` before using this in a release.

**Comment by NelleV** [comment]
Thanks @dstansby !
Should we open a ticket for the html5 migration or is it already opened?

**Comment by tacaswell** [comment]
It is on master and we haven't branched yet (probably tonight) so it will be in 3.2.

**Pull request merged**
