### PR TITLE
Deprecate two-args for cycler() and set_prop_cycle()

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Following a discussion in #10662, this deprecates the two-arg forms
- ``rcsetup.cycler(label, values)``
- ``Axes.set_prop_cycle(label, values)``
in favor of their keyword equivalents
- ``rcsetup.cycler(label=values)``
- ``Axes.set_prop_cycle(label=values)``

## PR Checklist

- [x] Code is PEP 8 compliant
- [x] Documentation is sphinx and numpydoc compliant
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
-1

**Comment by timhoffm** [comment]
@WeatherGod Can you please elaborate on your -1?

**Comment by WeatherGod** [comment]
As discussed previously, the two-arg form is not broken. Also, the form comes from the cycler package and was the original form. Many users learn how to use cyclers from that package's documentation, not ours. If you feel strongly about deprecating a non-broken API design, then do it there first. Otherwise, you will just cause confusion.

In addition, do not change the unit tests! The feature has not been removed (indeed, you didn't even set a removal date). Therefore, it must continue to be supported until (if) it gets removed. I seriously question the need to do this.

The argument of "there must be only one way to do it" isn't a hard-and-fast rule. Look at the many ways that exists to create a dictionary in python. You can pass keyword arguments. You can pass a sequence of tuples. Dictionary comprehensions. As well as literal dictionary construction. Each form has its pros-and-cons, and I am glad they all exist. It gives me the flexibility to create a dictionary in a manner that fits well with the situation.

**Comment by timhoffm** [comment]
I acknowledge you have a strong position on this as well. :smiley: 

> If you feel strongly about deprecating a non-broken API design, then do it there first. Otherwise, you will just cause confusion.

I don't think, it's possible to remove the two-arg form from the original cycler. There's exactly one reason for it. According to its docs:

> This is useful for when the label cannot be a keyword argument (e.g., an integer or a name that has a space in it).

Removing would cut functionality. However, in matplotlib we don't have this use-case. Property names can always be keywords.

**Where do we go from here?**
I want new users to learn and use the kwarg API. It's more pythonic, and more flexible (works with one and multiple properties). I'm not dogmatic about deprecating the two-arg form if it's too difficult for a reason.

So, I propose the following compromise:
- Don't deprecate anything.
- Make the two-arg form only the third alternative instead of the second in the docstrings (This is already the case for the [original cycler](https://matplotlib.org/cycler/generated/cycler.cycler.html#cycler.cycler)).
- Rewrite the examples to use kwargs.
- Leave the unit tests alone (though most of the tests are two-arg - probably for historic reasons. And testing one would be as good as the other. I'll leave it, hoping that nobody learns from the unit tests).

**Comment by WeatherGod** [comment]
I would be perfectly fine with that compromise.

**Comment by timhoffm** [comment]
Will do a new PR tomorrow.

**Pull request closed without merging**
