### PR TITLE
DOC: Add a plot to margins() to visualize the effect

### PR DESCRIPTION
**Pull request by timhoffm**

### CODE REVIEW

**Comment by jklymak** [comment]
This seems like a complicated example for the ApI docs?  Would we not prefer just a link-out here to a standalone example?

**Comment by timhoffm** [comment]
The code does not show up in the rendered docs:

https://output.circle-artifacts.com/output/job/00757267-8a4a-46fe-96a5-f087064abf30/artifacts/0/doc/build/html/api/_as_gen/matplotlib.axes.Axes.margins.html#matplotlib.axes.Axes.margins

we could alternatively embed a static image, but it's slightly simpler to adapt/maintain from code, and it's and "added feature" that an interested user can get the source via link. If you're concerned about raw docs, we could put the code into a separate file and

```
.. plot:: margins_illustration.py
```

**Comment by timhoffm** [comment]
New version:

grafik

and plot code separated to a file not not spam the raw docs too much.

**Comment by jklymak** [comment]
This is probably fine, though a link would work for rendered and raw docs.  However the docs are not building on this pr

**Comment by timhoffm** [comment]
Links sound better than they are for raw docs. A link would look like `:doc:`/gallery/some_subgallery/margins. You cannot do anything useful with it from an interpreter. You have to go to the browser *and* find out how the link translates to an URL. I claim it's then simpler to go to the browser and open the `margins()` docs.

Another issue with putting this into the gallery as is, is that the plot is specifically designed for the visual result, it's not an instructive code example for margins.

This PR specifically, makes `margins()` more understandable by itself. I see it as reasonable incremental improvement for that limited scope. A more complete "explanation doc" on limit handling would be useful. This is on of the topics tracked in #20984.

**Pull request merged**
