### PR TITLE
ENH: make antialiased gifs for Tk, and remove unused image files

### LINKED ISSUE #6610: Icons for Tk are not antialiased.
As pointed out here https://github.com/matplotlib/matplotlib/pull/5626#issuecomment-226927789 the new icons are particularly ugly with the Tkagg backend.  The reason is that Tk is using the ppm versions, which are not antialiased.  One solution would be to use, e.g., 
```
convert -antialias -geometry 24x24 back.svg back.gif
```
etc. to generate antialiased gif files to replace the ppm files, and then change one line in backend_tkagg.py so that it will use these files.

In addition, the old and now unused xpm files can be deleted.

### PR DESCRIPTION
**Pull request by efiring**
Closes #6610.

### CODE REVIEW

**Comment by QuLogic** [comment]
Why is it called `hand.*` when it's a cross in a circle? And where is that even used?

**Comment by efiring** [comment]
Good question, and I don't know the answer.  I think it might be the cursor for pan/zoom.  Or maybe it is a fossil.

**Comment by tacaswell** [comment]
:+1: I checked with tk and this does look much better

**Comment by tacaswell** [comment]
I did a quick look and I can not find any use of the hand icon (`git grep hand[^l]` returns only a few hits).  

Looking at `backend_tkagg` the file 'move' has been used for panning as far back as the git history goes (shows up in e34a333d00814124d3e19d462b9d78ac35e7a49a) but the comments at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L2795 imply that hand used to used for panning.  That comment also (with minor formatting changes) goes back to e34a333d00814124d3e19d462b9d78ac35e7a49a .

99% sure that the whole hand set is a fossil that we can safely remove.  There might be some third-party backends out there that use it?

**Comment by tacaswell** [comment]
I am in favor of merging this as-is and dealing with removing hand later.

Do we want to put in an API note for removing the xpm and ppm files?

**Comment by efiring** [comment]
I see those files as internal implementation details, not API; they were never intended for use outside matplotlib.

**Comment by efiring** [comment]
I see those files as internal implementation details, not API; they were never intended for use outside matplotlib, as far as I know.

**Pull request merged**
