### PR TITLE
Support unhashable callbacks in CallbackRegistry

### LINKED ISSUE #26012: [Bug]: "Unhashable type" when event callback is a method of a `dict` subclass
### Bug summary

I've got a class `Charts` that uses `self.fig.canvas.mpl_connect('key_press_event', self.sendEvent)` to handle keypresses, which works fine. But recently I tried changing my class to subclass `dict`, and – oddly – this seems to confuse Matplotlib. I get the error:

```
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/helipad/visualize.py", line 72, in launch
    self.fig.canvas.mpl_connect('key_press_event', self.sendEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2476, in mpl_connect
    return self.callbacks.connect(s, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/cbook/__init__.py", line 228, in connect
    if proxy in self._func_cid_map[signal]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'Charts'
```

Which is weird because I'm not passing `Charts` at all.
Looking at MPL's code, it looks like the `_weak_or_strong_ref` function is getting a reference to `Charts` back out of the method I passed as a callback, putting it in the `proxy` variable, and hashing it, which subclassing `dict` prevents it from doing. 

### Code for reproduction

```python
import matplotlib.pyplot as plt

class ThisWorks:
	def __init__(self):
		self.fig, plots = plt.subplots(1)
		self.fig.canvas.mpl_connect('key_press_event', self.sendEvent)
		self.keyListeners = {}

	def sendEvent(self, event):
		if event.name=='key_press_event' and event.key in self.keyListeners:
			for f in self.keyListeners[event.key]: f(self.model, event)

class ThisDoesntWork(ThisWorks, dict): pass

x = ThisDoesntWork()
```

### Actual outcome

```
Traceback (most recent call last):
  File "/Users/charwick/Desktop/example.py", line 15, in <module>
    x = ThisDoesntWork()
        ^^^^^^^^^^^^^^^^
  File "example.py", line 6, in __init__
    self.fig.canvas.mpl_connect('key_press_event', self.sendEvent)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/backend_bases.py", line 2476, in mpl_connect
    return self.callbacks.connect(s, func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/matplotlib/cbook/__init__.py", line 227, in connect
    if proxy in self._func_cid_map[signal]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'ThisDoesntWork'
```

### Expected outcome

Code above doesn't actually do anything, but it shouldn't generate an error.

### Additional information

_No response_

### Operating system

MacOS 13.3.1

### Matplotlib Version

3.7.1

### Matplotlib Backend

_No response_

### Python version

3.11.3

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by anntzer**
## PR summary

Closes #26012.

The first two commits are cleanup-ish:

- Record the connected signal in CallbackRegistry weakref cleanup function, to remove the need to loop over all signals in _remove_proxy.
- Flatten CallbackRegistry._func_cid_map: It is easier to manipulate a flat (signal, proxy) -> cid map rather than
a nested signal -> (proxy -> cid) map (especially for the third commit).

The last commit implements support for unhashable callbacks, by replacing _func_cid_map by a dict-like structure (_UnhashDict) that also supports unhashable entries.
Note that _func_cid_map (and thus _UnhashDict) can be dropped if we get rid of proxy deduplication in CallbackRegistry (#20210).

---

edit: ah, the joys of type-checking 😑 (https://github.com/python/mypy/issues/4266)

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
I am not convinced this is a good idea, but looks technically correct.

**Comment by tacaswell** [comment]
After discussion with @ksunden , we think it is simpler to fully remove `self._func_cid_map` and pay the cost of a linear search over `self.callbacks` when we need to rather than to have an very weird dictionary relative.

**Comment by anntzer** [comment]
Did you consider #20210 as well?

**Comment by tacaswell** [comment]
We would still need the linear search in the `_remove_proxy` callback on the weak/strong ref.

**Comment by anntzer** [comment]
Not if you also record the proxy's cid in the weakref callback, similarly to how I record the signal name at https://github.com/matplotlib/matplotlib/pull/26013/commits/b629ff86f2b62258ea8d661db72279c5e4732ff4#diff-84a45e2dda93ad4c1d950da5c16846965aa8d96aebfe8d00acaeb83a18c1b2f0R215?  (Fortunately, per the weakref docs: "If the referents are still alive, two references have the same equality relationship as their referents (regardless of the callback".)

**Comment by tacaswell** [comment]
you are correct.  I went through a couple of versions of injecting the cid that did not work but did not make it to `partial`.....

**Comment by anntzer** [comment]
The patch is basically
```patch
diff --git i/lib/matplotlib/cbook.py w/lib/matplotlib/cbook.py
index 4d6dc04a9b..7c1b0ef246 100644
--- i/lib/matplotlib/cbook.py
+++ w/lib/matplotlib/cbook.py
@@ -107,7 +107,7 @@ class _StrongRef:
         return hash(self._obj)
 
 
-def _weak_or_strong_ref(func, callback):
+def _weak_or_strong_ref(func, callback=None):
     """
     Return a `WeakMethod` wrapping *func* if possible, else a `_StrongRef`.
     """
@@ -204,7 +204,8 @@ class CallbackRegistry:
         cid_count = state.pop('_cid_gen')
         vars(self).update(state)
         self.callbacks = {
-            s: {cid: _weak_or_strong_ref(func, functools.partial(self._remove_proxy, s))
+            s: {cid: _weak_or_strong_ref(func,
+                                         functools.partial(self._remove_proxy, s, cid))
                 for cid, func in d.items()}
             for s, d in self.callbacks.items()}
         self._func_cid_map = {
@@ -217,10 +218,15 @@ class CallbackRegistry:
         if self._signals is not None:
             _api.check_in_list(self._signals, signal=signal)
         self._func_cid_map.setdefault(signal, {})
-        proxy = _weak_or_strong_ref(func, functools.partial(self._remove_proxy, signal))
+        # First check whether we're actually going to add the callback.  This
+        # relies on weakref comparison not taking the weakref destruction
+        # callback (which includes the cid here) into account.
+        proxy = _weak_or_strong_ref(func)
         if proxy in self._func_cid_map[signal]:
             return self._func_cid_map[signal][proxy]
         cid = next(self._cid_gen)
+        proxy = _weak_or_strong_ref(func,
+                                    functools.partial(self._remove_proxy, signal, cid))
         self._func_cid_map[signal][proxy] = cid
         self.callbacks.setdefault(signal, {})
         self.callbacks[signal][cid] = proxy
@@ -238,16 +244,14 @@ class CallbackRegistry:
 
     # Keep a reference to sys.is_finalizing, as sys may have been cleared out
     # at that point.
-    def _remove_proxy(self, signal, proxy, *, _is_finalizing=sys.is_finalizing):
+    def _remove_proxy(self, signal, cid, proxy, *, _is_finalizing=sys.is_finalizing):
         if _is_finalizing():
             # Weakrefs can't be properly torn down at that point anymore.
             return
-        cid = self._func_cid_map[signal].pop(proxy, None)
-        if cid is not None:
-            del self.callbacks[signal][cid]
-            self._pickled_cids.discard(cid)
-        else:  # Not found
-            return
+        if self._func_cid_map[signal].pop(proxy, None) is None:
+            return  # Not found.
+        del self.callbacks[signal][cid]
+        self._pickled_cids.discard(cid)
         # Clean up empty dicts
         if len(self.callbacks[signal]) == 0:
             del self.callbacks[signal]
```
where the need for pickling is really restricted only to _func_cid_map (i.e. deduplication) now.

Even if we really want to support an option for deduplication (which I would say should not be the default) per https://github.com/matplotlib/matplotlib/issues/20210#issuecomment-1865879419, we could just fall back to linear search for that case only.

**Comment by anntzer** [comment]
@tacaswell perhaps I'll close this and let you take it over?

**Review by tacaswell — APPROVED** [review]
Following up, no further work has materialized, this adds some complexity, but does not break any existing behavior and fixes a thing that would be reasonable that it worked.

We can leave the de-duplication work for later (and punt simplifying it to then).

**Comment by tacaswell** [comment]
power-cycled to re-run the tests.

**Pull request merged**
