### PR TITLE
Change `savefig.dpi` and `figure.dpi` defaults

### PR DESCRIPTION
**Pull request by three-comrades**
Change the default values for `savefig.dpi` and `figure.dpi` as suggested in #305.

```
savefig.dpi: 100 -> 'figure'
figure.dpi: 80 -> 100
```

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: from me

**Comment by efiring** [comment]
Cherry-picked to v2.0.x as a903315. @tacaswell, did I do that correctly?

**Comment by mdboom** [comment]
@efiring: We've been cherry-picking the merge commit (which in this case is 6333526) rather than the individual commits (in this case 016406a).  I think you did the latter.  It's not a huge difference, but it does keep a mention in the logs of which PR a feature came from for later reference if you do the former.  It's also easier to merge a multi-commit PR that way.

**Comment by efiring** [comment]
@mdboom,  OK, that makes sense, thank you.  That requires using the "-m parent" option to the "git cherry-pick" command, doesn't it?  How does one know the parent number?

**Comment by tacaswell** [comment]
It is always parent 1 because we are meeting things into master

**Comment by efiring** [comment]
Travis is complaining about the original commit, but it seems unrelated to the actual file changes.  Should I be worried?
```
ERROR: matplotlib.tests.test_axes.test_loglog.test

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/matplotlib-1.5.0+127.ga903315-py3.5-linux-x86_64.egg/matplotlib/testing/decorators.py", line 54, in failer

    result = f(*args, **kwargs)

  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/matplotlib-1.5.0+127.ga903315-py3.5-linux-x86_64.egg/matplotlib/testing/decorators.py", line 235, in do_test

    self._tol, in_decorator=True)

  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/matplotlib-1.5.0+127.ga903315-py3.5-linux-x86_64.egg/matplotlib/testing/compare.py", line 306, in compare_images

    raise IOError('Baseline image %r does not exist.' % expected)

OSError: Baseline image '/home/travis/build/matplotlib/matplotlib/result_images/test_axes/loglog-expected.png' does not exist.
```

**Comment by tacaswell** [comment]
Something seems to have gone wrong with that file, #5652 had the same issue.

**Comment by three-comrades** [comment]
Hm, strange. It seems like only AppVeyor was run.

**Pull request merged**
