### PR TITLE
Remove useless semicolons in "Introductory / Basic Usage" tutorial

### PR DESCRIPTION
**Pull request by gustavi**
## PR Summary

Remove useless semicolons in tutorial https://matplotlib.org/stable/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py.

## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [n/a] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for your work on this, however I do not think that these are useless. They are suppressing the output of the last line. See https://output.circle-artifacts.com/output/job/faf7ca9d-7305-4f7c-95e9-8d736399fd79/artifacts/0/doc/build/html/tutorials/introductory/quick_start.html#a-simple-example

which now has (I had it highlighted when I took the screen shot)

image

after the figure which is not particularly useful or informative (if we had better reprs that would be a different matter, but).

**Comment by tacaswell** [comment]
On second thought, that output is also in https://matplotlib.org/3.6.0/tutorials/introductory/quick_start.html#a-simple-example which is counter to what I expected so maybe they are useless...

There is clearly something I do not understand about sphinx-gallery here.

**Comment by QuLogic** [comment]
Yes, @jklymak added these on purpose to suppress the output #21794, but they didn't seem to have worked.

**Comment by timhoffm** [comment]
I would make sense to discuss with sphinx-gallery to make showing outputs configurable. Even if the semicolon worked it can be a little confusing for users not familiar with it.

Ideally that option could be configured on a global/file/block basis and be overridden by the more specific ones; i.e. global=off, this block=on.

**Comment by StefRe** [comment]
You can now configure `capture_repr `on file-by-file basis, see https://github.com/sphinx-gallery/sphinx-gallery/pull/891. It just didn't have the time to apply this to the matplotlib docs.

**Comment by StefRe** [comment]
> There is clearly something I do not understand about sphinx-gallery here.

@tacaswell : as I explained in https://github.com/sphinx-gallery/sphinx-gallery/pull/891: putting a semicolon after the last expression doesn't work here as the code is first compiled into an AST and then the last expression is taken from the tree where the semicolon as code delimiter isn't present, see [code](https://github.com/sphinx-gallery/sphinx-gallery/blob/9a09fc1377de833db9f1d7f23686e37c3d7a02dc/sphinx_gallery/gen_rst.py#L573-L574).

**Comment by timhoffm** [comment]
Superseded by #23978 .

@gustavi Rgank you for your effort, even though we found different solution to solve the issue.

**Comment by StefRe** [comment]
@timhoffm in fact the PR is still valid - the semicolons are useless in this case (see https://github.com/matplotlib/matplotlib/pull/23796#issuecomment-1242690563) and should be removed (along with the corresponding flake ignore)

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
@StefRe thanks for the correction.

**Review by tacaswell — APPROVED** [review]

**Comment by timhoffm** [comment]
Thanks @gustavi, and congratulations on your first contribution to Matplotlib!

**Pull request merged**
