### PR TITLE
Make pyplot more tolerant wrt. 3rd-party subclasses.

### PR DESCRIPTION
**Pull request by anntzer**
Don't force them to reproduce the names of "intended-as-positional"
arguments; don't force them to support the data kwarg.

xref #12288

attn @QuLogic can you pick it up from there if more changes are needed?

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
It's going to be pretty tricky to test this unless we make a copy of all pyplot signatures somewhere else to compare against, which sounds not so nice.

**Comment by jklymak** [comment]
I don’t think they all have to be tested just a smattering to make sure the boilerplate is doing the right thing. 

I do t understand what you mean by copying all the pyot signatures but maybe I’m misunderstanding what is going on here

**Comment by anntzer** [comment]
It's not clear to me what test you exactly want to add either...

**Comment by jklymak** [comment]
Ideally there would be some tests that would have failed #10918, which presumably means duplicating whatever signature cartopy was trying to use.  But again if there is a more informed critical mass of devs who don't think this is possible they should feel free to dismiss my review.  I'm not claiming deep understanding

**Comment by QuLogic** [comment]
I have not gone through the changes, but this is sufficient to get Cartopy tests working again. Keep in mind that Cartopy does not of course exercise the entirety of the `pyplot` API, just the following:
```
$ rg --no-filename -o 'plt\.[A-Za-z0-9_]+' | sort -u
plt.autoscale
plt.axes
plt.clf
plt.close
plt.contour
plt.contourf
plt.draw
plt.figure
plt.gca
plt.gcf
plt.get_backend
plt.imread
plt.imshow
plt.pcolor
plt.pcolormesh
plt.plot
plt.savefig
plt.scatter
plt.show
plt.subplot
plt.subplots_adjust
plt.switch_backend
plt.xlim
plt.ylim
```

**Comment by anntzer** [comment]
TBH I am not particularly interested in figuring out how to do implement a test.

**Comment by jklymak** [comment]
> TBH I am not particularly interested in figuring out how to do implement a test (especially wrt what guarantees we want to make regarding the subclassability of Axes).

I think all I'm asking for are tests that test the allowed signatures, which I think is where the downstream subclasses are tripping up.  But again, anyone who understands this better can dismiss my review if I'm off base about the testability of this.

**Comment by anntzer** [comment]
Can you open the request for tests as a separate issue instead?

**Comment by anntzer** [comment]
Can you push it?

**Comment by dstansby** [comment]
Done!

**Pull request merged**
