### PR TITLE
Update table.py

### PR DESCRIPTION
**Pull request by jcolonese**
On topic: https://github.com/matplotlib/matplotlib/issues/5350

### CODE REVIEW

**Comment by mdboom** [comment]
This looks great, and congrats on your first matplotlib pull request!

It would be nice to add a test -- i.e. something that failed before this change but works after it.  There's information on writing tests [here](http://matplotlib.org/devel/testing.html), but let us know if you have any questions.

**Comment by jcolonese** [comment]
thanks Michael, as user it's really nice to contribute somehow even in as simple issue like this. I'll prepare a test based on what I was doing when found the problem.

**Comment by tacaswell** [comment]
@jcolonese Any update on the test?

**Comment by tacaswell** [comment]
@jcolonese A commit with identical content was merged in #7520 , sorry this fell by the wayside.

I am going to close this as it has been superseded, hopefully we will here from you again!

**Pull request closed without merging**
