### PR TITLE
Make set_yscale("log") consistent with semilogy()

### LINKED ISSUE #8045: setting yscale to log, after drawing a plot with values equal to zero, results in incorrect handling of zero values
mpl 1.5.3 and 2.0, py3.6
```
_xs = np.linspace(-50, 50, 1001); plt.semilogy(scipy.stats.norm.pdf(_xs))
```
results in
figure_1
where zero values (due to floating point resolution limits, at the edges) get ignored, as expected, but
```
_xs = np.linspace(-50, 50, 1001); plt.plot(scipy.stats.norm.pdf(_xs))
plt.gcf().canvas.draw()
plt.gca().set(yscale="log")
```
results in the incorrect
figure_2

### PR DESCRIPTION
**Pull request by dstansby**
This is an update of  #8056, which fixes #8045 - I have now added the new test image, which should make the tests pass. Thanks to @jcalbert for the original fix.

### CODE REVIEW

**Comment by phobson** [comment]
If you remove the re-generated image, does it pass? (I can't spot the differences in the github UI)

```
          ImageComparisonFailure: images not close (RMS 0.044):
          	result_images/test_axes/log_scales_svg.png
          	result_images/test_axes/log_scales-expected_svg.png
```

**Comment by dstansby** [comment]
It seems to be the svg image (not the png one, which I updated) which is failing.

It's not failing locally on my OSX machine, and isn't failing on the OSX build either, so there must be a difference between linux and OSX when it comes to svg.

**Comment by phobson** [comment]
@dstansby maybe you need regenerate the SVG too.

**Comment by dstansby** [comment]
It's not failing on my machine, so I have no way to regenerate it! I presume if a linux box regenerated it the OSX build would fail?

**Comment by dstansby** [comment]
(note to myself to restart travis when #8672 gets merged)

**Comment by anntzer** [comment]
@dstansby done for you.

**Comment by dstansby** [comment]
Restarting travis didn't move the build to 14.04, so manually cycling the PR.

**Comment by dstansby** [comment]
Huh, still no luck on travis, will try and see what happens on a local linux box at some point.

**Comment by tacaswell** [comment]
Can you check the history of why this was changed to clip?  I have a vague memory that there was a long discussion at the time...

**Comment by dstansby** [comment]
It was originally changed to fix https://github.com/matplotlib/matplotlib/issues/163#issue-1087901 - changing it back will break that problem, so I adding the code in that comment as a test would be a good idea.

**Comment by tacaswell** [comment]
I do not see what changed about the test image...

**Comment by efiring** [comment]
I think the basic idea of this--essentially reverting #2147 and thereby restoring problematic errorbar behavior (#163)--will have to be noted, and we will have to be prepared for someone to raise the issue again.  Overall I think it is an improvement, though.

I think that the errorbar problem could be fixed in the errorbar code in this way: for any errorbar covering a range from negative to positive values, insert a point in the Line2D at 1e-300.  It would have no effect with a linear scale, and with a log scale it would allow a line to be plotted after the negative end-point is masked out. Worth the trouble?  I'm not sure.

**Comment by tacaswell** [comment]
I am in favor of:

 - reverting #2147 (with an API changes documentation)
 - adding a note to the errorbar docstring that, by default, errorbars which go negative will be clipped on log scales

**Pull request closed without merging**
