### PR TITLE
Boxplot concept figure update

### PR DESCRIPTION
**Pull request by rasbt**
Fixed a typos according to #5889

### CODE REVIEW

**Comment by tacaswell** [comment]
A tad concerned about the size increse.

**Comment by WeatherGod** [comment]
Yeah, we should make sure it looks ok in the docs.

**Comment by rasbt** [comment]
I exported it as 300 ppi figure this time, but I can rescale it to the size of the "original" image. I think the previous format was fine!? Also, it would reduce the page load time and help keeping the matplotlib repo "slim." What do you think and suggest?

**Comment by tacaswell** [comment]
That sounds good.  Please make use a force-push to make sure that the larger image never ends up in the history.

**Comment by rasbt** [comment]
I think it should be fine now.

**Comment by WeatherGod** [comment]
The copyright year is incorrect. Also, is this getting updated on wikimedia?

**Comment by rasbt** [comment]
> The copyright year is incorrect.
Right, should have changed the data after making these corrections.

> Also, is this getting updated on wikimedia?
I haven't uploaded it to wikimedia

**Comment by rasbt** [comment]
The date stamp should be okay now.

**Comment by jenshnielsen** [comment]
Backported to 1.5.1-doc as 1e55809ca6f57b8846200d8f27b767a80abd6089

**Comment by jenshnielsen** [comment]
Thanks

**Pull request merged**
