### PR TITLE
Improve PDF metadata support in PGF

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

The PGF backend only supported PDF metadata using the multi-page `PdfPages` class; this adds support for adding metadata to single-figure saving directly via `savefig`.

Additionally, refactor the metadata support from the PDF side into a common function to setup and verify metadata that can be used in the PGF side as well. This ensures that the same set of keys is allowed, which weren't before.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: In principle, but I think that this should get some through tests while we are thinking about it.

Do we want to push this to 3.4 or try to squeeze it in for 3.3?

**Comment by QuLogic** [comment]
This is difficult to test, because unlike the builtin PDF export, the PGF backend uses latex, which has no `pdf.compression` setting, and all the metadata is compressed. You can check in evince that the metadata is set from the test though.

**Comment by anntzer** [comment]
I guess you could possibly use pdfinfo (from poppler) or mutool (from mupdf) as optional test dependency to extract the metadata?

**Comment by QuLogic** [comment]
It doesn't print `Trapped`, but it looks like `pdfinfo` would work for the others. There might be a bug in one or the other, because the printed date is wrong...

**Comment by QuLogic** [comment]
Also, another possibility is [pikepdf](https://pypi.org/project/pikepdf/), which we could use from Python.

**Comment by QuLogic** [comment]
That was a good idea, because I found a few bugs in the PGF side, as hyperref seems to have some differing requirements on the format for things.

**Pull request merged**
