### PR TITLE
added spectrogram examples for mlab

### PR DESCRIPTION
**Pull request by rajatsaxena**
## PR Summary
I have added 3 examples to illustrate `mlab psd,  csd, cohere and specgram` functionalities along with a few other things that might be helpful for the users. 

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
We currently have examples about

* PSD: https://matplotlib.org/gallery/lines_bars_and_markers/psd_demo.html
* CSD: https://matplotlib.org/gallery/lines_bars_and_markers/csd_demo.html
* Coherence: https://matplotlib.org/gallery/lines_bars_and_markers/cohere.html
* Specgram: https://matplotlib.org/gallery/images_contours_and_fields/specgram_demo.html

in the gallery. In how far is this different?

**Comment by anntzer** [comment]
fwiw I think the spectral plotting methods should be considered soft-deprecated (in favor of doing your spectral analysis first with scipy.signal and then plotting the results) and slowly moved out of plain sight, so if anything I would rather decrease the number of examples showcasing them...

**Comment by jklymak** [comment]
Thanks for the hard work, but in addition to what @ImportanceOfBeingErnest said, we are really trying to deprecate these methods for the appropriate numpy/scipy methods

**Comment by rajatsaxena** [comment]
No worries, I will try to get some 3d plotting examples going since that is the other area I have worked a lot on.

**Pull request closed without merging**
