### PR TITLE
Py26 format

### PR DESCRIPTION
**Pull request by montefra**
fix few string formatting to avoid bugs with python 2.6. I hope that I got everything since grep [1] does not show me any match

[1] ``grep -r --include=*.py --exclude=.eggs/* -B 10 "\.format(" | grep {}``

### CODE REVIEW

**Comment by mdboom** [comment]
:+1:

**Comment by tacaswell** [comment]
Thank you!

**Comment by montefra** [comment]
You're welcome. Thanks to grep and vim or was easy.

**Comment by WeatherGod** [comment]
btw, you can use "git grep" to recursively grep the directories below you.
It will only search the files that are in the repository and not the other
files.

**Comment by montefra** [comment]
@WeatherGod I didn't know it. Thank you for the info!

**Comment by matthew-brett** [comment]
git grep - nice!

**Comment by WeatherGod** [comment]
people always complain to me about how unfriendly git is and how much they
loved subversion. Then I show them "git grep" and never hear a peep from
them again... :-P

**Pull request merged**
