### PR TITLE
Fix #5576: Handle CPLUS_INCLUDE_PATH

### LINKED ISSUE #5576: Improper reliance upon pkg-config when C_INCLUDE_PATH is set
In `setupext.py`, matplotlib uses `pkg-config --cflags --libs freetype2` to [determine where `ft2build.h` can be found](https://github.com/matplotlib/matplotlib/blob/master/setupext.py#L922-L924). That works well enough *except* when that path is already set in either the `C_INCLUDE_PATH` or `CPLUS_INCLUDE_PATH` environment variables. If the path is in one of those then pkg-config will not return the appropriate `-I/something` option and compilation will fail (i.e., setupext.py will mark freetype2 as being absent, even though it's not). `pkg-config` is behaving correctly, since gcc/clang/etc. check these environment variables.

Would it be possible to have `_check_for_pkg_config` also check these environment variables. That would solve some [issues on Galaxy](https://github.com/galaxyproject/tools-iuc/issues/417).

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by bgruening** [comment]
Is would be nice to have a backport of this to matplotlib-1.4. It breaks installation of matplotlib in Galaxy, xref https://github.com/galaxyproject/tools-iuc/issues/417

**Comment by mdboom** [comment]
Unfortunately, 1.4.x is no longer maintained.

**Comment by mdboom** [comment]
I think this is ready to merge.  The coveralls thing is clearly a false negative, since this didn't touch any runtime code at all.

**Comment by tacaswell** [comment]
backported as a385d3317207e97eb37ac782dcbf39bec3e6a9be

**Pull request merged**
