### PR TITLE
FIX: remove unnecessary `self` in `super_`-calls, fixes #12265

### LINKED ISSUE #12265: ParasiteAxesAuxTrans  pcolor/pcolormesh and contour/contourf broken
### Bug report

**Bug summary**

Calling `pcolormesh`/`pcolor` or `contour`/`contourf` from a parasite axes created with `ParasiteAxesAuxTrans` breaks. In the call to create the mesh using `super_pcolor` (or `super_contour`) an additional `self` is added to the *args: https://github.com/matplotlib/matplotlib/blob/9a46926afd22be8df6d18d8a2aa58cde4348800a/lib/mpl_toolkits/axes_grid1/parasite_axes.py#L114
This breaks subsequent `pcolor`/`pcolormesh`/`pcontour`/`pcontourf` processing.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist import SubplotHost, ParasiteAxesAuxTrans
from matplotlib.projections import PolarAxes
from matplotlib.transforms import Affine2D

fig = plt.figure(1, figsize=(7, 4))
ax1 = SubplotHost(fig, 1, 1, 1)
fig.add_subplot(ax1)
tr = Affine2D().scale(np.pi/180., 1.) + PolarAxes.PolarTransform()
ax2 = ParasiteAxesAuxTrans(ax1, tr, "equal")
ax1.parasites.append(ax2)
data = np.random.random((360,10))
x = np.arange(data.shape[0])
y = np.arange(data.shape[1])
xx, yy = np.meshgrid(x, y)
ax2.pcolormesh(xx, yy, data.T)
ax1.set_xlim(-10, 10)
ax1.set_ylim(-10, 10)
plt.show()
```

**Actual outcome**

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-3448b36e4131> in <module>()
     15 y = np.arange(data.shape[1])
     16 xx, yy = np.meshgrid(x, y)
---> 17 ax2.pcolormesh(xx, yy, data.T)
     18 ax1.set_xlim(-10, 10)
     19 ax1.set_ylim(-10, 10)

/home/kai/miniconda3/envs/wradlib/lib/python3.6/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py in pcolormesh(self, *XYC, **kwargs)
    120 
    121     def pcolormesh(self, *XYC, **kwargs):
--> 122         return self._pcolor(super().pcolormesh, *XYC, **kwargs)
    123 
    124     def pcolor(self, *XYC, **kwargs):

/home/kai/miniconda3/envs/wradlib/lib/python3.6/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py in _pcolor(self, super_pcolor, *XYC, **kwargs)
    114             gx = wxy[:, 0].reshape(orig_shape)
    115             gy = wxy[:, 1].reshape(orig_shape)
--> 116             mesh = super_pcolor(self, gx, gy, C, **kwargs)
    117             mesh.set_transform(self._parent_axes.transData)
    118 

/home/kai/miniconda3/envs/wradlib/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1783                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1784                         RuntimeWarning, stacklevel=2)
-> 1785             return func(ax, *args, **kwargs)
   1786 
   1787         inner.__doc__ = _add_data_doc(inner.__doc__,

/home/kai/miniconda3/envs/wradlib/lib/python3.6/site-packages/matplotlib/axes/_axes.py in pcolormesh(self, alpha, norm, cmap, vmin, vmax, shading, antialiased, *args, **kwargs)
   5957         allmatch = (shading == 'gouraud')
   5958 
-> 5959         X, Y, C = self._pcolorargs('pcolormesh', *args, allmatch=allmatch)
   5960         Ny, Nx = X.shape
   5961         X = X.ravel()

/home/kai/miniconda3/envs/wradlib/lib/python3.6/site-packages/matplotlib/axes/_axes.py in _pcolorargs(funcname, allmatch, *args)
   5527         else:
   5528             raise TypeError(
-> 5529                 'Illegal arguments to %s; see help(%s)' % (funcname, funcname))
   5530 
   5531         Nx = X.shape[-1]

TypeError: Illegal arguments to pcolormesh; see help(pcolormesh)
```

**Expected outcome**

parasite_axes

Works before PR #11678.

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries: 

Running conda environment using conda-forge channel.

### PR DESCRIPTION
**Pull request by kmuehlbauer**
## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
A test would sit either in `matplotlib/lib/mpl_toolkits/tests/test_axisartist_axislines.py`, `matplotlib/lib/mpl_toolkits/tests/test_axisartist_grid_helper_curvelinear.py`. 

As test you may choose the most minimal, yet general code that would produce this behaviour. Two options are:

1. Create a "smoketest", i.e. just put the code there. If it throws an error, the test would fail.
2. Create an image comparisson test. For this you would need to create a target image. 

Both are explained in https://matplotlib.org/devel/testing.html

**Comment by tacaswell** [comment]
Thanks @kmuehlbauer !

**Comment by ImportanceOfBeingErnest** [comment]
Since image comparisson tests are a little expensive, I think one would benefit from creating one single figure with 3 subplots (one for pcolor, one for pcolormesh, one for contour and contourf) instead of 4 individual figures. 

In general, you may by now have noticed that `axisartist` is pretty undertested. Since it seems you are using the axisartist toolkit a lot in your radar image library, there may be other cases you may not want to fail in future versions of matplotlib. Hence, please feel welcome to add additional tests (possibly in future PRs).

**Comment by kmuehlbauer** [comment]
@ImportanceOfBeingErnest You are completely right, I'll change it as suggested as soon as possible. 

Yes, we use the toolkits quite extensively. Time to give something back, I think.

**Comment by ImportanceOfBeingErnest** [comment]
So what's happening now is that the tests fail (Seen by the red "Some checks were not successful") because of some deviation between the produced image and the target image. This is most often the case when the `freetype` library in use differs from the one the tests are run with. The two alternative solutions to this are:

1. Make sure to use the same freetype when compiling matplotlib. This is shown [here](https://matplotlib.org/devel/contributing.html?highlight=freetype#building-matplotlib-for-image-comparison-tests)
2. Use `remove_text=True` in the image comparisson decorator. (Which is fine as long as the test isn't really testing anything which requires any texts to be rendered.)

**Comment by tacaswell** [comment]
As we are already talking about re-generating the images there is a 'remove text' option and a style option (which should be set to 'default').

Can you please make sure to squash the image commits (so we don't carry around the un-used images in git).

**Comment by kmuehlbauer** [comment]
parasiteaxesauxtrans_meshplot-failed-diff

You see the little dot in the lower right part? That is one corner of the contour line. Only one pixel is different. I know, we have the `tol` keyword but I'm unsure why this happens. Normally the contourlines should exactly be the same.

**Comment by kmuehlbauer** [comment]
The RMS was below 0.039 in all cases. So I set `tol` with a safety margin to `0.05` .

**Comment by kmuehlbauer** [comment]
Safety margin wasn't good enough. Will fix this the next day...

**Comment by kmuehlbauer** [comment]
rebased on top of current master due to conflicts

**Pull request merged**
