### PR TITLE
MEP28: fix rst syntax for code blocks

### PR DESCRIPTION
**Pull request by phobson**
I borked the python code blocks in my MEP. 

(they were interpreted as comments)

Small changes to fix that.

### CODE REVIEW

**Comment by phobson** [comment]
@jenshnielsen thanks for the quick turn around on the doc build this morning. Sorry I messed this up.

**Comment by tacaswell** [comment]
devdocs is built by travis and push everytime we merge to master. @jenshnielsen does sleep, but this process uses his keys (which I think we can now switch to an org deploy key but this works so lets not touch it).

**Comment by NelleV** [comment]
There's a tool to build and push for each branch as well. I forgot the name, but @Carreau should know. That may help in getting our build more consistent?

**Comment by jenshnielsen** [comment]
It's just using a key that I generated for this purpose (I guess it must contain my mail address but should probably be using one of the mailing lists instead) That key is added as a deploy key with write access for https://github.com/matplotlib/devdocs but no where else (github prevents you from using deploy keys more than once in their system). We build the docs for every branch but only deploy from master. We could extend this to other branches (2.x ...) but it would not be safe to automatically docs builds from PRs as far as I can see (anyone can open a PR and inject malware into the build docs).

[Travis-sphinx](https://github.com/Syntaf/travis-sphinx) can do much the same using an API key which would probably make it easier to build from multiple branches

**Comment by phobson** [comment]
@tacaswell unless there are objections, I'll announce this on the mailing list shortly.

**Comment by phobson** [comment]
(also thanks for the merge!)

**Pull request merged**
