### PR TITLE
FIX: Apply aspect before drawing starts

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

As noted in https://github.com/matplotlib/matplotlib/issues/4375#issuecomment-407083590 connection patches between artists with different transforms do not always work on the first draw, though they will on the second draw.  This happens because `apply_aspect` happens at draw time for axes, and not always in the order necessary for these connections to take place properly.

This PR proposes calling `apply_aspect` on all axes in a figure *before* they are drawn.  This positions them properly before the draw, and makes these kinds of connectors work.

Pro: connector patches (annotate) work.  
Con: `apply_aspect` gets called twice.  ~I've removed the `apply_aspect` call from `ax.draw`.  So the aspect is applied at the figure level rather than at each axes.  This isn't necessary - it can be in both places, but that has extra overhead.  However, I'm not 100% certain that `apply_aspect` can be removed from `ax.draw`.~ 

```python 
import matplotlib.pyplot as plt
import numpy as np

x=np.linspace(0,10,200)
y=np.exp(-x)*np.sin(x)

fig,ax = plt.subplots(figsize=(3.39,3))

ax.plot(x,y)

axins = ax.inset_axes([0.4, 0.5, 0.3, 0.3])
axins.xaxis.set_visible(False)
axins.yaxis.set_visible(False)
axins.set_aspect(0.2)
ax.annotate("",xy=(x[150],y[150]), xycoords=ax.transData,
        xytext=(1, 0), textcoords=axins.transAxes,
        arrowprops=dict(arrowstyle="->"))
# axins.apply_aspect()

plt.show()
fig.savefig('boo.png')
```

#### Show:
figure_1

#### boo.png:
boo

### After

figure_1

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
I wonder if there is a good way to create a test for this?

As for moving the apply aspect, I think it should be in both places, but
perhaps we can add some logic to detect that it has already happened?

**Comment by jklymak** [comment]
Agreed, this definitely needs a test.  Happy to keep it in twice.  I don't think its really very slow and makes life a lot more consistent...

**Comment by jklymak** [comment]
Actually to pass the tests, we need the apply_aspect in the draw as well.

**Comment by jklymak** [comment]
Note this fixes an annoyance in the

**Comment by jklymak** [comment]
Milestoning as 3.1, as this has been a long-standing problem with linked artists between axes, and I know we want to get 3.0 out.    OTOH, it would be nice to see it get into 3.0, and even 2.2.3 because it really does fix any plot that has artists that depend on the proper axes location to draw.

**Comment by jklymak** [comment]
Rebased on master. 

I still think this would be good for 3.0, because it really fixes some long-term annoyances...

**Comment by jklymak** [comment]
I don’t think this needs a rebase ;-)

**Comment by jklymak** [comment]
Ooops, I guess it did - rebase complete!

**Comment by QuLogic** [comment]
You have flake8 errors:
```
./lib/matplotlib/tests/test_axes.py:5793:1: E303 too many blank lines (3)
1     E303 too many blank lines (3)
```

**Comment by ImportanceOfBeingErnest** [comment]
If you need to `apply_aspect` for the figure to correctly show up, doesn't that mean that at some point down the road real coordinates are used instead of transforms? I mean if the transform chain isn't broken, it would be enough to draw the axes, inside the axes draw apply the aspect then draw all children of the axes.

**Comment by ImportanceOfBeingErnest** [comment]
Makes sense. Left is what is currently done, right is what would prevent this from happening.

image

I suppose there is then no other way, except completely refactoring the drawing order - which I guess is out of question.

**Comment by jklymak** [comment]
Refactoring the drawing order wouldn't be too hard, but I think would make the code a lot less clear.  

Another idea here is to call `apply_aspect` when `set_aspect` is called.  That would potentially be less expensive and might still fix the problem.  OTOH, I don't think `apply_aspect` is that expensive in the first place, though the code is long-ish.

**Comment by ImportanceOfBeingErnest** [comment]
Not sure in how far this could go into 3.0.x, since it's mainly a bug fix?

**Comment by jklymak** [comment]
Yeah but not a regression (it’s basically always been this way) so we don’t usually backport.

**Comment by jklymak** [comment]
This has two approvals... I'm hesitant to self-merge in case someone else wants to make sure it makes sense...

**Pull request merged**
