### PR TITLE
Rename outdated seaborn styles.

### PR DESCRIPTION
**Pull request by anntzer**
They are kept available under a versioned name for backcompat.

See https://github.com/matplotlib/matplotlib/issues/20252, https://github.com/matplotlib/matplotlib/issues/8351, https://github.com/matplotlib/matplotlib/pull/13680.

attn @mwaskom, I guess.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
Modulo adding a test that this actually warns (just for 1 name).

**Comment by anntzer** [comment]
test added.

**Comment by mwaskom** [comment]
LGTM, thanks @anntzer

**Review by jklymak — APPROVED** [review]

**Comment by timhoffm** [comment]
Just wondering, would `seaborn-0.8-bright` be better than `seaborn0.8-bright`?

**Comment by tacaswell** [comment]
I mildly prefer without the dash as the dash here is specifying something with in the namespace of seaborn styles and the 0.8 is clarifying that it is the namespace of a particular version of seaborn and we do not plan to pick up style sheets for every version of seaborn.

On the other hand, `seaborn-0.8-bright` does scan a bit better.

I also propose `seaborn08` with no extra punctuation.

**Comment by QuLogic** [comment]
There is a vague convention in Fedora that compatibility packages be named `<name><version>` without other changes (and then subpackages would be `<name><version>-<subpackage>`), so I have a slight preference for that (i.e., `seaborn0.8-bright`, etc.)

**Comment by timhoffm** [comment]
The python packaging naming convention is `seaborn-0.8.tar.gz` (https://pypi.org/project/seaborn/#files).

**Comment by QuLogic** [comment]
Those are not _backwards-compatibility_ names though; those are `<name>-<version>`, whereas I mean `<name><oldversion>` as _the name itself_.

**Comment by timhoffm** [comment]
I don't see (the point of) the distinction, but concerning package compatiblity I'm just a simple user :shrug:.

**Pull request merged**
