### PR TITLE
Test the macosx backend on Travis.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Split out of https://github.com/matplotlib/matplotlib/pull/16921.

edit: proof that it worked: https://codecov.io/gh/matplotlib/matplotlib/compare/54b426397c0e7567edaee4f7f77036c2b8569573...a90006151abc353ad26a3ef36895bf0180cd8762/src/lib/matplotlib/backends/backend_macosx.py

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Let's see whether we can also get coverage for the macosx extension module...

**Comment by QuLogic** [comment]
It doesn't look like macOS's compiler has what we need for coverage. I think llvm uses a different flag or a different linker to get that to work?

**Comment by QuLogic** [comment]
Actually, it may be that you need to pass `--coverage` in `LDFLAGS` too (which I think should be done on all systems, actually).

**Comment by anntzer** [comment]
Let's get this part in first, and defer the coverage to another PR; I reverted the change re: coverage.

**Pull request merged**
