### PR TITLE
Grammar fix for pyplot tutorial

### PR DESCRIPTION
**Pull request by brettcannon**
"an axes" -> "any axes"

### CODE REVIEW

**Comment by WeatherGod** [comment]
Thanks! Doc-fixes are greatly appreciated! If you find more, send 'em over.

**Comment by brettcannon** [comment]
So I have a question about using the term `axes`. I'm noticing that in a bunch of places it's used as a singular thing, such as "Add an axes to the figure" in the [matplotlib.pyplot.axes docs](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.axes). But I'm used to the plural meaning of "axes", like "add axes to the figure" because you're adding more than one axis. Which is the way you prefer? If it's the latter then I'm happy to send in PRs changing the grammar as I read through the user's guide (this has been the only consistent quirk that's throwing me as a new user with no MATLAB background if that's the reason for the phrasing choice).

**Comment by WeatherGod** [comment]
Yes, this is a perennial problem. The issue is that there is a concept of
an "axis" (i.e., the x-axis and y-axis). So, a plot is composed of 2 or
more axis-es. Hence, a plot is known as an "axes". So, we try and avoid
saying "axes" when we mean multiple "axis" (but that gets tricky). We
almost never say "axis" when we mean a single "axes".

English is a terrible programming language...

**Comment by tacaswell** [comment]
@brettcannon I hope http://matplotlib.org/faq/usage_faq.html#parts-of-a-figure clarifies things. 

Grammatically would it make more sense to say "Add an `axes` object to the figure"?

**Comment by dopplershift** [comment]
That sounds better to me.

**Comment by WeatherGod** [comment]
And what shall be the plural of `axis` and `axes`?

**Comment by dopplershift** [comment]
"objects"

**Comment by brettcannon** [comment]
The FAQ entry from @tacaswell does help explain why the docs use "axes" as a singular term. Is this a MATPLOTLIB thing?

Anyway, what I'll do is send a PR that tweaks the Pyplot tutorial to link to the FAQ entry so that it makes more sense to beginners.

**Comment by efiring** [comment]
On 2015/08/19 8:04 AM, Thomas A Caswell wrote:
> @brettcannon <https://github.com/brettcannon> I hope
> http://matplotlib.org/faq/usage_faq.html#parts-of-a-figure clarifies
> things.
>
> Grammatically would it make more sense to say "Add an |axes| object to
> the figure"?

Maybe this should be consistently capitalized, "Axes", to be a more 
explicit reference to the Axes class.

**Pull request merged**
