### PR TITLE
Backport PR #12705 on branch v3.0.0-doc

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Backport PR #12705 on branch v3.0.0-doc:

Improve docs on Axes limits and direction

### CODE REVIEW

**Comment by tacaswell** [comment]
Changes to the source files should not be backported to the -doc branches (see https://matplotlib.org/devdocs/devel/coding_guide.html#branches-and-backports which is a bit out of date).

The reasoning is that the docs are built against an installed version of the tag (ex 3.0.0) so these changes will have no effect!

Thank you for your work @timhoffm ,but closing this without merging.

**Comment by ImportanceOfBeingErnest** [comment]
That would be a pretty strong argument for not having the docstrings inside the source files at all.  
Or is it reasonable to only update the docs (i.e. the online documentation that people access every day via matplotlib.org) only twice a year?

**Comment by jklymak** [comment]
I think the API docs change on bug fix releases as well. You could argue we should do more bug fix releases, but @tacaswell only has so many hours in the day.

**Comment by ImportanceOfBeingErnest** [comment]
I have to admit that I don't understand the process in completeness. So from my naive point of view, 

1. What would be the problem of backporting all doc string changes to vx.y.0-doc and manually buiding the docs from an installed version of that branch? It seems to be less work and could even be automated.
2. There is a nightly built of the docs from master branch at `matplotlib.org/devdocs/`. Why can the vx.y.0-doc branch not have a similar nightly built, which is then directly accessible at `matplotlib.org` ?

**Comment by tacaswell** [comment]
1) to keep the web page in sync with the docstrings you get interactively. 
2) There is no technical reason we could not auto-deploy the doc branch nightly, no one has done the dev-ops to make that happen.  I am very much in favor of it.

**Pull request closed without merging**
