### PR TITLE
Text box widget, take over of PR5375

### PR DESCRIPTION
**Pull request by fariza**
Friendly take over of https://github.com/matplotlib/matplotlib/pull/5375

### CODE REVIEW

**Comment by fariza** [comment]
@tacaswell here is the new PR, I just discover a small bug

```
Traceback (most recent call last):
  File "/home/fede/workspace/matplotlib/lib/matplotlib/backends/backend_gtk3.py", line 249, in key_press_event
    FigureCanvasBase.key_press_event(self, key, guiEvent=event)
  File "/home/fede/workspace/matplotlib/lib/matplotlib/backend_bases.py", line 1839, in key_press_event
    self.callbacks.process(s, event)
  File "/home/fede/workspace/matplotlib/lib/matplotlib/cbook.py", line 541, in process
    proxy(*args, **kwargs)
  File "/home/fede/workspace/matplotlib/lib/matplotlib/cbook.py", line 408, in __call__
    return mtd(*args, **kwargs)
  File "/home/fede/workspace/matplotlib/lib/matplotlib/backend_bases.py", line 2685, in key_press
    key_press_handler(event, self.canvas, self.canvas.toolbar)
  File "/home/fede/workspace/matplotlib/lib/matplotlib/backend_bases.py", line 2609, in key_press_handler
    if not (event.key in all):
TypeError: argument of type 'builtin_function_or_method' is not iterable
```

I will try to fix it next week

@Nodraak can you submit a PR against this one?

 @smithsp can you create a PR from your branch https://github.com/smithsp/matplotlib/tree/text-box-widget  to mine https://github.com/fariza/matplotlib/tree/text-box-widget

**Comment by Nodraak** [comment]
@fariza [Here you go :)](https://github.com/fariza/matplotlib/pull/14)

> I just discover a small bug

I'm not sure if `all` is supposed to be `all_keys` ... Looks like a silly typo

**Comment by QuadmasterXLII** [comment]
Hi! Thanks for the friendly takeover -- sorry for dropping off the face of the earth there

**Comment by fariza** [comment]
@Nodraak for the time being I didn't take the `set_facecolor` change because I wasn't able to reproduce the problem.

**Comment by fariza** [comment]
@tacaswell I don't think the failure is related.

**Comment by jenshnielsen** [comment]
I merged #7006 which should fix the docs build error on Travis

**Comment by fariza** [comment]
@jenshnielsen any idea on the appveyor fail?

**Comment by smithsp** [comment]
@fariza 
Does https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.2460/job/xe3avci96c77qirw#L1609
not explain the failure?

**Comment by fariza** [comment]
@smithsp maybe I'm lost in the logs, but I don't see a relation between this PR changes and the failure

**Comment by smithsp** [comment]
@fariza 
I agree that this PR is not the cause of appveyor failure.  I guess that is why you pinged @jenshnielsen

**Comment by jenshnielsen** [comment]
That is probably fixed by #7011

**Comment by fariza** [comment]
In that case, that's all from my side.
Any other question/suggestion/changes?

Ready to merge

**Comment by jenshnielsen** [comment]
Power cycling again

**Comment by tacaswell** [comment]
Thanks everyone for getting this across the finish line!

**Comment by QuadmasterXLII** [comment]
Thank you so much for your help!

**Pull request merged**
