### PR TITLE
Strip python 2 code from subprocess.py

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by anntzer** [comment]
Actually subprocess is only unavailable on the standard google app engine environment, which is only py2.7; for py3 you apparently need to use the flexible environment, which is dockerized and afaict has subprocess available: https://cloud.google.com/appengine/docs/python/

So the whole submodule can go away (via the normal deprecation route, but calls to it can be removed in the rest of the codebase).

**Comment by dstansby** [comment]
What's the right way to deprecate a whole module? I only know how to do functions with the decorator.

**Comment by anntzer** [comment]
manually: https://github.com/matplotlib/matplotlib/blob/master/lib/mpl_toolkits/axes_grid/__init__.py

**Comment by anntzer** [comment]
While you are hacking the subprocess calls: the `str('foo')` in these calls were only needed on Py2 because Py2 wanted a native (py2) string, not a unicode string.  On Py3 these have become unnecessary.

**Pull request merged**
