### PR TITLE
`streamplot` can return start and end points. 

### LINKED ISSUE #22985: [ENH]: Add option to return streamline ending locations from streamplot
### Problem

In the field of groundwater modeling, we often perform well capture zone analyses using streamlines. To this end, it would be very useful if Matplotlib's streamplot() function had an option to return the ending locations of the streamlines. That way, I could identify which streamlines terminated at the well and color them differently - it is these streamlines that define the "capture zone." 

### Proposed solution

Please consider providing an option to return the ending locations of streamlines from the streamplot function. I imagine these locations are embedded somewhere in the code already.

### PR DESCRIPTION
**Pull request by Mattia-Vicari**
## PR Summary

I've added 2 methods to get the starting and finish points of every stream lines in streamplot as requested in the issue. Here and example of how them work:

`my_plot = plt.streamplot(X, Y, u, v)`
`startpoints = my_plot.get_startpoints()`
`endpoints = my_plot.get_endpoints()`

closes #22985

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
Thank you for your contribution!

Can you please add a doc-string to each methods introduced? Something like:
```
"""Get list of start points for stream lines."""
```
would do.

Also, can you please add some tests for this? Typically, I would expect a test asserting that the returned values are the expected.

I also believe that it can be instructive to add a release note with a usage example. For example, using the obtained start and end points to put a marker in those locations.

Finally, I took the liberty to change the title to be a bit more instructive.

**Comment by jklymak** [comment]
Thanks for your contribution!  OTOH I'm a little leery about providing people with this as a data analysis tool.

**Comment by Mattia-Vicari** [comment]
Hi, thank you for the feedback, can I ask wh? I really appreciate to understand

**Comment by jklymak** [comment]
Because the algorithm is not well documented and has had some bugs in the past.  I personally wouldn't use it for more than qualitative information.

**Comment by jklymak** [comment]
This was discussed on the call last week. We appreciate the sentiment of the idea, however, similar to how we do not directly expose contour paths, we prefer to not directly expose parts of the streamlines.  Users who need to annotate lines or otherwise know their values, can still access them in `streamlines.lines.get_segments`, which is public. 

Thanks a lot for your willingness to help improve Matplotlib. Sorry this didn't get in, but we hope you have future good ideas, and that we see you again.

**Pull request closed without merging**
