### PR TITLE
Rectified plot error

### PR DESCRIPTION
**Pull request by anubhavshrimal**
The plot shown on the page: https://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

Will be possible only if plt.show() is outside the loop

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Thanks for the patch, but that code is intended to be that way (check the paragraph before it.) The image shows three lines because `plt.show` is patched to do nothing when building docs, but I don't think there is any simple way to work around that.

**Comment by anntzer** [comment]
Agreed with @QuLogic, proposing to close the PR.

**Comment by ImportanceOfBeingErnest** [comment]
If the image isn't able to show what the code does, especailly if it shows the contrary of what the code does, it should be removed. I also cannot think of another good visualization of this case.

My proposal would hence be to change the relevant part to

```
# restriction is lifted, so one can write a script like this::
#
#     import numpy as np
#     import matplotlib.pyplot as plt
#
#     plt.ioff()
#     for i in range(3):
#         plt.plot(np.random.rand(10))
#         plt.show()
#
# which makes three plots, one at a time. I.e. the second plot will show up,
# once the first plot is closed.
```

**Comment by anntzer** [comment]
By the way, I think I know how to make this work in sphinx-exhibit, if there's still interest for that...

**Comment by ImportanceOfBeingErnest** [comment]
I don't currently see much of a use case for "making this work". In this case, you wouldn't want to clutter the tutorial with 3 images of those plots anyways, right?  
In other cases, you would simply put `plt.show()` at the position where you want to show all figures. If sphinx-exhibit can defer output to the position where `plt.show()` is called, that may truely be useful. In general I think the only chance sphinx-exhibit has is to come along as a working solution.

**Comment by tacaswell** [comment]
I agree with @ImportanceOfBeingErnest 's change.  I think that example is meant to show the workflow of
 
 - plot something 
 - show the plot and let the GUI event loop block the rest of python
 - when the user closes the plot window the script continues and opens the next widow
 - repeat

There is no good way to show that in rendered static figures in the docs so it is better to just change it to a code block.

**Comment by tacaswell** [comment]
@anubhavshrimal Thanks for your work on this!

**Comment by anntzer** [comment]
> I don't currently see much of a use case for "making this work". In this case, you wouldn't want to clutter the tutorial with 3 images of those plots anyways, right?

In this specific case I agree

> If sphinx-exhibit can defer output to the position where plt.show() is called, that may truely be useful.

That's what I had in mind.

**Comment by ImportanceOfBeingErnest** [comment]
Just to make sure how this is moving forwards,  
@anubhavshrimal Are you willing to make the changes discussed above to this PR?

**Comment by anubhavshrimal** [comment]
@ImportanceOfBeingErnest Though I would love to work on the discussed changes, I am not really sure how to go about doing that.

**Comment by ImportanceOfBeingErnest** [comment]
@anubhavshrimal it should really be as simple as mentionned [above](https://github.com/matplotlib/matplotlib/pull/12501#issuecomment-429304351)

> My proposal would hence be to change the relevant part to
```
# restriction is lifted, so one can write a script like this::
#
#     import numpy as np
#     import matplotlib.pyplot as plt
#
#     plt.ioff()
#     for i in range(3):
#         plt.plot(np.random.rand(10))
#         plt.show()
#
# which makes three plots, one at a time. I.e. the second plot will show up,
# once the first plot is closed.
```

**Comment by anubhavshrimal** [comment]
I have made some changes in the code and docs. Is that what you needed? 
I thought it was something with sphinx-exhibit 😅

**Comment by anubhavshrimal** [comment]
oh! So what I have understood is that you mean to comment out the rest of the code block as you have done?

**Comment by ImportanceOfBeingErnest** [comment]
Yes, exactly.

**Comment by anubhavshrimal** [comment]
Done! Have a look. 👍

**Comment by ImportanceOfBeingErnest** [comment]
In principle yes, except you missed the double colon (`::`)

**Comment by ImportanceOfBeingErnest** [comment]
What now happened is that you have a trailing empty space in line 610 and 615. And also the indentation is wrong.

This is your proposed code:

image


This is my proposal from above:

image

**Comment by anubhavshrimal** [comment]
Sorry but I am not sure what you mean by E501

**Comment by ImportanceOfBeingErnest** [comment]
`E501` is unimportant. The important part is to remove the `E402` from the linked line.

**Pull request merged**
