### PR TITLE
Nan issue

### PR DESCRIPTION
**Pull request by ffteja**
Pull request for #4066

### CODE REVIEW

**Comment by WeatherGod** [comment]
looks like you accidentally pushed some other commit to this branch?

**Comment by ffteja** [comment]
Yes. Sorry, I'm new to Github (coming from SVN)
I think I need to create a branch per patch I want to submit to you.

**Comment by WeatherGod** [comment]
Yes, that is correct. Do you need help fixing this PR? Or do you want to
just submit clean ones?

**Comment by ffteja** [comment]
This PR is related to #4066. I just wanted to submit to you the patch/commit 9f20337

Please forgot the next commit, it is another patch I want to send to the matplotlib project. I'm trying to understand how I can submit separate PR. Should I do one branch per PR?

**Comment by WeatherGod** [comment]
Yes, one branch per PR. But I can't merge this PR with that extra commit on
it, and I can't simply "ignore" that commit because we merge branches, not
commits.

http://stackoverflow.com/questions/927358/how-to-undo-the-last-commit

**Comment by WeatherGod** [comment]
ah, there we go. If you are feeling adventurous... you can "squash" your commits so that they never appear in the history:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

But I would understand if you don't want to learn too much git in one day... ;-)

**Comment by ffteja** [comment]
I tried :p 
I can do another PR if you prefer. It's a little patch I can redo easily.

**Comment by WeatherGod** [comment]
uh, yeah.. that commit history looks a little unclean. Let's start again from scratch. As you use git more often, get used to the idea of always working in new branches.

**Pull request closed without merging**
