### PR TITLE
CenteredNorm break infinite loop

### PR DESCRIPTION
**Pull request by grgkaran03**
## PR Summary
CenteredNorm gets stuck in infinite recusion when given all zeros. To fix, Nonsingular expansion in colorbar for the CenteredNorm case. Addressing issue #24093 

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [x] New features are documented, with examples if plot related.
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
This could use a test.  I'm also not clear where 0.1 comes from?

**Comment by tacaswell** [comment]
#24132 is also open with I think similar changes?

**Comment by greglucas** [comment]
I think this needs discussion on what we want to do for the bugfix versus going forward, so this may be OK for 3.6.x but we might want the other PR for 3.7. I like the other solution, which is why I PR'd that version, but others may feel differently.

> I'm also not clear where 0.1 comes from?

It comes from the nonsingular transform below to be the same as that, I am guessing it was an arbitrary choice at some point.

**Comment by greglucas** [comment]
Closing this PR because #24132 was merged instead. Thanks for your work on this @grgkaran03 and we hope to hear from you again!

**Pull request closed without merging**
