### PR TITLE
Always import pyplot when calling matplotlib.use().

### PR DESCRIPTION
**Pull request by anntzer**
This avoids having to reason about various delayed backend resolution
strategies.

Simpler (IMO) alternative to #13892.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I would rather just always raise and then the caller can catch the exception and do whatever they want, but that's going to be another discussion...

**Comment by tacaswell** [comment]
I do not like the hidden import of pyplot.

I do not disagree it is simpler, but I am not sure it is better.

**Comment by anntzer** [comment]
> I do not like the hidden import of pyplot.

Why? I honestly believe that the "try not to import pyplot" approach goes back the the time when importing pyplot was irreversible, but this is no longer the case (more specifically, I think we should treat backends that do irreversible things at *import* times as bugs).
If importing pyplot is now really fully reversible, then there is no issue with importing it there.

**Comment by tacaswell** [comment]
On the call I was convinced that @anntzer is correct and I have not fully updated by priors about "don't import pyplot" given recent code changes.

Punt the discussion of deprecating `matplotlib.use` in favor of `pyplot.switch_backend` down the road.

**Pull request merged**
