### PR TITLE
WIP: Try to fix macOS builds on Travis

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Don't know if this will work; hoping that homebrew just has `pip2` or `pip3` and we lost the unversioned symlink.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jenshnielsen** [comment]
As far as I know homebrew python is no longer installing python executable on path only the versioned executable `python2`. We may need to modify the path to fix this

from the homebrew help
```
python: stable 2.7.14 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python/2.7.14 (3,564 files, 49.2MB) *
  Poured from bottle on 2017-09-25 at 15:09:03
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
==> Dependencies
Build: sphinx-doc ✘, pkg-config ✔
Required: openssl ✔
Recommended: readline ✔, sqlite ✔, gdbm ✔
Optional: sphinx-doc ✘, tcl-tk ✘, berkeley-db@4 ✘
==> Options
--with-berkeley-db@4
	Build with berkeley-db@4 support
--with-poll
	Enable select.poll, which is not fully implemented on macOS (https://bugs.python.org/issue5154)
--with-quicktest
	Run `make quicktest` after the build (for devs; may fail)
--with-sphinx-doc
	Build HTML documentation
--with-tcl-tk
	Use Homebrew's Tk instead of macOS Tk (has optional Cocoa and threads support)
--without-gdbm
	Build without gdbm support
--without-readline
	Build without readline support
--without-sqlite
	Build without sqlite support
--HEAD
	Install HEAD version
==> Caveats
This formula installs a python2 executable to /usr/local/bin.
If you wish to have this formula's python executable in your PATH then add
the following to ~/.bash_profile:
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"

Pip and setuptools have been installed. To update them
  pip2 install --upgrade pip setuptools

You can install Python packages with
  pip2 install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages
```

**Comment by QuLogic** [comment]
> If you wish to have this formula's python executable in your PATH then add

Does that include the unversioned `pip`?

**Comment by jenshnielsen** [comment]
At least on my computer there is an versioned pip in that folder

**Comment by dstansby** [comment]
https://docs.travis-ci.com/user/languages/python/ says "Python builds are not available on the OS X environment." - is that new?

**Comment by QuLogic** [comment]
OK, `master` was [failing 15 hours ago](https://travis-ci.org/matplotlib/matplotlib/jobs/308894193), but magically started [working again 10 hours ago](https://travis-ci.org/matplotlib/matplotlib/jobs/308991690), so now I'm not entirely sure if this fixed the problem or not, or even if it needs fixing at all (e.g., if we were calling system python instead of brew, then it needs fixing.)

**Comment by jenshnielsen** [comment]
According to the logs this doesn't actually install python but uses an older brew version (2.7.12) that comes preinstalled with that travis image (I expect that version will be on path since its predates brew changed the python path policy). The image that we currently select is rather old so we may want to change that too or just use the default unspecified version see https://blog.travis-ci.com/2017-11-21-xcode8-3-default-image-announce

I think master started working again because Travis reverted changes to the image. In the 15 hours ago log you will find `Warning: python 2.7.14 is already installed` but in the 10 Hours ago log you will find `Error: python 2.7.12_1 is already installed`

**Comment by dstansby** [comment]
I'm running a default osx image build here to see what happens: https://travis-ci.org/dstansby/matplotlib/jobs/309531841

**Comment by dstansby** [comment]
All seems to be working fine at the moment, so should this be closed?
(https://travis-ci.org/matplotlib/matplotlib/builds)

**Comment by jenshnielsen** [comment]
@dstansby If my analysis is correct this will break as soon as Travis updates homebrew in that image so it does seem a bit brittle

**Comment by anntzer** [comment]
AFAICT this can be closed now?  Feel free to reopen otherwise.

**Pull request closed without merging**
