### PR TITLE
[MRG+1] Check at least one argument is provided for plt.table

### LINKED ISSUE #7519: plt.table() without any kwargs throws exception
Installed from source using pip on OSX.
Version 2.0.0b4+2948.g6a56f69

I encountered this when trying to fix #5350. Just using plt.table() errors, which I wouldn't expect given all the arguments are optional...

Minimal snippet:
```
import matplotlib.pyplot as plt
plt.table()
```

And output:
```
python test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    plt.table()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3484, in table
    ret = gca().table(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 5884, in table
    return mtable.table(self, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/matplotlib/table.py", line 587, in table
    rows = len(cellColours)
TypeError: object of type 'NoneType' has no len()
```

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #7519.

- ValueError seemed to be the most suitable exception to raise, but I might be wrong.
- Is it worth adding a test for this or not?

### CODE REVIEW

**Comment by efiring** [comment]
ValueError is appropriate.  I do not think a test should be added for this.

**Comment by NelleV** [comment]
Thanks @dstansby for the patch!

**Comment by QuLogic** [comment]
Backport?

**Comment by efiring** [comment]
Sure, go ahead.

**Comment by QuLogic** [comment]
Backported to v2.x as aef8acd9360fc8530b18bc4ddf75473953acb547.

**Pull request merged**
