### PR TITLE
ci: Publish result images as Azure artifacts.

### PR DESCRIPTION
**Pull request by QuLogic**
This should allow us to debug result images if they're failing on Azure.

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm thinking we probably want to add a condition so publishing works when stuff fails, but I didn't add it here just to see what the results look like. Should we publish _always_ or _only on failure_?

**Comment by anntzer** [comment]
I guess only-on-failure is good enough for now?

**Comment by QuLogic** [comment]
Hmm, looks like I need to give it a stage-specific name.

**Comment by QuLogic** [comment]
So Windows Prerelease build failed because nothing was actually run. Seems we're a bit too relaxed with that one.

**Comment by QuLogic** [comment]
I added the on-failure condition, and skipped artifacts for the Prerelease build (which is broken right now). You can see what it looks like in the [previous build](https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=10292&view=results). In the top card, under the Related heading, there is the "9 published" link which points to the artifacts. If you're on a specific Job view, then there's a link to "1 artifact produced".

**Pull request merged**
