### PR TITLE
Adjust face colors for 3D panes

### PR DESCRIPTION
**Pull request by dennylin93**
- Avoid using the same color as grid lines even if the alpha value is different. There are problems with formats lacking transparency.
- Make the face colors for all panes identical.

### CODE REVIEW

**Comment by WeatherGod** [comment]
This seems like it would only paper over a deeper problem, I think. But I do wonder now if the alpha values might be causing issues. I have no clue why alpha is even being used at all for the wall panels...

Does anybody know of a way to compute the equivalent RGB value from a RGBA + white blending? If so, maybe we can replace those RGBA's with RGB's?

**Comment by tacaswell** [comment]
But the background color is controlled by the figure patch face color, it is not safe to blend it to white.

The blending formula is `(foreground * alpha + background * (1-alpha))` iirc

**Comment by WeatherGod** [comment]
True, but I think in this is something I might be willing to break if it
solves this problem once and for all.

**Comment by tacaswell** [comment]
@dennylin93 where are the grid line RGB colors set?

**Comment by dennylin93** [comment]
It's set in __init__() in axis3d.py. See link below.

https://github.com/matplotlib/matplotlib/blob/68ff493e9bfac4e1e685d128a1b22497ec10f139/lib/mpl_toolkits/mplot3d/axis3d.py#L97.

**Comment by anntzer** [comment]
Transparency is needed at least because points may end up behind the panes (e.g. after zooming in); with transparent panes the points remain visible after that, which is probably a good idea...

**Comment by WeatherGod** [comment]
The panes are always rendered first. No point can end up behind a pane --
at least, in theory.

**Comment by jklymak** [comment]
I'll closed as abandoned; thanks for the PR, and feel free to re-open if you want to come back to this!

**Pull request closed without merging**
