### PR TITLE
Fix the vertical alignment of overunder symbols.

### PR DESCRIPTION
**Pull request by tfpf**
This fixes https://github.com/matplotlib/matplotlib/issues/18085.

When an overunder symbol has a subscript, it goes below the symbol, and the baseline of the `Vlist` thus created is actually the baseline of the lowest item in the `Vlist`. Hence, it must be moved only if there is a subscript, and not otherwise.

## PR Summary
MWE derived from the above-mentioned issue.
```
import matplotlib.pyplot as plt
(fig, ax) = plt.subplots()
ax.text(.01, .7, r"$\sum x\quad\sum^nx\quad\sum_nx\quad\sum_n^nx$", size=35); ax.axhline(.7)
ax.text(.01, .3, r"$\prod x\quad\prod^nx\quad\prod_nx\quad\prod_n^nx$", size=35); ax.axhline(.3)
plt.show()

```
Before:
Matplotlib_pull_before

After:
Matplotlib_pull_after

(Admittedly, the spacing could be much better. It is just right if there is no subscript and superscript, but not otherwise.)

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by oscargus — APPROVED** [review]
It would be nice with some tests (primarily so that this isn't broken later), but I cannot really figure out a way to do that without adding yet another set of images (which should be avoided to reduce the git load). I think I'll open an issue an try to collect things to put in new tests.

**Comment by jklymak** [comment]
I don't think we should be avoiding image tests where they are needed, like this PR.

**Comment by oscargus** [comment]
I was quite sure that I recently saw a PR going in which some tests were removed, so I was about to give you some input on what else to add in the test, but I cannot seem to find it now...

I must admit that I do not really understand when test images should be added and not.

**Comment by jklymak** [comment]
There are lots of things that can be tested with "figures_equal" or with hard coded value tests.   Other things, however, really require a render to test.   In this case I don't think there is anyway to test that the rendering is correct without an image test.

**Comment by tfpf** [comment]
All right, I'll add a test here with `\sum` and `\prod`, perhaps similar to the MWE above. (Not very familiar with adding image comparison tests, but I can try.)

Should the test go in `math_tests` or `lightweight_math_tests`?

**Comment by timhoffm** [comment]
Not an expert here, but I think there should be no differences between fonts, so `lightweight_math_tests` is sufficient.

**Comment by tfpf** [comment]
I added the test. Is there anything else to be done?

**Comment by oscargus** [comment]
> should be no differences between fonts

You are correct in that it should not be any difference, but I think there is (at least based on other examples). However, I still think this is enough as things like spacing is not really what it could be. The PR solves the problem it claims to do, so I think it is good to go.

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Hi-five ✋ on merging your first pull request to Matplotlib, @username! We hope you stick around and invite you to continue to take an active part in Matplotlib!

Your choices aren’t limited to programming 😉 – you can review pull requests, help us stay on top of new and old issues, develop educational material, refresh our documentation, work on our website, create marketing materials, translate website content, write grant proposals, and help with other fundraising initiatives. For more info, check out: https://matplotlib.org/stable/devel/index

f you haven’t yet, do join us on [gitter](https://gitter.im/matplotlib/matplotlib) and [discourse](https://discourse.matplotlib.org/) 🗣. The former is a chat platform, which is great when you have any questions on process or how to fix something, the latter is a forum which is useful for longer questions and discussions.

Last but not least, we have a monthly meeting 👥 for new contributors and a weekly meeting for the maintainers, everyone is welcome to join both! You can find out more about our regular project meetings in [this calendar page](https://scientific-python.org/calendars/).

**Comment by tfpf** [comment]
Thanks! Yep, will most certainly hang around!

**Pull request merged**
