### PR TITLE
Don't draw text when it's completely clipped away

### LINKED ISSUE #5429: Segfault in matplotlib.tests.test_image:test_get_window_extent_for_AxisImage on python3.5
On master here: https://travis-ci.org/matplotlib/matplotlib/jobs/89776539

Unfortunately this is not caught because we use the nose multiprocessing plugin just skips the test

### PR DESCRIPTION
**Pull request by mdboom**
Fix #5429.

### CODE REVIEW

**Comment by tacaswell** [comment]
This needs to get backported to 2.0.x as the faster text rendering was backported there as well.

**Comment by jenshnielsen** [comment]
Thanks unfortunately there seems to be something wrong 

boxarrow_test_image

**Comment by jenshnielsen** [comment]
I think that is due to the change from 
```
(yi - (y - image.dim(0))
to
```
(yi - y) - image.dim(0))
```

**Comment by mdboom** [comment]
Updated per @jenshnielsen

**Comment by jenshnielsen** [comment]
backported as 51291360b4047986cc2608166b924d79c5497c6ea

**Pull request merged**
