### PR TITLE
Tabbed gtk3 figuremanager

### PR DESCRIPTION
**Pull request by fariza**
*Updated description*:

Main goals of this backend
=============
 - Be able to group figures under the same window, and under the control of the same toolbar
 - Be able to easily modify the toolbar adding and removing toolitems.

Main characterstics of the multi-figure-backends
-------------
 - The configuration of the figures can be rearranged after creation by detach and reparent methods in the manager.
 - The single-window configuration is OFF by default, the user has to specifically set matplotlib.rcParams['backend.single_window'] = True for this multi-figure functionnality to become visible
 - It is possible to choose the window under wich the figure is going to be placed from the figure instantiation with the parent keyword
 - The multi-figure-toolbar has a add_tool method, that allows the user to implement tools and integrate them to the toolbar without modifing the backend
 - It is possible to use the Navigation keybindings even if the toolbar is disabled. Following the idea of https://github.com/matplotlib/matplotlib/pull/1849
 - There is an extra toolitem in the multi-figure-toolbar that SaveAll the figures under the window, not just the current one.

The PR includes:
-------------
 - The base clases to implement
  - multi-figure-backend
  - multi-figure-toolbar
  - tools that integrate with a multi-figure-toolbar
 - GTK3 Multi-figure-Backend implementation
 - Example of use examples/user_interfaces/multifigure_backend_gtk.py

The proposed implementation of the GTK3
-------------
 - The backend display figures inside a notebook instead of separate windows.
 - It is possible to detach and destroy the figures directly from the tabs of the notebook (individual detach and destroy buttons)
 - There is a tool for line managent (The lines tool that was with the GTK3 backend was not working due to the use of deprecated libglade.)
 - There is a tool for axes management

*I documented base classes following the numpydoc  (did my best).*

### CODE REVIEW

**Comment by tacaswell** [comment]
@fariza Where did we leave this?

**Comment by fariza** [comment]
@tacaswell I am working on a replacement that uses the MEP22 stuff, more aligned with MEP23 https://github.com/matplotlib/matplotlib/wiki/Mep23
Maybe I should just close this one and wait until MEP22 is merged

**Comment by tacaswell** [comment]
That sounds reasonable to me.

Really sorry about the epic odyssey getting these things review and merged as been.

**Comment by LindyBalboa** [comment]
@tacaswell Do you know if any of this actually ever got implemented? I'm currently building a small application (Qt based), to help with a school project, which integrates multiple tabs in a figure manager. If I were to want to try and add any of this to mpl, I just wanted to see if there was existing structure in another backend that should be considered.

**Comment by fariza** [comment]
@LindyBalboa I am waiting for MEP27https://github.com/matplotlib/matplotlib/pull/4143 to be merged before submiting my work on MEP23 (Multi Figure Manager).

Check https://github.com/fariza/tabbed_backend
This is my independent implementation of the tabbed backend. If you need any help getting it to run just let me know.

**Comment by LindyBalboa** [comment]
Okay cool. I won't have a chance to play with that for a bit anyways. Got a couple other small things to take care of (plus exams. EW.) first. But glancing over your implementation, I should have no problem setting up something similar for Qt. Cool!

**Comment by fariza** [comment]
@LindyBalboa Pr's are welcome, most of the work will be ported to main MPL in MEP23

**Comment by astromancer** [comment]
@fariza @LindyBalboa Just came across this after I released a package that does this in QT: https://github.com/astromancer/mpl-multitab. Comments and feedback welcome.  Keen to collaborate?

**Comment by fariza** [comment]
@astromancer I wanted this to be backend agnostic, but never got enough interest.
My main comment is that I used the  backend tools to be able to keep the state of the pan/zoom buttons across different tabs (this generated diverging opinions)

**Pull request closed without merging**
