### PR TITLE
Changing environment.yml for it to work on Windows

### PR DESCRIPTION
**Pull request by lucasricci**
## PR Summary

I moved the `pikepdf` package under the pip instalation area, this is because this package is not available on windows throught `conda-forge`, so it was failing to create the conda environment, but it is present as a pip package.

Changes:
```yml
# To set up a development environment using conda run:
#
#   conda env create -f environment.yml
#   conda activate mpl-dev
#   pip install -e .
#
name: mpl-dev
channels:
  - conda-forge
dependencies:
  - cairocffi
  - contourpy>=1.0.1
  - cycler>=0.10.0
  - fonttools>=4.22.0
  - kiwisolver>=1.0.1
  - numpy>=1.19
  - pillow>=6.2
  - pygobject
  - pyparsing
  - pyqt
  - python-dateutil>=2.1
  - setuptools
  - setuptools_scm
  - wxpython
  # building documentation
  - colorspacious
  - graphviz
  - ipython
  - ipywidgets
  - numpydoc>=0.8
  - packaging
  - pydata-sphinx-theme
  - sphinx>=1.8.1,!=2.0.0
  - sphinx-copybutton
  - sphinx-gallery>=0.10
  - sphinx-design
  - pip
  - pip:
      - mpl-sphinx-theme
      - sphinxcontrib-svg2pdfconverter
      - pikepdf
  # testing
  - coverage
  - flake8>=3.8
  - flake8-docstrings>=1.4.0
  - gtk3
  - ipykernel
  - nbconvert[execute]!=6.0.0,!=6.0.1
  - nbformat!=5.0.0,!=5.0.1
  - pandas!=0.25.0
  - psutil
  - pre-commit
  - pydocstyle>=5.1.0
  - pytest!=4.6.0,!=5.4.0
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - tornado
  - pytz
```

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
Am I correct that now pikepdf will always be installed from pip, even if it is available through conda?

Is it possible to do something like is done for the testing requirements? (I have no idea if/how this works...)
```
pywin32; sys.platform == 'win32'
```

**Comment by lucasricci** [comment]
I think so, we could see if it is possible to create a test for recognize the OS. If on windows download from pip, if Linux or macOS download from conda.

**Comment by lucasricci** [comment]
Or we can create two files, like `environmentwin.yml` and `environment.yml`

**Comment by tacaswell** [comment]
Yes, we now always pull `pipepdf` from pip, but I am not too worried about that.

Lets push off sorting out how to do OS gating until we know it is a problem.

**Pull request merged**
