### PR TITLE
pass deprecation warning thrown using PySide6

### PR DESCRIPTION
**Pull request by kvnp**
## PR Summary
Using matplotlib 3.7.0 with PySide 6.4.2 on Python 3.10.5 does not work. Instantiating FigureCanvasQTAgg raises DeprecationWarning and stops the application. Catching it fixes it.

I used the following example: https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_qt_sgskip.html

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by jklymak** [comment]
Do you understand why a deprecation warning would raise an error here?  Warnings don't usually kill the process...

**Comment by tacaswell** [comment]
I can not reproduce this failure, however it raising a warning as an exception is ... surprising but it would not be the most surprising thing pyside does.

Can you sort out which pyside6 attribute / method is causing this?

------

The docs failure is unrelated.

**Comment by QuLogic** [comment]
A warning is just a exception that the interpreter catches, prints out and returns to the caller (by default.) Are you running with `-Werror`?

**Comment by jklymak** [comment]
@kvnp can you clarify the need for this?

**Comment by kvnp** [comment]
> A warning is just a exception that the interpreter catches, prints out and returns to the caller (by default.) Are you running with `-Werror`?

Thanks! That's what I was doing. I'm integrating matplotlib into an existing project and didn't pay attention to the launch configuration.

Removing it fixes it, but wouldn't it be meaningful to catch the warning, since setting that attribute is expected not to work? How does PyQt handle this? Is it throwing an AttributeError instead?

**Comment by QuLogic** [comment]
> Removing it fixes it, but wouldn't it be meaningful to catch the warning, since setting that attribute is expected not to work? How does PyQt handle this? Is it throwing an AttributeError instead?

Catch what warning? Setting what attribute? How does PyQt handle _what_? You still haven't provided any context and no-one else can reproduce.

**Comment by kvnp** [comment]
> Catch what warning? Setting what attribute? How does PyQt handle _what_? You still haven't provided any context and no-one else can reproduce.

How much more context do you need? It's all in the comments as well as in the diff of this PR. I ran the example with `-Werror`. It's part of the launch configuration of the project I'm working on.

I discovered that it's possible to ignore certain warnings, I'm going to stick with that.

**Comment by tacaswell** [comment]
What is the deprecation that was triggering this?

We should definitely fix the warning, but catching the deprecation error is not the right fix.

**Pull request closed without merging**
