### PR TITLE
Remove LaTeX checking in setup.py.

### PR DESCRIPTION
**Pull request by anntzer**
We already have runtime tests for LaTeX and associated dependencies; the
check in setup.py is not used for anything.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
These checks are already available at runtime (as `matplotlib.checkdep_foo`), when the check is arguably more useful (it is not like a build time option where we actually need to build a different version of matplotlib depending on whether tex is available; even with tex not present I can just first install matplotlib and then install tex and everything will work fine).

**Comment by tacaswell** [comment]
It is nice to catch the warning when you install rather than when something fails.

**Comment by anntzer** [comment]
But this only gets executed when installing from source rather than from a wheel or a conda package (which is likely the most common case where the warning would be useful...).

**Comment by tacaswell** [comment]
Can we move this to (or do we already have?) a utility function at in the top level namespace like `check_latex_installation() -> Dict[packag_name, version or None]`?

**Comment by anntzer** [comment]
You mean these? :-)
```
In [7]: matplotlib.checkdep_dvipng()
Out[7]: '1.15'

In [8]: matplotlib.checkdep_tex()
/usr/bin/ipython:1: MatplotlibDeprecationWarning: The checkdep_tex function was deprecated in version 2.1.
  #!/usr/bin/python3
Out[8]: '3.14159265'

In [9]: matplotlib.checkdep_ghostscript()
Out[9]: ('gs', '9.22')
```
(and a few others)

**Comment by tacaswell** [comment]
Yes, those.  We should bundle them up into one summary function?

**Comment by anntzer** [comment]
That's what I proposed above (but you may have missed the edit :-))

**Comment by tacaswell** [comment]
:+1:

**Pull request merged**
