### PR TITLE
facecolor stale missing

### PR DESCRIPTION
**Pull request by fredrik-1**
`axes.facecolor` doesn't update the figure in interactive mode. 

I added the line
`self.stale = True`
that fix that.

### CODE REVIEW

**Comment by tacaswell** [comment]
If you noticed this, that means your are using `stale` and that makes me happy!

**Comment by WeatherGod** [comment]
Do we have a way to test stale-related things? Also, should this be back-ported?

**Comment by tacaswell** [comment]
There are some tests, but not exhaustive.

I am 50/50 on backporting this (it is a bug from the original implementation for iirc 1.4)

**Comment by jklymak** [comment]
Merged with backport.  Can revert backport if we think its a mistake, but I don't see the harm in making this work...

**Pull request merged**
