### PR TITLE
Fix multiple zero labels when using SymLogNorm

### LINKED ISSUE #10122: Color bar has multiple labels for 0 if matplotlib.colors.SymLogNorm is used
### Bug report

**Bug summary**

The color bar has multiple labels with the value 0 if `matplotlib.colors.SymLogNorm` is used leading to a "bold-looking" label.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import matplotlib as mpl

fig, axes = plt.subplots(1, 2, True, True)

for i, ax in enumerate(axes): 
    im = ax.imshow([[0]], norm=mpl.colors.SymLogNorm(1e-5, vmin=-1, vmax=1))
    cb = plt.colorbar(im, ax=ax)

# Clean up the labels
zero_labelled = False
for label in cb.ax.yaxis.get_ticklabels():
    if label.get_text() == r'$\mathdefault{0}$':
        if zero_labelled:
            label.set_visible(False)
        zero_labelled = True
```

**Actual outcome on the left, expected outcome on the right**

image

**Matplotlib version**

  * Operating system: Linux 1061836d2c20 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 GNU/Linux
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: numpy (1.13.3)

All libraries were installed using pip in a docker image derived from `python:3`.

### PR DESCRIPTION
**Pull request by Raab70**
## PR Summary
~~Use the previously unused position of a tick label to ensure that only a single zero label is rendered when using SymLogNorm. I store the first time a zero label is encountered and return blanks for all following zeros. The documentation on the `ticker.SymmetricalLogLocator.tick_values` shows how these multiple zeros come to be through the linear approximation near zero.~~

As per discussion below I have taken a different approach, trying to fix the root cause of the problem in the locator (`ticker.SymmetricalLogLocator.tick_values`) so that the extra zero ticks are never created in the first place. 

Fixes #10122 

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- N/A New features are documented, with examples if plot related
- N/A Documentation is sphinx and numpydoc compliant
- N/A Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- N/A Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/blob/64874e5d05dbc9a03d1662e5a3e6bf1cf092409f/lib/matplotlib/ticker.py#L2215

https://github.com/matplotlib/matplotlib/blob/64874e5d05dbc9a03d1662e5a3e6bf1cf092409f/lib/matplotlib/ticker.py#L2353

**Comment by Raab70** [comment]
That’s a great point. I’ll spend some more time in the locator and the linear approximation around zero and see if there’s a good way to ensure only a single zero value.

**Comment by Raab70** [comment]
@jklymak @anntzer Thanks for your help and patience, I believe this is the root of the issue. The multiple zeros are stemming from subticks being added. This change just prevents the addition of subticks to the zero label (since they will all be zero).

**Comment by tacaswell** [comment]
:+1: That makes sense and looks like a reasonable fix.

Could you add a test?  I suspect creating a symlog axis and then asserting that there is only 0 zero label it in is the best approach (no need for an image test).  The OP example is maybe a bit complex to trigger this, but as a last resort would be ok to use a test.

**Comment by dstansby** [comment]
Thanks a lot @Raab70!

**Pull request merged**
