### PR TITLE
ENH: Added `file` keyword to `setp` to redirect output

### PR DESCRIPTION
**Pull request by madphysicist**
Added this based on something I noticed with #6217.

### CODE REVIEW

**Comment by madphysicist** [comment]
Appveyor fails because conda won't install, not in an actual test.

**Comment by madphysicist** [comment]
Failure is unrelated to PR. Image mismatch.

**Comment by tacaswell** [comment]
This might need an entry in https://github.com/matplotlib/matplotlib/tree/master/doc/users/whats_new

What is the motivation for this?

**Comment by madphysicist** [comment]
I wanted to be able to print to `sys.stderr` mostly. My stdout was going to a file. This seemed like the easiest thing to do at the time.

**Comment by madphysicist** [comment]
Rebased and added a doc to whatsnew.

**Pull request merged**
