### PR TITLE
DOC: added missing import to navigation_toolbar.rst

### LINKED ISSUE #5645: Missing line in a self-sufficient example in navigation_toolbar.rst :: a minor bug in docs
(see at the bottom http://matplotlib.org/users/navigation_toolbar.html )

I presume such examples are designed to be self-sufficient, and therefore instead of 

    from matplotlib.figure import Figure
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
    from matplotlib.backends.backend_gtkagg import NavigationToolbar2GTKAgg as NavigationToolbar

it should contain 

    import gtk
    
    from matplotlib.figure import Figure
    from matplotlib.backends.backend_gtkagg import FigureCanvasGTKAgg as FigureCanvas
    from matplotlib.backends.backend_gtkagg import NavigationToolbar2GTKAgg as NavigationToolbar

as shown in another example http://matplotlib.org/examples/user_interfaces/embedding_in_gtk.html

### PR DESCRIPTION
**Pull request by jonchar**
Fixes #5645

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1:

**Comment by tacaswell** [comment]
backported to v1.5.1-doc as 10a860e

**Comment by tacaswell** [comment]
Thanks!

**Comment by jonchar** [comment]
No problem!

**Pull request merged**
