### PR TITLE
DOC: savefig method not necessarily on current figure

### PR DESCRIPTION
**Pull request by rcomer**
## PR Summary
As I understand it, the `savefig` method will save the figure the method is called on, which may not necessarily be the current (active) figure.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by rcomer** [comment]
Hmmm, I just realised this would also change the `pyplot.savefig` docstring, so perhaps it is not such a good idea 🤔

**Comment by tacaswell** [comment]
"current" as in `plt.gcf()` or "current" as in the one you are interacting with is a bit of rhetorical slight-of-hand...

**Comment by tacaswell** [comment]
I'm not sure the slight of hand is _good_, but I do not see a way to clarify this without doing docstring templating or something so that the inherited version can be different.

**Comment by rcomer** [comment]
@tacaswell yup, I agree.  It's a little unsatisfying, but sometimes you just have to be pragmatic!

**Pull request closed without merging**
