### PR TITLE
Addresses issue #24617 adding setters/getters for Figure

### PR DESCRIPTION
**Pull request by garveyz2**
## PR Summary
Hello, this is my first contribution to an open-source project. This PR is to address the concerns raised in #24617. I've cherrypicked my solution from a previous PR #21549. I have mainly added setters and getters for subplot params as well as modifying the aliases for size_inches to figsize and layout_engine to layout. 

## PR Checklist

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] New plotting related features are documented with examples.

**Release Notes**
- [x] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [x] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [x] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by rcomer** [comment]
@garveyz2 thanks for your work on this.  Is it ready to be reviewed?  If so you should see a "Ready for review" button which will take the "draft" status off it.

**Comment by NoyHanan** [comment]
Hi @rcomer,
I would like to take over this pr, can you please give me permissions? 
Thanks!

**Comment by rcomer** [comment]
Thank you @NoyHanan.  Please create a new branch and a new PR referencing this one.  You could `git cherry-pick` the commits from here into your branch or write something new, whichever you prefer.

**Comment by tacaswell** [comment]
I am going to close this PR as abandoned. 

Thank you for your effort @garveyz2 I do hope we hear from you again.

**Pull request closed without merging**
