### PR TITLE
Fix streamline plotting from upper edges of grid

### PR DESCRIPTION
**Pull request by dstansby**
## PR Summary
Fixes https://github.com/matplotlib/matplotlib/issues/21649. See the added comment for info and motivation.

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by dstansby** [comment]
The fixed bug is illustrated rather nicely in the new test image!

**Comment by jklymak** [comment]
Yes, the image does a good job, but given that we have indexing errors like this, would you consider starting from the other edges as well?

**Comment by dstansby** [comment]
> Yes, the image does a good job, but given that we have indexing errors like this, would you consider starting from the other edges as well?

As in adding streamlines drawn from around the edges to the figure test?

**Comment by jklymak** [comment]
Yep, just some more lines.

**Comment by dstansby** [comment]
👍 done. Is it worth getting rid of the pdf and svg test images at the same time too?

**Comment by jklymak** [comment]
I would unless we are testing something with them.

**Comment by jklymak** [comment]
One of the dots doesn't have a line.  Is that expected because it is close to an existing line?

**Comment by dstansby** [comment]
> One of the dots doesn't have a line. Is that expected because it is close to an existing line?

Yes, that's correct.

I've removed the pdf/svg images, and also removed the tolerance that was on this test before to see if we can do without it.

**Review by jklymak — APPROVED** [review]

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
