### PR TITLE
DOC: add note about enabling c++11 support for old gcc

### LINKED ISSUE #24530: [Doc]: update minimum gcc version?
### Documentation Link

https://matplotlib.org/devdocs/devel/dependencies.html#c-compiler

### Problem

The minimum stated version of gcc for building matplotlib is currently 4.8.1.  When trying to build matplotlib with (our system default) gcc v4.8.5, I get

```
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
```

On the same system, if I point at gcc v8.1.0, the build works fine.

### Suggested improvement

I suspect the simplest option would be to increase the stated minimum version in the installation guide, though I do not know what version that would be.  I note that 4.8.5 came out in 2015.

### PR DESCRIPTION
**Pull request by tacaswell**
Closes #24530

@rcomer Can you confirm if this works for you?

### CODE REVIEW

**Comment by tacaswell** [comment]
This is the "lazy" option.

**Review by QuLogic — APPROVED** [review]

**Review by rcomer — COMMENTED** [review]
Thanks @tacaswell, I tried

```
export CXXFLAGS=-std=c++11
```

before the install, but got the same error.  Am I misunderstanding how to set this?

**Comment by oscargus** [comment]
It seems like one have to set `CFLAGS` as `gcc` is used to compile some cpp-files... (It is OK not to set `CXXFLAGS`, at least on my CentOS 7 install.)

You will get a warning though for some of the compile steps:
```
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C [enabled by default]
```

**Comment by rcomer** [comment]
Thanks @oscargus 

```
export CFLAGS=-std=c++11
```
worked for me too.  I'm on RHEL7 (apparently next year we get RHEL9...)

**Comment by oscargus** [comment]
A small follow-up on this. Although it compiles and looks like it installs correctly there is also another message of interest:
``` 
/local/data1/miniconda3/compiler_compat/ld: build/freetype-2.6.1/objs/.libs/libfreetype.a(ftinit.o): plugin needed to handle lto object
```
and running mpl leads to 
```
ImportError: /local/data1/matplotlib/lib/matplotlib/ft2font.cpython-39-x86_64-linux-gnu.so: undefined symbol: FT_Load_Glyph
```

Do you get similar behavior @rcomer or does it work for you?

(This is for gcc 4.8.5, but I also have 7.3.1 and there it builds without problem, so back to a working version now...)

**Comment by rcomer** [comment]
@oscargus I don't see that error about the plugin, and I just used the environment to reproduce #24545.

**Review by rcomer — APPROVED** [review]

**Comment by rcomer** [comment]
Thanks All!

**Comment by rcomer** [comment]
@tacaswell I see this is 2 commits.  Should I squash-merge or just commit both or something else?

**Review by ksunden — APPROVED** [review]

**Comment by ksunden** [comment]
Cycling CI because it looked like a few checks had network errors that were likely temporary

**Comment by QuLogic** [comment]
You can do that directly in Circle; no need to modify the PR.

**Pull request merged**
