### PR TITLE
Ternary

### PR DESCRIPTION
**Pull request by HubertHolin**
This update should (git permitting…) resolve the failures referenced as

https://travis-ci.org/matplotlib/matplotlib/jobs/41735175

and as discussed in https://github.com/matplotlib/matplotlib/pull/3828 .

### CODE REVIEW

**Comment by HubertHolin** [comment]
Looking at the AppVeyor failures, I do not see how they relate to this PR. Is this a known (general) failure?

Looking at the COVERALL failures, I'll have to check, but this might be due to changes in the code preceding my modification. Is this something we should really worry about? If so, I'll try and see what precisely has to be done to redress the situation.

**Comment by jenshnielsen** [comment]
Just ignore coveralls it seems to be flaky. But that being said if we are going to merge this in will need good test coverage of the Ternary module. 


The failures on AppVeyor are probably not related.

**Comment by janschulz** [comment]
closing and reopening to see if the changes in master regarding the miktex failure lets this pass.

**Comment by jklymak** [comment]
There is a pretty robust community that uses Ternary diagrams.  How many of them use matplotlib is another issue.  But this would be a nice addition at some point.  My quick look at it is that the interface still needs some work, and that the demo should definitely *not* be in `pylab` :wink:

**Comment by anntzer** [comment]
I agree that this would be better suited as a third party package.

**Comment by jklymak** [comment]
Closing then - this PR will still turn up in a google search and someone can base their code on it.  If someone wants to open as an issue, then great!

**Comment by HubertHolin** [comment]
Hi

Sorry for replying late. Kevin Davies developed the code Ligon and I afterwards updated. I had also independently developed the same kind of functionality for work (meteorology - a very long time ago this started as MATLAB code), and updated it for my personal research (math - see for instance https://arxiv.org/abs/1610.02295). The original idea was that perhaps Kevin's code and mine would be merged, but this did not happen (lack of time, on my part, sorry). As I understand, the preferred solution would be to pull the code from matplotlib and put into an independent package. I have no objection to that, but would like to know what Kevin and Ligon feel about it. As well, which code base should be used? What interface adjustments would be wanted? I can (probably) work on this this summer (after I document and release an entirely different python library in the next few days, and an also completely different C++ library a little later on).

Perhaps a new thread would be useful. Any comment welcome!

**Comment by carlosgmartin** [comment]
@jklymak What is the recommended package for [ternary plots](https://en.wikipedia.org/wiki/Ternary_plot)?

**Comment by jklymak** [comment]
I don't make ternary plots so your google search would be as good as mine.  If you find a good one, encourage them to submit to https://matplotlib.org/mpl-third-party/

**Comment by HubertHolin** [comment]
Paris (U.E.), le 24/09/2022

	Hi

		Some six years or so ago, I had submitted a matplotlib package to create ternary diagrams that I had developed for work I was doing at the time. Another package was made by Kevin Devies or Ian Thomas, and the aim, at the time was to unify them. However it was later decided that it would be better if that package were not integrated into the matplotlib distribution, but given as a third party package. Sadly, I never had the time to do the work which was needed at the time, and as well did not need to use ternary diagrams for subsequent work, so the project died slowly. At least the package you found still exists and seems to be usable (I have not tried this), though the tradeoffs look different from the older packages (this one relies on more packages than mine, for instance, but the older packages had a utility layer written in C++ to accelerate things, which this one seems not to have).

		If there is some interest, and I finally have some time, I might try to revive this, but it might take quite some time to do, if only to remember what had to be done, so, in the meantime, it would certainly be best to go with what works now.

	Best of luck

			Hubert Holin

**Comment by kdavies4** [comment]
Hubert, all,
It's good to hear about this, and I endorse taking this however the team decides is best. I contributed my part to ternary plots as a general fascination and use in visualizing some work for my PhD, but since then, well life gets busy, and I still don't think I have the resources to actively participate. As I recall, what I did was somewhat of a hack of layering and transposing existing axes in matplotlib, and a "cleaner" approach would have required some fundamental changes or additions to the existing matplotlib axes or a new class entirely which could have been rather disruptive. I guess that's where the suggestion came for a third party package. Regardless, my point is that if there is interest and opportunity to revive this, I say by all means please go ahead.
Best regards, 
Kevin (from Honolulu, HI USA)

**Pull request closed without merging**
