### PR TITLE
Don't mark a patch transform as set if the parent transform is not set.

### PR DESCRIPTION
**Pull request by anntzer**
When updating a patch from another artist, if the other artist's
transform is marked as "uninitialized" (`_transformSet == False`), then
don't mark the updatee's transform as set either.

Typically, this occurs if the updator has not been added to an Axes yet;
its transform will be set when that adding occurs.  In that case, the
updatee's transform also needs to be set when actually being added to an
Axes.

Closes the incorrect transform part of #9377.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Is there a good test for this?

**Comment by tacaswell** [comment]
Sorry, changed my mind about where to target this to again.

**Comment by anntzer** [comment]
To be honest, looking at it again, I am not even that certain that that the constructor of that Shadow class makes a lot of sense.  Specifically, if I got it correctly, the ox and oy values are first multiplied by the dots-per-point conversion factor (e.g. 100/72 at 100dpi), then interpreted as offsets in *data* coordinates.  Which is quite... uh?

**Comment by tacaswell** [comment]
Looking at the history this goes back to JDH in 2004 so it pre-dates the transform machinery and I would guess added as a gee-whiz feature.

If you think it could be cleaned up for 2.2 :+1:

**Comment by anntzer** [comment]
I'm not really convinced of the utility of providing this class, but heh.

A problem with interpreting ox, oy as offsets in data units is that the only two public APIs that rely on that class (other than Shadow itself) are `pie(..., shadow=True)` and `legend(..., shadow=True)`, and for pie charts (which set the axes to polar) you'd better *not* interpret ox, oy in data coordinates.

So perhaps ox, oy should be interpreted either as axes coordinates or figure coordinates -- don't have a clear preference right now.

**Comment by anntzer** [comment]
@dstansby test has been added (a while ago, but no worries)

**Comment by efiring** [comment]
@dstansby Would you like to re-review and merge if it is OK?

**Comment by anntzer** [comment]
Seems ready to go in for 3.0 so labeling as RC.

**Pull request merged**
