### PR TITLE
WIP/DOC: explain behavior of notches beyond quartiles

### LINKED ISSUE #3631: Better document meaning of notches in boxplots
Hi,
I found a problem regarding the `boxplot` function when the `notch` shape is being used (matplotlib 1.4.0).

I uploaded an self-contained [example](http://nbviewer.ipython.org/github/rasbt/matplotlib-gallery/blob/master/bugreport/boxplot_notch/boxplot_notch.ipynb) as IPython notebook with more details.

### PR DESCRIPTION
**Pull request by phobson**
closes #3631 

Haven't had a chance to try to build to docs to make sure I didn't mangle the RST in the docstring. 

Does Travis test that?

### CODE REVIEW

**Comment by tacaswell** [comment]
Travis does build the docs these days (and pushing them to http://matplotlib.org/devdocs/ for master branch builds).

**Comment by tacaswell** [comment]
The text seems fine (to my level of understanding).  What is still WIP about this?

**Comment by phobson** [comment]
was just waiting to build the docs locally to confirm. the travis build on my branch failed. looks like this one passed though.

**Comment by tacaswell** [comment]
backported to v2.x as 05d910d

**Pull request merged**
