### PR TITLE
Doc change for matshow function clarifying row and column positions

### LINKED ISSUE #27852: [Bug]: matplotlib.pyplot.matshow "(first dimension of the array) are displayed horizontally" but are displayed vertically
### Bug summary

matshow states that  "(first dimension of the array) are displayed horizontally": https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.matshow.html#matplotlib-pyplot-matshow. However it seems that the first dimension is vertically.

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt


nx = 15
ny = 21

img = np.zeros((nx, ny))

for i in range(nx):
    for j in range(ny):
        if j == i:
            img[i, j] = 1

plt.figure()
plt.subplot(1, 2, 1)
plt.imshow(img)
plt.title('imshow')
plt.subplot(1, 2, 2)
plt.matshow(img, fignum=0)
plt.title('matshow')
plt.show()
```

### Actual outcome

First dimension is shown vertically

### Expected outcome

I would expect that the first dimension be show horizontally according to the documentation.

### Additional information

_No response_

### Operating system

Debian 12

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.12

### Jupyter version

_No response_

### Installation

conda

### PR DESCRIPTION
**Pull request by Impaler343**
## PR summary

This changes the documentation of the matshow function, making it clearer as to which dimension corresponds to which number in the array passed to the function. The convention used is standard practice, where the first number(rows) corresponds to the length of the vertical column and the second number(columns) corresponds to the length of the horizontal column.
Closes #27852

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by jklymak** [comment]
You can push changes to the same branch rather than opening and closibg PRs

**Comment by Impaler343** [comment]
Yeah, that was the plan, but I'm still figuring my ways around github, and I faced an issue where each subsequent PR had the history of commits alon with it. I tried looking for methods to fix this, and I found _cherry-pick_ and _branch-to-branch pushing_ PRs. Later I figured out, the changes I tried to implement somehow ended up in the main branch, and reverting merges is already sufficiently painful, due to which I deleted the fork and created a new one :) Any suggestions/comments would be welcome

**Comment by rcomer** [comment]
@Impaler343 our contributors’ guide here may help
https://matplotlib.org/devdocs/devel/development_setup.html

**Comment by Impaler343** [comment]
Oh wow, thank you very much! I think I need to read the entire documentation before starting off. Thanks!

**Comment by timhoffm** [comment]
Superseeded by #27857.

**Pull request closed without merging**
