### PR TITLE
ENH: add unified seaborn style sheet

### LINKED ISSUE #6452: Please add a generic "seaborn" style
I'm glad that matplotlib has included seaborn aesthetics in its built-in style sheets. However, the way that the different elements of the seaborn aesthetics were split up (i.e., that there are separate `seaborn-darkgrid`, seaborn-deep`, etc.) is both a little confusing and produces results that are, imo, visually unappealing.

I would much prefer if there were also a single "seaborn" style that encompasses `seaborn-darkgrid`, `seaborn-deep`, and `seaborn-notebook`, so that doing `plt.style.use("seaborn")` would create plots that look the same as actually importing seaborn.

### PR DESCRIPTION
**Pull request by tacaswell**
closes #6452 

attn @mwaskom I think this is half of what you had in mind.

### CODE REVIEW

**Comment by mwaskom** [comment]
LGTM, thanks!

**Comment by efiring** [comment]
Is there a reason why it is called "sns" instead of "seaborn"?

**Comment by tacaswell** [comment]
`sns` is the normal import alias of seaborn and is less letters.

**Comment by WeatherGod** [comment]
As someone who doesn't use seaborn, I wouldn't have guessed that "sns" was
the seaborn style.

On Sun, May 22, 2016 at 10:00 PM, Thomas A Caswell <notifications@github.com

**Comment by tacaswell** [comment]
renamed to seaborn

**Comment by WeatherGod** [comment]
this need to be backported at all?

**Comment by efiring** [comment]
Yes, it should go to v2.x.

**Comment by WeatherGod** [comment]
backported to v2.x via e70bc42b3

**Pull request merged**
