### PR TITLE
Better test for isarray in figaspect(). Closes #5464.

### LINKED ISSUE #5464: figaspect not working with numpy floats
If I try to use a numpy float as the input of the `matplotlib.pyplot.figaspect` function, I get an error.
This is the code

    import numpy as np
    import matplotlib.pyplot as plt
    
    aspect = np.float64(2) / np.float64(1)
    # print aspect
    w, h = plt.figaspect(aspect)
    fig = plt.figure(figsize=(w,h))
    ax = fig.add_axes([0.1, 0.1, 0.8, 0.8])

with the Error

```
/usr/local/lib/python2.7/dist-packages/matplotlib/figure.pyc in figaspect(arg)
   1770     # Extract the aspect ratio of the array
   1771     if isarray:
-> 1772         nr, nc = arg.shape[:2]
   1773         arr_ratio = float(nr) / nc
   1774     else:

ValueError: need more than 0 values to unpack
```

If I convert `aspect` to a `float`, it works ok

### PR DESCRIPTION
**Pull request by WeatherGod**

### CODE REVIEW

**Comment by WeatherGod** [comment]
Note that this change does change how the function errors if given a list or a tuple. Previously, it would error saying that it could not convert a list into a tuple. Now, it would give an attribute error. Don't know if anybody cares. It would be easy enough to put the attribute check back in.

**Comment by tacaswell** [comment]
Can you just document the API change?

**Comment by tacaswell** [comment]
If you add an `np.asarray` around line 1771 lists/tuples should work fine as well?

**Comment by WeatherGod** [comment]
Eh, rather than possibly causing an api change, I just added that attribute test back in (less to write and all that). I also added unit tests, which is always a good thing, right?

I am -0 on adding support for lists and tuples. This is for a bugfix, not for extending an API. Plus, I doubt very many people even use this function that way anyway.

**Comment by tacaswell** [comment]
cherry-picked back to v1.5.x as 98a54640a3fce18959a7114a9056f8d5b6c5f661

That is a gnarly API for specifying the aspect ratio....

**Comment by WeatherGod** [comment]
Interestingly, looking at the history, the original API as done by Fernando back in 2005 was to only accept a 2D array. The option to support an number as an input came a few months later...

**Comment by tacaswell** [comment]
Thank goodness that @fperez is insulated from api design these days 😇

**Pull request merged**
