### PR TITLE
Allow args to pass through _allow_super_init

### PR DESCRIPTION
**Pull request by hmaarrfk**
Without this, if you call `FigureCanvas` without any parameters, you would get the error
```
__init__() missing 1 required positional argument: 'figure'
```
But if you would try to provide the positional argument, you would get
```
TypeError: wrapper() takes 1 positional argument but 2 were given
```

because only `**kwargs` were passed through.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Is this correct or is the first error message incorrect? If this is right it’d be nice to have a short test.

**Comment by hmaarrfk** [comment]
The function signature is:

```
class FigureCanvasQT(QtWidgets.QWidget, FigureCanvasBase):

    # map Qt button codes to MouseEvent's ones:
    buttond = {QtCore.Qt.LeftButton: 1,
               QtCore.Qt.MidButton: 2,
               QtCore.Qt.RightButton: 3,
               # QtCore.Qt.XButton1: None,
               # QtCore.Qt.XButton2: None,
               }

    @_allow_super_init
    def __init__(self, figure):
```

which doesn't force `kwargs`

I copy pasted the error messages I got from the terminal. It definitely took me longer than I wanted to find what was wrong in my code.

Where do your tests go?

**Comment by jklymak** [comment]
Tests go in `lib/matplotlib/tests`... But I'm not familiar enough with the low-level backend APIs to know exqctly where or how you should test this.  However, if something this basic got through without tripping a test, then either its being called incorrectly and our documentation needs fixing, or it needs a test!

**Comment by hmaarrfk** [comment]
Yeah.... qt5agg uses a different code path that doesn't have the error. I added a test, but it doesn't cover the error since it is using the Agg backend.

**Comment by anntzer** [comment]
I think the test should really go to test_backend_qt4agg (as there's no problem with qt5)?... which is not run on CI both because we can't install pyqt4 there and because we can't import pyqt4 and pyqt5 in the same process, but that's another can of worms.

Otherwise looks good.

**Comment by hmaarrfk** [comment]
Qt5 is not the same codepath as Qt5Agg.

The problem is with Qt5 (I'm using PySide, but the code change I made is pretty clear that it would happen with PyQt5 as well. I may have tried it in a different environment too, not too sure).

The bug was in `lib/matplotlib/backends/backend_qt5.py`. I'm not sure if it happens in Qt4. I'm pretty sure Qt4 is the same code path as Qt5 these days. I'm really not a matplotlib expert, this one was just easy to fix. I felt it would have taken longer to write the "Issue"

**Comment by anntzer** [comment]
Now I'm confused by how exactly you got the error.  "qt5" is not a backend by itself, qt5agg and qt5cairo are.

**Comment by hmaarrfk** [comment]
I don't see `backends_qt5` importing `backends_qt5Agg`...

backends_qt5 has a different FigureCanvas object 
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5.py#L214
called `FigureCanvasQT`

The bug is in the decorator for `FigureCanvasQT`.

`FigureCanvasQTAgg` is distinct
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5agg.py#L17

**Comment by hmaarrfk** [comment]
But I don't see any tests for the QT backend, only the QTAgg, so I don't really have anything to base myself on. And I'm just learning how to use Qt, so I'm no expert.

**Comment by jklymak** [comment]
I'm still confused; on master, v2.2.2, and v2.2.3 , without this PR, I can run

```python

from matplotlib.backends.backend_qt4agg import FigureCanvas
from matplotlib.figure import Figure

FigureCanvas(Figure())
FigureCanvas(figure=Figure())
```

without the errors in your original message for either qt4 or qt5.  Can you specify what code triggers the error this PR is supposed to fix?

**Comment by hmaarrfk** [comment]
```python
In [2]: from matplotlib.backends.backend_qt5 import FigureCanvas
   ...: from matplotlib.figure import Figure
   ...: 
   ...: FigureCanvas(Figure())
   ...: 
   ...: 
   ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d7282e013989> in <module>()
      2 from matplotlib.figure import Figure
      3 
----> 4 FigureCanvas(Figure())
      5 

TypeError: wrapper() takes 1 positional argument but 2 were given

```

**Comment by jklymak** [comment]
I don't know the history well enough, but I think `backend_qt5` is a convenience abstraction of methods shared between the `backend_qt5agg` and `backend_qt5cairo` backends, and should not be used by itself.   Why it was not made private is above my paygrade, but I don't think its meant to be used directly like this....

**Comment by jklymak** [comment]
Perhaps a better explanation: https://stackoverflow.com/questions/47271291/matplotlib-backends-backend-qt5-vs-from-matplotlib-backends-backend-qt5agg

**Comment by hmaarrfk** [comment]
hmm ok, maybe that is why I had to add the navbar for things to draw.

that said, it is still a bug. the decorator should also pass `*args`.

**Comment by anntzer** [comment]
I can't repro your bug...
```
In [1]: matplotlib.backends.backend_qt5.FigureCanvas(matplotlib.figure.Figure())
Out[1]: <matplotlib.backends.backend_qt5.FigureCanvasQT at 0x7f187ee094c8>
```
(regardless of the fact that this class shouldn't really be instantiated as noted by @jklymak above).

In fact the super-method is called in `FigureCanvasQT.__init__` as
```
        super().__init__(figure=figure)
```
not posiitionally so it's unclear how you can get positional arguments to reach the patched super-init.

**Comment by hmaarrfk** [comment]
Maybe because I'm on PySide2....

PyQt5 just passes the original `__init__`
https://github.com/matplotlib/matplotlib/blob/c51e282b7614bd3719e0c0870455aa54fc5aa90a/lib/matplotlib/backends/backend_qt5.py#L140

The bug happens because the decorator only passes the keyword args and drops the args.

**Comment by anntzer** [comment]
Ah, I see.
The fix looks correct, but then the test is absolutely not testing the correct thing, and I would just remove it (not really worth it, the correct thing is testing instantiation of FigureCanvasQT which as stated above is not really useful anyways, etc.).

**Comment by jklymak** [comment]
Thanks for the persistence @hmaarrfk !  Sorry this was a confusing one...

**Comment by hmaarrfk** [comment]
Yeah it was. I'll try to use Qt5Agg, see how that works.

**Comment by tacaswell** [comment]
@meeseeksdev backport to v2.2.x

**Comment by tacaswell** [comment]
@meeseeksdev backport to v3.0.x

**Comment by tacaswell** [comment]
Looks like this did not get backported to 2.2.x but did make it into 3.0.0, remilestoned to match that.

**Pull request merged**
