### PR TITLE
Refactor code duplication in `matplotlib.markers`

### PR DESCRIPTION
**Pull request by sindunuragarp**
There was some code repetition in `lib/matplotlib/markers.py` in the functions to draw specific markers which had orientation differences such as `vline` and `hline`. Both these functions are exactly the same apart for an additional rotation in `hline`.

I saw that the piece of code with duplication has not been updated in a long time, so I tried to refactor it by removing code duplications. I have tried running the tests and I believe no errors occured because of this refactor.

### CODE REVIEW

**Comment by tacaswell** [comment]
Wait, why don't we need that svg file?  I think that means a test we think is running is not...

**Comment by QuLogic** [comment]
That file should not have been added; it's created by the tests multiple times to be sure determinism works. I think it was moved to a temporary directory at some point, though, so I'm not sure how it accidentally got added.

**Comment by tacaswell** [comment]
Great.  

@sindunuragarp In the future please rebase rather than merging master into your feature branch.

**Comment by sindunuragarp** [comment]
Sorry I'll make sure to remember that :+1:

**Pull request merged**
