### PR TITLE
FIX: set internal flags first in FigureCanvasBase

### LINKED ISSUE #5094: 'FigureCanvasAgg' object has no attribute '_is_idle_drawing' (1.5.0rc1)
Using the MacOSX backend as well as other backends (e.g. the PDF backend), saving a figure to a PNG fails with 1.5.0rc1:

```python
>>> from pylab import *
>>> figure()
<matplotlib.figure.Figure object at 0x10a387210>
>>> plot([1,2,5])
[<matplotlib.lines.Line2D object at 0x10c864a10>]
>>> savefig("test.png")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/pyplot.py", line 690, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/figure.py", line 1540, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 2136, in print_figure
    canvas = self._get_output_canvas(format)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 2072, in _get_output_canvas
    return self.switch_backends(canvas_class)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 2296, in switch_backends
    newCanvas = FigureCanvasClass(self.figure)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 1681, in __init__
    figure.set_canvas(self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/figure.py", line 563, in set_canvas
    self.stale = True
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/artist.py", line 267, in stale
    self.stale_callback(self, val)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/pyplot.py", line 564, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 2023, in draw_idle
    if not self._is_idle_drawing:
AttributeError: 'FigureCanvasAgg' object has no attribute '_is_idle_drawing'
>>> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/figure.py", line 1134, in draw
    func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_base.py", line 2203, in draw
    self.apply_aspect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_base.py", line 1329, in apply_aspect
    self.set_position(position, which='active')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/axes/_base.py", line 836, in set_position
    self.stale = True
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/artist.py", line 267, in stale
    self.stale_callback(self, val)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/figure.py", line 56, in _stale_figure_callback
    self.figure.stale = val
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/artist.py", line 267, in stale
    self.stale_callback(self, val)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/pyplot.py", line 564, in _auto_draw_if_interactive
    fig.canvas.draw_idle()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib-1.5.0rc1-py2.7-macosx-10.9-intel.egg/matplotlib/backend_bases.py", line 2023, in draw_idle
    if not self._is_idle_drawing:
AttributeError: 'FigureCanvasAgg' object has no attribute '_is_idle_drawing'
```

This error does not occur with matplotlib 1.4.3.

### PR DESCRIPTION
**Pull request by tacaswell**
If interactive mode is on using the model where every time any artist is
invalidated/marked as stale a `draw_idle` is triggered and the user is
using a non-Agg based backend, saving a png will result in a draw_idle
call triggered from inside the __init__ method of `FigureCanvasBase`
which then fails because the full object has not been set up (this is
not a problem using the IPython hooks because the stale state is only
checked once when all user code has completed executing).

closes #5094 

attn @mdehoon

### CODE REVIEW

**Comment by tacaswell** [comment]
@efiring Can you take a look at this?  I think that this + #5106 are the 2 blockers for rc2

**Comment by efiring** [comment]
I've been looking at it, but I don't completely understand the sequence of events.  Setting `_is_idle_drawing` to True in something that is not actually triggering an idle draw looks a bit hackish, but I see that it does solve the apparent problem indicated by the traceback in #5094.  Your check for `is_saving` looks plausible, but does it cause a needed screen update to fall on the floor when saving?

**Comment by tacaswell** [comment]
I don't think it will drop a screen update as saving figures goes through `print_figure` instead of the GUI's draw routine.  I think they are completely decoupled (as the saved figure can be at a different DPI than the screen).

The whole `_is_idle_drawing` construction is hacked, but is there so that `draw_idle` is re-entrant and we can fake asynchronous functionality with only synchronous calls (and without `asyncio`).  This is probably also fixable by moving the `figure.set_canvas(self)` all the way to the bottom below the `self._is_idle_drawing = False`, but that will result in the canvas being drawn twice when saving a figure (once in the `print_*` method and once from the auto-redraw).  Doing it as currently done in this PR will suppress the auto-redraw.

Another option is to remove `set_canvas` from the set of things that trigger the stale flag.

**Comment by efiring** [comment]
I don't object to the changes you already have in here; but your last suggestion sounds good, too.  Having `set_canvas` trigger the stale flag seems pointless.  I had actually missed this key point, that it is the `set_canvas` call in `__init__` that is causing the problem in the first place--correct?

**Comment by tacaswell** [comment]
Yes, but it seems something else is going on, I threw a print statement in `Figure.draw` and got this:

```python
>>> import matplotlib              
>>> matplotlib.use('svg')          
>>> import matplotlib.pyplot as plt
>>> plt.ion()                      
>>> plt.plot(range(3))             
[<matplotlib.lines.Line2D object at 0x7f37e065acc0>]
>>> plt.savefig('test.png')        
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
drawing
>>> 
```

**Comment by tacaswell** [comment]
644b4b2 fixed the excessive drawing issue:

```python
import matplotlib
matplotlib.use('svg')
import matplotlib.pyplot as plt
plt.ion()
plt.plot(range(3))
plt.savefig('test.png')
```

```python

(dd_35) ✔ /tmp 
19:05 $ python blarg.py
drawing
(dd_35) ✔ /tmp 
19:06 $ 

```

```diff
12:44 $ git diff
diff --git a/lib/matplotlib/figure.py b/lib/matplotlib/figure.py
index b640fed..a85626d 100644
--- a/lib/matplotlib/figure.py
+++ b/lib/matplotlib/figure.py
@@ -1052,7 +1052,7 @@ class Figure(Artist):
         Render the figure using :class:`matplotlib.backend_bases.RendererBase`
         instance *renderer*.
         """
-
+        print('drawing')
         # draw the figure bounding box, perhaps none for white figure
         if not self.get_visible():
             return

```

**Comment by efiring** [comment]
This is looking better now!  I see that the  `pyplot.draw()` docstring is out of date now; it doesn't reflect all the new stale handling.  Is there actually any need for it at all now, apart from backwards compatibility?

**Comment by efiring** [comment]
File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.6/site-packages/matplotlib-1.5.0rc1+100.g3b75d4f-py2.6-linux-x86_64.egg/matplotlib/tests/test_backend_ps.py", line 54, in _test_savefig_to_stringio

This is the second time we have gotten this error in one Travis build on this PR.  It is starting to make me wonder whether there is in fact a timing problem; but I wouldn't expect that with a non-interactive backend test.  There should be only one thread, and everything should be proceeding deterministically.

**Comment by tacaswell** [comment]
`plt.draw` is still useful if people are sitting at a repl with interactive mode off (I don't know _why_ you would do that, but).   There are also still a non-zero number of cases where changing attributes should trigger a re-draw, but does not current.  

Most of those will be caught by traitlets.

**Comment by tacaswell** [comment]
I tried re-working those tests a bit, I don't fully trust the multi-process thing that nose does.

**Comment by efiring** [comment]
Was the use of pyplot in test_backend_ps somehow causing the non-deterministic Travis failures?

**Comment by tacaswell** [comment]
See #5152 for why I think this is happening.

I can go either way on pulling the last commit off of this PR.  I like being more explicit about the tests for it's own sake, but am not willing to argue about it ;)

**Pull request merged**
