### PR TITLE
Tweak streamplot plot_types example.

### PR DESCRIPTION
**Pull request by anntzer**
- zorders don't need to be explicitly set, the contour is already below
  the streamplot.
- alpha=0.5 for the contour seems too faint IMO; fully opaque seems
  better?

before:
old
after:
new

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — COMMENTED** [review]
This is the only example that uses a secondary color. What is the purpose of the contour here anyway? I think we can just remove it.

While at it, you could add `ax.grid(False)` after the subplots commands. I think we should leave out the grid for all surface like plots (i.e. where x and y are the dependend variables).

**Comment by anntzer** [comment]
Removed the grid.  I think showing some contours is nice (to hint that the streamlines are indeed following the contour lines), but I can remove them if you feel strongly about it.

**Comment by timhoffm** [comment]
> I think showing some contours is nice (to hint that the streamlines are indeed following the contour lines)

The following is not exact (probably because they are not using the same values), see marked regions:
grafik
so not sure what that would tell us.


On a more general note: I don't think it's important for showcasing the plot type of stream lines that it is related to contours. IMHO all the example plot should have to tell is "We can plot stream lines. This is how they look". So I'm still in favor of removing the contour.

**Comment by anntzer** [comment]
removed the contour, then.

**Review by timhoffm — APPROVED** [review]
Anybody can merge after CI pass.

**Comment by jklymak** [comment]
The point of plotting the streamplot over the underlying stream function is that a) it is the same data as the other contour plots, and b) that the two ways of looking at the data are intimately related.   Of course the two aren't the same at finite resolution, but as dx/dy->0 they converge.

**Comment by anntzer** [comment]
I would support putting it back, but I don't feel overly strongly about it either.

**Comment by timhoffm** [comment]
> The point of plotting the streamplot over the underlying stream function is that a) it is the same data as the other contour plots, and b) that the two ways of looking at the data are intimately related. 

The primary goal is an example visual representation of the plot type.

a) The data is not particularly important. Data should primarily be chosen to give a good repesentation of the plot type. This may or may not be the same data as for other plots.
b) Relations between plot types is beyond the scope here. This is additional information better suited either in the docstring or a dedicated example. Anyway, IMHO this also needs textual description. Only plotting the two on top of each other without further comment does not get the message across.

**Comment by jklymak** [comment]
In general, when trying to teach something, the more you can reuse the same example in different ways, the better.  Of course you should not sacrifice clarity to do so, but when possible it really helps get concepts across for readers to not have to change contexts a lot.

**Pull request merged**
