### PR TITLE
Update banner logo on main website

### PR DESCRIPTION
**Pull request by mdboom**
This updates the banner logo on the `index.html` of the website to the new logo we've been making stickers of for about a year.

I know there are plans afoot to do more drastic things to the website, but this is an easy thing we can do now that looks a lot cleaner than what we currently have.

### CODE REVIEW

**Comment by tacaswell** [comment]
the gh preview of the svg is cropped, I hope that is just gh doing a bad job rendering?

**Comment by mdboom** [comment]
This is what the github preview looks like for me:

screen shot 2015-12-10 at 3 13 14 pm

**Comment by tacaswell** [comment]
backported to v1.5.0-doc as 325e47b

**Comment by WeatherGod** [comment]
Viewing the devdocs using Firefox 43 on Ubuntu, the banner looks cropped and the radar chart logo is misplaced.

**Comment by jenshnielsen** [comment]
Confirming. It looks good in Firefox on OSX but broken in firefox on Ubuntu 15.10 (virtual machine)

**Comment by jenshnielsen** [comment]
screenshot from 2015-12-29 15-58-14

This is rendering only the svg image

**Comment by WeatherGod** [comment]
yup, that is what it looks like to me.

**Comment by mdboom** [comment]
Sorry, guys.  Amateur mistake.  We should convert the text to paths, since we don't ship that font.  (It looks fine for me, because I have the font installed).  I'll have a PR shortly.

**Comment by cgohlke** [comment]
BTW, the SVG file breaks the Microsoft Compiled HTML Help (CHM) file. HTML Help control and SumatraPDF display a white placeholder of 540x617 px instead of the logo. xCHM does not render SVG either.

**Comment by mdboom** [comment]
> BTW, the SVG file breaks the Microsoft Compiled HTML Help (CHM) file. HTML Help control and SumatraPDF display a white placeholder of 540x617 px instead of the logo. xCHM does not render SVG either.

We'll probably need to add a PNG fallback for that case.  Since I don't have the tooling to validate a CHM, is this something you could do?

**Pull request merged**
