### PR TITLE
TST: fix tiny test differences

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by QuLogic** [comment]
I didn't check all, but it looks like the blue value is one less on the second red in the colourmap. It's not a big deal so :+1: if CI is fine.

**Comment by QuLogic** [comment]
Looks like you missed one though: matplotlib.tests.test_colorbar.test_colorbar_closed_patch.test

**Comment by tacaswell** [comment]
Sorry about that.  I did this on my laptop which might not have inkscape installed.  It is indeed a 1 bit color flip 

```diff

 L 158.4 32.4 
 L 158.4 43.2 
-" style="fill:#6bacd1;"/>
-    <path clip-path="url(#p2f8cb6be76)" d="M 288 43.2 
+" style="fill:#6bacd0;"/>
+    <path clip-path="url(#p3d4ec13d54)" d="M 288 43.2 
 L 417.6 43.2 
 L 417.6 32.4 
 L 288 32.4 
 L 288 43.2 
-" style="fill:#6bacd1;"/>
-    <path clip-path="url(#p2f8cb6be76)" d="M 417.6 43.2 
+" style="fill:#6bacd0;"/>
+    <path clip-path="url(#p3d4ec13d54)" d="M 417.6 43.2 
 L 547.2 43.2 
 L 547.2 32.4 
 L 417.6 32.4 
 L 417.6 43.2 
-" style="fill:#6bacd1;"/>
-    <path clip-path="url(#p2f8cb6be76)" d="M 28.8 32.4 
+" style="fill:#6bacd0;"/>
+    <path clip-path="url(#p3d4ec13d54)" d="M 28.8 32.4 
```

**Comment by tacaswell** [comment]
Merged v2.x up to master so all of the tests should be un-broken now.

**Pull request merged**
