### PR TITLE
Fix gaps in streamplot's by changing capstyle

### LINKED ISSUE #24946: [Bug]: Streamplot produces unconnected lines, gaps
### Bug summary

When a stream plot is drawn, curvature to the lines given by using smaller lines. However, these lines are never connected to each other. When the curvature is high the non-connection becomes visible if user saves the figure for later usage.

The visibility problem does not seem to be existent using show function. I have tested the pdf, svg, eps, png file types and all have the same issue.

Earlier commit, https://github.com/matplotlib/matplotlib/pull/25112, fixed the problem when the lines have same color and linewidth. However, when colors or linewidth vary, lines appear disconnected. 

### Code for reproduction

Example with color and linewidth:
```python
#!/usr/bin/py

import numpy as np
import matplotlib.pyplot as plt

w = 3
Y, X = np.mgrid[-w:w:100j, -w:w:100j]
U = -1 - X**2 + Y
V = 1 + X - Y**2

speed = np.sqrt(U**2 + V**2)
linewidth = 1 + 5*(speed-speed.min())/np.ptp(speed)

fig = plt.figure(1)
plt.streamplot(X, Y, U, V, color=speed, linewidth=linewidth)
plt.show()
fig.savefig("streamline.pdf")
```

### Actual outcome

Below is a screenshot of the problem. The line segments appear disconnected from each other when investigated with vector image editor such as Inkscape.

image

### Expected outcome

A random plot produced with matplotlib. In this picture, Inkscape shows the line is connected through its nodes.

image

### Operating system

Artix

### Matplotlib Version

3.11.1

### Matplotlib Backend

QtAgg

### Python version

3.14.7

### PR DESCRIPTION
**Pull request by gokberkgunes**
Lengthen the streamplot's tiny segments by changing their default cap style to rounded. This way, they appear connected to each other.

This commit fixes #24946.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by QuLogic** [comment]
Ideally, we'd figure out how to join all the segments; I don't know if that's possible with the multiple options-per-segment I mentioned in the issue, though.

This change is causing all streamplot tests to fail because they were generated with the previous broken-per-segment setup. Those would need to be updated if this is the way to go.

I think for uniform line width/colour, we do want to go with my suggestion at https://github.com/matplotlib/matplotlib/issues/24946#issuecomment-1402913872; I'm not sure yet whether this capstyle change is what we want to do for the other cases; I think we'd need to look into the effect on the variable width/colour closely first.

**Comment by gokberkgunes** [comment]
Thank you for the feedback. I will try to implement a non-hacky way to fix this.

**Comment by tacaswell** [comment]
I think that for uniform color, uniform width lines, switching to drawing continious lines in the correct solution.

For variably width / variable color I suspect the best "quick" fix is to make the stepsize smaller and the "right" fix is to upgrade the "lines" to effectively use pcolormesh as what we need is not rectangles, but quadrilaterals....

**Comment by gokberkgunes** [comment]
Altering the step sizes makes the produced images enormously large and generation of the plot considerably slow. That's why I thought it is out of the window. Though smaller step size could be a solution for smoother color gradients.

@tacaswell, by using pcolormesh are you thinking of creating every small segment as a quadrilateral? Then, should the start and end points are separated by starting and ending line widths?

Just to show the quick-fix with overlapping streamlines, below is how it ended up looking. It fixes the gaps appearing between the lines though the connection is still jumps between the two line widths.
image

**Comment by ksunden** [comment]
I'm going to close this as it is clear that the consensus is that a different solution is likely to win out.

@gokberkgunes thank you for your interest in fixing this, feel free to open an alternate PR with at least the proposed solution for the homogeneous width/color case. Note that that will still have test failures at the outset because the generated images are different (though better).

The idea of using a QuadMesh to draw the segments is interesting, and may work, but has some particularly challenging considerations (in particular that linewidth is specified in screen coordinates (i.e. points) but the position is specified in data coordinates).

**Comment by tacaswell** [comment]
> Then, should the start and end points are separated by starting and ending line widths?

Yes,  which ends up being a fair bit of computational geometry (you need the slope of the segment on either side, average them, then get the normal) and to compute the line width (which is set in screen space).  I suspect that the chain in the `draw` method should be lines in data space -> lines in screen space -> expand to quads in screen space -> draw mesh.

It does not seem impossible, just a fair bit of detailed work (and a new `Artist` class).  On the bright side, 100% of this can be prototyped outside of core!

**Pull request closed without merging**
