### PR TITLE
FIX: suppress offset text in ConciseDateFormatter when largest scale is in years

### LINKED ISSUE #19118: ConciseDateFormatter should suppress offset text when largest scale is in years
### Bug report

**Bug summary**

When plotting years-scale data with ConciseDateFormatter, the offset text is redundant.

**Code for reproduction**

```python
import datetime; from pylab import *
plot([datetime.datetime.now(), datetime.datetime.now() + datetime.timedelta(days=365)], [0, 0])
```

**Actual outcome**

out

**Expected outcome**

The extra "2022" should go away.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 39
  * Jupyter version (if applicable):
  * Other libraries:

### PR DESCRIPTION
**Pull request by harrymknight**
## PR Summary

Currently ConciseDateFormatter includes redundant offset text when largest scale is in months or years. This PR suppresses this behaviour and closes #19118.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Yeah I'd add a unit test, but it could just check that the offset text is suppressed rather than being an image test.  Thanks!

**Review by jklymak — APPROVED** [review]
Looks good to me.  Thanks a lot.  

The only minor suggestion I would have is that you could do all the datetime stuff with datetime64, but that is really a matter of taste

**Review by QuLogic — APPROVED** [review]

**Comment by QuLogic** [comment]
Thanks @harrymknight! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.

**Comment by jklymak** [comment]
Yes, thanks @harrymknight !

**Pull request merged**
