### PR TITLE
Fix the minortick-fix

### PR DESCRIPTION
**Pull request by Tillsten**
Sorry I messed up it last time and used the wrong name for the symlog-locator.

### CODE REVIEW

**Comment by QuLogic** [comment]
The line is now too long for PEP8. Probably best to just wrap after the comma.

**Comment by WeatherGod** [comment]
Why didn't tests catch this? Seem like a test should have been added.

**Comment by mdboom** [comment]
We have a symlog test, but it doesn't turn on the minor ticks.  It would be great to add a test now, or modify the existing symlog test to turn on minor ticks.

Also, we seem to have a PEP8 violation now (line too long).

**Comment by jenshnielsen** [comment]
Should this be backported to 1.5.x?

**Comment by jenshnielsen** [comment]
Nevermind this was backported in #5333

**Pull request merged**
