### PR TITLE
Addresses #8177, Readme badges

### PR DESCRIPTION
**Pull request by epintozzi**
Added badges for: Travis, Appveyor, Codecov, pypi, gitter, and depsy

### CODE REVIEW

**Comment by anntzer** [comment]
I would suggest a plain text gitter link next to the mailing-list section.

**Comment by tacaswell** [comment]
Can we be vain and not include codecov? :smiling_imp: 

Agree on including text link to gitter with the mailing lists

the 'view' button in the review page will also show you the rendering.

**Comment by dstansby** [comment]
I'll consider that a positive review @tacaswell, and merge!

**Comment by dstansby** [comment]
This looks like your first contribution to Matplotlib @epintozzi, thanks a lot!

**Comment by dstansby** [comment]
Backported to `2.0.0-doc` via. https://github.com/matplotlib/matplotlib/commit/6e52c5127c7e7bcdd46f410aca7c0e9f294876f1

**Pull request merged**
