### PR TITLE
adding links to color examples and tutorials in the api page

### PR DESCRIPTION
**Pull request by choldgraf**
per @anntzer 's suggestion, this adds links on the colors API page to the gallery and tutorial section.

### CODE REVIEW

**Comment by choldgraf** [comment]
I'm +1 on colorblind-friendly cmap documentation, though wanna keep the scope of this PR relatively narrow since I don't have a ton of time to iterate on this :-)  if you give me text that is guaranteed to get approved quickly then I'll add it to this PR, else let's leave it for another PR...that work?

**Comment by choldgraf** [comment]
@anntzer thanks for the check...latest push uses `:ref:`. I wasn't sure if `:doc:` would work since I'm not linking to a specific example, but instead to a subsection of a page.

**Comment by anntzer** [comment]
Ah yes (but as a general rule & side note, there's a bunch of
```
:ref:`sphx_glr_tutorials_foo.py`
```
which could advantageously be replaced by :doc:`/tutorials/foo`.)

**Comment by choldgraf** [comment]
I definitely don't think to do that often enough - I agree that's a better way to do it

looks like the links work now:

https://2926-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/colors_api.html

**Comment by story645** [comment]
@anntzer 's wording is ""for an in-depth overview of colomaps, including discussion about colorblind-friendliness, see (tutorial)".

**Comment by choldgraf** [comment]
ah I see - I thought you meant to actually add in a discussion of colorblind friendliness in this page.

I'm happy to add this in, though TBH we have a pretty scarce treatment of color blindness in the tutorial. E.g. this is the only section I see:

http://matplotlib.org/tutorials/colors/colormaps.html#color-vision-deficiencies

I would be a big +1 on a doc addition that added a more complete treatment for (and list of) colorblind-friendly colormaps.

**Comment by story645** [comment]
@choldgraf totally agree with you that it should probably be a doc addition and would also be +1 for a more complete treatment and list of colorblind friendly maps and pallets (for line/scatter/etc type plots).

**Pull request merged**
