### PR TITLE
Mep12 on color by yvalue.py

### PR DESCRIPTION
**Pull request by domspad**
pylab to plt and np

### CODE REVIEW

**Comment by efiring** [comment]
pep 8 failure (missing blank line); otherwise, probably OK.

**Comment by jenshnielsen** [comment]
@domspad  

You can run pep8 locally before committing to save the trouble of the pep8 issues.

You should be able to do `pip install pep8` 

and then run

```
python tests.py --pep8
```
from the main matplotlib dir to check before committing to git

**Comment by jenshnielsen** [comment]
@domspad Do you have time to work on this or Is it ok for me to finish it. 
@ericmjl Can you skip the 5 examples in this PR so that we don't duplicate work?

**Comment by ericmjl** [comment]
No problem, I will skip them.

**Comment by ericmjl** [comment]
From what I remember, @domspad and I decided that he would work from the front, and I would work from the back. So I'm going from letter Z backwards in the examples set. Still a whiles away from C.

**Comment by jenshnielsen** [comment]
@ericmjl Sounds good

**Comment by domspad** [comment]
Hey @jenshnielsen sorry, been a bit swamped lately. Feel free to finish it. Otherwise I'll probably not get to it until next week.

**Comment by jenshnielsen** [comment]
@domspad No problem. Just want to make sure that your work isn't lost

**Comment by tacaswell** [comment]
This function might also be relevant https://github.com/Nikea/xray-vision/blob/master/xray_vision/mpl_plotting/misc.py#L49

**Comment by jenshnielsen** [comment]
replaced by #4934

**Pull request closed without merging**
