### PR TITLE
Warn if MPLBACKEND is invalid.

### PR DESCRIPTION
**Pull request by anntzer**
I could be convinced to make this an error actually.

### CODE REVIEW

**Comment by NelleV** [comment]
Hi Anthony,
Do you mind having the warning list the possible values? Something like:

`("%s is not a valid backend. Valid backends are %s." % (s, the list of backends)`

Else it looks good. I'd also be fine raising an error.

**Comment by anntzer** [comment]
Actually the error message already contains the list of valid backends (you can see it by calling explicitly `matplotlib.use("foo")`); I'm just turning it into a warning.
Let's have a straw poll as to whether this should be an error or a warning?

**Comment by NelleV** [comment]
I finally understand what is going on.

I think a warning is fine for now: that's the current behaviour when the matplotlibrc ba kend is set to an unknown backend so it is at least consistent with the behaviour when using matplotlibrc.

In general, I think it might be worth be more strict and throw errors when options are set to wrong values, but this behaviour needs to be consistent.

**Comment by tacaswell** [comment]
I lean toward error as well.

**Comment by dopplershift** [comment]
"In the face of ambiguity, resist the temptation to guess." I'd say the zen argues for an error here.

**Comment by tacaswell** [comment]
Consensus seems to be to raise if invalid.

**Comment by anntzer** [comment]
That makes the patch even more trivial.

**Comment by NelleV** [comment]
Do you mind changing l. 1455 and l. 1105 (that will require more work) as well to have the error raised consistently.

**Comment by anntzer** [comment]
Changing l.1455 is probably a no-go (because other applications may be using matplotlib and using `-dfoo` themselves -- that's the whole reason `-d$backend` is deprecated I think).

Changing l.1105 comes down to switching the default value of `fail_on_error` to True, right?

**Comment by tacaswell** [comment]
I agree on 1455 having to stay as it is for being able to pass things through.

I ma not sure about L1105, that makes all rcparsing raise.  That should probably get wider discussion.

**Pull request merged**
