### PR TITLE
Adding font Size as default parameter

### PR DESCRIPTION
**Pull request by saikarna913**
Adding the font size as default parameter

## PR summary

-This PR automatically adjusts the font size when creating the table, provided the fontsize argument is specified, without requiring an explicit call to the set_fontsize function.
-Automatically applying the font size ensures consistent styling during table creation, streamlining the process for users. It eliminates the need for additional method calls

## PR checklist

- [x] closes fontsize in tables not working #29202 
- [x]  added the type hint and ran the boilerplate
- [x] tested the code with a new test case added in test_table.py

### CODE REVIEW

**Comment by rcomer** [comment]
Thank you for your contribution @saikarna913.  Please look through the points in our [Summary for Authors](https://matplotlib.org/devdocs/devel/pr_guide.html#summary-for-pull-request-authors) and try to address any that seem relevant.  In particular you will need to add a test and a type hint.  After adding the type hint, you will need to run [boilerplate.py](https://github.com/matplotlib/matplotlib/blob/main/tools/boilerplate.py) so that `pyplot.table` is updated to match `Axes.table`.

**Comment by saikarna913** [comment]
@rcomer i want to test this code, but I am unable to install the matplotlib completely it is giving me the import error 
@Kaustbh, I’m facing issues installing Matplotlib in the development environment, both on my local desktop and in GitHub Codespaces. It’s throwing an import error, so I’m unable to test the code changes I’ve made.  

Here’s what I’ve done so far:  
1. Forked the Matplotlib repository.  
2. Created a new environment and installed dependencies using:  
   ```bash
   pip install -r requirements/dev/dev-requirements.txt
   ```  
3. also tried GitHub Codespaces by activating the environment with:  
   ```bash
   conda activate mpl-dev
   ```  
4. Installed Matplotlib in editable mode with:  
   ```bash
   python -m pip install --verbose --no-build-isolation --editable ".[dev]"
   ```  
5. Also tried:  
   ```bash
   python -m pip install --no-build-isolation --config-settings=editable-verbose=true --editable .
   ```  

Despite these steps, I’m still encountering the import error. Could you help me figure out why this might be happening?

**Comment by saikarna913** [comment]
@rcomer I have tested the code by using this test code
```
import matplotlib.pyplot as plt
import numpy as np

# Data for plotting
x = np.linspace(0, 10, 100)
y = x + 1
tableData = [['a', 1], ['b', 1]]

# Create the figure and axis objects
fig, ax = plt.subplots()

# Plot the data
ax.plot(x, y)

# Add a table
t = ax.table(
    cellText=tableData,  # Table content
    loc='top',  # Position of the table
    cellLoc='center',  # Center-align the text in cells
    fontsize=30  # Set the font size for the table
)

# Save the figure as an image
plt.savefig('output_plot_with_table_after.png')  # Save as PNG file

# Optionally, close the plot (no need to display it)
plt.close()

```
I got this output 
output_plot_with_table_after

As a beginner, I’m not fully sure about type hints. Could you guide me on where exactly to add them in my code? I also attempted to include the following test code:
```
import pytest
import matplotlib.pyplot as plt
import numpy as np

# Test function for fontsize in table
def test_table_fontsize():
    # Data for plotting
    tableData = [['a', 1], ['b', 1]]
    
    # Create the figure and axis objects
    fig, ax = plt.subplots()
    
    # Plot the data (although we are focusing on the table)
    ax.plot(np.linspace(0, 10, 100), np.linspace(0, 10, 100) + 1)
    
    # Add a table with fontsize=30
    t = ax.table(
        cellText=tableData, 
        loc='top', 
        cellLoc='center', 
        fontsize=30
    )
    
    # Retrieve the font size from a specific cell (e.g., cell (0, 0))
    cell_fontsize = t[(0, 0)].get_fontsize()
    
    # Assert that the fontsize is correctly set to 30
    assert cell_fontsize == 30, f"Expected fontsize 30, but got {cell_fontsize}"

    # Clean up by closing the plot (important for pytest to avoid hanging processes)
    plt.close()

```
This test code has been running for a long time. I don't know why.

**Comment by rcomer** [comment]
The type hint goes in `table.pyi`.  Hopefully when you compare what's already in there with `table.py` it should be fairly intuitive what needs adding.

**Comment by saikarna913** [comment]
@rcomer  , please review this PR and approve it 
- [x] added the type hint and ran the boilerplate
- [x] tested the code with a new test case added in test_table.py

**Comment by NGWi** [comment]
Thank you, @saikarna913. 
This may sound annoying, but can you correct the flake8 formatting issues? If you work in VS Code, there are extensions to highlight flake8 issues.

**Comment by saikarna913** [comment]
@NGWi removed the flake issues
can you approve this pr

**Comment by rcomer** [comment]
@saikarna913 it looks like you have run an auto-formatter such as `black`.  This makes the size of the change much larger than is necessary for the PR.  I’m sorry but you will need to revert those changes.  [Note that Matplotlib intentionally does not use black](https://matplotlib.org/devdocs/devel/coding_guide.html#pep8-as-enforced-by-flake8).

**Comment by saikarna913** [comment]
> @saikarna913 it looks like you have run an auto-formatter such as `black`. This makes the size of the change much larger than is necessary for the PR. I’m sorry but you will need to revert those changes. [Note that Matplotlib intentionally does not use black](https://matplotlib.org/devdocs/devel/coding_guide.html#pep8-as-enforced-by-flake8).

done

**Comment by rcomer** [comment]
@saikarna913 please take a look at the automated tests below.  Mypy has failed although it was passing before.  Mypy checks the type hints so something has gone wrong there.

**Comment by rcomer** [comment]
Actually the Mypy failure is something to do with pylab, which you have not changed.  So I don't actually know what is going on there :confused:

**Comment by rcomer** [comment]
@saikarna913 did you mean to close this?

**Comment by QuLogic** [comment]
I believe this has been replaced by #29258.

**Comment by saikarna913** [comment]
> I believe this has been replaced by #29258.

yes

**Pull request closed without merging**
