### PR TITLE
Fix invalid escape sequence in docstring.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

fixes https://github.com/matplotlib/matplotlib/pull/10834/files#r176927952
release critical as that'll be a syntax error in future pythons

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I don't get how it passed the tests.  I don't think I'm running python 3.7!

**Comment by anntzer** [comment]
https://github.com/matplotlib/matplotlib/blob/master/tests.py#L32 if you're using tests.py, otherwise dunno

**Comment by tacaswell** [comment]
Hey folks, this needs to be backported as this will become a failure to import error in the future.

@meeseeksdev backport to v2.2.x

**Comment by QuLogic** [comment]
There are a few more in https://github.com/matplotlib/matplotlib/pull/11477/commits that might be needed.

**Pull request merged**
