### PR TITLE
ci: Merge sdist and wheel building workflows

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This allows verifying that wheels can be installed after building, and that the sdist can be built into a wheel without a second workflow.
    
Also simplify some of the checking scripts.

## PR Checklist

**Documentation and Tests**
- [n/a] Has pytest style unit tests (and `pytest` passes)
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] New plotting related features are documented with examples.

**Release Notes**
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [n/a] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
So some annoyance here: we still build 32-bit wheels, but NumPy doesn't. When we build ourselves, we ask for `oldest-supported-numpy` and build a 32-bit wheel of it. But then for the test, our requirement is just `numpy>=MINIMUM`, so then we have to build NumPy _again_.

This will probably also affect some of the ARM builds? Which will really explode the runtime for this workflow. Maybe we'll have to get by without the test...

**Comment by greglucas** [comment]
I'm not following how an echo on the test command verifies that it didn't totally fail. Don't you need to `pip install wheelhouse/*.whl` to verify that it can be installed?

To avoid the long stacked wheel builds in a single job, I've switched over to dynamically generating the run matrix on other projects which has worked nicely: https://github.com/pypa/cibuildwheel/discussions/1261

Perhaps we should open a separate issue about the 32-bit wheels, but it seems like if Numpy has dropped direct wheel support, we could probably follow suit as well and not bother with the extra maintenance there.

**Comment by QuLogic** [comment]
cibuildwheel creates the test environment and installs the wheel when there's a test command. Setting the environment variable just triggers this behaviour; it doesn't matter that it doesn't do anything.

I opened #25475 for dropping 32-bit wheels.

We did discuss doing a bit more testing, but that can wait for after the above change.

**Comment by greglucas** [comment]
> cibuildwheel creates the test environment and installs the wheel when there's a test command. Setting the environment variable just triggers this behaviour; it doesn't matter that it doesn't do anything.

That wasn't obvious to me, thanks for clarifying! I did go in and look at the CI log to verify that does work 👍 . Perhaps add a comment above that to indicate as much?

**Comment by ksunden** [comment]
Looks like there was a temporary disruption in the qhull download

**Comment by QuLogic** [comment]
I've realized that the `cibuildsdist.whl` workflow does some roughly equivalent test already. But that is on wheels that we don't end up distributing. So instead of closing this, I'm going to repurpose it to merge those two workflows. But this will wait for after dropping 32-bit wheels.

**Comment by QuLogic** [comment]
Sorry, that took a few tries to get working across platforms.

Annnd now we know that PyPy wheels don't import on Windows. Can anyone try that out with the release wheels? Or the previous nightly wheels?

**Comment by QuLogic** [comment]
Well, it seems to have magically fixed itself in the meantime.

**Review by ksunden — APPROVED** [review]

**Pull request merged**
