### PR TITLE
Expire Artist.set() property reordering

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Expired deprecation.

### CODE REVIEW

**Comment by jklymak** [comment]
This makes sense to me - where was the deprecation though?

**Comment by timhoffm** [comment]
What do you mean "where"? In the removed code. :question:

**Comment by jklymak** [comment]
Yes, if it was deprecated, presumably there was a message somewhere?

**Comment by timhoffm** [comment]
Yes. lines 1170-1176?

**Review by jklymak — APPROVED** [review]
My apologies, reading too fast!

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
