### PR TITLE
MAINT removing examples/subplots_axes_and_figures/subplot.py

### PR DESCRIPTION
**Pull request by NelleV**
This example is a duplicate of subplot_demo.py, using the pyplot interface instead of the oriented object one

### CODE REVIEW

**Comment by anntzer** [comment]
There's also https://matplotlib.org/devdocs/gallery/pyplots/pyplot_two_subplots.html#sphx-glr-gallery-pyplots-pyplot-two-subplots-py also using pyplot.
I think it's actually worthwhile to keep one of the two pyplot-based examples (or convert it to individual calls to fig.add_subplot() if we really hate pyplot here).

**Comment by NelleV** [comment]
Are you asking for a change or just making a statement?

**Comment by anntzer** [comment]
I'm suggesting that removing this specific pyplot example may not be best.
Now that I look at it again, I think that if anything I'd rather remove subplot_demo, which is more redundant with subplotS_demo...

**Comment by timhoffm** [comment]
I've updated ``subplots_demo`` in #13243. With that ``subplot_demo``  is really obsolete. Not sure we still additionally need a dedicated pyplot only example as this ``subplot`` example.

**Comment by anntzer** [comment]
The point is not so much pyplot-vs-OO, but keeping an example that shows `fig.add_subplot(2, 1, 2)` / `plt.subplot(2, 1, 2)` (i.e. adding one subplot at a time).

**Comment by NelleV** [comment]
@anntzer I'm confident that this is showcased in at least one of our 500 examples. There's really no point of adding examples to the gallery that showcase features that are sufficiently close that there's absolutely no difference between the image generated. It's not how our users use our gallery: they  scroll until they find an example with an image that is closely related to what they want to do.

Anyhow, obviously, I disagree with you, as I took the time and effort to open this pull request.

**Comment by anntzer** [comment]
My strictly personal belief is that googling/ctrl-f'ing the gallery page is more common.

**Comment by dstansby** [comment]
I'm +/- 0 on this; I think at least the two examples should be merged (the one being deleted at hte moment and the one that's identical apart from using `plt.subplots`)

**Comment by dstansby** [comment]
I'm +/- 0 on this; I think at least the two examples should be merged (the one being deleted at hte moment and the one that's identical apart from using `plt.subplots`)

**Comment by NelleV** [comment]
I've closed this PR: if this is not a clear merge, I don't want to spend more time on this.

**Pull request closed without merging**
