### PR TITLE
Backport PR #15791 on branch v3.2.x (Cleanup backend_bases docstrings.)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #15791: Cleanup backend_bases docstrings.

### CODE REVIEW

**Comment by QuLogic** [comment]
>  added this to the [v3.2.1](/matplotlib/matplotlib/milestone/49) milestone [15 hours ago](#event-2844526060)

v3.2.0 is still not out yet.

**Comment by timhoffm** [comment]
Does that mean, we shouldn't tag for v.3.2.1? Or should we but not merge the backports until 3.2.0 is out?

**Comment by QuLogic** [comment]
If you merge now, it will be in v3.2.0, unless @ivanov wants to go through the trouble of cherry-picking things. So if you really want to target v3.2.1, then it'll have to wait.

**Comment by timhoffm** [comment]
Is is ok to bring documentation-only changes still into 3.2.0 or do we prefer to have it frozen except for dedicated bugfixes.

**Pull request merged**
