### PR TITLE
[Doc]: Document the position parameter in apply_aspect()

### PR DESCRIPTION
**Pull request by haziq-khurshid**
## PR Summary
This PR documents the position paramter in apply_aspect()
Issue: https://github.com/matplotlib/matplotlib/issues/23583

## PR Checklist

**Tests and Styling**
- [N/A ] Has pytest style unit tests (and `pytest` passes).
- [ N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by haziq-khurshid** [comment]
@tacaswell Kindly close the previous PR: https://github.com/matplotlib/matplotlib/pull/23617
I couldn't update it because I had deleted the branch used to make that PR.
Apologies for any inconvinience.

**Comment by tacaswell** [comment]
In the future when you open a PR please only open it once and then push changes to that branch.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Thank you for you work on this @haziq-khurshid and congratulations on your first merged Matplotlib PR 🎉 

Hopefully we will hear from you agian!

**Comment by haziq-khurshid** [comment]
Thank you @tacaswell for being helpful.
I'll definitely contribute more often in the future!

**Pull request merged**
