### PR TITLE
Update annotate_explain.py

### PR DESCRIPTION
**Pull request by ggold7046**
Add more explanatory comments to annotate_explain.py example for enhanced readability.

## PR Summary
This Pull Request improves the documentation of the annotate_explain.py example.
Adds enough information in the example file for the user to understand every step
## PR Checklist

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by timhoffm** [comment]
Thanks for you contribution! However, I don't think this is going the right direction. I know, our current description how examples should look like is insufficient. Please read https://github.com/matplotlib/matplotlib/issues/11654#issuecomment-405567840 to get a general idea.

**Comment by ggold7046** [comment]
Hi @timhoffm , thank you for the reply. I looked at the link you provided. Could you please add some suggestion in this PR to improve. That will be much more easier for me to understand what else is needed.

**Comment by jklymak** [comment]
> * You may use some short explanatory comments within the code (a good example is the aspect comment in the pie chart example above). But do not clutter the code with too many comments.

This PR definitely clutters the code.  

The original issue refers to the fact that many of the examples were _just_ an example, with no preamble explaining the goal of the example, or what feature it is being demonstrated.   Most of these have been fixed, but if you look through the examples there are still a few that haven't been updated eg https://matplotlib.org/stable/gallery/subplots_axes_and_figures/axes_zoom_effect.html

**Comment by melissawm** [comment]
Hi @ggold7046 👋🏻 Let me know if you'd like to connect some time! Maybe we can chat either on [gitter](https://gitter.im/matplotlib/matplotlib) (where you can also join our #incubator channel) or through a zoom call and discuss possible ways to contribute. I'd be happy to know more about your goals and how we can best support you. Cheers!

**Comment by jklymak** [comment]
Converting to draft pending revision

**Pull request closed without merging**
