### PR TITLE
FIX: force blended transforms with data to be in data space

### LINKED ISSUE #17016: Issues with autoscaling and transforms with 3.2+
### Bug report

**Bug summary**

I am encountering a few seemingly related issues but can't exactly define what's happening. They broadly relate to unexpected changes in how plots are scaled and appear in the context of using the transform objects attached to the Axes. I assume they are caused by changes in autoscaling in 3.2, but don't know whether they are a bug or if previous code was relying on undefined behavior (the release notes are a little vague about what actually changed).

**Code for reproduction**

Here is a simple example derived from an issue in seaborn rugplot (https://github.com/mwaskom/seaborn/issues/2015)

```python
import numpy as np
import matplotlib as mpl
import matplotlib.transforms as tx
from matplotlib.collections import LineCollection
import matplotlib.pyplot as plt

a = [1, 2, 4]
height = .2

xy_pairs = np.column_stack([np.repeat(a, 2), np.tile([0, height], len(a))])
line_segs = xy_pairs.reshape([len(a), 2, 2])

f, ax = plt.subplots()
trans = tx.blended_transform_factory(ax.transData, ax.transAxes)
ax.add_collection(LineCollection(line_segs, transform=trans))
ax.autoscale_view(scalex=True, scaley=False)
```

**Actual outcome**

With matplotlib 3.2.1:

image

**Expected outcome**

With matplotlib 3.1.2:

image

**Matplotlib version**

  * Operating system: macos
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): ipython inline

**Other information**

Linking another seaborn issue (https://github.com/mwaskom/seaborn/issues/2013) where there has been a similar change in behavior with matplotlib 3.2 but where it's harder to extract a standalone issue.

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #17016
 (Maybe?)

This is a very naive approach.  Needs tests so we don't break it again.  Not sure what the *correct* thing to do for blended transforms is
```
import numpy as np
import matplotlib as mpl
import matplotlib.transforms as tx
from matplotlib.collections import LineCollection
import matplotlib.pyplot as plt

a = [1, 2, 4]
height = .2

xy_pairs = np.column_stack([np.repeat(a, 2), np.tile([0, height], len(a))])
line_segs = xy_pairs.reshape([len(a), 2, 2])

f, ax = plt.subplots()
trans = tx.blended_transform_factory(ax.transData, ax.transAxes)
ax.add_collection(LineCollection(line_segs, transform=trans))
ax.autoscale_view(scalex=True, scaley=False)
```

Now returns

fix

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I think the correct thing is "just" to autoscale only along dimensions that contains_branch_separately(transData), but not others?  Not saying it's so easy :/

**Comment by jklymak** [comment]
Fixed typos in commit messages, otherwise same PR as approved

**Comment by jklymak** [comment]
I'll self merge to hopefully make it easier for @moorepants to check if it also fixes #17004

**Comment by ImportanceOfBeingErnest** [comment]
No, I think https://github.com/matplotlib/matplotlib/issues/17004 is caused by https://github.com/matplotlib/matplotlib/pull/13593, which apparently was a deliberate change.

**Pull request merged**
