### PR TITLE
Make tutorial code reproducible

### PR DESCRIPTION
**Pull request by redi35**
Instead of using `print(img)`, directly call the object (i.e. just `img`), which results in a reproducible line of code, as opposed to hard-coding the result into the tutorial text which isn't reproducible. In other words, in IPython this correction results to an output `Out[5]:` which actually corresponds to the input `In[5]: img`. In its current state, an output `Out[5]` is generated by the `print()`-command which isn't visible in the tutorial; only the assignment `In[5]: img = mpimg.imread('../../doc/_static/stinkbug.png')` is. Hence the relation in the tutorial between `In[5]:` and `Out[5]` is simply incorrect and not reproducible.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
power-cycled to restart the CI, but it might not work with circle...

**Comment by WeatherGod** [comment]
Thinking out loud... this isn't a .ipynb file, but a .py file. So, for those running this in a regular REPL or as a script, what should they see?

**Comment by redi35** [comment]
This is isn't a .pynb file, indeed. The `In [5]:`, `Out [5]:`-syntax used in the tutorial suggests that they hold a relation to eachother; where in reality the `Out [5]:` is preformatted from the .py source file via a non-visible `print (img)` line in the .py source file.

**Comment by redi35** [comment]
@WeatherGod This is isn't a .pynb file, indeed. The `In [5]:`, `Out [5]:`-syntax used in the tutorial suggests that they hold a relation to eachother; where in reality the `Out [5]:` is preformatted from the .py source file via a non-visible `print (img)` line in the .py source file.

**Comment by anntzer** [comment]
I don't actually understand the point of this PR.  The tutorial as presented at http://matplotlib.org/devdocs/tutorials/introductory/images.html#sphx-glr-tutorials-introductory-images-py seems perfectly reasonable to me?

**Comment by jklymak** [comment]
Yeah, its fine, except for the preamble.  And the fact it uses `pyplot`, but at least its explicit about it

**Comment by tacaswell** [comment]
We (via sphinx gallery) generate ipython notebooks.  This looks like https://nbviewer.jupyter.org/urls/matplotlib.org/devdocs/_downloads/images.ipynb  however, this seems to have the worse problem that if you download it you don't get the image file!

**Comment by jklymak** [comment]
I'm closing this, because I don't think the existing tutorial has a problem.  Feel free to re-open if anyone disagrees.

**Pull request closed without merging**
