### PR TITLE
Fixes incorrect error bar colors when NaN values are present

### PR DESCRIPTION
**Pull request by kasanitej**
## PR Summary
incorrect error bar colors when NaN values are present
https://github.com/matplotlib/matplotlib/issues/13799
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Please give your PRs descriptive titles; what does this change do?

**Comment by kasanitej** [comment]
Hi,

This PR pertains to issue reported in #13799.

My change will look into the corresponding index of the color of X & Y where there are np.nan, and remove them.

Regards,
Bhanu.

**Comment by anntzer** [comment]
I think(??) the correct fix is to keep the invalid values in everywhere but not plot them, similarly to https://github.com/matplotlib/matplotlib/pull/12422.

**Comment by kasanitej** [comment]
yeah.. that's sound better than removing them.

**Comment by NelleV** [comment]
I would also raise a warning.

**Comment by jklymak** [comment]
Superseded by #16724

**Pull request closed without merging**
