### PR TITLE
Update index.rst - add Windrose as third party tool

### PR DESCRIPTION
**Pull request by scls19fr**
Fix https://github.com/scls19fr/windrose/issues/33

### CODE REVIEW

**Comment by pelson** [comment]
Cool package. Thanks for suggesting it on the matplotlib website. :+1:

**Comment by scls19fr** [comment]
That was @tacaswell suggestion in https://github.com/scls19fr/windrose/issues/33

**Comment by WeatherGod** [comment]
Failures are unrelated. Merging.

**Comment by scls19fr** [comment]
Thanks

**Pull request merged**
