### PR TITLE
Add computer modern font family

### PR DESCRIPTION
**Pull request by srvanrell**
Add Computer Modern family into rcsetup.py (requested in #5860):
- Computer Modern Roman
- Computer Modern Sans Serif
- Computer Modern Typewriter

### CODE REVIEW

**Comment by QuLogic** [comment]
It seems like no-one got around to reviewing this. I don't think there's anything controversial though as it's basically exactly what was stated in #5860.

Since the second commit is so trivial though, can you squash the two together?

Ping @zblz anyway, just in case.

**Comment by srvanrell** [comment]
Do you mean if I can squash those commits?  I don't know a clean way to do
it without rewriting the history

**Comment by QuLogic** [comment]
Yes, just run a rebase on them.

**Comment by srvanrell** [comment]
OK, I'll do it as soon as I get in front of my PC

**Comment by srvanrell** [comment]
Done

**Comment by QuLogic** [comment]
OK @zblz @mdboom ?

**Comment by tacaswell** [comment]
backported to v2.x as 9f9e8a3

**Pull request merged**
