### PR TITLE
Fix travis OSX build

### LINKED ISSUE #12578: macOS builds are broken
The [most recent CRON build](https://travis-ci.org/matplotlib/matplotlib/jobs/444165618) from 11 hours ago has started failing on macOS. Can someone on macOS investigate this?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/opt/gcc/lib/gcc/8/libquadmath.0.dylib
```
I'm not sure if maybe https://github.com/Homebrew/homebrew-core/pull/33207 is related.

### PR DESCRIPTION
**Pull request by dstansby**
The homebrew numpy seems to be broken, so this just uninstalls it which then lets pip install its own version later in the build. fixes #12578

### CODE REVIEW

**Comment by dstansby** [comment]
This now fixes #12578

**Comment by tacaswell** [comment]
Bailing on brew numpy seems a bit drastic.  I assume they will fix this eventually....?

**Comment by jklymak** [comment]
What’s the reason we use brew numpy instead of pip?  

I think there are reasons to use other builds but I would guess most Mac users use conda.

**Comment by tacaswell** [comment]
There is something to be said for staying inside of the ecosystem we are using and to avoid hitting pypi.  I am pretty confident that this installation issue is going to be transient.

**Comment by tacaswell** [comment]
But this makes the board green, so going to merge it :)

**Comment by dopplershift** [comment]
For Python packages I consider PyPI/conda to be the ecosystem we’re working in, NOT homebrew. Do we rely on Ubuntu Numpy packages on Linux?

**Pull request merged**
