### PR TITLE
Log about font manager generation beforehand.

### PR DESCRIPTION
**Pull request by pope1ni**
## PR Summary

Changes an info level log message to debug. This reduces noise on the root logger, e.g.
```
2020-01-30 13:45:33,150 INFO matplotlib.font_manager generated new fontManager
2020-01-30 13:45:33,150 INFO matplotlib.font_manager generated new fontManager
```
It's not very descriptive or helpful in general.

## PR Checklist

- [ ] ~~Has Pytest style unit tests~~
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] ~~New features are documented, with examples if plot related~~
- [ ] ~~Documentation is sphinx and numpydoc compliant~~
- [ ] ~~Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)~~
- [ ] ~~Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way~~

### CODE REVIEW

**Comment by jklymak** [comment]
This should rarely ever happen, though, hence it was pushed up to info I think.  Its also slow and users wanted to know why matplotlib was locking up.  However, I agree the message could be clearer?

**Comment by anntzer** [comment]
(I don't really care about the log level, but yes, this should only happen once...)

**Comment by pope1ni** [comment]
> This should rarely ever happen, though, hence it was pushed up to info I think. Its also slow and users wanted to know why matplotlib was locking up. However, I agree the message could be clearer?

Is it that slow? I hadn't really noticed. Is the speed dependent on how many fronts you have installed?

I suggested this change because it didn't seem all that useful to know in general. If users really needed to work out what was going on they could enable debug level logging.

Also this message occurs after the slow bit based on how it is phrased? Surely beforehand saying "Generating new font manager, this may take some time..." would make more sense?

> (I don't really care about the log level, but yes, this should only happen once...)

Sorry, it should be only once - I think that I added a separate handler for matplotlib to only log at info level due to the excess noise at debug level and forgot to stop propagation.

**Comment by jklymak** [comment]
By only "once" we mean it should only happen once *ever*, unless you clear your font cache.

**Comment by pope1ni** [comment]
Ah, yes. So I see it a lot because I have multiple docker containers spawned in parallel and the cache is lost when containers are shut down, so it is _always_ rather than _once_. I guess that it should be possible to change the cache path to put it on a volume and share/reuse it?

That is also probably why it doesn't take (too) much time because there are limited fonts installed within the container.

**Comment by jklymak** [comment]
Can you just make `.matplotlibrc` part of your container?

**Comment by tacaswell** [comment]
It does depend on the number of fonts you have installed (at one point we were looking at the full OSX system font directory and people were reporting ~minutes of run time).

The `MPLCONFIGDIR` env (https://matplotlib.org/faq/environment_variables_faq.html?highlight=mplconfigdir#envvar-MPLCONFIGDIR) controls where the font cache goes.

I suggest importing matplotlib as part of building the docker container (`python -c "import matplotlib"` should be enough).  It will make the docker container marginally bigger, but make your start up marginally faster.

**Comment by pope1ni** [comment]
Ok. So I see this really amounts to a configuration issue for me to address, although it wasn't obvious. I'll look into your suggestions, @tacaswell - Thanks.

I've tweaked this patch to restore the info level logging, but moved the message ahead of the generation - after all, it makes sense to tell the user that something is about to happen that takes ~minutes, rather than saying "oh, by the way that big pause was because..."

**Comment by timhoffm** [comment]
Thanks!

**Pull request merged**
