### PR TITLE
TST: test_legend/test_hatching without image comparison

### PR DESCRIPTION
**Pull request by pharshalp**
## PR Summary
alternative to #16363 (attempting to address the third bullet from #15054)
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This image seems complex enough that keeping the image is worth it?  How well is hatching tested otherwise elsewhere?  Is there an example that does this?

**Comment by pharshalp** [comment]
Will search to see if there is another test for hatching. I went ahead with
replacing the image comparison because this is listed under test_legend
(implying that the point of the test is to see if the ax.legend picks up
the hatching patches correctly).

**Comment by jklymak** [comment]
Sure, but lots of our tests test a few things at once.  This is a particularly rich test, so not convinced we should scrap it.

**Comment by pharshalp** [comment]
Listing image comparison tests that I found (that deal with hatching)...
`test_patches.py` --> `test_multi_color_hatch()`
multi_color_hatch

`test_backend_pdf.py`


hatching_legend-1


`test_artist.py` ---> test_hatching()
hatching

(test_clip_path_clipping)
clip_path_clipping

**Comment by jklymak** [comment]
I guess I'm -0.5 on removing this test.  But if other folks think its superfluous I'm not going to object too strongly.

**Comment by jklymak** [comment]
@pharslap I'm going to close this for now, but if you can get someone other than @anntzer who thinks its worthwhile dropping this image, please feel free to re-open.  Again, I think its useful having *some* images....

**Pull request closed without merging**
