### PR TITLE
Fix checking of 'labels' argument to Sankey.add.

### PR DESCRIPTION
**Pull request by anntzer**
Test by manually running the sankey examples.

Closes https://github.com/matplotlib/matplotlib/pull/11974#issuecomment-455493614.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
https://matplotlib.org/devdocs/gallery/specialty_plots/sankey_basics.html#sphx-glr-gallery-specialty-plots-sankey-basics-py and https://matplotlib.org/devdocs/gallery/specialty_plots/sankey_basics.html#sphx-glr-gallery-specialty-plots-sankey-basics-py are currently completely misrendered; this PR fixes that.
As I already explained elsewhere, the sankey module is nearly entirely untested, and while it would be nice to improve the situation, that's not the point of this PR.

**Comment by dstansby** [comment]
The test suite can't tell if the docs are being rendered correctly; correct me if I'm wrong, but adding a test that exercises the `ValueError` here doesn't seem like a huge job to me, and improving the test coverage bit by bit is a good thing.

**Comment by anntzer** [comment]
But the ValueError is not actually the relevant point; what matters is the fact that if `labels` is a list of n strings, then the previous version of the code would create a list containing n copies of `labels` (`[labels] * n`), whereas the current version doesn't.
IOW, testing for the ValueError doesn't actually check the problem.

An image test would be better, but *if* I was to add one I'd rather design a proper test that actually ensures as close to 100% coverage as possible on a single image test (which I don't have right now), rather than repeatedly trying to cover incrementally more parts of the module.

**Comment by dstansby** [comment]
Fair enough re. an image test. Would it be possible to create a diagram, then extract the resulting labels to check they're correct? Happy to look into this myself if you don't have time to add a test, but I think one should be added if possible.

**Comment by anntzer** [comment]
Actually you can probably do this by saving to *svg* (with rcParams["svg.fonttype"] = "none" to avoid converting glyphs to paths) (or pdf) and then looking for the substring in the result :p

**Comment by dstansby** [comment]
I've added a two line test that fails before this fix... I think the general argument of "it's not tested so there's no point adding tests" is a bit silly, and when we fix something as a rule there should always be a test added to make sure it doesn't break in the future.

**Comment by anntzer** [comment]
Thanks!

**Pull request merged**
