### PR TITLE
Add gadfly plot theme

### PR DESCRIPTION
**Pull request by JonnyCBB**
## PR Summary
Adds the Gadfly plot theme that I [wrote a blog post](https://towardsdatascience.com/a-new-plot-theme-for-matplotlib-gadfly-2cffc745ff84) about a couple of years ago

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes). N/A
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check). N/A
- [ ] New features are documented, with examples if plot related. N/A
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build] (https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error). N/A
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`). N/A
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there). N/A

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks a lot for the PR!

We are suggesting that new styles be contributed to https://github.com/petermckeeverPerform/themepy  If a theme ends up very popular there, we will definitely entertain including in the core library.

**Comment by JonnyCBB** [comment]
That's cool. I'll do that then and close this PR 👍

**Comment by JonnyCBB** [comment]
I think it would be useful to update the [contributing docs](https://matplotlib.org/devel/contributing.html?highlight=contributing) to let other contributors that are adding themes know to go to [themepy](https://github.com/petermckeeverPerform/themepy) first

**Comment by timhoffm** [comment]
Thanks for the suggestion. I'm a bit torn on adding themes to the contributing docs. While happening from time to time, people wanting to add themes is not super-common. The extra info would make the already long contributing docs even more confusing/intimidating. I'm also not sure that people wanting to contribute themes would actually find that info in there.

For now, I'd leave it out and redirect contributors on a case-by-case basis.

**Pull request closed without merging**
