### PR TITLE
Backport PR #16112 on branch v2.2.x (CI: Fail when failed to install dependencies)

### PR DESCRIPTION
**Pull request by Kojoley**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
I gave up and removed the OSX build and nightly, but added py38 on linux.

**Comment by Kojoley** [comment]
I think the OSX problem is in `osx_image: xcode7.3` (removing was not backported here)

**Comment by tacaswell** [comment]
Tried putting the osx build back and removing the offending line.

@Kojoley I don't want to force-push to your branch without your consent, but one of us should squash this history down to a handful of commits

**Comment by Kojoley** [comment]
> I don't want to force-push to your branch without your consent

I have no problems with this.

> one of us should squash this history down to a handful of commits

Squash and merge button on GitHub is not enough?

**Comment by tacaswell** [comment]
Fair enough, squashed and merged.

**Pull request merged**
