### PR TITLE
Fix for #4071

### PR DESCRIPTION
**Pull request by mlovci**
`Axes.bxp` skips plotting boxplots when there is missing data.

### CODE REVIEW

**Comment by WeatherGod** [comment]
Just a thought... what should be returned? What do we do for other kinds of plots where some aspect of the input data is empty? If someone puts in a length 3 array, isn't it reasonable to expect something length-3 back?

**Comment by tacaswell** [comment]
It would probably be better to make sure that the stats dict always comes back with the correct entries, just filled with `np.nan`

**Comment by phobson** [comment]
I think the way to handle this should originate in the `boxplot_stats` function in cbook.py. I took a stab it here: https://github.com/phobson/matplotlib/commit/2157679fd343ec17fc8ee1ddb451fe10b641aa60

**Comment by phobson** [comment]
@tacaswell I like that approach too. Currently no-data entries are returning `None`. Not sure which is better, but I think your approach will lead to a much smaller diff. so +1 on that.

**Comment by mlovci** [comment]
Yes @WeatherGod, probably right that this is a bad solution because it doesn't return lists of the right size. Closing this PR

**Pull request closed without merging**
