### PR TITLE
DOC:Add link to style examples in matplotlib.style documentation

### PR DESCRIPTION
**Pull request by sameshl**
## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by sameshl** [comment]
@dstansby Let me know if any changes are required.
PS: I didn't see any commits or PRs regarding https://github.com/matplotlib/matplotlib/issues/14362 for some time, so I figured I could fix it.

**Comment by jklymak** [comment]
@sameshi, can you rebase so that CI will run?  Sorry for the invconvenenience!  Otherwise this looks good.

**Comment by sameshl** [comment]
@jklymak I messed up the commit history of my this PR, so made a new PR. :sweat_smile:

**Comment by jklymak** [comment]
So this can be closed?

**Comment by timhoffm** [comment]
Replaced by #14790.

@sameshi In general, there is no need to abandon a PR because of a messed up commit. You can clean up your commits (in the simplest case with a `git commit --amend`) and force-push. If anything else fails, you can delete your local branch, recreate it with the same name, do the changes and then force-push.

**Comment by sameshl** [comment]
@timhoffm Thank you for the info!  Will keep in mind for future contributions:smiley:

**Pull request closed without merging**
