### PR TITLE
added function linanimate.

### PR DESCRIPTION
**Pull request by Liupold**
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks for the PR.  However it is a _very_ light wrapper; do users really have trouble with the slightly more flexible existing API to justify adding this?

**Comment by Liupold** [comment]
Honestly I know, but i think `duration` and `fps` added a useful abstraction, specially if fps and time needed  to  be changed. And also can be helpful where time precision is needed. I am aware of the fact that this does not add any functionality to the existing code.  I hope this will be useful specially for beginners. Let me know what do you think.

**Comment by Liupold** [comment]
I Now  think rather than adding a new function which does almost nothing it would be simpler to have a function which generate a `iterable` which can be passed to the Parameters `frames`, like:
`ani = FuncAnimation(fig, func, frames=linframes(lf, uf, fps, duration), ...)`
I think this will be much better at it doesn't change the api. And can be implemented as a separate package.

 Closing This PR now.

**Comment by tacaswell** [comment]
Thanks for working on this  @Liupold , even though we did not take it!

If you do end up creating a new package, please add it to the third-party page (https://github.com/matplotlib/mpl-third-party)

**Pull request closed without merging**
