### PR TITLE
Add PEP 519 support

### LINKED ISSUE #5968: Accepting pathlib.Path as path inputs?
pandas recently made the great effort to accept pathlib.Paths as inputs where traditionally strings would have to be provided for any path related requirements. Could this be done also for matplotlib?

### PR DESCRIPTION
**Pull request by aragilar**
Closes #5968. This should allow pathlib.Path or other PEP 519 objects to be used with matplotlib.

### CODE REVIEW

**Comment by Kojoley** [comment]
Please do not do `raise KnownFailureTest` without `knownfailureif` decorator as it breaks `pytest` compatibility.

**Comment by tacaswell** [comment]
I am not sure we want to put this on the 2.x branch, it should probably be targeted at master.

**Comment by aragilar** [comment]
@tacaswell do you want me to close this and rebase against master? Or should I just rebase this against the latest 2.x to avoid conflicts?

**Comment by tacaswell** [comment]
Please rebase and re open against master

**Comment by aragilar** [comment]
Replaced by #6788.

**Pull request closed without merging**
