### PR TITLE
New event examples showing z-value at cursor position.

### PR DESCRIPTION
**Pull request by ianthomas23**
New examples using `motion_notify_event` to show the z-value at the mouse cursor position.  Two examples, one of quadrilateral grids using `contourf` and the other of triangle grids using `tricontourf`.

The intention is to demonstrate how to solve problems like issue #14804 without adding such functionality for all contour/tricontour/pcolor like functions, which will detrimentally affect performance for many users.

### CODE REVIEW

**Review by timhoffm — COMMENTED** [review]
I'd probably expect outputting the range that's associated with the respective color.

Using `interp2d` generates continuously varying values, whereas contour draws a discrete set of ranges. The continuous interpolation invents z-values, that are not part of the plot (agreed that contouring also invents information from the discrete grid points, but having the same value information as is encoded in the plot colors seems desirable.

If returning ranges is not easily possible, you should at least add a note mentioning the difference.

**Comment by ianthomas23** [comment]
Displaying the contour plot is independent of the z-interpolation.  Really it is just a convenience to show the user something related to the z-field to guide their mouse movements.  It could just as easily be a pcolor plot for example.

Writing an example that shows how to iterate through the polygons returned from a contourf/tricontourf call is a really bad idea, as discussed in the related issue. It will be fine for some simple polygons but will scale badly and will end up with "performance is really bad" complaints.  I don't even want to start to guide users down that route.

I will add some extra words to clarify the relationship (or lack of) between the interpolation and contour plot.

**Comment by ianthomas23** [comment]
I've added some more text to explain that the interpolation is separate from the contour plots.

**Comment by jklymak** [comment]
This looks good, thought I haven't tried it yet.  However, I think we could just combine the two examples?  Our example gallery is a little out of control, and the difference between tricontour and contour is just in the underlying data structure, not the idea.  

Please ping for a re-review.  Someone on the issue was complaining that this hadn't been merged, and I think it just fell off the review queue.  Thanks!

**Comment by ianthomas23** [comment]
@jklymak If we reduce this to one example that will mean dropping the tricontour version as fewer users are interested in tri grids.  I'd rather keep both.

The contour version uses scipy's `interp2d` which is suboptimal, as pointed out by @timhoffm, in that it incorrectly interpolates values outside of the grid and also in any masked regions.  The tricontour version uses our `LinearTriInterpolator` which builds upon our `TrapezoidMapTriFinder` and works perfectly in that it handles masked regions correctly.

There is a general issue that the tri grids are a niche market and information about them is swamped by quad grid information.  All too often a user who has a question about tri grids receives a well-meaning answer to convert to a quad grid and use contour, etc, rather than use the specialised tri functions that are better.  So I would prefer either 2 or 0 examples here rather than 1.

**Comment by timhoffm** [comment]
What about putting both examples in a single file?

**Comment by ianthomas23** [comment]
Good idea!  Will do.

**Comment by jklymak** [comment]
Yes sorry I meant to combine the two examples into one file.

**Comment by jklymak** [comment]
@ianthomas23 I think this is in your court still?

**Comment by jklymak** [comment]
No rush just going through the backlog and seeing what seems stalled and putting in draft status.

**Comment by ianthomas23** [comment]
I am closing this as I evidently lost interest in it 2 years ago. I'll leave the branch hanging around in case anyone else wants to pick it up.

**Pull request closed without merging**
