### PR TITLE
DOC: restore SHA to footer

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary

Depends on https://github.com/matplotlib/mpl-sphinx-theme/pull/54 being merged.

We used to include the exact commit used to build the docs in the footer (see https://matplotlib.org/3.4.3/index.html) however that got lost as part of the move to mpl-sphinx-theme. This adds the option to put this in the footer again.

### CODE REVIEW

**Comment by tacaswell** [comment]
This will also require a pin forward on the version of mpl-sphinx-theme we require to build the docs.

**Comment by QuLogic** [comment]
There is no pin on `main`, only the release branch.

**Comment by tacaswell** [comment]
image

**Comment by QuLogic** [comment]
With a small bit of CSS:
```css
.bd-footer__inner {
	display: flex;
	flex-wrap: wrap;
}
.footer-item {
	margin: 0 0.5em;
}
.footer-item:first-child {
	width: 100%;
}
```
we can get it together like before:
image

**Comment by tacaswell** [comment]
I am in favor of leaving the CSS tweaking for later.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
Feel free to self-merge if mpl-sphinx-theme is already at 3.7

**Comment by tacaswell** [comment]
> Feel free to self-merge if mpl-sphinx-theme is already at 3.7

it is in a funny state (due to branch protections I could not push the version bumping commit to main but I _could_ push the tag, will fix that soon), but there is a release on pypi.

**Comment by tacaswell** [comment]
manually cancelled the appevyor to unblock it for other PRs.

**Comment by tacaswell** [comment]
Will backport this as part of #25194 .

**Comment by ksunden** [comment]
Backport included in 3.7.0 final preparation

**Pull request merged**
