### PR TITLE
Revert "Add inaxes method to FigureCanvas to check whether point is in an axes."

### PR DESCRIPTION
**Pull request by jklymak**
Reverts matplotlib/matplotlib#9845  This broke the build, and needs to be re-facotered to work with 3.0.1

### CODE REVIEW

**Comment by jklymak** [comment]
Huh, that didn't fully fix it either  There was another PR that maybe caused this, or maybe something is wrong w/. CI

**Comment by lkjell** [comment]
@jklymak have to tried to test it locally? I do not get any qt error as in travis on master. However, I had to change windows manager else test_dpi_ratio_change would fail.

**Comment by tacaswell** [comment]
This looks like a qt configuration error on travis to me...

**Comment by jklymak** [comment]
Yep agreed. Thanks.  This pr still needs modificTion but not to be reverted.  It was worth a try...

**Comment by smheidrich** [comment]
Adding ``qtbase5-dev`` as a package to be installed in ``.travis.yml`` **and deleting the cache on Travis** (didn't work without deleting it!) [seems to have fixed it for me](https://travis-ci.org/smheidrich/matplotlib/builds/491570220). But it was pure guesswork and maybe this could be solved by installing only a subset of ``qtbase5-dev``'s dependencies.

**Pull request closed without merging**
