### PR TITLE
[Bug]: .remove() on ErrorbarContainer object does not remove the corresponding item from the legend

### PR DESCRIPTION
**Pull request by Higgs32584**
#25274 
Patch for bug issue 25274
## PR Checklist

**Documentation and Tests**
- [ ] passes container_tests.py
- [ ] N/A
- [ ] (https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] N/A
- [ ] N/A
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by rcomer** [comment]
Thanks for your contribution @Higgs32584!  This will need a test that would have failed without the change, but now passes.  I think the example from the issue could be adapted into an [image comparison test](https://matplotlib.org/devdocs/devel/testing.html#writing-an-image-comparison-test) that uses the `check_figures_equal` decorator.

**Comment by Higgs32584** [comment]
I apologize for closing this, this was not meant to be closed! I will commit this with a test later, I am still getting used to the development workflow!

**Comment by rcomer** [comment]
@Higgs32584 we have various support for new contributors if it helps:
https://matplotlib.org/devdocs/devel/contributing.html

**Comment by Higgs32584** [comment]
Ok thank you! I will add a pull request later with tests! Have a nice day!

**Pull request closed without merging**
