### PR TITLE
[MRG] ENH new static images for the frontpage

### PR DESCRIPTION
**Pull request by NelleV**
I did not find any code to rebuild the frontpage static images. Here is some code more or less reproducing the front page images, with the new defaults.

Here is the frontpage new look:

screenshot from 2016-11-30 21-51-39

The images are:

contour_frontpage
histogram_frontpage
membrane_frontpage
surface3d_frontpage

If those are fine, i'll commit them to update the website.

I believe long term we could select a few images generated from our gallery, and add them to the frontpage. They will then always be regenerated if the design changes. (We do this for sklearn's frontpage images, and it works nicely).

ref #5654

### CODE REVIEW

**Comment by QuLogic** [comment]
They're a bit larger; do they fit well on the front page (does the CSS handle it?)?

**Comment by NelleV** [comment]
There is a screenshot of the frontpage at the top of the description of the comment that shows the current rendering.

**Comment by tacaswell** [comment]
The images are fixed to 162x139 in the css (https://github.com/matplotlib/matplotlib/blob/master/doc/_static/mpl.css#L759).  We should render them an the same size (to save band width and scaling on the client side).

**Comment by NelleV** [comment]
Feature request: be able to specify px by px size of the images we save !

**Comment by NelleV** [comment]
I've committed smaller files. I had expected mpl to save at 72 dpi, and it seems to save at 100px so the images are slightly bigger. @tacaswell is that fine or should I make them smaller again?

**Comment by NelleV** [comment]
@QuLogic Fixed. These "new" examples were  done by copy pasting stuff, hence the cryptic comments.

**Comment by tacaswell** [comment]
The new default in 100dpi!

**Comment by tacaswell** [comment]
and I still would rather they be the correct size.

**Comment by NelleV** [comment]
I've fixed the size.

**Pull request merged**
