### PR TITLE
Fix memory leaks found by memleak_hawaii3.py

### PR DESCRIPTION
**Pull request by mdboom**
Sorry I couldn't sort this one out before 1.5.0.

### CODE REVIEW

**Comment by WeatherGod** [comment]
The changes here make sense. Are there other places where `convert_to_string` was (mis)-used?

**Comment by mdboom** [comment]
No -- `convert_to_string` is only called from one place: `Py_convert_to_string`.

**Comment by pelson** [comment]
Do you want to target the v1.5.x branch?

**Comment by mdboom** [comment]
Might as well target 1.5.x

**Comment by WeatherGod** [comment]
backported to v1.5.x as a450f99a

**Comment by efiring** [comment]
@mdboom Thanks very much for tracking this down.  Out of curiosity: do you have a simple explanation for why the leak was so much larger on Python 3 than 2?

**Comment by mdboom** [comment]
Unfortunately, no.  But I was seeing a great deal of variation in the result from the `memleak_hawaii3.py` script -- I think it was actually calculating the average increase incorrectly, so it may well be that the numbers were just bogus.  (It was calculating the difference between the memory usage in the middle and the end and dividing by the steps.  That only makes sense if the range is monotonically increasing.  If it's jagged -- which it is -- you can get wildly incorrect numbers.  See #5360).

**Pull request merged**
