### PR TITLE
DOC: Clarify transparency in colors

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Follow-up to #24407.

- Rewrite section on transparency
- Add more subsections to the tutorial for better structure (and use the appropriate level marker (`======`) accordings to https://matplotlib.org/devdocs/devel/documenting_mpl.html#section-formatting

### CODE REVIEW

**Comment by timhoffm** [comment]
IMHO the [current figure](https://matplotlib.org/stable/tutorials/colors/colors.html#sphx-glr-tutorials-colors-colors-py) has some issues

- It's quite cluttered:
  - A table with an "Alpha value" column, but that value is already prominently stated in the titles.
  - Each Axes has a Legend and they look quite the same on first sight. - Better to directly write the zorder on the Artist rather than have the indirection via the legend.
- *alpha = 1* is trivial: You draw the one with higher zorder on top. You certainly don't need two examples for that; I'd argue you don't need that at all.
- *alpha = 0.3* is a value so low that I don't see a visual difference between the zorder at all. - What do we want to illustrate here?

Overall, this a lot of noise but I don't see a clear message we want to communicate with the figure. I suspect it should have something to do with the subsequent note "Re-ordering Artists is not commutative in Matplotlib." / "Changing the order of Artists will generally change the resulting figure." The first version was not comprehensible and was changed to the second version. While correct, the statement is essentially trivial: If you change the order and thus change what is drawn on top, the result may change. The only maybe not completely trivial case is if transparency is involved. That's what I've tried to illustrate in the figure: If you draw the blue alternatively above or below the red square, the mixed region is still not the same. - Though I have to admit, that if one thinks about it for a second and considers only a slight transparency this is also clear: The result is still mostly dominated by the color in front.

Reconsidering, I think the whole front/back discussion here is overemphasized and mostly beyond the scope of what we need to communicate in the context of transparency. Maybe after the formular we should just give an illustration

> The following plot shows an orange rectangle in the background and a set of blue rectangles with varying transparency in the front:

grafik

**Comment by timhoffm** [comment]
Commited with the new proposal.
---
> I wonder how much space a second figure under your first with the orange on top would take up.

What do you want to communicate with that? We'd need to add an alpha to the orange bar, otherwise it's quite meaningless:

image

With alpha=0.8

image

but we have to say a lot more, namely the bar alpha and the changed zorder, which makes it more buy.

One could also put both in one figure, but still this needs all the context information.

image

Overall, I think the simple illustration is enough.

**Comment by jklymak** [comment]
I like the last one.  Like it or not, people are confused by this. 

I don't know that we need 10 alpha values if we want to make the figure narrower.

**Comment by timhoffm** [comment]
Ok, added the two-row exmaple.

**Pull request merged**
