### PR TITLE
Expire deprecation of \mathcircled

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

A slightly tricky one: a bunch of baseline images had to be renumbered because the mathtext tests just index baseline images by their ordinal number, but the mathcircled tests were in the middle... (yes, this is brittle, but I'm not going to refactor this now)
1st commit removes the now unused baselines; 2nd commit renumbers the rest (so that the motion is more obvious in the log).  (Github show them as changed binaries, but they're actually all just deletes and renames.)
attn @timhoffm this may have been one of the issue you ran into in #15890.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
thanks, done

**Comment by tacaswell** [comment]
My approval should be suspect given that I pushed code to this branch, but :+1: to the removal.

I think it is better to accept a bit more complexity in generating the fixtures to avoid having to move many many files.

**Comment by anntzer** [comment]
Fixed a flake8 error, and additionally removed the corresponding entries in _mathtext_data.py.

**Comment by tacaswell** [comment]
rebased to fix the deprecation conflicts, will merge when green.

**Comment by anntzer** [comment]
(may be worth withholding merges until https://gitter.im/matplotlib/matplotlib?at=5e3e96051d23aa47aa003c3b is resolved (either way) in order to not make the history edit more complicated)

**Comment by tacaswell** [comment]
Oh good, UI is showing us all of the extra commits, will fix.

**Comment by tacaswell** [comment]
hmm, it is now not letting me force-push to this branch, sorry @anntzer

**Comment by anntzer** [comment]
rebased

**Comment by tacaswell** [comment]
of course I just broke this by merging the stackrel PR.

**Comment by anntzer** [comment]
rebased

**Pull request merged**
