### PR TITLE
mkdir is in the stdlib in Py3.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
Errors in tests: `TypeError("mkdir() got an unexpected keyword argument 'exist_ok'",)`

**Comment by tacaswell** [comment]
This presumably needs #10425 to go in first?

**Comment by anntzer** [comment]
yup.

**Comment by QuLogic** [comment]
Can rebase now.

**Comment by anntzer** [comment]
done

**Pull request merged**
