### PR TITLE
FIX: dpi and scatter for subfigures now correct

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

The dpi transform was not correct for scatter in subfigures.  Notice how the marker sizes are too small in the left-most axes below.  

Unfortunately the transform stack in collections is weird, in that the "transform" is just a Nx3x3 matrix rather than a full-fledged transform, so fixing directly is difficult.  Instead we just figure out what the proper scaling is by transforming one inch.  

*NOTE* I am deprecating the dpi argument to `collections.set_sizes`.  I'm not clear why you would ever want to hard code this...

### Before

Before

### After

After

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
The before and after images look exactly the same?

**Comment by jklymak** [comment]
Ooops, interesting.  If I save as png they look fine before and after.  If I just do plt.show() I get:

### Before:

Before

### After:

After

**Review by QuLogic — APPROVED** [review]

**Comment by anntzer** [comment]
@jklymak Is the following (approximately, untested) close to what we need (as discussed in the call?)
```patch
diff --git i/lib/matplotlib/figure.py w/lib/matplotlib/figure.py
index 4041793412..ef265b18cc 100644
--- i/lib/matplotlib/figure.py
+++ w/lib/matplotlib/figure.py
@@ -2001,6 +2001,14 @@ class SubFigure(FigureBase):
         if parent._layoutgrid is not None:
             self.init_layoutgrid()
 
+    @property
+    def dpi(self):
+        return self._parent.dpi
+
+    @dpi.setter
+    def dpi(self, value):
+        self._parent.dpi = value
+
     def _redo_transform_rel_fig(self, bbox=None):
         """
         Make the transSubfigure bbox relative to Figure transform.
```

**Comment by QuLogic** [comment]
Related to your question on the call, copying the test and saving at different DPI:

```python
import matplotlib.pyplot as plt


# markers in the left- and right-most subplots should be the same
fig = plt.figure()
gs = fig.add_gridspec(1, 2)
ax0 = fig.add_subplot(gs[1])
ax0.scatter([1, 2, 3], [1, 2, 3], s=30, marker='s')
ax0.scatter([3, 4, 5], [1, 2, 3], s=[20, 30, 40], marker='s')

sfig = fig.add_subfigure(gs[0])
axs = sfig.subplots(1, 2)
for ax in [ax0, axs[0]]:
    ax.scatter([1, 2, 3], [1, 2, 3], s=30, marker='s', color='r')
    ax.scatter([3, 4, 5], [1, 2, 3], s=[20, 30, 40], marker='s', color='g')

fig.savefig('foo0.png', dpi=100)
fig.savefig('foo1.png', dpi=200)
fig.savefig('foo2.png', dpi=300)
```
produces an image with changing scatter size (before this PR).

**Comment by jklymak** [comment]
Closed for #20771.  #20771 now includes the test here for tick spacing.

**Pull request closed without merging**
