### PR TITLE
Drop event_source.interval reset

### LINKED ISSUE #28647: [MNT]: TimedAnimation event loop interval
### Summary

`TimedAnimation` resets the event timer at the end of its `_step()` method: 

https://github.com/matplotlib/matplotlib/blob/f7b3def52b39a070064e0e713042cd948c985643/lib/matplotlib/animation.py#L1446

As far as I can tell, this is by design. The original commit included this comment:

https://github.com/matplotlib/matplotlib/blob/70e401fe681b6e32ed5fdbf7eea182828887d75b/lib/matplotlib/animation.py#L314-L318

To me, this was suprising and it took me a while to get to the bottom of it. From the documentation I took that the event loop calls the animation target at exactly the `interval` specified. However, the current implementation means that it actually calls it at `interval + time_in_callback`. In case the callback does some heavy lifting, like processing data or communicating with an instrument, this can add significant overhead to the real interval between frames.

<details>
<summary>
A MWE highlighting the effects of resetting the interval:
</summary>

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import animation

def update(frame):
    if len(frame) < 2:
        return []
    diff = np.diff(frame)
    avg.set_text(avg_txt.format(diff.mean()*1e3))
    cur.set_text(cur_txt.format(diff[-1]*1e3))
    return [avg, cur]


def frame():
    times = deque(maxlen=100)
    while True:
        time.sleep(0.1)
        times.append(time.perf_counter())
        yield times
        
fig, ax = plt.subplots(figsize=(1,1))
ax.axis('off')
avg_txt = 'avg: {:.3g} ms'
cur_txt = 'cur: {:.3g} ms'
avg = ax.text(0.5, 0.75, avg_txt.format(0), va='center', ha='center')
cur = ax.text(0.5, 0.25, cur_txt.format(0), va='center', ha='center')

anim = animation.FuncAnimation(fig, update, frame, repeat=False,
                               cache_frame_data=False, interval=200)
```

</details>

With the current behavior, this results in an effective interval of 300 ms. Commenting out [the line resetting the interval](https://github.com/matplotlib/matplotlib/blob/f7b3def52b39a070064e0e713042cd948c985643/lib/matplotlib/animation.py#L1446) results in the effective interval I would expect from `interval=200`, 200 ms.

### Proposed fix

There might be reasonable usecases for resetting the interval, but I cannot see any right now. Hence, I would propose to leave the timer running uninterrupted, i.e., dropping

https://github.com/matplotlib/matplotlib/blob/f7b3def52b39a070064e0e713042cd948c985643/lib/matplotlib/animation.py#L1446

### PR DESCRIPTION
**Pull request by Lucx33**
## PR summary

This PR fixes the TimedAnimation event loop by removing the interval reset within the _step() method. This ensures that the animation runs at the expected frame rate, regardless of the duration of the callback execution. Couldnt find examples where pileup happens.

## PR checklist

- [x] "closes #28647" is in the body of the PR description to [link the related issue](https://github.com/matplotlib/matplotlib/issues/28647)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by dopplershift** [comment]
Not setting the delay in that spot is going to cause any `loop_delay` to become permanent after one loop.

I'll also note that it seems that `loop_delay` is broken on macOS at the moment.

**Comment by dopplershift** [comment]
The `dynamic_image.py` example is a good place to test this.

**Comment by tacaswell** [comment]
I suspect that what we want to be doing to better hit the target frame rate is to time the call to `super()._step` and set `self.event_source.interval = max(0, self._interval - draw_time)`

**Comment by greglucas** [comment]
I wonder if the real culprit is that in a lot of backends we are "stopping"/"starting" a new timer every time the `interval` property gets updated. I'm curious if we should put a guard around this property update to only trigger if `self._interval != interval`
https://github.com/matplotlib/matplotlib/blob/ed8131be7727f3e9454f1b30e14ed195ee2ada33/lib/matplotlib/backend_bases.py#L1089

Our timer interval should just keep going at the requested rate under the hood, so updating it to depend on the underlying function call time seems like it would lead to issues and a constantly moving target. My thought with the update guard is that currently we are bringing that draw-time into the underlying timer every time we call that update function without realizing it by calling `start()` based on the event updates.

This diff does provide 200ms in the provided example in https://github.com/matplotlib/matplotlib/issues/28647

```diff
diff --git a/lib/matplotlib/backend_bases.py b/lib/matplotlib/backend_bases.py
index 95ed49612b..f5a41c140f 100644
--- a/lib/matplotlib/backend_bases.py
+++ b/lib/matplotlib/backend_bases.py
@@ -1042,6 +1042,8 @@ class TimerBase:
         """
         self.callbacks = [] if callbacks is None else callbacks.copy()
         # Set .interval and not ._interval to go through the property setter.
+        self._interval = None
+        self._single = None
         self.interval = 1000 if interval is None else interval
         self.single_shot = False
 
@@ -1085,8 +1087,9 @@ class TimerBase:
         # milliseconds, and some error or give warnings.
         # Some backends also fail when interval == 0, so ensure >= 1 msec
         interval = max(int(interval), 1)
-        self._interval = interval
-        self._timer_set_interval()
+        if self._interval != interval:
+            self._interval = interval
+            self._timer_set_interval()
 
     @property
     def single_shot(self):
@@ -1095,8 +1098,9 @@ class TimerBase:
 
     @single_shot.setter
     def single_shot(self, ss):
-        self._single = ss
-        self._timer_set_single_shot()
+        if self._single != ss:
+            self._single = ss
+            self._timer_set_single_shot()
 
     def add_callback(self, func, *args, **kwargs):
         """
```

**Pull request closed without merging**
