### PR TITLE
Let pgf backend use bracket delimiters for detecting math mode.

### PR DESCRIPTION
**Pull request by painch**
## PR Summary

LaTeX (and lualatex/xelatex) allows math mode to be delimited by '\\(', '\\)', '\\[' and '\\]'. This PR changes the pgf backend to detect this, so that e.g. '_' and '^' are not inadvertently escaped in math-mode labels etc.

The current behaviour leads to errors when certain label names are used. For example I've put a minimum working example script `mwe.py` and a tex file `mwe.tex` below. Running `mwe.py show` allows the use of non-pgf backends (Qt5Agg in my case), and displays `\(x^2\)` as $x^2$ correctly, whereas using just plain `mwe.py` then `lualatex mwe.tex` shows it as $x2$. This PR fixes this issue.

mwe.py:
```
#!/usr/bin/env python3

import sys
import matplotlib.pyplot as plt

plt.plot([0,1,2],[0,1,4])
plt.xlabel(r'\(x\)')
plt.ylabel(r'\(x^2\)')

if len(sys.argv)>1 and sys.argv[1]=='show':
    plt.show()
else:
    plt.savefig('mwe.pgf')
```

mwe.tex:
```
\documentclass{standalone}
\usepackage{pgf}

\begin{document}
\input{mwe.pgf}
\end{document}
```

### CODE REVIEW

**Comment by oscargus** [comment]
I think that this probably makes sense, but please include a test for it. I think something like this could be used as a template:
https://github.com/matplotlib/matplotlib/blob/cd9d371cd473b286310845ada9e5a3e786630e1a/lib/matplotlib/tests/test_backend_pgf.py#L326-L334
Use `$` for the reference and the new delimiters for the test.

For me, this still works correctly in the non-TeX backends with `text.usetex=True`, with or without this change. (And it doesn't work using the mathtext backend with or without it.)

**Comment by timhoffm** [comment]
I'm hesitant with this inclusion. As far as I understand LaTeX:

- `\[...\]` is display math mode, which puts the equation on a dedicated line. -  Matplotlib's math mode does not support this. Therefore, I think we should not accept this syntax.
- `\(...\)` is equivalent to `$...$`. So one could argue that we should support this as well. Note however, that due to the asymmetry/symmetry of the delimiters, the matching algorithm would need to be different. `$...$` just identifies pairs. However, you cannot simply add `\(` and `\)` to the matching regexp, because you would also incorrectly match `The \) inverted \( brackets` or even `mixtures $ between \) syntaxes`.
  Getting this right is significant work. I therefore propose not to support `\(...\)` and instead explicitly document that.-

**Comment by painch** [comment]
>     * `\[...\]` is display math mode, which puts the equation on a dedicated line. -  Matplotlib's math mode does not support this. Therefore, I think we should not accept this syntax.
That is a good point -- I've now made a change to reflect that.

>     * `\(...\)` is equivalent to `$...$`. So one could argue that we should support this as well. Note however, that due to the asymmetry/symmetry of the delimiters, the matching algorithm would need to be different. `$...$` just identifies pairs. However, you cannot simply add `\(` and `\)` to the matching regexp, because you would also incorrectly match `The \) inverted \( brackets` or even `mixtures $ between \) syntaxes`.
At least in their TeX Live implementations, lualatex, pdflatex and xelatex don't allow nested `\(...\(...\)...\)`, but do allow mixed `\(...$` and `$...\)`, so the matching algorithm should still work on any valid input, without any major changes.

>       Getting this right is significant work. I therefore propose not to support `\(...\)` and instead explicitly document that.
That is a very reasonable alternative if this doesn't work out.

**Comment by timhoffm** [comment]
> lualatex, pdflatex and xelatex [...] do allow mixed `\(...$` and `$...\)`

Do the they allow `\)...\(`?

**Comment by painch** [comment]
> I think that this probably makes sense, but please include a test for it. I think something like this could be used as a template:

I've had a go writing tests (see the last commit to this branch), I've tried them out locally, though I'm unfamiliar with pytest so they might need some checking.

**Comment by anntzer** [comment]
It would seem like a more robust(?) solution may be to just completely get rid of _tex_escape and instead configure tex to support `_^%` in text mode (I'm not really sure we can do anything, or if the current code does anything, about `$`?).  For underscores this is already done in standard usetex via the `underscore` latex package, and my uneducated guess is that we can implement something similar for `^` and `%`

**Comment by melissawm** [comment]
Hi @painch - let us know if you need any guidance on moving this forward. Thanks!

**Comment by anntzer** [comment]
I think this is superseded by #23442.

**Comment by jklymak** [comment]
Let's close in favour of #23442 and lack of response. @painch Thanks for your contribution - it definitely inspired an improvement!

**Pull request closed without merging**
