### PR TITLE
Use facecolor instead of axisbg/axis_bgcolor

### PR DESCRIPTION
**Pull request by mdboom**
Partial fix for #5309 (the second bullet point).

This deprecates axisbg and axis_bgcolor (which are axis-specific properties) in favor of facecolor.

### CODE REVIEW

**Comment by mdboom** [comment]
Coveralls decreasing because of the creation of deprecated functions.  Other than that, I think this is good to go.

**Comment by tacaswell** [comment]
Add a test which checks the warnings come out?  We don't do that all the time, but we probably should...

**Comment by mdboom** [comment]
Test added.

**Comment by mdboom** [comment]
Backported to 2.0 as 5f1127c41224

**Pull request merged**
