### PR TITLE
[Doc]: Document the position parameter in apply_aspect()

### PR DESCRIPTION
**Pull request by haziq-khurshid**
## PR Summary
This PR documents the position paramter in apply_aspect()
Issue: https://github.com/matplotlib/matplotlib/issues/23583
## PR Checklist

**Tests and Styling**
- [ N/A] Has pytest style unit tests (and `pytest` passes).
- [ N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by tacaswell** [comment]
@haziq-khurshid Why did you close this?  I think the docstring is an improvement, the `Parameters` section just needs to go below that paragraph of prose.

**Comment by haziq-khurshid** [comment]
@tacaswell thank you for responding.
Actually, I was trying to make my first ever open source contribution and 2 tests(ci/circleci: docs-python38 & View the built docs) were failing and I couldn't figure out a reason.
If you can guide me in the exact position of my new lines, I can place them there and make a new PR.

**Comment by tacaswell** [comment]
I will reopen this PR for you, please push new commits to this branch.

It looks like there are three warnings in the build (which are different than I guessed they would be from glancing at the rst).

- https://app.circleci.com/pipelines/github/matplotlib/matplotlib/18062/workflows/0b42bb08-eea2-4fc2-86ba-6d7e1ec991d4/jobs/70041?invite=true#step-113-1153
- https://app.circleci.com/pipelines/github/matplotlib/matplotlib/18062/workflows/0b42bb08-eea2-4fc2-86ba-6d7e1ec991d4/jobs/70041?invite=true#step-113-1145
- https://app.circleci.com/pipelines/github/matplotlib/matplotlib/18062/workflows/0b42bb08-eea2-4fc2-86ba-6d7e1ec991d4/jobs/70041?invite=true#step-113-1146

The first is due to `.get_position` being ambiguous, a number of classes have a method with that name.  The solution is to add qualifiers to the frost until it in not ambiguous.

The next two look to be the same actually issue which is you have put two back ticks before "None" and only one after so the rst parsing is failing.

Additionally, I think the "Paremeters" section should go _after_ the the paragraph you put it above.

**Comment by tacaswell** [comment]
Closing in favor of #23618

I have never seen github driven to this state where two PRs both report they are against the same branch.

**Pull request closed without merging**
