### PR TITLE
mep12 on mri_demo.py

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by pelson** [comment]
I confess, I've merged #4868, but just noticed the folder that this example is in. I wonder if we need to rename the directory, or whether that will just make the location inconsistent for users between mpl versions...

**Comment by ericmjl** [comment]
For now, I have stuck with only changing formatting, and ignored changing the directories of the `pylab_examples`. I think the decision as to which directory to put the example in should be discussed together, for each example, rather than decided by me :).

**Comment by ericmjl** [comment]
Btw, what's the failure point in this case? It doesn't look like my usual `pep8` failures.

**Comment by pelson** [comment]
Hmmm. I've not seen that before - I've restarted it to see if it is stochastic.

**Comment by jenshnielsen** [comment]
@pelson It's my hope that we can basically empty the pylab_examples folder by moving most examples to topic specific folders. I talket to @tacaswell at Scipy avout the fact that if we want users discouraged from using pylab then at least we shouldn't have any that many examples using pylab so IMHO this is a step in the right direction.

**Comment by jenshnielsen** [comment]
@ericmjl I merged this via #4871 to avoid the merge commit at the bottom (It still shows up as your commit)

**Pull request closed without merging**
