### PR TITLE
Use of colors in pie-chart

### PR DESCRIPTION
**Pull request by starstuti**
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by story645** [comment]
Thanks for the PR. Can you please provide a reason for why you made these changes?

**Review by tacaswell — CHANGES_REQUESTED** [review]
Thank you for you work on this, however this is definitely not the correct place for this example to go.  

It should either be integrated into one of the exiting pie demos or one of the color demos so that it gets built and published as part of the documentation rather than as a code comment in a private module.

**Comment by tacaswell** [comment]
Anyone can clear my review.

**Comment by jklymak** [comment]
Thanks so much for your interest in Matplotlib - we love new contributors! OTOH, as it is, this PR needs more justification in the PR description and the content requires more thought. We will close for now, but if you make substantive changes we will be happy to reconsider.

**Pull request closed without merging**
