### PR TITLE
HSV colormap dictionary fixed to be cyclic.

### PR DESCRIPTION
**Pull request by dbukenberger**
## PR Summary
Is there a reason why the hsv-colormap is hardcoded in such a nonintuitive way?
Currently it is not even cyclic as it is supposed to be, right?

Example:
```
>>> import matplotlib as mpl
>>> from matplotlib import cm
>>> cmap = mpl.cm.get_cmap('hsv')
>>> cmap(np.linspace(0,1,11))
[[1.         0.         0.         1.        ]
 [1.         0.5790447  0.         1.        ]
 [0.81874882 1.         0.         1.        ]
 [0.23970412 1.         0.         1.        ]
 [0.         1.         0.36250047 1.        ]
 [0.         1.         0.96470316 1.        ]
 [0.         0.45625236 1.         1.        ]
 [0.14595412 0.         1.         1.        ]
 [0.72499882 0.         1.         1.        ]
 [1.         0.         0.6727947  1.        ]
 [1.         0.         0.09375    1.        ]]
```

Wouldn't it be more accurate, with my edits?
It still doesn't behave as perfectly symmetric as I hoped it would, but it's close.
Nevertheless, it is now actually cyclic:
```
>>> cmap(np.linspace(0,1,11))
[[1.         0.         0.         1.        ]
 [1.         0.58823765 0.         1.        ]
 [0.7999964  1.         0.         1.        ]
 [0.21176228 1.         0.         1.        ]
 [0.         1.         0.4000012  1.        ]
 [0.         0.98823525 1.         1.        ]
 [0.         0.3999976  1.         1.        ]
 [0.21176828 0.         1.         1.        ]
 [0.8000024  0.         1.         1.        ]
 [1.         0.         0.58823412 1.        ]
 [1.         0.         0.         1.        ]]
```

My guess would be, the control-points from the `_cm.py` dictionary are not interpolated linearly and this causes the imprecision?

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for you work on this, however I am deeply skeptical of taking this change.   We consider the visual appearance of the colormaps to be part of our API and hence this change is a backward-incompatible API change. 

Can you at before / after images?

**Comment by dbukenberger** [comment]
Sure, both generated with:

```
import numpy as np
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.imshow([np.linspace(0, 1, 256)], aspect='auto', cmap=plt.get_cmap('hsv'))
ax.set_axis_off()
plt.tight_layout()
plt.savefig('img.png')
```

Before:
old

After:
new

**Comment by dstansby** [comment]
Thanks for opening this PR! I agree with @tacaswell, we probably don't want to edit pre-existing colormaps that people use and are used to. Is there any precedence elsewhere for the hsv colormap being like the changed version? If there is, perhaps we could create a new colormap with your changed version.

**Comment by timhoffm** [comment]
If our current colormaps is incorrect and it can be shown that the new one is actually *the* HSV map, I think it's viable to change the map in a minor release. This would be more like a bug fix and the change is small enough that it wouldn't be disturbing the majority of plots.

**Comment by jklymak** [comment]
I don't think we should post facto change long-standing colormaps.  I think that when it was marked as "cyclic" that was an error, and should be changed.  If we want a perfectly cyclic hsv I think it should be a new map, unfortunately.

**Comment by jklymak** [comment]
I'm going to close, because I don't think we should do this....  Thanks for the PR though!

**Pull request closed without merging**
