### PR TITLE
Simplify definition of mathtext symbols & correctly end tokens in mathtext parsing

### PR DESCRIPTION
**Pull request by anntzer**
### First commit: Simplify definition of mathtext symbols.
Use a single regex that handles both single_symbol (a single character)
and symbol_name (`\knowntexsymbolname`), and also slightly simplify the
"end-of-symbol-name" regex.

This parsing element comes up extremely often, and removing one
indirection layers shaves off ~3-4% off drawing all the current mathtext
tests, i.e.
```
MPLBACKEND=agg python -c 'import time; from pylab import *; from matplotlib.tests.test_mathtext import math_tests; fig = figure(figsize=(3, 10)); fig.text(0, 0, "\n".join(filter(None, math_tests)), size=6); start = time.perf_counter(); [fig.canvas.draw() for _ in range(10)]; print((time.perf_counter() - start) / 10)'
```

### Second commit: Correctly end tokens in mathtext parsing.
This avoids parsing `\sinx` as `\sin x` (it now raises an error
instead), and removes the need for `accentprefixed` (because `\doteq`
is treated as a single token now, instead of `\dot{eq}`).  This also
means that `\doteq` (and friends) are now correctly treated as relations
(per `_relation_symbols`, thus changing the spacing around them); hence
then change in baseline images.  Only keep the `x \doteq y` baseline
(and adjust the test string to undo the spacing), to avoid regen'ing
baselines.

Also shaves ~2% off drawing all the current mathtext tests, i.e.
```
MPLBACKEND=agg python -c 'import time; from pylab import *; from matplotlib.tests.test_mathtext import math_tests; fig = figure(figsize=(3, 10)); fig.text(0, 0, "\n".join(filter(None, math_tests)), size=6); start = time.perf_counter(); [fig.canvas.draw() for _ in range(10)]; print((time.perf_counter() - start) / 10)'
```
(including adjustment for the two removed test cases), probably because
accentprefixed was previously extremely commonly checked, being at the
top of the placeable list; however, performance wasn't really the main
goal here.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

Use a single regex that handles both single_symbol (a single character)
and symbol_name (`\knowntexsymbolname`), and also slightly simplify the
"end-of-symbol-name" regex.

This parsing element comes up extremely often, and removing one
indirection layers shaves off ~3-4% off drawing all the current mathtext
tests, i.e.
```
MPLBACKEND=agg python -c 'import time; from pylab import *; from matplotlib.tests.test_mathtext import math_tests; fig = figure(figsize=(3, 10)); fig.text(0, 0, "\n".join(filter(None, math_tests)), size=6); start = time.perf_counter(); [fig.canvas.draw() for _ in range(10)]; print((time.perf_counter() - start) / 10)'
```

### CODE REVIEW

**Comment by oscargus** [comment]
Considering the doc-build failure: maybe one should also add some test in the main test suite for accents of the types `"', '~', etc? As far as I can see, only `\acute` and so on are tested.

**Comment by anntzer** [comment]
Ah, good catch, fixed and added test.

**Review by oscargus — APPROVED** [review]

**Comment by tacaswell** [comment]
I would prefer if we re-gen the test images here.

I think the `'\ddots'`  symbol was one of the glyphs that was flat out wrong but still passing image tests with a tolerance.

**Comment by anntzer** [comment]
Actually this reveals another bug: I deleted the ddots (etc.) test because they are now recognized as relation operators and extra spaces got added around them, but such spaces should actually not be there because the test string is `r'$\dotplus$ $\doteq$ $\doteqdot$ $\ddots$'` i.e. the relation operator is at (both) extremities of the dollar-enclosed part, in which case tex does not introduce a space.  For a simpler example, consider `figtext(.5, .5, "a$=b$", size=24)` with or without usetex.  With usetex, there's no space between "a" and "=" (whereas there's one between "=" and "b"), whereas mathtext introduces a space on both sides of the "=".

Fixing this bug (which probably involves reusing something like the "Binary operators at start of string should not be spaced" part of the code in `def symbol()`) should allow keeping the old ddots test, so I'll look into that...

**Comment by anntzer** [comment]
I went for the easier path of just adding `\hspace{-0.2}` as needed to fix the images.

**Comment by jklymak** [comment]
@tacaswell can you re-review to be sure your concerns are met?

**Comment by jklymak** [comment]
@anntzer it looks like you have still removed a bunch of baseline images.  Are we sure those are still tested?

**Comment by anntzer** [comment]
Yes I am sure, this is only removing test 77, which checks that "accentprefixed" commands are correctly interpreted (e.g. \doteq is not interpreted as \dot eq), but this is essentially also covered by the `r'$\dotplus$ $\doteq$ $\doteqdot$ $\ddots$'` just above, and by the `\sinx` test I added below to check, more generally, that spaces (or braces) are required after operators now (I also added a similar `\dota` test for good measure).

**Comment by tacaswell** [comment]
It it worth an API change note on the spacing?

**Comment by anntzer** [comment]
Changelog entry added, also added dotminus to the spaced operators as it was clearly missing before.
Also moved dotplus and dotminus from "relational operators" to "binary operators" (see e.g. https://mirrors.ircam.fr/pub/CTAN/macros/unicodetex/latex/unicode-math/unimath-symbols.pdf), this actually has no effect on our rendering because we use the same amount of space for both even though that is a simplification over tex's algorithm (https://tex.stackexchange.com/a/38986).

**Review by tacaswell — APPROVED** [review]

**Pull request merged**
