### PR TITLE
MEP12 on axes_props.py

### PR DESCRIPTION
**Pull request by domspad**
pylab to plt and np

### CODE REVIEW

**Comment by WeatherGod** [comment]
PEP8 failure, and needs a rebase to fix an unrelated failure.
/home/travis/build/matplotlib/matplotlib/examples/pylab_examples/axes_props.py:7:19: W291 trailing whitespace

**Comment by jenshnielsen** [comment]
@WeatherGod I don't think we need the rebase. It will merge into current master when run again. I just reran a bunch of other jobs with unrelated failures from fonteffects demo

**Comment by WeatherGod** [comment]
Does travis always test against a merge between the branch and current master, or whatever the checkout of the branch is?

**Comment by jenshnielsen** [comment]
It's not as simple as that. I think the merge is into the master as the job gets queued. Certainly many of these jobs where running after we fixed master but added to the queue before however restarting them fixes the bug.  Also if the changes are in .travis.yml it behaves differently I think

**Pull request merged**
