### PR TITLE
FIX: bypass inverse in collection

### LINKED ISSUE #17203: Subplots using bad axis limits in 3.2
### Bug report

**Bug summary**

Subplots are _sometimes_ using bad axis limits depending on the number and layout of subplots. 

I guess those axis limits are guess from what gets plotted.

This happens in 3.2.1 but not in 3.1.2. I looked through the changelogs of 3.2 releases and saw nothing about axis limits. Sorry if I missed it.

**Code for reproduction**

Here I plot a point at x=0, y=0:

```python
import matplotlib.pyplot as plt

for rows in range(1, 3):
    for cols in range(1, 3):
        
        # skip single plot, no subplot there
        if rows == 1 and cols == 1: continue

        fig, axes = plt.subplots(rows, cols)

        for i, ax in enumerate(axes.ravel()):
            ax.scatter(x=0, y=0)
        
        plt.show()
```

**Actual outcome, in 3.2.1**

**Expected Outcome, in 3.1.2**

**Matplotlib version**

  * Operating system: Archlinux
  * Matplotlib version: 3.2.1 from Arch repos
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg, module://ipykernel.pylab.backend_inline
  * Python version: 3.8.2 from Arch repos

  * Matplotlib 3.1.2 from pip

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

I think this fixes #17203.  If anyone has a dev environment where #17203 is triggered can you test this?  It bypasses transforming the offsets if the offset transform and the data transform are the same.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
This works for me, though it appears tests are not happy about it.

**Comment by anntzer** [comment]
Untested, but I think the following may work fine too, be simpler, and cover more cases?
```patch
diff --git i/lib/matplotlib/collections.py w/lib/matplotlib/collections.py
index 181e46b45..55a681000 100644
--- i/lib/matplotlib/collections.py
+++ w/lib/matplotlib/collections.py
@@ -211,8 +211,6 @@ class Collection(artist.Artist, cm.ScalarMappable):
             # we may have transform.contains_branch(transData) but not
             # transforms.get_affine().contains_branch(transData).  But later,
             # be careful to only apply the affine part that remains.
-        if not transOffset.is_affine:
-            offsets = transOffset.transform_non_affine(offsets)
 
         if isinstance(offsets, np.ma.MaskedArray):
             offsets = offsets.filled(np.nan)
@@ -226,7 +224,8 @@ class Collection(artist.Artist, cm.ScalarMappable):
                 # also use this algorithm (like streamplot).
                 result = mpath.get_path_collection_extents(
                     transform.get_affine(), paths, self.get_transforms(),
-                    offsets, transOffset.get_affine().frozen())
+                    transOffset.transform_non_affine(offsets),
+                    transOffset.get_affine().frozen())
                 return result.transformed(transData.inverted())
             if not self._offsetsNone:
                 # this is for collections that have their paths (shapes)
@@ -234,14 +233,13 @@ class Collection(artist.Artist, cm.ScalarMappable):
                 # (i.e. like scatter). We can't uniquely set limits based on
                 # those shapes, so we just set the limits based on their
                 # location.
-                # Finish the transform:
-                offsets = (transOffset.get_affine() +
-                           transData.inverted()).transform(offsets)
+                offsets = (transOffset - transData).transform(offsets)
                 offsets = np.ma.masked_invalid(offsets)
                 if not offsets.mask.all():
                     points = np.row_stack((offsets.min(axis=0),
                                            offsets.max(axis=0)))
                     return transforms.Bbox(points)
+
         return transforms.Bbox.null()
 
     def get_window_extent(self, renderer):
```
The point is that `transOffset - transData` will check whether transOffset and transData contain the same subtransform and if so will cancel them out exactly.  So this would work even if e.g. `transOffset = someothertransform + transData` or whatnot.

**Comment by jklymak** [comment]
I *really* don't understand why transforms were implemented with __add__ and __minus__  to really mean multiplication and multiplication by the inverse.  Worse, these operators are, as far as I can tell, *completely* undocumented.  So I'm not in favour of adding them to the code until this situation improves.

**Comment by dstansby** [comment]
> I _really_ don't understand why transforms were implemented with **add** and **minus** to really mean multiplication and multiplication by the inverse. Worse, these operators are, as far as I can tell, _completely_ undocumented. So I'm not in favour of adding them to the code until this situation improves.

Woah, that is confusing! I was looking at your changelog and got really confused with what was happening because it never crossed my mind that + could ever mean multiplying two transformations together.

**Comment by jklymak** [comment]
I should stipulate that `__sub__` and `__add__` are documented, but as far as I can tell they don't come up in the webpage docs.

**Comment by anntzer** [comment]
There was one transform operator in the code before (an addition: `transOffset.get_affine() + transData.inverted()`); there's still one in my proposed patch (`transOffset - transData`), so in that sense it doesn't make things worse.  And my proposed patch avoids splitting the affine and non-affine parts of transOffset unless we really need to do it.

As to why multiplication and division are implemented as addition and subtraction: I didn't make that choice so I can't tell, but it's not a completely silly choice either.  In particular, if you follow the matrix multiplication semantics, you'd have `A + B [current] === B * A [matrix]`, i.e. apply B then A.  But then you simply don't have a good way to write `A - B` (apply A then the inverse of B) because there's no leftdivide in python.  Sure you could write `(1/B) * A` but then it becomes much more awkward to get the "enforced cancelling" when `A = B` (unless `1/B` returns a special object which knows its inverse), and even then `(1/B) * A` (or `B**-1 * A`) doesn't read that nicely either.

**Comment by jklymak** [comment]
> There was one transform operator in the code before 

Ha ha, guess why?  

I've implement it with the minus sign and put a comment.  The extra code in `transform` to handle the inverse properly does seem quite helpful.

**Comment by jklymak** [comment]
... added a simple test as well..

**Comment by jklymak** [comment]
OK, I have real troubles manually backporting:

```
$ git checkout v3.2.x
error: pathspec 'v3.2.x' did not match any file(s) known to git
```

Like maybe this PR isn't worth back porting, but the instructions *used* to work

**Comment by kannes** [comment]
> OK, I have real troubles manually backporting:
> 
> ```
> $ git checkout v3.2.x
> error: pathspec 'v3.2.x' did not match any file(s) known to git
> ```
> 
> Like maybe this PR isn't worth back porting, but the instructions _used_ to work

Works fine for me on a fresh git clone, maybe you need to `fetch` the remote branch to your repo?

**Pull request merged**
