### PR TITLE
Fix: [Bug]: Setting norm by string doesn't work for hexbin #28105

### PR DESCRIPTION
**Pull request by clementgilli**
## PR summary

The problem was that the methods on the norm were called directly on a string instead of the object itself.
So I put this block after `collection.set_norm(norm) in order to call the norm's getter.

```
# autoscale the norm with current accum values if it hasn't been set
        if norm is not None:
            if collection.norm.vmin is None and collection.norm.vmax is None:
                collection.norm.autoscale()
```

Seems to solve the issue.

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [x] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for working on this!  I think you need to do atleast two more things:

 - add a test that strings work (so it does not break again in the future).  Is this is "it used to explode" issue, it does not need to be an image test.  Can you also add a test that if you pass norm as a string and vmin and vmax that the norm object is what you expect and the vmin/vmax are set to what was passed in (the failure mode it is trying to catch would be the auto-scaling logic moving much earlier and getting in before we check "are you autoscaled")?
 - squash your commits into 1 to remove the added/deleted file from the history (we had an incident where someone committed a whole venv and then removed it in the history which was annoying to remove) see https://matplotlib.org/devdocs/devel/development_workflow.html#rewrite-commit-history

**Comment by clementgilli** [comment]
I squashed as you said, but I don't really know where add this tests, as I'm a new contributor.
For the first test, I don't understand what you are expecting.
For the second, here an idea :
```
ax =hexbin(rand(10), rand(10), norm="log",vmin=2,vmax=5)
assert ax.norm.vmin == 2
assert ax.norm.vmin == 5
```

**Comment by tacaswell** [comment]
That code (along with probably checking the type of `ax.norm`) is exactly what I was asking for.

Putting the new test near https://github.com/matplotlib/matplotlib/blob/199c31fa64f46d2b3dff59b0921eb0472f72570b/lib/matplotlib/tests/test_axes.py#L969-L978 makes sense to me, call it something like `test_hexbin_string_norm`

**Comment by tacaswell** [comment]
Content of the test looks good!  However, the linter needs to be placated.

**Comment by clementgilli** [comment]
Sorry for the wait, it should be good now.

**Review by timhoffm — APPROVED** [review]

**Comment by tacaswell** [comment]
Thank you for your work on this @clementgilli and congratulations on your first merged Matplotlib PR 🎉 

I hope we hear from you again.

**Pull request merged**
