### PR TITLE
Fixed color tuple's precision

### PR DESCRIPTION
**Pull request by kanishkanarch**
## PR Checklist

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] New plotting related features are documented with examples.

**Release Notes**
- [x] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [x] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [x] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for your work, but can you please provide some context as to what issue this is fixing?

My guess is that something is suffering from float errors and you are passing in values that are just barely out of gamut? If that is the case, I think you should be being doing that outside of Matplotlib.  If Matplotlib is generating these values internally, we should to the clipping / clamping where ever we generate the values not here. 

If I'm wrong about those being viable solutions, I think we should use `np.around` or the built in `round` instead.  It is also unclear to me why 7 decimal places in the correct level of precision to keep.

**Comment by kanishkanarch** [comment]
Hi, @tacaswell, thanks for reviewing this PR. 
I was working with [this PR on Detectron2](https://github.com/facebookresearch/detectron2/pull/4735), and backtracked the error to here.
Your are absolutely correct. I am changing only those values which are getting barely out of the range, something which might happen probably after the 7th or 8th bit of the number in binary representation.
Below I printed the tuple representing RGB values the **`c`** tuple is getting [here](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/colors.py#L394) (lines 394-396 below):

image

and the output is: 

image

(Maybe because the code is fast that's why it is showing the assertion error of the actual value after a couple of runs) You can see that the highlighted line has values narrowly going out of the suggested range of 0.0 - 1.0.

**Comment by kanishkanarch** [comment]
Taking this correction outside of Matplotlib will lead me to floating point representation in Python, which is fine for now. I think for practical purposes Matplotlib won't require a precision of more than 15 decimal places, that's why I suggest this PR to be done here and not in Python itself.

**Comment by kanishkanarch** [comment]
Thank you for guiding, following is a minimal example of the issue:
(Please guide if I should add this example anywhere else)

Code input:
```
import matplotlib.colors as mplc
color = (1.0, 1.0000000000000002, 0.9999999999999998)
mplc.to_rgb(color)
```
Output:
```
File ~/miniconda3/envs/m2f/lib/python3.10/site-packages/matplotlib/colors.py:395, in _to_rgba_no_colorcycle(c, alpha)
    393     c = c[:3] + (alpha,)
    394 if any(elem < 0 or elem > 1 for elem in c):
--> 395     raise ValueError("RGBA values should be within 0-1 range")
    396 return c
```

**Comment by jklymak** [comment]
@kanishkanarch that seems to be working as it should, and I don't think Matplotlib should change this.  It's up to downstream libraries to ensure their values are within 0 and 1.  Can we close this?

**Comment by tacaswell** [comment]
Reading through the linked PRs to https://github.com/facebookresearch/detectron2/pull/4500#discussion_r954387438 is asking you to find where the RGB values are computed and to the clipping _there_.  The correct place to fix this is someplace farther down stream at (one of) the call site of `draw_text` not further upstream in Matplotlib or CPython.

**Pull request closed without merging**
