### PR TITLE
Support non-integer bases in mathtext sqrt

### LINKED ISSUE #8665: Noninteger Bases in mathtext sqrt
### Bug report

**Bug summary**
It appears that only integer sqrt bases are allowed by mathtext. The documentation does not list this limitation.

**Code for reproduction**
```
import matplotlib.pyplot as plt

fig = plt.figure()
axis = fig.add_subplot(1, 1, 1)
axis.plot(1, 1, label=r'$\sqrt[a]{{x}}$')
axis.legend()
plt.show()
```

**Actual outcome**
`mathtext.Parser.parse` raises a `ValueError`.

**Expected outcome**
The [documentation](https://matplotlib.org/users/mathtext.html#radicals) states the following:

> Radicals can be produced with the \sqrt[]{} command ... Any base can (optionally) be provided inside square brackets. Note that the base must be a simple expression, and can not contain layout commands such as fractions or sub/superscripts

In fact, it seems that only a (signed) integer literal is allowed. From `mathtext.Parser.__init__`:
```
p.sqrt          <<= Group(
                     Suppress(Literal(r"\sqrt"))
                   - ((Optional(p.lbracket + p.int_literal + p.rbracket, default=None)
                      + p.required_group)
                   | Error("Expected \sqrt{value}"))
                 )
```
It would be convenient if other bases were allowed. If that change cannot be made (or in the meantime), I think the documentation should be updated.

**Matplotlib version**
  * Operating System: Debian 9.0
  * Matplotlib Version: 2.0.0
  * Python Version: 3.5.3

I believe I installed Python from the `python3.5` package in the `stretch` repository and Matplotlib from the `python3-matplotlib` package in the `stretch` repository, but I'm not sure.

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Fixes #8665 by using the code snippet proposed there https://github.com/matplotlib/matplotlib/issues/8665#issuecomment-735868884.

The test images show that it works.

I'm a bit hesitant to add 72kB of images just for testing this. I would also be ok to strip the test again and commit without tests. It's rather unlikely that we'll touch the base part of `sqrt` again and break it.

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]
I’d much rather have the tests. 72kb doesn’t seem worth worrying about.

**Comment by anntzer** [comment]
Actually one possibility would be to *only* test in svg and using `rcParams["svg.fonttype"] = "none"`, which avoids embedding the font, and therefore results in a very small (1.7kb) file.  (Another 30% could be chopped off if you could get rid of the metadata block...)

In order to render the result correctly, inkscape needs to know the path to Matplotlib fonts.  This can either be done by adding "Additional font directories" in the Inkscape GUI under preferences/tools/text, or (I guess that'll be the practical solution for us, which should be reasonably easily automatable) by copying the Matplotlib fonts to e.g. `/tmp/foo/inkscape/fonts` and running inkscape with `XDG_CONFIG_HOME=/tmp/foo`.

I think the savings may be worth it?  Especially as this should allow us to work much more regularly on adding mathtext improvements without being restricted by the baseline images problem at all.

**Comment by aitikgupta** [comment]
Can we not merge the new tests with the old ones?
(Might not affect the overall size, but could reduce the need to add new images for every new supported symbol?)
@anntzer said something in a similar line of thought here https://github.com/matplotlib/matplotlib/pull/18916#issuecomment-751782902/

**Review by anntzer — CHANGES_REQUESTED** [review]
Let's decide on https://github.com/matplotlib/matplotlib/pull/19201 first.

**Comment by anntzer** [comment]
Superseded by https://github.com/matplotlib/matplotlib/pull/19261.

**Pull request closed without merging**
