### PR TITLE
mathtext: Use DejaVu display symbols when available

### PR DESCRIPTION
**Pull request by zblz**
With the new DejaVu font default many of the symbols (most notably the integral, product, and summation symbol) are very small, as they are designed for inline math. The DejaVu fonts include display-sized variants for some of the math symbols outside of the unicode range. According to @mdboom, it is currently non-trivial to access these variants in a consistent manner from matplotlib, so here I did a bit of hack so we can always access them:

- I modified [the subset.py script from google web fonts](https://code.google.com/p/googlefontdirectory/source/browse/tools/subset/subset.py) so that it can create a font with a subset of all the glyphs with names ending in `.display` and move them to the unicode index corresponding to the regular glyph. I created two ttf files with this: `DejaVuSansDisplay.ttf` and `DejaVuSerifDisplay.ttf`. The family names have an additional ` Display` at the end to differentiate them from the regular fonts. These are pretty small, as they only have a dozen characters.
- I have saved this modified `subset.py` with the fonts in `lib/matplotlib/mpl-data/fonts/ttf`. I think it's good to keep it so this modification can be done in the future if we update the version of DejaVu fonts, but I am not sure this is the right place. A better location might be `tools`. Ideas? It has an Apache license, so AFAICT it's ok to distribute it.
- The DejaVu font classes in `mathtext.py` will now look first for a glyph in the display version of the fonts (I have added them as fontname `ex`, following the `cmex` example), and if not found will use the regular version. 

The baseline images definitely look better, specially the ones that include fractions and integrals.

### CODE REVIEW

**Comment by mdboom** [comment]
Wow.  This is super helpful.  Very cool.

> I created two ttf files with this: DejaVuSansDisplay.ttf and DejaVuSerifDisplay.ttf. 

That's a good idea.  Linux packagers will probably want to remove our DejaVu and substitute their own package.  Providing our own custom fonts for just these extra characters is going to be much better received than modifying DejaVu directly.

> A better location might be tools. Ideas? 

I think `tools` is probably better.  Can you also add a script that calls `subset.py` and does exactly the right thing to go from a new DejaVu to the Display subsets?  (Otherwise exactly how to do this will be lost in time).

> The baseline images definitely look better, specially the ones that include fractions and integrals.

I agree. They look much much better.

**Comment by zblz** [comment]
I added a small usage string for subset when called without arguments or with `-h`, as an additional scripts seems too much for the little used it will get.

**Comment by mdboom** [comment]
Maybe also add a note that fontforge must be installed...

**Comment by zblz** [comment]
Indeed, without fontforge the script does not even run to show the usage text, so I just moved it to a README file.

**Comment by zblz** [comment]
In the end I added a small script that makes the two calls to subset.py and checks before that fontforge is importable.

**Comment by mdboom** [comment]
Backported to 2.0.x as a77bb83a68ae

**Pull request merged**
