### PR TITLE
Deprecate toggling axes navigatability using the keyboard.

### PR DESCRIPTION
**Pull request by anntzer**
I made the backend_tools version just point to backend_bases to avoid
repeating the deprecation.

See discussion at https://github.com/matplotlib/matplotlib/issues/11432 (TL;DR: this feature is both confusing and buggy).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
rebased

**Comment by tacaswell** [comment]
needs yet another rebase.

**Comment by anntzer** [comment]
rebased

**Comment by tacaswell** [comment]
rebased yet again (this time conflicts with the docstring clean up PR).

**Comment by anntzer** [comment]
thanks :p

**Comment by tacaswell** [comment]
merged before we got another conflict

**Pull request merged**
