### PR TITLE
Choose offset text from ticks, not axes limits.

### PR DESCRIPTION
**Pull request by anntzer**
Turns out the fix for #5738 was easier than expected.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: 

This should get a png only image test (the example from #5738 is perfect).

It looks like there is some low-hanging re-factoring possible here (`_set_offset` is only called from `set_locs` which passes in the range derived from a call to `get_view_interval`, nothing is _wrong_ just could be neater and it is not clear to me that pulling on that stitch won't unravel way more than intended).

**Comment by anntzer** [comment]
I'm sort of hoping to just get this merged as-is and get a better test suite (not image based) / refactoring when working on #5755.

**Comment by tacaswell** [comment]
Fair enough

**Comment by tacaswell** [comment]
backported to 2.x as f52afbf0fa38eafbe777757a4881019a821c4457

**Pull request merged**
