### PR TITLE
Further shorten quiver3d computation...

### PR DESCRIPTION
**Pull request by anntzer**
... by using einsum instead of juggling axis order.

This has essentially no effect on performance.

followup to #15346.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by GalAvineri** [comment]
I compared the running time to my code and I do see about 10% reduction in time when the number of vectors is high, so I disagree with the "no effect on performance" part ;)

In addition I received an issue when running your code:
```
   2622             heads = shafts[:, :1] - np.multiply.outer(arrow_dt, head_dirs)
   2623             # stack left and right head lines together
-> 2624             heads.shape = (len(arrow_dt), -1, 3)
   2625             # transpose to get a list of lines
   2626             heads = heads.swapaxes(0, 1)
AttributeError: incompatible shape for a non-contiguous array
```
This could be reproduced with this MRE:
```python
x, y, z = [np.random.rand(10) for _ in range(3)]
X, Y, Z = np.meshgrid(x, y, z)
U, V, W = [np.random.rand(*X.shape) for _ in range(3)]
ax.quiver(X, Y, Z, U, V, W)
```

**Comment by GalAvineri** [comment]
If you can reproduce this as well, that also means that the automatic checks missed it somehow and perhaps they need to be improved as well

**Comment by anntzer** [comment]
> I compared the running time to my PR and I do see about 10% reduction in time when the number of vectors is high when using your PR, so I disagree with the "no effect on performance" part ;)

Is my version faster or yours?

> In addition I received an issue when running your code: (elided)

Did you miss https://github.com/matplotlib/matplotlib/pull/15373/files#diff-84224cb1c8cd1f13b7adc5930ee2fc8fR2625?

**Comment by GalAvineri** [comment]
> Did you miss https://github.com/matplotlib/matplotlib/pull/15373/files#diff-84224cb1c8cd1f13b7adc5930ee2fc8fR2625?

I indeed missed the reshape, thanks! Now there is no issue indeed :)

> Is my version faster or yours?

I ran it again and it isn't faster now.  I guess this happened because I only looked at the mean and not at the std as well?

**Comment by anntzer** [comment]
rebased

**Comment by timhoffm** [comment]
Flake8:

./lib/mpl_toolkits/mplot3d/axes3d.py:2544:17: E128 continuation line under-indented for visual indent

**Comment by anntzer** [comment]
fixed

**Pull request merged**
