### PR TITLE
Axis user guide

### LINKED ISSUE #9322: Usage Guide has description "circled in green" for Axis from v 1.5
The [Axis section of the user guide](https://matplotlib.org/tutorials/introductory/usage.html#axis) has the phrase "circled in green" which I believe refers to the image from v 1.5. This should be deleted. I happen to like the previous image better as the new one doesn't help define the hierarchy very well.

### PR DESCRIPTION
**Pull request by tdpetrou**
## PR Summary

Deleted a single phrase 'circled in green'. 
Closes #9322

### CODE REVIEW

**Comment by tacaswell** [comment]
The docs failures look like they are due to a clash between our configuration and the just release sphinx-gallery 0.1.13 https://github.com/matplotlib/matplotlib/pull/9325 has a fix.

@tdpetrou Could you also take out the comment to a blue square a few paragraphs up?

**Comment by anntzer** [comment]
Thanks for your first contribution!
Hoping to see you around again.

**Comment by tdpetrou** [comment]
@anntzer Sure, glad to help. I actually found an issue this morning and posted it about it in #8122.

**Comment by anntzer** [comment]
@tacaswell will need manual backport (due to squashmerge)

**Comment by tacaswell** [comment]
backported to v2.1.0-doc as 8022a92a6

This will go live next time the docs get rebuilt.

**Pull request merged**
