### PR TITLE
Always pass integers to wx.Size.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Fixes test failure on Python 3.10, https://bugzilla.redhat.com/show_bug.cgi?id=1902382

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]

**Comment by tacaswell** [comment]
Why `ceil` instead of `floor`?

**Comment by anntzer** [comment]
> Why ceil instead of floor?

(It would be nice to document once and for all how floating-point canvas sizes (which can legitimately occur e.g. with vector backends) are supposed to be handled by backends that only support integer sizes (typically raster backends).)

**Comment by QuLogic** [comment]
Because that's what's already done here:
https://github.com/matplotlib/matplotlib/blob/ff15ca9118f1c44db71d6d07b06a2e4d39f79710/lib/matplotlib/backends/backend_wx.py#L505-L508

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.3.x

**Pull request merged**
