### PR TITLE
Add Comic Neue as a fantasy font.

### PR DESCRIPTION
**Pull request by QuLogic**
All of xkcd, Humor, and Comic Sans MS are non-Free, but at least Comic Neue can be a fallback that is Free and available on Linux distros.

## PR Checklist

- [N/A] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [?] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [?] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
looks like Humor Sans (http://antiyawn.com/uploads/humorsans.html) uses SIL Open Font license, which is the same as Comic Neue (http://comicneue.com/)?

**Comment by timhoffm** [comment]
So strictly, this is not needed? OTOH it doesn't hurt to put as the last fallback.

**Comment by anntzer** [comment]
@QuLogic I don't mind adding Comic Neue, but I'm just confused about your original statement?

**Comment by QuLogic** [comment]
Ah, you're right, I originally found [the blog post](https://xkcdsucks.blogspot.com/2009/03/xkcdsucks-is-proud-to-present-humor.html) which directly links the font, and doesn't mention the license. I'm also not sure about copying someone else's handwriting to produce a font, but IANAL, so :man_shrugging: 

But in any case, Fedora doesn't have Humor Sans while it does have Comic Neue.

**Pull request merged**
