### PR TITLE
Upgrade jquery and jquery-ui

### LINKED ISSUE #5083: Please include un-minified version of JQuery
hello,
this has been reported in Debian at http://bugs.debian.org/788730 . Some licenses (GPL for example, one of the 2 JQuery is licensed with) requires to distribute the "preferred form of modification" of the program, which in our case is the unminified version of jquery.

I will host those files in the packaging, but it would be extra-awe along with the "compiled" (in this case minified) result some if you could ship (it's the web backend) also the verbose version of jquery along with the midified. It would be enough to have it in the source tarball and install only the minified one (we dont install source along with binaries, right?)

thanks for considering,
Sandro

### PR DESCRIPTION
**Pull request by jkseppan**
And include their source code, closes #5083 (also makes it somewhat
moot since the newer versions are MIT licensed only).

### CODE REVIEW

**Comment by jkseppan** [comment]
Some brief testing on my system doesn't show that anything is broken by this change.

**Comment by tacaswell** [comment]
Can you put the MIT license in the license folder?

https://github.com/matplotlib/matplotlib/tree/master/LICENSE

**Comment by jkseppan** [comment]
Yes, that latest commit adds it in LICENSE/LICENSE_JQUERY. I included the copyright notices from the jquery files.

**Comment by tacaswell** [comment]
This only affects the webagg backend, not nbagg where we use what ever version of jquery that is supplied by jupyyter.

**Comment by tacaswell** [comment]
Tested out webagg example, works.

This is technically an API change as we are no longer shipping the same version of jquery and users could be grabbing it by name, I will add the docs in a new PR.

**Comment by tacaswell** [comment]
attn @sandrotosi  I believe that debian's concerns have been addressed two ways 1) no longer using a GPL version of jquery 2) including the license

**Comment by sandrotosi** [comment]
+ having the un-minified version in the repo (and even in the released tarball right? should be implicitly covered by the current MANIFEST.in, but just want to be sure) - that's great guys, thanks a ton!! if you could also consider a release with this and the removal of Lena Söderberg image taht would be fantastic

**Comment by tacaswell** [comment]
Lena is already gone from the 1.5rc1 tag, this will be in 1.5rc2

**Comment by sandrotosi** [comment]
@tacaswell do you have any estimate on when  1.5rc2 will be tagged? I'd like to use this weekend to upload that version in Debian (which also will give more exposure to mpl on unconventional archs)

**Comment by tacaswell** [comment]
Maybe tonight.

**Comment by sandrotosi** [comment]
awesome, thanks (also for the super fast reply)!

**Pull request merged**
