### PR TITLE
Convert text to path in logo

### PR DESCRIPTION
**Pull request by mdboom**
Convert the text to path in logo

### CODE REVIEW

**Comment by mdboom** [comment]
Addresses this [comment](https://github.com/matplotlib/matplotlib/pull/5653#issuecomment-167803592) in #5653

**Comment by WeatherGod** [comment]
yay, the image looks good to me! I'll restart the failed tests.

**Comment by WeatherGod** [comment]
I take it that it'll get merged down to master at some point?

**Comment by mdboom** [comment]
> I take it that it'll get merged down to master at some point?

Yes.

**Comment by tacaswell** [comment]
This needs to be back-ported to 1.5.0-doc as well

**Comment by mdboom** [comment]
#5653 was not against 1.5.0/1.5.0-doc either, so this doesn't need to be backported that far either.  I sort of meant this "upgrade" of the website to come out along with all the other visual "upgrades" in 2.0.

**Comment by tacaswell** [comment]
I backported it (https://github.com/matplotlib/matplotlib/pull/5653#issuecomment-164648978)

**Comment by mdboom** [comment]
Oh -- sorry for the confusion.  I looked for the file on v1.5.x, but forgot I was looking at a stale checkout.

**Comment by mdboom** [comment]
Backported to v1.5.0-doc as ca5fe3704043

**Pull request merged**
