### PR TITLE
API: shrink default figure size

### PR DESCRIPTION
**Pull request by tacaswell**
downscale the figure size to account for the increase in DPI but keep
the default size of the figure (in pixels) the same.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
:+1: I agree this is the best solution to #5945

**Comment by mdboom** [comment]
:+1: from me, modulo fixing test failures.

**Comment by tacaswell** [comment]
@efiring After this is merged I think your two PRs will 'just work' :tm:

**Comment by tacaswell** [comment]
Bah, this needs to be merged up to master

**Comment by efiring** [comment]
I did that. 1c279847

**Comment by efiring** [comment]
@tacaswell, sorry, I intended to note the merge to master immediately after doing it, but evidently I got distracted.

**Pull request merged**
