### PR TITLE
Fix fill_between with decreasing data

### LINKED ISSUE #9235: Incorrect fill_betweenx interpolation
This sample:
```python
import matplotlib.pyplot as plt
import numpy as np

p = np.array([724.3, 700, 655])
t = np.array([9.4, 7, 2.2])
prof = np.array([7.9, 6.6, 3.8])

fig = plt.figure(figsize=(9, 9))
ax = fig.add_subplot(1, 1, 1)

ax.plot(t, p, 'tab:red')
ax.plot(prof, p, 'k')

ax.fill_betweenx(p, t, prof, where=prof<t,
                            facecolor='blue', interpolate=True, alpha=0.4)
ax.fill_betweenx(p, t, prof, where=prof>t,
                            facecolor='red', interpolate=True, alpha=0.4)

ax.set_xlim(0, 30)
ax.set_ylim(800, 600)
```
is producing incorrect results on 2.1rc:

fill_between

### PR DESCRIPTION
**Pull request by dopplershift**
One of the calls to interp passes data which is not guaranteed to be in
increasing order, which interp requires. Just use argsort the data, like
is done above.

Fixes #9235.

@tacaswell This fixes a bug in a new feature for 2.1--I'd love to see this go in before you cut if possible. 😁

### CODE REVIEW

**Comment by dopplershift** [comment]
On master I think I'm going to refactor the fill_betweens...there's too much duplicated code between them.

**Comment by WeatherGod** [comment]
don't forget to mark the svg file as binary.

Also, as a side note: there is an outstanding bug (not filed) where one of the fill functions respects cyclers properly, but the others don't. I came across it during my prep for my tutorial, but never got around to fixing it.

**Comment by dopplershift** [comment]
The SVG binary stuff was a wildcard, so I don't need to do anything, but it's only on master.

I'll keep an eye out for the cycler stuff when I work on refactoring them.

**Comment by dopplershift** [comment]
Rebased on current v2.1.x branch and fixed up test to make sure it uses mpl20 style.

**Pull request merged**
