### PR TITLE
DOC: don't make CL tutorial save new file all the time

### LINKED ISSUE #12677: DOC: CL tutorial now saves png each time...
_Originally posted by @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/pull/12394#issuecomment-434404280_

It seems one drawback of this is that now every time you build the docs it'll create two png images in the tutorials folder, which will then end up in any commit (if one doesn't pay attention).

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #12677:

Generates the files during build and copies them into `_static` instead of making them part of the repo.  Use `.gitignore` to ignore local copies (in case some one does `git add doc/_static`)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This worked fine.  Now the file won't be generated each time.  OTOH, if we change CL we will have to remember to regenerate it.

**Comment by timhoffm** [comment]
Can't you instead simply add the generated files to  `.gitignore`? AFAIK this does not affect the already commited version.

Advantages:
- It's simpler to update because the files are always generated. Otherwise you'd have to copy the code and run it somewhere.
- One might even add a script to automatically check if the generated image is still matching the one in the repository.

**Comment by jklymak** [comment]
For some reason the files don't regenerate in the same spot if I just remove them from the repo. Any idea what the new static link should be?

**Comment by jklymak** [comment]
i.e. the link `/_static/constrained_layout/CL02.png` is invalid.

**Comment by jklymak** [comment]
Thanks for suggestion @timhoffm - it was a struggle, but I finally got it to work...

**Comment by jklymak** [comment]
Well the sphinx folks said we should write a png "scraper" to copy the file over, and get it included in the written rst.  If it is a useful feature elsewhere, I'm happy to implement it.  It didn't seem that hard, and basically is what you suggest here...

**Comment by timhoffm** [comment]
Working for now. If there is interest in writing a scrapper, that can always be done later.

**Pull request merged**
