### PR TITLE
Initial HiDPI support for qt5agg backend

### PR DESCRIPTION
**Pull request by piannucci**
Here's what needs to be done to get HiDPI support working with qt5agg.  Not sure if you want to do it this way or some other way.

### CODE REVIEW

**Comment by tacaswell** [comment]
The changes in `qt5_backend.py` seem un-related?

**Comment by mretegan** [comment]
On OSX 10.11 I get the following error: 
  ```
File "/Users/marius/Library/Python/3.5/lib/python/site-packages/matplotlib/backends/backend_qt5.py", line 253, in mouseEventCoords
    x,y = self.mouseEventCoords(pos)
RecursionError: maximum recursion depth exceeded
```

**Comment by piannucci** [comment]
Whoops.  I typo'd that pretty badly when building the commit.  The changes in the two files are related: if the dpi_ratio is not 1, then mouse events need to be mapped between device and pixel coordinates in order for the rest of the event stack to behave correctly.

**Comment by fariza** [comment]
Can this be done in a more general way? something that will be useful for all backends?

What about adding a `FigureCanvasBase.get_device_pixel_ratio` or something like that (returns 1 by default).
And the basic multiplication done in the `FigureCanvasBase.xxxEvent` instead that in the specific backend?

**Comment by astrofrog** [comment]
It would be great to get a fix in for this, even if it is not a solution that is applicable to all backends. Currently for [glue](http://glueviz.org/en/stable/), everything looks nice and crisp, except the Matplotlib canvas, which looks pixellated (on a retina display).

**Comment by adrn** [comment]
Any progress on this? @astrofrog are you using the MacOSX backend in the meantime?

**Comment by tacaswell** [comment]
@adrn This seems to have stalled.  Can you test if this

**Comment by tacaswell** [comment]
Sorry for partial message (UI fail: start typing, decide to 'powercycle' to re-trigger CI, close and post partial message)

@adrn Can you test if this works for qt5 + hidpi?

I could be convinced that this should be backported for 2.0 if it gets done in the next week or so.

**Comment by mretegan** [comment]
@adrn For applications that embed the Matplotlib window, the MacOSX backend is not an option.

The only standing issue with this is dpi used in the figure; it is still the default 100, even for Retina display. Maybe this should be scaled by devicePixelRatio? Other than that everything looks really nice and crisp. A print screen of a small app that uses the backend and the [code](https://gist.github.com/mretegan/cd3d458b3fbaabec26a00887c0b5e702) used to make it. It would be really nice to have this in v2.0.

retina

**Comment by jenshnielsen** [comment]
I think we should push for getting this into 2.0. I will see what I can do

**Comment by adrn** [comment]
@tacaswell I'll also take a look at this today.

**Comment by tacaswell** [comment]
@adrn Can you coordinate with @jenshnielsen ?

**Comment by jenshnielsen** [comment]
@adrn if you have time to work on it that is much appreciated, I will then make sure it is reviewed and merged.

**Comment by adrn** [comment]
@jenshnielsen Will try -- I'm at [astrohackweek](http://astrohackweek.org) and will likely spend some hack time on this.

**Comment by jenshnielsen** [comment]
Great if you need any assistance please just ask

**Comment by adrn** [comment]
Alright here's what I see. I compares (this PR + qt5agg) and (this PR + tkagg) using this code:

```python
import numpy as np
import matplotlib as mpl
# mpl.rcParams['backend'] = 'tkagg'
# mpl.rcParams['backend'] = 'qt5agg'
import matplotlib.pyplot as plt

with plt.style.context('classic'):
    x = np.random.normal(size=128)
    y = np.random.normal(size=128)

    plt.scatter(x, y)
    plt.show()
```
qt5agg

tkagg

So it looks like the fix here works, but the fonts, markers, ticks, etc. need to be scaled by the pixel ratio?

**Comment by tacaswell** [comment]
I think you just need to up the DPI passed to the renderer?

**Comment by jenshnielsen** [comment]
https://github.com/matplotlib/matplotlib/pull/5383 which adds hidpi support to the notebook backend may give you some clues on how to do that.

**Comment by QuLogic** [comment]
Finished in #7507.

**Pull request closed without merging**
