### PR TITLE
Add simple ax.arrow test

### PR DESCRIPTION
**Pull request by dstansby**
Currently `ax.arrow` is not tested at all!

This adds a simple test, which should help catch anything backwards-incompatible changed as arrow plotting is overhauled.

### CODE REVIEW

**Comment by anntzer** [comment]
Perhaps you can squeeze in tests for a few more kwargs too?

**Comment by dstansby** [comment]
Okay, this is a bit more complicated now, but gives `ax.arrow` a good workout! Please don't merge before #8452

**Comment by tacaswell** [comment]
powercycled to re-run the tests

**Comment by tacaswell** [comment]
backported to v2.0.x as 46247c7d7

**Pull request merged**
