### PR TITLE
Ensure TwoSlopeNorm always has two slopes

### PR DESCRIPTION
**Pull request by dstansby**
## PR Summary
Fixes https://github.com/matplotlib/matplotlib/issues/24283.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by jklymak** [comment]
Wouldn't it be better to just error out here?

**Comment by dstansby** [comment]
Given this is in the autoscaling part (the user hasn't explicitly requested a vmin/vmax, I'd say it's better to choose some sensible vmin/vmax and give the user some sort of plot - if they want to change the vmin/vmax that's at least a starting point to go from.

**Comment by tacaswell** [comment]
This needs atleast a whats new and maybe a behavior change note.

**Comment by jklymak** [comment]
This seems good to me after a bit of documentation.  Ping for a review if it gets buried

**Comment by dstansby** [comment]
Added a behaviour change note as I didn't think this warranted a what's new - happy to add or move to what's new though if anyone disagrees.

**Review by jklymak — APPROVED** [review]
This looks good to me.  Thanks, and sorry for misunderstanding the intention.

**Comment by tacaswell** [comment]
Restarted the failed job, looked unrelated (a subprocess call for blitting with tk).

**Review by tacaswell — APPROVED** [review]
Anyone can merge on green.

**Pull request merged**
