### PR TITLE
Simplify azure setup.

### PR DESCRIPTION
**Pull request by anntzer**
One can keep everything in a single file by dispatching based on the OS,
rather than splitting the build over two different files.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by NelleV** [comment]
There's a conflict. Can you merge or rebase?

**Comment by anntzer** [comment]
rebased

**Comment by anntzer** [comment]
rebased to retrigger ci

**Comment by timhoffm** [comment]
@meeseeksdev backport to v3.2.x

**Pull request merged**
