### PR TITLE
Change done

### PR DESCRIPTION
**Pull request by soma2000-lang**
## PR Summary

#22584 

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by soma2000-lang** [comment]
@kolibril13 Please look into this

**Comment by kolibril13** [comment]
@soma2000-lang : Thanks for your pull request, but I can not see the changes that you've made. (https://github.com/matplotlib/matplotlib/pull/22600/files)
Maybe something went wrong when you pushed the changes to your branch?

**Comment by soma2000-lang** [comment]
Yes I am trying to fix that

**Comment by kolibril13** [comment]
@soma2000-lang : Are you still planning to work on this? In case that you have some questions feel free to ask them :)
 In case that you don't want to work on this anymore, I  recommend that you could close this pull request.

**Comment by tacaswell** [comment]
@soma2000-lang I am going to close this as it is has been idle for a month with only whitespace changes.  If you want to continue working on this either push more commits and re-open this PR or open a new one with an updated branch.

Thank you for your effort and we hope to hear from you in the future.

**Pull request closed without merging**
