### PR TITLE
Mask invalid values by default when setting log scale

### PR DESCRIPTION
**Pull request by dstansby**
This supersedes #8056 and #8537. See especially #8537 for previous discussion.

This should fix a few bugs: #8045, #8783

### CODE REVIEW

**Comment by tacaswell** [comment]
On the bright side our test suite catches the API change!

**Comment by dstansby** [comment]
I'm completely baffled by the travis failure on the .svg figure. I can't reproduce it on OSX or Linux (Python 3.6.1, Inkscape 0.92.1). Might it be because travis is using version `inkscape_0.48.4-3ubuntu2`?

**Comment by dstansby** [comment]
Close, but no cigar. Force installing the latest stable build of Inkscape gives an error of 0.001 vs. 0.044 for the default version. Perhaps this is going to need a custom tolerance on the image comparison?

https://travis-ci.org/dstansby/matplotlib/jobs/250114851#L3193 is a branch with latest stable Inkscape

**Comment by tacaswell** [comment]
Can you re-generate the svg and add it to the patch.  A while ago we changed how the number is the SVG output were encoded which resulted in similar inkscape version dependent failures.  

A feature of the vector outputs is that different text can result in the same image (which is why we test on comparing the rasterizations not the text), but it can lead to small issues like this.

**Comment by dstansby** [comment]
🎊

**Pull request merged**
