### PR TITLE
Draw RadioButtons using scatter to ensure circular buttons.

### LINKED ISSUE #24428: [Bug]: RadioButtons should be circular, not elliptic
### Bug summary

RadioButtons are drawn as Circles in transAxes space, which means that as soon as the containing Axes is not equal-aspect, they will actually be elliptical, not circular.
In order to fix this, either the parent axes must be forced to be equal-aspect (we already remove the ticks and the navigatability, so more configuration *may* be OK), or we should use add functionality to Circle so that the center and the radius can be in different transform systems (center in transAxes, radius in pixels) -- or abuse scatter() instead to draw the radiobuttons (but this would break the `radiobuttons.circles` attribute).

### Code for reproduction

```python
https://matplotlib.org/stable/gallery/widgets/radio_buttons.html
and make the window much wider than tall
```

### Actual outcome

radio buttons are elliptical

### Expected outcome

radio buttons stay circular

### Additional information

_No response_

### Operating system

fedora37

### Matplotlib Version

3.7.0.dev619+g3d6c3da884

### Matplotlib Backend

any

### Python version

3.10

### Jupyter version

ENOSUCHLIB

### Installation

git checkout

### PR DESCRIPTION
**Pull request by anntzer**
To ensure backcompat without bothering the majority of users who don't actually access the .circles attribute, dynamically (and irreversibly) switch back to the old draw method (list of Circles) whenever that attribute is accessed for the first time (if ever).

https://matplotlib.org/stable/gallery/widgets/radio_buttons.html now looks like
test
Note that the buttons are now circular.

Closes #24428.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by timhoffm — APPROVED** [review]
The fallback is very clever :+1:.

**Review by ksunden — APPROVED** [review]

**Comment by drammock** [comment]
What is the recommendation for those of us (MNE-Python) who *do* access the `.circles` property?  AFAICT from the diff there isn't an alternative in the public API of `RadioButtons` after this PR (but maybe I'm not looking carefully enough?)

**Comment by QuLogic** [comment]
If I've understood what that code does, it appears that you set a radius so that the buttons are reasonably sized. And the second thing is setting specific edge colours for each radio? I think the former is something we should just do, and the latter (styling options) is a reasonable enhancement request if you want to open an issue?

**Comment by drammock** [comment]
> If I've understood what that code does, it appears that you set a radius so that the buttons are reasonably sized. And the second thing is setting specific edge colours for each radio? I think the former is something we should just do, and the latter (styling options) is a reasonable enhancement request if you want to open an issue?

Another thing we do is apply transforms to ensure buttons are circular. That part should go be able to be removed after this PR, but we'll still want to be able to set size and linewidth (on all buttons uniformly) and set color, edgecolor, and opacity (on each button individually). I've opened #24583 for the feature request.

**Pull request merged**
