### PR TITLE
BLD: try to limit what coveralls looks at

### PR DESCRIPTION
**Pull request by phobson**

### CODE REVIEW

**Comment by QuLogic** [comment]
Neither of the sample Python projects from coveralls use this other file; are you sure it's necessary?

**Comment by phobson** [comment]
Perhaps it's not. I picked up the practice from the statsmodels repo, but that dates back to 2013. 

xarray uses just a plain `.coveragerc` with coveralls and started doing so early last year.

**Comment by jenshnielsen** [comment]
I don't think the coverage has ever looked at the examples. The coverage in #6522 does not fail due to the change in your example but because it thinks a line has dropped coverage in colors.py I think it gets confused about which branch to compare against so we can just ignore it.

**Comment by phobson** [comment]
I don't think this PR accomplished what I thought it did and even it if did, it wouldn't be necessary.

closing it.

**Pull request closed without merging**
