### PR TITLE
Fix scatter3d color/linewidth re-projection

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Technically, it's tested, though the test wasn't strictly designed to do so (#18156). Not sure if I should write a different test.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [n/a] New features are documented, with examples if plot related
- [n/a] Documentation is sphinx and numpydoc compliant
- [n/a] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [n/a] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
> Technically, it's tested, though the test wasn't strictly designed to do so (#18156). Not sure if I should write a different test.

How can this have been tested?  The behavior was broken and is now fixed, but you did not have to change anything in the tests.

**Comment by dopplershift** [comment]
That lines up with where codecov says exactly 0% of the lines of code touched in this PR have been executed by the test suite.

**Comment by QuLogic** [comment]
Sorry, I guess what is tested is the _opposite_ case. I can write up something that should cover everything.

**Comment by QuLogic** [comment]
I pushed a more extensive test, and also found that linewidth was not correctly propagated, so fixed that as well.

There's still a bug in #18287 in that initial draw is not correct, but any change in the view angle re-calculates stuff so it appears correctly. I think there's some stale trigger missing in `view_init`, but need to investigate that for a bit.

**Comment by QuLogic** [comment]
I'm very confused about this initial draw thing. To be clear, this PR does fix the sorting, which you can confirm by running #18287, and then rotating the view of the first figure so that the markers's depths are reversed.

However, on the second figure, the face colours of the scatter markers are not sorted, though the edge colours are. Inserting a `draw` (of any kind, lazy or forced) just before `plt.show()` magically fixes it. As far as I can tell, `Path3DCollection.do_3d_projection` sorts everything exactly the same way on both draws, but somehow it doesn't reflect that in the result.

**Comment by tacaswell** [comment]
I'm happy to merge this as-is without tracking down why the initial draw is wrong (which is not to say that isn't a bug that needs to be fixed).

**Pull request merged**
