### PR TITLE
Fixed #17970 - Docstrings should not accessed with -OO

### LINKED ISSUE #17970: AttributeError when using PYTHONOPTIMIZE (due to stripped docstring)
### Bug report

As I was investigating why the scikit-image CI build using `PYTHONOPTIMIZE=2` was failing, I identified the following problem:
when using `export PYTHONOPTIMIZE=2`, the following code results in an AttributeError

```python
In [1]: from mpl_toolkits.axes_grid1 import make_axes_locatable                                                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2bee72614a62> in <module>
----> 1 from mpl_toolkits.axes_grid1 import make_axes_locatable

~/sandbox/venv_mpl/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/__init__.py in <module>
----> 1 from . import axes_size as Size
      2 from .axes_divider import Divider, SubplotDivider, make_axes_locatable
      3 from .axes_grid import Grid, ImageGrid, AxesGrid
      4 
      5 from .parasite_axes import host_subplot, host_axes

~/sandbox/venv_mpl/lib/python3.7/site-packages/mpl_toolkits/axes_grid1/axes_size.py in <module>
     13 
     14 from matplotlib import cbook
---> 15 from matplotlib.axes import Axes
     16 
     17 

~/sandbox/venv_mpl/lib/python3.7/site-packages/matplotlib/axes/__init__.py in <module>
----> 1 from ._subplots import *
      2 from ._axes import *

~/sandbox/venv_mpl/lib/python3.7/site-packages/matplotlib/axes/_subplots.py in <module>
      4 from matplotlib import cbook, docstring
      5 import matplotlib.artist as martist
----> 6 from matplotlib.axes._axes import Axes
      7 from matplotlib.gridspec import GridSpec, SubplotSpec
      8 import matplotlib._layoutbox as layoutbox

~/sandbox/venv_mpl/lib/python3.7/site-packages/matplotlib/axes/_axes.py in <module>
     69 
     70 
---> 71 class Axes(_AxesBase):
     72     """
     73     The `Axes` contains most of the figure elements: `~.axis.Axis`,

~/sandbox/venv_mpl/lib/python3.7/site-packages/matplotlib/axes/_axes.py in Axes()
   5303             where=where, interpolate=interpolate, step=step, **kwargs)
   5304 
-> 5305     fill_between.__doc__ = _fill_between_x_or_y.__doc__.format(
   5306         dir="horizontal", ind="x", dep="y")
   5307     fill_between = _preprocess_data(

AttributeError: 'NoneType' object has no attribute 'format'
```

using matplotlib 3.3.0 in a fresh environment.

The reason is that docstrings are stripped from the code when using `PYTHONOPTIMIZE` with 1 or 2, hence  `fill_between.__doc__ ` is None. One solution could be to put this line in a try/except block.

### PR DESCRIPTION
**Pull request by linchiwei123**
## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This will need comments or next code clean someone will remove it.   I guess there is no way to test this.  

@anntzer I think you put the original code in

**Comment by tacaswell** [comment]
Can we make one of our CI jobs run with -OO ?

It might be worth adding a travs job that makes sure every module (except for the GUI backends) is importable?

**Comment by anntzer** [comment]
looks fine to me, agree that testing is necessary to avoid breakage (but doesn't have to be done as part of this pr).

**Comment by QuLogic** [comment]
It's already multi-line; that would make it even more multi-line.

**Comment by QuLogic** [comment]
Thanks @linchiwei123!

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.3.x

**Pull request merged**
