### PR TITLE
FIX: remove unused variable

### PR DESCRIPTION
**Pull request by keszybz**

### CODE REVIEW

**Comment by keszybz** [comment]
@NelleV

**Comment by NelleV** [comment]
LGTM :+1: for merging.

**Comment by tacaswell** [comment]
For the record, the code that used this variable was removed in f60aa887dc2e1698bde6d9009f6a79d364f4a034

**Comment by tacaswell** [comment]
Can who ever merges this please make sure the note in my last comment makes it in to the merge commit message?

**Comment by keszybz** [comment]
Repushed with amended commit message.

**Comment by NelleV** [comment]
@tacaswell I think this is ready for merge (I can't merge myself anymore).
The appveyor's build failure seems unrelated.

**Pull request merged**
