### PR TITLE
figure.legend can be called without arguments

### PR DESCRIPTION
**Pull request by sinhrks**
figure.legend() can be called without arguments. 

In this case, figure legend artists will be created from all the contained axes legend handles and labels in the figure. The figure legend will merge handles if its label is identical, assuming that the same handlers is assigned to the same label names in subplots.

### CODE REVIEW

**Comment by tacaswell** [comment]
@sinhrks Are you still interested in working on this?

**Comment by tacaswell** [comment]
@sinhrks This needs a rebase.

Does it make sense to group artist by label?  It might be worth getting the simpler change (making the API match that of `ax.legend`) in and doing the smarter grouping in a second pass?

**Comment by dstansby** [comment]
Since it's been over 2 years since last contact, I'll pick this up. Merged and rebased onto my own branch, just getting tests to run etc. and I'll open a new PR when ready.

**Comment by NelleV** [comment]
I am closing this in favor of #7811

**Pull request closed without merging**
