### PR TITLE
Solution for 16631

### PR DESCRIPTION
**Pull request by Wlodarski**
## PR Summary

Solution for issue #16631

### CODE REVIEW

**Comment by Wlodarski** [comment]
Two weeks without any manifestation of interest. Closing.

**Comment by tacaswell** [comment]
The tests are still not passing and none of the issues brought up in #16631 (the need to document the API changes, an attempt to move to the simpler fix, or a clear argument as to why IndexFormatter should not be deprecated).  From my point of view we have been waiting on you.

**Comment by WeatherGod** [comment]
It would also have helped if the issue title and description had more
information. I certainly could not tell what this PR was for just by
looking at this among all of the other PRs and issues.

**Comment by Wlodarski** [comment]
> The tests are still not passing

I will repeat for the last time : THE TEST REQUIRES THE BUG TO BE PRESENT.

The bug manifests itself by outputting ``Label 0`` for -1 < indexes < 0 instead of outputting an empty string ``""``. 

The test is passed when the bug is present, that is when``Label 0`` is wrongly outputted. 
The test fails when the bug is NOT present, that is when ``IndexFormatter``  returns an empty string, ``""``, AS IT SHOULD.

The solution --- which consists only of rounding the index value, ``round(i)``  instead of truncating the index value, ``int(i + 0.5)`` --- returns an empty string, ``""``.  The solution fails the test because the test is WRONG. The test is by itself A BUG.

> From my point of view we have been waiting on you.

I CANNOT CORRECT THE TEST. IT'S YOUR RESPONSIBILITY AND PREROGATIVE.

> the need to document the API changes

If you adopt the solution, THERE NO NEED TO CHANGE THE DOCUMENTATION NOR THE API

> why IndexFormatter should not be deprecated)

Because, WITH THE SOLUTION instead a deprecation :

1. IndexFormatter works. It simply works, as intended, without any bug.
2. ``IndexFormatter(x_labels)`` is far simpler than proposed convoluted alternatives like ``FuncFormatter(lambda x, _: dict(zip(range(len(x_labels)), x_labels)).get(x, ""))`` to achieve the same exact end result.
3. The solution doesn't break back compatibility in the middle of minor revision. The users don't have to change their programs. They don't have to find an alternative. 
4. It follows the precepts of semantic versioning instead of adopting post hoc rationalisations (like "others deprecated functionalities in the middle of minor revision so lets pretend it's okay for us to do the same")
5. You don't have to spend time and energy changing the documentation. You don't have to teach the users alternative methods that are necessarily harder to implement and explain.
6. Apparently, the DEPRECATION is based, at least partially, on the false assumption that a decade of zero complaints from the users somehow means the users are unhappy with IndexFormatter and therefore don't use it. 
7. THE DEPRECATION misses entirely the point of avoiding the vicious cycle of complexity. Increasing complexity to achieving the same exact functionality is a huge waste of your time. It only make you busier and busier, writing more convoluted code and spending more time managing harder to debug bugs.

I have wasted enough of my time trying to convince you. So be it.

**Comment by ksunden** [comment]
@Wlodarski 

Saying that it is the responsibility of the person proposing a change to make the tests pass does _not_ mean that the new behavior cannot be adopted. You can fix the test to match desired behavior, and that is still the perogative of the implementor.

That said, changing the test is a _strong_ indicator that the API _has_ changed. You may see it as minor, you may see it as correcting to expected behavior. Nonetheless it is changed, which should be documented in accordance with the projects goals.

I am not speaking as representative of Matplotlib, only as a member of the broader open source community.

You seem to be focussing on your particular use case, and I don't blame you. You found something you thought unexpected, and found a rather simple fix for it. I applaud you for being willing to dive into a complicated codebase and find that solution.

That said, please acknowledge that the maintainers are acting in good faith here, that they are considering what you have pointed to, but are also looking out for the best interests of the userbase as a whole. You may disagree with them, and that's fair. But being silent for two weeks, then getting angry when they point to unresolved discussion points is not a productive disagreement.

The matplotlib project, being so core to how so many other people do their work, has very stringent expectations when it comes to behavioral changes, even small ones, by design, while balancing the desire to move forward, add features, clean up code, etc. And for future reference, two weeks is an extremely short time in open source software. Most of the people here are volunteers, working on their own free time. I myself have had PRs open for months (including one active one in this project) that have ultimately lead to being merged.

@tacaswell @WeatherGod Thank you for all that you do for the project.

**Comment by tacaswell** [comment]
@Wlodarski We expect everyone to engage in a professional manner consistent with the PSF code of conduct (https://www.python.org/psf/conduct/).  I do not think your comments in this thread (or in #16631) reach that bar, please be more considerate of your words in the future.

I am going to close and lock this thread as I do not think this discussion will be productive if continued here.  If anyone wants to pick up this work please open a new PR where we can start fresh.

-----

@ksunden Thank you for your kind and considered words :)

**Pull request closed without merging**
