### PR TITLE
Cairo rendering for Qt5

### LINKED ISSUE #8618: pyside2 as qt5 backend
### Bug report

**Bug summary**
using Pyside2 as a qt5 backend is failing

**Code for reproduction**
```python
import matplotlib; matplotlib.use('Qt5Agg'); matplotlib.rcParams['backend.qt5']='PySide2'
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
```

**Actual outcome**
```python
    fig, ax = plt.subplots()
  File "<...>/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1189, in subplots
    fig = figure(**fig_kw)
  File "<...>/lib/python3.6/site-packages/matplotlib/pyplot.py", line 544, in figure
    **kwargs)
  File "<...>/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "<...>/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "<...>/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 246, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "<...>/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 68, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "<...>/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 246, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)
AttributeError: 'figure()' is not a Qt property or a signal
```

**Matplotlib version**

  * Operating System: Ubuntu 17.04
  * Matplotlib Version: f1072075db6615954cac2ff0fa44c4d6c7764a23 (latest commit on master)
  * Python Version: 3.6.1
  * Other Libraries: Qt 5.8.0 + Pyside2

what can I do ?

### PR DESCRIPTION
**Pull request by anntzer**
This PR implements a cairo based renderer for Qt canvas, under the name "Qt4Cairo"/"Qt5Cairo".  Test e.g. by setting the MPLBACKEND environment variable to `qt4cairo`/`qt5cairo`.

> The quoted text below is no longer relevant (the corresponding PRs have been merged).

> The first three commits include a number of cleanups to specific backends code, some of them related to the issue at hand and some of them not so much.  They are also the object of a separate PR (#8772), that may be merged first (and independently) to simplify review.

> The fourth commit ("backend class to factor out common code") implements a class-based approach to define the various functions needed by a backend module, in order to remove large chunks of copy-pasted code.  It does not modify the public API though.  Likewise, it is the object of a separate PR (#8773) that may be merged second to simplify review.

The following commits implement the Qt5Cairo backend, then the Qt4Cairo backend, and redistributes relevant code chunks between the various `backend_qt*` modules in order to maximize code reuse, and then update the docs.  I would suggest restricting comments for this PR to the diff of these last commits.

> As a side effect of the refactoring of the Qt canvas classes, this also closes #8618 (PySide2 support).

Note that because of the way the cairo backend is currently written, all the drawing occurs during the Qt draw event, instead of being buffered before it as in Agg.  The third party mplcairo backend works around this limitation, but this PR is still useful to cleanly separate the windowing and rendering parts of the code.

## PR Checklist

- [X] Has Pytest style unit tests
    -> see test_backends_interactive.py
- [X] Code is PEP 8 compliant
- [X] New features are documented, with examples if plot related
- [X] Documentation is sphinx and numpydoc compliant
- [X] Added an entry to doc/users/whats_new.rst if major new feature
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I rebased this (as needed) after #8931 was merged, but as I have no mixed-dpi setup for testing it would be nice if someone could confirm I did not break the mixed dpi handling.

**Comment by matthew-brett** [comment]
Worth rewriting main text above now #8772 is merged?

**Comment by anntzer** [comment]
Done.  Looks like there are some issues with the tests pointed out in https://github.com/matplotlib/matplotlib/pull/8931#pullrequestreview-53734488 so I'll (at least) wait until they are resolved before getting back to this.

**Comment by tacaswell** [comment]
attn @maartenbreddels

**Comment by anntzer** [comment]
rebased

**Comment by anntzer** [comment]
@maartenbreddels If you want to use cairo with matplotlib I would suggest having a look at https://github.com/anntzer/mpl_cairo -- the backend currently shipped by matplotlib has a number of issues that are hard to fix, so I just rewrote the whole thing :-)

**Comment by jklymak** [comment]
This seems to have an issue on Macs; seems a retina issue...  Maximizing the window makes the window bigger but the rendering is still off by a factor of two.


```python
import matplotlib
matplotlib.use('Qt5Cairo')
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
plt.show()
```

figure_1

**Comment by anntzer** [comment]
I don't have access to a high DPI screen, but I tried using QT_SCALE_FACTOR (as in #7507) and I can't see a difference between applying the patch or not.
So I would definitely appreciate help from a Mac user :-)

**Comment by jklymak** [comment]
Happy to help.  Can you push a candidate version that I can checkout?  

I'd actually offer the use of a machine via VNC, but our school clamped down on VNC ports :-(

**Comment by anntzer** [comment]
I think it's going to be much easier if I have access to a machine (I don't have a strong guess as to where the fix is needed).  I can sometimes borrow one from a colleague, but that may take a while.

**Comment by anntzer** [comment]
@jklymak I think the hi-dpi issue is fixed now (turns out it wasn't that bad).  Please give it a try (hi-dpi and vnc also interact in non-trivial fashion, so it'd be nice if you can confirm without passing through vnc), and thanks for giving me access!

**Comment by jklymak** [comment]
Retina issue seems fine to me on a local machine w/ the test above.   Was there more thorough tests I can help w/?

**Comment by anntzer** [comment]
I think that's basically all.

**Comment by anntzer** [comment]
I would really appreciate if this could make it in 2.2 because it is more or less a prerequisite for me to make a first release of mplcairo (i.e. with a working GUI backend).  So labeling it as such, but feel free to retag if you think this is too hard.

**Comment by jklymak** [comment]
@anntzer I'd be OK w/ it if it were more self contained.  What are good tests that the changes in `backend_qt5`, `backend_qt5agg` etc don't have bad knock-on effects?  Is the test suite adequate for this?  

I agree it would be very nice to see this in for 2.2.  It seems that cairo is a great way forward, particularly as it can be used to drive openGL if I understand correctly.

**Comment by anntzer** [comment]
Splitting out the nonessential parts...

**Comment by anntzer** [comment]
Superseded by #10210.

**Pull request closed without merging**
