### PR TITLE
Fix new leak in ft2font introduced in #22604

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

As noted at https://github.com/matplotlib/matplotlib/pull/22604#discussion_r821118057

## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by anntzer — APPROVED** [review]

**Comment by oscargus** [comment]
Is there a link to info about this? It seemed like the right thing to do. Not that I doubt you, but a bit surprising.

**Comment by QuLogic** [comment]
`PyLong_FromSsize_t` returns a [new reference](https://docs.python.org/3/c-api/long.html#c.PyLong_FromSsize_t).

**Review by oscargus — APPROVED** [review]

**Comment by oscargus** [comment]
Thanks! And sorry about that!

**Comment by tacaswell** [comment]
@oscargus I merged it so you are not alone in this!

I think a key to maintaining a healthy developer community is that people feel safe to make mistakes.  While obviously we should never _try_ to break things and strive to get things right the first time, everyone makes mistakes and that is OK.

**Pull request merged**
