### PR TITLE
MNT: deprecate patches.YAArrow

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

So far as I can see 

https://github.com/matplotlib/matplotlib/blob/4d1ca36d64af1c0a53b6eceb8292144715ebef3e/lib/matplotlib/patches.py#L1275

 is not ever called or documented (except in the API).  Maybe there is a huge fan base out there, but...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
Careful, I don't think `FancyArrow` can be a replacement for that. Possibly `FancyArrowPatch` can be, but better check first. If not, better not to state any *alternative*  at all than a wrong one. The point being that  FancyArrow seems to live completely in data space (or whatever coordinate system you want) while YAArrow has a transform associated with it.

**Comment by jklymak** [comment]
Ooops, I meant `FancyArrowPatch`. 

I don't know that its a direct replacement, and I don't think stating an alternative necessarily means it is.  It just means thats where the user can go to get the same functionality...

**Comment by ImportanceOfBeingErnest** [comment]
Relevant: https://github.com/matplotlib/matplotlib/wiki/MEP-29-(arrows) (Not to have this reference getting lost.)

**Comment by afvincent** [comment]
Pinging @dstansby who recently did some work about an overhaul about arrow overhaul if I remember correctly
Pinging @efiring who did some work on removing YAArrow usage from the codebase (at least in 2015, see for example #4178 and the following [comment](https://github.com/matplotlib/matplotlib/pull/4178#issuecomment-113996738) )

NB: it is more asking for opinions rather than “requesting review” :).

**Comment by jklymak** [comment]
#11219 addresses this via documentation.  I’ll close this though still skeptical this is needed.

**Comment by dstansby** [comment]
Sorry if I confused you @jklymak, I think YAArrow should be deprecated.

**Pull request merged**
