### PR TITLE
Autogenerate footer Copyright year

### LINKED ISSUE #15285: DOC: make copy right year auto-update
The copyright in the footer of the webpage is currently hard-coded, this can probably be set so that the final year is automatically updated.

### PR DESCRIPTION
**Pull request by the-c0d3br34k3r**
## PR Summary
Closes #15285
Instead of hardcoding the Copyright
year, which needs to be changed every year,
it now uses datetime to fetch the current year.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This looks "fine".  Not this PR's fault, so happy to merge as is, but why is our footer off centre?

Untitled 2


Built documentation is here: https://25222-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/index.html

**Comment by jklymak** [comment]
Thanks for your first PR!

**Comment by the-c0d3br34k3r** [comment]
@jklymak Thank you.
Btw, for the footer alignment issue, I think it's because of this:
https://github.com/matplotlib/matplotlib/blob/030157c49a887d0d63780258a57ec86b00f71d4d/doc/_static/mpl.css#L352

**Comment by the-c0d3br34k3r** [comment]
Yup, the footer alignment issue is because of https://github.com/matplotlib/matplotlib/blob/030157c49a887d0d63780258a57ec86b00f71d4d/doc/_static/mpl.css#L352

With
> text-align: right

image

On changing that to 
> text-align: center
it aligns as expected.

image

**Comment by the-c0d3br34k3r** [comment]
@jklymak Looks like you're way faster than me :)
https://github.com/matplotlib/matplotlib/issues/15306

**Comment by timhoffm** [comment]
Footer alignment will be handled via #15306.

@the-c0d3br34k3r Thanks and congratulations on your first contribution to Matplotlib! Maybe see you back some time.

**Pull request merged**
