### PR TITLE
Deprecate ps.useafm for mathtext

### PR DESCRIPTION
**Pull request by jkseppan**
## PR Summary

See #18722 

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by anntzer** [comment]
I don't think we should bother with a deprecation, but straightaway ignore ps.useafm for mathtext?  I see this mostly as a bugfix.

**Comment by jkseppan** [comment]
Someone could be using the feature, e.g. through the feature that renders tick labels as mathtext. I think it would be fair to give them a notice that their plots are going to change in the future.

**Comment by anntzer** [comment]
Fair enough.

**Review by anntzer — APPROVED** [review]
post ci

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
