### PR TITLE
TST: enable caching on travis

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
:+1: Unfortunatly it doesn't work with the Trusty environments in #5730

**Comment by tacaswell** [comment]
how badly does this overlap with what you have been doing (other than trying trusty?)

with ccache + pip cache + wheelhouse it seems to go from boot -> running tests as < 2minutes.

**Comment by jenshnielsen** [comment]
Unfortunately the trusty environment only support caching for paid instances (at the moment?) If this speeds up things significantly I am +0.5 on doing this rather than the trusty environments. The only real gain from trusty at this stage is a more up to date Texlive (2013 vs 2009) which enables us to run the pgf/xelatex tests on Travis. As I said in that PR I wish I knew more about what Travis's long term strategy is.

**Comment by jenshnielsen** [comment]
Can you try adding a `pip install wheel --upgrade` after `pip install --upgrade setuptools` that should enable it to build and cache wheels of numpy on python 3.6 where the wheel is not available on the wheelhouse

**Comment by jenshnielsen** [comment]
I didn't read your comment carefully enough. I have not looked into any more travis work beyond the trusty stuff and silencing some warnings here and there in the tests.

**Comment by tacaswell** [comment]
@jenshnielsen I am inclined to self merge this after this round of travis passes, I want to see how much this helps master.

**Comment by jenshnielsen** [comment]
Feel free to do that and regard this as a review if Travis is green

**Comment by jenshnielsen** [comment]
Looks like installing wheel worked 

```
  Running setup.py bdist_wheel for numpy
  Stored in directory: /home/travis/.cache/pip/wheels/09/99/27/1eae69e0d6be3d744317fe1da672278fe91ab8c15dcced4248
  Running setup.py bdist_wheel for pillow
  Stored in directory: /home/travis/.cache/pip/wheels/4a/50/3d/d5d9f8a46e67a55269632e5d2adc9c04c5254c2d708e9fbe9d
  Running setup.py bdist_wheel for snowballstemmer
  Stored in directory: /home/travis/.cache/pip/wheels/26/52/99/e0eb6b825c16715026ef290c13f4a0fbb86f1a5eab51bb10a0
  Running setup.py bdist_wheel for MarkupSafe
  Stored in directory: /home/travis/.cache/pip/wheels/94/a7/79/f79a998b64c1281cb99fa9bbd33cfc9b8b5775f438218d17a7
Successfully built numpy pillow snowballstemmer MarkupSafe
```

**Comment by jenshnielsen** [comment]
It might be worth rerunning the 3.6 job after this completes before merging to ensure that the caching of wheels works correctly

**Comment by jenshnielsen** [comment]
I retriggered the 3.6 job. Doing bdist_wheel it took "9 min 54 sec"

**Comment by jenshnielsen** [comment]
Doesn't look like any significant difference installing numpy etc takes 25 with and without wheel thanks to ccache but that is still much better than without caching approx 180 sec.

**Comment by mdboom** [comment]
This is cool.  I didn't know Travis had this feature now.

We could probably also include `.cache/matplotlib` not because I would expect any great speedup, but it might help us catch instances where the font cache id needs to be updated.

**Pull request merged**
