### PR TITLE
Post stubtest results to GitHub checks

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Unfortunately, the way that `stubtest` outputs its error messages makes it difficult to post a message on _both_ the `.py` and `.pyi` stub, so we decided to take the full message and post it only on one.

As a test, I have made PR in my repo https://github.com/QuLogic/matplotlib/pull/30 which started from the previously-unfixed #25542, and then I also added a commit with multiple argument mismatches to confirm that `stubtest` didn't output some different format.

Results are at the bottom of https://github.com/QuLogic/matplotlib/pull/30/files

## PR Checklist

**Documentation and Tests**
- [n/a] Has pytest style unit tests (and `pytest` passes)
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] New plotting related features are documented with examples.

**Release Notes**
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [n/a] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by ksunden** [comment]
The case that may need to be looked at a bit is the missing stub case, as that does not have a stub path to parse.

**Comment by ksunden** [comment]
No, just for a new method is what I was thinking

**Comment by QuLogic** [comment]
The `stubtest` output for that case doesn't include a line number, so it doesn't get posted, but the other errors do work fine. I'm not sure if I can get it to fall back to posting on the `.py` or if it would confuse it.

**Comment by QuLogic** [comment]
I also just added an extra function in the stub, but not the Python file, and I see that that doesn't get posted either; it looks like there's a slightly difference in output in that case, which I should be able to cover.

**Comment by QuLogic** [comment]
OK, this is now able to post 1) differences between stubs and runtime; 2) items in stubs but not in runtime. Unfortunately, the case with items in runtime but not stubs cannot be caught, AFAICT.

See https://github.com/QuLogic/matplotlib/pull/30/files

**Comment by QuLogic** [comment]
I opened an issue on stubtest to see if concise error messages could contain a bit more information (linked above). This could simplify this posting process as message would not be multiline.

**Review by oscargus — APPROVED** [review]
Let's try this and see what happens.

**Review by ksunden — APPROVED** [review]

**Pull request merged**
