### PR TITLE
Change the way API changes are documented

### PR DESCRIPTION
**Pull request by dstansby**
Given the pace at which we are making API changes in each new release, the current method of one change/file, then merge just before a release isn't very sustainable. I did the `3.1.0` changes, and I've given up doing the `3.2.0` changes because it's a very boring task. Problems are:

- The merger has to decide how to categorise each change, despite not being involved in most of them
- Each note is written in a different style, which in places has to be fixed
- It takes a **really** long time to merge all the individual files
- It is very easy for individual API change files to get accidentally lost in the merge up to a big file

So I am proposing a change such that all API changes are added at the time the change is made to one of four files (categories up for discussion here):

- Behaviour changes
- Deprecations
- Removals
- Development changes

I know this will involve merge conflicts along the way, but I honestly think it's a hit worth taking to make the ultimate task of putting together a coherent API changes page easier.

### CODE REVIEW

**Comment by anntzer** [comment]
What about https://github.com/matplotlib/matplotlib/pull/14589 (the towncrier PR)? It looks like the necessary upstream PR (https://github.com/hawkowl/towncrier/pull/157) already went in.
Also, given that I'm not the one doing the merging but probably one of those creating the most work there, I'm happy with whatever solution you prefer, including towncrier, even if this requires some changes on my workflow...

**Comment by NelleV** [comment]
@dstanby I think that your proposed workflow would work fine. 
Out of curiosity, how much changes do we have per releases and how are they distributed between the four categories you are proposing?

In terms of writing style, that should be fixed prior to merging the PR. Might be worth adding a note to the reviewing guidelines about that.

**Comment by dstansby** [comment]
@anntzer even though it's merged, it's not released and I don't think towncrier is the most actively developed project.

I think (w/ no real evidence) adding to the same file that already has some changes will help first-timers see what kind of thing to write, and will hopefully reduce the amount of copy editing that needs to be done at release time.

**Comment by dstansby** [comment]
@NelleV Most stuff by quantity is deprecations, but excluding @anntzer's commits(*) I'd say it's fairly well split between the 4 categories.

(*) Not a complaint at all, but he seems to do most of the deprecating ;)

**Comment by tacaswell** [comment]
> I know this will involve merge conflicts along the way,

We used to do it that way and it caused so many re-bases that we moved to the many files.

**Comment by NelleV** [comment]
Could we do a mixture of boths? Split between four categories, but keep several files with a strong naming conventions and structure, and "simply" do a cat before the release?

**Comment by jklymak** [comment]
We discussed this on the weekly call, and there was support for exactly the approach in this PR.  Yes, there will be some rebasing needed, but usually new developers who would be burdened by rebasing are not doing deprecations etc which get hit heavily.  And splitting into four categories lessens the chance of conflicts.

**Comment by dstansby** [comment]
Woops, not sure why I closed this!

**Comment by tacaswell** [comment]
@dstansby What is the state of this?  I think we want to get this enabled for 3.3 ASAP!

**Comment by dstansby** [comment]
Thanks for the nudge, I think modulo getting the docs to build this is almost there. Will try and sort this out in the next couple of days!

**Comment by dstansby** [comment]
I think this is ready now!

**Comment by timhoffm** [comment]
Doc builds complain:

> /home/circleci/project/doc/api/api_changes.rst:40: WARNING: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'api/api_changes/api_changes_3.2.0.rst'.

**Comment by timhoffm** [comment]
There's four API change notes on master so far. I can handle these in one go.

Open PRs will need an update by the respective author.

**Pull request merged**
