### PR TITLE
FIX: re-order symbol and acent in mathtext

### LINKED ISSUE #4462: following mathematic symbols failed in matplotlib.mathtext, version 1.3.1
$\Cup$ $\Cap$ $\dotplus$ $\barwedge$ $\doteq$ $\doteqdot$ $\rightharpoonup$ $\ddots$ $\leftharpoonup$

### PR DESCRIPTION
**Pull request by tacaswell**
Try to find symbols before finding accents

Closes #4462 

attn @mdboom What can of worms have I opened here?

### CODE REVIEW

**Comment by mdboom** [comment]
I suspect this change is fine as long as there are no symbols that are strict prefixes of accents.  (Don't know if that's the case).  Maybe add some tests?  (Clearly it doesn't break existing ones, which is a good thing.)

**Comment by tacaswell** [comment]
@mdboom rebased + tests added

**Comment by tacaswell** [comment]
Ping me if I should merge these tests into one, the idea was to split them up to make bisection easier

**Comment by tacaswell** [comment]
ping @mdboom

**Comment by zblz** [comment]
@tacaswell: In my system this switch messes up the position of the accents. It might be system dependent, but I think my system is common enough that this shouldn't happen (everything from Debian Testing repos except matplotlib master, Python 3.4). Before the fix, accents rendered fine, symbols didn't:
accent_test_mpl_cm_old

After it, accents are shifted to the left:
accent_test_mpl_cm_master

I don't know much about parsers, so I don't really understand how this can happen from a cursory glance at ``mathtext.py``. What other info do you need?

**Comment by tacaswell** [comment]
Well, that is exciting.

**Comment by WeatherGod** [comment]
What is the mathtex string you are using?

**Comment by zblz** [comment]
The top one is from a test, the bottom is the one from issue #4462, and which is in tests as well since this PR:
```
r'$\ddot{o}\acute{e}\grave{e}\hat{O}\breve{\imath}\tilde{n}\vec{q}$'
r'$\Cup \Cap \dotplus \barwedge \doteq \doteqdot \rightharpoonup \ddots \leftharpoonup$'
```
Note as well that the mathtext test for the first one doesn't fail for me: maybe the accents don't have enough area to meet the threshold?

**Comment by WeatherGod** [comment]
re: accents, I bet you are right about that. We probably only test them on
normal size text, and so they aren't big enough to fail.

As for the parsing, what I think is really strange is that the \hat for the
'O' is at the midlevel, rather than raised, and the \breve is at the
midlevel as well. Makes me wonder if they are getting rendered completely
independently of the text they are operating upon?

**Comment by zblz** [comment]
It seems so: instead of being rendered in place and then shifted, it looks
as if the parser parses them independently of their associated character
and renders them before (assuming x-height for the base character?).
El dia 07/08/2015 19:35, "Benjamin Root" <notifications@github.com> va
escriure:

**Comment by tacaswell** [comment]
Turns out this PR breaks the accent parsing, as in it never happens (and the comment in the code was correct).  I am working on fixing this.

@zblz Thanks for catching this before we released!

**Pull request merged**
