### PR TITLE
Add option to gcf/gca to disable new figure/axes creation.

### PR DESCRIPTION
**Pull request by anntzer**
This provides a relatively more user-friendly way to check whether a
current figure/axes exists.  (`_pylab_helpers.Gcf.get_active` is way too
"internal".)

Inspired by #20770.  I'm not particularly wedded to the kwarg name, better suggestions are welcome.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by timhoffm** [comment]
Name should probably be something with "create", e.g. "allow_create" or "create_if_none".

**Comment by anntzer** [comment]
create_if_none it is (for now)

**Review by timhoffm — COMMENTED** [review]
At first I was hesitant to touch `gca()` at all, because it's deeply tied into the pyplot state, and generally I think that's best left in peace.

However, I agree that something has to be done: `gca()` does two things: 1. obtaining the current axes, 2. creating a new one if needed. While the combination is often what people want in pyplot, it's a shortcoming that we cannot easily check whether a current axes exists.

I'm +/-0 on this solution to the problem. I'm hesitant with a `create_if_none` kwarg because `gca()` has a very particular but well established functionality. The `create_if_none` extension is straight forward, but adds a additional functionality that makes understanding `gca()` a bit harder. Before the functionality was really only "Get the current Axes, creating one if necessary." Now, we have to make a distinction in case there is no default Axes.

Please consider an explicit `plt.has_current_axes()` function as an alternative and give your opinion which solution is better.

Side question: For symmetry, should we have a similar behavior for the current figure?

**Comment by jklymak** [comment]
I actually do not understand this PR at all, particularly compared to #20770.  The problem in that issue is that we no longer search the stack for matching kwargs to gca().  I don't see what this PR has to do with that?

**Comment by anntzer** [comment]
@timhoffm `plt.has_current_figure()` is basically the same as `len(plt.get_fignums()) != 0` and `plt.has_current_axes()` would be `len(plt.get_fignums()) and len(gcf().axes)`; IOW the functionality is basically already there, it's just a question of discoverability.  Perhaps we can just add that info to the docstrings instead?

@jklymak I'm specifically adressing the following point in @dstansby's issue:
> The only thing I don't know how to get is a list of pyplot axes (pyplot_axes above).

**Comment by timhoffm** [comment]
I *assume* that people rarely want to know if there is a current axes (otherwise the request should have come more early/often). So maybe we can get by with documenting the snippet and not introduce any new API. OTOH the question may be fundamental enough to warrant a dedicated API one way or the other.

**Comment by jklymak** [comment]
> @jklymak I'm specifically adressing the following point in @dstansby's issue:
> 
> > The only thing I don't know how to get is a list of pyplot axes (pyplot_axes above).

But thats just `fig.axes`, or are you concerned they are not explicitly pyplot axes?  Does that matter?

**Comment by timhoffm** [comment]
> But thats just `fig.axes`, or are you concerned they are not explicitly pyplot axes?  Does that matter? 

The thing is, that from within pyplot, you don't have `fig` a-priori. You have to obtain it via `gcf()` but that in turn could create a figure as a side effect. Therefore, one has to do the `has_axes = len(plt.get_fignums()) and len(gcf().axes)` dance.

**Comment by jklymak** [comment]
Yes, but they want a figure so creating one is fine.

**Comment by timhoffm** [comment]
Yes, but there should be a side-effect free way of checking if an Axes exists.

Ah, that said: `plt.gca()` calls `gcf().gca()`, so as this PR is now `plt.gca(create_if_none=False)` will still create a Figure if needed. That's quite confusing and makes me :-1: on the proposed impelementation.

**Comment by anntzer** [comment]
> plt.gca() calls gcf().gca(), so as this PR is now plt.gca(create_if_none=False) will still create a Figure if needed.

Good catch, now fixed.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/20783 for the "let's just document this" approach.

**Comment by anntzer** [comment]
Closing in favor of #20783 (I think the docs improvement is actually better than expanding the API), though if anyone wants to champion this patch, feel free to pick it up.

**Pull request closed without merging**
