### PR TITLE
update colorbar.py make_axes_gridspec

### PR DESCRIPTION
**Pull request by ShawnChen1996**
## PR Summary
I made a little change so that now the `anchor` argument in `make_axes_gridspec` mimic the behavior of that in `make_axes`.  Now the postion of colorbar is determined by `anchor` and `shrink`, should be very useful when `shrink` < 1.0

The effect is demostrated in the plot below. Now I can place the colorbar at different place with different shrinked size.

```python
import numpy as np
import matplotlib as mpl
import matplotlib,pyplot as plt

x = np.random.randn(100)
y = np.random.randn(100)
fig = plt.figure()
ax = fig.add_subplot()
mappable = ax.scatter(x,y, c=y)
ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), shrink=0.5) 
```
A good figure

Before the change, we can achieve that using `ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), use_gridspec=False) ` , however, this will create a colorbar as a `Axes` not a `Subplot`, when I use `subplots_ajust` to adjust the border margins, I got the following plot.
```python
fig = plt.figure()
ax = fig.add_subplot()
mappable = ax.scatter(x,y, c=y)
ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), shrink=0.5, use_gridspec=False) 
ax.figure.subplots_adjust(bottom=0.1)
```
A bad figure

It seems the colorbar Axes is ignored and my plot is re-placed according to its `panchor` parameter that `make_axes` set. It bothers me when I have multiple plots and wanna adjust the plots  border margins and wspace, hspace.

`gridspec` offers a better approach and is the default setting when creating a colorbar, however, I want the colorbar to be 0.5 size and placed at the bottom right, which is mot implemented.

So this is what I did basically.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks a lot for the PR.  After a quick look this seems feasible and reasonable.  Will probably need some tests, and you have a flake8 error (follow links under Travis CI).  Can you also check that this works w/ `constrained_layout`?

**Comment by ShawnChen1996** [comment]
I have made a another commit, should fix the format error. 
I may need some help on checking the `constrained_layout`

**Comment by jklymak** [comment]
Sorry, I forgot about this.  This is not compatible with `constrained_layout`, but that need not prevent it, and indeed maybe constrained_layout should be fixed to do this.  

This needs tests and a what's new entry, but I don't see any reason why adding this would be a problem.

**Comment by jklymak** [comment]
BTW< don't be shy about pinging for review at a reasonable interval.

**Comment by ShawnChen1996** [comment]
Thank you for pushing this PR forward, this is my 1st time to contribute to matplotlib, thus not very familiar with the procedure. What do I do next? I can see it fails the codecov test.

**Comment by jklymak** [comment]
If you can, it would be nice if you would add some tests, probably in `lib/matplotlib/tests/test_colorbar.py`.  Preferably without using image comparison, which we are trying to avoid.  In this case, you can probably just check that the anchored position of the colorbar is correct without resorting to an image test.

**Comment by ShawnChen1996** [comment]
Sorry for the delay.
I have added test for colorbar postioning.  
Please tell me if there is anything I need to do.
@jklymak

**Comment by jklymak** [comment]
Sorry, this needs a rebase, and the docs should build as well.  Please feel free to ping - I think this is a good addition.

**Comment by jklymak** [comment]
- oh, and this needs at least an update to the docstring for colorbar., but an example would be nice as well...

**Comment by ShawnChen1996** [comment]
I rebased my commits into a branch named  `colorbarGridPostion`, however, I don't know how to change this PR to merge from that branch, is there anyone who can help me?

I will work on the docstring and example very soon.

**Comment by jklymak** [comment]
Since it was just me who has reviewed this so far, why not make things easier on ourselves and just open a new PR...  Its better that you have the commits in a branch other than `master` anyhow.  Thanks...

**Comment by ShawnChen1996** [comment]
new PR done.

Has merge conflicts

**Comment by jklymak** [comment]
Closed in lieu of #18340

**Pull request closed without merging**
