### PR TITLE
MNT: Deprecate FontProperties(pattern)

### PR DESCRIPTION
**Pull request by timhoffm**
... and use `FontProperties.from_pattern()` instead.

`FontProperties(pattern)` was an overloaded API that easily conflicts with `FontProperties(family)`. The parameter was assumed to be a pattern if it was a string and the only parameter.

Noted in https://github.com/matplotlib/matplotlib/pull/28836#pullrequestreview-2313787610.

### CODE REVIEW

**Comment by anntzer** [comment]
See also the item starting with "The FP constructor is a bit a mess..." at #10249, I guess.
Based on the writeup at #10249 I vaguely suspect we should rather deprecate `FP(family)` because that's easily written as `FP(family=family)` (consistently with all other attributes), and if anything the constructor without named parameter should take a pattern (... perhaps a CSS pattern, but that's another issue).

**Comment by timhoffm** [comment]
Sure. We could do `__init__(pattern=None, /, *, family=None, ...)`. Notes:
- We still need an *either pattern or the other parameters* internal check, i.e. we have two orthogonal APIs in the constructor, but at least they are logically separated.
- for the deprecation: can we detect whether a given single parameter is a family rather than a pattern?

**Comment by anntzer** [comment]
> * for the deprecation: can we detect whether a given single parameter is a family rather than a pattern?

In the single-arg case, I would try calling parse_fontconfig_pattern, then if it raises, treat as a family (and warn)  (If it doesn't raise, this can also occur if the family and the pattern are identical, e.g. "Times" parses as {"family": "Times"}.)

**Comment by timhoffm** [comment]
Superseeded by #28843.

**Pull request closed without merging**
