### PR TITLE
Support for shorthand hex colors.

### PR DESCRIPTION
**Pull request by PatrickFeiring**
## PR Summary

Added support for shorthand hex colors as described in section 4.2 of the current CSS Color Module Level 4 Working Draft from 5 March 2019.

Examples:
#&#x2060;123 is interpreted as #&#x2060;112233
#&#x2060;123a is interpreted as #&#x2060;112233aa

It is a minor change, and I did this mainly to match expectations for anyone coming from web design (myself including) and to make tasks like specifying softer blacks like #&#x2060;333 or greys like #&#x2060;ccc quicker.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Looks good to me - could you add a quick note in `/doc/users/next_whats_new` to advertise the new feature?

**Comment by anntzer** [comment]
For reference this is defined at https://www.w3.org/TR/css-color-4/#hex-notation.  Likely https://matplotlib.org/tutorials/colors/colors.html and a few other places will also need updating.

**Comment by PatrickFeiring** [comment]
I added a line about the change in the colors.py and in the color specification tutorial, as well as a new entry in `/doc/users/next_whats_new`.

**Comment by anntzer** [comment]
A link to the css spec (e.g. the one I posted above) in colors.py would be nice.  (Probably not necessary in the tutorial as well.)

**Comment by NelleV** [comment]
:+1: Thanks @PatrickFeiring !

**Comment by tacaswell** [comment]
re-milestoned to 3.2 as we have not branched yet so it's going to be in 3.2 not 3.3.

**Pull request merged**
