### PR TITLE
Correct regex in filterwarnings

### PR DESCRIPTION
**Pull request by jenshnielsen**
The method name has changed, also enable an assert which should have been enabled earlier

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Actually I would probably prefer changing the error message. The message is inside subplots() not add_subplots so not sure whats going on

**Comment by jenshnielsen** [comment]
Implemented the other solution in the second commit

**Comment by tacaswell** [comment]
This does not cherry-pick cleanly back to 1.5.x because where `subplots` is implemented moved to figure from `pyplot` in https://github.com/matplotlib/matplotlib/pull/5146 (which is where the name miss-match comes from, in the initial version of the PR the function was called `add_subplots` not `subplots`).

The assert should be uncommented on 1.5.x in a it's own PR.

**Comment by jenshnielsen** [comment]
Ok I will do a PR to fix the assert on 1.5.x

**Comment by tacaswell** [comment]
thanks.

**Comment by jenshnielsen** [comment]
Done as #5736

**Pull request merged**
