### PR TITLE
ci: Bump Ubuntu to 18.04 LTS.

### LINKED ISSUE #19494: Update azure ubuntu images to 18.04, or update texlive in CI
### Describe the issue

**Summary**

The pgf/luatex tests have been flaky for a while on azure (see e.g. https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=17033).  Based on the logs
```
E               ! LuaTeX error ...xmf-dist/tex/luatex/luaotfload/fontloader-2016-02-12.lua:11111
E               : attempt to get length of local 'lookupdata' (a number value).
E               <to be read again> 
E               \scan_stop: 
E               <*> .../work/1/s/lib/matplotlib/mpl-data/fonts/ttf/}]
```
I have traced this back to a piece of code in luaotfload that has been removed in early 2016 from luaotfload (https://github.com/latex3/luaotfload/commit/0cf41dff08cdc61119a2598cf1fa501cd15bfc54 / https://github.com/contextgarden/context-mirror/commit/788487819ccf38a8478cc2afd88e0c0b088d0ec1 are the specific commits, grep for `local function ligature` in `src/fontloader/misc/fontloader-font-otn.lua` (`fontloader-2016-02-12.lua` is a concatenated version of the lua sources)).  I don't think it's worth spending more time on a 5y old bug(?) in luatex, so perhaps we could consider either updating the azure ubuntu images to 18.04, or, if we really want to keep the 16.04 images, figure out how to use a more recent texlive in it.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Ubuntu 16.04 LTS went EOL at the end of April 2021.

Fixes #19494.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [n/a] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
The EPS failures are a bit strange, and sporadic:
```
$ identify result_images/test_backend_ps/type3*
result_images/test_backend_ps/type3.eps PS 576x432 576x432+0+0 16-bit sRGB 4651B 0.000u 0:00.000
result_images/test_backend_ps/type3_eps.png PNG 595x842 595x842+0+0 8-bit sRGB 5736B 0.000u 0:00.000
result_images/test_backend_ps/type3-expected.eps PS 576x432 576x432+0+0 16-bit sRGB 4651B 0.000u 0:00.000
result_images/test_backend_ps/type3-expected_eps.png PNG 612x792 612x792+0+0 8-bit sRGB 5456B 0.000u 0:00.000
```
They're both the same size as EPS, but different size when converted to PNG. Also, previous commits failed more jobs than the current one, with the EPS failures, so it seems a bit flaky.

**Comment by QuLogic** [comment]
OK, I realized we cache `~/.cache/matplotlib` on runners, and since conversions of expected test images to `.png` would be using different system latex/ghoscript/inkscape/etc., those caches needed to be invalidated. This should fix the random `.eps` test failures (which probably only passed when the cache was too big and _happened_ to drop those files by chance).

**Comment by anntzer** [comment]
Possibly consider having an 20.04 job?  per https://github.com/matplotlib/matplotlib/pull/19255#issuecomment-795432831 and following comments...

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
I tried that just now, but there are a couple issues. Something seems wrong with coverage, possibly to do with parallel tests, but I have not investigated. There are failures in some tests; this is good for me since they've been broken on Fedora with newer dependencies, but it won't be equal to the Ubuntu 18.04 tests.

I think I'll open the 20.04 changes in a separate PR.

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.4.x

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.4.2-doc

**Pull request merged**
