### PR TITLE
Allow build children to run 

### PR DESCRIPTION
**Pull request by jenshnielsen**
This was a regression from the moving of the file which resulted in the launching of the OSX builds to fail. This only applies on the master branch since the 2.x and 1.5.x branch don't have this issue

### CODE REVIEW

**Comment by QuLogic** [comment]
Where do OSX builds run? Not on Travis?

**Comment by jenshnielsen** [comment]
You can only build one type of travis jobs in one script. This triggers another travis job that does the osx build

**Comment by QuLogic** [comment]
That's not true; you can specify the `os` key in the build matrix. For example, libsass [does so](https://github.com/sass/libsass/blob/master/.travis.yml#L31) and their builds [run on Linux and OSX in one go](https://travis-ci.org/sass/libsass).

**Comment by jenshnielsen** [comment]
Ok, I didn't know that it's probably worth investigating to port our jobs to run OSX in the same job. Never the less this was originally setup to trigger a child job (not by me) to run on OSX and as as far as I know that was because there was no support for running mixed OS jobs at that time.

**Comment by QuLogic** [comment]
In any case, I don't think anything could go wrong here.

**Pull request merged**
