### PR TITLE
Backport PR #17006 on branch v3.2.1-doc (Fix typo)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #17006: Fix typo

### CODE REVIEW

**Comment by tacaswell** [comment]
We should not have merged changes to the library files to the -doc branch.

**Comment by QuLogic** [comment]
Yes, do we have conflicts now?

**Comment by tacaswell** [comment]
no conflicts, just that if you build the docs from this branch with the tagged version installed this change will be ignored (because we pull the docstrings from the installed version of the code).

**Comment by tacaswell** [comment]
I also merged one (https://github.com/matplotlib/matplotlib/pull/17384) that should not have been.

**Pull request merged**
