### PR TITLE
Include template matplotlibrc in package_data.

### LINKED ISSUE #10717: Failure to find matplotlibrc when testing installed distribution
During wheel testing:

```
_______________________ test_if_rctemplate_is_up_to_date _______________________
[gw0] linux -- Python 3.5.3 /venv/bin/python3.5

    def test_if_rctemplate_is_up_to_date():
        # This tests if the matplotlibrc.template file
        # contains all valid rcParams.
        dep1 = mpl._all_deprecated
        dep2 = mpl._deprecated_set
        deprecated = list(dep1.union(dep2))
        #print(deprecated)
        path_to_rc = mpl.matplotlib_fname()
>       with open(path_to_rc, "r") as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/venv/lib/python3.5/site-packages/matplotlib/mpl-data/matplotlibrc'

```

See full log available via https://travis-ci.org/MacPython/matplotlib-wheels/jobs/350816982

Is the matplotlibrc being correctly bundled / registered for install?

### PR DESCRIPTION
**Pull request by anntzer**
This is necessary to make the tests pass for a non-editable install.

Should close #10717 (attn @matthew-brett).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
Is this file going to be auto-generated before it gets included? I am not exactly sure how this process works in setuptools.

**Comment by anntzer** [comment]
@WeatherGod It's always present in the source tree.

**Comment by WeatherGod** [comment]
What do you mean? It isn't in the source tree.
https://github.com/matplotlib/matplotlib/tree/master/lib/matplotlib/mpl-data

**Comment by anntzer** [comment]
Oh sorry, my bad.
But yes, it is generated by `setup.py`
```
        with open('lib/matplotlib/mpl-data/matplotlibrc', 'w') as fd:
            fd.write(
                template.safe_substitute(TEMPLATE_BACKEND=default_backend))
```
and that happens even before setuptools has a chance to look at sys.argv, IOW early enough in the process for things to work.

**Pull request merged**
