### PR TITLE
Remove axis() manual argument parsing.

### PR DESCRIPTION
**Pull request by anntzer**
axis is now just a standard function taking 0-1 arguments.  This change *does* make it possible to call `axis(None)` as synonym for `axis()`, as well as passing the sole argument under the name `arg` (unless we decide to switch to positional-only args -- @timhoffm?) but that seems fine.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by timhoffm** [comment]
BTW: What is `axis()` doing anyway? AFAICS this results in `set_xlim(None, None, emit=True, auto=None)` and likewise for ylim, wich does not change anything. - Maybe we should deprecate `axis()` and require either a positional or keyword parameter to be set.

**Comment by anntzer** [comment]
Sure, made it positional only.

`axis()` with no args is documented to return xmin, xmax, ymin, ymax, which is shorter than calling `xlim()`/`get_xlim()` and `ylim()`/`get_ylim()` separately; sure, we could deprecate it out of purity but I don't actually think we should -- even if I don't ever use that form, that just seems to be gratuitiously breaking end users (or if we do, we should also get rid of e.g. `axis("on")`/`axis("off")` on the grounds that this should be spelled `set_axis_on()`/`set_axis_off()`).

Having None be the default and mean the same as no args is pretty standard in Python, and I don't really like the idea of introducing _DEFAULT to strictly keep the same call semantics as previously (for example, distinguishing between None and unset is also the root issue of #24413); Axes.set() is a rather special case as here the signature absolutely cannot be spelled out without introducing such a placeholder.

**Comment by jklymak** [comment]
> Maybe we should deprecate an empty axis() 

`axis` returning the limits is a Matlab-ism:  https://www.mathworks.com/help/matlab/ref/axis.html

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Still a real test failure.

**Comment by anntzer** [comment]
oops, fixed.

**Review by ksunden — APPROVED** [review]

**Pull request merged**
