### PR TITLE
Merge pull request #11786 from timhoffm/collections-abc

### PR DESCRIPTION
**Pull request by tacaswell**
Fix collections import warnings for Python 3.7

Put try...except blocks in to support py27

### CODE REVIEW

**Comment by tacaswell** [comment]
```
 C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:C:\Miniconda-x64\envs\test-environment\Library\lib /LIBPATH:.\lib /LIBPATH:C:\Miniconda-x64\envs\test-environment\libs /LIBPATH:C:\Miniconda-x64\envs\test-environment\PCbuild\amd64 /LIBPATH:C:\Miniconda-x64\envs\test-environment\PC\VS9.0\amd64 png.lib z.lib /EXPORT:init_png build\temp.win-amd64-2.7\Release\src/_png.obj build\temp.win-amd64-2.7\Release\src/mplutils.obj /OUT:build\lib.win-amd64-2.7\matplotlib\_png.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\src\_png.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\src\_png.pyd.manifest
961    fatal error C1900: Il mismatch between 'P1' version '20150812' and 'P2' version '20080116'
962    LINK : fatal error LNK1257: code generation failed
963    error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1257
```

It looks like building Matplotlib on python2 an appveyor has bit-rotted.

The first SO result for this error is https://stackoverflow.com/questions/8959973/il-mismatch-between-p1-version-20080116-and-p2-version-20070207 which suggests we have miss-matched versions of visual studio.

**Comment by jklymak** [comment]
Do we really want to worry about MPL 2.x compatibility with py3.7?  Like fine if we do, but maybe 2.x should just have a maximum python version it supports?

**Comment by tacaswell** [comment]
Yes, because we want to make the python2 -> python3 transition as smooth as possible for people just doing this now.  There will be people jumping from py27 -> py37 so not making them jump from mpl 2.2.x -> 3.2.x in the same go.  

Also, as a general principle, any branch we are still supporting should support all released versions of Python per https://numpy.org/neps/nep-0029-deprecation_policy.html

**Comment by NelleV** [comment]
I restarted the failure on appveyor, and it fails consistently.

**Comment by jklymak** [comment]
Yes I don’t doubt that apveyor isn’t building just that it’s not the fault of this PR

**Comment by QuLogic** [comment]
AppVeyor has been broken for a very long time. I tried to fix some of it, but don't really understand the Py2 errors.

Since this works on Py3 (which is the point) on master and Py2 on Travis, I'm inclined to merge and just fix AppVeyor later.

**Pull request merged**
