### PR TITLE
Formatted docs

### PR DESCRIPTION
**Pull request by Gaurav-Kumar-Soni**
## PR summary
Reformatted the release notes as per the style conventions at https://matplotlib.org/devdocs/devel/document.html#section-formatting.

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [X] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
These files are fine, but it depends on if it breaks all the files in their toctrees.

**Comment by Gaurav-Kumar-Soni** [comment]
Okie ..

**Review by QuLogic — APPROVED** [review]
Seemed good to me on a quick look through things.

**Comment by QuLogic** [comment]
Thanks @Gaurav-Kumar-Soni! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.

**Pull request merged**
