### PR TITLE
Simplify intro tutorial re: asarray.

### PR DESCRIPTION
**Pull request by anntzer**
DataFrames can also be converted to numpy arrays using np.asarray; no
need to mention a separate way of converting them.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
If it's always just `numpy.asarray`, IMHO we should put that at the beginning of the relevant functions. Doesn't cost anything if it's already an array. Telling people to always manually convert is a bit pedantic. We should change our policy to

~~~
All of plotting functions expect `numpy.array` or `numpy.ma.masked_array` input, or objects that can be converted to these using `numpy.asarray` (such as `pandas.DataFrame` and `numpy.matrix`).
~~~

**Comment by anntzer** [comment]
Well, we can't launder everything though asarray because units.  Lack of support for e.g. np.matrix was explicitly added in https://github.com/matplotlib/matplotlib/pull/3394.
Even if we were to change this policy, this part of the docs would need to stay until we have asarray() calls (+ whatever unit handling needs) in place everywhere.

**Comment by timhoffm** [comment]
I see. Then I'd leave this as is. IMHO `df.values` is more canonical than `np.asarray(df)`. It's shorter to type (not much but still less annoying when working interactively), and people will not necessarily have numpy imported when working with pandas.

**Comment by timhoffm** [comment]
Actually [to_numpy](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html) is preferred over [values](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html) since pandas 0.24. We should advertise that.

**Comment by anntzer** [comment]
But we support older versions of pandas and I don't think we should start having to field questions from confused users using old pandas.  (I don't think the usage tutorial should become a pandas tutorial either.)
I personally like asarray() because it always works (and that's what we use internally anyways); I guess we could just remove the examples here.  Or just close the whole PR if you prefer, I'm not overly attached to it.

**Comment by timhoffm** [comment]
I'd leave as is; primarily telling "convert to numpy", plus "here is an example" is the right priority.

Anyway, thanks for thinking about how to improve the docs!

**Pull request closed without merging**
