### PR TITLE
FIX: if the first elements of an array are masked keep checking

### LINKED ISSUE #14356: matplotlib.units.ConversionError on scatter of dates with a NaN in the first position
### Bug report

**Bug summary**

When on a scatter plot the first number on the y values is a nan, and the x values are dates, I get the error:

`matplotlib.units.ConversionError: Failed to convert value(s) to axis units: masked_array`

*Code for reproduction**

```python
import numpy as np
import pylab as plt

times = np.arange('2005-02', '2005-03', dtype='datetime64[D]')

y = np.random.random(size=len(times))
y[0] = np.nan
plt.scatter(times, y)

plt.show()
```

**Actual outcome**

On Matplotlib 3.0.0, I get no warning.

On 3.1.0, I get an error.

```
Traceback (most recent call last):
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/axis.py", line 1551, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/dates.py", line 2011, in convert
    return date2num(value)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/dates.py", line 426, in date2num
    return _to_ordinalf_np_vectorized(d)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/dates.py", line 226, in _to_ordinalf
    base = float(dt.toordinal())
AttributeError: 'numpy.float64' object has no attribute 'toordinal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 501, in _draw_idle
    self.draw()
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/figure.py", line 1709, in draw
    renderer, self, artists, self.suppressComposite)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2645, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/image.py", line 135, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/collections.py", line 866, in draw
    Collection.draw(self, renderer)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 38, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/collections.py", line 257, in draw
    transform, transOffset, offsets, paths = self._prepare_points()
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/collections.py", line 229, in _prepare_points
    xs = self.convert_xunits(offsets[:, 0])
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/artist.py", line 180, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/home/david/.virtualenv/py36/lib/python3.6/site-packages/matplotlib/axis.py", line 1554, in convert_units
    f'units: {x!r}') from e
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: masked_array(data=[--, 731979.0, 731980.0, 731981.0, 731982.0, 731983.0,
                   731984.0, 731985.0, 731986.0, 731987.0, 731988.0,
                   731989.0, 731990.0, 731991.0, 731992.0, 731993.0,
                   731994.0, 731995.0, 731996.0, 731997.0, 731998.0,
                   731999.0, 732000.0, 732001.0, 732002.0, 732003.0,
                   732004.0, 732005.0],
             mask=[ True, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=1e+20)

```

**Matplotlib version**
  * Operating system:
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6

Matplotlib installed through pip on a virtual environment

### PR DESCRIPTION
**Pull request by tacaswell**
closes #14356

This is a slight modification and a test of what @anntzer proposed in the issue.

Will not back port cleanly but :woman_shrugging: .

### CODE REVIEW

**Comment by jklymak** [comment]
@tacaswell, I directly edited a change to this. Hope that was OK.

I approved this, but you could self-merge on my changes to get the test to work, or someone else could merge; I don't think I should merge since I last edited...

**Comment by tacaswell** [comment]
Thanks @jklymak !

In general assume you can push non-controversial stuff to any of my branches.

**Comment by tacaswell** [comment]
@anntzer had some questions about this in  #14356 .  I think that keeping checking until we find an un-masked element is the correct behavior which seems safer than assuming that a fill value will have the right units.

**Comment by jklymak** [comment]
Yeah, though it is kind of wasteful for a long masked-out array.  We still should sit down an write a specification for what units are and how they can be packed, because I'm not sure how we would get in the situation where a masked out element would have different units than the unmasked elements.  

Also what happens if the whole array is masked?  I'm not sure this will ever return anything?

**Comment by tacaswell** [comment]
It will have the same behavior as passing an empty list (which is to return `None` which may or may not be what we want it to do, but at least it is consistent?)

**Pull request merged**
