### PR TITLE
 return extension metadata

### PR DESCRIPTION
**Pull request by jschueller**
see http://sphinx-doc.org/latest/extdev/index.html

### CODE REVIEW

**Comment by mdboom** [comment]
Interesting.  Would this explain why doing a parallel build of our docs only makes things *slower*?

**Comment by jenshnielsen** [comment]
@mdboom I think so. I looked into this at some point we need to mark all the plugins we are using as parallel safe for that to work

**Comment by jenshnielsen** [comment]
What I was trying to say is that I think there are more extensions that need to be marked safe for this to work in our docs build

**Comment by mdboom** [comment]
I'm playing around with parallel doc building in #5597.  I don't think we need to wait for that to merge this, though.  This will still help others who use the plot directive in their own projects.

**Comment by jschueller** [comment]
@mdboom, exactly

**Comment by tacaswell** [comment]
backported to v2.x as 591b6d6

**Pull request merged**
