### PR TITLE
Cleanup examples

### PR DESCRIPTION
**Pull request by timhoffm**
- <s>Use `set_xticks(positions, labels)` instead of `set_xticks(positions); set_xticklabels(labels)`.</s> *Moved to #20636 for easier review*.
- Use batch `ax.set()` instead of multiple `set_*` calls when appropritate.

### CODE REVIEW

**Comment by jklymak** [comment]
Is this something we want to do this pervasively?  I _never_ use `ax.set`, though I suppose I could get in the habit, but I'm not sure if I think its good style or not. It certainly does not tab-complete because the arguments are just `**kwargs`.  (Sorry for the noise if this was a decision already decided on)

**Comment by timhoffm** [comment]
You are right, we did not have a formal decision on this. Maybe we should.

At least we have that API and we should consider if it's something that should be promoted.
I find batch-setting worthwile. Kwargs often used in more modern plot tools. Personally, I find the compact notation better than having lots of `ax.set_*` calls.

> It certainly does not tab-complete because the arguments are just `**kwargs`. 

It now does after #20569.

**Comment by story645** [comment]
>Is this something we want to do this pervasively?

I feel like for the docs it's less confusing if properties are set in a consistent way across examples where the property setting isn't the point, and shoving the property setting into a function helps make it kinda of go away.

**Comment by jklymak** [comment]
I think that the docs should reflect users' typical use cases, and every axis _should_ have a label.  So sure, for highly technical docs where we are doing something completely orthogonal, doing the more mysterious thing is OK.  I'm not horrified by `ax.set(xlabel='my xlabel', ylabel='my ylabel')` but 
1. it is _not_ as flexible (you can't pass any of the optional kwargs), 
2. it is not as intuitive to explain to new users, 
3. it is not as searchable (either in the docs or on the internet), and 
4. it does not tab complete the same way as `ax.set_x...` does.  

I think the only thing it has going for it is that it is (usually) shorter and can be written in one line.  

So I'm pretty skeptical of removing it very often or deciding that it is the "preferred" way, if nothing else because of 1.  maybe folks can talk about it at the meeting this week (I'll be away, but I'm sure you understand the concerns).

**Comment by timhoffm** [comment]
We had some discussion about this in the dev call (which was only a small group today). The overall consensus is that both the explicit setter functions as well as the batch-set have their merits and are targeted at different use cases / user groups. Ideally, they would be separate API-levels, but that's not the case for historic reasons. It is important to communicate the reasons for both concepts and when to use what. I'll write a tutorial on that, which hopefully gives an understanding and clear directions. Until that's agreed on, I put this PR on hold.

**Comment by timhoffm** [comment]
Let's close this. If we want to pick this up at some point, starting anew will be easier than trying to rebase.

**Pull request closed without merging**
