### PR TITLE
relax two test tolerances on x86_64

### PR DESCRIPTION
**Pull request by nschloe**
When running the tests locally on `x86_64`, I had to relax two tolerances to the same value as `aarch64`.

This is on Ubuntu 20.04, so perhaps the reason why no one else has run into this before is an upgraded version in the dependency stack.

### CODE REVIEW

**Comment by timhoffm** [comment]
flake8 errors:
~~~
./lib/matplotlib/tests/test_usetex.py:15:80: E501 line too long (87 > 79 characters)
./lib/matplotlib/tests/test_backend_pgf.py:171:80: E501 line too long (87 > 79 characters)
~~~

**Comment by nschloe** [comment]
> I'm a bit uneasy relaxing tolerances just because "then it works".

I'm with you there. When running the tests locally I noticed those tests are failing with the same tolerance as the aarch64 exceptions, so I threw that curve ball at you. I would guess that the exceptions aren't related to the architecture but the version of some dependency, perhaps a few layers down. Might be hard to figure out.

**Comment by timhoffm** [comment]
Can you provide the diff image of the failed tests? They should be in the folder `result_images` after running the test. That may give an indication what changed.

**Comment by anntzer** [comment]
Also, do you still observe the need for this after `rm -rf ~/.cache/matplotlib/test_cache`?

**Comment by nschloe** [comment]
> Also, do you still observe the need for this after rm -rf ~/.cache/matplotlib/test_cache?

Yes.

Here are the plots for the failing `lib/matplotlib/tests/test_backend_pgf.py` test with the visual diff created with
```
compare image1 image2 -compose src diff.png
```

pgf_mixedmode-expected_pdf
pgf_mixedmode_pdf
diff2


And for `lib/matplotlib/tests/test_usetex.py`:

test_usetex
test_usetex-expected
diff

**Pull request merged**
