### PR TITLE
Improve imshow performance - Issue 8143

### PR DESCRIPTION
**Pull request by eozcelik**
Changed & to * in lib/matplotlib/image.py invalid_mask calculation to improve performance
#8143

### CODE REVIEW

**Comment by eozcelik** [comment]
#8143 - Changed from * to & for improved performance

**Comment by WeatherGod** [comment]
For posterity, could you document how you determined that this is a
performance improvement?

**Comment by eozcelik** [comment]
I have originally commented this on the issue 8143, but here is the snippet i used to test differences.
```
X = np.arange(100)
X = X.reshape(5, 20)

fig = plt.figure()
ax1 = fig.add_subplot(311)
print(timeit.timeit("ax1.imshow(X, interpolation='nearest')", "from __main__ import ax1, X", number=10000))
```
The differences is to the second(sometimes third) decimal place, but it is still an improvement

**Comment by dstansby** [comment]
Thanks for checking this out! You've based your PR on our `v2.0.x` branch, but the bug isn't targeted until `2.1`; could you rebase on top of our `master` branch instead?

**Comment by QuLogic** [comment]
This is going to be a bit of a pain for @eozcelik because he started with his own `v2.0.x` branch instead of a feature branch. It might be less trouble to open a new PR based on a feature branch.

Also, @eozcelik, your commits are attributed with an email address that is the host name of the virtual machine you used; is that really the address you want to use?

**Comment by eozcelik** [comment]
@QuLogic that is not the email address i want to use, something must have gone wrong setting up my email address on the vm. I'll fix it in the new PR.
So to summarize I just need to submit my changes in a new branch and merge this with the master right ?

**Comment by QuLogic** [comment]
Submit your changes in a new branch based on `master`; don't merge `master`, but rebase these commits to start from `master` instead of `v2.0.x`.

**Comment by dstansby** [comment]
There's a step by step guide here which might be helpful: http://matplotlib.org/devdocs/devel/contributing.html#contributing-code

**Comment by eozcelik** [comment]
@QuLogic the code I made changes to isn't in the master branch, should I still follow the same course of action ?

**Comment by tacaswell** [comment]
This is fine to target 2.0.x, we can re-target the original issue.

**Comment by eozcelik** [comment]
@tacaswell so just to clarify, make a new branch based off of 2.0.x then do a PR targeting matplotlib/2.0.x instead of master right ? or do i rebase to 2.0.x branch ?

**Comment by tacaswell** [comment]
That is not the best test, I don't think that actually forces the figure to render and just adds _lots_ of `AxesImage` artists to the `Axes`.

**Comment by eozcelik** [comment]
@tacaswell do you have any suggestions to how I can approach testing this ? I can try to localise the result in AxesImage.make_image ?

**Comment by tacaswell** [comment]
`fig.canvas.draw()` should force a re-draw, but sorting out how to directly call the inner functions might be better (less other things going on in the timing).

**Pull request closed without merging**
