### PR TITLE
DOC fix set_xticklabels docstring

### PR DESCRIPTION
**Pull request by TomDLT**
Major change in `axes.set_xticklabels` and `axes.set_yticklabels` docstrings

### CODE REVIEW

**Comment by anntzer** [comment]
Congrats on your first contribution, hoping to see you around again :-)

**Comment by anntzer** [comment]
Actually, before merging: The patch has your email as `<TomDLT@users.noreply.github.com>`.  Do you wish to replace this by a real email?

**Comment by QuLogic** [comment]
> @dstansby dstansby added this to the v2.1.0-doc milestone 13 minutes ago

Only .rst changes go in that branch.

**Comment by NelleV** [comment]
Thanks @TomDLT !

**Pull request merged**
