### PR TITLE
Subplot spacing

### PR DESCRIPTION
**Pull request by tacaswell**
Replaces #6129

### CODE REVIEW

**Comment by efiring** [comment]
This has a bunch of image failures.  Some of them I recognize as trouble-makers from earlier style changes.  I'm not sure whether the best solution is just replacing the images.

**Comment by tacaswell** [comment]
Digging into why these are failing is on my list of things to do today.

**Comment by tacaswell** [comment]
3 of the tests that explicitly use the new defaults and 4 of them are the pgf tests.

I think that until we tag 2.0, the image comparison should just knownfail any non-'classic' style test.

**Comment by tacaswell** [comment]
Assuming this passes it should be ready to go.  The other default change PRs should probably be rebased to also side-step some of this pain.

**Pull request merged**
