### PR TITLE
Backport PR #12809 on branch v2.2.x (Fix TypeError when calculating tick_values)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #12809: Fix TypeError when calculating tick_values

### CODE REVIEW

**Comment by timhoffm** [comment]
CI fails due to

~~~
E               _pytest.warning_types.RemovedInPytest4Warning: MarkInfo objects are deprecated as they contain merged marks which are hard to deal with correctly.
E               Please use node.get_closest_marker(name) or node.iter_markers(name).
E               Docs: https://docs.pytest.org/en/latest/mark.html#updating-code
~~~

Solution: Either pin pytest<3.8 or backport #12154.

**Comment by tacaswell** [comment]
power cycled to re-run now that pytest pinning is merged.

**Comment by ArchangeGabriel** [comment]
@NelleV For the CI to pass (outside of MacOS that is just broken), #13181 must be merged first (or alternatively just part of it + alternative pinning of some deps).

**Comment by NelleV** [comment]
@ArchangeGabriel there's actually two different problem right now. Tom and I have fixed them in a PR.

**Comment by ArchangeGabriel** [comment]
@NelleV I think you fixed 3.0.x branch (PR #13216), but this is for 2.2.x.

**Comment by ArchangeGabriel** [comment]
I don’t know what the coverage failure means, but outside from that all other CIs now pass.

**Pull request merged**
