### PR TITLE
Prefer add_subplot(foo=bar) to subplots(subplot_kw={"foo": bar}).

### PR DESCRIPTION
**Pull request by anntzer**
When creating a single subplot I think the former is more readable.

(Note that before mpl3.1 one had to write `add_subplot(111, foo=bar)`
where the tradeoff was less clear.)

Happy to discuss which form to prefer...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
+0.5. I think, this is more readable for the cases presented here.

I'm a bit worried on the `ax = plt.figure().add_subplot(projection='3d')` chaining. This is not a pattern commonly used in matplotlib so far. And explicitly creating a figure without binding it to a variable may appear a bit pedantic. In the pyplot world (which you are sort of in here even if you are later only working on the axes, this could simply be `ax = plt.subplot(projection='3d')`.

So if we're going away from "just use `plt.subplots()` and then work with the axes", I think we can equally allow `plt.figure()` and `plt.subplot()`.

**Comment by efiring** [comment]
The advantage of `plt.figure().add_subplot()` over `plt.subplot()` is that it makes the figure creation explicit, and the chain is easily split if it turns out that one needs a reference to the figure.  It takes more typing, but I think that it might in the end help new users understand mpl more quickly than if they rely on the additional pyplot magic in `plt.subplot()`.

**Comment by timhoffm** [comment]
I agree that the explicit figure creation has its merit, and partly withdraw my argument that `plt.subplot()` and `plt.subplots()` should be used equally (it's unfortunate that these functions are named similarly, but have a different behavior with respect to figure creation).

This whole axes creation is a bit of a mess. If we did not have history
~~~
ax = plt.figure().add_subplot()
axs = plt.figure().add_subplots()
~~~
would look like a reaonable API to me (maybe with optional pyplot shortcuts using implicit figure creation). But we're not there. The latter is `plt.figure().subplots()`  and we've advertized `plt.subplots()` instead.

I'm really worried we're confusing users with all these different methods and changed recommendations for axes creation. Even if `plt.subplots(subplot_kw={"foo": bar})` is ugly, at least it's the straight forward extension of  `plt.subplots()` / `plt.subplots([2, 2])`. Making the former look nicer but in exchange break API similarity with related functions is not a big win (if any).

Essentially, I see two reasonable ways:
1. Keep as is for now to not have yet another partial change; i.e. stay with `plt.subplots()` for now.
2. Rethink the whole Axes generation and establish one consistent API. This could be:

  - Create `Figure.add_subplots()` as a synonym for `Figure.subplots()` (deprecate or keep the latter).
  - establish
    ~~~
    ax = plt.figure().add_subplot()
    axs = plt.figure().add_subplots()
    ~~~
    as a canonical way to create axes. Split the call if you need a reference to the figure. Optionally use pyplot functions as a shortcut. Should that be `plt.subplot[s]()` or `plt.add_subplot[s]()`?

  This is just an of-the-top of my head concept and certainly would need more thorough consideration.

**Comment by anntzer** [comment]
Well, I would really have preferred to have `Figure.add_subplots` instead of `Figure.subplots` but I lost the discussion at https://github.com/matplotlib/matplotlib/issues/5139 https://github.com/matplotlib/matplotlib/pull/5146 :(

I agree that ever-changing recommendations are not great :( but OTOH we're all (well, at least I'm definitely still) learning how to best design an API.

Obviously the necessary "technology" (i.e. both Figure.add_gridspec and a stronger focus on non-pyplot APIs) was not available when subplots() was first introduced (as a pyplot-only helper), but if I was designing things from scratch,
```
plt.subplots(*args, gridspec_kw=..., subplot_kw=..., **fig_kw)
```
would be spelled
```
plt.figure(**fig_kw).add_gridspec(*gridspec_args, **gridspec_kw).subplots(**subplot_kw)
```
I think...

**Comment by jklymak** [comment]
I'm not a fan of favouring a different API for a single subplot than for multiple subplots, and I'm not at all a fan of `add_subplot` which is really just a matlab-ism.  OTOH, I agree that `subplot_kw` is pretty ugly, and makes those kwargs non-discoverable.  Would be good to talk about these use cases in one place and come up w/ what we think should be canonical?

**Review by timhoffm — COMMENTED** [review]
I'm still very undecided between `subplots(..., subplot_kw=...)` and `figure().add_subplot()`.
Personally, I likely wouldn't actively rewrite this, but also wouldn't block if you push this forward again. 

We should definitively limit the kwargs to polar and 3d. Everything else (see suggestions) should not be crammed into the subplots creation. This is a change that can be made independently of above decision.

**Comment by anntzer** [comment]
OK, I rewrote the whole thing to just make the changes that should be uncontroversial.

**Comment by anntzer** [comment]
I think a *crucial* point of python semantics as opposed to matlab (which is still pretty commonly used in my field) is exactly that you *can* chain calls, i.e. `tmp = foo(); b = tmp.bar()` is equivalent to `b = foo().bar()` and therefore you explicitly don't need to litter your code with all the intermediate temporaries (and another crucial point is that parentheses mark function calls, which again isn't the case in matlab (which implicitly calls functions with no args)).
I would say the chained call is proper style; if there's opposition to it I'd rather just close the whole thing rather than writing `fig = plt.figure(); ax = fig.add_subplot(...)` which is worse IMO.

**Comment by anntzer** [comment]
Let's just close this until we can actually decide on a standard.

**Comment by jklymak** [comment]
We have already added width_ratio and height_ratio as pass throughs.  The only one I really miss is facecolor

I think in general passing the figure back to the user is quite often necessary even in the case of a single subplot - in particular for colorbars.  We could have ax.colorbar but again, having a separate idiom for single axes versus multiple axes in the docs seems confusing.  I think we should always use fig, axs = plt.subplots() for consistency, even if there is just one axes.

**Pull request closed without merging**
