### PR TITLE
Remove mpl_examples symlink.

### PR DESCRIPTION
**Pull request by anntzer**
AFAICT we're not using it for anything, we don't have a similar symlink
to the tutorials, and it annoys my tab-completion when I try to get into
mpl_toolkits...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
does this affect what goes into the build products when we release?

**Comment by jklymak** [comment]
The docs look fine.  Is it there to maintain links?  Or maybe archived links instead of returning a 404?

**Comment by anntzer** [comment]
The sdist actually contains 2 copies of the examples, as the tgz (or probably the distutils archiver) doesn't keep mpl_examples as a symlink.
Other than that, I don't think anything changes.

**Comment by tacaswell** [comment]
This will need a deprecation note then is case down-stream consumers are expecting this directory.

**Comment by anntzer** [comment]
Not sure how you want to word this, can you directly push to the PR?

**Comment by tacaswell** [comment]
This is the second time you have removed this symlink... https://github.com/matplotlib/matplotlib/pull/9708

**Comment by tacaswell** [comment]
@sandrotosi @QuLogic Can you verify this won't mess up debian and fedora packaging?

**Comment by QuLogic** [comment]
We don't install it, and currently don't even build the docs, so I'm not sure it's needed here.

**Comment by sandrotosi** [comment]
thanks @tacaswell for checking with the distro packagers! yes this should be fine for debian (you plan on keep distributing the `examples/` dir in the tarballs right?)

**Pull request merged**
