### PR TITLE
Deprecate unit_cube-related methods in Axes3D

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

I cannot see that there is any valid public use for these. No doc-string either.

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
Maybe soften this to "...if you rely on this let us know and we will consider preserving"?

**Comment by oscargus** [comment]
> Maybe soften this to "...if you rely on this let us know and we will consider preserving"?

Doesn't that always hold?

(I checked on grep.app and one other library seems to use `tunit_edges`.)

**Comment by timhoffm** [comment]
> Doesn't that always hold?

Basically, yes. But people may not be aware of that. However, IMHO adding this is is only needed in cases where we ourselves have some doubts and consider it likely that there might be substantial downstream issues.

This here is good as is.

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
@oscargus maybe you want to give the one known downstream user a heads up.

**Pull request merged**
