### PR TITLE
Remove datetime test for axes.pie

### PR DESCRIPTION
**Pull request by Sheepfan0828**
## PR summary
The task i am working with is `Axe.pie` problem from the issue https://github.com/matplotlib/matplotlib/issues/26864 . The `Axe.pie` should be removed from the file `test_datetime.py` file because we cannot directly pass the `datetime` object into `pie` as a parameter to perform any of the plots. The error message below shows the case occured when `datetime` object is directly passed into the `pie` function:
屏幕截图 2023-10-17 164915

## PR checklist
- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by Sheepfan0828** [comment]
Both u7277320 and sheepfan0828 are my personal Github account

**Comment by Sheepfan0828** [comment]
Is it okey that some checks are not passed?

**Comment by ksunden** [comment]
The linting would need to be addressed.

However, more fundamentally, this is not exercising the datetime  unit machinery that is expected here, and in fact `pie` in general does not use the units system (and it's unclear what it even _would_ mean).

As such I think `pie` should just be removed from this file all together (much like we did to table/spectral methods in #27072)

The list from the original issue/stubs was intentionally a bit broad but part of the idea was to evaluate whether it was using units at all. In this case it is not, and so it should just be removed.

**Comment by Sheepfan0828** [comment]
@ksunden Sorry, what do you mean by that? I cannot understand.

**Comment by ksunden** [comment]
This method falls into the category that passing datetimes to it directly does not make sense and therefore should just be removed (From  #26864):

> iii: If passing datetime / united data to the method does not make any sense or it should not work open a PR removing that test method and similarly reference this issue.

By calling `to_ordinal` here, you are not passing the datetime objects, and so are not doing what this test file is trying to exercise. This is because the idea of this test file does not make sense for `pie`, and therefore the xfail stub (the entire method) should just be removed altogether.

**Comment by Sheepfan0828** [comment]
> This method falls into the category that passing datetimes to it directly does not make sense and therefore should just be removed (From #26864):
> 
> > iii: If passing datetime / united data to the method does not make any sense or it should not work open a PR removing that test method and similarly reference this issue.
> 
> By calling `to_ordinal` here, you are not passing the datetime objects, and so are not doing what this test file is trying to exercise. This is because the idea of this test file does not make sense for `pie`, and therefore the xfail stub (the entire method) should just be removed altogether.

So do you mean that is the method that i am testing with (`pie` this case) is not accepting datetime object so that the testing function for `pie` should be removed from the file? If so, i need to remove it from `test_datetime.py` right now and then create another pull request that i have removed the `pie`. Is that right?

**Comment by ksunden** [comment]
You can update this PR, no need to make a new one, but yes, I am saying that `pie` should just be removed from this file.

**Review by ksunden — APPROVED** [review]
I would suggest squash merging this (unless @Sheepfan0828 you wish to squash commits [see here](https://matplotlib.org/stable/devel/development_workflow.html#rewrite-commit-history))

**Review by rcomer — APPROVED** [review]

**Comment by rcomer** [comment]
I took the liberty of updating the PR title as we are no longer smoke testing this method.

Thanks @Sheepfan0828 and congratulations on your first Matplotlib PR!  We hope to hear from you again.

**Pull request merged**
