### PR TITLE
Legend artist should take same gid as original artist

### PR DESCRIPTION
**Pull request by OceanWolf**
Basically this PR pre-empts MEP26 which will allow us to style artists by gid, but as I needed something similar for my own work I thought I would submit this now and take us part of the way there.

### CODE REVIEW

**Comment by tacaswell** [comment]
This seems to run against the idea of `gid` as it is no longer globally unique and it may be hard to tell which artist in the 'real' one and which one is the legend one.

**Comment by OceanWolf** [comment]
So how else should we do it then?  By definition of a legend we would want it to have the same style as the real artist it represents.

I imagine in the script one would do
```python
ChangeStyle(ToolBase):
  def trigger(self, *args, **kwargs):
    gid = ... # gid of what we want to change
    ax = ... # axes that controls the stylesheet
    ax.set_style("#%s {alpha: 0.8; lw: 2; ...}")
```
i.e. we need a way to keep the legend in sync with changing the style of the real artist.

With this approach we can still use ``Legend #gid`` as a selector to only select the elements within the legend, and perhaps MEP 26 will also provide a not selector?

Alternatively to this approach we could have a hook to auto-update the legend artist if the original artist changes.

Currently I use this code in a tool to cycle through the artists (as I have too many and it looks crowded), though it could equally get used in machine learning to investigate different groupings, perhaps I miss an obvious way to this at present, anyway, my current code (excuses for the ugliness) and obviously this would simplify a great deal MEP 26:
```python
def set_lines_visibility(self, state, gid):
    for ax in self.figure.get_axes():
        for line in ax.get_children():
            if not self.set_state_gid(line, state, gid) and str(line).startswith('Legend'):
                child = line.get_children()
                for col in child[0].get_children()[1].get_children():
                    for row in col.get_children():
                        items = row.get_children()
                        for item in items[0].get_children():
                            self.set_state_gid(item, state, gid)
    self.figure.canvas.draw()

def set_state_gid(self, artist, state, gid):
    if artist.get_gid() is not None and (gid is None or artist.get_gid() == gid):
        artist.set_visible(state)
        return True
    else:
        return False

```

**Comment by WeatherGod** [comment]
"By definition of a legend we would want it to have the same style as the
real artist it represents"

Not exactly. We have seen situations where users have wanted the legend
markers to be larger or smaller than the marker used in the plot. Or maybe
the user wants the lines to be thicker in the legend. Also, some legend
artists may be a bit different from the artist used in the plot and so the
style semantics might not be perfectly matched (I am thinking along the
lines of the ProxyArtist situations).

I also don't see why the artists in the legend *must* have the same gid as
the ones in the plot. They are logically different: one is used in the
plot, the other is not. That said, the artist in the legend should by
default inherit the style of the plot artists to the extent possible, but
certain characteristics may be different. It would make sense for the
legend artist to have some sort of reference back to the plot artist (or
vice-versa, depending on implementation), so that changes in style for the
plot artists can get reflected in the legend artist right away (but any
defined changes for the legend should still apply).

**Comment by OceanWolf** [comment]
@WeatherGod sure, I agree completely, I think I took that as implied, ASS should solve that with Legend ASS rules overruling non-Legend ASS rules by precedence.

@JamesRamm do you have any thoughts on this?  Any news on MEP26?

**Comment by tacaswell** [comment]
The other way to handle this is with callbacks on the artists when a
property changes.

**Comment by jklymak** [comment]
Hard to see that this is pertinent any more.  Feel free to re-open if you think we should be doing this....

**Pull request closed without merging**
