### PR TITLE
[BUG] Don't allow 1d-arrays in plot_surface.

### LINKED ISSUE #3116: mplot3d: argument checking in plot_surface should be improved.
Following explamle should probaly rise an error.

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D

x = np.linspace(0.5,10,num=100)
y = np.linspace(0.5,10,num=100)

X, Y = np.meshgrid(x, y)
z = np.random.randn(100)

fig = plt.figure(figsize=(14,6))
ax = fig.add_subplot(1, 2, 1, projection='3d')
p = ax.plot_surface(X, Y, z, linewidth=0)

### PR DESCRIPTION
**Pull request by Tillsten**
raise value error instead. fixes #3116.

### CODE REVIEW

**Comment by WeatherGod** [comment]
I have been wavering about whether or not this is a bug or a feature. I am leaning towards bug because when one has a 1D Z array, it can ambiguous which way the user intended it to be oriented. This check does still allow for broadcasting of inputs, so a Nx1 array would still work (and it would be a simple work-around for any users that depended on the atleast_2d() behavior).

@tacaswell , I am assuming we are holding off on merging any non-critical PRs until after you branch 1.5?

**Comment by Tillsten** [comment]
As questioned in the issue: Is there ANY useful usage of a 1-dim Z input? I can't imagine one. On other hand i spend time due to the current behavior hiding a bug in my code.

**Comment by WeatherGod** [comment]
Never claimed there was. The current behavior came about as the result of adding broadcasting abilities, which was specifically requested for 1-D X or Y inputs. The ability to broadcast Z was merely a natural side-effect of that feature.

**Comment by WeatherGod** [comment]
I should note that the documentation does say that inputs should be 2D.

**Comment by Tillsten** [comment]
Sorry i am confused, i don't touch the broadcasting of x and y?

**Comment by WeatherGod** [comment]
I only mentioned broadcasting of X and Y because it was the addition of that feature a few years ago that introduced this "bug/feature" that you are fixing now. The only question is if it really is a bug or not. I am leaning towards it being a bug that needs to be fixed.

**Comment by WeatherGod** [comment]
Oh, it looks like the same problem is in `plot_wireframe()`.

**Comment by tacaswell** [comment]
Yes please.  I plan to set up a 1.5.x and 2.x branches after tagging rc2

**Comment by tacaswell** [comment]
@WeatherGod If you think this should be in 1.5 move it.

**Comment by WeatherGod** [comment]
This is non-critical. It can wait.

**Comment by tacaswell** [comment]
@Tillsten or @WeatherGod can you also apply the same fix to `plot_wireframe`?

I don't think think this breaks back compatibility because a) we can't quite figure out how it would work b) the new behavior matches the docstring.

Inclined to not back-port this for 2.0.x, but it would be very easy to convince me otherwise.

**Comment by WeatherGod** [comment]
@tacaswell, this PR applied the fix to both plot_surface and plot_wireframe.

As for backporting, I would be against that. The old code would have done something correct-ish if either the X or Y arrays were 2D.

**Comment by tacaswell** [comment]
:sheep: Sorry for missing that.

RE backporting, sold.

**Pull request merged**
