### PR TITLE
Remove the system_monitor example.

### PR DESCRIPTION
**Pull request by anntzer**
It drives an animation in a fairly roundabout way (one should just use
plt.pause() (as shown in animation_demo) if not using the animation
framework), and the example title isn't particularly related to the
content either.

OTOH it is one of the oldest examples in the repo, dating back to the
12th overall commit :)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
I kinda like this example....

**Comment by anntzer** [comment]
Not going to fight about its removal (close the PR if you just want to say no), but I do think that the example is a bit silly...

**Comment by NelleV** [comment]
I'm in favor of removing it, so :+1: on this PR for me.

**Comment by tacaswell** [comment]
I think that this is something we should document how to do, but with more context, this should be covered in #4779 .

**Pull request merged**
