### PR TITLE
Re-run boilerplate.py.

### PR DESCRIPTION
**Pull request by anntzer**
Also remove second blank line between cmap definitions, consistently
with the other wrapper functions.

xref https://github.com/matplotlib/matplotlib/pull/11234#issuecomment-389027797

Planning to selfmerge as "unbreaking the build".

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Merging to fix build issues.

**Comment by timhoffm** [comment]
Just a remark:

> Also remove second blank line between cmap definitions, consistently
with the other wrapper functions.

Technically, PEP-8 wants two blank lines between top-level functions. Not sure why it does not complain. Maybe we have deactivated that check, or the comment counts as blank line. Didn't check.

**Comment by anntzer** [comment]
1) It's probably disabled for that specific file
2) PEP8 also says "Extra blank lines may be used (sparingly) to separate groups of related functions. Blank lines may be omitted between a bunch of related one-liners (e.g. a set of dummy implementations)."  Yes, these are strictly speaking not one-liners, but I think it's close in spirit (and think 2 blank lines are totally pointless here).

**Comment by tacaswell** [comment]
Thank you @anntzer !

**Pull request merged**
