### PR TITLE
[MRG+1] Fix captions for plot directive in latex target

### PR DESCRIPTION
**Pull request by jarrodmillman**
Builds on  #4702

### CODE REVIEW

**Comment by jarrodmillman** [comment]
The error appears to be unrelated to the change I made.  It appears to be an issue with an incomplete download.

```
Downloading from http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
Traceback (most recent call last):
  File "bootstrap-obvious-ci-and-miniconda.py", line 103, in <module>
    install_obvci=not args.without_obvci)
  File "bootstrap-obvious-ci-and-miniconda.py", line 71, in main
    urlretrieve(URL, basename)
  File "C:\Python27\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "C:\Python27\lib\urllib.py", line 289, in retrieve
    "of %i bytes" % (read, size), result)
urllib.ContentTooShortError: retrieval incomplete: got only 67854 out of 40918392 bytes
Command exited with code 1
python visual_tests.py
Traceback (most recent call last):
  File "visual_tests.py", line 11, in <module>
    import six
ImportError: No module named six
Command exited with code 1
```

**Comment by tacaswell** [comment]
@mdboom I think you are the only person around here how knows enough sphinx to review this.

**Comment by tacaswell** [comment]
That said, this seems reasonable to me and I am willing to believe @jarrodmillman that this works.

**Comment by NelleV** [comment]
Hi @jarrodmillman,
Thanks for the patch!
Do you mind rebasing? This branch is a bit old…
Cheers,
N

**Comment by jarrodmillman** [comment]
@NelleV I've rebased.  One test failed:
https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.2668/job/s5uiy60v9mdioyty

But according to the log, it was a problem cloning the repo:
```
Build started
ECHO %PYTHON_VERSION% PYTEST=%USE_PYTEST% %CONDA_INSTALL_LOCN%
2.7 PYTEST=no C:\Miniconda
git clone -q https://github.com/matplotlib/matplotlib.git C:\projects\matplotlib
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
Command exited with code 128
python visual_tests.py
python: can't open file 'visual_tests.py': [Errno 2] No such file or directory
Command exited with code 2
```

It wasn't apparent to me how to get AppVeyor to try the build again.

**Comment by jarrodmillman** [comment]
I rebased again and now there is a different failure:
https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.2694/job/4xtfn67it73jrf6p

Here is the complaint:

```
======================================================================
FAIL: matplotlib.tests.test_backend_pgf.test_pdflatex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\test-environment\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 150, in wrapped_callable
    func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\testing\decorators.py", line 476, in backend_switcher
    result = func(*args, **kwargs)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_backend_pgf.py", line 106, in test_pdflatex
    compare_figure('pgf_pdflatex.pdf', tol=0)
  File "c:\projects\matplotlib\lib\matplotlib\tests\test_backend_pgf.py", line 49, in compare_figure
    raise ImageComparisonFailure(err)
ImageComparisonFailure: Error: Image files did not match.
  RMS Value: 14.0418635074
  Expected:  
    C:\projects\matplotlib\result_images\test_backend_pgf\expected_pgf_pdflatex_pdf.png
  Actual:    
    C:\projects\matplotlib\result_images\test_backend_pgf\pgf_pdflatex_pdf.png
  Difference:
    C:\projects\matplotlib\result_images\test_backend_pgf\pgf_pdflatex_pdf-failed-diff.png
  Tolerance: 
    0
----------------------------------------------------------------------
Ran 6166 tests in 1671.759s
FAILED (KNOWNFAIL=37, SKIP=24, failures=1)
```

I took a look at `pgf_pdflatex_pdf.png` and `expected_pgf_pdflatex_pdf.png`.  I doesn't appear the error was related to my modification of the Sphinx PDF template.  However, I am not sure what happened.

I'll rebase again soon and see if the error persists.

**Comment by NelleV** [comment]
Hi Jarrod,
The appveyor tests are very unreliable: I wouldn't worry too much about this.
Thanks for rebasing. I'll test on my computer tonight.

**Comment by NelleV** [comment]
This looks good to me. :+1: 
@jarrodmillman by curiosity, do you use the plot directive in any projects?

**Pull request merged**
