### PR TITLE
Give wide code blocks a scrollbar on website

### LINKED ISSUE #8153: Long lines in literal blocks run off the edge of the page
e.g.
screen shot 2017-02-25 at 12 44 54

I assume the fix is to make the box scrollable, which would probably be an upstream fix.

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #8153

### CODE REVIEW

**Comment by NelleV** [comment]
I don't think this is the approriate fix.

**Comment by dstansby** [comment]
The git example is one area where this happens; I'll be there's a few others, and 99% of the time code never overruns the box. When it does I think having a scrollable box is way better than lines running off into the sidebar!

**Comment by NelleV** [comment]
IMO, those places should be fixed individually by following good practices, not by adding a scrollbar (which is really not a good usability solution).

I won't approve this PR but I am not blocking it either.

**Comment by anntzer** [comment]
You should use `auto` instead of `scroll` so that only the few boxes that need it get a scrollbar.

I agree that we should try as much as possible to get rid of overly wide boxes, but 1. it's not so easy to check them (AFAICT) and 2. you never know what the window width of the reader is.

**Comment by anntzer** [comment]
thanks!

**Comment by tacaswell** [comment]
backported to v2.0.0-doc as fa76580e44799dab6ae8392c66b562aa4a359db4

**Pull request merged**
