### PR TITLE
Bump minimum NumPy version to 1.23

### PR DESCRIPTION
**Pull request by oscargus**
## PR summary

I take it that we will stick with 1.22 for MPL 3.9. Probably we could have gone to 1.23, but I recall that we are a bit conservative here: https://numpy.org/neps/nep-0029-deprecation_policy.html

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by oscargus** [comment]
Seems like it is not trivial to install numpy 1.26 (probably because of Meson) on CygWin (hence, the pinning in the install step). However, since build isolation is used, it will try to reinstall an unpinned version.

The minver test is probably related, although I cannot really find anything specific in the 1.22 release notes that seems related. The PR that introduced the failing test is: https://github.com/matplotlib/matplotlib/pull/26253

**Comment by oscargus** [comment]
Seems like there are two floating-point related errors with 1.22. Since these are really small, should I just add a bit of tolerance (and a note that these are for NumPy 1..2)?

**Comment by QuLogic** [comment]
I've had to bump tolerance on at least one of those failing tests in Fedora https://github.com/fedora-python/matplotlib/commit/d429c3d4b548a976bc9eac437fca09fdfe784fa8 (though I cheated a little bit and put it in the non-x86 commit). I think it's likely to be the SIMD optimization issue that we've run into with newer NumPy.

**Comment by QuLogic** [comment]
We discussed on the call today and decided to go directly to 1.23, so I've pushed that, and also updated the missed `pyproject.toml`.

**Review by tacaswell — APPROVED** [review]

**Review by ksunden — APPROVED** [review]

**Pull request merged**
