### PR TITLE
mathtext: Fix bugs in conversion of apostrophes to primes

### LINKED ISSUE #5864: mathtext mishandling of certain exponents
From [the second example for twin axes in AxesGrid1](http://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#example-2-twin), where the intent was probably to have a "seconds of angle" symbol:
```
$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt; plt.gca().set_xlabel("$^{''}$/yr"); plt.show()
<matplotlib.text.Text object at 0x7f6451604f98>
```
(same result from within ipython with `%matplotlib` active)
screenshot_20160116_211600

> EDIT: This part is invalid and should be ignored
> Weirdly enough, running the same command from with `python -c` a different result:
```
$ python -c 'import matplotlib.pyplot as plt; plt.gca().set_xlabel("$^{''}$/yr"); plt.show()'
```
screenshot_20160116_211836

> (checked without any matplotlibrc).

Preempting @tacaswell to @zblz this time :-)

### PR DESCRIPTION
**Pull request by zblz**
- Fix #5864: wrong typesetting of `$''/yr$` by recognising apostrophes in first position as part of the superscript.
- Fix the width of the superscript block when generated from apostrophes. For some reason the `Hlist.extend` method does not recompute the kerning (so in strings like `$f''''(x)$` the primes would overrun the parens and the x), so I added an `hpack()` and `kern()` calls after extending. 

I also modified an existing test to include the two bugs fixed.

### CODE REVIEW

**Comment by QuLogic** [comment]
This is really minor, but it seems like with the serif font, the `f` and single prime are slightly closer together than with triple primes. Is there some ligature invoked there?

**Comment by zblz** [comment]
@QuLogic - There is indeed a slight difference in the `dejavuserif` version. However, it is also present when typesetting it with `\prime` instead of apostrophes, so it is not related to the things done in this PR. Note that italics `f` are particularly troublesome with respect to kerning; see #4987.

**Comment by zblz** [comment]
ping @mdboom

**Comment by mdboom** [comment]
Backported to v1.5.x as cd866e9

**Pull request merged**
