### PR TITLE
DOC: Add an option to disable Google Analytics.

### LINKED ISSUE #5823: pleas dont include the Google Analytics tracking in the off-line doc
Hey hey! even in the offline docs (as shipped in the source tarball) there is the Google Analytics tracking code, which is rather bad from a privacy point-of-view; please either provide a way to disable it or wrap it around some code taht only enables it if the visited website is matplotlib.org. thanks!

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Fixes #5823.

## PR Checklist

- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by dstansby** [comment]
Is there a way to more intelligently only add the google analytics code for pages served on matplotlib.org? If not this seems like a good solution.

**Review by tacaswell — APPROVED** [review]

**Comment by timhoffm** [comment]
> Is there a way to more intelligently only add the google analytics code for pages served on matplotlib.org? If not this seems like a good solution.

Can't we configure the build to not include analytics by default, and only optionally enable it via a parameter [`sphinx-build -D`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-D) or [`sphinx-build -A`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-A).
Then, only set that parameter for the [release doc build](https://matplotlib.org/devel/release_guide.html#build-and-deploy-documentation).

**Comment by QuLogic** [comment]
Ah, I didn't see that in Sphinx; that seems a good way to do it.

**Review by timhoffm — APPROVED** [review]
Waiting for another review since @tacaswell's approval was for another solution.

**Pull request merged**
