### PR TITLE
Add entry for blume to thirdparty package index

### PR DESCRIPTION
**Pull request by swfiua**
## PR Summary

Document the blume package which provides an alternative table module.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
It looks like the doc build failure is real:
```
/home/circleci/project/doc/thirdpartypackages/index.rst:5: WARNING: Duplicate explicit target name: "github repository".
```

**Comment by swfiua** [comment]
Fixed up the duplicate reference.

btw is there a reason the sphinx makefile uses pythono rather than python3?

**Comment by jklymak** [comment]
Because on the compiling machines python == python3?

**Comment by swfiua** [comment]
Somewhat confusing if you are on any kind of normal machine where python is
still very much python 2.

Shouldn't there be a note about this in the doc building docs?

**Pull request merged**
