### PR TITLE
Updates to plot types

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

- Change plot_types categories:
  - barbs: stats -> arrays
  - pie: basic -> stats
- Update plot_types barbs to show a more realistic use case:
  Barbs are a visualization of vector fields and usually plotted on a
regular grid.
- Simplify data generation for imshow and pcolormesh plot_types

### CODE REVIEW

**Comment by story645** [comment]
I have mixed feelings about pie charts since they're one of the most widely used almost everyone learns about them charts. Is turning counts into rations considered a computation?

**Comment by timhoffm** [comment]
> Is turning counts into rations considered a computation?

Sure. The distribution of fractions of a whole is genuinely a statistical topic.

The second and didactic motivation for the move is to deemphasize pie charts by placing them further down in a more specialized section. While it may be that "they're one of the most widely used almost everyone learns about them charts", typically there are better visualizations than pie charts https://www.google.com/search?q=don%27t+use+pie+charts. So let's show other plot types first. If we get someone to not choose a pie chart because they see something else first, I consider this a plus.

**Comment by jklymak** [comment]
I agree with moving `barbs.py`.  OTOH, its pretty specialized, and I kind of wonder if it should really be in here.

If we keep it, can it get the same flow field as `quiver`?  They are really alternate ways to show the same thing.

**Comment by timhoffm** [comment]
> I kind of wonder if it should really be in here.

I'd tend to keep more types in here. We should show what we can. The preview pictures are small enough that some more plots don't significantly harm the overview. OTOH I don't have a strong opinion here.

> If we keep it, can it get the same flow field as `quiver`? They are really alternate ways to show the same thing.

I find it hard to invent a dataset that illustrates both types of plots in the small previews well. Barbs have a more complex marker structure than arrows, so we need them to be bigger. While we could have equally few arrows, that'd be a less good vector field impression of quiver that is possible without that restriction on size and number of markers. Additionally, Barbs want a fixed scale of ~100 to show a variety of barb symbols. OTOH, such a dynamic range in arrow lengths is impractical as you'd only see the few largest arrows.

You are welcome to propse different data. I'm not attached to my choice. The data should just make sense for the individual visualizations.

One a side note: As discussed previously with quiver/streamplot, I don't see "using the same data" as a particular high priority between plot types. Sure if it's doable, but not at the cost of harming the visual impression of that plot type.

**Review by jklymak — APPROVED** [review]
I'm fine with the change, but lets make sure @story645 still is...

**Comment by timhoffm** [comment]
Thanks @jklymak, @story645 !

**Pull request merged**
