### PR TITLE
DOC: explain how to make a fixed-size axes

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Also added some facecolor to some of the figures that could use it.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by jklymak** [comment]
https://output.circle-artifacts.com/output/job/ddc569b7-fef5-4ed9-95e4-66d282c8502a/artifacts/0/doc/build/html/tutorials/intermediate/arranging_axes.html#adding-single-axes-at-a-time

**Comment by rcomer** [comment]
Huh.  I didn’t know you could pass a position into `add_subplot`, and would have expected this example to use `add_axes`.  Even now I know, the [docstring](https://output.circle-artifacts.com/output/job/ddc569b7-fef5-4ed9-95e4-66d282c8502a/artifacts/0/doc/build/html/api/figure_api.html#matplotlib.figure.Figure.add_subplot) is confusing: `pos` is listed in the valid call signatures, but not described under parameters.

So is `add_axes` redundant api or is there some difference in what you would get?

**Comment by jklymak** [comment]
Switched to add_axes.  I actually meant to do that originally.  

I don't understand why CI is running.  I thought the Actions check would work here...

**Comment by jklymak** [comment]
@rcomer is this OK now?

**Review by rcomer — APPROVED** [review]

**Pull request merged**
