### PR TITLE
ci: Fix linting being ignored by reviewdog

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Checklist

- [n/a] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [n/a] New features are documented, with examples if plot related
- [n/a] Documentation is sphinx and numpydoc compliant
- [n/a] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [n/a] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm not entirely sure why it didn't complain in #17822, but I've disabled the filter entirely. For certain reporters, errors outside the diff would be a problem, but this does work with the one we are using. And we want to catch things that might be outside the diff, like imports no longer being used.

**Comment by tacaswell** [comment]
I'm 50/50 on backporting the linting config to 3.3.x.

**Comment by dopplershift** [comment]
Since we never merge from 3.3.x to master, it might not be worth it. The branch has a life of what, 6-12 months?

**Comment by QuLogic** [comment]
We do merge up; I plan to do so after 3.3.1, as it fixes the `git describe` result.

**Comment by dopplershift** [comment]
Ah, ok. Then yes (as you've done)

**Pull request merged**
