### PR TITLE
Use traditional linestyle shortcuts

### PR DESCRIPTION
**Pull request by ycopin**
'-'=solid, '--'=dashed, ':'=dotted, '-.'=dashdot. The conversion is done on the fly, no other changes needed in the code.

### CODE REVIEW

**Comment by tacaswell** [comment]
What is the motivation for this?  The graphics context is a very internal thing so we can be very picky about it's input.

**Comment by WeatherGod** [comment]
Isn't there already a PR trying to solve this, and it got mired down in
edge cases?

**Comment by WeatherGod** [comment]
Btw, consistency is the motivation for this. I opened issue #2136 a while
back when I noticed this. And the open PR is #3772

**Comment by tacaswell** [comment]
@WeatherGod The other PR is taking care of this validation/consistency at the `Artist` level, not at the `GraphicsContext` level.  We shouldn't do normalization in both places and should do the normalization/validation as close to the user as possible (so that they get an exception at artist creation time, not at draw time).

**Comment by WeatherGod** [comment]
I agree with that. I just wanted to make sure that we choose this PR for
lack of another solution, or maybe we decide that this is better than the
rather extensive changes shown in the other PR. I like having ducks in a
row.

**Comment by WeatherGod** [comment]
err..  *not* choose

**Comment by tacaswell** [comment]
I think the other PR is very close.  It needs a final review but I have not
had time to get back to it.

**Comment by ycopin** [comment]
Sorry for not having seen the other PR, which is indeed way more complete (including user-level documentation). Yet I don't understand comment "get an exception at artist creation time, not at draw time". As for now, an invalid linestyle is  intercepted in `GraphicsContextBase.set_linestyle()` in `backend_bases.py`, not any time sooner (this is how I found it).

**Comment by WeatherGod** [comment]
Right. The point is that if an exception is thrown at draw time, the user
will have a harder time tracing the problem back to its origin. Whereas if
we raise the exception at the call to plt.plot() or some other plotting
function for invalid values, it would be much easier to debug.

**Comment by tacaswell** [comment]
iirc, one of the things that #3772 does is to push the exceptions up to creation time.

**Comment by efiring** [comment]
I think this is superceded by #3772 which has now been merged.  If not, please reopen it.  In any case, thank you for the contribution.

**Pull request closed without merging**
