### PR TITLE
MEP12 on alignment_test.py

### PR DESCRIPTION
**Pull request by domspad**
pylab to plt

### CODE REVIEW

**Comment by domspad** [comment]
hey @jenshnielsen, just a quick clarification on these pull requests - since we are just correcting the `from pylab import *` parts of the (MEP12)[https://github.com/matplotlib/matplotlib/pull/2474] issue right now with these examples. If I make any more changes to them with regards to the other bullet points in MEP12, should they be in a new branch? Or can I continue on this branch even though it is closed?

**Comment by jenshnielsen** [comment]
@domspad Thanks for all your work. You can continue on the same branch as long as the pull request is not merged when it is merged please open a new one to make more changes. You can probably open a new pull request from the same branch (Github should automatically detect that some of the commits have been merged) but for clarity I would recommend that you open a new one.

**Comment by jenshnielsen** [comment]
@domspad however if you want to do more work on an open pull request please just leave a note about not merging it, or better edit the title to say don't merge yet or something.

**Comment by WeatherGod** [comment]
I usually add a "[WIP]" to the name of the PR if it is a work in progress.

**Pull request merged**
