### PR TITLE
Improve docs of toplevel module.

### PR DESCRIPTION
**Pull request by anntzer**
Hiding the huge RcParams.validators list, putting some sections, and
reordering some functions in a more logical order?

Before: https://matplotlib.org/devdocs/api/matplotlib_configuration_api.html
After: https://8397-7439715-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/matplotlib_configuration_api.html

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
https://matplotlib.org/devdocs/tutorials/introductory/customizing.html#a-sample-matplotlibrc-file should provide the relevant info.

**Comment by story645** [comment]
@timhoffm & @anntzer  - would a follow up PR that documents that RC file in nice organized tables make sense or not worth it?

**Comment by timhoffm** [comment]
@story645 yes, I think so. This would also be a good link target for our :rcparams: directive.

**Comment by anntzer** [comment]
added the link to the tutorial.

**Pull request merged**
