### PR TITLE
Fixed not being able to set vertical/horizontal alignments in polar graphs

### PR DESCRIPTION
**Pull request by Charlesruan**
## PR Summary
Previously polar graphs could not have their vertical/horizontal alignments set by set_rgrids(), this fix should re-enable this functionality.

[Issue #10105](https://github.com/matplotlib/matplotlib/issues/10105)
## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant

### CODE REVIEW

**Comment by Charlesruan** [comment]
I believe [this](https://github.com/matplotlib/matplotlib/pull/9068) pull request is what caused this regression.

**Comment by pbregener** [comment]
Would love to see this simple patch backported to `v2.2.x` as well :+1:

**Comment by OD1995** [comment]
@Charlesruan @pbregener is this fix live? If so, how can I take advantage of the changes?

**Comment by pbregener** [comment]
This MR is not merged, yet, so it's not "live" in the sense that it is part of any release or even current master. I guess the 5 commits should be squashed into one with a sensible commit message and then some maintainer should review and eventually merge it.

**Comment by ImportanceOfBeingErnest** [comment]
There is also this regression on polar plots:  #10882 
Are they related?

**Comment by jklymak** [comment]
PRs need to reviews.  This looks reasonable, but it would be nice to know what PR the regression came in from and wether this was just an oversight or a design decision.

**Comment by pbregener** [comment]
@jklymak This goes back to #9068 and therefore `v2.1.0`. Also see the original issue for this: #10105

**Comment by jklymak** [comment]
Thanks.  ping @QuLogic who is the local polar expert.

**Comment by dopplershift** [comment]
If this really is a regression, it should probably be milestoned for v2.2.3

**Comment by jklymak** [comment]
Its a 2.1 regression.  Not sure on the policy there.

**Comment by pbregener** [comment]
It is a regression and as mentioned above, I would love to see this in `v2.2.x`. Should be really easy to backport, too.

Not sure about how matplotlib usually handles this, but I guess it would be nice to squash the five commits for this fairly trivial change into one @Charlesruan

**Comment by dopplershift** [comment]
@tacaswell said:

> I propose the following criteria for backporting PRs to the 2.2.x branch.  We always will backport 
> - critical bug fixes (segfault, failure to import, things that the user can not work around)
> - fixes for regressions against 2.0 or 2.1 

This would seem to fit.

**Comment by Charlesruan** [comment]
Commits have been squashed

**Comment by pbregener** [comment]
ping @jklymak and especially @QuLogic for an update on this PR?

**Comment by phobson** [comment]
@Charlesruan thanks so much for this PR and your patience with the process!

**Pull request merged**
