### PR TITLE
WIP: updated defult boxplot styles

### PR DESCRIPTION
**Pull request by phobson**
I'm sort of flailing around at the moment.

Not exactly sure how you want the defaults modified. I just took at crack at the rcParams that are currently (see #5441) available.

 - [x] add test imates
 - [ ] clean up redundant style checking between `bxp` and `boxplot`
 - [ ] medians not showing up with custom patch artists: https://github.com/matplotlib/matplotlib/pull/5523/files#diff-ac6c423875c2703c15afceabfdaf3692

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks.  I'll incorporate this in the huge stack of other style changes we are doing for 2.0.

It might be helpful to update the test images in a separate commit so we can see and review the changes here...

**Comment by mdboom** [comment]
Thanks.  This for the most part looks good.  The only change I would suggest is that instead of hardcoding `b`, which will always be blue, we should use `[0]` after #5674 (or something like it) is merged.

**Comment by tacaswell** [comment]
ping @phobson The color cycle color selector is now merged (as `'C0'`, `'C1'`, ...)

**Comment by phobson** [comment]
thanks. @tacaswell. should I rebase off of master or 2.x?

**Comment by tacaswell** [comment]
as this PR is against master, rebase on master

**Comment by jenshnielsen** [comment]
Looks like the image tests are not using the classic style so we will need to also update the test images or switch the boxplot image tests to use the classic style.

**Comment by phobson** [comment]
prefixed https://github.com/matplotlib/matplotlib/pull/5523/commits/b2c8cca35a1c7bf6d6457e0ad2440b2851de9ed7 as "WIP" since:

  1. there's gotta be a better way; and 
  2. there has to be some redundency with the style checking in `Axes.boxplot`. IOW, some of the style checking should be moved from `boxplot` to `bxp`.

I've add some TODO's to the original message up top

**Comment by phobson** [comment]
Just the test images:
https://github.com/matplotlib/matplotlib/pull/5523/commits/b2d20e80c2c5f2214216f9e9300a611680a31701

**Comment by tacaswell** [comment]
Locally I am seeing

```
matplotlib/lib/matplotlib/__init__.py:1096: UserWarning: Bad val "auto" on line #341
        "boxplot.flierprops.markerfacecolor: auto
"
        in file "/home/tcaswell/source/p/matplotlib/lib/matplotlib/mpl-data/stylelib/classic.mplstyle"
        Key boxplot.flierprops.markerfacecolor: auto does not look like a color arg

```

**Comment by tacaswell** [comment]
Closing this in favor of #6481

**Pull request closed without merging**
