### PR TITLE
Pin pytest<4.1 to unbreak CI tests

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Temporary fix for #13121.

This can be undone once a new pytest-cov release is out.

### CODE REVIEW

**Comment by jklymak** [comment]
Though should it just be !=4.1 ?

**Comment by hugovk** [comment]
Pytest > 4.1 will still have the same feature removed, so I think < 4.1 makes more sense until there's a new pytest-cov release.

**Comment by timhoffm** [comment]
I hope that there will be a pytest-cov release soon since it's affecting all pojects using pytest-cov. This question is raised here https://github.com/pytest-dev/pytest-cov/pull/253.

Therefore, I would wait for an answer of the pytest-cov developers before pinning and later unpinning the other branches manually.

**Comment by tacaswell** [comment]
@timhoffm fair enough.

**Comment by timhoffm** [comment]
pytest-cov 2.6.1 has just been released. So no need to backport anymore.

**Comment by timhoffm** [comment]
How do we unpin pytest?

Bump pytest-cov dependency to 2.6.1? That implies pytest>=3.6 (currently >=3.4). But I think that's ok.

**Pull request merged**
