### PR TITLE
Deprecate passing most Legend arguments positionally

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

There are so many of them, it really doesn't make sense to do positionally.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by timhoffm — APPROVED** [review]

**Review by oscargus — APPROVED** [review]

**Comment by timhoffm** [comment]
While at it, should we do this for most Artists?

**Comment by QuLogic** [comment]
Probably; I noticed this in #23140 (which has since dropped the new argument to `Legend`), but I'm sure it can apply to most of the others.

**Comment by EwoutH** [comment]
I couldn't find this change in the [API Changes for 3.6.0](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html), should I look somewhere else for the documentation on this?

**Comment by QuLogic** [comment]
#23177 made it generally applicable to all `Artist`s; it is the entry [here](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.6.0.html#positional-keyword-arguments).

**Pull request merged**
