### PR TITLE
Fixes issue where toolbar tools wouldn't shown when selected - wxpython and macOS

### PR DESCRIPTION
**Pull request by jbhopkins**
## PR Summary
This fixes the bug identified in issue #16701: "When using the WxAgg backend on MacOS, if you select a tool in the toolbar you essentially can't tell that the tool is selected. There is only a very small change in the appearance. On other platforms (linux, windows) it is very obvious that the tool is selected."

As suggested in that issue, I converted from using the `wx.Toolbar` to the `wx.lib.agw.buttonpanel`, which is a native python widget providing full control over the appearance of the toolbar. This fixes the bug, as well as fixing an addition bug where on Windows the old toolbar didn't have clearly disabled forward/back buttons when appropriate.

While I have some concerns (see below) about the change, there doesn't seem to be any other way to fix this issue and maintain a toolbar that can be placed anywhere in a wxpython frame without making changes in wxwidgets itself.

Results:
MacOS:
Old (zoom tool highlighted):
mac_mpl_toolbar_old

New:
mac_mpl_toolbar_new

Windows 10:
Old (forward button disabled):
win10_mpl_toolbar_old

New:
win10_mpl_toolbar_new

Ubuntu 18.04:
Old:
ub18_mpl_toolbar_old

New:
ub18_mpl_toolbar_new

Concerns:
I've put in a few convenience functions -- `AddTool`, `AddCheckTool`, `ToggleTool`, and `EnableTool` -- that increase backwards compatibility, but this change may break compatibility for someone who has customized a toolbar based on adding their own tools. For example, to bind a tool event you now need to use `wx.EVT_BUTTON` instead of `wx.EVT_TOOL,` which means that custom controls that bind `wx.EVT_TOOL` will no longer work. Also, because it's subclassing `buttonpanel` instead of `Toolbar` there are wxwidget specific methods that are different between the two that may break compatibility.

Additionally, there is a bug in `buttonpanel` that causes display issues with high resolution icons on MacOS on a retina display, so those using custom icons at high resolution will encounter that (though I will open a PR about this for wxpython).

It also loses the 'native' look of the toolbar widget on windows and linux. Not something I personally worry about, but since part of the appeal of wxpython to some may be the native style I suppose it could be an issue.

Finally, I understand that this may need to be documented in the api_changes, but it wasn't clear to me what the best way to do that was. The specific API functions that have changed are those attached to change from `ToolBar` to `buttonpanel` widgets, which are a lot functions to document. I'm happy to make changes if someone can suggest the best approach.

## PR Checklist

- [ ] Has Pytest style unit tests
- [X] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
Thanks for digging into this!

Is it correct that we do this dance just because the `wx.Toolbar` does not render toggle buttons well on OSX? I‘m concerned that is solution may cause more harm than it‘s worth. We loose the native look and feel on all platforms and introduce breaking changes.

My first impression was that this should be fixed on the wx side. OTOH, if we really want to work around this ourselves, would it be an option to fake a toggle button by subclassing a regular button, storing click state and exchanging the icon when changing the state?

**Comment by jbhopkins** [comment]
Yes, this is to get around what seems to be a bug in wx.Toolbar on MacOS. Ideally it would be addressed in wxwidgets, but it looks like the current situation may be a fix from a different bug, based on a link Robin Dunn shared in issue #16701.
https://trac.wxwidgets.org/ticket/16645

This is why I think it's probably best to fix it (or at least work around it) on the matplotlib side. 

Based on the wx.Toolbar documentation, I don't think directly modifying the button is possible, but we can modify the button bitmap through the toolbar itself. Since the toggle buttons are already bound and have methods in the NavigationToolbar code, it wouldn't be too hard to generate the appropriate icon and swap it in and out.

The upside to this approach would be maintaining backwards compatibility and native styling. However, the downside is that it doesn't actually fix the bug. So if users are adding their own custom toggle buttons, they will have to do the same thing to bind and swap to get the right appearance. The solution proposed in this pull request fixes that, and any tool added to the toolbar will work, but at the cost of backwards compatibility and the native styling.

If you think that the later approach is a good option, I'm happy to give it a try and see how it works. Since I don't have a ton of experience with git, is there a way I could attach a second branch or pull request to this one, or would I need to open a new pull request for the alternative solution?

**Comment by anntzer** [comment]
I don't know if we want to fix the solution here rather than try again to get it fixed upstream, but if we do want to fix it here, I think we should at least gate this to be OSX only and keep the old code path on Linux and Windows -- no need to break native theming there.

**Comment by jbhopkins** [comment]
If someone wants to open up a wxwidgets ticket for this that would be fine by me. In the meantime, I've made a version that just creates a custom bitmap. It uses the native wx.Toolbar and just swaps the bitmaps in and out, as suggested by @timhoffm, and it only changes the MacOS toolbar as suggested by @anntzer. 

The main concerns I have with this approach are:
1) If a user adds custom toggle tools they'll have to do the same thing.
2) If a user toggles the pan or zoom tool programmatically (self.ToggleTool) it won't properly update the image.

I made it in a separate branch, in case we wanted to come back to the buttonpanel approach. The code is here:
https://github.com/jbhopkins/matplotlib/tree/wx_toolbar_fix2

I don't know if you want me to update this branch with the new code, open a new pull request, or what. 

Below is an image of how the tool looks on the new branch.
macos_toolbar_zoom_active

Here's the relevant bits of code in their updated version. There's probably a more efficient way to generate the toggled bitmap, but using wx DCs to draw is not something I've ever done before.

```python
class NavigationToolbar2Wx(NavigationToolbar2, wx.ToolBar):
    def __init__(self, canvas):
        wx.ToolBar.__init__(self, canvas.GetParent(), -1)
        NavigationToolbar2.__init__(self, canvas)
        self.canvas = canvas
        self._idle = True
        self.prevZoomRect = None
        # for now, use alternate zoom-rectangle drawing on all
        # Macs. N.B. In future versions of wx it may be possible to
        # detect Retina displays with window.GetContentScaleFactor()
        # and/or dc.GetContentScaleFactor()
        self.retinaFix = 'wxMac' in wx.PlatformInfo

    def get_canvas(self, frame, fig):
        return type(self.canvas)(frame, -1, fig)

    def _init_toolbar(self):
        _log.debug("%s - _init_toolbar", type(self))

        self._parent = self.canvas.GetParent()

        self.wx_ids = {}
        self.bitmaps = {}
        for text, tooltip_text, image_file, callback in self.toolitems:
            if text is None:
                self.AddSeparator()
                continue

            bitmap = _load_bitmap(f"{image_file}.png")
            if text in ["Pan", "Zoom"]:
                self.bitmaps[text] = {"Normal": bitmap,
                    "Toggled": self._make_toggled_bitmap(bitmap)}

            self.wx_ids[text] = (
                self.AddTool(
                    -1,
                    bitmap=bitmap,
                    bmpDisabled=wx.NullBitmap,
                    label=text, shortHelp=text, longHelp=tooltip_text,
                    kind=(wx.ITEM_CHECK if text in ["Pan", "Zoom"]
                          else wx.ITEM_NORMAL))
                .Id)
            self.Bind(wx.EVT_TOOL, getattr(self, callback),
                      id=self.wx_ids[text])

        self.Realize()

    def _make_toggled_bitmap(self, bitmap):
        bmp = bitmap.ConvertToImage().ConvertToBitmap()
        bmp2 = bitmap.ConvertToImage().ConvertToBitmap()
        brush = wx.Brush(wx.Colour(167*0.85, 167*0.85, 167*0.85))
        pen = wx.Pen(wx.Colour(167*0.85, 167*0.85, 167*0.85))
        dc = wx.MemoryDC()
        dc.SelectObject(bmp)
        gc = wx.GraphicsContext.Create(dc)
        gc.SetBrush(brush)
        gc.SetPen(pen)
        gc.DrawRoundedRectangle(0, 0, 24, 24, 4)
        gc.DrawBitmap(bmp2, 0, 0, 24, 24)
        dc.SelectObject(wx.NullBitmap)

        return bmp

    def zoom(self, *args):
        evt = args[0]
        self.ToggleTool(self.wx_ids['Pan'], False)
        NavigationToolbar2.zoom(self, *args)
        if 'wxMac' in wx.PlatformInfo:
            self.SetToolNormalBitmap(self.wx_ids["Pan"],
                self.bitmaps["Pan"]["Normal"])
            if evt.IsChecked():
                self.SetToolNormalBitmap(self.wx_ids["Zoom"],
                    self.bitmaps["Zoom"]["Toggled"])
            else:
                self.SetToolNormalBitmap(self.wx_ids["Zoom"],
                    self.bitmaps["Zoom"]["Normal"])

    def pan(self, *args):
        evt = args[0]
        self.ToggleTool(self.wx_ids['Zoom'], False)
        NavigationToolbar2.pan(self, *args)
        if 'wxMac' in wx.PlatformInfo:
            self.SetToolNormalBitmap(self.wx_ids["Zoom"],
                self.bitmaps["Zoom"]["Normal"])
            if evt.IsChecked():
                self.SetToolNormalBitmap(self.wx_ids["Pan"],
                    self.bitmaps["Pan"]["Toggled"])
            else:
                self.SetToolNormalBitmap(self.wx_ids["Pan"],
                    self.bitmaps["Pan"]["Normal"])
```

**Comment by timhoffm** [comment]
@jbhopkins thanks for working this out. Please open a separate PR for the bitmap-toggling solution.

IMHO it's the "correct" workaround on our side: It solves 90% of the issue (not the cases in your concern), but keeps the native look and does not break any API. And since we don't have an API change, it's easy to roll back if this is fixed in wx some day.

As a side-remark: Only applying the `buttonpanel` solution to OSX would not be a good solution, because it would breack cross-platform compatibility users trying to modify/add buttons.

**Comment by dstansby** [comment]
It looks like the original issue this is fixing is closed - not sure which PR fixed it, but I'm pretty sure it's fixed. As such I'm going to close this PR - thanks for the contribution, and if you think I've got something wrong shout and we can re-open this!

**Pull request closed without merging**
