### PR TITLE
[MRG+1] Fix some minor warnings in extensions

### PR DESCRIPTION
**Pull request by QuLogic**
Fix prototypes, an unused variable and some new misleading indentation warnings on GCC 6.

### CODE REVIEW

**Comment by QuLogic** [comment]
Also fixed warnings about format specifiers and doubly-defined macros.

**Comment by NelleV** [comment]
I've approved this, but this is typically things that should not go into 2.x at this point.

**Comment by QuLogic** [comment]
Admittedly, it got a bit larger than I expected (I could have sworn that `NPY_INTP_FMT` thing was done already), but besides that, these are trivial warnings to fix. Trivial warnings are always useful to fix because you never know how a user might misinterpret them. But anyway, it's only a build time thing, so that's why it's milestoned 2.0.1, not 2.0.

**Comment by tacaswell** [comment]
The unused variable came in via #5672 and was made redundant via #6764

**Comment by tacaswell** [comment]
from https://stackoverflow.com/questions/8132399/how-to-printf-uint64-t it looks like it is a difference between compilers.

**Comment by QuLogic** [comment]
Ah yes, gcc 6.2.1; I always forget it's that much newer (especially as Travis becomes older and older.)

**Pull request merged**
