### PR TITLE
For make raw_input compatible with python3

### PR DESCRIPTION
**Pull request by rishikksh20**
Fix issue #7388

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you either un-densify this (we enforce pep8/pycodestlye as part of our test suite) or use `from six.moves import input`?

**Comment by rishikksh20** [comment]
Ok

**Comment by rishikksh20** [comment]
@tacaswell its done please review it and let me know if any other modification required.

**Comment by tacaswell** [comment]
Please do not backport this until after 2.0 final is out.

**Comment by QuLogic** [comment]
Backported to `v2.0.0-doc` as 68d2327620c46cd306229e2373afdb0d5f93f1d2.

**Pull request merged**
