### PR TITLE
FIX:  parasite axis2 demo

### LINKED ISSUE #12208: parasite axis2 demo now crashes with log x-axis
### Bug report

**Bug summary**

The code from the Parasite Axes2 demo crashes when the x-axis is turned to a logarithmic scale.
This problem is new in the 2.2 branch.

**Code for reproduction**
Execute the code from Demo Parasite Axes2
  https://matplotlib.org/gallery/axisartist/demo_parasite_axes2.html
This will work correctly.
Then set the x scale to log (before the show):
``` python
  plt.xlim(.1)
  plt.xscale('log')
```
Now the program will produce many errors.

**Actual outcome**
```
Traceback (most recent call last):
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 433, in draw
    self.figure.draw(self.renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/figure.py", line 1475, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/mpl_toolkits/axes_grid1/parasite_axes.py", line 286, in draw
    self._get_base_axes_attr("draw")(self, renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/mpl_toolkits/axisartist/axislines.py", line 756, in draw
    super(Axes, self).draw(renderer, inframe)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2607, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/mpl_toolkits/axisartist/axis_artist.py", line 1479, in draw
    self._draw_ticks(renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/mpl_toolkits/axisartist/axis_artist.py", line 1211, in _draw_ticks
    self.major_ticks.draw(renderer)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/mpl_toolkits/axisartist/axis_artist.py", line 330, in draw
    locs = path_trans.transform_non_affine([loc])
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/transforms.py", line 2489, in transform_non_affine
    return self._a.transform_non_affine(points)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/transforms.py", line 2263, in transform_non_affine
    x_points = x.transform_non_affine(points)[:, 0:1]
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/transforms.py", line 2489, in transform_non_affine
    return self._a.transform_non_affine(points)
  File "/opt/anaconda2/envs/py2_conda52/lib/python2.7/site-packages/matplotlib/transforms.py", line 2265, in transform_non_affine
    x_points = x.transform_non_affine(points[:, 0])
TypeError: list indices must be integers, not tuple
```

**Expected outcome**
There should be no errors.

**Matplotlib version**
  * Operating system: linux and windows
  * Matplotlib version: 2.2.2
  * Matplotlib backend: Qt5Agg
  * Python version: 2.7.15

Installed with conda (anaconda=5.2 python=2).
Same problem with python 3.6.5.
Problem is probably there in 3.0.0 but I have not tested that.

Note that it used to work without errors with anaconda 5.1 (matplotlib=2.1.2).

**Possible fix**
The problem is probably because of commit ffb54613eacf

I can fix it by changing line 330 in mpl_toolkits/axisartist/axis_artist.py (methode draw of Ticks) from
`  locs = path_trans.transform_non_affine([loc]) `
to
` locs = path_trans.transform_non_affine(np.array([loc])) `

Another option would be to NOT use numpy indexing in transform_non_affine of BlendedGenericTransform of matplotlib/transforms.py

### PR DESCRIPTION
**Pull request by abhinuvpitale**
## PR Summary

Closes #12208   

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
@abhinuvpitale Thanks so much for your contributions.  I took the liberty of formatting your title and the start of your PR desc.  We don't need the Issue # in the PR title, but a "closes #xxxxx" in the body of the PR description allows the automatic issue closing system to work.  Thanks again!

**Comment by abhinuvpitale** [comment]
@jklymak added flake8 corrections, I should hope that it passes the ci
thanks for change in title!

**Comment by ImportanceOfBeingErnest** [comment]
@MeeseeksDev backport to v2.2.4

**Comment by ImportanceOfBeingErnest** [comment]
@MeeseeksDev backport to v2.2.x

**Comment by ImportanceOfBeingErnest** [comment]
I tried to backport to v2.2.x, because 
* this is a regression to 2.1
* a user (@lupien) requested this in https://github.com/matplotlib/matplotlib/issues/12208#issuecomment-424758692
* it looked easy to backport due to only a single line being affected

 but the suggested `git cherry-pick -m1 ed2740821c37b597e865e1483629e873c4488dc6` fails with   
`error: mainline was specified but commit ed2740821c37b597e865e1483629e873c4488dc6 is not a merge.`

At this point this is probably beyond my paygrade, but happy to continue with it if someone wants to talk me through.

**Comment by QuLogic** [comment]
It's because you did a squash merge, so there is only one parent (it's not a merge commit.) You don't need to specify `-m1` in that case.

**Comment by Carreau** [comment]
My Fault, I haven't implemented support for squash-merge into the bot. PR welcome.

**Comment by ImportanceOfBeingErnest** [comment]
If I follow this further (leaving out `-m1`) and pushing to `git push origin v2.2.x`, it'll create a PR with some 21 commits and 14 changed files from all kinds of different authors, instead of only 1 commit (2 files) that this should include. Maybe `YOURFORK` should be something else? :fork_and_knife:

**Comment by Carreau** [comment]
> 21 commits and 14 changed files from all kinds of different authors

That seem wrong this PR is 5 commits, and when you squashed you only got 1, so you should only get one in the end: 

```
 ~/dev/matplotlib[v2.2.x ✓] $ git checkout v2.2.x
Already on 'v2.2.x'
Your branch is up to date with 'origin/v2.2.x'.
 ~/dev/matplotlib[v2.2.x ✓] $ git pull
Already up to date.
 ~/dev/matplotlib[v2.2.x ✓] $ git cherry-pick ed2740821c37b597e865e1483629e873c4488dc6
error: could not apply ed2740821... FIX:  parasite axis2 demo (#12261)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
$ # Fix conflicts
$ git commit -a
```

And push that to whatever your fork is. I usually can't know what the name of the remote for your fork is, for me it's named `github`, for some it's `origin`. 

I'm not sure what "something else" would be, it has to be interpreted by the person running the command.

**Comment by QuLogic** [comment]
When you tried to open a PR, was the base branch `v2.2.x` or `master`?

**Comment by ImportanceOfBeingErnest** [comment]
> When you tried to open a PR, was the base branch v2.2.x or master?

Ups.. :rofl: I guess one has to make this mistake once, to never do it again. It's all good now. Seems the problem is the web interface which is set to "master" by default even it you're pushing to another branch.

@QuLogic Does the newly created PR need new reviews or is it usual to just merge it directly after tests have been completed?

**Pull request merged**
