### PR TITLE
issue form files

### PR DESCRIPTION
**Pull request by story645**
## PR Summary
Started drafting the issue form files. Mostly kept the same fields + content as the templates. Haven't validated them yet/deleted the templates because want to discuss:
1) which fields are required versus which are optional
2) if this is actually any better than the templates

Also how do I test that these are correct?

### CODE REVIEW

**Comment by story645** [comment]
React mixes the two styles and the textareas are free text https://github.com/facebook/react/issues/new/choose

Also, I learned that I can validate these forms by looking at 'em on github https://github.com/story645/matplotlib/tree/itemplates/.github/ISSUE_TEMPLATE

**Comment by jklymak** [comment]
I think it can't hurt to try this.  When folks fill out the forms do they have full Github functionality, like they can drag images into them etc?

**Comment by story645** [comment]
So this is what the textarea field (c/o of the react form) looks like:
image

I'm not sure if we should convert all the issues to forms though, which is why I've left both.

**Comment by jklymak** [comment]
Should we just convert them and try it for a while?  Its easy to revert if we get complaints/decide we don't like it.  I do like the idea of some mandatory fields, because it saves some time in triage...

**Comment by story645** [comment]
So I got rid of the *.md files, but which fields do folks think should be mandatory? I picked whatever I thought made sense, but likely missed some and required others nobody else thinks should be mandatory.

**Review by jklymak — APPROVED** [review]
I think this looks good and we could iterate.  Probably should get a second review from someone.

**Comment by timhoffm** [comment]
I'd make "Bugs: Backend" optional. It's not relevant for most of the bugs. Users do not necessarily know what a backend is, so it may be confusing.

"Bugs: Code for Reproduction". Shorten the description to
"If possible, please provide a minimum self-contained example."

**Comment by QuLogic** [comment]
Install source should probably have "Distro (Debian/Fedora/etc.)"

**Comment by story645** [comment]
Oh, so should I add another option (Linux package manager?) or make it a seperate freeform like the conda package? I ask for the system elsewhere - basically the form won't let me do other (freetext)

**Comment by QuLogic** [comment]
Just another option, I think. They can always leave a note in the system field or something if that's not good enough.

**Comment by QuLogic** [comment]
Let's see how it goes.

**Pull request merged**
