### PR TITLE
Update Axis docs

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Axis / tick handing will get an overhaul some time. Until then, it's helpful to know what attributes it offers.

### CODE REVIEW

**Comment by anntzer** [comment]
Anyone can merge after CI.

**Comment by NelleV** [comment]
@timhoffm Do you know why github didn't create a merge commit on that merge? It could be because you merged your own PR and there was only one commit. But then it changed the commit message, and I suppose as a result the commit hash.
(I'm interested for a project I'm working on analysing github data. I thought we could identify those merge commits easily but my hypothesis is wrong on this PR)

**Comment by timhoffm** [comment]
I pressed the „Squash and merge“ button, which is the default to be displayed here.

**Comment by QuLogic** [comment]
Not quite, it's not the default, it's the last one you used.

**Comment by timhoffm** [comment]
> Not quite, it's not the default, it's the last one you used.

Oh. I've learned something new.

**Pull request merged**
