### PR TITLE
Added DNA Features Viewer description + screenshot in docs/thirdparty/

### PR DESCRIPTION
**Pull request by Zulko**
## PR Summary

Added a section to ``docs/thirdpartypackages/index.rst`` to present [DNA Features Viewer](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer) (DNA sequence map plots with Matplotlib), as per [this Twitter discussion](https://twitter.com/matplotlib/status/1217070834268983296).

Screenshot:
dna_features_viewer_screenshot

## PR Checklist

- [X] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by Zulko** [comment]
Done!

**Comment by anntzer** [comment]
(As a tangent, writing a quick and dirty a plasmid viewer was at the origin of one of my first PRs to matplotlib: https://github.com/matplotlib/matplotlib/pull/1635 :-))

**Comment by Zulko** [comment]
Nice! My library implements an [ArrowWedge](https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/blob/master/dna_features_viewer/CircularGraphicRecord/ArrowWedge.py) on top of your Wedge.

**Comment by timhoffm** [comment]
Thanks a lot!

**Pull request merged**
