### PR TITLE
add mplsoccer to the third party packages list

### PR DESCRIPTION
**Pull request by Slothfulwave612**
## PR Summary
This adds the [mplsoccer package](https://github.com/andrewRowlinson/mplsoccer) to the third party packages list.

### CODE REVIEW

**Comment by jklymak** [comment]
@Slothfulwave612 Thanks for adding this.  We are actually in the midsts of moving this page to https://github.com/matplotlib/mpl-third-party  Would you mind terribly being a guinea pig and adding mplsoccer as a PR there?  And of course letting us know if the instructions are not clear!

**Comment by Slothfulwave612** [comment]
So, I have to make `.yml` file for mplsoccer which will contain repo, section and description; and add it to the packages directory Right?

**Comment by Slothfulwave612** [comment]
So I am create a PR, you can find it here: https://github.com/matplotlib/mpl-third-party/pull/39

**Comment by jklymak** [comment]
I'll close this here in lieu of matplotlib/mpl-third-party#39  Thanks @Slothfulwave612

**Pull request closed without merging**
