### PR TITLE
Change default interpolation to nearest

### PR DESCRIPTION
**Pull request by jenshnielsen**
#4622 agains 2.0.x

### CODE REVIEW

**Comment by jenshnielsen** [comment]
There is something seriously wrong somewhere 

This causes matplotlib.tests.test_image.test_get_window_extent_for_AxisImage to segfault at least on python 3.5

**Comment by jenshnielsen** [comment]
Furthermore a fair number of tests fail due to the change. They don't seem to pickup the classic style

**Comment by mdboom** [comment]
I don't think the test suite has been set up to forcibly use the classic style yet.

**Comment by jenshnielsen** [comment]
Ok the seqfault is genuine thou

**Comment by jenshnielsen** [comment]
I thought this was supposed to set it up to use the classic style https://github.com/matplotlib/matplotlib/blob/v2.0.x/lib/matplotlib/testing/decorators.py#L232

**Comment by WeatherGod** [comment]
It was set up to use the classic style for any image comparison test.
Something is wrong if it isn't doing that.

**Comment by mdboom** [comment]
Sorry, I missed that.  I was expecting to see that in the cleanup decorator, not the image comparison one.

**Comment by jenshnielsen** [comment]
The segfault is on master too https://travis-ci.org/matplotlib/matplotlib/jobs/89776539 
see #5429

**Comment by jenshnielsen** [comment]
rebased to fix the segfault

**Comment by tacaswell** [comment]
@mdboom is this folded into your style branch?

**Comment by mdboom** [comment]
> @mdboom is this folded into your style branch?

Yes.  And related to this (for the record) I think we should also set `image.resample` to `True` by default (see the discussion in #5718)

**Pull request closed without merging**
