### PR TITLE
Remove separate section for support of 3d subplots.

### PR DESCRIPTION
**Pull request by anntzer**
It's not "special" and doesn't warrant its own section; we can just
mention that in passing.

Also remove the "Getting started" section, which is by itself at its
level (see TOC at https://matplotlib.org/devdocs/tutorials/toolkits/mplot3d.html).

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — APPROVED** [review]

**Review by WeatherGod — APPROVED** [review]

**Comment by anntzer** [comment]
rebased

**Comment by timhoffm** [comment]
Doc build failure:
```
/home/circleci/project/doc/tutorials/introductory/sample_plots.rst:128: WARNING: Failed to create a cross reference. A title or caption not found: toolkit_mplot3d-tutorial
/home/circleci/project/doc/users/prev_whats_new/whats_new_0.99.rst:25: WARNING: Failed to create a cross reference. A title or caption not found: toolkit_mplot3d-tutorial
/home/circleci/project/doc/users/prev_whats_new/whats_new_1.1.rst:141: WARNING: Failed to create a cross reference. A title or caption not found: toolkit_mplot3d-tutorial
```

**Comment by anntzer** [comment]
thanks for pointing it out, should be fixed.

**Review by tacaswell — APPROVED** [review]
Anyone can merge on docs green.

**Comment by timhoffm** [comment]
Still one to go:
```
/home/circleci/project/doc/users/prev_whats_new/whats_new_1.1.rst:141: WARNING: unknown document: /tutorial/toolkits/mplot3d
```

**Comment by anntzer** [comment]
woops.

**Pull request merged**
