### PR TITLE
Don't update style-blacklisted rcparams in rc_* functions

### PR DESCRIPTION
**Pull request by anntzer**
xref #9135

## PR Summary

Don't update style-blacklisted rcparams in rc_* functions.
This avoids e.g. incorrectly updating the "backend" or "interactive" rcParams.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [X] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Would be nice to get this in in relation with #11600, so I'll milestone as 3.0 (but not insisting on it).

**Comment by WeatherGod** [comment]
Probably should extend the tests that exist right now for blacklisting. Otherwise, looks good to me.

**Comment by anntzer** [comment]
Can't see any blacklisting tests in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_style.py.  Not saying they shouldn't be added, but that can perhaps be a separate PR?

**Comment by timhoffm** [comment]
CircleCI fails because it cannot load font-humor-sans. This is onrelated to the PR.

**Pull request merged**
