### PR TITLE
DOC: Fix missing-reference generation on Windows

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

On Windows, the path is absolute and contains a colon after the drive letter, so splitting on colon results in trying to relativize 'c' (or whatever the drive is) to the base directory, which just makes the final path into base directory + file path.

These missing references all broke in #26628, though I'm not sure why builds never failed since they aren't on Windows, or using the same base paths.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
> though I'm not sure why builds never failed since they aren't on Windows, or using the same base paths.

Ah, I think because on load and comparison it runs through:
https://github.com/matplotlib/matplotlib/blob/2cbdff865f170fffb868cc12f1265715c0e4f40c/doc/sphinxext/missing_references.py#L135-L142
which with the Windows-style paths gives us always `doc/C` so everything matches, perhaps?

**Comment by QuLogic** [comment]
So it looks like CI is getting additional unused references:
```
doc/docstring of builtins.list:17: WARNING: Reference py:class HashableList[_HT] for doc/docstring of builtins.list:17 can be removed from missing-references.json. It is no longer a missing reference in the docs.
lib/mpl_toolkits/axisartist/axisline_style.py:docstring of mpl_toolkits.axisartist.axisline_style.AxislineStyle:1: WARNING: Reference py:class mpl_toolkits.axisartist.axisline_style._FancyAxislineStyle.FilledArrow for lib/mpl_toolkits/axisartist/axisline_style.py:docstring of mpl_toolkits.axisartist.axisline_style.AxislineStyle:1 can be removed from missing-references.json. It is no longer a missing reference in the docs.
lib/mpl_toolkits/axisartist/axisline_style.py:docstring of mpl_toolkits.axisartist.axisline_style.AxislineStyle:1: WARNING: Reference py:class mpl_toolkits.axisartist.axisline_style._FancyAxislineStyle.SimpleArrow for lib/mpl_toolkits/axisartist/axisline_style.py:docstring of mpl_toolkits.axisartist.axisline_style.AxislineStyle:1 can be removed from missing-references.json. It is no longer a missing reference in the docs.
lib/matplotlib/path.py:docstring of matplotlib.path:1: WARNING: Reference py:class numpy.uint8 for lib/matplotlib/path.py:docstring of matplotlib.path:1 can be removed from missing-references.json. It is no longer a missing reference in the docs.
doc/docstring of builtins.list:17: WARNING: Reference py:obj matplotlib.typing._HT for doc/docstring of builtins.list:17 can be removed from missing-references.json. It is no longer a missing reference in the docs.
```
but I don't see them locally. I guess that's probably because of some differing versions of things. I'll leave that option off for now.

**Comment by QuLogic** [comment]
> The missing references file confuses me/I also I think more or less had the linter ignore it - I'm just not sure which of those I'm supposed to care about.

This file causes the `WARNING: xyz link target could not be found` type of things to be skipped. Mostly they're there for stuff that isn't documented, but linked, e.g., a method with an inherited docstring from a superclass with links to other methods that are not overridden (so the linked methods don't show up in the subclass).

**Review by ksunden — APPROVED** [review]
The changes look fine, but I am slightly confused as to why we _weren't_ getting warnings for all of the things in that file that had the windows paths.

Are we ignoring the path portion entirely somehow? if so should it just be removed in total from the json file?

I get that we have config on whether or not to warn about unused entries in this file (which is currently set to not warn for those), but presumably many of these are valid entries that _should_ be included in the ignores.

**Comment by ksunden** [comment]
I guess I was expecting the warning that should have been silenced to still show up (and flag as a warning/get extracted by the circle build step etc.

**Comment by QuLogic** [comment]
> Are we ignoring the path portion entirely somehow? if so should it just be removed in total from the json file?

I looked again; it appears that the answer is yes. Only the keys are used for ignoring warnings:
https://github.com/matplotlib/matplotlib/blob/2cbdff865f170fffb868cc12f1265715c0e4f40c/doc/sphinxext/missing_references.py#L285C62-L285C62

The file paths appear to be only to help people to investigate ignored things, and to make the warnings for _unused_ ignores.

**Pull request merged**
