### PR TITLE
Conda on travis

### PR DESCRIPTION
**Pull request by tacaswell**
Replaces #3273

@mdboom This requires a re-base

### CODE REVIEW

**Comment by mdboom** [comment]
Sure.  I consider this a little lower priority than originally thought, since it does not decrease testing times.  @jenshnielsen made the valid point that we could run the Qt tests if we did this, but that will require further refinement.

**Comment by tacaswell** [comment]
On the other hand, pip has been being really flaky on travis recently and our use of `--use-mirrors` is apparently deprecated so we will have to deal with that eventually.

**Comment by tacaswell** [comment]
Closing this as the `.travis.yaml` file has diverged significantly.  This is still probably worth doing (it will get us the numpy compile time back) but the docs are now the bottle neck anyway.

**Comment by matthew-brett** [comment]
There are numpy wheels [here](http://travis-wheels.scikit-image.org/) if you want to reduce compile time.

**Comment by tacaswell** [comment]
@matthew-brett I know I have asked this N times before, but can you point me to directions on how to use them?

**Comment by jenshnielsen** [comment]
BTW It looks like travis already has Numpy preinstalled on there venvs and we are only installing if from source in the python26/numpy16 env Compare https://travis-ci.org/matplotlib/matplotlib/jobs/62790222 to https://travis-ci.org/matplotlib/matplotlib/jobs/62790223

**Comment by matthew-brett** [comment]
Here's a PR to use travis wheels for installation:

https://github.com/matplotlib/matplotlib/pull/4435

**Pull request closed without merging**
