### PR TITLE
Deprecated `afm`, `fontconfig_pattern`, and `type1font`

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Related to #16181.

Will update with release notes once the tests pass (and I get a PR-number...)

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
How should one deal with these issues:
```
/home/circleci/project/lib/matplotlib/font_manager.py:docstring of matplotlib.font_manager.afmFontProperty:8: WARNING: py:obj reference target not found: AFM
/home/circleci/project/doc/api/next_api_changes/behavior/20715-JKS.rst:4: WARNING: py:obj reference target not found: type1font.Type1Font.prop
/home/circleci/project/doc/api/next_api_changes/behavior/20715-JKS.rst:4: WARNING: py:obj reference target not found: type1font.Type1Font.transform
/home/circleci/project/doc/api/prev_api_changes/api_changes_0.91.0.rst:39: WARNING: py:class reference target not found: AFM
/home/circleci/project/doc/api/prev_api_changes/api_changes_0.98.x.rst:66: WARNING: py:meth reference target not found: matplotlib.afm.AFM.get_fullname
/home/circleci/project/doc/api/prev_api_changes/api_changes_0.98.x.rst:66: WARNING: py:meth reference target not found: matplotlib.afm.AFM.get_familyname
api/prev_api_changes/api_changes_3.5.0/behaviour.rst:230: WARNING: py:obj reference target not found: type1font.Type1Font
```
Should one change the previous links to point to the new one? Import the required classes/functions explicitly in the to-be-removed file?

**Comment by timhoffm** [comment]
Please change the links in API changes to code literals using fully qualified names, e.g.

```
`~.type1font.Type1Font`
```
to 
```
``matplotlib.type1font.Type1Font``
```
The API changes are historic documents for that point in time and we should not change their meaning. We  can't reference with links in the current docs so the best option is literals. This is also true for the unreleased `next_api_changes`.

Concerning the first one, change `` `..AFM` `` to plain text for now. We currently don't build the docs for the new private modules. - I still have to decide if we want that. There are pros and cons for building docs for private parts. Anyway, for now there is nothing to link to. It might well be that `font_manager.afmFontProperty()` will become private as well. At least, it requires `AFM` as input, which is now private. But I have to have a closer look at this.

**Comment by oscargus** [comment]
> It might well be that `font_manager.afmFontProperty()` will become private as well.

It is only used (in the matplotlib codebase) in `FontManager.addfont()`, so would probably make sense. Let me know and I can do it here.

For consistency, one may also consider making `ttfFontProperty` private. However, that is directly used in both the cairo and svg backends, so may indicate that it maybe should stay.

**Review by timhoffm — COMMENTED** [review]
Please switch to the two-commit solution as described in https://github.com/matplotlib/matplotlib/pull/22134#pullrequestreview-847082722 to preserve history here as well.

**Review by timhoffm — APPROVED** [review]

**Comment by oscargus** [comment]
Imports are slightly improved here as well.

**Review by jklymak — APPROVED** [review]

**Pull request merged**
