### PR TITLE
DOC: replace anatomy static by new example

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

The anatomy of figure example was changed in #21753, but I forgot to update the static version of this for including in other tutorials.  

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by timhoffm** [comment]
Just noticed the think grey outllne (actually already introduced in #21753). I'm not sure I like that. It's very bulky and a quite uncommon style for our figures.

**Comment by jklymak** [comment]
The goal was to differentiate from the rest of the webpage (which is also white). We could color the whole thing but then it's a lot harder to make the little circles look good with their nice occurring effect.

**Comment by QuLogic** [comment]
I'd rather we link to the generated file rather than another new static image.

**Comment by jklymak** [comment]
Sure, replaced by a link.  That way when the example gets updated, this image will also.

**Comment by QuLogic** [comment]
Unfortunately, it looks like you can't link the 2x image because some builds need to run without them. Maybe we can expand `image-sg` to allow this, but we'll have to do the 1x image for now.

**Comment by jklymak** [comment]
Or have a static.

**Comment by jklymak** [comment]
Changed back to hi-res static since the hi-res is not always generated by sphinx-gallery.

**Review by timhoffm — DISMISSED** [review]

**Review by timhoffm — COMMENTED** [review]
Oh, CircleCI is not happy:

> /home/circleci/project/doc/tutorials/introductory/quick_start.rst:96: WARNING: image file not readable: _images/sphx_glr_anatomy_001_2_0x.png

**Review by timhoffm — CHANGES_REQUESTED** [review]
This is correct now. I'll temporarily block because I have some idea concerning the figure border that I want to try out. Will get back within 1-2 days.

**Comment by timhoffm** [comment]
I've done some formatting improvements in #22206. That should be checked and possibly included before adding a new static image.

**Comment by jklymak** [comment]
Lets close and just put the static image in #22206.  That saves me having to sync this up with whatever happens there.

**Pull request closed without merging**
