### PR TITLE
DOC: point align-ylabel demo to new align-label functions

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

https://matplotlib.org/gallery/pyplots/align_ylabels.html#sphx-glr-gallery-pyplots-align-ylabels-py shows a hard way to do whats in https://matplotlib.org/gallery/subplots_axes_and_figures/align_labels_demo.html#sphx-glr-gallery-subplots-axes-and-figures-align-labels-demo-py

The hard way is potentially useful, but the easy way should at least be referenced.

### CODE REVIEW

**Comment by jklymak** [comment]
https://10377-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/pyplots/align_ylabels.html#sphx-glr-gallery-pyplots-align-ylabels-py

**Comment by ImportanceOfBeingErnest** [comment]
tbh I find the two big boxes on top a bit... too much. How did the Note box get introduced anyways? Can we get rid of that? I mean the page should start with its title, not with a note.

image

**Comment by jklymak** [comment]
I didn't introduce that!  sphinx-gallery maybe?

**Comment by ImportanceOfBeingErnest** [comment]
[I'm proposing to remove that box.](https://github.com/matplotlib/matplotlib/pull/11428)

**Comment by timhoffm** [comment]
I’d rather have See also sections below the code. Having it up the is like saying “I’ll show you how to do alignment, but first you should look at these alternative ways.

Then again the referenced method is the simpler more standard case, which should come first.

The best solution would be to rewrite the example: First show a simple ˋalign_ylabel()ˋ example, then show the current code in case someone needs more control.

But I do not necessarily require this as part of this PR. Mentioning ˋalign_ylabel()ˋ is an improvement already.

**Comment by jklymak** [comment]
Well ok fair enough.  On phone and can’t label but I agree that combining the examples is a better solution.  So please don’t merge until I do that.

**Comment by jklymak** [comment]
https://10508-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/pyplots/align_ylabels.html#sphx-glr-gallery-pyplots-align-ylabels-py

**Comment by jklymak** [comment]
@timhoffm are the changes ok?  If so, we can merge...

**Comment by jklymak** [comment]
Not a big deal to bother w/ backport...

**Pull request merged**
