### PR TITLE
Add a flag for disabling LTO.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

For developers, it may be useful to disable it to improve build time when repeatedly re-building.

## PR Checklist

- [N/A] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Is there a way to use an ENV to set this (`git clean -xfd` is a core part of my personal workflow)?

**Comment by QuLogic** [comment]
Sure, we can do that, though I thought we moved away from envvars, at least with the FreeType option?

For me, I set `alias.purge=clean -fxd -e setup.cfg -e ...` for the things I want to keep.

**Comment by tacaswell** [comment]
> For me, I set alias.purge=clean -fxd -e setup.cfg -e ... for the things I want to keep.

Fair, that seems like is a better solution to my problem (and makes it my problem not everyones).

**Comment by anntzer** [comment]
Ah, nice trick re: aliasing the git subcommand.

**Pull request merged**
