### PR TITLE
Backend plt/gcf refactor

### PR DESCRIPTION
**Pull request by tacaswell**
This is an alternative to #2617.  The idea is to factor Gcf out of the toolkit backends so that the manager classes can be reused in external gui applications.

These changes should be backwards compatible.

Added an example for Qt4 to show how to use the managers in an external program.

Currently only backend_bases, qt4 and qt4agg are done, but the other backends should be doable incrementally. 

The relavent backends are (I think)

- [x] qt4/qt4Agg
- [x] gtk
- [x] gtk3
- [ ] macosx
- [ ] pdf (in `PdfPages`)
- [x] ps 
- [ ] tkAgg
- [ ] webAgg
- [ ] wx

This possibly should get a MEP.

### CODE REVIEW

**Comment by OceanWolf** [comment]
@tacaswell  Do you have a plan for the breaking of this up into smaller commits?  Or even an MEP document to look which outlines this?  I would like to have a look at this, but over 13k changes in the codebase looks a bit daunting to start reading through...

**Comment by tacaswell** [comment]
_most_ of those lines are just copies as I split files up.

The outline of this is that nothing in backend* should import `pyplot_helpers`.  The problem with changing that is that it breaks API so the solution I was going for was to split the files in half, one part was 'clean' and could be used for embedding in a way that does not ever import `Gcf` and the other half which maintains the current API.

Getting back to this has been on my to-do list for over a year now....

This should be split up, one PR to do backend_bases.py and one PR per backend after that.

**Comment by OceanWolf** [comment]
Perhaps something like the Navigation refactor, i.e. one PR for ``backend_bases.py`` plus one backend as an example, then the other backends go separate PRs?

I have very little time to look at this right now, but I would imagine the way to do this refactor would just mean splitting out the pure backend logic from the general mpl logic, in master we have the ``FigureManagerGTK3`` backend doing both:
```python
self.set_window_title("Figure %d" % num)
```
Here it combines the mpl logic ``title = "Figure %d" % num``, with the backend logic ``self.set_window_title(title)``.

As we have ``ToolbarGTK3`` to do a toolbar and ``FigureCanvasGTK3`` to abstract the canvas drawing, so too I think we need ``FigureWindowGTK3`` to abstract away the windowing parts.  Then we can have ``FigureManager`` dealing with just the mpl logic of how these abstracted backend components work together.

**Comment by fariza** [comment]
I am starting to implement the MEP23 https://github.com/matplotlib/matplotlib/wiki/Mep23 and I have conflicts with `Gcf` and general `pyplot` stuff (I can hack my way around that but not clean).

@tacaswell just a crazy idea, what do you think if I implement the MEP23 in a completely new set of MultiFigureManagers, that don't include any `pyplot` stuff. So no backward compatibility problem, and if somebody wants to use it, they will have to adhere to whatever new **interactive** mode we define.

**Comment by OceanWolf** [comment]
@tacaswell Anyway, sounds simple enough, I shall work on getting a PR on this done in the next few hours :).

**Comment by tacaswell** [comment]
@OceanWolf Great! 

Just to be clear, I am ecstatic that you are taking over this project.

**Comment by OceanWolf** [comment]
@tacaswell Just to make it clear, I don't know much about the various backends, so I will put all my focus on refactoring just ``GTK3``, in doing so it may look very GTK centric in its base approach, which I then expect to polish out later.

**Comment by OceanWolf** [comment]
@tacaswell Getting there, just finished the 2nd class :).

One question though, I see the method ``FigureManagerBase.show_popup``, though I see no reference to it anywhere.  Shall I just remove this from the refactor?

**Comment by tacaswell** [comment]
We have to be _very_ careful about changing public API.  It either needs to stay or to go through a proper deprecation cycle.

**Comment by OceanWolf** [comment]
@tacaswell I make completely new classes, so by remove, I mean not putting them in the new one... I think I shall leave it out for now, and make a comment about it in the PR.

**Comment by tacaswell** [comment]
:-1:  on completely new classes for this core stuff unless they match the old API exactly.  There is too much existing code (particularly for embedding).  I don't want to maintain _two_ version of code that do the same thing, that way lies madness confusion and angry users.

I am now very confused about what you are working on.

**Comment by OceanWolf** [comment]
DW, I have ``backwards compatibility`` as my middle name ;).

**Comment by tacaswell** [comment]
Replaced by MEP27 and #4143

**Pull request closed without merging**
