### PR TITLE
Capitalization fixes in example section titles.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

(See https://matplotlib.org/devdocs/users/index.html for how it currently looks.)

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — COMMENTED** [review]
I don't think this is an improvement.

Mixing in some verbatim titles in the toc looks odd:
https://63548-1385122-gh.circle-artifacts.com/0/doc/build/html/users/index.html

Even more, this leads to completely different title formatting in the gallery itself:
https://63548-1385122-gh.circle-artifacts.com/0/doc/build/html/gallery/index.html#pyplot

I'd rather leave these unformatted here.

**Comment by anntzer** [comment]
I removed the double backquotes (but kept the uncapitalization, and the underscore in axes_grid1), perhaps that'll look better?

**Comment by timhoffm** [comment]
@anntzer forgot to push?

**Comment by anntzer** [comment]
oops, indeed.

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
