### PR TITLE
Fix #5693: Implemented is_sorted in C

### LINKED ISSUE #5693: Invalid caching of long lines with nans
```
import numpy as np, matplotlib.pyplot as plt
x = [3, 5] + [np.nan] * 10000 + [0, 2]
plt.plot(x, x)
plt.xlim([0, 2])
plt.show()
```
As of matplotlib 1.5.0, this fails to plot the section of the line between 0 and 2 (which can be seen by replacing 10000 by e.g. 1).

This is due to incorrect caching logic in `Line2D.recache` and more specifically in `Line2D._is_sorted`, which believes that the line's x-points are sorted because `nanmin(diff(x)) > 0` (but this skips across the zero).

Related to #5365.

I believe a proper fix for both issues would be to replace the implementation of `_is_sorted` by something like `x = x[~np.isnan(x)]; return len(x) == 0 or np.diff(x).min() >= 0`.

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by efiring** [comment]
Nice!

**Comment by tacaswell** [comment]
tad worried what this will do with large int arrays or pd.Series but so long an np will do the corrosion it should be no worse than it is now (I think).

**Comment by mdboom** [comment]
> tad worried what this will do with large int arrays or pd.Series but so long an np will do the corrosion it should be no worse than it is now (I think).

Yeah.  I *think* a conversion was already happening in the `nanmin` call (since nans don't even make sense with ints), so this is no worse.  That said, there's probably some low-hanging fruit to do the easy thing if it's an int array to begin with.

**Comment by mdboom** [comment]
I've updated this to work on ints directly as well.

**Comment by tacaswell** [comment]
backport on this had conflicts, making sure it works locally before pushing

**Comment by tacaswell** [comment]
backported as db80928

**Comment by QuLogic** [comment]
I know this is merged already, but I'm curious as to the expected behaviour with respect to infinities? As you may guess from the name, `std::isfinite` returns false for infinity, so the behaviour is different, and there are no tests that exercise that case to show what's expected.

```python
>>> import numpy as np
>>> x = np.arange(10.)
>>> x[4] = np.inf
>>> x
array([  0.,   1.,   2.,   3.,  inf,   5.,   6.,   7.,   8.,   9.])
>>> np.nanmin(x[1:] - x[:-1]) >= 0
False
>>> from matplotlib import _path
>>> _path.is_sorted(x)
True
```

Is it just not possible for there to be infinities at this location?

**Comment by tacaswell** [comment]
That is a good point that I think we missed on review.

**Pull request merged**
