### PR TITLE
Return bytestring when fname is None in savefig

### PR DESCRIPTION
**Pull request by hs2361**
## PR Summary
This PR addresses #18614. I reproduced the code from https://github.com/matplotlib/matplotlib/pull/6909. However, the tests are not passing, and I am getting the following error on each of the failed tests:

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpev0li8x_/f.png'`

and I am unable to figure out how to fix this. Further, the codecov/patch check is failing as well.

Also, as @efiring had suggested in https://github.com/matplotlib/matplotlib/pull/6909, the tests need to be simplified. I was thinking of including a basic assertion test to check whether a bytestring is indeed returned when the fname is explicitly set to `None`.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by timhoffm** [comment]
@hs2361 Thanks for working on this.

Despite virtually every core dev approved this in #18614 or #6909, as API consistency lead, I need a bit more convincing (@anntzer @tacaswell). I'm still slightly worried by adding a return value. Less from a point of type stability, but more from a point of semantics. `savefig()` writes the data to the place specified in the first parameter. By passing `None` we're now saying "Save the data nowhere". And `savefig()` responds by "You did tell me to not save the data anywhere, so I'll just throw them back to you". That feels too clever, and it's implicit due to the negaive logic. `None` only specifies what we don't want.

Alternatives would be to either come back to the [previously discarded dedicated function](https://github.com/matplotlib/matplotlib/pull/6909#issuecomment-238072758), or use a different parameter value. `savefig('bytes', format='png')` would read much better, but I don't think we can use any string value as that would prevent writing to a file with that name. Another option would be passing the class `savefig(BytesIO, format='png')` with the slight drawback that users still need to import that name.

**Comment by anntzer** [comment]
I actually think `savefig(bytes, format="png")` (passing the `bytes` class object) would be quite cute, but perhaps too clever, and possibly slightly confusing to document? (as alluded to elsewhere documenting a parameter that takes a *type* is not well standardized).

**Comment by tacaswell** [comment]
I agree with @anntzer,  literally taking `bytes` a reasonable singleton, but it is much harder to document and explain than `None`.

The analogy of "you told us to write a figure, but did not tell us where so we are going to push it back to you" is not terrible (as the other option of "drop it on the floor" is not useful at all).

**Comment by hs2361** [comment]
> I agree with @anntzer, literally taking `bytes` a reasonable singleton, but it is much harder to document and explain than `None`.
> 
> The analogy of "you told us to write a figure, but did not tell us where so we are going to push it back to you" is not terrible (as the other option of "drop it on the floor" is not useful at all).

I am of the opinion that keeping `None` would be a little more intuitive. "You didn't tell me where you wanted to save the figure, so I will give the bytes to you, and you can use them elsewhere" is better than "You didn't tell me where you wanted to save the figure, so I will simply not do anything". 

Passing the `bytes` object is an even better alternative, as it clarifies the user's intention of having the figure saved as bytes. If it's possible, we can have both alternatives, with the `fname` parameter taking in either `None` or a `bytes` object both corresponding to having the bytes object returned. I will try to clarify this in the docstring of the function as best as I can, as well as in the documentation.

**Comment by timhoffm** [comment]
IMO None violates "explicit is better than implicit" and "In the face of ambiguity refuse the temptation to guess". If the major concern with "bytes" is clear documentation, I'm convinced we can find a good solution for that.

I'm 👎 on supporting both. It would only make the documentation longer and put an additional burden on the user (understand that there are two ways and choose one).

**Comment by hs2361** [comment]
> IMO None violates "explicit is better than implicit" and "In the face of ambiguity refuse the temptation to guess". If the major concern with "bytes" is clear documentation, I'm convinced we can find a good solution for that.
> 
> I'm  on supporting both. It would only make the documentation longer and put an additional burden on the user (understand that there are two ways and choose one).

If not both, I think passing a `bytes` object should be the right course of action then? It is not ambiguous, and it explicitly clarifies the intention of the user. The documentation wouldn't have to be very complicated then.

**Comment by efiring** [comment]
Are there any other cases in our API, or similar ones, in which something like this is done? That is, having an argument that can either be a class object that serves as a flag to indicate what kind of thing to return, or can be some completely different sort of instance? And is there any *other* class object that would ever be acceptable for this argument?

Advantage of None: it's consistent with its typical meaning of "do the default".  If no filename is supplied, a reasonable default is to return the bytes instance.

**Comment by jklymak** [comment]
You can't use a string `"bytes"` because that is a valid filename, so I vote we take that off the table.

Passing a type `bytes` seems bizarre.  

So I think we have either `None`, or just documenting how to use `BytesIO`.  

I favour people just create a stream using `BytesIO`  - I don't see the need for this hard-to-document, weird API nicety. I would expect people who want the bytes stream for some reason are also capable of using `BytesIO`.

**Comment by timhoffm** [comment]
> Are there any other cases in our API, or similar ones, in which something like this is done? That is, having an argument that can either be a class object that serves as a flag to indicate what kind of thing to return, or can be some completely different sort of instance?

If you ask that specifically: No. But that's more attributed to the fact that in itself it is rare to modify the output type. We're really stretching the API here to do something new, that now suddenly requires an output vs. no output before. I can conversely ask: Are there any other cases in our API, in which we return something or not depending on a parameter? I guess not. That may be an indication that we try to do too much with the method and a dedicated method would be better.

But assuming we want to go down this special route of extended functionality, I think there's little precedence for an API design. Therefore we should aim to make it as explicit and unambiguous as possible.


On a bit broader note, there's precedence for parameters accepting types and strings. E.g. numpy accepts  `np.zeros(5, dtype='float64')` and `np.zeros(5, np.float64)`. Similar, the `tool` parameter in `ToolManager.add_tool()`.

**Comment by hs2361** [comment]
> But before drifting into a long and controversal discussion here, I propose to schedule this topic for the next dev call.
Alright, so if the proposed changes will take some more discussion, I think I can put this PR on hold for the moment.

**Comment by timhoffm** [comment]
This will be discussed in the next dev call. @hs2361 You are welcome to join the call if you like (Tue, Nov 3, 15:00 Eastern US Time (UTC -05:00). Let us know if you are interested, then we'll forward you the zoom call link.

**Comment by hs2361** [comment]
> This will be discussed in the next dev call. @hs2361 You are welcome to join the call if you like (Tue, Nov 3, 15:00 Eastern US Time (UTC -05:00). Let us know if you are interested, then we'll forward you the zoom call link.

Thanks for inviting me to join the meeting. I will certainly try to join it. Is there a communication channel for Matplotlib which I can join?

**Comment by timhoffm** [comment]
The meeting notes are at https://hackmd.io/yfYAAbEIQlayXoFLwC2EoA.

You'll also find the zoom link there.

**Comment by hs2361** [comment]
Thanks @timhoffm for sharing the details. I would have loved to join the meeting, however, due to time zone differences I may not be able to join it. I will still try to join it if possible.

**Comment by timhoffm** [comment]
No worries, if you can't make the meeting. Joining is just an offer. Well post the result here, and you can also check the above meeting notes.

**Comment by hs2361** [comment]
> No worries, if you can't make the meeting. Joining is just an offer. Well post the result here, and you can also check the above meeting notes.

@timhoffm I will be joining the meeting. Would you be so kind as to share the meeting link with the password on Gitter?

**Comment by timhoffm** [comment]
On the dev call we decided not to support this API. Reasons:

- This is only a convenince abbreviation for:
  `import io; buf = io.BytesIO(); fig.savefig(buf, **kwargs); bytestring = buf.getvalue()`
- Adds slightly more complexity. In particular, proper documentation is more cumbersome.
- We think this is a niche use case (e.g. within a web server). There's probably no use case for "interactive" use, where the convenience of not having to write the 4 above statements would have the most benefit.
- Strong differing opinions on `savefig(None, ...)` vs `savefig(bytes, ...)`; indicating that there is no natural intuitive way the API should look like.
- The API of returning something or not depending on parameters seems questionable.

@hs2361 I'm sorry we had this as an open issue but nevertheless decided not to do this. Sometimes you have to flesh out the details to find out that a seemingly good idea is actually not good. Many, thanks for your contribution! Hope to see you back some time.

**Pull request closed without merging**
