### PR TITLE
Badges

### PR DESCRIPTION
**Pull request by tacaswell**
Supersedes #5811 

screenshot_20160110_134418

@doraf help get the button styled so the fit in with our color theme and get slightly darker on mouse-over.

This PR also includes commits to address some of the issues reproted by @sandrotosi

### CODE REVIEW

**Comment by mdboom** [comment]
:+1:, but it looks like the existing sidebar content is gone...?

**Comment by tacaswell** [comment]
stand by

**Comment by tacaswell** [comment]
screenshot_20160110_144728

Restored the search box and tweaked the style a bit more.

**Comment by tacaswell** [comment]
Unless someone gets to this in the next hour or two I plan to self-merge this to get 1.5.1 tagged today.

**Comment by jenshnielsen** [comment]
Looks ready to merge once Travis passes :+1:

**Comment by tacaswell** [comment]
self merged after +1 from @mdboom and @jenshnielsen

**Pull request merged**
