### PR TITLE
Enable sphinx.ext.viewcode

### LINKED ISSUE #10676: Add source code to documentation
# Feature Request

I propose to use the Sphinx extension [sphinx.ext.viewcode](http://www.sphinx-doc.org/en/stable/ext/viewcode.html) to add the python source code to the docs and crosslink it.

This could help users understand the relations between the various levels of indirection we use. Also it could be a little help with poorly or undocumented parts of the API (we should improve the docs, but that's a long-term project).

Here is an example how this would look like (note the `[source]` link): 

grafik

The link will guide to a page containing the source code:

grafik

Please give a short feedback on the idea. If there is a general approval, I'll submit a pull request.

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Closes #10676.

### CODE REVIEW

**Comment by tacaswell** [comment]
The built source is not rendering great:

https://9046-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/_modules/matplotlib/colorbar.html#Colorbar

**Comment by tacaswell** [comment]
:+1: on this though!

**Comment by timhoffm** [comment]
> The built source is not rendering great

What exactly are you referring to? The `[docs]` links, which shift the lines?

**Comment by tacaswell** [comment]
Yes, that [docs] links that shift the code.

**Comment by timhoffm** [comment]
Fixed by copying css from the standard sphinx css files.

Is it intentional, that we maintain a complete css file of our own? Usually, I would use the basic sphinx css file and just add our own adaptions in an additional file.

**Comment by tacaswell** [comment]
We started using sphinx very early which probably predated what are considered current best practices with both sphinx and css.

**Comment by timhoffm** [comment]
[Example for review](https://9066-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.pyplot.sca.html#matplotlib.pyplot.sca)

**Comment by jklymak** [comment]
Any reason to not backport this?

**Comment by timhoffm** [comment]
+1 on backporting

**Comment by tacaswell** [comment]
Thanks @timhoffm !

**Pull request merged**
