### PR TITLE
Added support for displaying percentiles to violinplot function

### PR DESCRIPTION
**Pull request by Dylan-Dotti**
## PR Summary

    These changes will add the option for displaying percentile lines in the violinplot function. For each list given as input (2D for more than one plot), the respective plots will display lines at the percentiles given by that list.
    I also wanted to mention KurtWink, my collaborator for this project. We needed to remake the repository we were using to set it up for a PR (a bit new to GitHub), and I ended up pushing all our final changes at once.

https://github.com/matplotlib/matplotlib/issues/8532

## PR Checklist

- [ ] Has Pytest style unit tests
- [X] Code is PEP 8 compliant
- [X] New features are documented, with examples if plot related
- [X] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Looks like a cool new feature! Could you post a short example of how this works in practice?

**Comment by jklymak** [comment]
Yes, and it needs a test...

**Comment by Dylan-Dotti** [comment]
Here's the code I've been using to test my changes, though it only covers the case of all plots having the same percentiles.
```
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(19680800)
fs = 10
pos = [3, 4, 5]
data = []
percentiles = []
for std in pos:
    data.append(np.random.normal(0, std, size=100))
    percentiles.append([5.0, 20.0, 80.0, 95.0]) 

plt.violinplot(data, pos, points=20, widths=0.3, showmeans=True, 
               showextrema=True, showmedians=True, percentiles=percentiles)
plt.title('Custom violinplot 1', fontsize=fs)
plt.show()
```
Using something like 
```
percentiles=[[],[5.0, 95.0],[20.0, 80.0]]
```
Will display different percentiles for each plot (or none in the case of empty list).

I will try to write tests after my finals, though I'm not quite sure how to go about it yet.

**Comment by jklymak** [comment]
Thats great!  Let us know if you need pointers...

http://matplotlib.org/devel/testing.html

**Comment by Dylan-Dotti** [comment]
When I was trying to run 'python tests.py' after building from the Linux guide [here](https://matplotlib.org/2.1.0/users/installing.html) I got this error:
```
dylan@dylan-VirtualBox:~/violinfeaturebranch/matplotlib$ sudo python tests.py
('Python byte-compilation optimization level:', 0)
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1474: UserWarning: Matplotlib is 
not built with the correct FreeType version to run tests.  Set local_freetype=True in setup.cfg 
and rebuild. Expect many image comparison failures below. Expected freetype version 2.6.1. 
Found freetype version 2.6.1. Freetype build type is not local
  "" if ft2font.__freetype_build_type__ == 'local' else "not "
Traceback (most recent call last):
  File "tests.py", line 56, in <module>
    recursionlimit=args.recursionlimit)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1494, in test
    raise ImportError("Matplotlib test data is not installed")
ImportError: Matplotlib test data is not installed
```
I tried following the instructions for installing in dev mode [here](https://matplotlib.org/devel/contributing.html). I edited setup.cfg.template to set local_freetype and tests to True and then rebuilt.
I also edited ci/travis/setup.cfg (I think this is the right file?) to look like the 3 line file shown in the guide.

When trying again, I got the same error, but this time many tests ran with the results:
```
============== 9 skipped, 3 xfailed, 6965 error in 16.51 seconds ===============
```
All the errors I saw looked like this:
```
/home/dylan/violinfeaturebranch/matplotlib/lib/matplotlib/testing/conftest.py:19
__________________ ERROR at setup of test_outward_ticks[png] ___________________
pytest.fixture functions cannot use ``yield``. Instead write and return an inner function/generator 
and let the consumer call and iterate over it.:
```
I'm using a relatively fresh VirtualBox VM running Ubuntu 16.04

**Comment by jklymak** [comment]
https://matplotlib.org/devel/testing.html  I would guess your pytest is too old..

**Comment by anntzer** [comment]
We don't actually support pytest 3.0 (xref #9317).

**Comment by jklymak** [comment]
@Dylan-Dotti are you still interested in this?  We'd love to see it pushed through...

If you *really* have trouble setting up the testing environment, its not considered too bad to just let our CI process handle the tests...

**Comment by timhoffm** [comment]
Superseeded by #14107.

**Pull request closed without merging**
