### PR TITLE
Typo: fix some typos in patches.FancyArrowPatch

### PR DESCRIPTION
**Pull request by magnunor**

### CODE REVIEW

**Comment by WeatherGod** [comment]
+1 from me and should get backported to v1.5.x-doc and such.

**Comment by tacaswell** [comment]
just back to 1.5.x, the `1.5.1-doc` branch is for changes to non-source (ex rst or examples) only.

**Comment by tacaswell** [comment]
restarted the failing test, one of the transient stix fails.

**Comment by tacaswell** [comment]
backported to v1.5.x as c32329908dd10dfe7c2c857c555a195b7493c693

**Comment by tacaswell** [comment]
@magnunor Thanks!  We really appreciate fixes to the documentation.

**Pull request merged**
