### PR TITLE
[mpl_toolkits] Fix picking for things drawn on parasite axes

### PR DESCRIPTION
**Pull request by smheidrich**
Second attempt at fixing https://github.com/matplotlib/matplotlib/issues/5581 .

This time it is done by implementing custom `pick` methods for host and parasite axes classes.
In actuality the pick methods are both stolen from [`Artist.pick`](https://github.com/matplotlib/matplotlib/tree/f4209922972afa3917a0ce61ae3d58b2ebba3264/lib/matplotlib/artist.py#L418) and extended, I'm not sure if I should remove [that duplicate wall-of-text comment](https://github.com/productivememberofsociety666/matplotlib/blob/5b1aae649748543b5ceb0a785b66dabc54c4244c/lib/mpl_toolkits/axes_grid1/parasite_axes.py#L366).

Also added tests that check if this behaves exactly as picking on "normal axes" (`pyplot.gca()` on a clean slate) does even for overlapping objects.

### CODE REVIEW

**Comment by mdboom** [comment]
Cc: @leejjoon

**Comment by jklymak** [comment]
I think this one still comes up once in a while...  Any chance it'll get looked at?

**Comment by jklymak** [comment]
Sorry we missed that you rebased this.

**Comment by jklymak** [comment]
I wasn't quite sure how firing works for overlapped artists?  If two artists overlap do they both fire the pick?  If so, this looks right.  If one of the artists is supposed to be picked, then this seems to pick both of them.

**Comment by smheidrich** [comment]
@jklymak I wasn't sure either, which is why the tests [also check how picking on "regular" axes works](https://github.com/matplotlib/matplotlib/pull/5590/files#diff-52dc8e4cf3638d0644b6834777162fbbR438) to make sure it does the same thing. If the behavior on regular axes is ever changed, the tests will fail and hopefully signal that the behavior for parasite axes should be changed in accordance.

**Comment by smheidrich** [comment]
But it seems a bit stupid to me now that I just straight up copied those methods from ``Artist``... let me check if this can't be solved with just ``super()``...

**Comment by smheidrich** [comment]
Done; also simplified the tests a bit.

**Comment by smheidrich** [comment]
Done (also simplified the tests a bit).

**Comment by smheidrich** [comment]
Done (finally).

**Comment by jklymak** [comment]
Can someone else review this very old PR?

**Comment by timhoffm** [comment]
Merging a PR after >3 years 🎆 🍾 😄

**Comment by smheidrich** [comment]
Thanks! :smile:

**Pull request merged**
