### PR TITLE
FIX: Correct output of mlab._spectral_helper when scale_by_freq=False

### LINKED ISSUE #4328: Incorrect and Inconsistent output of function PSD when scale_by_freq=False
If we state `scale_by_freq=False`, then we are asking for the power spectrum of the signal, instead of the power spectral density; i.e. units of V^2 instead of V^2/Hz, for example. 

`mlab.psd`, which actually is `mlab._spectral_helper` under the hood, does not return the expected value of the power in a sinusoid. Furthermore, in contrast to the PSD case, it does not correct for the energy of the signal lost to the window function, meaning that the results differ depending on the window used. 

Here's an illustration. If we have a simple signal of a cosine oscillation happening at 100Hz with amplitude of 10, we would expect the power spectrum result at 100Hz to be 50, regardless of the window used. (A cosine like this that is identically zero at each integer second means we can use one second FFTs and compare the rectangular window to the hanning window, without worrying about any distortion)

 In MATLAB:
```
fs=2048;
tt=[0:1/fs:60-1/fs];
x = 10*cos(2*pi*100*tt);
[pR, f]=pwelch(x, ones(1,fs), 0, fs, fs, 'power');
[pH, f]=pwelch(x, hann(fs), 0, fs, fs, 'power');
```
gives `pR(101)==50` and `pH(101)==50.000...`, as expected. 

In `matplotlib.mlab`:
```
fs = 2048
tt = np.arange(fs*64)/float(fs)
x = 10*np.cos(2*np.pi*100*tt)
# One second FFT segments
psdHann, ff = mlab.psd(x, Fs=fs, NFFT=fs, window=mlab.window_hanning, scale_by_freq=False)
psdRect, ff = mlab.psd(x, Fs=fs, NFFT=fs, window=mlab.window_none, scale_by_freq=False)
```
gives `psdRect[100] == 102400`, which too large by a factor of `nfft` and `psdHann[100] ==  68233.3`, which differs further by some window correction factor. 

I came across this in scipy/scipy#4682, where I was adapting the code for inclusion in scipy's signal processing repertoire. There, I used `scale = 1.0 / win.sum()**2` for the power spectrum case. I haven't looked for the exact places where `_spectral_helper` should be fixed, at this time.

### PR DESCRIPTION
**Pull request by e-q**
Closes #4328

### CODE REVIEW

**Comment by tacaswell** [comment]
This causes all of the spectral tests to fail.

**Comment by e-q** [comment]
True, didn't check the tests before submitting. In this case, the tests are in error. 

Specifically, all of the failures are in `test_psd_windowarray_scale_by_freq`, which tests `assert_allclose(spec_s, spec_n/self.Fs, atol=1e-08)`, where `spec_s` is computed with `scale_by_freq=True` and `spec_n` is computed with `scale_by_freq=False`. This equality is only true when using a flat window. 

I've chosen to modify the tests to use a flat window, instead of the function's default, which I believe is a Hanning window. If, instead, we want to test with the Hanning window, the test can be modified to calculate the difference in window correction factors.

The tests now seem to pass on my machine, let's see what Travis thinks...

**Comment by e-q** [comment]
Hmm, now the tests are failing by a factor of 100. I'll get back to this soon.

**Comment by e-q** [comment]
There we go. I used the hanning window after all.

**Pull request merged**
