### PR TITLE
Fix a warning in the doc build.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Search for
> /home/circleci/.local/lib/python3.7/site-packages/numpydoc/docscrape.py:377: UserWarning: Unknown section Note in the docstring of <class 'matplotlib.scale.ScaleBase'> in /home/circleci/project/lib/matplotlib/scale.py.

in https://circleci.com/gh/matplotlib/matplotlib/17517 (for example).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Let's try `.. note::` instead, perhaps that'll make numpydoc+our docstring manipulation work better together...

**Comment by timhoffm** [comment]
It really depends what you want. `.. note::` gives an admonition box. The `Notes` section is a numpydoc section (Not that it has to be plural which was the reason for the warning).

**Comment by anntzer** [comment]
The problem is that the docstring of the scale gets copied into the docstring of Axis.set_scale, and then the Notes end up indented, once it's NoteS with an "s" numpydoc tries to handle that and all hell breaks loose.

**Comment by anntzer** [comment]
Let's try another approach which should avoid that problem...

**Pull request merged**
