### PR TITLE
Make new colormaps full-fledged citizens

### LINKED ISSUE #5202: New colormaps are not included in the plt.cm.datad dictionary.
The new colormaps (viridis, magma, plasma, and inferno) do not appear in the plt.cm.datad dictionary.

    C:\>python
    Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import matplotlib as mpl
    >>> import matplotlib.pyplot as plt
    >>> print(mpl.__version__)
    1.5.0rc2
    >>> 'jet' in plt.cm.datad
    True
    >>> 'viridis' in plt.cm.datad
    False
    >>> s1 = set(plt.colormaps())
    >>> s2 = set(plt.cm.datad.keys())
    >>> sorted(s1 - s2)
    ['inferno', 'inferno_r', 'magma', 'magma_r', 'plasma', 'plasma_r', 'viridis', 'viridis_r']
    >>> mpl.cm.datad is plt.cm.datad
    True
    >>>

As a result, the pylab_examples example code `demo_bboximage.py` will not include the new color maps, and the documentation for `matplotlib.cm.get_cmap(name=None, Lut=None)` is no longer correct. It states that "_name_ must be a standard mpl colormap name with a corresponding data dictionary in _datad_."  In fact, `map = mpl.cm.get_cmap('viridis')` works just fine despite the fact that 'viridis' has no entry in datad.

Suggested fix:
* Add the new colormaps to plt.cm.datad.

Alternate fix:
* Update `demo_bboximage.py` to include the new colormaps.
* Update the documentation for `matplotlib.cm.get_cmap()`.

### PR DESCRIPTION
**Pull request by mdboom**
Fix #5202

### CODE REVIEW

**Comment by WeatherGod** [comment]
Not sure if I am happy with the "reduce" name. Makes me think of python's reduce() or numpy's reduce().

**Comment by mdboom** [comment]
Maybe "segment"?

**Comment by WeatherGod** [comment]
Eh... better, but not really clear. Maybe a better docstring would help in explaining its purpose. To me, it just looks like a glorified copy constructor...

**Comment by mdboom** [comment]
It's a copy constructor that changes the number of lookup table entries.  Maybe "resample"?

**Comment by WeatherGod** [comment]
Much better!

**Comment by mdboom** [comment]
Updated with renamed methods.

**Comment by WeatherGod** [comment]
by the way... pet peeve of mine is the error message below that prints out the list of keys. The keys aren't sorted, so it changes all the time and it is hard to find the one I want if I misremember the name. Think we can sneak a fix of that here?

**Comment by mdboom** [comment]
Keys are now sorted in the error message.

**Comment by WeatherGod** [comment]
+1 from me

**Comment by WeatherGod** [comment]
do we need a "whats_new"?

**Comment by mdboom** [comment]
I don't think this needs a what's new -- it's basically just a bugfix that should have been done when the new colormaps were added (and there's already a what's new for those).

**Comment by WeatherGod** [comment]
I was more referring to the introduction of a new colormap method. Unless you want to make it private for now?

**Comment by mdboom** [comment]
I'll just make these private for now.  The interface to this is really `cm.get_cmap` (as it's always been).

**Comment by WeatherGod** [comment]
alright, so it is now +1 from me. Was this intended to get backported to v1.5.x?

**Comment by jenshnielsen** [comment]
@WeatherGod  yes I think so #5202 is tagged at 1.5.0

**Comment by WeatherGod** [comment]
backported to v1.5.x as e7e08073

**Pull request merged**
