### PR TITLE
Slightly reorganize api docs.

### PR DESCRIPTION
**Pull request by anntzer**
- Move _enums to _enums_api, consistently with other modules, and
  move it to the end (together with the other private module, _api).

- Group the various GUI backends together based on the GUI toolkit.
  (It seems a bit silly to have so many pages which all refer to
  backends with no generated docs anyways, and even if we could easily
  generate docs for them on CI we would not want to document all 4
  mostly indentical copies of qt{4,5}{agg,cairo} on 4 different pages.)

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by jklymak — CHANGES_REQUESTED** [review]
Blocking just so that we sort out the moving/redirect process before this is merged.  We will likely try to start using reredirects and this PR would need entries in the list of re-directs.  https://gitlab.com/documatt/sphinx-reredirects/-/tree/master/

**Comment by jklymak** [comment]
This has a real error?

/home/circleci/project/doc/api/backend_wx_api.rst:12: WARNING: py:mod reference target not found: matplotlib.backends.backend_wxcairo

**Comment by anntzer** [comment]
hopefully better now...

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
How did you make the missing_references.json?

**Comment by anntzer** [comment]
`make O=-Dmissing_references_write_json=1 html`

**Pull request merged**
