### PR TITLE
Use `figure.stale` instead of internal member in macosx

### LINKED ISSUE #6237: MacOSX agg version: doesn't redraw after keymap.grid keypress
On master, with the new MacOSX, pressing 'g' on a raised and active figure has no effect until a redraw is forced, e.g. by resizing the window.
It also behaved badly on the old macosx--in that case, a cursor movement would trigger the redraw with  or without the grid.
I'm guessing this might be easy to fix with the new version; but if not, the milestone can be moved to 2.0.1

### PR DESCRIPTION
**Pull request by mdboom**
Fix #6237.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
:+1: it also fixes an issue that I have been seeing (but forgot to report) with the image_slices_viewer.py example

**Comment by jenshnielsen** [comment]
I can also confirm that it fixes #6237 for me

**Comment by mdboom** [comment]
I think this is good-to-go.  The appveyor test is obviously a false negative.

**Comment by jenshnielsen** [comment]
backported to 2.x as bdc3b2565f0ffc29bdc1971857fbb34aed9ec97e

**Pull request merged**
