### PR TITLE
Remove deprecated code in image.py

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by dstansby** [comment]
Did someone remove this in another PR? There's an API note here that can be merged anyway.

**Comment by jklymak** [comment]
Odd conflicting file...

**Comment by tacaswell** [comment]
Something funny is going on with git here...

**Comment by jklymak** [comment]
This is still just the API change file.  Is that all you wanted for this PR?

**Comment by dstansby** [comment]
Yeah, an API change should go in if it isn't already.

**Comment by dstansby** [comment]
Continually rebasing this is getting quite tedious, could someone merge it?

**Pull request merged**
