### PR TITLE
CI: try and run job on macstadium mac

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary

This is trying to run jobs on the hosted mac-mini we have.  Unfortunately M1's can not be used yet, but hopefully that is coming soon?

### CODE REVIEW

**Comment by tacaswell** [comment]
Pro: we can hit the mac-mini and get work started there!
Con: fails to install.

**Comment by QuLogic** [comment]
Did you set this up as a separate account on the mac? What macOS version is it anyway?

**Comment by tacaswell** [comment]
Currently 10.15.7 Catalina.  It is a "late 2012" mac mini with a dual-core i5 and too old to get upgraded to 12 (https://support.apple.com/en-us/HT212551).  There are newer macs on macstadium, but they are priced such that if we wanted to have access to a newer intel mini we should just buy one (and would save money in ~1 yr). 

I set it up under my account, but putting it under a service account is definitely a better idea.

**Comment by tacaswell** [comment]
We have canceled the contract on this machine so this PR is no longer a going concern.

**Pull request closed without merging**
