### PR TITLE
Added info for creating 3D graphs

### PR DESCRIPTION
**Pull request by sshiv5768**
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks for the suggestion, but this sticks out a bit in the README.rst - we don't show people how to do most things there, and they really should be directed to other resources (like your link).  Maybe consider adding a sentence or clause to the statement above about the purpose of Matplotlib, and then maybe link to the 3-D tutorial?

**Comment by story645** [comment]
I agree that I don't think this belongs in the readme. Maybe a general link to the tutorials & examples page at the top, but what's the reason for special casing 3D?

**Review by tacaswell — CHANGES_REQUESTED** [review]
I am :-1: on this change.  We do not have any other python code in this file and I do not think we should call out 3D plotting specifically.

**Comment by jklymak** [comment]
Thanks so much for your interest in Matplotlib - we love new contributors!  OTOH, as it is, this PR needs more justification in the PR description and the content requires more thought.  We will close for now, but if you make substantive changes we will be happy to reconsider.

**Pull request closed without merging**
