### PR TITLE
Doc changes to git setup

### PR DESCRIPTION
**Pull request by RebeccaWPerry**
## PR Summary
Small doc changes to help new devs set up git. Removed "Of course..." because words like "of course" and "just do..." can be off-putting to people who don't see what follows as obvious.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I think this section gets copied over from the gitwash repository so I think you need to make the PR there.

**Comment by dstansby** [comment]
Thanks for the PR @RebeccaWPerry. To elaborate, these bits of the docs are copied from here: https://github.com/matthew-brett/gitwash - it looks like that repository hasn't been updated in about 2 years though and is dead, so maybe we should just put the changes directly into Matplotlib?

**Comment by RebeccaWPerry** [comment]
@dstansby haha, oops! Was just trying to make a simple doc change as my first PR. It does look like gitwash is pretty ignored. Including some PR's from @tacaswell.

**Comment by anntzer** [comment]
I personally think it doesn't make sense to maintain our full git tutorial and we should just strip that all out and put some links to generic tutorials (e.g. https://guides.github.com/).

**Comment by jklymak** [comment]
@anntzer I’d have had trouble getting a work flow together from those tutorials.  They are bizarrely devoid of command line examples, perhaps on the assumption a lot of folks will use a GUI?

**Comment by anntzer** [comment]
I just picked these links as the first thing that google gave me, but certainly there can be better choices?
Or at least we should try to revive the upstream gitwash project and just link to it.  Certainly we can share the same tutorial with numpy/scipy/whatnot?  Hopefully if you can contribute to any of these projects, you're able to replace `github.com/<repoowner>/<reponame>` by `github.com/matplotlib/matplotlib` or whatnot.

**Comment by jklymak** [comment]
I thought that's what gitwash was supposed to be?

**Comment by jklymak** [comment]
After a quick look, and I'd be fine just linking w/ numpy's tutorial.  It seems comprehensive and their workflow is close enough to ours.

**Comment by jklymak** [comment]
I'm closing this because these changes won't take effect.  If anyone feels strongly about not using gitwash, we can open a new issue...  Thanks @RebeccaWPerry !

**Comment by timhoffm** [comment]
As far as I can see, these changes would take effect - unless we sync with the gitwash repo, which I don't think we do (otherwise why would the doc be here).

So until someone comes up with a replacement for gitwash, this would at least be an improvement.

**Comment by jklymak** [comment]
```
All documentation in the gitwash directory are automatically generated by running the gitwash_dumper.py
script in the project's root directory using the following parameters:

python gitwash_dumper.py doc/devel Matplotlib --repo-name=matplotlib --github-user=matplotlib \
   --project-url=http://matplotlib.org \
   --project-ml-url=https://mail.python.org/mailman/listinfo/matplotlib-devel

The script is hosted at https://raw.githubusercontent.com/matthew-brett/gitwash/master/gitwash_dumper.py.
For more information please visit https://github.com/matthew-brett/gitwash
```

**Comment by timhoffm** [comment]
@jklymak the last run seems to have been Feb 2017. Since then we've had some local changes. So we're down that road already. Since the gitwash project seems dead anyway, that's not too much of an issue.

**Comment by jklymak** [comment]
Sounds good.  I think we should discuss a way forward but it’s not urgent.

**Comment by timhoffm** [comment]
@RebeccaWPerry thanks, and congratulations on your first contribution to Matplotlib! Hope to see you back some time.

**Pull request merged**
