### PR TITLE
Add PEP8-compliant aliases to transAxes, transData, etc.

### PR DESCRIPTION
**Pull request by anntzer**
ax.transAxes / transData / etc. are perhaps one of the most user-facing
parts of mpl that are not pep8 compliant.  Provide some PEP8-compliant
aliases for those (like myself) who are excessively (and unduly?)
bothered by that.

Note that (quite unusually for myself :-)) I am **not** proposing to
deprecate the camelCase names.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Should we call them something like `axes_transform` instead of the other way?

**Comment by anntzer** [comment]
Would be fine with that too.

**Comment by timhoffm** [comment]
Can do with 3-5.

Still, I would like to have at least 2. in this PR. Changing that later would basically revert this PR.

**Comment by anntzer** [comment]
I actually think 2 & 3 should be done together (unless you can show that there's no performance issue, given how much we access these internally).
(FWIW I also think that deprecating the old names gets a bit close to "causing gratuitious code churn" (who'd have thought I'd once say this...).)

**Comment by timhoffm** [comment]
Ok, for 2-3 I'd basically have to create a competing PR. But we should discuss and agree if we want 1-6 before starting further work.

**Comment by anntzer** [comment]
I am +1 on 1-5 (feel free to open your own PR) and +0 on 6.

**Comment by efiring** [comment]
I'm far from convinced that this renaming is a good idea--that its advantages (ability to avoid camelCase) outweighs its disadvantages (more code, more explanations required, two names for exactly the same thing).

**Comment by tacaswell** [comment]
Moving to 3.1 as this will need more consideration.

**Comment by jklymak** [comment]
Did we still want to try and discuss for 3.1?

**Comment by timhoffm** [comment]
Moving further to 3.2 because this still needs some consideration and I don't see a dire need to rush this. Feel free to re-milestone.

**Comment by anntzer** [comment]
General agreement during call was to close this, but @timhoffm gets to reopen this if he wants :)

**Comment by timhoffm** [comment]
Let's keep this closed for now. There are enough other battles to fight.

However, I reserve the right to revisit. :smile:

**Pull request closed without merging**
