### PR TITLE
Update flake8.txt

### PR DESCRIPTION
**Pull request by reyesvicente**
Updated flake8 to 6.1.0

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
Unless you can motivate why this is needed (e.g. do older versions of flake8 error with current config?) then I'm :-1: on bumping the version of this dependency, especially to such a recent version. We generally wish to keep development tools where at least a year old version works while we are able.

If you are coming here for hacktoberfest, we kindly ask that you check out the [Good First Issue](https://github.com/matplotlib/matplotlib/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22) label. In particular, an easy entry point may be one of the entries in #26864 

I've marked this as spam because it is a low-effort pull request that has no explanation of why the change was made.

**Comment by reyesvicente** [comment]
The update is needed for security purposes.

**Comment by jklymak** [comment]
Please cite the security issue, or close the PR.

**Comment by reyesvicente** [comment]
Please don't tag as spam. I'll close this. This will serve as a lesson to me. Thank you for your kind consideration.

**Pull request closed without merging**
