### PR TITLE
Fix typo in color mapping documentation in quick_start.py

### PR DESCRIPTION
**Pull request by lubianat**
## PR summary

I found this typo  while browsing the "Quick start guide." Instead of "a colors," it should read "colors," as far as I can tell. 

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Thanks!  I'm 75/25 in favor of this resolution rather than "by a color in colormap", either would probably be OK, but I also like the version in this PR better.

Thank you for you work on this @lubianat and congratulations on your first merged Matplotib PR 🎉 

I hope we hear from you again!

**Comment by tacaswell** [comment]
@meeseeksmachine please backport to 3.9.x

**Comment by tacaswell** [comment]
My first PR was to change a 4 to a 7 https://github.com/matplotlib/matplotlib/pull/1062

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.9.x

**Pull request merged**
