### PR TITLE
Add protection against out-of-bounds read in ttconv

### PR DESCRIPTION
**Pull request by sauerburger**
This PR addresses https://github.com/matplotlib/matplotlib/issues/20628.

## PR Summary

The member variable `font->numTables` indicates the number of tables stored in the directory table. The size of the memory allocated for the directory table [is derived from this variable](https://github.com/matplotlib/matplotlib/blob/30cbdf7d2e2963f585f9ab21d7c1d31bd09197d0/extern/ttconv/pprdrv_tt.cpp#L1238). This PR adds a safe-guard in `ttfont_sfnts()` to prevent `ptr` to move beyond the end of the table and thus prevent read-access beyond the memory allocated for `font->offset_table`.

See https://github.com/matplotlib/matplotlib/issues/20628

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by jkseppan — APPROVED** [review]
Good catch!

**Review by aitikgupta — APPROVED** [review]
Awesome! 🎉 

Can we introduce a test (likely the code sample in https://github.com/matplotlib/matplotlib/issues/20628#issue-941446747) here?
(that raises another bug, but is there a way we can trigger _only_ this out-of-bounds error?)

Or.. testing ttconv snippets are out of scope of Matplotlib?

**Review by QuLogic — APPROVED** [review]

**Comment by QuLogic** [comment]
You should try to use the [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when you know this fixes the issue.

Since I've merged the other PR, please add a test here.

**Comment by sauerburger** [comment]
> You should try to use the [linking keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) when you know this fixes the issue.

Sorry, about that. I've updated the other open PRs.

> Since I've merged the other PR, please add a test here.

Thanks! I'll rebase the PR.

It would be super difficult to test the initial issue, i.e. a test that would fail on an out-of-bounds read. The table search exits in most cases by chance. At some point, random bytes interpreted as a table name make the algorithm think it is already beyond the sought for entry. To test this manually, I ran `valgrind` with `grep 'pprdrv_tt.cpp:7'` (since I couldn't get the Python suppression to work) and made sure that this problematic memory access disappears.

I can, however, add a test, like the example, to make sure that the output is valid (but this test would succeed in ~99% of the cases even without this PR).

**Comment by QuLogic** [comment]
Yes, but it would at least check that the change from the other PR wouldn't break. We'll have to live with the possibility of a flaky error if this one resurfaces, but that's unlikely anyway.

I was able to replicate this issue in valgrind, so at least that's known to be fixed.

**Pull request merged**
