### PR TITLE
Fix a typo in pyplot tutorial

### PR DESCRIPTION
**Pull request by bingyao**
## PR Summary

This PR changed a comment line in pyplot tutorial:

`interval ]0, 1[` --> `open interval (0, 1)`

### CODE REVIEW

**Comment by WeatherGod** [comment]
to be honest, I don't think it is a typo, but rather an odd convention that I have rarely seen. I think this is much clearer (by stating "open interval"), as well as using a more common notation.

**Comment by ImportanceOfBeingErnest** [comment]
It's not odd. Square brackets pointing outwards `]x,y[` denote open intervals according to [ISO 31-11:1992](https://en.wikipedia.org/wiki/ISO_31-11)

Picture from [wikipedia](https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints):

image

It's also what I learned at school and I was rather supprised about the alternative `(x,y)` when I first saw it.

**Comment by anntzer** [comment]
In think "open" square brackets may be more of an European thing? (I prefer them too, but heh.)

**Comment by timhoffm** [comment]
I also prefer the open square bracket because it cannot be mixed up with a tuple. Anyway the "open interval" makes it clear enough.

**Pull request merged**
