### PR TITLE
Deprecate update_datalim_bounds.

### PR DESCRIPTION
**Pull request by anntzer**
This method was introduced in 56d43e6 with a note that it would be more
efficient to use it in some cases, then the note went away in ad74c3f
(2008) without the method ever being used either before or after.  In
any case, it is simple enough to be reimplemented (possibly inline) if
we really need it.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Mentioned the alternative (which is just inlining the existing implementation).

**Comment by anntzer** [comment]
rebased

**Comment by jklymak** [comment]
sorry, too many merges and this needs to be rebased again...

**Comment by jklymak** [comment]
... did it with the online editor.

**Pull request merged**
