### PR TITLE
style: make grid more discreet in dark_background

### PR DESCRIPTION
**Pull request by ubitux**
## PR Summary

Currently:
grid-cur

Proposed:
grid-fix

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by story645** [comment]
I think this is a fairly reasonable change (though I'd prefer the grid a touch darker) given that in light mode the grid is lighter than the axes and this style is supposed to be analogous.

**Comment by ubitux** [comment]
> thanks for the PR! I think this is a reasonable change (though I'd prefer the grid a touch darker) given that in light mode the grid is lighter than the axes and this style is supposed to be analogous.

Even darker? Did you mean lighter? Something like `777777` maybe?

**Comment by story645** [comment]
> Even darker? Did you mean lighter? Something like 777777 maybe?

Sorry meant brighter/closer to white, something like EEEEEE/DDDDD maybe?

**Comment by ubitux** [comment]
> > Even darker? Did you mean lighter? Something like 777777 maybe?
> 
> Yeah, sorry meant brighter/closer to white, something in the .7-.9 range

This is going to be way too light. They eye is more sensitive to nuances in the dark colors, and you have to take into account gamma compression, so you can't just be symmetric to the light colors mathematically. Also, color models are extremely complex, you're better off choosing with your eyes. For the record, here is with `bbbbbb` (73%):

bbbbbb

And here is `777777`:

**Comment by jklymak** [comment]
Is this a proposed new style.  I don't the wrong change the existing styles for compatibility reasons.

**Comment by ubitux** [comment]
> Is this a proposed new style? I don't think we change the existing styles for compatibility reasons.

No it's simply adjusting the grid color for the `dark_background` style; I have a hard time believing people appreciate the current grid color since enabling it tends to make the graph unreadable.

@story645 do you want me to update the commit to switch to `777777`?

Also, is the CI supposed to pass currently?

**Comment by jklymak** [comment]
Like it or not the current style is the current style and it's hard to know whether anyone likes it or not.  But our policy is pretty clear that we won't change existing styles and we are extremely parsimonious about adding new styles.

**Review by jklymak — CHANGES_REQUESTED** [review]
We can't just change an existing style.

**Comment by ubitux** [comment]
OK too bad; If we are to add a new theme, I'd rather re-do it entirely, but that's going to be too much work for me so I'll pass. I'll keep this as a local change for now and hope for the best with regards to https://github.com/matplotlib/matplotlib/issues/23599

**Comment by story645** [comment]
> @story645 do you want me to update the commit to switch to 777777?
Yes, and I don't think it's worth closing this w/o a discussion. 

@jklymak if we can't change the existing style, then I think in this case it's very much worth it to add a new dark style with lighter gridlines. I think the gridlines being white in the current dark style is kind of a bug since that behavior is inconsistent with the default behavior on the light theme - ie in the light theme, the gridlines are not the same color as the axes.

**Comment by ubitux** [comment]
Here are the default and different flavors:

colors

**Comment by story645** [comment]
I think 7 and 6 are great and also going by the documentation on the dark background, I'm really not sure that white gridlines for dark gray lines was intentional. 
This 
https://github.com/matplotlib/matplotlib/blob/ecab6dec78b41933ed2b162a236cbda431858e3d/lib/matplotlib/mpl-data/stylelib/dark_background.mplstyle#L1

sounds like the intent was black->white and the gridlines got bundled in

**Comment by tacaswell** [comment]
It is our long standing position that because we are a plotting library the visual output is part of the API and hence changes to the style is an API change.  This is reflected in the test suite where we do exact image comparisons for many of the tests.   This is also the reason why we did v2.0 for changing the default styles and our "seaborn" styles no longer actually match seaborn (because seaborn changed and we did not follow).   In many ways changing the visual appearance is a much more insidious change than a change that breaks user code.  At least if the code raises the user knows something in broken, if we have "just" changed the styling everything works, but the output is changed!

We also have a soft moratorium on new styles and color maps due to this.  We can not easily change them after they are released and do not want to end up with a growing number of subtle variations. 

I am not sure how you are making the local changes, but

```python
mpl.style.use(['dark_background', {'grid.color': '#777'}])
```

works to easily tweak a style (or even combine multiple styles!).

-----

Thank you for your work on this @ubitux , however I think it is very unlikely we will take a change to the style at this time.  I hope you are not discouraged and we hear from you again!

I am undecided on if we should add more dark style files, but if we do it should be more substantial than just changing the grid color.   

-----

As an unrelated side point, circleCI builds from the tip of your branch not from the implicit merge commit.  I think this is branched from a very old commit so you are seeing a very old (and now bit-rotted) circleci config.  Rebasing on main would fix the docs build.

**Review by tacaswell — CHANGES_REQUESTED** [review]
As discussed in a comment, changes to styles are API changes.

**Comment by story645** [comment]
So the context for this PR was @ubitux made a comment on twitter about the grid [link](https://twitter.com/insouris/status/1557418414028750851) so I responded open an issue/PR because far as I know that's the route folks are supposed to take to raise suggestions. @ubitux then had this PR in within 30 minutes, which I think is amazing. 

I understand that this is an API change, which is why I labeled it as such, but we merge the occasional API change when warranted. I think here grids that are the same color as the axis are generally unwanted, which I think is supported by the matplotlib docs. I'm honestly unsure here if the grid is a different color or appears as such because it is so much thinner than the axis https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/mpl-data/stylelib/classic.mplstyle#L279, but that is the sort of perceptual issue where a 1-1 approach might not work, as mentioned in https://github.com/matplotlib/matplotlib/pull/23598#issuecomment-1211114702
https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.grid.html?highlight=grid#examples-using-matplotlib-axes-axes-grid
image

but also the grid width is not set in the dark background - is .5 the default?

**Comment by timhoffm** [comment]
IMHO we need to become better at theme-management

- We need stability guarantees for those who need them.
- We need an update strategy.
- We need better ways to include external themes.

I think one fundamental aspect for addressing the first two issues is theme versioning: We need something like
```
plt.style.use("dark_background-v1")  # The current style
plt.style.use("dark_background-v2")  # The new style
plt.style.use("dark_background")  # Use the newest version available in your matplotlib installation.
```
People who need stability can pin a version. People who want follow updates use the unpinned version.

This would also help e.g. with the seaborn style syncing issue #22317, #13680, #14331.

**Comment by jklymak** [comment]
We should discuss on the call, but I'm not convinced having a "pinnable" style, but the main style changing at arbitrary points in the dev cycle is very desirable either.  If you have old code, and you understandably didn't realize you needed to pin, its still going to cause reproducibility problems.  

I'm also concerned with PR churn as folks tweak styles.  "surely no one likes the ticks [that long/pointing outward/that thick]", "publishable plots must use [latex fonts/serifed fonts/sans-serif]", "surely no one wants the title [so large, so small]". etc etc.  and then we change it, and the original designer will rightly ask "why did you mess with the style I made"?  

The current method to inject a new style is to put the style sheet somewhere and reference it, or put it in `mpl_configdir/stylib` where we will automatically pick it up.  https://matplotlib.org/stable/tutorials/introductory/customizing.html#defining-your-own-style. That seems pretty flexible and straight forward to me?

**Comment by timhoffm** [comment]
Unfortunately, I'll not be on the call today. 

> If you have old code, and you understandably didn't realize you needed to pin, its still going to cause reproducibility problems

This could only be prevented by a "we never change a style ever" policy, which IMHO is overly restictive and has downsides of its own.

**Comment by jklymak** [comment]
> This could only be prevented by a "we never change a style ever" policy,

In recent times, Matplotlib only changed styles in the 2.0-3.0 transition, with lots of notice and advertisement.

**Comment by story645** [comment]
So as discussed on the call, closing this for now cause we have to sort out the policy and we'll move discussion of styles to the appropriate issues.

Thanks so much @ubitux for the very quick turnaround on the PR and spurring the discussion & sorry for any time wasted on your part during this back and forth.

**Pull request closed without merging**
