### PR TITLE
Implement Qt4 backend by fully reexporting Qt5 backend.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

All's in the title: transform the Qt4 backend into a thin shell that just reexports everything from the Qt5 backend.

## PR Checklist

- [ ] Has Pytest style unit tests
- [X] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by fariza** [comment]
The decision tree is not working properly

I have pyside installed, and 4/5 work (5 shoulnd't work)
If I install sip, then neither 4/5 works (import error PyQtx), but I still have pyside installed, so they must work
If I install pyqtx then starts working

**Comment by tacaswell** [comment]
@fariza I think that is more of a problem in the `qt_compat` than with this?

**Comment by fariza** [comment]
sorry, my bad

**Comment by tacaswell** [comment]
@fariza No worries!

**Pull request merged**
