### PR TITLE
Cycler signature code format fix

### PR DESCRIPTION
**Pull request by MarioChao**
## PR summary

The call signature code for form2 is incorrect. This pull request changed `set_prop_cycle(label=values[, label2=values2[, ...]])` to `set_prop_cycle(label=values, label2=values2, ...)`.

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
Thank you for your interest in improving Matplotlib!  However, I believe the square brackets here are intended, and are meant to convey that the second and further parameter are optional.

**Review by kiruthikpurpose — APPROVED** [review]

**Comment by tacaswell** [comment]
The `[]` are indeed intentional (riffing on the style used in https://docs.python.org/3/library/socket.html#socket.socketpair as an example) but I agree that in this case they are not helping that much.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
The mypy failure looks to be happening to all jobs as of 18 hours ago so I'm going to merge over it.

**Comment by tacaswell** [comment]
Thank you for your work @MarioChao and congratulations on your first merged Matplotlib PR :tada: I hope we hear from you again!

**Pull request merged**
