### PR TITLE
Fix doc references in subclasses of `mpl._enum` members

### LINKED ISSUE #19839: Subclasses of Polygon with numpydoc xref throws error b/c of CapStyle, JoinStyle
### Problem

The sphinx links to `CapStyle`  and `JoinStyle` in v3.4.0 are relative to the file, so a subclass of `matplotlib.patches.Patch` in a package with numpydoc xref (https://numpydoc.readthedocs.io/en/latest/install.html) turned on cannot link to the objects and errors with.
```WARNING: py:obj reference target not found: CapStyle```
```WARNING: py:obj reference target not found: JoinStyle```

https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch.set_capstyle
https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Patch.html#matplotlib.patches.Patch.set_joinstyle

```
   @docstring.interpd
    def set_capstyle(self, s):
        """
        Set the `.CapStyle`.

        Parameters
        ----------
        s : `.CapStyle` or %(CapStyle)s
        """
        cs = CapStyle(s)
        self._capstyle = cs
        self.stale = True
```

**Edit:**

The problem also appears to involve ``Patches.__init__``. I can monkey-patch a fix with 

```
Polygon.__init__.__doc__ = Polygon.__init__.__doc__.replace(
    "`.CapStyle`", "``matplotlib._enums.CapStyle``")
Polygon.__init__.__doc__ = Polygon.__init__.__doc__.replace(
    "`.JoinStyle`", "``matplotlib._enums.JoinStyle``")
Polygon.set_capstyle.__doc__ = Polygon.set_capstyle.__doc__.replace(
    "`.CapStyle`", "``matplotlib._enums.CapStyle``")
Polygon.set_joinstyle.__doc__ = Polygon.set_joinstyle.__doc__.replace(
    "`.JoinStyle`", "``matplotlib._enums.JoinStyle``")
```

### Suggested Improvement

* This line could be be changed to say
```
   @docstring.interpd
    def set_capstyle(self, s):
        """
        Set the `~matplotlib._enums.CapStyle`.

        Parameters
        ----------
        s : `~matplotlib._enums.CapStyle` or %(CapStyle)s
        """
        cs = CapStyle(s)
        self._capstyle = cs
        self.stale = True
```

**Matplotlib version**

  * Operating system: Big Sur & Ubuntu
  * Matplotlib version 3.4.0
  * Matplotlib documentation version (is listed under the logo): 3.4.0

### PR DESCRIPTION
**Pull request by brunobeltran**
Avoid using explicit references to private module in docs, instead let
intersphinx handle it.

## PR Summary

`numpydoc`'s xref breaks for external subclasses of `Patch` because we use references to `.CapStyle` and `.JoinStyle` (after importing those classes), but external library authors subclassing Patch are certainly not required to import them, so numpydoc cannot resolve the unqualified reference.

<strike>We do not wish to expose the full reference, `matplotlib._enum.CapStyle` (and similar for `JoinStyle`) in order to avoid tieing ourselves to this experimental/private module as much as possible. 

Therefore, [as mentioned here](https://github.com/matplotlib/matplotlib/issues/19839#issuecomment-816207094), this PR instead changes the references to the form `CapStyle_` and `JoinStyle_` to allow intersphinx to handle them.</strike>

Trying to add the full reference `~matplotlib._enums.CapStyle` everywhere in the docstrings where it is relevant creates an absolute mess of docstring lines that are way too long in ways that can't be fixed. Since we're already using interpolation in most of the same places to list out the possible Join/CapStyles (`%(JoinStyle)s` expands to `('miter', 'round', 'bevel')`), we add `%(JoinStyleL)s` that exands to ` ``~matplotlib._enums.JoinStyle`` `

This should fix #19839.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by brunobeltran** [comment]
First attempt threw warnings after passing locally, I'll mark as draft until it's passing.

**Comment by brunobeltran** [comment]
Pretty sure the original strategy proposed (on a call during my post-graduation absence) of changing `\`.CapStyle\`` to `CapStyle_` won't work because autodoc actually generates restructuredtext references of the form `matplotlib._enum.CapStyle`, so it would not actually hide it. Therefore I'm just going to drop the whole string in there. I don't think hiding the existence of the `_enums` module should be as high of a priority as fixing #19839.

**Comment by jklymak** [comment]
@brunobeltran how can we test this with other projects?  Do you suggest merging and then just asking one of them to test their intersphinx?

**Comment by timhoffm** [comment]
> Pretty sure the original strategy proposed (on a call during my post-graduation absence) of changing `.CapStyle` to `CapStyle_` won't work because autodoc actually generates restructuredtext references of the form `matplotlib._enum.CapStyle` (as seen on the [current build](https://matplotlib.org/stable/api/_enums_api.html?highlight=joinstyle#matplotlib._enums.JoinStyle)), so it would not actually hide it. 

I'm not sure I'm following. Wasn't there the idea of using ReST labels and references.

```
cs : :ref:`CapStyle` or %(CapStyle)s
```
and 

```
.. _CapStyle:

.. autoclass:: CapStyle
      :members: demo
      :exclude-members: butt, round, projecting, input_description
```

so that we're not dependent on name resolution at all?

**Comment by jklymak** [comment]
I'm not sure the original issue is still an issue, so I'll close this, but feel free to request a re-open.

**Pull request closed without merging**
