### PR TITLE
[MRG+1] Remove image with non-free color calibration profile

### LINKED ISSUE #8034: necked_tensile_specimen.png contains non-free color calibration profile
Hello,
as reported in http://bugs.debian.org/854280, lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png calibration code is copyrighted by Apple but no license is specified, so the "all rights reserved" means it's a non-free package, possible even totally non-distributable (ie it shouldnt be in the upstream tarball/repo at all):

```
$ exiftool lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png
ExifTool Version Number         : 10.40
File Name                       : necked_tensile_specimen.png
Directory                       : lib/matplotlib/mpl-data/sample_data
File Size                       : 93 kB
File Modification Date/Time     : 2017:01:17 22:48:59-05:00
File Access Date/Time           : 2017:01:17 22:48:59-05:00
File Inode Change Date/Time     : 2017:01:17 22:48:59-05:00
File Permissions                : rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 634
Image Height                    : 945
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Profile Name                    : ICC Profile
Profile CMM Type                : appl
Profile Version                 : 2.2.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2009:02:25 11:26:11
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             : appl
Device Model                    : 
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : appl
Profile ID                      : 0
Profile Description             : Generic RGB Profile
Profile Description ML (sk-SK)  : Všeobecný RGB profil
Profile Description ML (hr-HR)  : Generički RGB profil
Profile Description ML (ca-ES)  : Perfil RGB genèric
Profile Description ML (pt-BR)  : Perfil RGB Genérico
Profile Description ML (uk-UA)  : Загальний профайл RGB
Profile Description ML (fr-FU)  : Profil générique RVB
Profile Description ML (zh-TW)  : 通用 RGB 色彩描述
Profile Description ML (it-IT)  : Profilo RGB generico
Profile Description ML (nb-NO)  : Generisk RGB-profil
Profile Description ML (ko-KR)  : 일반 RGB 프로파일
Profile Description ML (cs-CZ)  : Obecný RGB profil
Profile Description ML (he-IL)  : פרופיל RGB כללי
Profile Description ML (de-DE)  : Allgemeines RGB-Profil
Profile Description ML (hu-HU)  : Általános RGB profil
Profile Description ML (sv-SE)  : Generisk RGB-profil
Profile Description ML (zh-CN)  : 普通 RGB 描述文件
Profile Description ML (ja-JP)  : 一般 RGB プロファイル
Profile Description ML (ro-RO)  : Profil RGB generic
Profile Description ML (el-GR)  : Γενικό προφίλ RGB
Profile Description ML (pt-PO)  : Perfil RGB genérico
Profile Description ML (nl-NL)  : Algemeen RGB-profiel
Profile Description ML (es-ES)  : Perfil RGB genérico
Profile Description ML (th-TH)  : โปรไฟล์ RGB ทั่วไป
Profile Description ML (tr-TR)  : Genel RGB Profili
Profile Description ML (fi-FI)  : Yleinen RGB-profiili
Profile Description ML (pl-PL)  : Uniwersalny profil RGB
Profile Description ML (ru-RU)  : Общий профиль RGB
Profile Description ML (ar-EG)  : ملف تعريف RGB العام
Profile Description ML          : Generic RGB Profile
Profile Description ML (da-DK)  : Generel RGB-beskrivelse
Profile Copyright               : Copyright 2007 Apple Inc., all rights reserved.
Media White Point               : 0.95047 1 1.0891
Red Matrix Column               : 0.4543 0.24191 0.01489
Green Matrix Column             : 0.35335 0.67363 0.09064
Blue Matrix Column              : 0.15665 0.08446 0.71957
Red Tone Reproduction Curve     : (Binary data 14 bytes, use -b option to extract)
Chromatic Adaptation            : 1.04788 0.02292 -0.0502 0.02957 0.99049 -0.01706 -0.00923 0.01508 0.75165
Blue Tone Reproduction Curve    : (Binary data 14 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 14 bytes, use -b option to extract)
Pixels Per Unit X               : 2835
Pixels Per Unit Y               : 2835
Pixel Units                     : meters
XMP Toolkit                     : XMP Core 5.1.2
Photometric Interpretation      : RGB
Orientation                     : Horizontal (normal)
Image Size                      : 634x945
Megapixels                      : 0.599
```

what would be the impact (in this case for Debian, in the immediate) if we just remove that file from what we distribute in debian? something will break? how badly it would break?

thanks for considering!

### PR DESCRIPTION
**Pull request by tomspur**
The example that used to use this image was remove already in commit 9692c31.

This closes #8034.

### CODE REVIEW

**Comment by tacaswell** [comment]
👍 This should be backported to 2.0.x so debian gets this with the next release.

**Comment by tomspur** [comment]
The PR with the backporting is in #8243. I hope this helps and is the way you usually do the backportings :)

**Comment by tacaswell** [comment]
We usually backport by cherry-picking the merge, but this is fine too.

**Comment by tomspur** [comment]
This wouldn't have been possible in this case as the example that used this image is removed in master in a different commit

**Comment by NelleV** [comment]
I would be very surprised that this breaks anyone's code, but this is an incompatible backward change (which I am very happy to ignore)

**Comment by NelleV** [comment]
I am merging without waiting for appveyor to get to that point. (cause we'll be stuck here forever if we wait for appveyor)

**Comment by phobson** [comment]
thanks @tomspur !

**Comment by sandrotosi** [comment]
thanks all!!

**Pull request merged**
