### PR TITLE
Add middle for delims

### LINKED ISSUE #23212: Support `\middle`
### Problem

There is currently no way to use the `\middle` constructor to get an automatically size separator (typically a vertical bar) in the middle of an equation.

Here is a random SE question about what it is (check the answer): https://tex.stackexchange.com/questions/45713/creating-a-large-such-that-symbol

### Proposed solution

Add support for `\middle`.

### PR DESCRIPTION
**Pull request by devRD**
## PR summary
Fixes #23212 

Adds support for `\middle` delimiter

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by oscargus** [comment]
Looks good! Can you please add a test for `\middle .` as well? Both to get code coverage and to confirm that deleting during the loop causes any issue. Should be possible to simply just add it to the new test?

**Review by oscargus — APPROVED** [review]

**Comment by jklymak** [comment]
I'm confused why so many other images needed to be regenerated?

**Comment by devRD** [comment]
It does look strange, yes. I'm unsure why the additional images were regenerated as they don't look that far off from the original but these images all use the `\left` and `\right` delimiters... maybe it's regenerating because this PR touched that part?

**Comment by oscargus** [comment]
There are some minor changes in the spacing, although quite hard to spot. I guess this is because the width and height is computed slightly different now.

Not sure if you have tried this, but what about doing the added for-loop before determining width and height?

**Comment by devRD** [comment]
Thanks for the suggestion! @oscargus 

I tested moving the for-loop before the height and depth calculation, but it doesn't set the `AutoHeightChar` for the middle delimiters. Moving it inside the `if len(middle):` after the height calculation works without the additional images being regenerated.

**Review by ksunden — APPROVED** [review]

**Pull request merged**
