### PR TITLE
Fix agg image size rounding

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by mdboom** [comment]
If anything, I would think `ceil` would be correct (if there's partial pixels on the edge, maybe we want to keep them), but I think truncation is fine, too (if there's partial pixels on the edge, clip them so it doesn't look messy on the edge).  But rounding doesn't make much intuitive sense.  Is there a specific bug for this?

**Comment by tacaswell** [comment]
Sorry, #4280

**Comment by tacaswell** [comment]
This is an issue with float precision and computing the size in inches for a given number of pixels + dpi where  `(pixels / dpi) * dpi != pixels`, rounding does the right thing when it is off by `+/- 1e-16`.

**Comment by mdboom** [comment]
Hmm...  I'm just worried about the repurcussions in the other code path (when not saving a figure image), if `inches * dpi` is non-integer such that it rounds up and you would get grey antialising lines in the right and lower pixels.  I wonder if there's a way to account for this in `FigureImage` (it's not obvious at first glance, unfortunately).  That would at least reduce the effective area of this change.

**Comment by tacaswell** [comment]
I don't follow on the aliasing issue, but I understand far less of agg than
I should.

**Comment by efiring** [comment]
If the intention is to handle only the floating point arithmetic error, then instead of rounding one could add a very small number before truncating.  Granted, this is a messy solution involving picking a magic number that almost always does what one wants; but I think it would solve the problem 99.9% of the time with minimal side effects.

**Comment by tacaswell** [comment]
another option is to push the rounding logic out a bit more to impact fewer code-paths.  I did it as close to the c-layer as possible here (exactly to hit as many code paths as possible).

**Comment by mdboom** [comment]
I think #5718 fixes most of the things this was trying to solve, so we should probably just close this.  Feel free to reopen if I misunderstand.

**Pull request closed without merging**
