### PR TITLE
fixed ordering of lightness plots and changed from getting lightness …

### PR DESCRIPTION
**Pull request by kthyng**
…from CIELAB to CAM02-UCS colorspace. This is to address issue #3791.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Nice can you add the install of colorspacious to our .travis.yml file [here](https://github.com/matplotlib/matplotlib/blob/master/.travis.yml#L81) 

We are building the docs on Travis so we need the dependencies there too

**Comment by jenshnielsen** [comment]
Can we use `colorspacious` in the `grayscale.py` and `Lfunction.py` files in this directory too? That would allow us to get rid of `color.py` and the `colorconf` function there in. I modified the plots at some point to use an internal version of the `colorconf` function from `scikit-image` to reduce the dependencies when building the docs. I think depending on `colorspacious` is fine thou

**Comment by kthyng** [comment]
I haven't done this before — do I just add a line of 
`pip install colorspacious`
after line 81? I'll look at the other scripts to see if colorspacious can be used instead.

**Comment by jenshnielsen** [comment]
Thanks, Adding colorspacious to line 81 should be enough. I.e. it should read:
`pip install $PRE numpydoc ipython colorspacious`

**Comment by jenshnielsen** [comment]
You can ignore the AppVeyor thing. This is fallout from #5595

**Comment by tacaswell** [comment]
@kthyng Thanks!

**Comment by tacaswell** [comment]
backported to 1.5.0-doc as c234879d40bc085cfd9419db69613631c9deb314

**Comment by kthyng** [comment]
I have another PR (#5611) to address @jenshnielsen suggestion to use colorspacious, etc.

**Comment by alimuldal** [comment]
What's the mechanism for updating the documentation on the website? The old inverted image is still being shown on the [Choosing Colormaps page](http://matplotlib.org/users/colormaps.html#miscellaneous).

**Comment by tacaswell** [comment]
The dev-docs are built automatically from master every time we push to it and are hosted at http://matplotlib.org/devdocs/users/colormaps.html  

Updating the main page is a manual process which no one has done yet.  We are going to do a 1.5.1 release this week which will include the updated plots.

**Comment by alimuldal** [comment]
@tacaswell Thanks, that's good to know

**Pull request merged**
