### PR TITLE
FIX: properly check figure on gridspec

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This fixes the check for a figure in `gridspec`.    The current (new) implementation actually instantiates a subplotspec that may not ever be desired by the user, and this messes up `constrained_layout`.  

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
The fact that .figure doesn't exist on sub-subplotspecs is exactly the reason why I went for the "awkward" way of getting the figure.  Adding it seems reasonable (perhaps make it a property instead?)
I'm slightly confused though, is the subplotspec created by `self[0, 0]` "persistent"?  i.e. how comes it affects later constrained_layout calls?  I would have thought that it would be garbage-collected immediately after that line.

**Comment by jklymak** [comment]
Because I make a layout box for it and it gets entered into the layout box tree with parents and children etc. 

TBH I don't think it really affects the future CL calls, but I was sure confused why there was an extra subplotspec in all my trees when debugging.

**Comment by anntzer** [comment]
hmm, should the layoutboxes get removed when the gridspec gets deleted? (in `__del__`).

Regardless I'm fine with the change here but I think figure should be a property on GridSpecFromSubplotSpec (just in case we ever allow any fancy reparenting, and also prevents people from assigning to it :)).

**Comment by jklymak** [comment]
I'm not sure I'm following what making it a property does.  And why not for the parent `GridSpec` as well?

**Pull request merged**
