### PR TITLE
pytest-testmon for GHA

### PR DESCRIPTION
**Pull request by Bogusik**
## PR Summary
Proposed solution for https://github.com/matplotlib/matplotlib/issues/22868.
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
Restarting the GH tests to see if there is any difference in performance.

Question: is a consequence that coverage will not work if this is implemented?

**Comment by oscargus** [comment]
I'm not sure that I follow this. At the second run (where I assume that there should have been some cache?), the time is still the same for both test runs. Can you please explain what is the potential benefit here?

**Comment by tacaswell** [comment]
I am skeptical of using this in our CI, but am in favor of documenting this as a thing that developers may want to use on their local machines.

**Comment by jklymak** [comment]
I'll close here and discuss further in the issue https://github.com/matplotlib/matplotlib/issues/22868.

**Pull request closed without merging**
