### PR TITLE
Fix minor typo in artist tutorial

### PR DESCRIPTION
**Pull request by lesteve**
Replace 'my **x**data' by 'my **y**data' in set_ylabel string argument.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Thanks, Looks good to me

**Comment by tacaswell** [comment]
@jenshnielsen Can you backport this to 1.4.2-doc?

**Comment by jenshnielsen** [comment]
Sure and 1.4.x ?

**Comment by tacaswell** [comment]
I will take care the merge cascade this weekend when I do the release

**Comment by jenshnielsen** [comment]
Done as ebf992d30814c7a4e64db1a8714ae548b9ec1292

**Comment by tacaswell** [comment]
Thank you

**Pull request merged**
