### PR TITLE
Backport of PR 12686 on v2.2.x

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Backports of #12686 and #12431.

Note: I only backport the code of #12431, not the tests and test images. But I assume that's ok as changes are made against master and tested there.

### CODE REVIEW

**Comment by tacaswell** [comment]
Master has moved far enough away from the 2.2.x branch is is probably better to backport the tests as well.

**Comment by ImportanceOfBeingErnest** [comment]
This may be a bit naive, but I'd say one should always backport the tests. Even with tests it's still possible to break things unconsciously, but at least it ensures not to break the very feature that is added.

**Comment by tacaswell** [comment]
Oh, good catch @ImportanceOfBeingErnest !

I miss-read things, I am -0.5 on backporting these PRs as they are not critical bugs in 2.2.x

**Comment by timhoffm** [comment]
Fine with not backporting.

**Pull request closed without merging**
