### PR TITLE
DOC: condense version switcher

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This just makes the version switcher shorter...

Note skipping CI because there is nothing to test here.  

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
Also, this would be where we decide if we want stable/latest or devdocs/dev

**Comment by timhoffm** [comment]
Marking as release critical. If we do nothing, we'll have a version switcher with a very long text for the dev branch in the next release.

**Comment by QuLogic** [comment]
Isn't this about the number of entries, not the dev entry?

**Review by greglucas — APPROVED** [review]
I like dropping the patch version from the dropdown menu and leaving it only at minor versions. Perhaps also drop the "3.5.1 (stable)" and make it "3.5 (stable)"?

3.6 (dev) sounds better to me, we know they are docs already. (Python docs have the order switched to "(dev) 3.6", I'm indifferent on the order)

Do we want to have the version switcher able to go back to 1.x versions? That also adds quite a bit of length to the selector.

The Python docs skip the older versions, going as 2.7, 3.5, 3.6, ... . Perhaps keep only the most recent 2.x version in the dropdown?

**Comment by jklymak** [comment]
I think keeping it as compact as possible makes sense.  Folks can still always find their version manually.

**Comment by QuLogic** [comment]
I think what @greglucas suggested seems reasonable.

**Comment by jklymak** [comment]
This commit just has 3.5, 3.6, 3.4, 3.3, 2.2, and 1.5  Remove 1.5 as well?

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
