### PR TITLE
By default, don't change the figure face/edgecolor on savefig().

### LINKED ISSUE #7619: Figure background colors
I find the current handling of background colors very non-intuitive:
1. figure `facecolor` is not applied for `savefig()` by default
2. figure `facecolor` is not applied setting `frameon=False`
3. `axis_bgcolor` is not applied when hiding axis lines/ticks via `axis('off')`

So using a white plain surface to draw objects needs the following code:

    fig = figure(..., facecolor='w', edgecolor='None')
    ax.axis('equal')        # equal scale
    ax.axis('off')          # do not show axis
    ax.axis([-1, 1, -1, 1]) # scale to unit lengths
    show()
    fig.savefig(..., facecolor=fig.get_facecolor(), edgecolor='None', transparent=True)

My suggestion
- apply same colors to `savefig()` by default
- mention in the docs of `axis_bgcolor` and `axis('off')` that this setting is ignored
- mention in the docs of `facecolor` and `frameon` that this setting is ignored

### PR DESCRIPTION
**Pull request by anntzer**
This seems to repeatedly confuse users.

Closes #7619; fixes https://gitter.im/matplotlib/matplotlib?at=5d5faff768406739f96b2673; alternate for #10023.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
The `dpi` argument accepts `"figure"`. Would it make sense to stay consistent with that and use `"figure"` also for the edge-, and facecolor?

In general this makes much more sense to me than #10023. I don't understand the exitstack thingy so I will leave this for others to review.

**Comment by anntzer** [comment]
For colors, there's already places that accept "auto" and places that accept "inherit" (specifically, legends).  I'd rather not add a third spelling for the same (general) idea.  (In fact I plan to deprecate "inherit" in favor of "auto", but that's a separate issue.)

**Comment by ImportanceOfBeingErnest** [comment]
`"figure"` is still also clearer about the origin of the value. `"auto"` could be anything.

**Comment by anntzer** [comment]
So what do you think the "auto" cases of lines.markerfacecolor, lines.markeredgecolor, boxplot.flierprops.markerfacecolor, and axes.titlecolor should be named?

**Comment by tacaswell** [comment]
I see your your point @ImportanceOfBeingErnest , however I think that the ambiguity of "auto" is a benefit here because we can use the same spelling across a wide range of contexts.

**Pull request merged**
