### PR TITLE
Don't use gdb on Travis (as it breaks the build).

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Let's see whether this helps unbreaking the build...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Duplicate (plus or minus an 'x') #10217...

**Comment by jklymak** [comment]
... which as we can see, *does* unbreak the builds.

**Comment by anntzer** [comment]
Oh, sorry, I saw @QuLogic's original PR but missed your changes.

**Comment by jklymak** [comment]
Did we want -ex for 'set'?  Its '-v' for #10217  ?

**Comment by anntzer** [comment]
I would keep "set -e" (and thus drop the "return $?"); set -x is nice as it removes the need to echo the pytest args ourselves (it's exactly what -x does...); -x also makes -v a bit redundant.
So overall I like -ex...

**Comment by jklymak** [comment]
Done!

**Pull request closed without merging**
