### PR TITLE
Fixed warnings catching and counting with `warnings.catch_warnings`

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by tacaswell** [comment]
This makes sense but what motivated this change?

**Comment by Kojoley** [comment]
`pytest` fails on `test_axes.test_eventplot_problem_kwargs` test and I have discovered that this issue actually persists in other places too, so after that I have discovered that `test_figure.test_too_many_figures` test does not even work.

**Comment by tacaswell** [comment]
pep8 is fixed on master already.

Not bothering to wait for appveyor, it is super backed up today

**Comment by QuLogic** [comment]
Would any of these need backporting?

**Pull request merged**
