### PR TITLE
PRF: change draw -> draw_idle

### LINKED ISSUE #6058: "Configure subplots" tool is initialized very inefficiently in the Qt backends
Instrument `fig.canvas.draw` as follows:
```
from pylab import *
fig, ax = subplots()
__old_draw = fig.canvas.draw
def draw():
    print("drawing")
    __old_draw()
fig.canvas.draw = draw
show()
```
Clicking on the "configure subplots" button shows that in the Qt backends even without touching the sliders, the figure is redrawn 8(!) times just by the time the dialog is created (probably once for each slider initialization).  As a comparison, the Tk backend does not redraw the figure once.
This is rather annoying when working with slow-to-draw figures, e.g. `plt.plot(np.random.rand(1e5))`.

python 3.5.1, matplotlib 1.5.1

### PR DESCRIPTION
**Pull request by tacaswell**
closes #6058

### CODE REVIEW

**Comment by efiring** [comment]
I haven't tested it, but it certainly makes sense.

**Comment by tacaswell** [comment]
attn @anntzer

**Comment by anntzer** [comment]
Performance seems much better.  However, while testing this I noticed another issue: just opening the configure subplots menu (whether with or without this PR) will move the subplots by a tiny amount.  To see this effect, create e.g. a 5x5 array `plt.subplots(5, 5)` and repeatedly open and close the configure subplots menu while paying attention to the position of the subplots.

Perhaps I should create a separate issue for this?

**Comment by tacaswell** [comment]
Open another issue for that (and I can confirm that it happens).

**Comment by anntzer** [comment]
See #6121.

**Comment by tacaswell** [comment]
about to push a fix to #6121   :heart:  asynchronous programming

**Comment by tacaswell** [comment]
See the commit message for an explanation of what was going on.  @anntzer Good catch!

**Pull request merged**
