### PR TITLE
[ENH] : Provide axis('equal') for Axes3D (replace PR #22705)

### PR DESCRIPTION
**Pull request by patquem**
## PR Summary
Closes https://github.com/matplotlib/matplotlib/issues/22570
Make axis('equal') available

@oscargus 
Replace PR #22705 with a separate dedicated branch

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by oscargus — APPROVED** [review]

**Comment by scottshambaugh** [comment]
A 'what's new' entry would be great for this one

**Comment by jklymak** [comment]
@patquem can you add a What New Note (`doc/users/next-whats-new`) and move back out of draft?

**Comment by scottshambaugh** [comment]
If patquem is not reachable I'd say we merge without the what's new note and I can make a separate PR to add that in. Would hate to miss 3.6 on this great feature just because of that.

**Comment by QuLogic** [comment]
This needs a rebase to fix conflicts as well.

**Comment by jklymak** [comment]
@scottshambaugh maybe you could open a new PR based on this one, rebased and with the note?  If you keep the authored-by comment in the commit message the original author will still get credit.

**Comment by scottshambaugh** [comment]
This can close with the merge of https://github.com/matplotlib/matplotlib/pull/23409

**Comment by tacaswell** [comment]
Thank you for your work on this @patquem !

**Pull request closed without merging**
