### PR TITLE
verify here

### PR DESCRIPTION
**Pull request by krishvsoni**
Matplotlib is a versatile Python library that allows you to create a wide range of visualizations, including static images, animated plots, and interactive charts.

### CODE REVIEW

**Comment by rcomer** [comment]
Discussion is happening on #26973, so let’s close this one.

**Comment by krishvsoni** [comment]
Please this was first time I have contributed in hacktoberfest can you please revoke spam from me, I will take care of that by mistake i sent two PR due to changing in branch i was confused, I apologise for that.

Thanks

**Comment by rcomer** [comment]
I think it's reasonable to remove the label from the duplicate at least.  Two strikes for the same change seems a bit harsh.

**Comment by rcomer** [comment]
@krishvsoni please have a look at projects' issues lists to find out what changes they actually want.  You may be interested in #26864, which is split into lots of small tasks, expecting lots of small PRs.

**Comment by krishvsoni** [comment]
Thanks alot @rcomer for helping me!!

**Comment by krishvsoni** [comment]
Can you please remove this also , I will take care that it wont happen again
https://github.com/matplotlib/matplotlib/pull/26973

**Pull request closed without merging**
