### PR TITLE
Merge 2.x to master

### PR DESCRIPTION
**Pull request by efiring**
There were 3 conflicts, so I am using a PR for this merge to allow more checking.

### CODE REVIEW

**Comment by tacaswell** [comment]
I merged `style_sheets.rst` into `customizing.rst`, it looks like `style_sheets.rst` got resurected?

**Comment by efiring** [comment]
Yes, I misinterpreted the situation.  I will re-kill style_sheets.rst.

**Comment by efiring** [comment]
Two failures: a sphinx problem in an old whats_new in the docs, and one svg image comparison failure in the pytest build (/home/travis/build/matplotlib/matplotlib/result_images/test_mplot3d/mixedsubplot.svg).

**Comment by tacaswell** [comment]
I have fixed the reference and re-started the pytest run (that smelled like a transient to me).  If the svg failure is transient I will push this + my extra commit to fix the ref directly to master.

**Pull request merged**
