### PR TITLE
Make legend title fontsize obey fontsize kwarg by default

### PR DESCRIPTION
**Pull request by gepcel**
As the issue [#8699](https://github.com/matplotlib/matplotlib/issues/8699) from long time ago stats, I often found this annoying. Seems like nobody is against this idea, and it is a really simple modification. So I'm pulling a request.

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks for the PR.  Seems reasonable to me.  

To get this to pass, you'll (unfortunately) need to update some of the `test_legend` image files.  See https://travis-ci.org/matplotlib/matplotlib/jobs/299639390#L2312

**Comment by gepcel** [comment]
I'll find some time to see what I can.

**Comment by jklymak** [comment]
You could alternatively add a fantasize argument to the legend entries on the failing tests to match the test image sizes.  That would be easier on the repository size.

**Comment by gepcel** [comment]
@jklymak Sorry for the delay. Now I'm planning to complete this. But I'm new to this. Can you help me out?

If I understands right, there are a few images failed in the tests due to the font size of legend title. `fancy`, and `scatter_rc1`, and `scatter_rc3` (.pdf, .png, .svg) to be specific. So I'm supposed to generate those **9** images with the latest master code and include those in a commits. Right?

And by what you say `a fantasize argument`, I'm guessing you mean I can modify the test code so that the font size of legend title matches the old ones. Maybe like:
```python
lg = legend(...)
lg.get_title().set_fontsize(10)
```

Am I guessing right? Would please explain a little?

I'm really new to this. Now I'm actually starting from reading [The Matplotlib Developers’ Guide](http://matplotlib.org/devel/contributing.html#retrieving-and-installing-the-latest-version-of-the-code). Any help would be appreciated.

**Comment by WeatherGod** [comment]
Why would it be necessary to set the fontsize in the tests? That would mean that this is a breaking change. I would have figured that this should only fix the situation where fontsize was explicitly specified as a keyword argument? In which case, we would need a test that demonstrated that that works now.

**Comment by jklymak** [comment]
Yes, I'm confused now.  There is a bunch of fontsize handling stuff above this.  Why is it wrong and why don't you fix up there?  Certainly if you have to grab the title fontsize after instantiation there is something awry.  I *think* whats happening is the legend title is set to whatever the legend fontsize is perfectly reasonable....

**Comment by jklymak** [comment]
Oh, OK, I see, it wasn't respecting the legend fontsize or the legend font properties.  

I'm not clear on what `TextArea` defaults to in terms of properties?  Axes default fonts?  In which case it begs the question what is better, to default to the rest of legend or default to the rest of the axes.

**Comment by gepcel** [comment]
@WeatherGod, You were right, by this pull request, I just want the fontsize of legend title to obay the fontsize kwarg of `plt.legend()`. But since the tests failed, and after trying very hard I failed to set up a develop environment, thus I can't test changes locally. Since the only thing changed was the legend title fontsize, I thought that setting the fontsize back in the `tests` would be an easy way to get this commits passed. Still trying to figure out how to make this work.

Please anyone give me some instructions on what to do next. Or just make this right (much easier than teaching me to do it).

**Comment by jklymak** [comment]
I think @WeatherGod  point is that the legend title's font properties are set by the axes font properties.  The logic is that the legend font properties are for inside the legend, and the title is outside.  If you want to change the behaviour thats a bigger discussion.  I appologize if I mislead you above.  I thought that the legend's title font properties weren't controllable at all.

**Comment by gepcel** [comment]
@jklymak. Before this, the fontsize of legend item labels is 'large'. And the legend title doesn't pick this as its own size, so maybe ~~10~~ 12 as the default font size. After [the change](https://github.com/matplotlib/matplotlib/pull/9731/files#diff-58172dfa9d6f39eba6a725389fbf179bR706), the fontsize title would be `large`, the same as legend item labels.

After another looking, maybe I picked a wrong version of `matplotlibrc`, which says `font.size=10, legend.fontsize='medium'`, instead of `12`, and `large`. And of all tests, this will only affect those with a legend and more importantly with a legend title. That's the reason I only changes those few lines in tests. Maybe there's more I haven't noticed. 

As your question "what is better, to default to the rest of legend or default to the rest of the axes".  I think default to the legend is more sensible. And besides that, it makes more sense that `plt.legend(fontsize=somevalue)` would change the title all together (the kwarg is not something like  `label_fontsize` after all). And `lg.get_title().set_fontsize(some_other_value)` to change it if not suited.

**Comment by gepcel** [comment]
@WeatherGod, So these falls to 2 questions:

* Without a `fontsize` kwarg, should the fontsize of lebend title defaults to `label.fontsize` of legend or `font.size` of the default of others.
* With a `fontsize` kwargs, would it better to set the whole legend font size or better to only set the item labels without the title.

**Comment by jklymak** [comment]
There is merit to that argument, but as @WeatherGod says, its a "breaking change" in that people who were counting on the old behaviour will be discomfited by the new behaviour.  So, it needs a consensus that the breakage is acceptable.

**Comment by jklymak** [comment]
I think for 3.0 we could consider adding this kwarg again.  @gepcel did you manage to set up a development environment, or did you want someone else to take this over?

**Comment by jklymak** [comment]
@gepcel Thanks so much for your work on this.  This approach makes some sense, but is a breaking change. I've proposed an alternate at #10715 that is not a breaking change.  i.e it will keep the old behaviour by default, but allow users to set the legend title to a different fontsize if they wish.  I hope this is OK w/ you and would suit your needs.  I'll keep this open in the case that it does not.

**Pull request closed without merging**
