### PR TITLE
Reducing repetitive computations and simplified rotation calculation

### PR DESCRIPTION
**Pull request by Akshat111111**
## PR summary
[MNT]: Reducing repetitive computations and simplified rotation calculation in proj3d.py https://github.com/matplotlib/matplotlib/issues/27186
reduced the repetitive computations by storing the repetitive values like (1/dx,1/dy,1/dz). Apart from it using the Numpy function effectively for vectored operations.
And the rotation_about_vector function is also enhanced by removing not required intermediate variables.
As well as implemented vectorized division and column stacking in multiple places.

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
@Akshat111111 over the last couple of weeks you have [opened PRs in a variety of projects](https://github.com/pulls?q=is%3Apr+author%3AAkshat111111+archived%3Afalse+-user%3AAkshat111111+).  In several of these, the maintainers have questioned the purpose of the change.  Some have taken the time to give a detailed review.  So far, none have been merged.  This does not look to me like a good use of maintainers' time.

If you want to make a genuine contribution, please have a look through projects' issues list to find out what changes they want.

**Comment by tacaswell** [comment]
I am going to close this for now.  If you want to clean this up by removing the extraneous changes please do so and ask to have the PR re-opened.

**Comment by Akshat111111** [comment]
> @Akshat111111 over the last couple of weeks you have [opened PRs in a variety of projects](https://github.com/pulls?q=is%3Apr+author%3AAkshat111111+archived%3Afalse+-user%3AAkshat111111+). In several of these, the maintainers have questioned the purpose of the change. Some have taken the time to give a detailed review. So far, none have been merged. This does not look to me like a good use of maintainers' time.
> 
> If you want to make a genuine contribution, please have a look through projects' issues list to find out what changes they want.

Sure, But I am also suggesting my point of view in order to improve the efficiency and performance of the existing codebase. But I will focus more on the existing issues and understand your point of view.I request you to please change the label.

**Comment by Akshat111111** [comment]
> There is no reason to change docstrings to comments, or remove deprecations from functions. It makes it very difficult to determine what it is you actually intend here as an optimization. Please remove the superfluous changes so that it is clearer what is going on here. Also, did you run any benchmarks to show that these are indeed faster?

I agree with you, but I have gone through the documentation, and currently working on the performance optimization.But the rotation is actually simplified in accordance to local machine,But I am working more on it, in order to address it effectively.

**Comment by jklymak** [comment]
If you work on it please submit a new PR with an explanation of the performance improvement ideally with evidence of an improvement using benchmarks.  Not me the pr should pass our tests or you should modify the test to show what changed

**Comment by Akshat111111** [comment]
> If you work on it please submit a new PR with an explanation of the performance improvement ideally with evidence of an improvement using benchmarks. Note the pr should pass our tests or you should modify the test to show what changed

Sure, I will do as you have instructed with a brief explanation and after effects, Please change the label of it please.

**Pull request closed without merging**
