### PR TITLE
backport pr 18549

### PR DESCRIPTION
**Pull request by jklymak**
Backport of #18549 to v3.3.x

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by dopplershift — APPROVED** [review]

**Comment by timhoffm** [comment]
Travis OSX failure is #18551 and should probably be cleared before merging.

**Comment by jklymak** [comment]
I don't think there is anything here that is MacOS specific.

**Comment by timhoffm** [comment]
If we are confident this doesn't make resolving #18551 harder, we can merge.

**Comment by jklymak** [comment]
99.5% confident?  I'll merge...

**Pull request merged**
