### PR TITLE
Arrow head color fix to match arrow body

### LINKED ISSUE #11759: The color of the 3D arrow head does not match that of the arrow body
### Bug report

**Bug summary**

The color of the 3D arrow head does not match that of the arrow body. (In fact, the two segments of head itself don't even match.)

Not sure if it is related to #11746, so I posted it separately just to make things clearer.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

x = np.zeros(10)
y = np.zeros(10)
z = np.arange(10.)
dx = np.zeros(10)
dy = np.arange(10.)
dz = np.zeros(10)

ax = plt.figure().add_subplot(projection='3d')

arrow_color = plt.cm.Reds(dy/dy.max())

ax.quiver(x, y, z, dx, dy, dz, colors=arrow_color)
ax.set_ylim(0,10)
plt.show()
```

**Actual outcome**

test_arrow_head_color

**Expected outcome**

The entire arrow should have a single color.

**Matplotlib version**

  * Operating system: macOS 10.13.6
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.15
  * Jupyter version (if applicable): 5.6.0
  * Other libraries: 

matplotlib and Python were installed with Anaconda.

### PR DESCRIPTION
**Pull request by raunM**
## PR Summary
Tried to fix this issue by separating arrow head bodies and arrow heads to be used for generating gradient lines separately. This PR is part of coursework for CSCD01 at UTSC.

Closes #11759

## Bug Description
Currently when plotting arrows using the quiver method with a gradient correctly shows a gradient for arrow bodies but not for arrow heads. Within the `quiver` method inside class `Axes3D` in `mpl_toolkits/mplot3d/axes3d.py` each arrow head is actually created as two lines that are at a different angle to the body of the arrow. Originally the main body lines and the lines used to generate the arrow heads are being passed together to create a single `Line3DCollection` object:

```
lines = [*shafts, *heads]
.
.
.
linec = art3d.Line3DCollection(lines, *args[argi:], **kwargs)
```

This resulted in the arrow heads to have an inconsistent gradient for the plot. The fix was to create separate `Line3DCollection` for each collection of lines. Instead of one single `Line3DCollection` object to be plotted containing the body lines and then the arrow head lines, I now split it into a `Line3DCollection` object for the body lines, a `Line3DCollection` object for one side of the arrow heads, and a `Line3DCollection` object for the other side of the arrow
heads. 

## Example code to test
```
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

x = np.zeros(10)
y = np.zeros(10)
z = np.arange(10.)
dx = np.zeros(10)
dy = np.arange(10.)
dz = np.zeros(10)

fig = plt.figure()
ax = fig.gca(projection='3d')

arrow_color = plt.cm.Reds(dy/dy.max())

ax.quiver(x, y, z, dx, dy, dz, colors=arrow_color)
ax.set_ylim(0,10)
plt.show()
```

## Before
before

## After
arrowheads

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by raunM** [comment]
Tried to fix this issue by separating arrow head bodies and arrow heads to be used for generating gradient lines separately.

Before:
before

After:
arrowheads

**Comment by timhoffm** [comment]
Thanks for going forward with trying to solve this issue.

The problem with using three line collections is that the return value of `Axes3D.quiver()` is a single line collection. The proposed solution only returns the collection of the shafts, which breaks the API. Returning separate collections is not really better as that would break the existing API and on top it's not a good API to have three separate collections for the API.

Not really sure, what the right way to go is:
- One could replicate colors so that `[c1, c2]` would be transformed to `[c1, c1, c1, c2, c2, c2]` before passing to the line collection.
- One could change the `LineCollection` to a `PolyCollection` and draw each arrow with a single stroke. This is also an API change.
- One could simple disallow multiple colors for the color parameter in `Axes3D.quiver()`.

Maybe other devs have more ideas.

**Comment by raunM** [comment]
What about also having a single line collection of all the lines that can be used just for returning purposes. This would essentially be the same as what was being done before.

**Comment by timhoffm** [comment]
> What about also having a single line collection of all the lines that can be used just for returning purposes?

That's basically my first bullet point. Since you have `[shaft1, arrowleft1, arrowright1, shaft2, arrowleft2, arrowright2, ...]`, you need to have the first color three times, then the second color three times and so on.

Note that it will be a bit tricky to implement this correctly. Color-replication should only be done if there are multiple colors - i.e. not if e.g. `colors='green'`. But colors can have many (including list-like) formats: https://matplotlib.org/api/colors_api.html#module-matplotlib.colors. So deciding if this is a single color or multiple colors is not simple.

Note also, that the same problem will arise for other arguments, e.g. `linestyles=['--', ':']`, making a complete solution using replication even more cumbersome.

**Comment by jklymak** [comment]
This looked on the right track...

**Comment by scottshambaugh** [comment]
This PR is stale and the issue has been addressed by https://github.com/matplotlib/matplotlib/pull/27754, so closing this one.

**Pull request closed without merging**
