### PR TITLE
Change the description of Rectangle's xy parameter

### PR DESCRIPTION
**Pull request by SidharthBansal**
## PR Summary

matplotlib.patches.Rectangle's first parameter, xy, is previously only documented for data plotting functions in which xy means left and bottom coordinates. However, in imshow(), the vertical axis's direction is inverted, and xy means left and top coordinates. See #15401.

In this PR, a fix is made to explain xy as starting coordinates so as to make it suitable for both cases
Closes #15433

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by SidharthBansal** [comment]
@timhoffm @anntzer @story645 @tacaswell kindly review and suggest changes if any. I am just trying to complete some pending PRS from which contributors left. This will help me to learn about mpl :-)
Thanks

**Comment by SidharthBansal** [comment]
I am not able to add reviewers' from lefthand side topmost panel. Can anyone give me access to add reviewers if possible?
Thanks 
Sidharth

**Comment by QuLogic** [comment]
I'm not sure I agree with this change, as what constitutes the anchor point of the rectangle?

**Comment by SidharthBansal** [comment]
The leftmost bottommost point of the rectangle

**Comment by SidharthBansal** [comment]
Kindly check https://github.com/matplotlib/matplotlib/issues/15401#issuecomment-541064351

**Comment by timhoffm** [comment]
Whether *xy* is really the bottom left depends on the direction of the axis and the sign of *width* and *height*.

IMHO, it's correct to call it anchor point, but this needs more context:

> The rectangle extends from *xy* by *width* in x-direction and by *height* in y-direction.
or
> The rectangle extends from `xy[0]` to `xy[0] + width` and from `xy[1]` to `xy[1]` to height`
or similar. Please find a suitable wording yourself.

**Comment by SidharthBansal** [comment]
Done! Thanks for a detailed explanation.

**Comment by SidharthBansal** [comment]
Thanks @story645

**Comment by story645** [comment]
You need to fix the CI error before it can be merged though

**Comment by SidharthBansal** [comment]
@story645 I have rectified the flake error. Kindly merge.

**Pull request merged**
