### PR TITLE
Unpin pydocstyle

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Undo #14710.

The incompatibility has been resolved in flake8-docstring v1.3.1 (https://pypi.org/project/flake8-docstrings/).

Let's see if CI agrees.

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, I know, we need to set bash to pipefail, so it errors if any part of the pipe fails.

**Comment by timhoffm** [comment]
rebased.

**Comment by timhoffm** [comment]
Pydocstyle seems to be more picky and partly even incorrect in the reported messages.

Needs more investigation.

**Comment by timhoffm** [comment]
Superseded by #18780 .

**Pull request closed without merging**
