### PR TITLE
Merge branch v3.7.2-doc into v3.7.x

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

Mainly for the flake8 fixes.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
The GitHub diff is a bit strange; it should only be showing the flake8 fix and the Zenodo image/DOI.

**Comment by tacaswell** [comment]
Are there backports to 3.7.x that got missed?

**Comment by QuLogic** [comment]
Not that are shown in this diff. Pulling the merge commit and comparing heads does not show the extra changes that are here.

**Comment by QuLogic** [comment]
In any case, linting is fixed, so I'm going to merge this, and leave the test failures (which are `pyparsing`) to #26432.

**Pull request merged**
