### PR TITLE
remove empty constuctor

### PR DESCRIPTION
**Pull request by OceanWolf**

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @pwuertz

**Comment by pwuertz** [comment]
I guess it's my personal preference to explicitly implement subclass constructors just in case, but no objections if you prefer to have it removed.

**Comment by OceanWolf** [comment]
Looking at the other non-gui backends, none of them have their own constructor.  I guess I go for extra stuff to maintain.

Here for example it only accepts and passes *args and not **kwargs to the parent class (something I need for MEP27).  As this constructor doesn't actually do anything I thought it easier to just remove the whole thing, than add **kwargs, but I don't really mind, but we should stay consistent with the other backends

**Comment by pwuertz** [comment]
Right, its easier to maintain in case you want to add something to the base class. No objections.

**Pull request merged**
