### PR TITLE
Add `style` to api doc; fix capitalization.

### PR DESCRIPTION
**Pull request by anntzer**
All other sections use a lowercase title.  Also mention `legend_handler`
in the title for the `legend` api doc as they are in the same file.

### CODE REVIEW

**Comment by tacaswell** [comment]
Who ever merges this, please backport to `v1.5.3-doc`

**Comment by tacaswell** [comment]
@NelleV did you do the backport?

**Comment by NelleV** [comment]
Yep, I did.
Is there a way to run travis on other branches than master? That's going to be very annoying to fix on my computer, considering I can't built the doc with warnings treated as error.

**Comment by tacaswell** [comment]
backported to v1.5.3-doc as 5c548e53d99b8da762d6b38177614c8aa1cc8748

**Comment by NelleV** [comment]
Hum… sorry. Yes I did the backport, but the documentation built fails. Hence my very unclear previous message…

**Comment by tacaswell** [comment]
It is very odd that it passed on master, but not on v1.5.3-doc..... I will take a look at this (me and sphinx are getting to know each other too well).

**Comment by NelleV** [comment]
In the meantime, I'm doing another attempt at setting up my dev environment to build the sphinx documentation with the same options as on travis. I'll keep posted if I have any luck.

**Comment by tacaswell** [comment]
The docs build cleanly for me locally, I restarted travis on this branch (accidentally for the full matrix :/)

**Comment by tacaswell** [comment]
but with python 3.5 + sphinx 1.4.6 not py2.7 + sx1.3.1

**Comment by QuLogic** [comment]
Docs appear to still not be building.

**Pull request merged**
