### PR TITLE
windows dlls packaging 

### PR DESCRIPTION
**Pull request by tacaswell**
supersedes #5103

Adds code @mdboom left in comments.

### CODE REVIEW

**Comment by mdboom** [comment]
I see.  So MSVC dumps a system dll in `lib/matplotlib` somehow?  I'm a little unclear on the rationale for this.

**Comment by tacaswell** [comment]
I am not sure, I am trusting @cgohlke on this.

**Comment by cgohlke** [comment]
The rational was explained on the mailing list and at https://github.com/matplotlib/matplotlib/pull/5100.

This patch would allow me to package the required DLLs from the "Visual C++ Redistributable for Visual Studio 2015" with the matplotlib binaries for Python 3.5.

**Comment by mdboom** [comment]
Backported to v1.5.x as b2bb5abf

**Pull request merged**
