### PR TITLE
Optimise png files

### PR DESCRIPTION
**Pull request by jlec**
Using optipng [1] to losslessly optimise the png files in the repo,
an on average size reduction of 20% could be achieved. In total a
size reduction of 10MB (11%) is visible.

1)
http://optipng.sourceforge.net/

Signed-off-by: Justin Lecher <jlec@gentoo.org>

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for your effort, however I am against merging this.

It only saves space on the checked out pngs but increases the total size of the repository.

It also seems to have thrown out the alpha channel on many of the images which is something that we test against.

**Comment by jlec** [comment]
> It only saves space on the checked out pngs but increases the total size of the repository.

The repo increases but the final installation on the customers machines is smaller. And this was the initial goal.

> It also seems to have thrown out the alpha channel on many of the images which is something that we test against.

Good point, let me check that again.

**Comment by tacaswell** [comment]
If you are packaging mpl I think it is ok for you to run this optimization (modulo the alpha channel stripping) as part of your packaging or just not ship the test images.

**Comment by jlec** [comment]
Alright, let's close this then

**Pull request closed without merging**
