### PR TITLE
Typo: markeredgewith -> markeredgewidth

### PR DESCRIPTION
**Pull request by Energya**

### CODE REVIEW

**Comment by WeatherGod** [comment]
Thanks for spotting the error!

**Comment by jenshnielsen** [comment]
This should probably be backported to 2.x?

**Comment by WeatherGod** [comment]
ah, right... almost forgot

**Comment by WeatherGod** [comment]
backported to v2.x via c7d7cbb

**Comment by tacaswell** [comment]
@Energya Thank you.  Hopefully we will hear from you again :smile:

**Pull request merged**
