### PR TITLE
BUG/API : relax validation in hist

### LINKED ISSUE #3882: hist / hist2d inconsistent for plotting single data point
matplotlib version 1.4.2

hist throws an error when fed with a single data point, but hist2d doesn't.

``` python
figure()
hist2d([1], [1]) # works

figure()
hist(1)  # throws a ValueError
```

The error is: "ValueError: x has only one data point. bins or range kwarg must be given"

### PR DESCRIPTION
**Pull request by tacaswell**
Relax the validation on input data to hist.
- up-convert scalar to length 1 list
- don't error out for length 1 input data

closes #3882

### CODE REVIEW

**Comment by tacaswell** [comment]
@pelson @mdboom @efiring second guessing my original view that should not be on 1.4.x.  Thought?

**Comment by efiring** [comment]
I don't see any harm in including it in 1.4.x.  But how long is this branch going to stay alive?  Is there a compelling reason not to move on to 1.5.0?

**Comment by tacaswell** [comment]
Well, in this case I am thinking about pulling it back for 1.4.3.

Do we want to shut down 1.4.x and target 1.5.0 for scipy (modulo 2.0 due to colormap changes).

**Comment by efiring** [comment]
If things going into 1.5.0 are not too revolutionary, then I don't see much point in having a long series of 1.4 bugfix releases, so I think shutting 1.4.x makes sense.
Pulling the hist change into 1.4.3 is fine with me, regardless.  It involves significant effort compared with accepting the rc1 as the release, though, doesn't it?

**Pull request merged**
