### PR TITLE
Remove outdated, annoying warning

### PR DESCRIPTION
**Pull request by EBenkler**
## PR Summary
Remove the outdated warning related to Toolbar toolmanager (see issue #15284)
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by anntzer — CHANGES_REQUESTED** [review]
I do not think the warning should be fully removed because there are many design points which remain to be discussed (https://github.com/matplotlib/matplotlib/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22MEP%3A+MEP22%22).  However I do agree that it is currently too annoying to suppress the warning, so I'd suggest using the patch at https://github.com/matplotlib/matplotlib/issues/15284#issuecomment-687015853.

**Comment by EBenkler** [comment]
> I do not think the warning should be fully removed because there are many design points which remain to be discussed (https://github.com/matplotlib/matplotlib/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22MEP%3A+MEP22%22). However I do agree that it is currently too annoying to suppress the warning, so I'd suggest using the patch at [#15284 (comment)](https://github.com/matplotlib/matplotlib/issues/15284#issuecomment-687015853).

Thanks for your reply.
I see and have submitted a new pull request #19461 which implements the changes of your patch. Sorry, I was unsure how to do this in this same pull request. Is there anything else I can do to achieve that these changes reach an official release?

**Comment by anntzer** [comment]
> Sorry, I was unsure how to do this in this same pull request.

You can force-push over the original PR, but if you're not familiar with that a new PR is fine (within reason, don't open ten versions of a same PR).

> Is there anything else I can do to achieve that these changes reach an official release?

The PR needs to be merged, but that means tests needs to pass first, which is not the case currently.

**Comment by jklymak** [comment]
So lets close this before we forget.  But note that doesn't remove the branch etc, so feel free to reopen if needed...

**Pull request closed without merging**
