### PR TITLE
Whitespace/braces/#defines cleanup to macosx.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

This should not change any code logic.

I intentionally did not touch the parts currently worked on by the key-modifier and subplot_tool PRs.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by greglucas — APPROVED** [review]
I agree, this does look nicer.
This guide https://google.github.io/styleguide/objcguide.html also seems to imply that you could move a bunch of the start method braces up onto the method definition line too if you wanted. Although I'm guessing your linter didn't suggest that ;)

**Comment by anntzer** [comment]
I personally like function braces on their own lines (https://www.kernel.org/doc/html/latest/process/coding-style.html#placing-braces-and-spaces ("Heretic people all over the world have claimed that this inconsistency is … well … inconsistent, but all right-thinking people know that (a) K&R are right and (b) K&R are right. Besides, functions are special anyway (you can’t nest them in C)." -- mostly the last part is relevant :-))  It's also consistent with PEP7.

**Comment by anntzer** [comment]
Edit: additionally commented out and gave a more meaningful name to the `unused` arg to choose_save_file and set_cursor.

**Comment by tacaswell** [comment]
https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=22418&view=logs&j=0de6cdcb-72d7-5519-795d-247cd4b3fb83&t=a176e118-8b4f-5c79-d96f-bc5bbdea43ba&l=662

The OSX failures seem to be caused by this PR.

**Review by tacaswell — APPROVED** [review]
I approve modulo fixing the build issues.  @anntzer can self merge when CI is green.

**Comment by anntzer** [comment]
oops, turns out there's some versions where you can't unset arg names, so I undid https://github.com/matplotlib/matplotlib/pull/21690#issuecomment-975305951.

**Comment by anntzer** [comment]
selfmerging per the above.

**Pull request merged**
