### PR TITLE
cursor with hovering text labels

### PR DESCRIPTION
**Pull request by K2LEEKorea**
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [x] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
Hi, thanks for the contribution!  However, I'm not sure we would accept this in the main library.  You may also want to see mpl_cursors.  If this has unique functionality, it can perhaps best be packaged as a third party package, which we would be very happy to point to at the third_party webpage.  https://github.com/matplotlib/mpl-third-party

**Comment by K2LEEKorea** [comment]
> Hi, thanks for the contribution! However, I'm not sure we would accept this in the main library. You may also want to see mpl_cursors. If this has unique functionality, it can perhaps best be packaged as a third party package, which we would be very happy to point to at the third_party webpage. https://github.com/matplotlib/mpl-third-party

**Comment by K2LEEKorea** [comment]
> > Hi, thanks for the contribution! However, I'm not sure we would accept this in the main library. You may also want to see mpl_cursors. If this has unique functionality, it can perhaps best be packaged as a third party package, which we would be very happy to point to at the third_party webpage. https://github.com/matplotlib/mpl-third-party

Hi, whether these code could be accepted or not is not the point here. I have used mpl_cursors but it looks not pretty.
So I implement plotly style [https://blog.plotly.com/post/97004982472/5-plots-on-gender-you-have-to-see] hovering cursor labels by combining a few matplotlib examples. So these are completely different.

**Comment by K2LEEKorea** [comment]
These codes are too simple and not perfect, yet. So my intention is just to put these into examples category.
Most graphic packages like plotly, matlab, bokeh etc.  has this cross-cursor label functionality but matplotlib.
So I just hope to share these simple tricks.

**Comment by jklymak** [comment]
Its still not clear what you want us to do with this.  Obviously it can't live at the top level of our code base.  DO you want this to be an example?  It is _very_ extensive for an example.  Please see https://matplotlib.org/stable/devel/contributing.html  However, in my opinion this should still just be an external package.

**Comment by K2LEEKorea** [comment]
Hi, firstly forgive me for my ignorance of "top level of our code base".
I am new to this matplotlib posting. It seemed I wrongfully uploaded to the TOP level but could not remove these neither. My original intension is just sharing codes. So example section (folder) would be more proper place. And these examples seem too long. So If possible, I would like to delete two example files and keep just "curosrxlib.py" that I could further strip down to less than 200 lines.

**Comment by jklymak** [comment]
If your intention is to just share the code, then https://discourse.matplotlib.org is a great place to do it.  If you would like to create a package and host it on GitHub, you can get a cookie cutter project maker at https://github.com/matplotlib/matplotlib-extension-cookiecutter and then you could also link your project at mpl-third-party: https://github.com/matplotlib/mpl-third-party  

However, the main code base is used by thousands of users, so unless you have a small self contained example for our examples directory, I don't think it is appropriate here.

**Comment by K2LEEKorea** [comment]
Good to know. Thank you

**Pull request closed without merging**
