### PR TITLE
Doc event loop requirements for Figure.show

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Trying to better document `Figure.show()` and how it's different from `plt.show()`.

Hopefully this is reasonably correct and understandable so that #13586 or #13101 do not happen anymore. Improvements welcome as this is hard to describe (see discussion in #13101).

### CODE REVIEW

**Comment by timhoffm** [comment]
Milestoning 3.1 because it would be nice if this would make it into the docs soon. But feel free to re-milestone.

**Comment by anntzer** [comment]
I actually think we should just deprecate Figure.show() in favor of e.g. plt.show(figures=[fig1, fig2]) (if you really want to raise just a subset of figures).

Figure.show only works for pyplot-managed figures, so it makes sense to have that functionality in pyplot, plus having it it plt.show() will properly spin up the event loop if needed.

If you are managing your own GUI then *hopefully* you are not using pyplot (...), in which case fig.show() is not useful.

**Comment by timhoffm** [comment]
Given https://github.com/matplotlib/matplotlib/issues/13101#issuecomment-453282797, can we really deprecate `Figure.show()`?

Not an expert on this, but there seem to be two differences betweeen the two `show()` functions:
1. Rasing all vs. only one figure
2. Managing an event loop.

`plt.show(figures=[fig1, fig2])` only addresses 1.

**Comment by anntzer** [comment]
But `plt.show(figures=[fig1, fig2])` would also reuse the code that already exists in `plt.show()` to manage the event loop.

**Comment by tacaswell** [comment]
I think the improvements to `plt.show` can be done separately.

Currently `plt.show` calls `show` from the backend bases template which calls `manager.canvas.figure.show()` which then calls `manager.show()` so there is clearly some room for simplifying that call chain....  We will never be able to deprecated `manager.show()` as that is typically inherited from the underlying GUI widget.

**Comment by anntzer** [comment]
I'm not talking about deprecating manager.show() (which is indeed needed as a backend customization point), just figure.show().

**Comment by dstansby** [comment]
Thanks, I think this will be helpful 👍

**Pull request merged**
