### PR TITLE
DOC: Sort gallery subsections by filename

### PR DESCRIPTION
**Pull request by ImportanceOfBeingErnest**
## PR Summary

Up to now the subsections of the gallery were sorted by the length of the code section(s) in the respective example. This let the gallery look a bit chaotic.  
Instead it might be useful to **sort the examples within each subsection by the filename of the example**. This would still not give perfect thematic ordering, but since in many cases the filenames start with the name of the function they focus on, some kind of basic ordering would be achieved.

Note that an alternative would be to order by example headline/title. This seems not too useful because we can have the examples named like "A bar plot...", "Bar plot...", "Demo for Bar..", "Subplots with bars" etc.

This PR would introduce ordering by filename, since it seems to be the best one can achieve automatically and without renaming half of the examples. 

## PR Checklist

- [x] Code is PEP 8 compliant
- [x] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by QuLogic** [comment]
This was added in sphinx-gallery 0.1.13, so you need to bump the minimum version in the requirements.

**Comment by ImportanceOfBeingErnest** [comment]
Good point. I added this to the `doc-requirements.txt`.

**Comment by jklymak** [comment]
I suppose this is beter.  It'd still be nice if we could order them ourselves somehow...

https://124-100939689-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/index.html

**Comment by ImportanceOfBeingErnest** [comment]
I mean we *could* order them by using consistent filenames. Or by using a clear structure for the titles (and then use another sphinx-gallery sorter). We could also writer our own sorter, but on what would it need to sort?

**Comment by jklymak** [comment]
I mean we could just have an index.rst in the directory...

**Comment by jklymak** [comment]
its been discussed :wink:

**Comment by jklymak** [comment]
We should just number the file names  of the tutorials.  I assume it’ll sort on numbers.  Suggest %03doldname.py.  just in case someone gets ambitious

**Comment by ImportanceOfBeingErnest** [comment]
I agree with @timhoffm here. We do not want to rename any files and we do not want to break any links. But we do want to have control over at least some of the subsection orders, e.g. in the tutorials. 

I think there is a solution to this. I will prepare a new PR later tonight or tomorrow.

**Comment by jklymak** [comment]
Good points!  Would you like this merged or did you want to wait on your new PR?

**Comment by anntzer** [comment]
See https://github.com/sphinx-gallery/sphinx-gallery/issues/275#issuecomment-318934002 for my thoughts on the topic...

**Comment by ImportanceOfBeingErnest** [comment]
I posted an alternative to this PR in #11257. This would allow custom ordering where necessary.

The "thoughts" by @anntzer to use rst toctrees does not seem feasable (currently); they would need to come from the sphinx-gallery side.

The idea by @jklymak to number the examples themselves would be doable, but has the drawback to clutter the titles with numbers and makes it hard to change a once determined order in case a new example should be positionned between two existing ones. 

I think the alternative in #11257 might be a good compromise for now.

**Comment by jklymak** [comment]
Closing in lieu of #11257.  Feel free to reopen if that doesn't work out

**Pull request closed without merging**
