### PR TITLE
turn on minor ticks by default

### PR DESCRIPTION
**Pull request by beckermr**

### CODE REVIEW

**Comment by beckermr** [comment]
I didn't get the `matplotlibrc.template` file. Got it now.

**Comment by efiring** [comment]
I do not favor this as a default.  It seems to me that in most plotting situations with linear axes, minor ticks are clutter.  The tendency in plot design is to minimize clutter.  (With log axes, the minor ticks provide a visual reminder that one is looking at a log scale, and they are also very helpful when interpreting intervals smaller than a decade.  That's why minor ticks are included by default with log axes.)

**Comment by beckermr** [comment]
Minor ticks increase the utility of plots for technical publications immensely. Plenty of plotting packages make 'pretty' plots already. Whether or not they are clutter is a matter of taste.

**Comment by efiring** [comment]
As you say, a matter of taste--and a question of which technical publications, what sort of plots, and how they are going to be used.  That's why we provide rcparams, kwargs, etc. The question here is whether changing the *default* visibility of minor ticks would constitute an improvement for matplotlib's broad user base, on average.  I'm pretty sure it would not.

**Comment by beckermr** [comment]
Fair enough. I'm pretty sure it would. :)

**Comment by Mrngilles** [comment]
I agree with @efiring on this point. It is true that it can improve plots utility in *some* cases, in some domains, but it mainly clutters the graph, and reduce its readability (for example, in a scientific publication where the main point of a graph is to illustrate). Also, in scientific journals, plots are usually pretty small, and if you add more than there already is (without the minor ticks), you cannot see a thing anymore. The only utility I see to add the minor ticks on a plot is if you want to do some graphical analysis on printed paper, which is IMO, not the most common use.

**Comment by esheldon** [comment]
Every plot I have ever included in a scientific publication contains minor ticks.  This is overwhelmingly true for plots used in astrophysics and physics journals.  Lack of minor ticks makes it difficult to get quantitative information from the plot.  In hard sciences plots are not usually just illustrative but are expected to provide quantitative information.

**Comment by Mrngilles** [comment]
In any case, I think the best approach would be to add this as an rcParameter so that you can choose to activate it by default on your plots. Thoughs?

**Comment by WeatherGod** [comment]
At the very least, we would need that for v1.5, so that it can be a style
option for 2.0.

**Comment by Mrngilles** [comment]
Well, it sees it was already in the rc... Did not look very well...

**Comment by mdboom** [comment]
I think we are going to leave this one as-is for 2.0, as the minor ticks do introduce come clutter, and it's somewhat data dependent whether they are helpful or not.

We will, however, add documentation of them to matplotlibrc.template, which was merely an oversight.

**Comment by mdboom** [comment]
I'm going to add this to my style-change branch.  It seems that @beckermr 's fork has been deleted, so I can't cherry-pick it anymore.

**Pull request closed without merging**
