### PR TITLE
[MRG+1] [DOC] Clean up equal-aspect example

### PR DESCRIPTION
**Pull request by dstansby**
Part of #7956

### CODE REVIEW

**Comment by tacaswell** [comment]
```
/home/travis/build/matplotlib/matplotlib/doc/faq/howto_faq.rst:356: WARNING: undefined label: pylab_examples-equal_aspect_ratio (if the link has no caption the label must precede a section header)
```

Moving the example broke an internal link.

**Comment by NelleV** [comment]
Apart from the broken link, it looks good to me!

**Comment by NelleV** [comment]
Actually, while you are at it, do you mind adding the prefix plot to this?

**Comment by dstansby** [comment]
> Actually, while you are at it, do you mind adding the prefix plot to the filename?

I'm confused as to what that means...

**Comment by NelleV** [comment]
Renaming the files as plot_something.py

**Comment by dstansby** [comment]
👍 rebased and squashed

**Comment by QuLogic** [comment]
> @tacaswell tacaswell added this to the 2.0.1 (next bug fix release) milestone 7 days ago

Do you really want this in 2.0.1? While many doc changes are generally fine, I think anything that moves an example is not a good idea to backport.

**Pull request merged**
