### PR TITLE
Axes.hist: use bottom for minimum if log and histtype='step...'

### LINKED ISSUE #4606: Axes.hist with log=True, histtype='step...' ignores bottom kwarg
The `Axes.hist` method doesn't handle the `bottom` kwarg properly when given `log=True` and `histtype='step'` or `histtype='stepfilled'`. As the example below shows, the method sets a `minimum` value to prevent issues with zeros on a log scale, but that supercedes a non-zero `bottom` kwarg:

```python
import numpy
from matplotlib import pyplot
fig = pyplot.figure()
ax = fig.gca()
ax.hist(numpy.random.random(1000), bins=100, log=True, bottom=1e-2, histtype='stepfilled')
ax.set_ylim(1e-2, 1e3)
ax.set_title('Bottom should be 1e-2, but instead is 1/base')
```

mpl-hist-bottom

I can correct the issue with the following edit:

```diff
diff --git a/lib/matplotlib/axes/_axes.py b/lib/matplotlib/axes/_axes.py
index 4d10e86..2392a6d 100644
--- a/lib/matplotlib/axes/_axes.py
+++ b/lib/matplotlib/axes/_axes.py
@@ -5779,7 +5779,9 @@ class Axes(_AxesBase):
                     logbase = self.yaxis._scale.base
 
                 # Setting a minimum of 0 results in problems for log plots
-                if normed or weights is not None:
+                if np.min(bottom) > 0:
+                    minimum = np.min(bottom)
+                elif normed or weights is not None:
                     # For normed data, set to log base * minimum data value
                     # (gives 1 full tick-label unit for the lowest filled bin)
                     ndata = np.array(n)
```

which uses the `bottom` value to set the `minimum` if it's nonzero. If this is confirmed as a bug, I can open a PR.

### PR DESCRIPTION
**Pull request by duncanmmacleod**
This PR fixes #4606, whereby a histogram with `log=True` and `histtype=step...` would override `bottom` to prevent zeros on a log scale.

With the included patch, the same code (or at least very similar) as given in the issue produces the following:

```python
import numpy
from matplotlib import pyplot
fig = pyplot.figure()
ax = fig.gca()
ax.hist(numpy.random.random(1000), bins=100, log=True, bottom=1e-2, histtype='stepfilled', label='Bottom = 1e-2')
ax.hist(numpy.random.random(1000), bins=100, log=True, histtype='stepfilled', label='No bottom', alpha=0.6, facecolor='red')
ax.set_ylim(1e-2, 1e3)
ax.legend()
```

mpl-hist-bottom

### CODE REVIEW

**Comment by jenshnielsen** [comment]
The fix looks correct to me even if the remaining code is more complicated than I would like. 

Could you add a couple of tests for this? I would add a test where bottom is larger than 1/base and one where it is smaller.

http://matplotlib.org/devel/testing.html#writing-an-image-comparison-test describes how to do image comparison tests. We probably only need a png test.

**Comment by duncanmmacleod** [comment]
@jenshnielsen: I have drafted the following test, but wanted to run it by you before committing a new image to the repo:

```python
@image_comparison(baseline_images=['hist_step_log_bottom'],
                  remove_text=True, extensions=['png'])
def test_hist_step_log_bottom():
    # check that bottom doesn't get overwritten by the 'minimum' on a
    # log scale histogram
    np.random.seed(0)
    data = np.random.standard_normal(2000)
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.hist(data, log=True, histtype='stepfilled', alpha=0.5)
    ax.hist(data, log=True, histtype='stepfilled', bottom=1e-2, alpha=0.5)
    ax.hist(data, log=True, histtype='stepfilled', bottom=0.5, alpha=0.5)
    ax.set_ylim(9e-3, 1e3)
```
which produces (blue: no `bottom`, green: `bottom < 1/base`, red: `bottom > 1/base`):
hist_step_log_bottom
The test runs and passes in place on my system, at least.

**Comment by jenshnielsen** [comment]
Thanks that looks good to me. 

Perhaps is is worth setting the colours explicitly for the 3 sections to make it easier to compare the code to the image?

Adding a reference to the this pr i.e. #4608 to the comment would be useful too.

**Comment by WeatherGod** [comment]
Does the gap at the bottom make sense?

**Comment by duncanmmacleod** [comment]
@WeatherGod: which gap? I have manually set the lower ybound to `9e-3` to highlight the `bottom=1e-2` call, if that's what you mean.

**Comment by duncanmmacleod** [comment]
@jenshnielsen: I can set the colours explicitly, my assumption was that the image is only every analysed by the test engine, and not by real humans. Anyways, simple, done.

**Comment by WeatherGod** [comment]
I was seeing the gap between the green bar and the x-axis, and was
expecting to see blue for it not having a bottom, before realizing that
this is the stepfilled histogram. So, I might be getting confused as to
what the expected behavior is there (I don't use stepfilled).

**Comment by duncanmmacleod** [comment]
On a `log=True`, `histtype=step{filled}` histogram the `bottom` is automatically set to `1/base` (if `normed=False, weights=None`), or `np.min(x[nonzero])/base` otherwise. This PR fixes the bug whereby that default would over-ride the `bottom` specified by a user, even if non-zero and positive.

Perhaps the `bottom` for a log-scale hist might be best defaulted to some small positive number (`1e-100`) so long as that doesn't automatically set the orientation axis lower bound as well (which is the current behaviour). I'll leave that for another issue/PR.

**Comment by jenshnielsen** [comment]
@duncanmmacleod Yes it's not at all critical. It just makes it a bit easier if the test breaks to understand what the intention of the test is

**Comment by jenshnielsen** [comment]
It looks like there is another bug with the snapping of the top of the bars not being exactly identical see the last bar.

**Comment by jenshnielsen** [comment]
Nevermind that is just bottom working as expected offsetting the histogram

**Comment by duncanmmacleod** [comment]
I hadn't appreciated that setting `bottom` would actually move the lower-end of the bar, i.e. scale the bars to have the same height with a different starting point, but it looks like I've stumbled across a bug and a fix in the mean time.

I was actually just wanting to make sure that the `minimum` can be set to something off the bottom of the chart, especially when using `weights`. Anyways, if the tests are good, I will commit and wait for review.

**Comment by jenshnielsen** [comment]
Neither had I. I think we should clarify the docstring but that is for another time. 

Your test is good so please go ahead and commit it :+1: 

Perhaps it is worth adding a test where bottom is an array too. Something like the following should work: 

```python
np.random.seed(0)
data = (np.random.standard_normal(2000))
bottom = np.arange(1,11)
fig = plt.figure()
ax = fig.add_subplot(111)
hist1 = ax.hist(data, log=True, histtype='stepfilled', bottom=bottom, alpha=0.5, color='green')
hist2 = ax.hist(data, log=True, histtype='stepfilled', alpha=0.5, color='blue')
ax.set_ylim(9e-3, 1e3)
plt.show()
```

**Comment by jenshnielsen** [comment]
Thanks

**Pull request merged**
