### PR TITLE
Explicitly set foreground color to black in svg icons

### PR DESCRIPTION
**Pull request by jmoraleda**
Currently the monochromatic svg icons do not explicitly specify foreground color, so they appear black, which is the svg default. This PR explicitly sets the foreground color of the monochromatic icons to black.

The rationale for this change is that explicitly setting the foreground color, enables changing the color through string replacement. In particular this permits adding dark-theme support in backends that use svg icons by doing a string replacement `fill:black;` -> `fill:white;`.

### CODE REVIEW

**Comment by anntzer** [comment]
Ideally this change would have been made in a way that regenerating the icons with make_icons.py maintains the explicit 'style="fill:black"', but I see that backend_svg.py has a cutout for black text and explicitly saves some output by not outputting the color in that case, so I guess it's not really worth the trouble.

**Comment by jmoraleda** [comment]
I see the filter for black text in `backend_svg.py`:
```
        if color != '#000000':
            style['fill'] = color
```

I assume we don't want to change that.


I was not familiar with `make_icons.py`. If we want to preserve its functionality intact, then we could hack the function `make_icons` in the script to make a string replacement to add ` style="fill:black;"` to the right files after they are saved in `../lib/matplotlib/mpl-data/images`. We could make this change as part of this PR.

**Comment by jmoraleda** [comment]
I modified the script. It feels a little hacky since it performs a purely syntactic search and replace with no svg model underlying it, but I think it does the job. 

I tested it in my system where the svg backend produces very different icon code from what is currently committed, although the icons appear visually indistinguishable. So it should definitely work on systems that produce the svg code that is currently committed.

**Review by oscargus — APPROVED** [review]
Subject to a confirmation/comment about the GTK aspect.

**Comment by anntzer** [comment]
In case this turns out to be a problem for gtk, I guess the "base" files could *not* include the explicit foreground color but just have a xml marker-comment as to where the wx backend should insert the foreground color (`"\> <!-- insert color in previous tag -->` -> `" ...\>`).

**Comment by QuLogic** [comment]
From my testing, it appears that this does not break GTK3 dark mode. GTK4 dark mode is already broken because it uses some other method that hasn't been implemented by us.

**Review by anntzer — APPROVED** [review]

**Comment by anntzer** [comment]
@jmoraleda Can you squash?  (Not compulsory.)

**Comment by anntzer** [comment]
Thanks for the PR!

**Pull request merged**
