### PR TITLE
MAINT removing unused files and symlinks

### PR DESCRIPTION
**Pull request by NelleV**
I am pretty user these symlink/files are unused and uninstalled so here is a PR to remove them.

- lib/mpl_examples
- lib/pylab.py

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm pretty sure `pylab.py ` _is_ installed and its existence is the cause for several users being confused due to the other "pylab" package on PyPI, and several (old?) tutorials using it. I don't think it's going away without a _long_ deprecation period.

**Comment by NelleV** [comment]
That's what I thought as well, but I don't see how it could be installed considering it dose not appear in any of our build system.

**Comment by QuLogic** [comment]
It's [here](https://github.com/matplotlib/matplotlib/blob/master/setupext.py#L711).

**Comment by NelleV** [comment]
eh…

**Comment by QuLogic** [comment]
I don't see `mpl_examples` being installed though; I wonder if it was just there because documentation links use it and someone thought it might be necessary?

**Pull request closed without merging**
