### PR TITLE
Update round fix

### PR DESCRIPTION
**Pull request by hildogjr**
## PR Summary
On webpage `int(pct/100.*np.sum(allvals))` cause a wrong round and absolute number representation.
Here `int(round(foo))` make a not needed `int(foo)` conversion.
Remove the `int(foo)`.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
I can understand if it's not needed, but what do you mean by _wrong_? Can you give an example?

**Comment by hildogjr** [comment]
Yes. Now the example on the official page use `int(pct/100.*np.sum(allvals))` at the `perceptual_absolute(foo)`:

```python
scores = [116, 133, 18, 19, 4, 2]
def perceptual_absolute(pct, allvals):
        absolute = int(pct/100.*np.sum(allvals))
        return '{:.2f}%\n({:d})'.format(pct, absolute)
plt.pie(scores.values(), explode=explode,
                            autopct=lambda pct: perceptual_absolute(pct, list(scores.values())),
                            pctdistance=1.1, labeldistance=1.2, startangle=0)
```

`int(pct/100.*np.sum(allvals))` get 132 but the correct is 133, given by `round(pct/100.*np.sum(allvals))`.


The actual code here in master (maybe not deployed yet) use `int(round(pct/100.*np.sum(allvals)))` but `round(foo)` already returns a `int` type. The call `int(foo)` is not used at the code.

**Comment by jklymak** [comment]
For consistency sake with the rest of our examples, it should probably just be `np.round` and let the formatter take care of making it an integer.

**Comment by hildogjr** [comment]
In this case may be necessary to do `int(np.round(foo))` because `np.round(foo)` returns `numpy.float` type.

**Comment by ianhi** [comment]
>  because np.round(foo) returns numpy.float type.

This is actually a bug in numpy (https://github.com/numpy/numpy/issues/15297) that is fixed in more recent versions. See https://github.com/numpy/numpy/pull/15840

So if you do `pip install --upgrade numpy` that behavior should go away.

**Comment by jklymak** [comment]
Yeah, fair enough - I didn't realize that `'{:d}'.format(np.round(3.4))` fails with `ValueError: Unknown format code 'd' for object of type 'float'`.  `print('%d'%np.round(3.4))` works just fine.

**Comment by hildogjr** [comment]
Interesting point:

```
print('%d'% 56)
print('%d'% 56.0)
print('%d'% 56.9)
```

All print "56".

**Review by jklymak — APPROVED** [review]

**Pull request merged**
