### PR TITLE
Adding a dynamically resize of mathtext symbol table

### LINKED ISSUE #26143: [Doc]: dynamically resize the mathtext symbol tables
### Documentation Link

https://matplotlib.org/devdocs/users/explain/text/mathtext.html#symbols

### Problem

In the math text example, the number of columns for displaying each set of symbols is specified as part of defining each set of symbols:
https://github.com/matplotlib/matplotlib/blob/f329eb8fda1dc38c468caecf0d7f7d835a753f10/doc/sphinxext/math_symbol_table.py#L6-L12

This makes the tables somewhat brittle with respect to a reordering or a resizing.

### Suggested improvement

modify the [run function](https://github.com/matplotlib/matplotlib/blob/f329eb8fda1dc38c468caecf0d7f7d835a753f10/doc/sphinxext/math_symbol_table.py#L97) of the directive to generate a more dynamic table, maybe a [sphinx-design grid](https://sphinx-design.readthedocs.io/en/latest/grids.html)

tagging this good first issue because the work is contained to the `math_symbol_table.py` file and the way to verify that the changes make sense is to build the docs and ensure that the resulting tables in the mathtext tutorials look similar to the old ones but **the number of columns change to fit better when the browser window is resized**. This issue requires working knowledge of sphinx.

### PR DESCRIPTION
**Pull request by NikosNikolaidis02**
## PR summary
I tried to find a more dynamic way to calculate the number of columns in order to have rows as more completed as possible. I've added the function `columns_calculation` which illustrates the function I described.

## PR checklist

- [ ] "closes #26143 " is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by oscargus** [comment]
Thank you! However, I do not think that having complete columns is really the main optimization objective that we want.

Basically, the main problem is the length of some of the LaTeX commands. So if anything, I'd try to come up with some good heuristic to determine a suitable number of columns based on that. 

(However, it should be noted that it is almost impossible to come up with a perfect one as the columns will not have the same width anyway, so if all other columns only contains "short" commands there can be more columns compared to if all contains "long" commands.)

Also, it seems like you have some unrelated changes in `image.py` committed?

**Comment by NikosNikolaidis02** [comment]
> Thank you! However, I do not think that having complete columns is really the main optimization objective that we want.
> 
> Basically, the main problem is the length of some of the LaTeX commands. So if anything, I'd try to come up with some good heuristic to determine a suitable number of columns based on that.
> 
> (However, it should be noted that it is almost impossible to come up with a perfect one as the columns will not have the same width anyway, so if all other columns only contains "short" commands there can be more columns compared to if all contains "long" commands.)
> 
> Also, it seems like you have some unrelated changes in `image.py` committed?

Yes, i don't want this change to happen it's from another change

**Comment by NikosNikolaidis02** [comment]
We can also optimize this by find the perfect combination for the lenght of the string

**Comment by NikosNikolaidis02** [comment]
@oscargus Can you check it?

**Comment by oscargus** [comment]
As I said, I do not believe in this approach, but I'd let e.g. @story645 chip in if it is an OK solution for the issue. 

Also, it seems like there has been something happening to your branch which must be fixed. Not really clear what and how though...

Probably a case of either starting a new branch and copy-and-paste the relevant parts or use `git rebase` in a cautious way.

**Comment by NikosNikolaidis02** [comment]
#26191 I've created a new branch to resolve the previous problems on this PR

**Pull request closed without merging**
