### PR TITLE
Add polar_radar.py to examples/pie_and_polar_charts

### PR DESCRIPTION
**Pull request by tasbihaasim**
## PR Summary
Add Radar Plot to examples of Polar/Pie plot charts

The following example shows a way to plot Radar chart in matplotlib.
Such charts are a way to visualize multivariate data. 
They are used to plot one or more groups of values over multiple common variables.

Here, school subjects are common variables.
Group of values are the scores obtained in those
subjects by two students.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
... somehow you've checking a bunch of other files to your git repository.  In this case, its probably better to save the file and then `git -reset --hard upstream/master` on your `examples` branch and then re-add the file.

**Comment by QuLogic** [comment]
Other than the boundary shape, I'm not sure what the difference here is to [examples/specialty_plots/radar_chart.py](https://matplotlib.org/gallery/specialty_plots/radar_chart.html). Though perhaps one might also say that that example is a bit complicated.

**Comment by timhoffm** [comment]
@tasbihaasim are you still interested in working on this?

**Comment by QuLogic** [comment]
I'm going to close due to no response, and I think this example is a duplicate of an existing one.

**Pull request closed without merging**
