### PR TITLE
Added PDF version of navigation icons

### PR DESCRIPTION
**Pull request by astrofrog**
This adds PDF versions of the navigation icons, as requested by @mdehoon in #4978, since it will allow us to use HiDPI icons in the MacOS X backend (and maybe others)

Note: I also created a new icon for the ``subplots`` icon since the SVG was missing for the original icon. I tried to make it look similar to before:

screen shot 2015-09-10 at 13 47 43

### CODE REVIEW

**Comment by astrofrog** [comment]
I'm confused about the Python 3.5 failure - is this related to this PR?

**Comment by jenshnielsen** [comment]
It's most likely one of our random transient failures. I have restarted that job

**Comment by astrofrog** [comment]
@jenshnielsen - thanks!

**Comment by mdehoon** [comment]
I can confirm that these PDF files work with the MacOSX backend.

Low resolution:
screengrab lowres

High resolution:
screengrab highres

**Comment by WeatherGod** [comment]
yay!  I also like the redone icon for the subplot editor. Much neater than
before!

**Comment by tacaswell** [comment]
as a side note, these pdfs are smaller than most of our source files.

**Comment by tacaswell** [comment]
@astrofrog Thanks!  I also really like the new sub-plot icon.

**Comment by astrofrog** [comment]
@tacaswell - thanks for merging!

@mdehoon - will you open a pull request with the changes needed to switch the MacOS X backend to using these?

**Comment by mdehoon** [comment]
@tacaswell  OK.

**Pull request merged**
