### PR TITLE
TST: update and enable 'default' style tests

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
@pwuertz Can you do the same for the pgf tests?  I am having issues getting pgf to run on my machine.

**Comment by pwuertz** [comment]
I'm not sure I'm up to speed with the current development. What do you need? Check and recreate the reference images for the tests in the master and/or v2.x branch?

**Comment by jenshnielsen** [comment]
@pwuertz I did the last updates and am happy to do these to if it makes it any easier. Basically we just need to rerun the tests locally with the pgf dependencies installed and copy the new results to the baseline directory and remove the knowfailure on the pgf tests

**Comment by pwuertz** [comment]
Recreated baseline images with matplotlib master and removed knownfailure.

Commit is here: https://github.com/pwuertz/matplotlib/commit/36394382e9caaa0320ab1d5c30e401f4e1f1f93c

Do you want to integrate it into your own test update PR or do you want me to create 2 PRs for master and v2.x?

**Comment by tacaswell** [comment]
@QuLogic if you have band width please take this PR over

**Comment by QuLogic** [comment]
I'm trying this out, but more things failed on Travis than locally.

**Comment by QuLogic** [comment]
Or maybe it's because I didn't have `xelatex` installed, but unfortunately, now _more_ things are failing locally than on Travis.

**Comment by QuLogic** [comment]
`matplotlib.tests.test_axes.test_boxplot_rc_parameters` passes by itself, but fails as a group. There's might be a `@cleanup` decorator missing somewhere.

**Comment by WeatherGod** [comment]
try clearing out your caches. that fixed a lot of issues for me, once.

**Comment by tacaswell** [comment]
if you change gs version and are not on master you have to clear `.cache/matplotlib/test_*`

**Comment by QuLogic** [comment]
I've rebased to latest `v2.x` and updated several test images due to various other changes occurring in the meantime.

There is still the question of `matplotlib.tests.test_axes.test_boxplot_rc_parameters` which works fine if run by itself, or as the first test, but fails if it's not. There don't appear to be any `@cleanup` missing, but there's clearly some setting that's falling through the cracks somewhere.

**Comment by QuLogic** [comment]
And now we're :white_check_mark:.

**Comment by QuLogic** [comment]
Now rebased to remove any redundant image changes.

**Comment by afvincent** [comment]
@QuLogic Could your problem with `matplotlib.tests.test_axes.test_boxplot_rc_parameters` be related to `_rc_test_bxp_helper` not being private? I remember having had a similar issue of setting leaking through tests in #6035 that was due to such a reason: see @jenshnielsen last comment in #6035 .

**Comment by tacaswell** [comment]
@QuLogic Is this ready to go or does in need to be squashed?

**Comment by QuLogic** [comment]
@afvincent I am not sure to what you are referring in that issue, but I think the problem is fixed by 26774ca.

@tacaswell It is good to go from my side; I removed the redundant image changes.

**Comment by afvincent** [comment]
@QuLogic *If 26774ca made everything OK, then everything is fine :).* For the record, I was referring to the issue of "`matplotlib.tests.test_axes.test_boxplot_rc_parameters` which works fine if run by itself, or as the first test, but fails if it's not." I had a similar issue with #6035 (a test that was OK if run alone, but not in the test suite) and @jenshnielsen  found that it was related to the custom setup function I was using, which was not a test (i.e. not named `test_*`), was not private either. It was like the function was leaking some context to the ones after it. @jenshnielsen made it private and the issue just vanished.

(By the way, is it normal that `test_boxplot_rc_parameters` has a tolerance of 1?)

**Pull request merged**
