### PR TITLE
Addition of numticks=N in LogLocator

### LINKED ISSUE #19856: BUG: Contours with LogNorm
### Bug report

**Bug summary**
Contour plots don't interact nicely with `matplotlib.colors.LogNorm`.
Likely related to #19748

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib.colors import LogNorm
import numpy as np

# BUG: setting levels as a scalar has no effect and no warning or error is printed
fig, ax = plt.subplots()
im = ax.contourf(x, y, data, norm=LogNorm(), levels=4)
fig.colorbar(im, ax=ax)
plt.savefig("/tmp/mpl_logcontours_bug1.png")
```
mpl_logcontours_bug1

```python
# kinda buggy too: setting levels as an array does have some of the desired effects
# but ticks and ticklabels are incorrect
fig, ax = plt.subplots()
levels = np.logspace(np.log10(data.min()), np.log10(data.max()), 5)
im = ax.contourf(x, y, data, norm=LogNorm(), levels=levels)
fig.colorbar(im, ax=ax)
plt.savefig("/tmp/mpl_logcontours_bug2.png")
```

mpl_logcontours_bug2

**Expected outcome**

The experience should be comparable with what happens when the norm isn't specified: the `levels` kwarg should be usable in both cases.
I note that the output from the first snippet is consistent with the case where neither `levels` or `norm` are specified, and is correct in that case, so it's definetely not _completely broken_ and I hope the fix is somewhat straightforward.

I'm happy to take a look at the source and see if I can come up with an easy patch, but I'm not sure when I'll have time to dive in there myself. Any piece advice from maintainers or contributors is more than welcome !

**Matplotlib version**

  * Operating system: MacOS
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.9.1
  * Jupyter version (if applicable): NA
  * Other libraries: 

I installed matplotlib using pip.

### PR DESCRIPTION
**Pull request by manushree635**
# Addition of numticks=N in LogLocator in def _autolev(self, N):
## PR Summary

 "closes #19856"
Contour plots don't interact nicely with matplotlib.colors.LogNorm. Level=N doesn't work with LogNorm.
Added numticks=N in LogLocator in def _autolev(self, N):
## PR Checklist

- [ N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ N/A] New features are documented, with examples if plot related.
- [ N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
@manushree635 Thanks a lot for the PR.  Can you tidy up a bit and add a descriptive title and link the issue in the description instead of the title?  If you say "closes #19865" it will automatically close.  

Without looking at the original issue, I suspect you will want to add a test so that this doesn't break in the future.

**Comment by manushree635** [comment]
> @manushree635 Thanks a lot for the PR. Can you tidy up a bit and add a descriptive title and link the issue in the description instead of the title? If you say "closes #19856" it will automatically close.
> 
> Without looking at the original issue, I suspect you will want to add a test so that this doesn't break in the future.

done

**Comment by jklymak** [comment]
Thanks - this needs to pass the current test suite and preferably would have a new test.

**Comment by melissawm** [comment]
Hi @manushree635 - are you interested in continuing this work? Please let us know if you need help moving forward. Cheers!

**Comment by dstansby** [comment]
Given this is very old with no response, and is made obsolete by https://github.com/matplotlib/matplotlib/pull/27576, I'm going to close. Thanks for opening!

**Pull request closed without merging**
