### PR TITLE
Add image tutorial as ipynb - with some additional content

### PR DESCRIPTION
**Pull request by msarahan**
Preliminary folder at root level called "tutorials" - probably not exactly what you guys want, but just a proposal to get the discussion going on where IPython Notebook-based tutorials might live.

The additional content is regarding axes calibration (extent) and aspect ratio.  There's also a little bit of cleanup/rework.

### CODE REVIEW

**Comment by tacaswell** [comment]
@msarahan Can you squash this so the checkpoints never existed?

**Comment by msarahan** [comment]
Thanks for looking at this.  I hope the squash worked.  I have also fixed a couple of minor issues (old Sphinx link that needed updating).  If there's any other outstanding issues, please ping me.

**Comment by tacaswell** [comment]
Thanks for coming back to this after so long!  Looks like the squash went perfectly.

I would like to hold off merging this until we have viridis in and then switch to using that as the color map :wink: and because we need a bit more thinking about how we want to handle notebooks + our docs.

Do we want to worry about the size of adding bunches of notebooks to the code base?  Do we want to output strip them for committing to the code base and execute them as part of building the docs (like we do with the script-based examples)?

**Comment by msarahan** [comment]
RE Viridis: sounds good.  Please ping me when that is done, and let me know exactly how you'd like this document (and the image tutorial, for that matter) to look.

Handling notebooks in docs is an open question in my humble opinion.  I'd be perfectly happy if this PR sat here until tools like NBDiff were integrated somehow with GitHub.  Personally, I wouldn't actually want notebooks as documentation at this point, since the diff/review process is more annoying.

That said, if you do want to go ahead including it, I think your idea of output stripping them and executing them at build time is the proper way to do it.

**Comment by NelleV** [comment]
It's done :)

I am slightly worried thought that having a notebook in the documentation is going to be a pain to maintain. Would it be possible to migrate to a sphinx-gallery like type of tutorial, and generate the notebook automatically from the python script? mne has cool tutorials based on this (cf http://martinos.org/mne/stable/auto_tutorials/plot_introduction.html, the notebook: http://martinos.org/mne/stable/_downloads/plot_introduction.ipynb and the corresponding code: https://github.com/mne-tools/mne-python/blob/master/tutorials/plot_introduction.py

**Comment by dstansby** [comment]
@NelleV thoughts on this now sphinx-gallery is happening? Maybe we could still incorporate the tutorial somehow?

**Comment by choldgraf** [comment]
my 2 cents: now that sphinx-gallery is fully incorporated into the docs, I think it's better to write these tutorials as python files, since they will be auto-converted into jupyter notebooks for users to download. I agree w/ @NelleV that it will make things much easier to maintain

**Comment by tacaswell** [comment]
I agree that it is probably better to convert this to a `*.py` file that gets run through sphinx-gallery.

**Comment by msarahan** [comment]
Ok. I have to say the probability of me getting to this any time soon is
pretty small. If there's a motivated volunteer, please feel free to take
this in your own direction.

**Comment by tacaswell** [comment]
no worries @msarahan !

**Comment by choldgraf** [comment]
this seems to be almost totally already implemented here:

http://matplotlib.org/devdocs/tutorials/introductory/images.html#sphx-glr-tutorials-introductory-images-py

It seems somebody has already done this work, no?

**Comment by jklymak** [comment]
yeah this is already in the docs.  Closing!

**Pull request closed without merging**
