### PR TITLE
fix for #1235

### PR DESCRIPTION
**Pull request by wmak**
Fix for #1235, legend box not taking points into account.

### CODE REVIEW

**Comment by tacaswell** [comment]
@wmak Are you still interested in working on this?

**Comment by dashed** [comment]
@pelson @efiring  @tacaswell Seems this PR was put forth by a group of students as part of a university course in 2014. see: http://www.utsc.utoronto.ca/~atafliovich/cscd01/

@wmak may unlikely to follow up on this PR anymore as he has since graduated. I'm also taking the same course in question for the 2016 semester. I'm part of a team of students looking for bugs/features to take on; and we'll happily take over this PR.

----

I'm pretty much active on GitHub, so I can, and will definitely follow up on this PR till it's merged; even after I've finished the course :smile:

**Comment by pelson** [comment]
> @wmak may unlikely to follow up on this PR anymore as he has since graduated. I'm also taking the same course in question for the 2016 semester. I'm part of a team of students looking for bugs/features to take on; and we'll happily take over this PR.

Yes please. :+1: for your community spirit. Contributions *very* welcome!

**Comment by WeatherGod** [comment]
This would actually be very important to have for the upcoming v2.0 release, as it will have "best" as default.

**Comment by QuLogic** [comment]
Replaced by #6110.

**Pull request closed without merging**
