### PR TITLE
BUG : fix security bug reported via debian by Matt Giuca

### PR DESCRIPTION
**Pull request by tacaswell**
attn @mdboom

### CODE REVIEW

**Comment by tacaswell** [comment]
and attn @efiring

**Comment by tacaswell** [comment]
@mgiuca ping me if you want this rebased with your name on the commit.

**Comment by mgiuca** [comment]
Hi @tacaswell. Glad to see this is getting patched in. If you can, please set the author email to mgiuca@google.com (so that the work is attributed to Google).

**Comment by efiring** [comment]
Looks OK to me.

**Comment by tacaswell** [comment]
I don't think that test actually tests `Printf` any more and something else along the line is raise an error that the file name is too long.

Trying to get to `Printf` via capstyle is also proving difficult, too many layers do verification before it goes to the c++ layer.

**Comment by efiring** [comment]
You could just take out the test.  Nul-terminating a C string can't hurt.  We'll never have tests for *everything*.

**Comment by tacaswell** [comment]
and removed instead of going though and understanding how that exception changed between py2k and py3k.

**Comment by tacaswell** [comment]
This is failing on the pep8 tests.

I am strongly disinclined to back-port those fixes to the 1.4.x branch.

**Comment by efiring** [comment]
@tacaswell I agree--it doesn't seem worthwhile to do that backport.  It's now one more reason to freeze the branch after 1.4.3.

**Comment by mdboom** [comment]
This didn't *introduce* a PEP8 failure, right?  Is there some change to the pep8 tool that is causing all these new warnings?

In any event, this patch looks fine.  The code simply doesn't exist anymore on master, so it doesn't matter there.

**Comment by tacaswell** [comment]
Yes, the pep8 issues are from the pep8 version bumping and changing error codes (see #4081).

**Comment by tacaswell** [comment]
I'll add a flag to travis to force-install the old version for this branch.

**Comment by mdboom** [comment]
Cool.  Merging.

**Pull request merged**
