### PR TITLE
Remove the private Axes._set_position.

### PR DESCRIPTION
**Pull request by anntzer**
The distinction between Axes.set_position and Axes._set_position is no
more since the constrained_layout rewrite went in.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Oh, hmm.  I think this is not the correct fix.  I think when the user manually calls `set_position` we need to take the axes out of the layout machinery somehow.  a) if this passes all the tests, we need to fix the tests, and b) we may need a proper method to not move an axes.

**Review by jklymak — CHANGES_REQUESTED** [review]
Blocking because we need some way to manually let users set the position and not then change it on them on the next redraw...

**Comment by anntzer** [comment]
This does pass the tests, so I guess some other test is needed and you can take this as a bug report then :)

**Comment by jklymak** [comment]
Agreed.  I'll look at it "soon".  This should definitely block 3.4 but I should have time to fix before 3.4 is actually released 😉

**Comment by jklymak** [comment]
Right, so 

```python
import matplotlib.pyplot as plt

fig, axs = plt.subplots(2, 2, constrained_layout=True)

axs[0, 0].set_position([0.2, 0.3, 0.2, 0.3])
plt.show()
```

would do 

Old

but now does:

New

which is a clear regression (for 3.4)

**Comment by jklymak** [comment]
Failing tests are nbconvert on windows...

**Comment by anntzer** [comment]
Superseded by https://github.com/matplotlib/matplotlib/pull/18453.

**Pull request closed without merging**
