### PR TITLE
Deprecate angleA/B parameters of bracket arrowstyles.

### PR DESCRIPTION
**Pull request by anntzer**
They actually have no accompanying implementation and have no effect (as
can be checked e.g. with
```
annotate("", (.4, .5), (.6, .5),
         arrowprops=dict(arrowstyle=mpl.patches.ArrowStyle("]-[", angleA=45, lengthB=5)))
```

Perhaps the feature (rotating the brackets) makes sense, but we can
always restore it when someone puts in an implementation).

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
These would seem pretty straightforward to implement, though we would have to decide what 0 meant.

**Comment by anntzer** [comment]
I would just have said `0` (or `90`) = normal (orthogonal to the arrow) and rotate counterclockwise (or clockwise, whatever we do for every other rotation)?
I am not opposed to someone implementing it, but for now the thing is just confusing.

**Comment by timhoffm** [comment]
Slight preference for `0` = normal.

**Comment by anntzer** [comment]
Superseded by #19460.

**Pull request closed without merging**
