### PR TITLE
[MRG+2] Moved python files from doc/pyplots to examples folder

### PR DESCRIPTION
**Pull request by wgma00**
Completed the first two changes specified in  #7390  . When I was looking through the ``pyplots`` files with grep I didn't spot any places where the stdlib ``random`` module was used in stead of the ``numpy.random`` module.

### CODE REVIEW

**Comment by NelleV** [comment]
That's great!
Thank you for doing this work.

**Comment by NelleV** [comment]
The failing tests are pep8 related error, which we probably don't want to fix in this PR…
If we merge, what's going to happen? How are the pep8 tests ran?

**Comment by QuLogic** [comment]
You can add those files to the list near the end of `lib/matplotlib/tests/test_coding_standards.py` to ignore the pep8 warnings for now.

**Comment by efiring** [comment]
Strangely, the pep8 checker doesn't ignore the excluded files, it checks to make sure they *need* to be excluded!
```
ValueError: Some exclude patterns were unnecessary as the files they pointed to either passed the PEP8 tests or do not point to a file:
  */pyplots/pyplot_scales.py
  */pyplots/pyplot_text.py
  */pyplots/pyplot_three.py
  */pyplots/whats_new_99_mplot3d.py
```

**Comment by NelleV** [comment]
The strategy implemented on #7403 which runs flake8 on diffs fixes the issue we have on this PR.

Currently, there is a test that ensures that blacklisted files need to be blacklisted. Hence the new failure.

**Comment by NelleV** [comment]
Thanks @wgma00 for the patch!

Cherry-pick in 2.0 with 263e675327

**Comment by tacaswell** [comment]
Complaining that an excluded file passes is a feature of the system to (slowly) ratchet our way to PEP8 compliance (so we do not accidentally fix a file and then break it again).

**Pull request merged**
