### PR TITLE
Fix integers being passed as length to quiver3d.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

closes https://github.com/matplotlib/matplotlib/issues/15186.

As it turns out there was a subtle difference between `linspace(0, length, num=2)` and `np.asarray([0, length])`: the former always returns a float array...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
I added a test and explicitly set the dtype rather than relying on implicitly picking up the float.

**Comment by tacaswell** [comment]
this did not get backported for v3.1.2 or v3.1.3 but is included in v3.2.0, re milestoned to match that.

**Comment by QuLogic** [comment]
But the backport of this PR didn't happen for 3.2.0 either?

**Comment by tacaswell** [comment]
This got merged before we branched.  The commit claims to be in the rcs

**Comment by QuLogic** [comment]
Oh yes, I hadn't realized this was so old. It is there.

**Pull request merged**
