### PR TITLE
[ENH] Initial support for linestyle cycling on plot()

### PR DESCRIPTION
**Pull request by WeatherGod**
Work in progress. Need tests and need to make sure I don't have unintended side effects.

Do we want to do markers as well? Possibly hatches, too?

### CODE REVIEW

**Comment by tacaswell** [comment]
@WeatherGod I think this should be re-address using Cycler.

**Comment by WeatherGod** [comment]
Right, it does look like the right thing to do. So basically, redo this to use the Cycler objects?

**Comment by tacaswell** [comment]
Yes.  I think the right path here is to add a `Cycler` object (well a `itertools.cycle` of a `Cycler`) to the Axes, everyplace we use the color cycle internally change to look at deal with dicts out of `Cycler`, deprecate the current color cycle, but fake it up well enough that user code that uses it still works, and add the needed rcparams + helper functions.

**Comment by WeatherGod** [comment]
Sounds like a good project to do on an airplane ride to SciPy, don't you
think? ;-)

**Comment by pelson** [comment]
> Sounds like a good project to do on an airplane ride to SciPy, don't you think? ;-)

:+1: - that, or in the sprints proper... might even be a nice little project for somebody with less experience.

**Comment by ppinard** [comment]
The "default changes" tag should be added to this pull request.

**Comment by tacaswell** [comment]
This should not be changing any defaults, just adding more flexibility.

**Comment by tacaswell** [comment]
Sorry, was confused what pr this was my email

**Comment by WeatherGod** [comment]
This should be considered as superseded by #4686.

**Pull request closed without merging**
