### PR TITLE
Prefer Axes.remove() over Figure.delaxes() in docs.

### PR DESCRIPTION
**Pull request by anntzer**
remove() works for all artists, and is thus more useful to know than
delaxes() (which is does exactly the same, but only for axes).

See also https://github.com/matplotlib/matplotlib/pull/15290.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by timhoffm** [comment]
+\-0 on this. The downside is that delaxes() is also the pyplot way to do this.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Approval modulo fixing the doc build.

I take @timhoffm 's point about matching pyplot, but I tip more towards "there is no reason Axes are different than other Aritsts".

**Comment by QuLogic** [comment]
Rebasing should fix the docs, I think.

**Comment by anntzer** [comment]
rebased

**Comment by timhoffm** [comment]
@anntzer is it correct that there is only one change left after the rebase?

**Comment by anntzer** [comment]
that was the only change to start with?

**Pull request merged**
