### PR TITLE
cairo: remove the append_path() fast path

### PR DESCRIPTION
**Pull request by lazka**
## PR Summary

With the performance improvements in #13039 the old slow path is now faster
than the previously fast one. And it also works with pycairo.

Using the Gtk3Cairo backend with wire3d_animation_sgskip.py:

cairocffi + append_fast: 13.27 fps
cairo + append_slow: 15.07 fps
cairocffi + append_slow: 13.54 fps

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by lazka** [comment]
This should be ready now.

**Comment by tacaswell** [comment]
I would like @anntzer to take a look at this before we merge, I suspect this orthogonal to mplcairo, but just want to be sure.

**Comment by anntzer** [comment]
I was thinking that for very long paths (e.g. `plot(np.random.rand(10000))`), the "fast" codepath would still be preferable (as it converts the whole Path object to cairo's internal representation in one go, rather than looping on Python's side), but interestingly this is not the case.
I thought what's happening is that:
- for short paths, @lazka's optimizations made python-side iteration fast enough that the previously slow path is good enough,
- for long paths, when rasterizing to the screen or to png, it's the rasterization time itself that starts dominating over the loop-in-python (because the rasterizer must check for all possible self-intersections of the path).
However, the "slow" codepath is actually also faster when writing to a vector format (e.g. pdf), so that can't be the only explanation involved.

In any case, I can repro the reasonable performance (and yes this is totally orthogonal to mplcairo, thanks for the heads up).

**Comment by lazka** [comment]
Thanks! :)

**Pull request merged**
