### PR TITLE
fix: removed inconsistent spacing between lines

### PR DESCRIPTION
**Pull request by Thillerer**
## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by oscargus** [comment]
As noted from the linting errors, we would like to keep two lines between different classes/functions etc.

**Comment by Thillerer** [comment]
@tacaswell Where can I find the style guide for the project. I would really like to contribute but I am just a beginner on github and an intermediate on python, so I thought I could start by doing this. Can you point me in a direction?

**Comment by rcomer** [comment]
Thanks for your interest in contributing @Thillerer!  Please see our guide here:
https://matplotlib.org/stable/devel/contributing.html

**Comment by melissawm** [comment]
Hi @Thillerer - feel free to also join our [gitter space](https://gitter.im/matplotlib/matplotlib) or our monthly New Contributor meetings if you have questions. Cheers!

**Pull request closed without merging**
