### PR TITLE
Fix colorbar bad ticks

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

As noted in issue #11510, extra ticks can get into the colorbar that extend past the minimum or maximum due to the presence of the "extend='both/lower/upper'` kwarg. This fixes that issue for *major* ticks.  

An *enhancement* would be to come up with a `cb.minorticks_on` function to colorbar that supplies the appropriately trimmed minor tick locator as well.  That can be a further PR.   But this really fixes a bug in the existing functionality...

```python

import matplotlib.pyplot as plt
import numpy as np

np.random.seed(seed=12345)
x = np.random.randn(20, 20)
fig, ax = plt.subplots()
im = ax.pcolormesh(x)

cbar = fig.colorbar(im, extend='both')
plt.show()

```

## Before:
boo

## After

boo

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I mentioned in a few places that it should really be the responsibility of the ticker to return ticks that are indeed between vmin and vmax (should perhaps start a metaissue on that :)); looks like this is yet another reason to require so.  Won't block this quickfix of course but perhaps leave a comment that it doesn't address the root issue (so that we can remove this patch once the real fix above is implemented).

**Comment by jklymak** [comment]
> perhaps leave a comment that it doesn't address the root issue...

Well, the docstring of the classes explicitly state that they work around this limitation - the problem here was that I forgot to actually do it for `_ColorbarAutoLocator` in the original PR!  Duh...

**Comment by jklymak** [comment]
@meeseeksdev backport to v2.2.x

**Comment by jklymak** [comment]
probably not worth the backport wrigamarole...

**Pull request merged**
