### PR TITLE
Allow interrupts to be delivered once Python is fixed.

### PR DESCRIPTION
**Pull request by mdehoon**
This is related to issue #3991. Until now the MacOSX backend did not deliver interrupts while the event loop is running as Python itself would ignore those interrupts anyway. This PR allows interrupts to be delivered once Python is fixed.

### CODE REVIEW

**Comment by tacaswell** [comment]
@mdehoon Who else knows this code well enough to review it?

**Comment by tacaswell** [comment]
and should this be back-ported to 1.4.x?

**Comment by mdehoon** [comment]
@tacaswell  Few people have a good understanding of event loops, in particular people coming from a scripting background. This PR is not a major change, so I think getting a review is not critical. I would suggest to wait until Python itself is fixed (because without that, this PR doesn't add any functionality anyway), and after that apply the PR and let some users test it. This PR does not need to be back-ported to 1.4.x.

**Comment by mdehoon** [comment]
I have uploaded a patch for Python; see issue 23237 at
http://bugs.python.org/issue23237
With this patch, and this pull request, interrupts will be delivered for the MacOSX backend (and also for Tkinter). I would appreciate it if interested people can give this a try.

**Comment by tacaswell** [comment]
Is there harm in merging this before python is fixed?

**Comment by mdehoon** [comment]
This can be merged before Python is fixed, so it's OK to merge it now. This pull request also fixes issue #3654 .

**Pull request merged**
