### PR TITLE
FIX scipy is not a requirement

### PR DESCRIPTION
**Pull request by NelleV**
Scipy is not a requirement for the documentation build.

### CODE REVIEW

**Comment by tacaswell** [comment]
How did we lose the scipy dependency in building the docs?

**Comment by tacaswell** [comment]
Thanks @NelleV !

**Comment by QuLogic** [comment]
We "do" and we "don't"; e.g., these two examples use scipy:
* https://github.com/matplotlib/matplotlib/blob/a9a8634f17791f00e8c88c0b3d467e6be3c32c07/examples/animation/double_pendulum_animated_sgskip.py
* https://github.com/matplotlib/matplotlib/blob/81495363d283809021b5ae4fc87bbd5edbbb3f6c/examples/animation/bayes_update_sgskip.py
But they're currently being skipped.

**Comment by anntzer** [comment]
They're both animations, so we "don't" until s-g starts supporting animations...

**Comment by tacaswell** [comment]
The changes to `check_deps` from #9365 did not get backported.

Re-milestoned this to 2.2 and not backporting, any protests?

**Comment by NelleV** [comment]
I don't think this needs backporting.

**Pull request merged**
