### PR TITLE
Don't fallback to view limits when autoscale()ing no data.

### LINKED ISSUE #15251: Large memory growth with log scaling and linear ticking
I found that I can make my machine spike in memory usage with just this:
```python
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator

fig, ax = plt.subplots()
ax.set_yscale('log')
ax.yaxis.set_major_locator(MultipleLocator(100))
plt.savefig('test.png')
```
When I say huge, I mean I see memory usage go up and I kill it before I end up with an unresponsive system.

Removing either of the log scaling or the `MultipleLocator` causes the huge memory spike to disappear.

### LINKED ISSUE #15331: Log Scale: FloatingPointError: underflow encountered in power
### Bug report

**Bug summary**

When setting the scale to log on an empty axis while having numpy error handling set to raise, a FloatingPointError is thrown. When plotting data beforehand, everything works fine.

This is an issue for me, because I'm trying to plot multiple subplots with shared y axes after each other, where this issue occurs as well. For some reason in that context the error handling seems to bet set to raise.

Issue #4285 is related but the stack trace is different and this issue is not dependent on data.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

np.seterr(all="raise")

#plt.plot([1], [1])
plt.yscale("log")
```

**Actual outcome**

```
Traceback (most recent call last):
  File ".../.PyCharmCE2019.2/config/scratches/scratch_44.py", line 7, in <module>
    plt.yscale("log")
  File ".../venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3088, in yscale
    return gca().set_yscale(value, **kwargs)
  File ".../venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3711, in set_yscale
    self.autoscale_view(scalex=False)
  File ".../venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2498, in autoscale_view
    'minposy', self.yaxis, self._ymargin, y_stickies, self.set_ybound)
  File ".../venv/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2486, in handle_single_axis
    x0, x1 = inverse_trans.transform([x0t, x1t])
  File ".../venv/lib/python3.6/site-packages/matplotlib/transforms.py", line 1394, in transform
    res = self.transform_affine(self.transform_non_affine(values))
  File ".../venv/lib/python3.6/site-packages/matplotlib/scale.py", line 334, in transform_non_affine
    return ma.power(self.base, a)
  File ".../venv/lib/python3.6/site-packages/numpy/ma/core.py", line 6717, in power
    result = np.where(m, fa, umath.power(fa, fb)).view(basetype)
FloatingPointError: underflow encountered in power
```

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.8
  * Other libraries: Numpy == 1.17.2

All packages were installed using pip.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Closes #15251; see discussion there.

Edit: Also closes #15331.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
oops.
I checked @jklymak's example where just `yscale("log")` would result in huge limits -- this PR fixes that, with now a test; but not yours.  Indeed things still break in your case because you swap out the locator before it had time to set proper limits; I guess this validates @jklymak's point that this should really be the job of the scale, not of the locator.  In the meantime, though, this can be fixed by forcing an autoscale immediately after set_xscale/set_yscale...

**Comment by jklymak** [comment]
Like I guess this is fine.  Is there a reason to not just do a `_request_autoscale_view` like we do for adding most artists?

**Comment by anntzer** [comment]
Because if one does so, the autoscale() occurs too late -- @dopplershift already swapped out the correct locator at that point (correct for the purpose of finding the default range).

**Comment by jklymak** [comment]
Sorry I meant where you put the extra logic in scale.

**Comment by anntzer** [comment]
sorry, what do you exactly propose?

**Comment by jklymak** [comment]
In `set_yscale`, just call `self.autoscale_view` (I thought you could say "request" but it doesn't get called until too late as you say).  That just seems simpler than a the convoluted way you are checking to inf now.  

I still think this should be in `scale`  We already have `limit_range_for_scale`; a `default_range_for_scale` would make a heck of a lot more sense than calling `nonsingular` for the `locator`.  (Why is it called `nonsingular` anyhow?)

**Comment by anntzer** [comment]
> In set_yscale, just call self.autoscale_view (I thought you could say "request" but it doesn't get called until too late as you say). That just seems simpler than a the convoluted way you are checking to inf now.

It *looks* this this would work, but in that case you get again a warning when using secondary axes with 1/x (because it would try to do 1/0, even if you later move the limits away from zero).  Yes, it's kind of a gross hack, essentially relying on the fact that SecondaryAxes doesn't override nonsingular...

> I still think this should be in scale We already have limit_range_for_scale; a default_range_for_scale would make a heck of a lot more sense than calling nonsingular for the locator.

Agreed this would be a better place (I forgot about limit_range_for_scale), but then where do you handle dates?

> (Why is it called nonsingular anyhow?)

Probably because it (also) expands singular limits (xmin=xmax)?

**Comment by jklymak** [comment]
OK so an axis has a scale, units, and Locators, and they are all kind of separate but intermingled.  Blech.  

Long run I don't think dates should have a limitation to positive numbers >1 (see  https://github.com/matplotlib/matplotlib/pull/15148).  That will mean the default dates will be -0001-12-01 to 0000-01-01, but so be it.  Do other units have strange limitations on the limits?

If we agree units should not have a problem with any value thrown at them, then I'd argue the limits should still go on the scale.  OTOH, I'm sure #15148 won't go in any time soon, but I think its worth thinking through where this functionality belongs

**Comment by anntzer** [comment]
In the core lib no other units wants their own default limits.  pandas datetimes appear to use the same machinery; astropy units appear to not touch that; dunno what other big unit users there are out there that we can check.  I guess we could ask @dopplershift his opinion too given that 1) he reported the original issue and 2) he's involved in units handling, IIRC :)
I guess alternatively units could grow their own limit_range_for_unit and we'd call both the scale's limit_range_for_scale and the unit's limit_range_for_unit in some yet to be decided order.  "Blech", as you say.

**Comment by dopplershift** [comment]
In my mind the units machinery is only about converting data to a common numerical reference frame before plotting. Given that, I don't think it makes sense for limits to enter into the picture--and indeed that our current date time handling enacts limits seem kind of arbitrary.

**Comment by jklymak** [comment]
The practical problem is that the default linear limits are [0, 1], and the default `datetime` library doesn't accept anything less than 1.0 as an ordinal number.  So if someone instantiates a date axes, but don't put any data on it, it errorred out.  

How the locators ended up as the home of the default limits, I don't know.

**Comment by anntzer** [comment]
By the way, note that `limit_range_for_scale` "doesn't really work", either -- it takes 3 args -- vmin, vmax, and minpos, where minpos (the smallest positive data value) is basically there "just" so that log scale can do its thing, but of course other scales such as logit are basically stuck because we don't track the largest data value less than 1...
I think the correct approach is actually to *not* track dataLim as artists are being added, but rather, *at autoscaling time*, perform the transform and compute the (finite) data limits from there -- then negative values in log scale just map to nan and can be properly ignored.  Unfortunately this runs into a snag when log scale uses nonpos="clip" rather than nonpos="mask" :(

**Comment by anntzer** [comment]
They are effectively tested by test_date_empty, test_date_axhspan, test_RRuleLocator, and a couple of other tests which get broken if that snippet is removed.

**Comment by anntzer** [comment]
I'll milestone as 3.2 as it's a regression in 3.1, but won't insist on it as we're quite late in the cycle already...

**Pull request merged**
