### PR TITLE
Fix AttributeError when saving figure with partial Latex elements as a postscript (issue 7741)

### LINKED ISSUE #7741: AttributeError when saving figure with partial Latex elements as a postscript.
I am trying to save some figures I made as .ps or .eps but I am getting an error. I narrowed the error down to the fact that I am using Latex for some of the text in my figure but using `rc.params['text.usetex'] = False`. Here is some code that reproduces the bug:

```python
import matplotlib
import matplotlib.pyplot as plt
fig = plt.figure()
plt.text(0.5, 0.5, 'Here is some text, $math mode$', ha='center', va='center', usetex=True)
fig.savefig('test.ps')
```

The error you get is `AttributeError: 'RendererPS' object has no attribute 'textcnt'` 

When looking at [this code in in the RendererPS class](https://github.com/matplotlib/matplotlib/blob/ab98852fa3b760e87208de53d058f82c3bf934bc/lib/matplotlib/backends/backend_ps.py#L191) the `textcnt` attribute is only added when `rc.params['text.usetex'] = True`. However I am just using Latex for specific text objects with the option `usetex=True`. Is there a way to save these figures as .ps or .eps?

I am using Matplotlib 1.5.1 installed via conda on Windows with python 2.7. I also tested it with Matplotlib 2.0.0b4 which also produced the same error, however I would prefer a solution for 1.5.1 if possible.

### PR DESCRIPTION
**Pull request by ibnIrshad**
Fixes #7741 

The PostScript backend relies on `rcParams['text.usetex']` being set explicitly in order to load TeX correctly. So we set `rcParams` when the Axes arg `usetex` is set.

The fix can be verified by running this bug reproduction script (it will crash with an AttributeError unless this PR's patch is applied).

```python
import matplotlib
import matplotlib.pyplot as plt
fig = plt.figure()
plt.text(0.5, 0.5, 'Here is some text, $math mode$', ha='center', va='center', usetex=True)
fig.savefig('test.ps')
```

### CODE REVIEW

**Comment by tacaswell** [comment]
The first half of this (grapping `usetex` from kwargs is good), but the other half of this is probably going to have to be in the ps backend.

**Comment by ibnIrshad** [comment]
@tacaswell I agree that it seems hacky to modify global state in a single artist...but I think it is appropriate here. The PS backend relies on the `rcParams['text.usetex']` setting in order to initialize its latex texmanager, which is then used by all subsequent latex text renderings. This `rcParams` setting does not affect the rendering of every Text object (you can still have non-latex objects on the screen after setting rcParams to true), as it only controls the initialization of latex-specific managers. I think modifying the global state is appropriate in this case, because if a single artist requires latex, then the backend should initialize latex-specific stuff, even if it is not used for all the remaining text objects.

**Comment by jklymak** [comment]
Thanks for the PR. This hasn't seen action for a long time so marking stale.  Note that PRs sometimes fall through the cracks, so if this is important, please ping for more reviews.

**Comment by jklymak** [comment]
Closing due to no action.

**Pull request closed without merging**
