### PR TITLE
Use versioneer for version 

### PR DESCRIPTION
**Pull request by pelson**
Means we no longer have to go through the release version ping-pong. Just tag and go - nowhere in the source should the version be written explicitly.

### CODE REVIEW

**Comment by dopplershift** [comment]
:+1: in general. I've used it for a couple of my projects and love the fact that I don't change the source to reflect the version--just eliminates duplication of information.

**Comment by pelson** [comment]
Note - the downside of this is that we do not have a good naming scheme for maintenance branches (e.g. you can't tell the difference between a build from the ```v1.4.x``` branch and the ```master``` branch). I proposed such a change in https://github.com/warner/python-versioneer/pull/90, but haven't had it merged at this point.

**Comment by WeatherGod** [comment]
The release guide page should also be updated: http://matplotlib.org/devel/release_guide.html

**Comment by tacaswell** [comment]
:heart:  

I am partial to the `.postN` style formatting so `'1.4.3+2821.g2aae565'` vs `'1.4.3.post2821+g2aae565'`

@WeatherGod That is out of date anyway see #3707

**Comment by pelson** [comment]
Also, just found that downloading zip files from my fork results in a useless version. See https://github.com/warner/python-versioneer/issues/99. I'm not convinced that is a show-stopper though.
Overall, I'm happy with the the pro of not having to do version ping-pong commits vs the con's of:
 * not having an explicit version string to look at
 * cloned repos do not compute meaningful version strings from zip files

**Comment by pelson** [comment]
> I am partial to the .postN style formatting so

Me too. I'll update the defaults.

**Comment by mdboom** [comment]
:+1:  I guess this is a good reason to get #3707 in as well.

**Comment by tacaswell** [comment]
definitely agree that downloading zips from side-forks not having good versions is not a show-stopper (although, I am a bit confused as it looks like your fork has tags https://github.com/pelson/matplotlib/tags )

I'll convert that checklist over to rst as I go through it for this release.

**Comment by pelson** [comment]
> although, I am a bit confused as it looks like your fork has tags

I just pushed them. Trying to figure out if the problem exists between the keyboard and the chair... :wink:

**Comment by tacaswell** [comment]
hurray for race conditions!

**Comment by pelson** [comment]
> Trying to figure out if the problem exists between the keyboard and the chair... :wink:

Hmmm. Maybe it got a bit late - I just pushed the branch to upstream and downloaded from there (https://github.com/matplotlib/matplotlib/tree/versioneer), to the same result. I wonder if there is a git-ism that I've misunderstood...

Note to self: delete the branch tomorrow. (unless somebody beats me to it)

I'm going to have to call it a day today - should be available in T+14 hours @tacaswell.

**Comment by danielballan** [comment]
Is this installation of versioneer up to date? If I understand correctly, there should be a section in `setup.cfg` that I can't find here. That could be related to this issue.

@pelson's versioneer-fu is well above my own, though. Forgive me if I misunderstood your way of doing this.

**Comment by dopplershift** [comment]
Both of my other projects use versioneer without `setup.cfg` stuff. It's all in `setup.py`.

**Comment by danielballan** [comment]
The cfg component is in new versions only (and perhaps not essential,
depending on what you put in setup.py, but it seemed worth mentioning).

**Comment by tacaswell** [comment]
This happens on one of our day-job projects when downloading master as well, but it works when downloading tagged zips.

**Comment by tacaswell** [comment]
added a commit to change version string format and merged locally

**Comment by pelson** [comment]
> Is this installation of versioneer up to date? If I understand correctly, there should be a section in setup.cfg that I can't find here. That could be related to this issue.

Yes, it's up to date, but I patched the versioneer.py file to prevent the need for a setup.cfg, which I wanted to avoid if possible as I'd like people to be able to use their existing setup.cfg files for the next release of matplotlib. Not hugely pretty, but pragmatic.

> @pelson's versioneer-fu is well above my own

I'm not so sure. I've gone deep to add some core functionality, but I confess I still don't use it daily for my own projects yet. Hopefully having it in mpl will help that though.

**Pull request merged**
