### PR TITLE
Fix sphinx 1.4.0 issues

### PR DESCRIPTION
**Pull request by jenshnielsen**
It seems like the primary issues were that we added nodes and roles to the sphinx extensions multiple times. However, my understanding of the Sphinx extensions is not particularly great so I may be misunderstanding something.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
We may want to backport this to 2.x or possibly 1.5.x?

**Comment by jenshnielsen** [comment]
Fixes #6235

**Comment by mdboom** [comment]
Seems ok to me, and it makes sense that they would be more strict about adding nodes and directives multiple times.

**Comment by tacaswell** [comment]
backported to v1.5.1-doc as 3a944a6

**Pull request merged**
