### PR TITLE
Squashed commits for #11225

### PR DESCRIPTION
**Pull request by cldssty**
## PR Summary
This time I've squashed only the commits that I've made. 

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by cldssty** [comment]
#11225

**Comment by jklymak** [comment]
You can resurrect #11225:  

```
git pull origin
git checkout old-version
git reset --hard origin/new-version
git push origin old-version --force 
```
That will populate old-version with exactly what is in this version and make the old PR work fine...

**Comment by QuLogic** [comment]
But please also give the commit a more descriptive message than "1205".

**Comment by cldssty** [comment]
Ah right - thanks for the tip. Will edit the description as well!

**Comment by cldssty** [comment]
Ah right - will resurrect in a bit if that'll make things less convoluted!

**Comment by cldssty** [comment]
#11225 resurrected with correct squashed commits

**Pull request closed without merging**
