### PR TITLE
DOC: Prevent double entries in navigation panel of Using Matplotlib

### LINKED ISSUE #26261: [Doc]: Double entries in navigation menu of Using Matplotlib
### Documentation Link

https://matplotlib.org/devdocs/users/explain/colors/index.html

### Problem

The navigation panels for the sections `Colors`, `Text`, and `Animations using Matplotlib` contain their entries two times:
grafik

(the other sections are OK)

### Suggested improvement

remove double entries

### PR DESCRIPTION
**Pull request by StefRe**
## PR summary

Prevent double entries in navigation panel of Using Matplotlib.

closes #26261.
 
## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by StefRe** [comment]
Renaming README.txt to index.rst solved the double entries issue but it also removed to sphinx gallery thumbnails. Do we need the thumbnails?

OLD:
grafik

<br><br>  

NEW:
grafik

**Comment by tacaswell** [comment]
I would prefer the thumbnails over the headings, but that is a mild preference.  If getting that is hard this is :+1:

**Comment by jklymak** [comment]
Ah, 3 is probably the best bet

```
.. toctree::
   :includehidden:
```

So the todo here is 1) remove the manual TOC entries in https://github.com/matplotlib/matplotlib/pull/26141 and fix users/explain/index entries to have `:include hidden:`.  @StefRe happy for you to do this, or I'm happy to do it.

**Review by jklymak — CHANGES_REQUESTED** [review]
See comments for what I think is the right path here.

**Comment by StefRe** [comment]
@jklymak I would be grateful if you could finish this. I tried several things but I admit didn't fully understand what I'm doing actually, so it would be great if you could make this work so maybe I can learn how things work here.

**Comment by jklymak** [comment]
Sure, if OK it'll be easier for me to just open a new PR.  Thanks for noticing the issue!

**Pull request closed without merging**
