### PR TITLE
Drop support for Python 3.7

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

According to NEP 29 [1], Python 3.7 support should be dropped after Dec 26, 2021. As Matplotlib 3.6 will be out a few months from now, it is already time to be dropping 3.7.

I added Python 3.10 runs in place of 3.7 where they didn't already exist.

[1] https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by QuLogic** [comment]
Ah, there's no NumPy wheel, we should probably bump that first.

**Comment by QuLogic** [comment]
NEP 29 says we should be on NumPy 1.19 already; we're still on 1.17. I hope the two release bump is okay?

**Comment by tacaswell** [comment]
I think jumping 2 versions is OK.  The mistake was not bumping earlier, no reason to compound that by not bumping far enough now.

**Comment by tacaswell** [comment]
There are not wheels for pillow6.2.0 for py38 but there are for 6.2.1

**Comment by QuLogic** [comment]
I tried building with `oldest-supported-numpy`, but that installed an older version on Python 3.8, and the `setup_requires` bumped it to the latest, which didn't have wheels, so I had to do a fixed version there.

Also, disabled PyPy temporarily as the version of cibuildwheel that supports it breaks Windows builds, which I need to investigate and report upstream.

But otherwise, [the wheels are building](https://github.com/QuLogic/matplotlib/actions/runs/1695375362).

**Comment by QuLogic** [comment]
And AppVeyor doesn't have a 3.9 miniconda, so I just went with the default one instead.

**Comment by tacaswell** [comment]
Adding `image: "Visual Studio 2022"` should switch us to a new image that has a py38 miniconda.  

It also looks like they have a bunch of "system" python build (https://www.appveyor.com/docs/windows-images-software/#python) if we update the image.  I am not sure if we want to keep appveyor on conda (so we can test that things work as exected in conda), move it to the system Python or just drop appveyor all together.

**Comment by QuLogic** [comment]
> Adding `image: "Visual Studio 2022"` should switch us to a new image that has a py38 miniconda.

Yes, but there's still no 3.9 one.

**Comment by QuLogic** [comment]
Not sure why Tk is missing on macOS for Python 3.10; is anyone running 3.10 on a mac that can check?

**Comment by greglucas** [comment]
I have no issues with tk locally, from a fresh Python 3.10 installation from the release page.
image

I also don't have any issue with a conda python3.10 environment and running the interactive tests. It may be due to the MacOS 11 image...
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml

**Comment by tacaswell** [comment]
I think the right fix here is to be more careful about assuming tk is available in the tests.

**Comment by QuLogic** [comment]
Seems to be a bug Azure environment: https://github.com/actions/virtual-environments/issues/4931

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
So here it's failing in `test_backends_interactive` because of missing TkAgg. There is a skip, but the problem is it just checks that the package exists, and doesn't attempt an import, probably to avoid conflicts. The failure here is that it cannot be imported, not that it doesn't exist.

I don't know if we want to try harder to skip these sorts of errors, as it might require some extra communication from the subprocess to the main test. Maybe the changes in #22005 would make it easier?

**Comment by tacaswell** [comment]
I think one of later commits in #22005 will correctly skip tk in this case (but it is failing on the py37 issues again).

**Comment by QuLogic** [comment]
It looks like the fixes were tagged yesterday, but just haven't been rolled out to all builders yet.

**Comment by QuLogic** [comment]
They needed another fix; rollout is this week some time (I guess starting on the 9th probably.)

**Comment by QuLogic** [comment]
Deployment is around 99.9%, but it's close enough to get our build working. By the time this is merged, their fix will probably be out on all Azure machines.

**Review by greglucas — APPROVED** [review]

**Pull request merged**
