### PR TITLE
Adding spacer support for Tkinter's tookbar

### PR DESCRIPTION
**Pull request by DavidA94**
Screen snip of a custom toolbar with a spacer added:
capture

### CODE REVIEW

**Comment by tacaswell** [comment]
Nice!

Can you rebase this onto current master?  See http://matplotlib.org/devdocs/devel/gitwash/development_workflow.html?highlight=rebase#rebasing-a-pull-request-pr

**Comment by DavidA94** [comment]
I think it's rebased now. Please let me know if I did it wrong.

**Comment by tacaswell** [comment]
You merged your branch back in before pushing.  The last step of the rebase is to force push to GH.

**Comment by QuLogic** [comment]
That last step is a force push _without_ merging (which includes `git pull` which also does an implicit merge.) So rebase again and force push as the last step; no pull or merge beforehand.

Also, many tutorials seem to ignore branches, but it's _really_ useful to start a new branch when you are working on a PR. GitHub's PRs track branches. Since yours is named `v2.x`, it's hard to keep track of the "real" `v2.x` that's in the matplotlib repo here and the "patched" `v2.x`.

**Comment by DavidA94** [comment]
I'm just going to redo the change with proper branching and all.

**Comment by tacaswell** [comment]
@DavidA94 Thanks!  Sorry for git issues adding friction to this process.

**Comment by DavidA94** [comment]
Not a problem. The cost of version control. :) Before I do the new pull request, the rebase command just says "Current branch master is up to date". Is that because I just did a fresh fork? Or am I doing something wrong?

**Comment by tacaswell** [comment]
What exactly did you type + the std out?  Git has too much state to answer that question from the given information.

**Comment by DavidA94** [comment]
Tried a few commands:
> git rebase matplotlib/master
fatal: Needed a single revision
invalid upstream matplotlib/master

> git rebase master
Current branch TkSpacer is up to date.

> git rebase origin/master
Current branch TkSpacer is up to date.

**Comment by tacaswell** [comment]
can you go to our gitter https://gitter.im/matplotlib/matplotlib this will be faster that way :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
