### PR TITLE
BUG: Allowing unknown drawstyles

### LINKED ISSUE #6143: drawstyle accepts anything as default rather than raising
Setup
-----
`matplotlib.__version__` = 1.5.1
`matplotlib.__version__numpy__` = 1.6
Python 3.5.1, IPython 4.1.2  running under anaconda
OS: Red Hat 6.5

Matplotlib installed with `conda install matplotlib`.

Issue
-----
Supplying invalid `drawstyle` parameter to `plot` (and possible others) does not raise an error. I would expect the following **not** to work, but it does:

    >>> import matplotlib.pyplot as plt
    >>> plt.plot(range(5), range(5), drawstyle='mwahahahahaha')

For contrast, trying the same thing with `fillstyle` raises the expected error:

    >>> plt.plot(range(5), range(5), fillstyle='mwahahahahaha')
    ...
    ValueError: Unrecognized fillstyle full left right bottom top none

Notes
-----
The issue seems to be happening here: https://github.com/matplotlib/matplotlib/blob/3ba9279fd9810b088d876988b8b7cf419e470716/lib/matplotlib/lines.py#L988. I would submit a PR, but I am pretty sure that adding something like

    drawstyles = ('default', 'steps', 'steps-pre', 'steps-mid', 'steps-post')
    if drawstyle not in drawstyles:
        raise ValueError(' '.join(('Unrecognized drawstyle',) + drawstyles))

would mess up something or another. If not, I would be glad to make the change.

To help us understand and resolve your issue please check that you have provided
the information below.

### PR DESCRIPTION
**Pull request by madphysicist**
Fixes #6143. Added test as well.

### CODE REVIEW

**Comment by madphysicist** [comment]
@tacaswell Looks like its working now.

**Comment by tacaswell** [comment]
Backported to v2.x as e73859390f7d9cdc17838e007a900f2a3d2fd785

**Comment by tacaswell** [comment]
@madphysicist Thanks!

**Comment by madphysicist** [comment]
No problem. Is there a release notes or something like that I should update?

**Comment by tacaswell** [comment]
We maintain a `whats_new` for new features and an `api_changes` for api breaking changes.  This does not really fall into either category.

Looking into this a bit more, this might have caused a minor regression which is it used to be possible to set the drawstyle to `None` (which is the default value).  That should probably be restored.

**Comment by madphysicist** [comment]
Fixed that here: #6156.

**Pull request merged**
