### PR TITLE
[MRG+2] DOC Numpydoc documentation for def fill()

### PR DESCRIPTION
**Pull request by NelleV**
This PR converts the fill documentation to numpy doc.

This supersedes #7034 (removes the polygon args which are referred to properly in the docstring already and add pep8 fixes).

### CODE REVIEW

**Comment by QuLogic** [comment]
I don't suppose you can find out from @ZohrehPythonSchool whether he wanted to use his full name or not?

**Comment by NelleV** [comment]
@QuLogic I don't think it matters much.

**Comment by ZohrehPythonSchool** [comment]
I don’t mind really. Zohreh Shams or ZohrehPythonSchool are both fine.

Thank you,
Zohreh

**Comment by Kojoley** [comment]
backported to v2.x as 5524b35092f1c0601566047309040fc3c392bf59

**Pull request merged**
