### PR TITLE
Small cleanups to QuiverKey.

### PR DESCRIPTION
**Pull request by anntzer**
- Text already calls FontProperties._from_any on anything passed as
  fontproperties; no need to do it ourselves again.
- Group together x and y shifts for text positioning.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
I've moved this to draft until #23116 to prevent a new contributor from having to rebase because of a cleanup.

**Comment by anntzer** [comment]
I don't think these actually conflict, but sure, no hurries.

**Review by oscargus — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Comment by anntzer** [comment]
Actually to the best I can see this doesn't collide with #23116 at all.

**Comment by QuLogic** [comment]
I agree.

**Pull request merged**
