### PR TITLE
MEP30: make each "pseudotype" a class

### PR DESCRIPTION
**Pull request by brunobeltran**
## PR Summary

Hopefully I set this up correctly, looking forward to discussion!

### CODE REVIEW

**Comment by anntzer** [comment]
In the specific case of capstyle and joinstyle, I think it should be relatively easy\* to turn them into StrEnums (like IntEnums, but for strs...), i.e.
```
class CapStyle(str, Enum):
    butt = "butt"
    round = "round"
    projecting = "projecting"
```
and put the doc there and just call it a day.

(\*for mpl-specific values of "easy", conditions may apply)

**Comment by story645** [comment]
A discussed on the call, I like this ideas in terms of documentation/writing a matplotlib user manual of sorts...

I'm way more hesitant about it as code w/out a clear articulation of which parameters should be pseudotypes for. But as a first pass, I think this intersects w/ #6738 since doing that properly would require a validation method per parameter.

**Comment by QuLogic** [comment]
xref #14642 on enums.

Also, s/matplotlib/Matplotlib/g, mostly.

**Comment by timhoffm** [comment]
I propse to close this as too heavy. I think the solution is somewhere between `StrEnum`s and `Literal` type annotations, c.f. #14642.

**Pull request closed without merging**
