### PR TITLE
ENH: make subplot reuse gridspecs if they fit

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Right now, if we call

```python
import matplotlib.pyplot as plt
fig = plt.figure()

ax = fig.add_subplot(3, 4, 1)
ax2 = fig.add_subplot(3, 2, (3, 5))
print(ax.get_subplotspec().get_gridspec())
print(ax2.get_subplotspec().get_gridspec())

plt.show()
```

The gridspecs will be different.    Thats unfortunate, because there is no reason for these two subplots to not share the same gridspec, and if they do, then constrained_layout will work with them.  Note this change will mean that many calls to `pyplot.subplot` and `pyplot.subplot2grid` will now work with `constrained_layout=True` as well.  

This PR changes that so they two subplots use the same gridspec.  

**Note** The more fine-grained subplot call must come first, or the grid specs will not "fit", so this is pretty simple minded.  However, the PR doesn't make things worse, it just makes two gridspecs like it did before.  i.e. if we switch the order of the calls we get two gridspecs:

```python
import matplotlib.pyplot as plt
fig = plt.figure()

ax2 = fig.add_subplot(3, 2, (3, 5))
ax = fig.add_subplot(3, 4, 1)
print(ax.get_subplotspec().get_gridspec())
print(ax2.get_subplotspec().get_gridspec())

plt.show()
```

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I suppose this is a breaking change if someone was checking the results of `ax.get_geometry()` in their code and expected the geometry to stay the same:

```python
ax1 = fig.add_subplot(1, 2, 1)
ax2 = fig.add_subplot(1, 1, 1)
print(ax2.get_geometry())
```
used to return `(1, 1, 1)`, but now returns `(1, 2, 1)`.  Note thats `get_geometry` is pretty crappy function anyways, as it does not return the full geometry specification for an axes; i.e. the actual geometry of `ax2` is `(1, 2, (1, 2))`

**Comment by anntzer** [comment]
Perhaps a better idea would be to just always create a new gridspec with shape (lcm(gs1.nrows, gs2.nrows), lcm(gs1.ncols, gs2.ncols)) and reparent all axes to this gridspec?  This would avoid the order dependency.

**Comment by jklymak** [comment]
Yes, that could work.  Wasn't 100% sure this whole PR was a good idea, rather than just telling people to not use `add_subplot`, but happy to come back to it...

**Comment by anntzer** [comment]
I'm not really sure it's worth it either (well I don't think the implementation would be *that* complex), just pointing out the possibility.

**Comment by jklymak** [comment]
Taking this up again in a simpler form in #17347

**Pull request closed without merging**
