### PR TITLE
Cleanup: use `is not` instead of `not ... is`, etc.

### PR DESCRIPTION
**Pull request by anntzer**
https://github.com/takluyver/astsearch is great for looking for patterns to fix :-)

### CODE REVIEW

**Comment by afvincent** [comment]
Wouldn't the CI failure be due to [numpy issue #3322](https://github.com/numpy/numpy/pull/3322) (about `array_equal`)? All the failure tracebacks are similar to
```
File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.7/site-packages/numpy/core/numeric.py", line 2119, in array_equal
    return bool(equal(a1,a2).all())
AttributeError: 'NotImplementedType' object has no attribute 'all'
```

**Comment by anntzer** [comment]
Yes, basically this needed numpy 1.8.0.  Fixed now.

**Comment by NelleV** [comment]
I am pretty sure something is still wrong :)

**Comment by anntzer** [comment]
Bah, I just dropped that patch.

**Comment by NelleV** [comment]
@tacaswell We really need to set up appveyor so that the team is able to restart jobs.

**Comment by NelleV** [comment]
Closing and reopening for appveyor.

**Comment by QuLogic** [comment]
Something is weird in what actually got build on CI; I think a rebase is in order.

**Comment by anntzer** [comment]
Done (it rebased cleanly).

**Pull request merged**
