### PR TITLE
Made INSTALL.rst consistent

### PR DESCRIPTION
**Pull request by SidharthBansal**
## PR Summary

Changed `;`->`.` to make them consistent across the document
Changed heading to `Installtion Guide`

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by SidharthBansal** [comment]
Hi, I am Sidharth Bansal, new to this organisation. I have made a small change. @anntzer @story645
Kindly review the changes and suggest me if any changes required.

I have submitted the GSoC proposal. I am looking forward to contribute to Matplotlib this April so that I can grasp insights of the repo and tech stack. This will help me to go deep into the use cases for the proposal.

Thanks

**Comment by tacaswell** [comment]
Looks good to me, thank you!

**Comment by timhoffm** [comment]
Thanks!

**Comment by tacaswell** [comment]
We have changed minimum versions between master and v3.2.x.  I think it is OK to not backport these changes.

**Pull request merged**
