### PR TITLE
Revert "ENH: ship six 1.9.0"

### PR DESCRIPTION
**Pull request by matthew-brett**
This reverts commit 8fe495a705153bdb7a224f58c02d54272c321094.

Go back to using external six, to fix bug at #6537.

Also - update six required version to 1.10

Conflicts:
	lib/matplotlib/artist.py
	lib/matplotlib/axes/_base.py
	lib/matplotlib/backend_tools.py
	lib/matplotlib/backends/backend_mixed.py
	lib/matplotlib/backends/backend_pdf.py
	lib/matplotlib/backends/backend_svg.py
	lib/matplotlib/colors.py
	lib/matplotlib/dates.py
	lib/matplotlib/font_manager.py
	lib/matplotlib/legend_handler.py
	lib/matplotlib/tests/test_artist.py
	lib/matplotlib/tests/test_axes.py
	lib/matplotlib/tests/test_backend_qt5.py
	lib/matplotlib/tests/test_dviread.py
	lib/matplotlib/tests/test_image.py
	lib/matplotlib/tests/test_lines.py
	lib/matplotlib/tests/test_spines.py
	lib/matplotlib/textpath.py
	lib/mpl_toolkits/axes_grid/colorbar.py
	lib/mpl_toolkits/axes_grid1/anchored_artists.py
	lib/mpl_toolkits/axes_grid1/inset_locator.py

### CODE REVIEW

**Comment by matthew-brett** [comment]
I think the test failures are now unrelated.

**Comment by tacaswell** [comment]
:+1: I would merge this now, but I do not have time to backport it so will hold off on that.

**Comment by matthew-brett** [comment]
I'm happy to backport - you mean to the `v2.x` branch?

**Comment by jenshnielsen** [comment]
Yes to the 2.x branch. We are basically ready to cut 1.5.2 if we don't hear about any new issues so I think this is too high risk at the moment on 1.5.x and there will probably not be any 1.5 release after 1.5.2

**Comment by WeatherGod** [comment]
devil's advocate here:

the original reason for vendoring six was because of changes that were
happening in subsequent releases of six that broke our code. I didn't think
it was ever about pypi's reliability.

**Comment by tacaswell** [comment]
@WeatherGod I mostly recall the issue being bug reports where by people were getting mpl install without a working version of `six`

**Comment by matthew-brett** [comment]
I think I was the original advocate for vendoring six.  One of the arguments was to protect against new bugs in six, but it was always a fairly weak argument, because six is so widely used and stable now.  I suppose another year of six gives some more evidence against that case, and conversely, #6537 is someone hitting a bug that has been fixed in six.   So, I'm not saying it's completely cut and dried, but on balance I think unvendoring is better.

**Comment by tacaswell** [comment]
closing in favor of #6556 

This will land in master via one of the merge cascades.

**Pull request closed without merging**
