### PR TITLE
FIX: don't round image sizes to pixel if meant to be unsampled

### LINKED ISSUE #8981: Incorrect imshow extent in PDF backend
### Bug report

**Bug summary**

When plotting with `imshow` using the PDF (or SVG) backend the right and top edges of the extent are not correct. The left and bottom edges seem to be correct. 

The deviation is small but noticeable (I used a smaller figure size to make it more visible -- it seems not to scale with figure size). It also appears to be unaffected by the interpolation mode. I noticed while returning to an old set of scripts -- I think this wasn't an issue for MPL pre-2.0 but unfortunately I'm unable to be more specific than that. 

A minimal code example is given below (I've tested it with a blank matplotlibrc as well and the issue persists).

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
fig.set_size_inches([2,2])
ax = fig.add_subplot(111)

x0, x1 = 0.0, 1.0

ax.set_xlim(x0-0.1,x1+0.1)
ax.set_ylim(x0-0.1,x1+0.1)

ax.plot([x0,x0],[x0,x1],color='r',lw=0.1)
ax.plot([x1,x1],[x0,x1],color='r',lw=0.1)
ax.plot([x0,x1],[x0,x0],color='r',lw=0.1)
ax.plot([x0,x1],[x1,x1],color='r',lw=0.1)

ax.imshow(np.zeros((16,16))+0.5,
          cmap='Blues',
          origin='lower left',
          extent=(x0,x1,x0,x1),
          interpolation='none',
          vmin=0,vmax=1)

fig.savefig("minimal.pdf")
fig.savefig("minimal.png",dpi=600)
```

**Actual outcome**

The red outlines (set to match the extent) are *not* at the edge of the blue square. See the PDF examplee and the zoomed version (attached below).

[minimal.pdf](https://github.com/matplotlib/matplotlib/files/1194753/minimal.pdf)
show-pdf-zoom

**Expected outcome**

The red outlines (set to match the extent) should be at the edge of the blue square. See the PNG example and the zoomed version (attached below).

minimal
show-png-zoom

**Matplotlib version**
  * Operating System: Linux 4.12.3-1-ARCH
  * Matplotlib Version: 2.0.2 (Both packaged from Arch and latest version compiled myself)
  * Python Version: 2.7.13 and 3.6.2

### PR DESCRIPTION
**Pull request by jklymak**
Closes #8981 
## PR Summary

For images we do some pixel rounding, but if we are doing unsampled images (eg `imshow(..., interpolation='none')`) and saving to a backend that allows rasters (svg, pdf), then we don't want to do the pixel rounding - that just makes the image sizes fractionally too large when that isn't needed at all if we don't resample.  

All the test images that changed just model my a pixel, and all have `imshow(..., interpolation='none')`.  

### Old

Old

### New

New

#### code 

```python
import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot([0, 0, 1, 1, 0], [0, 1, 1, 0, 0], color='r', lw=0.1)
np.random.seed(19680801)
ax.imshow(np.random.randn(16, 16), cmap='Blues', extent=(0, 1, 0, 1),
            interpolation='none', vmin=-1,vmax=1)
ax.set_xlim(-0.1, 1+0.1)
ax.set_ylim(-0.1, 1+0.1)
```

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by oscargus — APPROVED** [review]
I haven't checked, but maybe make sure that all of the now modified tests have `style='mpl20'`?

**Comment by jklymak** [comment]
I think for review send posterity it probably makes sense to leave the images in the style they are already in? It's pretty easy to see they are only trivially changed whereas if we changed the colormaps they would change a lot.  I think the style changes are minimal for these ones anyway - just colormaps for instance.  While I appreciate there are those who hate jet, it's probably OK for testing 😀

**Comment by jklymak** [comment]
Hopefully it will be moot when @tacaswell finishes his procedure for keeping track of image changes

**Review by ksunden — APPROVED** [review]

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.7.x

**Pull request merged**
