### PR TITLE
Fix deprecation for pydata-sphinx-theme 0.13.0

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Fixes half of #25344

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by oscargus** [comment]
There are no files `images/logo2.svg` (but `logo2.svg`) and `images/logo_dark.svg` (although I actually had one in my build directory earlier).

This came in through https://github.com/matplotlib/matplotlib/commit/f4a50d3ebfcd3cb85f9062c5a0238214b7e25867

@jklymak any ideas?

**Comment by jklymak** [comment]
These are part of `mpl-sphinx-theme` and are at `mpl-sphinx-theme/mpl_sphinx_theme/static/images/`. They get transferred across as part of the build process to `_static/images`.  Is this not working with 0.13?

**Comment by jklymak** [comment]
This looks to have been changed by https://github.com/pydata/pydata-sphinx-theme/pull/1132. I don't have time right now to dig into how to fix, but I think it needs to be in mpl-sphinx-theme.

**Review by jklymak — CHANGES_REQUESTED** [review]
I'll block because I think this needs to happen in mpl-sphinx-theme..

**Comment by oscargus** [comment]
Ahh, OK!

I think that maybe the other change is valid, but I will revert the logo-part.

**Comment by jklymak** [comment]
I would just avoid 0.13.0 for now.  I'll try to work with them for a fix for 0.13.1

**Comment by oscargus** [comment]
OK! Guess the deprecation will still be there, so for what it is worth.

**Comment by oscargus** [comment]
Closing this since it has been solved elsewhere(?).

**Pull request closed without merging**
