### PR TITLE
Add SVG animation.

### PR DESCRIPTION
**Pull request by dbrnz**
This is PR #4255 re-based against master and with a minor tidy up. The various examples that I've tried work although saving to SVG is slow for a non-trivial example; I next intend to go through the code to try to speed things up.

### CODE REVIEW

**Comment by jklymak** [comment]
@dbrnz is this still active?

**Comment by OceanWolf** [comment]
If this still exist as active... (and yay for resurrecting 4255)

I have just had a very cursory glance, and the one thing that jumps out at me lies in the bringing of backend classes into the "frontend", both the import .  This seems very wrong to me, and will most likely end up with problems later.

**Comment by dbrnz** [comment]
@jklymak I was looking for ways to generate animated SVG from Python, discovered PR #4255 and rebased it, hence this PR. I've done no work on it since as we decided that animation via matplotlib wouldn't be the best way to go (instead most of the work is done in Javascript, with Python generating some of the JS and inserting it into an existing SVG diagram).

And I agree with @OceanWolf that the backend classes shouldn't be in the frontend...

**Comment by jklymak** [comment]
OK, I'll close for lack of interest.  The PR is here if anyone wants to pick it up...  Thanks!

**Comment by OceanWolf** [comment]
@dbrnz Ahh, where did that discussion take place?  Was that on the devel email list?

**Comment by dbrnz** [comment]
@OceanWolf, my apologies if you are confused. By `we` I meant myself and others involved with developing our code, not a group of matplotlib developers...

**Pull request closed without merging**
