### PR TITLE
cleared test_barbs[png] 

### PR DESCRIPTION
**Pull request by jaideep-seth**
## PR Checklist

- [x] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jaideep-seth** [comment]
#11526

**Comment by jaideep-seth** [comment]
No worries ill move onto another!

**Comment by anntzer** [comment]
Closing per decision in #11526.

**Comment by QuLogic** [comment]
Are we good to close now?

**Comment by jaideep-seth** [comment]
Thank you guys!!

**Comment by tacaswell** [comment]
@jaideep-seth Thank you for your work on this (even though it did not get merged).  Hopefully we will hear from you again!

**Pull request closed without merging**
