### PR TITLE
Document that axes unsharing is impossible.

### PR DESCRIPTION
**Pull request by anntzer**
The feature may perhaps be desirable, but let's document the current state of things.

See https://github.com/matplotlib/matplotlib/issues/28345#issuecomment-2153389095.

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rdg-netra** [comment]
Thanks for the quick PR.

Just curious, should this note also apply to Axes3D.sharez ?

From a quick look, perhaps not. The documentation says sharez can only be used once, so I guess maybe there is a different / simpler sharing mechanism for z? This doesn't effect me, just though I would mention it.

**Comment by tacaswell** [comment]
I expect that this will apply to `sharez` as well (as if we do not use the same sharing mechanism we should!).

**Comment by anntzer** [comment]
Sure, documented the limitation for sharez too.

**Comment by scottshambaugh** [comment]
Axes3D shareview as well.

**Review by scottshambaugh — APPROVED** [review]

**Comment by scottshambaugh** [comment]
That's all the sharing that's done, merging with the single review for a low-impact docs change.

**Pull request merged**
