### PR TITLE
Improved contributing.rst

### PR DESCRIPTION
**Pull request by abhinavsagar**

### CODE REVIEW

**Comment by QuLogic** [comment]
I'm :-1: on suggesting the shortcut by default without any explanation, and not sure about with an explanation either.

**Comment by abhinavsagar** [comment]
Commit messages should be helpful right.

**Comment by QuLogic** [comment]
Yes? There's no way to create a commit without a message (other than going through some hoops.)

**Comment by jklymak** [comment]
What @QuLogic is saying is that `git commit` will usually pop up an editor, whereas `git commit  -m "Short description"` will not, and that he'd prefer we didn't advertise the shortcut.

**Comment by abhinavsagar** [comment]
Got it. Closing this.

**Pull request closed without merging**
