### PR TITLE
Rotate errorbar caps in polar plots

### PR DESCRIPTION
**Pull request by dstansby**
## PR Summary
Fixes https://github.com/matplotlib/matplotlib/issues/441 (what prize do I get for a three figure issue 😄?). Here's an example:
Figure_1

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by anntzer** [comment]
To decrease the image diff I think it's good enough just add a separate test just checking png (as we don't expect to have anything that's backend-dependent here) and leave test_errorbar as it was initially?

Otherwise looks good to me.

**Comment by dstansby** [comment]
> To decrease the image diff I think it's good enough just add a separate test just checking png (as we don't expect to have anything that's backend-dependent here) and leave test_errorbar as it was initially?

👍 - I thought it was better to modify or add to an existing image than create a new one, but I guess that's not the case?

**Comment by dstansby** [comment]
Ah right, I get your point about just adding a new .png test instead of changing all three images 👍

**Comment by anntzer** [comment]
Thanks.
Now that the figure is bigger, it appears that the caps for theta-errorbars are drawn radially *at the position of the cap*, but perhaps it would make more sense to draw them to always be perpendicular to the errorbar instead?  (radial caps would make sense if we drew the theta errorbars as circular arcs, but that's not the case currently)
(I *guess* it's "mostly" a matter of storing somewhere the info so that when you apply the rotation to the cap, you know where the center is.)

**Comment by deep-jkl** [comment]
Hi, would you kindly consider changes in #20914 ? It will allow you specify transform during construction and not by overwriting _transform afterwards. However, it is not reviewed and I don’t know if it is  a good practice to chain PRs.

**Comment by dstansby** [comment]
Thanks for bringing that up - I've had a look at that PR, and will re-base this one if/when #20914 is merged.

**Comment by jklymak** [comment]
I'll mark draft until #20914 gets in...

**Comment by timhoffm** [comment]
#20914 is in. Ping @dstansby ready for rebase.

**Comment by tacaswell** [comment]
This PR is affected by a re-writing of our history to remove a large number of accidentally committed files [see discourse](https://discourse.matplotlib.org/t/minor-re-writing-of-history-and-moving-from-master-to-main-for-default-branch/22354/6) for details.

To recover this PR it will need be rebased onto the new default branch (main).  There are several ways to accomplish this, but we recommend (assuming that you call the matplotlib/matplotlib remote `"upstream"`

```bash
git remote update
git checkout main
git merge --ff-only upstream/main
git checkout YOUR_BRANCH
git rebase --onto=main upstream/old_master
# git rebase -i main # if you prefer
git push --force-with-lease   # assuming you are tracking your branch
```

If you do not feel comfortable doing this or need any help please reach out to any of the Matplotlib developers.  We can either help you with the process or do it for you.

Thank you for your contributions to Matplotlib and sorry for the inconvenience.

**Comment by dstansby** [comment]
I'm going to close this, as I'm not enjoying trying to get my head round the logic in `errorbar` at the moment. I'll leave the branch though if anyone wants to pick this up and address https://github.com/matplotlib/matplotlib/pull/21006#issuecomment-918150335.

**Pull request closed without merging**
