### PR TITLE
API: remove agg path chunking logic

### LINKED ISSUE #4404: Automatically setting agg.path.chunksize?
I just realized that agg backends can throw an OverflowError when dealing with large datasets (in `draw_path`, `self._renderer.draw_path` throws OverflowError).  I wonder if it would be a good idea to automatically set `nmax` (i.e., the `agg.path.chunksize` config param) to a larger value and retry the plot.

### PR DESCRIPTION
**Pull request by tacaswell**
Removes experimental feature added in 2008 and never enabled by
default.

Closes #4404 

attn @efiring

### CODE REVIEW

**Comment by efiring** [comment]
Good catch--I forgot all about this.  Path simplification doesn't supersede this, however.  It can still make the difference between being able make a plot, and not.  Here is an example:
```python
import numpy as np
import matplotlib.pyplot as plt
xx = np.random.randn(1000000)
yy = np.ma.array(xx)
yy[::3] = np.ma.masked
plt.plot(yy)  # fails
plt.rcParams['agg.path.chunksize'] = 20000
plt.plot(yy) # succeeds
```
Maybe the thing to do, in the interest of simplification, is to remove the rcParam and hardwire a suitable chunksize. @mdboom, is there a better way of avoiding the agg limitation?

**Comment by tacaswell** [comment]
Ah, sorry I misunderstood your comment.

**Comment by mdboom** [comment]
@efiring: No -- unfortunately, the limit is a compile-time constant in Agg.

**Comment by QuLogic** [comment]
There's a test case for the chunking in #8176, so it does seem to work; is its non-use the only reason for removing it?

**Pull request closed without merging**
