### PR TITLE
DOC: Fix small typos in 'eventplot' docstring

### PR DESCRIPTION
**Pull request by afvincent**
Summary: `'horizonal'` <- `'horizontal'` and make a quote symbol consistent with the other ones of the docstring.

The whole docstring would definitely need some love (i.e. a significant overhaul), but this may be done later in another PR. Especially if one wants to avoid conflict with changes that may be done in #7602.

### CODE REVIEW

**Comment by afvincent** [comment]
Huh, a Travis failure that I never encountered before ^^ :
```
raise IOError(msg % style)

E                   OSError: 'https://gist.github.com/adrn/6590261/raw' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.
```
It does not seem related to this PR (but rather to an unavailable style file), does it?

**Comment by anntzer** [comment]
Thanks.

**Comment by anntzer** [comment]
I guess test failure was due to temporary impossibility of retrieving a style file online.

**Comment by tacaswell** [comment]
backported to v2.0.x as 9c0332bb3

**Pull request merged**
