### PR TITLE
[DOC]: added parent link for `FuncAnimation` and `ArtistAnimation`

### PR DESCRIPTION
**Pull request by kwsp**
## PR Summary

https://github.com/matplotlib/matplotlib/issues/24150#issuecomment-1279589581

## PR Checklist

**Tests and Styling**
- [ ] ~~Has pytest style unit tests (and `pytest` passes).~~ **No code changes**
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] ~~New features are documented, with examples if plot related.~~
- [ ] ~~New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).~~
- [ ] ~~API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).~~
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by kwsp** [comment]
I'm currently having trouble building matplotlib on my machine, and so I cannot build the docs that reflect the changes I made.

https://github.com/matplotlib/matplotlib/issues/24168

**Comment by oscargus** [comment]
Closing and reopening to retrigger docs build. (PR looks OK, not sure what causes the CircleCI error. Happens sometimes.)

**Review by oscargus — APPROVED** [review]
Not sure why the doc build directly fails. Looks good though! 

(I think the description is better than before, even if we provides inherited members.)

**Comment by oscargus** [comment]
I'll merge this as I do not understand what causes the completely failed doc-build...

Thanks @kwsp and congratulations on your first merged PR in Matplotlib! Hope to see your around!

**Comment by kwsp** [comment]
@oscargus thanks!

**Pull request merged**
