### PR TITLE
Remove references to MATLAB trademark.

### PR DESCRIPTION
**Pull request by anntzer**
They are not necessary, see e.g.
https://academia.stackexchange.com/questions/21521/is-it-mandatory-to-include-the-registered-trademark-symbol-next-to-the-name-of/61852#61852

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by story645** [comment]
Which style guide does the Matplotlib doc technically use? I'm thinking IEEE or ACM technically, but don't have time right now to check their guidelines.

**Comment by anntzer** [comment]
I don't think this was ever discussed.

**Comment by jklymak** [comment]
I'm not a lawyer, but would tend to leave these in.  The stackoverflow makes it clear that commerical entities should refer to each other with TM in the text.  We aren't disinterested academics citing Matlab; its kind of a competitor.  So I'd err on the side of caution.

**Comment by anntzer** [comment]
Frankly, I haven't been able to find a single reference indicating that the trademark sign is required by anyone but the company owning the trademark (whereas there are references indicating that it is not necessary, e.g. CMOS or a large number of legal websites (just google for it)).
I also don't think that *deleting* lines really qualifies as churn...

OTOH I'm not going to throw a tantrum if this gets closed either :)

**Comment by jklymak** [comment]
https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/support/books/members/pdfs/Trademark_Logo_Guidelines.pdf

**Comment by anntzer** [comment]
You win :)

**Pull request closed without merging**
