### PR TITLE
[MRG+1] Remove a dead code (`font_manager.ttfdict_fnames`)

### PR DESCRIPTION
**Pull request by kshramt**

### CODE REVIEW

**Comment by QuLogic** [comment]
It appears you may have not set your git config email correctly; perhaps you wish it to be private, but I suggest using GitHub's [email alias instead](https://help.github.com/articles/keeping-your-email-address-private/) because then it will be a bit more unique.

**Comment by kshramt** [comment]
Thank you for letting me know.
Following your instruction, I set Github's email alias.

**Comment by kshramt** [comment]
I am not sure if the Travis failure is related to this change.

**Comment by NelleV** [comment]
Even if the code is not used internally, it may be used elsewhere. We cannot remove a function without a proper deprecation warning. Can you add the function back, and deprecate it?

**Comment by kshramt** [comment]
@NelleV Thank you for the comment.
I force pushed the fix.

**Comment by QuLogic** [comment]
Another side bar: The private address uses `users.noreply.github.com`, not `github.noreply.github.com`.

**Comment by kshramt** [comment]
Thanks, I fixed the address.

**Comment by anntzer** [comment]
@QuLogic Out of curiosity, where can you see the committer email from the github interface?

**Comment by QuLogic** [comment]
@anntzer I don't, but there's a hint from the profile image next to the commit. It's the generic 'unknown author/committer' instead of @kshramt's. You have to fetch the pull commits to see the actual email.

**Comment by anntzer** [comment]
Thanks.
LGTM.

**Comment by NelleV** [comment]
Thanks @kshramt !

**Pull request merged**
