### PR TITLE
API: Remove deprecated axes kwargs collision detection

### LINKED ISSUE #18832: MNT: Remove AxesStack and deprecated behavior of reuse of existing axes with same arguments
### Describe the issue

**Summary**

In Matplotlib 2.1, the behavior of reusing existing axes when created with the same arguments was deprecated (see #9037). The request is to finally remove this behavior.

My immediate motivation is that I have a [collection of projection classes](https://git.ligo.org/lscsoft/ligo.skymap/-/blob/master/ligo/skymap/plot/allsky.py) that take as a keyword argument an instance of [astropy.coordinates.SkyCoord](https://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html#astropy.coordinates.SkyCoord), which [as of Astropy 4.1 are no longer hashable](https://docs.astropy.org/en/stable/whatsnew/4.1.html#whatsnew-4-1-inplace-skycoord) (see also astropy/astropy#9857). This unexpectedly broke my code because I had not realized that projection keyword arguments had to be hashable.

### Proposed fix

Remove the AxesStack class, remove the `Figure._make_key` method, and update the documentation to reflect the removal of the old deprecated behavior.

### PR DESCRIPTION
**Pull request by lpsinger**
## PR Summary

In Matplotlib 2.1, the behavior of reusing existing axes when created with the same arguments was deprecated (see #9037). This behavior is now removed.

Functions that create new axes (`axes`, `add_axes`, `subplot`, etc.) will now always create new axes, regardless of whether the kwargs passed to them match already existing axes.

Passing kwargs to `gca` is deprecated. If `gca` is called with kwargs that do not match the current axes, then an exception is raised.

Fixes #18832.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by lpsinger** [comment]
The Travis failure seems to be unrelated.

**Comment by tacaswell** [comment]
Well, it looks like the changes to the OSS version of travis have finally caught up with us, safe to ignore that.

**Review by tacaswell — APPROVED** [review]
I am still a bit worried about this as changing how how axes are created seems like it should get extra consideration, however this has been warning from 2.1 which is more than fair warning.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/issues/12513 for other discussion.

**Comment by tacaswell** [comment]
Consusensus on the call was that we can not break

```python
plt.subplot(222)
plt.subplot(222)
```

because as much as we think this is a bad idea (and holding onto the returned Axes object leads to significantly better code) there is no other way to "get back to" a previous axes using just the pyplot API.   The logic for this re-use should fully live in `pyplot.subplot` and only check the subplot spec and warn if any kwargs are passed.  The information we need to sort out if the given Axes exists in the Figure already exists on the Axes objects so we don't need to add any new state (just walk state we already have).

**Comment by jklymak** [comment]
I've not looked at all the changes here carefully, but can try to do so.  However, as discussed on the weekly call, we need to make sure 
```
ax0 = plt.subplot(2, 1, 1)
plt.subplot(2, 1, 2)
ax1 = subplot(2, 1, 1)
assert ax0 == ax1
```
still works, preferably without warning....

We did discuss the extra arguments case and decided that 

```
ax0 = plt.subplot(2, 1, 1, polar=True)
plt.subplot(2, 1, 2)
ax1 = subplot(2, 1, 1, polar=False)   #  Warns about ignored kwargs
assert ax0 == ax1    # pass
ax2 = subplot(2, 1, 1, polar=True)   #  Warns about ignored kwargs
assert ax0 == ax2    # pass
```
should both warn that the second and third call has kwargs that are being ignored, rather than trying to check if the kwargs match the creation they should just be ignored.  This precludes users from getting two axes over one another using pure pyplot, but they can still do this via non-pyplot:
```python
ax0 = fig.add_subplot(2, 1, 1, polar=True)
ax1 = fig.add_subplot(2, 1, 1, polar=False)   # creates a *second* cartesian axes
```
Note that in that case, `plt.subplot(2, 1, 1)` will be somewhat ill-defined, in that it will return the first axes added.  

Ping @tacaswell, @anntzer, @timhoffm in case I got any of that incorrect.

**Comment by lpsinger** [comment]
@tacaswell, @jklymak, I've attempted to implement that behavior, but I am getting some unit test failures related to twin axes, and I'm a bit stuck. Would you take a look, please?

**Comment by lpsinger** [comment]
I now understand the problem with twin axes. The method `matplotlib.axes._subplots.SubplotBase._make_twin_axes` calls `matplotlib.figure.Figure.add_subplot`, which in my implementation is still doing the key lookup.

To avoid this issue, is it OK if the logic for reusing an existing subplot lives _only_ in `matplotlib.pyplot.subplot`, and not in its object-oriented sibling `matplotlib.figure.Figure.add_subplot`?

**Comment by QuLogic** [comment]
I think this PR was replaced by #19153.

**Pull request closed without merging**
