### PR TITLE
[MRG+1] Tripcolor.py: Remove documentation rendering error

### PR DESCRIPTION
**Pull request by rishikksh20**
This commit remove formatting issue in Tripcolor function documentation.

Fixes https://github.com/matplotlib/matplotlib/issues/7803

### CODE REVIEW

**Comment by NelleV** [comment]
Thanks for the patch @rishikksh20 
This indeed fixes the problem in sphinx, but unfortunately, it also makes reading the docstring in a terminal much harder…

I am :+1: for the patch, but I'd like to rediscuss docstring writing with matplotlib core dev (attn @tacaswell ).

**Comment by anntzer** [comment]
The single backslash would likely be a deprecation warning in 3.6, should be \\.
Anyways, I would just rst'ify the paragraph instead (` ``facecolors=C`` instead of just ``C``. `)

**Comment by NelleV** [comment]
I would remove the * and not replace them anywhere. I checked on several opensource projects, and it was seems the mostly widely adopted. But that is out of the scope of this PR.

**Comment by tacaswell** [comment]
I think going to ` ``text`` ` is the best option here (for the reasons given by @NelleV and @anntzer ).

@NelleV not sure this is the best venue for a larger doc-string discussion (as hopefully it will be merged soon :wink: ), but what do you have in mind?

**Comment by anntzer** [comment]
At the very least `\` needs to be replaced by `\\` (3.6 warning).

**Comment by NelleV** [comment]
@tacaswell I just want to make sure I follow Matplotlib's convention if they are any, and draft basic rules if they are none (and maybe mentioned our awesome docathon event :D )

**Comment by rishikksh20** [comment]
@phobson So I have to change only ` *facecolors*\=C`  to  `facecolors=C`  that's it not `*C*` in doc-string.

**Comment by phobson** [comment]
I would prefer the suggestion from @anntzer (double backticks throughout):
 
    ``facecolors=C`` instead of just ``C``

**Comment by NelleV** [comment]
Thanks @rishikksh20 !

**Pull request merged**
