### PR TITLE
Create error surface gradient descent plot example

### PR DESCRIPTION
**Pull request by vitorglemos**
This example shows how to plot an error surface for the descending gradient using matplotlib.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks for the PR!

We have lots of examples, so we have to be a bit finicky about what we include.  I wouldn't call this a statistics plot per-se; the statistics are all pre-plot, and frankly they are a little mysterious (don't worry I understand the underlying method, but I'm not sure how I'd understand it from this example).  After that, I'm not sure it offers anything unique from the other 3-D plots already in the examples?

**Comment by vitorglemos** [comment]
> Thanks for the PR!
> 
> We have lots of examples, so we have to be a bit finicky about what we include. I wouldn't call this a statistics plot per-se; the statistics are all pre-plot, and frankly they are a little mysterious (don't worry I understand the underlying method, but I'm not sure how I'd understand it from this example). After that, I'm not sure it offers anything unique from the other 3-D plots already in the examples?

Hello, you are right about that! Thanks for answering me!

**Comment by jklymak** [comment]
@vitorglemos Did you think this was unique enough to be in the gallery?  Or did you just think this was useful, and wanted to share?  Thanks!

**Comment by vitorglemos** [comment]
> @vitorglemos Did you think this was unique enough to be in the gallery? Or did you just think this was useful, and wanted to share? Thanks!

I thought the example could be useful for the statistics examples, but maybe there is something similar in another example folder.

**Comment by story645** [comment]
Would you be interested in turning this into a post for our blog? With a little more discussion about gradient descents and also plotting?

**Comment by vitorglemos** [comment]
> Would you be interested in turning this into a post for our blog? With a little more discussion about gradient descents and also plotting?

@story645 Of course, I have some more detailed examples and discussions about gradient descent in practice.

**Comment by story645** [comment]
Awesome! 🤩 Contributing guide is at https://matplotlib.org/matplotblog/posts/how-to-contribute/

**Comment by jklymak** [comment]
OK, I'll close this here.  Thanks @vitorglemos

**Pull request closed without merging**
