### PR TITLE
add matplotlib.__bibtex__ attribute

### PR DESCRIPTION
**Pull request by Tafkas**
Added a bibtex attribute for quick command-line access to the recommended citation info. Idea by @jakevdp: https://twitter.com/jakevdp/status/524329573580697600

### CODE REVIEW

**Comment by Tafkas** [comment]
networkx/networkx#1271 has been merged. How should we proceed here? Merge it too? Or just close the PR?

**Comment by WeatherGod** [comment]
This needs a rebase. Probably should get it in for v1.5?

**Comment by tacaswell** [comment]
The community level discussion is still outstanding (as far as I know) and if iirc got bogged down in trying to include output for every conceivable bibliographic manager.

I am just going to merge this to master locally as a) it is better than nothing b) bibtex is the only format we currently provide on the website

**Comment by tacaswell** [comment]
Closing as #6204 has been merged.

**Pull request closed without merging**
