### PR TITLE
FIX: inset-axes not having proper transform

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This should fix the issue noted in https://github.com/matplotlib/matplotlib/pull/10756#issuecomment-377818550 where #10756 didn't quite do the right thing.  I went a step further and said bbox_to_anchor should always be a four-tuple.  See #8952.  

Fixes the reversion in 2.2.2 so that this didn't work: 

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
xdata, ydata = np.arange(8), np.arange(8)

plt.figure(figsize=(6,3))
ax = plt.subplot(111)
ax.plot(xdata, ydata)
axins = inset_axes(ax, width=0.2, height=0.2, loc='upper left')
```

Now works, tests pass, and examples look right.  It may break other people's perceived ideas of what these functions are supposed to do.  If so, please do report the issue, but in my mind the old state of things was pretty unclear.

### CODE REVIEW

**Comment by jklymak** [comment]
ping @ImportanceOfBeingErnest

**Comment by jklymak** [comment]
OK< I think this fixes the issue.  OTOH, I still don't really understand what `bbox_to_anchor` or `bbox_transform` really mean, what units they are in etc.  This is all pretty poorly documented and the code non-trivial to trace through.  

I still think this functionality could/should be moved to the base axes class at some point.

**Comment by jklymak** [comment]
@ImportanceOfBeingErnest  Do you understand what `inset_axes(ax1, width=.7, height=.7,bbox_to_anchor=(100,100))` means?  I don't see where pixels is specified as the default transform, and so far as I can tell the above doesn't work at all (either with this change or without).  But maybe I am completely not understanding `inset_axes`.  

My real proposed fix to this is #11005, where we do this all properly, includding proper documentation.

OTOH, if you have a different PR to fix this, I'm not going to be offended if you push an alternate fix.  i *really* don't understand what `bbox_to_anchor` is supposed to mean in `inset_axes`.

**Comment by ImportanceOfBeingErnest** [comment]
It may indeed be useful to get proper `inset_axes` to the normal `matplotlib.axes`! They could work differently then the ones from axes_grid1 and hence be more understandable.  
I would probably not change those from the `axes_grid1`. They are there for some reason and people have been using them.  

<hr>

`inset_axes(ax1, width=.7, height=.7,bbox_to_anchor=(100,100))` used to work; it is actually working on 2.2.2. But the attempted fix #10756 has broken it. 
This creates an inset axes, which is 0.7 inches wide and high. This is positioned relative to a bounding box of `(100,100, 0,0)` (note, no width, no height, just as usual with legend bbox etc). Since we do not specify any transform here, this is `None` and hence equivalent to `bbox_transform=matplotlib.transforms.IdentityTransform()`. This means it is just the raw pixel coordinates of the final figure.  
The default `loc` is `"upper right"`, so the upper right corner of the axes is aligned to the upper right corner of the bounding box. The bounding box having no extention, this means that the upper right corner of the axes is at pixel position (100,100).  
This is not quite the case, because of the default `borderpad = 0.5`. This means that there is an offset of 

    borderpad*fontsize [points] = borderpad*fontsize * dpi / 72 ppi = 0.5*10*100/72 = 6.9 [pixels]

for the default `dpi=100` and `fontsize=10`. And this is indeed what we observe in the final generated plot. (Again, for pdf it's different, because that seems to ignore dpi setting.)

Now it's clear that specifying a bounding box like that is usually not desirable.
In principle the `inset_axes` can take all arguments needed to specify more useful scenarios.  
The main problem I see is that the relative width and height are specified in a rather unusual way (e.g. `"100%"`) compared to other matplotlib specs. 

I still think it's best to revert back to this old behaviour and update the documentation. This would at least make sure not get a non-working version out. I could provide a PR if desired. One problem seems that the documentation of axis_grid1 is somehow non-existent (c.f. #9582). So any update to it might not help anyone.

**Comment by ImportanceOfBeingErnest** [comment]
Just leave it as it is and I will come with a consistent PR tomorrow or so. This PR would

* delete the two lines that have been introduced and break things now.
* Add warnings for the cases which are truely non-sensical
* update the documentation about it.

**Comment by jklymak** [comment]
OK, thats great.  Thanks a lot!

**Comment by ImportanceOfBeingErnest** [comment]
The point of the example in #8120 is indeed that if you specify something in pixels, the output will be in pixels. If you then change dpi (which is done deliberatly for png, and unintentionally for pdf due to some other strange thing with pdf dpi), you will get seemingly arbitrary output - but they are all consistent.

I suppose this is undesired in almost all cases, but who knows... why not position something in pixels? One definitely has to tell users about this in the docs, that's clear.

**Comment by jklymak** [comment]
Not saying pixels shouldn't be an option, but its a strange default for an inset axes.

**Pull request closed without merging**
