### PR TITLE
ticker.LinearLocator view_limits algorithm improvement closes #6142

### LINKED ISSUE #6142: matplotlib.ticker.LinearLocator view_limits algorithm improvement?
Inspecting the code of matplotlib.ticker.LinearLocator
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1161

you can see that the view limits are chosen such that the difference between vmin and vmax is an interger multiple of scale, which is itself a power of 10. Therefore, the range  will be nicely divisible when divided by 10 (11 tickmarks).
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1213

Therefore, the view_limits function determines the limits assuming there are 11 ticks. This assumption is implicit in two lines:
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1224
https://github.com/matplotlib/matplotlib/blob/7d1a7c2e4637efba239ad3b984928c0175d45f98/lib/matplotlib/ticker.py#L1227

Code is repeated here:

```
exponent, remainder = divmod(math.log10(vmax - vmin), 1)
if remainder < 0.5:
    exponent -= 1
scale = 10 ** (-exponent)
vmin = math.floor(scale * vmin) / scale
vmax = math.ceil(scale * vmax) / scale
```

Since we know the number of ticks, from `self.num_ticks`, we can generalize the current algorithm to be better suited for any number of ticks. Suggested generalized algorithm:

```
exponent, remainder = divmod(math.log10(vmax - vmin), math.log10(self.num_ticks-1))
if remainder < 0.5:
    exponent -= 1
scale = (self.num_ticks-1) ** (-exponent)
vmin = math.floor(scale * vmin) / scale
vmax = math.ceil(scale * vmax) / scale
```

This generalized expression reduces to the current form when `self.num_ticks==11` (which is the current default). For other cases, here is an example:
when num_ticks = 10, vmin = 20, vmax=90
Current algorithm returns vmin = 20, vmax=90, corresponding to ticks spaced by 7.77778.

The proposed algorithm returns vmin = 18, vmax = 90, corresponding to ticks spaced by 8.

Is this something worth doing? The patch is trivial -- just changing two lines of code. I can turn this in to a pull request to illustrate if it is helpful.

### PR DESCRIPTION
**Pull request by maqifrnswa**

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @mdboom 

The conditions where this applies are a) if `rcParams['axes.autolimit_mode'] == 'round_numbers` which was added as a back-compatibility mode in 2.0 and b) the number of ticks in the locator `!= 11`. 

This is technically an API break, but could be convinced this is enough of a corner case / no one really wants the old behavior to let it slide.

@maqifrnswa Can you add some before/after example of what this looks like?

**Comment by tacaswell** [comment]
How did you end up using `LinearLocator`?  We have (for the most part) deprecated the use of this locator internally in favor of `MaxNLocator` which tries to pick both nice limits _and_ a nice number of ticks which helps to alleviate some of these issues.

I played with this a bit and could not see that this was clearly better than the current behavior.

Pushing this off to 2.1 as it is not a blocking issue for 2.0.

Can you provide some before/after examples and add a note to the `api_changes` folder?

**Comment by maqifrnswa** [comment]
The use case is for lining up the grid lines of a plot with two y-axis. When you are using ```twinx()``` and want to show gridlines, and you want the exact same number of ticks on both y-axes so the grids of each properly line up. ```MaxNLocator``` does not guarantee the exact number of ticks on each axis, so you have to use ```LinearLocator```. It might be good to add a note in the ```twinx``` documentation to let people know about ```LinearLocator```. I can put together notes to ```api_changes``` and some text in twinx making users aware of this change so they don't have to resort to hacks (which is what is done in the reference's below):

References with example figures:
http://stackoverflow.com/questions/26752464/matplotlib-two-y-axis-scales-how-to-align-gridlines/35904761#35904761

http://stackoverflow.com/questions/20243683/matplotlib-align-twinx-tick-marks

**Comment by tacaswell** [comment]
Ah, that use case is compelling.

Can you give any examples of data ranges where this makes a big difference?

This needs a rebase at any rate.

**Comment by maqifrnswa** [comment]
Do you think twinx plots should default to this proposed linearlocator?

To show examples of data ranges where this makes a difference, here's a script to generate lists of tick locations versus numticks and data size:
https://gist.github.com/maqifrnswa/5d23546f9314f15cd39c228101eadf1c

Here is for sample ranges of 20-90 and numticks from 3 to 11
The biggest changes in this example are for numticks >11 and for numticks = 10, 9, 7, and 4.

numticks: 12, data min: 20, data max: 90
Current:
[ 20.          26.36363636  32.72727273  39.09090909  45.45454545
  51.81818182  58.18181818  64.54545455  70.90909091  77.27272727
  83.63636364  90.        ]
Proposed:
[ 11.  19.  27.  35.  43.  51.  59.  67.  75.  83.  91.  99.]


numticks: 10, data min: 20, data max: 90
Current:
[ 20.          27.77777778  35.55555556  43.33333333  51.11111111
  58.88888889  66.66666667  74.44444444  82.22222222  90.        ]
Proposed:
[ 18.  26.  34.  42.  50.  58.  66.  74.  82.  90.]


numticks: 9, data min: 20, data max: 90
Current:
[ 20.    28.75  37.5   46.25  55.    63.75  72.5   81.25  90.  ]
Proposed:
[ 16.  26.  36.  46.  56.  66.  76.  86.  96.]


numticks: 8, data min: 20, data max: 90
Current:
[ 20.  30.  40.  50.  60.  70.  80.  90.]
Proposed:
[ 14.  25.  36.  47.  58.  69.  80.  91.]

numticks: 7, data min: 20, data max: 90
Current:
[ 20.          31.66666667  43.33333333  55.          66.66666667
  78.33333333  90.        ]
Proposed:
[ 18.  30.  42.  54.  66.  78.  90.]


numticks: 6, data min: 20, data max: 90
Current:
[ 20.  34.  48.  62.  76.  90.]
Proposed:
[ 20.  34.  48.  62.  76.  90.]


numticks: 5, data min: 20, data max: 90
Current:
[ 20.   37.5  55.   72.5  90. ]
Proposed:
[ 16.  36.  56.  76.  96.]


numticks: 4, data min: 20, data max: 90
Current:
[ 20.          43.33333333  66.66666667  90.        ]
Proposed:
[ 18.  42.  66.  90.]


numticks: 3, data min: 20, data max: 90
Current:
[ 20.  55.  90.]
Proposed:
[  0.  48.  96.]




Finally, no change if you use the current default number of ticks:
numticks: 11, data min: 20, data max: 90
Current:
[ 20.  27.  34.  41.  48.  55.  62.  69.  76.  83.  90.]
Proposed:
[ 20.  27.  34.  41.  48.  55.  62.  69.  76.  83.  90.]

**Comment by efiring** [comment]
On 2016/03/29 10:34 AM, Scott Howard wrote:
> Do you think twinx plots should default to this proposed linearlocator?

I think the way to expose it should be not as a default, but via kwargs 
to select the locator and the target or required number of bins.

**Comment by tacaswell** [comment]
I like it (and even understand the implementation now!).

Given that this is an API break but not strictly a new feature, I think this should be pulled into v2.x.

The choice of `1` vs `min(self.num_ticks-1, 1)` should be controlled by `_internal.classic_mode` kwarg.

**Comment by tacaswell** [comment]
@maqifrnswa Can you do the twinx/twiny changes in a follow up PR?

**Comment by QuLogic** [comment]
> Given that this is an API break but not strictly a new feature, I think this should be pulled into v2.x.

> @tacaswell tacaswell modified the milestone: 2.0 (style change major release), 2.1 (next point release) 4 days ago

I'm a bit confused; one side says 2.0, the other says 2.1.

**Comment by QuLogic** [comment]
Oops, I meant to refer to #6142 there. No backports noted just yet.

**Comment by tacaswell** [comment]
I think this should be back ported to 2.x.

**Comment by QuLogic** [comment]
I don't think this was backported...

**Comment by tacaswell** [comment]
(finally) backported to v2.x as e785afb

**Comment by tacaswell** [comment]
@QuLogic Thanks for keeping track of this!

**Pull request merged**
