### PR TITLE
Make Tk windows use the same icon as other backends 

### PR DESCRIPTION
**Pull request by daniilS**
## PR Summary
This makes the icons look better, and consistent with the other backends. See below for examples on Windows. The only icon that doesn't quite look right is the titlebar icon at 100% scaling. If a 16x16 image is supplied, Windows will preferentially use that, which looks better, but then it will also use it at other scaling factors, making them blurry. I think this is the best the icons can look with the current version of Tk.

| Old | New |
| ---: | :--- |
| 100_icon_old | 100_icon_new |
| 100_taskbar_old | 100_taskbar_new |
| 150_icon_old | 150_icon_new |
| 150_taskbar_old | 150_taskbar_new |

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
It looks like we switch from a gif to a ppm in 2015.  Is the important change here going from ppm -> png or just that the png icon is higher resolution (and has alpha)?

**Comment by daniilS** [comment]
The change is going from ppm to png, as all the other backends use the auto-generated png icons, but Tk had its own file that looks different. I reckon it's best to minimise backend differences, same logic as #18889. Alpha channel support is also an advantage.

**Comment by tacaswell** [comment]
Sorry, my last comment was very confusing 🐑 

I think the real improvement here is to use a better icon (which matches the rest of the backends).  The fact that the old one was ppm and the new one is png is not really relevant (as if they were called `v0.png` and `v1.png` and we had the before / after above we would still want to do this)?

Or is there something about ppm files (that I do not know/understand) that makes the png version of the icon better?

**Comment by daniilS** [comment]
Ah right, I get you. Yes, the change is going from v0 to v1, the change to png is just because that's how the v1 icon is stored and there's no need for the unique ppm file any more now that PIL is a dependency. I'll change the title.

**Review by QuLogic — APPROVED** [review]
I've been meaning to do this since I noticed it.

**Comment by QuLogic** [comment]
Thanks @daniilS! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.

**Comment by daniilS** [comment]
Thanks @QuLogic! I thought the Tk backend could use some love so have been going through all the open "GUI/tk" issues one by one 😅

**Pull request merged**
