### PR TITLE
Remove deprecated methods and attributed in Axes3D

### PR DESCRIPTION
**Pull request by oscargus**
## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by scottshambaugh** [comment]
For my own knowledge, where does the deprecation policy live? I can't find it in the devdocs.

**Review by scottshambaugh — APPROVED** [review]

**Comment by oscargus** [comment]
Not sure... Short version:

Everything user facing. Two minor versions.

**Review by scottshambaugh — CHANGES_REQUESTED** [review]
Lines 946-949 should get cleaned up as well

**Comment by timhoffm** [comment]
> For my own knowledge, where does the deprecation policy live? I can't find it in the devdocs.

https://matplotlib.org/stable/devel/contribute.html#api-changes

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
