### PR TITLE
Add pytest==3.6.0 on requirements/testing/minver.txt

### PR DESCRIPTION
**Pull request by aalocked**
## PR Summary
issue #23154 Added pytest==3.6.0 on requirements/testing/minver.txt
## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/actions/runs/4534266219/jobs/7988219026?pr=25562#step:9:223

Appears to have worked.

**Review by tacaswell — APPROVED** [review]

**Comment by rcomer** [comment]
Looks like we need at least v5.4 if we want to parametrize with integers.
https://docs.pytest.org/en/7.2.x/changelog.html#id229

**Comment by ksunden** [comment]
using `reason` with `importorskip` requires at least v4.1, which explains the `Fail` conditions, but as @rcomer points out, there are other features we use which require v5.4

My vote is to pin the minver to 6.2.0 (patch version negotiable, if there are bugs which are patched in that series) and document as a 2 year support window rather than a specific version

**Comment by aalocked** [comment]
So bumping up the version to 6.2.0 should do it?

**Comment by rcomer** [comment]
I think we just need to find a version that works, and pin to that.  We can update the pin as and when we start using newer pytest functionality.  I don’t think we need a particular support window because this only affects devs, who presumably have a dedicated environment for mpl development that they can update as and when needed.

**Comment by rcomer** [comment]
@aalocked maybe try 6.2.0 and see what happens 🙂

**Comment by tacaswell** [comment]
@aalocked Did you mean to delete your fork of Matplotlib?

**Comment by aalocked** [comment]
Yes, for some reason I had to delete it. I forked it again if that's okay

**Comment by aalocked** [comment]
I created a new pull request for it again. Apologies for the inconvenience. 

https://github.com/matplotlib/matplotlib/pull/25563

**Pull request closed without merging**
