### PR TITLE
set_tick_params(label1On=False) should also make offset text invisible.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

See changelog.
Closes https://github.com/matplotlib/matplotlib/issues/16895, which is likely a better example than anything I could write :-)
(The issue refers to mpl_toolkits, but it's actually present in standard mpl as well.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
Careful. This would remove the offset in case the right or top axis is used for ticking. E.g.

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([1, 1e8])
ax.yaxis.tick_right()
plt.show()
```

would result in the offset missing.

**Comment by anntzer** [comment]
fair enough, I decided to be a bit more generous and keep the offset text visible if either the left or the right labels are visible.

**Comment by QuLogic** [comment]
Add a test for the new case?

**Comment by anntzer** [comment]
sure, done

**Pull request merged**
