### PR TITLE
Backport #4335 to master

### PR DESCRIPTION
**Pull request by mdboom**
Done as a pull request to give it some Travis testing first.

### CODE REVIEW

**Comment by tacaswell** [comment]
I am now confused if we want to put this in for 1.5 or 2.0

**Comment by mdboom** [comment]
Well, I guess strictly speaking it's an API / behavior change.  It's already on color_overhaul.  Let me know where else you think it should go.

**Comment by WeatherGod** [comment]
If it is on color overhaul, then it should be on 1.5. There should be
little, if any, code difference between 1.5 and 2.0.

**Comment by jenshnielsen** [comment]
Im :+1:  on getting it into 1.5 for the same reasons as @WeatherGod

**Comment by tacaswell** [comment]
Going with this is a bug fix and merging in for 1.5

**Pull request merged**
