### PR TITLE
created new branch and added _traits directory with artist.py and tra…

### PR DESCRIPTION
**Pull request by katierose1029**
…its.py

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/whats_new.rst if major new feature
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
@katierose1029 I re-targetted this at traitlets.

**Comment by katierose1029** [comment]
@tacaswell Thank you!

**Comment by tacaswell** [comment]
It looks like `_traits` is not being picked up by `setup.py`

**Comment by katierose1029** [comment]
@rmorshea here is the PR

**Comment by WeatherGod** [comment]
There are a lot of doc fixes here that would be great to have in master now for the 2.1 release. Any chance those commits could get split off into a separate pull request?

**Comment by katierose1029** [comment]
@WeatherGod I didn't see this comment until now. Is there a way to separate those commits into a separate pull req? Which ones if I may ask ?

**Comment by WeatherGod** [comment]
You can cherry-pick commits onto a new branch and make a merge request out of that.

However, looking back on your commit list, I see that a lot of the early commits are actually merges from other branches that were already merged into master, I think? So, perhaps you should be rebasing this branch on master so that those changes don't show up?

**Pull request closed without merging**
