### PR TITLE
added layout="compressed" for pyplot #25223

### PR DESCRIPTION
**Pull request by RishabhSpark**
## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by jklymak — COMMENTED** [review]
The new line is still too long (89>88).

**Comment by RishabhSpark** [comment]
> The new line is still too long (89>88).

Hi, sorry but I'm new to open source and matplotlib, can you help me out with the error please? :D

**Comment by rcomer** [comment]
Here is an example where the type descriptions are continued on the next line to keep within the line length limit:

https://github.com/matplotlib/matplotlib/blob/2b05ace97f5d5f47acb1be09731178413af76207/lib/matplotlib/offsetbox.py#L1257-L1258

**Review by rcomer — APPROVED** [review]

**Comment by rcomer** [comment]
Thanks @RishabhSpark!

**Pull request merged**
