### PR TITLE
Fix #4487: Take hist bins from rcParam

### LINKED ISSUE #4487: Should default hist() bins be changed in 2.0?
I would advocate changing the default histogram bins to a data-adaptive choice in 2.0. For an example of how this might look, see info on the recently-merged astropy ``hist()`` function: http://astropy.readthedocs.org/en/latest/visualization/histogram.html#normal-reference-rules

Using the freedman-diaconis rule as the default would be a useful change, IMO (though it would require some modification in the case of weighted samples)

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by tacaswell** [comment]
bah, merged this then noticed it was lacking whats_new entry.

**Comment by tacaswell** [comment]
backported to v2.0.x as ac7bba90d770c0b712107e85ae5939ac71cf765d

**Comment by WeatherGod** [comment]
And missing an entry in the classic style?

**Comment by tacaswell** [comment]
@WeatherGod Yes, that too.  Sorry, too quick on the trigger here.

**Comment by mdboom** [comment]
Sorry about that.

**Pull request merged**
