### PR TITLE
Fix polar() regression on second call failure

### PR DESCRIPTION
**Pull request by beckja**
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by beckja** [comment]
This is a fix for PR #21113

**Review by timhoffm — APPROVED** [review]

**Comment by tacaswell** [comment]
@beckja Do you feel up to adding a test for this?

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Thanks @beckja !  I hope you do not mind, I took the liberty of pushing a slight modification to your test to use unpacking syntax (to make sure that only one thing is returned and to make the rest of the rest read a bit better).

Given that I pushed a commit to this PR I probably should not merge it.

**Comment by beckja** [comment]
@tacaswell appreciate the clean-up.  This is my first pull request on any open source project, so grateful for the help.

**Comment by tacaswell** [comment]
@beckja You identified a problem, proposed a fix, added a test, and look on track to get merged with only very minor revisions, so you are doing pretty good for your first PR!

**Review by jklymak — APPROVED** [review]

**Comment by tacaswell** [comment]
Congratulation @beckja on your first Matplotlib PR 🎉 !

Hopefully we will hear from you again.

**Pull request merged**
