### PR TITLE
renaming duplicated file names

### PR DESCRIPTION
**Pull request by choldgraf**
## PR Summary
This renames a few examples/tutorials that have duplicated filenames in matplotlib. Partially since it's best-practice, but also because whenever sphinx-gallery releases a new version we'll be able to include Binder links in all the examples and it'll throw a warning if we have duplicated examples/tutorials names.

### CODE REVIEW

**Comment by tacaswell** [comment]
You probably need to adjust pytest.ini to skip checking the right examples.

**Comment by choldgraf** [comment]
@tacaswell any idea why this would fail on Circle 2.7 but not on 3.5?

**Comment by QuLogic** [comment]
Because 2.7 runs linkchecker and you've got a broken link somewhere:
```
URL        `_images/sphx_glr_animated_histogram_thumb1.png'
Name       `screenshots'
Parent URL file:///home/circleci/project/doc/build/html/index.html, line 121, col 7
Real URL   file:///home/circleci/project/doc/build/html/_images/sphx_glr_animated_histogram_thumb1.png
Check time 0.002 seconds
Result     Error: URLError: <urlopen error [Errno 2] No such file or directory: '/home/circleci/project/doc/build/html/_images/sphx_glr_animated_histogram_thumb1.png'>
```

**Comment by choldgraf** [comment]
looks like linkchecking is happy now!

**Pull request merged**
