### PR TITLE
DOC: more pcolor fixes

### LINKED ISSUE #16493: Example/tutorials warn due to new pcolormesh shading
The new warning introduced in #16258 is now being triggered by several examples, and the tutorials. At least for the latter, I assume we don't want to go through and just do a blanket `Z[:-1, :-1]`, but instead take a more nuanced approach. Though possibly not; I have not looked at the issues yet, but I don't want to forget about this.

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #16493

Note I've removed a bunch of "user_demo" examples.  I made those back when I made the original tutorials largely because I thought I was supposed to, but I think we want to not duplicate tutorials and examples, so I have removed them.  

From #16493, These remaining files are *meant* to have warnings emitted:

- matplotlib/examples/images_contours_and_fields/pcolormesh_grids.py:66 
- matplotlib/examples/images_contours_and_fields/pcolormesh_levels.py:67

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Perhaps just set the rcParam instead?
Also needs a rebase.

**Comment by jklymak** [comment]
I don't think there is anything wrong with being explicit here, even if we plan to change the default.  I am not a particular fan of rcParams in examples because the user doesn't know what the rcParam value is.

**Comment by QuLogic** [comment]
Unfortunately needs a rebase again.

**Comment by jklymak** [comment]
... rebased

**Pull request merged**
