### PR TITLE
[WIP] Implement a scattertext plot method.

### PR DESCRIPTION
**Pull request by dopplershift**
Adds a TextCollection object that facilitates drawing a bunch of text
with common properties at different locations. scattertext() uses this
to plot text in data coordinates, with an optional offset.

This is a first cut in order to get design feedback. TextCollection inherits only from Text right now, just overriding the draw() method to do multiple calls to draw_text(). The implementation here started with Text.draw(), so there are some things like bbox and PathEffects that are inherited that may or may not make sense.

Questions:
1. How to refactor `Text` so that the hack for `get_layout()` isn't necessary
2. Any reason to also inherit `Collection`
3. Adding colormapping: using `cm.ScalarMappable`? 
4. Interface for `scattertext()`: Should it take an array of data values or an array of strings?

Any other issues?

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: For feature.

There might also be issues with the `_bbox_patch` and it's associated helper functions.

**Comment by dopplershift** [comment]
This should address additional comments raised in #345. I'm not sure if this `TextCollection` has any significant performance benefits (since that's not my driving interest), but #347 may be relevant.

**Comment by tacaswell** [comment]
I am also :+1: on not being worried about performance with this.  

The ability to easily do broadcasting of interesting properties over artists is one of the places that bokeh is well ahead of us.  I wonder if in addition to the `Collection` subclasses (which really are about performance optimizations as all of the broadcast logic lives in their draw methods) it would be worth providing a top-level generic broadcasting function, something like:

```python
def broadcast_magic(ax, Art_cls, **kwargs):
    static_kwargs = dict()
    broadcast_names = []
    max_count = -1
    cycle_values = []
    for k, v in kwargs.items:
        if is_iterable(v) and not is_string(v):
           broadcast_name.append(k)
           cycle_values = cycle(v)
           if len(v) > max_count:
               max_count = len(v)
        else:
            static_kwargs[k] = v
    ret = []
    for count, b_vals in enumerate(zip(cycle_values)):
        if not count <max_count:
            break
        local_kwargs = dict(static_kwargs)
        local_kwargs.update({k: v for k, v in zip(broadcast_names, b_vals)})
        art = Art_cls(**local_kwargs)
        ax.add_artist(art)
        ret.append(art)
    return ret
```

**Comment by OceanWolf** [comment]
If you only need ``TextCollection`` to group properties, then can't we do that with ASS?  As far as I see that should do the same thing but in a much more general way.

**Comment by dopplershift** [comment]
@OceanWolf I'm lost on your acronym, and strangely, googling it isn't helping. :)

**Comment by WeatherGod** [comment]
Artist Style Sheets. It is one of the MEPs.

**Comment by dopplershift** [comment]
It's unclear to me if MEP26 is relevant. I want to easily be able to put a bunch of text on a plot, all with the same style (maybe changing color, but that's all). This facilitates plotting many text values (or even just strings) in data coordinates, often offset from the center location.

This can certainly be accomplished now directly with a `for` loop; this seems inefficient and verbose. `TextCollection` would essentially let `Text` take arrays. As far as I can tell, ASS would simply be a better way to do the `for` loop method.

**Comment by tacaswell** [comment]
This should inherit from `Collection` so that it may be color-mappable and such.

**Comment by jklymak** [comment]
No objections to this being re-opened, but closing because its been 3 years, and I'm not entirely sure what the advantage is over just having a for-loop to add the text (and creating a list of handles if you want to store them for future reference). I imagine most folks who want this are getting by using this method.

**Comment by anntzer** [comment]
It's relevant to #5665 (moving ticks to use LineCollections instead of individual lines would (perhaps) logically move label texts to TextCollections as well).  But I'm fine leaving this closed for now, we can always revisit it later.

**Pull request closed without merging**
