### PR TITLE
Added cursor widget with coordinate text

### PR DESCRIPTION
**Pull request by Joschua-Conrad**
Added a new widget, which is a sub class of the Cursor widget, but displays a text field right next to the cursor showing a tuple of the current mouse x position and the function value y at that x coordinate or vice versa.

An entry in the whats new section and an example was added. There is no unittest yet (the Cursor instance also does not have one).

The behaviour of the cursor class is adapted. The new methods, which overwrite the base class always also call the method of the base class.

Please have a look on especially these two things:
-In widgets.py [1327] the Cursor method onmove() returns, if the cursor is supposedto be invisible. But line 1332 and 1333 therefore will not be reached and cannot make the cursor invisible?
-In the gallery, the cursor is not visible in the picture, because the picture is exported without creating a mouse move event. The example I commit hereby describes the problem with a code example. Does somebody have suggestions?

Please be patient with me ;D

### CODE REVIEW

**Comment by QuLogic** [comment]
Can you add a screenshot of what this actually does?

**Comment by KoenigRigips** [comment]
Screenshot
text_cursor

**Comment by ImportanceOfBeingErnest** [comment]
I find it not very convincing that the coordinate that is shown has nothing to do with the horizontal line of the cursor.

**Comment by KoenigRigips** [comment]
> I find it not very convincing that the coordinate that is shown has nothing to do with the horizontal line of the cursor.

text_cursor

I changed the behaviour such that the horizontal line sticks to the plotted line in  [commit](https://github.com/matplotlib/matplotlib/pull/13933/commits/99d8f7f006b1b205d61ac1f4a68c0bc65cc62838)
I thought the same.

**Comment by jklymak** [comment]
This looks nice, but I'm concerned that its pretty specialized to finding values along a line.  I wonder if this would be better suited to being a (long-ish) example?   If this is meant to be a general tool, I'd be opposed to having the `Line2D` object have anything to do with this.  What do we do if the line is multi valued in `x`?    Given that the cursor location is already given in the display coords on most backends, I'm not sure what the advantage of the new API is....

**Comment by anntzer** [comment]
The version tracking the line is likely better served by mpldatacursor/mplcursors.
I'm not sure about the version not tracking the line, but if it goes in, I doubt it needs to be its own class rather than just an additional kwarg on the Cursor class.

**Comment by KoenigRigips** [comment]
> This looks nice, but I'm concerned that its pretty specialized to finding values along a line. I wonder if this would be better suited to being a (long-ish) example? If this is meant to be a general tool, I'd be opposed to having the `Line2D` object have anything to do with this. What do we do if the line is multi valued in `x`? Given that the cursor location is already given in the display coords on most backends, I'm not sure what the advantage of the new API is....

The advantage is, that the cursor sticks to plotted datapoints and the mouse only 'guides' where to stick. For example: You did a fourier analysis and you only interest for peak values in your spectrum. If you use the mouse and the fact that the cursor position is displayed in the plot window, it's still not intuitive, because you have to move your cursor to the exact peak in order to see its value. With the text cursor, you add one line of code in your script and if you move the mouse next to the peak, the cursor fetches at the exact peak position and you can compare the height of other peaks. So I think it is an intuitive tool for investigating plotted data.

But still, the connection to the Line2D object doesn't look right. It made writing the code easy and there was no necessity for preprocessing the plotted data before finding the value, where the cursor should fetch. np.searchsorted does the job fast. But I could also search for the closest datapoint next to the mouse pointer by searching in all data tuples plotted in the axis, no matter on which line they are? I guess I would load all plotted data vectors when the cursor is constructed, align and sort them and then continue using np.searchorted when the onmove() event becomes active? Would that be a solution for you?

And an example instead of the widget class would anyway contain the new subclass TextCursor, because the subclass is a good way to pair all the event processing of cursor and text. And I thought the idea would be much more used, if the class is already part of the matplotlib.

**Comment by KoenigRigips** [comment]
> The version tracking the line is likely better served by mpldatacursor/mplcursors.
> I'm not sure about the version not tracking the line, but if it goes in, I doubt it needs to be its own class rather than just an additional kwarg on the Cursor class.

The existing cursors do not fetch at the data points. You have to move your mouse pointer precisely on the plotted line. This is bad if somebody asks "what is the precise height of this peak in your plot" and that's why I wrote this widget.

**Comment by raodantam12** [comment]
Looks nice. But normally the user specifies x (by using mouse) and expects only y to show up on the curve. So the horizontal red line is redundant in that sense. So it will be nice if the user has the ability to suppress the horizontal line

**Comment by tacaswell** [comment]
Thank you for working on this @KoenigRigips , I agree that this is a useful feature (for example the charts in https://pypistats.org/packages/matplotlib have this).

On one hand we want Matplotlib to be "batteries included" but on the other, we want to keep the library from growing out of control size wise.  

I think I agree with @anntzer that this functionality is a better fit for mpldatacursor/mplcursors.  The release cycle can be faster so your work can get in peoples hands faster ;)

**Comment by KoenigRigips** [comment]
> Looks nice. But normally the user specifies x (by using mouse) and expects only y to show up on the curve. So the horizontal red line is redundant in that sense. So it will be nice if the user has the ability to suppress the horizontal line

One can suppress the visibility of horizontal/vertical line by using hline/vline parameter of the Cursor baseclass. The coordinate text of e.g. the x coordinate can be suppressed by using an format string, which explicitly selects only one coordinate, e.g. "{1:.2f}".

**Comment by KoenigRigips** [comment]
> Thank you for working on this @KoenigRigips , I agree that this is a useful feature (for example the charts in https://pypistats.org/packages/matplotlib have this).
> 
> On one hand we want Matplotlib to be "batteries included" but on the other, we want to keep the library from growing out of control size wise.
> 
> I think I agree with @anntzer that this functionality is a better fit for mpldatacursor/mplcursors. The release cycle can be faster so your work can get in peoples hands faster ;)

Ok. So I change the code, such that an additional argument to the "Cursor" class activates the display of the text and a second one activates the "stick to the line" functionality. The resulting code should be much shorter, because I have less trouble with the Cursor object blit functionality interfering with. I guess this is what most reviewers want.

**Comment by timhoffm** [comment]
Thanks for working on this, it's a useful feature. However, I don't see it in core Matplotlib currently. First of all, the whole widget system is IMO only a half-baked. It's working, but falls behind in visual appearance, API, usability and features from what I expect from a professional solution. I don't want to add that part of the library because I don't want to increase the API/maintainance burden there.

For now, this would be better placed in mpldatacursor/mplcursors. Alternatively, I would be ok with adding this as an example how to extend `Cursor`.

A technical remark:
When having less points and the mouse moves but the cursor stays on the same data point, the text flickers. To avoid that, you should probably save the current data point and only redraw in `onmove()` if the point changes.

**Comment by jklymak** [comment]
I think the consensus was that this should be a separate package, in mplcursors, or an example.  Thanks a lot - cool use of the widgets!

**Comment by Joschua-Conrad** [comment]
Sorry I completely forgot about this PR...

So if I clean-up my changes in unittest and move the new widget class into the example file, you'd consider this as useful for MPL?

**Comment by jklymak** [comment]
That'd be great if you had time.  BTW, always feel free to ping us for reviews.  Stuff falls off the top of the guthub queue and its hard to remember to go back!

**Comment by Joschua-Conrad** [comment]
@jklymak thank you for your help!

So I did the following changes to the branch I PR'ed from here:

- Moved the definition of the TextCursor class into examples/widgets/text_cursor.py
- Removed added unittest
- Merged upstream/master into the feature branch, because the feature branch has been stall for such a long time (sorry again)
- Fixed linting errors in source code of the added example
- Added ReST explanation inside the example
- Minor changes in docstrings and comments
- Removed lengthy explanation for cursor not being shown in example's peview and replaced it by a ReST _.. note::_ directive in example's head
- Fixed "Whats's new" explanation to concur with recent changes

In comparison to the tip of the master branch, only the new examples/widgets/text_cursor.py and doc/users/next_whats_new/cursor_widget_with_coordinate_text.rst have been added. No files, which exist on the master branch have been changed. Furthermore, the behavior of the cursor is the exact same as in the discussion of this PR. I hope that makes reviewing the changes easier.

That leaves me with a couple of questions:

1. Do you want me to open a new PR or is this PR re-opened?
2. The source code of the class "TextCursor" still contains docstrings, which previously have been processed by autodoc. But example files are not processed by autodoc. Shall I re-format the docstrings to be in the ReST section of the example? Or leave it that way? Or can I manually trigger autodoc to process this one class definition inside text_cursor.py? An _.. autoclass:: TextCursor_ does not work, because the class definition is outside the matplotlib package scope.

Thank you for your time!

**Comment by jklymak** [comment]
I don't thin examples are run through autodoc.  We do not want the docstings for examples in our main docs.  

Similarly a new example does not typically get a what's new entry. If you want to advertise you could make a matplotlib blog entry. 

Finally if you want to make this easy for people you could just make a package and we would list on our third party packages page.  That would also let you collect stats and if it is heavily used we could reconsider adding to the main library 

Yes a new PR would be cleaner.

**Comment by Joschua-Conrad** [comment]
New PR #20019 created. I think there is just not enough code for having this as an own package and when reading

> First of all, the whole widget system is IMO only a half-baked. It's working, but falls behind in visual appearance, API, usability and features from what I expect from a professional solution.

I would rather not create an additional package, which heavily relies on the widgets API.

But thank you for your advice. If nobody learns something when watching the example, at least I learn how to submit a PR ;D

**Comment by jklymak** [comment]
I think its true that the widgets API is not super-professional, but for science and engineering use across many different GUI backends, it seems not too bad. I'm not aware of an effort to replace it.

**Comment by Joschua-Conrad** [comment]
It's definitely a handy API! And the example might help users with a non-computer-science background understanding how to add custom widgets.

**Pull request closed without merging**
