### PR TITLE
%s -> %r else if invalid char unable to print error

### PR DESCRIPTION
**Pull request by mdipierro**

### CODE REVIEW

**Comment by WeatherGod** [comment]
attn: @mdboom

**Comment by tacaswell** [comment]
Looks reasonable to me, what conditions caused this to matter?

**Comment by mdipierro** [comment]
I upgraded anaconda on Mac and I started getting:

Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Normal)
Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Georgia)
Found an unknown keyword in AFM header (was Normal)
Traceback (most recent call last):
....
    import matplotlib.backend_bases as backend_bases
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/textpath.py", line 19, in <module>
    import matplotlib.font_manager as font_manager
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1415, in <module>
    _rebuild()
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1400, in _rebuild
    fontManager = FontManager()
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1059, in __init__
    self.afmlist = createFontList(self.afmfiles, fontext='afm')
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 568, in createFontList
    font = afm.AFM(fh)
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/afm.py", line 346, in __init__
    parse_afm(fh)
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/afm.py", line 333, in parse_afm
    dhead = _parse_header(fh)
  File "/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/afm.py", line 172, in _parse_header
    print('Found an unknown keyword in AFM header (was %s)' % key,
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa9 in position 0: ordinal not in range(128)

After the change the output was:

Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Normal')
Found an unknown keyword in AFM header (was '\xa9')

I am not sure how and were \xa9 got in there. It does not happen in my code.

**Comment by tacaswell** [comment]
No, that is coming out of parsing the AFM files.  Can you tell which font it is that is causing trouble?

For reference the offending character: 

```python
In [12]: print('\xa9')
©
```

**Comment by mdipierro** [comment]
thanks for responding so quickly. :-)
How do I check which font?

**Comment by tacaswell** [comment]
If you can get into debug mode you can walk the trace back up until it shows you the file path in `createFontList`.  The other option is to just add a print statement into `font_manager.createFontList` and which ever one it prints out last is the problem ;)

**Comment by mdipierro** [comment]
...
/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts/Times-Bold.afm
/Users/massimodipierro/anaconda/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/afm/phvl8a.afm
/Library/Fonts/georgia.afm
Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Georgia')
Found an unknown keyword in AFM header (was 'Normal')
Found an unknown keyword in AFM header (was '\xa9')
/usr/X11/lib/X11/fonts/Type1/UTB_____.afm
/usr/X11/lib/X11/fonts/Type1/c0583bt_.afm
...

does it help?

**Comment by tacaswell** [comment]
It looks like the offending file is `/Library/Fonts/georgia.afm` which does not seem to be a 'standard' font on OSX.  It is probably worth sorting out if your file is badly formed or our parser is not complete (or both!), but not worth holding this PR up over.

**Comment by tacaswell** [comment]
@mdipierro Thank you!

**Comment by mdipierro** [comment]
Thank you. Sorry for not responding sooner.

**Comment by jenshnielsen** [comment]
Looks good to me. I just want to add for any future reference that this is similar to the issue observed in #3849 fixed by #3853 in the truetype font code.

**Pull request merged**
