### PR TITLE
Add guiEvent data to Qt backend

### PR DESCRIPTION
**Pull request by blink1073**
Boy do I wish I stared contributing 3 years ago...
I could have prevented detours to Chaco, PyQtGraph, guiqwt, ...ugh.

### CODE REVIEW

**Comment by pelson** [comment]
Thanks @blink1073 - we wish you'd started contributing 3 years ago too!
So, can you give us a heads up as to the reason for this change? This is slightly awkward in that this isn't the interface defined in backend bases..

**Comment by tacaswell** [comment]
It looks like gtk, gtk3, tk, and wx do this already.  

I think the idea is that this is a way to transparently pass the gui-framework specific event objects through to your call backs.

**Comment by blink1073** [comment]
What Tom said. :smile:

**Comment by blink1073** [comment]
See also: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L1316

**Comment by pelson** [comment]
Cool - I learnt something new. :smile:

**Pull request merged**
