### PR TITLE
Clean conda on appveyor

### PR DESCRIPTION
**Pull request by dstansby**
I think that appveyor is currently failing because it's picking up a corrupted cache - maybe cleaning conda will help?

### CODE REVIEW

**Comment by dstansby** [comment]
Or maybe not... lets try disabling the cache

**Comment by dstansby** [comment]
Slight progress; upgrading conda changes the error to 

```
conda install -c conda-forge --yes --quiet obvious-ci
Package plan for installation in environment C:\Miniconda-x64:
The following NEW packages will be INSTALLED:
    anaconda-client:  1.6.5-py_0     conda-forge
    beautifulsoup4:   4.6.0-py27_0   conda-forge
    chardet:          3.0.4-py27_0   conda-forge
    clyent:           1.2.2-py27_0   conda-forge
    conda-build:      2.1.17-py27_0  conda-forge
    conda-verify:     2.0.0-py27_0   conda-forge
    contextlib2:      0.5.5-py27_0   conda-forge
    decorator:        4.1.2-py27_0   conda-forge
    filelock:         2.0.6-py27_0   conda-forge
    functools32:      3.2.3.2-py27_1 conda-forge
    futures:          3.1.1-py27_0   conda-forge
    ipython_genutils: 0.2.0-py27_0   conda-forge
    jinja2:           2.9.6-py27_0   conda-forge
    jsonschema:       2.5.1-py27_0   conda-forge
    jupyter_core:     4.3.0-py27_0   conda-forge
    markupsafe:       1.0-py27_0     conda-forge
    nbformat:         4.4.0-py27_0   conda-forge
    obvious-ci:       0.6.1-py27_2   conda-forge
    pkginfo:          1.4.1-py27_0   conda-forge
    pycrypto:         2.6.1-py27_1   conda-forge
    python-dateutil:  2.6.1-py27_0   conda-forge
    pytz:             2017.2-py27_0  conda-forge
    pyyaml:           3.12-py27_1    conda-forge
    traitlets:        4.3.2-py27_0   conda-forge
    yaml:             0.1.6-vc9_0    conda-forge [vc9]
The following packages will be SUPERSEDED by a higher-priority channel:
    conda:            4.3.25-py27_0              --> 4.3.23-py27_0 conda-forge
    conda-env:        2.6.0-0                    --> 2.6.0-0       conda-forge
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::anaconda-client-1.6.5-py_0'.
CondaError: Cannot link a source that does not exist. C:\Miniconda-x64\Scripts\conda.exe
Attempting to roll back.
```

**Comment by anntzer** [comment]
see also https://github.com/conda-forge/anaconda-client-feedstock/issues/15 and linked issues

**Comment by tacaswell** [comment]
backported to v2.1.x as ebd3a7288 to un-break appveyor there too

**Pull request merged**
