### PR TITLE
[MRG+1] Filled + and x markers

### PR DESCRIPTION
**Pull request by has2k1**
The rationale for the addition of these symbols is; to allow a
grammar based plotting package to conveniently use the common
plotting symbols (circle, square, triangle, plus and x) and not
have to deal with some of them not being fillable.

### CODE REVIEW

**Comment by tacaswell** [comment]
I am :+1: modulo a bit of discussion about the names and the details of the shape.

It is a bit annoying that `x` -> `X` make sense but `p` -> `P` does not, but I do not really see any better options here.

Maybe make the limbs a little narrower?  This look very blocky to me.

**Comment by has2k1** [comment]
Yeah, the options for plus were not great, the silver medallist was `#`. 

I will mock-up some options with various limb sizes.

**Comment by efiring** [comment]
For filled markers, I think a blocky design makes sense--you have to have room inside to fill it.  This PR looks good to me.  Using the hash instead of the P might be an improvement.

**Comment by has2k1** [comment]
Here are some marker options for a rough vote.

The labels at the top of the columns indicate the ratio for the breadth of the "limbs".
The markers in the top half have a larger `linewidth` than those in the bottom half.

**plus**
filled-plus

**x**
filled-x

For a uniform look it should be the same breadth ratio for both markers. The current implementation uses a ratio of `1/3`.

My vote: **1/4**

**Comment by tacaswell** [comment]
I lean towards 1/5, but am ok with 1/4

:+1: to using the same ratio for both.

I am sure _someone_ will ask for the ability to control this ratio via rcparams, but lets put off doing that until someone asks for it :smile: .

**Comment by efiring** [comment]
I think 1/3 is most functional, 1/4 is still acceptable, 1/5 is too skinny.  The point of a filled marker is to have a filling and an outline.  Make it too skinny, and the marker will have to be very large for there to be enough room for an outline and a fill; and the filling should occupy at least as much area as the outline.  My assumption is that normally markers will be small compared to the Axes dimensions.  In the examples given here, the smallest ones are larger than I would expect most real-life markers to be.

**Comment by WeatherGod** [comment]
How about we put this up as a vote on matplotlib-users?

**Comment by tacaswell** [comment]
@efiring That is a good point that I had not considered.

**Comment by efiring** [comment]
I'm inclined to merge this as-is.  The AppVeyor failure is unrelated.  I do not support setting up a vote on the mailing list--way too much fuss for a simple decision.  It might be too late to get this into 2.0--I don't think that backporting it is essential.

**Comment by has2k1** [comment]
I used the markers as they are in the PR and I have not wished to alter the limb sizes. I am fine on that front. Otherwise, I do indeed think a *hash* is a better symbol for the filled plus marker. I will make that
change in the next within a day or so.

**Comment by WeatherGod** [comment]
one problem with the hash symbol... it can't be used in our current
matplotlibrc reader. We should probably update the reader so that comments
are properly parsed.

**Comment by efiring** [comment]
backported to v2.x as 00495d9.
Thank you, @has2k1!

**Pull request merged**
