### PR TITLE
DOC: add gsoc banner

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by story645** [comment]
can the banner be a different color? Like maybe the pale yellow in the logo #E9D881 (also this did not show up in my notifications 😦 )

**Comment by tacaswell** [comment]
Built and pushed the docs from this branch (which do not fail locally for me).

The colors can definitely be better...

**Comment by story645** [comment]
I'm a little concerned that this is unmerged and yet live:
image

**Comment by story645** [comment]
GSOC applications finished, so this should get removed. Thanks!

**Comment by QuLogic** [comment]
I'm not sure we need to merge this anymore; just revert the changes on the doc site?

**Pull request closed without merging**
