### PR TITLE
Re-enable CI buildwheel and cygwin labels

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

I guess this was renamed recently?

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by ksunden — APPROVED** [review]

**Review by jklymak — APPROVED** [review]
My apologies - I renamed this; I had no idea it was being used for a workflow.  Alternative is to change the name back.  Note I also changed the Cygwin name.  

Perhaps in the description, we can be more draconian: "DON'T RENAME AS IT BREAKS AN ACTION" ?

**Comment by tacaswell** [comment]
While you are doing this can you fix the cgywn one as well?

**Comment by tacaswell** [comment]
I also wonder if in the GHA it is possible to grab the label id rather than the name (which should be stable over time!)?

**Comment by oscargus** [comment]
Added Cygwin as well.

Couldn't figure out which members are available for the events...

Probably this should be backported? Thinking that otherwise one cannot do this for backported PRs? Like the qhull LICENSE issue?

**Comment by ksunden** [comment]
Cygwin ci does not exist for 3.7.x, so the changes to cygwin are not backported

**Pull request merged**
