### PR TITLE
Simplify binary data handling in ps backend.

### PR DESCRIPTION
**Pull request by anntzer**
- bytes.hex() can now perform linewrapping itself, so use that in
  draw_image.
- draw_gouraud_triangles can rely on PostScript's hexstring format
  (`<...>` instead of `(...)`) and thus on bytes.hex() too.  This makes
  _quote_ps_string fully unused, thus tweak the deprecation of
  quote_ps_string.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by oscargus — APPROVED** [review]
The only potential "problem" is that the deprecation note says: "Vendor the code of the similarly named private functions if you rely on these functions." https://github.com/matplotlib/matplotlib/blob/main/doc/api/next_api_changes/deprecations/22797-OG.rst

But hopefully people will understand anyway (there are several functions deprecated, so probably not worthwhile special handling this one).

**Comment by oscargus** [comment]
Oh, if there is a suitable test to add that would be great! (Or are the lines actually tested despite the report?)

**Comment by anntzer** [comment]
It is quite possible that this is actually not tested; will add a test...

**Comment by anntzer** [comment]
Test added.

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
