### PR TITLE
Backport #5307 to v2.0.x

### PR DESCRIPTION
**Pull request by mdboom**
Running this through a PR to give it proper Travis testing.

### CODE REVIEW

**Comment by mdboom** [comment]
This is green on Travis, and therefore probably good to merge.

**Comment by QuLogic** [comment]
To trim this down a bit, the text changes seem consistent with those on `master`. There are a few different images:
```
git di --shortstat backport-lower-tolerance-2.0..master -- lib/matplotlib/tests/baseline_images/ lib/mpl_toolkits/tests/baseline_images/
 17 files changed, 5853 insertions(+), 5742 deletions(-)
```
which are mostly non-existent on 2.0, but there are a few more other changes.

`lib/matplotlib/tests/baseline_images/test_artist/default_edges.png` and `lib/matplotlib/tests/baseline_images/test_transforms/pre_transform_data.{png,pdf,svg` are different due to altered view limits around some collections. I think that's from #5583, but I'm wondering why that's not also on `master`.

I'm not sure why `lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/divider_append_axes.svg` is different.

I don't understand why `lib/matplotlib/tests/baseline_images/test_axes/dash_offset.{pdf,png}` exist only on master, but `dash_offset.svg` exists on this branch too. I don't think it should have been added here.

**Comment by mdboom** [comment]
Thanks for looking at this.

I think #5583 never got fully backported to 2.0.x.  I've done that, now I'll rebase this on the new 2.0.x and see how that pans out.

**Comment by mdboom** [comment]
> I don't understand why lib/matplotlib/tests/baseline_images/test_axes/dash_offset.{pdf,png} exist only on master, but dash_offset.svg exists on this branch too. I don't think it should have been added here.

I'm not sure I follow.  It exists in both places, AFAICT.

**Comment by mdboom** [comment]
I've redone this after backporting #5583 to v2.0.x and there were far fewer conflicts this time -- mainly just in tests that exist on master but not 2.0.x.

**Comment by mdboom** [comment]
I found two other PRs that should have been backported to 2.0.x but weren't (we probably need a better workflow for that, but it is what it is for the present time).  These PRs were #5501 and #5433.

**Comment by QuLogic** [comment]
> It exists in both places, AFAICT.

They didn't exist when I looked ;)

> I'm not sure why `lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/divider_append_axes.svg` is different.

This file is still different. Maybe including #5651 here will make them more consistent.

> These PRs were #5501 and #5433.

For some reason, GitHub is not show the backport of #5433 here even though it does say it's part of this PR if you go to your fork and look at the commit directly. Anyway...

**Comment by mdboom** [comment]
> For some reason, GitHub is not show the backport of #5433 here even though it does say it's part of this PR if you go to your fork and look at the commit directly. 

#5433 was backported directly onto v2.0.x, and then this PR was based on that.

**Comment by mdboom** [comment]
> I'm not sure why lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/divider_append_axes.svg is different.
> This file is still different. Maybe including #5651 here will make them more consistent?

Unless I'm misunderstanding, I think this is no longer the case.  Different from what?  On this branch vs. upstream/master?

```
git diff master -- lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/divider_append_axes.svg
```

**Comment by mdboom** [comment]
I think this is green again.  @QuLogic: I *think* I've addressed all that you found, but let me know if otherwise.

**Comment by tacaswell** [comment]
I am seeing 3 files different 

```
 $git diff --stat matplotlib/master -- lib/mpl_toolkits/tests/baseline_images/
 lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/divider_append_axes.svg         |  3714 ++++++++--------
 lib/mpl_toolkits/tests/baseline_images/test_axes_grid1/twin_axes_empty_and_removed.png |   Bin 37749 -> 0 bytes
 lib/mpl_toolkits/tests/baseline_images/test_mplot3d/mixedsubplot.svg                   | 16034 +++++++++++++++++++++++++++++++++++-----------------------------------
 3 files changed, 9874 insertions(+), 9874 deletions(-)
```

**Comment by mdboom** [comment]
I'll just forcibly pick those 3 files from master (since I think the differences are all non-visible anyway) and see how that goes...

**Comment by mdboom** [comment]
Ok.  I think we're finally good-to-go here.

**Comment by tacaswell** [comment]
I don't see where those other 3 files got pulled in

**Comment by tacaswell** [comment]
maybe #5621 should be backported to 2.0.x and then this backport rebased on top of it?  That is the source of the missing png

**Comment by mdboom** [comment]
> I don't see where those other 3 files got pulled in

I checked them out directly from master and amended the commit it order to reduce the amount of large diff.

> maybe #5621 should be backported to 2.0.x and then this backport rebased on top of it? That is the source of the missing png

Sure.  Done.

**Comment by tacaswell** [comment]
Ah, sorry, I was confused

**Comment by mdboom** [comment]
No worries -- I was confused as well.  This massive PRs are hard to manage...

**Pull request merged**
