### PR TITLE
Solarize_Light2

### PR DESCRIPTION
**Pull request by ilivni**
Adapted from ggplot2

Title padding
Title color
Minor grid width
Alpha for graphs with a "fill"

### CODE REVIEW

**Comment by tacaswell** [comment]
@ilivni Any interest in picking this up again?  I think that this looks OK to merge (modulo moving the example to the examples folder).

**Comment by QuLogic** [comment]
The style is named `Solarize_Light2` but not Solarized. Also, why the 2?

There are some TODOs left in the comments.

**Comment by andreas-h** [comment]
I'd love to see this in mpl, I love the solarized colors!

But shouldn't the style be called `solarized_light2` instead of `solarize_light2`?

**Comment by tacaswell** [comment]
Closing in favor of #9026 which is a rebase-and-squash of the commits here

@ilivni Thank you for your work and sorry it sat so long!

**Pull request closed without merging**
