### PR TITLE
FIX: macosx framework check

### LINKED ISSUE #11846: macosx backend won't load
### Bug report

#11600 (34794819d8) appears to have broken the macosx backend.  

```
% git checkout 34794819d8
% cd lib
% git clean -xdf
% cd ..
% pip install -e .
% pythonw testMac.py

Traceback (most recent call last):
  File "testMac.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 2410, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 246, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

```python 
import matplotlib
matplotlib.use('macosx')
```

No error on the previous commit (f4ae5d1ccb).  #11600 had a bunch of changes in the `_src/macosx.h`....

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #11846

In the macosx backend, `verify_framework` now (post #11600) gets called before the app gets started, so the checks for the framework always fail.  This PR, ~at the suggestion of @anntzer simply uses the old pre 10.6 checks.  Not sure this is the correct solution versus moving `verify_framework` to a point after the app has started, but it does work on my machine (10.13.6); using framework python (`pythonw`) works, using non-framework python (`python`) gives the appropriate error.~

This PR moves the `verify_framework` check into `lazy_init`, where the app is started, and passes success or failure up a level.  

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Attn @jenshnielsen...

**Comment by anntzer** [comment]
Happy with the change, but I'm not claiming any expertise on the topic.

**Comment by jklymak** [comment]
OK, figured out how to pass the failure up the line.  Now `lazy_init` calles `check_framework` after the app has started...

**Comment by jklymak** [comment]
... and doesnt' depend on the deprecated calls...

**Comment by anntzer** [comment]
The problem is that for backend fallback to correctly work, we need *importing* the backend to fail with ImportError; backend fallback (at least as it is written right now) doesn't work with later failures.
So I think right now using the deprecated Carbon API remains the best solution that we know of.

**Comment by jklymak** [comment]
OK - see my comment on gitter - it turns out that not having the Framework installed (`pythonw`) doesn't stop the GUI from working FAICT, it just is slightly suboptimal in that the GUI doesn't have a doc icon, so it can get burried under other windows.  To my taste that isnt' something to Error over, but rather we could/should throw a warning.

**Comment by anntzer** [comment]
Well, you have to ask those who put in the check to start with (#1613 and other PRs).
(Let's keep the discussion here rather than on gitter.)

**Comment by jklymak** [comment]
Ah, OK, the issue is https://github.com/matplotlib/matplotlib/issues/665; if you open the save dialog you can't get typing focus in the dialog box.  I'm 50/50 still if that requires us to error or warn, but it *can* be said to be not fully functional.

**Comment by jenshnielsen** [comment]
@jklymak Afaik we put this in because we got so many errors and spent so much time tracking down why the gui was not working. With pyqt5 and wxpython being pip installable now it seems easier for users to switch to a functioning backend rather than using a semi broken one so I am mildly in favor of erroring out but warnings are fine with me too.

**Comment by anntzer** [comment]
OK, let's try something else.
In the pre-OSX10.6 code, only GetCurrentProcess and SetFrontProcess are deprecated (https://developer.apple.com/documentation/applicationservices/1501115-getcurrentprocess?language=occ); CGMainDisplayID is not (https://developer.apple.com/documentation/coregraphics/1455620-cgmaindisplayid).  Would we be lucky enough to have CGMainDisplayID() return 0 on non-framework and nonzero on framework builds, in which case that'd be a way to check for frameworkness?

**Comment by jklymak** [comment]
> Would we be lucky enough to have CGMainDisplayID() return 0 on non-framework and nonzero on framework builds, 

Nope, that doesn't work.  Newest push just uses the deprecated methods at import.

**Comment by tacaswell** [comment]
Merging this as it un-breaks osx for now (and pushing the reckoning of using deprecated APIs to future us).

The OSX backend is now agg based like the others (rather than an alternate rendering path) and presumably should also be made to play nice with cairo.  The biggest advantage of the OSX backend over tk/wx is that it support hi-dpi.  The biggest advantage over Qt is that it is no extra dependencies (on macs).

**Pull request merged**
