### PR TITLE
[WIP] Collection draw order and other mplot3d stuff

### LINKED ISSUE #3370: Patch3DCollection doesn't update color after calling set_color
I've run into an issue in 1.3.1 and the latest nightly build of the 1.4.x release candidate where calling `set_color` on a Patch3DCollection object doesn't seem to work.  I only see the issue when using a 3D plot.

This bug was first reported [here](https://github.com/matplotlib/matplotlib/issues/3362), but it seems to be unrelated.

Below is a snippet similar to what I've been trying. You can comment the lines at the bottom to alternate which version (2d or 3d) you're testing. The same mechanism works for a 2d scatter plot, but not for a 3d one.

The goal is to add a new point on each animation. Then, change all older points to a different color. It's not optimal and will constantly change the color of old points even if they've already been changed. However, it clearly demonstrates that the call to set_color doesn't have any effect even though it's a somewhat silly example.

``` python
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.animation as animation
import matplotlib.pylab as plt

import numpy as np

NUM_POINTS = 10
values = []

for ii in xrange(NUM_POINTS):
    values.append(np.random.random_integers(0, 500, 3))

points = []

n = 0


def two_dim_example():
    def animate(i):
        """
        Goal is to slowly add new points and have the most current point in red
        while all other points are gray
        """

        global n

        # No more animation needed
        if n >= NUM_POINTS:
            return

        # Change color of all old points
        for point in points:
            point.set_color('gray')

        x, y, z = values[n]

        point = ax2D.scatter(x, y, s=75, c='red', marker ='o')
        points.append(point)

        n += 1

    ax2D = fig1.add_subplot(111)
    ani = animation.FuncAnimation(fig1, animate, interval=500)
    plt.show()


def three_dim_example():
    def animate(i):
        """
        Goal is to slowly add new points and have the most current point in red
        while all other points are gray
        """

        global n

        # No more animation needed
        if n >= NUM_POINTS:
            return

        # Change color of all old points
        for point in points:
            point.set_color('gray')

        x, y, z = values[n]

        point = ax3D.scatter(x, y, z, s=50, c='red', marker ='o')
        points.append(point)

        n += 1

    ax3D = fig2.add_subplot(111, projection='3d')
    ani = animation.FuncAnimation(fig2, animate, interval=500)
    plt.show()


# Uncomment to see that 2d works
#fig1 = plt.figure()
#two_dim_example()

fig2 = plt.figure()
three_dim_example()
```

### PR DESCRIPTION
**Pull request by WeatherGod**
- Added _draworder to Collection class
- Utilized it for Poly3DCollection to simplify code and close #4067 
- Also fixed issue with Path/Patch3DCollections, closes #3370 

TODO: See if I can share zsorting code across all the 3D collection classes (right now, it only resides in Poly3DCollection)

### CODE REVIEW

**Comment by WeatherGod** [comment]
Travis errors are spurious download errors

**Comment by syee** [comment]
I believe I'm still running into this issue today. Below is the error message I receive when attempting to convert hb_made (a hexbin PolyCollection) into a Poly3DCollection. Are there any other ways to convert 2D PolyCollections into 3D PolyCollections?

ax.add_collection3d(hb_made, zs=shotNumber.get_array(), zdir='y')

File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 2201, in add_collection3d
art3d.poly_collection_2d_to_3d(col, zs=zs, zdir=zdir)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 716, in poly_collection_2d_to_3d
col.set_3d_properties()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 595, in set_3d_properties
self._edgecolors3d = PolyCollection.get_edgecolors(self)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/collections.py", line 626, in get_edgecolor
return self.get_facecolors()
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 699, in get_facecolors
return self._facecolors2d
AttributeError: 'Poly3DCollection' object has no attribute '_facecolors2d'

**Comment by tacaswell** [comment]
@WeatherGod This needs a rebase

**Comment by tacaswell** [comment]
ping @WeatherGod is this still a going concern?

**Comment by jklymak** [comment]
I'll close this for lack of progress...

**Pull request closed without merging**
