### PR TITLE
Fix mathtext rendering of `\|` and sizing of `|` and `\|`

### LINKED ISSUE #23250: [Bug]: Incorrect mathtext rendering of `r"$\|$"` with default (dejavu) math fontfamily
### Bug summary

`r"$\|$"` should render as a double vertical bar, which it does with usetex or with math_fontfamily="cm", but not with the default "dejavusans" math_fontfamily.

### Code for reproduction

```python
s = r"single$|$ double$\|$"
figtext(.5, .7, s); figtext(.5, .6, s, math_fontfamily="cm"); figtext(.5, .5, s, usetex=True)
```

### Actual outcome

test

### Expected outcome

Double vertical bar in the first line too.

### Additional information

_No response_

### Operating system

arch

### Matplotlib Version

3.6.0.dev2423+gd0bef3b3d7

### Matplotlib Backend

qt5agg

### Python version

3.10

### Jupyter version

ENOSUCHLIB

### Installation

git checkout

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Closes #23250

(Implements the less controversial part of #23685)

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
Since we have to update the test image, maybe we can drop the extra `\Vert` and `\vert` at the end? At least, I think those are redundant with the first two.

**Comment by oscargus** [comment]
I think the idea is to test `\left` and `\right` in combination with these. However, it doesn't really make sense for a single letter. I'll update the first to consider a fraction instead (to clearly illustrate a bug in | not being resized).

**Comment by oscargus** [comment]
The new text images illustrates some of the issues, but others are missed. So the question is if we should also add tests for a single letter with `\left`/`\right` etc? For cm the bars are adjusted down in size for a.

Maybe @anntzer can weigh in on relevant test cases?

**Comment by oscargus** [comment]
It seems like getting rid of the following line sorts out the sizing, but I have not checked what else it breaks...

**Comment by oscargus** [comment]
Figured out a way to get the vertical bar size correct. https://github.com/matplotlib/matplotlib/issues/23250#issuecomment-1221357226

Added a second commit with that change so that one can see the differences. The rationale is to scale if there are no alternatives (or rather only a single alternative).

(Make sure to squash the commits.)

**Comment by oscargus** [comment]
The drawback of the current approach of getting the size right is that the font size is changed, so wider bars, but probably still better than having too short ones...

**Comment by anntzer** [comment]
Looks good to me; just need a squash.

**Review by anntzer — APPROVED** [review]

**Pull request merged**
