### PR TITLE
Added share_tickers parameter to axes._AxesBase.twinx/y

### LINKED ISSUE #7376: Twinned axes do not allow setting of different formatters
To help us understand and resolve your issue please check that you have provided
the information below.

- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)
Matplotlib 1.51, Python 3.5.2 on Red Hat Enterprise Linux 6.5

- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)
Anaconda 1.5.1 (conda 4.2.9)

- [x] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.
```python
from matplotlib import pyplot as plt
from matplotlib.ticker import Formatter, MaxNLocator

ax = plt.plot([0, 1, 2, 3], [0, 1, 2, 3])[0].axes
ax.figure.subplots_adjust(bottom=0.3)
ax.set_xlabel('Axis1')  # To demonstrate that labels can be set differently
ax2 = ax.twinx()
ax2.set_frame_on(True)
ax2.patch.set_visible(False)
ax2.yaxis.set_visible(False)
ax2.xaxis.set_visible(True)
ax2.spines['bottom'].set_position(('axes', -0.2))  # So far so good
ax2.set_xlabel('Axis2')  # Surprisingly (or not), this works

class F(Formatter):
    def __call__(self, x, pos=None):
       return '%03d' % x

# This does not work as expected:
ax.xaxis.set_major_locator(MaxNLocator(integer=True))  # Both locators get modified
ax2.xaxis.set_major_formatter(F())  # Both formatters get modified
```

I suspect that this has something to do with the fact that `Axis` has a `Ticker` container for the attributes that are behaving inappropriately, and that they are not being copied correctly when the axis is twinned for some reason. I have not been able to trace this problem down yet, but with a few pointer from the experts, I'd probably be able to make a PR. Assuming this is actually an issue, of course.

- [ ] If this is an image generation bug attach a screenshot demonstrating the issue.
- [ ] If this is a regression (Used to work in an earlier version of Matplotlib), please 
      note where it used to work.

### PR DESCRIPTION
**Pull request by dstansby**
This is my attempt to resurrect #7528, which fixes #7376.

### CODE REVIEW

**Comment by jklymak** [comment]
Can you provide an example as well?  I finally parsed why we would want this from the original issue, and I think it’d be a helpful example to have.   

I guess I’m also still concerned that @efiring issue with the locator being different is still valid because the locator also returns the autolims.  Which locator wins if the locators are different?  This should be consistent and documented.

**Comment by efiring** [comment]
Given the warning of possible dire consequences, why do this at all?  I think this is simply a bad idea, short of a total overhaul of the way we track and determine axis limits.

**Comment by jklymak** [comment]
I think it’s a useful idea to have a second scale for the same axis, which i think was the original idea.  But I’m not at all sure this is the best way to do it.

**Comment by dstansby** [comment]
My personal example, is I have a timeseries data, on two shared x-axis. I want to put timestamps on one of the axis labels, but want to format the second axis labels a different way (but still have them linked, so when I drag or zoom one the other drags/zooms too).

I don't think this is a bad idea at all in theory - the location of data on the graph is independent of the ticks and labels above. I'll have a proper look at the autoscaling worries soon.

**Comment by dstansby** [comment]
(at least as a minimum being able to set different formatters would be good if setting different locators is a problem.)

**Comment by dstansby** [comment]
To record my findings, the way I think `autoscale_view` works is:

1. Call `autoscale_view` on a single axis (I don't think it's possible to call it on a shared set)
2. Work out the data limits from all the current axis and all of its shared axis'
3. Using these data limts, let the locator of the **current** axis determine the final view limits

So I don't think having different locators is a problem code wise - there might just be different results depending on which axis is autoscaled, even if they are twinned. Would that be a problem?

**Comment by jklymak** [comment]
This and #10961 are almost the same thing....

**Comment by dstansby** [comment]
Okay, I'll close this in favour of discussion on #10976, thanks for taking the time to look over this!

**Pull request closed without merging**
