### PR TITLE
DOC: fix an overlooked docs change from #19153

### PR DESCRIPTION
**Pull request by lpsinger**
## PR Summary

Fix an overlooked docs change from #19153, noted by @dstansby in #19432.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
We can't just get rid of these docs without deprecating the behaviour it documents (if indeed we do want to change the behaviour, which I'm not sure we do in this case), in particular
> Meanwhile, if you do not want this behavior (i.e., you want to force the creation of a new subplot), you must use a unique set of args and kwargs.

**Comment by astrofrog** [comment]
I'm very concerned about this change, even if it was to go through a deprecation phase. As indicated in https://github.com/matplotlib/matplotlib/issues/19432 I don't understand why one would ever want the same axes to be returned if the projection and kwargs are different?

**Comment by dstansby** [comment]
I don't think I can dismiss my review, but if another maintainer wants to then go ahead. Apologies for jumping the gun on lots of this discussion, that has clearly been discussed more thoroughly on a dev call. I've tagged this as release critical so we don't forget it either way.

**Comment by lpsinger** [comment]
Closing in favor of #19438.

**Pull request closed without merging**
