### PR TITLE
Don't pretend to support old pythons in setup.py.

### PR DESCRIPTION
**Pull request by anntzer**
setup.py uses f-strings, so it fails with SyntaxError on Py<3.6, so
let's not pretend to support older Pythons there (see also https://github.com/matplotlib/matplotlib/issues/16733).

(The alternative would be to only put the version check in setup.py and
then move *everything* else into setupext.py, which may not be silly
either?)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
If anything, #16733 seems to prove that we need to keep the check in _longer_. Python 2 was only just let go this year.

**Comment by anntzer** [comment]
But the point is that the check is actually not doing its job, because if you're running setup.py in an old Python you get the syntax error even before the check runs.

**Comment by timhoffm** [comment]
The point is to fix that other syntax error and not to add more incompatibility?

**Comment by anntzer** [comment]
> The point is to fix that other syntax error

This is bound to break regularly again unless we actually test that.
If we care about this use case I would suggest that we just move everything to setupext.py with just a version check in setup.py before importing setupext.

**Comment by timhoffm** [comment]
The jquery stuff and command definitions surely should go into setupext.py; as well as the package collection. However I would leave `setup()` in place. That's where people expect it.

**Comment by QuLogic** [comment]
Since we got another report about the `SyntaxError`, I don't think we're ready to be removing this check. I've opened the above-mentioned PR to fix the syntax errors instead. I'm going to close this for now.

**Comment by anntzer** [comment]
Sounds fair.

**Pull request closed without merging**
