### PR TITLE
Mention gr backend in docs.

### LINKED ISSUE #7950: Mention gr as a third party backend
[gr](http://gr-framework.org/) seems to be a graphics framework by @jheinen that, in particular, can be used as a high performance matplotlib backend.  In https://github.com/jheinen/gr/issues/16 @tacaswell suggested (>1y ago) that it be added to matplotlib's documentation, but the issue seems to have fallen through the cracks, so I'm reposting it on this tracker.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Closes #7950.  The text for gr was paraphrased from http://gr-framework.org/ and http://gr-framework.org/about.html.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I think we merged something w a flake8 error.

**Comment by jklymak** [comment]
...or something happened to flake8 so it no longer works

**Comment by timhoffm** [comment]
pydocstyle 4.0 was released yesterday (https://pypi.org/project/pydocstyle/#history). I'm quite shure this is the reason for the failure (though I did not check what exactly goes wrong there).

**Comment by anntzer** [comment]
basically flake8-pydocstyle doesn't support (yet) the last version of pydocstyle, although there's a PR open on their repo to fix that

**Comment by timhoffm** [comment]
Since this is doc-only. I don't think flake8 would check the changes anyway. So merging without waiting for the flake8-docstring fix (#14710).

**Pull request merged**
