### PR TITLE
added venv to gitignore

### PR DESCRIPTION
**Pull request by HashiramaP**
## PR summary

The commit adds venv/ to the .gitignore file to prevent the tracking of Python virtual environments so only relevant project files are committed.

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https//matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by tacaswell** [comment]
Why did you add and then remove `envs`?

**Comment by HashiramaP** [comment]
> Why did you add and then remove `envs`?

It wasn't necessary

**Comment by timhoffm** [comment]
> most people use venv

Do you have a reference for that? We don't specify the name of the venv in our [dev setup instructions](https://matplotlib.org/devdocs/devel/development_setup.html#create-a-dedicated-environment). Numpy uses `numpy-dev` (https://numpy.org/doc/stable/dev/development_environment.html#using-virtual-environments). I feel a name containing the library is better because your prompt shows what environment you are in and if everything is named `venv` that's not too helpful.

**Comment by HashiramaP** [comment]
> > most people use venv

I just went with common sense of what most people use when creating venv, the ideal thing would be to recommend a venv name and add that to the gitignore although adding venv is still not a bad idea.

> > most people use venv
> 
> Do you have a reference for that? We don't specify the name of the venv in our [dev setup instructions](https://matplotlib.org/devdocs/devel/development_setup.html#create-a-dedicated-environment). Numpy uses `numpy-dev` (https://numpy.org/doc/stable/dev/development_environment.html#using-virtual-environments). I feel a name containing the library is better because your prompt shows what environment you are in and if everything is named `venv` that's not too helpful.

I chose 'venv' based on the common practice among developers when creating virtual environments. However, I agree that recommending a more descriptive virtual environment name would be ideal for clarity.

**Comment by timhoffm** [comment]
My suggestion - and I would like to have feedback from other core devs on this - would be to add a concreate name to the dev setup instructions and add that name to .gitignore.
I have no clear opinion what that name should be as I mostly use conda envs, which are not locally stored.

OTOH adding `venc/` likely doesn't hurt either.

**Comment by jklymak** [comment]
I think in the past we have recommended people not store their venv in the Matplotlib subdirectory? Not sure if we want to recommend putting it there now, but I don't use venv regularly to know what people usually do.  On the one machine where I do use them, they are all in ~/.venvs/

**Comment by Msa360** [comment]
When I want to create a venv in the most simple way I just use the virtualenv python package and name it venv, which automatically stores it in the **venv/** subdirectory. I think I would not hurt to add it to the gitignore.

**Comment by tacaswell** [comment]
Given that we are unlikely to use these names for things we need to do, I'm inclined to add any path we think some one _might_ stash an environment in the gitignore.  Seems low cost and prevents checking in a whole environment (again).

**Comment by greglucas** [comment]
I agree with all that has been said so far and we shouldn't overthink this too much. I would suggest adding at least these, and possibly just merging the missing content from GitHub's gitignore suggestions:
https://github.com/github/gitignore/blob/807578222ddd1dcef7d41c1dc9215751620f7246/Python.gitignore#L124-L131

**Comment by timhoffm** [comment]
@HashiramaP can you please follow @greglucas suggestion above and include all env names from GitHub's ignore list?

**Comment by HashiramaP** [comment]
> @HashiramaP can you please follow @greglucas suggestion above and include all env names from GitHub's ignore list?

Done!

**Review by timhoffm — APPROVED** [review]

**Review by greglucas — APPROVED** [review]

**Comment by greglucas** [comment]
Thanks @HashiramaP! We hope to hear from you again 🎉

**Pull request merged**
