### PR TITLE
Fix documentation link with renaming `voxels` to `voxelarray`

### LINKED ISSUE #21608: [Doc]: `ax.voxels` links to wrong method.
### Documentation Link

https://matplotlib.org/stable/gallery/mplot3d/voxels.html

### Problem

image
The line `ax.voxels` links here:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray

### Suggested improvement

It should link here instead:
https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.voxels

### Matplotlib Version

3.4.3

### Matplotlib documentation version

3.4.3

### PR DESCRIPTION
**Pull request by kolibril13**
Fixes #21608

### CODE REVIEW

**Comment by kolibril13** [comment]
The wrong link is now removed:
https://64751-1385122-gh.circle-artifacts.com/0/doc/build/html/gallery/mplot3d/voxels.html
Now, there is no link at all, but I think it is still an improvement.

**Comment by jklymak** [comment]
Yeah I think mplot3d doesn't link properly...

**Review by jklymak — APPROVED** [review]

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.5.x

**Comment by QuLogic** [comment]
@meeseeksbot backport to v3.5.x

**Pull request merged**
