### PR TITLE
Cleanup old print statements

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Update comments and docstrings that use old print statements, either with functions or just removing the comments entirely.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Lets see if I got the backport configuration set up right....

**Comment by tacaswell** [comment]
@meeseeksdev backport to v2.2.x

**Comment by tacaswell** [comment]
@Carreau any advice on what I have configured wrong for auto-backports to work?

**Comment by Carreau** [comment]
Are you missing the `on-merge: backport to v2.2.x` in the milestone description ?

**Comment by tacaswell** [comment]
"Release of v2.2.0 final release. on-merge: backport to v2.2.x" is the description.

**Comment by Carreau** [comment]
> "Release of v2.2.0 final release. on-merge: backport to v2.2.x" is the description.

Sorry, too early in the morning. Let me look at the logs.

**Comment by Carreau** [comment]
Did you milestoned just before merging ? Because it seem the bot did not see the milestone when it saw the merged/pushed commits. Let me know if it still does not work on subsequent PRs.

**Pull request merged**
