### PR TITLE
Log all failures to extract font properties.

### PR DESCRIPTION
**Pull request by anntzer**
Some failures were previously not logged.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
@meeseeksdev backport to v3.0.x

**Comment by QuLogic** [comment]
>  [jklymak](/jklymak) added this to the [v3.1.0](/matplotlib/matplotlib/milestone/35) milestone [22 minutes ago](#event-2209212555)

> @meeseeksdev backport to v3.0.x

These are not the same branches; which one did you mean?

**Comment by jklymak** [comment]
Ooops.  Typo

**Comment by jklymak** [comment]
@meeseeksdev backport to v3.1.x

**Pull request merged**
