### PR TITLE
[MRG] ticker: cast argument to int to avoid numpy warning

### PR DESCRIPTION
**Pull request by efiring**

### CODE REVIEW

**Comment by efiring** [comment]
This is a very simple one; there is no need for an extended review.  @qulogic, it is in response to a problem you found (numpy warning), so if it looks OK to you, please go ahead and merge it.

**Comment by phobson** [comment]
I'm happy to merge, but I'm really surprised that `b//2` wasn't sufficiently int-like for numpy.

**Comment by phobson** [comment]
@efiring & @tacaswell: what's the backport strategy (if any) when merging into a maintenance branch? In other words, does this need to go into `master` too? And if so, how?

**Comment by QuLogic** [comment]
`a//b` with `a` or `b` as floats is unfortunately still a float.

**Comment by QuLogic** [comment]
@phobson `v2.x` is periodically merged up to `master`.

**Pull request merged**
