### PR TITLE
Link to matplotlibrc of used version

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

When suggesting to update matplotlibrc, link to the relased version of the current code, not master.

Follow up to prevent confusion of #14547.

### CODE REVIEW

**Comment by tacaswell** [comment]
Is the template someplace in the build docs?  It might make more sense to link there rather than github?

I can see why either way would be better, :+1: in either case.

**Comment by timhoffm** [comment]
You have https://matplotlib.org/devdocs/tutorials/introductory/customizing.html#a-sample-matplotlibrc-file, but I don't think you have the file itself in the built docs.

**Comment by tacaswell** [comment]
Maybe use https://raw.githubusercontent.com/matplotlib/matplotlib/v3.1.0/matplotlibrc.template instead so it is something you can wget?  If it is going to go to a page you have to copy-paste anyway, I think the docs are marginally better.

In any case, this is an improvement, feel free to ignore my :bike: :house: comments.

**Comment by timhoffm** [comment]
@tacaswell Thanks for your comment. I take the liberty and not follow it. It is not obvious that https://raw.githubusercontent.com/matplotlib/matplotlib/v3.1.0/matplotlibrc.template is the actual file. So I assume that most people will put it in a browser anyway to check. And then, your link is also just one click away.

Additionally, with the github link you can access the history and lookup what was changed recently.

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.1.x

**Comment by QuLogic** [comment]
Backport in #14828.

**Pull request merged**
