### PR TITLE
Abbreviating offset_transforms to trans

### PR DESCRIPTION
**Pull request by Yoshitsuneee**
Good evening, this is my first contribuition to open source projects, I thought that by doing a simple contribution it would help me to improve my next ones. I hope that we keep in touch and thanks for your time

### CODE REVIEW

**Review by ksunden — CHANGES_REQUESTED** [review]
This is not what was meant by #22156

That issue was about what to call _local_ variables. In particular all of the functions and parameters _should not_ change (without deprecation cycles at the very least).

Additionally old api notes should not change

**Comment by Yoshitsuneee** [comment]
Oh, I'm sorry, I thought it was about the offset_transforms because of the PR about changing his name

**Comment by ivanov** [comment]
~~@Yoshitsuneee can you explain your motivation behind this change? ~~ Nevermind, I see Kyle's linked to the issue. Your contributions have a better chance getting reviewed when you link to the relevant issues in the opening discussion of a pull request (or in subsequent comments).

Here's some stuff I wrote before I saw the link about why your proposed changed doesn't fit the bill:  `offset_transform` is called that because it is a transform that applies to the offsets, and there are several places where there are *other* transforms, and removing the `offset_` prefix introduces ambiguity. With your proposed changes, there would be places where the public API exposes `set_transform` and `set_trans` and those two refer to separate things (what is currently referred to by `set_transform` and `set_offset_transform`.

**Comment by Yoshitsuneee** [comment]
@ivanov thanks for the help, I will revert and start working on this again (in the right way this time)

**Comment by ksunden** [comment]
I will caution you a little bit, that I'm not even sure that there was consensus on what we wanted or if we even want to change existing code or just standardize going forward.

**Comment by ksunden** [comment]
@Yoshitsuneee We discussed the issue at our dev call today and decided that while we would like to encourage use of `trans` as the variable name for a transform, we are not interested changing existing code (that is not otherwise being edited)

Please do have a look at our `Good First Issue` label if you are interested in finding something to do.

**Pull request closed without merging**
