### PR TITLE
Update docs on Axes.set_prop_cycle

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Documentation update.

### Questions

1. `` :func:`cycler` `` does not link. I'm unclear where it should go. There is `matplotlib.rcsetup.cycler` and the external `cycler.cycler`. Which one is recommended?
2. Should we deprecate or at least discourage the signature `set_prop_cycle(label, values)` in favor of the equivalent `set_prop_cycle(label=values)`. There's no need for additionally supporting the first version and it's not quite pythonic after all.

### CODE REVIEW

**Comment by phobson** [comment]
Restarted the one failed travis build. The failure seems transient.

**Comment by WeatherGod** [comment]
link to the matplotlib cycler. The only difference between it and the
external one is that it has input validation, which was needed for use in
rc params (want to catch invalid values as early as possible).

As for the two ways to do cyclers, that has some history. Initially (in the
external cycler) package, you were supposed to have a cycler for each
element, so the two argument form was the only form you could use. You then
would use the binary operators to construct the final cycler. However, as I
developed the property cycler feature, I found that that restriction wasn't
very friendly for users who just want a simple zip-like cycle. So, a bunch
of us worked on expanding the API a bit to allow a few different
constructions. They are all valid and I wouldn't want to go down any
deprecation routes for this.

**Comment by timhoffm** [comment]
@anntzer I share your view on `set_prop_cycle`. I would be willing to argue for a deprecation of the two-arg signature if there's a chance of getting this through (There should be one-- and preferably only one --obvious way to do it.).

At best, it could be deprecated at cycler.Cycler, but a smaller step in rcsetup.cycler or maybe only in `set_prop_cycle` would be an improvement. Do you think, there is a chance of getting any of this through?

**Comment by anntzer** [comment]
You can always try to open a PR for that :-)

**Comment by WeatherGod** [comment]
The two arg form comes from the cycler package. I would suggest starting
there. Most users don't know there are actually two cyclers, one in the
package, and one internal to matplotlib. So, they work off of the
documentation for the package. So, if you want to get rid of the two-arg
form, you need to get rid of it there first.

The tricky part for deprecation is that, IIRC, the matplotlib cycler
construction is largely pass-through. So, it you deprecate it there first,
you would need to write a bit of shim code to convert the two-arg form into
the keyword form under-the-hood. Seriously, is it really worth the effort
to go through this for something that isn't broken? Don't forget that
you'll have to update all of the unit tests, too.

I am totally fine with not having examples with the two-arg form, but I
really just don't see the point in getting rid of it. I think we got bigger
fish to fry, here.

**Pull request merged**
