### PR TITLE
Fix Axes `get_children` order to match `draw` order

### PR DESCRIPTION
**Pull request by blink1073**
`get_children` is used by `hitlist`, and should match the ordering used by `draw`.  Also consolidates so the order is only established in one place, and `draw` calls `get_children` to get the proper ordering.

### CODE REVIEW

**Comment by blink1073** [comment]
I would recommend *using* `get_children` in `draw`, and then *removing* artists if they are not going to be rendered.

**Comment by blink1073** [comment]
On a side note, I should have started hacking on `matplotlib` at least three years ago, this is a lot of fun.

**Comment by tacaswell** [comment]
Looks good to me.  This should probably be documented in https://github.com/matplotlib/matplotlib/tree/master/doc/api/api_changes .

:+1: on re-using this in `draw`, the more we can reduce the size of the library the better.

**Comment by blink1073** [comment]
Done on both fronts.

**Comment by tacaswell** [comment]
This broke all of the builds

```

======================================================================
FAIL: matplotlib.tests.test_collections.test_polycollection_close.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 51, in failer
    result = f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 196, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.noseclasses.ImageComparisonFailure: images not close: /home/travis/build/matplotlib/tmp_test_dir/result_images/test_collections/polycollection_close.png vs. /home/travis/build/matplotlib/tmp_test_dir/result_images/test_collections/polycollection_close-expected.png (RMS 16.460)

======================================================================
FAIL: matplotlib.tests.test_table.test_label_colours.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 51, in failer
    result = f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 196, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.noseclasses.ImageComparisonFailure: images not close: /home/travis/build/matplotlib/tmp_test_dir/result_images/test_table/table_labels.png vs. /home/travis/build/matplotlib/tmp_test_dir/result_images/test_table/table_labels-expected.png (RMS 21.070)

======================================================================
FAIL: mpl_toolkits.tests.test_mplot3d.test_mixedsubplots.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 51, in failer
    result = f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 196, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.noseclasses.ImageComparisonFailure: images not close: /home/travis/build/matplotlib/tmp_test_dir/result_images/test_mplot3d/mixedsubplot.png vs. /home/travis/build/matplotlib/tmp_test_dir/result_images/test_mplot3d/mixedsubplot-expected.png (RMS 13.760)

======================================================================
FAIL: mpl_toolkits.tests.test_mplot3d.test_mixedsubplots.test
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 51, in failer
    result = f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/matplotlib-1.5.dev1-py3.4-linux-x86_64.egg/matplotlib/testing/decorators.py", line 196, in do_test
    '(RMS %(rms).3f)'%err)
matplotlib.testing.noseclasses.ImageComparisonFailure: images not close: /home/travis/build/matplotlib/tmp_test_dir/result_images/test_mplot3d/mixedsubplot_pdf.png vs. /home/travis/build/matplotlib/tmp_test_dir/result_images/test_mplot3d/mixedsubplot-expected_pdf.png (RMS 20.466)

```

**Comment by blink1073** [comment]
Hopefully that does it.

**Comment by tacaswell** [comment]
This is a change to a core-enough part of the library this needs to be looked at by at least a few more people.

cc @mdboom @efiring @WeatherGod @pelson

**Comment by blink1073** [comment]
Ha!  *Drawing* is a core part of the library?

**Comment by blink1073** [comment]
(tongue in cheek of course)

**Comment by blink1073** [comment]
Passes now (waiting on build docs, holy smokes it takes a while to build those suckers).

**Comment by efiring** [comment]
I like the idea of fixing the order in `get_children()`.  Looking at this brings the following thought:  it seems a little odd to have to get all of the children and then throw away half of them because they are special cases--the patch, the frame, etc.  Would it make sense to let `get_children()` take an argument to determine whether it returns all children, or just the ones in a category?  There seem to be two major categories: the artists directly associated with the Axes, and those that can be considered data.  I haven't looked closely, so chances are I am missing something.

**Comment by tacaswell** [comment]
@efiring I agree that makes sense, but want to punt on that to get this merged ASAP (so it gets some usage by the brave souls running master before we tag) .

It might be useful to let `get_children` (or a slightly differently named sibling method) take a function as an input so you could use it as a filter ex `get_children(filter=lambda x : isinstance(x, Line2D))`.

Explicitly tagging Artists as being 'infrastructure' or 'data'  (or whatever) is probably something we should think about in the coming Great Artist Refactor of '15.

**Comment by WeatherGod** [comment]
This sort of touches on a similar theme I raised in a PR (I don't have the
number on me), where I wanted to be able to select the order in which
elements of a collection are drawn. I did it by keeping a private attribute
that can be supplied to numpy arrays (so it can be indexes, slice or
boolean array). Maybe it could be generalizable?

**Pull request merged**
