### PR TITLE
Remove some wx version checks.

### PR DESCRIPTION
**Pull request by anntzer**
mpl3 wx supports any wxpython that does support Py3 (i.e., wwpython>=4),
so we can drop the version checks.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jenshnielsen** [comment]
That presumably also means that is_phoenix will always evaluate to True as phoenix is the codename for wx 4.x which should allow significantly more code to be deleted.

**Comment by anntzer** [comment]
yup, but that'll be another PR.

**Comment by jenshnielsen** [comment]
Ok sure but then your title is slightly misleading ;) you are only dropping part of the version checks.

**Comment by anntzer** [comment]
rebased

**Pull request merged**
