### PR TITLE
Don't clip colorbar dividers

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary
They are sometimes right on the edge of the `Axes`, and the last (or possibly first) don't get drawn due to clipping. Because the divider line width is the same as the `Axes` frame line width, we don't have to worry about it going outside when unclipped.

Fixes #22864

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by oscargus — APPROVED** [review]

**Comment by jklymak** [comment]
I think we can zoom in on colorbar axes now, though, and we can certainly set the x/ylimits.  Won't these now dangle in space if we do that?

**Comment by QuLogic** [comment]
I was thinking that, but when I tried it with the original example, I was unable to pan or zoom the colorbar. Did it break, or is the test not sufficiently set up to allow it?

**Comment by greglucas** [comment]
I don't see these dangling in space if I test the original example with this...

```python
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt  
from matplotlib.colors import from_levels_and_colors

my_cmap = mpl.cm.viridis
bounds = np.arange(10)
nb_colors = len(bounds) + 1
colors = my_cmap(np.linspace(100, 255, nb_colors).astype(int))
my_cmap, my_norm = from_levels_and_colors(bounds, colors, extend='both')

plt.figure(figsize=(5, 1))
ax = plt.subplot(111)
cbar = mpl.colorbar.ColorbarBase(ax, cmap=my_cmap, norm=my_norm, orientation='horizontal', drawedges=True)
cbar.ax.set_xlim(2, 10)
cbar.ax.set_navigate(True)
plt.subplots_adjust(left=0.05, bottom=0.4, right=0.95, top=0.9)
plt.show()
```

Because it is a `BoundaryNorm` we disable interaction:
https://github.com/matplotlib/matplotlib/blob/02e93e23ac855a42697990e9ef17d28e3097987f/lib/matplotlib/colorbar.py#L474-L477
Manually enabling interaction moves the colors, but not the boundary lines, so those will not move around either apparently?

**Comment by QuLogic** [comment]
Going back to what pan/zoom on the Colorbar means, it moves the norm limits, and then moves the axis to match, so the colours and the dividers _never_ move.

Calling `set_xlim` can break things though:
image

**Comment by QuLogic** [comment]
This now tests with `set_xlim` as well as the other vertical orientation. It should produce a divider at the right places now even when the limits have been changed.

**Pull request merged**
