### PR TITLE
FIX: Remove some numpy function overrides from pylab

### LINKED ISSUE #25379: [TST] Upcoming dependency test failures
The weekly build with nightly wheels from numpy and pandas
has failed. Check the logs for any updates that need to be
made in matplotlib.
https://github.com/matplotlib/matplotlib/actions/runs/4329604936

### PR DESCRIPTION
**Pull request by greglucas**
## PR Summary

Numpy added round, max, min to their exported names which we don't want when we import * from Numpy.

xref: https://github.com/numpy/numpy/pull/23302

closes #25379

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by rcomer — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Comment by chrisjbillington** [comment]
FYI, Numpy 1.25 is now out with the changes, and this fix hasn't yet made it into a matplotlib release. Currently, importing * from pylab currently shadows the builtin max and min functions with the latest release of both libraries.

**Comment by rcomer** [comment]
Thank you @chrisjbillington.  We are hoping to release Matplotlib v3.8 in July, so I suggest pinning numpy back to 1.24 until then.

Note that use of pylab is [strongly discouraged](https://matplotlib.org/stable/api/index.html#module-pylab), and I think this problem is a good illustration of why.  So if you have code that is breaking because of this, it would be better to update to not use pylab.  I appreciate it can be difficult to find time to update old legacy code though.

**Comment by chrisjbillington** [comment]
Thanks for the timeframe.

Yes, understood, we're only using pylab because it seemed like a good idea about 13 years ago, and haven't yet made the backward incompatible (since users may access pylab names via our library) change of removing it, but it's on the wish list!

**Comment by rcomer** [comment]
@chrisjbillington you may have already seen, but v3.7.2 was just released with this fix.

**Comment by chrisjbillington** [comment]
@rcomer I hadn't, thanks for letting me know!

**Pull request merged**
