### PR TITLE
Extended the convolution filter for correct dilation

### PR DESCRIPTION
**Pull request by chbauman**
Changed the convolution filter from [1, 1] to [1, 1, 1] such that the mask is dilated on both sides, not only at the end.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks for the PR.  I can imagine this is correct.  Do you have some examples showing the previous version did bad things and this is better?

**Comment by chbauman** [comment]
Hi,

The following plots show the difference, they can be regeneratue using the
given example (https://matplotlib.org/gallery/event_handling/resample.html)
and setting ax.set_xlim
<https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_xlim.html#matplotlib.axes.Axes.set_xlim>(232,
234) instead of ax.set_xlim
<https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_xlim.html#matplotlib.axes.Axes.set_xlim>
(16, 365).

The first plot shows how it was before the PR and the second shows how it
will be after. As you can see, the first plot seems to start somewhere at
about 232.175, but actually the data is provided many timesteps before that
(from x-range = 16 to ..) Therefore, it makes sense that the line would
start before the first point that is shown in the first plot.

This is all the PR is about, the extended convolution filter makes sure
that the mask includes a point that lies before the shown x-range.



[image: 1_1.png]

[image: 1_1_1.png]

Thanks for reviewing and have a nice weekend,
Chris


Am Fr., 15. Jan. 2021 um 16:30 Uhr schrieb Jody Klymak <
notifications@github.com>:

**Comment by jklymak** [comment]
Your images didn't make it through via email.

**Comment by chbauman** [comment]
This should work I guess.

**Comment by chbauman** [comment]
The following plots show the difference, they can be regeneratue using the given example (https://matplotlib.org/gallery/event_handling/resample.html) and setting ax.set_xlim(232, 234) instead of ax.set_xlim(16, 365).
The top image shows how it was before, the one below shows how it looks with the proposed changes.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
Makes sense to me.  Thanks a lot!

**Pull request merged**
