### PR TITLE
DOC: make canonical version stable

### LINKED ISSUE #12374: Examples in docs should be redirected to latest version number
_Originally posted by @anntzer in https://github.com/matplotlib/matplotlib/pull/12244#issuecomment-426337602_

There's no redirection right now.  I think we should redirect matplotlib.org/gallery/... to matplotlib.org/$version/gallery/... (which is what cpython does) so that people don't bookmark links that will be broken in the future, but that's a wholly separate issue...

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Depends on https://github.com/matplotlib/matplotlib.github.com/pull/47

Makes `matplotlib.org/stable` the canonical root.  

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Added an update of `release_guide.rst` to explain how to maintain this upon release...

**Comment by jklymak** [comment]
I think this is right for now.  

It would be nice if "canonical" *changed* for the newest version of an obsolete page.  However, for now I think its best for search engines to try and find it at `/stable/`

**Comment by jklymak** [comment]
If matplotlib/matplotlib.github.com#49 goes in, this will need to be slightly modified

**Comment by jklymak** [comment]
This has been modified to take into account  matplotlib/matplotlib.github.com#49

**Review by QuLogic — APPROVED** [review]
I'm not an SEO expert, but this sounds good.

**Review by tacaswell — APPROVED** [review]

**Pull request merged**
