### PR TITLE
DOC: make all links in whats_new anonymous

### PR DESCRIPTION
**Pull request by tacaswell**
No idea what changed that made 1.5.x start failing doc builds.  Maybe this will fix it.

### CODE REVIEW

**Comment by mdboom** [comment]
Yeah -- weird this didn't happen before.  Hopefully it will help.

**Comment by tacaswell** [comment]
It looks like https://github.com/matplotlib/matplotlib/commit/f04b6c9a53b7991dc3ff6400477946097309f720#diff-61e12c21f86c98bcad67f7d3446516efL2005 that is the change that broke it.  Maybe the issue is that both the name and target are the same?

**Comment by mdboom** [comment]
I think the issue is that the same name is used twice in the whole sphinx document.  I always thought that was a bit heavy-handed of Sphinx, but at least the anonymous link thing gets around it.

**Comment by tacaswell** [comment]
This fixed the doc build, don't really understand _why_ it broke, but it is un-broken now (just waiting on the 2.6 build to re-run).

**Comment by jenshnielsen** [comment]
Merged I think the missing end bracket on the matplotlib-users link was the real issue. This is fixed in this pr too so that is fine

**Pull request merged**
