### PR TITLE
TEST: Merge pull request #6442 from matthew-brett/dynamic-tkagg

### PR DESCRIPTION
**Pull request by efiring**
MRG: loading TCL / Tk symbols dynamically

cherry-pick of commit f3e5576

Conflicts resolved:
    .travis.yml
    appveyor.yml
    setupext.py

### CODE REVIEW

**Comment by efiring** [comment]
I am testing this backport of #6442 via this PR so that all the checks will be run on it. If it works, I can push it directly.

**Comment by matthew-brett** [comment]
OSX builds from this branch passing [here](https://travis-ci.org/MacPython/matplotlib-wheels/builds/132645765).

**Comment by matthew-brett** [comment]
Download OSX wheels from this branch for testing: [Python 2.7](http://wheels.scipy.org/matplotlib-1.5.2rc1%2B12.g7069119-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl), [Python 3.4](http://wheels.scipy.org/matplotlib-1.5.2rc1%2B12.g7069119-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl) [Python 3.5](http://wheels.scipy.org/matplotlib-1.5.2rc1%2B12.g7069119-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)

**Comment by efiring** [comment]
I fixed the backport by removing appveyor.yml, and pushed b80e0f1 to v1.5.x.  Closing.

**Pull request closed without merging**
