### PR TITLE
Backport PR #22732: FIX: maybe improve renderer dance

### PR DESCRIPTION
**Pull request by tacaswell**
Merge pull request #22732 from jklymak/fix-renderer-dance

FIX: improve cached renderer dance
(cherry picked from commit 9e0eb54fd98bb804f51a74101db88164870a2458)

The changes had to be moved to figure.py due to a major refactoring that will
be released in 3.6 that is already on main.

### CODE REVIEW

**Comment by tacaswell** [comment]
This should be reviewed carefully because it is essentially a different patch than in #22783 due to code having moved around.

**Comment by jklymak** [comment]
@tacaswell I took the liberty of pushing a typo fix to your branch....

**Comment by tacaswell** [comment]
I manually tested the two cases again

```python

import matplotlib.pyplot as plt

plt.rcParams['figure.autolayout'] = 'True'

plt.plot([1, 2, 3], [1, 2, 3], 'o-')
plt.title(r'$\sum_{i=0}^{\infty} x_i$ just a test')
plt.savefig('/tmp/test2.eps', format='eps')

```

(interactively)

```python
from matplotlib import pylab as plt
plt.rcParams['savefig.format'] = 'pdf'
plt.ion()

fig, ax = plt.subplots()
ax.plot([0,1])
fig.tight_layout()


```

and both appear to work.

**Comment by tacaswell** [comment]
I may have jumped the gun on merging this, sorry about that.

**Pull request merged**
