### PR TITLE
correct use of ax.barh that preserves order

### PR DESCRIPTION
**Pull request by diemoschwarz**
this example is wrong when the labels (question texts) are not alphabetically ordered (barh reorders them, losing connection with labels).
There's also a dependency on dict preserving keys order, which is true only for python >= 3.7.
(I just spent half a day of my life figuring this out, and would like spare others this chore =-)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
We don't sort categorical keys since matplotlib 2.2.  Are you on 2.1?
Also, even though 3.6 does not *guarantee* key-ordering, in practice keys *are* ordered there.  Or do you have an example where they are not?

**Comment by diemoschwarz** [comment]
thanks for checking!  matplotlib 2.0.2

**Comment by anntzer** [comment]
OK, so I guess this can be closed?
Examples are only supposed to be run on the corresponding Matplotlib version.

**Comment by diemoschwarz** [comment]
understood, thanks!

**Pull request closed without merging**
