### PR TITLE
Fix for scatter not showing points with valid x/y but invalid color

### PR DESCRIPTION
**Pull request by QiCuiHub**
## PR Summary
Fix for #4354 scatter points being ignored when they have a valid x,y but invalid color such as np.nan or np.inf

### CODE REVIEW

**Comment by jklymak** [comment]
This PR seems reasonable to me.  However, the `masked` kwarg is ambiguous, so I think some other name should be chosen.  `plotinvalid` or `showinvalid`?

**Comment by QiCuiHub** [comment]
@jklymak you are right, we decided to change it to plotinvalid

**Comment by efiring** [comment]
The goal is reasonable; I can see the argument for using the "set_bad" color for masked or otherwise invalid points.

I think the implementation will need quite a bit more thought and testing, however.  As it stands, with plotinvalid=True, there is a huge change in behavior, affecting much more than the handling of colormapping: the deletion of points masked based on other variables (x, y, size, etc.) is disabled.

This is related to #10381.

**Comment by jklymak** [comment]
Ping @QiCuiHub is this still something you want to go in?  We should clear up any hesitation @efiring has.

**Comment by jklymak** [comment]
Closing in lieu of #12422.  Thanks for getting the ball rolling @QiCuiHub !

**Pull request closed without merging**
