### PR TITLE
added Stairs to basic plot types

### LINKED ISSUE #23204: [Doc]: More plot types?
### Documentation Link

https://matplotlib.org/stable/plot_types/index.html

### Problem

Most of the plot types are shown here, although not all. I guess it is really a good starting point for a newcomer, but also useful for a more experienced person to see what is possible "out of the box".

I wasn't even aware of the magnitude_spectrum etc, but was originally opening for psd/csd.

### Suggested improvement

Should there be a section for "Signal processing plots"? Related: #22920 so maybe not all if we are deprecating mlab (but the plots that relies on numpy can stay?).

`stairs` should be added to basic plot types.

`semilog*`, `loglog`? (Good for a newcomer if nothing else.)

### PR DESCRIPTION
**Pull request by mariamalykh**
## PR checklist

- [ ] "closes #23204" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by mariamalykh** [comment]
Yes, but I can't do it with my access. Can you delete step plot type?

**Comment by mariamalykh** [comment]
> @mariamalykh you should be able to delete it locally on your working branch and push that change up. If you do, then the file will be deleted once your PR is merged.
> 
> Though I disagree with deleting it & would like plot types to be a bit more comprehensive with respect to the plotting methods - imshow and pcolormesh also produce similar plots and the difference is in how the data is structured just like stairs vs. step and imshow and pcolormesh are in the plot gallery.

maybe that's why we should accept the 1st variant of the request, it has passed all the autotests

**Comment by jklymak** [comment]
Stairs and step are the same, just with different ways of specifying the step edges.  The imshow and pcolormesh are similar, but pcolormesh is much more flexible on the spacing and location of the x and y grids.  If someone proposed adding pcolor or pcolorfast to the basic plot types I would also object that they are the same as pcolormesh and are not needed. In my opinion having stair and step on this page just clutters the page and is more mystifying than helpful.  

I think that both here and in the method documentation both methods should refer to each other.

**Comment by rcomer** [comment]
@mariamalykh your branch is quite far behind our repo’s main branch.  The file you are trying to delete had been updated here since you created your fork.  You will need to [rebase](https://matplotlib.org/devdocs/devel/development_workflow.html#rebasing-on-upstream-main) to pick up those changes, and then the deletion should work.

**Comment by jklymak** [comment]
Remember to do "git rm" or "git mv" so git knows about the change.

**Comment by rcomer** [comment]
There is a related PR in the cheat sheets: https://github.com/matplotlib/cheatsheets/pull/112

**Pull request closed without merging**
