### PR TITLE
Improve docs on automated tests

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

- Mention Azure pipelines
- Add tips for finding the cause of failed tests.
- Mention that Codecov and LGTM are for information only, i.e. not necessarily a blocker for merging.

### CODE REVIEW

**Comment by QuLogic** [comment]
Do you also want to mention that [Azure has image artifacts](https://github.com/matplotlib/matplotlib/pull/17011#issuecomment-608208071) if a tests fail?

**Comment by timhoffm** [comment]
Makes sense. Would you mind adding a description how to find these? I don't have a clear picture of that yet.

**Comment by QuLogic** [comment]
Unfortunately, I don't see any quick link to artifacts. Feel free to massage this into something useful:
> Go to the Azure check, and click "View more details on Azure Pipelines". If you clicked on the overview, then the "Related" section should list a "# artifacts" link. If you clicked on a Job, then there should be a "# artifacts" link in the log.

Note, you won't see it on this PR because they're only posted on failure to save space.

**Comment by timhoffm** [comment]
Added a section on image artifacts on Azure.

**Pull request merged**
