### PR TITLE
DOC: Update INSTALL.rst

### PR DESCRIPTION
**Pull request by AnkurDedania**
## PR Summary

fix command typo in INSTALL.rst

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
Are there cases where `python -mpip ...` gives a different result than `python -m pip ...`?

**Comment by QuLogic** [comment]
I don't think so. While it's true that single-letter options can be combined after a single dash (e.g., `-sv`), `-m` is documented as terminating the option list, and it does, since `-mpip` neither errors due to unknown option (`-p` is not an option), nor causes interactive inspection (`-i`).

**Comment by tacaswell** [comment]
I am 50/50 on this.  I normally do `pytthon -mpip` because I am lazy, but also see the case that adding the space is clearer.

**Comment by anntzer** [comment]
I'd rather leave it as -mpip, let's say -0.

**Comment by tacaswell** [comment]
@meeseeksdev backport to v3.0.0-doc

**Comment by Carreau** [comment]
@meeseeksdev backport to v3.0.0-doc

**Comment by AnkurDedania** [comment]
Looking at the code, I found other files referencing `python -mpip ...`

**Pull request merged**
