### PR TITLE
Use svg instead of png for website logo

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

This reverts an accidental flip svg -> png introduced in #10065. Sorry for the error!

### CODE REVIEW

**Comment by tacaswell** [comment]
We should look into trying to shirk the svg before we make this change.  The png in 20k, the svg is 128k.

**Comment by timhoffm** [comment]
I've compressed the svg from 128k to 11k using https://vecta.io/nano (precision level 2). That includes a slightly lossy compression (nodes are slightly moved), but you won't notice unless really flipping back and forth on larger magnifications.

**Comment by tacaswell** [comment]
I spoke with @dorafc about this.  Her only concern was if all browsers would support this.  According to https://caniuse.com/#feat=svg everything but dangerously out of date IE does.  There is a handful (~130 / 276,000 in the last week) of users who would be hit by this but it is probably but it is not enough to worry about.

**Comment by tacaswell** [comment]
I'm working on backporting this to the 3.1 series.

**Comment by tacaswell** [comment]
Backported directly to v3.1.1-doc as 7830e2643 and will get onto v3.1.x by merging v3.1.1-doc into v3.1.x before tagging v3.2.0.

**Pull request merged**
