### PR TITLE
Fix lw float cast

### PR DESCRIPTION
**Pull request by tacaswell**
there is a `set_linewidth` in `backend_gdk.py`, but it calls the parent class `set_linewdith` which already has the needed cast.

### CODE REVIEW

**Comment by tacaswell** [comment]
Closes #4306

**Comment by efiring** [comment]
This looks reasonable and will do the job--but I'm still uncomfortable with the idea of  supporting `plot(x, y, lw='1.5')`.  To me, this is just bad code that is slipping through because we have placed a low priority on argument validation, it is contrary to the documentation, and therefore it is not something we have to support in the future--it was only half-supported by accident.  I don't see any use-case justification for it.

**Comment by tacaswell** [comment]
On the other hand, supporting 'float like' seems very much in the spirit of python and duck typing.  This will also clean up any issues with scalar numpy arrays or integers going through.

**Comment by efiring** [comment]
A string does not behave like a number, so no, it is not in the spirit of duck typing.  A string is not "float-like" at all.  It doesn't pass our `is_numlike()` duck-typing test. I don't object to using the float cast if it helps homogenize things that would otherwise cause trouble in the lower levels, but I don't like the idea of thinking of a string representation of a float as equivalent to a float.  In color spec parsing a string representation of a float is used for gray; the distinction between the string and a true number is critical.

**Comment by tacaswell** [comment]
Fair enough, I was using 'float-like' <-> `float(foo)` does not fail.  

I had forgotten that detail in the colorspec.

The alternative I see is

```python
if is_numlike(lw):
    lw = float(lw)  # still want to homogenize for down stream I think
else:
    raise ValueError("...")
```

My inclination is to be as permissive as possible, but will change them all over to this form if you want.

**Comment by efiring** [comment]
This brings us to some strategy questions regarding input argument validation that should be addressed but can be deferred.   For the time being I don't mind leaving the PR as-is; but I don't want it to be seen as endorsing or even officially supporting string inputs where numbers are called for.

**Comment by tacaswell** [comment]
Fully on board with not endorsing string input for linewidth and would have no problem breaking this API with out warning (so long as we push the exception way up the interaction stack).

**Pull request merged**
