### PR TITLE
Raise on missing closing quotes in matplotlibrc

### LINKED ISSUE #22636: [Bug]: Infinite loop when there is single double quote in matplotlibrc
### Bug summary

This code https://github.com/timhoffm/matplotlib/blob/7c378a8f3f30ce57c874a851f3af8af58f1ffdf6/lib/matplotlib/cbook/__init__.py#L403-L415 on the main branch (not released yet) falls into an infinite loop when there is only one double quotation because when `s.find('"', quote_pos + 1) == -1` `pos == 0`

context:
- https://github.com/matplotlib/matplotlib/pull/22589
- https://github.com/matplotlib/matplotlib/issues/19288

### Code for reproduction

```python
from pathlib import Path

import matplotlib.pyplot as plt

Path("./test.mplstyle").write_text('grid.color: "aa')
plt.style.use("./test.mplstyle")
```

### Actual outcome

The program doesn't exit.

### Expected outcome

Show an error or set `'"aa'`.

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.6.0.dev1816+gb9ae51ca8c.d20220311

### Matplotlib Backend

_No response_

### Python version

Python 3.10.0

### Jupyter version

_No response_

### Installation

_No response_

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Closes #22636.

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Are we sure we have no legitimate value which will have one `"` in it ?

**Comment by timhoffm** [comment]
Single `"` should be escaped: `"Use backslash to escape \" in a quoted string"`.

This is e.g. also the behavior in YAML, which supports quoted and unquoted strings.

**Comment by oscargus** [comment]
Should the error message say that? (Espace single ").

**Review by oscargus — APPROVED** [review]

**Comment by timhoffm** [comment]
Added a note on escaping to the exception message.

**Pull request merged**
