### PR TITLE
Fix issue with shared x-axis resetting when calling cla() on shared axes

### LINKED ISSUE #27825: [Bug]: Axes.cla() with sharex may wrongly reset the axes limit.
### Bug summary

For example, when  subplot A shares the x-axis with subplot B (A is created with sharex=B), a call to `B.cla()` will set the xlimit to [0, 1], which may not be expected (in contrast, a call to `A.cla()` will not change the xlimit).

I think the main problem comes from the following function, where it will check whether its `_sharex` attribute is `None`; however, in this case, B is shared to A, but no axis is shared to B, so B's `_sharex` attribute is `None`.
https://github.com/matplotlib/matplotlib/blob/9e18a343fb58a2978a8e27df03190ed21c61c343/lib/matplotlib/axes/_base.py#L1369   

### Code for reproduction

```Python
ax = plt.subplot(211)
ax2 = plt.subplot(212, sharex=ax)
ax.plot(range(50))
ax2.plot(range(50))
ax.cla()
plt.show()
```

### Actual outcome

image

### Expected outcome

image

### Additional information

_No response_

### Operating system

_No response_

### Matplotlib Version

3.8.3

### Matplotlib Backend

'TkAgg'

### Python version

3.9.13

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by ydotwang**
## PR summary

Fix bidirectional axis sharing in sharex, sharey, and __clear methods

Description:
This pull request addresses issues related to the handling of shared axes (sharex and sharey) in Matplotlib, particularly in scenarios involving clearing of axes.

Summary of Changes:
Bidirectional Sharing:
The sharex and sharey methods have been updated to ensure bidirectional sharing of axes. Previously, when axis A shared its x-axis with axis B, changes to B would not affect A. This has been corrected by ensuring that B also shares its x-axis back with A.

Impact:
These changes resolve the issue where shared axes would not behave symmetrically, leading to unexpected behavior when clearing axes or working with inverted axes. The updates ensure consistent and predictable behavior in shared axes scenarios.

Before PR:
image

After PR:
image

Testing:
Existing tests related to shared axes should be reviewed to ensure they cover these scenarios. New tests can be added to specifically verify bidirectional sharing and correct inversion handling during clearing.
This pull request ensures that Matplotlib handles shared axes in a robust manner, improving the overall user experience when working with subplots and synchronized axes.

## PR checklist

- [ ] "closes #27825" is in the body of the PR description to [#27825](https://github.com/matplotlib/matplotlib/issues/27825)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)

### CODE REVIEW

**Review by Oliver-lab-dev — APPROVED** [review]

**Comment by rcomer** [comment]
Thanks for your contribution @ydotwang!  Please could you add a [test](https://matplotlib.org/devdocs/devel/testing.html) to ensure this behaviour does not break again in future?

**Comment by timhoffm** [comment]
This is a dupliate. The approach was suggested in the [original issue](https://github.com/matplotlib/matplotlib/issues/27825#issuecomment-2065382495) and the poster already made a PR (#28101). Discussion should continue in that PR.

**Comment by ydotwang** [comment]
> Thanks for your contribution @ydotwang! Please could you add a [test](https://matplotlib.org/devdocs/devel/testing.html) to ensure this behaviour does not break again in future?

Hi, I see. I would like to write tests for this! Could you give me some advice?

**Comment by timhoffm** [comment]
@ydotwang thanks for the interest. It's currently not possible to write a test. The solution of mutually sharing Axes would solve the concrete issue, however it would introduce other issues. The proper way forward is laid out in https://github.com/matplotlib/matplotlib/pull/28101#issuecomment-2067640782, but it's a non-trivial rearchitecturing. Tests will need to be written in the process of that migration.

**Comment by ydotwang** [comment]
> @ydotwang thanks for the interest. It's currently not possible to write a test. The solution of mutually sharing Axes would solve the concrete issue, however it would introduce other issues. The proper way forward is laid out in [#28101 (comment)](https://github.com/matplotlib/matplotlib/pull/28101#issuecomment-2067640782), but it's a non-trivial rearchitecturing. Tests will need to be written in the process of that migration.

Thank you for your answer!

**Pull request closed without merging**
