### PR TITLE
[WIP]Removed pyplot.plotting()

### PR DESCRIPTION
**Pull request by SidharthBansal**
## PR Summary

Removed pyplot.plotting()

Part of #16181

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
Unfortunately, it's not as simple as just removing the function. If it was just removing one line of code, we'd likely done that already 😄.

There's code that generates the docstring.

It's used here in the docs https://matplotlib.org/api/pyplot_summary.html#matplotlib.pyplot.plotting, which is partly redundant with https://matplotlib.org/api/_as_gen/matplotlib.pyplot.html#module-matplotlib.pyplot. This mess has to be cleaned up along the way.

Steps to do (I haven't looked into the details so I might be wrong somewhere. Please check yourself that this makes sense):
- Check both docs and verify that the latter is equivalent to the former, so that we can drop the function listing exposed via the `plotting()` docstring.
- Replace the former by the latter. Ideally, the colors stuff should be moved somewhere else. IMHO it does not belong into the pyplot module docstring. It may also be redundant, but t.b.c.
- Remove `plotting()` and the code that populates its docstring.

**Comment by SidharthBansal** [comment]
Thanks for the steps. I will do it asap.

**Comment by tacaswell** [comment]
#16181 was merged without `plt.plotting()` being removed.  Combined with this PR being dormant for over 2 years I am going to close this PR. 

Thank you for your work even if we did not merge it @SidharthBansal and I hope we hear from you again!

**Comment by QuLogic** [comment]
`pyplot.plotting` was removed in #22669.

**Pull request closed without merging**
