### PR TITLE
Force installation of wx from whl, not from pypi.

### PR DESCRIPTION
**Pull request by anntzer**
It appears that travis is still trying to build wxpython from source (https://travis-ci.org/matplotlib/matplotlib/jobs/289866130#L1365).  Try to force it to really not use pypi, but wxpython's own servers...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Ah, of course, that's because there's no wheel for ubuntu14.04+py36 (compare https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/ and https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04/).  @RobinD42 would you consider providing such a wheel?  Thanks.

**Comment by efiring** [comment]
Ubuntu 14.04 plus Py3.6 seems like an odd combination; are we stuck with that because of the way Travis works?

**Comment by anntzer** [comment]
yes

**Comment by dopplershift** [comment]
I don't think 14.04 + 3.6 is all that weird, though. 14.04 is an LTS release for Ubuntu.

**Comment by RobinD42** [comment]
I've added Python 3.6 builds for Ubuntu 14.04 to the build script, and have uploaded wheels for 4.0.0b2.

**Comment by tacaswell** [comment]
Thanks @RobinD42 !

**Pull request merged**
