### PR TITLE
Move enumeration of text tutorial into table.

### PR DESCRIPTION
**Pull request by anntzer**
making the table proposed at https://github.com/matplotlib/matplotlib/pull/9827/files#r152655635 (attn @jklymak)

### CODE REVIEW

**Comment by jklymak** [comment]
Ha, now if only the sphinx docs had a nice example like that!  ... that I could find... or that I could understand.  Anyway, thanks so much - looks great I'll merge when we can check it works ;-)

**Comment by anntzer** [comment]
http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#tables

**Comment by jklymak** [comment]
OK, there *was* an example in that second link that had the lines wrapping that I missed.  I wouldn't say its super obvious!

**Comment by anntzer** [comment]
Well you have to like reading spec-like docs (rather than tutorial style), which is definitely an acquired taste...

**Pull request merged**
