### PR TITLE
Use the right function to disable the offset

### LINKED ISSUE #16232: set_useOffset(False) is not working
Hi,

I try to disable the offset computed to label the axes in the plot.

It looks like the global or local set of `useOffset` is just ignored.

**Code for reproduction**

```python
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.axisartist.axislines import Subplot

# Disable it globally
matplotlib.rcParams["axes.formatter.useoffset"] = False

fig = plt.figure(figsize=(3, 3))

ax = Subplot(fig, 111)
fig.add_subplot(ax)

ax.axis["right"].set_visible(False)
ax.axis["top"].set_visible(False)

# Disable it locally
ax.get_yaxis().get_major_formatter().set_useOffset(False)

ax.set_ylim(10 ** 8, 10 ** 8 + 1)

print(ax.get_yaxis().get_major_formatter().useOffset)
# > False

plt.show()
```

**Actual outcome**

Screenshot from 2020-01-15 17-21-52

**Expected outcome**

We should not see the `1e8` and the axis should be labelled without the remove of the offset.

**Matplotlib version**

* matplotlib 3.1.1

### PR DESCRIPTION
**Pull request by vallsv**
## PR Summary

This PR update the example from the documentation to use the proper function to avoid using scientific offset in the plot.

Relative to this discussion #16232

Closes #16232

Fill free to close this PR and the related issue if it do not fit.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
Interestingly, 

     ax.plot(np.arange(2000, 2010), range(10))

does not result in any offset with current matplotlib. Hence this needs to change anyways for the whole paragraph to make sense. 

So suppose it is 

    ax.plot(np.arange(20000, 20010), range(10))

instead. Then, using `ax.get_xaxis().get_major_formatter().set_useOffset(False)` does indeed get rid of the offset, just as currently described in that part.

Concerning the "multiplicative offset", another example can be added. E.g. if

    ax.plot(np.linspace(0, 3e8, 301), range(301))

then adding `ax.get_xaxis().get_major_formatter().set_scientific(False)` will remove the  "multiplicative offset".


The difference between the two is not well documented anywhere. So it would in addition make sense to add a respective paragraph in the [ticks-and-ticklabels](https://matplotlib.org/tutorials/text/text_intro.html#ticks-and-ticklabels) section of the text tutorial.

**Comment by vallsv** [comment]
Thanks a lot. If you fix the matplotlib behavior in order to provide 2 independent concepts for offset and scientific notation, it is far better.

But if you only update the docstring, you only provident documentation which do not match the actual matplotlib behavior. So, do you plan to fix the behavior? Is there a related issue i can follow?

Thanks a lot.

**Comment by timhoffm** [comment]
Offsets and scientific notation are two independent concepts, and IMO work as they should. This is only a documentation issue. See #17590, #17592.

**Comment by vallsv** [comment]
Definitely not. Else, disabling scientific notation should not be needed to disable the offset.

This said, i did not checked it again since January.

**Comment by vallsv** [comment]
Oh, yes, in fact the issue was on my PR description #16232

**Comment by timhoffm** [comment]
I've commented in #16232 on that.

**Comment by vallsv** [comment]
I see, there is an offset and a factor. Thanks a lot for the clarification.

**Pull request closed without merging**
