### PR TITLE
Mark all extensions as free-threading safe

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

This PR includes all the current and future pybind11 PRs, so it might be rebased or otherwise modified without notice. So don't bother reviewing any of the changes, unless you want to note them in the original PRs.

The only important thing here is the resulting wheels, which should be useful for testing.

@greglucas

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by tacaswell** [comment]
I put together this script to test our thread safety:

```python
import threading
from pathlib import Path
import time

import numpy as np
import matplotlib.figure as mfigure

target = Path("/tmp/p_test")
target.mkdir(parents=True, exist_ok=True)

ω = 2
N = 1024 * 10

N_threads = 70


def gen_frames(steps):
    fig = mfigure.Figure(layout="constrained")
    ax = fig.subplots()
    ax.set_xlim(0, 2 * np.pi)
    ax.set_ylim(-1.1, 1.1)
    # ax.axis("off")

    x = np.linspace(0, 2 * np.pi, 1024 * 10)
    (ln,) = ax.plot(x, np.ones_like(x))

    fr_ann = ax.annotate(
        "step:        ",
        (1, 1),
        xytext=(-1, -5),
        xycoords="axes fraction",
        textcoords="offset points",
        ha="right",
        va="top",
        font="hack",
        visible=True,
    )
    φ_ann = ax.annotate(
        "φ:        ",
        (1, 0),
        xytext=(0, -5),
        xycoords=fr_ann,
        textcoords="offset points",
        ha="right",
        va="top",
        font="hack",
        visible=True,
    )

    for step in steps:
        φ = 2 * np.pi * step / 1024
        y = np.sin(x * ω + φ)
        ln.set_data(x, y)
        fr_ann.set_text(f"n: {step: 5d}")
        φ_ann.set_text(f"φ: {φ:.4f}")
        fig.savefig(target / f"sin_{step:05d}.png")


threads = []
for j in range(N_threads):
    threads.append(threading.Thread(target=gen_frames, args=(range(j, N, N_threads),)))

start = time.monotonic()
[t.start() for t in threads]
[t.join() for t in threads]
stop = time.monotonic()

print(f"Took {stop - start:.2f} for {N} frames with {N_threads} threads")

```

which can be stitched with `ffmpeg -f image2 -framerate 60 -i sin_%05d.png a.mp4`.  The idea is to generate a movie which by eye we should be able to notice if anything went wrong.

It seems to work!  We currently have a lock on `Figure.draw` so we only ever draw one figure at a time.  I did a bit of experimentation with removing that and it still seems to work (we now do fonts pre-thread and the mathtext parser has its own lock).

**Comment by QuLogic** [comment]
Next release of NumPy [should have Windows free-threading wheels](https://github.com/numpy/numpy/issues/26157#issuecomment-2414471900) as well.

**Comment by ianthomas23** [comment]
FYI there are now ContourPy Windows free-threaded wheels available at https://anaconda.org/scientific-python-nightly-wheels/contourpy/files

**Comment by QuLogic** [comment]
I enabled free-threading wheels on Windows now that there are wheels in the nightly repo, which is enough for cibuildwheel's limited testing.

**Review by ksunden — APPROVED** [review]

**Review by ianthomas23 — APPROVED** [review]

**Pull request merged**
