### PR TITLE
Small docstring updates

### PR DESCRIPTION
**Pull request by timhoffm**
What the title says.

### CODE REVIEW

**Comment by timhoffm** [comment]
Self-merging based on @anntzer's approval.

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.1.x

**Comment by QuLogic** [comment]
I'm not going to go through the trouble of backporting this. Feel free to do so if you wish.

**Comment by timhoffm** [comment]
Probably too much going on currently. I think I'm giving up on backporting doc changes to 3.1.2. Hopefully 3.2.0 won't be much later than 3.1.2.

**Pull request merged**
