### PR TITLE
DOC: s/xasis/xaxis/ in whats_new.rst

### PR DESCRIPTION
**Pull request by akrherz**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Thanks!  

Just want to wait for CI to spin before merging.

**Comment by dstansby** [comment]
The travis 3.6 test seems to be flaky, but it's not related to this.

**Comment by QuLogic** [comment]
@Carreau sorry to ping you again, but @dstansby _is_ on the whitelist, no?

**Comment by Carreau** [comment]
Yes.

**Comment by Carreau** [comment]
I've invited you on the heroku app, so you can see the logs.

**Comment by QuLogic** [comment]
@meeseeksdev backport to v2.2.x

**Pull request merged**
