### PR TITLE
DOC: Update docstring to numpy format for last few functions in transforms

### PR DESCRIPTION
**Pull request by TomDonoghue**
## PR Summary

Update docs in some standalone functions in matplotlib/transforms, adding docstrings to a couple functions that didn't have them, and updating a couple others to use numpy docs standards. Updates are all documentation - no code changes. 

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
There are some minor markup issues.  Given that everyone seems to get them wrong, I'll make a PR to document that...

**Comment by anntzer** [comment]
but basically, see http://matplotlib.org/devdocs/devel/documenting_mpl.html#formatting (regarding backquotes)

**Comment by anntzer** [comment]
@QuLogic Can you check what's happening with circleci?
Otherwise looks good to me (conditional on PEP8 passing).

**Comment by TomDonoghue** [comment]
@anntzer 

Thanks for checking in on this, and the heads up on the argument syntax - I wasn't totally sure on that, and missed the note about using *. 

I added links to classes too, and then last commit is just a updating link to class in local file, because I wasn't sure if that had something to do with CircleCI failing (not sure what's going on there)

**Comment by anntzer** [comment]
Circleci failing is certainly independent of your patch, but we may as well try to figure out what's happening.  I'll wait for someone else to check on that before merging mostly so that that problem doesn't get lost but otherwise the PR looks good.
Thanks a lot for fixing the markup, it's a bit tedious because everyone starts by confusing with the markdown syntax but it's actually different :-)

**Comment by QuLogic** [comment]
There seems to be something up with the Debian mirrors. Previously, it was throwing 404 for packages, and the rebuild is now throwing 503  Quorum weight not reached. I'm not sure if we can really do anything; it might eventually fix itself once it reaches quorum.

**Comment by anntzer** [comment]
Congrats on your first contribution, hoping to see you around again!

**Comment by anntzer** [comment]
@Carreau where are the logs? (may be worth at least mentioning in the meeseeksdev README)

**Comment by QuLogic** [comment]
The build worked on master, so it seems the CircleCI issues fixed themselves.

**Comment by tacaswell** [comment]
meeseekdev seems to not work with squash-merge.

**Comment by tacaswell** [comment]
backported to v2.1.x as 8f9a2083d

Thanks @TomDonoghue !

**Comment by Carreau** [comment]
> @Carreau where are the logs? (may be worth at least mentioning in the meeseeksdev README)

Only owner of the app can see logs (for security reason, in case a Token get leaked in the stack trace), otherwise they are [here](https://papertrailapp.com/systems/meeseeksbot/events)

@tacaswell is right it only works for merge commits; also I'm happy to give other admin right on heroku to be able to see logs.

```
Oct 07 23:44:20 meeseeksbot app/web.1: Cherry-picking 5645f24e5e0b92a8ece7cae76a2a4dd67f59e0a6 
Oct 07 23:44:20 meeseeksbot app/web.1:   stderr: 'error: Mainline was specified but commit 5645f24e5e0b92a8ece7cae76a2a4dd67f59e0a6 is not a merge. 
Oct 07 23:44:20 meeseeksbot app/web.1: fatal: cherry-pick failed' 
```

We should allow backport of squashed commits; it should not be too hard.

**Pull request merged**
