### PR TITLE
Add \dddot and \ddddot as accents in mathtext

### PR DESCRIPTION
**Pull request by danzimmerman**
## PR Summary
This is an experiment to address and discuss #20595 

Note that `dddot` and `ddddot` were already defined as 8411 and 8412 in `tex2uni` in `_mathtext_data.py`, I added them again as `combiningthreedotsabove` and `combiningfourdotsabove`.

This PR also added a `--keep-going` flag in `make.bat` so I could build the documentation on Windows. I should probably  raise that in a separate issue/PR. 

**Before, Mathtext Mode**
dddot_before

**After, Mathtext Mode** 
dddot_after

## LaTeX vs. Mathtext Tests

With the right packages included, this works fine with `usetex=True`:
```
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.rc('text.latex', preamble=r'\usepackage{amsmath}\usepackage{amssymb}')

fig = plt.figure(figsize=(15, 9), dpi=200)
ax = fig.subplots(1, 1)
fs = 80

pstra = r'$\dot{x}\hspace{1.5}\ddot{x}\hspace{1.5}\dddot{x}\hspace{1.5}\ddddot{x}$'
pstratex = r'$\dot{x}\hspace{1.5em}\ddot{x}\hspace{1.5em}\dddot{x}\hspace{1.5em}\ddddot{x}$'

ax.annotate(pstra, xy=(0.1, 0.1), fontsize=fs)
ax.annotate(pstratex, xy=(0.1, 0.5), fontsize=fs, usetex=True)
ax.plot([0, 1], [0.591]*2, linewidth=0.5)
ax.plot([0, 1], [0.221]*2, linewidth=0.5)
ax.set_ylim([-0.1, 1])
ax.set_xlim([0, 1])
fig.tight_layout()
```

`usetex=True` on the top, Mathtext mode on the bottom:

image

## PR Checklist

- [X] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (many warnings on originals)
- [X] New features are documented, with examples if plot related.
- [X] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — APPROVED** [review]

**Comment by anntzer** [comment]
Can you squash the commits (possibly splitting out the --keep-going patch)?  Otherwise looks good to me, can be merged after CI completes *and* squashing (or not) is decided.

**Review by anntzer — APPROVED** [review]
(see above)

**Comment by jklymak** [comment]
@danzimmerman if you are not comfortable squashing (though I imagine you are given the technical needs of this change), let us know and we can just squash merge on our end.

**Comment by danzimmerman** [comment]
> @danzimmerman if you are not comfortable squashing (though I imagine you are given the technical needs of this change), let us know and we can just squash merge on our end.

@jklymak I'm not so familiar with squashing commits, and it looks like I complicated things by updating my branch from `master` while I was working (in my history now there are many interleaved commits).

I reverted the `--keep-going` in `make.bat`. If it's easy to squash merge it, please go ahead!

**Comment by timhoffm** [comment]
I've squash-merged.

Thanks @danzimmerman and congratulations on your first contribution to Matplotlib! Hope to see you again.

**Pull request merged**
