### PR TITLE
Doc hidpi

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This PR would like a sphinx-gallery scraper that makes two versions of the image and makes rst that fills a new directive that takes advantage of the mechanism @timhoffm  found: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#resolution_switching_same_size_different_resolutions to let us serve hidpi and normal dpi images:

The API is certainly up for discussion, but what is done here is to lightly modify `sphinx_gallery.matplotlib_scraper` to make the two sets of images, make a new directive:

```rst
.. image-srcset:: /plot_types/basic/images/sphx_glr_bar_001.png
         :alt: bar
         :hidpi: /plot_types/basic/images/sphx_glr_bar_001_hidpi.png
         :class: sphx-glr-single-img
```

that reenders as:

```html
     <img srcset="_images/sphx_glr_bar_001.png, sphx_glr_bar_001_hidpi.png 2x",
         src="sphx_glr_bar_001_hidpi.png"
         alt="bar"
         class="sphx-glr-single-img>
```

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
That worked with less fuss than I was afraid of.  Of course the code is a mess, and probably can be subclassed etc, and probably should go up a level to sphinx-gallery since I basically just vendored their matplotlib scraper, and it can probably be more elegantly done at their level.  

https://56342-1385122-gh.circle-artifacts.com/0/doc/build/html/index.html

**Comment by jklymak** [comment]
Here is the difference on my screen (click on the image to see full size...)

OldNew

**Comment by jklymak** [comment]
The doc build took 19 minutes, which is not a lot longer than normal builds (17-18 minutes?).

**Comment by jklymak** [comment]
@larsoner, do you have any suggestions for the interaction here?  

@matplotlib is this something we want in the docs?  (I'll put on today's agenda)

**Comment by larsoner** [comment]
> The doc build took 19 minutes, which is not a lot longer than normal builds (17-18 minutes?).

Given the number of images your gallery creates and that it now has to do twice as many, I think this is actually pretty good!

> @larsoner, do you have any suggestions for the interaction here?

Do you mean inter-package interaction / "where should this live"? I would say that an opt-in config value + implementation at the sphinx-gallery end would be great. I'd opt into it for the libraries that I manage that use SG+MPL at least, and I imagine most would.

Regarding the `.. image-srcset` directive, it would be great to have this in `matplotlib`, I would probably use it in other packages. Another package might be another option, though, since it seems quite general. Sphinx-gallery would be a sort of in-between option (and I think my preferred one) since it wouldn't require starting a new package, is pure Python, `setup_requires` is pretty small I think, and there is precedence for using small subsets of SG functionality (e.g., `sphinx_gallery.load_style` https://github.com/sphinx-gallery/sphinx-gallery/pull/601). In `image-srcset` You could also implement the lazy-loading of thumbnails requested by @timhoffm in https://github.com/sphinx-gallery/sphinx-gallery/issues/803 which would be a nice complementary modernization of the `.. image` directive.

**Comment by jklymak** [comment]
1) I think adding the scraper at sphinx-gallery (perhaps as a config option) makes the most sense.  I'll have to look, but I would guess just adding it to `matplotlib_scraper` would work fine. 

2) I think adding the custom directive at sphinx-gallery would also make the most sense so downstream libraries could use it with the scraper.  

On the dev call today we decided we would like this implemented for 3.5 (if possible).  For SG, would you suggest opening an issue asking for input on the API?

**Comment by jklymak** [comment]
See https://github.com/sphinx-gallery/sphinx-gallery/pull/808 for where this is going....

**Comment by jklymak** [comment]
Closing in favour of fixing in sphinx-gallery.  https://github.com/sphinx-gallery/sphinx-gallery/pull/808

**Pull request closed without merging**
