### PR TITLE
fix #4854: set default numpoints of legend entries to 1

### LINKED ISSUE #4854: set numpoints to 1
(File under "default changes".  For all I know this is already on the list of things to change, but if so I couldn't find it under either "numpoints" or "scatterpoints".)

My most popular answer on SO (see ["matplotlib legend markers only once"](http://stackoverflow.com/questions/6146778/matplotlib-legend-markers-only-once)) explains how to avoid multiple points showing up in the legend.

This is far from scientific, but for what it's worth the question has 107 upvotes, my answer has 117 upvotes, and neither has a single downvote.

My experience is that those who don't like the multiple-marker convention *really* don't like it, and those who do don't seem particularly worked up about it.

### PR DESCRIPTION
**Pull request by gauteh**
check #4854: set default numpoints to 1.

I am a bit unsure abouth wether classic.mplstyle should be changed.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
The classic style should have numpoints=2, The idea of the classic style is to provide a style that exactly replicates how MPL looked before the default changes.

**Comment by gauteh** [comment]
Also apparently the test-images must be updated when the PR is ready.

**Comment by jenshnielsen** [comment]
No the tests run with the classic style as default to avoid having to update all the test images.

**Comment by tacaswell** [comment]
Please don't merge this until we have pushed the 1.5 development off the master branch.

**Comment by WeatherGod** [comment]
Hmmm, that is strange that only the legend_expand tests failed. Could that codepath be utilizing rcparams incorrectly?

**Comment by QuLogic** [comment]
@gauteh Can you rebase? I believe something has corrected the failure on master.

**Comment by QuLogic** [comment]
Backported as part of #5774.

**Pull request merged**
