### PR TITLE
MAINT finance module is deprecated

### PR DESCRIPTION
**Pull request by NelleV**
Here is a deprecation for the finance module.

Supersedes #7071 
We should probably make a call for contributor out.

### CODE REVIEW

**Comment by tacaswell** [comment]
Looks good modulo minor word smithnig.

Who ever merges, please remember to backport to v2.x

**Comment by QuLogic** [comment]
Backported to v2.x via 5d1efbd34ef2c552d7c678a67878a6c0a0f3a204.

**Comment by anntzer** [comment]
@NelleV Actually this interferes somewhat awkwardly with the fact that IPython still imports pylab (https://github.com/matplotlib/matplotlib/issues/7186#issuecomment-250169829, fixed as of IPython 5.2).  Now you get the deprecation warning when running `%matplotlib` in IPython...

**Comment by efiring** [comment]
Maybe the deprecation warning needs to be inside each function in the module, instead of at the module level?

**Comment by tacaswell** [comment]
we could just wrap the import in a warning context and snarf the warning?

IPython merged my PR to remove most of the pylab imports https://github.com/ipython/ipython/pull/9998

**Comment by anntzer** [comment]
I think @tacaswell's solution is the best.

**Comment by NelleV** [comment]
I think having the warning at least at module level is important, as some people sometimes import stuff from our modules (totally unrelated to our code) which is going to break as well. (That used to be a reason not to remove unused imports at the top of some of our modules).

I could also be very aggressive and add deprecation warnings to all the functions of the module. That's extremely easy to do with our deprecated decorator.

I'll look at ipython's issue with our deprecation warning.

**Pull request merged**
