### PR TITLE
Fix tuple markers

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

I was able to write a test for polygon tuple markers, but not for star or asterisk yet. The star tuple is not the same as `*` and asterisk, while similar to `+` or `x`, seem to have a different weight.

This broke in 3.2.0 in #14244.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [n/a] New features are documented, with examples if plot related
- [n/a] Documentation is sphinx and numpydoc compliant
- [n/a] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [n/a] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Oh, that was supposed to be WIP because the other two tests weren't written, but oh well.

**Comment by QuLogic** [comment]
Not sure what to do about star markers, so I just did a smoke test.

**Comment by tacaswell** [comment]
Specifically https://github.com/matplotlib/matplotlib/pull/14244/files#diff-f078f095bee3dd9c6ed756b47a04f74fL375

**Comment by tacaswell** [comment]
How did you find this out of curiousity?

**Comment by QuLogic** [comment]
I was running `flake8` without extra warnings and noticed an unused variable.

**Comment by tacaswell** [comment]
Should L333 turn into an `else`?  I think there is now a path through this for an unboundlocal error.

**Comment by QuLogic** [comment]
That is verified in `set_marker`:
https://github.com/matplotlib/matplotlib/blob/e9da814cefb55bf1b4f79f0a0703abb3b1d0e6fe/lib/matplotlib/markers.py#L279-L281

**Comment by tacaswell** [comment]
fair enough, still seems like a bit of a foot-cannon to leave in the code base.

**Pull request merged**
