### PR TITLE
MEP12 on geo_demo.py

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by thisch** [comment]
Why do you always have those merge commits in your PRs?

**Comment by ericmjl** [comment]
I think it's becuase of Github desktop. I used to use the command line git, but I recently became lazy :P.

**Comment by ericmjl** [comment]
My older MEP12 commits don't have them, I think.

**Comment by tacaswell** [comment]
Can you squash out the merge commits?

**Comment by ericmjl** [comment]
Sure, no problem. Out of curiosity, is there a reason for wanting to squash commits?

**Comment by ericmjl** [comment]
Damn, I screwed up. I am going to ditch this PR, and start again...

**Comment by tacaswell** [comment]
I don't normally ask for squashing, but having merges from master on branches merged into master makes the history more confusing than strictly needed.

**Comment by jenshnielsen** [comment]
@ericmjl I think this happens when you try to bring your branch up to master.

I normally use reset on a new brach to make sure that it matches master before adding commits to it. 

```
git checkout -b "mynewbrach"
git fetch upstream
git reset --hard upstream/master
```
Assuming that upstream is your name for the main Matplotlib repository. and then start working. This gives you a new branch which is a exact copy of master. 

If you use merge to bring your branch up to date with master then you will get these extra merge commits.

**Comment by ericmjl** [comment]
@jenshnielsen got it, thanks for the git tips! Look forward to a re-do of this mep12 example coming soon.

**Pull request closed without merging**
