### PR TITLE
Fix arcs with very large width/height.

### LINKED ISSUE #9659: patches.Arc objects randomly drawing the full ellipse
### Bug report

**Bug summary**

Providing theta1 and theta2 to the Arc constructor sometimes causes the arc to be drawn as the full ellipse.

**Code for reproduction**

```python
from matplotlib.patches import Arc
import matplotlib.pyplot as plt

patches = [
    Arc((143954140, 374), 476, 476, theta1=0, theta2=180),
    Arc((143954902, 374), 2001, 749, theta1=0, theta2=180),
    Arc((143955137, 374), 2471, 749, theta1=0, theta2=180),
    Arc((143955276, 374), 2748, 749, theta1=0, theta2=180),
    Arc((143955362, 374), 2022, 749, theta1=0, theta2=180),
    Arc((143955500, 374), 2299, 749, theta1=0, theta2=180),
    Arc((143955641, 374), 488, 488, theta1=0, theta2=180),
    Arc((143955650, 374), 506, 506, theta1=0, theta2=180),
    Arc((143955885, 374), 976, 749, theta1=0, theta2=180),
    Arc((143956128, 374), 489, 489, theta1=0, theta2=180),
    Arc((143956135, 374), 467, 467, theta1=0, theta2=180),
    Arc((143956137, 374), 471, 471, theta1=0, theta2=180),
    Arc((143956276, 374), 748, 748, theta1=0, theta2=180),
    Arc((143956515, 374), 1226, 749, theta1=0, theta2=180),
    Arc((143956167, 374), 412, 412, theta1=0, theta2=180),
    Arc((143956170, 374), 402, 402, theta1=0, theta2=180),
    Arc((143956172, 374), 401, 401, theta1=0, theta2=180),
    Arc((143956183, 374), 380, 380, theta1=0, theta2=180),
    Arc((143956321, 374), 657, 657, theta1=0, theta2=180),
    Arc((143956610, 374), 80, 80, theta1=0, theta2=180),
    Arc((143956849, 374), 558, 558, theta1=0, theta2=180),
    Arc((143956928, 374), 400, 400, theta1=0, theta2=180),
    Arc((143956960, 374), 335, 335, theta1=0, theta2=180),
    Arc((143956962, 374), 331, 331, theta1=0, theta2=180),
    Arc((143957055, 374), 146, 146, theta1=0, theta2=180),
    Arc((143957346, 374), 105, 105, theta1=0, theta2=180),
    Arc((143957397, 374), 207, 207, theta1=0, theta2=180),
    Arc((143957448, 374), 308, 308, theta1=0, theta2=180),
    Arc((143957459, 374), 331, 331, theta1=0, theta2=180),
    Arc((143957475, 374), 363, 363, theta1=0, theta2=180),
    Arc((143957696, 374), 804, 749, theta1=0, theta2=180),
    Arc((143958871, 374), 3154, 749, theta1=0, theta2=180),
    Arc((143957954, 374), 287, 287, theta1=0, theta2=180),
    Arc((143957957, 374), 292, 292, theta1=0, theta2=180),
    Arc((143958125, 374), 628, 628, theta1=0, theta2=180),
    Arc((143958305, 374), 268, 268, theta1=0, theta2=180),
    Arc((143958313, 374), 251, 251, theta1=0, theta2=180),
    Arc((143958368, 374), 142, 142, theta1=0, theta2=180),
    Arc((143958369, 374), 136, 136, theta1=0, theta2=180),
    Arc((143958370, 374), 138, 138, theta1=0, theta2=180),
    Arc((143958905, 374), 535, 535, theta1=0, theta2=180),
    Arc((143959528, 374), 1780, 749, theta1=0, theta2=180),
    Arc((143959543, 374), 1810, 749, theta1=0, theta2=180),
    Arc((143959544, 374), 1813, 749, theta1=0, theta2=180),
    Arc((143959849, 374), 1198, 749, theta1=0, theta2=180),
    Arc((143960119, 374), 658, 658, theta1=0, theta2=180),
    Arc((143960678, 374), 151, 151, theta1=0, theta2=180),
    Arc((143960682, 374), 158, 158, theta1=0, theta2=180),
    Arc((143960682, 374), 159, 159, theta1=0, theta2=180),
    Arc((143960723, 374), 241, 241, theta1=0, theta2=180),
    Arc((143960797, 374), 388, 388, theta1=0, theta2=180),
    Arc((143960845, 374), 484, 484, theta1=0, theta2=180),
    Arc((143960809, 374), 363, 363, theta1=0, theta2=180),
    Arc((143960943, 374), 95, 95, theta1=0, theta2=180),
    Arc((143960945, 374), 92, 92, theta1=0, theta2=180)
]

plt.figure()
ax = plt.gca()
map(ax.add_patch, patches)
plt.xlim(143953697, 143961337)
plt.ylim(-150, 900)
plt.show()
```

**Actual outcome**

image

**Expected outcome**

All the arcs should be half-ellipses above the line `y = 0.5`.

**Matplotlib version**

  * Operating system: Mac OS Sierra
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.14 (Homebrew)
  * Jupyter version (if applicable):
  * Other libraries: numpy 13.3.3

python 2.7.14 from homebrew (`brew install python`); matplotlib from pip (`sudo -H pip install matplotlib`)

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Large width/height triggers a different code path that didn't correctly
draw limited arcs instead of the whole ellipse.

Fixes #9659.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Not sure if this should go in `2.1.1`

**Comment by dopplershift** [comment]
It should, it's a pretty low-risk bug fix.

**Comment by dopplershift** [comment]
@meeseeksdev backport to v2.1.1

**Comment by dopplershift** [comment]
@meeseeksdev backport to v2.1.x

**Comment by scnorton** [comment]
Requesting reopening of issue because is not fixed in version 2.1.0+1007.gbaa5f8e22.

```Python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as pch

import matplotlib
print(matplotlib.__version__)


GENE_CHR = 'chr8'
GENE_STR = 143953272
GENE_STP = 143961762
BEDFILE = np.array([('chr8', 143953772, 143955902),
                    ('chr8', 143956373, 143956570),
                    ('chr8', 143956650, 143956728),
                    ('chr8', 143956728, 143956797),
                    ('chr8', 143957128, 143957294),
                    ('chr8', 143957657, 143957811),
                    ('chr8', 143958098, 143958301),
                    ('chr8', 143958439, 143958638),
                    ('chr8', 143959173, 143959250),
                    ('chr8', 143960448, 143960603),
                    ('chr8', 143960762, 143960896),
                    ('chr8', 143960991, 143961262)
], dtype=[('Chr', 'S4'), ('Start', int), ('End', int)])
JUNCTIONS = [(0, 1),
             (0, 2),
             (1, 2),
             (2, 3),
             (2, 4),
             (3, 4),
             (4, 5),
             (5, 6),
             (6, 7),
             (7, 8),
             (7, 9),
             (8, 9),
             (9, 10),
             (9, 11),
             (10, 11)]

plt.figure(figsize=[20, 2])
exons = []
junctions = []
ax = plt.gca()
bedfile = np.genfromtxt('/Volumes/data/Scott/struan/exons.bed', dtype=None, names=('Chr', 'Start', 'End'), delimiter='\t')
for exon in bedfile:
    exons.append(pch.Rectangle((exon['Start'], 0), exon['End'] - exon['Start'], 0.2, facecolor='#cccccc', edgecolor='k'))
    ax.add_patch(exons[-1])
for src, tgt in JUNCTIONS:
    left = bedfile[src]['End']
    right = bedfile[tgt]['Start']
    if left == right:
        continue
    junctions.append(pch.Arc(((left + right) / 2, 0.2), (right - left), 0.2, theta1=0, theta2=180))
    ax.add_patch(junctions[-1])
plt.axis('off')
plt.xlim(GENE_STR, GENE_STP)
plt.ylim(-.1, .5)
plt.tight_layout(rect=(0, .1, 1, 1))
plt.show()
```

image

**Pull request merged**
