### PR TITLE
Add docstring to set_interpolation

### PR DESCRIPTION
**Pull request by dstansby**
This fixes (at least locally) the doc build. I have no idea why.

### CODE REVIEW

**Comment by dstansby** [comment]
Since this fixes CI and is (I hope) uncontroversial I'm going to self-merge.

**Comment by QuLogic** [comment]
@Carreau this one should have backported too?

**Comment by QuLogic** [comment]
@meeseeksdev backport to v2.2.x

**Comment by Carreau** [comment]
That is strange. 

I've added a couple of debug statements to see what's happening.

**Pull request merged**
