### PR TITLE
CI: Use Ubuntu Bionic compatible package names

### PR DESCRIPTION
**Pull request by Kojoley**
otf-freefont was renamed to fonts-freefont-otf
pgf is now provided with texlive-pictures

### CODE REVIEW

**Comment by timhoffm** [comment]
Do we have to worry about back compatibility here?

**Comment by tacaswell** [comment]
These are internal CI configuration not user facing.  So long as CI passes we don't have to worry about back-compat.

**Comment by timhoffm** [comment]
Waiting for #15632.

**Comment by timhoffm** [comment]
@meeseeksdev backport to v3.2.x

**Pull request merged**
