### PR TITLE
BLD: certifi is not a run-time dependency

### LINKED ISSUE #18337: Error installing matplotlib-3.3.1 using pip due to old version of certifi on conda environment
Hi!

I'm using `mapltolib` on CICD (linux) and I found this unexpected behavior. When I install `matplotlib-3.3.1` on a `conda` environment with an older version of `certifi` (required by `conda`), the installation process fails. I'm wondering if this is the expected behavior or not. 

I've checked the [`setup.py` ](https://github.com/matplotlib/matplotlib/blob/v3.3.1/setup.py#L282) and I saw that `matplotlib` requires `certifi>=2020.06.20`, so if I have an older version installed the error occurs. 

# MWE

Here is an example of my workflow.

```bash
$ docker run -it intelpython/intelpython3_core:2019.4
(base) root@9c3da40a58ba:/# pip install matplotlib
```

# Traceback 

```bash
$ docker run -it intelpython/intelpython3_core:2019.4
Unable to find image 'intelpython/intelpython3_core:2019.4' locally
2019.4: Pulling from intelpython/intelpython3_core
cc1a78bfd46b: Pull complete
49eab01d36f3: Pull complete
c2c2cfea0213: Pull complete
419499c9a4cf: Pull complete
f7550509e92e: Pull complete
4d32c595223c: Pull complete
Digest: sha256:fb45b594cb3e6960311157393eda3b86225f7446e07768a96517d3c2b314bc2a
Status: Downloaded newer image for intelpython/intelpython3_core:2019.4

(base) root@9c3da40a58ba:/# pip list
Package      Version
------------ ---------
asn1crypto   0.24.0
certifi      2018.1.18
cffi         1.11.5
chardet      3.0.4
conda        4.6.14
cryptography 2.2.2
idna         2.6
mkl-fft      1.0.13
mkl-random   1.0.4
mkl-service  1.0.0
numpy        1.16.2
pip          10.0.1
pycosat      0.6.3
pycparser    2.18
pyOpenSSL    18.0.0
PySocks      1.6.8
PyYAML       4.1
requests     2.18.4
ruamel-yaml  0.15.37
scipy        1.2.1
setuptools   39.2.0
six          1.11.0
TBB          0.1
urllib3      1.22
wheel        0.31.1
You are using pip version 10.0.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(base) root@9c3da40a58ba:/# pip install matplotlib
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/96/a7/b6fa244fd8a8814ef9408c8a5a7e4ed0340e232a6f0ce2046b42e50672c0/matplotlib-3.3.1-cp36-cp36m-manylinux1_x86_64.whl (11.6MB)
    100% |████████████████████████████████| 11.6MB 2.5MB/s
Collecting certifi>=2020.06.20 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 9.9MB/s
Collecting kiwisolver>=1.0.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/ae/23/147de658aabbf968324551ea22c0c13a00284c4ef49a77002e91f79657b7/kiwisolver-1.2.0-cp36-cp36m-manylinux1_x86_64.whl (88kB)
    100% |████████████████████████████████| 92kB 6.5MB/s
Requirement already satisfied: numpy>=1.15 in /opt/conda/lib/python3.6/site-packages (from matplotlib) (1.16.2)
Collecting cycler>=0.10 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 7.4MB/s
Collecting pillow>=6.2.0 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/30/bf/92385b4262178ca22b34f82e0e09c2922eb351fe39f3cc7b8ba9ea555b41/Pillow-7.2.0-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 6.6MB/s
Collecting python-dateutil>=2.1 (from matplotlib)
  Downloading https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 8.8MB/s
Requirement already satisfied: six in /opt/conda/lib/python3.6/site-packages (from cycler>=0.10->matplotlib) (1.11.0)
mkl-service 1.0.0 requires cython, which is not installed.
Installing collected packages: certifi, kiwisolver, cycler, pyparsing, pillow, python-dateutil, matplotlib
  Found existing installation: certifi 2018.1.18
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
You are using pip version 10.0.1, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(base) root@9c3da40a58ba:/# exit
```

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary

Closes #18337

### CODE REVIEW

**Comment by QuLogic** [comment]
I don't remember exactly, but I think I added certifi to runtime because of the download-from-URL style handling. Since this only affected wheel builders, I don't think you'll see whether that's broken from our usual CI.

**Comment by tacaswell** [comment]
We shouldn't let our build details leak into user space though.  If the issue is just our wheel builders we should fix it there by pre-installing like we do with numpy.

I am very hesitant to do it now (because the space is still moving really fast), but eventually we are going to have to have a look at pep517 and friends....

**Comment by tacaswell** [comment]
now this and ##18637 are going to clash, but will deal with that when it happens.

**Comment by tacaswell** [comment]
This one should be merged first to make the backport easier.

**Review by timhoffm — APPROVED** [review]

**Comment by anntzer** [comment]
Actually it *is* a runtime dependency, e.g. `imread("https://matplotlib.org/1.5.0/_static/logo2.png")` now *requires* certifi to be present.  In fact I think that 1) this should not actually depend on certifi and 2) we should not support directly opening urls anyways...

**Pull request merged**
