### PR TITLE
fix __builtins__ for better compatibility

### PR DESCRIPTION
**Pull request by zjjott**
issue #7186 
Maybe I fix it or maybe it's no an error.....\_(:з」∠)\_

### CODE REVIEW

**Comment by zjjott** [comment]
`AttributeError: 'dict' object has no attribute 'bytes'`
wtf....why  `__builtins__`  is dict?

**Comment by Kojoley** [comment]
> wtf....why  `__builtins__`  is dict?

https://docs.python.org/2/reference/executionmodel.html

> **CPython implementation detail**: Users should not touch `__builtins__`; it is strictly an implementation detail. Users wanting to override values in the builtins namespace should import the `__builtin__` (no ‘s’) module and modify its attributes appropriately.

I agree that we need a fix, but then we should use [`__builtin__`](https://docs.python.org/2/library/__builtin__.html)/[`builtins`](https://docs.python.org/3/library/builtins.html) __module__.

**Comment by zjjott** [comment]
thanks~ @Kojoley 

> By default, when in the __main__ module, __builtins__ is the built-in module __builtin__ (note: no ‘s’); when in any other module, __builtins__ is an alias for the dictionary of the __builtin__ module itself. __builtins__ can be set to a user-created dictionary to create a weak form of restricted execution.

looks like __main__ module or other module have diffence __builtins__ and type,I'll close this PR

**Comment by anntzer** [comment]
This should probably be
```
from six.moves import builtins
bytes = builtins.bytes
```
(feel free to re-close this if you want to make a separate PR).

**Comment by Kojoley** [comment]
Fixed by #7272

**Pull request closed without merging**
