### PR TITLE
BUG : fix PowerNorm with scalars

### LINKED ISSUE #4053: PowerNorm().__call__ doesn't work with scalar input value
result[value<0] = 0; #fails if value is scalar

### PR DESCRIPTION
**Pull request by tacaswell**
closes #4053

### CODE REVIEW

**Comment by tacaswell** [comment]
@matplotlib/developers Can someone take a look at this today?

**Comment by jenshnielsen** [comment]
The fix looks correct to me and I can confirm that it resolves the issue.

Looking at that piece of code for the first time I don't understand how clip bool is supposed to work.
It assigns values to an array called ```val``` which is never used as far as I can see.
This is confirmed by trying to do ```cNorm2(120)``` which returns ```1.20202020202``` regardless of whether clip is True or False (with ```vmax=100```). The solution should be to assign ```result``` rather than ```val``` but it would need a test too. 

I don't think this is a new issue so I am fine with merging this as is and cutting 1.4.3 and postponing the clip issue to 1.4.x

**Comment by jenshnielsen** [comment]
@tacaswell I submitted a pr against your branch which I think should address the clip issue. If you think this is to high risk I am fine with merging this as is and postponing it to 1.4.x as I said above.

**Comment by tacaswell** [comment]
@jenshnielsen Looks good.  If travis passes I will merge _this_ PR.

**Pull request merged**
