### PR TITLE
Fix issue where colorbar moves second x-axis

### PR DESCRIPTION
**Pull request by Rasori**
## PR Summary
This PR finishes PR #19109 which have been stale for a while. The original PR had suggested patch implemented already but the merge was not done as there were minor issues with the placing of the test etc. This PR have implemented changes proposed by @QuLogic for the original PR.

The goal of this PR is to fix secondary x-axis scaling when e.g. color bar is added afterwards. The problem is described more in depth in issue #5904.

This PR closes issue #5904 and removes the need for PRs #19109 and #21576

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
    - During local testing some latex related test failed (probably not related)
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by Rasori** [comment]
It seems that the image comparison fails on some platforms. I looked the differences in images and the diff image itself from _Tests / Python 3.9 on ubuntu-20.04 (pull_request)_ and I think this could be a tolerance issue. Do you have any suggestion for the tolerance value?

**Comment by Rasori** [comment]
I took a look into failed checks and it seems that [example](https://matplotlib.org/stable/gallery/subplots_axes_and_figures/two_scales.html) using twinx() and tight_layout() will raise warning

`UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  fig.tight_layout()  # otherwise the right y-label is slightly clipped`

I compared the resulting images between release version and this PR and indeed the second y-axis is almost clipped away.

Expected:
expected_image


Resulting:
resulting_image

ATM I have no idea about how the tight_layout() works or how to fix this issue but I am happy to continue with this PR if someone can give a hint where to start.

**Review by jklymak — CHANGES_REQUESTED** [review]
Thanks for the PR.  OTOH I can see why this is stalled:

There seems to be a confounding here of main library and the axes_grid toolbox.  tight_layout is not compatible with axes_grid.  However, here you have added an axes_grid locator to the main library's twin functionality (which works fine with axes_grid).  

If you want colorbars to play nicely with the main library's twinx, then I believe that constrained_layout is the correct approach.  But if that is your goal then please provide and example using the main library code.    Thanks!

**Comment by Rasori** [comment]
Thanks for the comment.
I am afraid that I do not understand the whole picture here. 

If I understood correctly the proposed changes of this PR are fine:
> ... axes_grid locator to the main library's twin functionality (which works fine with axes_grid).

But in order to fix the presented issue / warning from the example I should modify it to use constrained_layout instead of tight_layout? By doing so it produces seemingly same figure.

```Python
import numpy as np
from matplotlib import pyplot as plt

t = np.arange(0.01, 10.0, 0.01)
data1 = np.exp(t)
data2 = np.sin(2 * np.pi * t)

fig, ax1 = plt.subplots(constrained_layout=True)

color = 'tab:red'
ax1.set_xlabel('time (s)')
ax1.set_ylabel('exp', color=color)
ax1.plot(t, data1, color=color)
ax1.tick_params(axis='y', labelcolor=color)

ax2 = ax1.twinx()  # instantiate a second axes that shares the same x-axis

color = 'tab:blue'
ax2.set_ylabel('sin', color=color)  # we already handled the x-label with ax1
ax2.plot(t, data2, color=color)
ax2.tick_params(axis='y', labelcolor=color)

plt.show()
```
constrained_layout


Or do you actually mean to forget the proposed patch and provide an example where twinx and colorbar is used with constrained_layout [(Similar to)](https://github.com/matplotlib/matplotlib/issues/5904#issuecomment-661637700) to get around the problem in the first place?

> If you want colorbars to play nicely with the main library's twinx, then I believe that constrained_layout is the correct approach. But if that is your goal then please provide and example using the main library code. Thanks!

**Comment by jklymak** [comment]
I don't think we should accept a change to the main library to make axes_grid happy if it breaks behaviour of the main library.

**Comment by Rasori** [comment]
I believe that we are on the same page now.

I would suggest that we remove the labels from the original issue as this is not anymore a good first issue and the suggested patch breaks the main library.

I can make few examples where the colorbar is used with the constrained layout to get around the problem. Should I do it in this PR or open another one for it?

The only thing that still annoys me is that there is no indication for the user when the axes are/could be out of sync. Would there be a possibility to add warning for that? Although, it could be rather hard come up with set of actions/values that would lead to that error.

**Comment by jklymak** [comment]
Thanks for your understanding on this @Rasori and sorry for the wild goose chase!  Hopefully we will see you again.

**Pull request closed without merging**
