### PR TITLE
Fix issue with Sphinx 1.3.4

### LINKED ISSUE #5869: doc build fails with mpl-1.5.1 and sphinx-1.3.4 (sphinx-1.3.3 is fine)
```python ./make.py --small html```files with

```python
# Sphinx version: 1.3.4
# Python version: 2.7.11 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:
#   reading sources... [  4%] api/index
#   reading sources... [  4%] api/index_backend_api
#   reading sources... [  4%] api/legend_api
#   reading sources... [  4%] api/lines_api
#   reading sources... [  4%] api/markers_api
#   reading sources... [  4%] api/mathtext_api
#   reading sources... [  4%] api/matplotlib_configuration_api
#   reading sources... [  5%] api/mlab_api
#   reading sources... [  5%] api/offsetbox_api
#   reading sources... [  5%] api/patches_api
# Loaded extensions:
#   sphinx.ext.graphviz (1.3.4) from /usr/lib64/python2.7/site-packages/sphinx/ext/graphviz.pyc
#   sphinxext.github (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/doc/sphinxext/github.py
#   sphinx.ext.autodoc (1.3.4) from /usr/lib64/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.doctest (1.3.4) from /usr/lib64/python2.7/site-packages/sphinx/ext/doctest.pyc
#   matplotlib.sphinxext.mathmpl (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/build/build/lib/matplotlib/sphinxext/mathmpl.py
#   matplotlib.sphinxext.plot_directive (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/build/build/lib/matplotlib/sphinxext/plot_directive.py
#   alabaster (0.7.7) from /usr/lib64/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.inheritance_diagram (1.3.4) from /usr/lib64/python2.7/site-packages/sphinx/ext/inheritance_diagram.pyc
#   matplotlib.sphinxext.only_directives (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/build/build/lib/matplotlib/sphinxext/only_directives.py
#   numpydoc (unknown version) from /usr/lib64/python2.7/site-packages/numpydoc/__init__.pyc
#   sphinxext.gen_rst (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/doc/sphinxext/gen_rst.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /usr/lib64/python2.7/site-packages/IPython/sphinxext/ipython_console_highlighting.pyc
#   sphinxext.gen_gallery (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/doc/sphinxext/gen_gallery.py
#   sphinx.ext.autosummary (1.3.4) from /usr/lib64/python2.7/site-packages/sphinx/ext/autosummary/__init__.pyc
#   IPython.sphinxext.ipython_directive (unknown version) from /usr/lib64/python2.7/site-packages/IPython/sphinxext/ipython_directive.pyc
#   sphinxext.math_symbol_table (unknown version) from /var/tmp/portage/dev-python/matplotlib-1.5.1/work/matplotlib-1.5.1-python2_7/doc/sphinxext/math_symbol_table.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 266, in build
    self.builder.build_update()
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/__init__.py", line 251, in build_update
    'out of date' % len(to_build))
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/__init__.py", line 265, in build
    self.doctreedir, self.app))
  File "/usr/lib64/python2.7/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/lib64/python2.7/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib64/python2.7/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/lib64/python2.7/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/lib64/python2.7/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/lib64/python2.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/usr/lib64/python2.7/site-packages/sphinx/transforms.py", line 182, in apply
    apply_source_workaround(n)
  File "/usr/lib64/python2.7/site-packages/sphinx/util/nodes.py", line 53, in apply_source_workaround
    '\s*:\s*%s' % classifier.astext(), '', node.rawsource)
  File "/usr/lib64/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib64/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
error: unbalanced parenthesis
```

### PR DESCRIPTION
**Pull request by jenshnielsen**
Fixes #5869 by rewriting the offending doc string as numpy doc

I also updated .travis.yaml. This originally started with the aim to ensure that the latest version of Sphinx and other dependencies is always installed by only installing Numpy and Pandas from the wheel house. (The wheel house requires manually rebuilding the wheel when a new version is released to pypi and was thus using an older version of Sphinx) The speed benefits are limited since other packages than numpy and pandas are fast to install and we now have the pip wheel cache on Travis anyway. 

I took the opportunity to refactor the Travis config a bit more to collect all the pip installs one place and group relevant sections.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Looks like there is another issue with Sphinx 1.3.4 I will take a look tomorrow

```
Warning, treated as error:
['find_tex_file(filename, format=None)', ':module: matplotlib.dviread', '', '', '', 'Call :program:`kpsewhich` to find a file in the texmf tree. If', '*format* is not None, it is used as the value for the', ':option:`--format` option.', '', 'Apparently most existing TeX distributions on Unix-like systems', 'use kpathsea. I hear MikTeX (a popular distribution on Windows)', "doesn't use kpathsea, so what do we do? (TODO)", '', '.. seealso::', '', '  `Kpathsea documentation <http://www.tug.org/kpathsea/>`_', '    The library that :program:`kpsewhich` is part of.']:3: WARNING: unknown option: --format
```

**Comment by jenshnielsen** [comment]
It looks like that was as simple as removing the :option: key

**Comment by jenshnielsen** [comment]
I think the docs changes should be backported to 1.5.2 but the changes to Travis might not be wort it to backport

**Comment by jenshnielsen** [comment]
BTW it would be good to convert the rest of that file to numpydoc/napoleon too

**Comment by jenshnielsen** [comment]
There seems to be an issue with downloading the Cursive font from Googles github account. I should fix that before merging

**Comment by jenshnielsen** [comment]
Looks like the google fonts are back on github so this is ready for review

**Comment by jenshnielsen** [comment]
Sphinx 1.3.5 has been released with a fix for the regex issue so we don't strictly need 0ccce1b218c08634ceaedb975b15ba663c6a2922 anymore but it's still an improvement. We do need  7f37443 to have it build cleanly with 1.3.5 thou 

I am happy to separate out the travis changes if that makes more sense?

**Comment by tacaswell** [comment]
I will cherry pick this back but discard the travis changes

**Comment by tacaswell** [comment]
backported to 1.5.x as b7dfa4f

**Pull request merged**
