### PR TITLE
Mathtext brackets

### PR DESCRIPTION
**Pull request by mdboom**
Fix for #3374.

This special cases the minus sign to be treated as if it has full `x` height.  Also fixes a small problem with vertical alignment of text that was discovered along the way.

### CODE REVIEW

**Comment by tacaswell** [comment]
The vertical aliment of the `|->` does not look right to me in the pngs

**Comment by mdboom** [comment]
To my eyes, the Computer Modern one looks fine.  The stix is a bit low, but the minus sign is a bit low in that font anyway.  It doesn't look and odd in the context of more stuff.

**Comment by WeatherGod** [comment]
yeah, cm looks right to me, the other pngs don't seem right. The vertical extent of the | doesn't match the extent of the bracket, and they aren't aligned. Are they supposed to or not? In cm, the vertical bar doesn't match the vertical extent, but it seems to be better aligned.

**Comment by tacaswell** [comment]
I think the `-` should be even with the center of the `>` .  Below is the output from 

```latex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
\thispagestyle{empty}
\begin{math}
  \left\langle - \right| \left | + \right\rangle
\end{math}
\end{document}

```

braket

I am wearing my physicist hat here complaining about this. 

This PR is definitily an improvement and if the answer is 'use tex' to get the more centered version that is probably ok.

**Comment by mdboom** [comment]
Fixing this properly has turned into a rather deep wormhole of problems...  I say we just keep this open and I (or some other brave soul) can continue to hack away at it as able...

**Comment by anntzer** [comment]
#3374 was fixed by #5871. 
Vertical alignment of +/- and brakets remains less than perfect, but this PR doesn't change that situation AFAICT, so I'll close this.

**Pull request closed without merging**
