### PR TITLE
Fix version switcher links

### LINKED ISSUE #23794: [Doc]: Version switcher broken in devdocs
### Documentation Link

https://matplotlib.org/devdocs/index.html

### Problem

A / is missing so switching to e.g. stable gives `https://matplotlib.org/stableindex.html`.

Marking as rc as I assume that the idea is to include the version switcher in 3.6?

### Suggested improvement

Add the missing / (I have no idea where unfortunately...).

### PR DESCRIPTION
**Pull request by melissawm**
## PR Summary

The links listed in the version switcher `switcher.json` file are missing a trailing slash, creating broken links.

Closes #23794

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by jklymak — APPROVED** [review]
Should this be working in the rendered docs?   OTOH this looks right to me.

**Comment by melissawm** [comment]
No unfortunately it will only work after it is merged because the switcher.json file is only read from a URL but not locally.

**Comment by QuLogic** [comment]
The file is blocked by CORS; I've added a temporary exception to allow it on the server.

**Comment by QuLogic** [comment]
Ah, but of course, that won't fix it here since it's not yet on the server.

**Comment by QuLogic** [comment]
It appears to be working again, though you might need a full refresh to pick up the new `switcher.json`.

**Pull request merged**
