### PR TITLE
Default animation.convert_args to ["-layers", "OptimizePlus"].

### PR DESCRIPTION
**Pull request by anntzer**
On the simple_anim.py example, adding e.g.
```python
plt.rcParams["animation.writer"] = "imagemagick"
plt.rcParams["animation.convert_args"] = []
ani.save("old.gif")
plt.rcParams["animation.convert_args"] = ["-layers", "OptimizePlus"]
ani.save("new.gif")
```
shows that OptimizePlus yields a >2.5x decrease in gif size.  (Admittedly I haven't tried more examples.)

Goes on top of #23370.  Supersedes #15784.  Thanks to @erelson for suggesting to use `-layers`.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by dopplershift** [comment]
This can be rebased on main now that #23370 is merged.

**Comment by anntzer** [comment]
rebased.

**Comment by QuLogic** [comment]
Do we have a minimum supported ImageMagick version? When was this added?

**Review by story645 — APPROVED** [review]

**Comment by anntzer** [comment]
I don't know when it was added exactly, but https://legacy.imagemagick.org/Usage/anim_opt/ dates back to 2007 and already mentions it.

**Comment by jklymak** [comment]
I'm not really convinced that we should change the defaults like this, but rather users should be choosing these sorts of things depending on their application.  This is presumably lossy, and I would guess the lossy-ness depends on the animation.

**Review by tacaswell — APPROVED** [review]

**Review by dopplershift — APPROVED** [review]

**Pull request merged**
