### PR TITLE
mep12 on pstest.py

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
looks like this one passed too! :smile:

**Comment by WeatherGod** [comment]
This one is basically identical to one of the other ones. I suspect this was an old test script before the days of the testsuite. I would just get rid of it to reduce clutter.

**Comment by ericmjl** [comment]
I see.

To clarify: I will delete `pstest.py` from my branch, then submit a PR. Yes/no?

**Comment by WeatherGod** [comment]
Yes and No. Delete it in this branch, then just push it up, updating this PR. In a sense, it is a MEP12, because we are "cleaning up" outdated pylab examples. No need for a new PR.

**Pull request merged**
