### PR TITLE
Deprecate add_subplot(<no positional args>) silently doing nothing.

### PR DESCRIPTION
**Pull request by anntzer**
To avoid head-scratching when `add_subplot(projection="3d")` does
nothing (the correct call is `add_subplot(111, projection="3d")`).

Also a poll: after the deprecation period, should `add_subplot(<no positional args>)`
- raise an exception?
- behave as `add_subplot(111, **kwargs)` (see the mplot3d case above for a reasonable use case)?

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Looks like it needs a test.

**Comment by anntzer** [comment]
Seems like a bit overkill right now; if we do make add_subplots() behave like add_subplots(111) then I'll add a test at that time...

**Comment by jklymak** [comment]
POLL: add_subplot() adds a plot...

**Comment by timhoffm** [comment]
Just to be fair:
POLL: add_subplot() should raise an exception

**Comment by tacaswell** [comment]
- `add_subplot()` should add an axes to match the behavior of `plt.subplots()`
 - `add_subplot()` should raise because it has never done anything before.

The `projection='3d'` case is pretty persuasive for the first one.

**Comment by anntzer** [comment]
Do we even want a deprecation period here, or should we just switch directly to adding the 111 plot?
Upvote for switching immediately, downvote for a deprecation period.

**Comment by tacaswell** [comment]
What is the use-case story for someone _intentionally_ passing nothing into `add_subplot` and relying on it doing nothing?  The best I can come up with is some elaborate custom GUI embedding where they are relying on us to do the "no user input -> no action" logic rather than owning it, but that is a stretch.

**Comment by anntzer** [comment]
The same question applies to many other changes I've proposed over the years, but I've learnt better...

**Comment by tacaswell** [comment]
This code appears to go back to 18dca6619db9c3844bcfc56580362f3a60b54f53 .

`add_axes` has the same behavior, we should change it in both places.

@anntzer I do feel your frustration, but telling apart "there is no use case, it is like this by coincidence" from "this is critical to a use-case that I am not familiar with" from "this used to be part of an important use-case that no longer exists" is subtle (because it involves proving a negative and / or knowing what you don't know).

**Comment by anntzer** [comment]
@jklymak why the needs-revision tag?  Did we decide to just skip the deprecation?

**Comment by jklymak** [comment]
Yeah I think so, right?  As in no one could think of a case where the do nothing behaviour would be desirable.

**Comment by jklymak** [comment]
I guess add_axes should also be checked out as well?

**Comment by anntzer** [comment]
I don't think there's a sane default rectangle for add_axes?

**Comment by anntzer** [comment]
Changed the behavior of add_subplot as suggested.

**Comment by jklymak** [comment]
I'm going to merge on the basis of the polls above, despite the fact @dstansby's approval somewhat predated those changes.

**Pull request merged**
