### PR TITLE
FIX/DOC - make Text doscstring interp more easily searchable

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

We use docstring interpolation for `Text` in quite a few places, but that is extremely hard to trace through the code.  Changed to `_Text_docst`.  

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — COMMENTED** [review]
To be more specific than `docst`, I would call this `Text_kwargs` or `Text_properties`. The latter would be even more correct but is a bit difficult due to the ambiguity between matplotlib properties and python properties. So rather `Text_kwargs` should be good enough. - Also the name is essentially a key for looking up in `docstring.interpd` so no added value in prefixing with `_`.

**Comment by jklymak** [comment]
Sure.  We have `_Line2d_docstr` and `_legend_kw_doc`.  So I just chose one of them

**Comment by timhoffm** [comment]
That could also be cleaned up for clarity :smile:.

Thinking a bit more: We should always use `Class_kwdoc` for `artist.kwdoc` output, i.e. docstring.interpd.update(*Class*_kwargs=artist.kwdoc(*Class*)).

*Disclaimer:* I still find the name `kwdoc` imprecise and unclear, but that's tied to the function `artist.kwdoc` and renaming that is a bit larger effort. - Actually I suppose it should be private anyway.

**So proposal:** Change to `Text_kwdoc` here and we do other ones in follow up PRs (or if you want to invest more, you can change all here).

Other interpolation names could also be unified but that's for another PR.

**Comment by jklymak** [comment]
Sure!

**Review by tacaswell — APPROVED** [review]

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
