### PR TITLE
Provide arguments to mencoder in a more proper way

### PR DESCRIPTION
**Pull request by pupssman**
As  discussed in #4003 

Regarding whitespace changes -- PEP8 is violated like everywhere, can't stand it.

### CODE REVIEW

**Comment by pupssman** [comment]
Need second look at the test suit to find out what tests do I turn on.

**Comment by dopplershift** [comment]
I wouldn't be surprised if I never checked passing anything beyond codec to mencoder. I can confirm the problem here with master and that this pr fixes the problem on my system, so +1 from me.

**Comment by dopplershift** [comment]
I'll add that it doesn't look like our simple smoketest exercises any additional movie generation parameters, so it wouldn't have caught this.

Also, we don't even try to install mencoder on Travis--I'm not sure if that's an oversight or intentional.

**Comment by WeatherGod** [comment]
Didn't we try to do that at one point, but gave up due to weird problems?

**Comment by dopplershift** [comment]
All I can find is #2678 , which doesn't indicate that it's ever tried. I can throw up a PR and see what happens.

**Comment by tacaswell** [comment]
My only memory of that is memcoder was being difficult and went with the low hanging fruit of testing everything else.  

Either we fixed something else sense then (doubtful) or I am/was confused (likely) as the tests seem to work now.

**Comment by dopplershift** [comment]
Either way, we can discuss anything else about the mencoder tests in #4005, and just leave this about the fixes for commandline args. Does anyone have any objections to this PR?

**Comment by tacaswell** [comment]
Probably should be back-ported to 1.4.x

**Comment by tacaswell** [comment]
cherry-picked as 09be64efb53828df7220f0efc56b0578ad796bc3

**Pull request merged**
