### PR TITLE
Adjust default linewidth to 1.5

### PR DESCRIPTION
**Pull request by efiring**
The default linewidth was changed from 1 to 2.5 for v2.0 in rcsetup, but was given as 2.0 in matplotlibrc.template.  Although a fat line can look good for very simple plots, it does not work well for more complex plots.  Therefore I recommend a compromise value of 1.5.  Regardless of whether this recommendation is accepted, the value in rcsetup needs to match the value in matplotlibrc.template, as it does with this PR.

### CODE REVIEW

**Comment by efiring** [comment]
It looks like the test failures are all image comparisons involving backend_pgf--that seems odd.

**Comment by jenshnielsen** [comment]
@efiring The pfg backend tests does the image comparison in a slightly odd way so it's not running with the classic style but with the default one

**Comment by mdboom** [comment]
Yeah.  :+1: on this (once the PGF baselines are updated).

**Comment by tacaswell** [comment]
:+1: on this from me as well.

**Comment by jenshnielsen** [comment]
And me too 👍

**Comment by efiring** [comment]
Closing and reopening after merging #6290 to trigger the tests again.

**Comment by efiring** [comment]
Trying again after removing the commit that modified the pgf test files.

**Comment by efiring** [comment]
I'm stuck; after many tries, I still can't get a mergeable collection of changesets in which the pgf tests pass.

**Comment by mdboom** [comment]
My guess is some mismatch in LaTeX libraries between your machine and Travis.  I've had success in the past with this, so I'll give it a go.

**Comment by mdboom** [comment]
Closed by #6300.

**Pull request closed without merging**
