### PR TITLE
Fix trivial typo in deprecation warning message.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

fixup for #15894.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by story645** [comment]
I'm a bit confused on how this is release critical but tagged for 3.3?

**Comment by jklymak** [comment]
Some of his PRs get lost?

**Comment by anntzer** [comment]
yup, just making sure it doesn't fall between the cracks

**Comment by astromancer** [comment]
I personally found this deprecation message a little unclear. It wasn't obvious to me upon first reading it that the deprecation is specifically for lists of strings and not for the latex preamble parameter as a whole. Might be good to explicitly include the words "list of strings" in the deprecation message instead of (or in addition to) printing the actual user input list.

**Pull request merged**
