### PR TITLE
Make sure that pyparsing 2.0.4 is not installed.

### PR DESCRIPTION
**Pull request by jenshnielsen**
It has broken python 3 support due to print statements in the code.

Just released today so hopefully there will be a new release soon fixing this

### CODE REVIEW

**Comment by jenshnielsen** [comment]
See https://sourceforge.net/p/pyparsing/bugs/82/

**Comment by mdboom** [comment]
Thanks.  I guess we should backport this to 1.5.x as well so we can keep the testing alive and working there.

**Comment by jenshnielsen** [comment]
Yes I think we should. I guess `pip install matplotlib` will also pull in 2.0.4 without this

**Comment by mdboom** [comment]
Yes -- `pip` will follow these instructions.

**Comment by jenshnielsen** [comment]
In that case I think we should definitely backport

**Comment by mdboom** [comment]
Backported to 1.5.x as 3c5d20d4626509df3216422dee6bb6c7520c9e7e

**Comment by jenshnielsen** [comment]
For reference 2.0.5 was just released fixing this.

**Pull request merged**
