### PR TITLE
Stop codecov from posting messages

### PR DESCRIPTION
**Pull request by anntzer**
See https://docs.codecov.io/docs/pull-request-comments-1#section-disable-comment and https://docs.codecov.io/docs/codecov-yaml#section-can-i-name-the-file-codecov-yml-

Also remove travis helper scripts unused since #6568.

### CODE REVIEW

**Comment by QuLogic** [comment]
According to the [FAQ](https://docs.codecov.io/docs/codecov-yaml#section-can-i-name-the-file-codecov-yml-) on the second page, it can be anywhere, so maybe put it in `ci/codecov.yml` instead of cluttering up the root.

**Comment by anntzer** [comment]
Good idea.

**Comment by QuLogic** [comment]
Err, I hope that's because the file's not on `master` yet.

**Comment by anntzer** [comment]
"lol"
(I have no idea, just following the docs... in any case this should be the coverage for the *first* version, where .codecov.yml was still in root.  Let's see what happens now.)

**Comment by Carreau** [comment]
I would strongly recommend the [codecov browser extension](https://chrome.google.com/webstore/detail/codecov-extension/keefkhehidemnokodkdkejapdgfjmijf?hl=en-US)  which show the coverage diff directly in GitHub UI. Also it's strange you get coverall commit status but not codecov.

**Comment by anntzer** [comment]
That is a neat extension!

**Comment by Carreau** [comment]
> That is a neat extension!

Yeah, I have the not-so-secret wish to have time to write one  for vim to highlight the coverage of most recent commit in my gutter.

**Comment by QuLogic** [comment]
I think codecov is waiting for appveyor; it only posted before because @anntzer force-pushed which triggered an auto-cancel on appveyor.

**Comment by QuLogic** [comment]
Fingers crossed this works in the future.

**Pull request merged**
