### PR TITLE
Update colormap user page

### PR DESCRIPTION
**Pull request by kthyng**
This is to address request in PR #5591 by @jenshnielsen to have colorspacious be used for colorspace conversions. I changed the grayscale.py code to do so, and to use the CAM02-UCS colorspace instead of CIELAB and removed the Lfunction part of the docs on colormaps and the code itself because I don't think it is very helpful anymore.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Looks good, Will merge when Travis is happy. Thanks @kthyng

**Comment by tacaswell** [comment]
I think this should be backported to 1.5.x so next round of official docs get updated, but if we rebuild the docs for 1.5.0 this change will not be included.

Sound reasonable?

**Comment by jenshnielsen** [comment]
:+1:

**Comment by tacaswell** [comment]
backported as 896d089c1ea0ee4a976a32cce6a27e986c1e197a

**Pull request merged**
