### PR TITLE
No explicit mathdefault in log formatter

### PR DESCRIPTION
**Pull request by mdboom**
The log formatter has, for some time, used `mathdefault` to make the text of the superscripts match the regular text (i.e. to be in Vera Sans).  In 2.0, `mathtext.fontset` is now `dejavusans` by default, and therefore already matches the default font.  This is just a simplification to make things faster and more consistent.

### CODE REVIEW

**Comment by mdboom** [comment]
I think this one is good to go (and is apparently uncontroversial).

**Comment by WeatherGod** [comment]
yup, looks good to me. Does this get backported to 2.0?

**Comment by mdboom** [comment]
Yes.  This is for 2.0.

**Comment by tacaswell** [comment]
backported to v2.0.x as 8bf6705

**Pull request merged**
