### PR TITLE
Docs / examples fixes.

### PR DESCRIPTION
**Pull request by anntzer**
`examples/axes_grid1/parasite_simple2.py`

See #5864 for the weirdness before the fix.

After the fix (master / 1.5.0):
screenshot_20160117_114835
screenshot_20160117_114907

### CODE REVIEW

**Comment by anntzer** [comment]
Bundling in an unrelated broken link fix.

**Comment by mdboom** [comment]
I think the failure is unrelated (we've seen it creep up in other PRs).

:+1: from me otherwise, though.

**Comment by zblz** [comment]
@anntzer - I fixed the arcsecond thing in #5880, so now `$''/yr$` should parse correctly (as in TeX). I'm not sure whether it's worth making the change to `\prime` if it will get typset correctly (eventually) as it is now.

**Comment by anntzer** [comment]
Then I'd still need to change `$^{''}$` to `$''$` right?  A quick check with `usetex=True` tells me `$^{''}$` is even smaller (which makes sense as `$'$` is `$^\prime$` and `\prime` is a larger version of `'`).

**Comment by zblz** [comment]
Yes! I did not realize the original was `$^{''}$`, that definitely makes no sense.

**Comment by jenshnielsen** [comment]
Thanks Backported to 1.5.x as 6405839866563e9976bf02bef80d6c451c169b2b

**Pull request merged**
