### PR TITLE
Closes #22011: Changes to SubFigures so it behaves like a regular artist

### LINKED ISSUE #22011: [Bug]: subfigures messes up with fig.legend zorder
### Bug summary

When using subfigures, legends called with `fig.legend()` are hidden behind the subfigure background **and** the axes background.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(1, 10, 10)
y1 = x
y2 = -x

fig = plt.figure(constrained_layout=True)
subfigs = fig.subfigures(nrows=2, ncols=1)

for subfig in subfigs:
    axarr = subfig.subplots(1, 2)
    for ax in axarr.flatten():
        l1, = ax.plot(x, y1, label='line1')
        l2, = ax.plot(x, y2, label='line2')
            #
        ax.set_facecolor('none')  # Comment this line
    subfig.set_facecolor('none')   # and this line to make the legend hidden behing the white backgrounds
l = fig.legend(handles=[l1, l2], loc='upper center', ncol=2)
plt.savefig('subfigures_figlegend.png', dpi=200)
plt.show()
```

### Actual outcome

With `ax.set_facecolor('none')` and `subfig.set_facecolor('none')` commented:
subfigures_figlegend2
With `ax.set_facecolor('none')` and `subfig.set_facecolor('none')` not commented, i.e transparent backgrounds:

subfigures_figlegend

### Expected outcome

Legend should be on the top of the backgrounds, as produced when building the figure with `plt.subplots()`:

```
fig, axarr = plt.subplots(2, 2, constrained_layout=True)
for ax in axarr.flatten():
    l1, = ax.plot(x, y1, label='line1')
    l2, = ax.plot(x, y2, label='line2')
    #
    ax.legend()
fig.legend(handles=[l1, l2], loc='upper center', ncol=2)
plt.savefig('subplots_figlegend.png', dpi=200)
plt.show()
```
subplots_figlegend

### Additional information

- This does not happen for `ax.legend()` and `subfig.legend()`.

### Operating system

Ubuntu 20

### Matplotlib Version

3.5.0

### Matplotlib Backend

QtAgg

### Python version

3.8.10

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by cgadal**
Closes #22011:

- changing self._get_draw_artists() so subfigs are now part of the artists' list.
- changing draw() methods so subfigures are drawn like regular artists

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
Instead of commenting out the code, can you remove it entirely? Commented out code like this (especially) is likely to cause confusion on whether it was meant to be reintroduced or removed, and so if we want it gone it should be fully gone (we have git for a reason, if we do ever want it back).

Additionally while we seem to have not triggered any existing tests, tests of the expected behavior would help to ensure we don't break it in the future.

**Comment by cgadal** [comment]
For testing, do you think something like this is enough:

```python
def test_subfigure_zorder():
    # test that we can change the order of a subfigure...
    fig = plt.figure(layout='constrained')
    subfig = fig.subfigures(1, 1)
    subfig.set_zorder(5)
    assert  subfig.get_zorder() == 5
```
Or should I go up to an image comparison, with something like this, to test that subfigures are indeed plotted under fig level artists if their order is not changed ?

subfigures_figlegend2

My underlying question is probably "Is there something like too much testing ?" ?

Thanks !

**Comment by tacaswell** [comment]
This may require an image test.

The test you wrote will pass on the current release (the problem is that we are ignoring the zorder not that the `set_zorder` / `get_zorder` machinery was broken)!

The test needs to check that things are really rendered in the right order which requires looking at the output.

**Comment by cgadal** [comment]
I am not sure if I am supposed to say so, but this is ready for review :) Thanks !

**Comment by QuLogic** [comment]
There seem to be some unrelated style changes here, which makes it difficult to look at what exactly you've changed.

**Comment by cgadal** [comment]
Oh, I did not remove the auto-formatting on this project. I will fix that ASAP,

**Comment by cgadal** [comment]
I corrected all commits removing any style change !

Now it is failing check `codecov/projetcs/tests`, but I remember someone telling me on the Gitter/incubator not to worry too much about this. Is that OK ?

**Comment by tacaswell** [comment]
Codecov failing on the tests module is one of the ones we worry about the most (it is easy to write tests that "pass" because they do not run like you expect 😉 ).

**Comment by cgadal** [comment]
Oh, never mind then. Could you give me some pointers on what to do next?

From what I understand, the test is failing due to a decrease in code coverage of the tests.
However, I do not understand how my changes could affect the tests `test_tickers.py` and `test_backends_interactive.py`.

From what I understand, this fails because some parts of the tests are not tested due to `try.. except..` statements. This looks unrelated to the changes I have made. Should I rebase on main? 

This is all really blurry in my head, so please do not hesitate to point out where I am mistaken :)

**Comment by tacaswell** [comment]
https://app.codecov.io/gh/matplotlib/matplotlib/commit/265e49ebe3bd3a10979b55b54101eda5676506b6/indirect-changes is from a different PR and shows only one CI job hitting that code (and randomly picking up some coverage)

I am guessing there is only one CI job that actually has the DE locale available and somehow the coverage of code run in the subproccesses is flaky (?!).   I opened https://github.com/matplotlib/matplotlib/pull/27581 as try and make that test run on more of our CI jobs to reduce the odds it gets lost.

**Review by tacaswell — APPROVED** [review]
see comment about the coverage failure (unrelated).

**Review by ksunden — APPROVED** [review]

**Comment by QuLogic** [comment]
Thanks @cgadal! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.

**Pull request merged**
