### PR TITLE
Improve paper size selection for PS backend

### LINKED ISSUE #7551: automatic papersize selection by ps backend is almost certainly broken
No minimal example, but the relevant chunk (`backend_ps.py`) is
```python
papersize = {'letter': (8.5,11),
             'legal': (8.5,14),
             'ledger': (11,17),
             'a0': (33.11,46.81),
             'a1': (23.39,33.11),
             <elided>
             'a10': (1.02,1.457),
             'b0': (40.55,57.32),
             'b1': (28.66,40.55),
             <elided>
             'b10': (1.26,1.76)}

def _get_papertype(w, h):
    keys = list(six.iterkeys(papersize))
    keys.sort()
    keys.reverse()
    for key in keys:
        if key.startswith('l'): continue
        pw, ph = papersize[key]
        if (w < pw) and (h < ph): return key
    else:
        return 'a0'
```

Note that the sorting is by name, which means that the size is the first one among "a9, a8, ..., a2, a10, a1, b9, b8, ..., b2, b10, b1" (in that order) that is larger than the requested size -- which makes no sense.

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Closes #7551  
Closes #16657

Sorting based on size rather than name. Use <= for comparison, not <.

Not sure why `l*` sizes are skipped? Should one also skip `b*`?

Maybe use the case in #16657 to test this?

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
I agree. More like you pointed out in #7551: the selection logic is most likely incorrect. So it may not be the best way to support automatic selection, but now it at least works as one might expect it to.

I have not looked very deep into this, so I do not really know when the paper size is and when it is simply ignored... But I agree that it may be better to see if one can find a better approach to deal with this. (And if none has shown up for 3.6, one can revisit this.)

**Comment by tacaswell** [comment]
I'm inclined to merge something like this.  Independent of if this is a good idea, we should at least do it in a non-broken way.

**Comment by anntzer** [comment]
The fact that it has never worked properly (likely for many many years) suggests that no one is really relying on this, though...

**Comment by timhoffm** [comment]
> I'm inclined to merge something like this. Independent of if this is a good idea, we should at least do it in a non-broken way.

> The fact that it has never worked properly (likely for many many years) suggests that no one is really relying on this, though...

Be careful here. It can well be that people have a specific figure size that selected a reasonable (maybe not optimal) page size. Or they might have set up some post processing to fix the size later. Changing, even if it is improving, would break those people. We should do this only once. Now changing the detection algorithm only to abandon it in the next release can cause extra migration pain. Let's decide once how this should be handled and stick with it.

**Comment by tacaswell** [comment]
@timhoffm Fair. I take back my statement.

**Pull request closed without merging**
