### PR TITLE
Pin OSX CI to numpy<1.15 to unbreak the build.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

1st commit: Trivial cleanups to travis setup.
2nd commit: Pin OSX CI to numpy<1.15 to unbreak the build.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Is this actually a bug w 1.15 or just a rounding change on Macos?  if the later I’d just change the tolerance of the csd test.

**Comment by anntzer** [comment]
I don't know and don't really plan to investigate this :)

**Comment by jklymak** [comment]
OK, well, #11754 also has a tolerance fix for this (increased to .002).  Given that the failing test is failing with .001, I think the problem is better solved by adjusting the tolerance on the test.

**Comment by jklymak** [comment]
Closed in lieu of #11767

**Pull request closed without merging**
