### PR TITLE
TST: tweak  how to pass args to nose

### LINKED ISSUE #6539: network tests are not skipped when running tests.py with --no-network
To help us understand and resolve your issue please check that you have provided
the information below.

- [x] Matplotlib version, Python version and Platform (Windows, OSX, Linux ...)

> 1.5.2rc2, 2.7.11/3.5.1, Fedora rawhide

- [x] How did you install Matplotlib and Python (pip, anaconda, from source ...)

> From source.

- [ ] If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
      that demonstrates the issue i.e a small piece of code which reproduces the issue
      and can be run with out any other (or as few as possible) external dependencies.

```
python2 tests.py --no-network
```
or
```
python3 tests.py --no-network
```
The following tests are failing:

- `lib/matplotlib/tests/test_image.py:549` `test_load_from_url()`
- `lib/matplotlib/tests/test_style.py:60` `test_use_url()`

### PR DESCRIPTION
**Pull request by tacaswell**
closes #6539

### CODE REVIEW

**Comment by WeatherGod** [comment]
so, why didn't the original form work? Could it be version-dependent?

**Comment by tacaswell** [comment]
There are somethings I do not want to know :wink:

**Comment by WeatherGod** [comment]
@rathann, could you please try out this patch to double-check that it works as expected for you?

**Comment by rathann** [comment]
@WeatherGod , unfortunately I'm still getting this:
```
[...]
======================================================================
ERROR: matplotlib.tests.test_image.test_load_from_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/python-matplotlib-1.5.2-0.1.rc2.fc25.x86_64/usr/lib64/python2.7/site-packages/matplotlib/tests/test_image.py", line 552, in test_load_from_url
    "http://matplotlib.org/_static/logo_sidebar_horiz.png")
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1229, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1196, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/builddir/build/BUILDROOT/python-matplotlib-1.5.2-0.1.rc2.fc25.x86_64/usr/lib64/python2.7/site-packages/matplotlib/testing/disable_internet.py", line 71, in new_function
    raise IOError("An attempt was made to connect to the internet "
IOError: An attempt was made to connect to the internet by a test that was not marked `remote_data`.

======================================================================
ERROR: matplotlib.tests.test_style.test_use_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILDROOT/python-matplotlib-1.5.2-0.1.rc2.fc25.x86_64/usr/lib64/python2.7/site-packages/matplotlib/tests/test_style.py", line 63, in test_use_url
    with style.context('https://gist.github.com/adrn/6590261/raw'):
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/builddir/build/BUILDROOT/python-matplotlib-1.5.2-0.1.rc2.fc25.x86_64/usr/lib64/python2.7/site-packages/matplotlib/style/core.py", line 121, in context
    use(style)
  File "/builddir/build/BUILDROOT/python-matplotlib-1.5.2-0.1.rc2.fc25.x86_64/usr/lib64/python2.7/site-packages/matplotlib/style/core.py", line 90, in use
    raise IOError(msg % style)
IOError: 'https://gist.github.com/adrn/6590261/raw' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.

----------------------------------------------------------------------
Ran 5202 tests in 113.233s

FAILED (KNOWNFAIL=453, SKIP=14, errors=2)
error: Bad exit status from /var/tmp/rpm-tmp.YogPU3 (%check)
```

**Pull request merged**
