### PR TITLE
Fixing Bug with RGB photos in imshow using alpha array-type

### PR DESCRIPTION
**Pull request by NikosNikolaidis02**
## PR summary
"
This pull request tries to ressolve issue #26092 
I've tried to added the proposal solution of @tacaswell , but I would like your feedback what else I should try to include to ressolve this issue.
"

## PR checklist

- [ ] "closes #26092 " is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
Thank you for your contribution @NikosNikolaidis02!  Please could you have a look through the checklist in the PR summary above and also the [pull request guidelines](https://matplotlib.org/devdocs/devel/coding_guide.html) in the developers' guide.  In particular

* This will need new tests to prove that the code change has the desired effect.
* The existing tests need to pass: currently four are failing.
* We appreciate the PR title to describe what the change is about.

I'm going to mark this as "draft" for now.  Please mark it as "ready for review" when you are ready.  In the meantime, if you need help, feel free to ask questions here.  Or you may prefer to ask them in our [incubator gitter room](https://matplotlib.org/stable/devel/contributing.html#contributor-incubator).

**Comment by NikosNikolaidis02** [comment]
> Thank you for your contribution @NikosNikolaidis02! Please could you have a look through the checklist in the PR summary above and also the [pull request guidelines](https://matplotlib.org/devdocs/devel/coding_guide.html) in the developers' guide. In particular
> 
> * This will need new tests to prove that the code change has the desired effect.
> * The existing tests need to pass: currently four are failing.
> * We appreciate the PR title to describe what the change is about.
> 
> I'm going to mark this as "draft" for now. Please mark it as "ready for review" when you are ready. In the meantime, if you need help, feel free to ask questions here. Or you may prefer to ask them in our [incubator gitter room](https://matplotlib.org/stable/devel/contributing.html#contributor-incubator).

Hello @rcomer, 

Thank you for your fast response!

I will try to fix these issues in these days, so I would really like your guidelines through the process!

**Comment by NikosNikolaidis02** [comment]
@rcomer should I ignore the failure on macos?

**Comment by QuLogic** [comment]
That is also a known issue that can be ignored for now.

**Comment by NikosNikolaidis02** [comment]
So when my pull request will be open to be reviewed?

**Comment by rcomer** [comment]
At the moment it looks like you only applied the patch from https://github.com/matplotlib/matplotlib/issues/26092#issuecomment-1583090581, but that comment also says that that patch is not the whole solution.  To proceed, we would need a complete solution, including new tests to confirm the behaviour is now as we want it.

I do not want to discourage you from contributing in Matplotlib but I will note that the issue is marked "medium difficulty".  So if you are inexperienced with python or testing, it may be better to choose a different issue to work on initially.

**Comment by NikosNikolaidis02** [comment]
Ok, thank you! I will try to continue with this issue, but I would appreciate your help on testing on which I am unexperienced.

**Comment by rcomer** [comment]
We have guidance about writing tests here:
https://matplotlib.org/stable/devel/testing.html

But I also see from https://github.com/matplotlib/matplotlib/issues/26092#issuecomment-1583090581 that the current change
> does not address the "what about RGBA" issue and I think will double apply the alpha in scalar cases.

So there is probably also still more to do in the main code.

**Comment by rcomer** [comment]
Hi @NikosNikolaidis02 I’m guessing you decided not to pursue this PR since you opened one for a different issue.  So I’m going to close it so it’s more obvious to others that they can work on it.

If you are still interested in working on this, please do comment and we can re-open.

**Pull request closed without merging**
