### PR TITLE
Fix typo in pyplot_scales.py

### LINKED ISSUE #5642: Mistype in pyplot_scales.py of pyplot_tutorial.rst :: a minor bug in docs
Two diagrams are plotted to the same area in matplotlib/doc/users/pyplot_tutorial.rst :: pyplot_scales.py

Please see the attached image.

screenshot584

### PR DESCRIPTION
**Pull request by WeatherGod**
Closes #5642

### CODE REVIEW

**Comment by WeatherGod** [comment]
Huh, the web-based editor doesn't seem to make the branch on your own repo, but in the same repo as the project. Oops! We should make sure that we delete this branch once done.

**Comment by mdboom** [comment]
That's weird about the web-based editor making a branch in the main repo.  I feel like it didn't used to do that, but I don't use that feature very often.  I hope that only happens for those of us with commit rights to matplotlib (and I suspect it does) otherwise it's a definite authorization violation.

**Comment by jenshnielsen** [comment]
It's a new feature that it allows you to create a branch and make a PR. It just used to directly edit files in the current branch.

**Comment by WeatherGod** [comment]
I am pretty sure I remember some people contributing tiny patches to us
from the editor before that didn't have commit rights. I suspect my issue
is that I have commit rights, so it picked this repo instead of my fork. I
probably should have done the edit in my fork instead, but I am not sure it
would have made a PR against matplotlib's repo. Weird.

**Comment by jenshnielsen** [comment]
@WeatherGod If you do it agains a repo where you don't have rights it does indeed fork however if you had rights it used to only allow you to edit the files in place on the branch.

**Comment by WeatherGod** [comment]
This looks good to go.

**Comment by tacaswell** [comment]
backported to v1.5.0-doc as 37f08ba

**Pull request merged**
