### PR TITLE
Consolidating Installation Docs [WIP]

### LINKED ISSUE #17412: Document the dependency on the type1ec LaTeX package
I've just run into https://github.com/matplotlib/matplotlib/issues/16911. The problem is that the `type1ec` LaTeX package is necessary when `text.latex.unicode` is `True` in the `rcParams` (which is the default since 3.0). On debian this is part of the `cm-super` system package. I've had some trouble discovering this information.

  1. As of https://github.com/matplotlib/matplotlib/pull/14151 the problem is clear at least: `type1ec` is missing. (Although I got this error using a completely innocent, ascii-only, as far as I know ligature-free label in a plot. The error hadn't come up two figures earlier with other, innocent, ascii-only labels. And this is without `text.usetex`.)
  2. This LaTeX package [isn't mentioned anywhere on the matplotlib website](https://matplotlib.org/search.html?q=type1ec), and [only one closed issue](https://github.com/matplotlib/matplotlib/issues/16911) mentions it.
  3. It's not trivial to track down the appropriate debian package, fortunately the linked issue took care of this.
  4. As a side note, I read that the default for `text.latex.unicode` changed to `True` in 3.0 [here](https://github.com/matplotlib/matplotlib/pull/14151), but this is not mentioned [in the easy-to-find What's new](https://matplotlib.org/users/prev_whats_new/whats_new_3.0.html), only in the [hard-to-discover API changes](https://matplotlib.org/api/prev_api_changes/api_changes_3.0.0.html).

Ideally the dependency should be mentioned somewhere, perhaps among [the installation guide](https://matplotlib.org/users/installing.html). Currently that page mentions

> LaTeX and GhostScript (>=9.0) : for rendering text with LaTeX;

In [Text rendering with LaTeX](https://matplotlib.org/tutorials/text/usetex.html) (which focusses on `usetex`) it mentions

> On Ubuntu and Gentoo, the base texlive install does not ship with the type1cm package. You may need to install some of the extra packages to get all the goodies that come bundled with other latex distributions.

Note that `type1cm` is part of `texlive-latex-extra` which is a straightforward system package to install for LaTeX stuff, and for matplotlib in particular. However, `type1ec` is not included there, and what's worse, `apt search type1ec` doesn't turn up any resuts (unlike the same for `type1cm`).

### PR DESCRIPTION
**Pull request by r0cketr1kky**
## PR Summary
This PR is an attempt at consolidating docs as suggested in #17327 and will also track my progress as proposed [here](https://discourse.matplotlib.org/t/developing-matplotlib-entry-paths-for-gsod20-suggestions/21191).

As of now, I have made a few small changes in the `INSTALL.rst` file and also included the Conda installation in it. 

## PR Checklist

- [x] Small changes in `INSTALL.rst`
- [ ] Individual Documentation for different systems
- [ ] Include all changes suggested at #17327 
- [ ] Add reference to the one canonical page in `INSTALL.rst` - Long term plan
- [ ] Fix #17412 also

### CODE REVIEW

**Comment by story645** [comment]
Thanks for tackling this! I think long term Install.rst shouldn't really exist, or at least it should mostly only link to the one canonical place for the install docs.

**Comment by r0cketr1kky** [comment]
Thanks for the feedback! That actually makes sense, maybe not removing it entirely but referring it to one place would do the trick. I'll add this to the checklist :)

**Comment by jklymak** [comment]
This seems orphaned

**Comment by story645** [comment]
I think this might be closable in light of @timhoffm's recent PRs?

**Comment by jklymak** [comment]
Agreed but if there is still some todo, feel free to submit a new PR!

**Comment by timhoffm** [comment]
IMHO https://matplotlib.org/devdocs/users/installing.html is good now.


https://matplotlib.org/devdocs/devel/development_setup.html still needs #17096

**Pull request closed without merging**
