### PR TITLE
Merge "Scatter Symbol" and "Scatter Custom Symbol" examples

### LINKED ISSUE #22266: [Doc]: Improve examples in documentation
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html

### Problem

`housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.4,
 s=housing["population"]/100, label="population", figsize=(10,7),
 c="median_house_value", cmap=plt.get_cmap("jet"), colorbar=True,
)`
I recently found the above code on Jupyter notebook and I referred matplotlib documentation in order to understand about the parameter s, c and alpha. But, I found it difficult to understand about these parameters, and found it unclear due to lack of explanation in the examples provided. The examples provided just has code and no explanation of the parameters.

### Suggested improvement

1. Along with making the users select the examples manually and read the code, I feel that it would also be good if there is a default example available which contains few basic parameters to give a feel of what a particular function does.
2. I feel there should be a clear explanation of what the particular parameter does, and not just code(in the examples).
3. It would be even better if an example is further modified by tweeking/changing the value of a particular parameter, so that the user can get an even better understanding of what the parameter does.
For Example: in this [https://matplotlib.org/stable/gallery/lines_bars_and_markers/scatter_symbol.html#sphx-glr-gallery-lines-bars-and-markers-scatter-symbol-py](url) page, you can provide different values of alpha like (0.5,0.2,08) in order to show how the output differs.

### Matplotlib Version

3.5.0

### PR DESCRIPTION
**Pull request by timhoffm**
Merge "Scatter Symbol" and "Scatter Custom Symbol" examples.

Remove "Scatter plot with pie chart markers". This is only a variant of
path-as-custom-symbol, which is already covered here. Also, all pie
markers in the scatter plot have the same data distribution, so the
pie is more a style thing and cannot convey additional
datapoint-specific information.

Also closes #22266 by using *sizes* instead of *s* and spelling out the
color to make their meaning clearer.

### CODE REVIEW

**Review by oscargus — APPROVED** [review]

**Comment by anntzer** [comment]
FWIW there's also https://matplotlib.org/stable/gallery/lines_bars_and_markers/scatter_star_poly.html.  Perhaps also link to https://matplotlib.org/stable/gallery/lines_bars_and_markers/marker_reference.html (which is more general and warrants being separate)?

**Comment by timhoffm** [comment]
Yes, but I don‘t have the time to work on this for now. Therefore I prefer to merge as is. Feel free to amend or open an issue so that we don‘t forget.

**Comment by timhoffm** [comment]
Self-merging based on the positive review as an incremental improvement. @anntzer I've added an issue based on your suggestion: #22663

**Review by dixon-kun — APPROVED** [review]
Ok now 👍

**Pull request merged**
