### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by timhoffm**

### CODE REVIEW

**Comment by dopplershift** [comment]
Can you update `.flake8` to remove the F401 ignore for these files? That way they stay cleaned up going forward.

**Comment by timhoffm** [comment]
Updated .flake8 for all changes but `backend_*.py: F401`. This also covers intended unused imports in some backends.

**Comment by dopplershift** [comment]
Which of course reveals that there are further unused imports in those files. Any interest in cleaning those up too?

**Comment by timhoffm** [comment]
Will look at these some time later. Some of them contain `FigureManager*` and `NavigationToolbar*` imports from other backends, which may actually be intended to be imported in the backend to make them available to users. But this needs clarification. Also I'd do a full search for unused F401 across the lib. But let's defer these things to a future PR.

**Pull request merged**
