### PR TITLE
Additional details on VS install on installation page

### PR DESCRIPTION
**Pull request by 23ccozad**
## PR Summary

Originally from an issue we resolved in [Gitter](https://gitter.im/matplotlib/matplotlib?at=62757238fa846847c951a836) as I was building from source. The docs currently don't specify which parts of Visual Studio that Windows users need when installing matplotlib from source. This PR adds this information to the docs, and also provides a link to a page from which VS can be downloaded.

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [X] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you @23ccozad ! 

This reads correctly to me, but I do not have a windows machine (or develop on windows regularly) so lack the expertise to actually review this....

**Review by andrew-fennell — APPROVED** [review]
Looks great!

I did a clean install on a Windows machine. I attempted to build without the packages that you specified and ran into the same errors. I installed the packages and it was able to build.

The next step to getting this merged is waiting for 2 maintainers with *write* access to approve this PR. For what it's worth, I approve!

**Comment by andrew-fennell** [comment]
There is a discrepancy in the naming of "C++ CMake tools for Windows" in previous version of Visual Studio (such as Visual Studio 2017).

However, if someone is going to install Visual Studio for the first time, they are likely downloading the latest version, so I don't think it is worth changing. I think any change or addition would make it confusing.

**Comment by oscargus** [comment]
Thanks @23ccozad for the PR and @andrew-fennell for checking and approving.

As documentation changes can be merged with a single approval (on the "better than before" premise) and the additional approval, I'll merge.

Congratulations on your first PR to Matplotlib! Hope to see you around!

**Review by oscargus — APPROVED** [review]

**Comment by oscargus** [comment]
meeseeksdev backport to v3.5.x
meeseeksdev backport to v3.5.2-doc

**Pull request merged**
