### PR TITLE
GradientLineCollection class has been added to support multicolored lines

### PR DESCRIPTION
**Pull request by ufukty**
## PR Summary

example usage of addition
> First 2 lines regular LineCollection lines. Sequential lines produced with GradientLineCollection. Code for this example is below.

**Motive**

Showing directional edges with arrows makes the image so cluttered, if the network has too much edges and nodes. So, the better way to differentiate which end is which end is drawing them with different colors. [I recently shared a work at Reddit's r/dataisbeautiful community](https://www.reddit.com/r/dataisbeautiful/comments/ktxcuo/oc_subreddits_with_most_links/) and people's reaction showed that this sort of visualization has some value in the eyes of audience.

**Implementation**

My implementation is not the perfect alternative. In summery, `GradientLineCollection` class is regular `LineCollection` class, although it creates that gradient effect by splitting each line into `pieces` smaller individually colored lines. Since, I already overly exceeded my free time, I can't dive in the deeper areas of API. I think that implementation will work great until someone figure out better way. 

**Example of possibility with addition**

That image shows the subreddits with most hyperlinks. Orange for outgoing links, blue for incoming links. Image shows that incoming links are well distributed to larger set of communities compared to outgoing links.

network visualization example

**Example usage**

```python
# Regular version
lc = mpl.collections.LineCollection(
    [[(0, 4), (1, 4)], [(0, 4.3), (1, 4.3)]],
    colors=["r", "b"],
    linewidths=10,
    alpha=0.8,
)

glc1 = GradientLineCollection(
    [[(0, 3), (1, 3)]],
    gradient={
        0.0: "red",
        1.0: "blue",
    },
    linewidths=10,
    alpha=0.8,
    pieces=50
)

glc2 = GradientLineCollection(
    [[(0, 2), (1, 2)]],
    gradient={
        0.0: (1, 0, 0, 1),
        0.4999: [1, 0, 0, 0],
        0.5: "#0000ff00",
        1.0: [0, 0, 1, 1],
    },
    linewidths=10,
    alpha=0.8,
    pieces=200
)

glc3 = GradientLineCollection(
    [[(0, 1), (1, 1)]],
    gradient={
        0.0: "red",
        0.2: "yellow",
        0.4: "green",
        0.6: "cyan",
        0.8: "blue",
        1.0: "magenta",
    },
    linewidths=10,
    pieces=200
)

ax = plt.gca()
ax.add_collection(lc)
ax.add_collection(glc1)
ax.add_collection(glc2)
ax.add_collection(glc3)
```

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by ufukty** [comment]
related #6040

**Comment by jklymak** [comment]
This seems interesting, and I assume the line can be curved.  

However, we already have an API for mapping between colors and numbers between 0 and 1.  I think it would be better if your "gradient" argument were replaced by a colormap/norm pair for consistency with the rest of the library.  I also think that would save you a lot of new code.

**Comment by ufukty** [comment]
@jklymak I don’t think lines can be curved. I thought there are only predefined cmaps. If they allow customization the way current solution does then gradients could be replaced

**Comment by jklymak** [comment]
Sure there is a whole tutorial on how to create colormaps.  https://matplotlib.org/tutorials/colors/colormap-manipulation.html

**Comment by ufukty** [comment]
Thanks for link. Will look into it when I get a chance

**Comment by melissawm** [comment]
Hi @ufukty  - are you interested in continuing this work? If so, please mark the PR as ready for review and let us know if you need help with the rebase, we have [instructions for that here](https://matplotlib.org/devdocs/devel/development_workflow.html#rebasing-on-upstream-main). Thanks!

**Comment by timhoffm** [comment]
As given, this is a nice application and is thus not well suited for core matplotlib. If somebody has interest in following up, I suggest to start a third-party package. If we go towards for lines inside core matplotlib, #28242 is the more general approach.

**Pull request closed without merging**
