### PR TITLE
ENH: passing colors (and other optional keyword arguments) to violinplot()

### PR DESCRIPTION
**Pull request by alimuldal**
I'm really glad that matplotlib now has a `violinplot()` function, but I find the current implementation a bit annoying to customize, since the only way to change the colors, alpha values etc. is to modify each artist after creating the plot. One would ideally want to be able to pass in any arbitrary keyword arguments for the `PolyCollection` and `LineCollection` artists in each individual 'violin', but there's a trade-off between flexibility and simplicity.

I think a reasonable compromise is to have the option to specify individual fill colors for each violin (like the `color` kwarg for `hist()`), but to have only a single dict for all the other optional kwargs for the fills and lines. For the time being I've stuck to the default colors/alpha values in the original implementation, but it might make more sense to leave these defaults unspecified so that they can be set according to `rcParams`.

### CODE REVIEW

**Comment by Stretch97** [comment]
Can I ask if these changes will allow me to set the alpha for the violin body fill color independently of the body edge color?  

In matplotlib v1.4.0, the violin body is a `PolyCollectionObject` which seems to have only one value for alpha.  (I can input a RGBA list for `facecolor` or `edgecolor`, but the A element gets ignored.)  In contrast, if I use `patch_artist = True` when I create a box plot, the box is a `PathPatch` object, which allows me to specify different alpha values for `facecolor` and `edge color`.

**Comment by jklymak** [comment]
It still seems violin plots don't allow diff colours?  Does anyone want to pick this one up and champion?

**Comment by jklymak** [comment]
Closing as abandoned, but does seem potentially useful, so hopefully someone takes it up.

**Comment by timhoffm** [comment]
@jklymak Just as a remark: Nobody will find "good first issue" in closed PR. The default search will only go for open issues. If we want to advertise this as a "good first issue", we need to make an open issue that references this PR.

**Pull request closed without merging**
