### PR TITLE
ci: Export sphinx-gallery run results to CircleCI.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This exports sphinx-gallery example run results to CircleCI, so we can get some idea of which examples fail often, etc., as in https://sphinx-gallery.github.io/stable/configuration.html#using-junit-xml-files

It _probably_ won't amount to much, but might as well try it out.

## PR Checklist

- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Where can we see the results of this change?

**Comment by tacaswell** [comment]
I suspect they will show up https://app.circleci.com/insights/github/matplotlib/matplotlib/workflows/build/tests?reporting-window=last-90-days&branch=b1d8acd4-8701-4c76-8a87-7ff2320aa95f once we merge this.

**Review by tacaswell — APPROVED** [review]
Can see the step in the logs, but not any of the results in the UI.

Not sure if this means we need this merged to the default branch to trigger things on the circle side or if it is configured wrong.

Given that this is only changes to CI config, I'm in favor of merging and finding out!

**Comment by QuLogic** [comment]
> Can see the step in the logs, but not any of the results in the UI.

Yes, it seems a bit in flux. On the build for _this_ PR, I can see a Tests tab with 553 'results'. This also has a link to Insights which _does_ work, though it only shows information for the one build. The information on pass/fail is probably irrelevant, but I think the stats on slowest tests might be useful. This may start working better for the main repo once it starts populating.

**Pull request merged**
