### PR TITLE
[MRG+1] Fix inverted expected/found FreeType version warning.

### PR DESCRIPTION
**Pull request by QuLogic**
I've always been confused by this message, and it turns out it's backwards.

### CODE REVIEW

**Comment by dopplershift** [comment]
On this particular one, it's targetted to the right branch, so no backport for the 2.0.1 release--just a merge to master at some point. It's also clearly a bug fix (not super critical, but almost zero risk). I'm not sure what's wrong with putting this in the next release.

**Comment by NelleV** [comment]
@dopplershift My concern with this state of mind is that we backport everything.

**Comment by dopplershift** [comment]
Ah. Might want to pick that battle on something that's more arguably out of bounds. 😁

**Comment by NelleV** [comment]
@dopplershift I think only major bugs should be backported: this isn't a major bug.

**Comment by dopplershift** [comment]
My take is if it's a bug, and the fix is ready, it goes in, with one proviso: The lines in question have to have tests to ensure that it didn't accidentally break something. It doesn't have to be a new test (a test for this specific change would just be silly), but the test suite should be executing any lines that changed.

I have no idea if this change was run by the tests or not.

**Comment by QuLogic** [comment]
> I have no idea if this change was run by the tests or not.

Unfortunately not; all tests are run with the builtin freetype version, so this warning will _never_ be triggered on CI. Locally, however, I never build with `local_freetype=True`, so I'm fairly certain that the warning gets the message backwards.

**Comment by dopplershift** [comment]
Less concerned about whether they're backwards (I trust you) and more about making sure there's a test somehow that makes sure there's not an unexpected error lurking in the change--if we're planning on putting this in 2.0.1.

**Comment by anntzer** [comment]
Merged, but I'm not entering the debate of whether to backport or not :)

**Comment by anntzer** [comment]
Apparently this went into 2.0.x, not master (I just clicked the green button).  Someone please check whether this was correct...

**Pull request merged**
