### PR TITLE
Doc: Don't use Sphinx 1.8

### PR DESCRIPTION
**Pull request by ImportanceOfBeingErnest**
## PR Summary

The use of sphinx 1.8 has two downsides

1. The search on the webpage is broken. See [this link](https://matplotlib.org/3.0.0/search.html?q=imshow&check_keywords=yes&area=default) or just go to the [matplotlib.org](https://matplotlib.org) and type somthing in the "Quicksearch". To see how it should be, see the [2.2.3 version](https://matplotlib.org/2.2.3/search.html?q=imshow&check_keywords=yes&area=default).

2. The [Writing mathematical expressions](https://matplotlib.org/tutorials/text/mathtext.html) tutorial aquires all kinds of red symbols which dont belong there.

 image  or   image

 While (2) can potentially be fixed from the matplotlib side, (1) cannot. I would hence propose to not use sphinx 1.8 until those are fixed.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I'm slowly working on (2), there's a few mathtext-related PRs.
(1) is known https://github.com/sphinx-doc/sphinx/issues/5460 and milestoned for sphinx 1.8.1, I agree with blacklisting 1.8.0.

**Comment by tacaswell** [comment]
This means I need to re-generate and re-publish the docs tonight?

**Comment by ImportanceOfBeingErnest** [comment]
@tacaswell No pressure. As soon as you have time. I think the search function proves useful especially when a new version is out, so waiting for 2 more weeks might be a bit too long.

In the long run, how realistic is it to generate the docs automiatically from the respective vx.y.z-doc branch every couple of days, similar to the devdocs?

**Comment by tacaswell** [comment]
Yes, we have google analytics on the site, looks like ~50k hits to search a month...

**Comment by tacaswell** [comment]
manually backported to v3.0.0-doc as ea132530f4dec06a7aab77ec00cac09816a2c5b3

**Comment by tacaswell** [comment]
I just pushed the updated docs, should be live in the next 10-15 minutes.

**Comment by ImportanceOfBeingErnest** [comment]
@tacaswell It doesn't look like search is working in the updated docs at matplotlib.org even though it says to have been built with sphinx 1.7.9. 

* [Search at matplotlib.org](https://matplotlib.org/search.html?q=imshow) (**not working**)
image

* [Search of this PR's circle-ci build](https://370-100939689-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/search.html?q=imshow&check_keywords=yes&area=default)  (**working**)
image

I noticed that there are also other differences between the docs on the website and the ones created via circle-ci, e.g. the version number seems to be different, but also the "note" box in the examples that was removed in https://github.com/matplotlib/matplotlib/pull/11428 is still there on matplotlib.org (cf. [ci-build](https://370-100939689-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/lines_bars_and_markers/arctest.html#sphx-glr-gallery-lines-bars-and-markers-arctest-py) vs. [web](https://matplotlib.org/gallery/lines_bars_and_markers/arctest.html#sphx-glr-gallery-lines-bars-and-markers-arctest-py)). When I build the docs locally they are in line with the ci-builds. Any idea on a possible difference?

<hr>

Now, sphinx released version 1.8.1 yesterday without fixing the search. So effectively the `sphinx!=1.8.0` introduced here is already useless. New ci-builds will use sphinx 1.8.1, again introducing the non-working search and red symbols for mathtext.

Concerning search, the fix is not done in sphinx itself as it stands, but one has to modify `layout.html` to include some additional javascript. I will try to make a PR with that shortly.

**Comment by timhoffm** [comment]
Have you tried refeshing your browser? I had the problem that even with 1.7.9 it used a cached erroneous javascript or something.

:disappointed: on sphinx 1.8.1. So we should `sphinx<1.8.0` for the time being.

**Comment by tacaswell** [comment]
@timhoffm Try now?  I just cleared the cloudflare cache as well.

**Comment by timhoffm** [comment]
@tacaswell Thanks. It works now, though I'm not sure if I had the problem on this machine.

**Comment by ImportanceOfBeingErnest** [comment]
Wow... so there are remains from the past in my browser, and they are hidden deep.
It's rather disturbing to find out that my browser executes some javascript from a site I visited yesterday...   
Completely clearing the browser cache did the trick though.

**Comment by ImportanceOfBeingErnest** [comment]
Here is the fix for the search: #12216
I don't know how far the activities on fixing the red mathtext symbols have moved and whether it would hence make sense to pin sphinx to <=1.7.9 or not.

**Comment by anntzer** [comment]
I think I know how to fix the red mathtext symbols (you "just" need to patch the suitable docutils dicts and/or send a patch to docutils) but it's not going to be a priority for me, pinning to 1.7.9 in the meantime is fine.

**Comment by timhoffm** [comment]
Math issue is now tracked in #12532.

**Pull request merged**
