### PR TITLE
Use correct pip/pytest on azure

### PR DESCRIPTION
**Pull request by dstansby**
This is the same as https://github.com/matplotlib/matplotlib/pull/15300, but the Azure build seems to have disappeared from that PR so this is just to see what the build error is (and maybe fix it).

### CODE REVIEW

**Comment by dstansby** [comment]
Progress: installing numpy first has moved the error to `pillow` needing to be compiled, but not finding the installed copy of `zlib`.

**Comment by tacaswell** [comment]
I think we tookout too much here: https://github.com/matplotlib/matplotlib/pull/15193/files#diff-a3fee1253ef9cd8f9d05eaa692bbe035L28-L29

**Comment by tacaswell** [comment]
Looking at pillow's CI, they use appveyor and have a somewhat complicated set of scripts to set up the build enviroment.

It looks like there are already py38 wheels available (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow) but I am not sure the best way to get that installed.

**Comment by dstansby** [comment]
The other option is if we don't need to save compressed PNGs we could in theory disable the need for zlib: https://pillow.readthedocs.io/en/latest/installation.html#external-libraries

**Comment by dstansby** [comment]
Perhaps another option is to do the python preview testing on Linux, where hopefully it will be easier to deal with the pillow compilation requirements?

**Comment by tacaswell** [comment]
We should run it on both ;)

Hopefully the patch release pre-releases will be easier to manage (as the wheels from the 3.8.0 should still work)

**Comment by anntzer** [comment]
@tacaswell re: chris gohlke's windows wheels: for mplcairo (where I need the cairocffi wheel for the windows build) I just downloaded manually chris' wheel and mirrored it myself https://github.com/anntzer/cairocffi-windows-wheels https://github.com/matplotlib/mplcairo/blob/144388bf94d4cfb8010e835ae5c3e13643533354/azure-pipelines.yml#L53

**Comment by tacaswell** [comment]
Can we not install zlib at all then?

**Comment by anntzer** [comment]
that's the intent of https://github.com/matplotlib/matplotlib/pull/15378.

**Comment by tacaswell** [comment]
The mac fix went in via #15429 and a hacky way of skipping 38 on azure came in via #15447 .

**Pull request merged**
