### PR TITLE
MNT: Mailmap fixes and simplification

### PR DESCRIPTION
**Pull request by jkseppan**
Remove some duplication from `git shortlog` by adding new mappings and altering some mappings (the first commit), and simplify the `.mailmap` file by matching on email address in most cases, which allows removing some redundant mappings (the second commit; this should have no effect on the shortlog output).

I have tried to guess the preferred spelling and email address for the contributors affected by the first commit, but could have gotten it wrong. Here is a list of those contributors:

- [x] @curiale
- [x] @caspervdw
- [x] @dkua 
- [x] @endolith 
- [x] @ericmjl 
- [x] @jaimefrio 
- [x] @jakevdp 
- [x] @jlutgen 
- [x] @jowr
- [x] @leeonadoh 
- [ ] @memmett
- [x] @mdehoon 
- [x] @minrk 
- [ ] @OceanWolf 
- [ ] @patchen 
- [x] @hodgestar
- [x] @stefanv 
- [ ] @wernerfb

### CODE REVIEW

**Comment by hodgestar** [comment]
Mine looks good to me.

**Comment by minrk** [comment]
:+1:

**Comment by ericmjl** [comment]
my emails look good to me as well!

**Comment by curiale** [comment]
👌

**Comment by jakevdp** [comment]
:+1:

**Comment by jlutgen** [comment]
My preferred address is jlutgen@gmail.com

Thanks.

**Comment by jaimefrio** [comment]
+1

**Comment by endolith** [comment]
yes that's my email address

**Comment by tacaswell** [comment]
Also see https://github.com/matplotlib/matplotlib/pull/4583 for preferences.  I think it is safe to assume that things are the same as in July for most people.

**Comment by jowr** [comment]
OK

**Comment by dkua** [comment]
👍

**Comment by caspervdw** [comment]
Ok for me too

**Comment by stefanv** [comment]
:+1:

**Comment by leeonadoh** [comment]
:+1:

**Comment by jenshnielsen** [comment]
Is this ready to go?

**Comment by mdehoon** [comment]
OK for me.

**Comment by tacaswell** [comment]
Merging as a majority of people have responded.

**Pull request merged**
