### PR TITLE
Add an arrow tutorial

### LINKED ISSUE #11219: Write an arrow tutorial
In order to work out which arrow methods to keep, and which to deprecate and then remove, it would be good to write a tutorial about how to plot arrows in Matplotlib. A basic structure could be:

1. Plotting arrows in data space
2. Plotting arrows with the head/tail patches fixed in display space, but the beginning/end fixed in data space
3. Plotting arrows with everything in display space

Now I understand the `transformation=...` keyword argument better than I did when I wrote MEP29, I think I could have a good go at this.

### PR DESCRIPTION
**Pull request by dstansby**
Fixes #11219 

This is quite short, but I think illustrates how to plot arrows with various display/data space options. All suggestions and comments welcome!

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
I think this rather qualifies as example than as tutorial? 

There is also already the [annotation_demo](https://matplotlib.org/gallery/text_labels_and_annotations/annotation_demo.html) example and the [annotations](https://matplotlib.org/users/annotations.html) tutorial. So I wonder in how far they are overlapping or not. Independent of that, there should be links in between them.

**Comment by dstansby** [comment]
Thanks for the feedback! I agree that as this stands it's more like an example, so I've put it in examples. I don't have time to expand this at the moment, but I think is an improvement as is that is worth going in.

All of your suggestions for expanding this are great @ImportanceOfBeingErnest ; maybe it would be best to put them in a new issue that someone could work on in the future?

**Comment by jklymak** [comment]
Pushed an underline change to your PR....  I'll merge this once it passes.  Indeed it doesn't cover everything, but is a good start/placeholder for further efforts.

**Comment by jklymak** [comment]
Thanks @dstansby 

Other folks - more than welcome to open new PRs with additional tutorial material!

**Pull request merged**
