### PR TITLE
"Switch to Adapter instead of Subclass of Axes"

### PR DESCRIPTION
**Pull request by weipeng1999**
## PR Summary
Use an Adapter named toolkits.axesgrid1.mpl_axes.AxesAdapter instead of old toolkits.axesgrid1.mpl_axes.Axes, because the Adapter can provide .axes dick-like property by simple wrapping matplotlib.axes.Axes object, so it can not only support Axes of matplotlib but also the subclass of Axes in other python package ( like GeoAxes in cartopy ).
## PR Checklist
 python -m pytest ./lib/mpl_toolkits/tests/test_axes_grid1.py

**Tests and Styling**
[-] Has pytest style unit tests (and `pytest` passes).
[-] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by weipeng1999** [comment]
Well, forgot this, it cannot work because the interaction of mpl_axes.Axes is more than i thought.

**Comment by jklymak** [comment]
Is there a feature from the toolkit you needed?  Maybe the base library has the same functionality?

**Comment by weipeng1999** [comment]
> Is there a feature from the toolkit you needed? Maybe the base library has the same functionality?

I want to use ImageGrid on GeoAxes. After check codes, i find the special class mpl_axes only provide .axis porperty. So i think that can use an adapter to wrap anytime if it need .axis. But unforturnetely, when i try to pass the test, I find that .axis porperty use as the Axes porperty in some Example of document! That means if do this change, the example will be broken! So...

**Comment by jklymak** [comment]
On the main branch you can try `plt.figure(layout='compressed')`

**Comment by weipeng1999** [comment]
> On the main branch you can try `plt.figure(layout='compressed')`

thank you👍

**Pull request closed without merging**
