### PR TITLE
Deprecate clear_temp param/attr of FileMovieWriter.

### PR DESCRIPTION
**Pull request by anntzer**
It overlaps in awkward ways with frame_prefix, which effectively
provides the same functionality.

followup to https://github.com/matplotlib/matplotlib/pull/16082.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dopplershift** [comment]
Failing CI for some reason.

**Comment by timhoffm** [comment]
Failing CI for this reason:
~~~
/home/circleci/project/doc/api/_as_gen/matplotlib.animation.AVConvFileWriter.rst:39:<autosummary>:1: WARNING: py:obj reference target not found: matplotlib.animation.AVConvFileWriter.clear_temp
/home/circleci/project/lib/matplotlib/animation.py:docstring of matplotlib.animation.FFMpegFileWriter.supported_formats:1:<autosummary>:1: WARNING: py:obj reference target not found: matplotlib.animation.FFMpegFileWriter.clear_temp
/home/circleci/project/lib/matplotlib/animation.py:docstring of matplotlib.animation.ImageMagickFileWriter.supported_formats:1:<autosummary>:1: WARNING: py:obj reference target not found: matplotlib.animation.ImageMagickFileWriter.clear_temp
~~~

**Comment by anntzer** [comment]
That's basically because the animation api docs autosummary is somehow configured to list all properties too (and clear_temp is now one of them, but has no docs).  Updated missing-references.json.

**Comment by anntzer** [comment]
@dopplershift @timhoffm both of you approved; this should be good to go?

**Pull request merged**
