### PR TITLE
ENH : Nbagg blit

### LINKED ISSUE #4288: nbagg blit support
Hi, on the nbagg backend, blit doesn't seem to update without re-drawing. Here's a simple example:

``` python
import matplotlib.pyplot as plt

prev_artist = None
cur_y = 0.1

def onclick_handle(event):
  """Should draw elevating green line on each mouse click"""
  global ax, bg, prev_artist, cur_y
  ax.figure.canvas.restore_region(bg)
  if prev_artist:
    prev_artist.remove()
  cur_y += 0.1
  prev_artist = ax.plot([0, 1], [cur_y, cur_y], 'g')[0]
  ax.draw_artist(prev_artist)
  ax.figure.canvas.blit(ax.bbox)
  print "Drew line"

ax = plt.gca()
ax.plot([0, 1], [0, 1], 'r')
# ax.figure.canvas.draw()
bg = ax.figure.canvas.copy_from_bbox(ax.bbox)
ax.figure.canvas.mpl_connect('button_press_event', onclick_handle)
```

With `%matplotlib nbagg`, clicking on the plot doesn't cause any updates until the plot is re-drawn. With other backends (say qt) the plot updates immediately on clicking.

An unrelated oddity, if I uncomment the draw command and try re-drawing the figure just disappears (edit - on 1.4.3; seems fixed on 1.5.1dev1).

If it helps, IPython version is 2.3.0 and matplotlib is 1.4.3/1.5.1dev1; occurs on both chrome and firefox. [UAT including animation example](http://nbviewer.ipython.org/github/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_uat.ipynb) more or less run fine.

(Coincidental to the other nbagg animation issue just posted. Google led to [this post also](http://matplotlib.1069221.n5.nabble.com/blit-support-in-webagg-nbagg-backends-td43879.html).)

### PR DESCRIPTION
**Pull request by tacaswell**
Closes #4288

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @pelson

**Comment by tacaswell** [comment]
Also closes #4287

**Comment by tacaswell** [comment]
attn @blink1073  This might be relevant for scikit-image's stuff.

**Comment by blink1073** [comment]
Ooh, shiny!  I'll check it out tonight.

**Comment by blink1073** [comment]
This appears to have broken UAT 13 - Animation.  If I run the all of the cells, it yields an empty figure.  If I try and run it again, I get a static line with an animated line running through it, and this error:

```python
ERROR:tornado.application:Exception in callback <bound method TimerTornado._on_timer of <matplotlib.backends.backend_nbagg.TimerTornado object at 0x109d78450>>
Traceback (most recent call last):
  File "/Users/stevensilvester/Library/Python/2.7/lib/python/site-packages/tornado/ioloop.py", line 989, in _run
    return self.callback()
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/backend_bases.py", line 1290, in _on_timer
    ret = func(*args, **kwargs)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/animation.py", line 925, in _step
    still_going = Animation._step(self, *args)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/animation.py", line 784, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/animation.py", line 804, in _draw_next_frame
    self._post_draw(framedata, blit)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/animation.py", line 827, in _post_draw
    self._blit_draw(self._drawn_artists, self._blit_cache)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/animation.py", line 841, in _blit_draw
    bg_cache[a.axes] = a.figure.canvas.copy_from_bbox(a.axes.bbox)
  File "/Users/stevensilvester/workspace/matplotlib/lib/matplotlib/backends/backend_webagg_core.py", line 196, in copy_from_bbox
    renderer = self._last_renderer
AttributeError: 'FigureCanvasNbAgg' object has no attribute '_last_renderer'
```

**Comment by blink1073** [comment]
If I run UAT 1 and then skip down to UAT 13, it runs but the spines and tick labels are flickering.

**Comment by tacaswell** [comment]
If you resize it a couple times it eventually sorts it's self out.

I think the underlying issue is related to it actually having _two_ renderers so half the time it ends up drawing the line on to a renderer that never had the rest of the artists drawn.  The re-sizing causes enough thrashing that eventually things work out.

Looking into this now.

**Comment by tacaswell** [comment]
There are other problems such as the animation object not stopping after the figure is closed which pins a CPU....

**Comment by WeatherGod** [comment]
I would bet that that problem is the same as the one recently reported for
starting animations from another cell. Both the start and the finishing of
an animation is triggered through events emitted from the figure. If those
events aren't making it back to the animation objects, then nothing changes.

**Comment by mdboom** [comment]
Apologies that this has become a bit stale.  Rebasing this on top of master, I get:

```
Traceback (most recent call last):
  File "/home/mdboom/.pyenv/versions/miniconda3-3.16.0/lib/python3.4/site-packages/tornado/ioloop.py", line 1020, in _run
    return self.callback()
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/backend_bases.py", line 1305, in _on_timer
    ret = func(*args, **kwargs)
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/animation.py", line 1021, in _step
    still_going = Animation._step(self, *args)
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/animation.py", line 827, in _step
    self._draw_next_frame(framedata, self._blit)
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/animation.py", line 845, in _draw_next_frame
    self._pre_draw(framedata, blit)
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/animation.py", line 858, in _pre_draw
    self._blit_clear(self._drawn_artists, self._blit_cache)
  File "/home/mdboom/Work/builds/matplotlib/lib/matplotlib/animation.py", line 898, in _blit_clear
    a.figure.canvas.restore_region(bg_cache[a])
KeyError: <matplotlib.axes._subplots.AxesSubplot object at 0x7f38d7acfb38>
```

It would be nice to see this revived...

**Comment by jklymak** [comment]
Closing in lieu of #9240

**Pull request closed without merging**
