### PR TITLE
changed default values of Axes.specgram()

### PR DESCRIPTION
**Pull request by andreh7**
as proposed in https://github.com/matplotlib/matplotlib/issues/9100#issuecomment-325207842

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I still think this is the wrong way to go, and that `axes.specgram` should pass `None` arguments through to `mlab.specgram` so the defaults in `mlab.specgram` are used.   Otherwise, the two are in danger of becoming inconsistent.   

To properly format the plot, the *output* from `mlab.specgram` should be used, not the input. Given that the plotting function only uses `Fs`, and `Fs` is easily retrievable from the output (`= 2 * freq[-1]`) this is easily done.

**Comment by dstansby** [comment]
(FWIW I think eventually `mlab.specgram` should disappear and be replaced by https://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.signal.spectrogram.html since `Matplotlib` is really a plotting library and not a spectral analysis library)

**Comment by anntzer** [comment]
pyplot would need to be regenerated too (or #9173 merged :-)).  And I agree that the whole thing should be deprecated anyways.

**Comment by jklymak** [comment]
I'm going to close this, because its sat for quite a while and I don't think the proposed behaviour is correct.  Feel free to re-open if I am mistaken.

**Pull request closed without merging**
