### PR TITLE
`image_comparison` decorator refactor

### PR DESCRIPTION
**Pull request by Kojoley**
It is now function based, what removes the need of pytest workaround. On pytest it uses `mark.parametrize` instead of a generator, what makes collection phase lightning fast and significantly reduces number of generators usages and corresponding deprecation warnings. (generators are deprecated since pytest 3.0 and will be removed in 4.0)

Note: There is a bug in Nose related to `GeneratorExit` exception handling in `setup` fixture of a function. It is workarounded in `image_comparison` decorator, but you will see this line in such case in the log: `RuntimeError: generator ignored GeneratorExit`

### CODE REVIEW

**Comment by tacaswell** [comment]
How does this relate to https://github.com/matplotlib/pytest-mpl ?

**Comment by Kojoley** [comment]
Currently pytest-mpl does not support multiple extensions and multiple figures/baselines. I have some thoughts about how it should be handled (for example one possibility is to use `yield fig` in image comparison tests), but it is not the main priority, while long collection phase is something that annoys me a lot and slowdowns development.

**Comment by tacaswell** [comment]
I opened a PR against your branch to fix the scatter issue in a different way.  That should have been creating two identical figures, instead it was over-plotting.

**Comment by Kojoley** [comment]
The discussion and diff image is here https://github.com/Kojoley/matplotlib/pull/1

**Comment by tacaswell** [comment]
I am going to merge this as-is because the failure on appveyor is pgf related and was not caused by this PR.

**Pull request merged**
