### PR TITLE
mep12 on geo_demo.py

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
Looks like that worked.

**Comment by WeatherGod** [comment]
Indeed!

**Comment by thisch** [comment]
How many pylab examples do you still need to convert? IMHO it would be faster (and also energy-saving as the # of travis CI runs gets reduced) if you grouped several examples into a single PR, but this has probably been discussed in one of our PRs.

**Comment by ericmjl** [comment]
Not many examples left before having to reclassify them. I estimate ~15-ish right now. I decided against multiple examples in a single PR earlier. Forgot the exact reason, but I think it had to do with simplifying each PR.

**Comment by WeatherGod** [comment]
I'd be happy with 3 examples per PR. Especially now that it seems like you
are getting the hang of git and such.

By the way, in case it hasn't been said, we are really grateful for this
work that you are doing. It goes a *long* way to improving our
documentation!

**Comment by ericmjl** [comment]
Thanks a lot guys! :smile: I'm happy to help as well! 

Btw, some nice things I've observed so far about this - The task's level was just right for my level, it gave me the extra knowledge to make my own repos continuously-integrated, and oh my, it was a great release/positive distraction to work on open source having had my paper rejected from a 3rd journal :laughing:

**Comment by tacaswell** [comment]
@ericmjl Seconding what Ben says, thank you so much for doing this!  Poor documentation and out of date examples are the soft dark underbelly of OSS.

Also glad to hear that this work has made you a better developer in your other work.  That has been my experience as well and is one of (in my view) the best things about our community.

**Pull request merged**
