### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by tacaswell**
replaces #5313

### CODE REVIEW

**Comment by tacaswell** [comment]
This will need to be back-ported

**Comment by mdboom** [comment]
:+1: to merge once Travis passes.

**Comment by mdboom** [comment]
Oh -- and let's just merge this so we can move forward with the release, but I'd still like to see a test updated for this code path as mentioned in #5313.

**Comment by tacaswell** [comment]
I concur re patching up the tests later.

**Comment by mdboom** [comment]
Backported to v1.5.x as 60ec100de7dd

**Pull request merged**
