### PR TITLE
Add tests for mpl_toolkit anchored artists

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Tests for previously untested anchored artists.

~Includes the fix in #23862 so if this is merged before that, no need for that. But since that should go in 3.6 and this doesn't have to...~

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
We should probably talk about where all these tests are going?  mpl_toolkits has, in the past, been discussed as under-tested and under-maintained.  If we want to maintain it, why not move into the main library?

**Comment by oscargus** [comment]
I have not really understood the role of mpl_toolkits. Is it correct that it is possible to "install" other packages under mpl_toolkits and that some do?`

Primarily just trying to increase coverage and learn a bit more of the code base... (And sometimes, untested code actually turns out to be incorrect, like in this case.)

But one could for sure, I guess, claim that for 4.0 one moves the useful parts of it to the main library?

**Comment by jklymak** [comment]
💯 your work here has been great and _if_ we plan to keep these routines around is well overdue. But if the plan is to obsolete a fair bit of this, then I didn't want you to feel you had wasted effort. 

It would be great to revisit this on a call soon.  I guess id recommend that if you find parts of the tool kit useful, consider if there are straightforward ways to bring into the main library.  For instance we did that with inset_axes a couple of years ago, and 3.6 will have layout="compressed" which is meant to do the same things as image_grid.

**Comment by oscargus** [comment]
I do not really have that much of a threshold for doing this. Something I play around with when I lack energy for proper things... It will probably take some time to deprecate etc anyway.

**Comment by jklymak** [comment]
Yes but if we codify the behaviour with tests, it becomes even harder to change and or deprecate.

**Comment by oscargus** [comment]
Another way to see it is that then we know that we change the behavior...

(All these exists in tutorials/examples. I have more or less copied them
from there and only changed a bit to trigger parts of the code.)

But let's talk about it on Thursday(?).

(There is code that has completely breaked in some examples as there's been
no tests for it.)

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
