### PR TITLE
Simplify animation writer fallback.

### PR DESCRIPTION
**Pull request by anntzer**
The fallback now always returns PillowWriter, which is the first
registered writer and is always available, so we may just as well be
more explicit.

(Not all writers support all output formats, but we don't have machinery
to select writers based on the output format right now anyways.)

Slightly more complex than https://github.com/matplotlib/matplotlib/pull/16966 so I'm milestoning this one to 3.3.0 instead, but we could also backport it to 3.2.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
#16966 should be merged first and backported and then this one.

**Comment by tacaswell** [comment]
We don't have a hard dependency on pillow with 3.2 so we should not backport this to 3.2.x

**Comment by anntzer** [comment]
Ah, lost track of when the dependency came in.

**Comment by timhoffm** [comment]
Flake8:


./lib/matplotlib/animation.py:1095:50: F821 undefined name 'alt_writer'

**Comment by anntzer** [comment]
oops

**Comment by anntzer** [comment]
rebased

**Pull request merged**
