### PR TITLE
Fixes #10501.  python3 support and pep8 in jpl_units

### LINKED ISSUE #10501: cmp() is an undefined name in Python 3
These three files each contain at least one call to the Python 2-only builtin function __cmp()__ that was removed in Python 3.  Without a change (removing the surrounding `__cmp__()` method altogether?), a NameError or TypeError: unorderable types could be raised at runtime.

* http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp
* http://python-future.org/compatible_idioms.html#cmp

flake8 testing of https://github.com/matplotlib/matplotlib on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/matplotlib/testing/jpl_units/Duration.py:95:14: F821 undefined name 'cmp'
      return cmp( self._seconds, rhs._seconds )
             ^
./lib/matplotlib/testing/jpl_units/Epoch.py:144:17: F821 undefined name 'cmp'
         return cmp( t._jd, rhs._jd )
                ^
./lib/matplotlib/testing/jpl_units/Epoch.py:146:14: F821 undefined name 'cmp'
      return cmp( t._seconds, rhs._seconds )
             ^
./lib/matplotlib/testing/jpl_units/UnitDbl.py:142:14: F821 undefined name 'cmp'
      return cmp( self._value, rhs._value )
             ^
```

### PR DESCRIPTION
**Pull request by TD22057**
Fix for #10501 - adds rich comparison methods to all classes for python3 support.  Also updated all the code to be pep8/flake8 compliant (so the diff looks enormous because of indentation updates on virtually every line).  

Tests cases that use jpl_units were run function normally.

### CODE REVIEW

**Comment by tacaswell** [comment]
@t20100 What would need to be done for these tests to be run by travis?

**Comment by TD22057** [comment]
Sorry - I don't understand.  These aren't test cases, they're utilities to allow tests w/ units to be written.

**Comment by timhoffm** [comment]
Just a short feedback: I wanted to review this PR, but turned away because it's too much effort.

It would be better for review to have the changes separated. There's a lot of whitespace change and hidden in between some functional and py3 changes. At least the github viewer does not really show the difference. Some larger whitespace changes are interpreted as completely new text, and I don't want to recheck everyone of them for a possible py3 or functional change.

**Comment by efiring** [comment]
This is a special case.  As soon as the merge conflict is resolved, I think we should go ahead and merge this.

**Comment by QuLogic** [comment]
@timhoffm Have a look at then [diff without (most) whitespace changes](https://github.com/matplotlib/matplotlib/pull/10618/files?w=1).

@jklymak yes the exceptions should be removed from `pytest.ini`.

**Comment by timhoffm** [comment]
@QuLogic Thanks, I've learned something new.

**Comment by TD22057** [comment]
Sorry about that.  I tried to update my local branch with a rebase and resolve the conflicts and somehow I ended up with a mess showing all the diffs from the original branch point.  Let me know what's the best way to resolve this (deleting it and starting over is the only way I know to easily fix this) - my git merge/update skills are clearly lacking...

**Comment by jklymak** [comment]
Hah, I just did that yesterday too:

1. copy the files you modified somewhere else (hopefully finite #) 
2. rename the branch you messed up (i.e. `git branch -m py3_jpl_units_broke`)
3. make a new branch from upstream/master with the same name as the old one (`py3_jpl_units`)
4. copy the modified files back onto the branch.

The trick to rebasing to master is to squash all your own commits *first* and then rebase onto master.  

Hope that helps - feel free to ask if any of the steps not clear...

**Comment by TD22057** [comment]
@jklymak Sorry - that didn't seem to work.  There were changes on the same files - that's why there were conflicts in the first place.  I tried what you suggested and it tells me the push was rejected it's behind the remote branch (I'm assuming this is because I pushed all those commits so they are already there).

So... perhaps I should just close this and submit two different pull requests, one for the original __cmp__ update and one to update the flake8 warnings.   Sound ok?

**Comment by jklymak** [comment]
Well, try a force push first!
```
git push origin  py3_jpl_units --force
```

**Comment by dstansby** [comment]
Does this still want to be backported to the `2.2.x` branch? My guess would be no since it doesn't look like it fixes a regression.

**Pull request merged**
