### PR TITLE
Allow tuples of 4 floats as color rcparams.

### PR DESCRIPTION
**Pull request by anntzer**
Fixes https://github.com/matplotlib/matplotlib/issues/9030#issuecomment-322412192.
(Although I *still* think (as argued in many other places) that the proper solution is to use Python files, or at least a full Python expression evaluator, as rcfile.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by afvincent** [comment]
Huh... `validate_color` is not tested in `test_rcparams.py`?

**Comment by afvincent** [comment]
@anntzer Would it be worth to add this kind of snippet
```python
# One would need to also import validate_color beforehand

        {'validator': validate_color,
         'success': (('None', 'none'),
                     ('none', 'none'),
                     ('AABBCC', '#AABBCC'),  # RGB hex code
                     ('AABBCC00', '#AABBCC00'),  # RGBA hex code
                     ('tab:blue', 'tab:blue'),  # named color
                     ('C0', 'C0'),  # color from cycle
                     ('(0, 1, 0)', [0.0, 1.0, 0.0]),  # RGB tuple
                     ((0, 1, 0), (0, 1, 0)),  # non-string version
                     ('(0, 1, 0, 1)', [0.0, 1.0, 0.0, 1.0]),  # RGBA tuple
                     ((0, 1, 0, 1), (0, 1, 0, 1)),  # non-string version
                     ('(0, 1, "0.5")', [0.0, 1.0, 0.5]),  # unusual but valid
                     
                    ),
         'fail': (('tab:veryblue', ValueError),  # invalid name
                  ('C123', ValueError),  # invalid RGB(A) code and cycle index
                  ('(0, 1)', ValueError),  # tuple with length < 3
                  ('(0, 1, 0, 1, 0)', ValueError),  # tuple with length > 4
                  ('(0, 1, none)', ValueError),  # cannot cast none to float
                 ),
```
to `generate_validator_testcases` in `test_rcparams.py`?

FWIW, currently (on Matplotlib 2.0.2) `validate_color((0, 1))` or `validate_color((0, 1, 0, 1, 0))` (NB: the argument is *not* a string here) raises an `AttributeError` exception because in this case (i.e. a tuple of invalid length) the validator tries to call the `.find` method of the argument (which does not exist for tuples). Seems like an issue to me, but I may be wrong.

**Comment by anntzer** [comment]
I honestly care very little about the rcparam validator because, as I have already argued in many places, I think its entire design should be redone from scratch (to just use python expressions as syntax, either through eval or through a hand-written safe AST evaluator if we consider it worth it).
But you should feel free to push additional commits to this PR to enhance the tests, I won't complain either.

**Comment by afvincent** [comment]
@anntzer I created a [branch](https://github.com/afvincent/matplotlib/tree/len-4-color-rcparams) on my own fork, which first replicates your commit and second add a proper test for the validator. Unfortunately, I did not manage to understand how to push it to your branch or open a PR against it :/.

**Comment by anntzer** [comment]
Something like
```
git fetch upstream pull/9038/head:pull/9038
git checkout pull/9038
# hack hack
git commit
git push
```
should work.  Perhaps this should go to the devdocs, btw.

**Comment by afvincent** [comment]
Thank you @anntzer, I was severely missing the first line ^^. Almost there now but it looks like I am still missing something for pushing... A simple `git push` yield
```
fatal: the current branch  pull/9038 does not have an upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin pull/9038
```
Of course the suggested solution just made a branch on my own fork, while replacing `origin` by `upstream` led to consequences I do not want to think about again 🐑 ...

**Comment by anntzer** [comment]
What are these consequences?  (dunno)
We may as well get how to do this clearly written in the devdocs.

**Comment by tacaswell** [comment]
I cherry-picked @afvincent 's second commit and pushed it to this branch.

**Comment by afvincent** [comment]
BTW @anntzer, the "consequences" were that I created a new branch on the upstream Matplotlib repository :/.

Huh, seems like I let a white blank line on my initial branch on my own fork, which causes PEP8 failures. Too bad, I had it remove on the branch I created on the upstream repository ^^.

**Comment by anntzer** [comment]
Sorry about the wrong instructions then :/

**Comment by afvincent** [comment]
Don't be: thanks to them I already went further than I had before ;).

**Pull request merged**
