### PR TITLE
Moving from make.py to Makefile for sphinx-build

### LINKED ISSUE #5798: Use Makefile for sphinx build
#5743 reminded me:

We still use an ancient `make.py` that is based on what early versions of `sphinx-quickstart` used to generate.  We should probably modernize this to use a Makefile like current versions of sphinx create.

This is sort of low-priority, because the only _real_ advantage would be consistency with other Python projects.  The Makefile won't magically make things faster or anything.  Also, the work is non-trivial since our `make.py` includes customizations and other things that get run that will need to be ported to the "current way to do things" (probably Sphinx extensions).

### PR DESCRIPTION
**Pull request by NelleV**
"We still use an ancient make.py that is based on what early versions of sphinx-quickstart used to generate. We should probably modernize this to use a Makefile like current versions of sphinx create."

closes #5798

### CODE REVIEW

**Comment by anntzer** [comment]
I still think that #9513 is a better fix...
- there's no need to install conda on circleci.
- there's no need to introduce custom targets in the makefile, we can directly use the one provided by sphinx (which is also much shorter now).
- there's no need to modify the units examples.

**Comment by dopplershift** [comment]
Why *does* this PR change to use conda on circleci?

Also, I'm completely confused as to why this PR needs to change the examples while #9513 doesn't.

**Comment by efiring** [comment]
@NelleV, what do you see as the advantages of this over #9513?  The latter has the a priori advantage of brevity.

**Comment by NelleV** [comment]
I've closed my PR. Both solution work, and I really don't care which one gets in.

**Comment by efiring** [comment]
@NelleV, thank you for getting this topic rolling.

**Pull request closed without merging**
