### PR TITLE
Fixed GraphicsContextBase linestyle getter

### LINKED ISSUE #3354: Unecessary arguement in GraphicsContextBase get_linestyle
There is an unnecessary arguement in `get_linestyle` of `GraphicsContextBase`. An unused arguement is required, which shouldn't be there.
It blocks any future 'propertification'...

I made the changes, but when trying to make a pull request against that commit, GitHub says there is nothing to compare?

Here is the commit:
https://github.com/JamesRamm/jplotlib/commit/0bab98249ee1b966eac96ac295e0e613a279b1cd

### PR DESCRIPTION
**Pull request by Kojoley**
Closes #3354

### CODE REVIEW

**Comment by tacaswell** [comment]
For reference, this has been like this since e34a333d00814124d3e19d462b9d78ac35e7a49a and has no previous history.

We also do not appear to ever use it internally.  All of our backends use `get_dashes` instead which (mostly) ensures that the dash pattern is the same across all backends (and enables us to scale the pattern with line width).

This needs an API changes note (there may be third-party backends working around this), but given that the current API is obviously problematic (and no one has complained) I do not think it needs a deprecation cycle.

**Comment by Kojoley** [comment]
`GraphicsContextBase.get_linestyle` is not used anywhere in mpl code.
`GraphicsContextBase._linestyle` is used only in `GraphicsContextBase.copy_properties` and it sets the variable DIRECTLY.
`GraphicsContextBase.set_linestyle` is used only in [one place](https://github.com/matplotlib/matplotlib/blob/5b1d671722d5b4723566273b6d3c6272de335c16/lib/matplotlib/patheffects.py#L357) and [overridden only in wx backend](https://github.com/matplotlib/matplotlib/blob/6a56f696874c9f62b01cd123872c1a985ce3cb59/lib/matplotlib/backends/backend_wx.py#L513).
There is [a TODO entry in pdf backend](https://github.com/matplotlib/matplotlib/blob/ab98852fa3b760e87208de53d058f82c3bf934bc/lib/matplotlib/backends/backend_pdf.py#L2328) about `_linestyle`  from 2006 year and I am not sure it makes any sense now.

So I assume it is safe to fix this without deprecation (or even to remove the property).

**Comment by anntzer** [comment]
If we're going to break backcompat, let's just remove the property?

**Comment by tacaswell** [comment]
power cycled to run CI with fixes from master branch to other tests.

**Comment by NelleV** [comment]
LGTM :+1: 
Thanks @Kojoley

**Pull request merged**
