### PR TITLE
Don't draw axis (spines, ticks, labels) twice when using parasite axes.

### PR DESCRIPTION
**Pull request by anntzer**
We can just defer to the superclass' draw (axes._base.Axes.draw)
which will correctly draw everything in get_children();
axislines.Axes.get_children already adds the axislines and gridlines to
the superclass' get_children().

Likewise, get_tightbbox() doesn't need to be overridden because the
superclass' get_tightbbox by default uses
get_default_bbox_extra_artists, which fetches all visible children.
(This point is not needed for the bugfix, but we may as well...)

Don't bother using remove_text in the new figures, because that doesn't
remove the labels anyways (and the tests are also about label placement).

Issue pointed out by @tacaswell in https://github.com/matplotlib/matplotlib/issues/11602#issuecomment-403682538 and @ImportanceOfBeingErnest in https://github.com/matplotlib/matplotlib/issues/11602#issuecomment-403786587.

I feel like I should charge a quarter for every bugfix that *only* involves deleting code :)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
:+1: :tada: 

Before:

image

After:

image

**Comment by ImportanceOfBeingErnest** [comment]
As this affects *every* axes drawn with the toolkits, I would think this is significant enough to get a what's new entry (there are no bug-fixed entries, right?) to tell people that those axes now look as great as the usual matplotlib axes and are hence even usable for publication quality figures. 

Is it too late to get this into 3.0?

**Comment by anntzer** [comment]
Added a whatsnew.  I don't particularly care re: 3.0 or not.

**Comment by anntzer** [comment]
The docs build is failing because of the whatsnew manipulation in #11603, we just need to decide whether the item is going into the main file or whether we're starting with the whatsnew directory again.

**Pull request merged**
