### PR TITLE
[Doc] add pcolor and contour to tutorials/introductory/sample_plots.py

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

`tutorials/introductory/sample_plots.py` didn't have a `pcolor` plot or an example of `contour`!

## PR Checklist

- [x] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by anntzer** [comment]
fwiw (not directly related but perhaps you can also remove it here) there seems to be an extraneous plot at the bottom of the page, see below http://matplotlib.org/devdocs/tutorials/introductory/sample_plots.html#xkcd-style-sketch-plots

**Comment by jklymak** [comment]
Well, it does get used for the thumbnail.  But can I choose one of the other plots for the thumbnail?

**Comment by anntzer** [comment]
Ah... looks like a feature (pick a thumbnail not in the notebook) we should ask the s-g gallery folks about (I think it's a nice thumbnail).  @choldgraf ? :-)

Also, there's no imshow example, which seems waaay more fundamental.  Perhaps something like:
> The imshow() function (I'd replace "command" by "function" throughout, we're not MATLAB...) can be used to make a colored representation of a 2D array.
(example)
If the underlying array uses irregular sampling, consider using pcolormesh()
(example)
Contour plots, created by contour() and contourf(), are yet another way to represent 2D data.
(example)

**Comment by jklymak** [comment]
OK, I can do that.  I thought I was being good and economical by choosing an example that had `pcolor` and `contour` in one figure, but I'm happy to add a few more examples.  

(I was pretty surprised that none of these functions made it onto the "sample plots" page, since they are the main type of visualization I do - even more fundamental than line plots)

**Comment by anntzer** [comment]
It's all a matter of field of application I guess... (typically imshow is enough for me :-))

**Comment by jklymak** [comment]
Ooops, made git mistake.  Closing and re-opening.

**Comment by anntzer** [comment]
@jklymak git push --force / git push --force-with-lease should let you reuse the same PR.  At least I tend to use it quite liberally (on PRs only of course).

**Comment by jklymak** [comment]
Ahhh.  I should have done that!  Thanks.

**Pull request closed without merging**
