### PR TITLE
Bug Fix - Polar plot rectangle patch not transformed correctly (#8521)

### PR DESCRIPTION
**Pull request by MeowsterEric**
## PR Summary

Fixed rectangle patch not transformed correctly in polar plot #8521.
_interpolation_steps field should be revised to new value in PolarAxes instead of using default value (1).

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Does this address https://github.com/matplotlib/matplotlib/pull/9265 and the reasons we reverted the original fix?

**Comment by QuLogic** [comment]
This is effectively the same as #8539 (which was reverted), though perhaps a bit better, but it still breaks [the radar axes example](https://6477-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/api/radar_chart.html?highlight=radar).

**Comment by MeowsterEric** [comment]
May I know what's the expected output for radar chart?

**Comment by afvincent** [comment]
@MeowsterEric See the expected outcome in #9261 :)

**Comment by MeowsterEric** [comment]
Thanks. I will take a look.
Btw, how do I properly set up the image comparison test?
Seems like the expected and actual image has RMS diff of 35.0

**Comment by MeowsterEric** [comment]
What's the preferred image comparison tolerance value?

**Comment by QuLogic** [comment]
The preferred image tolerance is 0. Make sure you have [build Matplotlib correctly for image comparison tests](https://matplotlib.org/devdocs/devel/contributing.html#building-matplotlib-for-image-comparison-tests) and then you can copy the result of the test as the expected image.

Please also add `style='mpl20'` to the `image_comparison` decorator so you get a new-style image.

**Comment by efiring** [comment]
Given that this breaks an example, and that this plus a proposed fix are in #10561, I am closing this as redundant.  It is still available and linked, so the comments can be reviewed as part of the history when considering #10561.

**Pull request closed without merging**
