### PR TITLE
DOC: link brokenaxes package in third part

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

As pointed out in #11682, there is a package `brokenaxes` that could be linked in our thrid-party tools.  @bendichter is it OK to link your package?  Is it in a stable enough state to advertise?  

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
https://11773-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/thirdpartypackages/index.html#broken-axes

I don’t think ci failure is related

**Comment by jklymak** [comment]
Doc changes are one approval unless controversial for some reason.

**Comment by jklymak** [comment]
Don’t see why not.  The milestone will backport it.

**Comment by tacaswell** [comment]
:+1: nifty package.

**Comment by jklymak** [comment]
Yes, I do wonder if it could fit into the core API....

**Pull request merged**
