### PR TITLE
Update pyplot.py

### PR DESCRIPTION
**Pull request by aflahkhan**
Fixed Grammar Error 
Earlier with had been typed in twice while only one was needed.
Fixed this by removing one occurence of with to make documentation more readable in the future

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by aflahkhan** [comment]
Can Some Developers tell me what went wrong?
I just changed the documentation a bit and didn't change anything else

**Comment by aflahkhan** [comment]
@timhoffm I saw that you were monitoring a lot of issues.
Can you check out my pull request.
I only made a small change and all these builds failed?
I'd be helpful if you could tell what's going wrong or refer to some forum or person whom I can ask
Thanks :)

**Comment by jklymak** [comment]
test_animation seems to be failing.  Its not this PR.

**Review by jklymak — APPROVED** [review]

**Comment by aflahkhan** [comment]
okk thank you for the clarifications @jklymak

**Pull request merged**
