### PR TITLE
TST: Use importlib for importing in pytest

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

This fixes the rewriting so that we get detailed variable information again, which was broken with the move to Meson (which does weird import hacking for editable installs.)

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
Interestingly, this seems to be fine on the Minimum Versions CI, but everywhere else doesn't like it. That build uses pytest 7.0.0, and locally I have 7.2.1. The other jobs appear to be 7.4.3. I will have to investigate whether that might be the cause of the problem.

**Comment by QuLogic** [comment]
And on Windows, I have pytest 7.4.0 which works.

**Comment by QuLogic** [comment]
And updating my Windows machine to 7.4.3 also works, so it seems to be something else.

**Comment by tacaswell** [comment]
If I launch the tests as 

```
pytest -n 20
```

it works

If I launch the tests as 

```
python -mpytest -n 20
```

it fails locally

```
python -I -mpytest -n 20
```

works.

**Comment by QuLogic** [comment]
Ah right; I think what we'd want is `python -P`? But it wasn't available in all Python versions we support. I'm also confused why the Minimum Versions was okay with that since it doesn't run things any differently.

But to continue, do we want to:
1. Change _only_ CI to use `importlib` and direct `pytest`?
2. Stop recommending `python -m pytest` over `pytest` (note their default documented invocation is with `pytest`, not `python -m pytest`)?
3. Change the `pytest` options for everyone?

**Comment by tacaswell** [comment]
I think we want to:

 - change the options for everyone (not getting the diffs is annoying)
 - change how we invoke the tests on CI and in our docs to just `pytest`
 - add a note about `python -P` / `python -I` for running with `python -m`

There was a big push to move everything to `python -m ...` but that seems to have fizzled out.  The main argument for it was to avoid the risk of picking up cli tools from the underlying shell when in a conda/virtual environment.  However, this seems to have been instead handled by a combination of "don't mess up", aggressively always installing pip (which had the highest risk of causing chaos!), and better tooling around managing environments.

**Comment by QuLogic** [comment]
OK, now we can see that that leak test if failing as:
```
>       assert growth <= acceptable_memory_leakage
E       assert 3014656 <= 2000000
```

It appears that Cygwin broke a while ago, and I've opened https://github.com/pybind/pybind11/issues/4999 for that.

**Review by tacaswell — APPROVED** [review]

**Review by ksunden — APPROVED** [review]

**Pull request merged**
