### PR TITLE
FIX: remove recursive call to str in transform repr

### LINKED ISSUE #11163: RecursionError when calling get_yaxis_transform() on a Symlog-scaled axis.
### Bug report

**Bug summary**

Calling `get_xaxis_transform()` after `set_yscale('symlog')` results in a `RecursionError`. I found this bug when investigating why there's no yticks (except 0) shown when using a symlog scale.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np

f, ax = plt.subplots()
ax.plot(np.arange(100))
ax.set_yscale('symlog')
print(ax.get_yaxis_transform())
```

**Actual outcome**
```
RecursionError: Maximum recursion depth exceeded
```

**Expected outcome**
An object of type `matplotlib.scale.SymmetricLogScaleTransform` or something like that.

**Matplotlib version**

  * Operating system: Ubuntu 16.04.1
  * Matplotlib version:  2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5

Installation was done via conda default channel.

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This makes `__repr__` for transform objects just a one-line object repr.  

It retains the pretty-print for `print`.

It fixes the recursion in #11163

Supercedes #11173, if we think that `__repr__` should return something short....  If we think `__repr__` should be more verbose, this is the wrong solution, and #11173 is correct.

Closes #11163.

```
In [1]: from matplotlib import pyplot as plt
   ...: import numpy as np
   ...:
   ...: f, ax = plt.subplots()
   ...: ax.plot(np.arange(100))
   ...: ax.set_yscale('symlog')
   ...: ax.get_yaxis_transform()
   ...:
Out[1]: <matplotlib.transforms.BlendedGenericTransform at 0x10fcff908>

In [2]: print(ax.get_yaxis_transform())
BlendedGenericTransform(
    BboxTransformTo(
        TransformedBbox(
            Bbox(x0=0.125, y0=0.10999999999999999, x1=0.9, y1=0.88),
            BboxTransformTo(
                TransformedBbox(
                    Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                    Affine2D(
                        [[ 200.    0.    0.]
                         [   0.  200.    0.]
                         [   0.    0.    1.]]))))),
    CompositeGenericTransform(
        TransformWrapper(
            BlendedGenericTransform(
                IdentityTransform(),
                <matplotlib.scale.SymmetricalLogTransform object at 0x1179b4f28>)),
        CompositeGenericTransform(
            BboxTransformFrom(
                TransformedBbox(
                    Bbox(x0=-4.95, y0=-0.2525144679040212, x1=103.95, y1=136.74800843761523),
                    TransformWrapper(
                        BlendedGenericTransform(
                            IdentityTransform(),
                            <matplotlib.scale.SymmetricalLogTransform object at 0x1179b4f28>)))),
            BboxTransformTo(
                TransformedBbox(
                    Bbox(x0=0.125, y0=0.10999999999999999, x1=0.9, y1=0.88),
                    BboxTransformTo(
                        TransformedBbox(
                            Bbox(x0=0.0, y0=0.0, x1=6.4, y1=4.8),
                            Affine2D(
                                [[ 200.    0.    0.]
                                 [   0.  200.    0.]
                                 [   0.    0.    1.]]))))))))
```

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
OK, the other time we didn't fix the root cause of this (#10242) had a comparison of the repr.  I've removed that because it obviously fails now.

**Comment by efiring** [comment]
Does this need to be backported?

**Comment by anntzer** [comment]
Would probably be a good idea.

**Comment by jklymak** [comment]
@meeseeksdev backport to v2.2.x

**Pull request merged**
