### PR TITLE
DOC: update doc requirement

### PR DESCRIPTION
**Pull request by ImportanceOfBeingErnest**
## PR Summary

For some reason the documentation now requires numpydoc 0.8 and sphinx-gallery 0.2. (See https://github.com/matplotlib/matplotlib/pull/11585#discussion_r202523818 for what happens otherwise)

Also changing pillow minuimum version to 3.4. I'm not sure if pillow is really a requirement (it isn't for matplotlib itself, but maybe for the docs), but if it is, it [needs to be >=3.4](https://github.com/matplotlib/matplotlib/pull/11132).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by NelleV** [comment]
Thanks for the patch!
Can you also update the circe-ci doc builds, so that we use the minimal requirement version? This should allow us to identify when we need to bump those packages' versions in our requirements.

**Comment by ImportanceOfBeingErnest** [comment]
The problem is that the requirements always say a minimal version. So if we put something like `package>0.5`, the build will still use `package 0.6` as soon as that is available. 

Anyways, isn't `doc-requirements.txt` the file that is used for circle/ci builds? If not, I wouldn't know which file to update in addition.

**Comment by NelleV** [comment]
We can set the packages to a specific version in the build. This is what I am suggesting to do. We should already be doing something identical on travis to test for "old" versions of numpy.

**Comment by ImportanceOfBeingErnest** [comment]
Isn't it better to run the doc builds against the newest available version, instead of some fixed one? The amout of work is roughly identical I'd say. As it stands you need to update the minimum version from time to time. With the suggestion of fixing the version, you would need to update the fixed version from time to time.

Maybe this can be decided among core devs. I personally don't care, but with this PR I simply wanted to work within the system, not change it. If someone wants to change the system they would need to find out which packages to fix for which versions.  
Of course if someone wants to provide a table for which packages to fix to which versions, I'm happy to include that in this PR.

**Comment by jklymak** [comment]
You can exclude a version with !=

**Comment by NelleV** [comment]
We run the documentation build twice. What is typically done is one of the build runs on all the most recent version of all the packages, and the other one on the minimal version of all packages. I am suggesting moving the requirements of the circle-ci build on python 3.5 to use all the minimal requirement version, and leave the python 3.6 as it is right now, using the most recent ones.

**Comment by ImportanceOfBeingErnest** [comment]
Sorry, I'm really no expert with yml/requirements. Does this line
https://github.com/matplotlib/matplotlib/blob/edd053d16fce81dc604e4e2b9828e04a71155b3f/.circleci/config.yml#L135

say that the minimum version should be used? Or is it that this line should be changed to actually use the minimal version?

**Comment by timhoffm** [comment]
Milestoning as 3.0. While it's not release critical, it would be good to get this straight for 3.0.

**Comment by ImportanceOfBeingErnest** [comment]
I'd say this is pretty straight already :-) It just documents the de facto minimal requirements for building the docs.

**Comment by tacaswell** [comment]
moving this to 3.1 (for now) to make book keeping easier for me as I try to get 3.0 tagged today.

**Comment by jklymak** [comment]
@meeseeksmachine backport to v3.0.0-doc

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.0.0-doc

@jklymak ^

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.0.x

**Pull request merged**
