### PR TITLE
Missing `f` prefix on f-strings fix

### PR DESCRIPTION
**Pull request by code-review-doctor**
Fixes #22882

### CODE REVIEW

**Comment by tacaswell** [comment]
I have mixed feelings about PRs from bots (?) but this fix is correct and I see no reason not to take it.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
May be better to merge #22883 though.

**Review by oscargus — APPROVED** [review]
Should we merge this for 3.5.2 and #22883 for 3.6.0?

(Feel free to merge once decided.)

**Comment by oscargus** [comment]
The problem is not in 3.5.2 so I changed to 3.6 for this, which leads to closing this and merging #22883 instead.

**Comment by code-review-doctor** [comment]
@tacaswell I'm really a person that found a bug via a static analysis bot I wrote and then (I checked 666 of the most popular python repos on GitHub and found 73 repos that had this issue). I then ran my script that auto-creates the issues in GitHub then auto-creates the PR to fix the issues. Half bot half human I guess :)

**Comment by tacaswell** [comment]
@code-review-doctor Sorry, when I clicked through the profile I jumped to conclusions 🐑 

This found a real bug and even though we fixed it differently, we appreciate the PR and hope to hear from you again!

**Pull request closed without merging**
