### PR TITLE
FIX: use str (not unicode) to ensure comparison works on python2

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
It seems that the wheels do not work for 2.7 so we missed this issue.

**Comment by anntzer** [comment]
We missed the issue because we're not testing the GUI toolkits at all (except that TkAgg can be imported) on Py2.

**Comment by tacaswell** [comment]
We are installing wx on the 2.7 build, how hard would it be to run the tests?

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/8660#discussion_r118447627.  subprocess32 has timeout but right now it's only installed on {posix and py2} (where it is an actual dependency).  I dropped the test on Py2 because subprocess32 appears unsupported on windows but we can probably change it to drop the test only on Py2+windows...

**Pull request merged**
