### PR TITLE
Fix #5302: Proper alpha-blending for jpeg

### LINKED ISSUE #5302: Pixelated fonts when plot saved as jpeg
I have noticed that when you save figures as jpeg using the nbagg backend you will get pixelated fonts for labels and tickmarks.  It appears this has to do with giving PIL raw data with transparent regions when trying to save jpeg images.  This can be avoided with setting: rcParams['nbagg.transparent'] = False.

Is this behavior desired?  Perhaps there is a way we can assign default values that will be called for when you have a transparency in a figure and you are trying to save it to a file format that doesn't support transparency?

Please see http://stackoverflow.com/questions/33283274/pixelated-fonts-when-plot-is-saved-as-jpeg for more information.

### PR DESCRIPTION
**Pull request by mdboom**
Saving a JPEG with an alpha channel doesn't look right -- I think pillow just removes the alpha channel altogether and uses the rest of the RGB values as-is.

This blends RGBA images onto a white background before saving.

This is JPEG-specific since it's our only raster output file format that doesn't support alpha blending.  If we ever grow another (unlikely) this will need to be duplicated there.

### CODE REVIEW

**Comment by QuLogic** [comment]
Strangely, the image from #5302 is white in the transparent parts, so I'm not sure what Pillow is doing.

Anyway, :+1: from me, but I'm not sure where 2.0.1 fixes are going.

**Comment by mdboom** [comment]
This is passing and ready to merge.

**Comment by WeatherGod** [comment]
Just curious. Do we want to hardcode a white background, or should we be getting the color from an rcParam?

**Comment by mdboom** [comment]
I think adding an rcParam would just add complication to this.  We already have an rcParam for the figure background (`savefig.facecolor`).  If the user really wants a different background color, they can just set that.  This *only* deals with the case where the background was accidentally set to transparent (through `savefig.transparent` or the `transparent` kwarg) without realising that JPEG can't handle that.

**Comment by mdboom** [comment]
That said, I suppose it could go to `savefig.facecolor`, which by default is white.

**Comment by WeatherGod** [comment]
Right... that was the param I was thinking of.

**Comment by mdboom** [comment]
This now gets the background color from `savefig.facecolor` as suggested by @WeatherGod.

**Comment by mdboom** [comment]
The test failures are puzzling, and I can't reproduce locally.  :cry:

**Comment by WeatherGod** [comment]
Perhaps add a useful message for the assert so that we can see what the value is?

**Comment by WeatherGod** [comment]
prints aren't getting caught by nosetests (I think it is some sort of option set by us). Add that stuff to the assert message so that the exception will print out the relevant message.

**Comment by cbreeden** [comment]
When I first tried coming up with a patch, I tried using `tostring_rgb` from the renderer  but that doesn't seem to be good enough.  My guess is that RGB doesn't really 'flatten' the transparency regions when converting from RGBA, which I thought would've been the ideal solution, which I think would allow for figures to be given figure.facecolor and axes to be given axes.facecolor.  But honestly I don't think anyone really uses transparency; except for `nbagg` that insists on having transparency in the figure.

I opened up a new issue related to this #5335.

**Comment by QuLogic** [comment]
Printing does work; it's just muddled between the dots: "num colors:  181".

**Comment by mdboom** [comment]
@QuLogic: Thanks for catching that.  My hunch is there is some variability because it's lossy JPEG.  I'll just increase the range somewhat.

**Comment by mdboom** [comment]
@cbreeden: I suppose we could try to fix `tostring_rgb` as well, but it would need to have a background color as an argument added.  I've created #5336 for that.

**Comment by tacaswell** [comment]
Do we want to backport this to 2.x?

**Comment by efiring** [comment]
Sounds reasonable to me; it can be viewed as a bugfix.  But it also makes me wonder whether saving a jpg with `transparent=True`, which this handles, should raise a warning.

**Comment by QuLogic** [comment]
I guess this was not backported, then?

**Comment by QuLogic** [comment]
Backported to v2.x via 1e437d347fbe16264834f0a7a283389d2d4be9a3.

**Pull request merged**
