### PR TITLE
Avoid unnecessary QApplication instance reference counting increase

### PR DESCRIPTION
**Pull request by vasole**
It may lead to python crashes when closing PyQt5 applications.

Addresses issue #14178

### CODE REVIEW

**Comment by tacaswell** [comment]
I'm a bit concerned about this as the type of `qApp` will depend on if we create the application or it was pre-created.

Is there any theory as to what causes the underlying bug?  I assume this has something to do with tear-down order?

**Comment by vasole** [comment]
Yes, it has to do with the clean up when the application is closed.

Your concern about using a weakref proxy should not be such. In principle a module should never keep a handle to a QApplication unless it has been created by that module. One should always use QApplication.instance() instead of a reference. I tried to made the minimum change.

The other alternative is that I can modify the pull request as follows

- The call to  _create_qApp only happens if QApplication.instance() is None
- Replace any reference to qApp inside the module by QApplication.instance() as it should 

That way your handle would be either None or an actual QApplication but there would be no unnecessary reference count increase.

Please let me know if that is acceptable so that I modify the PR.

**Comment by vasole** [comment]
Alternative solution without changing the type of qApp sent. The problem with this later case is that if somebody was directly accessing qApp expecting something behaving as a QApplication the situation is worse than with my original solution.

**Comment by tacaswell** [comment]
I think this is worse as now sometimes it will be `None`, despite there being an active QApplication around.

It seems that there needs to be at least one hard-ref around (or the QApplication get gc'd on the python side) so if we create it we definitely have to hold on to it.  

In the case where someone else creates the QApplication, I think we should still hold onto a hard-reference to it in case who ever is holding the hard reference drops it.


Can you get the crash on windows if you do

```
from PyQt5.QtWidgets import QApplication, QPushButton
app = QApplication([])
app2 = app
w = QPushButton('hi there!')
w.show()
app.exec_()
app = None
```

This really seems like an upstream bug that should be fixed rather than worked around...

Maybe make `qApp` always a proxy and stash a private hard reference in the case where we create it?

**Comment by tacaswell** [comment]
@vasole could you revert this to the initial proposal?

Does adding an `at_exit` that sets the global back to None help?

> One should always use QApplication.instance() instead of a reference.

Do you have a reference on this? 

The other thing I find confusing is that in the original report, when the program exits the user-space reference has already been dropped.

Do you see this problem when you use Matplotlib from inside of IPython?  Depending on the order of making the first canvas and ipython installing the Qt inputhook we may end up in the same situation (see https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/qt.py).

**Comment by vasole** [comment]
I will try from within IPython and the at_exit stuff, but I will not be able to do it until Monday.

**Comment by vasole** [comment]
- Unfortunately the atexit solution did not work.
- I also encounter the problem from within IPython.

When using IPython, the problem is still there even with the patch. Probably due to using the same approach being used within IPython as you pointed out.

In my applications I avoid the crashes at exist overwriting matplotlib.backends.backend_qt5._create_qApp

https://github.com/vasole/pymca/blob/master/PyMca5/PyMcaGraph/backends/_patch_matplotlib.py

The code below systematically crashes on one of my machines but not on another. If you consider it is a problem restricted to my system, please feel free to close the issue.  For me it is not critical, but I do think holding a hard reference to a QApplication when it was not created by matplotlib is a bad idea. Only one QApplication is to be created (https://doc.qt.io/qt-5/qguiapplication.html) and the fact of holding a hard reference to it seems to confuse something.

```python

import PyQt5.Qt as qt
import sys

app = qt.QApplication([])
w = qt.QWidget()
w.show()
if len(sys.argv) > 1:
    print("Crashing")
    sys.exit(app.exec_())
else:
    print("Not crashing")
    ret = app.exec_()
    app = None
    sys.exit()
```

**Comment by tacaswell** [comment]
I spoke with @vasole about this in person and he can no longer reproduce the issue.

I stand by the position that it should be possible for multiple hard-references to the qapp to exist so I am going to close this.

Thanks for your effort on this @vasole !

**Pull request closed without merging**
