### PR TITLE
Skip Appveyor for doc only change (second attempt)

### PR DESCRIPTION
**Pull request by rcomer**
## PR Summary

The path matching for skipping the Appveyor tests doesn’t work - they were queued up in #25461.  So I had a closer look at the [file matching rules](https://www.appveyor.com/docs/how-to/filtering-commits/#file-matching-rules), and I think this should do it.

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by rcomer** [comment]
See a little further up the docs
https://www.appveyor.com/docs/how-to/filtering-commits/#skip-commits-2

> skip_commits.files allows skipping AppVeyor build if all of the files modified in push’s head commit match any of the file matching rules

**Comment by rcomer** [comment]
Or did you mean “or” between the `message` and the `files`?

**Comment by rcomer** [comment]
Example here has “Skipping commits with particular message or from specific user”
https://www.appveyor.com/docs/appveyor-yml/

**Comment by jklymak** [comment]
OK.  OTOH I think doc/**/* is what we want?

**Comment by jklymak** [comment]
ooops, yes, should vibe fine.  Lets merge and see what happens

**Review by jklymak — APPROVED** [review]

**Pull request merged**
