### PR TITLE
Move {get,set}_{x,y}label to _AxesBase.

### PR DESCRIPTION
**Pull request by anntzer**
This lets SecondaryAxes also use it rather than having to reimplement it
(and do so only partially: previously SecondaryAxes did not support the
`loc` kwarg).

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and `pydocstyle<4` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by QuLogic — APPROVED** [review]
Seems reasonable.

**Review by story645 — COMMENTED** [review]
Is it worth making small tests to make codecov happy?

**Comment by anntzer** [comment]
Codecov is fine?

**Comment by story645** [comment]
I'm seeing codecov warnings in the review window:
image

**Review by jklymak — APPROVED** [review]
Yes, this is helpful...

Just to be clear about the codecov - the old code didn't have coverage on those lines either.  They just show up because code was moved around.  If someone wants to open a new issue about those lines and maybe get someone to write some tests, that would be great.  However, I'll merge this as an improvement.

**Pull request merged**
