### PR TITLE
Fix the way to get xs length in set_3d_properties()

### PR DESCRIPTION
**Pull request by wangzexi**
The `xs` is a 1D array that may not have a `shape` attribute.

```python
lines_3d.set_xdata([0, 1])
lines_3d.set_ydata([0, 1])
lines_3d.set_3d_properties([0, 1], zdir='z') # 💥 AttributeError: 'list' object has no attribute 'shape'
```

### CODE REVIEW

**Comment by tacaswell** [comment]
Thanks for working on this.  This definitively should get a test so we do not regress this in the future. 

-----

Are we sure that this is the right place to fix this?  I suspect so as we want to preserve the xdata as a list as long as possible?

It looks like this use of `.shape` came in via 5a49f09ee4a8e3bf6a3355ab83e713d9ae73aeb6 relatively recently.  Are we sure that this value will _always_ be 1D (but sometime a list and sometimes an array)?

**Comment by wangzexi** [comment]
Yes, I'm sure.

---

The `Line3D` is derived from `Line2D`, it shows the `x` will always be a 1D array. For a 1D array, whether its type is `list` or `numpy.ndarray`, the `len()` will always work will.

For `np.broadcast_to`, the second parameter `shape` needs a `tuple`. After testing, both `len(xs)` or `(len(xs),)` are working properly.


https://github.com/matplotlib/matplotlib/blob/08f4629d918b60f5c8e0f35f6a24ecad43088752/lib/matplotlib/lines.py#L1219-L1229
https://github.com/matplotlib/matplotlib/blob/070e0938763628daccf552ba5b5515e5c8ef9d50/lib/matplotlib/lines.py#L967-L978
https://github.com/matplotlib/matplotlib/blob/357db6dd57a4693b2a13e083504932221014fae4/lib/mpl_toolkits/mplot3d/art3d.py#L172-L177

https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html

**Comment by jklymak** [comment]
Please move out of drafts and remove the "needs tests" when the tests are added.  Thanks!

**Comment by timhoffm** [comment]
Re tuple vs. int:
int support is implemented, but not documented. Let's briefly wait and see if they accept this in their documentation (https://github.com/numpy/numpy/pull/19445). If not, it's considered an implementation detail and we shouldn't use it.

**Comment by timhoffm** [comment]
Now, it's official: broadcast_to supports int as shape.

**Review by QuLogic — APPROVED** [review]

**Review by jklymak — APPROVED** [review]

**Pull request merged**
