### PR TITLE
DOC: add banner for 2019 JHEPC

### PR DESCRIPTION
**Pull request by tacaswell**
Adds the banner for the 2019 plotting contest

### CODE REVIEW

**Comment by NelleV** [comment]
Hi Tom,
That's the wrong link (people can edit the form with this one). I'll find the correct one and add it as a comment here.

**Comment by NelleV** [comment]
Here it is: https://docs.google.com/forms/d/e/1FAIpQLSe-_AnKvYSzeQWfNDRoXgW0vl7_8q6jj3QbLIac8eUcb9lSAA/viewform?usp=sf_link

**Comment by jklymak** [comment]
Hang on...........   when did we get draft pull requests?   That’s awesome!!

**Comment by tacaswell** [comment]
I resurrected the commit from last year without changing the link.  I suspect this means we ran last year with submitter editable forms?!

**Comment by tacaswell** [comment]
fixed the submit link and the year.  What url should we use for the first link?

**Comment by NelleV** [comment]
For the first link, I'd use the officiel JHEPC page instead of the scipy website.
jhepc.github.io

if you'd rather go with the scipy website: https://www.scipy2019.scipy.org/

**Comment by NelleV** [comment]
Thanks! LGTM :+1:

**Comment by tacaswell** [comment]
I will build and deploy this in a few hours.

**Comment by tacaswell** [comment]
Deployed (with one extra commit that I pushed upstream, was missing an https so the github.io link was trying to be local).

**Pull request merged**
