### PR TITLE
Fold table.CustomCell into Cell.

### PR DESCRIPTION
**Pull request by anntzer**
We don't use plain Cells, only CustomCells, which is a subclass.
Flattening the inheritance hierarchy makes it easier to document all
parameters in a single constructor.  No backcompat break as CustomCell
is left as an alias.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
One needs to be aware of the fact that noone would construct a `CustomCell` by themselves anyways. 
Instead, one would monkey-patch the `CustomCell` with a new subclass of it, like

    matplotlib.table.CustomCell = CellThatCanDoMoreCoolThings

and obviously, *that* will break with this change. (One application would be [this one](https://stackoverflow.com/a/53573651/4124317), using a cell that can have a background color without edges)

**Comment by timhoffm** [comment]
I suppose we don‘t guarantee that users can monkey-patch classes in Matplotlib.

**Comment by ImportanceOfBeingErnest** [comment]
True. I just want to mention it, because "No backcompat break" sounds like it wouldn't annoy anyone.

**Comment by anntzer** [comment]
Well, literally (nearly) *any* change is a backcompat break in that sense anyways, because even when adding a new feature, we may be overstepping over another method/kwarg name that someone else is using in their monkeypatched alternative class.

**Comment by timhoffm** [comment]
This should have an API change note even though it's not a breaking change.

I advocate for deprecating `CustomCell` to remove unnecessary clutter in the long run.

**Comment by anntzer** [comment]
sure

**Pull request merged**
