### PR TITLE
Added Aria-Labels to all inputs with tooltips for generated HTML animations: issue #17910

### PR DESCRIPTION
**Pull request by xlilos**
## PR Summary
Added aria label attributes to generated HTML to increase accessibility for screenreaders.

## PR Checklist

- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by QuLogic** [comment]
This is fine, but the lines are too long now, as you can see from the flake8 failure.

**Comment by timhoffm** [comment]
I'd be ok excluding the line limitation for `_animation_data.py`. To do so add

~~~
    lib/matplotlib/_animation_data.py: E501
~~~

to `.flake8`.

**Comment by xlilos** [comment]
Thank you QuLogic and timhoffm for bearing with me on this, something I definitely overlooked, sorry about that. Just updated the flake8 file as tim suggested.

Thank you again for the right to the point comments

**Review by timhoffm — APPROVED** [review]

**Comment by tacaswell** [comment]
Awesome, thank you @xlilos !  Congratulations on your first PR to Matplotlib, hopefully we hear from you againg :tada:

**Pull request merged**
