### PR TITLE
doc/conf.py: if set, use SOURCE_DATE_EPOCH to set copyright year.

### PR DESCRIPTION
**Pull request by vagrantc**
The build date of the software shouldn't really have any bearing on
the copyright dates, but by respecting SOURCE_DATE_EPOCH, it at least
limits this to the last time something in the source was changed.

https://reproducible-builds.org/specs/source-date-epoch/

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by vagrantc** [comment]
originally reported as https://bugs.debian.org/990339

**Comment by jklymak** [comment]
Is this really an issue?  Matplotlib source changes a lot more often than yearly.

**Comment by QuLogic** [comment]
`SOURCE_DATE_EPOCH` is set in package builds to make things more reproducible; we also obey it for timestamps in e.g., PDF files.

This needs to pass flake8 though.

**Comment by vagrantc** [comment]
> Is this really an issue? Matplotlib source changes a lot more often than yearly.

One problem is if you build a version from 2019 in 2021, without changing anything in the source code, the documentation will incorrectly claim copyright for the year it was built(2021), not when the source was written(2019).

Another problem is if you build a version from 2019 in 2021, it will contain changes, even if you use the exact same toolchain for the two builds, so it is not bit-for-bit identical, requiring manual review of the differences rather than comparing for bit-for-bit identical files using a checksum.

Hope that helps explain it better!

**Comment by vagrantc** [comment]
flake8 issue should be fixed now.

**Review by QuLogic — APPROVED** [review]

**Review by jklymak — APPROVED** [review]

**Pull request merged**
