### PR TITLE
FIX: PILLOW asarray bug

### LINKED ISSUE #20560: test_png is failing
```
lib/matplotlib/tests/test_png.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
lib/matplotlib/pyplot.py:2378: in imread
    return matplotlib.image.imread(fname, format)
lib/matplotlib/image.py:1544: in imread
    if isinstance(image, PIL.PngImagePlugin.PngImageFile) else
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pil_png = <PIL.PngImagePlugin.PngImageFile image mode=1 size=32x32 at 0x7F4A53D83910>

    def _pil_png_to_float_array(pil_png):
        """Convert a PIL `PNGImageFile` to a 0-1 float array."""
        # Unlike pil_to_array this converts to 0-1 float32s for backcompat with the
        # old libpng-based loader.
        # The supported rawmodes are from PIL.PngImagePlugin._MODES.  When
        # mode == "RGB(A)", the 16-bit raw data has already been coarsened to 8-bit
        # by Pillow.
        mode = pil_png.mode
        rawmode = pil_png.png.im_rawmode
        if rawmode == "1":  # Grayscale.
>           return np.asarray(pil_png, np.float32)
E           TypeError: __array__() takes 1 positional argument but 2 were given
```

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #20560 and fixes CI

I'm not sure if the other rawmodes should be fixed?

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by timhoffm** [comment]
Maybe better to just avoid pillow 8.3.0 like [here](https://github.com/PyTorchLightning/pytorch-lightning/pull/8234/files)?

**Comment by jklymak** [comment]
That's be fine w me. I don't have time for the next few hrs if someone else wanted to do it

**Review by anntzer — APPROVED** [review]
I think I prefer this solution, but perhaps @QuLogic should chime in wrt. packaging implications of #20566 as well?

**Comment by anntzer** [comment]
I decided to merge this with my sole review in order to unbreak the build.  Feel free to revert and exchange for #20566 if that ends up being preferred.

**Pull request merged**
