### PR TITLE
"gif" third-party package added to the extension page

### PR DESCRIPTION
**Pull request by maxhumber**
## PR Summary

Added the `gif` package to the third-party package page at the behest of [this](https://twitter.com/matplotlib/status/1223070498336182273) tweet!

## PR Checklist

- [N/A] Has Pytest style unit tests
- [N/A] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [✅] New features are documented, with examples if plot related
- [✅] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

## Note

Hope I did this right. Thanks for the invitation! Let me know how I can improve this PR if need be!

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
Thanks for this PR. Can I suggest to put *gif* and *animatplot* into a new section named *animations* or similar - because those are not really about interactivity?

**Comment by maxhumber** [comment]
@ImportanceOfBeingErnest just moved all three animation libraries into their own section (sorted alphabetically)!

**Comment by maxhumber** [comment]
> This looks good to me.
> Unfortunately, no circleci test have been run on this (possibly there was a maintainance(?)), so I will not directly merge.

Okay! Is there anything more that you need me to do?

**Comment by ImportanceOfBeingErnest** [comment]
> Okay! Is there anything more that you need me to do?

No. Thanks again for your PR.

**Comment by jklymak** [comment]
Recycled to re-run CI

**Comment by jklymak** [comment]
LGTM https://30024-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/thirdpartypackages/index.html#gif

CI passed before, so merging....

**Pull request merged**
