### PR TITLE
Make `functions` param to secondary_x/yaxis not keyword-only.

### PR DESCRIPTION
**Pull request by anntzer**
I suspect the parameter was made keyword-only because the originally planned signature (#11859) was `secondary_xaxis(location, forward=..., inverse=...)` where the keywords actually add some semantics (though that signature overall seems worse); however, for a single `functions` parameter, having to type an extra `functions=` in the call doesn't help the reader much (either they know what secondary_x/yaxis does, in which case the explicit kwarg doesn't matter, or they don't, in which case the kwarg name hardly helps)... and is a bit annoying.  See the modified gallery entry, for example.

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Review by timhoffm — APPROVED** [review]
Ok. Stubs need to be updated.

**Comment by anntzer** [comment]
oops, done.

**Review by oscargus — APPROVED** [review]

**Comment by oscargus** [comment]
Is an API change note worthwhile? If not, anyone can merge.

**Comment by timhoffm** [comment]
An API change note is not neccessary since we're only relaxing the API. It's also not very helpful: Nobody will read through API changes, see this and take an action ("Finally, this is not kwonly anymore - I go through my code and change to positional use" is not gonna happen). So the note would mostly be noise. The only possible benefit would be a `.. versionchanged::` note in the function, so that a user could decide to write backward-compatible code. - But then again. I don't think, we have such information consistently. I would not bother.

**Pull request merged**
