### PR TITLE
Do not restrict coverage to `matplotlib` module only

### PR DESCRIPTION
**Pull request by Kojoley**
Addition to #6819

### CODE REVIEW

**Comment by WeatherGod** [comment]
I should point out that mpl_toolkits is an optional install. Furthermore, could this lead to confusion if basemap is installed on a user's system? basemap's tests (such that it is) doesn't get triggered by matplotlib's test suite.

**Comment by Kojoley** [comment]
I do not why someone may be confused more than now, because current tests list is [hardcoded](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/__init__.py#L1546-L1548) with `mpl_toolkits` tests while coverage test is not enabled by default.

**Comment by jenshnielsen** [comment]
We can just restrict coverage to 

```
matplotlib
mpl_toolkits.axes_grid	
mpl_toolkits.axes_grid1	
mpl_toolkits.axisartist
mpl_toolkits.mplot3d
```

or similar. That would avoid it picking up `basemap`

**Comment by Kojoley** [comment]
I do not see any `basemap` import in the whole tests collection (in the list of possible test modules) so I have no clue how `matplotlib.test()` may touch basemap.

The [--cover-package](http://nose.readthedocs.io/en/latest/plugins/cover.html#cmdoption--cover-package) option (or `NOSE_COVER_PACKAGE` env variable) is just about filtering the coverage report. It does nothing to test collection. Default nose coverage plugin reports information only about files that have been touched during runned tests.

To ensure that nothing comes from the `basemap` to the coverage report this can be done to `.coveragerc`
```
[report]
omit =
    lib/mpl_toolkits/basemap/*
```

P.S. I do not know what we are arguing here about, because this PR is just a fix for #6819 and the questions should be addressed not to me then...

**Comment by tacaswell** [comment]
I think this is fine.  It is good to be able to see the coverage on axes_grid and friends.

We only install basemap as part of the building the docs (and only after the tests are run).

**Pull request merged**
