### PR TITLE
BLD: make minimum cycler version 0.10.0

### LINKED ISSUE #6325: Master requires cycler 0.10.0
Master requires cycler 0.10.0, not 0.9.0+ (as specified in setupext.py).

For 0.9.0, importing matplotlib fails:
```python

    In [1]: import matplotlib

        <<< SNIP >>>

        807     for prop in cycler_inst.keys:
        808         norm_prop = _prop_aliases.get(prop, prop)
    --> 809         cycler_inst.change_key(prop, norm_prop)
        810 
        811     return cycler_inst

    AttributeError: 'Cycler' object has no attribute 'change_key'
```
`change_key` was added to 0.10.0 according to the cycler release notes.

### PR DESCRIPTION
**Pull request by tacaswell**
closes #6325

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @WeatherGod 

I think we did not backport those changes to 2.x so I do not think this needs to be backported either.

**Comment by jenshnielsen** [comment]
In that case I think 2.x should run the tests with cycler 0.9 on Travis as 1.5.x does

**Comment by WeatherGod** [comment]
Also need to update `setupext.py`

**Comment by tacaswell** [comment]
@WeatherGod update what else in setupext.py?

**Comment by WeatherGod** [comment]
Sorry, let me clarify... in my PR, I updated `get_install_requires()` so that it returned "cycler>=0.9". I don't know why the diff you have does not reflect that.

**Comment by tacaswell** [comment]
I could not find anything in the code that did any version checking on cycler last night (which confused me).  Maybe we lost it in a bad merge?

**Comment by WeatherGod** [comment]
The faulty PR is #6275. It was backported to 2.x.

**Comment by tacaswell** [comment]
:sheep: I forgot to update my local master before forking this branch, stand by.

**Comment by WeatherGod** [comment]
backported as 9f83d531808

**Pull request merged**
