### PR TITLE
DOC: remove JDH memorial block; other front page tweaks; credits

### PR DESCRIPTION
**Pull request by efiring**
On the front page, in addition to removing the memorial:

- Capitalized Matplotlib, Python, IPython
- removed unnecessary reference to Mathematica

I'm tempted to remove the reference to Matlab also; is it doing us any good? Maybe it is helpful as an indication of our historical origins.

The credits page needs the actual contributors list from git followed by formatting and editing.

### CODE REVIEW

**Comment by tacaswell** [comment]
Names of people extracted from git, the current count is 600 (!?).

The text should also include a sentence like 'The following people have contributed code to the Matplotlib code base.  This does not account for the many people who have made valuable contributions by reporting bugs, answering questions, and teaching over the years."

```
['4over7', 'Aaron Boushley', 'AbdealiJK', 'Acanthostega', 'Adam Ginsburg', 'Adam Heck', 'Adam Ortiz', 'Adam Williamson', 'Adrian Price-Whelan', 'Adrien Chardon', 'Adrien F. Vincent', 'Ahmet Bakan', 'Alan Bernstein', 'Alan Du', 'Alberto', 'Alejandro Dubrovsky', 'Alex C. Szatmary', 'Alex Loew', 'Alex Rothberg', 'Alexander Taylor', 'Alexei Colin', 'Alexis Bienvenüe', 'Ali Mehdi', 'Ali Uneri', 'Alistair Muldal', 'Allan Haldane', 'Alvaro Sanchez', 'Amit Aronovitch', 'Amy', 'AmyTeegarden', 'AndersonDaniel', 'Andrea Bedini', 'Andreas Hilboll', 'Andreas Mayer', 'Andreas Wallner', 'Andrew Dawson', 'Andrew Merrill', 'Andrew Straw', 'Andy Zhu', 'Anton Akhmerov', 'Antony Lee', 'Arie', 'Ariel Hernán Curiale', 'Arnaud Gardelein', 'Arpad Horvath', 'Arvind', 'Aseem Bansal', 'BHT', 'Behram Mistree', 'Ben Cohen', 'Ben Gamari', 'Ben Keller', 'Ben Root', 'Benedikt Daurer', 'Benedikt J. Daurer', 'Benjamin Berg', 'Benjamin Congdon', 'Benjamin Reedlunn', 'Binglin Chang', 'Bradley M. Froehle', 'Brandon Liu', 'Brett Cannon', 'Brett Graham', 'Brian Mattern', 'Brian McLaughlin', 'Bruno Beltran', 'Bruno Zohreh', 'CJ Carey', 'Cameron Bates', 'Cameron Davidson-Pilon', 'Cameron Fackler', 'Carissa Brittain', 'Carl Michal', 'Carwyn Pelley', 'Casey Webster', 'Casper van der Wel', 'Charles Moad', 'Chen Karako', 'Chris Beaumont', 'Chris G', 'Chris Holdgraf', 'Christian Brueffer', 'Christian Stade-Schuldt', 'Christoph Dann', 'Christoph Deil', 'Christoph Gohlke', 'Christoph Hoffmann', 'Cimarron Mittelsteadt', 'Conner R. Phillips', 'Corey Farwell', 'Craig M', 'Craig Tenney', 'DaCoEx', 'Damon McDougall', 'Dan Hickstein', 'Daniel C. Marcu', 'Daniel Hyams', "Daniel O'Connor", 'Danny Hermes', 'Dara Adib', 'Darren Dale', 'David A', 'David Anderson', 'David Haberthür', 'David Huard', 'David Kaplan', 'David Kent', 'David Kua', 'David Stansby', 'David Trémouilles', 'Dean Malmgren', 'Devashish Deshpande', 'Diego Mora Cespedes', 'Dietrich Brunn', 'Dmitry Lupyan', 'DonaldSeo', 'Dora Fraeman', 'DoriekeMG', 'Drew J. Sonne', 'Duncan Macleod', 'Dylan Evans', 'E. G. Patrick Bos', 'Edin Salkovic', 'Egor Panfilov', 'Elena Glassman', 'Elias Pipping', 'Elliott Sales de Andrade', 'Elvis Stansvik', 'Emil Mikulic', 'Eric Dill', 'Eric Firing', 'Eric Larson', 'Eric Ma', 'Eric O. LEBIGOT (EOL)', 'Erik Bray', 'Eugen Beck', 'Eugene Yurtsev', 'Evan Davey', 'Ezra Peisach', 'Fabian-Robert Stöter', 'Fabien Maussion', 'Fabio Zanini', 'Federico Ariza', 'Felipe', 'Fernando Perez', 'Filipe Fernandes', 'Florencia Noriega', 'Florian Le Bourdais', 'Florian Rhiem', 'Francesco Montesano', 'Francis Colas', 'Francoise Provencher', 'Frank Yu', 'François Magimel', 'Gaute Hope', 'Gellule Xg', 'Geoffrey Spear', 'Geoffroy Billotey', 'Gerald Storer', 'Giovanni', 'Graham Poulter', 'Gregory Ashton', 'Gregory R. Lee', 'Grillard', 'Grégory Lielens', 'Guillaume Gay', 'Gustavo Braganca', 'Hakan Kucukdereli', 'Hans Dembinski', 'Hans Meine', 'Hans Moritz Günther', 'Hassan Kibirige', 'Hastings Greer', 'Heiko Oberdiek', 'Henning Pohl', 'Herbert Kruitbosch', 'Holger Peters', 'Hubert Holin', 'Ian Thomas', 'Ignas Anikevicius (gns_ank)', 'Ilia Kurenkov', 'ImSoErgodic', 'Ioannis Filippidis', 'Isaac Schwabacher', 'Isaac Slavitt', 'Ismo Toijala', 'J. Goutin', 'Jaap Versteegh', 'Jack Kelly', 'Jacob McDonald', 'Jae-Joon Lee', 'Jaime Fernandez', 'Jake Vanderplas', 'James A. Bednar', 'James Pallister', 'James R. Evans', 'JamesMakela', 'Jan Schlüter', 'Jan Schulz', 'Jan-Philip Gehrcke', 'Jan-willem De Bleser', 'Jarrod Millman', 'Jascha Ulrich', 'Jason Grout', 'Jason King', 'Jason Liw Yan Chong', 'Jason Miller', 'Jason Zheng', 'JayP16', 'Jeff Lutgen', 'Jeff Whitaker', 'Jeffrey Bingham', 'Jeffrey Hokanson @ Loki', 'Jens Hedegaard Nielsen', 'Jeremy Fix', "Jeremy O'Donoghue", 'Jeremy Thurgood', 'Jessica B. Hamrick', 'Jim Radford', 'Jochen Voss', 'Jody Klymak', 'Joe Kington', 'Joel B. Mohler', 'John Hunter', 'John Vandenberg', 'JojoBoulix', 'Jonathan Waltman', 'Jorrit Wronski', 'Josef Heinen', 'Joseph Fox-Rabinovitz', 'Joseph Jon Booker', 'José Ricardo', 'Jouni K. Seppänen', 'Juan Nunez-Iglesias', 'Julia Sprenger', 'Julian Mehne', 'Julian Taylor', 'Julian V. Modesto', 'JulianCienfuegos', 'Julien Lhermitte', 'Julien Schueller', 'Julien Woillez', 'Julien-Charles Lévesque', 'Jun Tan', 'Kacper Kowalik (Xarthisius)', 'Kanwar245', 'Katy Huff', 'Ken McIvor', 'Kevin Chan', 'Kevin Davies', 'Kevin Keating', 'Kimmo Palin', 'Kjartan Myrdal', 'Klara Gerlei', 'Konrad Förstner', 'Konstantin Tretyakov', 'Kristen M. Thyng', 'Kyle Bridgemohansingh', 'Kyler Brown', 'Lance Hepler', 'Laptop11_ASPP2016', 'Larry Bradley', 'Leeonadoh', 'Lennart Fricke', 'Leo Singer', 'Levi Kilcher', 'Lion Krischer', 'Lodato Luciano', 'Lori J', 'Loïc Estève', 'Loïc Séguin-C', 'Luis Pedro Coelho', 'Magnus Nord', 'Majid alDosari', 'Maksym P', 'Manuel GOACOLOU', 'Manuel Jung', 'Manuel Metz', 'Marc Abramowitz', 'Marcos Duarte', 'Marek Rudnicki', 'Marianne Corvellec', 'Marin Gilles', 'Markus Roth', 'Markus Rothe', 'Martin Dengler', 'Martin Fitzpatrick', 'Martin Spacek', 'Martin Teichmann', 'Martin Thoma', 'Martin Ueding', 'Masud Rahman', 'Mathieu Duponchelle', 'Matt Giuca', 'Matt Hancock', 'Matt Klein', 'Matt Li', 'Matt Newville', 'Matt Shen', 'Matt Terry', 'Matthew Brett', 'Matthew Emmett', 'Matthias Bussonnier', 'Matthias Lüthi', 'Matthieu Caneill', 'Matěj Týč', 'Maximilian Albert', 'Maximilian Maahn', 'Maximilian Trescher', 'Mellissa Cross', 'Mher Kazandjian', 'Michael', 'Michael Droettboom', 'Michael Sarahan', 'Michael Welter', 'Michiel de Hoon', 'Michka Popoff', 'Mike Henninger', 'Mike Jarvis', 'Mike Kaufman', 'Mikhail Korobov', 'MinRK', 'Minty Zhang', 'MirandaXM', 'Miriam Sierig', 'Muhammad Mehdi', 'Nathan Goldbaum', 'Nathan Musoke', 'Neil', 'Neil Crighton', 'Nelle Varoquaux', 'Niall Robinson', 'Nic Eggert', 'Nicholas Devenish', 'Nick Semenkovich', 'Nico Schlömer', 'Nicolas P. Rougier', 'Nicolas Pinto', 'Nicolas Tessore', 'Nikita Kniazev', 'Niklas Koep', 'Nikolay Vyahhi', 'Nils Werner', 'Norbert Nemec', 'OceanWolf', 'Oleg Selivanov', 'Olga Botvinnik', 'Oliver Willekens', 'Orso Meneghini', 'Pankaj Pandey', 'Parfenov Sergey', 'Pascal Bugnion', 'Patrick Chen', 'Patrick Marsh', 'Paul', 'Paul Barret', 'Paul G', 'Paul Ganssle', 'Paul Hobson', 'Paul Ivanov', 'Paul Kirow', 'Paul Romano', 'Pauli Virtanen', 'Per Parker', 'Perry Greenfield', 'Pete Bachant', 'Pete Huang', 'Pete Peterson', 'Peter Iannucci', 'Peter Mortensen', 'Peter St. John', 'Peter Würtz', 'Petr Danecek', 'Phil Elson', 'Phil Ruffwind', 'Pierre Haessig', 'Pierre de Buyl', 'Pim Schellart', 'Piti Ongmongkolkul', 'Przemysław Dąbek', 'Puneeth Chaganti', 'Qingpeng "Q.P." Zhang', 'Ramiro Gómez', 'Randy Olson', 'Reinier Heeres', 'Remi Rampin', 'Richard Hattersley', 'Richard Trieu', 'Ricky', 'Robert Johansson', 'Robin Dunn', 'Robin Wilson', 'Rohan Walker', 'Roland Wirth', 'Rui Lopes', 'Russell Owen', 'RutgerK', 'Ryan Blomberg', "Ryan D'Souza", 'Ryan Dale', 'Ryan May', 'Ryan Morshead', 'Ryan Nelson', 'RyanPan', 'Salganos', 'Salil Vanvari', "Sameer D'Costa", 'Samuel St-Jean', 'Sander', 'Sandro Tosi', 'Scott Howard', 'Scott Lasley', 'Scott Lawrence', 'Scott Stevenson', 'Sebastian Pinnau', 'Sebastian Raschka', 'Sebastián Vanrell', 'Seraphim Alvanides', 'Sergey Kholodilov', 'Sergey Koposov', 'Silviu Tantos', 'Simon Cross', 'Simon Gibbons', 'Skelpdar', 'Skipper Seabold', 'Slav Basharov', 'Spencer McIntyre', 'Stanley, Simon', 'Stefan Lehmann', 'Stefan Pfenninger', 'Stefan van der Walt', 'Stefano Rivera', 'Stephan Erb', 'Stephen Horst', 'Sterling Smith', 'Steve Chaplin', 'Steven Silvester', 'Steven Tilley', 'Stuart Mumford', 'Tadeo Corradi', 'Takafumi Arakaki', 'Takeshi Kanmae', 'Tamas Gal', 'Terrence J. Katzenbaer', 'The Gitter Badger', 'Thomas A Caswell', 'Thomas Hisch', 'Thomas Kluyver', 'Thomas Lake', 'Thomas Robitaille', 'Thomas Spura', 'Thorsten Liebig', 'Till Stensitzki', 'Timo Vanwynsberghe', 'Tobias Hoppe', 'Tobias Megies', 'Todd Jennings', 'Todd Miller', 'Tomas Kazmar', 'Tony S Yu', 'Tor Colvin', 'Travis Oliphant', 'Trevor Bekolay', 'Trish Gillett-Kawamoto', 'Truong Pham', 'Ulrich Dobramysl', 'Umair Idris', 'Vadim Markovtsev', 'Valentin Haenel', 'Valentin Schmidt', 'Victor Zabalza', 'Viktor Kerkez', 'Vlad Seghete', 'Víctor Terrón', 'Víctor Zabalza', 'Warren Weckesser', 'Wen Li', 'Wendell Smith', 'Werner F Bruhin', 'Wes Campaigne', 'Wieland Hoffmann', 'Will Silva', 'William Granados', 'William Manley', 'Wouter Overmeire', 'Xiaowen Tang', 'Xufeng Wang', 'Yann Tambouret', 'Yaron de Leeuw', 'Yu Feng', 'Yunfei Yang', "Yuri D'Elia", 'Yuval Langer', 'Zach Pincus', 'Zair Mubashar', 'Zbigniew Jędrzejewski-Szmek', 'Zohreh', 'alcinos', 'alex', 'alvarosg', 'aneda', 'anykraus', 'arokem', 'aseagram', 'aszilagyi', 'bblay', 'bev-a-tron', 'blackw1ng', 'blah blah', 'burrbull', 'butterw', 'cammil', 'captainwhippet', 'chadawagner', 'chebee7i', 'danielballan', 'davidovitch', 'daydreamt', 'deeenes', 'dlmccaffrey', 'domspad', 'donald', 'drevicko', 'e-q', 'elpres', 'endolith', 'fardal', 'ffteja', 'fgb', 'fibersnet', 'frenchwr', 'fvgoto', 'gcallah', 'gepcel', 'gitj', 'gluap', 'goir', 'greg-roper', 'hannah', 'hugadams', 'insertroar', 'itziakos', 'jbbrokaw', 'jonchar', 'juan.gonzalez', 'kcrisman', 'kelsiegr', 'khyox', 'kikocorreoso', 'klaus', 'klonuo', 'kramer65', 'kshramt', 'lboogaard', 'lichri12', 'limtaesu', 'lspvic', 'lzkelley', 'mamrehn', 'marky', 'masamson', 'mbyt', 'mcelrath', 'mdipierro', 'mlub', 'mobando', 'mrkrd', 'muahah', 'myyc', 'nbrunett', 'nepix32', 'nickystringer', 'nwin', 'pkienzle', 'productivememberofsociety666', 'profholzer', 'pupssman', 'rahiel', 'rhoef', 'rsnape', 's9w', 'scls19fr', 'scott-vsi', 'sdementen', 'sfroid', 'sohero', 'spiessbuerger', 'stahlous', 'switham', 'syngron', 'tmdavison', 'tomoemon', 'torfbolt', 'u55', 'ugurthemaster', 'ultra-andy', 'vbr', 'vraelvrangr', 'xbtsw', 'xuanyuansen']
```

---

```bash
#! /bin/bash
echo 'time&name' > commits_time_author.csv; 
git log --pretty=format:'%at&%aN <%aE>' >> commits_time_author.csv
```

```python
import pandas as pd
commits = pd.read_csv('commits_time_author.csv', sep='&')
au = set(commits.name)
nn = set(n.split('<')[0] for n in au)
print(sorted(nn))
```

It is easy to sort this by commit count, but I think alphabetical is better.

**Comment by QuLogic** [comment]
Or `git shortlog -s`... (with `-n` for commit count sorting.)

**Comment by tacaswell** [comment]
But I _know_ how to use this hammer 😉

**Comment by NelleV** [comment]
I would remove the mention of matlab. While it was certainly relevant 10 years ago, I don't think it is relevant today. matplotlib is not going to be either a reason or a roadblock to migrating matlab code to python.

**Comment by dopplershift** [comment]
>  While it was certainly relevant 10 years ago, I don't think it is relevant today.

I would love to live in your world--for many my sector, MATLAB is what they know of, not this weird Python thing. Even if at a code level moving to matplotlib isn't smooth, mentioning MATLAB as a reference point for similar plotting functionality is useful.

**Comment by efiring** [comment]
There are surely more improvements that can be made, but I think this PR is now merge-ready as a reasonably self-contained and complete increment.

**Review by NelleV — APPROVED** [review]
LGTM :+1: 
Thanks!

**Pull request merged**
