### PR TITLE
Create barh.py

### PR DESCRIPTION
**Pull request by tanujdhiman**
Add Broken barh plots

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks @tanujdhiman 

Just to be clear about plot_types: it is not meant to be comprehensive, but rather to be a stripped down quick reference to what matplotlib can do.  More comprehensive docs are in the gallery and API docs 

In my opinion, this suggestion is too specialized for plot_types. Maybe consider moving to examples, if there is not a similar example already?

**Comment by tanujdhiman** [comment]
Hi @jklymak 
This example or plot type is not there in the directory so that I specified it with an example of "Broken Barh" Plot.

Hope you understand !!
Thanks

**Comment by jklymak** [comment]
I _do_ understand.  And again, not _every_ plot type is listed, nor should it be in my opinion.  `bar` is listed, and `broken_barh` is just a variation on `bar`.  If you wanted to add a see-also to the bar plot_type, that would be great, but I'm not in favour of putting too many variations in this gallery.

**Comment by tanujdhiman** [comment]
Yes. But from my personal experience most of the very beginner guys did suffering on Github for do all the plots. They don't find it there. You know Github is open Source and all the things are collectively available here. I am guiding them. That's why I felt this must be added into it.

I know it is the variation of Bar plot but shouldn't it to be added for the ease of students like they just do all the implementation from one repository. Please add if possible 

Thanks

**Comment by tanujdhiman** [comment]
> Thanks @tanujdhiman
> 
> Just to be clear about plot_types: it is not meant to be comprehensive, but rather to be a stripped down quick reference to what matplotlib can do. More comprehensive docs are in the gallery and API docs
> 
> In my opinion, this suggestion is too specialized for plot_types. Maybe consider moving to examples, if there is not a similar example already?

No there is no example of Broken Barh we can add there. Shouldn't we ?

**Comment by jklymak** [comment]
Yes that would be great if there is none already.  🙏

**Comment by tanujdhiman** [comment]
> Yes that would be great if there is none already. 🙏

I've just make an PR for adding file into examples. Please merge it will help.

Thanks

**Pull request closed without merging**
