### PR TITLE
Added option for an offset for MultipleLocator

### PR DESCRIPTION
**Pull request by jondoesntgit**
## PR Summary

Allows for an optional kwarg `offset` to be passed to MultipleLocator. For example, allows ticks to be placed at (.5, 1.5, 2.5, 3.5) with `MultipleLocator(base=1, offset=.5)`.

## PR Checklist

I cannot get matplotlib to build locally. 

```
$ python setup.py install
[...]
In file included from src/py_converters.cpp:3:
In file included from src/py_converters.h:17:
src/_backend_agg_basic_types.h:7:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1
```

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(matplotlib-env)
```

Once I can build, I can finish the other check marks in your checklist:

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

Other questions: 

- Which branch should I try to merge into? I'm assuming it's not master. Is 3.5.x the right target?

### CODE REVIEW

**Comment by jklymak** [comment]
I moved to draft.   Let us know if you still cannot build locally.  There are quite a few of us using apple and I don't recall any (recent) issues building.  Though there was something about clang versus cpp at some point, the solution to which you may be able to find in old issues.

**Comment by jondoesntgit** [comment]
Will try again when I have time (may be several weeks though)

**Comment by tacaswell** [comment]
This PR is affected by a re-writing of our history to remove a large number of accidentally committed files [see discourse](https://discourse.matplotlib.org/t/minor-re-writing-of-history-and-moving-from-master-to-main-for-default-branch/22354/6) for details.

To recover this PR it will need be rebased onto the new default branch (main).  There are several ways to accomplish this, but we recommend (assuming that you call the matplotlib/matplotlib remote `"upstream"`

```bash
git remote update
git checkout main
git merge --ff-only upstream/main
git checkout YOUR_BRANCH
git rebase --onto=main upstream/old_master
# git rebase -i main # if you prefer
git push --force-with-lease   # assuming you are tracking your branch
```

If you do not feel comfortable doing this or need any help please reach out to any of the Matplotlib developers.  We can either help you with the process or do it for you.

Thank you for your contributions to Matplotlib and sorry for the inconvenience.

**Comment by jondoesntgit** [comment]
Thanks @tacaswell @jklymak,

The PR only changes three lines of code (should take 30 seconds for someone who already has a dev install of matplotlib). I can try rebasing, but it will take me a lot longer than 30 seconds to figure everything out.

You can see the three simple changes here: https://github.com/matplotlib/matplotlib/pull/21168/commits/ba6aeff071196f705aa213d4e2b49221c0b61883

Jonathan

**Comment by rcomer** [comment]
This seems like a useful thing to have, so I have picked it up in #25542.  I think we can close this one now.  Thank you for your work and for providing clear directions to the relevant commit @jondoesntgit!

**Pull request closed without merging**
