### PR TITLE
Fixes png showing inconsistent inset_axes position

### PR DESCRIPTION
**Pull request by AlexCav**
## PR Summary
In response to issue #8120. 
Added a fix for inconsistent inset_axes position across different savefig formats. 
When creating an inset_axes, not specifying a bbox_transform property will default to parent_axes.transAxes. Changes located in inset_locator.py, with image comparison tests added to test_axes_grid1.py. 

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This looks like a good fix.  You have some PEP8 errors (look under the travis py 3.6 tests).   Thanks!

**Comment by tacaswell** [comment]
Thanks @AlexCav !

**Comment by tacaswell** [comment]
(my approval is moudlo the pep8 fixes)

**Comment by AlexCav** [comment]
Thank you for the quick approval! I have made the necessary pep8 fixes.

**Comment by ImportanceOfBeingErnest** [comment]
I fear this "fix" has broken the usual behaviour of the inset axes.

Running the following in a jupyter notebook

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
xdata, ydata = np.arange(8), np.arange(8)

plt.figure(figsize=(6,3))
ax = plt.subplot(111)
ax.plot(xdata, ydata)
axins = inset_axes(ax, width=0.2, height=0.2, loc='upper left')
```

results in a huge figure of 18129 x 31028 pixels, which I can't even upload here to show it to you because it's too big. Running that code as script (without the notebook's default `bbox_inches="tight"` simply results in an empty plot.

**Comment by jklymak** [comment]
I think one proper thing to do here is move inset_axes into the main axes method and overhaul it, including better documentation.  This is the one thing from axes_grid1 that I would use somewhat often and it seems like core functionality.  

Not to say that a more short term fix to these inconsistencies would also not be welcome.

**Comment by jklymak** [comment]
Btw can this be a new issue so it gets some attention?

**Comment by ImportanceOfBeingErnest** [comment]
I simply think that this is not the proper fix for the issue. Shouldn't it be reverted back and the old issue be reopened?

**Comment by jklymak** [comment]
I agree that the fix is wrong, though I think I like the test, so I won't revert.  

It seems that #8120 is just bad documentation and not using `bbox_to_anchor` correctly?  It seems that if `bbox_to_anchor` is not `None` then the default should indeed be `bbox_transform = parent._axes.transAxes` if it is not supplied.  But if `bbox_to_anchor` is not supplied, then the transform needs to stay None.  #8952 explains things quite well. 

It is all a bit confusing, not helped by quadruply nested subclasses.  I'll try and have a PR in the next couple of days, if no one beats me to it, that tries to a) fix the error, b) make the documentation more clear, c) add an error check on the bbox argument so that it at least has all the elements needed to make a width and height.

**Comment by jklymak** [comment]
As discussed in #10986 and above, this PR incorrectly assigned `transAxes` as the transform.  While @AlexCav is correct, that will yield the a consistent application of the inset across different DPI output, it breaks old behaviour.  So I'm reverting the merge...

**Comment by jklymak** [comment]
OK, can't auto-revert...  New PR

**Pull request merged**
