### PR TITLE
Add workaround for failures due to newer miktex

### PR DESCRIPTION
**Pull request by janschulz**
This should stop the current failures on appveyor, e.g., https://github.com/matplotlib/matplotlib/pull/6741

I will investigate what the real problem is...

### CODE REVIEW

**Comment by janschulz** [comment]
Builds in 

https://ci.appveyor.com/project/JanSchulz/matplotlib/build/1.0.197
https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.2040

Will merge when one of them passes...

**Comment by jenshnielsen** [comment]
Thanks @janschulz

**Comment by jenshnielsen** [comment]
For the record I am happy for you to self merge this

**Comment by janschulz** [comment]
Oh fun, can't reproduce on my local system (which also has updated *local* latex packages on top of the conda installed miktex conda-package provided ones...):

```
[matplotlib_build] λ nosetests.exe -v matplotlib.tests.test_backend_svg
matplotlib.tests.test_backend_svg.test_bold_font_output.test ... SKIP: Don't know how to convert svg files to png
matplotlib.tests.test_backend_svg.test_bold_font_output_with_none_fonttype.test ... SKIP: Don't know how to convert svg files to png
matplotlib.tests.test_backend_svg.test_fill_black_with_alpha.test ... SKIP: Don't know how to convert svg files to png
matplotlib.tests.test_backend_svg.test_noscale.test ... ok
matplotlib.tests.test_backend_svg.test_noscale.test ... ok
matplotlib.tests.test_backend_svg.test_noscale.test ... SKIP: Don't know how to convert svg files to png
matplotlib.tests.test_backend_svg.test_composite_images ... ok
matplotlib.tests.test_backend_svg.test_determinism_notex ... ok
matplotlib.tests.test_backend_svg.test_text_urls ... ok
matplotlib.tests.test_backend_svg.test_visibility ... ok
matplotlib.tests.test_backend_svg.test_determinism_tex ... ok

----------------------------------------------------------------------
Ran 11 tests in 86.486s

OK (SKIP=4)
```

**Comment by janschulz** [comment]
Ok, I can replicate when I start with no local latex packages -> it seems that this happens when you use a newly installed miktex, so the problem is in the miktex package.

**Comment by janschulz** [comment]
Ok, tests pass, lets merge this and then I will hopefully find the problem in miktex and fix it there...

**Pull request merged**
