### PR TITLE
CI: add -v to appveyor pytest incantation

### PR DESCRIPTION
**Pull request by tacaswell**
To check which test it is failing on

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
On a tangent, I just discovered you can remote-desktop into the appveyor VM during the build... https://www.appveyor.com/docs/how-to/rdp-to-build-worker/ handy.

**Comment by dstansby** [comment]
xref #9176

**Comment by QuLogic** [comment]
-1073740791 == c0000409 == STATUS_STACK_BUFFER_OVERRUN; I've not had much luck triggering any error in valgrind on Linux, though it's a bit hard to sort through. I added `pytest-faulthandler` to AppVeyor here, but I'm not sure if it'll be effective.

**Comment by QuLogic** [comment]
According to UBsan, there is a `memcpy` on `NULL` in FreeType. I am not sure if that is the cause of the problem here, but a long time ago Windows `printf` didn't like `NULL` strings so it might be the reason. (It's also triggered by a few other tests, but `test_cull_markers` is the first one.)

It is fixed in FreeType 2.6.3, but using that version causes 930 failures. Also, SF is not redirecting properly so we can't download it onto builders right now (it's working from cache, mostly).

**Comment by anntzer** [comment]
Change the download logic (setupext.py line 1181 etc.) so that on a hash mismatch the second url gets tried?  Or simpler, just prefer downloading from savannah...
Although interestingly https://www.freetype.org/download.html is down too.

**Comment by tacaswell** [comment]
https://twitter.com/Slav636/status/912906308889825280 for a pointer to https://www.microsoft.com/en-us/download/confirmation.aspx?id=985 to look up details.

**Comment by QuLogic** [comment]
There's a table [here](https://msdn.microsoft.com/en-us/library/cc704588.aspx) for that.

**Comment by tacaswell** [comment]
The two appevyor fails on this PR are in a different place than the rest (after all of the tests passed) or the freetype issue.

**Comment by tacaswell** [comment]
https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.3136
https://ci.appveyor.com/project/matplotlib/matplotlib/build/1.0.3149

**Pull request closed without merging**
