### PR TITLE
Silence labeled data warning in tests

### PR DESCRIPTION
**Pull request by jenshnielsen**
Continuing to fix various warnings in the test suite. 

This suppresses a warning in the labeled data test and improves the error message a bit.

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I added another commit to fix a warning in the cycles test. The warnings.catch_warnings context manager does not actually catch the warning without a warnings filter.

**Comment by jenshnielsen** [comment]
Silenced yet another warning by making sure a font file is closed

**Comment by tacaswell** [comment]
how far back do we want to port this?

**Comment by jenshnielsen** [comment]
I was inclined to not backport it apart from the improved warning message it really only touches test output but I am ok with backporting it to 2.x

**Comment by tacaswell** [comment]
sold on not backporting.

**Pull request merged**
