### PR TITLE
Fix broken inset_locator used with subfigures

### PR DESCRIPTION
**Pull request by matt256**
## PR Summary
Addresses the bug report https://github.com/matplotlib/matplotlib/issues/24589

From report: 

> When using inset_locator functions in subfigures, the plots are not placed correctly. Adapting this demo
> https://matplotlib.org/stable/gallery/axes_grid1/demo_colorbar_of_inset_axes.html
> to use subfigures shows incorrect plots.

Implemented the proposed resolution and wrote a unit test that validates the image referenced in the bug report is generated properly

## PR Checklist

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] New plotting related features are documented with examples.

**Release Notes**
- [N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by rcomer** [comment]
Hi @matt256, thanks for the PR and welcome to Matplotlib!  It looks like, since you created your branch, there have been some changes on the `main` branch within the same file you edited.  So you will need to rebase and fix some conflicts, following the instructions here:
https://matplotlib.org/devdocs/devel/development_workflow.html#rebasing-on-upstream-main

For your question [here](https://github.com/matplotlib/matplotlib/issues/24589#issuecomment-1345281882), you will see a failure in our tests having both added and replaced an image in the same PR.  To fix that, you will need to squash the commits down to one.  There are instructions for that here:
https://matplotlib.org/devdocs/devel/development_workflow.html#rewriting-commit-history

**Comment by rcomer** [comment]
Hi @matt256, it looked like your branch got into a bit of a tangle.  I thought it might be difficult to guide you through fixing that so, I hope you don't mind, I just pushed a change myself.  While I was there, I also dropped your last two commits, as it looked like you used `black` or a similar auto-formatter on the test file.  This created a lot of changes that were not relevant to the problem you are solving so would have made it harder to review.  You can fix those `flake8` errors by just adding an extra space to the start of the lines.

**Comment by matt256** [comment]
Hi @rcomer, thanks for you help and digging me out of my hole. You are correct. I got a bit turned around, and I did use black. I'll see if I can get these issues resolved this evening with your guidance on flake8 and then go ahead and get it squashed to get the other error to go away. couple quick questions, though: 

* I noted that creating the test image via a standalone script and creating it inside the test file created a file that was about 3kb different in size. Whatever the change actually was, it caused the image comparison to fail. Because I used the same script to generate the image both inside and outside the test, I assumed it was something that the decorator was doing and it wasn't a big deal, Just wanted to note it, though. 
* This likely may have been due to my late-night stupor, but before I set up my linter and formatter, I was getting flake8 errors for "line too long" throughout the entire test file. Did I see that right? I see that isn't the case anymore. I thought I may have just been the first one to get to it. Am I going crazy? It may just not matter anymore

**Comment by jklymak** [comment]
@matt256 - the default styles all change with Matplotlib 2.0, but the tests still default to the old style so we did not need to regenerate the images.  New test should usually use the up-to-date style: e.g. `@image_comparison(['contour_hatching'], remove_text=True, style='mpl20')`

**Comment by QuLogic** [comment]
Please update the title of this PR; it is currently auto-generated from your branch name, but it is not very clear what it is for someone looking at notifications/the list of PRs.

**Comment by oscargus** [comment]
Closing this as #24783 is a newer version.

**Pull request closed without merging**
