### PR TITLE
Feature Request (Issue #14661): Ability to show quartiles in violin plot

### PR DESCRIPTION
**Pull request by JAbrokwah**
## PR Summary

Addresses [issue #14661](https://github.com/matplotlib/matplotlib/issues/14661), where a feature was requested on the Axes violinplot function. The feature allows a user to easily render the quartiles in a violinplot if desired.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Perhaps rather add `showquantiles` (e.g. =[0.25, 0.75]) for quartiles) so that one doesn't have to go through this once again if someone asks for support for deciles?
(Obviously one may need to decide how things would interact with showmedians...)

**Comment by JAbrokwah** [comment]
Thanks for your prompt reply! 
So you're proposing instead to implement a `showquantiles` parameter, similar to the `quantiles` parameter that currently exists ?

**Comment by tacaswell** [comment]
I am not sure that this is what the user in #16997 was asking for (what did they mean by 'box' in the title?).  Further, I think that if this _is_ the requested functionality it already exists by passing  `ax.violin(..., quantile=[0.25, 0.5 0.75])`.   The median is defendably special, but I don't think we need flags for every other quantile variant.

----

I am not a statistician, so I consulted wikipedia (https://en.wikipedia.org/wiki/Quantile).  My understanding is that 'quartile' is a specific version of 'quantile' which divides the probability into 4.

**Comment by anntzer** [comment]
I didn't check if this was already achievable; if so then yes we shouldn't add another way to do it.
Quantile just matches the name of np.quantile.

**Comment by JAbrokwah** [comment]
Thank you both for your input! 

@tacaswell I think the "box" in the title referred to how quartiles are easily displayed in the box plots. 
As per your comment [here](https://github.com/matplotlib/matplotlib/issues/14661#issuecomment-507043852), we were able to extend these lines to the end of the violin, whereas the `quantiles` all extend to an arbitary length.

I do agree with you all though that inserting [0.25, 0.75] into quantiles provides a similar solution.

**Comment by JAbrokwah** [comment]
Hi all, hope this finds you well!
Are there any suggested next steps for this issue?

**Comment by timhoffm** [comment]
Modified https://matplotlib.org/devdocs/gallery/statistics/customized_violin.html by
~~~
ax1.violinplot(data, quantiles=[[0.25, 0.75]]*4)
~~~
yields
grafik

So:
- The basic functionality is available.

But:
- You have to pass a set of quantiles for every violin. We should accept a single list, which would apply to all violins. This is a general usability issue, which just shows more if we decide `quantiles` is enough.
- The quartiles, or more precisely the IQR = 25%-75% range are a special measure. - This is the extent of the box in box plots. One might want to mark that. However, I don't know if it's used a lot in violinplots. For box plots it illustrates a characteristic width of the distribution, but violins already illustrate the distribution.

I quickly searched google and hardly found any violins with quartiles.

The way forward is to collect example usages and convince us that it's worth adding such a parameter and that `quantiles=[0.25, 0.75]` is not sufficient.

Also note that seaborn plots quartiles: https://seaborn.pydata.org/examples/grouped_violinplots.html
On the one hand, that could mean, we leave complex adaptions of violins to specialized downstream libraries. On the other hand, we might coordinate the implementation with seaborn.

Attn @mwaskom do you have an opinion on this topic?

**Comment by JAbrokwah** [comment]
@timhoffm Thank you for your input!

I think one of the main advantages of the violin plot is that it shows a lot more information compared to a box plot, including everything a box plot shows + the distribution of the data. 

image

- First Graph: `quantiles=[[0.2, 0.25, 0.3, 0.4, 0.5, 0.73, 0.75, 0.76]]*6, showquartiles=False`
- Second Graph: `quantiles=[[0.2, 0.3, 0.4, 0.73, 0.76]]*6, showquartiles=True`

From the picture above, I think it's clear that it helps to have a distinction between the quartiles and any other quantiles, to provide a smoother reading experience as well. And since we are proposing a parameter, it's easy to toggle on and off to the user's needs.

I also like this article: [Common Violin Plot Options](https://chartio.com/learn/charts/violin-plot-complete-guide/#common-violin-plot-options), which encourages using quartile lines to reduce visual noise compared to placing a box plot in the violin.

**Comment by tacaswell** [comment]
I have concerns that this functionality is not going to be flexible enough and is painting us into a bit of a corner.   I suspect the first thing people are going to want is the ability for more finer control of the style of the quartile lines which if it is controlled by a bool I don't see a clean way to extend the API to allow for that.

I think @timhoffm has a good point that we really should broadcast the quantiles to _all_ of the violins if it is clear we can do so.  I think that would be a good and uncontroversial API extension.

A slightly more controversial API extension would be to allow `quantile` to take the strings `{'quartile', 'quintile', ...}`.

I also agree that the quantile bars extending all the way out to the edge of the violin looks a lot better.  I think adding a way to control the length of the quantile bars would be another uncontroversial stand-alone API extension (as an implementation detail, using a clipping path  of the violin may be an easier method than computing where the lines should end in dataspace).  Similarly, there should be a way to control the aesthetics of the quantile lines (line width, style, etc).

While the example does show that if you the user is trying to show multiple sets of quantiles at the same time having a special quartile flag does make it easier to see, however this raises the question of this is actually something people who use violin plots do?  If it is, then this suggests to me that we need another low-level function (like `violin`) which is only responsible for drawing the quantile lines.  The API for allowing the user to pass in multiple sets of style and locations is likely to get messy, it may be simpler to ask the user who needs 3 sets of quantiles drawn with different styles to call `violin_quantiles` 3 times.

**Comment by mwaskom** [comment]
> While the example does show that if you the user is trying to show multiple sets of quantiles at the same time having a special quartile flag does make it easier to see, however this raises the question of this is actually something people who use violin plots do?

I’ve never wanted to do this, nor have I ever gotten it as a seaborn feature request. One situation I could imagine it being useful would be if you want to show the quartiles extended the width of the violin while also representing tail quantiles that might be difficult to see when drawn that way. But in general, I don’t think there’s a good reason to represent sets of quintiles differently.

**Comment by phobson** [comment]
@JAbrokwah My name is Paul. I'm going to take on shepherding this through to the point where it can be merged. I'm still processing the discussion that has already happened and the changes that are proposed. I'll comment here with my thoughts later today (I'm on US/Pacific time). Feel free to @-me with any questions.

**Comment by JAbrokwah** [comment]
@phobson Pleasure to meet you, Paul! I'm looking forward to working with you.

**Comment by JAbrokwah** [comment]
@phobson Hope you are doing well. Have you been able to take a look at the issue?

**Comment by jklymak** [comment]
This PR seeks to special-case quartiles with the argument that someone may want to have quartiles *and* other quantiles on the same plot.  If you want to achieve that, you can readily call `violinplot` twice, and then set the facecolor to 'none' or just get plot the quartile lines by hand using `np.percentile` (as shown in  https://matplotlib.org/devdocs/gallery/statistics/customized_violin.htm).  So I think its easy to achieve what this PR implements, and I don't agree that quartiles merit a special case.

**Pull request closed without merging**
