### PR TITLE
[MRG] Begin deprecation of "hold": remove from examples

### PR DESCRIPTION
**Pull request by efiring**
This is a start on addressing #3070.  The first commit should be uncontroversial.  I will look into adding the deprecation warning in subsequent commits.

### CODE REVIEW

**Comment by NelleV** [comment]
Do you want to create one whole big PR or should we review/merge as these come in.
(We could merge this for example).

**Comment by efiring** [comment]
If you want to merge this, go ahead.  I am working on stage 2 right now, but if this is merged I can easily make that another PR.  Stage 2 is not so trivial, so it might require some revisions.

**Comment by efiring** [comment]
This is actually independent of stage 2, so please go ahead and merge it whenever you like.  I will make stage 2 a separate PR right now.

**Comment by NelleV** [comment]
Thanks!

**Pull request merged**
