### PR TITLE
WIP: Testing getting AppVeyor working [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by dopplershift**
It seems that adding this test is when things started going sideways...

### CODE REVIEW

**Comment by tacaswell** [comment]
This makes very little sense to me...

**Comment by dopplershift** [comment]
Two separate successful AppVeyor runs confirm it's related, though.

**Comment by tacaswell** [comment]
Combined with the fact that adding -v to the tests seems to move the segfault to the end and that @cgohlke reports that this is dependent on a python mirco version makes me hope that this is something upstream in how `BytesIO` or `bytes` are handled.

It looks like there is a path (which we don't test?) that saves everything into memory and then embeds the frames.  I think the code path we are testing is writing to a temporary directory.

**Comment by QuLogic** [comment]
It's now the third time around and still passing...

**Pull request closed without merging**
