### PR TITLE
FIX: normalize image data in write_png fast path

### LINKED ISSUE #7373: Regression in imshow
The imshow command in 2.0.0b4 and current master (07adcde) don't export images with colormaps correctly. The colormap is not scaled correctly:

imshow_git

This bug is not present in 1.5.1:

imshow_1 5 1

Some precisions:
* version 1.5.1 from ubuntu 16.04 repository
* git master (07adcde) #installed from source on ubuntu 16.04

Code to reproduce this behavior:

```python
#!/usr/bin/env python2.7
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

print(matplotlib.__version__)

cmap = plt.cm.jet

# coordinates
bbox=20
resolution = 100

xcoords = np.linspace(0, bbox, resolution)
ycoords = np.linspace(-bbox, bbox, 2*resolution)
    
# evaluate
xnb = len(xcoords)
ynb = len(ycoords)
dat = np.zeros((ynb,xnb))
for i in range(xnb):
    for j in range(ynb):
        dat[j][i] = np.sqrt(xcoords[i]**2+ycoords[j]**2)
# export to png
plt.imsave("imshow.png", dat, cmap=cmap, vmin=0, vmax=None)
```

### PR DESCRIPTION
**Pull request by tacaswell**
Closes #7373 

Still thinking about the best way to test this.

### CODE REVIEW

**Comment by NelleV** [comment]
Did the code before produce valid png files?

**Comment by NelleV** [comment]
The answer is no… Should have read the ticket :)

**Comment by tacaswell** [comment]
I did produce a valid (but just wrong).  the color maps treat everything above 1 as 'over' which defaults to mapping to the same color as 1 maps to.

**Comment by NelleV** [comment]
FYI, this looks good to me, but it'd be indeed nice to have a test.

**Comment by efiring** [comment]
It looks fine to me, too; unless someone has an inspiration for a simple test in the interim, I think we should go ahead and merge it as-is on Monday.

**Pull request merged**
