### PR TITLE
ENH: rely on non-rectangular patch paths rather than bboxes for legend auto-placing (fix #9580)

### LINKED ISSUE #9580: Broken legend auto-position with step*-type histograms
### Bug report

**Bug summary**

Automatic placing of legend seems to be not working with histograms of type `step*`. If I am correct, this is a new entry in the long list of current issues with legend ^^.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

hist_types = ('bar', 'barstacked', 'step', 'stepfilled')

fig, axs = plt.subplots(nrows=len(hist_types), num="test")    
for ax, ht in zip(axs.flat, hist_types):
    ax.set_title(ht)
    ax.hist([0] + 5*[9], bins=range(10), label=f"This is a label", histtype=ht)               
    ax.legend(loc="best")

fig.tight_layout()
#fig.savefig(fig.get_label() + ".png")
```

**Actual outcome**

Matplotlib 2.1

test

**Expected outcome**

The same auto-position of the legend on each subplot, i.e. *upper left*, whatever is the histogram style.

**Matplotlib version**

  * Operating system: GNU/Linux (Fedora 26)
  * Matplotlib version: 2.1 from conda (also test “successfully” with master)
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.3 from conda
  * Jupyter version (if applicable): X
  * Other libraries:  X

*FWIW, I tried the above snippet on Matplotlib 1.5.0 and the result is similar.*

**Edit:** tweaked a bit the snippet to be Matplotlib v1.5.x-compliant.

### PR DESCRIPTION
**Pull request by afvincent**
## PR Summary

This PR addresses issue #9580.

### Rationale

Currently, when using the legend auto-placing (NB: default since 2.0), one can get significantly surprising results as 
orig_test
where things are OK with the two upper subplots but the two lower ones are not.

As @anntzer explained in #9580, this is because "step*" histogram types return a single `Polygon` patch while non-"step*" types return a list of `Rectangle` patches. As the legend auto-placing algorithm relies on the *bbox* of the patches, it can significantly overestimates the actual patch area (e.g. as in the case displayed above). **This PR simply suggests to use the path that defines non-rectangular patches instead of their _bbox_ in the legend auto-placing algorithm.** By doing this the algorithm should handle these patches as well (or bad) as any Line2D instances.

At least, it fixes the previous example...
with_cleverer_auto_legend

### Remaining concerns

*NB: the followings points are kind of related actually.*

#### Is it not kind of a nuke to treat every non-rectangular patches as a path?

A less radical change may be to keep the current bbox-based approach for some other patches like `Ellipse`, `Circle`, etc. where the issue stated above is less “severe” and the bbox provide a quite good approximation of the area that is covered by the patch.

#### What about speed?

A [very crude and genuine benchmark](https://github.com/matplotlib/matplotlib/issues/9580#issuecomment-340040536) with a ~ 1000 bin-histogram is given in #9580 and suggest than this change is not likely to be the performance bottleneck of legend. If I am correct, at least for histograms, the new approach should not be really more computationally expensive than the cost of the non-step* histogram types, where the legend bbox is tested against *every* `Rectangle` patch the histogram is made of, isn't it? *However, it may be worth to check that performance does not become a issue for plot with very high amounts of “complex” patches.*

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [?] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

This breaks the previously “incorrect” behavior, and there will be no way to recover it. @tacaswell  *Should I add a proper entry in `api_changes.rst` about it?*

### CODE REVIEW

**Comment by afvincent** [comment]
Tests are ~~coming!~~ here. I tried to use *non* image ones, but to do so, I did not find an more straightforward way than relying on assertions about the *Bboxes* of the legends... If there was something way more clever to do, I am interested.

In both tests, the leftmost subplot is designed to be used as the reference case. FYI, here are the pictures (*not used to perform the tests*) that I used for the two tests:
test_legend_auto4
test_legend_auto5
while formerly the results would have been:
old_behavior_test_legend_auto4
old_behavior_test_legend_auto5

**Comment by afvincent** [comment]
Sorry, I let an F-string from former iterations in the previous commit (3.6+ ❤️)... I fixed it and rebased to squash the one character-commit.

**Review by anntzer — APPROVED** [review]
I think it would be good to add a "the auto-legend locator algorithm has been tweaked" note in the API changes, without necessarily going into the details (so if we change it again before the next release it would be OK to leave it as it is), mostly to leave a breadcrumb if anyone is confused by the change in behavior.

I honestly wouldn't worry about the loss of a clearly less optimal behavior.

**Comment by Kojoley** [comment]
So with this change it could place a legend inside a non-solid bar (if the bar is big enough)?

**Comment by anntzer** [comment]
good point... (but I think being fully in a solid polygon is less annoying that crossing some boundaries)

**Comment by jklymak** [comment]
You could check if the legend was inside any polygons as well though your second test would fail.  But I don’t think most of the time you want the legend inside a drawn polygon.

**Comment by tacaswell** [comment]
How much computation time does this add?  With the 'auto' behavior now the default this is a bit of a hot-path for people updating plots.

**Comment by afvincent** [comment]
@anntzer: I added an entry in `api_changes`, quite minimalistic as you suggested ;).

@tacaswell: I tried to write a benchmark script [here](https://gist.github.com/afvincent/fe0618837d36f668bc885451b17b6bce). It seems to me that the performance impact is barely noticeable. **However TBH I know very little about profiling (and monkey-patching with `mock` too...), so I may have misunderstand the profiler (`pprofile`) output.* Any advice or suggestion are welcome if there were better ways to do this kind of study :sheep:.

The plots used for benchmarking look like:
- **current (former?) algorithm**
benchmark_of_former_method_000

- **suggested (new?) algorithm**
benchmark_of_new_method_000

and they are more intended to give hard time to the `legend` locator than to be representative of real-life plots. (Well, *I* am not used to plot histograms with ~ 5000 bins or plots with 500 `Polygon` patches with ~ 10 edges each.) 

One can see that the behavior with the patch collection is still quite surprising (not to say wrong...), and there is something weird with the coordinate. (I guess, that I missed some `transform` trick.)

@Kojoley and @jklymak: I am still looking into the consequences of this PR in the kind of situations, that you suggested!

**Comment by afvincent** [comment]
Putting back the [WiP] mark, as some legitimate questions about the consequences of this PR have been made and still need to be evaluated.

**Comment by jklymak** [comment]
Personally, I think putting a legend inside an artist is an OK *fallback*, but only if it can't be put outside an artist.   I wonder if a "better" way to go would be doing the old bounding box check first and then, only if that fails for all possible locations, do the intersecting-vertex check.  I think that gets better behaviour but still preserves the spirit of this PR.

**Comment by jklymak** [comment]
Also, looking at the above, I wonder if the check order needs to be changed.  I'd far prefer the legend top center than bottom center in the first test.

**Comment by afvincent** [comment]
@jklymak About the check order: I was having the same thought (but usually @tacaswell is a bit reluctant with API changes just for “aesthetic” reasons 😈 :P). Anyway, other things are broken/weird with the check order, for example "(centered) right" seems to be evaluated twice but not even in successive positions...

For your other idea, that is an interesting idea, I'll try to give it a shot when I have more time (likely not today...).

**Comment by jklymak** [comment]
ping @afvincent I still think this is a great enhancement....

**Comment by afvincent** [comment]
@jklymak I did not forget it ;). It is simply that day-job and other more natural events (Thomas Fire, I am speaking of you 😈) have required a significant share of my attention during the past few weeks... Hopefully I will have more time to take care of this (and the other PRs I opened recently) during the second half of December. If something is really urgent, I do not mind friendly take overs. But I guess that the next “deadline” was pushed to 2.2, which gives a bit of time, does it not?

**Comment by jklymak** [comment]
Yeah, but 2.2 has over 900 issues, so we will be busy ;-)

**Comment by jklymak** [comment]
ping @afvincent real-life bah!  I still think this should go in, maybe after some mods...

**Comment by afvincent** [comment]
@jklymak Hearing you loud and clear, and this PR is still in my on-going work list ;).

I am still trying to find a useful way to benchmark that change (IIRC @tacaswell was a bit worry about that change). Besides, there was also a comment in the thread about the fact that the default order used to explore the possible position might not be the most “intuitive” one (whatever this means :P), but I guess that we might re-evaluate it for 3.0 if that is relevant.

**Comment by jklymak** [comment]
As someone who is slowing down drawing as fast as others are speeding it up, I disagree that perfomance is a huge issue (within reason).  If a user needs performance, they shouldn't  use automatic convenience functions, i.e in this case, they can specify the location kwarg.   But thats just my vote; I appreciate that its also the default, so it has the potential to slow people down by default is an issue.  

My only problem w/ this PR is that I think its possible to theoretically put the legend inside the data curve, and that doesn't appeal.

At the very least, this could get its own value for the location kwarg.  "superauto"?

**Comment by anntzer** [comment]
Would rather not introduce a new location keyword, keep things lean, yada yada. If it's just a 1% slowdown I wouldn't worry to much about it...

**Comment by jklymak** [comment]
ping @afvincent - I think this one was quite close if you have time...

**Comment by jklymak** [comment]
Annual ping @afvincent...

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
@jklymak Can you please make the call if this should go in or be pushed to 3.8?

**Review by jklymak — APPROVED** [review]
This seems like it should work and not be too much of a speed drain (beyond what best already does).  Thanks for rebasing @tacaswell.

**Comment by jklymak** [comment]
I took the liberty of doing a squash merge

**Comment by zhondori** [comment]
It took 5 years to merge this PR 🙂

**Review by ser112r — APPROVED** [review]

**Comment by laduran-envoy** [comment]
> It took 5 years to merge this PR 🙂

It is now famous.
https://www.stacking.dev/?utm_source=stack-comment

**Pull request merged**
