### PR TITLE
Draw a scatter Plot

### PR DESCRIPTION
**Pull request by 26Saksham**
Two scatter plot draw with some property like marker,label,color

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for your work on this @26Saksham , however we already have several examples of using scatter including https://matplotlib.org/stable/plot_types/basic/scatter_plot.html#sphx-glr-plot-types-basic-scatter-plot-py and https://matplotlib.org/stable/gallery/shapes_and_collections/scatter.html#sphx-glr-gallery-shapes-and-collections-scatter-py.

What is this adding that is not already covered on one of those examples?  Can we extend one of those instead of adding a new example?

**Comment by 26Saksham** [comment]
yes, we can extend the example! but I can not see the file of those examples 
my motive is to clear the concept of scatter plot by taking a simple example

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/blob/main/plot_types/basic/scatter_plot.py and https://github.com/matplotlib/matplotlib/blob/main/examples/shapes_and_collections/scatter.py are the source files of those two pages.

**Comment by jklymak** [comment]
I'll close for lack of response.  Thanks for being willing to improve Matplotlib.  Even though we did not take this change, we hope to hear from you again!

**Pull request closed without merging**
