### PR TITLE
On 2.7, run tests on oldest documented supported pytest and pytest-cov.

### PR DESCRIPTION
**Pull request by anntzer**
... to make sure that they are indeed supported.
Basically to avoid issues like like https://github.com/matplotlib/matplotlib/pull/9303.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Added testing of oldest versions of all deps we claim to support.

**Comment by anntzer** [comment]
Well, looks like we actually don't support pytest 3.0 :-) I'll probably just bump the minimum supported version.

**Comment by tacaswell** [comment]
:+1: to bumping pytest version to the minimum we really do support.

**Comment by anntzer** [comment]
It's actually not clear at all from looking at their changelogs which version of pytest introduced the needed functionality...

**Comment by tacaswell** [comment]
Just keep bumping it until it passes? #experimentalist

**Comment by anntzer** [comment]
Looks like I got it now.

**Comment by QuLogic** [comment]
I don't see any error with pytest 3.0? The only failure there is brokenness on our part, which is fixed [here](https://github.com/matplotlib/matplotlib/pull/9304/commits/5417f2d90186d6c6da716b261ce5a01771a2b837) in another PR.

**Comment by anntzer** [comment]
hmmm does travis delete old logs?  can't point to it anymore, but basically it was not liking the skipif in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_backends_interactive.py#L21

**Comment by dstansby** [comment]
Going to merge into master since this has two approvals, and also backport to `2.1.2` (if travis runs fine with this on `2.1.2`)

**Comment by tacaswell** [comment]
backported to v2.1.x as c72d3fcfcba3700677bb59a50dc59547982dd6e7

**Pull request merged**
