### PR TITLE
ENH: if bar has tick_label, override mouse over

### PR DESCRIPTION
**Pull request by tacaswell**
Slowly stumbling to understanding what we need to do to support catagorical axis.

### CODE REVIEW

**Comment by tacaswell** [comment]
appveyor test failure is network issue during install

@mdboom we need to sort out how to share admin on that.

**Comment by mdboom** [comment]
> @mdboom we need to sort out how to share admin on that.

Yeah -- it's non-obvious to me from the Appveyor site itself.

**Comment by QuLogic** [comment]
["Set up your team"](http://www.appveyor.com/docs/team-setup), I guess.

**Comment by mdboom** [comment]
Reading that page, I would expect @tacaswell, who is also an owner of the matplotlib org, to have admin permissions on AppVeyor, but it doesn't seem he does.  I'll probably contact AppVeyor tomorrow with this question.

**Comment by mdboom** [comment]
Looking at `barchart_demo.py`, I only get `x=` in the status bar, not `x=A`, `x=B` etc.  Am I testing the right thing?

**Comment by tacaswell** [comment]
Try: 

```python
import matplotlib.pyplot as plt

plt.bar([1, 2], [.5, .75], tick_label=['bar1', 'bar2'],
           align='center')
```

This relies on the use of the `tick_label` kwarg.

**Comment by tacaswell** [comment]
barchart does not modify well as there are two sets of bars :disappointed:

**Comment by tacaswell** [comment]
`barchart_demo.py` does not modify well under this feature as there are two sets of bars :disappointed:

**Comment by tacaswell** [comment]
@story645 This one might also be of interest to you.

**Comment by jklymak** [comment]
This seems lost in the mists of time given categorical support is now added.  Feel free to re-open if I'm mistaken!

**Pull request closed without merging**
