### PR TITLE
Rotate markers in Scatter plot

### PR DESCRIPTION
**Pull request by mgoacolou**
This a re-summit of the #2432

Make possible to give a scalar or an array for rotate markers. This is usefull for representing for example Speed, Type, Direction of mobile targets.

### CODE REVIEW

**Comment by tacaswell** [comment]
@mgoacolou any interest in continuing to work on this?

`RegularPolyCollection` already has a `rotation` param.  Probably should be consistent with that naming.

**Comment by mgoacolou** [comment]
@tacaswell Hi, I am now more confident with git now. I'll take a look this week on this.

**Comment by flying-sheep** [comment]
oh nice, definitely looking forward to this?

so am i correct that after this is in, i can e.g. do:

```py
df = pd.DataFrame({X: ..., Y: ..., C: ['Foo', 'Bar', ...]})
marker_map = {'Foo': 'o', 'Bar': 'x'}

plot(df.X, df.Y, marker=[marker_map[c] for c in df.C])
```

**Comment by tacaswell** [comment]
No, this is the other meaning of rotate as in 'change the orientation of the marker'.  Basically quiver, but with any marker not just arrows.

There are deep performance related issue that `plot` has exactly one marker.  I would do what you want as

```python

for k, _df in df.group_by('C'):
    ax.plot(_df,X, _df.Y, **style_map[k])
```

**Comment by flying-sheep** [comment]
is there a more ggplot-like interface to matplotlib? i.e. where you give a DataFram and column names to `x`, `y`, `marker`, `c`, and so on and it does *the right thing*™ (including legends)?

seaborn just has its own high-level plots, and pandas’ DataFrame.plot only allows specifying x and y in this way.

i basically want to do: `scatter('Height', 'Weight', c='Age', marker='Gender')`, and it uses the color cycle for categorical variables and the colormap for continuous ones.

**Comment by WeatherGod** [comment]
We are working towards supporting a more robust API like that. You can get
partly there right now by passing the dataframe as the "data" argument and
use the string names for the x and y arguments. I don't think we support
the color and marker arguments yet, though.

**Comment by flying-sheep** [comment]
currently, mpl works on a “series-based” level, which imho makes no sense for multidimensional data: you can have one dimension represented by shape, the other by color, the third by size, and two more by x/y position. this results in an exponential number of series.

therefore to make sense, your API must deviate from the previous model, and simply track 1. each point individually and 2. each represented feature via legend (marker shape, discrete color), colorbar (continuous color), “volume slider triangle” or axis label (x/y position).

like this, but using an [isosceles trapezoid](https://en.wikipedia.org/wiki/Isosceles_trapezoid) as “colorbar for size”:

**Comment by tacaswell** [comment]
color and size should work with scatter + `data`, but not marker.

The pandas/table/dataframe/R view of data is not universal or fundamental where as vectors / arrays of number are, hence that is what the core of mpl targets and will continue to target.

There is definitely interest from many parties for there to a pandas-aware domain-specific plotting library that lives under the matplotlib gh umbrella organization that _can_ require pandas and do these 'magic' things.  The only hold up is developer time.  @flying-sheep You have any interest in leading this effort?

That said, `scatter` creates a `PathCollection` and it _should_ be pretty easy to extend it to take a vector of shapes instead of broadcasting a single shape.

**Comment by flying-sheep** [comment]
i don’t know if i’m suited, but i’d definitely like to chime in wherever discussion is happening regarding the `data=` API.

regarding an universal interface, i disagree: the [grammar of graphics](http://www.springer.com/us/book/9780387245447) is a deconstruction/analysis of the way data visualization happens. and those rules *do* directly translate into a data frame structure: a heterogeneous collection of feature columns that each carry one entry for each sample.

by mapping those feature columns onto graphical features, we get all possible permutations of visualizations.

**Comment by tacaswell** [comment]
The `data` kwarg API shipped with v1.5.0.

**Comment by flying-sheep** [comment]
ah, OK, so this ship has sailed then. damn.

i submitted #6214 for further discussion

**Comment by WeatherGod** [comment]
I am not sure what you mean by "this ship has sailed". All we implemented
was a generic way to *access* data within a dataframe or other similar
objects, and a minimal usage. I don't see any limitations to extending the
syntax, but that'll have to be done judiciously, like how this first round
of the API was done. There are a few technical improvements that will be
needed (having multiple norms, be able to modify more properties, etc), but
we have been wanting to implement them for awhile now.

**Comment by jklymak** [comment]
... I'm going to close this as abandoned.  I'm also not aware that anyone has asked for this functionality for quite a while, and while it looks cool its a significant complication to the code...  Feel free to re-open or ask to have it re-opened if I'm closing in error.

**Pull request closed without merging**
