### PR TITLE
Fix bug in `Axes.bar_label(label_type='center')` for non-linear scales.

### LINKED ISSUE #23688: [Bug]: `Axes.bar_label()` on log scale does not center the label.
### Bug summary

When plotting on a log scale, if you pass `label_type='center'` to `Axes.bar_label()` the resulting labels are not centered in the bar, since the labels are being centered using the original base 10 scale.

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
ax.bar_label(bar_container, label_type='center')
```

### Actual outcome

Screen Shot 2022-08-20 at 6 07 03 PM

### Expected outcome

I was expecting the labels to be in the center of the bar.

### Additional information

The label should be placed using figure coordinates rather than data coordinates. I'm not sure how to get that information from the rectangles though.

### Operating system

M1 Mac

### Matplotlib Version

main branch

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

git checkout

### PR DESCRIPTION
**Pull request by stefmolin**
## PR Summary
Fixes #23688

Incorporated @anntzer's [solution](https://github.com/matplotlib/matplotlib/issues/23688#issuecomment-1221603145) from the issue into the `Axes.bar_label()` method.

---

Example using a log scale:
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
ax.set_xscale('log')
ax.set_xlim(1, None)
ax.bar_label(bar_container, label_type='center')
```

Current output:
Screen Shot 2022-08-20 at 6 07 03 PM

Output with this change:
Screen Shot 2022-08-21 at 7 08 47 PM

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by stefmolin** [comment]
I'm not sure what would be the best way to test this. We could check that the label's `xy` is `(0.5, 0.5)`, but that doesn't seem too robust; does this need an image test?

**Review by tacaswell — APPROVED** [review]

**Comment by stefmolin** [comment]
> Yes, I believe that an image test is good here.

@oscargus - Can you walk me through how to do that?

**Comment by timhoffm** [comment]
See https://matplotlib.org/devdocs/devel/testing.html#writing-an-image-comparison-test for a basic introduction. If you need more help, please ask.

**Comment by oscargus** [comment]
Just in case (this probably won't work directly):

``` python
@image_comparison(["centered_bar_label_nonlinear.png"])
def test_centered_bar_label_nonlinear()
    fig, ax = plt.subplots()
    bar_container = ax.barh(['c', 'b', 'a'], [1_000, 5_000, 7_000])
    ax.set_xscale('log')
    ax.set_xlim(1, None)
    ax.bar_label(bar_container, label_type='center')
    ax.set_axis_off()
```
You will on the first local run get a failure and a file `result_images/test_axes/centered_bar_label_nonlinear.png` (if you put it in `test_axes.py`) which should be copied to `baseline_images/test_axes` and then everything should work.

I sometimes reduce the image size to get smaller figure sizes. I think that can probably be done here without losing anything.

**Comment by tacaswell** [comment]
To add more opinions, an svg might make sense here (not sensitive to the freetype version issue but is sensitive to text placement changes).

**Comment by stefmolin** [comment]
Thanks all! I'll look into it.

**Comment by timhoffm** [comment]
To add more options: If we don't want an image comparison (for size, font glitch or whatever reasons) IMHO it would already be sufficient to take the example from the original post and check that the texts are anchored on the left half of the figure (i.e. transform the coordinates to figure coordinates and check that x < 0.5).

Going one step further, one could also transform the bar limits to figure coordinates and then check that the text is centered between the bar limits in figure coordinates (which is the exact definition of what we expect).

**Comment by stefmolin** [comment]
I added an image test with a PNG file since it says it can't do SVG or PDF comparison tests on my system. Let me know if we still need an SVG test, and if so, how to generate the file in the first place since it just skips the test.

Screen Shot 2022-09-05 at 6 55 09 PM

**Comment by stefmolin** [comment]
> I added an image test with a PNG file since it says it can't do SVG or PDF comparison tests on my system. Let me know if we still need an SVG test, and if so, how to generate the file in the first place since it just skips the test.
> 
> Screen Shot 2022-09-05 at 6 55 09 PM

We ended up talking about this in the new contributor's meeting. I might be missing some dependencies for the image test. I will look into it and report back.

**Comment by timhoffm** [comment]
> I might be missing some dependencies for the image test. 

Might be Inkscape.

See also https://matplotlib.org/devdocs/devel/dependencies.html#dependencies-for-testing-matplotlib.

**Comment by stefmolin** [comment]
It was Inkscape. I see there was some new logic added to make it easier to understand what is going on :smile:

https://github.com/matplotlib/matplotlib/blob/1fe8792a7648044dc917a9cc9a6ac4e7275b7491/lib/matplotlib/testing/decorators.py#L266-L272

**Review by greglucas — APPROVED** [review]
I'm glad you were able to get that to work, @stefmolin. This works great on window resizes too which is nice :)

**Pull request merged**
