### PR TITLE
Fixing the issue where right column and top row generate wrong stream…

### PR DESCRIPTION
**Pull request by pmackenz**
The interpolation function in streamplot was duplicating the second to last right data column instead of using the rightmost column.  Same issue for topmost row being replaced by the row just below the top.

## PR Summary
This was indeed an indexing error.  Fixing the index solved the issue.

Here the corrected images (same code as in the bug report, but now generating correct figures with streamlines as tangent to velocity vectors):
streamplotissue1

streamplotissue2

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
xref: This supposedly fixes #11452

**Comment by jklymak** [comment]
Thanks a lot @pmackenz !  You were right, it *was* an indexing issue.  Thats great!

This fails all the image tests that used streamplot because now the streamplots are corrected.  Someone will have to generate the new image comparison files and commit them as part of this PR before it can go in.  Are you up to try?  If not, I'm happy to help by pushing to your commit.  

https://matplotlib.org/devel/testing.html

**Comment by jklymak** [comment]
Ooookay, I think I did that right.  Note I pushed onto yout matplotlib/master branch which is what you made this commit on.  In the future, better to create a new branch in your repo rather than use "master"

**Comment by jklymak** [comment]
Reviewers, not that I updated the style and removed the text from all the tests...

**Comment by dopplershift** [comment]
Anyone else not getting the option to view image diffs?

**Comment by jklymak** [comment]
fixing_the_issue_where_right_column_and_top_row_generate_wrong_stream _by_pmackenz_ _pull_request__11455_ _matplotlib_matplotlib

**Comment by dopplershift** [comment]
I swear that wasn't there earlier. 🐑

**Comment by jklymak** [comment]
Grrrr, I can't reproduce the two remaining image failures locally.

**Comment by jklymak** [comment]
Can anyone closer to the Travis build reproduce the error in `pytest --pyargs matplotlib.tests.test_transforms::test_pre_transform_plotting`?  It runs fine on both of my machines, and is the only test failing, so I don't think its a setup problem.

**Comment by jklymak** [comment]
We may want to investigate what was meant here...

https://github.com/matplotlib/matplotlib/pull/664/commits/5632418b2e7b8cbc3347d2a01e1e9cbb6a70da51

**Comment by jklymak** [comment]
OK thin I fixed it.  A bit annoying.  Running
```
py.test -v --pep8 --pyargs matplotlib.tests.test_transforms::test_pre_transform_plotting
```
gives a warning:
```
/Users/jklymak/matplotlib/lib/matplotlib/testing/conftest.py:11: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```
and I couldn't get the images to match.

Calling as 

```
py.test -v lib/matplotlib/tests/test_transforms.py
```
I don't get that warning and the images come out different.

<details>
 <p>
 <summary>Full warning stack</summary>

```
$ py.test -v --pep8 --pyargs matplotlib.tests.test_transforms::test_pre_transform_plotting

============================================ test session starts ============================================
platform darwin -- Python 3.6.3, pytest-3.3.1, py-1.5.2, pluggy-0.6.0 -- /Users/jklymak/anaconda3/envs/matplotlibdev/bin/python
cachedir: .cache
rootdir: /Users/jklymak/matplotlib, inifile: pytest.ini
plugins: pep8-1.0.6
/Users/jklymak/matplotlib/lib/matplotlib/testing/decorators.py:407: MatplotlibDeprecationWarning: The ImageComparisonTest class was deprecated in Matplotlib 3.0 and will be removed in 3.2.
  savefig_kwargs=savefig_kwarg, style=style)
/Users/jklymak/matplotlib/lib/matplotlib/testing/conftest.py:11: UserWarning:
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'Qt5Agg' by the following code:
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/bin/py.test", line 6, in <module>
    sys.exit(py.test.main())
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/config.py", line 59, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 134, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 103, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 140, in _main
    config.hook.pytest_collection(session=session)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 150, in pytest_collection
    return session.perform_collect()
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 640, in perform_collect
    items = self._perform_collect(args, genitems)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 662, in _perform_collect
    rep = collect_one_node(self)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/runner.py", line 502, in collect_one_node
    rep = ihook.pytest_make_collect_report(collector=collector)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/runner.py", line 369, in pytest_make_collect_report
    'collect')
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/runner.py", line 189, in __init__
    self.result = func()
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/runner.py", line 368, in <lambda>
    lambda: list(collector.collect()),
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 686, in collect
    for x in self._collect(arg):
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 696, in _collect
    names = self._parsearg(arg)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 753, in _parsearg
    parts[0] = self._tryconvertpyarg(parts[0])
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/main.py", line 733, in _tryconvertpyarg
    loader = pkgutil.find_loader(x)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/pkgutil.py", line 490, in find_loader
    spec = importlib.util.find_spec(fullname)
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/Users/jklymak/anaconda3/envs/matplotlibdev/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/jklymak/matplotlib/lib/matplotlib/tests/test_transforms.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 68, in <module>
    from matplotlib.backends import pylab_setup
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/__init__.py", line 12, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('agg')
```
</p>
</details>

**Comment by jklymak** [comment]
Milestoning for 3.0 - not a reversion, but certainly a bug that should be fixed sooner than later.  I can't review because I pushed the images...

**Comment by pmackenz** [comment]
Wow, never expected to cause that much trouble with by two-character bug fix (really, just 2 characters).  I very much appreciate how everybody is helping out here.  This was my first micro-contribution aside from bug reports and I feel I owe everyone here!  THANKS.

**Comment by ImportanceOfBeingErnest** [comment]
I guess the open question is (as [mentionned above](https://github.com/matplotlib/matplotlib/pull/11455#issuecomment-398274268)) still why that `2` instead of `1` got introduced in the first place.

**Comment by pmackenz** [comment]
Might have been a workaround for a different (now historic) bug.  Workaround turned bug once the original issue was resolved ... ?

**Comment by timhoffm** [comment]
The code was introduced in https://github.com/matplotlib/matplotlib/commit/5632418b2e7b8cbc3347d2a01e1e9cbb6a70da51 as part of #664. That was quite a large merge and might really have got in without thoroughly thinking on the index.

The proposed change `Nx - 2` -> `Nx -1` seems correct. However, I think the context of the code itself is flawed, or at least unnecessarily complex:

~~~
def interpgrid(a, xi, yi):
    """Fast 2D, linear interpolation on an integer grid"""

    Ny, Nx = np.shape(a)
    if isinstance(xi, np.ndarray):
        x = xi.astype(int)
        y = yi.astype(int)
        # Check that xn, yn don't exceed max index
        xn = np.clip(x + 1, 0, Nx - 1)
        yn = np.clip(y + 1, 0, Ny - 1)
    else:
        x = int(xi)
        y = int(yi)
        # conditional is faster than clipping for integers
        if x == (Nx - 2):
            xn = x
        else:
            xn = x + 1
        if y == (Ny - 2):
            yn = y
        else:
            yn = y + 1

    ...
~~~
Basically, what this does is for `xi` (which possibly may be a float or a np.array):

- convert xi to integer -> x
- create `xn = x + 1` but make sure, it's not larger than the size of `a` (Nx-1)`

As far as I can see, the else clause is only relevant for single numbers.

- Special handling single numbers seems unnecessary to me, you could just `x = np.asarray(xi, dtype=int)` and discard the whole else branch.
- The comment "conditional is faster than clipping for integers" is hinting at an attempt of unnecessary optimization: Performance on single integers can only be a concern if you're calling that function many times. However then, you should call it once with an array instead.
- Additionally, the two branches behave differently. While the if-branch clips, the else-branch just doesn't do the +1 shift for a single number. This is only the same as long as x is in the range (-1, Nx-1). Maybe the internal calls ensure that, but it's a fragile API.

I propose to replace the whole if-else block by

~~~
x = np.asarray(xi, dtype=int)
y = np.asarray(yi, dtype=int)
# Check that xn, yn don't exceed max index
xn = np.clip(x + 1, 0, Nx - 1)
yn = np.clip(y + 1, 0, Ny - 1)
~~~

**Comment by jklymak** [comment]
@dstansby done

@timhoffm  I agree the code is suboptimal as it stands.  OTOH, lets get this in, and then we can fix the underlying algorithm

**Comment by dstansby** [comment]
Does anyone have any thoughts on backporting to `2.2.x`? It fixes a pretty major bug (see the above issue)

**Comment by dstansby** [comment]
@meeseekesbot backport to v2.2.x

**Comment by QuLogic** [comment]
It is a sort of bugfix, but it does cause downstream effects, e.g., https://github.com/SciTools/cartopy/pull/1130/commits/1bf2c97d65fc00f6794c89afc7c31b1d7a85e373 So if we do backport, it'd be good to know to get that condition right.

**Comment by jklymak** [comment]
@meeseeksdev backport to v2.2.x

**Pull request merged**
