### PR TITLE
Added linear scaling test to Hexbin marginals

### LINKED ISSUE #21165: Hexbin marginals need a test for linear scaling
Looks like there is no linear scale marginals=True?  Can we add that test?

_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/pull/21039#discussion_r711927679_

### PR DESCRIPTION
**Pull request by j-bowhay**
## PR Summary
Added test for hexbin marginals that uses a linear scale. Closes #21165 
## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by timhoffm — DISMISSED** [review]
I block this because there is a bug with the gridsize parameter #21349 and we want that fixed before adding a reference image.

Anybody can dismiss after #21349 is fixed and a new reference image is push (ideally with a squash) - Otherwise, whoever discards this should squash-merge the PR.

**Comment by jklymak** [comment]
lets move to draft until we sort out.  @j-bowhay please ping us if the issue with hex bin does not get resolved soon.

**Review by dstansby — CHANGES_REQUESTED** [review]
This definitely needs updating or adopting in it's current state - see the above comment!

**Comment by lucasricci** [comment]
Hey @j-bowhay, are you still working in this PR? Because it is been inactive for a long time. Hope I am not disturbing you.

**Comment by j-bowhay** [comment]
Hi @lucasricci this was blocked on #21349 by @timhoffm so I have not made the requested changes yet. I see there has been no progress on this issue yet. I am happy to finish the pr once the issue is fixed or if it is decided to add these test with the bug present and then update later.

**Comment by lucasricci** [comment]
@j-bowhay Oh I see, thanks

**Comment by timhoffm** [comment]
@j-bowhay thanks for the ping, and thanks for the PR!

**Pull request merged**
