### PR TITLE
Use tempfile.mkdtemp for animation.FileMovieWriter.

### PR DESCRIPTION
**Pull request by anntzer**
Currently, `animation.FileMovieWriter` (e.g. `FFMpegFileWriter`)
creates temporaries in the current folder, without even checking
whether the file existed before.  This is obviously risky (e.g., create
a file named `_tmp0000000.png` in the current folder before running
`moviewriter.py` from the docs examples and it will be overwritten.
Moveover, temporaries are not cleaned up if an exception is raised
(e.g., KeyboardInterrupt).

This is relatively easy to fix using `tempfile.mkdtemp`, although I
had to modify `finish` so that it doesn't call `cleanup` by itself
(obviously, this can be fixed by keeping a `cleaned_up` attribute
but it feels like a minor API change is preferable; moreover the
context-manager API stays the same).

Only basic, manual testing done.

### CODE REVIEW

**Comment by tacaswell** [comment]
@anntzer Any interest in revisiting this PR?

**Comment by anntzer** [comment]
I don't really care anymore, as I have my own wrapper now: https://gist.github.com/anntzer/e0186a16b392b4abf3e1
Anyone who wants to work on it is welcome to copy parts of it.

Note that this directly takes `QImage` as input, but it's really just passing the RGBA bytes to the pipe; from matplotlib's POV it's probably just as good to use `fig.canvas.print_raw`.  http://stackoverflow.com/questions/5391026/matplotlib-alternatives-to-savefig-to-improve-performance-when-saving-into-a compared saving raw bytes to saving to png and found a twofold improvement in performance (and likewise the decoding on ffmpeg's side is probably faster too), so it's probably also worth taking this into account.

**Comment by tacaswell** [comment]
bump on this.

**Comment by anntzer** [comment]
Honestly I think the whole thing should just be rewritten to pipe the RGBA bytes to ffmpeg's (or whatever process is used) stdin.

**Comment by tacaswell** [comment]
That is what http://matplotlib.org/api/animation_api.html#matplotlib.animation.FFMpegWriter and friends do.

I think the file-base version exist either for back-compatibility or some use case where writing to stdin does not work.

**Comment by anntzer** [comment]
Fair enough.  Still not enough to convince me to fix the rebase :-)

**Comment by tacaswell** [comment]
Closing this as the rebase has become pretty nasty due to other changes to `animation.py`.

**Pull request closed without merging**
