### PR TITLE
Rename `rcParams['savefig.directory']` to `rcParams['gui.save.directory']` fix #20790

### LINKED ISSUE #20790: rename`rcParams['savefig.directory']` to `rcParams['gui.save.directory']`
### Bug summary

Figures saved via the `savefig` method are not saved relative to the `rcParams['savefig.directory']` path. Looking at the source code, it seems that this path is only prepended to the filename if the save request came via the interactive toolbar. Not sure if this is done intentionally, but it seems to me that the `savefig.directory` should always be respected.  

In the example below I use the home directory `~`, but the same behaviour occurs for any other existing directory.

### Code for reproduction

```python
from pathlib import Path
from matplotlib import rc, pyplot as plt


# All figures to go into home
rc('savefig', directory='~')

fig, ax = plt.subplots()
fig.savefig('test.png')

(Path.home() / 'test.png').exists() # False => Not saved in rcParams['savefig.directory']
(Path('.') / 'test.png').exists() # True => Saved in current working directory
```

### Actual outcome

The figure is saved in the local working directory. 

### Expected outcome

If `rcParams['savefig.directory']` has been set, and `savefig` is given a filename (not a full path), the figure should be saved relative to `savefig.directory`.

### Operating system

Ubuntu

### Matplotlib Version

3.3.4

### Matplotlib Backend

Qt5Agg

### Python version

3.8.10

### Jupyter version

NA

### Other libraries

_No response_

### Installation

pip

### Conda channel

_No response_

### PR DESCRIPTION
**Pull request by Kislovskiy**
## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [N/A] New features are documented, with examples if plot related.
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by Kislovskiy** [comment]
@tacaswell I added `'savefig.directory'` to `_deprecated_ignore_map`, however, I couldn't find any usage of that method in the past: would it be OK to keep the parameter in `_deprecated_ignore_map`, or should I add it to `_deprecated_map` instead?

**Comment by Kislovskiy** [comment]
@tacaswell Could you take a look when you have time?

**Comment by jklymak** [comment]
I'm going to close this as I agree with @anntzer, and the PR is stalled anyway.  However, feel free to request a re-open.

**Comment by QuLogic** [comment]
Then a proper decision should be made on the original issue.

**Comment by tacaswell** [comment]
Thank you for your work @Kislovskiy however we have decided that this is not a change we want to make after all.  Hopefully we will hear from you again.

**Pull request closed without merging**
