### PR TITLE
Make separator configurable in EngFormatter

### PR DESCRIPTION
**Pull request by HDembinski**
## PR Summary

Some people prefer to not have a space between the number and the engineering prefix. Plotly does not use a space, this saves value space on an axis. This patch makes the separator configurable.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by afvincent** [comment]
@HDembinski Some duplicate might exist: #6542 (even if it has kind of fallen through the cracks for the moment :/)

**Comment by HDembinski** [comment]
@afvincent You are right, it is a duplicate. I will close this PR, since yours provides the same functionality and you also improved the tests. If you need help with your PR, let me know!

**Comment by tacaswell** [comment]
@HDembinski Thank you for your work (even if it is a duplicate!).  If you have time, a review of #6542 from you would be appreciated.  Both to verify that it actually addresses your need and given that you just did this work, you probably currently have a better understanding the this section of the code than most of the core devs (certainly better than I do right now!).

**Comment by HDembinski** [comment]
@tacaswell Thank you for the kind words. :) I went over to #6542 and looked at the code and the existing reviews. All that looked fine. I will try to merge the branch onto my computer and have a closer look.

**Pull request closed without merging**
