### PR TITLE
Add Yellowbrick to third party packages

### PR DESCRIPTION
**Pull request by bbengfort**
## PR Summary

Adds a blurb and link about Yellowbrick to the documentation along with our README gallery image that shows some of the visualizers that Yellowbrick produces for classification, regression, and clustering.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by bbengfort** [comment]
Sure - I've resized and compressed the image.

**Comment by tacaswell** [comment]
@meeseeksdev backport to v3.1.x

**Comment by QuLogic** [comment]
> If someone else merges, please squash so that the original large image is squashed out.

@jklymak *cough* please be careful of this request in the future.

**Comment by jklymak** [comment]
Ooops, sorry, I'll attempt to revert and fix...

**Comment by QuLogic** [comment]
No, the commits are public now. They could be removed but it's not nice to any forks and not really worth the effort in this case.

**Comment by jklymak** [comment]
I promise to read full sentences in the future

**Pull request merged**
