### PR TITLE
DOC: Fix version switcher links to documentation

### LINKED ISSUE #23193: [Doc]: Version switcher links broken
### Documentation Link

 https://matplotlib.org/devdocs/

### Problem

The version switcher now recognizes the entries from `switcher.json`: 

image

However, the entry links do not work.

### Suggested improvement

_No response_

### PR DESCRIPTION
**Pull request by melissawm**
## PR Summary

Closes #23193 by adding a URL field to the version switcher json file. This is [new in pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions)

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by melissawm** [comment]
I'm not sure I understand the CI failures, unfortunately.

**Comment by greglucas** [comment]
It looks like the pydata theme also deprecated the logo link and replaced it with a logo dictionary that can be filled now.
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html?highlight=logo#customize-logo-link

So, I think this needs to be updated to that new format:
https://github.com/matplotlib/matplotlib/blob/c7defd7e7bce1ad17bb8df2da91763ffdcbf64b6/doc/conf.py#L332

**Comment by tacaswell** [comment]
I think the other change is https://github.com/pydata/pydata-sphinx-theme/pull/698  I'll push a commit.


Do we need to pin pydata-sphinx very far forward (or back)?  On one hand it is a pure-python doc-build-only dependency, on the other adding / changing dependencies on the docs builds can still be harsh on our down-stream packagers.

**Comment by jklymak** [comment]
Looks like we will have to update the CSS, probably in mpl-sphinx-theme to get back the 'C0' section headers. 

Newlook

**Review by timhoffm — APPROVED** [review]

**Comment by melissawm** [comment]
Thanks folks! Let me know if there's any follow up I can pick up.

**Comment by jklymak** [comment]
pydata-sphinx-theme 0.9.0 has some pretty major changes in how css gets handled, most of which are marked as beta.   I'm not sure we should be switching to it just yet.  Probably discuss at https://github.com/matplotlib/mpl-sphinx-theme/issues/32

**Pull request merged**
