### PR TITLE
Filter out inf values in plot_surface

### PR DESCRIPTION
**Pull request by LemonBoy**
## PR summary

Extend the logic introduced by https://github.com/matplotlib/matplotlib/pull/20725 for NaN values to inf values,
avoiding the introduction of infinite vertices in the mesh that wreak
havoc when performing the z-sorting.

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [X] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for your work on this.

If I am understanding the test example correctly, one of the quadrants sets the z value to `inf` which by some mechanism messes with the z-sorting of between the other quadrents:


```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(projection="3d")

x, y = np.mgrid[-2:2:0.1, -2:2:0.1]
z = np.sin(x) ** 2 + np.cos(y) ** 2
z[x.shape[0] // 2 :, x.shape[1] // 2 :] = np.inf

ax.plot_surface(x, y, z, cmap="jet")
ax.view_init(elev=45, azim=145)

```

so

vs what it should look like (a different angle)

so2


I agree something is definitely wrong, but I suspect it may be better to fix this in the code in `Collection3D` that sorts the patchs rather than by dropping all non-finite data on the floor.

There has been a push recently to make the 2D mesh-like methods do a better job of holding onto the shape of the originally passed in data (to make it easier to update x / y / color / ... after the fact).  We have not (to my knowledge) done anything similar with the 3D methods yet, but we may want to go that way eventually.  This also suggests that the right place to filter out the non-finite data is in the sorting step, not in the "what data are we holding" step.

**Comment by LemonBoy** [comment]
> I agree something is definitely wrong, but I suspect it may be better to fix this in the code in Collection3D that sorts the patchs rather than by dropping all non-finite data on the floor.

That was my initial guess too, but the linked issue pointed towards this dataset-cleaning approach.

> We have not (to my knowledge) done anything similar with the 3D methods yet, but we may want to go that way eventually. This also suggests that the right place to filter out the non-finite data is in the sorting step, not in the "what data are we holding" step.

What I am afraid of is the additional complexity of having to filter the dataset whenever it's needed, eg. before the z-sort, before computing the colormap min/max values, etc. However, if the general consensus is to remove the preliminary data filtering I'd be happy to send another patch soon.

**Comment by LemonBoy** [comment]
Friendly ping.

**Comment by timhoffm** [comment]
Fundamentally, I agree with @tacaswell that the Collection should hold all data, and handling of nan and inf should be done in there.

Given that the nan handling was already implemented on the outer level in #20725, it is bearable to extend that logic to include inf values as well. It's an improvement in the sense, that we fix a buggy plot. We'll anyway have to do an API change for the existing code when we want to move nonfinite data handling into the 3D Collections.

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Can this still go to 3.8?

**Pull request merged**
