### PR TITLE
FIX : turn path snapping off on 'o' marker path

### LINKED ISSUE #4421: IPython Notebook: irregular marker edge for 'o'
In the notebook, using `%matplotlib inline`, plotting circle markers (`'o'`) with size of 7 results in a rendering error:

    plt.plot([1,2,3,4], [3,1,2,4], 'o', ms=7)

image

The problem is present also in the png produced by `savefig`.

Changing the marker size to 6 or 8 results in correct rendering.

This rendering issue is very annoying also because the `ms=7` happens to be the default marker size in seaborn. In fact, I reported the bug there first (https://github.com/mwaskom/seaborn/issues/557).

### PR DESCRIPTION
**Pull request by tacaswell**
Set the _snap_threshold for 'o' markers to `np.inf` which
effectively turns it off.

This makes 'o' markers look more circular at all sizes at all dpi.

This change subtly changed several tests.

Closes #4421

### CODE REVIEW

**Comment by tacaswell** [comment]
## this PR
o_fix

## curent-ish master
o_master

This looks slightly different from the image in #4421 at ms=7, but that is because these are saved at 100 dpi, not 72

**Comment by tacaswell** [comment]
@mdboom You last touched this in 6a3cc745d5d124ca6b30e38dc12e98cc24aecb8e,  e0f917690d02f3a976dcac27e4849ce912b0abd0, and 6fe5fa03e8608949cb08a485a4d6adf9247a5ffb.

The commit message on e0f9176 convinced me that turning the snapping off altogether was the right thing to do.

**Comment by mdboom** [comment]
Thanks -- sorry I hadn't squashed it completely earlier.

**Comment by jenshnielsen** [comment]
Looks good to me. Should this be backported?

**Comment by tacaswell** [comment]
I am mildly :-1: on backporting.  It is a subtle API break (even if it is for the better).

**Comment by jenshnielsen** [comment]
Ok, I don't feel strongly either way

**Pull request merged**
