### PR TITLE
BLD: Add Python 3.11 builds to CI

### PR DESCRIPTION
**Pull request by matthewfeickert**
## PR Summary

With [`cibuildwheel` `v2.9.0`](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0), CPython 3.11 wheels are now built (by default) and as NumPy now has CPython 3.11 wheels out as of NumPy v1.23.2, matplotlib can build CPython 3.11 wheels (though as of 2022-08-16 [`contourpy`](https://pypi.org/project/contourpy/) does not have 3.11 wheels yet).

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by matthewfeickert** [comment]
The 3.11 builds are very slow at the moment (and so maybe this shouldn't be merged yet?) given that both `contourpy` and `kiwisolver`

https://github.com/matplotlib/matplotlib/blob/276436aba3f52ab3158efb89212fe31ed45806ed/setup.py#L307-L311

are not pure-Python and so have wheels that need to be built and neither of them have Python 3.11 wheels out as of 2022-08-16 (though they are both in a good position for their next release given https://github.com/contourpy/contourpy/pull/151 and https://github.com/nucleic/kiwi/pull/153).

**Comment by ianthomas23** [comment]
Note that lack of `contourpy` wheels for CPython 3.11 isn't a problem at all. `contourpy` builds and passes tests on the 3 major platforms without any problems. You'll have to build `contourpy` from source but
```
time pip install --no-binary contourpy contourpy
```
in a clean venv takes 25 seconds on my dev machine, and less than 18 seconds if `contourpy` sdist and `numpy` wheel have already been cached. This is significantly less time than it takes to build `matplotlib`.

**Comment by matthewfeickert** [comment]
> Note that lack of `contourpy` wheels for CPython 3.11 isn't a problem at all. `contourpy` builds and passes tests on the 3 major platforms without any problems. You'll have to build `contourpy` from source but
> 
> ```
> time pip install --no-binary contourpy contourpy
> ```
> 
> in a clean venv takes 25 seconds on my dev machine, and less than 18 seconds if `contourpy` sdist and `numpy` wheel have already been cached. This is significantly less time than it takes to build `matplotlib`.

Yup, you're very right and I was just coming back here after testing this myself to comment a similar thing.

```console
$ docker run --rm -ti python:3.11.0rc1-bullseye /bin/bash
root@5b71d1f2c405:/# python -m venv venv && . venv/bin/activate
(venv) root@5b71d1f2c405:/# python -m pip --quiet install --upgrade pip setuptools wheel
(venv) root@5b71d1f2c405:/# time python -m pip install --no-binary contourpy contourpy
Collecting contourpy
  Downloading contourpy-1.0.4.tar.gz (12.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 22.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.16
  Downloading numpy-1.23.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 21.6 MB/s eta 0:00:00
Building wheels for collected packages: contourpy
  Building wheel for contourpy (pyproject.toml) ... done
  Created wheel for contourpy: filename=contourpy-1.0.4-cp311-cp311-linux_x86_64.whl size=254190 sha256=aec204ffc9cef62f736cc0469dcc842636571c6b7dcd9c8a95a85d1f044b4741
  Stored in directory: /root/.cache/pip/wheels/52/10/34/903aecdade518daec5468b58437fb4e2a85b22a9c7b19c82f7
Successfully built contourpy
Installing collected packages: numpy, contourpy
Successfully installed contourpy-1.0.4 numpy-1.23.2

real	0m13.112s
user	0m41.278s
sys	0m1.843s
(venv) root@5b71d1f2c405:/# 
```

So I guess all the time I was seeing last night was coming from the `kiwisolver` build(?) and this PR shouldn't be significantly slower beyond the extra wheel build time.

**Review by tacaswell — APPROVED** [review]

**Review by oscargus — APPROVED** [review]

**Comment by tacaswell** [comment]
Thanks @matthewfeickert !  I must have miss-read the release notes on the cibuildwheel update as I thought we were already doing this :/

**Comment by matthewfeickert** [comment]
> I must have miss-read the release notes on the cibuildwheel update as I thought we were already doing this :/

I think we both did, as I had just seen the [release note](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0) comment

> CPython 3.11 wheels are now built by default - without the CIBW_PRERELEASE_PYTHONS flag. It's time to build and upload these wheels to PyPI! This release includes CPython 3.11.0rc1, which is guaranteed to be ABI compatible with the final release.

and (unreasonably) assumed that things would be extra magically taken care of somehow. Then I noticed that there weren't `cp311` nightly wheels and realized after looking at matplotlib's GHA workflows that as all of the build jobs specify [`CIBW_BUILD`](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip)

https://github.com/matplotlib/matplotlib/blob/9f5c041158024733c68fbc15eaee57cbe97fdab7/.github/workflows/cibuildwheel.yml#L68-L71

that there is never a default and so this needed to get added. This all makes sense to me from a workflow pattern as you want to ensure that you're building the wheels you think you are and so explicitly stating them seems good to my mind. :+1:

**Comment by oscargus** [comment]
Should this be backported to 3.5.3? To enable 3.11 wheels? For example, #23645.

(I do not know how the release build-process works...)

**Comment by tacaswell** [comment]
I'm inclined not, we have historically not gone back and rebuilt wheels after the fact.  If we do 3.5.4 we should re-consider.

**Pull request merged**
