### PR TITLE
Add method for comparing two colors

### PR DESCRIPTION
**Pull request by dstansby**
Colors in Matplotlib can come in many weird and wonderful forms; this allows two colors to be compared.

### CODE REVIEW

**Comment by WeatherGod** [comment]
Will need a what's new entry, won't it?

**Comment by tacaswell** [comment]
:+1: @WeatherGod sorry I missed that.

**Comment by dstansby** [comment]
There might be other bits of the codebase that compare if two colors are equal?

Even if there aren't I think it's a useful user function to have given then many different ways colors can be specified, and it makes it clear in our internal code when we are comparing colors for equality.

Will add a what's new when I get time, or if someone wants to push one to my branch feel free.

**Comment by tacaswell** [comment]
I think this is the first step towards a more consistent color representation at the python layer.

**Comment by jklymak** [comment]
Right - see #9995.  It would prob make sense to have a `color` class that then did all this automagically.

**Comment by WeatherGod** [comment]
Other thing to consider is how this would fold in with traitlets (don't
know where we currently stand on that.)

**Pull request merged**
