### PR TITLE
Soft-deprecate mutation_aspect=None.

### PR DESCRIPTION
**Pull request by anntzer**
mutation_aspect=1 is a synonym that's just simpler and consistent with
other scalar values.

Not really worth a proper deprecation; just changing the defaults in the
signatures and normalizing None to 1 in the getter.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
CI doesn't think it's so simple...

**Comment by anntzer** [comment]
Looks like this exposed another bug, namely `annotate("foo", (.5, .5), xytext=(.4, .4), arrowprops={"arrowstyle": "->", "mutation_scale": 2})` likely never ever worked; one just needs to get rid of a spurious `zip` call.

**Comment by timhoffm** [comment]
Which if?

**Comment by anntzer** [comment]
I wouldn't bother (as usual, unless one shows a real-world case where this is the bottleneck), the cost should typically be negligible compare to the actual transmutation...

**Comment by tacaswell** [comment]
@timhoffm The one at 2889 the determines if we go into "actually do the scaling" code path.

**Pull request merged**
