### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by mamrehn**

### CODE REVIEW

**Comment by WeatherGod** [comment]
Heh... that example still exists? @dopplershift, should we just get rid of this one?

**Comment by dopplershift** [comment]
We probably should just get rid of it--the animation module has better ways to do this.

**Comment by tacaswell** [comment]
Merging this as it corrects an obvious typo.

@WeatherGod @dopplershift If you want to get rid of this example please do so in another PR.

**Comment by tacaswell** [comment]
backported to v2.x as b26a776

@mamrehn Thank you for your contribution!  Documentation and examples are super important to the health of the project.  Hopefully we will hear from you again :tada: .

**Pull request merged**
