### PR TITLE
[BUG] Prevent under the hood downcasting of values

### PR DESCRIPTION
**Pull request by abcnishant007**
I think this behaviour was not intended. Spotted the issue due to a question posted on Stackoverflow https://stackoverflow.com/questions/76195580/when-plotting-autocorrelation-function-plot-getting-ufunctypeerror

When using a list of integers in the `xcorr` function, the following lines:
https://github.com/matplotlib/matplotlib/blob/4bdae2e004b29d075f96a7dbbee918f7dfb13ed1/lib/matplotlib/axes/_axes.py#L2118-L2119

 result in an under-the-hood downcasting to int, and as a result, the following error is thrown: 
```python
  File "---/pythonProject/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 2120, in xcorr
    correls /= np.sqrt(np.dot(x, x) * np.dot(y, y))
TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') 
according to the casting rule ''same_kind''
```
The obvious fix is to remove in-place update and use standard assignment. 

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by abcnishant007** [comment]
Reopened to trigger waiting tests.

**Comment by tacaswell** [comment]
Thank you for working on this.  

I would describe this is more forcing an up-conversion that preventing a down conversion (as it looks like `np.corrolate` is preserving the types passed in) but that is neither here nor there.  The current best work-around for users is to do `np.asarray(data, dtype=float)` before passing it in to ensure that we are working with floats all the way through.


Could you add a simple test that passing in a list of ints does not raise?

**Comment by abcnishant007** [comment]
Sure thing, I will add the test case today. 

Thanks for the review!

**Comment by abcnishant007** [comment]
@tacaswel I wrote the test, but in one of the CI tests, it compares against the original main and fails. Am I missing something trivial here? For your reference, the permalink of the error is reproduced below:

https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=33482&view=logs&j=aa39683c-d595-5f65-0b25-75adb2a2e3f3&t=2551f7a6-26d7-58a2-495a-78f1a540557c&l=292

**Comment by tacaswell** [comment]
```
        if normed:
>           correls = correls / np.sqrt(np.dot(x, x) * np.dot(y, y))
E           RuntimeWarning: overflow encountered in scalar multiply

```

I am very confused why this is only happening on windows, but this looks like a real warning from numpy and our tests are set to fail on any warning.

Given that we are looking for "does this fail", what is the simplest (smallest) input data we can get away with using?

**Comment by ksunden** [comment]
Alternative would be to upcast to float _sooner_ which would likely elide the precision warning (though may still have slight imprecision due to inexact float calcs).


e.g.

```python
    correls = np.correlate(x, y, mode="full").astype(float)
```

(And then keep the `/=`)

**Comment by abcnishant007** [comment]
> ```
>         if normed:
> >           correls = correls / np.sqrt(np.dot(x, x) * np.dot(y, y))
> E           RuntimeWarning: overflow encountered in scalar multiply
> ```
> 
> I am very confused why this is only happening on windows, but this looks like a real warning from numpy and our tests are set to fail on any warning.
> 
> Given that we are looking for "does this fail", what is the simplest (smallest) input data we can get away with using?

This may be due to the system default long in Windows vs Linux. So, trying explicit `int64` now. I don't have a Windows machine at hand at the moment. Apologies for triggering this test here directly without testing on local.

**Review by tacaswell — APPROVED** [review]
modulo squashing or squash-merge.

**Comment by tacaswell** [comment]
Looks good @abcnishant007 !  

Are you comfortable squashing your commits (see https://matplotlib.org/stable/devel/development_workflow.html#rewriting-commit-history)?

**Comment by abcnishant007** [comment]
Thanks for the review @tacaswell. I targeted two commits- 1 for the change and 1 for the test.  I did the cleaning and squashing using rebase, but while changing the commit message of the first commit, there was a dummy merge. Now, GitHub won't let me squash that merge commit anymore.

If this is unacceptable, I can create a new pull request with exactly two commits and the same changes as this one. What do you think?

**Comment by abcnishant007** [comment]
Thanks for the guidance! Yes, that was the trap. Finally, I managed to fix it by:
- using `reset --hard` 
- and then re-introducing the two commits. 
- finally push with `--force`

Now, we have a clean commit history of two commits, one for the fix, other for the test.

**Comment by tacaswell** [comment]
tried to re-trigger CI to pick up a fix on main for the mypy error.

**Review by tacaswell — APPROVED** [review]

**Comment by abcnishant007** [comment]
I think the `mypy subtest` issue is resolved after re-running the tests.

**Review by ksunden — APPROVED** [review]

**Pull request merged**
