### PR TITLE
Sort 3d sizes along with other properties

### LINKED ISSUE #18135: Point size array in the Axes3D scatter() does not follow the same order as in the data points
### Bug report

**Bug summary**
If I pass point sizes in an array through the `s` parameter in the `scatter()` function, the order of the values in `s` does not follow the same order as in the data points. I'm using `scatter()` function through `Axes3D` on jupyter notebook. The data to generate this issue can be found [here](https://gist.github.com/chudur-budur/50916cf1a98bf73790125f8d23d9aaf4).

**Code for reproduction**
```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

P  = np.loadtxt("data.csv", delimiter=',')

S = np.array(np.ones(P.shape[0])) * 5.0 # set all data point sizes to 5.0
# The indices of the three extreme corners are 0, 43 and 989.
# Now set these three point sizes to 100
S[0] = 100
S[43] = 100
S[989] = 100

# Plot
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(P[:,0], P[:,1], P[:,2], s=S)
plt.show()
```

**Actual outcome**
I know the indices of the three extreme corners are 0, 43 and 989. Therefore, if I plot, those points should come up as the largest, but they don't.
fail-case

Now, if I do the same thing in a different way, it works. But it doesn't help since I need to pass the point sizes in an array, all at once.
```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

P  = np.loadtxt("data.csv", delimiter=',')

# set these three point sizes to 100
I = np.array([0, 43, 989])

# Plot
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(P[:,0], P[:,1], P[:,2], s=5)
ax.scatter(P[I,0], P[I,1], P[I,2], s=100)
plt.show()
```

**Expected outcome (from the above code)**

pass-case

**Matplotlib version**

  * Operating system: posix Darwin 19.6.0
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): nbAgg
  * Python version: 3.7.5
  * Jupyter version (if applicable): 
     - jupyter core     : 4.6.3
     - jupyter-notebook : 6.0.3
     - qtconsole        : 4.7.5
     - ipython          : 7.16.1
     - ipykernel        : 5.3.4
     - jupyter client   : 6.1.6
     - jupyter lab      : not installed
     - nbconvert        : 5.6.1
     - ipywidgets       : 7.5.1
     - nbformat         : 5.0.7
     - traitlets        : 4.3.3
  * Other libraries: numpy 1.19.1, scipy 1.5.2
  * Browser: Firefox 78.0.2 (64-bit)

### PR DESCRIPTION
**Pull request by tomneep**
## PR Summary

Fixes #18135. The sizes of the points need to be updated when reordering along with the other properties.

scatter3d_fixed

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [n/a] New features are documented, with examples if plot related
- [n/a] Documentation is sphinx and numpydoc compliant
- [n/a] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [n/a] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
This seems to be the right solution, but this is going to need a test. You can use the demo code in the original issue as the basis for the test.

**Comment by timhoffm** [comment]
Targeting for 3.3.1 as release critical, because it's a regression in 3.3.0 introduced via #17378.

**Comment by tomneep** [comment]
Added a test. Maybe plotting 100 points was overkill thinking about it. Let me know if you want me to reduce the number of points.

## Pre-fix

old

## Post-fix
new

**Comment by WeatherGod** [comment]
This looks pretty good. Quick question for the peanut gallery. Technically speaking, a `Poly3DCollection` is probably also impacted by this bug because it derives from `PolyCollection`, which derives from `_CollectionWithSizes`. Don't know of any real use-case though of specifying sizes for poly3d collections, though (or if it even works?).

**Comment by QuLogic** [comment]
Is an image test really required here? Can you not pull the sizes from the produced collection, or is this re-ordering draw-dependent?

If that's not possible, then I think we can still use a figure comparison test instead. Just compare with a plot using individual scatter calls.

**Comment by tomneep** [comment]
@QuLogic The reordering is draw dependant so I couldn't get a standard test to work using `get_sizes`. I took your advice and changed to a figure comparison test with individual scatter calls.

**Comment by tacaswell** [comment]
@tomneep Can you should this to one commit (or we can squash-merge it)?  As it is the image will still be in the history (and we are trying to keep the repo from getting even bigger than it already is).

**Comment by tomneep** [comment]
@tacaswell Makes sense. I've rebased and squashed into a single commit.

**Comment by jkseppan** [comment]
Thanks @tomneep!

**Pull request merged**
