### PR TITLE
FIX: Don't apply tight_layout if axes collapse

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Partially addresses #12256

If tight_layout is called and there is an annotation or legend that is outside the axes, it can sometimes happen that the axes completely collapses.  There is currently a warning, but this PR also doesn't apply tight_layout if that happens, under the assumption its better to draw something rather than draw something that is completely broken.

Note however, it is still possible for the axes to get quite small.

The origin of these issues is that `axes.get_tightbbox` now includes all artists when computing the bounding box, whereas before 3.0 it only included the axes elements themselves, and *none* of the artists.  Now artists can be excluded by explictly setting `a.set_inlayout(False)`.  

NOTE: this is an API change in that `tight_layout.auto_adjust_subplotpars` now can return None if no good subplotpars were computed.  

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] Documentation is sphinx and numpydoc compliant
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
@tacaswell Yes, marked WIP now - it should get a test as well..

**Comment by timhoffm** [comment]
Please document that `get_tight_layout_figure()` can now return `None` as well.

**Comment by jklymak** [comment]
@timhoffm - is the new commit what you were after?   Thanks!

**Comment by timhoffm** [comment]
> ./lib/matplotlib/tight_layout.py:298:56: W291 trailing whitespace
>      W291 trailing whitespace

**Comment by jklymak** [comment]
Thanks!  Evil trailing space eradicated....

**Comment by tacaswell** [comment]
Thanks @jklymak !  Your work to make sure the tight/constrained layout works well is greatly appreciated!

**Pull request merged**
