### PR TITLE
Revise the misleading title for subplots demo

### PR DESCRIPTION
**Pull request by bingyao**
## PR Summary

``plt.subplot`` is different from ``plt.subplots``, and this great introduction article is about ``plt.subplots``.

### CODE REVIEW

**Comment by bingyao** [comment]
Also, I am just wondering why this great article is put in the _Gallery_ instead of in _Introductory level Tutorial_? I personally think it's very suitable to be as an Introductory level Tutorial.

**Comment by jklymak** [comment]
Thanks.  Perhaps the question about where this tutorial goes needs its own issue?

**Comment by QuLogic** [comment]
@meeseeksbot backport to v3.1.1-doc

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.1.1-doc

**Pull request merged**
