### PR TITLE
Fix cairo's image inversion and alpha misapplication.

### LINKED ISSUE #8798: gtk3cairo draw_image does not respect origin and mishandles alpha
As of master (and probably since a long time)
```
from pylab import *
rcdefaults()
fig, axs = plt.subplots(1, 2)
axs[0].imshow(np.arange(4).reshape((2, 2)))
axs[1].imshow(np.arange(4).reshape((2, 2)), alpha=.5)
show()
```
produces, on gtk3agg
gtk3agg
and on gtk3cairo
gtk3cairo

Looks like image.origin is not respected, and alpha is not applied correctly (this is not surprising, as cairo uses *premultiplied* ARGB (https://www.cairographics.org/manual/cairo-Image-Surfaces.html#cairo-format-t CAIRO_FORMAT_ARGB32).

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Closes #8798.  Looks like people are actually using the backend and running into the bug :p
I guess this would be nice to have in 3.0 (as it fixes a pretty bad bug) but won't insist on it either.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
So there is no test for this?

**Comment by anntzer** [comment]
No CI.

**Comment by jklymak** [comment]
@meeseeksdev backport to v2.2.x

**Comment by tacaswell** [comment]
This did not get backported to 2.2.x, but did make it in to 3.0.0, re-milestoned as such.

**Pull request merged**
