### PR TITLE
Build docs with oldest numpy on 2.7.

### PR DESCRIPTION
**Pull request by anntzer**
Saving some more time on CI, and checking that the docs build with old
numpys as well.

#8232 could probably be closed after that.

### CODE REVIEW

**Comment by anntzer** [comment]
Well, looks like the docs don't build on numpy 1.7.1 :-)

**Comment by anntzer** [comment]
"fixed"

**Comment by anntzer** [comment]
for real this time.

**Comment by anntzer** [comment]
Ah, I see, misunderstood BUILD_DOCS.  Let's build the docs with 2.7+oldest numpy then?

**Comment by QuLogic** [comment]
Don't really need to wait for AppVeyor.

**Pull request merged**
