### PR TITLE
Cleanup imports.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Same as #9929, but for the lib itself: remove unused imports and sort/group some remaining imports.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Are there any benefits to this other than a bit of organization?

**Comment by anntzer** [comment]
Cutting down on pyflakes output...

**Comment by dopplershift** [comment]
Removing unused imports could improve matplotlib's import time and memory usage. I'm not saying necessarily significantly, but I'll take what I can get for free. 😁

**Comment by jklymak** [comment]
PEP 8 doesn't like `animation.py`

**Comment by tacaswell** [comment]
It only helps if they are thing that would not be imported other wise.  If things are already in sys.modules the import is basically free.

**Comment by anntzer** [comment]
Note that I never claimed this was for performance :p 
PEP8 should be appeased now...

**Comment by tacaswell** [comment]
I think we explicitly do not check this bit of pep8, if we are going to do this travis should enforce it.

The dark side of 'discover-the-api-via-tab-complete' is that users will have found and used some of those un-used imports so I expect this to break some user code.  It should get some level of mention in the API changes docs.

**Comment by anntzer** [comment]
Not saying that this PR fixes pep8; rather, pep8 was unhappy because it wanted conditional imports (vs Python version) to be at the bottom of the import list.
Added api changes note.

**Comment by dopplershift** [comment]
@tacaswell I agree...that's why I said "could". 😁 Also, the unused import adds to the module's globals dict (not to mention takes a few instructions to execute), so that's technically more memory usage (and CPU). I'm not saying it's significant, but it's a "free" fix to not ask for things you don't use.

**Comment by anntzer** [comment]
grouped some more imports (in a separate commit)

**Pull request merged**
