### PR TITLE
FIX: No rcparam minor ticks in colorbar #8358

### LINKED ISSUE #8358: Minor ticks on log-scale colorbar are not cleared
### Bug report

**Bug summary**

- Using pcolormesh with logarithmic color scale and minor ticks enabled results in a cluttered-looking set of minor ticks, apparently because the linear ticks are not removed, just overplotted with the log scale ones.  

**Code for reproduction**

```python
import numpy
from matplotlib.colors import LogNorm
from matplotlib.pyplot import pcolormesh, colorbar, rcParams
rcParams['xtick.minor.visible']=True
rcParams['ytick.minor.visible']=True
data=numpy.random.random((10,12))*100.0+0.1 
pcolormesh(data,norm=LogNorm())
colorbar()
```

**Actual outcome**
lognormmess

**Expected outcome**

- Expect that the colobar minor ticks would appear logarithmically.

**Version Info**
Platform: GNU/Linux 2.6.32-642.11.1.el6.x86_64  
Python: 2.7.13 |Anaconda custom (64-bit)
IPython: 5.2.2
Matplotib: 2.0.0

All python components installed via Anaconda.

### PR DESCRIPTION
**Pull request by Dih5**
## PR Summary
Fixes #8358. Minor ticks were shown in colorbars when the `ytick.minor.visible` rcParam is `True`. A user won't be regarding a colorbar as a y axis, so this is a bug and not a feature :wink:
This PR forces removal of the minor ticks on the axes of a colorbar when its created. A image comparison test is also provided.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
#9903 also addresses this.

**Comment by Dih5** [comment]
I notice now that minor ticks should not be hidden by default in linear scale, so my fix is not good!
Please, consider checking #8358 is fixed in #9903, that seems proper way to address the problem.

**Comment by jklymak** [comment]
Well #9903 is pretty radical change to colorbars so it may not get in.  So an interim fix to this problem might be a good idea  I don’t have the time to check right now but will try to remember later if #9903 fixes that issue.

**Comment by Dih5** [comment]
I updated the changes to apply only with Log/SymLog normalizations. I hope for #9903 to make it eventually, but in the meantime perhaps this might solve the issue.

**Comment by Dih5** [comment]
Now that #9903 has been merged, there is no need for this PR. Thanks to @jklymak for this great job :tada:

**Pull request closed without merging**
