### PR TITLE
Simplify colormap reversal.

### PR DESCRIPTION
**Pull request by anntzer**
... plus small docstrings cleanups.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
It's one of the two possible ways of defining a colormap -- either a callable, or a list of colors.  Sure, I could call it callable_or_list, but that doesn't really help -- you basically need to be familiar with the details of colormap definition to understand this code...

**Comment by story645** [comment]
I was thinking more generally of like naming data "colormap" or whatever since that felt disconnected, but it's not a blocker. Second question though, why does _reverser need to be a standalone function (and not like a lambda) given it's only called once?

**Comment by anntzer** [comment]
Because lambdas are not picklable whereas toplevel functions are, and we need colormaps to be picklable in order to make things that refer to them (such as figures, via images) picklable as well.
`val` is actually *not* a colormap, just something that allows building one, so naming it `colormap` would make things more confusing imo...

**Comment by story645** [comment]
Thank you for your patience with my confusion and ugh :/

**Comment by anntzer** [comment]
no worries, thanks for the review :)

**Pull request merged**
