### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by franzhaas**
## PR Summary
This adresses #21783 

It is a very very small change, i droped the setuptools dependency for runtime and added a wheel dependency for setuptime.

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for working on this and sorry for the extraneous dependencies.

---- 

Why do we need the dependency on `wheel`? 

This is breaking all of our tests because in `__init__.py` we check if we are in a non-shallow git repo to make sure we get correct versions during development without having to re-build and we apparently have full git repos on some of the CI services (which is maybe something we should fix for other reasons, but I digress).

Would it be possible to detect (or tell our selves) that we are building a wheel and extending rather than dropping this logic?

**Comment by franzhaas** [comment]
@Why do we need the dependency on wheel?

I did run.:

py -m pip wheel URL_2_matplotlib_repository#egg=...

and it failed, with a error message that led me to believe that the wheels dependency is missing. Lacking knowledge of the internals, I expected it to be a good idea to add this dependancy. 

I believe that the lack of setuptools_scm is the problem for the test, and not the existance of wheel at setup time.

I do believe it is hard to detect a test environment correctly, as matplotlib may end up to be suposed to run production mode in somebody elses test. 

i tried to add the setuptools_scm dependancy to the tox.ini file...

**Comment by tacaswell** [comment]
Please see the discussion in #21783 and #21820 as well.

I do not think we use the tox.ini anywhere in our CI process, I suspect it is out-of-date in otherways as well.

**Comment by franzhaas** [comment]
this is taken care of elsewhere

**Comment by tacaswell** [comment]
Thanks @franzhaas !  As you noted we went with an alternate solution for 3.5.1 that will fix the dependencies for the next set of wheels and will make setuptools-scm fully optional for 3.6.

**Pull request closed without merging**
