### PR TITLE
DOC: view_init docstring for 3d axes primary view angles

### PR DESCRIPTION
**Pull request by scottshambaugh**
## PR Summary

Adds documentation showing azimuth and elevation angles needed to look at the primary planes in 3d plots. Fulfills some of the needs of https://github.com/matplotlib/matplotlib/issues/23544, resulting views are in that issue

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by scottshambaugh** [comment]
Docs build and look good: 
image

**Review by timhoffm — COMMENTED** [review]
The naming follows a consistent, but maybe not intuitive pattern:

- The first letter defines the horizontal axis, values increase from left to right
- The second letter defines the horizontal axis, values increase from top to bottom

The first one is clear, but top-bottom direction in the vertical may be surprising. All normal 2D and 3D plots use a vertically increasing values. The direction is a combined result of the `roll=0` constraint and the rotations necessary to get the horizontal and vertical axes positioned.

As long as this is only documentation and not API, it's not overly important because we can change it later.

However, I suggest to consider alternative names `AB` where A is horizontal axis, increasing left to right, and B is the vertical axis, increasing bottom to top. One can optionally add a `-` to reverse each axis separately (t.b.d. whether that minus should be before or after the letter, e.g. `X-Y-` or `-X-Y`). Depending on the axises and the orientation, this may involve roll or not, but the coordinate system itself would still remain right-handed (well, unless you reverse the axis limits, e.g. `set_xlim(1, -1)`, which you can always do).

**Comment by scottshambaugh** [comment]
@timhoffm I believe what you're suggesting is currently the convention when you plug in those values? First letter defining an left-right increasing horizontal axis, and second letter defining an increasing bottom-top vertical axis, with the negative sign flipping that axis. Are you seeing something different?
image

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
@scottshambaugh You are right: the vertical axis is as expected. Thanks for the PR!

My more general comment on the minus signs is mostly relevant in case we want to introduce the naming as API. I agree it's not reasonable to list all possible views in the docstring.

**Pull request merged**
