### PR TITLE
ci: Remove Linux & macOS from Azure

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

After an audit of all CI, we don't believe we are gaining anything by duplicating GitHub Actions here.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [tbd] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
For the record, the system Linux packages explicitly installed on GitHub Actions, but not Azure are:
- ccache
- libcairo2-dev
- libffi-dev
- libgeos-dev
- libgirepository1.0-dev
- libsdl2-2.0-0
- libxkbcommon-x11-0
- libxcb-cursor0
- libxcb-icccm4
- libxcb-image0
- libxcb-keysyms1
- libxcb-randr0
- libxcb-render-util0
- libxcb-xinerama0
- pkg-config
- qtbase5-dev
and vice versa:
- libgirepository-1.0-1
- poppler-utils

On macOS, GitHub Actions has:
- ghostscript
- gobject-introspection
- gtk4
- font-noto-sans-cjk
- inkscape
whereas for Azure its:
- ffmpeg
- imagemagick
- mplayer
- pkg-config
- font-noto-sans-cjk-sc
- xquartz

It also turns out that we never uploaded macOS coverage reports, so coverage is only down by 2 report from Linux. The coverage change shows that we lost:
- pdftocairo
- xpdf
- pdftops
I don't think we are missing any backends, specifically. Possibly on macOS, we may also want to add ffmpeg? But that's definitely caught by Linux builds.

**Comment by oscargus** [comment]
Do we know if xquartz is installed on GitHub or if it actually wasn't needed for Azure? It seems like the GUI-tests does not complain at least?

Interesting that a bit of the "executable not available"-tests lost coverage. Probably not worthwhile to have separate pipeline for those, but one may expect the minimum version test to handle them? Or maybe they are skipped earlier in the process? Is it worthwhile to setup a "minimum requirements" test (unless that is actually included in minimum versions)?

**Comment by tacaswell** [comment]
https://app.codecov.io/gh/matplotlib/matplotlib/pull/29171/blob/lib/matplotlib/backends/backend_pgf.py#L170

It looks like we support `pdftocairo` and `gs` for getting raster images out of pgf but always have `pdftocairo` installed so never test `gs`.  If this is what was before, lets open an issue to look at it, if this is new can we get one job that uses ps (I have not chased things back, but I have a suspicion that `pdftocairo` is a system dependency of something we depend on for pgf).

Can we drop ffmpeg on the minimal deps run?

**Comment by QuLogic** [comment]
> Do we know if xquartz is installed on GitHub or if it actually wasn't needed for Azure? It seems like the GUI-tests does not complain at least?

I think this may have been for GTK2. I don't recall if GTK3 used XQuartz, but GTK4 should be native. So I removed it and everything seems fine.

> Interesting that a bit of the "executable not available"-tests lost coverage. Probably not worthwhile to have separate pipeline for those, but one may expect the minimum version test to handle them? Or maybe they are skipped earlier in the process? Is it worthwhile to setup a "minimum requirements" test (unless that is actually included in minimum versions)?

> It looks like we support `pdftocairo` and `gs` for getting raster images out of pgf but always have `pdftocairo` installed so never test `gs`. If this is what was before, lets open an issue to look at it, if this is new can we get one job that uses ps (I have not chased things back, but I have a suspicion that `pdftocairo` is a system dependency of something we depend on for pgf).

These were from adding `poppler-utils`; I've left it out of the minimum versions build and now both of those code paths are touched.

> Can we drop ffmpeg on the minimal deps run?

Yes, did that as well.

**Review by tacaswell — APPROVED** [review]

**Review by ksunden — APPROVED** [review]

**Pull request merged**
