### PR TITLE
Increase axes test coverage

### PR DESCRIPTION
**Pull request by dstansby**
Add a few simple tests for methods that aren't being tested at all.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: in principle!

Can you add `style='default'` to the image decorators and replace the images?  Better if we can start to move away from the 'classic' style in the tests!

**Comment by WeatherGod** [comment]
point of order...

should it be 'default', or should it be 'v2' (or whatever the alias is?). I
can conceive of arguments both ways.

**Comment by tacaswell** [comment]
@WeatherGod you are right, I completely forget we put in that alias.

**Comment by dstansby** [comment]
Huh, all these image tests are passing fine locally but not on travis...

**Pull request merged**
