### PR TITLE
Deduplicate attribute docs of ContourSet and its derived classes

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary
I'm not 100% sure if we feel it's ok to build custom interpolation decorators, but it works :smile: .

### CODE REVIEW

**Comment by tacaswell** [comment]
I'm leaving an approval, but want a second set of eyes on this.

On one hand this makes no difference to the interactively accessed docs and the built docs, reduces the LOC we have floating around and means that we can be sure that these docstrings all stay in sync, but it comes at the cost of making the docstrings being much less clear when you are reading through the docs (which is what I spend most of my time doing so I am maybe over-sensitive to that).

I think that this is a net positive, but want to make sure someone else agrees.

**Comment by jklymak** [comment]
Don’t we already do docstring interpolation other ways?  Not a fan of a new mechanism.  Also it’s really helpful to have consistent prefixes for the docstring interpolation variables so we can easily search for them.

**Comment by QuLogic** [comment]
The other way is to put the replacements on a global `Substitution` instance; is there a reason these can't go on there?

**Comment by timhoffm** [comment]
Changed to use the global `Substitution` instance `docstring.interpd`.

**Pull request merged**
