### PR TITLE
FIX: restore verbose attribute at top level

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
How the heck did that happen.  Sorry about that....

**Comment by tacaswell** [comment]
@jklymak I hit the merge button so I should take most of the blame for this one.

Caught it before we pushed anything to pypi so we can just tag 2.2.2 as soon as this is merged and carry on from there!

**Comment by jklymak** [comment]
I’m actually curious what happened because I had those changes in (except for the test appaerntly).

**Comment by tacaswell** [comment]
@jklymak Looking at  `git reflog` may help reconstruct what happened.

**Pull request merged**
