### PR TITLE
Move the common implementation of Axes.set_x/y/zscale to Axis.

### PR DESCRIPTION
**Pull request by anntzer**
... together with an _axis_method_wrapper.

It may be worth trying to figure out later whether Axis._set_scale and
Axis._set_axes_scale need to have subtly different behaviors...

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
The 3D-versions where not tested earlier. Would be nice to have a test that passes both before and after this PR.

**Comment by anntzer** [comment]
3D axes don't actually meaningfully support any scales other than linear, so I don't think we can really write meaningful tests there.  Note that if anything this PR already *improves* the test coverage by getting rid of untested code (Axes3D.set_{x,y,z}scale).

**Review by oscargus — APPROVED** [review]
It improves the coverage for sure, I'm more worried about not changing behaviour. But after a more careful reading of the code, I can probably agree with you that it does the same thing as before.

**Comment by tacaswell** [comment]
The docs failure is understood as the sphinx-gallery reset issue, should not block.

The difference is that the autoscaling is now conditional, but I suspect that is OK.

**Pull request merged**
