### PR TITLE
Remove some manual manipulation of whatsnew when releasing.

### PR DESCRIPTION
**Pull request by anntzer**
This PR ensures that the "unmerged" whatsnew entries get included in the
docs if and only if we're building the docs for a "local release", i.e.
when the version number includes a git tag, but not a tagged release.
This previously required manual manipulation.

Noted while reviewing #10548.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
rebased

**Comment by jklymak** [comment]
Should the doc builds not work?

**Comment by anntzer** [comment]
Can't reproduce the failure locally (the whatsnew gets included)...

**Comment by jklymak** [comment]
I suspect a rebase will fix this; I had this error for something as well that shouldn't have had the error, but it worked after a rebase?

**Comment by anntzer** [comment]
rebased

**Comment by tacaswell** [comment]
Can you extend this to api_changes too?

**Comment by anntzer** [comment]
Done.
I believe that the build "failure" is due to a spurious sphinx warning: https://github.com/sphinx-doc/sphinx/issues/4770.

(but I guess it may still make sense to wait until the issue is fixed on sphinx's side before merging this, so that we don't start universally failing doc builds...)

**Comment by anntzer** [comment]
Temporarily closing until the issue is fixed upstream.

**Pull request closed without merging**
