### PR TITLE
Add Seaborn style sheets; addresses #4566

### PR DESCRIPTION
**Pull request by petebachant**
This commit adds the default Seaborn "darkgrid" style to the style library.

### CODE REVIEW

**Comment by efiring** [comment]
Thanks for doing this.
In anticipation of additional Seaborn styles being added, should the file name include some indication of the particular variant?
Maybe we need some more thought about how to categorize, organize, and name styles.

**Comment by petebachant** [comment]
I was thinking of calling this one simply `seaborn` since it is the default style when importing `seaborn`, then adding `seaborn-white`, `seaborn-whitegrid`, and `seaborn-ticks`.

**Comment by efiring** [comment]
Attn @mwaskom: comments?

**Comment by mwaskom** [comment]
I would prefer the current default seaborn style to be called `seaborn-darkgrid` (or however you choose to indicate the variant).

Do matplotlib stylesheets have any facility for handling style and element scale ("context" in seaborn, regrettably) independently?

**Comment by WeatherGod** [comment]
There is MEP26 that is being ironed out, if that is what you are thinking?
http://matplotlib.org/devdocs/devel/MEP/MEP26.html

**Comment by mwaskom** [comment]
I just mean that the "seaborn styles" are really the product of two independent sets of rc parameters.

**Comment by petebachant** [comment]
The scaling and colors could be split into two different stylesheets, which would allow users to

```
plt.style.use("seaborn-darkgrid")
plt.style.use("seaborn-paper")
```

**Comment by mwaskom** [comment]
Actually good point, you also need a third piece: the color cycle palette.

**Comment by tacaswell** [comment]
Would it be worth adopting the scale style sheets wholesale so

```
plt.style.use('seaborn-darkgrid")
plt.style.use("media-paper")
# plt.style.use("media-interactive")
# plt.style.use("media-talk")
```
?

The color cycle might be complicated / should embrace https://github.com/matplotlib/matplotlib/pull/4258 (which needs to be replaced by a PR to add https://github.com/tacaswell/cycler (which needs to end up on pypi and move to the mpl org) ).

**Comment by mwaskom** [comment]
I don't think seaborn does anything as complicated as your cycler tool, it just sets the color cycle independently from the axes style and plotting context.

**Comment by tacaswell** [comment]
Right, leave cycler out of this.

@petebachant Can you split the style sheet up as discussed (base axes settings, font/tick sizes, color cycle)?

There is a PR in to use styles in styles (https://github.com/matplotlib/matplotlib/pull/4240 ) which can be used to create composite style sheets if we want that as well.

**Comment by petebachant** [comment]
Sure, I will split the stylesheets up.

**Comment by petebachant** [comment]
Just split the darkgrid style into three sheets for the scaling, colors, and palette. What do you guys think? Should I make the other Seaborn variants?

**Comment by tacaswell** [comment]
:+1: to both this and the other variants.

**Comment by tacaswell** [comment]
@petebachant I am going to merge this as-is, can you make a new PR with the other variants ?

**Comment by petebachant** [comment]
Will do!

**Pull request merged**
