### PR TITLE
FIX: better default spine path (for logit)

### LINKED ISSUE #11386: Logit scale doesn't position x/ylabel correctly first draw
### Bug summary

Using `constrained_layout` or `tight_layout` in conjunction with a `logit` scale fails or crashes.

### Constrained layout:

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(constrained_layout=True)

ax.plot([.2,.4,.6,.8],[.2, .4, .5, .9])
ax.set_xscale('logit')

plt.show()
```

results in a crash of python in Windows. I.e. it shows a pop up saying python needs to be closed because it crashed.

### Tight layout

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()

ax.plot([.2,.4,.6,.8],[.2, .4, .5, .9])
ax.set_xscale('logit')

fig.tight_layout()
plt.show()
```
produces a long traceback for a `ValueError: cannot convert float NaN to integer`.

```
D:\...\envs\mplgit\lib\site-packages\numpy\core\_methods.py:29: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims)
D:\...\envs\mplgit\lib\site-packages\numpy\core\_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values
posx and posy should be finite values

Traceback (most recent call last):
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\backends\backend_qt5.py", line 513, in _draw_idle
    self.draw()
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\backends\backend_agg.py", line 421, in draw
    self.figure.draw(self.renderer)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\figure.py", line 1478, in draw
    renderer, self, artists, self.suppressComposite)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\axes\_base.py", line 2583, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\axis.py", line 1177, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\axis.py", line 1017, in _update_ticks
    tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\axis.py", line 961, in iter_ticks
    majorLocs = self.major.locator()
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\ticker.py", line 1922, in __call__
    return self.tick_values(vmin, vmax)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\ticker.py", line 1930, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\ticker.py", line 1876, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
  File "d:\...\python\matplotlib\source\matplotlibgit\matplotlib\lib\matplotlib\axis.py", line 2503, in get_tick_space
    return int(np.floor(length / size))
ValueError: cannot convert float NaN to integer
```

### Expected outcome

Using either of above without layout manager gives the correct figure.

Also, using either of above without the line `ax.set_xscale('logit')` produces the expected output.

This may be related to #5456.

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 2.2.2.post1271+g0a70730fa
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg, TkAgg
  * Python version: 3.6

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Closes #11386;  see also #11404 which fixes the errors for tight_layout and constrained_layout.

```python 
import matplotlib.pyplot as plt

fig, ax = plt. subplots()
ax.plot([0.1, 0.2, 0.6, 0.9])
ax.set_yscale('logit')
ax.set_ylabel('Boo')

plt.show()
```

gives a warning, and does not show the ylabel.  Issue is that the yaxis spine path is 
```
Path(array([[  0.,  13.],
       [  0.,  13.]]), None)
```
and `_update_label_position` needs a valid path to get started, whereas the logit scale injects Infs.

This PR changes the default PATH to something that would theoretically fit on the figures (and hence all values are less than 1).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Could this or #11404 get a test? (just the code that is in #11386 would probably be fine)

**Comment by jklymak** [comment]
@dstansby Thanks,; new test fails on master, passes on this PR.

**Comment by jklymak** [comment]
Hmmm, well, the problem is `logit` transform, which doesnt do sensible things if the values passed to it are not 0<a<1.  It has a "clip" argument, but we don't call transforms with `clip` turned on, so.  Conversely, you may not want to always clip data sent to the transform, because maybe you want to tell the user its gone to infinity....  

The other solution that occured to me is getting the spine Path to resolve itself properly earlier, but that seemed hard, and unecessary.

**Comment by phobson** [comment]
I should probably write a similar test for mpl-probscale, which is very similar to logit scales

**Pull request merged**
