### PR TITLE
check the type of the output animation filename

### PR DESCRIPTION
**Pull request by mherkazandjian**
Currently it is difficult to determine the error when the animation movie
filename is something other than a string. Even with the debug output of
matplotlib, it is not easy to determin the reason why the subprocess call
fails.

I added a check that explicitly checks the type of the output file variable.

### CODE REVIEW

**Comment by anntzer** [comment]
I would say that the error message of subprocess.Popen when given a non-str argument is quite clear (`expected str, bytes or os.PathLike object, not int` in Py3.6), and there isn't really a reason to explicitly type-check for this call rather than for the thousands of other functions that exist in matplotlib.
I'm going to close this, but feel free to argue (e.g. with a specific example) that we should reconsider.

**Comment by mherkazandjian** [comment]
Hi,

actually maybe an example that reproduces the issue i am addressing would have been good. So here it is:


````python
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.animation as manimation

FFMpegWriter = manimation.writers['ffmpeg']
metadata = dict(title='Movie Test', artist='Matplotlib',
                comment='Movie support!')
writer = FFMpegWriter(fps=15, metadata=metadata)

fig = plt.figure()
l, = plt.plot([], [], 'k-o')

plt.xlim(-5, 5)
plt.ylim(-5, 5)

x0, y0 = 0, 0

with writer.saving(fig, True, 100):
    for i in range(100):
        x0 += 0.1 * np.random.randn()
        y0 += 0.1 * np.random.randn()
        l.set_data(x0, y0)
        writer.grab_frame()
````

running this both with python2 and 3 results in an error message:

````error
TypeError                                 Traceback (most recent call last)
/home/john/test_ffmpeg_movie_writer.py in <module>()

29 x0, y0 = 0, 0
     30 
---> 31 with writer.saving(fig, True, 100):
     32     for i in range(100):
     33         x0 += 0.1 * np.random.randn()

~/anaconda/anaconda3/lib/python3.6/contextlib.py in __enter__(self)
     80     def __enter__(self):
     81         try:
---> 82             return next(self.gen)
     83         except StopIteration:
     84             raise RuntimeError("generator didn't yield") from None

~/anaconda/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, *args, **kw)
    250         '''
    251         # This particular sequence is what contextlib.contextmanager wants
--> 252         self.setup(*args, **kw)
    253         try:
    254             yield self

~/anaconda/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in setup(self, fig, outfile, dpi)
    240         # Run here so that grab_frame() can write the data to a pipe. This
    241         # eliminates the need for temp files.
--> 242         self._run()
    243 
    244     @contextlib.contextmanager

~/anaconda/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in _run(self)
    266             output = subprocess.PIPE
    267         verbose.report('MovieWriter.run: running command: %s' %
--> 268                        ' '.join(command))
    269         self._proc = subprocess.Popen(command, shell=False,
    270                                       stdout=output, stderr=output,

TypeError: sequence item 26: expected str instance, bool found
````

The error message 

````
TypeError: sequence item 26: expected str instance, bool found
````
is quite ambiguous and I believe it improves the user experience to have a clear message
and do good argument checking.

**Comment by tacaswell** [comment]
This is dying while formatting a log message, that is fun, if we did not have the message it would fail for the same reason inside of `Popen`.

I am inclined to just cast `output` to `str` or do nothing.

**Comment by anntzer** [comment]
Strongly against casting to str (here it would just write to a file named "True", which is probably wrong anyways).
Note that the first frame of the traceback that points to your code literally points to the line where the bug is: `with writer.saving(fig, True, 100)` should be quite clear together with `expected str instance, bool found`.  Compare for example with the many other places where a wrongly typed argument would cause a failure at *draw* time, so the traceback would not even be able to point to the incorrect line in the user code.

**Comment by mherkazandjian** [comment]
yes, you are right. I think it is a good idea not to mention the supplied value of ````outfile```` in the msg. i.e
show the message

````python
            msg = (
                'output file must be a string like object.\n The provided'
                'output file value is of type {}'.format(type(self.outfile))
            )
````
The traceback message itself

````
TypeError: sequence item 26: expected str instance, bool found
````
is misleading, because it refers to an ````item 26``` that is part of the command passed to Popen.

you should look at this from a user perspective not a developer perspective. For a regular user the traceback is not clear and requires digging.

**Comment by dopplershift** [comment]
Why don't we fix the assumption that `''.join(command)` is safe and make it `''.join(str(c) for c in command)`?

**Comment by mherkazandjian** [comment]
````python
    print(str(True)
````
would still generate a command that has a 'True' in it.

**Comment by dopplershift** [comment]
Right, but then at least running with verbose logging would give you a useful diagnostic of what command it was trying to run.

**Comment by WeatherGod** [comment]
why are we against input validation? seems like it would be reasonable
thing to do to notify the user early on that something is wrong.

**Comment by mherkazandjian** [comment]
yes. input validation in the case of this ````writer.saving```` would be good. Mainly because the the writing
is delegated to an external program. i.e ````ffmpeg````.

This is a small digression, but i think another argument for validating the input. replacing ````True```` in the example above with e.g a path that does not exist like ````/foo/my_movie.mp4````, i.e the 

````python
with writer.saving(fig, '/foo/loo.mp4', 100):
````
 (where /foo is a directory that does not exist or a location where the file can not be created), would result in an backtrace:

````python
Traceback (most recent call last):
  File "foo.py", line 25, in <module>
    writer.grab_frame()
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/matplotlib/animation.py", line 289, in saving
    self.finish()
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/matplotlib/animation.py", line 309, in finish
    self.cleanup()
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/matplotlib/animation.py", line 348, in cleanup
    out, err = self._proc.communicate()
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/subprocess32.py", line 927, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/subprocess32.py", line 1713, in _communicate
    orig_timeout)
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/subprocess32.py", line 1769, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/home/john/progs/anaconda/anaconda3/envs/conda2/lib/python2.7/site-packages/subprocess32.py", line 1748, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
````
so a regular user would have a hard time guessing what this refers too. A closed file? or a file that does not exist ? which took me some time to figure out. In this case the closed file refers to the pipe between
matplotlib and ffmpeg (i guess), where ffmpeg is doing the actual writing. so a few simple check on the most common use cases of the ````MovieWriter```` arguments would be handy and easy to maintain too.

I'll work on the unit tests if you agree on having these checks in.

**Comment by efiring** [comment]
I'm reopening this, because at the very least it is pointing to a bug in the log message formatting.  (See @tacaswell's comment early in the thread.) I'm inclined to think that some additional validation is also in order before anything is fed to an external process.  Exactly how and where that validation should occur is not yet clear to me.

**Comment by mherkazandjian** [comment]
Yes. Tnx.
There are many things that could go wrong in the arguments passed to the external writer since i think there are several writers, not just ffmpeg. So it is impossible to do the work of the writers and check all the arguments passed to them. But at least some basic checks can be done, such as the file name, negative frame rates, negative bit rates. Moreover, we can dump the error message of the write as part of the 
error message being raised by default or in debug mode.

**Comment by QuLogic** [comment]
Please remove the last commit; `is_string_like` is deprecated.

**Comment by mherkazandjian** [comment]
done.

**Comment by anntzer** [comment]
As of master, the example given above fails with
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    with writer.saving(fig, True, 100):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/antony/src/extern/matplotlib/lib/matplotlib/animation.py", line 227, in saving
    self.setup(fig, outfile, dpi, *args, **kwargs)
  File "/home/antony/src/extern/matplotlib/lib/matplotlib/animation.py", line 341, in setup
    self._run()
  File "/home/antony/src/extern/matplotlib/lib/matplotlib/animation.py", line 352, in _run
    creationflags=subprocess_creation_flags)
  File "/usr/lib/python3.7/subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1447, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: expected str, bytes or os.PathLike object, not bool
```
(as the log-formatting issues have been fixed), which is I think quite good enough.
I thus propose to close (once again) this PR.

**Comment by anntzer** [comment]
Closing per the comment above as no one commented again; thanks for the PR.

**Pull request closed without merging**
