### PR TITLE
Relational Operators for mathtext

### LINKED ISSUE #25042: [Bug]: `\geqslant`, `\leqslant` and `\eqslantgtr` are not spaced like their non-slanted versions
### Bug summary

There should be a space on both sides of these operators.

### Code for reproduction

```python
import matplotlib.pyplot as plt
plt.text(.3, .2, r'$a\leq2$', size=40)
plt.text(.3, .4, r'$a\leqslant2$', size=40)
plt.text(.3, .6, r'$a\geqslant2$', size=40)
plt.text(.3, .8, r'$a\eqslantgtr2$', size=40)
plt.show()
```

### Actual outcome

nospace

### Expected outcome

Spacing should be the same for all of these symbols.

### Additional information

_No response_

### Operating system

Debian GNU/Linux 11 (bullseye)

### Matplotlib Version

3.5.0.dev7385+ge6bf91dcfd

### Matplotlib Backend

TkAgg

### Python version

Python 3.9.2

### Jupyter version

_No response_

### Installation

git checkout

### PR DESCRIPTION
**Pull request by devRD**
## PR summary
Fixes #25042 
Closes #25045 

Added mappings to binary operators missing Unicode ref
## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by devRD** [comment]
Hi @tacaswell @anntzer @ksunden 

Could you please take a look at the patch? :)

**Comment by oscargus** [comment]
I'd suggest adding spaces so that the entries ends up in columns.

The sorting and completeness is clearly a huge step over my PR!

(Will not approve because of the relation to my earlier PR.)

**Review by ksunden — APPROVED** [review]
Implementation looks good, I went and ran the original report code.

Could argue for test(s?) perhaps, but not _too_ set on what granularity is needed (or if the _new_ things need it if, there were already tests of other things in this list)

CI failures appear to be unrelated (Qt/macos tk, which have been addressed elsewhere)

**Comment by tacaswell** [comment]
I am surprised that this did not fail any tests!

There is a wall of tests for mathtext: https://github.com/matplotlib/matplotlib/blob/f5f2cd9fb0d2f7d788650d6b588baaa78be7c492/lib/matplotlib/tests/test_mathtext.py#L21-L122 

Are these worth a whats new?

**Comment by oscargus** [comment]
There are a number of PRs that add and/or correct symbols, so maybe one should create a single What's new that can be appended?

**Comment by devRD** [comment]
I have included some of the relational operators from the list in #26024. 
Is the `what's new` note required to be added?

**Comment by oscargus** [comment]
I think that at some stage before 3.8 there should be a What's new note in some form. Maybe not listing all the added symbols etc, but stating something more general. Then, this can be updated in the different PRs (for example, it doesn't really make sense to add  a note for #26010 , but I can for sure add a line to an existing note about relational operators).

**Review by oscargus — APPROVED** [review]
Although this is partly based on a very rudimentary initial PR from me, I think it has diverged enough so that I can fairly review it. (Especially given that nothing has happened in three weeks,)

**Pull request merged**
