### PR TITLE
Draw markers around center of pixels

### PR DESCRIPTION
**Pull request by mdboom**
When the snapping of circle markers was disabled in 37927b2, in order to make them look more round, it also made them half a pixel off of center (since the snapping was no longer happening).  This shifts non-snapped markers by half a pixel to keep (0, 0) running down the middle of the pixel.

BEFORE THIS PR:

old

AFTER THIS PR:

new

As a procedural point, we should try to get this in before #5307, as it will change many of the baseline images (for the better, we hope).

### CODE REVIEW

**Comment by WeatherGod** [comment]
Would probably be good to have some tests specifically for this. Different markers, different sizes, different locations and at different resolutions. Does shifting it half a pixel only impact the visual result if rounding would have been an issue?

I also wonder if a similar approach might solve the contourf problem?

**Comment by mdboom** [comment]
> Would probably be good to have some tests specifically for this. Different markers, different sizes, different locations and at different resolutions. Does shifting it half a pixel only impact the visual result if rounding would have been an issue?

Once the tests are lowered to zero tolerance in #5307, the existing tests should do that and detect changes of this magnitude.  And there are already tests that test all of the different markers (`test_axes.test_marker_styles`).  I think it best not to add additional tests in this case.

> I also wonder if a similar approach might solve the contourf problem?

I don't think so.  I've already experimented with snapping to solve that problem some time ago, and it doesn't help.

**Comment by tacaswell** [comment]
Does this address https://github.com/matplotlib/matplotlib/issues/3400 ?

**Comment by WeatherGod** [comment]
And when we lower the tolerance to zero, and images are remade en masse, are we going to be able to verify every single marker is drawn correctly? Also, we don't have all that many tests that use different resolutions?

I would love to see test images made at fairly low resolutions that draws lines like you have above and plots markers at their intersections. Having it at a low resolution would make it visually obvious that something is wrong.

**Comment by mdboom** [comment]
> And when we lower the tolerance to zero, and images are remade en masse, are we going to be able to verify every single marker is drawn correctly?

Yes.  That was why I built the comparison tool in #5521, to make that kind of thing *much* easier.

> Also, we don't have all that many tests that use different resolutions?

That's true.

> I would love to see test images made at fairly low resolutions that draws lines like you have above and plots markers at their intersections. Having it at a low resolution would make it visually obvious that something is wrong.

That's a good point.

**Comment by mdboom** [comment]
> Does this address #3400 ?

I think not, unfortunately -- addressing that requires the line and the marker line to know about each other and snap in sync.  We don't really have that kind of global knowledge.  But #3400 only really becomes a problem if the user customizes the line width or marker edge width to be a mismatch of even/odd sizes.

**Comment by QuLogic** [comment]
Was `test_axes/stackplot_test_baseline.png` really supposed to change here?

**Comment by mdboom** [comment]
> Was test_axes/stackplot_test_baseline.png really supposed to change here?

Yep.  For reasons that are rather obscure, stackplots end up going through the `draw_marker` code path on Agg.

**Comment by WeatherGod** [comment]
So, the stackplots are polygons, right? Would it make sense to treat
contourf polygons similarly?

I am being overly hopeful, but the stackplots do look better now, so I just
wanted to make sure that this possibility has been considered.

**Comment by tacaswell** [comment]
backported to 1.5.x as 34c7dad19ee3cc962fb038b18f301a1b00c8844d

**Pull request merged**
