### PR TITLE
Add a 'useMathText' param to method 'ticklabel_format'

### PR DESCRIPTION
**Pull request by gepcel**
As discussed in #6330. Can anyone examine this?

### CODE REVIEW

**Comment by gepcel** [comment]
Now we can do like:
```python
plt.plot(1, 10000, 2, 20000, 'ro')
ax = plt.gca()
ax.ticklabel_format(scilimits=(-3, 3), useMathText=True)
plt.show()
```

or:
```python
plt.plot(1, 10000, 2, 20000, 'ro')
ax = plt.gca()
fmt = ax.yaxis.get_major_formatter()
fmt.set_useMathText(True)
#or fmt.useMathText = True
fmt.set_powerlimits((-3, 3))
plt.show()
```

**Comment by QuLogic** [comment]
It would be nice to be more PEP8-y on the name, but I don't know if we want to just leave it to be consistent with the existing name. Or perhaps some deprecation notice would be possible on the original name...

**Comment by gepcel** [comment]
Hi, @QuLogic . I'm not sure I understand you. Can you explain more? What should I do?

**Comment by QuLogic** [comment]
The comment is not a suggestion for you; it's a question for the other devs.

**Comment by tacaswell** [comment]
making the names more pythonic is a good fight, but one that is beyond the scope of this PR.  I think the standard practice in these cases is to stay consistent with the local naming and do the renaming/deprecation in a separate PR.

**Pull request merged**
