### PR TITLE
DOC: Update to the primary prompt

### PR DESCRIPTION
**Pull request by nvd1en**
## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [N/A] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
Can you give some context here?  This seems like an unnecessary change, but maybe you have a good reason for suggesting it.

**Comment by nvd1en** [comment]
I think using the `>>>` sign instead of the `>` sign makes code blocks more apparent and friendly to read.

**Comment by anntzer** [comment]
These are *not* python prompts (which would indeed be `>>>` in the default python shell), so making the change would just be *more* confusing IMO.

**Comment by StefRe** [comment]
the `>` denotes the shell prompt here, for standard bash it would be `$` (or `#` for root), so if this is going to be changed, it should be change to `$`.

**Comment by nvd1en** [comment]
@anntzer @StefRe
Thanks for your response!

**Pull request closed without merging**
