### PR TITLE
Bugfix for issue #750 (gridlines for 3d axes cover a plotted surface …

### PR DESCRIPTION
**Pull request by AmyTeegarden**
…after ax.cla() is called)

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @WeatherGod

**Comment by WeatherGod** [comment]
I think we already fixed this in master recently. Could you provide a
minimal example that demonstrates the problem and also which version of mpl
you are using?

**Comment by AmyTeegarden** [comment]
I'm using 1.4.3 with python 2.7.10 on Windows 8. I've been trying to figure out how to set up a virtual environment with virtualenv so I can test code from master, but I'm having trouble installing matplotlib from source.

**Comment by AmyTeegarden** [comment]
Minimal example:

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np


X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)

fig = plt.figure()
ax = fig.gca(projection = '3d')
ax.cla()
ax.set_axisbelow(True)
ax.plot_surface(X, Y, X + Y, rstride=1, cstride=1, zorder = 10)
plt.show()

**Comment by WeatherGod** [comment]
Yeah, I am not seeing the problem in master with your example. I suspect that #4553 inadvertently fixed this issue as well. Oddly enough, it `set_axis_on()` rather than off, but it does so in the base Axes class. I haven't had time to think about the exact differences here, but I am inclined to close this PR.

If you can prove that the problem still exists in master (maybe via a different mechanism), then feel free to reopen this PR.

**Comment by tacaswell** [comment]
This is what renders on mostly-master for me:

so

https://github.com/jbmohler/matplotlib-winbuild This may be a useful repo for getting mpl to build on windows.

**Pull request closed without merging**
