### PR TITLE
STY: fix line length

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary

unbreaks CI on master.

## PR Checklist

- [x] Code is PEP 8 compliant

### CODE REVIEW

**Comment by anntzer** [comment]
thanks

**Comment by dstansby** [comment]
Sorry...

**Comment by QuLogic** [comment]
Backported as part of #10099.

**Comment by lkjell** [comment]
Sorry, is it 80 char that is max?

**Comment by anntzer** [comment]
79

**Comment by lkjell** [comment]
Same for doc as well or 72?

**Comment by anntzer** [comment]
We use 79 everywhere.

**Pull request merged**
