### PR TITLE
[WIP] Add tutorial for LogScale

### PR DESCRIPTION
**Pull request by souravsingh**
## PR Summary

#8863 

## PR Checklist

- [x] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Thanks @souravsingh, but I think this is a little basic for a tutorial.  Maybe move into the examples?

**Comment by timhoffm** [comment]
So far, this is just a minor rewrite of the existing log demo. C.f.

[existing log demo](https://matplotlib.org/2.2.2/gallery/scales/log_demo.html#sphx-glr-gallery-scales-log-demo-py)
[this PR](https://9780-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/tutorials/intermediate/log_tutorial.html?highlight=logscale)

@souravsingh I assume you are going to expand on this. OTOH there's no need to open a PR in this early stage. PRs should be opened when the feature is either complete or if you need feedback on certain aspects before completion.

**Comment by souravsingh** [comment]
@timhoffm Yes, It is a minor rewrite of the existing demo, which I intend to extend by adding tick behavior and symlog. I opened the PR early so I can get iterative feedback for the PR.

**Comment by timhoffm** [comment]
@souravsingh Thanks for the explanation. Please keep in mind that our review capacity is limited (actually it‘s one of the main limiting factors in the development).

That said, there is no general rule when to submit a first version. If it‘s too early, we‘re wasting reviewer time, if it‘s too late, the PR may go in the wrong direction and needs correction, which is extra work for the author. As a rule of thumb, a PR does not have to be polished, if you are having doubts. But in that case, it should at least demonstrate your ideas. Also, it helps a lot, if you comment your ideas and indicate the state of the changes.

**Comment by souravsingh** [comment]
Closing the PR since there is zero incentive for me in working on this.

**Comment by timhoffm** [comment]
@souravsingh I hope we don't have scared you off with our comments. Helping to improve the documentation is greatly apreciated.

Of course, the motivation has to come from within yourself. We can only give feedback and help along the way. I recognize that priorities and motivation can change, and that's perfectly fine. Maybe see you another time.

**Pull request closed without merging**
