### PR TITLE
Upgrade pillow to >= 10.3.0

### PR DESCRIPTION
**Pull request by marcusps**
## PR summary

There are several security vulnerabilities in `pillow==8`, as flagged by `pip_audit` and [Github's advisory databse](https://github.com/advisories?query=type%3Areviewed+pillow). Upgrading to `pillow>=10.3.0` fixes them all.

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by timhoffm** [comment]
What is the motivation behind this?

**Comment by marcusps** [comment]
I wasn't sure what the proper process to bring this up is (and in the process of trying to find out, forgot to get back here to provide context), but there is a relatively long list of vulnerabilities associated with `pillow==8` (obtained through `pip_audit`, but it also shows up on [Github's advisory database](https://github.com/advisories?query=type%3Areviewed+pillow) and in automated alerts in Azure Dev Ops), and some of them allow for arbitrary code execution.  The more recent issue is only fixed in `pillow==10.3.0`.

```
Name       Version ID                  Fix Versions
---------- ------- ------------------- ------------
pillow     8.0.0   PYSEC-2021-137      8.2.0
pillow     8.0.0   PYSEC-2021-138      8.2.0
pillow     8.0.0   PYSEC-2021-70       8.1.0
pillow     8.0.0   PYSEC-2021-331      8.3.0
pillow     8.0.0   PYSEC-2021-41       8.1.1
pillow     8.0.0   PYSEC-2021-71       8.1.0
pillow     8.0.0   PYSEC-2021-69       8.1.0
pillow     8.0.0   PYSEC-2021-38       8.1.1
pillow     8.0.0   PYSEC-2021-139      8.2.0
pillow     8.0.0   PYSEC-2021-94       8.2.0
pillow     8.0.0   PYSEC-2021-39       8.1.1
pillow     8.0.0   PYSEC-2021-36       8.1.1
pillow     8.0.0   PYSEC-2021-40       8.1.1
pillow     8.0.0   PYSEC-2021-37       8.1.1
pillow     8.0.0   PYSEC-2021-317      8.3.2
pillow     8.0.0   PYSEC-2021-35       8.1.1
pillow     8.0.0   PYSEC-2021-93       8.2.0
pillow     8.0.0   PYSEC-2021-42       8.1.1
pillow     8.0.0   PYSEC-2021-92       8.2.0
pillow     8.0.0   PYSEC-2022-10       9.0.0
pillow     8.0.0   PYSEC-2022-9        9.0.0
pillow     8.0.0   PYSEC-2022-8        9.0.0
pillow     8.0.0   PYSEC-2022-168      9.0.1
pillow     8.0.0   PYSEC-2022-42979    9.2.0
pillow     8.0.0   PYSEC-2023-175      10.0.1
pillow     8.0.0   PYSEC-2023-227      10.0.0
pillow     8.0.0   GHSA-jgpv-4h4c-xhw3 8.1.2
pillow     8.0.0   GHSA-4fx9-vc88-q2xc 9.0.0
pillow     8.0.0   GHSA-3f63-hfp8-52jq 10.2.0
pillow     8.0.0   GHSA-j7hp-h8jx-5ppr 10.0.1
pillow     8.0.0   GHSA-56pw-mpj4-fxww 10.0.1
pillow     8.0.0   GHSA-44wm-f244-xhp3 10.3.0
```

**Comment by timhoffm** [comment]
I'm unclear whether it's on Matplotlib as a project to exclude versions of dependencies that are technically working, but have vulnerabilities. Vulnerability management must happen on the user side via other tools. Note also that this does not make a difference for standard new installations, because package managers pull the most recent version of dependencies by default.

From a [process perspective](https://matplotlib.org/devdocs/devel/min_dep_policy.html#python-dependencies)
- we have not documented this as a reason to bump dependencies. If we decide to to it, the docs need an update.
- we commit to support all releases from the last 12 months. So, we cannot jump to 10.3 immediately because it's just been [released 3 weeks ago](https://pypi.org/project/pillow/#history).

**Comment by tacaswell** [comment]
Our policy is that as a library (not an application) it is not our place limitations on our users (even if our user should definitely be updating pillow!) that technically work.

Additionally, because pypi does not support updating metadata (https://pypackaging-native.github.io/key-issues/pypi_metadata_handling/) this will be minimally effective as it would only affect new releases.

**Comment by QuLogic** [comment]
Thanks for this PR, but I'm going to close. As stated, we have not required recent dependency versions for security reasons, as we are not an application (interactive mode notwithstanding.)

**Pull request closed without merging**
