### PR TITLE
NF - New legend example with line collection

### PR DESCRIPTION
**Pull request by AmyTeegarden**
This is a new example with a custom legend handler. It displays all of the lines in a line collection instead of just the first one.

### CODE REVIEW

**Comment by AmyTeegarden** [comment]
This file works with my version of matplotlib (1.4.3). It looks like there's some code in the 1.5 version of set_color for Line2D that won't accept the output of get_colors()[0]. I'm not sure how to make this work. It seems odd that a set_color method won't work with a get_colors() method, though.

**Comment by tacaswell** [comment]
Thanks for the example and good job finding a regression!

**Comment by AmyTeegarden** [comment]
Do I need to resubmit the pull request or do anything else now?

**Comment by WeatherGod** [comment]
You can "fetch" from this repo and rebase this branch off of the updated master. Then push it up. Assuming that this repo is called "origin" and your clone is called "myrepo" (and assuming you are on this branch):
```
git fetch origin
git rebase origin/master
git push myrepo legend_demo5
```
That should retrigger the Travis checks.

**Comment by AmyTeegarden** [comment]
Thanks, WeatherGod. That seems to have done the trick. Ah -- should those other commits be in this, too, or did I do the rebase incorrectly?

**Comment by WeatherGod** [comment]
eh, looks benign enough. Github is still showing that this PR changes only a single file. You'll get the hang of the git workflow after a few tries.

**Comment by WeatherGod** [comment]
oh, oops. I thought that #4778 was merged already. It wasn't. I just merged it in, so you can now go ahead and fetch/rebase/push.

**Comment by AmyTeegarden** [comment]
Okay, I'm not quite certain why the checks failed this time. It was an issue with matplotlib.tests.test_backend_ps.test_savefig_to_stringio_with_usetex, and ultimately the problem was RuntimeError: LaTeX was not able to process the following string: '$1.2$'

Sorry if I'm doing this all wrong -- this is my first time contributing to a project and I'm really not sure what I'm doing. Also, I noticed (here: https://github.com/matplotlib/matplotlib/wiki/MEP12) that new categories are being made for the examples. I'm not sure if this should go under "Text, labels, and annotations," "Subplots, axes, and figures," or something else.

**Comment by tacaswell** [comment]
That failure is an intermittent failure related to Travis step on its own
toes.

**Comment by tacaswell** [comment]
@AmyTeegarden Thank you and congratulations on your first contribution to mpl (and hopefully not the last)!

Documentation is something that we as a community tend to under-do (my self included), but which is as or more important that the code.

You can see the built version of this example at http://matplotlib.org/devdocs/examples/pylab_examples/legend_demo5.html

**Pull request merged**
