### PR TITLE
Simplify 3d axes callback setup.

### PR DESCRIPTION
**Pull request by anntzer**
Always setup the 3d mouse rotate/zoom callbacks and don't store their
cids; instead, handle their disconnection by disabling all mouse buttons
(which has the same observable effect).

This is in preparation of restoring the pan/zoom callbacks upon
unpickling (#10843): after a pickle/unpickle cycle, even if we restore the
callbacks, we can't guarantee that the callback numeric ids will stay
the same, and so self._cids would become incorrect.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by WeatherGod** [comment]
I am a little uneasy about this change. How does the regular 2d axes object handle this stuff? I am also realizing that it was possible to accidentally connect multiple sets of the same callbacks through repeated calls, which is technically "fixed" by this..

**Comment by anntzer** [comment]
2d axes don't generate their own callbacks (they are completely ignorant of the callback system), they are set up by the canvas (more specifically, by the toolbar) and attached to the canvas object.
When unpickling, the figure is attached to a new canvas who may or may not have a toolbar, which again is in charge of the callbacks.

**Comment by timhoffm** [comment]
Please rebase so that Travis can run.

**Comment by anntzer** [comment]
done

**Pull request merged**
