### PR TITLE
Synchronize units change in Axis.set_units for shared axis

### LINKED ISSUE #10304: No link to shared axes for Axis.set_units
### Bug report

**Bug summary**

The `Axis.set_units` method does not emit to linked axes in the same way that `Axes.set_xlim` does (by default).

**Code for reproduction**

```python
from matplotlib import pyplot
from astropy import units
from astropy.visualization import quantity_support

data = units.Quantity([1, 2, 3, 4, 5], 'm')

with quantity_support():
    fig = pyplot.figure()
    ax1 = fig.add_subplot(2, 1, 1)
    ax2 = fig.add_subplot(2, 1, 2, sharey=ax1)
    ax1.plot(data)
    ax2.plot(data)
    print('After first plot:')
    print(ax1.yaxis.get_units())
    print(ax2.yaxis.get_units())
    ax1.yaxis.set_units(units.cm)
    print('After manual set_units():')
    print(ax1.yaxis.get_units())
    print(ax2.yaxis.get_units())
```

**Actual outcome**

```
After first plot:
m
m
After manual set_units():
m
cm
```

**Expected outcome**

If `set_units` was linked to all shared axes, I would expect the call out to `ax1.yaxis.set_units` to also operate on `ax2`.

This is probably best exposed via new `set_xunits` and `set_yunits` methods for the `Axes` object, that include an `emit=True` keyword to use `self._shared_x_axes.get_siblings` in the same way as `Axes.set_{x,y}lim`.

**Matplotlib version**

  * Operating system: macOS 10.13.2
  * Matplotlib version: 2.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'agg'
  * Python version: 2.7.14
  * Jupyter version (if applicable):
  * Other libraries: astropy 2.0.2

all installed with macports.

### LINKED ISSUE #18311: Subplot scatter plot with categorical data on y-axis with 'sharey=True' option overwrites the y-axis labels
### Bug report

**Bug summary**

In the Jupyter Notebook, I tried to create a subplots plot with two scatter subplots with y axis shared for labels and catagorical data on y-axis. The two plots have all the labels common except only one unique label in each data. The plotted unique label of second plot overwrites the unique label of first plot.  Ideally, there should be two points on y-axis, for both the unique entries.

**Code for reproduction**

#Importing necessary modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

#Creating the grid for 2 plots
fig, axes = plt.subplots(1, 2, sharey=True, figsize=(12,4))

#Creating data
ind1 = [0,1,2,3,4]
ind2 = [5,6,7,8,9]

df1 = pd.DataFrame({'Labels': ['Label0', 'Label1', 'Label2', 'Label3', 'Label4'], 
                    'Numbers1': [5, 10, 15, 20, 25],
                    'Numbers2': [10, 15, 20, 25, 30]}, 
                                index=ind1)
                                
df2 = pd.DataFrame({'Labels': ['Label1', 'Label2', 'Label3', 'Label4', 'Label5'], 
                    'Numbers1': [5, 10, 15, 20, 25],
                    'Numbers2': [10, 15, 20, 25, 30]}, 
                                index=ind2)

#First set of data points
axes[0].scatter(x=df1['Numbers1'], y=df1['Labels'])
axes[0].scatter(x=df1['Numbers2'], y=df1['Labels'])
axes[0].grid()

#Second set of data points
axes[1].scatter(x=df2['Numbers1'], y=df2['Labels'])
axes[1].scatter(x=df2['Numbers2'], y=df2['Labels'])
axes[1].grid()

#Setting up titles
axes[0].set_title('Note that Label0 is missing')
axes[1].set_title('Note that labels are wrongly aligned')

plt.show()

**Actual outcome**

Actual Outcome

**Expected outcome**

The expected outcome is that it shows  two different lines on y-axis, for Label0 only the points in first subplot and for Label 5, only the points in second plot. But Y-axis needs to have both Label0 and Label5. I don't know for sure if this worked correctly in the previous versions, however, I have tried a similar graph in plotly module (python) and it works perfectly fine.

**Matplotlib version**

  * Operating system: Microsoft Windows 10 Enterprise (Version: 10.0.17763 Build 17763)
  * Matplotlib version: '3.1.3'
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.7.6
  * Jupyter version (if applicable): jupyter core     : 4.6.1
                                                     jupyter-notebook : 6.0.3
                                                     qtconsole        : 4.6.0
                                                     ipython          : 7.12.0
                                                     ipykernel        : 5.1.4
                                                     jupyter client   : 5.3.4
                                                     jupyter lab      : 1.2.6
                                                     nbconvert        : 5.6.1
                                                     ipywidgets       : 7.5.1
                                                     nbformat         : 5.0.4
                                                     traitlets        : 4.3.3
  * Pandas: '1.0.1'
  * Numpy: '1.18.1' 

I installed anaconda and jupyter notebook, matplotlib etc. are installed with it.

### PR DESCRIPTION
**Pull request by l-johnston**
## PR Summary
Closes #10304
Closes #18311 

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by timhoffm** [comment]
I'm not particularly fond of replicating all `Axis.set_foo` methods to `Axes.set_x/yfoo`. I favor the paradigm `ax.xaxis.set_foo()` over `ax.set_xfoo` for most but the simplest cases (e.g. label).

Having more functionality via `emit` might be seen as a justification, but conversely I argue that functionality should not whether I set it via the Axes or via the Axis. `emit` in `set_x/ylim` is basically a crude hack for synchronizing the `Axis`es without running into recursive updates.

The *proper* solution would be a concept in which an Axis can communicate changes to it's shared siblings. Making the higher level `Axes` responsible for synchronization is fragile. Of course, that's a much harder task.

From the API and logic side I'm -0.9 on this. But I acknowledge that we likely won't get the proper solution any time soon. So this might be bearable as a workaround to get the desired functionality.

**Comment by anntzer** [comment]
Would something along the lines of
```patch
diff --git i/lib/matplotlib/axis.py w/lib/matplotlib/axis.py
index 6d28fae6c..d889785c5 100644
--- i/lib/matplotlib/axis.py
+++ w/lib/matplotlib/axis.py
@@ -1533,11 +1533,22 @@ class Axis(martist.Artist):
         """
         if u == self.units:
             return
-        self.units = u
-        self._update_axisinfo()
-        self.callbacks.process('units')
-        self.callbacks.process('units finalize')
-        self.stale = True
+        if self is self.axes.xaxis:
+            shared = [
+                ax.xaxis
+                for ax in self.axes.get_shared_x_axes().get_siblings(self)]
+        elif self is self.axes.yaxis:
+            shared = [
+                ax.yaxis
+                for ax in self.axes.get_shared_y_axes().get_siblings(self)]
+        else:
+            shared = [self]
+        for axis in shared:
+            axis.units = u
+            axis._update_axisinfo()
+            axis.callbacks.process('units')
+            axis.callbacks.process('units finalize')
+            axis.stale = True
 
     def get_units(self):
         """Return the units for axis."""
```
work? (untested...)

**Comment by timhoffm** [comment]
Looks like that could work. Mildly worried that the last five lines are too low level to be called across Axises and that that should be a possibly private single function of Axis, but 🤷 .

@l-johnston would you be interested in trying out @anntzer's suggestion?

**Comment by jklymak** [comment]
I would need to check, but I think the `axis` unit setting gets called when data are added.  So now the user plots floats on the first axis and then plots datetime on the shared one.  What do we want to happen?  Its not clear to me that we want the first axis to suddenly be changed to datetime units. I'd like to see a few more tests to see how this really behaves if the user does something incorrect.

**Comment by l-johnston** [comment]
yes, @anntzer 's approach works with slight mod.

**Comment by l-johnston** [comment]
@jklymak in the case of an actual unit system implementation such as `unyt`, attempting to set conflicting units on a shared axis raises a unit conversion error.

**Review by timhoffm — APPROVED** [review]
This looks like the right solution to me. Same behavior between `Axis` and `Axes` is to be preferred if possible (and here it is).

@jklymak leaving open, to give you the chance of a final word. Whether pulling up wrappers to `Axes` or accessing the lower level `Axis` is the preferred way, may need a final say but the dev call today showed a tendency for using `Axis`. I agree that Axis docs could use improvement.
 Leaving open, to give @jklymak a chance for

**Pull request merged**
