### PR TITLE
Fix qt5 mouse

### PR DESCRIPTION
**Pull request by tacaswell**
attn @efiring 

This is the last thing for 2.0.1 I believe.

### CODE REVIEW

**Comment by QuLogic** [comment]
So this basically undoes #8144, but that's supposedly fixing a bug. Is there some difference in Qt5 versions being used or sometihng?

**Comment by efiring** [comment]
This is what I am using when seeing the bug:
```
(test) efiring@manini2:~/currents/programs/pycurrents/scripts$ conda list pyqt
# packages in environment at /Users/efiring/anaconda/envs/test:
#
pyqt                      5.6.0                    py35_0
```

**Comment by QuLogic** [comment]
What about qt?

**Comment by efiring** [comment]
```
(test) efiring@manini2:~/currents/programs/pycurrents/scripts$ conda list | grep -i qt
ipython-qtconsole         4.0.1                    py35_0
pyqt                      5.6.0                    py35_0
qt                        5.6.0                         0
qtawesome                 0.3.3                    py35_0    conda-forge
qtconsole                 4.2.1                    py35_1
qtpy                      1.1.2                    py35_0
```

**Comment by tacaswell** [comment]
@QuLogic I _think_ the bug was in @astrofrog 's example code.  Internally we need to use the the pixels the renderer thinks it has not the pixels qt thinks it has.

**Comment by tacaswell** [comment]
attn @astrofrog Can you test this out with both qt5 and osx?

**Comment by tacaswell** [comment]
I still suspect that there are a bunch of un-needed scaling factors in there (as we scale up one place and down in the other), but it is not clear exactly _which_ pairs of them need to be pulled out.

**Comment by tacaswell** [comment]
And I am working on a "high-dpi" style sheet.

**Comment by astrofrog** [comment]
@tacaswell - can you mark me as a reviewer so that I don't lose track of this, and I'll review/test it on Monday

**Comment by efiring** [comment]
I'm running into a new problem with this: it is hanging my terminal after I kill a plot window and try to plot again.  This is with ipython 5.3, to which I changed from ipython 5.1 today; I don't know whether that is related. I am using "ipython --pylab" for this testing.

**Comment by efiring** [comment]
I deleted a comment about this hanging my terminal; it seems to have been caused by an ipython version update.

**Comment by efiring** [comment]
@tacaswell, your suggestion of adding back the block that was deleted at the end of cedaaae works fine; I think that with that change, this is ready for 2.0.1.

**Comment by astrofrog** [comment]
Sorry I dropped the ball on reviewing this, I won't have time to check it in the short term but I don't want to delay 2.0.1, so this is fine by me.

**Comment by tacaswell** [comment]
@efiring Can you test this set of commits (I force-pushed).

There is one more thing I want to add (but might not be worth holding PR over) is to connect up the signal Qt provides when the dpi ratio changes.

**Comment by efiring** [comment]
In my quick check, it looks good and works perfectly.  I tested saving to png via the gui, manual resizing, get_size_inches and set_size_inches, cursor readout, and zoom to rect.

**Comment by efiring** [comment]
In my quick check, it looks good and works perfectly.  I tested saving to png via the gui, manual resizing, get_size_inches and set_size_inches, cursor readout, and zoom to rect.

**Pull request merged**
