### PR TITLE
Support generative tests in @cleanup.

### PR DESCRIPTION
**Pull request by anntzer**
All's in the title.

### CODE REVIEW

**Comment by anntzer** [comment]
Rebased #5785 onto this, just to show that this implementation works.

**Comment by tacaswell** [comment]
:+1: that is way simpler than I expected it to be!

**Comment by anntzer** [comment]
Hum...  I am pretty sure that the `cleanup` decorator (in its old version) made nose silently skip `test_axes.test_remove_shared_axes`, which has then been (effectively) broken in some later commit.  Can you investigate?

**Comment by tacaswell** [comment]
Huh, good catch.  I will try to take a look at that tomorrow.

**Comment by mdboom** [comment]
Thanks.  We were just talking about this in #5718.

**Comment by tacaswell** [comment]
I do not have a clear memory of writing that test (but git blame tells me I did!).  Sometimes I work in a tdd style where I just run the tests to check things so that test may have never worked.

For expediency of getting this merged, maybe throw a KnownFail on this create an issue telling me to fix the test.

**Comment by anntzer** [comment]
Done.  By the way, why was the *previous* AppVeyor build successful even though the test suite failed?  (I am a bit confused.)

**Comment by anntzer** [comment]
I am even more confused by the new test failure.  Anyone wants to take over this PR?  (TBH I have little interest in investigating this.)

**Comment by tacaswell** [comment]
Did you run these locally?  That error is what happens if the test module is not importable.

**Comment by tacaswell** [comment]
Turns out the fix is trivial, there is just an extra `assert` before the `assert_array_equal`.  The function was not raising, so returning `None` which fails the assert.

**Comment by tacaswell** [comment]
I am going to do some local git merging to:

 - drop the second commit of this PR
 - add a commit to fix the test
 - backport the whole thing to v1.5.x

**Comment by tacaswell** [comment]
Actually, I am having issues getting this to pass locally and am getting a large number of file not closed warnings, see https://github.com/anntzer/matplotlib/pull/1

**Comment by anntzer** [comment]
Actually my original patch was wrong... can you see why?  It's fixed now.

**Comment by tacaswell** [comment]
backported to v2.x as 80be85391bbe4a32f12cbcdcf62c9b131128f34b

**Pull request merged**
