### PR TITLE
update documentation after #18966

### PR DESCRIPTION
**Pull request by impact27**
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
@oscargus mentioned in https://github.com/matplotlib/matplotlib/pull/22202#discussion_r790141546 that there is also an example that needs to be fixed?

Would it be better to fix the return or as that impossible with the other changes now?

**Comment by impact27** [comment]
I don’t think returning something would be good as this is clearly not a synchronous operation. I think the callback is a better solution to get a return valie

**Comment by impact27** [comment]
Where is this example?

**Comment by tacaswell** [comment]
They are in a `if __name__ == "__main__":` at the bottom of this file https://github.com/matplotlib/matplotlib/blob/fd51e059690266d55f62b82c46d4e8fdb45afa9c/lib/matplotlib/backends/qt_editor/_formlayout.py#L542-L585

**Review by tacaswell — APPROVED** [review]
Still approve after edits

**Review by timhoffm — APPROVED** [review]

**Comment by tacaswell** [comment]
The test failure is `test_fork` merging over that because we understand it (regression from coverage 6.3) and it is fixed on main.

**Pull request merged**
