### PR TITLE
Corrected docstring for artist.Artist.set_agg_filter

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

https://github.com/matplotlib/matplotlib/issues/23050

### CODE REVIEW

**Comment by oscargus** [comment]
Can you please shorten the lines to 79 characters? (This is where linting complains.)

The ideal way is to change it, do `git commit --amend` (after adding the files) and then `git push origin <branchname> --force-with-lease` to avoid multiple commits.

**Comment by SaumyaBhushan** [comment]
@oscargus Please review.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
Thank you @SaumyaBhushan .  Congratulations on your first merged Matplotlib PR 🎉 !  Hopefully we will hear from you again.

**Comment by SaumyaBhushan** [comment]
Thanks a lot @tacaswell 🥳

**Pull request merged**
