### PR TITLE
Improve formatting of "Anatomy of a figure"

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

- Simplify code
- Adapt margins
- Reduce figure border width (still thick but not massive)
- Code formatting: use monospace and `()` when it's a function
- slightly move annotations to better places

### CODE REVIEW

**Comment by timhoffm** [comment]
Still have to grab the static image from the doc build (too lazy to build locally).

**Review by jklymak — APPROVED** [review]
Feel free to merge once the static image is added.

**Comment by timhoffm** [comment]
Note I intentionally reduced the size from 800px to 750px because 750 is the max-width in the pydata-sphinx-theme. 800px would be resampled by the browser.

**Comment by jklymak** [comment]
Is that hi dpi though?  I think in the case where we have a static image we should always serve as hi dpi.  Lo dpi plots look really bad on a 2x display.

**Comment by timhoffm** [comment]
Yes, if you Check the image it‘s 1500 px.

**Comment by timhoffm** [comment]
@meeseeksdev backport to v3.5.x

**Pull request merged**
