### PR TITLE
Backport PR #16255 on branch v2.2.x (Move version info to sidebar)

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Backport PR #16255 on branch v2.2.x (Move version info to sidebar).

Need to check that styling is correct via the CI built version of the docs.
I couldn't easily build 2.2.x docs locally probably because my dev env is not compatible to 2.2 anymore.

### CODE REVIEW

**Comment by tacaswell** [comment]
@timhoffm I think you have to rebase this branch for circle to pick up the change.

**Comment by timhoffm** [comment]
Yes, I was busy yesterday. Will do tonight. If you need itvearlier, feel free to rebase and push to this branch.

**Comment by tacaswell** [comment]
Builds cleanly locally, will merge as soon as CI passes.

**Comment by timhoffm** [comment]
Thanks for fixing this,

**Pull request merged**
