### PR TITLE
DOC: Update link to IBM's colormap selection paper

### PR DESCRIPTION
**Pull request by saketkc**
## PR Summary

Small doc change that fixes broken link to IBM's color selection paper.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
Thanks for the contribution!

Even though http://www.research.ibm.com/people/l/lloydt/color/color.HTM looks like a specialized address, it seems to just bring me to the general reseach entry page of IBM. Can you please recheck this?

**Comment by saketkc** [comment]
Hi @timhoffm, that's correct. That seems to be a default page for a 404. For example:
https://www.research.ibm.com/whatever.html

**Comment by matthew-brett** [comment]
If you search the IBM site for "select colormap" you get the page as the top hit, with the address you've given, so I think the link is correct, but IBM's site isn't working correctly.

**Comment by timhoffm** [comment]
The article seems to be gone from the IBM site. http://www.citeulike.org/user/akavipat/article/5983364 references the article via the similar address http://researchweb.watson.ibm.com/people/l/lloydt/color/color.HTM, which also just gets redirected to the start page.

There's a copy on github: https://github.com/ResearchComputing/USGS_2015_06_23-25/blob/master/25_June/ColorTheory_References/Why%20Should%20Engineers%20and%20Scientists%20Be%20Worried%20About%20Color.pdf, but I'm not sure we want to link to that.

**Comment by saketkc** [comment]
Will the archive link not be okay?

The paper seems to be here (b & w): http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.452.1807&rep=rep1&type=pdf

**Comment by jklymak** [comment]
Please reference by DOI if available, then we aren't at the mercy of changing websites.  If there is  a free version that can be linked as well  http://ultra.sdk.free.fr/docs/Image/Colors/A%20Rule-based%20Tool%20for%20Assisting%20Colormap%20Selection.htm

http://dx.doi.org/10.1109/VISUAL.1995.480803

**Comment by NelleV** [comment]
Thanks @saketkc !

**Pull request merged**
