### PR TITLE
subplots generator

### PR DESCRIPTION
**Pull request by prinsherbert**
Returns a generator yielding the subplots row-column order and creates new figures when all subplots in the previous were yielded and a new one is requested.

This is helpful for experiments where for example one wants to get a quick overview of some random samples from an image data set or simply display a lot of plots.

Imagine needing to plot ~250 plots, separate figures would clutter the window manager, one subplot grid would make the plots to small, but a trade-off between subplots and different windows can work. This would however require two for-loop constructs, a nested double loop iterating over the figures and axes and a single-loop iterating over data samples. That is a nuisance to combine.

I found myself and coworkers using this feature in ipynotebooks. one can simply iterate over `zip(data, pyplot.subplots_iterator(ncols=6))` and plot each sample in some manor.

Generator can be used concurrently transparent as well by 

    axes = pyplot.subplots_iterator(ncols=6)`
    for data, ax0, ax1 in zip(data, axes, axes):
        # ...

In general this results in very 'pythonic' code and removes some boilerplate code when reporting results of experiment (as I typically do in ipynb's).

### CODE REVIEW

**Comment by prinsherbert** [comment]
I seem to have problems with images not being close during one run, and being the same the other due to slightly shifted characters. Is there a reason why this non-deterministic text-rendering happens?

**Comment by tacaswell** [comment]
Isn't there another PR with very similar code?

**Comment by prinsherbert** [comment]
> Isn't there another PR with very similar code?

Yes, I forgot to mention it: this one https://github.com/matplotlib/matplotlib/pull/6400

**Comment by prinsherbert** [comment]
Just to make it clear, I created a new PR because now this feature is separate from the encode_as-feature, and I implemented it in pyplot only and not in figure. The latter made no sense (in retrospect), because the generator uses 0 or more figures. Also the code is simpler and I added a test case (which fails unfortunately, due to text-rendering glitches)

**Comment by prinsherbert** [comment]
It seems that except for a pep8-related problem the only issue now is:

`Downloading http://download.savannah.gnu.org/releases/freetype/freetype-2.6.1.tar.gz
error: [Errno socket error] [Errno 10060] A connection attempt failed because the connected party did not properly `

**Comment by anntzer** [comment]
Similarly to the discussion in #6400 I'm not sure we need to add a function for something as simple as
```
chain.from_iterable(plt.subplots(x, y, squeeze=False)[1].flat for _ in repeat(None))
```

**Comment by prinsherbert** [comment]
> Similarly to the discussion in #6400 I'm not sure we need to add a function for something as simple as
> 
> `chain.from_iterable(plt.subplots(x,` y, squeeze=False)[1].flat for _ in repeat(None))`
> 
> (although the idea is cute).

Well, your idea is slightly less readable, especially for something as simple. If you wish to write it explicitly, I would suggest:

    (ax for _ in repeat(None) for ax in pyplot.subplots(....., squeeze=True))

But maybe I try to avoid itertools too much. Nevertheless, pyplot.subplots_generator(...) would still have my preference, as it requires no extra repeat import and can be used elegantly within the zip of a for-loop. Either expression is quite long and would mention `for` 3 times.

But I have to admit, I came up with my generator expression after this pull request, and also started doubting the need for the` subplots_generator`.

PS: Why did almost all the tests complete green all of a sudden? I remember seeing a lot more red :S

**Comment by anntzer** [comment]
Actually you can have it without relying on itertools at all:
```
(ax for fig, axs in iter(lambda: plt.subplots(2, 2, squeeze=False), None)
    for ax in axs.flat)
```

**Comment by anntzer** [comment]
Closing since the OP agrees that the need for `subplots_generator` is doubtful.  Feel free to let me know if you think otherwise.

**Comment by prinsherbert** [comment]
I was actually was hoping for more, diverse opinions, I am very much pro-subplots-generator as it results in readable pythonic code for experiments, but admit that I am only one voice (plus maybe one for co-worker who also used my subplots generator).

Nevertheless, it seems a bit quiet regarding that discussion :(

**Pull request closed without merging**
