### PR TITLE
Solve the issue that some fonts are not handled correctly

### PR DESCRIPTION
**Pull request by cy18**
## PR Summary

This pull request fixes the problems I found when I try to use "Noto Serif CJK" and "Source Han" font families.
1. In some fonts the font information are not given by Platform ID 1, but by Platform ID 3. 
1. The weight "thin" and "demilight" are used by some fonts, which is not handled correctely.
1. When judging weight, there's a problem that "demibold" may be judged as "bold", "ultralight" may be judged as "light". This can be fixed by testing weight names in the order of  names' length.

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/whats_new.rst if major new feature
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Could you post a short bit of code to demonstrate what specifically wasn't working before this fix?

**Comment by cy18** [comment]
Most fonts in "Noto Serif CJK" and "Source Han" families does not work before fix. 

Please download font files from the following link and take a try. You will know what I'm talking.

https://noto-website.storage.googleapis.com/pkgs/NotoSansCJKtc-hinted.zip

Please comment if you need any further information.

**Comment by cy18** [comment]
First, please download the otf files from https://noto-website.storage.googleapis.com/pkgs/NotoSerifCJKsc-hinted.zip 

Don't forget deleting the cache file ".matplotlib/fontList.json" before each testing.

Run the following code:

    from matplotlib import font_manager
    print(font_manager.findfont('noto serif cjk sc'))

Before fixing, the result is 'C:\\Windows\\Fonts\\NotoSerifCJKsc-Light.otf'.
After fixing, the result is 'C:\\Windows\\Fonts\\NotoSerifCJKsc-Regular.otf'.

With following code:

    from matplotlib import ft2font
    ft = ft2font.FT2Font('C:\\Windows\\Fonts\\NotoSerifCJKsc-Regular.otf')
    print(ft.get_sfnt())
    
We can see that the reason is that font informations are missing at (1,0,0,2) and (1,0,0,4). However the information could be found at (3,1,1033,2) and (3,1,1033,4).

**Comment by tacaswell** [comment]
xref https://github.com/matplotlib/matplotlib/pull/8551

**Comment by anntzer** [comment]
Superseded by #16203; thanks for the pr.

**Pull request closed without merging**
