### PR TITLE
Add test_barh to test_datetime.py

### PR DESCRIPTION
**Pull request by CozyFrog**
## PR summary
I have added a datetime/timedelta smoke test for `Axes.barh` in `lib/matplotlib/tests/test_datetime.py`.
This addresses the `Axes.barh` task from #26864.

The image below is the plot generated from this smoke test/example code.
barh_smoke_test

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Review by ksunden — CHANGES_REQUESTED** [review]
See comment from https://github.com/matplotlib/matplotlib/pull/27033#pullrequestreview-1665154088:

(Copied here for convenience, note that it was written originally for `bar`, so swap horizontal/vertical etc, but the sentiment is the same)


I think the bar graphs with dates on the vertical (for `bar`, horizonatal for `barh`) axis should be given a bit more care here. That there is an implicit `0` mark, which results in `1970-01-01` is not a particularly good representation of a bar plot.

I think that for this, there should be a `bottom` argument specified as a datetime and then using a `timedelta` instead of a `datetime` for the heights, as indicated by the `bar` [docstring](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.bar.html#matplotlib.axes.Axes.bar)

Here is some code I wrote for someone who had started working on this but never opened a PR:

```python
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime, timedelta
import matplotlib as mpl

mpl.rcParams["date.converter"] = 'concise'
fig, (ax1, ax2) = plt.subplots(2, 1, layout='constrained')
price_date = np.array([  datetime(2020, 6, 30),
                datetime(2020, 7, 22),
                datetime(2020, 8, 3),
                datetime(2020, 9, 14)], dtype=np.datetime64)

price_close = [8800, 2600, 8500, 7400]
start_date = np.datetime64(datetime(2020, 6, 1))

ax1.bar(price_date, price_close, width=np.timedelta64(4, "D"))
ax2.bar(np.arange(4), price_date-start_date, bottom=start_date)
```

Note the `start_date` and `price_date-start_date` in this example.

**Comment by ksunden** [comment]
I would also rather explictly _avoid_ having the times be in 1970 to make sure we arent falling into certain traps with datetimes.

**Comment by CozyFrog** [comment]
Thank you so much for your notes and sample code, I appreciate the help!

**Comment by CozyFrog** [comment]
I have made a few fixes.
- The test now consists of two subplots; one passes datetime and timedelta arguments to the `y` and `height` parameters respectively, and the other passes timedelta and datetime arguments to the `width` and `left` parameters respectively.
- The times are in 2020 now to avoid any datetime traps.

Below is an image of the new test:
barh_smoke_test_second_pr

**Review by ksunden — APPROVED** [review]

**Review by QuLogic — APPROVED** [review]

**Comment by QuLogic** [comment]
Thanks @CozyFrog! Congratulations on your first PR to Matplotlib :tada: We hope to hear from you again.

**Pull request merged**
