### PR TITLE
Remove reference to changelog from frontpage

### PR DESCRIPTION
**Pull request by jenshnielsen**
Fixes link checker issue in documentation as discussed with @tacaswell

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This seems to ultimatly be caused by a IPython/Traitlets issues:

At the end of the docs build we are seeing:
```bash
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/IPython/core/history.py", line 547, in end_session
    len(self.input_hist_parsed)-1, self.session_number))
sqlite3.OperationalError: disk I/O error
Fatal Python error: PyImport_GetModuleDict: no module dictionary!
Current thread 0x00007ff58684b700 (most recent call first):
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/traitlets/traitlets.py", line 1136 in on_trait_change
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/IPython/core/extensions.py", line 64 in __del__
Aborted (core dumped)
```

The SQL error is old and repoted to ipython in ipython/ipython#8850 and should be fixed in IPython 4.1
The seqfault is new and I guess related to the release of a new traitlets release.

**Comment by jenshnielsen** [comment]
I have reported the Ipython Traitlets issue in https://github.com/ipython/traitlets/issues/162

**Comment by jenshnielsen** [comment]
It looks like the issue only happens on the master branch which uses Python 3.5 to build the docs

**Comment by jenshnielsen** [comment]
This is not the prober fix but we might still want to remove that link and perhaps retire the changelog?

**Comment by tacaswell** [comment]
backported to v1.5.1-doc as 6db0faf

**Pull request merged**
