### PR TITLE
Add textloc="best" for Annotation

### PR DESCRIPTION
**Pull request by iburinoc**
## PR Summary

Adds support for `textloc='best'` option for `axes.annotate` and `Annotation`, implementing the request from #4489.

The selection logic is the same as the one used in `legend.py`, it was refactored out to `_auto_placement.py`.  In #4489 it was suggested that the functions be moved to cbook but it relied on other matplotlib geometry classes so from what I understand that cbook wouldn't be a good place for it because of the import limitations there.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
Welcome to Matplotlib and thanks for the contribution!

Generally, I like the idea of automatically placing annotation labels in "good" positions. Some things to consider:

- We do not need an extra kwarg for that. You can use `xy='best'`.
- I'd rather call the value 'auto' instead of 'best' since there is no optimal position.
- I'm not convinced that the naive placement algorithm used for legends is a suitable choice for annotations. There's a fundamental difference between a good annotation position and a good legend position. Legends are usually best placed at some edge or corner to not distract from the plot contents. On the other hand, annotations are explicitly there to draw attention and are usually placed more to the center. I would find it quite awkward to have an annotation label sqeezed in the bottom right corner as in the `annotation_best_location_complex.png` example.

**Comment by jklymak** [comment]
In general I don’t see how you can automagically place annotations, unless there are no arrows associated with them.  Is that the use case here?

**Comment by Tillsten** [comment]
There are still uses cases for automatic text placement. Sometimes the kind of legend matplotlib offers is not what I want and instead I just use coloured text, which I have to place manually now.  Since I have to use multiple Text objects for the colored text, this still wont work, but I think there are similar use-cases where the offered solution is good enough.

**Comment by timhoffm** [comment]
Thanks all for the constructive discussion.

**Comment by andrzejnovak** [comment]
@anntzer @timhoffm I'd like to chime in. I find myself adding annotations to many plots as a way to display additional information about what's shown (for example data preselection). It's usually not suitable to show these as part of the legend header, either because it's not directly related to the legend entries or just formatting in general. So in case I have two "free" corners on the plot, an automated legend('best') -> one corner, and annotate('best') -> the other one would be very nice.

**Comment by ImportanceOfBeingErnest** [comment]
@andrzejnovak I think what you're asking for is rather a `loc="best"` option for [`AnchoredOffsetbox`](https://matplotlib.org/3.1.0/api/offsetbox_api.html#matplotlib.offsetbox.AnchoredOffsetbox), such that one could write `AnchoredText("my text", loc="best")`. This is very different from what this PR suggested, and most concerns raised here would not even apply.    
So it would be totally possible and completely similar to how the legend's best-option works.

**Comment by jsh9** [comment]
@ImportanceOfBeingErnest As a matplotlib user, I would really like to see a `loc="best"` implemented for `AnchoredOffsetbox`. However I have a question: if I'd like to add both an anchored offset box and a legend to the same axes, is it possible to use `loc="best"` for both of them? How would the expected behavior be?

**Comment by ImportanceOfBeingErnest** [comment]
@jsh9 I can imagine it to make sense to open a new issue for this feature request, such that it can be tracked. The current algorithm to find the "best" position for the legend only takes data inside the axes into account. If two legends are placed, both with loc="best", chances are high that they overlap. The same would happen with an AnchoredOffsetbox and a legend. Taking into account existing boxes makes this all more complicated.

**Pull request closed without merging**
