### PR TITLE
Improve Demo Text Rotation Mode

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

- Rewrote description.
- Improved layout, giving more visual focus on the relation between the label and the reference point.

[Old example](https://matplotlib.org/gallery/text_labels_and_annotations/demo_text_rotation_mode.html)

[New example](https://19147-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/text_labels_and_annotations/demo_text_rotation_mode.html#sphx-glr-gallery-text-labels-and-annotations-demo-text-rotation-mode-py)

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
I think I liked the old design better, mainly because each case got its own carré, so the alignment is easier to grasp. 

Also I think showing the bounding box in case of the `"default"` rotation would make the concept clearer.

image

**Comment by timhoffm** [comment]
Thanks, showing the bbox is a good idea I've taken over that approach.

**Comment by ImportanceOfBeingErnest** [comment]
Drawing the figure multiple times is probably inefficient. Below the example it says 2 seconds, which seems a lot. Maybe one can externalize the part where the rectangles are drawn, such that figure only needs to be drawn once, like

```
    texts = []
    for va in va_list:
        for ha in ha_list:
            ax = grid[i]

            # prepare axes layout
            for axis in ax.axis.values():
                axis.toggle(ticks=False, ticklabels=False)
            ax.axis([0, 1, 0, 1])
            ax.axvline(0.5, color="skyblue", zorder=0)
            ax.axhline(0.5, color="skyblue", zorder=0)
            ax.plot(0.5, 0.5, color="C0", marker="o", zorder=1)

            # add text with rotation and alignment settings
            tx = ax.text(0.5, 0.5, "Tpg",
                         size="x-large", rotation=40,
                         horizontalalignment=ha, verticalalignment=va,
                         rotation_mode=mode, **kw)
            texts.append(tx)
            i += 1

    if mode == "default":
        # highlight bbox
        fig.canvas.draw()
        for i, tx in enumerate(texts):
            bb = tx.get_window_extent().inverse_transformed(grid[i].transData)
            rect = plt.Rectangle((bb.x0, bb.y0), bb.width, bb.height,
                                 facecolor="C1", alpha=0.3, zorder=2)
            grid[i].add_patch(rect)
```

**Comment by timhoffm** [comment]
Only drawing once saves about 25% of the time. I guess a significant part of the time goes into creating the axes. Anyway, the code is better, so I've applied it. Thanks.

**Comment by QuLogic** [comment]
Looking at the gallery for this, I also found [this example](https://19181-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/text_labels_and_annotations/text_rotation.html#sphx-glr-gallery-text-labels-and-annotations-text-rotation-py); should we merge them together? I like the new look here, but the other one has some textual explanation as well.

**Comment by timhoffm** [comment]
I’ve seen the other rotation example as well. In principle it would make sense to merge them. However`, I‘ve decided not do it as part of this PR to keep the the changes more managable. Sorting out styling was the main focus of this PR. I‘m happy to do a follow-up.

**Comment by NelleV** [comment]
Thanks @timhoffm !

**Pull request merged**
