### PR TITLE
Allow sharing Locators and Formatters across Axises.

### LINKED ISSUE #19988: Removal of x-shared polar axes causes crash
### Bug report

**Bug summary**

All's in the title.

(Note that x-sharing (which really means theta-sharing) polar axes makes sense because one can use set_thetalims to draw just a wedge.)

**Code for reproduction**

```python
from pylab import *
ax1, ax2 = gcf().subplots(2, sharex=True, subplot_kw={"projection": "polar"}); ax2.remove()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File ".../path/to/matplotlib/artist.py", line 162, in remove
    self._remove_method(self)
  File ".../path/to/matplotlib/figure.py", line 967, in delaxes
    _reset_locators_and_formatters(last_ax.xaxis)
  File ".../path/to/matplotlib/figure.py", line 930, in _reset_locators_and_formatters
    isDefault = majloc.axis.isDefault_majloc
AttributeError: '_AxisWrapper' object has no attribute 'isDefault_majloc'
```

**Expected outcome**

Normal axes removal.

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): head
  * Matplotlib backend (`print(matplotlib.get_backend())`): mplcairo
  * Python version: 39
  * Jupyter version (if applicable): 
  * Other libraries: 

#13482 happens to fix this, because it moves handling of isDefault_\* to the tickers themselves (where they logically belong), rather than having them on the axis.

(Note that this is a separate issue from https://github.com/matplotlib/matplotlib/issues/19989 as the root cause seems very different.)

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

Perhaps a better solution than #13439 to #13438.

Needs tests.

There's still quite a bit of code, but it's much less involved I think.

Edit: also closes #19988 as a side effect.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
So, the fundamental idea of this PR is to reassign the axis whenever we‘re obtaining the locator/formatter from the axis?

This feels quite hacky, because reading an axis property modifies the state of the returned object. I wouldn‘t expect axis.locator to modify any state. It‘s probably working for the common use cases. But one can certainly construct code with surprising effects based on this PR.

**Comment by anntzer** [comment]
> So, the fundamental idea of this PR is to reassign the axis whenever we‘re obtaining the locator/formatter from the axis?

Yes.

> This feels quite hacky, because reading an axis property modifies the state of the returned object. I wouldn‘t expect axis.locator to modify any state. It‘s probably working for the common use cases. But one can certainly construct code with surprising effects based on this PR.

If the locator/formatter is used on only one axis, this doesn't change anything.  If it is used on multiple axises simultaneously, this at least fixes certain cases that were previously not working.

**Comment by ImportanceOfBeingErnest** [comment]
Possibly relevant for further discussion: [Here](https://stackoverflow.com/questions/55010236/set-major-locator-removes-x-ticks-and-labels-from-previous-subplots) is a real user struggling with reusage of tickers.

**Comment by anntzer** [comment]
A side effect of rebasing showed that the isDefault_{maj,min}{loc,fmt} attributes should also really live on the ticker instances; moving them there (using properties to redirect access, yada yada) gave a nice simplification over https://github.com/matplotlib/matplotlib/pull/14997.

**Comment by efiring** [comment]
> If we really want to "fix" this, I think a better solution may be to make ticker not store the axis info and make get_major_formatter() (and friends) create a temporary FormatterWithAxisAttached object that wraps the Formatter and attaches the Axis info to it.

The proposal by @anntzer  at the end of https://github.com/matplotlib/matplotlib/pull/13439#issuecomment-466164895 (above) seems like the cleanest solution, given the way we are boxed in by back-compatibility constraints.  Conceptually, it seems like the fundamental problem is that the machinery--the algorithm and initialized parameters of a given ticker--should be fully shareable and re-usable, only needing to be created once by the user if it is needed multiple times.  Info from the axis should be supplied when needed for the machinery to run--when generating specific ticks or strings.  Ideally, perhaps the tickers would have been designed so that each method takes the axis, or the info required from the axis, as an explicit argument instead of referring to a stored axis attribute.

If I understand correctly, the present proposal is supplying that axis info by modifying a possibly shared instance each time it is accessed for use; I agree with @timhoffm that this doesn't feel quite right, though I also see its advantage over the present situation.

I think the proposal in the cited comment would get us closer to what we actually want, but I don't know what obstacles it would run into.

**Comment by anntzer** [comment]
IIRC (it's been a while, didn't have a look again, just typing this from memory) the problem with FormatterWithAxisAttached is that it's even more work to implement and you need to make sure that it quacks enough like a normal Formatter, and then if someone calls get_major_formatter() and modifies that instance in-place (via one one the numerous setters that exist) they certainly expect the real formatter for be modified so you need to send the updates back to the underlying real Formatter.  Well, you can always give it a try :-)

**Comment by jklymak** [comment]
Can we make an issue that shows what breaks due to the sharing?  I'm not sure this approach is the easiest one, but maybe there are use cases I a not understanding.

Naively I'd just make a copy of the locator or formatter if `self.axis` is not `None` when we call `set_major_formatter` or `set_major_locator` etc...

**Comment by anntzer** [comment]
@jklymak I think the issues are described in https://github.com/matplotlib/matplotlib/issues/13438#issuecomment-733921930 and the subsequent discussion?

**Comment by jklymak** [comment]
I'm marking draft for now until we resolve the design here.  Maybe better done in #13438....

**Comment by anntzer** [comment]
Ditto https://github.com/matplotlib/matplotlib/pull/13439#issuecomment-1569647381.

**Pull request closed without merging**
