### PR TITLE
removing unused DialogLineprops from gtk3

### PR DESCRIPTION
**Pull request by fariza**
The class DialogLineprops was copied from gtk2 to Gtk3 but it doesn't work.
Also it is not used anywhere.

### CODE REVIEW

**Comment by tacaswell** [comment]
should this be backported to 2,x?

**Comment by fariza** [comment]
It doesn't fix anything, just removes dead code. It depends on the policy/criteria for back-porting stuff

**Comment by tacaswell** [comment]
backported to v2.x as 25bdedd

Why ship code we know is broken and unused?

**Comment by OceanWolf** [comment]
Just rebasing MEP27 and noticed this had gone... as it exists as a Qt tool, I had thought about rewriting this as a generic tool for all backends, i.e. replacing the native widgets with matplotlib versions of the widgets, making it a backend independant tool like subplots tool becomes in MEP27.

Not really super keen on spending time doing that, but otherwise we would either have to write code that only adds that tool for Qt, or loose it together, which may well see lots of complaints...

**Comment by tacaswell** [comment]
Losing the Qt version is a non-starter

**Comment by OceanWolf** [comment]
I thought so ;)... just that with the new toolbar, we have a default list of tools which get applied independent of backend.  Without a nasty hack, implement lineprops as a backend independent tool would probably look the nicest, no nasty hacking.

**Pull request merged**
