### PR TITLE
add hsl_to_rgb function

### PR DESCRIPTION
**Pull request by sinaze**
Add a function to convert arrays of HSL values to RGB. Inspired by and using the overall structure of the already existing hsv_to_rgb function.

Useful, at least in my case, to plot HSL valued arrays using pyplot.imshow(), e.g. for visualizing complex valued mathematical functions (domain coloring, etc.).

## PR Checklist

- [ ] Has Pytest style unit tests
- [x ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x ] New features are documented, with examples if plot related
- [x ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
This doesn't seem like too outlandish a request, though I think Matplotlib is somewhat hesitant to be a general purpose color manipulation library.  This PR would definitely need some tests, and ideally some references to argue that you have implemented the conversion correctly and in a way thats standard.  Is this compatible with `colorsys`?

**Comment by anntzer** [comment]
Also the implementation seems quite complicated; would it be easier e.g. to first convert hsl to hsv and then simply pipe that into hsv_to_rgb?

**Comment by dstansby** [comment]
Does `colorsys.hls_to_rgb(h, l, s)` work with arrays? If so I'd be inclined to say we shouldn't include this.

**Comment by dstansby** [comment]
Thanks for opening this PR. Since this functionality appears to be available in the `colorsys` library, I don't think it's worth duplicating in Matplotlib unless we have a reason to use it internally. If anyone disagrees and would like to see this in, feel free to either open an issue, or pick up this PR and add tests and I can re-open it.

**Pull request closed without merging**
