### PR TITLE
ENH: call update_ticks before we return them to the user

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Currently, `get_x/yticks` doesn't work until a draw is called. But we can update the ticks, so why not?

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
This one is pretty basic; if someone asks for the ticks on an axis, I don't see why we would force them to do a whole draw...

**Review by timhoffm — CHANGES_REQUESTED** [review]
That this is so basic makes me suspicious: Why haven't we done such a simple thing before?

My first guess "we use it heavily in the codebase (and it thus might be a performance issue)" is not correct. Apart from one usage in `SecondaryAxis` this is only used in tests an a tutorial. Why? Because internally we use `get_minorticklocs()` and `get_majorticklocs()`. Since both of them are public API as well, they should have the same update state as `get_ticklocs()`. I.e. if we update that should happen in there.

Now, I'm not sure what the implication of that would be. `_update_ticks()` queries `get_minorticklocs()` and `get_majorticklocs()` so we'd need to have a closer look on that cyclic usage. It might also be the case that we should make the current `get_major/minorticklocs` private for internal use without update and have change the public variants to use updates.

Anyway I'm afraid only adding `_update_ticks()` here is too simple.

**Comment by jklymak** [comment]
I'm actually confused now what prompted this.  Going back to 3.3.0 

```python 
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()

ax.plot(np.arange(100))
print(ax.xaxis.get_majorticklocs())
print(ax.xaxis.get_minorticklocs())
print(ax.get_xticks())
```

works as expected.  So I'll close this until we can remember why this was an issue.

**Comment by QuLogic** [comment]
This was re-done by #23170, because it wasn't really working as stated above.

**Pull request closed without merging**
