### PR TITLE
Fixed broken `test_pickle.test_complete` test

### LINKED ISSUE #6839: Test `test_pickle.test_complete` is broken
I am pretty much sure that `test_pickle.test_complete` does nothing.
Evidences:
  - After running `python tests.py matplotlib.tests.test_pickle` there is no `result_images` folder
  - This test passes even with adding `assert False` to the top of the function

This behavior is caused by using simultaneously the `cleanup` and `image_comparison` decorators.
I suggest removing the `cleanup` decorator and regenerate baseline image (PR #6840).

The bug comes from https://github.com/matplotlib/matplotlib/commit/d595fe391a27cd925def4c8f608316caeb2b5de9 (PR #4264)

### PR DESCRIPTION
**Pull request by Kojoley**
Fixes #6839

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Looks right to me. The cleanup and image_comparison decorators should not be used together.

**Comment by tacaswell** [comment]
This does not backport cleanly due to subtle changes in the stream plot.

attn @afvincent

**Comment by tacaswell** [comment]
I screwed up and pushed this backport to upstream as aaeaffd9a0bc7d02cf3eab1566b41beac55b95e8  I am going to give travis a chance to confirm that it fails and then revert it.

**Comment by tacaswell** [comment]
Reverted the backport to un-break 2.x as c9c2bfe2fc7bcde5f26b151c1a3c0f9940bb5ebd

Sorry folks :sheep:

**Pull request merged**
