### PR TITLE
Fix `axline` for slopes <= 1E-8. Closes #28386

### LINKED ISSUE #28386: [Bug]: Minor issue - Drawing an axline sets slopes less than 1E-8 to 0
### Bug summary

Very minor issue in which calling Axes.axline() with a sufficiently small slope creates a horizontal line. axline() uses numpy.close() with default parameters to set slopes with absolute value less than 1E-8 (numpy's default) to 0.

### Code for reproduction

```Python
import matplotlib
import matplotlib.pyplot as plt 
matplotlib.use('TkAgg')
plt.axline(xy1=(0, 0), slope=1E-8)
plt.show()

# compare

import matplotlib
import matplotlib.pyplot as plt 
matplotlib.use('TkAgg')
plt.axline(xy1=(0, 0), slope=1.1E-8)
plt.show()
```

### Actual outcome

image

### Expected outcome

Similar to this image (from the 2nd code snippet):
image

### Additional information

I came across this issue when plotting some particularly terrible electrochemical data - measuring a current response in the nanoamps (10^-9) versus voltage in the 0-5 V range. It seems like `axline.get_transform(`) sets the slope to 0 if it satisfies `np.isclose()`. I am not sure why this is done (maybe numerical stability reasons?), since `axhline()` exists if the user _intentionally_ wants to make a horizontal line. It seems safe to me to remove the check or at least shrink the `atol` of that `np.isclose()` call. 
  

### Operating system

Windows

### Matplotlib Version

3.9.0 

### Matplotlib Backend

TkAgg (probably all) 

### Python version

3.11.5

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by kyracho**
## PR summary

I think this fixes the issue #28386 as suggested by @oscargus in PR #28754.

Changes: 

Initialize a variable `manual_slope` as `False` and sets it to `True` if a user has provided a slope. 

https://github.com/matplotlib/matplotlib/blob/d45bb7f0769d05e82c90ce8e963bbca4a9eaebf1/lib/matplotlib/lines.py#L1500-L1502
https://github.com/matplotlib/matplotlib/blob/d45bb7f0769d05e82c90ce8e963bbca4a9eaebf1/lib/matplotlib/lines.py#L1519-L1521

Replace `if np.isclose(slope, 0): ` with `if not manual_slope and np.isclose(slope, 0) or slope == 0:`.
https://github.com/matplotlib/matplotlib/blob/d45bb7f0769d05e82c90ce8e963bbca4a9eaebf1/lib/matplotlib/lines.py#L1523-L1525

Add a test to verify that the slope isn't set to 0 when the user has specified a nonzero slope.

https://github.com/matplotlib/matplotlib/blob/d45bb7f0769d05e82c90ce8e963bbca4a9eaebf1/lib/matplotlib/tests/test_lines.py#L441-L457

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
Thank you for your contribution @kyracho!  I think the discussion is still ongoing in #28386 about exactly which fix is the right one, so a detailed review here will likely need to wait for that to be resolved.  In the meantime, please could you update the title here to briefly describe what the change does?

**Comment by kyracho** [comment]
Sorry, I didn't realize the discussion is still ongoing in #28386. When a fix has been decided, I'd be happy to implement it in this PR :)

**Comment by timhoffm** [comment]
@kyracho I believe the discussion is through (https://github.com/matplotlib/matplotlib/issues/28386#issuecomment-2338109751). Let's continue based on that.

**Comment by timhoffm** [comment]
@kyracho do you want to continue on this? We'd like to get this in soon, because we're about to cut the 3.10 release candidate.

**Comment by kyracho** [comment]
Hello, I'm closing this PR and will be opening a new one for a clean and manageable commit history for review. 

The current PR shows an unexpectedly large number of changed files, which was not intended. The issue likely arose after force-pushing the branch and attempting to squash the previous commits into the final commit to make the code change easier to review. During that process, I merged the latest changes from `matplotlib:main` into my `bugfix-for-issue-28386` branch, but this resulted in a huge number of changed files. 

I attempted to fix this by rebasing, resetting, and force-pushing to clean up the branch, but unfortunately, the issue persists, and the force-pushes caused more complications.

To avoid any more confusion, I will open a new PR from a fresh branch with only the necessary changes applied. Thank you for your understanding!

**Pull request closed without merging**
