### PR TITLE
Fix #5573: Use SVG in docs

### LINKED ISSUE #5573: Support HiDPI (retina) displays in docs
For 2.0, it would be nice to show off the new styles in the docs by having proper hi-resolution image support.

It may be that using SVG by default is now sufficient, since browser support for SVG has come a long way since we first put together the docs.  Alternatively, we can provide images at twice the current resolution, scaled down (which probably won't look as good on traditional low-DPI displays).

### PR DESCRIPTION
**Pull request by mdboom**
This looks a lot better on hi-res displays, and I think will be a nice show-off for the style changes in 2.0.

I think what this PR needs is testing on various browsers and some manual looking for things where SVG breaks (though it all looks pretty good to me on spot-checking, and SVG is one of our better-tested backends).

### CODE REVIEW

**Comment by jenshnielsen** [comment]
Something goes wrong in the format parsing 

```
/home/travis/build/matplotlib/matplotlib/doc/mpl_examples/pylab_examples/xcorr_demo.py:11: 
WARNING: image file not readable: api/../build/plot_directive/mpl_examples/pylab_examples/xcorr_demo.p
```

**Comment by tacaswell** [comment]
Merging this so that we can see what the built docs look like at http://matplotlib.org/devdocs

We should hold of back porting this until we are sure we are happy with it.

**Comment by jenshnielsen** [comment]
For this to take effect on the devdocs we probably need to change either https://github.com/matplotlib/matplotlib/blob/master/.travis.yml#L110 to not build small or 
change small to include svg

**Comment by QuLogic** [comment]
This was reverted.

**Pull request merged**
