### PR TITLE
Slim down animation examples in the gallery

### PR DESCRIPTION
**Pull request by dstansby**
## PR Summary
This removes three animation examples from the gallery that between them take ~ 1.5 minutes to run in the doc build, but do not demonstrate Matplotlib concepts/functionality that isn't in other examples. In my opinion they are nice to have, but saving 1.5 mins on each doc CI run is a worthwhile saving. I'm probably +0.5 on it though, so if someone is keen that they stay very happy for this to be closed without merging.

Also some other minor PEP8 fixes.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by story645** [comment]
I dunno if it's a pro or con that the double pendulum & rain examples are all over the internet - a follow up might be to move these to the blog?

**Comment by tacaswell** [comment]
These also produce large output (I think unchained is actually the worst in that regard).

I would rather see the length of the animations cut down or skipped on CI (which might require work against sphinx-gallery) so save time rather than cutting them all together.  I think there is a lot of value in a pretty complete application that, even though it does not show anything unique, shows how to put them together.  That bit of "oooh, you can assemble the pieces like _that_...." spark should not be discounted.

**Comment by jklymak** [comment]
Does this need discussion @dstansby, or do you have enough to work on?  I'm putting back to draft given the comments above, but feel free to put back int he active queue.  Thanks!

**Comment by dstansby** [comment]
Thanks - I think there's enough to go on when I come back round to looking at this 👍

**Pull request closed without merging**
