### PR TITLE
FIX: fix default flier line style

### LINKED ISSUE #5173: Error in boxplot, 1.5.0.rc2
In RC2 of matplotlib 1.5.0, outliers in boxplots are connected by lines (see attached image). This should not be the case.
error_boxplot

### PR DESCRIPTION
**Pull request by tacaswell**
closes #5173

### CODE REVIEW

**Comment by mdboom** [comment]
Do we have a test that exercises #5173?  Maybe we should add one here?

**Comment by tacaswell** [comment]
We have tests that were not failing: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/baseline_images/test_axes/boxplot_sym2.png

Test:

image

11:27 $ git describe
v1.5.0rc2-24-gb5d8674


so

**Comment by mdboom** [comment]
Hmm...  Maybe we can crank down the threshold or crank up the linewidth on these?

**Comment by tacaswell** [comment]
probably would have to be the threshold.

I would like to punt the aggressive test reworking to the 2.x series.  We are probably going to want to _eventually_ replace most of our images to use the new defaults rather than the 'classic' style sheet.  I think that would be a good opportunity to do a more general clean up of the tests.

**Comment by mdboom** [comment]
@tacaswell: Agreed on when to do aggressive test reworking.

**Comment by Tillsten** [comment]
While fixing the bug, it would be probably better to have and use a `validate_linestyle` function.

**Comment by tacaswell** [comment]
@Tillsten That seems a bit orthogonal to this bug and is something that we have never had (as far as I can tell).

**Pull request merged**
