### PR TITLE
3.2.0 API changes page

### PR DESCRIPTION
**Pull request by dstansby**
Here's the PR to put everything together for the API changes for 3.2.0. I'll probably work on this in chunks, and ping everyone when it's ready for review.

### CODE REVIEW

**Comment by dstansby** [comment]
@matplotlib/developers I'm burnt out on finishing this up (there's not much left), so would be grateful if someone else can take this over (feel free to force push to my branch or take a copy and open a new PR).

Both this and the `3.1.0` API changes have been a real drain of time, so I'm going to propose a change in how this works for `3.3.0` soon.

**Comment by ImportanceOfBeingErnest** [comment]
I've done the remaining API changes. Unfortunately, I could not push after rebasing (technically, because "Updates were rejected because the tip of your current branch is behind its remote counterpart.", realistically, because I still haven't understood how git works)

Therefore I made https://github.com/matplotlib/matplotlib/pull/15163 out of it.

**Comment by NelleV** [comment]
Rebasing changes the history, and thus the local git hashes. You probably rebased something that was already on @dstansby's branch. As a result, git thinks you need to pull the more recent history before pushing (hence your tip being behind the remote's counterpart).

**Comment by tacaswell** [comment]
> Both this and the `3.1.0` API changes have been a real drain of time,  so I'm going to propose a change in how this works for 3.3.0 soon.

I am very grateful for your work on this!

**Comment by tacaswell** [comment]
@ImportanceOfBeingErnest If you had don `git push --force ...` it would have worked, but closing this PR in favor of #15163

**Pull request closed without merging**
