### PR TITLE
Skip webagg test if tornado is not available.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I'm confused -- were the tests failing before if run on an env without tornado installed?

**Comment by QuLogic** [comment]
Yes, for example, this [other webagg test](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_backends_interactive.py#L130) skips if `tornado` is not installed.

Though now that I look at it, this test also touches nbagg, so I will fix the skip to only run on webagg.

**Comment by anntzer** [comment]
Actually nbagg depends on webagg_core (one imports the other) and thus on tornado, so I think always skipping (the previous version) is correct?

**Comment by QuLogic** [comment]
Oops, I think you're right. We don't install `IPython`, so I misunderstood the skip.

**Comment by tacaswell** [comment]
@meeseeksdev backport to v3.1.x

**Pull request merged**
