### PR TITLE
doc: fix unescaped backslash

### PR DESCRIPTION
**Pull request by nathanmusoke**

### CODE REVIEW

**Comment by WeatherGod** [comment]
Thanks for catching that! This should probably get back-ported... which branch is it now? v2.x?

**Comment by tacaswell** [comment]
to 2.x

**Comment by nathanmusoke** [comment]
Yeah, probably should be back-ported too. I just made a pull request against master as I couldn't find the maintenance branch mentioned in the Coding guide.

**Comment by WeatherGod** [comment]
backported to v2.x via c88b341

**Comment by WeatherGod** [comment]
Yes, the coding guide needs to be updated since v2.x is now the maintenance branch.

**Pull request merged**
