### PR TITLE
Added USF Masters Data Science inspired stylesheet, great for presentat…

### PR DESCRIPTION
**Pull request by bassimeledath**
…ions

## PR Summary
This is a simple pull request just adding a style sheet that would work well in presentations. It is unique enough that it might add value to other people. I'm a first time contributor here so apologies in advance if I'm missing a step in doing this.

The documentation builds without issue but I'm having some trouble adding the new style to the documentation. Please advise, thank you.

## PR Checklist

**Documentation and Tests**
- [N/A] Has pytest style unit tests (and `pytest` passes)
- [ X] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [N/A] New plotting related features are documented with examples.

**Release Notes**
- [ N/A] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ N/A] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ N/A] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by bassimeledath** [comment]
@story645 thank you for your timely response and sure!

I've attached screenshots of the `usf-msds` design along with the fivethirtyeight and the seaborn poster designs as I believe they all fall under the same category for posters or presentations. I've used the other two designs (especially fivethirtyeight) for years (for presentations) so this new design is based on my learnings. I think of this design as an improved version of fivethirtyeight.

The unique qualities of the `usf-msds` design:
1. By default only keeps the left and right border to reduce clutter (Knaflic, 2015)

2. Additionally, it removes axes ticks and makes axes labels and lines light grey. The point is to establish a visual hierarchy such that primary attention is given to the graph first before the axes numbers and labels (Knaflic, 2015)

3. Left aligns titles: By default jupyter notebooks left align plots, so it looks odd when the title is in the center, so I've made the title left aligned by default and increased the padding to make the title stand out a little more.

4. High contrast colors: this isn't exactly a unique feature but the color palette is unique and features high contrast colors (higher contrast than seaborn's poster style sheet).

5. Keeps the background white: unlike fivethirtyeight which greys the background, I keep the default background white. This is because in most presentations and jupyter notebooks, the background is white, not grey. So it looks awkward when someone uses the default fivethirtyeight.

Some of these design choices are subjective but for the most part it agrees with what's there in the literature on design. Again, thought it might be useful for the community, totally cool if not or if it's not unique enough. Thanks!

Screenshot 2023-04-11 at 8 50 09 AM

Screenshot 2023-04-11 at 8 52 06 AM

Screenshot 2023-04-11 at 8 52 46 AM

**Comment by jklymak** [comment]
@bassimeledath this looks nice, but as @story645 mentions, we are very conservative about adding new style sheets (after a period of not being so conservative).  

I'd love to see a user-contrib style site; I think it is unreasonable to make a style a whole third-party package, but a site where users submitted a style and it rendered as a big gallery of styles, perhaps with subsections, would be a really nice resource.

**Comment by jklymak** [comment]
Well adding voting would be an interesting feature, or download counts...

**Comment by ksunden** [comment]
I'm going to close as I think the consensus is "looks nice, but let's not add too many styles here"

Please do let us know if you have any follow up on a site/showcase for styles!

**Pull request closed without merging**
