### PR TITLE
Fill between cleanup

### PR DESCRIPTION
**Pull request by dopplershift**
Cherry-picks #9236 from v2.1.x. It also goes further and refactors `fill_between(x)` a bit.

`fill_between` and `fill_betweenx` were almost entirely duplicated between each other. This adds a helper function with the common functionality, and attempts to generalize between them without making the logic *too* convoluted.

### CODE REVIEW

**Comment by QuLogic** [comment]
`v2.1.x` should get merged back to `master`; you don't really need to cherry-pick things back.

**Comment by dopplershift** [comment]
Ok...doing this off of un-patched master would result in conflicts.

**Comment by QuLogic** [comment]
`v2.1.x` is merged into `master`; do we still need this?

**Comment by tacaswell** [comment]
I don't think we need this.

**Comment by dopplershift** [comment]
Actually, this still has the work to refactor and reduce duplication. I’ll rebase so it’s clear what’s new here.

**Comment by tacaswell** [comment]
Sorry

**Comment by efiring** [comment]
This looks like a nice refactor and I don't want to see it get lost, but unfortunately it needs a non-trivial rebase.  Perhaps we can push on it right after the 2.2 release?

**Comment by dopplershift** [comment]
I should be able to manage that after 2.2.

**Comment by anntzer** [comment]
Superseded by #16023.

**Pull request closed without merging**
