### PR TITLE
Don't add 1 to all hexbin data when using log norm

### PR DESCRIPTION
**Pull request by dstansby**
## PR Summary
This seems very wrong - it means that every bin that doesn't actually have a data point turns up with a value of 1, and all other bins have a value of 1 added to them. We handle the case where the bin value = 0 and a log scale fine by just not showing the bin.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
What is the git blame for that? It'd be interesting to see the reasoning.

**Comment by anntzer** [comment]
This came in in 5f8a88a back in 2010, and I guess logzero handling was more iffy back then.
I agree that the current behavior is undesirable.
Some tests need to be updated, though.

**Comment by dstansby** [comment]
It goes all the way back to 2010: https://github.com/matplotlib/matplotlib/commit/5f8a88af6c60d0fc363c5b26f5396a2caaf12210. I'm not sure what the motivation for it was, but perhaps handling zero values on a log norm didn't work as well back then?

**Comment by dstansby** [comment]
I'm closing this in favour of https://github.com/matplotlib/matplotlib/pull/21039 which has more fixes, to avoid changing a test image twice.

**Pull request closed without merging**
