### PR TITLE
DOC: Boxplot color demo update

### PR DESCRIPTION
**Pull request by phobson**
supersedes #6488 and #7317

### CODE REVIEW

**Comment by ivanov** [comment]
👍  Looks good to me!

**Comment by NelleV** [comment]
Hum… I was so happy to see @ivanov starting to review again that I merged before travis had time to finish. We'll see…

Thanks @phobson for the patch!

**Comment by phobson** [comment]
@NelleV  thanks for the merge. Looks like Travis as happy & AppVeyor canceled itself after the merge (phew)

**Comment by phobson** [comment]
I'll take care of it as soon I can get back on GH. See my comment to Paul
above :/

**Comment by phobson** [comment]
Thanks Paul. I'm getting notification emails, but I can access github.com
or push ATM because of the Dyn DDoS
http://gizmodo.com/this-is-probably-why-half-the-internet-shut-down-today-1788062835
:/

**Comment by phobson** [comment]
I meant to. Thanks for catching that.

**Comment by QuLogic** [comment]
Err, those got through a bit late...

**Pull request merged**
