### PR TITLE
MNT: Temporarily skip failing test to unbreak CI

### PR DESCRIPTION
**Pull request by timhoffm**
Works around the failure #29129. A proper analysis and resolution is still needed.

### CODE REVIEW

**Review by greglucas — APPROVED** [review]

**Comment by tacaswell** [comment]
The appveyor failure is due to issues removing temporary directories, merging over the failure.

**Comment by timhoffm** [comment]
@meeseeksmachine backport to v3.10.x

**Comment by ksunden** [comment]
@meeseeksbot please backport to 3.10.x

**Comment by ksunden** [comment]
@meeseeksdev please backport to 3.10.x

**Comment by ksunden** [comment]
Try all the names, I guess

**Comment by ksunden** [comment]
@meeseeksdev please backport to v3.10.x

**Pull request merged**
