### PR TITLE
Add Arev Sans fonts and license

### PR DESCRIPTION
**Pull request by hetland**
Added Arev Sans TTF files and license. 

I suggest this be the default font, as it has many math glyphs and works well with mathtext.

### CODE REVIEW

**Comment by toddrjen** [comment]
What is the advantage of Arev over [DejaVu](http://dejavu-fonts.org/wiki/Main_Page)?  It seems like DejaVu has already incorporated the Arev characters, and includes a large number of other characters as well.  Further, from the copyright, it looks like the Arev project has been abandoned (it hasn't seen a release in almost 10 years), while the DejaVu project is well-maintained (last release in May of this year) and is widely-used in open-source project.

**Comment by hetland** [comment]
At the time I made the choice of Arev (some years ago), it contained many
more math glyphs. But you are correct that DejaVu has incorporated those
glyphs and is more active. I would say that DejaVu seems like a better
choice now.

My primary motivation for the pull request was to create a default san
serif font with matching math font. San-serif seems to be a better design
choice for figures (e.g., see Tufte
<http://www.edwardtufte.com/tufte/books_vdqi>).  Arev/DejaVu seem to be a
pretty font with good, matching math glyphs for rendering equations, and a
permissive license, which makes it a good way to achieve the design goal of
sans-serif font with math capabilities.

On Wed, Sep 23, 2015 at 4:16 AM, toddrjen <notifications@github.com> wrote:

> What is the advantage of Arev over DejaVu
> <http://dejavu-fonts.org/wiki/Main_Page>? It seems like DejaVu has
> already incorporated the Arev characters, and includes a large number of
> other characters as well. Further, from the copyright, it looks like the
> Arev project has been abandoned (it hasn't seen a release in almost 10
> years), while the DejaVu project is well-maintained (last release in May of
> this year) and is widely-used in open-source project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/pull/4636#issuecomment-142537763>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by mdboom** [comment]
So, I think we're in agreement to not use Arev, but the Vera that we ship could probably use an update.  @hetland: Would you like to make a PR to do that?

**Comment by zblz** [comment]
As I mentioned in #5128, a new default font should have associated mathtext fontset. I have gone ahead and added them for DejaVu in #5214 in preparation for the default change. This has the advantage over setting `custom` in `mathtext.fontset` that I was able to set STIX as fallback, which  matches DejaVu better than Computer Modern does.

**Comment by zblz** [comment]
Moving setting DejaVu as default for both text and math to #5214

**Pull request closed without merging**
