### PR TITLE
DOC: add note to example about keeping hard-ref to SpanSelector

### LINKED ISSUE #14276: SpanSelector does not work when used in method
Hi there,

I don't know how to get the SpanSelector working when the plot is created within a class definition. The plot is created but loses it's interactive capabilities. To illustrate this issue I simply put a standard example into a class definition. Has anybody any ideas?

Thanks in advance!!

**Working example:**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector

# Fixing random state for reproducibility
np.random.seed(19680801)

fig, (ax1, ax2) = plt.subplots(2, figsize=(8, 6))
ax1.set(facecolor='#FFFFCC')

x = np.arange(0.0, 5.0, 0.01)
y = np.sin(2*np.pi*x) + 0.5*np.random.randn(len(x))

ax1.plot(x, y, '-')
ax1.set_ylim(-2, 2)
ax1.set_title('Press left mouse button and drag to test')

ax2.set(facecolor='#FFFFCC')
line2, = ax2.plot(x, y, '-')


def onselect(xmin, xmax):
    indmin, indmax = np.searchsorted(x, (xmin, xmax))
    indmax = min(len(x) - 1, indmax)

    thisx = x[indmin:indmax]
    thisy = y[indmin:indmax]
    line2.set_data(thisx, thisy)
    ax2.set_xlim(thisx[0], thisx[-1])
    ax2.set_ylim(thisy.min(), thisy.max())
    fig.canvas.draw()

# Set useblit=True on most backends for enhanced performance.
span = SpanSelector(ax1, onselect, 'horizontal', useblit=True,
                    rectprops=dict(alpha=0.5, facecolor='red'))


plt.show()
```

**My code:**

```python

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector


# Fixing random state for reproducibility
np.random.seed(19680801)
class SpanTest():
    def plot(self):
        fig, (ax1, ax2) = plt.subplots(2, figsize=(8, 6))
        ax1.set(facecolor='#FFFFCC')

        x = np.arange(0.0, 5.0, 0.01)
        y = np.sin(2*np.pi*x) + 0.5*np.random.randn(len(x))

        ax1.plot(x, y, '-')
        ax1.set_ylim(-2, 2)
        ax1.set_title('Press left mouse button and drag to test')

        ax2.set(facecolor='#FFFFCC')
        line2, = ax2.plot(x, y, '-')


        def onselect(xmin, xmax):
            indmin, indmax = np.searchsorted(x, (xmin, xmax))
            indmax = min(len(x) - 1, indmax)

            thisx = x[indmin:indmax]
            thisy = y[indmin:indmax]
            line2.set_data(thisx, thisy)
            ax2.set_xlim(thisx[0], thisx[-1])
            ax2.set_ylim(thisy.min(), thisy.max())
            fig.canvas.draw()

        # Set useblit=True on most backends for enhanced performance.
        span = SpanSelector(ax1, onselect, 'horizontal', useblit=True,
                            rectprops=dict(alpha=0.5, facecolor='red'))


        plt.show()
        
st = SpanTest()
st.plot()
```

**Matplotlib version**

  * Operating system: **Ubuntu 18.04**
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): **TkAgg**
  * Python version: **3.6**
  * Jupyter version (if applicable):
  * Other libraries: **numpy-version -> 1.16.3**

I installed matplotlib via pip. I'm not using conda.

Thank you very much!
Have a great one!
Christian

### PR DESCRIPTION
**Pull request by tacaswell**
closes #14276

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by ImportanceOfBeingErnest** [comment]
This doesn't seem to have the desired effect: https://21369-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/widgets/span_selector.html

But even if the "note"-box appeared, would you want it to cut the code in half? Maybe use normal inline comments? Or put the note outside the code, such that it is still copy-pastable as a single entity?

Btw. I guess this note would then need to appear in *all* the widget examples?

**Comment by anntzer** [comment]
As argued in https://github.com/matplotlib/matplotlib/pull/10876#issuecomment-376788351 / https://github.com/matplotlib/matplotlib/pull/10908#issuecomment-376800580 I think CallbackRegistry should just keep strong references...

**Comment by tacaswell** [comment]
I was trying to cut the code in half, but will go back to just in-line comments.

**Comment by NelleV** [comment]
@tacaswell Let me know when you fix the rendering issue?

**Comment by ImportanceOfBeingErnest** [comment]
@timhoffm Does merging this mean that you will take the responsibility to make sure the note actually appears in a future PR?

**Comment by NelleV** [comment]
It was an improvement in any case. I'm sure someone will at some point see this, and open a PR to fix it.

**Comment by timhoffm** [comment]
@ImportanceOfBeingErnest I was a bit quick. Assuming you mean #14422.

**Pull request merged**
