### PR TITLE
BUG: arrowhead drawing code

### PR DESCRIPTION
**Pull request by pizzathief**
removing a left part drawing instruction fixes
an arrowhead drawing problem.

### CODE REVIEW

**Comment by pizzathief** [comment]
partly fixes issue # 5344, the arrowhead drawing part.  arrowhead direction still wrong.

**Comment by mdboom** [comment]
Thanks.  Have you looked into how hard it will be to fix the arrowhead direction?

**Comment by tacaswell** [comment]
:+1: on merging this as-is

**Comment by jenshnielsen** [comment]
:+1: How easy is it to add a test for this?

**Comment by tacaswell** [comment]
Sorry this sat for so long without attention.  Retstarting tests against current master.

**Comment by QuLogic** [comment]
Don't see why this can't be merged...

**Comment by QuLogic** [comment]
Backported to v2.x via 64cee30e26f191ef3392ad98a03588350a387a47.

**Pull request merged**
