### PR TITLE
Don't duplicate docstrings of pyplot-level cmap setters.

### PR DESCRIPTION
**Pull request by anntzer**
Dynamically generating these docstrings takes ~40us, which is
negligible compared to the import time.

flake8 had to be updated, as older versions incorrectly warned about the
lack of blank lines between the one-liners.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
3.3 is not yet branched. Either we wait or milestone this for 3.3.

**Comment by anntzer** [comment]
I'm not in a hurry.

**Comment by jklymak** [comment]
Doers this need to wait for the branch?  Not sure I understand why we don't just merge for 3.3?

**Comment by timhoffm** [comment]
I'm unclear why azure is failing.

Otherwise we could re-target this to 3.3 and merge.

**Pull request merged**
