### PR TITLE
Fix exception causes all over the codebase

### PR DESCRIPTION
**Pull request by cool-RR**
## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by cool-RR** [comment]
@timhoffm Ready for review

**Comment by jklymak** [comment]
Maybe you could include a few words as to why we want to use this grammar?

**Comment by cool-RR** [comment]
@jklymak This is the final part of #16684.

Basically this makes the right message appear between the two tracebacks.

**Comment by tacaswell** [comment]
Thanks @cool-RR !

**Comment by cool-RR** [comment]
I just made a blog post about this change here: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

**Pull request merged**
