### PR TITLE
Capitalize headings in example Gallery

### PR DESCRIPTION
**Pull request by kolibril13**
The headings in the example section are mostly upper case, but also a few lowercase headings::
image

This pr capitalizes all headings.

### CODE REVIEW

**Comment by oscargus** [comment]
Thanks you for this PR! However, as those that you modified here are module names, I am not sure that they should be modified, at least not like this.

(Also, I think the style guide indicates that "Title Case" should not be used. https://matplotlib.org/stable/devel/documenting_mpl.html#formatting-and-style-conventions  Rather "Specialty Plots" should probably be changed to "Specialty plots".)

I do agree with you though that the current approach looks a bit weird. Maybe one should format the modules as "code", so 
```
``pyplot``
=======
```
etc, but not sure exactly what that would look like.

**Comment by kolibril13** [comment]
I've now changed it to `Upper lower`.
For most example names in the gallery, there is the `Title Case` used.
image


Regarding module names: I think the style guide saies that "`" should not be used.
https://matplotlib.org/stable/devel/documenting_mpl.html#function-arguments

**Comment by anntzer** [comment]
Please don't change the capitalization or remove underscores from module names (you can't `import Pyplot` or `import Axes grid`).  If you want to make these more homogeneous, I would write e.g. `The pyplot module`/`The axes_grid1 module`.

**Comment by kolibril13** [comment]
> Please don't change the capitalization or remove underscores from module names

My changes are affecting is the example gallery, so I thought that the example gallery the captions should have names that describe to the users what examples to expect. Are the example gallery captions the right place for module names? 
In my opinion no, but I am open to be convinced otherwise.

I think module names should only be used in the reference headings:
https://matplotlib.org/stable/api/toolkits/axes_grid1.html#mpl-toolkits-axes-grid1


> you can't `import Pyplot` or `import Axes grid`

Yes, but so one can not do `import Statistics` from the [Statistics](https://matplotlib.org/stable/gallery/statistics/index.html) section

**Comment by anntzer** [comment]
> Yes, but so one can not do import Statistics from the Statistics section

Indeed, but pyplot is nothing *but* a module name, whereas Statistics is obviously a common noun.

**Comment by oscargus** [comment]
Just to confirm that what @anntzer maybe expressed clearer, is exactly what I was trying to say with the example. These are modules and should be spelled as the module, probably with some formatting to make it clear that it is a module.

**Review by jklymak — CHANGES_REQUESTED** [review]
Thanks for this, but I agree with @oscargus  and @anntzer: the last one is fine, the rest are incorrect.

**Comment by kolibril13** [comment]
Thanks for these very quick responses! 

> probably with some formatting to make it clear that it is a module

For consistency, I've now changed it to `The axes_grid1 module` , `The axisartist module` and `The pyplot module`

**Review by jklymak — APPROVED** [review]

**Pull request merged**
