### PR TITLE
Shareable property cyclers

### PR DESCRIPTION
**Pull request by anntzer**
First commit: Simplify _process_plot_var_args.set_prop_cycle.

It is private, so we can restrict it to only support cycler instances
and None.

Second commit: Shareable property cyclers.

Allow a single property cycler to be reused across multiple axes, with
plots on any axes advancing the same joint iterator.

e.g.
```python
from matplotlib import pyplot as plt
from matplotlib.axes._base import to_shareable_cycler

shared = to_shareable_cycler(plt.rcParams["axes.prop_cycle"])
fig, axs = plt.subplots(2, sharex=True)
axs[0].set_prop_cycle(shared)
axs[1].set_prop_cycle(shared)

axs[0].plot([0, 1])
axs[1].plot([0, 1])
# Check that fill uses a separate iterator.
axs[1].fill([2, 3, 4], [0, 1, 0])
axs[0].fill([2, 3, 4], [0, 1, 0])
# Check that the second axes goes back to the first color, even though it
# didn't use it on the first cycle.
for i in range(10):
    axs[1].plot([5+i, 5+i], [0, 1])
plt.show()
```
test

We may want to move `to_shareable_cycler` and `_get_cycling_iterator` to the cycler repo itself (possibly under different names), here I just made them free functions to keep the PR self-contained.

An example use case:
```python
from matplotlib import pyplot as plt
from matplotlib.axes._base import to_shareable_cycler
import numpy as np

fig, axs = plt.subplots(2, 3, sharex=True, sharey=True)
axs = axs.ravel()
shared = to_shareable_cycler(plt.rcParams["axes.prop_cycle"])
for ax in axs[1:]:
    ax.set_prop_cycle(shared)

xs = np.arange(10)
all_ys = (5 + np.random.randn(5)[:, None]) * xs + 3 * np.random.randn(5, 10)
axs[0].set_title("all datasets")
for i, ys in enumerate(all_ys):
    axs[0].plot(ys)
    axs[i + 1].set_title(f"dataset #{i} & fit")
    axs[i + 1].plot(ys)
    axs[i + 1].plot(xs, np.polyval(np.polyfit(xs, ys, 1), xs), c="k", zorder=.5)

plt.show()
```
test
(Obviously this is also doable by manually passing the correct colors to each plot call, although it's quite harder to do so if you want to support arbitrary property cycles...)

Closes https://github.com/matplotlib/matplotlib/issues/19479.

### CODE REVIEW

**Comment by timhoffm** [comment]
While this is a clever way to hack the sharing behavior into the existing structure. However I'm not convinced of this because

1. I'm unclear of the intended scope of `Cycler` and whether it holds state (see https://github.com/matplotlib/matplotlib/issues/19479#issuecomment-775583610). Only if it holds the cycling state, sharing cyclers can be reasonable semantically.
2. I don't like the conversion `to_shareable_cycler()`. Distinguishing between sharable and non-sharable cyclers would be an advanced concept which I don't want to throw at and explain to the user.

IMHO you should share something that is an iterator. So either cyclers would need to become iterators, or you should accept iterators in `set_prop_cycle` and share `iter(cycler)`.

**Comment by anntzer** [comment]
Turning cyclers into iterators is basically going to break anyone calling `set_prop_cycle(cycler)` on multiple Axes and expecting the old behavior (which is likely the most commonly required one anyways).  So "shareable cyclers" need to be something else: here, I implemented them as cyclers with an extra internal flag, but I could easily have returned a non-Cycler object instead (let's just call it a Foo, better names welcome) e.g. by moving the current Cycler implementation to a hidden `_CyclerBase` base class and making `Cycler` and `Foo` both inherit from `_CyclerBase`, with `Foo` just having the extra flag; also `to_shareable_cycler` would be renamed `to_foo`. In fact I guess could even rename `to_shareable_cycler` to `Cycler.__iter__` (making that return a Foo -- the trick here being that `__iter__`, while usually implemented as a generator, can also return an iterator object instead) and get the `it = iter(cycler); set_prop_cycle(it)` API to work.

**Comment by anntzer** [comment]
Added a test, so this should be good to go -- modulo the discussion of whether we actually want that or not, of course...

**Comment by anntzer** [comment]
I still think this would be useful, but this is basically tracked by #19479.  @oscargus you did express some interest, perhaps you may be willing to champion something along these lines?

**Pull request closed without merging**
