### PR TITLE
Avoid using Bbox machinery in Path.get_extents; special case polylines.

### PR DESCRIPTION
**Pull request by anntzer**
update_from_data_xy is much slower than needed; we can use plain numpy
instead.  (This speeds up #17974 another ~30-40% on top of #17994.)
For polylines, we can completely skip the bezier handling for even more
speedup.  (This fixes the performance regression.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Because it constructs general path objects and then iterates over it using overly general mechanisms, I guess.

**Comment by timhoffm** [comment]
As a performance regression fix, should this be backported to 3.3.1?

**Comment by jklymak** [comment]
I think the regression has been there since 3.0.0, so not urgent, unless there is something more than the tight_bbox PR that added to the slowdown.

**Comment by QuLogic** [comment]
Further discussion on #17974 says this _was_ introduced in 3.3.0, so maybe we should backport this?

**Comment by QuLogic** [comment]
@meeseeksdev backport to v3.3.x

**Pull request merged**
