### PR TITLE
SVG Backend gouraud_triangle Correction

### PR DESCRIPTION
**Pull request by avinashmnit30**
## PR Summary
As pointed out in #11321, the SVG backend does not render **Gouraud shading** correctly. ts mentioned that SVG backend is following http://www.svgopen.org/2005/papers/Converting3DFaceToSVG/index.html paper. But the Gouraud triangle implementation is incorrect. This pull request fixes the implementation.

**Code for reproduction:** https://matplotlib.org/2.0.1/examples/pylab_examples/quadmesh_demo.html

**SVG Backend Orignal Output:**
incorrect_svg

**Using correct implementation:**
correct_svg

### CODE REVIEW

**Comment by tacaswell** [comment]
Great!

Can you investigate why the tests are failing?

We seem to have lost the pep8 checking on master, there are some issues (trailing white space, too long lines) that will need to be cleaned up.

**Comment by avinashmnit30** [comment]
@tacaswell  Ok, I would check it.

**Comment by avinashmnit30** [comment]
@tacaswell The "travis-ci" test suite contains a **pcolormesh** test in **test_axis** which uses SVG backend for gouraud shading. Due to the wrong implementation, the expected SVG image is generating the failure.
### Expected SVG Output (Incorrect)
pcolormesh-expected_svg

### Corrected Fix Output
pcolormesh_svg

**Comment by ImportanceOfBeingErnest** [comment]
The "Corrected Fix Output" has some strange pixels in the rightmost image. Are they expected? In how far is this "more correct" than the current output?

**Comment by avinashmnit30** [comment]
@ImportanceOfBeingErnest The rightmost image is using Gouraud shading in SVG. The strange pixels are due to limitations of SVG features. Most of the triangle edges are dissolved (compared to flat shading) due to use of 3 colors per triangle and filtering them. But some of them would remain visible as there is no direct method to implement Gouraud shading in SVG. 
http://www.svgopen.org/2005/papers/Converting3DFaceToSVG/index.html

**Comment by ImportanceOfBeingErnest** [comment]
I wonder if the current implementation, while academically incorrect, would give smoother results, one should not stick to it?

**Comment by avinashmnit30** [comment]
@ImportanceOfBeingErnest Current implementation is not giving smoother results. You misread it. The SVG gouraud shading (implemented in the paper: http://www.svgopen.org/2005/papers/Converting3DFaceToSVG/index.html) works well for smoother input images.

**Comment by ImportanceOfBeingErnest** [comment]
Ok, seems I misunderstood that. Would you mind spending some words on what "Expected SVG Output (Incorrect)" and "Corrected Fix Output" refer to and why something like

image
 would be preferred over

image
?

**Comment by tacaswell** [comment]
@avinashmnit30 can you update the svg image (the easiest way is to run the tests locally and then commit the svg)?

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/baseline_images/test_axes/pcolormesh.png 

image

is the Agg version of the test so the updated one is certainly closer.  We are also looking an png versions of the svg file the 'hot' pixel may be a rendering artifact (not a feature of the svg file).

**Comment by avinashmnit30** [comment]
@tacaswell Did the SVG image update.

**Comment by jklymak** [comment]
In Firefox, the svg still renders as flat vertices, though the annoying dashes between facets goes away.  In Illustrator both the old and new versions look bad.

So,... what is the canonical SVG viewer?  I don't see that either the ones I use manage to make gouraud shading look correct...

### Old Firefox
mozilla_firefox

### New Firefox
mozilla_firefox

**Comment by tacaswell** [comment]
@avinashmnit30 If you get a chance could you rebase and squash this into 1 or 2 commits?

**Comment by tacaswell** [comment]
As far as I know there is not a 'canonical' svg viewer, just a specification document.

**Comment by avinashmnit30** [comment]
@tacaswell I have rebased it to single commit now.

**Comment by tacaswell** [comment]
Thanks @avinashmnit30 !

**Pull request merged**
