### PR TITLE
TYP: add float to to_rgba x type

### PR DESCRIPTION
**Pull request by dpinol**
## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
This certainly _works_ in the current implementation... but it is not clear from reading the docstring whether that is _intended_ behavior.:

> Return a normalized RGBA array corresponding to *x*.
    
> In the normal case, *x* is a 1D or 2D sequence of scalars, and
> the corresponding `~numpy.ndarray` of RGBA values will be returned,
> based on the norm and colormap set for this ScalarMappable.

When handed a float, the return type is actually not an array, but a tuple.

This method is a little ambiguous (i.e. using the phrase "in the normal case"), so I would like to hear @timhoffm's opinion on whether this should be included. The implementation gaurds explicit ndarray behaviors behind a `try/except`, so perhaps we should be more permissive on  typing too.

If it to be included, I would do so as an `@overload` which captures the different return type.

Ultimately the implementation is a call to `cmap.__call__`, so technically all of those typings (for the primary parameter and the corresponding return types) are valid (insofar as they will work):

https://github.com/matplotlib/matplotlib/blob/2360c5919567d5592ab7a66ef31eca2dc6ff3fd3/lib/matplotlib/colors.pyi#L72-L83

So, I think we either keep it at where it is, or we do the more complete change to fully encapsulate both param types and return types, as well as updating the docstring (which is not in numpydoc format in the first place).

**Comment by timhoffm** [comment]
This functions maps "input data" RGB/RGBA arrays or scalar values to a standardized RGBA representation. It's primary use is internal to process the data content of ScalarMappables. I'm not sure whether this needs to be public at all. @dpinol How did you find this? Do you have a use-case?

The anticipated use case is clearly processing array-likes. The catch block seems to be defensive to support non-ndarrays - but I think still array-likes.

I don't have a stong opinion either way, but if we want to support this, we need to update the docs and add tests as well.

**Comment by dpinol** [comment]
@timhoffm I use it to create and html color from a value within a range. St like:
```python
    @staticmethod
    def from_float_range(
        value: float, min: float, max: float, colormap: Optional[str] = None
    ) -> str:
        cmap_name = colormap or ModalityColor.DEFAULT_CMAP
        norm = mpl.colors.Normalize(vmin=min, vmax=max)
        cmap = cm.get_cmap(cmap_name)
        m = cm.ScalarMappable(norm=norm, cmap=cmap)
        color = m.to_rgba(value)  # type: ignore
        val = (
            f"#{int(color[0]*255):02x}{int(color[1]*255):02x}{int(color[2]*255):02x}".upper()
        )
        return val

```

**Comment by ksunden** [comment]
For that purpose I would avoid making a `ScalarMappable` at all (it is quite odd to make a bare ScalarMappable in the first place):

```python
def from_float_range_2(
        value: float, min: float, max: float, colormap: str | None = None
    ) -> str:
        cmap_name = colormap or "viridis"
        norm = mpl.colors.Normalize(vmin=min, vmax=max)
        cmap = mpl.colormaps[cmap_name]
        return mpl.colors.to_hex(cmap(norm(value)))
```

(Note, did viridis instead of your default)

The `to_hex` method exists, though does round to the nearest RGBA integer values where your version always rounded down, so not _exactly_ the same, but if anything perhaps more correct.

This method does type check as okay (well, pyright complains about `mpl.colors`, but that can be fixed by adjusting imports... the actual method calls type check okay, though). And there is no extraneous `ScalarMappable` object.

**Comment by dpinol** [comment]
@ksunden thanks! your code works beatifully. Should I close the PR?

**Pull request closed without merging**
