### PR TITLE
Unify the three Qt5 embedding examples.

### PR DESCRIPTION
**Pull request by anntzer**
... and modernize them a bit.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
examples/user_interfaces/embedding_in_qt4_wtoolbar_sgskip.py is nice because it shows you do not have to sub-class `FigureCanvas` to embed it.

**Comment by anntzer** [comment]
Good point.  In fact the subclassing in the other example is completely unnecessary -- I'll move to the non-subclassing style...

**Comment by anntzer** [comment]
I wrote what is basically a completely new embedding example, which does not rely on subclassing the Canvas (that is totally unneeded, both here and in my experience), and still showcases having multiple canvases, including a dynamic one, and the corresponding toolbars.
I voluntarily fully redrew the dynamic canvas on each iteration as I don't think the point of the example is to showcase blitting or modification of an existing Line2D instance.

**Comment by afvincent** [comment]
Quite unrelated, but the 2nd canvas of the new example illustrates quite well the issue #9546 (annoying behavior with the busy cursor).

**Comment by anntzer** [comment]
I know...

**Comment by anntzer** [comment]
I think the backend docs need to be rewritten in general, it's somewhere on my todo list...

**Comment by jklymak** [comment]
Its fine, but do you need to do this versus just using the more vanilla Annimation module?

**Comment by anntzer** [comment]
Probably the examples predate the animation module, I essentially just copy-pasted and trimmed their general approach.  May be nice to further modernize them to use animation but perhaps not in this PR?

**Comment by jklymak** [comment]
Yep, no problem.  I'll merge...

**Pull request merged**
