### PR TITLE
Refactor some parts of ft2font extension

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

Mainly, this is moving Python-specific code from `ftfont.{cpp,h}` to `ft2font_wrapper.cpp`; this keeps the Python code encapsulated in the one file. Also remove the deprecations that can be expired now.

This is based on #27885, and is a first step in moving to pybind11.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
My reading of the mypy error is that it simply wants the stub to match the final status of the implementation by adding `@final` to decorate the class in the pyi. That makes sense to me, though didn't actually try it to check

**Comment by ksunden** [comment]
build failures on windows do appear to be related here.

**Comment by QuLogic** [comment]
Ah, interesting that designated initializers are so new in C++ vs C.

**Comment by ksunden** [comment]
Remains true that the errors on Windows appear to be related.

**Comment by QuLogic** [comment]
I also put in the deprecated function removals here.

**Comment by tacaswell** [comment]
Changing the classes to `final` needs an API change note as they are technically public.

Do we have any sense of the preformance trade off of doing a single pass but maybe multiple memory allocations vs doing two passes but only one memory allocation?

**Comment by QuLogic** [comment]
> Do we have any sense of the preformance trade off of doing a single pass but maybe multiple memory allocations vs doing two passes but only one memory allocation?

Running tests with `pytest -n4` on my machine, mostly idle, averaging 3 of 5 (dropping best/worst times) gives 236.4 ± 0.3 for the commit before, and 234.4 ± 0.5 after. Now this isn't a true microbenchmark, but at least times aren't horribly worse.

**Comment by QuLogic** [comment]
A possibly reasonable microbenchmark:
```
import string
import timeit

from matplotlib.text import TextToPath
from matplotlib.font_manager import FontProperties, findfont, get_font

ttp = TextToPath()
fp = FontProperties()
font = get_font(findfont(fp))

timer = timeit.Timer("ttp.get_glyphs_with_font(font, string.ascii_uppercase)",
                     globals={'ttp': ttp, 'font': font, 'string': string})

timer.autorange(print)
```
This ends at 500 iterations, with average before of 0.236 ± 0.014s, and average after of 0.231 ± 0.004s.

**Review by tacaswell — APPROVED** [review]

**Comment by QuLogic** [comment]
Snuck in one more thing; noticed that the C++ side's `FT2Image.m_dirty` is unused, so removed it.

**Comment by QuLogic** [comment]
And `ft2font.Glyph` was removed from the API change note because the class part is not public; it isn't exposed in the module and can only be used when returned by some other method.

**Review by oscargus — APPROVED** [review]

**Pull request merged**
