### PR TITLE
pdf: Use explicit palette when saving indexed images

### LINKED ISSUE #20575: cm.set_bad() not working for specific values of grayscale and dpi when saving as pdf
### Bug report

**Bug summary**

When modifying a colormap with cm.set_bad( color='0.9' ) and saving the image as pdf, the bad colors appear as green instead of gray. This happens for some data sets (I cannot reproduce it with synthetic data sets, it happens with some of my datasets), with some dpi values (for the attached example, it happens with dpi of 1200, but not with dpi of 1000), with some grayscale values (for the attached example, it doesn't happen with color values of '0.79' or darker), and when saving as pdf (it does not happen when displaying the figure with plt.show()).

This is the dataset used for the example code: [Data.csv](https://www.dropbox.com/s/7jzqylwwho2je64/Data.csv?dl=0)

**Code for reproduction**

```python
# Paste your code here
#
#

import numpy as np
import pandas as pd

from copy import copy
from matplotlib import cm

from matplotlib import pyplot as plt

fig_size_px = (1280, 960)
fig_dpi = 200
fig_size_inch = tuple( fi/fig_dpi for fi in fig_size_px )

n = 1730
m = 1731

data = pd.read_csv( 'Data.csv', index_col=0, engine='c',  dtype=np.float64 ).values

Mask = np.uint8( np.reshape( data[ :, 0 ], ( m, n ) ) )
data = np.reshape( data[ :, 1 ], ( m, n ) )

cmap_jet = copy( cm.jet )
cmap_jet.set_bad( color='0.9' )
# cmap_jet.set_bad( color='0.78' )
# cmap_jet.set_bad( color=(0.9, 0.9, 0.9) )
# cmap_jet.set_bad( color='#d8dcd6' )

fig4 = plt.figure( 4, figsize=fig_size_inch, dpi=fig_dpi, facecolor='w', clear=True, tight_layout=True )
fig4.clf()
ax4 = fig4.add_subplot(111, aspect='equal')
ax4.cla()

data_masked = np.ma.MaskedArray( data, Mask==0 )

h4 = ax4.imshow( data_masked, origin='lower', cmap=cmap_jet, interpolation='Antialiased' )

ax4.get_xaxis().set_visible( False )
ax4.get_yaxis().set_visible( False )

fig4.savefig( 'Plot_Bad.pdf', dpi=fig_dpi*6, format='pdf', transparent=True )
fig4.savefig( 'Plot_Good.pdf', dpi=fig_dpi*5, format='pdf', transparent=True )
plt.show()

```

**Actual outcome**

[Plot_Bad.pdf](https://github.com/matplotlib/matplotlib/files/6762424/Plot_Bad.pdf)

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

[Plot_Good.pdf](https://github.com/matplotlib/matplotlib/files/6762444/Plot_Good.pdf)

**Matplotlib version**

  * Operating system: Gentoo Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): GTK3Agg
  * Python version: 3.9.5
  * Jupyter version (if applicable): 
  * Other libraries: 

From the distribution repositories

### LINKED ISSUE #25806: [Bug]: pdf export for large image sizes results in wrong colors
### Bug summary

Exporting a figure filled with imshow as pdf is using the wrong colors if the image size/resolution becomes large: E.g. gray cells become red.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

# data: four background tiles with one of them highlighted
background = [0.9]*3 # gray
highlight = [1,0,0] # red
X = np.array([[background,highlight],[background,background]]) # varying colors and combinations gives a rich spectrum of bug-phenotypes

# big figure
dpi, figsize = 500, 20 # less dpi or figsize avoids the bug
fig,ax = plt.subplots(figsize=(figsize,figsize),dpi=dpi)
ax.imshow(X)

# export it
fig.savefig(f'minimal.png') # shows correctly three tiles in gray and one tile in red
fig.savefig(f'minimal.pdf') # shows incorrectly all four tiles in red
```

### Actual outcome

The png export shows the correct colors: 3 quarters gray, 1 quarter red. The pdf export shows incorrect colors: 4 quarters red.
minimal
[minimal.pdf](https://github.com/matplotlib/matplotlib/files/11370977/minimal.pdf)

### Expected outcome

The png and pdf export shows the correct colors: 3 quarters gray, 1 quarter red. I.e. the pdf should also look like the png pasted above.

### Additional information

This bug only appears for large figure sizes and dpi (maybe if figuresize * dpi is larger than some threshold).
It is also dependent on the colors chosen and the content of the image. In my real-world use case I have a large heatmap with many fields and one color is consistently replaced by some other color from the plot. I also observed variations which replace a color with a darker version of it, e.g. if one switches the roles of red and gray in the minimal example above: Then instead of red the background is dark red in the pdf.

This minimal example was executed in a fresh conda env with matplotlib as only dependency. I tried it before with matplotlib 3.6.3 on a less clean environment with the same results. I dont have an example of it working in previous versions.

I guess it is an issue with a buffer of fixed size in the pdf backend, as it works with the png backend.

A workaround can be the reduction of the dpi - for vector graphics this still contains all the information. But it changes the "physical" size of the pdf.

### Operating system

RHEL 7.9

### Matplotlib Version

3.7.1

### Matplotlib Backend

_No response_

### Python version

3.11.3

### Jupyter version

_No response_

### Installation

conda

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

Asking Pillow for an "adaptive palette" does not appear to guarantee that the chosen colours will be the same, even if asking for exactly the same number as exist in the image. Instead, create an explicit palette, and quantize using it.

Additionally, since now the palette may be smaller than 256 colours, Pillow may choose to encode the image data with fewer than 8 bits per component, so we need to properly reflect that in the decode parameters (this was already done for the image parameters).

The effect on test images with _many_ colours is small, with a maximum RMS of 1.024, but for images with few colours, the result can be completely wrong as in the reported #25806.

Since this bugginess requires a large image with few colours and relies on possibly-fixable caching in Pillow, I opted to just update the existing test images instead and we should be a little more careful in changing them in the future.

Fixes #20575
Fixes #25806

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Review by ksunden — DISMISSED** [review]

**Comment by ksunden** [comment]
Looks like there is one additional failing test left unresolved:

`lib/matplotlib/tests/test_image.py::test_figimage[pdf-False]`

**Comment by QuLogic** [comment]
I can reproduce this on Ubuntu WSL, but it's for both `suppressComposite`. Confusingly, if I copy the result into the baseline, `git` shows no differences and the tests still fail. Not sure if there's a Ghostscript bug on Ubuntu.

**Comment by QuLogic** [comment]
Further testing shows that the results are in fact still wrong. Disabling the code for indexed image results in all related tests failing.

Using a fairly simple image of a red gradient with pure Pillow, and the attempted conversion in this PR:
```python
import numpy as np
from PIL import Image

x = np.zeros((256, 1, 3), dtype=np.uint8)
x[:, 0, 0] = np.arange(256)
orig = Image.fromarray(x)

palette = Image.new('P', (1, 1))
palette.putpalette([comp for _, color in orig.getcolors() for comp in color])
new = orig.quantize(dither=Image.Dither.NONE, palette=palette)

print(*new.getdata())
y = np.asarray(new.convert('RGB'))
print(y[:, 0, 0])
np.testing.assert_array_equal(x, y)
```
results in an assertion:
```
255 255 255 255 251 251 251 251 247 247 247 247 243 243 243 243 239 239 239 239 235 235 235 235 231 231 231 231 227 227 227 227 223 223 223 223 219 219 219 219 215 215 215 215 211 211 211 211 207 207 207 207 203 203 203 203 199 199 199 199 195 195 195 195 191 191 191 191 187 187 187 187 183 183 183 183 179 179 179 179 175 175 175 175 171 171 171 171 167 167 167 167 163 163 163 163 159 159 159 159 155 155 155 155 151 151 151 151 147 147 147 147 143 143 143 143 139 139 139 139 135 135 135 135 131 131 131 131 127 127 127 127 123 123 123 123 119 119 119 119 115 115 115 115 111 111 111 111 107 107 107 107 103 103 103 103 99 99 99 99 95 95 95 95 91 91 91 91 87 87 87 87 83 83 83 83 79 79 79 79 75 75 75 75 71 71 71 71 67 67 67 67 63 63 63 63 59 59 59 59 55 55 55 55 51 51 51 51 47 47 47 47 43 43 43 43 39 39 39 39 35 35 35 35 31 31 31 31 27 27 27 27 23 23 23 23 19 19 19 19 15 15 15 15 11 11 11 11 7 7 7 7 3 3 3 3
[  0   0   0   0   4   4   4   4   8   8   8   8  12  12  12  12  16  16
  16  16  20  20  20  20  24  24  24  24  28  28  28  28  32  32  32  32
  36  36  36  36  40  40  40  40  44  44  44  44  48  48  48  48  52  52
  52  52  56  56  56  56  60  60  60  60  64  64  64  64  68  68  68  68
  72  72  72  72  76  76  76  76  80  80  80  80  84  84  84  84  88  88
  88  88  92  92  92  92  96  96  96  96 100 100 100 100 104 104 104 104
 108 108 108 108 112 112 112 112 116 116 116 116 120 120 120 120 124 124
 124 124 128 128 128 128 132 132 132 132 136 136 136 136 140 140 140 140
 144 144 144 144 148 148 148 148 152 152 152 152 156 156 156 156 160 160
 160 160 164 164 164 164 168 168 168 168 172 172 172 172 176 176 176 176
 180 180 180 180 184 184 184 184 188 188 188 188 192 192 192 192 196 196
 196 196 200 200 200 200 204 204 204 204 208 208 208 208 212 212 212 212
 216 216 216 216 220 220 220 220 224 224 224 224 228 228 228 228 232 232
 232 232 236 236 236 236 240 240 240 240 244 244 244 244 248 248 248 248
 252 252 252 252]
Traceback (most recent call last):
  File "/home/elliott/code/matplotlib/foo.py", line 15, in <module>
    np.testing.assert_array_equal(orig, new.convert('RGB'))
  File "/var/container/conda/envs/mpl39/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 983, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/var/container/conda/envs/mpl39/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/var/container/conda/envs/mpl39/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 192 / 768 (25%)
Max absolute difference: 3
Max relative difference: 0.75
 x: array([[[  0,   0,   0]],

       [[  1,   0,   0]],...
 y: array([[[  0,   0,   0]],

       [[  0,   0,   0]],...

```
Even though NumPy says 25% difference, that's for all channels, and only the 256 values from the red channel were unique, so 192 mismatches is really more like 75% difference. You can also see in the printed out indices or the re-converted RGB, that several values are skipped.

Probably due to https://github.com/python-pillow/Pillow/issues/1852#issuecomment-855949860, even the explicit palette used in the example above / in this PR does not work. I think Pillow's quantization is not reliable if we want to have lossless palette conversion. Options seem to be either 1) implement some kind of lookup a) in NumPy or b) via our C extensions; 2) disable this optimization altogether. Whether we do one or the other might depend on the speed vs file size tradeoff.

**Comment by QuLogic** [comment]
We can discuss tomorrow or Thursday; I guess pushing out to 3.8 depends on how we decide to fix it.

**Comment by jklymak** [comment]
It seems for short term we should revert the optimization?  If a proper fix gets in for 3.8, that's great, if not at least we won't have something buggy?  

We should perhaps still consider making interpolation_stage='rgba' the default to avoid the resampling code by default

**Comment by QuLogic** [comment]
> We should perhaps still consider making interpolation_stage='rgba' the default to avoid the resampling code by default

Note that interpolation is a red herring; what really matters is how many colours are in the final image, and possibly its size. Interpolation just changes what the final size is.

**Comment by QuLogic** [comment]
I've now re-implemented the indexing in NumPy, instead of using Pillow. I hoped to add a test that could show simply how the original results were wrong, but in order to reproduce the error from #25806, it requires an image of >= 7073*7073 pixels, which makes a 12s-long test. As many other test images were also changed by fixing this bug, I did not see the benefit of adding such a test instead of updating existing results. Instead, I've added a test that confirms that my original plan of using Pillow's `quantize`-with-an-explicit-palette method does not work (which, if you revert the code back to ba490cb8878d8b8f79b28e3f6b41f53ec07af877, results in an image as in https://github.com/matplotlib/matplotlib/pull/25824#issuecomment-1577994295).

Additionally, to confirm that this code is now correct, I've commented out the block that does this optimization, run the test suite again, and thus checked against the normal RGB version. The only test that fails that is `test_rotate_image` as so:
rotate_image_pdf-failed-diff
And this case seems small enough that it's a PDF renderer issue.

**Comment by QuLogic** [comment]
As an additional test, I wrote a small benchmark:
```python
from io import BytesIO
import struct
import timeit

import numpy as np
from PIL import Image


def _writePng(img):
    buffer = BytesIO()
    img.save(buffer, format="png")
    buffer.seek(8)
    png_data = b''
    bit_depth = palette = None
    while True:
        length, type = struct.unpack(b'!L4s', buffer.read(8))
        if type in [b'IHDR', b'PLTE', b'IDAT']:
            data = buffer.read(length)
            if len(data) != length:
                raise RuntimeError("truncated data")
            if type == b'IHDR':
                bit_depth = int(data[8])
            elif type == b'PLTE':
                palette = data
            elif type == b'IDAT':
                png_data += data
        elif type == b'IEND':
            break
        else:
            buffer.seek(length, 1)
        buffer.seek(4, 1)   # skip CRC
    return png_data, bit_depth, palette


def pillow(data):
    height, width, color_channels = data.shape
    img = Image.fromarray(data)
    img_colors = img.getcolors(maxcolors=256)
    if color_channels == 3 and img_colors is not None:
        num_colors = len(img_colors)
        dither = getattr(Image, 'Dither', Image).NONE
        pmode = getattr(Image, 'Palette', Image).ADAPTIVE
        img = img.convert(
            mode='P', dither=dither, palette=pmode, colors=num_colors
        )
        png_data, bit_depth, palette = _writePng(img)
        palette = palette[:num_colors * 3]


def numpy(data):
    height, width, color_channels = data.shape
    img = Image.fromarray(data)
    img_colors = img.getcolors(maxcolors=256)
    if color_channels == 3 and img_colors is not None:
        num_colors = len(img_colors)
        palette = np.array([comp for _, color in img_colors for comp in color],
                           dtype=np.uint8)
        palette24 = ((palette[0::3].astype(np.uint32) << 16) |
                     (palette[1::3].astype(np.uint32) << 8) |
                     palette[2::3])
        rgb24 = ((data[:, :, 0].astype(np.uint32) << 16) |
                 (data[:, :, 1].astype(np.uint32) << 8) |
                 data[:, :, 2])
        indices = np.argsort(palette24).astype(np.uint8)
        rgb8 = indices[np.searchsorted(palette24, rgb24, sorter=indices)]
        img = Image.fromarray(rgb8, mode='P')
        img.putpalette(palette)
        png_data, bit_depth, palette = _writePng(img)
        palette = palette[:num_colors * 3]


for size in [2, 10, 100, 1000, 10000]:
    print(size)
    data = np.full((size, size, 3), 239, dtype=np.uint8)
    data[:size//2, size//2:, :] = (255, 0, 0)
    for mode in ['pillow', 'numpy']:
        print(mode, timeit.timeit(f'{mode}(data)', globals=globals(), number=10))
```
This creates an 'image' of various sizes in grey with a red square in the top right quadrant, and then tries the old and new indexing. The results are:
```
2
pillow 0.013012180104851723
numpy 0.001572401961311698
10
pillow 0.0008533929940313101
numpy 0.001532592112198472
100
pillow 0.006254185922443867
numpy 0.0027515022084116936
1000
pillow 0.5866641108877957
numpy 0.17633948801085353
10000
pillow 57.763156425906345
numpy 31.72443200601265
```
Surprisingly, in almost all cases, NumPy is faster than Pillow.

**Comment by QuLogic** [comment]
Conflicts are:
```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        both modified:   lib/matplotlib/tests/baseline_images/test_backend_pdf/grayscale_alpha.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_image/image_alpha.pdf
        deleted by us:   lib/matplotlib/tests/baseline_images/test_image/image_placement.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_image/image_shift.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_image/imshow_masked_interpolation.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_image/no_interpolation_origin.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_image/rotate_image.pdf
        both modified:   lib/matplotlib/tests/baseline_images/test_tightlayout/tight_layout5.pdf
```
and these all appear to be caused by #25704 which wasn't backported.

**Comment by QuLogic** [comment]
The backport should work now with #25704 backported, I think.

@meeseeksdev backport to v3.7.x

**Pull request merged**
