### PR TITLE
Added support for using float-tuple like kwarg legend 

### LINKED ISSUE #22338: [Bug]: rcParams['legend.loc'] can't use float-tuple like kwarg legend(loc...)
### Bug summary

We can now use a (x,y) argument for `plt.legend(loc=(x,y))`,
but using the tuple as a value for rcParams['legend.loc'] fails. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import matplotlib as mpl
xs, ys = [1,2,3], [2,3,1]

fig, ax = plt.subplots(3)

ax[0].scatter(xs, ys, label='loc-tuple-arg')
ax[0].legend(loc=(1.1, .5)) # works

ax[1].scatter(xs, ys, label='loc-rcparam-tuple')
mpl.rcParams['legend.loc'] = (0.9, .7)
ax[1].legend() # fails w/o documentation

ax[2].scatter(xs, ys, label='loc-rcparam-str(tuple)')
mpl.rcParams['legend.loc'] = '(.8, .3)'
ax[2].legend() # fails with documentation
```

### Actual outcome

Setting rcParams['legend.loc'] to a tuple fails with 

> AttributeError: 'tuple' object has no attribute 'lower'

setting rcParams['legend.loc'] to the string representation of a tuple fails with a list of supported values. 

### Expected outcome

Ideally  rcParams['legend.loc']  would apply a tuple the same way the kwarg does. 

Second best would be a bit more documentation; 1) reporting the list of supported strings for any un-interpretable value, and 2) mentioning in the default matplotlibrc  that only a set of strings are supported. 

### Additional information

I believe the  `loc` kwarg originally only took string values, but that seems to have been at least a major version ago. 

### Operating system

Ubuntu

### Matplotlib Version

3.3.4

### Matplotlib Backend

TkAgg

### Python version

Python 3.9.7

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by NoyHanan**
closes #22338 

## PR summary
We can now use a (x,y) argument for plt.legend(loc=(x,y)), but using the tuple as a value for rcParams['legend.loc'] fails. 
I Added support for using float-tuple like kwarg legend.
This new change will help to a consistent and a uniform approach to using legend.
Addresses both parts of the issue.

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by tacaswell** [comment]
@NoyHanan Did you mean to delete your branch and close the PR?

**Comment by NoyHanan** [comment]
@tacaswell Yes, I had too many problems with it.
Working on a new one.
Thank you!

**Comment by tacaswell** [comment]
OK, looking forward to seeing it.

**Comment by ksunden** [comment]
Not too sure what happened with the merges (or what other problems you were referring to), but the initial test failure (Azure MacOS with py 3.10) was not due to this PR, that has been consistently happening over the last several weeks on all PRs and is due to install problems on Azure's end.

**Comment by NoyHanan** [comment]
@ksunden It's just that I'm new to open source contributing, and I accidentally pushed and updated when I didn't want to :)

**Pull request closed without merging**
