### PR TITLE
Inline or simplify FooFormatter.pprint_val.

### PR DESCRIPTION
**Pull request by anntzer**
This avoids confusion between the three implementations
(OldScalarFormatter, ScalarFormatter, and LogFormatter).

OldScalarFormatter._pprint_val and ScalarFormatter._pprint_val are not
used elsewhere and can be inlined.
LogFormatter._pprint_val is also used by LogFormatterExponent and must
be kept (even though it looks likely that LogFormatterExponent can also
be simplified , e.g. the test
`abs(math.log(x) / math.log(self._base)) > 10000`
is basically never True for any realistic case -- but that'll be for
another time).

Followup to #12924.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by timhoffm** [comment]
-0.5 on inlineing. Pretty-printing takes a number of lines of code and is a semantic operation of it's own. Therefore it deserves its own function, even if it's just used once.

I would be positive on unifying the API, or maybe moving it to a cbook function.

**Comment by timhoffm** [comment]
I agree with your assessment of the current state. However, my recommendation to changing a bad code structure is to make a better structure, not to throw away all structure.

**Comment by anntzer** [comment]
Well, the good thing is that at least now the structure is private, so we can play with it in whatever way we want...

**Comment by jklymak** [comment]
Lets merge and if we want to re-factor privately we can...

**Pull request merged**
