### PR TITLE
Pin pytest-timeout to fix the build.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

See https://gitter.im/matplotlib/matplotlib?at=5b23860732618e705ebca4ed and below.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
That test case is running minimum (almost) everything.

**Comment by anntzer** [comment]
Now fixed (needed to work around the fact that travis installs a not-up-to-date pytest by default).

**Comment by tacaswell** [comment]
@meeseeksdev backport to v2.2.x

**Comment by tacaswell** [comment]
I assume that backport is going to fail, but I suspect we are going to have the same issues on the 2.2.x branch...

**Comment by QuLogic** [comment]
Backport at #11478.

**Pull request merged**
