### PR TITLE
Import cbook.restrict_dict into backend_gdk

### PR DESCRIPTION
**Pull request by tswsl1989**
Prevents a NameError when using GDK as a backend

### CODE REVIEW

**Comment by tswsl1989** [comment]
Bug triggered by setting "backend: GDK" in ~/.config/matplotlib/matplotlibrc on a Fedora 21 machine, with python-matplotlib 1.3.1-7.fc21

**Comment by tacaswell** [comment]
This was added in https://github.com/matplotlib/matplotlib/pull/1771 and it is not clear it _ever_ worked, backporting this to color_overhaul as well.

Tells us something about how widely used the gdk backend is.

**Comment by tacaswell** [comment]
cherry-picked as 2e445c2c4f66f1e0de9779a3fd966aaf8d8ed2c5

**Comment by tacaswell** [comment]
@tswsl1989 Thank you!

**Pull request merged**
