### PR TITLE
OffsetImage: use dpi_cor in get_extent

### PR DESCRIPTION
**Pull request by Tillsten**
Before the image was always drawn with 72 dpi in the pdf backend, indepent of the dpi setting..

### CODE REVIEW

**Comment by tacaswell** [comment]
looks like a bugfix to me

attn @jkseppan as this names the PDF backend specifically

**Comment by jkseppan** [comment]
It seems to me that since the pdf backend doesn't define `points_to_pixels`, `dpi_cor` would be one and this would have no effect with that backend. This is @leejjoon's code and @NelleV added the FIXME comment, maybe they can comment on the pull request?

**Comment by Tillsten** [comment]
@jkseppan I not 100% this was the right fix, but it does fix my problem and doesn't brake tests.Both backend_bases and backend_agg, which afaik renders the image even in the pdf backend, implement points_to_pixels.

To explain what it fixes: Have a look at

http://matplotlib.org/examples/pylab_examples/demo_annotation_box.html

The png, hires-png and pdf version look all different, which should not be the case
if dpi_cor is set to True.

**Comment by jkseppan** [comment]
I wonder if this is connected to #2831, #3364, #3918, #4375?

attn @mdboom, @WeatherGod

**Comment by WeatherGod** [comment]
Hmm, quite possibly. I'll try out some of the SCCEs in those issues and
report back.

On Tue, Sep 22, 2015 at 8:08 AM, Jouni K. Seppänen <notifications@github.com

**Comment by WeatherGod** [comment]
none of the examples in those issues got fixed by this.

**Comment by efiring** [comment]
@tacaswell I don't see any good reason not to merge this and backport it to 2.x, assuming it fixes the blatant error in our gallery as @Tillsten notes above.

**Comment by efiring** [comment]
The only Travis failure is in the Xcode build:
```
Error: libpng-1.6.23 already installed
To install this version, first `brew unlink libpng`
```
Lots of package installations occurred after this, but then the build apparently stalled and timed out.

**Comment by efiring** [comment]
Back-ported to v2.x as 2fe9e32.  Thank you, @Tillsten!

**Pull request merged**
