### PR TITLE
DOC: Use scientific-python-nightly-wheels for nightly build index

### PR DESCRIPTION
**Pull request by matthewfeickert**
## PR summary

~(Should follow PR #25950)~

The Scientific Python org is requesting that users of the https://pypi.anaconda.org/scipy-wheels-nightly/ package index migrate nightly builds to the new package index https://pypi.anaconda.org/scientific-python-nightly-wheels/ which will have community support moving forward.
   - c.f. https://scientific-python.org/specs/spec-0004/
   - c.f. PR #25950

Example showing all instances are fixed in the docs:

```console
$ git grep "scipy-wheels-nightly" -- doc
doc/users/prev_whats_new/github_stats_3.6.0.rst:* :ghpull:`23349`: CI: Remove old scipy-wheels-nightly uploads to ensure space
```

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
Since I've uploaded a set of wheels, this may be able to go in now even before #25950

**Comment by matthewfeickert** [comment]
> Since I've uploaded a set of wheels, this may be able to go in now even before #25950

@ksunden given that this is ready for review then. :+1:

**Review by ksunden — APPROVED** [review]

**Review by QuLogic — APPROVED** [review]

**Comment by matthewfeickert** [comment]
@ksunden @QuLogic should I backport this to the `v3.7.x` branch? I don't know how to use `meeseeksmachine` so maybe this is something that can be done automatically.

**Comment by tacaswell** [comment]
@meeseeksmachine please backport to v3.7.x

**Comment by tacaswell** [comment]
@meeseeksmachine please backport to v3.7.1-doc

**Comment by ksunden** [comment]
@meeseeksdev please backport to v3.7.x

**Comment by ksunden** [comment]
@meeseeksdev please backport to v3.7.1-doc

**Pull request merged**
