### PR TITLE
[WIP] Close #6968 make autoscale respect tight

### LINKED ISSUE #6968: autoscale differences between 1.5.1 and 2.0.0b3
Based on description of tight ("If True, set view limits to data limits"), I would have expected MPL 1.5.1 behavior (see code and image below).  Though perhaps there was a little margin added intentionally? 

Edit: I see this first part was intended, as change https://github.com/matplotlib/matplotlib/pull/5583. See second issue below.

```
import matplotlib as mpl

plt.plot([1,2,3,4])
plt.autoscale(axis='both', tight=True)

plt.show()
```

limits_tight

---

Aside from this, MPL 1.x use to conveniently adjust view limits for log and symlog when tight autoscaling was not on, but MPL 2 does not seem to do this anymore. 

This actually also looks like a result of https://github.com/matplotlib/matplotlib/pull/5583. I would argue the previous behavior was actually desirable in many instances. Is there a way to recover it? 

```
import matplotlib as mpl

plt.plot([1,2,3,4])

ax = plt.gca()
ax.set_xscale('log')
ax.set_yscale('log')

plt.show()
```

log_scaling

Python 2.7 and 3.4
Using tkagg backend.
Windows 7

### PR DESCRIPTION
**Pull request by jenshnielsen**
The test is currently broken. For reasons that I don't understand yet the margin does not seem to be applied at all in the tests.

### CODE REVIEW

**Comment by tacaswell** [comment]
I suspect it is because the test all run in 'classic' mode with that feature disabled.

**Comment by jenshnielsen** [comment]
Yes I realised that too after pushing. Will fix

**Comment by tacaswell** [comment]
Non-classic tests are currently skipped because https://github.com/matplotlib/matplotlib/pull/6757 has stalled.

**Comment by jenshnielsen** [comment]
Only if they are image comparison right? This fails other tests. Have not had the time to investigate why yet.

**Comment by NelleV** [comment]
I confirm @tacaswell's diagnostic. The tests run fine on my computer on your branch after a rebase + using default style (on the two tests I've executed). Apart from the failing tests that should be quite straightforward to fix, this patch looks good!

**Comment by tacaswell** [comment]
The problem is that if you explicitly use `ax.margins` in (eventually) sets `ax._tight` to `True` to disable the previous default of 'round' numbers.

This is going to take a while to pick apart...

**Comment by tacaswell** [comment]
xref #6968

**Comment by efiring** [comment]
I think I see the problem and how to solve it; I will propose an alternative PR within a few days.

**Comment by efiring** [comment]
closing; replaced by #7458

**Pull request closed without merging**
