### PR TITLE
add support for PySide2, #5971

### PR DESCRIPTION
**Pull request by thliebig**
Signed-off-by: Thorsten Liebig <Thorsten.Liebig@gmx.de>

### CODE REVIEW

**Comment by tacaswell** [comment]
Are things more-or-less 'just working'?

**Comment by tacaswell** [comment]
the IPython folks would probably appreciate a PR into their shim layer as well.

**Comment by thliebig** [comment]
Since the qt5agg is in place for PyQt5 and PySide2 does have the same interface, so far it is just working for me. Of course there might be problems with PySide2 since it is still in active development, but this should all not concern matplotlib. 
We only need to make sure it is possible to request the PySide2 backend and that nothing goes wrong if it is just not installed.

**Comment by tacaswell** [comment]
Can you clean up the style issues?

```
======================================================================
FAIL: matplotlib.tests.test_coding_standards.test_pep8_conformance_installed_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/matplotlib/matplotlib/venv/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/tests/test_coding_standards.py", line 249, in test_pep8_conformance_installed_files
    expected_bad_files=expected_bad_files)
  File "/home/travis/build/matplotlib/matplotlib/lib/matplotlib/tests/test_coding_standards.py", line 143, in assert_pep8_conformance
    assert_equal(result.total_errors, 0, msg)
AssertionError: 3 != 0 : Found code syntax errors (and warnings):
/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_compat.py:68:67: E713 test for membership should be 'not in'
/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_compat.py:68:80: E501 line too long (96 > 79 characters)
/home/travis/build/matplotlib/matplotlib/lib/matplotlib/backends/qt_compat.py:174:80: E501 line too long (86 > 79 characters)
----------------------------------------------------------------------
```

I know it is annoying, but consistently enforcing pep8 really does help maintaining a code base the size of mpl with the number of people we have touching the code.

**Comment by thliebig** [comment]
No problem and I can totally understand the idea. What would be the proper way to do it? Add a commit that fixes it or change/amend the old one??

**Comment by tacaswell** [comment]
attn @mfitzp

**Comment by WeatherGod** [comment]
We are flexible. We only request rebase/squashing when a PR has many
commits, particularly with images. Whichever way you'd like to do it is
fine with us.

**Comment by mfitzp** [comment]
This looks absolutely fine to me and as @thliebig says the interfaces for PyQt5/PySide2 are otherwise identical (thankfully). I've not got PySide2 built on my system to test it but I can have a go later.

**Comment by tacaswell** [comment]
I confirmed that this does not break the existing pyqt5 functionality.

**Pull request merged**
