### PR TITLE
Use json for the font cache instead of pickle

### PR DESCRIPTION
**Pull request by jkseppan**
See discussion at #4756.

### CODE REVIEW

**Comment by WeatherGod** [comment]
Do we even have any unit tests for font caching? The problem with Travis here is that the font cache isn't used there at all, I don't think.

**Comment by mdboom** [comment]
The font cache is always used to draw text, and the test suite draws text.  On Travis, the font cache is rebuilt from scratch each time.  What we *don't* have is a test of saving to disk and loading it again.  But that should be easy enough to write by calling the various functions in font_manager.py directly from a unit test.

**Comment by jkseppan** [comment]
One problem with testing this class is that it searches the filesystem when you call `__init__`. But I guess we can work around that.

**Comment by mdboom** [comment]
I think it's probably good enough to just save and reload the existing singleton (font_manager.py:fontManager) to a temp file.  That *shouldn't* do a lot of file I/O (other than the tempfile).  The generation of the cache itself from the font files on the system is already tested (or at least covered) by the existing unit test suite.

**Comment by mdboom** [comment]
@jkseppan: Do you consider this ready to merge?  Looks good to me.

**Comment by jkseppan** [comment]
I think it should be ready to merge to master, but it's probably too large of a change to add to 1.5.x in the release-candidate phase.

**Comment by mdboom** [comment]
Yes -- definitely not for 1.5.

**Comment by tacaswell** [comment]
Master is fair game for 2.1 code.

**Pull request merged**
