### PR TITLE
TST pandas support bar

### PR DESCRIPTION
**Pull request by NelleV**
## PR Summary

Adds a smoke test for #13187

### CODE REVIEW

**Comment by jklymak** [comment]
Well, that was the original code, but the real error was further down in the issue.

... and I didn’t understand well enough what was going on innpandas to write the test.

**Comment by dopplershift** [comment]
IMO there's nothing wrong with a more "integration test"-like thing that describes the desired behavior rather than a very specific test triggering the error.

**Comment by NelleV** [comment]
When I wrote it, I checked it failed before the patch and passed after.

**Comment by jklymak** [comment]
Sure but this test just errors because it’s not the desired behaviour and never worked.   (You need to specify width with datetime units somehow).     Well we could say that we should be able to infer the width from x which is what @anntzer latest or tries to do.

**Comment by NelleV** [comment]
@jklymak I agree that a smoke test is not ideal, but it is better than not having a test.

**Comment by jklymak** [comment]
I love smoke tests, its just the error was from https://github.com/matplotlib/matplotlib/issues/13186#issuecomment-454212924...  Hopefully your new test checks that use case...

**Comment by jklymak** [comment]
This looks good.   not sure whats going on w/ test cov....

**Comment by dopplershift** [comment]
What's confusing you about the coverage?

**Comment by jklymak** [comment]
Ooops, it looks fine now

**Pull request merged**
