### PR TITLE
hist2d() is now using pcolormesh instead of pcolorfast

### PR DESCRIPTION
**Pull request by jankoeh**
Pull request in response to issue #4615

### CODE REVIEW

**Comment by efiring** [comment]
Interesting, this evidently changed the test image slightly.  This might be related to #4584; it suggests there are inconsistencies in snapping or rounding among our various Artists.  It looks like the problem here is only in the pdf.  In this test the grid is regular, so pcolorfast was using AxesImage in the baseline image.

**Comment by WeatherGod** [comment]
AxesImage is subtly different from the pcolors in that coordinates are
pixel centers versus pixel corners. Does pcolorfast take that into account?

**Comment by WeatherGod** [comment]
Also note that this would be an API change if accepted.

**Comment by efiring** [comment]
@weathergod,  Yes, pcolorfast does take into account the way AxesImage works.  The travis failure is coming from a very subtle shift in *some* boundaries in the pdf output.

**Comment by petehuang** [comment]
@efiring @WeatherGod did you happen to remember if you were leaning towards merging or more discussion at last comment?

**Comment by efiring** [comment]
The test image would have to be changed.  Once this is rebased and all tests pass, I would favor merging it.  It would be nice to fix pcolorfast to work correctly with log scales, but that's a bigger job.
I don't see why this would be considered an API change.

**Comment by WeatherGod** [comment]
The reason for it being an API change is the different interfaces for the
different objects returned by pcolorfast(). This is important for things
like animation code. By pinning the output type to be a particular type of
artist, we do make things more consistent overall, but it is still a
different object than what some users had before, and may have coded
against.

**Comment by dopplershift** [comment]
I agree that it would be an API change; not a particularly disruptive one, but by definition, return types are part of the API.

**Comment by jklymak** [comment]
Closing in lieu of #9987.  Umm, this is slightly rude, as @jankoeh no longer gets credit for the PR.  Happy to close my new one and have them either re-opne and get this one up to snuff, or have them open a new one.  In either case, @jankoeh thanks a lot for this!

**Pull request closed without merging**
