### PR TITLE
[MRG+1] Make radio and check buttons visible

### LINKED ISSUE #7860: widget radio buttons and check buttons no longer display outlines
### Bug report

**Bug summary**

Widget radio buttons and check boxes no longer have outlines in the 2.0.0 release, presumably because with the new style changes: "Most artists drawn with a patch no longer have a black edge by default."

**Code for reproduction**

This can be demonstrated with the widgets example codes:

http://matplotlib.org/examples/widgets/radio_buttons.html
http://matplotlib.org/examples/widgets/check_buttons.html

**Actual outcome**

The buttons are created, and can be clicked on, but you have to guess where they are.

radio_buttons

check_buttons

**Expected outcome**

Buttons should be visible. This worked in the 1.5.x releases.

**Matplotlib version**

- Matplotlib version = 2.0.0
- Python version = 2.7.12
- Platform = MacOS 10.12

- Matplotlib installed via pip

### PR DESCRIPTION
**Pull request by naoyak**
Fixes #7860.

Add `black` edge color to radio and check buttons so they are visible.
img1
img2

### CODE REVIEW

**Comment by dopplershift** [comment]
Fixes #7860.

**Comment by naoyak** [comment]
@dopplershift I haven't written an image comparison test before, but I guess it would mean:

- Produce a simple plot example with check/radio buttons
- Generate the plot PNGs locally and commit them
- Add the image comparison test somewhere (say, `test_widgets.py`)

Does that sound about right?

**Comment by dopplershift** [comment]
That's it exactly.

**Comment by naoyak** [comment]
Thanks for the input, added an image comparison test.

**Comment by QuLogic** [comment]
Since these are a) new tests and b) only broken on the new style, you will need to add `style='default`` to the `image_comparison` decorator or else you won't _really_ be testing that the new style isn't broken.

Also, please amend the last commit so that we don't have an extra copy of the test images.

**Comment by naoyak** [comment]
@QuLogic 
Ah, gotcha. Didn't realize the `image_comparison` decorator defaults to `style='classic'` - might be why it's failing.

**Comment by naoyak** [comment]
btw, is there a way to display both sets of buttons (Radio and Check) and relocate them so they don't overlap?

**Comment by jenshnielsen** [comment]
I have restarted the relevant tests but yes they look like network issues. Failing to install nose from github and failing some url based tests

**Comment by QuLogic** [comment]
> btw, is there a way to display both sets of buttons (Radio and Check) and relocate them so they don't overlap?

Do you mean on the same figure? Use different values for `rax`; the widgets are placed within that `Axes`.

**Comment by naoyak** [comment]
Thanks - actually can you hold off on merge for one sec? Seeing if I can combine the tests into 1 test instead of 2.

**Comment by naoyak** [comment]
OK, I think this is good to merge now. Thanks!

**Comment by phobson** [comment]
Thanks @naoyak!

Backported to `v2.0.x` as 8beb59a86c68334bad8d4783d6d0434db4a95c62

**Comment by QuLogic** [comment]
The backport of this seems to have broken CI somehow.

**Comment by QuLogic** [comment]
`get_status` was added to `CheckButton` in #6018 which is only in 2.1. If it's required for this patch, it might have to be reverted on `v2.0.x`.

**Comment by naoyak** [comment]
@QuLogic the failing test is also from #6018. I'm not sure why only the test made it into `v2.0.x`.

**Comment by QuLogic** [comment]
Oh yes, you're right. Looks like it's just a merge error on backport then. Should be a bit easier to fix then.

**Pull request merged**
