### PR TITLE
FIX: Image scaling for large dynamic range ints

### LINKED ISSUE #10072: imshow doesn't properly display some images
### Bug report

**Bug summary**
When using imshow with larger images, you lose pixel resolution for low intensity pixels with lots of nearby zeros (not sure if the intensity or nearby zeros are relevant, or just relative isolation of the pixel). It's like they're being interpolated away, even if interpolation is set to nearest. This is new behavior in version 2.1.

**Code for reproduction**
Use the attached npy file, which is an image referenced in this test script.
```python
import matplotlib.pyplot as plt
import numpy as np

img = np.load('test_image.npy')

#Display full image
plt.imshow(img, interpolation = 'nearest')
plt.clim(0, 5)
plt.show()

#Display part of image
plt.imshow(img[200:400,500:700], interpolation = 'nearest')
plt.clim(0, 5)
plt.show()
```

**Actual outcome**
Using matplotlib 2.1.1:
Screenshot from the display of full image (first plot in code above):
full_plot_2p1

Using the  zoom tool to zoom in on a region when the full image is plotted:
zoom_full_plot_2p1

Plotting roughly the same zoom region initially (second plot in code above):
partial_plot_2p1

**Expected outcome**
It should all look like the third image. Here's the output when the same code is run in version 2.0.2
Screenshot from the display of full image (first plot in code above):
full_plot_2p0

Using the  zoom tool to zoom in on a region when the full image is plotted:
zoom_full_plot_2p0

Plotting roughly the same zoom region initially (second plot in code above):
partial_plot_2p0

**Matplotlib version**
  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.1.1 (broken) and 2.0.2 (working)
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 2.7.12
  * Other libraries: numpy version 1.13.3

All libraries are installed through conda, using the standard channel. This includes both versions of matplotlib (2.1.1 and 2.0.2).

Numpy file with image data:
[test_image.zip](https://github.com/matplotlib/matplotlib/files/1579886/test_image.zip)

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This fixes #10072.

The problem was that for a uint32 image, the dynamic range was too high for a float32 to properly represent.  Simply changing to float64 fixes the issue.  I suppose someone could use a unit64 image, but...

Test coming: code:

```python
import matplotlib.pyplot as plt
import numpy as np

img = np.load('/Users/jklymak/downloads/test_image.npy')
img = np.array([[1, 2, 3], [1, 2, 10000000000]], dtype=np.uint32)
#Display full image
plt.imshow(img, interpolation = 'nearest')
plt.clim(0, 5.)
plt.show()
```

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
That's not going to help the efforts on trying to reduce the memory footprint of imshow... (#6952, #8143, etc.).  Not a blocker, but should be kept in mind.

**Comment by jklymak** [comment]
Yeah, understood.  This is the dumbest solution.  

I don't quite understand why this rescaling is necessary, despite the nice comments....

**Comment by jklymak** [comment]
OK, I only used the bigger float64 if the amin-amax > 1e8.

**Comment by anntzer** [comment]
I think(?) you probably care more about maxabs/minabs.

**Comment by jklymak** [comment]
Hmmm, not at all sure, because I once understood all the low-level reps of floats etc, but not so good at it anymore.  Happy if someone wants to pick this up and do it better.

But, I think the error comes in when we do:

https://github.com/matplotlib/matplotlib/blob/884060ac59c4c15e657e418e3e4cd59ceb810107/lib/matplotlib/image.py#L389-L390

and the resulting float doesn't preserve all the bits in the `unit32`.

**Comment by tacaswell** [comment]
This is a reasonable approach. 

The scaling is to be able to track the over/under pixels and get around ringing in the interpolations.

**Comment by tacaswell** [comment]
Discussed this on the phone call.  Will investigate

 - delaying conversion to float as long as possible
 - avoiding float128 due to platform-dependence
 - add a test

**Comment by jklymak** [comment]
Test added, and changes requested above made...  Thanks!

**Pull request merged**
