### PR TITLE
FIX: maintain return type stability in win32InstalledFonts

### LINKED ISSUE #12173: Cannot import pyplot
### Bug report

**Bug summary**
I am unable to `import matplotlib.pyplot` starting in version 3.0.0. Might be related to Issue #9485?

**Code for reproduction**

```python
import matplotlib.pyplot as plt
```

**Actual outcome**

I get the following traceback when executing the above `import`

```
Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1353, in <module>
    fontManager = json_load(_fmcache)
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 888, in json_load
    with open(filename, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\.matplotlib\\fontlist-v300.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:\Python\Python35\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Python\Python35\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.contour as contour
  File "C:\Python\Python35\lib\site-packages\matplotlib\contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1363, in <module>
    _rebuild()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 1344, in _rebuild
    fontManager = FontManager()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 978, in __init__
    ttffiles = findSystemFonts(paths) + findSystemFonts()
  File "C:\Python\Python35\lib\site-packages\matplotlib\font_manager.py", line 264, in findSystemFonts
    fontfiles.update(win32InstalledFonts(fontext=fontext))
TypeError: 'NoneType' object is not iterable
```

**Matplotlib version**

  * Operating system: Windows 10 64-bit
  * Matplotlib version: 3.0.0
  * Matplotlib backend: TkAgg
  * Python version: 3.5.4
  * Jupyter version (if applicable): NA
  * Other libraries: NA

Installed via `pip`

### PR DESCRIPTION
**Pull request by tacaswell**
closes #12173

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
@Cory-Kramer can you see if this fixes it?  I don't have a windows machine I can test on or know how to exercise this code path on appveyor....

**Comment by Cory-Kramer** [comment]
Just tested this change locally, yes it does fix the import issue.

**Comment by dsentinel** [comment]
Not sure if this should be addressed here, or another PR.
Similar issue on mac details in #12173

**Comment by jklymak** [comment]
@dsentinel I'm unable to reproduce on master with my mac, so not sure whats going on here.  Any chance you are up to checking this PR on your setup?  Its a bit of a heavy ask because you need to add @tacaswell 's repo as a remote and then `pip install -e .` , but once you learn how to do it, its not too bad.

**Comment by dsentinel** [comment]
I'd be happy to test the tree, but not sure I will be able to today

If you want to try with a conda my environment.yml

```yaml
name: mat_bug_py37
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.4.16=py37_0
  - clangdev=6.0.1=default_1
  - cycler=0.10.0=py_1
  - freetype=2.9.1=h6debe1e_4
  - icu=58.2=hfc679d8_0
  - kiwisolver=1.0.1=py37h2d50403_2
  - libcxx=6.0.1=0
  - libffi=3.2.1=hfc679d8_5
  - libiconv=1.15=h470a237_3
  - libpng=1.6.35=ha92aebf_2
  - libxml2=2.9.8=h422b904_5
  - llvm-meta=6.0.1=0
  - llvmdev=6.0.1=hf8ce74a_2
  - matplotlib=3.0.0=py37h45c993b_0
  - ncurses=6.1=hfc679d8_1
  - openssl=1.0.2p=h470a237_0
  - pip=18.0=py37_1
  - pyparsing=2.2.1=py_0
  - python=3.7.0=h4eca856_1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - readline=7.0=haf1bffa_1
  - setuptools=40.4.0=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.25.1=hb1c47c0_0
  - tk=8.6.8=ha92aebf_0
  - tornado=5.1=py37h470a237_1
  - wheel=0.31.1=py37_1
  - xz=5.2.4=h470a237_1
  - zlib=1.2.11=h470a237_3
  - blas=1.0=mkl
  - intel-openmp=2019.0=118
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.0=118
  - mkl_fft=1.0.4=py37h5d10147_1
  - mkl_random=1.0.1=py37h5d10147_1
  - numpy=1.15.1=py37h6a91979_0
  - numpy-base=1.15.1=py37h8a80b8c_0
```

don't forget the bug shows if `~/.matplotlib/fontlist-v300.json` does not exist.

**Comment by dsentinel** [comment]
Apologies for claiming a hang. It turns out if you have a large tree under your current directory,
The empty string at the end of this list:
https://github.com/matplotlib/matplotlib/blob/1a40221e2651b465bdacce24e071d36951214ee0/lib/matplotlib/font_manager.py#L126-L133
will get used in this glob `**/*.*`
https://github.com/matplotlib/matplotlib/blob/1a40221e2651b465bdacce24e071d36951214ee0/lib/matplotlib/font_manager.py#L150-L158
and this can take a long while... minutes+ but will eventually return, if your FS is finite.

Not very pleasant, but still probably a bug.

Hard to reproduce if you're in a small dir trying to recreate :/ ... These hairy bugs are a pain, almost eluded me.

**Comment by dsentinel** [comment]
Looks like this was a typo, and then a flake commit included `""` which pathlib interperetes as `.`
https://github.com/matplotlib/matplotlib/pull/11963/files#r218979454

**Comment by dsentinel** [comment]
opened #12176

**Comment by anntzer** [comment]
The patch looks fine but I'm a bit confused why we didn't hit this before.  On the one hand, in https://github.com/matplotlib/matplotlib/commit/898998c7f24a7b7aa930bc5e387061e05aa60b62#diff-915a89f5ee0062db3d8190c8505a240fL186 there is the slightly ominous deletion of
```
        if not local:
            return list_fonts(directory, fontext)
```
which is the only relevant difference I can find.  On the other hand, the docs clearly say that any non-closed, non-detached key is truthy (https://docs.python.org/3/library/winreg.html#registry-handle-objects) and that failure to open a key results in an exception, not a falsy key (https://docs.python.org/3/library/winreg.html#winreg.OpenKey), so it's not clear how that specific conditional could ever have been triggered before.

**Comment by anntzer** [comment]
not really...

**Comment by Kojoley** [comment]
The only way that can result in `None` after https://github.com/matplotlib/matplotlib/commit/898998c7f24a7b7aa930bc5e387061e05aa60b62#diff-915a89f5ee0062db3d8190c8505a240fL186 change is if `winreg.EnumValue` throws an exception for some reason (f.ex. number of entries in registry has lowered since `winreg.QueryInfoKey` call during the loop).

**Comment by tacaswell** [comment]
I am happy to defer to @Kojoley on this issue.

**Comment by timhoffm** [comment]
No matter when or why that code path is executed, the return value should be `[]` instead of `None`.

**Comment by Kojoley** [comment]
Superseeded by #12213

**Pull request closed without merging**
