### PR TITLE
Add \underline to mathtext

### PR DESCRIPTION
**Pull request by wesbarnett**
## PR Summary

Implements #14235 to add \underline to mathtext.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by pprasha** [comment]
let me take a look

**Comment by wesbarnett** [comment]
@jklymak can you take a look? Super late getting to this, but I think it's done

**Comment by jklymak** [comment]
@wesbarnett popping to draft until the rebase gets figured out....  You may need to follow instructions at https://discourse.matplotlib.org/t/default-branch-renamed-with-minor-edit-to-history/22367/2  Thanks!

**Comment by tfpf** [comment]
There haven't been any updates here for a while. Unless I am mistaken, this is not extremely hard to implement. The details are in node 735 of _TeX_, but it doesn't look that's what's happening here?

**Comment by tfpf** [comment]
I think mimicking TeX's behaviour is straightforward. Not sure how exactly `overline` works, but TeX puts a space between the text and the underline equal to thrice the thickness of the underline (even if the text has depth). Just adding vertical kerning should work?

I can open another pull request to implement it if that's okay.

**Comment by timhoffm** [comment]
> I think mimicking TeX's behaviour is straightforward. Not sure how exactly `overline` works, but TeX puts a space between the text and the underline equal to thrice the thickness of the underline (even if the text has depth). Just adding vertical kerning should work?
> 
> I can open another pull request to implement it if that's okay.

I'm not a TeX expert, but if you have a straight-forward solution, please go ahead and open a new PR.

**Comment by melissawm** [comment]
It looks like there are two PRs trying to solve the same issue here - this one and #23616. Any chance @wesbarnett and @tfpf could team up or review each other's work so this feature can move forward? Thanks!

**Comment by rcomer** [comment]
Looks like @tfpf opened the other PR because this one had stalled....

**Comment by tfpf** [comment]
Initially, I though this approach could be improved by applying the `make_under` procedure of TeX (node 735 in _TeX: the Program_). To my utter surprise, wesbarnett's code (from here) and the TeX code (from https://github.com/matplotlib/matplotlib/pull/23616) produce the exact same images! Unless I have terribly messed something up, the PNG files are identical, byte for byte; the SVG files are also identical, at least visually.

w
w
```
import matplotlib.pyplot as plt
fig = plt.figure()
plt.text(.5, .5, r'$\underline{ul}$', size=50)
plt.axhline(.5)
plt.savefig('s.svg')
plt.savefig('p.png')
plt.show()
```

Note that the SVG and PNG backends render the image differently. I got stuck here, and documented it in https://github.com/matplotlib/matplotlib/issues/23763. Still unable to figure out why _that_ happens.

**Comment by wesbarnett** [comment]
My PR is so far off with `main` at this point, I'm happy to close this as a duplicate of #23616. (My implementation was basically copying the overline functionality and making a few adjustments for it to be used as an underline.

**Pull request closed without merging**
