### PR TITLE
Remove various Python 2.6 related workarounds

### PR DESCRIPTION
**Pull request by jenshnielsen**
Now that we don't support 2.6 any more we might as well get rid of this. This is what I found from grepping the code so there might as well be more that we can delete. 

I also fixed the version check in `__init__` we might want to backport that to 2.0.x

### CODE REVIEW

**Comment by jkseppan** [comment]
The changes look good to me, and the tests are passing. I guess one question may be whether we want to error out immediately when running in 2.6, or just give a warning and try to run in any case, since at least the way I understood the announcement as merely withdrawing "official support".

**Comment by jenshnielsen** [comment]
With #5299 merged (which depends on functool32 which is python 2.7 and later only) I think we have broken 2.6 support fully. This should not go into 1.5.x which should still work with 2.6

**Comment by jkseppan** [comment]
You're right, Python 2.6 won't run current master. :+1:

**Comment by mdboom** [comment]
We may also want to consider a friendly error message on Python 2.6 from `setup.py` similar to the one in `__init__.py`.  No point in installing it only to find out it won't work later.

**Comment by tacaswell** [comment]
back-ported to v2.0.x as 1866a8c

**Comment by joranbeasley** [comment]
can you at least tell me which version i should install if i do want py2.6?

**Comment by WeatherGod** [comment]
v1.5.3 should support 2.6, IIRC

**Comment by tacaswell** [comment]
The 1.4 series is the last versions to officially support python 2.6.

There was a loing discusion about this in 2015 http://matplotlib.1069221.n5.nabble.com/Matplotlib-devel-supported-python-versions-tt46154.html and no one volunteered to take care of 2.6 compatible branch so it got dropped.

@joranbeasley I have deleted your comment.  Insulting core maintainers (who are volunteers) is not condusive to us taking your concerns seriously.  Please be civil in our channels.

**Comment by WeatherGod** [comment]
Thomas is right. v1.4.x was the last one to support py26. My memory was
faulty.

**Pull request merged**
