### PR TITLE
mpl_toolkits: Fiducials/Landmark markers

### PR DESCRIPTION
**Pull request by JGoutin**
I created a toolkit for use numbered fiducial "cross" markers with Matplotlib interactively.

This is mainly useful for image processing, but may also help for other cases.

I propose it for adding in mpl_toolkits.

### CODE REVIEW

**Comment by tacaswell** [comment]
Nifty (attn @licode this is probably useful at BNL).

This would probably do better as a stand alone repo under the mpl organization (which decouples you from our glacial release cycle :wink: )

This might also fit in @joferkington 's mpldatacursor?

Have only skimmed this, but might have some interaction with @blink1073 's widget work?

**Comment by JGoutin** [comment]
Your release cycle don't bother me. I didn't planed to update this really intensively :wink:.

I not tested interactions with packages other than MPL. There is maybe some possible conflicts on keys shortcuts.

**Comment by licode** [comment]
I think so. Good to know this feature.

**Comment by blink1073** [comment]
@tacaswell, yeah, these could certainly overlap (especially for the advanced marker types), if I ever get around to finishing #5786.

**Comment by anntzer** [comment]
I think this kind of feature belongs more to a third-party package (there is some overlap with mpldatacursor and mplcursors -- disclaimer, I wrote the later).
A dependency, even optional, on skimage is a non-starter IMO.
This would also need some testing.

Unless someone objects, I will close the PR.

**Comment by JGoutin** [comment]
You can close this PR. I see not objects.

Note: I'll not make a third party package for this. If someone is interested by getting this, no problems, I can eventually help to add this to another package. If not, I'll delete my forked repository when this PR will be closed.

**Comment by anntzer** [comment]
Closing based on lack of activity or objections against closing...

**Pull request closed without merging**
