### PR TITLE
TST: Don't use set -e.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This may or may not help with Travis, if we're lucky.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
No luck with that, but let's debug a little.

**Comment by QuLogic** [comment]
No luck so far; feel free to push any other ideas, but maybe squash before merging if it works.

**Comment by jklymak** [comment]
I think we should temporarily drop `gdb` until we can sort out what is going on.

**Comment by jklymak** [comment]
This is passing travis-ci.  I suggest we merge this for now until we figure out what gdb is doing.  I can modify #10216 so it is a reminder that gdb has been removed....

**Comment by jklymak** [comment]
Sorry @QuLogic , I hijacked your debug branch to get this working again.

**Comment by tacaswell** [comment]
:+1: nice team work

**Comment by QuLogic** [comment]
Backported to `v2.1.1-doc` as cca6e68651cf2d8683b4967019aad163d55f77e9; we need this everywhere to have Travis passing.

**Pull request merged**
