### PR TITLE
Cleanup mpl_toolkits locators.

### PR DESCRIPTION
**Pull request by anntzer**
mpl_toolkits locators have a separate API from "normal" Locators.  Work
towards unifying them by deprecating the unused set_factor method.

Also remove a branch for the never-unset _ignore_factor attribute of
FormatterPrettyPrint.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dstansby** [comment]
Just tried fixing the merge conflict with the web UI for the first time

**Comment by anntzer** [comment]
rebased

**Comment by timhoffm** [comment]
Anybody can merge after rebase.

**Comment by anntzer** [comment]
rebased

**Pull request merged**
