### PR TITLE
Revert backport of #21631 to v3.5.0-doc

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This PR renames a tutorial, and thus needs to update a link in a `.py` file. Changes to `.py` files have no effect on the -doc branch, because it is run against the released version, so this breaks the build since the old link is gone.

This reverts commit 37131e99a84709d3095c46f006b470d786830ae1.

## PR Checklist

**Tests and Styling**
- [n/a] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [n/a] New features are documented, with examples if plot related.
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by QuLogic** [comment]
The Basic usage guide backport also appears to have broken things. I have half a mind to force-push these backports away, since this isn't `main`.

**Comment by jklymak** [comment]
Oh, thats confusing.  Sorry for the breakage, and of course feel free to revert what is needed.

**Comment by jklymak** [comment]
... that is even more confusing, as the back ports passed CI - I guess its not worth having a different CI for these branches, but...

**Comment by tacaswell** [comment]
We do not run the link-checker as part of CI and the CI does not try to install the released version.

Given that we now have a handful of git-related checks on GHA, I suspect would could set up a check that asserts nothing in the lib or src directories are changed on `*-doc` branches.

**Comment by tacaswell** [comment]
I'm mixed on force-pushing to `-doc`.  On one hand I'm against doing it as a bit of a social / process control thing.  "do not force push to the matplotlib/matplotlib repo" is a very easy rule to understand and enforce.  But we have broken 2x in the last 5 years (once "for real" and once kinda-sorta-language-lawyer-maybe-not)  so it is actually "do not force push to the matplotlib/matplotlib repo except in extenuating circumstances" which is fuzzier.   Doing it here would be another step down the path to normalizing force-pushing to matplotlib/matplotlib (slippery slope etc etc) so we should not.

On the other hand, there is no reason to keep commits + their reversions around, this is not `main` and I strongly suspect that @QuLogic is the only person in the world that currently has it as a local branch so just do the simple thing and move on.

I'm pretty 50/50 on this and am OK with either option.

**Comment by QuLogic** [comment]
Fixing the usage guide is less work than I thought (only one line), but now I see other stuff was merged, so I'll need to check that that is okay.

**Comment by jklymak** [comment]
I think there was only #21813 and #21815...

**Pull request merged**
