### PR TITLE
Fix broken QApplication init in a test.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by anntzer — APPROVED** [review]
postci

**Comment by QuLogic** [comment]
Hmm, actually, this still crashes for me if run by itself. I think it just worked because something else ran before it.

**Comment by tacaswell** [comment]
Shouldn't this be using our "get or make the qt application" helper from `qt_backend`?

**Comment by QuLogic** [comment]
Yea, that works; now I can directly run `pytest lib/matplotlib/tests/test_backend_qt.py::test_form_widget_get_with_datetime_and_date_fields` without it crashing.

**Review by dstansby — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
