### PR TITLE
Don't merge: FIX: fixing Qt5Agg speed issue

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This hack addresses #9406, #10140 and #10162 by partially rolling back the changes @tacaswell made to address the first two issues.  

I'm not going to pretend I actually understand why there was a performance hit from https://github.com/matplotlib/matplotlib/commit/9b8a944db954c8240e14413e517e1b781881b80b#diff-24fdb85343951b7d9bd270c47d6abe8f and why this fixes it.  I tested the other two issues and they seem fine as well.  

Feel free to close this if someone has a "proper" solution for what is going on here, and use this as a hint...

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Oh, I get it.  `self.draw_idle()` was setting `self._agg_draw_pending = True` and not setting it in the `finally:` was leaving it True, so the re-draw wasn't happening.

**Comment by WeatherGod** [comment]
Maybe a comment explaining that would be useful. From my perspective, I
would be totally confused by the fact that agg_draw_pending was set to
False already before the try...except.

**Comment by jklymak** [comment]
Finally figured out what was happening.  By leaving as True, `self.paintEvent` would run the next event loop, despite the fact nothing had changed...

**Comment by tacaswell** [comment]
How is it getting set to true?  Line 149 at the top of the function sets it to False...

**Comment by jklymak** [comment]
It gets set to `True` after `self.draw()`, tested via print statements...

**Comment by tacaswell** [comment]
I will have a slightly different PR to fix this (sorry, race conditions are fun!)

**Pull request closed without merging**
