### PR TITLE
Fix Pillow compatibility in example

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Should fix https://github.com/matplotlib/matplotlib/pull/23855#issuecomment-1245059589

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by anntzer** [comment]
Instead of resampling down the stinkbug image down to 64x64 via pillow code (which is a bit distracting for the tutorial, especially if you start having version gating like here), perhaps simpler would be to just crop down to its central region?  e.g. img[175:225, 225:275] seems reasonable.  (Obviously the surrounding text needs adjusting too.)

**Comment by oscargus** [comment]
To be fully honest, I didn't read another line of the code except for the problematic one...

Doing that, do we actually need to specify the resampling scheme? I mean, it is really a Pillow-function that we are using, so maybe it is not that important? (Default is bicubic.)

(Btw, we also provide an, untested, thumbnail function, although that reads the file, possibly pops it up, and then saves it, as well as returning a Figure.)

**Comment by anntzer** [comment]
I didn't really pay attention to the context either.

**Comment by oscargus** [comment]
I changed it to not specify resampling scheme (as that sort of makes sense as well and my previous approach was wrong).

**Comment by oscargus** [comment]
It seems like the `pikepdf` install is suddenly failing...

**Comment by oscargus** [comment]
"Windows support is currently blocked": https://github.com/pikepdf/pikepdf/issues/390

Pin version (on Windows)?

**Review by anntzer — APPROVED** [review]

**Comment by tacaswell** [comment]
> Pin version (except for Linux)?

Yes

**Pull request merged**
