### PR TITLE
Uncaught exns are fatal for PyQt5, so catch them.

### PR DESCRIPTION
**Pull request by anntzer**
See discussion starting at https://github.com/matplotlib/matplotlib/issues/6816#issuecomment-244838928.

Minimal example:
```
from matplotlib import pyplot as plt
plt.gcf().canvas.mpl_connect("draw_event", lambda event: 1/0)
plt.show()
```

### CODE REVIEW

**Comment by WeatherGod** [comment]
Looks good to me. The Appveyor failure does seem un-related, but possibly not transient?

Should this get cherry-picked to 1.5.x as well as 2.x?

**Comment by anntzer** [comment]
I'd suggest doing so.

**Comment by jenshnielsen** [comment]
There is no 1.5.x branch to cherry-pick onto at the moment.

**Comment by tacaswell** [comment]
I have a running list of things to backport.  We probably should give up an re-create the 1.5.x branch :/

**Comment by tacaswell** [comment]
backported to v2.x as c5cdc1a

**Comment by tacaswell** [comment]
backported to v1.5.x as 81d5a24f1554d1284f3306f82782cc5cb027052a

**Pull request merged**
