### PR TITLE
Added alias color for c in axes.scatter for Issue #3489

### PR DESCRIPTION
**Pull request by yangineer**
Greetings!

I added a fix to pop "color" off the kwargs list and assign it to c.
This fixes the skipping colors problem in Issue #3489.
I also added a image comparison test for the fix.

### CODE REVIEW

**Comment by tacaswell** [comment]
This may conflict with https://github.com/matplotlib/matplotlib/pull/4079

**Comment by tacaswell** [comment]
Thank you for the patch (with tests)!

I am on my way to bed and don't have the bandwidth to do a more through review right now.

**Comment by efiring** [comment]
@yangineer #4079 also pops color.  I think it takes care of present problems in a more comprehensive way.  Please check it out.

**Comment by yangineer** [comment]
Oops, how did I not see #4079?
Wow, that's a much better solution. It handles all the other color kwags too!

**Pull request closed without merging**
