### PR TITLE
Drop conditional import of figureoptions.

### PR DESCRIPTION
**Pull request by anntzer**
As far as I can tell, the only way the import of figureoptions could
fail is under PyQt 4.3 or earlier (QFormLayout was introduced in Qt
4.4).  PyQt 4.4 was released in 2008 and the oldest version still
downloadable on SourceForge seems to be 4.9, so that seems safe...

Also up the version requirement on PyQt.

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: , but it looks like the doc failure is real and caused by this change.

**Comment by anntzer** [comment]
Do you know what's the version of Qt used on Travis?  I couldn't find a reference to it.

**Comment by jenshnielsen** [comment]
As far as I remember travis mocks out qt when building the docs

**Comment by anntzer** [comment]
This may explain why QtGui appears as a "type object" rather than a module in the traceback.
Do you have a pointer as to how the mocking is done?

**Comment by tacaswell** [comment]
It is done in conf.py https://github.com/matplotlib/matplotlib/blob/master/doc/conf.py#L328

**Pull request merged**
