### PR TITLE
"Fix" tight_layout for template backend.

### LINKED ISSUE #17730: Using backend Template and plt.tight_layout raises UnboundLocalError
Matplotlib 3.3.0rc1 appears to be breaking our documentation builds at scikit-image, see 

https://travis-ci.org/github/scikit-image/scikit-image/jobs/701180133#L5665-L5691

I was able to create a minimal example that reproduces the error on my machine, see code below.

### Bug report

**Bug summary**

```python
import numpy as np
import matplotlib
matplotlib.use('Template')
import matplotlib.pyplot as plt

fig, axes = plt.subplots()
axes.imshow(np.random.random((5, 5)), cmap=plt.cm.gray)
plt.tight_layout()
```

**Actual outcome**

```pytb
Traceback (most recent call last):
  File "mpl_error.py", line 8, in <module>
    plt.tight_layout()
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1489, in tight_layout
    gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/figure.py", line 2604, in tight_layout
    renderer = get_renderer(self)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 176, in get_renderer
    return backend_bases._get_renderer(fig)
  File "/home/jni/miniconda3/envs/skimage-test/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1556, in _get_renderer
    return renderer
UnboundLocalError: local variable 'renderer' referenced before assignment
```

**Expected outcome**

No crash.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.0rc1
  * Matplotlib backend (`print(matplotlib.get_backend())`): Template
  * Python version: 3.8.3
  * Jupyter version (if applicable): N/A
  * Other libraries: 1.19.0

**Installation**

```
conda create -n matplotlib-rc python=3.8
conda activate matplotlib-rc
pip install --pre matplotlib numpy
```

### PR DESCRIPTION
**Pull request by anntzer**
We rely on print_foo actually walking through the Figure tree (which any
non-trivial canvas should likely do...).

Closes #17730.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
To be honest I don't know why we expose the template backend as a "real" backend, but heh.
I wouldn't bother with docs unless someone shows me a real backend that can implement print_foo() without walking the Figure tree...

**Comment by tacaswell** [comment]
How is this preventing a unbound local?

**Comment by anntzer** [comment]
The unbound local comes from the fact that previously, `FigureCanvasTemplate.print_foo()` did not `figure.draw(renderer)` (which I argue is unrealistic of any non-trivial drawer), whereas get_renderer() works by overriding `figure.draw()` to immediately throw ("goto") back to the caller and propagating the renderer out of the call stack.  Now `print_foo()` does call `figure.draw(renderer)` and everyone is happy.

**Comment by jni** [comment]
With the caveat that I don't know the codebase, it seems to me that UnboundLocals need to be fixed in the code structure itself and should not be allowed to happen, regardless of what a canvas *should* do vs actually does.

I also agree with @timhoffm that a test should be added, especially since based on comments in #17730 skimage might move to Agg for this check, which means we wouldn't be implicitly testing this for you in the future. :grimacing:

**Comment by anntzer** [comment]
Got rid of the UnboundLocalError (in favor of a RuntimeError).  Someone else gets to write the test if you really want it... (I'd think we should just run a full test suite against all of backend_template (which is completely untested) if we really want to support that, rather than doing so in a piecemeal fashion).

**Comment by anntzer** [comment]
Pushed a second commit that fixes https://github.com/matplotlib/matplotlib/issues/17744.  May be better to rewrite _get_output_canvas() to be a context-manager that auto-restores the original canvas at exit, but let's keep that for later (also, name suggestions would be welcome).

**Comment by QuLogic** [comment]
Oh, I forgot about the testing stuff, oh well.

**Pull request merged**
