### PR TITLE
Fix download of freetype 2.6.1.

### PR DESCRIPTION
**Pull request by anntzer**
by checking file hash before exiting the download loop.

attn @QuLogic

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by dopplershift** [comment]
@meeseeksdev backport to v2.1.x

**Comment by dopplershift** [comment]
Ok, I'm not seeing a new PR for the back port...

**Comment by tacaswell** [comment]
it only listens to fixed list of people right now, you may not be on it.

@meeseeksdev backport to v2.1.x

**Comment by dopplershift** [comment]
Good, less work for me. 😝

**Comment by Carreau** [comment]
> Good, less work for me.

I think you are on the whitelist now. 
Also ; if you edit the 2.1 milestone on add in the description field:

```
on-merge: backport to v2.1.x
```

On a line on it's own (you can do several `on-merge` line), it _should_ auto-trigger.
The milestone should be before merging of course.

**Pull request merged**
