### PR TITLE
Function to add a slope-intercept line to an existing plot

### PR DESCRIPTION
**Pull request by shukkkur**
## PR Checklist

 
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by jklymak — CHANGES_REQUESTED** [review]
Thanks for the PR! But `plot_types` is for matplotlib core functions, not examples.  Perhaps this could go in examples, but it is pretty rudimentary and does not really show a plotting feature, but rather a (simple) bit of math.

**Comment by WeatherGod** [comment]
Should use `plt.axline()`, which is relatively new, so we should advertise it.

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axline.html

**Comment by WeatherGod** [comment]
This is also almost exactly the same as the accepted answer here: https://stackoverflow.com/questions/7941226/how-to-add-line-based-on-slope-and-intercept-in-matplotlib

**Comment by tacaswell** [comment]
Thank you for your work on this.

Even though it it not going in we appreciate the work and hope to hear from you again!

**Pull request closed without merging**
