### PR TITLE
FIX: always decode byte strings from AFM files as utf8

### LINKED ISSUE #9196: UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 20: ordinal not in range(128)
### Bug report

**When I want to use `pyplot` from `matplotlib`, it causes error.
There is no problem with `import matplotlib` but I cannot use `pyplot`**

**Code for reproduction**

```python
from matplotlib import pyplot
```

**Actual outcome**

```
---------------------------------------------
FileNotFoundErrorTraceback (most recent call last)
/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in <module>()
   1428         try:
-> 1429             fontManager = pickle_load(_fmcache)
   1430             if (not hasattr(fontManager, '_version') or

/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in pickle_load(filename)
    964     """
--> 965     with open(filename, 'rb') as fh:
    966         data = pickle.load(fh)

FileNotFoundError: [Errno 2] No such file or directory: '/home/javad/.cache/matplotlib/fontList.py3k.cache'

During handling of the above exception, another exception occurred:

UnicodeDecodeErrorTraceback (most recent call last)
<ipython-input-3-a371ea114746> in <module>()
----> 1 from matplotlib import pyplot

/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py in <module>()
     27 from cycler import cycler
     28 import matplotlib
---> 29 import matplotlib.colorbar
     30 from matplotlib import style
     31 from matplotlib import _pylab_helpers, interactive

/usr/lib64/python3.6/site-packages/matplotlib/colorbar.py in <module>()
     34 import matplotlib.collections as collections
     35 import matplotlib.colors as colors
---> 36 import matplotlib.contour as contour
     37 import matplotlib.cm as cm
     38 import matplotlib.gridspec as gridspec

/usr/lib64/python3.6/site-packages/matplotlib/contour.py in <module>()
     20 import matplotlib.colors as colors
     21 import matplotlib.collections as mcoll
---> 22 import matplotlib.font_manager as font_manager
     23 import matplotlib.text as text
     24 import matplotlib.cbook as cbook

/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in <module>()
   1437             raise
   1438         except:
-> 1439             _rebuild()
   1440     else:
   1441         _rebuild()

/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in _rebuild()
   1416         global fontManager
   1417 
-> 1418         fontManager = FontManager()
   1419 
   1420         if _fmcache:

/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in __init__(self, size, weight)
   1070         self.afmfiles = findSystemFonts(paths, fontext='afm') + \
   1071             findSystemFonts(fontext='afm')
-> 1072         self.afmlist = createFontList(self.afmfiles, fontext='afm')
   1073         if len(self.afmfiles):
   1074             self.defaultFont['afm'] = self.afmfiles[0]

/usr/lib64/python3.6/site-packages/matplotlib/font_manager.py in createFontList(fontfiles, fontext)
    581             try:
    582                 try:
--> 583                     font = afm.AFM(fh)
    584                 finally:
    585                     fh.close()

/usr/lib64/python3.6/site-packages/matplotlib/afm.py in __init__(self, fh)
    347         """
    348         (dhead, dcmetrics_ascii, dcmetrics_name, dkernpairs, dcomposite) = \
--> 349             parse_afm(fh)
    350         self._header = dhead
    351         self._kern = dkernpairs

/usr/lib64/python3.6/site-packages/matplotlib/afm.py in parse_afm(fh)
    335     _sanity_check(fh)
    336     dhead = _parse_header(fh)
--> 337     dcmetrics_ascii, dcmetrics_name = _parse_char_metrics(fh)
    338     doptional = _parse_optional(fh)
    339     return dhead, dcmetrics_ascii, dcmetrics_name, doptional[0], doptional[1]

/usr/lib64/python3.6/site-packages/matplotlib/afm.py in _parse_char_metrics(fh)
    196         if not line:
    197             break
--> 198         line = line.rstrip().decode('ascii')  # Convert from byte-literal
    199         if line.startswith('EndCharMetrics'):
    200             return ascii_d, name_d

UnicodeDecodeError: 'ascii' codec can't decode byte 0x8e in position 20: ordinal not in range(128)
```

**Expected outcome**

using `%matplotlib` magic in `jupyter notebook` also produces the same error. 

**Matplotlib version**

  * Operating System: Fedora 26, 64bit
  * Matplotlib Version: 2.0.0-2
  * Python Version: 2.7 / 3.6
  * Jupyter Version (if applicable): 4.1.0
  * Other Libraries:

### PR DESCRIPTION
**Pull request by tacaswell**
closes #9196

This fixes a (long standing) 'can not import' bug.

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is PEP 8 compliant

### CODE REVIEW

**Comment by anntzer** [comment]
Actually, can someone point to an actual example of a file that fails? http://www.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5004.AFM_Spec.pdf suggests that everything should be ASCII compatible (page 10).  I'm just curious whether it's some afm file that doesn't follow the spec, or if I'm misreading the spec...

**Comment by tacaswell** [comment]
The OP in #9196 has such a font.  From digging into this for the headers it tends to be comments and names that are non-ascii.  Not sure what could be in the metrics that would be non-ascii though...

**Comment by tacaswell** [comment]
It may also be the comment lines which are not explicitly constrained to ascii.

**Comment by anntzer** [comment]
Would
```
diff --git a/lib/matplotlib/afm.py b/lib/matplotlib/afm.py
index 30d335879..3a06c4618 100644
--- a/lib/matplotlib/afm.py
+++ b/lib/matplotlib/afm.py
@@ -189,23 +189,22 @@ def _parse_char_metrics(fh):
     ascii_d = {}
     name_d = {}
     for line in fh:
-        line = line.rstrip().decode('ascii')  # Convert from byte-literal
-        if line.startswith('EndCharMetrics'):
+        line = line.rstrip()
+        if line.startswith(b'EndCharMetrics'):
             return ascii_d, name_d
         # Split the metric line into a dictionary, keyed by metric identifiers
-        vals = dict(s.strip().split(' ', 1) for s in line.split(';') if s)
+        vals = dict(s.strip().split(b' ', 1) for s in line.split(b';') if s)
         # There may be other metrics present, but only these are needed
-        if not {'C', 'WX', 'N', 'B'}.issubset(vals):
+        if not {b'C', b'WX', b'N', b'B'}.issubset(vals):
             raise RuntimeError('Bad char metrics line: %s' % line)
-        num = _to_int(vals['C'])
-        wx = _to_float(vals['WX'])
-        name = vals['N']
-        bbox = _to_list_of_floats(vals['B'])
-        bbox = list(map(int, bbox))
+        num = _to_int(vals[b'C'])
+        wx = _to_float(vals[b'WX'])
+        name = vals[b'N'].decode('ascii')
+        bbox = _to_list_of_ints(vals[b'B'])
         # Workaround: If the character name is 'Euro', give it the
         # corresponding character code, according to WinAnsiEncoding (see PDF
         # Reference).
-        if name == 'Euro':
+        if name == b'Euro':
             num = 128
         if num != -1:
             ascii_d[num] = (wx, name, bbox)
```
(i.e. use bytes throughout, just decode at the very end) not be better?

**Comment by tacaswell** [comment]
Until we know what the offending font looks like, I am inclined to be more defensive.

In either case, we should not fail to import on a non-compliant font.

**Comment by anntzer** [comment]
Please add a comment to the code explaining why we are seemingly not following the spec, then.  Otherwise lgtm.

**Comment by tacaswell** [comment]
@anntzer done and force-pushed

**Comment by tacaswell** [comment]
Self-merging this as it has 2 approvals.

**Pull request merged**
