### PR TITLE
Fixed typos using codespell. (previous pull request was told not to change the agg files) 

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
Thanks for the PR - most of these look great, but we don't want to edit any of the files in the `extern/` directory - could you undo those changes?

**Comment by MalikIdreesHasanKhan** [comment]
Sure! Will do.

**Comment by MalikIdreesHasanKhan** [comment]
I have done it. Please review it and tell me if anything  remains to be undone.

**Review by tacaswell — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Comment by timhoffm** [comment]
Thanks @MalikIdreesHasanKhan!

**Comment by MalikIdreesHasanKhan** [comment]
My pleasure, @timhoffm !

**Pull request merged**
