### PR TITLE
Fix scaling of RadioButtons

### PR DESCRIPTION
**Pull request by Abdul-Miraj**
## PR Summary

This fix scales the radio buttons correctly with the size of the legend by taking the height that is already calculated for each section of the legend, which is defined by the variable dy (line 984).  I took the dy value and converted appropriately into a radius (by dividing the value by 2) and subtracting a very small unit to allow for some spacing for in between the buttons. I made it default back into the previously hard-coded value of 0.05 if the value of the radius is any bigger so in the case where there isn't many radio buttons, they wouldn't be huge. Previously the value of the RadioButtons were set to 0.05 thus when the space given for each radio button was less then the 0.05 unit the buttons would overlap onto eachother.

Note: The tests seem to be failing at the image comparison tests for the radio button. Not entirely sure why, the test pass locally on my own machine. Any insight would be helpful, thank you.

before

after

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is PEP 8 compliant

### CODE REVIEW

**Comment by afvincent** [comment]
Hum, about the failing image test comparison, I would suspect a Freetype issue as it is quite usual. See for example this [section](https://matplotlib.org/devel/contributing.html#building-matplotlib-for-image-comparison-tests) in the documentation.

On top of that you could try to add `remove_text=True` to the image comparison decorator, to at least partly mitigate the issue with most of the fonts (the texts in the widgets are likely to stay visible, but the labels, tick labels and titles shoud be hidden IIRC). Being there, you could also add `style='mpl20'` to be more future-proof.

**Comment by Abdul-Miraj** [comment]
I original thought I was using the correct Freetype, as I set my setup.cfg correctly but realized it wasn't actually using the version mlp wanted. I had to delete my build folder and recompile the project for it to use the correct version [#6911](https://github.com/matplotlib/matplotlib/issues/6911/). 

I've been attempting to fix the travis CLI error but am having a hard time diagnosing it. We've setup Travis CLI on our local forked repo and I've been trying to get the test to pass on Travis but am stuck. I've ran python 3.6 (thats what seems to be failing) on my local machine and those test pass. I'll be continuing to get the test to work but any pointers to the right direction will be greatly appreciated! Thank you.

**Comment by br-Zhang** [comment]
Based on the logs, it looks like CI is failing due to a PEP8 issue because of trailing whitespaces on line 93 of test_widgets.py.

**Comment by Abdul-Miraj** [comment]
Oh.. I completely missed that. Thank you @br-Zhang

**Pull request merged**
