### PR TITLE
Fix STIX virtual font entry for M script character

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by WeatherGod** [comment]
oooh, that is a nasty one. Good catch. +1 from me.

**Comment by QuLogic** [comment]
Why did the A change too?

**Comment by WeatherGod** [comment]
Indeed, the A gets changed up in a couple of the test images. I should have been more careful looking this over. Thanks for noticing that, @QuLogic!

**Comment by mdboom** [comment]
Ok -- something weird going on there.  I'll look into it.

**Comment by mdboom** [comment]
I had broken something on a branch based off of this one.  This branch alone doesn't actually break the A.  The images are fixed now.

**Comment by WeatherGod** [comment]
backported to 1.5.x as 99fe9a2f7

**Pull request merged**
