### PR TITLE
Issue #4271: reversed method added to Colormap objects.

### PR DESCRIPTION
**Pull request by kjartankg**
- method added to all Colormap classes
    - a test added in test_colors

A few things that I ran into while implementing this:

* Functions to reverse Colormap data already existed in [matplotlib.cm](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cm.py) but they are inconvenient for a user. After seeing that I changed my implementation to resemble them more. Perhaps the old functions should eventually be deprecated?
* The documentation for [LinearSegmentedColormap](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L669) does not mention that input data can be functions. It is mentioned briefly in the doc for [makeMappingArray](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L429) but should probably be mentioned in the doc for LinearSegmentedColormap.
* The data is specified as "list of tuples" [LinearSegmentedColormap](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L669) and [ListedColormap](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colors.py#L788) "a list of matplotlib color specifications, or an equivalent Nx3 or Nx4 floating point array (*N* rgb or rgba values)". I would suggest that this would be changed to *array_like* and that the data is then copied into a numpy array for internal use.

figure_1
figure_2
figure_3
figure_4
figure_5
figure_6

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @efiring

**Comment by kjartankg** [comment]
As I made the rookie mistake of working on the master branch and now there's a conflict, I need to close this PR and make a new one.

**Comment by tacaswell** [comment]
For future reference you can just force-push to this branch and the PR will update it's self.

**Comment by kjartankg** [comment]
@tacaswell , you mean then keep working on the master branch? I considered that but didn't really dare to. Guess I should have asked first..

Also since I have no clue how long this PR was going to take I kinda wanted to free up my master branch.

Sorry for the mess I'm making.

**Comment by tacaswell** [comment]
Ah, sorry I missed that this PR was from your master, carry on :sheep:

**Pull request closed without merging**
