### PR TITLE
Use a standard white background for GTK backends.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

See explanation in #19410, but using non-deprecated API.

## PR Checklist

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by anntzer** [comment]
I guess that makes it impossible for people to override that?  Previously they could e.g. inherit `FigureCanvasGTK3Agg` and after `super().__init__()` they could override the background to whatever they wanted.  (This is similar to the situation on Qt, where the background color is just set once at the end of `__init__`.)

Not sure whether it matters in practice, tbh.

**Comment by QuLogic** [comment]
Hmm, that's a good point; does that work on other backends properly?

**Comment by anntzer** [comment]
Hmm... actually
```python
from PyQt5.QtWidgets import *
from matplotlib import pyplot as plt

plt.figure(facecolor=(1, 0, 0, .5))
QApplication.instance().setStyleSheet(
    "QWidget {background-image: url('path/to/image.png')}")
plt.show()
```
also has the figure completely overriding the background image, for reasons not totally clear to me.  I have the vague memory of this being mentioned once somewhere, but can't find it right now.

**Comment by anntzer** [comment]
#19410 has been changed to use non-deprecated APIs.

**Comment by QuLogic** [comment]
OK, that looks good.

**Pull request closed without merging**
