### PR TITLE
CI: prefer (older) binaries over (newer) sdists

### PR DESCRIPTION
**Pull request by tacaswell**
## PR Summary
Try to fix installing test deps on windows + mac

### CODE REVIEW

**Comment by tacaswell** [comment]
I started out planning to pin pikepdf back, but thought to try `--prefer-binary` before sorting out how to do platfrom specific pinning.

**Comment by tacaswell** [comment]
It looks like it is working, I intend to self-merge if this is green.

**Comment by tacaswell** [comment]
The appveyor failure is an upload not test failure.

**Comment by tacaswell** [comment]
Well, I made the merge rules also apply to admins so I can not.

**Comment by QuLogic** [comment]
This file is in the documentation (through `dev/dev-requirements.txt`); do we want to force this preference on developers? Or just apply it to CI?

**Comment by tacaswell** [comment]
I am OK with having this applied for developers too (we are so loose about pinning anyway I think soft-pinning back is OK).

There is motion to make this the default behavior in pip as well.

**Review by QuLogic — APPROVED** [review]

**Review by oscargus — APPROVED** [review]

**Comment by oscargus** [comment]
How would this relate to `environment.yml`?

**Comment by QuLogic** [comment]
It looks like there's a conda-forge feedstock for it: https://github.com/conda-forge/pikepdf-feedstock So we should move to that and then it would definitely be a binary.

**Comment by QuLogic** [comment]
Oops, I should have checked the history first; we used to use it, but switched to `pip` because there were no Windows conda-forge packages, and it seems like there still aren't.

**Comment by oscargus** [comment]
Could one add this switch to the pip-section there? (I could try off course...)

**Pull request merged**
