### PR TITLE
Fix GH14900: numpy 1.17.0 breaks test_colors.

### LINKED ISSUE #14900: Numpy 1.17.0 breaks test_colors
It seems that Numpy 1.17.0 produces a `IndexError: invalid index to scalar variable.` in `test_colors.py` ([testing failure trace log]):

`FAILED lib/matplotlib/tests/test_colors.py::test_light_source_masked_shading`

[testing failure trace log]: https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=5172&view=ms.vss-test-web.build-test-results-tab&runId=1018210&resultId=101153&paneView=debug

```python
def test_light_source_masked_shading():
        """Array comparison test for a surface with a masked portion. Ensures that
        we don't wind up with "fringes" of odd colors around masked regions."""
        y, x = np.mgrid[-1.2:1.2:8j, -1.2:1.2:8j]
        z = 10 * np.cos(x**2 + y**2)
    
        z = np.ma.masked_greater(z, 9.9)
    
        cmap = plt.cm.copper
        ls = mcolors.LightSource(315, 45)
>       rgb = ls.shade(z, cmap)
```

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-96ee2a102cfd> in <module>
      1 cmap = plt.cm.copper
      2 ls = mcolors.LightSource(315, 45)
----> 3 rgb = ls.shade(z, cmap)

~/visualization/matplotlib/lib/matplotlib/colors.py in shade(self, data, cmap, norm, blend_mode, vmin, vmax, vert_exag, dx, dy, fraction, **kwargs)
   1800         rgb1 = self.shade_rgb(rgb0, elevation=data, blend_mode=blend_mode,
   1801                               vert_exag=vert_exag, dx=dx, dy=dy,
-> 1802                               fraction=fraction, **kwargs)
   1803         # Don't overwrite the alpha channel, if present.
   1804         rgb0[..., :3] = rgb1[..., :3]

~/visualization/matplotlib/lib/matplotlib/colors.py in shade_rgb(self, rgb, elevation, fraction, blend_mode, vert_exag, dx, dy, **kwargs)
   1871         # Only apply result where hillshade intensity isn't masked
   1872         if hasattr(intensity, 'mask'):
-> 1873             mask = intensity.mask[..., 0]
   1874             for i in range(3):
   1875                 blend[..., i][mask] = rgb[..., i][mask]

IndexError: invalid index to scalar variable.
```

### PR DESCRIPTION
**Pull request by bingyao**
## PR Summary

Try to fix #14900 

### Part I

In the original file(`colors.py`), the following lines should be (functionally) equivalent:

```python
>>> # A: using assignment and output arguments AT THE SAME TIME
>>> intensity = np.clip(intensity, 0, 1, intensity)
>>> # B: using output arguments
>>> np.clip(intensity, 0, 1, out=intensity)
>>> # C: WITHOUT using output arguments
>>> intensity = np.clip(intensity, 0, 1)
``` 
Although I know the `ufunc`'s output argument can save memory, but I don't quite understand why the original file used A instead of B? (whether was a misusage or there is some advantage?)

### Part II

Everything was fine until Numpy 1.17.0 where `np.clip` breaks the equivalence with `MaskedArray`:

```python
In [1]: import numpy as np                                                                                                                                                 

In [2]: np.__version__                                                                                                                                                     
Out[2]: '1.17.0'

In [3]: a = np.arange(10)                                                                                                                                                  

In [4]: m = np.ma.MaskedArray(a, mask=[0, 1] * 5)                                                                                                                          

In [5]: np.clip(m, 0, 5)                                                                                                                                                   
Out[5]: 
masked_array(data=[0, --, 2, --, 4, --, 5, --, 5, --],
             mask=[False,  True, False,  True, False,  True, False,  True,
                   False,  True],
       fill_value=999999)

In [6]: m                                                                                                                                                                  
Out[6]: 
masked_array(data=[0, --, 2, --, 4, --, 6, --, 8, --],
             mask=[False,  True, False,  True, False,  True, False,  True,
                   False,  True],
       fill_value=999999)

In [7]: np.clip(m, 0, 5, m)                                                                                                                                                
Out[7]: 
masked_array(data=[0, 1, 2, 3, 4, 5, 5, 5, 5, 5],
             mask=False,
       fill_value=999999)

In [8]: m                                                                                                                                                                  
Out[8]: 
masked_array(data=[0, 1, 2, 3, 4, 5, 5, 5, 5, 5],
             mask=False,
       fill_value=999999)
```

I also opened an issue in numpy's repo: https://github.com/numpy/numpy/issues/14140

### CODE REVIEW

**Comment by jklymak** [comment]
Looks good.  Were we ignoring an API change warning on this?

**Comment by jklymak** [comment]
Is there a reason codecov didn’t trigger for this PR?

**Comment by bingyao** [comment]
@jklymak Thanks for the reviewing! But I don't quite follow your two comments here: API change warning? and codecov didn't trigger? 😝What are they means?

**Comment by jklymak** [comment]
We have a codecoverage check called codecov that makes sure your change is actually tested.  

Numpy obviously changed their API.  If we weren’t getting deprecation notices they may have changed this inadvertently and it should be reported to them.

**Comment by tacaswell** [comment]
I'm going to merge this because it un-breaks the build.  

Thanks @bingyao for the fix and for reporting it upstream!

**Comment by eric-wieser** [comment]
The change in numpy was indeed an accident, and will hopefully restore the correct behavior in 1.17.1. I don't know if you want to do a version-check here for just the broken release, and keep the more memory-efficient out argument otherwise?

**Pull request merged**
