### PR TITLE
Pin mpl-sphinx-theme on the v3.7.x branch

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

A similar thing was done for the `v3.6.x` branch.

## PR Checklist

**Documentation and Tests**
- [n/a] Has pytest style unit tests (and `pytest` passes)
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] New plotting related features are documented with examples.

**Release Notes**
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [n/a] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
This should also go in the release guide updates?

**Comment by QuLogic** [comment]
Yes, probably; cc @ksunden

**Comment by ksunden** [comment]
Is there any reason not to pin this way on `main`? Its our own first party dependency that we control the release cycle of. While we currently version it for every release, it could in theory slow down that it doesn't need to be updated for each mpl release.

I feel like updating the pin is already a part of the theme release (we only updated it because we want to change/fix something, essentially), but changing it to `~=` from `>=` doesn't change that procedure, and we pretty much always want to pin it to the most recent version.

If it is pinned on main, then there is nothing special to do for release, and just the repinning to newer versions doesn't get backported.

**Comment by tacaswell** [comment]
fair point.  I am in general against hard pins, but this is in an internal requirements file we use for setting up CI + developers machines (not something carved into stone on pypi or a packaging system) so I guess that would be OK.

**Pull request merged**
