### PR TITLE
DOC: simplify sidebar

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

As pointed out in https://github.com/matplotlib/matplotlib/issues/21666 the sidebar is a bit of a mess in the new theme.  This keeps it the same for "Contributing" and "Reference", but makes it the same as user/index for the rest of the pages...

Probably could make a better navigation for the LHS but I kind fo doubt it would be a lot better than the RHS top-level nav.

Also closes https://github.com/matplotlib/matplotlib/issues/22395

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
I think this looks better than the current sidebar nav (LHS) for most of the pages at least until we figure out how to make better nav for SG and pages with multiple TOC: https://64894-1385122-gh.circle-artifacts.com/0/doc/build/html/index.html

**Comment by jklymak** [comment]
I'll still advocate for this PR, though I note the artifact is gone.  

We have a nice site on mobile now, except if I go to an example or API page, I have 500 things to scroll through before I get to the content.

**Comment by story645** [comment]
Pydata sphinx added some new features for sidebars in their latest release - the custom stacking seems like maybe could help here?
https://github.com/pydata/pydata-sphinx-theme/releases

**Comment by jklymak** [comment]
> Pydata sphinx added some new features for sidebars in their latest release - the custom stacking seems like maybe could help here?
> https://github.com/pydata/pydata-sphinx-theme/releases

Hmm, OK< I'll put this on draft while I look at that!  Thanks

**Comment by jklymak** [comment]
I'll put this as still the better solution.  Yes in pydata-sphinx-theme we can control the navigation better, but the fact remains that our navigation structure just doesn't work properly with pydata-sphinx-theme.  I _expect_ we could fix that, but in the meantime, I still think we should not present a _bad_ sidebar.

**Comment by jklymak** [comment]
I will still argue for this change.  The left hand navigation is really impossible on mobile...

**Comment by ianhi** [comment]
@jklymak ok to open and close to regenerate the docs artificat? It seems to have expired.

I'd be very pro merging an incremental improvement. I ended up back on the mobile page again today and it's essentially unusable.

**Comment by ianhi** [comment]
hmm that didn't seem to trigger a rebuild. still getting a "not found". maybe a dummy commit would do the trick?

**Comment by QuLogic** [comment]
CircleCI builds PR head, not merge, so open/close won't do anything. A rebase will work.

**Comment by jklymak** [comment]
ping @ianhi

**Comment by ianhi** [comment]
oops missed that - thanks for the ping!

Definitely slightly worse on desktop but I'd say the improvement on mobile more than makes up for it.


Maybe a slicker fix would be to have that sidebar auto collapsed when on mobile? As it is I guess you've removed it, but it's still present as the Cheatsheets link ends up at the top. Which is a bit awkward, ideally you'd see the top of the example as soon as you open the page. 


image



I'm not sure this totally closes the linked issues as there could still be some productive iterations on top of this, but I do think it's a big improvement over the current state so :+1: from me

**Comment by jklymak** [comment]
I don't know that we can collapse the sidebar (probably, but that is probably an upstream issue with pydata-sphinx-theme).  However, we could remove the cheatsheet...

**Comment by timhoffm** [comment]
### General comment

AFAICS the situation is as follows:

- The right sidebar is quite ok: "On this page". It's the page-local table of contents and left out if the page does not have subsections.
- The left sidebar seems to show the hierarchy of titles of all pages. But from the top level, only one level down, e.g. starting at `api/index.html`, `reference/index.html` etc. But not quite, `users/index.html` does not have left sidebar content. Then again `users/explanation/index.html` starts a new hierarchy.

One part of the left sidebar problem may be that our page structure is a bit convoluted.

### Specific comment

 I'm ok removing the leftbar content as a stopgap solution. Long-term I'd like to see a better overall structure navigation. (to be checked: how do other projects using the pydata-sphinx-theme cope with this?)

One suggestion: Don't put the cheatsheet and "support matplotlib" on every page. I have the feeling that they are out of context there and should only appear on the top index page.

**Comment by jklymak** [comment]
Yes, agree with all the above.  There is something strange about how we layout our docs where the left sidebar is not useful.  

The responsiveness of the left sidebar to smaller screens is something I think pydata-theme should take up.  I'll open an issue there.  

I'll remove the cheatsheet and donate button.

**Comment by jklymak** [comment]
This version works.  Pretty silly to have a huge sidebar that most of our pages don't use, but at least its not spammed with nonsense.  If there is something else we should have in here, I think we should add it...

**Comment by timhoffm** [comment]
The following pages have decent enough context in the left sidebar. If you want to fine-tune, you could still use the standard content for them:

https://matplotlib.org/stable/users/explain/index.html
https://matplotlib.org/stable/users/faq/index.html
https://matplotlib.org/stable/devel/index.html
https://matplotlib.org/stable/users/project/index.html

**Comment by oscargus** [comment]
I sort of see the point of not having the huge list of items to the left, especially on mobile, but I'm also realizing that I miss it a bit now that it is not there. I can probably live with that though, but what about disabling that on mobile rather than putting it at the top?

What I cannot live with is the lack of search (except for the first page). I really think that should be somewhere. Either a (looking glass?) link in the top bar to the search page or, even better, some sort of way to reintroduce the search bar somewhere.

**Comment by oscargus** [comment]
An interesting side-effect here is that the plot types page show five plots on the same line for a certain browser width, but for wider browsers goes back to four. I guess it is just a question of fine-tuning some parameter though (or maybe not go back to four?).

**Comment by jklymak** [comment]
I'll close in favour of a more holistic solution.

**Pull request closed without merging**
