### PR TITLE
Cleanup colors.py docstrings.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
```
/home/circleci/project/lib/matplotlib/colors.py:docstring of matplotlib.colors.BoundaryNorm:44: WARNING: py:obj reference target not found: Colormap.__call__
```

**Comment by tacaswell** [comment]
The 3.8 doc build now fails due to not pulling the pytest object inventory, but this change adds several extra `__foo__` entries, my attempts to re-exclude them locally are not going great....

**Comment by anntzer** [comment]
We could just re-exclude `__call__` for now, or regen missing-references.json.

**Comment by efiring** [comment]
I think the docs failure is a transient:
```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://pytest.org/en/stable/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 502 Server Error: Bad Gateway for url: https://pytest.org/en/stable/objects.i
nv
```
If so, this can be merged.

**Comment by anntzer** [comment]
at least it looks so to me.

**Pull request merged**
