### PR TITLE
Avoid using `axis([xlo, xhi, ylo, yhi])` in examples.

### PR DESCRIPTION
**Pull request by anntzer**
In my view, `axis()` does too much: it can manipulate axis limits, axes
aspect ratio, lines and label visibility, etc.

This PR replaces in the examples `axis([xlo, xhi, ylo, yhi])` by
`set(xlim=(xlo, xhi), ylim=(ylo, yhi))` (or
`plt.xlim(xlo, xhi); plt.ylim(xlo, yhi)` for pyplot examples), which is
easier to intuit IMO.

There are also cases where I just remove the call to axis() when it
doesn't add much to the example.

Special cases:

- anscombe can be greatly shortened by using shared axes.  Note that
  the "old" xlims (2, 20) were immediately overwritten by xticks=(0, 10,
  20) which expanded the xlims to (0, 20)...
- fonts_demo/fonts_demo_kw are better showcased using figtext() anyways.
- In pcolor_demo, the call to axis() is unneeded (pcolor/pcolormesh
  correctly set the artist sticky edges to have the right bounds).
- In pyplot_formatstr (which could probably be deleted...), the call
  to axis() does not showcase anything.
- In slider_demo, margins(x=0) is semantically more correct.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
I wouldn't bother for this PR, whose point is only to make the example a bit more readable (to my taste at least).

**Comment by timhoffm** [comment]
Doesn't necessarily have to be within this PR. I was just wondering, if we don't want to use this pattern in the examples, maybe we should tell users that it's not the preferred way to do it.

**Comment by anntzer** [comment]
I added the alternate form in the docstring of `axis()`, but without indicating a preference for one form or the other.

**Comment by timhoffm** [comment]
I think this is ready to be merged. Not sure if this is only failing due to the pytest 4.5 issue. @anntzer can you please rebase?

**Comment by anntzer** [comment]
rebased

**Comment by timhoffm** [comment]
Thanks.

**Pull request merged**
