### PR TITLE
MNT: Remove redundant f-strings

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

No need for an f-string if no formatting is done.

As I stumbled upon a line that was mentioned in https://github.com/matplotlib/matplotlib/issues/21959 I also fixed that.

Closes #21968 (except that there is no test for it here).

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by anntzer** [comment]
FWIW I prefer keeping the leading f's when some part of the implicitly concatenated string uses formatting (and will intentionally add them), to make the string prefixes aligned...

**Comment by tacaswell** [comment]
I have mixed feelings.  On one hand I agree with @anntzer that keeping the prefixes lined up in helps keep the code readable.  On the other hand I have had a linter catch "I meant to make this an f-string but forget the f" on a couple of occasions.

A suggestion that I think everyone will be against, we could use an explicit `u` on non-f-string strings in these stacks (it is legal https://docs.python.org/3.10/reference/lexical_analysis.html#string-and-bytes-literals) aligned and the linters happy.

**Comment by anntzer** [comment]
I would rather fix the linters to allow (perhaps as an option) the "there's an f just to align with another f in the implicitly concatenated string".

**Comment by timhoffm** [comment]
I tend to agree with @anntzer.

This is a very general styling topic. Are we aware of any recommendations/best practice of other libraries?

**Comment by jklymak** [comment]
I'll close, but feel free to reopen if we think this is really needed.

**Pull request closed without merging**
