### PR TITLE
refresh the github stats

### PR DESCRIPTION
**Pull request by ivanov**
Learning to release sitting next to @tacaswell

### CODE REVIEW

**Comment by ivanov** [comment]
doc builds failed because one of the PRs titles had `**kwargs` which ended up an opening for strong/bold text without a matching close thing. I pushed a commit to fix that.

**Comment by ivanov** [comment]
Also, I added a commit just to iterate here, but it probably makes sense to squash it once we're happy with it.

**Comment by NelleV** [comment]
:champagne:

**Comment by choldgraf** [comment]
so refreshed

**Comment by tacaswell** [comment]
Thanks @ivanov !

**Pull request merged**
