### PR TITLE
Interactive setting of savefig rcParams (Qt only).

### LINKED ISSUE #7352: expose savefig.transparent / savefig.dpi in the UI
It would be nice if, after interactively selecting a filename where the figure will be saved, a second dialog popped up to let the user pick figure transparency, DPI, JPEG quailty if applicable, etc. (basically whatever kwargs `fig.savefig` takes).

Labeling this as QUI/Qt because the presence of formlayout should make this relatively easy to implement in this backend, but possibly nice to have in other backends too.  (By the way perhaps we should just have a general "GUI" label?)

### PR DESCRIPTION
**Pull request by anntzer**
An additional window pops after selecting the filename to allow setting
of savefig-related rcParams.

For simplicity and consistency, the "ps.usedistiller" rcParam is now
normalized to `None` when not set.

Closes #7352.

### CODE REVIEW

**Comment by tacaswell** [comment]
👍 in principle.  

Is there a way to work this into the UI other than another modal dialog box?  How much can we hack on the filepicker?

**Comment by WeatherGod** [comment]
would this second window always pop up? I would find that incredibly
annoying. I would rather have something that would show up with the
file-chooser dialog as advance settings or something.

**Comment by anntzer** [comment]
A quick googling suggests that it is possible to embed a QFileDialog within, say, a QHBoxLayout so that one has a standard filepicker on the left and the options panel on the right.  It would require quite a bit more effort to implement though.

Right now the second window always pops up but you can just <enter> through it, and it is not different from the behavior of, say, Inkscape when saving to a format where options are available, and it's not *that* intrusive either.

**Comment by anntzer** [comment]
Upon further searching, I now believe that it is not possible to embed a Qt file dialog into a larger widget, *unless* we choose to not use the native file dialog (see difference at https://kb.froglogic.com/display/KB/Automating+native+or+Qt+%28file%29+dialogs+in+Qt+applications#AutomatingnativeorQt%28file%29dialogsinQtapplications-DialogsinQtapplications).  (The reason being that a native file dialog can be anything and Qt cannot know how to embed it.)

In my opinion, using the native dialog is much preferrable from a UI POV, so I'd rather keep this PR as it is (except for a rebase).

**Comment by anntzer** [comment]
I put together an alternative implementation, which uses an additional menu for setting the options.  The toolbutton menu is easy enough to discover (so that the feature actually gets used...) without being as conspicuous as an additional tool button.  Not sure how this would interact with MEP22 though.

screenshot_20170604_143843
screenshot_20170604_143913

**Comment by fariza** [comment]
Maybe too late for this, but why don't use a canvas and the widgets that we have, this way, we can reuse for other backends

**Comment by anntzer** [comment]
I think a native window is just *much* nicer.  See also #8683.

**Comment by fariza** [comment]
Yes I agree that native widgets are much nicer.
The problem is: **this just makes backend maintenance a lot harder.**
This is the main point of MEP22 and MEP27

**Comment by dopplershift** [comment]
I'm not a fan of adding more Qt-only features, unless we decide that's really the direction the project wants to go in.

**Comment by jklymak** [comment]
@anntzer I'll close this as not likely to move forward, but feel free to reopen if you want to re-pursue

**Pull request closed without merging**
