### PR TITLE
Enhancement of tick label offset text positioning

### PR DESCRIPTION
**Pull request by cimarronm**
Enables missing functionality to properly locate the offset text for the xaxis when either located at the top or bottom of the plot.

It uses an unused attribute `offset_text_position` that looks like it was incorporated with this in mind but the functionality never was added.

### CODE REVIEW

**Comment by cimarronm** [comment]
An attempt at incorporating the missing functionality reported in #5238 

## Example in #5238 

#### before
image

#### after
image

**Comment by cimarronm** [comment]
Need to fix up the failing test and look at a possible test for xaxis. Will do that tomorrow

**Comment by mdboom** [comment]
:+1:

**Comment by cimarronm** [comment]
probably should add something to `whats_new` before this goes in

**Comment by jklymak** [comment]
This is still a bug in master. @cimarronm any chance you have time to rebase and resurect this?

**Comment by QuLogic** [comment]
This appears to be done by #15592.

**Pull request closed without merging**
