### PR TITLE
Fix crash if byte-compiled level 2

### PR DESCRIPTION
**Pull request by JGoutin**
Fix crash if byte-compiled level 2 (Python -OO command line argument)

### CODE REVIEW

**Comment by tacaswell** [comment]
Is this really the only place that breaks?  We have some pretty extensive docstring substitution/rewriting code.

**Comment by JGoutin** [comment]
After fixing this, I get no crash on importing Matplotlib. But, I don't use all Matplotlib possibilities in my software and don't import everything.

The bug come only when `__doc__` ( = `None` if byte compiled level 2) is used like with a `str` function or operator.

**Comment by jenshnielsen** [comment]
I guess if we want to ensure that this works one of the jobs on travis should run the tests with -OO ?

**Comment by tacaswell** [comment]
Indeed, I nominate the 3.4 run (2.7 has the old deps, 3.5 has pandas, and the nightly is an optional fail).

**Comment by JGoutin** [comment]
Tried to update `.travis.yml` to include test with `-OO`.

**Comment by tacaswell** [comment]
This seems to need a rebase?

**Comment by JGoutin** [comment]
Go to #6729

**Pull request closed without merging**
