### PR TITLE
Use HiDPI icons for PyQt5

### PR DESCRIPTION
**Pull request by astrofrog**
This partially addresses https://github.com/matplotlib/matplotlib/issues/4978, by adding and using HiDPI PNG icons for the PyQt5 framework.

**Before:**

mb_before

**After:**

mb_after

Note that I had to adjust the toolbar height and spacing because otherwise it ended up more condensed than before for some reason.

**Note:** I'm not aware of a reliable way to determine the DPI of a display so at the moment this always uses the HiDPI icons when using PyQt5. It would be great if someone could check that this still looks fine (and no worse than before)

### CODE REVIEW

**Comment by astrofrog** [comment]
I've found a way to figure out whether we need to use the HiDPI icons (i.e. what the screen resolution is). I'll work on it later this week.

**Comment by tacaswell** [comment]
It looks like qt understands svg, could we use those instead of hi-res pngs? 

http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats

**Comment by astrofrog** [comment]
@tacaswell - ah, certainly! I had not realized that. I will work on that in a few days.

**Comment by astrofrog** [comment]
@tacaswell - although it looks like this was actually changed *to* PNG in the past for Qt4:

https://github.com/matplotlib/matplotlib/commit/c61df400d96d3e7b86fd6855e265f1ef25286001

https://github.com/matplotlib/matplotlib/pull/143

http://sourceforge.net/p/matplotlib/mailman/matplotlib-users/thread/4D4EA423.5090802@vanderHoeven.biz/

Sounds like this caused some issues on Windows? This was 4 years ago though, so maybe things have changed?

**Comment by tacaswell** [comment]
attn @jbmohler @mfitzp Do either of you have experience with py2exe + qt ?

**Comment by astrofrog** [comment]
@tacaswell - how do you think we should proceed on this? Is there anyone else who might be able to advise on what to do here re: PNG vs SVG?

**Comment by tacaswell** [comment]
I am not sure, `py2exe` seems to be a persistent thorn in our side in general and I have no windows experience.

I know @jrevans has recently done a lot of work porting a Qt app over to Qt5, he might have some insight here (not sure what platform they run on).

**Comment by mfitzp** [comment]
@tacaswell I've not used py2exe before. But from the mailing list link it looks like the change to PNG was more due to a packaging issue (i.e. py2exe wasn't bundling the required xml handler). I have a Windows machine available I can test this on. On Qt5 Svg I think rendering is handled by a separate Qt.Svg module so I suspect there will be the same problem, but with a different fix.

Making this work may just be a case of including the Svg/other import in our `qt_compat.py`. The linked post says that this didn't work, but that may be a case of where to do the import + what exactly to import.

**Comment by fariza** [comment]
We are adding more files to  `lib/matplotlib/mpl-data/images/` without any organization or control.

I really don't like the hand adding of icons of different sizes and hand naming is even worst.

Why don't we use a script to convert the source `svg` to different sizes automatically at build, generating different `40x40_, 60x60_... 1280x1280_` or `small_, medium_... xxlarge_`?
 
With an automatic icon creation, we are sure the size that we are requesting in the format that we are requesting will be there.

**Comment by mdboom** [comment]
> With an automatic icon creation, we are sure the size that we are requesting in the format that we are requesting will be there.

Just FYI: I'm working on this.

**Comment by astrofrog** [comment]
I think this is now fixed in master?

**Comment by jenshnielsen** [comment]
Confirming that Qt5Agg and the OSX backend have HiDPI icons on HiDPI screens Thanks @astrofrog

**Pull request closed without merging**
