### PR TITLE
TST: Update test images for new Ghostscript.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

These are created using 9.24; just trying to see if that's what will fix it. @jklymak says Travis is now on 9.25. If this works, we should probably add some tolerances for old versions.

## PR Checklist

- [x] Has Pytest style unit tests
- [N/A] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
OK, even though I replaced the image, `test_boxplot[pdf]` is still failing. It also fails locally too.

I also don't understand why `hatch_simplify` seems to have gotten thicker lines but this never failed before.

**Comment by QuLogic** [comment]
So `hatch_simplify.pdf` hasn't been changed since 2015, but in fact it should have changed with #6198 which unified the width of hatch lines across formats. Due to buggy Ghostscript I guess, this was never done.

**Comment by QuLogic** [comment]
Possibly. Can someone who has an older ghostscript try it out to see if we need any higher tolerances for them?

**Comment by QuLogic** [comment]
In the interest of getting CI working, I'm going to merge this. If anyone has any problems, please open a PR with increased tolerance.

**Comment by timhoffm** [comment]
FYI: This works with ghostscript 9.19.

**Comment by QuLogic** [comment]
Ah, good to know.

**Comment by QuLogic** [comment]
@meeseeksdev backport to v2.2.x

**Pull request merged**
