### PR TITLE
Add Py.test testing framework support

### PR DESCRIPTION
**Pull request by Kojoley**
This PR is part of preparation for migration to `pytest`

### CODE REVIEW

**Comment by Kojoley** [comment]
Missed several other places, will update PR soon.

**Comment by story645** [comment]
Is this a continuation of #5325?

**Comment by tacaswell** [comment]
Also, please be aware of https://github.com/matplotlib/pytest-mpl

**Comment by Kojoley** [comment]
Pytest 3.0 released with this change:
> `yield`-based tests are considered deprecated and will be removed in pytest-4.0.

:confused:

**Comment by Kojoley** [comment]
Coverage problem is because of `if [[ $NOSE_ARGS="--with-coverage" ]]; then` in `.travis.yml`. The expression should be either `[ a=b ]` or `[[ a==b ]]`.

**Comment by Kojoley** [comment]
PR is now ready for review and merge.

Key notes:
  - Collection phase is long due to `image_comparison` decorator
    (pytest runs `setup_class` during it)
  - `matplotlib.test` is not aware of pytest yet
  - `pytest-xdist` is disabled due to #6899
  - `--collect-filter` is `blacklist` by default (https://github.com/matplotlib/matplotlib/issues/6902#issuecomment-238075375)
  - `--no-pep8` is implemented, but `--pep8` is not

**Comment by tacaswell** [comment]
It looks like pytest is finding 5 more tests than nose so that is probably a victory.

It looks like pep8 is being run by pytest on travis, but not on appveyor, but that is ok for now.

There is a big CI hit time wise for this and we will have to (soon) pick some of the nose builds to drop.

**Comment by Kojoley** [comment]
> It looks like pep8 is being run by pytest on travis, but not on appveyor, but that is ok for now.

I made this intentionally because we have separated pep8 only build on travis so there is no need to run them on all appveyor builds. Or I was wrong?

**Comment by tacaswell** [comment]
If anything pep8 should be skipped by travis pytest build.  According to the handy output, it is only 45s which is not a big deal on top of our total runtime.

**Comment by jenshnielsen** [comment]
As far as I remember the main reason for splitting pep8 out in a separate build is not so much runtime but making it simpler to spot failures that are due to pep8 only

**Pull request merged**
