### PR TITLE
Fix crash if byte-compiled level 2

### PR DESCRIPTION
**Pull request by JGoutin**
Follow #6719

### CODE REVIEW

**Comment by JGoutin** [comment]
The Travis test with `-OO` work as intended.

And, tests completed without error. There is no other crash like this.

**Comment by tacaswell** [comment]
:+1:  Thanks

**Comment by QuLogic** [comment]
You've only added `-OO` to the test run. Does the `-OO` actually apply to the matplotlib files that are already installed?

**Comment by tacaswell** [comment]
From reading the docs, it will regenerate the byte code if needed.

**Comment by tacaswell** [comment]
Sorry, clicked the wrong button.

**Pull request merged**
