### PR TITLE
Add tutorials to the Users Guide.  

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Adds tutorials to the user guide.  

Addresses #9349 issue of nothing in users guide any more.

*Note* the heading level for all the tutorial/*/Readme.txt was lowered.  

ping @choldgraf 

###   [Users Guide](http://matplotlib.org/users/index.html) 
user s_guide_ _matplotlib_2_1_0rc1_post144_dev0_g5645f24e5_documentation

### [Docs overview](http://matplotlib.org/contents.html)

overview_ _matplotlib_2_1_0rc1_post144_dev0_g5645f24e5_documentation

## PR Checklist

- [x] Documentation is sphinx and numpydoc compliant

### CODE REVIEW

**Comment by choldgraf** [comment]
ah that's a nice solution! Can you clarify what the two images are? Are those two different pages in the docs?

**Comment by jklymak** [comment]
Upper image is the [Users Guide](http://matplotlib.org/users/index.html) and the lower image is the [docs overview](http://matplotlib.org/contents.html).  (links here are to current documentation)

**Comment by choldgraf** [comment]
gotcha - well I am +1 on this and would be in favor of backporting as well

**Comment by choldgraf** [comment]
@tacaswell maybe we can try out our meeseecks friend on this?

**Comment by tacaswell** [comment]
Yes, lets see if it works for other branches!

**Comment by tacaswell** [comment]
@meeseeksdev backport to v2.1.0-docs

**Comment by choldgraf** [comment]
@Carreau look we're using it!

**Comment by choldgraf** [comment]
@meeseeksdev say oooooohhhh eeeee!

**Comment by choldgraf** [comment]
@meeseeksdev backport to v2.1.0-doc

**Comment by choldgraf** [comment]
@meeseeksdev say ooooeeeee @tacaswell , you gave the wrong branch name!

**Comment by QuLogic** [comment]
@tacaswell speaking of wrong branch names, did @meeseeksdev not backport because the branch and milestone are not the same name?

**Comment by tacaswell** [comment]
No, it was just because I flubbed the typing, but I think I will change the milestone to match the branch name.

**Comment by QuLogic** [comment]
No, I meant automatically because the milestone was set before the PR was merged.

**Comment by tacaswell** [comment]
The automatic backport is controlled by the `on-merge: backport to v2.1.0-doc` line in the description of the milestone (which I added after this PR was merged) (see https://github.com/matplotlib/matplotlib/milestones )

I only know how this works because @Carreau was sitting next to me and pointed me to where I needed to edit for the v2.1.1 milestone.

**Comment by Carreau** [comment]
> I only know how this works because @Carreau was sitting next to me and pointed me to where I needed to edit for the v2.1.1 milestone.

Yeah, I implemented that about 48h before showing it to @tacaswell and need to document it. 
I also need to add better error handling when the branch name is wrong.

**Pull request merged**
