### PR TITLE
Run setupext qt checks in a subprocess rather than with multiprocessing.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

(yes, having code as strings is a bit ugly, but less that having multiprocessing in setup.py...)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you also remove the `multiprocess` import now?  

Bit surprised that you can import both pyqt and pyside in one process.

**Comment by anntzer** [comment]
#10885 needs to be merged too before removing multiprocessing (or I can rebase the later of the two PRs).
I think the impossibility of importing qt4 and qt5 in the same process is due to C symbol clash(?), so that's not a problem with pyqt and pyside(?).

**Comment by anntzer** [comment]
This will basically become obsolete once https://github.com/matplotlib/matplotlib/pull/11600 or a variant thereof gets merged (we won't be checking for the GUI toolkits during the build at all anymore).
I guess #11600 (or variant) should get in soon so I'll remilestone this away from 3.0 for now; I'll close this once #11600 goes in (it's not a problem either if this gets merged if #11600 ends up taking too long).

**Comment by anntzer** [comment]
Obsoleted by #11962.

**Pull request closed without merging**
