### PR TITLE
Fix #5777.  Don't warn when applying default style

### LINKED ISSUE #5777: Using default style raises warnings about non style parameters
For instance:
```python
import matplotlib
import matplotlib.pyplot as plt

matplotlib.style.use('default')
plt.plot(range(10))
plt.show()
```

raises

```
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'webagg.port_retries', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'datapath', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'figure.max_open_warning', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'timezone', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'backend.qt4', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'toolbar', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'savefig.directory', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'tk.window_focus', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'backend_fallback', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'webagg.open_in_browser', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'backend', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'interactive', that is not related to style.  Ignoring
  "style.  Ignoring".format(key))
/usr/local/lib/python3.5/site-packages/matplotlib/style/core.py:52: UserWarning: Style includes a parameter, 'webagg.port', that is not related to style.  Ignoring
```

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
The context manager is badly named it does not actually catch any warnings it just resets the warning filter when leaving the context.  I think you have to do:
```python
with warnings.catch_warnings(record=True):
    warnings.simplefilter("ignore", UserWarning)
    _apply_style(rcParamsDefault)
```

**Comment by jenshnielsen** [comment]
If I understand this correctly the `with warnings.catch_warnings(record=True)` means that the warning is only showed once but it is still showed exactly once

**Comment by mdboom** [comment]
> If I understand this correctly the with warnings.catch_warnings(record=True) means that the warning is only showed once but it is still showed exactly once

For me, at least, the warnings aren't shown at all, due to the `record=True`.  But on further consideration, a think a new kwarg is better -- it will be more efficient, as there's no need to generate the warning object in the first place, only to catch and suppress it elsewhere.  Updating this PR...

**Comment by jenshnielsen** [comment]
It's shown once in https://travis-ci.org/matplotlib/matplotlib/jobs/99718127 but that might be do to other reasons.

**Comment by mdboom** [comment]
Let's see if the latest commit here fixes that warning in the doc build.  If not, there's probably something else to track down.

**Comment by jenshnielsen** [comment]
There is still a single `/home/travis/build/matplotlib/matplotlib/lib/matplotlib/style/core.py:53: UserWarning: Style includes a parameter, 'backend', that is not related to style.  Ignoring` so that must presumably be triggered by some other code path.

**Pull request merged**
