### PR TITLE
Replace hardcoded parameter names when creating error bars

### PR DESCRIPTION
**Pull request by wqian94**
## PR Summary

Use `inspect.signature` to automagically check whether a `kwarg` is a
line argument, rather than relying on a hardcoded list. See issue #23375 

## PR Checklist

**Tests and Styling**
- [❌] Has pytest style unit tests (and `pytest` passes).
- [✔️] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [✔️] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by oscargus** [comment]
I think that although the idea of the PR is good, it is probably quite hard to get through as there is quite a bit of magic going on with the keyword handling, including aliases. However, it is no way intended to discourage you of doing this, it may be possible for some classes, but be prepared for that it can be quite a bit of hassle, closing in to impossible in some cases.

**Comment by timhoffm** [comment]
I'm hesitant whether the automatism of introspection is useful here. A subset of the parameters should be passed on. While I think this proposal would currently work correctly, it's not a-priori correct that we should not pass any Line2D parameters to the caps. e.g.

- `color` should indeed be passed on. The introspection filters it out, and it's only still working because we have special-handling code for that below, which re-introduces the parameter.
- Other properties like `alpha` should propagate as well. This works here only because `alpha` is handled in the Line2D signature via `**kwargs`. If we would make that explicit, propagation would become broken.

Therefore, it may well be that future code changes will break the mechanism. The effect is a change in the output (i.e. some properties are not propagated), but no error, which is hard to detect.
OTOH, hard-coding some non-supported parameters is defensive - only remove what you are sure is not working. This may not be complete, but if we pass too much, users will get an error like in #23375, which we can fix explicitly.

**Comment by wqian94** [comment]
Sorry, been away for the weekend.

I'm working on some changes, but it sounds like there isn't much appetite for this, so maybe I'll just keep it as part of a local build instead.

**Comment by timhoffm** [comment]
@wqian94 Yes, I think just adding `markerfacecoloralt` to the hardcoded list. Is the better approach here. Would you be willing to make a PR for that?

**Comment by wqian94** [comment]
Sure, I'll submit a separate PR.

**Comment by wqian94** [comment]
Replaced with PR #23475

**Pull request closed without merging**
