### PR TITLE
Refresh pgf baseline images.

### PR DESCRIPTION
**Pull request by jenshnielsen**
These have changed due to the 2.x work on ticks and changes of dpi but was not caught since travis does not run the pgf tests. I think the changes are ok and makes sense

### CODE REVIEW

**Comment by mdboom** [comment]
@pwuertz may want to double check these, but in principle it seems fine to me.

**Comment by jenshnielsen** [comment]
We probably want to hold this up until  #5724 is merged since that probably changes pgf_rcupdate2.pdf again

**Comment by jenshnielsen** [comment]
This should probably be backported to 2.x?

**Comment by tacaswell** [comment]
maybe waiting on #5772

**Comment by pwuertz** [comment]
Looks reasonable, and reminds me to check the test results from time to time. Some small details might be worth checking out (not related to this PR).

**Comment by jenshnielsen** [comment]
@pwuertz The tests should really be run on Travis. If I remember correctly the reason they are not is that the Travis images are based on Ubuntu 12.04 which ships a too old version of texlive (xetex). I tried switching to the new images in #5730 unfortunately that does not work with the Travis cache feature that we use.

**Comment by pwuertz** [comment]
Yea, the issue was that the setup for running the PGF tests was too heavy / uncommon so we decided to exclude them from the default set of tests. I guess this was even before we had a CI system / Travis. Could be possible to include the tests in such a controlled environment, but I don't know about the cache feature you mentioned.

**Comment by jenshnielsen** [comment]
The cache feature is not related to the pgf backend. It's there such that we don't have to build Numpy etc from scratch every time we run the tests. Unfortunatly it's not available on the Ubuntu 14.04 images.

**Comment by jenshnielsen** [comment]
I tried installing the pgf and zetex packages on this Travis node type unfortunately now a different test is failing

**Comment by jenshnielsen** [comment]
I have installed the dependencies on Travis and refreshed all images. Lets hope that is enough to get the tests to pass.

**Comment by jenshnielsen** [comment]
This still needs to be hold of until #5724 and #5772 is merged to avoid regenerating the images multiple times

**Comment by jenshnielsen** [comment]
From looking at the tests on a Ubuntu 12.04 image the main reason for the needed tolerance seems to be the fonts selected. The 2 pdflatex test are different do to a different font whereas the xelatex one mainly seems to be due to different kerneling which may or may not be due to the font.

**Comment by jenshnielsen** [comment]
Regenerated the images on top of the new master. Still need to fix the font selection. The links below show the changes since github still does not due rich diffs for pdfs

* [pgf_bbox_inches.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_bbox_inches.pdf) and [pgf_bbox_inches.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_bbox_inches.pdf)

* [pgf_mixedmode.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_mixedmode.pdf) and [pgf_mixedmode.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_mixedmode.pdf)

* [pgf_pdflatex.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_pdflatex.pdf) and [pgf_pdflatex.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_pdflatex.pdf)

* [pgf_rcupdate1.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_rcupdate1.pdf) and [pgf_rcupdate1.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_rcupdate1.pdf)


* [pgf_rcupdate2.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_rcupdate2.pdf) and [pgf_rcupdate2.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_rcupdate2.pdf)


* [pgf_xelatex.pdf 1.5.x](https://github.com/matplotlib/matplotlib/blob/v1.5.x/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_xelatex.pdf) and [pgf_xelatex.pdf This PR](https://github.com/jenshnielsen/matplotlib/blob/refreshpgfimages/lib/matplotlib/tests/baseline_images/test_backend_pgf/pgf_xelatex.pdf)

**Comment by jenshnielsen** [comment]
By installing cm-super I should have been able to lover the diffs for two more tests to zero. Unfortunatly cm-super is not currently allowed on Travis. I will take care of that. 


The final test still needs a diff of 4 to pass. From manual comparison it seems like it's only a text kerning issue but inspecting the pdf files seems to indicate that they are using different fonts.
```
pdffonts pgf_rcupdate1.pdf 
name                                 type              emb sub uni object ID
------------------------------------ ----------------- --- --- --- ---------
UKIXHV+LMRoman10-Regular-Identity-H  CID Type 0C       yes yes yes      6  0
UDYZXV+LMSans17-Regular-Identity-H   CID Type 0C       yes yes yes      8  0
EGPOOW+CMSY10                        Type 1C           yes yes no       9  0
GOUKDS+CMMI12                        Type 1C           yes yes no      10  0
EQCFIK+CMR17                         Type 1C           yes yes no      11  0
ICUTZB+CMR12                         Type 1C           yes yes no      12  0
```

```
pdffonts expected_pgf_rcupdate1.pdf 
name                                 type              emb sub uni object ID
------------------------------------ ----------------- --- --- --- ---------
QXFOXX+LMSans17-Regular-Identity-H   CID Type 0C       yes yes yes      7  0
CHCLNW+CMSY10                        Type 1C           yes yes no       8  0
VLXDTR+CMMI12                        Type 1C           yes yes no       9  0
ZOZAKN+CMR17                         Type 1C           yes yes no      10  0
UQFOZG+CMR12                         Type 1C           yes yes no      11  0
```

**Comment by jenshnielsen** [comment]
This should finally be working. I have reduced all the tolerances to 0 apart from rc_update1 (see above) 

I have rebased the changed on top of the now merged style changes pr #5774 (the pgf tests do not use the classic style) It is useful to verify the changes by comparing the pdf links above but I think they make sense.

**Comment by tacaswell** [comment]
Should this be backported to 2.x?

**Comment by jenshnielsen** [comment]
Yes I will do that as a pr

**Pull request merged**
