### PR TITLE
[MRG+1] Renamed all 'mtrans' into more common 'mtransforms'

### PR DESCRIPTION
**Pull request by sindunuragarp**
While looking through the codebase, I found that the `matplotlib.transforms` module was imported twice in `matplotlib.axes._axes` with two different names, namely `mtrans` and `mtransforms`. I found that the latter was a more common usage therefore I renamed all `mtrans` usages into `mtransforms`.

### CODE REVIEW

**Comment by anntzer** [comment]
You'll need to fix the lines that became too long and cause PEP8 violations (https://travis-ci.org/matplotlib/matplotlib/jobs/212698819).

**Comment by sindunuragarp** [comment]
Oh thanks for pointing that out :+1: I'll fix it right away

**Comment by anntzer** [comment]
still not there... you may want to run the checks locally.

**Comment by sindunuragarp** [comment]
I have run `pep8` locally and corrected all e501 violations that is made by `mtransforms`

**Comment by NelleV** [comment]
Thanks @sindunuragarp 
btw, most text editor have pep8 plugins that show you as you type if you are breaking pep8 compatibility.

**Comment by sindunuragarp** [comment]
Thanks for the suggestion! I'll keep that in mind :+1:

**Pull request merged**
