### PR TITLE
ENH: pass dash_offset through to gc for Line2D

### PR DESCRIPTION
**Pull request by tacaswell**
Previously, the user supplied offset to Line2D set_linestyle
was silently discarded.  This commit makes the value to be passed
through to the underlying GC on draw, but not all of the backends do
anything with the offset (ex Agg does not).

### CODE REVIEW

**Comment by mdboom** [comment]
See my enh_dashoffset branch.  I fixed the Agg backend and the PostScript backend.  All other backends seemed to already work.  (Can't make PR against this because we have too many forks and I can't set yours as the base ?!?)

We should add a test based on your example in #5430.

**Comment by tacaswell** [comment]
We have emailed gh about that issue, we are just too big.  The work around
is url hacking as the bug is in generating the drop down menu.

**Comment by tacaswell** [comment]
I think this is ready to go.

**Comment by mdboom** [comment]
Backported to 2.0.x as d11e344d313b

**Comment by afvincent** [comment]
In `test_dash_offset()`, is it normal to have `plt.show()` at the end of the test? I just ask this because when I run `test_axes` in an IPython session, it is the only test that plots something on my screen (and waits for me to close the window to finish the other tests, as plt.ion() is not used).

**Comment by tacaswell** [comment]
That can probably be removed.

**Pull request merged**
