### PR TITLE
Add emojis to issue template titles

### PR DESCRIPTION
**Pull request by ianhi**
## PR Summary
Follow up to https://github.com/matplotlib/matplotlib/pull/19521

### CODE REVIEW

**Comment by ianhi** [comment]
These were directly inspired by https://github.com/napari/napari

**Comment by jklymak** [comment]
I understand the sentiment, but I do not think these really help understanding, and they frankly look cheesy to me.

**Comment by dopplershift** [comment]
@jklymak Is that you think they look cheesy when rendered in the [GitHub chooser](https://github.com/napari/napari/issues/new/choose)? I'm kinda ok with them: 
image

**Comment by jklymak** [comment]
Sure, it's a taste issue.  Where I will be more strenuous in objecting is if they start showing up in milestones and issue labels.  You can't easily search on them.

**Comment by dopplershift** [comment]
Absolutely. I just wanted to clarify, because I was much more OK with them in the UI than I was seeing them in the raw markdown.

**Comment by QuLogic** [comment]
The problem though, is that emoji display is not necessarily consistent:
image
Here I thought the bug looks more like a snake at that size.

**Comment by timhoffm** [comment]
grafik

Windows doesn't look too good either (independent of browser Chrome/Firefox/Edge).

**Comment by WeatherGod** [comment]
It is an "em"-worm!

Sorry, I'll show myself out...

**Pull request closed without merging**
