### PR TITLE
[MRG+1] BUG: fix autoscale_view with log scale and margins

### PR DESCRIPTION
**Pull request by efiring**
LogLocator.view_limits was always clipping vmin to minpos;
now it sets vmin to minpos only if vmin <= 0.

### CODE REVIEW

**Comment by efiring** [comment]
There are many failed tests because the test baseline images show the effects of the bug.  I am fixing the images.

**Comment by NelleV** [comment]
Thanks! This looks good.

**Comment by NelleV** [comment]
Was there a ticket opened for this bug? It sorts of rings a bell…

**Comment by efiring** [comment]
Closes #6643.

**Comment by efiring** [comment]
@qlogic, minpos is the minimum *positive* value in the data.  It is used to handle log scales applied to data that might include zero or negative values.

**Comment by NelleV** [comment]
Thanks @efiring !

**Comment by tacaswell** [comment]
wow, that is a major improvement!

**Comment by efiring** [comment]
@anntzer pointed out the error in his writeup of #6643.

**Pull request merged**
