### PR TITLE
TST: Lock pytest to 3.2.5 until 3.3.1 released

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

As per @QuLogic comments in #9867 Appveyor tests are breaking because of a change to pytest 3.3.0 https://github.com/pytest-dev/pytest/issues/2957  Until 3.3.1 is released this locks us to 3.2.5 on appveyor.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Note pytest has a fix: https://github.com/pytest-dev/pytest/pull/2969

**Comment by jklymak** [comment]
Looks like the error has spread to Travis as well.  If someone can fix it before I do feel free to push onto this branch

**Comment by tacaswell** [comment]
You can also do `!=3.3.0` which is a bit more robust.

**Comment by tacaswell** [comment]
but, not worth holding the PR over that.

**Comment by jklymak** [comment]
Oh cool!

**Comment by jklymak** [comment]
This basically passes (Xcode check not done). Prob should be merged soon if OK by everyone...

**Comment by jklymak** [comment]
Hmmmm, how does this get manually backported (if needed?)

**Comment by tacaswell** [comment]
backported to v2.1.0-doc in #9885 and merged to 2.1.x in 55830e520528e07a0a3b4eac5f174544fb42f42d

**Pull request merged**
