### PR TITLE
Bug fix for Hatch linewidths in an rcParam context #21325

### PR DESCRIPTION
**Pull request by rishavganguly007**
## PR Summary
Provided fix based on the sugesstions given for the issue https://github.com/matplotlib/matplotlib/issues/21108
## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

### CODE REVIEW

**Comment by QuLogic** [comment]
Thank you for the PR. Please revert all the unrelated stylistic changes, as it is difficult to pin down what exactly you are changing here and they are all superfluous. This will also require adding some tests, I think.

**Comment by melissawm** [comment]
Hi @rishavganguly007 - there are still a couple of lines that are too long to pass our linter, could you check that so we can move forward with the review? Thanks!

**Comment by rishavganguly007** [comment]
> Hi @rishavganguly007 - there are still a couple of lines that are too long to pass our linter, could you check that so we can move forward with the review? Thanks!

Hi @melissawm I have corrected the linting issue , but in the github test I can see still the flake8 test is failing for some whitespaces,
However, in my local when I am running the cmd `flake8 <file path>` I am not getting any issues.

**Comment by melissawm** [comment]
Might be worth checking your flake8 installation - when I run `flake8 lib/matplotlib/hatch.py` locally, I also get
```
lib/matplotlib/hatch.py:239:1: W293 blank line contains whitespace
lib/matplotlib/hatch.py:239:38: W292 no newline at end of file
```

In any case, you can use the CI as the source of truth here and fix those anyway.

**Comment by rishavganguly007** [comment]
> Might be worth checking your flake8 installation - when I run `flake8 lib/matplotlib/hatch.py` locally, I also get
> 
> ```
> lib/matplotlib/hatch.py:239:1: W293 blank line contains whitespace
> lib/matplotlib/hatch.py:239:38: W292 no newline at end of file
> ```
> 
> In any case, you can use the CI as the source of truth here and fix those anyway.

Thanks @melissawm , all the lint related issues has been fixed.

**Comment by melissawm** [comment]
Ok - it looks like now you have a few failed tests, can you take a look and see if those are related to your PR?

**Comment by rcomer** [comment]
@rishavganguly007 are you still interested in working on this one?

**Comment by rcomer** [comment]
I am going to close this one as it seems to have stalled.  Closing will indicate to other contributors that they can pick up the issue.  The patch is at https://github.com/matplotlib/matplotlib/issues/21108#issuecomment-922269138, so I think it will be at least as easy to start from there as it would be to rebase this branch.

@rishavganguly007 if you are still interested in working on this, please do comment and we can re-open.

**Pull request closed without merging**
