### PR TITLE
Remove mention that tkagg was derived from PIL.

### PR DESCRIPTION
**Pull request by anntzer**
It has basically been entirely rewritten (and rearchitected) by Matthew Brett and myself
(and others), at this point.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
The paint one was clear (that code is fully gone), I am less sure on this one.  I am not sure how far you have deform code to no longer be considered "derived" ("this is my grand parent's axe, my parent replaced the handle and I replaced the head").   I would like to consult a lawyer before we merge this.  

The baseline to compare to should be what ever the initial code was?

**Comment by tacaswell** [comment]
I'm sending an email about this now via private channels.

**Comment by tacaswell** [comment]
Update: legal is backed up, review is still pending.

**Comment by QuLogic** [comment]
Any update?

**Comment by tacaswell** [comment]
Re-pinged on the legal front.  

If we do not need it, but carry it anyway I think there is little down side, but if we need to have it and strip it I think we are risking a relatively large down side (but IANAL), out of an abundance of caution pushing to 3.4.

**Comment by tacaswell** [comment]
Sorry, the update on this got lost in my mental queue

The advice is to, if we are sure all the code has been re-written, we should add this text someplace in the docs: 

> "Where is PIL?
Many years ago, Matplotlib used to include code from PIL. Since then, the code has changed a lot - the organizing principle and methods of operation are now quite different. Because our review of the codebase showed that all the code that came from PIL was removed or rewritten, we have removed the PIL licensing information. If you want PIL, you can get it at <URL>."

**Comment by anntzer** [comment]
I can put that snippet at the top of tkagg.cpp if you want.

**Comment by tacaswell** [comment]
That seems like a good place to put it.

**Comment by anntzer** [comment]
done

**Pull request merged**
