### PR TITLE
DOC: mac + pkg-config

### PR DESCRIPTION
**Pull request by tacaswell**
- change name for brew -> pkg-config (pkgconfig is alais)
 - add pkgconfig for macports

attn @jenshnielsen

### CODE REVIEW

**Comment by tacaswell** [comment]
I don't have a mac to actually test this, based on https://www.macports.org/ports.php?by=library&substr=pkgconfig

**Comment by jenshnielsen** [comment]
The Brew instruction is correct. I don't actually have macports installed on my Mac to test but I think it looks fine. If no one else steps in I can try get MacPorts up and running on a VM on my mac.

**Comment by jenshnielsen** [comment]
I haven't had a chance to test the macports instructions and I am temporary without my Mac. Perhaps we can merge as is and correct if anyone finds issues with the macport instructions?

**Comment by tacaswell** [comment]
cherry-picked to master as 2299f3018f351c580149e91bd8015c30f2897217

**Pull request merged**
