### PR TITLE
Build docs on Python 3.5

### PR DESCRIPTION
**Pull request by mdboom**
I really can't take any credit for this one-line change to turn this on.  There has already been a great deal of heavy lifting over many months to get this working, esp. @jenshnielsen.  Thanks, everyone!

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This fails because #5292 hasn't been merged into master from 1.5.x

**Comment by mdboom** [comment]
Ok.  I'll do the merge.

**Comment by jenshnielsen** [comment]
Linkchecker is not python 3 compatible :disappointed:

**Comment by mdboom** [comment]
Bummer.  Since linkchecker doesn't actually have to run in the same Python as the docs build, though, I wonder if we could just install it from the Debian package.  I might as well try that here.

**Comment by mdboom** [comment]
It seems `linkchecker` is not in the Travis APT installable whitelist.  It's been requested, I think it just needs a human from Travis to manually verify that it's safe: https://github.com/travis-ci/apt-package-whitelist/issues/1187

We could try to install and run linkchecker in the Python 2.7 install alongside building the docs in 3.5, but that could get hairy...

**Comment by tacaswell** [comment]
If we used conda we could just make two envs.....

It looks like linkchecker is making progress on python3 compatibility on their master branch, probably not worth the effort though.

**Comment by jenshnielsen** [comment]
We can do that with virtualenv too if we want to something like 

```python
deactivate
source ~/virtualenv/python2.7/bin/activate
pip install linkchecker
```

But I don't know how brittle that will be.

**Comment by jenshnielsen** [comment]
Closed since #5797 is merged

**Pull request closed without merging**
