### PR TITLE
Add badges to readme

### PR DESCRIPTION
**Pull request by patniharshit**
#8177 
Add badges to readme

### CODE REVIEW

**Comment by QuLogic** [comment]
This is a duplicate of #8178; please check for existing PRs before starting to work on something.

**Comment by patniharshit** [comment]
Nobody referenced the issue so I thought no one was working on it :(

**Comment by anntzer** [comment]
No worries.

**Comment by dstansby** [comment]
Sorry you didn't see it; it's often a good idea to check recent pull requests as well as the original issue.

**Pull request closed without merging**
