### PR TITLE
[Doc] Add ACCEPTS for some Axes set methods

### PR DESCRIPTION
**Pull request by oscargus**
## PR summary

If I understand things correctly, this will provide information to the property tables and avoid "unknown".

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by timhoffm** [comment]
Do you have a link to a property table that is affected?

**Comment by oscargus** [comment]
New: https://output.circle-artifacts.com/output/job/c73ffe8b-889a-4308-8f90-557401d33a44/artifacts/0/doc/build/html/api/_as_gen/matplotlib.axes.Axes.html#matplotlib.axes.Axes

Old: https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.html#matplotlib-axes-axes

`xbound` is one example.

**Review by timhoffm — APPROVED** [review]
This is good for now.

FYI: The obscure `.. ACCEPTS`  doc comments should be repaced by a decorator in the future, see 2#2699.

**Comment by oscargus** [comment]
Yes, I agree that they are obscure. But since they solve the problem and there seems to be issues agreeing on the decorator...

**Pull request merged**
