### PR TITLE
DOC: some minor fixes to the usage rewrite

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This fixes a few typos and missed commas in `usage.py`.  

Follow up of #21641

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by dstansby** [comment]
Why all the extra `plt.show()` calls? sphinx-gallery should show the figures under the block they were created in, and I always think it's better to just have one `plt.show()` call at the end when running examples locally so all the figures appear at once.

**Comment by jklymak** [comment]
Ah, because if you don't SG put "Out: Legend(...)" in a yellow box after everything.  I _could_ just put semicolons I guess?

**Comment by dstansby** [comment]
I'm +1 for semicolons as opposed to `plt.show()`

**Comment by jklymak** [comment]
Hmm, except semicolons are a flake8 exception...

**Review by dstansby — APPROVED** [review]
Lets leave it with `plt.show()`s then, not a big deal 😄

**Comment by jklymak** [comment]
This commit drops the shows, adds `;` and puts in an exception for the trailing semicolon.  In exchange I got rid of the lines that were too long :wink:  OTOH we _never_ make this exception so I'm not quite sure what our policy is on it.  I personally don't see what the big deal is, and it greatly enhances the readability of the examples.  Maybe there is a SG setting to suppress...

**Comment by jklymak** [comment]
I understand in general we do not want semicolons at the end of statements, but in this case it serves a really useful purpose - it saves the extra useless and confusing output, or it saves a spurious `plt.show`, or it saves a spurious and confusing assignment.  OTOH I won't object if someone has a way to suppress these via configuration.  However, note that some of our examples _want_ the output to show up, so it can't be global.

**Review by dstansby — APPROVED** [review]

**Comment by tacaswell** [comment]
I'm in favor of not backporting this and letting the examples start to diverge again.

**Comment by QuLogic** [comment]
This depends on #21641, which has not been backported yet. But that also conflicts, so I guess depends on whether @jklymak wants to do it.

**Comment by jklymak** [comment]
I think we _should_ back-port these, as the current Usage Guide is very sparse....

**Comment by StefRe** [comment]
> I understand in general we do not want semicolons at the end of statements, but in this case it serves a really useful purpose - it saves the extra useless and confusing output


I have no idea why, but the yellow output boxes are still present  in the current [devdocs Basic Usage tutorial](https://matplotlib.org/devdocs/tutorials/introductory/usage.html), despite the semicolons.

**Comment by jklymak** [comment]
Yes, that didn't work too well ;-)

**Pull request merged**
