### PR TITLE
[WIP] Merge pull request #7907 from jkseppan/fc-list-format

### PR DESCRIPTION
**Pull request by tacaswell**
BUG: Add a newline separator in fc-list call

Conflicts:
	lib/matplotlib/tests/test_font_manager.py
	 - only backport the fix not the test as it uses a decorator
	that does not exist in 2.0.x

This needs to have a test added, but putting here as a place holder so I do not forget.

### CODE REVIEW

**Comment by NelleV** [comment]
setting this explicitly as a WIP, to prevent merging too soon

**Comment by jkseppan** [comment]
I pushed a test onto your branch, but now the conflict shows that a test has already been added on v2.0.x. Perhaps this PR is obsolete?

**Comment by jkseppan** [comment]
Seems that commit fe1641b33ec0df1154425a4b260d9ebaab4818e8 took care of this.

**Comment by QuLogic** [comment]
Huh, didn't know this PR existed. Yes, the backport is done already.

**Comment by tacaswell** [comment]
@QuLogic @jkseppan Thanks!  Sorry for the confusion / poor communication on my part.

**Pull request closed without merging**
