### PR TITLE
FIX: guard against numpy warnings

### LINKED ISSUE #6970: quiver problems when angles is an array of values rather than 'uv' or 'xy'
I use the version of matplotlib that is included in the following distribution:
Python 3.5.2 |Anaconda 4.1.1 (x86_64)| (default, Jul  2 2016, 17:52:12) 
IPython 4.2.0 -- An enhanced Interactive Python.

quiver produces the following warnings when called with angles=array :

/Users/mlandriau/anaconda/lib/python3.5/site-packages/matplotlib/quiver.py:609: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.angles == 'xy' and self.scale_units == 'xy':
/Users/mlandriau/anaconda/lib/python3.5/site-packages/matplotlib/quiver.py:614: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.angles == 'xy' or self.scale_units == 'xy':
/Users/mlandriau/anaconda/lib/python3.5/site-packages/matplotlib/quiver.py:647: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self.angles == 'xy':
/Users/mlandriau/anaconda/lib/python3.5/site-packages/matplotlib/quiver.py:649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.angles == 'uv':

It seems to produce the right answer, except quiverkey no longer works properly (the arrow is a filled half-circle instead of a line).

### PR DESCRIPTION
**Pull request by tacaswell**
Do not try to compare a string to an array.

closes #6970

### CODE REVIEW

**Comment by WeatherGod** [comment]
looks good to me.

**Comment by efiring** [comment]
This is fine and I'm on the edge of pressing the button, but... I think that adding the test is overkill.  Here's the larger issue: test code is still code, still subject to bugs, still a potential cause of puzzlement among developers, still something that needs maintenance.   The test here is for a very specific problem that has been solved in a general and obvious way--there are probably hundreds of similar places in the code where problems like this have been solved, or never arose, and it would do us no good to put in tests for them.  Similarly, I think that in the long run having this test included will be a net drag, not a net gain, for the development and maintenance process.

**Comment by efiring** [comment]
Aha, I didn't update my web page before writing that comment, so I see my point is moot for this PR.  Nevertheless, I think that this issue of how to ensure our test suite is lean and effective, and minimally puzzling, is something we need to consider more carefully in the future.

**Comment by tacaswell** [comment]
@efiring Want me to open a PR to remove that test?

**Comment by efiring** [comment]
Only if you agree with my rationale and feel motivated.  We can discuss this on Monday if you like.  It's really more the big picture that I'm concerned about.

**Comment by tacaswell** [comment]
I also half-viewed those tests as a down-payment on more through quiver tests (as this was a code path we do not otherwise touch) so it is getting us some additional (smoke-test) coverage.

**Pull request merged**
