### PR TITLE
Add tests for ImageGrid

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

Add tests for ImageGrid.

Minor correction to docs and code as one can get the impression that a string can be passed as `rect`, but this will give an error later on.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by QuLogic — APPROVED** [review]

**Comment by QuLogic** [comment]
Oh, also, do you need text; can you set `remove_text=True`?

**Review by timhoffm — COMMENTED** [review]
I suggest to connect the color are with the respective axes images, so that they are not empty. C.f. https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_grid.html

Also, not sure if it’s worth it here, but I generally try to introduce asymmetry into tests, e.g. (2,3) instead of (2,2) so that the test gets sensitive to a mixup of rows/columns.

**Comment by oscargus** [comment]
> Oh, also, do you need text; can you set `remove_text=True`?

I also test `label_mode`, so the text is required to see the effect.

**Comment by oscargus** [comment]
> I suggest to connect the colorbars with the respective axes images, so that they are not empty. C.f. https://matplotlib.org/stable/gallery/axes_grid1/demo_axes_grid.html
> 
> Also, not sure if it’s worth it here, but I generally try to introduce asymmetry into tests, e.g. (2,3) instead of (2,2) so that the test gets sensitive to a mixup of rows/columns.

Sure, I can modify the tests like that.

**Comment by oscargus** [comment]
This is updated based on the comments, including expanding the test names to tell what is tested.

It is maybe not a good idea to test two features, colorbar and `label_mode` in the same test, but there will be quite a lot of images testing all combinations...

**Comment by timhoffm** [comment]
> This is updated based on the comments, including expanding the test names to tell what is tested.
> 
> It is maybe not a good idea to test two features, colorbar and `label_mode` in the same test, but there will be quite a lot of images testing all combinations...

`label_mode` can easily be tested algorithmically by checking visibility attributes. I don't think we need images for that. This has the added benefit that these tests become independent of the visual representation of ticks and labels.

**Comment by oscargus** [comment]
I was a bit unclear. I was referring to combination of colorbar combinations (`each`, `single`, `edge`) x ('left', 'right', 'top', 'bottom').

Not so clear why the colorbar content should be in the test (which is not at all related to ImageGrid as such), but the text should not (which allows visible inspection of what should happen).

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
