### PR TITLE
Confluence builder in plot directive

### PR DESCRIPTION
**Pull request by jjcaballero**
## PR Summary
Added "confluence" as a possible builder in plot_directive.py.
This allows using _matplotlib_ with this sphinx extension: https://github.com/sphinx-contrib/confluencebuilder
The images were already properly generated, the only pending thing was to consider confluence as a builder and then add the images within the template.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Does everything else build as expected with the confluence builder?

**Comment by anntzer** [comment]
Perhaps #14683 is a worthwhile alternative approach?

**Comment by tacaswell** [comment]
Temporarily closing in favor of #14683 .  If the confluence backend can not be made to support selecting it's preferred format we can re-address this.

**Comment by tacaswell** [comment]
Thank you for your work on this @jjcaballero !

**Comment by jjcaballero** [comment]
@tacaswell No problem, it makes sense. The alternative is more general #14683, I will look into the confluence builder to handle the *. Thanks!

**Pull request closed without merging**
