### PR TITLE
Allow use of units in 3d plotting

### PR DESCRIPTION
**Pull request by EzraBrauner**
## PR Summary
Allows use of units in 3-dimensional plotting. This is my first open-source contribution, and I'm not so familiar with the codebase, so please let me know if these changes cause any issues, or if I need to do anything else. See #22207.
## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by QuLogic** [comment]
This is not the right approach. Everything in `matplotlib.testing` is for testing only.

Unit conversion is done with `Axes.convert_xunits` or (more generally) `Axis.convert_units`.

**Comment by tacaswell** [comment]
Thank you for your work @EzraBrauner , but I agree with @QuLogic that this is not the correct approach and am going to move this to a "draft".

The x and y data are actually passed through the unit conversion machinery when we call `super().plot(...)`, it is only the z that is not handled.  Presumably we will have to duplicate most of the handling from the 2D case to the z-axis (and may have to _undo_ some of the 2D unit work!).  I suspect that there will be some subtlety involved in ensure that the conversion and 2D->3D conversion is handled in the right order.

I think the first step in implementing this feature would be to walk through and understand how units are handled in the 2D case.

**Comment by EzraBrauner** [comment]
Hi, I have a general sense of how a plot() call has its units converted, although it is unclear to me how this conversion affects the error in the referenced Issue. The error occurs in auto_scale_xyz(...), which I think uses the original xs, ys, and zs and not the values of xs and ys converted by super().plot(...). I don't think my most recent commit is what you're looking for; if it isn't, feel free to let someone else tackle this as I don't think I am comfortable enough with the codebase yet. Thanks!

**Comment by tacaswell** [comment]
Thank you again for your effort @EzraBrauner (even if we are not going to merge it).

You started off with the code base by jumping into an issue that hits the two of the more complex and under-documented parts of the code base (3D and units).  As is typical with software, when taken together the complexity in multiplicative not additive!  Please do not be discouraged and we hope to hear from you again.

**Comment by EzraBrauner** [comment]
@tacaswell Thanks for the encouragement! It was difficult for me to tell that this issue was complex based on my limited understanding of the code, so in the future I'll be sure to pay more attention to difficulty before choosing an issue to fix.

**Comment by tacaswell** [comment]
Estimating how hard things will be in software is ... hard.   You frequently do not actually know how hard it will be until you try (I have had "this will take 5 minutes..." turn into a few days of work and things I thought would take days, only take an hour).

My advice is to pick an issue that is relevant to you and dig in!  Worst case is you have learned something and hopefully had some fun (ok, maybe not everyone shares my enthusiasm for digging into code bases....), best case you fix a bug.

**Comment by EzraBrauner** [comment]
Makes sense! Thanks for the advice.

**Pull request closed without merging**
