### PR TITLE
Clarify to_rgba docstring.

### PR DESCRIPTION
**Pull request by anntzer**
All's in the title.

### CODE REVIEW

**Comment by anntzer** [comment]
Go ahead.

**Comment by anntzer** [comment]
(And you can force-push as much as you want.)

**Comment by tacaswell** [comment]
@NelleV going to merge this as-is (as I want it for the rc), can you follow up with another PR for the formatting?

**Comment by anntzer** [comment]
Sure.

**Comment by tacaswell** [comment]
backported to v2.x as 56635c5

**Pull request merged**
