### PR TITLE
Add research notice

### PR DESCRIPTION
**Pull request by yochannah**
this helps make sure that people contributing to this repo are aware metrics will be gethered as part of the study over the next twelve months :)

## PR Checklist

- [n/a] Has pytest style unit tests (and `pytest` passes).
- [n/a] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by WeatherGod** [comment]
Would it also make sense to have a small note and link to this section of the readme in the Issue and PR templates? Many contributors won't notice this in the readme if they have been contributing before.

**Comment by tacaswell** [comment]
Are you going to be pulling any data that is not already public / accessible through the GH api?  If not, I'm skeptical that this notice is needed at all, but I do not think we need to add more text to the already very verbose issue and PR templates.

**Comment by yochannah** [comment]
Nothing non public is going to be gathered from github repositories, but I
think even though it's technically public, it's polite and less spooky to
let people have some way to know we're gathering info.

In my ethics application, I said we'd try to place notes in readmes. The
rest is up to y'all - thanks for signing up!!

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
I'll merge this for the README (both for the reasons @yochannah noted and to give the project a bit more advertising!), but stand by not needing to put a note anywhere else.

**Comment by tacaswell** [comment]
Also, @yochannah congratulations on getting your first PR into Matplotlib :tada:

**Pull request merged**
