### PR TITLE
[MRG + 1] Fixed a small mistake in matplotlibrc.template

### PR DESCRIPTION
**Pull request by rebot**

### CODE REVIEW

**Comment by WeatherGod** [comment]
could you double-check that the same mistake wasn't made in other style sheets?

**Comment by dopplershift** [comment]
Well I guess that's evidence that changing the base branch can do weird things.

**Comment by dopplershift** [comment]
I switched back to v2.0.0-doc (which will eventually get merged into master), and have closed/opened the PR to see if Travis works again.

**Comment by tacaswell** [comment]
@rebot Thanks!  I think this is your first contribution to Matplotlib 🎉  

Hopefully we will hear from you again!

**Pull request merged**
