### PR TITLE
Fix errobar order

### LINKED ISSUE #1622: zorder is not respected by all parts of `errorbar`
This was found by via a SO question  (http://stackoverflow.com/questions/14003572/how-to-force-errorbars-to-render-last-with-matplotlib)

It looks like the root cause of this issue is that LineCollections do not take zorder as a parameter.

The hacky work around is to put negative zorder on the lines you want to be below the error bars.

```
import matplotlib.pyplot as plt
fig = plt.figure()
ax = plt.gca()
[ax.plot(rand(50),color='0.75') for j in range(122)];
ax.errorbar(range(50),rand(50),yerr=.3*rand(50))
plt.draw()
```

eb_wrong

```
fig = plt.figure()
ax = plt.gca()
[ax.plot(rand(50),color='0.75',zorder=-32) for j in range(122)];
ax.errorbar(range(50),rand(50),yerr=.3*rand(50))
plt.draw()
```

eb_hack

### PR DESCRIPTION
**Pull request by cosama**
## PR Summary

Closes #1622 #17139 

This pull request fixes inconsistent behaviors of `errorbar` and the order they are drawn with respect to other elements.

They way this is done, is to change how the vertical and horizontal columns of `errorbar` are plot. So far a `LineCollection` was used. Unfortunately, the only way to have a collection being drawn before `Lines2D` is to change the `zorder`, which let to weird behavior as well, when other objects are supposed to be plot above the error bars. The proper way to fix this would be to fix the internals of how collections and lines are stored and ordered as mentioned by @tacaswell in https://github.com/matplotlib/matplotlib/issues/1622#issuecomment-142469866.

As the proper fix is a major rework of `matplotlib` and probably not possible in the foreseeable future, I suggest an easier fix here: The vertical and horizontal bars are drawn with `Line2D`s. The only issue this causes it that the call to `errobar` now returns a `list` of `Line2D` while so far a `LineCollection` was returned. It would be even possible to add the errorbar caps directly to these new `Line2D` making errorbars more flexible and less argument parsing necessary, but that would have created even more changes, so I kept it simple for now (let me know if that is something you think is worth it).

The implementation should pass all tests, I had to change a few tests, where the test checked inconsistent behavior/wrong images caused by the old implementation.

Don't think this is a API change that can be made easily backward-compatible, or where a deprecation warning could be used, I'm open to suggestions how to resolve this. For sure might cause some issues of packages that depend on the correct return type. However, unless someone else has a good idea how this can be fixed, I think the benefits outweigh the drawbacks for now.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Thank you for working on this!

However, I have several serious concerns about this.

As you note, this is a un-mitigatable API change so anyone who is currently working with the return values will have their code broken with no warning.  This will also break any code that is expecting to be able to look at the `line` or `collections` attributes on the Axes.

`LineCollection`with many lines is significantly more preformant than the same number of Line2D objects, I am worried that switching to individual Line2D objects will cause significant performance regressions.

---

A middle ground, which accepts some API breakage of not being able to find the artists in the expected lists is:

 - change from using `self.vlines` and `self.hlines` to creating the `LineCollection` artists directly (like we already do with `Line2D` instead of using `self.plot`)
 - write a very thin Artist sub-class (or duck-type?) that basically only knows enough for forward it's draw call onto its children
 - add all of the created artists to the proxy / bucket artist described above (rather than calling `self.add_line`) 
 - add the proxy artist to the axes with `self.add_artist`. 
 - make sure the new artist participates it autoscaling as we expect etc

In this case we do get to fix the rendering order issues but still preserve the return type and the performance gains.

---

Sorting out how to do a major overhaul is part of what @story645 is funded to work on under CZI grant so hopefully the major overhaul is much closer than it used to be!

**Comment by tacaswell** [comment]
You need inkscape locally to run the svg tests (we do comparisons after rasterization rather than text comparison and use inkscape to do that rasterization).

The very very fast summary of Artists is everything you see in the output is represented by an `Airtist` internally (see https://matplotlib.org/tutorials/introductory/usage.html#parts-of-a-figure).  When we render a figure we create a `renderer` object and then pass it into `Figure.draw(renderer)` which in turn recursively calls the `draw` method of its children and so on (aka visitor pattern).  In each `draw` method the artist has the ability to leave marks on the canvas.  At the end those aggregated marks are serialized out as the svg/png/... 


https://aosabook.org/en/matplotlib.html is a good reference for the overall architecture.

**Comment by cosama** [comment]
@tacaswell. Thank you so much for taking time to explain that. Your references have been very valuable so far.

The way I would think the objects should appear is:
1) Any previously plotted line, etc.
2) Error bar lines and error bar bars depending on `barsabove`
3) Any line, etc. plotted later

I think I figured out how the different artists are sorted for `Axes` through https://github.com/matplotlib/matplotlib/blob/d4bd4e70161ea438ba39080fd9168b34c0276250/lib/matplotlib/axes/_base.py#L2728 and https://github.com/matplotlib/matplotlib/blob/d4bd4e70161ea438ba39080fd9168b34c0276250/lib/matplotlib/axes/_base.py#L4038-L4054. If my understanding of this is correct, the envisioned order only is possible if the new artist sub-class is a `line2D` itself and added through `Axes.add_line`, so that it appears in `AxesBase.lines` at the correct position.

I think using `Line2D` as a base class would be quite natural for something like `Line2DWithErrorbars`. Most code currently being implemented in `Axes.errorbar` could be moved to that new class, or left where it is for now, depending on how big these changes should be (opinions are welcome).

If you agree with me on this, I think I could manage the required changes.

**Comment by anntzer** [comment]
The fact that all child artists are not stored in a single list is unfortunate, making it difficult to break ties by insertion order (which is more or less what we need here, I guess).  I guess one option would be to complement zorder with a hidden `_insertion_order` which would use a global counter, and use *that* to break ties in zorder instead.

**Comment by cosama** [comment]
I pushed another implementation of this, now as @tacaswell descriped using a single `Artist` holding all error bar objects, in this case a class inheriting directly from `Line2D`. As it is mostly a line, it can be sorted in correctly with the other `Line2D` objects in `Axes.lines`. I think a lot of the complexity currently present in `Axes.errorbar` could be moved to that new class, but I hold off doing so to see what you guys are thinking about it first.

There is something wrong with the documentation, will fix that later, but other than that it seems to pass all tests.

**Comment by cosama** [comment]
I will leave this as it is for now. With @anntzer's suggestion in #17247, these changes would be unnecessary.

I think however, putting errorbars into a single `Artist` container is a good idea, however, if it doesn't have to be sorted in as a `Line2D` the implementation probably could be optimized.

**Comment by QuLogic** [comment]
#18216 is now in, so I think we can now close this. Thank you for working on this, @cosama, and sorry it did not get merged in. If you want to work on the other things, feel free to open a PR.

**Comment by cosama** [comment]
@QuLogic Thanks for working on this. Awesome to see this finally getting into matplotlib. Was happy to help.

**Pull request closed without merging**
