### PR TITLE
Fix flipped paths in non-writable config dir warning.

### LINKED ISSUE #18011: Confusing error message when home config directory not writable
### Bug report

**Bug summary**

If matplotlib is run in an environment without a writable home directory, a very confusing error message is printed in which the configdir and the tempdir are interchanged. 

**Code for reproduction**

1. In Linux, create a user `someone` with no home directory. 
2. Run Python with a command like

    sudo -u someone python3

3. In the Python shell, type `import matplotlib`

**Actual outcome**

```
Matplotlib created a temporary config/cache directory at /root/.config/matplotlib because the default path (/tmp/matplotlib-9yoi7m8l) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

**Expected outcome**

```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9yoi7m8l because the default path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.9.0b4
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Matplotlib was compiled from source. The error is at line 482 in `__init__.py` at the root level in the source tree. The parameters are the wrong way round.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Fixes #18011.

## PR Checklist

- [ ] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/next_api_changes/* if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by john-zenden** [comment]
Error: [WARNING]	2022-08-01T20:35:34.010Z		Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dw7qh4b1 because the default path (/home/sbx_user1051/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.

I got this in AWS Lambda and comment here only for the benefit of those who might come across this in a Google search.

If you are using Matplotlib (or something which depends on it) in the AWS Lambda environment you have probably already run up against 250MB limit for the Zip deployment method of the AWS Lambda function. If you go to a Image deployment, your image can be up to 10GB.

Deploying the AWS Lambda function as an image offers two things to solve this error (and speed up your function). First, in the Configuration section for the function, set the Ephemeral Storage to a higher value (something like 1024). Be aware that your costs will calculated at GB/seconds for this resource.  Then, add the following to your Dockerfile after the RUN command calling pip to install your dependencies:

ENV MPLCONFIGDIR=/tmp

If you look carefully at the Ephemeral Storage setting in AWS, you'll see it refers to /tmp. You are telling Matplotlib to use /tmp as its temp storage, and configuring the max size in AWS at 1GB (1024MB).  To see why this works, bring up a CLI for the Docker image. I am developing on Windows with VSCode with the AWS SAM CLI, which requires Docker be installed. So after running > 'sam build' at the Terminal CLI in VSCode, Docker starts running the image. In Docker I click the ">" button and a CLI terminal for the image appears.

Like any other Linux environment, you'll be in a user directory. CD back to the root folder. Do an ls -al and take note of the permissions for /home and /tmp. You'll see that /tmp is writable by default, but /home is not. By adding the ENV command in Dockerfile you are telling Matplotlib to use /tmp. By setting the Ephemeral Storage value in AWS you are allocating sufficient space in /tmp.

Thew warning in the logs should then disappear.

**Comment by tacaswell** [comment]
One of the things that goes into the cache directory is a json file of the fonts we found.  Pre-generating that file and uncluding it in your image will speed up the initial import time by avoid a (possibly expensive) file walking process.

**Comment by john-zenden** [comment]
@tacaswell Is the JSON filename always the same?

**Comment by tacaswell** [comment]
Yes, but if we change the spec of the file we will change the filename.  We have not changed it recently, but I suspect we will change it soon.  If you need to support more than one version of mpl include both files.

https://github.com/matplotlib/matplotlib/blob/133f797ea87f4ab0172718832de3fa1bbc921f66/lib/matplotlib/font_manager.py#L1623-L1638

**Pull request merged**
