### PR TITLE
__future__ division is now.

### PR DESCRIPTION
**Pull request by anntzer**
In divisions with a literal numerator or denominator, it is not
necessary anymore to artificially add ".0" to get float division instead
of integer division.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
... while I agree this is true, the extra `.0` doesn't exactly hurt anything...

**Comment by timhoffm** [comment]
While I'm usually pro-codestyle-commits, I'm not sure that this is good. The decimal points are not very noticeable. OTOH this commit creates quite some noise in the git annotations of the code.

**Comment by anntzer** [comment]
As usual it's just running a couple of regexes.  If there's strong opposition to it I'm fine with closing.

**Comment by WeatherGod** [comment]
I am also -0 on this. Seems like unnecessary churn that would also make
backports more difficult. I doubt there is a net gain here.

**Comment by tacaswell** [comment]
Thanks for the work and being understanding @anntzer .

**Pull request closed without merging**
