### PR TITLE
Add Save Tool to NbAgg Figure [backport to 1.4.x]

### PR DESCRIPTION
**Pull request by blink1073**
Adds a toolbar save icon that opens a new window with the image that can be saved to a local file.

screenshot from 2015-01-07 15 53 35

Also adds ability to save the figure using the "S" key.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @pelson

**Comment by pelson** [comment]
CC @mdboom based on the [comment](https://github.com/matplotlib/matplotlib/issues/3972#issuecomment-68954041) in #3972.

@blink1073 - the hardest part of this is figuring out where to go to download content.

If this is really a route we want to take (I personally don't see much of a use for a save button inside the notebook UI), then perhaps [downloadify](https://github.com/dcneiner/Downloadify) may be of interest.

**Comment by blink1073** [comment]
@pelson, my use case is when the figure is part of a larger notebook UI.  We could have a "Save" button in the UI, but this is more elegant and in keeping with the rest of the backends' toolbars.

**Comment by blink1073** [comment]
New method: use the HTML5 `input` tag, so that when the user clicks the button it brings up a file selector dialog.  This could be used for the webagg backend as well.

**Comment by blink1073** [comment]
We can then push the `save` event back to the Python side, and use `canvas.print_figure`.

**Comment by mdboom** [comment]
Cool.  At least speaking for myself, we're always looking for more web/HTML5 development expertise, so feel free to fix up anything else you find that could be done better.

**Comment by blink1073** [comment]
@mdboom, I'm a beginner at JS, but thanks for the vote of confidence!

**Comment by tacaswell** [comment]
How do we deal with converting the figure to a png when the figure gets killed?  Presumably we could just use that method to serve up a png? [disclaimer, making this up as I go]

**Comment by blink1073** [comment]
Shucks, the `input` tag can only select files *on* the user's file system.  I'm still puzzling out how select a new file.

**Comment by blink1073** [comment]
Success!

**Comment by blink1073** [comment]
When you click the download button, it opens a new window with the image in the desired type, and you can save it from there.

**Comment by blink1073** [comment]
@tacaswell, I don't follow your question.

**Comment by blink1073** [comment]
Hmm, the only two formats that work are PNG and JPG, and the JPG doesn't look that great (it only shows a white background and the plot line itself).  Should we just output PNG and remove the selector?

**Comment by tacaswell** [comment]
This needs a re-base.

**Comment by blink1073** [comment]
Done.

**Comment by tacaswell** [comment]
Is there some reason the drop-down didn't get ported over to the nbagg ui?  It seems useful to be able save vector graphics from the notebook.

On the other hand, users have access to `*.savefig('...pdf')` so not sure how compelling that use-case is as compared to the web-agg use-case.

**Comment by tacaswell** [comment]
and everything here works as advertised for me.

**Comment by blink1073** [comment]
At first I tried using [toDataURL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement.toDataURL), but for all but JPEG it ended up falling back on PNG.  With JPEG, it rendered the transparent background as black, obscuring the spines.

**Comment by pelson** [comment]
@tacaswell - do you have some git foo which allows you to cherry-pick a branch onto v1.4.x?

**Comment by tacaswell** [comment]
Git co v1.4.x
Git cherry-pick hash_of_merge -m 1

Take a look that it added just one commit past upstream v1.4.x with all of
the changes squashed and then push to upstream.

That should probably be documented some place

**Comment by tacaswell** [comment]
back-ported as 408fed6e53d381377b4cbd6f068ff4dae423cec4

**Comment by pelson** [comment]
Seems to have been merged into v1.4.x with 408fed6. Wasn't me though... @tacaswell - did you do it?

**Comment by tacaswell** [comment]
Yes

**Pull request merged**
