### PR TITLE
When linking against libpng/zlib on Windows, use upstream lib names.

### PR DESCRIPTION
**Pull request by anntzer**
See changelog for details.

Should fix the symptoms (failure to link png.lib) of #13016 (@rth, can you confirm?).

Implements part of #9693; the static/dynamic switch proposed there could be added later.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
We should also check if this will have an impact on conda-forge

**Comment by anntzer** [comment]
Likely also needed for https://github.com/matplotlib/matplotlib/pull/13077 unless one wants to also write the manual renaming for azure.

**Comment by tacaswell** [comment]
I'm going to close this as it has been folded into #13077

**Comment by anntzer** [comment]
Reopening as #13077 doesn't appear close to being merged and the nonstandard names are still confusing (https://github.com/matplotlib/matplotlib/pull/14355#issuecomment-498717582).

**Comment by timhoffm** [comment]
Not yet merging because the second approval was long ago. @tacaswell is your approval still valid?

**Comment by tacaswell** [comment]
This may conflict with the patches conda applies: https://github.com/conda-forge/matplotlib-feedstock/blob/master/recipe/setupext.patch

**Comment by cgohlke** [comment]
LGTM

**Pull request merged**
