### PR TITLE
Move from @cbook.deprecated to @_api.deprecated

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Follow-up to #18657, which moved the functions. This PR now starts to move their usages in our code base.

### CODE REVIEW

**Comment by QuLogic** [comment]
Mostly looking okay, but you have many missing references.

**Comment by QuLogic** [comment]
Actually, no, `_api` does not expose any of the deprecation machinery directly like that.

**Comment by brunobeltran** [comment]
Why not just `from _api.deprecation import deprecated`? Instead of just making `_api` the new catch-all name space for helper functions?

**Comment by timhoffm** [comment]
I'm a bit paranoid by now concerning semi-public API. Importing `deprecated` leaks the name into the module namespace. -  I know that other imports do that as well, but we can prevent that in this case quite easily. 

Also, I don't want to import the specific functions (check_in_List, warn_deprecated, make_keyword_only, rename_parameter, ...) and remove the imports when they expire. That's a big back and forth adapting of the imports. One could even consider inlining the deprecation module into _api, but for now I'd leave it as a sub module.

Furthermore, I like the _api prefix indicating the context. For example it makes it immediately clear, that `_api.check_in_list()` is some sort of standard function within our framework and not only a local helper function `check_in_list()`.

**Review by brunobeltran — APPROVED** [review]
I'm convinced by the argument that everything should live under `_api`. At that point, I would honestly prefer if everything was just inlined into `_api` directly (especially since I'm about to move one random function into `_api.deprecation` just to avoid circular imports (#18817)), but it doesn't seem like doing it this way for now fundamentally hurts our ability to do differently moving forward so...it'd be good to get this in.

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
