### PR TITLE
Fix pgf tests with TeXLive 2022

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Apparently, the `Micro Sign` glyph in text is now upright and not italic, as `\mu` is in math mode.

~~Unfortunately, I don't think CI is new enough to trigger this, so this PR is really just bookkeeping to have something to remember when that changes.~~

## PR Checklist

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] New plotting related features are documented with examples.

**Release Notes**
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [n/a] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by anntzer** [comment]
Perhaps change create_figure to no longer include a `\mu` in the text in order to hopefully keep the baseline more robust against texlive version changes?
(If you do so I would also replace the `\usepackage{sfmath}` in test_rcupdate by perhaps something slightly more common, as I'm not sure sfmath is installed by default (I ran into it not being installed a couple of times)).

**Comment by QuLogic** [comment]
That's also a possibility; I wasn't sure if we used that specific text/package for any good testing reason.

**Comment by QuLogic** [comment]
It appears that replacing with Unicode Greek alpha does not work directly, as that glyph does not seem to be available in all the cases that the tests run. Looking at the text again, it's actually 'MICRO SIGN' (U+00B5), not the Greek letter mu. Trying the latter actually ends up with an empty glyph as well. So this is specifically a character from the Latin-1 Supplement block, which ü and ° already cover. We could change it to 'PLUS-MINUS SIGN' (which would probably not italicize) or perhaps remove entirely.

**Comment by QuLogic** [comment]
I've changed it to `Section Sign` to keep a similar text dimension, and confirmed that it works on Fedora 38 (texlive 2022) and Ubuntu 22.04 (texlive 2021).

**Review by ksunden — APPROVED** [review]

**Pull request merged**
