### PR TITLE
Tweek tol for test_hist_steplog to fix tests on appveyor

### PR DESCRIPTION
**Pull request by jenshnielsen**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
This is against master to confirm that it fixes appveyor but should probably be backported to 2.x

**Comment by jenshnielsen** [comment]
Ok this finally passed on appveyor. I suggest merging asap to unbreak appveyor on master

**Comment by QuLogic** [comment]
Seems like this needs a backport still.

**Comment by tacaswell** [comment]
thanks for the reminder!

**Comment by tacaswell** [comment]
backported to v2.x as 6103dd6

**Pull request merged**
