### PR TITLE
Make examples that load npy files with datetime(objects) py3 compatible

### PR DESCRIPTION
**Pull request by jenshnielsen**
Requires np 1.10 to work under py3 because encoding wasn't added until 1.10

### CODE REVIEW

**Comment by jenshnielsen** [comment]
There is still a few related failures in recipes.rst

**Comment by mdboom** [comment]
:+1:

**Comment by jenshnielsen** [comment]
Fixed the examples in recipes the same way. With this the docs finally build with all examples under python3

**Comment by mdboom** [comment]
That's awesome.  :clap:

Though, just for reference of someone else coming by, I did run into an unrelated glitch building the docs in Python 3 on Mac today.  See #5295

**Pull request merged**
