### PR TITLE
Bug fix and general touch ups for hist3d_demo example (#1702)

### PR DESCRIPTION
**Pull request by discardthree**
- Fixes bug #1702 by using 'F' when flattening xpos, ypos
- Makes the bin ranges fixed, also as discussed on #1702
- Adds a docstring (as per MEP12) plus some clarifying comments

### CODE REVIEW

**Comment by discardthree** [comment]
I can see that the build has failed, but I've looked at the logs and I'm not sure how the failures are actually related to my changes.  I'd appreciate some help understanding this.  Thanks in advance!

**Comment by jenshnielsen** [comment]
The failure on Travis is intermittent and not related to your changes. I have restarted the particular test. I suspect the same is the case on appveyor

**Comment by jenshnielsen** [comment]
Appveyor is failing due to #5950 since conda have switched to Numpy 1.11

**Comment by discardthree** [comment]
Okay, great, thanks!  I see Travis passed this time. :)

**Comment by tacaswell** [comment]
Thanks!  

I believe this is your first mpl contribution, congrats and hopefully we will see you again :smile:

**Comment by discardthree** [comment]
Thanks!  I've been looking for something approachable to contribute to, and now that I've discovered MEP12 I'm thinking of sticking around here and work on cleaning up some of the other examples.  :blush:

**Comment by tacaswell** [comment]
Great!  Good documentation is very important and an area where mpl could definitely be doing much better.  Any work on the examples is very appreciated.

**Comment by tacaswell** [comment]
backported to v1.5.x as a8851dd

**Pull request merged**
