### PR TITLE
Backport PR #21663 on branch v3.5.x (Use standard subplot window in macosx backend)

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Backport PR #21663 on branch v3.5.x (Use standard subplot window in macosx backend)

### CODE REVIEW

**Comment by QuLogic** [comment]
@greglucas can you check there's no issue with the backport?

**Comment by greglucas** [comment]
The scaling all looks good to me jumping between the monitors, but now there is another issue of the updates not triggering a draw. On 3.5.0 when I move the slider, the window immediately updates the draw. Here, the slider moves, but there is no visual response. But, if I go into pan mode and click on the plot, the canvas is updated with the proper scaling I had selected.

Note that on 3.5.0, it is not flawless for me, I can slide the bar around for a bit and then all of a sudden it freezes on me and interactivity is gone. So there is something odd going on there too.

**Comment by QuLogic** [comment]
Could be related to the `flush_events`-type stuff?

Anyway, I'll merge this now as that seems something else.

**Comment by greglucas** [comment]
:+1: Yes, I think so.

**Pull request merged**
