### PR TITLE
Doc: Move search field into nav bar

### LINKED ISSUE #15717: Move search field into nav bar
I propose to move the search bar up into into the new nav bar. Similar to this:

grafik

- It's more reasonably placed closer to the other navigation elements. The placement in the side bar historically comes from the sphinx theme.
- This also declutters the sidebar.

Attn. @dorafc, you might want to consider this for the new front page layout. I could hack this together, but for sure you know better how to lay this out properly.

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Closes #15717. See there for the motivation.

I'm not a HTML/CSS expert, so not sure the code is the best one can do, but it renders as I would like it to :smile: .

[Built docs](https://27361-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/index.html)

Before:
grafik

After:
grafik

### CODE REVIEW

**Comment by story645** [comment]
I'm a fan of this, but definitely gonna defer to @dorafc

**Comment by timhoffm** [comment]
The whole page is not responsive. It's wider than typical mobile screens. Therefore, you have to scroll horizontally. This is not getting better or worse by moving the search field.

[Link to built docs](https://27361-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/index.html)

**Comment by story645** [comment]
Yes I agree responsiveness is for a seperate PR, but what I'm wondering is when/if we ever do responsiveness, if search would still make sense in the nav bar. Basically I'm worried search would be moved only to be moved back & that might be disorienting for users. Agree with you though on side panel being a good place for announcements.

**Comment by timhoffm** [comment]
I'm not concerned that we would have to move the search field back for responsiveness. With responsive designs, you typically fold the navbar and expand it on demand. It's common to take the search bar along. Take https://seaborn.pydata.org/ for example:

Menu folded:
grafik

Menu unfolded:
grafik

**Comment by dorafc** [comment]
Apologies for somewhat disappearing - I started a job search and its taken up more time / emotional bandwidth than I anticipated. I think moving the search bar into the nav bar is fine idea. It's still pretty close to where it is in the current site, which should help if anyone is surprised to not see the search bar where they anticipate. Moving the search bar into the nav is probably better for future responsiveness. As Tim pointed out, search fields do often get moved into expandable menus on mobile devices, and it would make more sense to keep the nav here than in the sidebar when things shrink down.

Code looks fine too.

**Comment by timhoffm** [comment]
I don't think it's necessary to backport to 3.1.1-doc. There are some other issues with the nav bar in there, which prevents a clean backport.

**Pull request merged**
