### PR TITLE
Merge branch v3.9.x into main 

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

As in title.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
Also marked 3.9.2 as the stable version so that the banner on the website is corrected.

**Comment by QuLogic** [comment]
I don't know what's up with wheels, but that's not super important to getting this in at the moment.

**Review by tacaswell — APPROVED** [review]

**Comment by tacaswell** [comment]
We should re-consider if we want to keep the brew ENVs as it is not clear if they are doing what we think they are doing.

**Comment by tacaswell** [comment]
of all of these commits I think we only want to backport 6c04a4 and c88d13 ?

**Pull request merged**
