### PR TITLE
Update INSTALL.rst.

### PR DESCRIPTION
**Pull request by anntzer**
- Dedent the overindented bullet lists (compare e.g. the indentations at
  https://matplotlib.org/users/installing.html#test-data and at
  https://matplotlib.org/users/installing.html#linux-using-your-package-manager).
- Add a link for FreeType.
- Suggest `python -mpytest` instead of `pytest` to run the tests for the
  same reason as `python -mpip` is suggested (avoids invoking an
  out-of-venv pytest).
- Clarify the situation regarding pycairo/cairocffi (the former works
  for everything and is a requirement for gtk3 (unless you're using pgi,
  but in that case you're mostly on your own)).

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I've merged, but you may want to check that my rebase fix was correct....

**Comment by anntzer** [comment]
Can you point to the rebase commit?

**Comment by jklymak** [comment]
Sorry did w the web interface so I guess it makes it as part of the merge commit?  I think I did it right....

**Comment by anntzer** [comment]
Looks fine to me...

**Pull request merged**
