### PR TITLE
changed paths in kwdocs

### PR DESCRIPTION
**Pull request by fredrik-1**
The links to the axes properties where not rendered correctly in the kwdoc table because `axes._base` and `axes._axes` are not included in the documentation. This is a simple solution that change the paths.

edit: So the changes is in the rendered docstrings when `docstring.dedent_interpd` is used with `%(Axes)s`  (and maybe in some other docstrings)

- [ ] Has Pytest style unit tests
- [x] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I'm having trouble telling where and what the change is supposed to be.  Can you give more detail, pref with a link to https://circleci.com/gh/matplotlib/matplotlib/10434/artifacts/0//home/circleci/project/doc/build/html/index.html

**Comment by fredrik-1** [comment]
I am not sure if it is rendered in the docs at the moment but it probably should be in for example `axes._base._AxesBase.__init__`. (which also be the docstring in `axes.Axes` with my other PR) or in for example `Figure.add_subplot`

The difference is  that `artist.kwdoc(matplotlib.axes.Axes)` with `rcParams['docstring.hardcopy]=True` now renders to lines like
``':meth:`yticklabels <matplotlib.axes.Axes.set_yticklabels>`                     List[str]' ``       
which results in correct links to the documentation compared to the lines before:    
``':meth:`yticklabels <matplotlib.axes._base._AxesBase.set_yticklabels>`                     List[str]' ``    
which don't link to a  place in the documentation.

**Comment by fredrik-1** [comment]
I added some docstrings

**Comment by fredrik-1** [comment]
Many links in the kwargs list [in](https://10525-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_subplot) don't work. This PR fix those links.

**Comment by fredrik-1** [comment]
I see now that the kwarg list was actually included in Figure.gca [New](https://10434-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.gca) [old](https://10525-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.gca)

**Comment by fredrik-1** [comment]
Could someone review this? This pr make the links in the kwarg lists in for [example](https://10798-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/api/_as_gen/matplotlib.pyplot.subplot.html#matplotlib.pyplot.subplot) work.

**Comment by timhoffm** [comment]
I've checked against master and did not see any change in the links. Which ones exactly do not work on master?

**Comment by fredrik-1** [comment]
[axes](https://matplotlib.org/devdocs/api/axes_api.html#module-matplotlib.axes)

For example adjustable in the kwarglist should be a link and this pr fix that.

**Comment by timhoffm** [comment]
The bold parameter list is a regression from #11495. I'll detail what's going on and fix it in a separate PR. You don't have to worry about that here.

**Comment by NelleV** [comment]
Thanks @fredrik-1 !

(quick note--@timhoffm I don't know if you are aware that for documentation pull request, only one core dev is required to approve the PR before merging)

**Comment by jklymak** [comment]
@NelleV I think that’s true for bare edits of the docs.  This was an actual code change for how the docs are handled.

**Comment by NelleV** [comment]
Yeah, good point.

**Pull request merged**
