### PR TITLE
Deprecate support for dash-offset = None.

### PR DESCRIPTION
**Pull request by anntzer**
## PR Summary

e.g. `plot([1, 2], ls=(None, (4, 4)))` which was previously a synonym
for `plot([1, 2], ls=(0, (4, 4)))` which means "dash-pattern of
4pt-long dashes separated by 4pt spaces, with an offset of 0pt at
start".

Passing None instead of 0 was already not (likely, never) supported for
pdf, ps, or svg (an exception is raised at savefig() time for ps/svg, an
invalid pdf is generated).  There isn't much of a point in supporting
None (this also makes e.g. mplcairo more complex because of static
typing in C++ extensions), so just deprecate it.

Goes on top of #15827.
Edit: closes https://github.com/matplotlib/matplotlib/issues/14996, which is basically the issue described here.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Could we normalize `None` as input to 0 instead?

The failures look real, but did not dig into them....

**Comment by anntzer** [comment]
The failures are real, need to look into it.
I think the (small) cleanup to Line2D from not normalizing (allowing to remove a few checks for None) is also nice to have.  Again note that this has (likely) never worked for pdf/ps/svg so I doubt there are many people who rely on it...

**Comment by anntzer** [comment]
figured out the failure, now fixed, should be good to go.

**Comment by anntzer** [comment]
edited accordingly, and rebased.

**Pull request merged**
