### PR TITLE
Add CPython 3.9 wheels.

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Note, this does mean that our Python 3.9 wheels will be built against NumPy 1.19, because there are no older wheels available.

## PR Checklist

- [n/a] Has pytest style unit tests (and `pytest` passes).
- [n/a] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [n/a] New features are documented, with examples if plot related.
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [n/a] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by tacaswell** [comment]
Building against np 1.19 does leave a bit of a support gap where someone could have installed from source an older numpy and then pip installed our wheel, but they always have the fall-back of building mpl from source as well.

**Comment by jarrodmillman** [comment]
Any idea when you will release 3.9 wheels?  I am hoping to release NetworkX 2.6 in December.  We've recently made Matplotlib a default dependency (previously it was optional).  We plan to support 3.9 with our 2.6 release.  Matplotlib wheels for 3.9 is our last task before NetworkX officially support 3.9.

No rush, just want your rough estimate so I can have a better handle on our release plans.

**Comment by orome** [comment]
> Any idea when you will release 3.9 wheels?
> [...]
> No rush, just want your rough estimate so I can have a better handle on our release plans.

It would indeed be great to know this so we can plan our releases.
Is there a roadmap somewhere that would indicate when Matplotlib will work with 3.9?

**Comment by tacaswell** [comment]
"Soon", definitely before December. 

I do want to stress that Matplotlib _works_ with py39, it is the packaging that is not done.

**Comment by orome** [comment]
> "Soon", definitely before December.

Excellent!

> I do want to stress that Matplotlib _works_ with py39, it is the packaging that is not done.

Yes what "works" depends on use case of course. My focus was on something that worked with the vast majority of package consumers (esp. consumers of packages for which Matplotlib is just a dependency), for whom "works" means `pip install` works.

**Comment by cbrnr** [comment]
It seems like this should be ready because all tests pass - looking forward to finally moving to Python 3.9! Big thanks for providing this great package :+1:!

**Review by timhoffm — APPROVED** [review]

**Comment by jklymak** [comment]
I don't know if the tests passing means anything.  @QuLogic any hints for how we can tell if this is working?

**Comment by QuLogic** [comment]
These would only run on the main branches, not PRs; here is a (somewhat older) build on [master](https://github.com/QuLogic/matplotlib/actions/runs/335123526) and one on [v3.3.x](https://github.com/QuLogic/matplotlib/actions/runs/354780201).

**Pull request merged**
