### PR TITLE
Added boxplot rcparams to dark_background.mplstyle

### PR DESCRIPTION
**Pull request by manan2501**
## PR Summary
I have added boxplot rcparams to dark_background.mplstyle as suggested by @tacaswell to make boxes visible in dark_background style which will solve issue #15675 .

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by QuLogic** [comment]
Why did you close this?

**Comment by manan2501** [comment]
> Why did you close this?
I have installed matplotlib according to this => https://matplotlib.org/3.1.1/users/installing.html#installing-from-source
And I was unable to observe changes made in code. So, I was not sure that this would work ( I even tried to change the value of colors ).
That is the reason I closed this PR. 
( Can you help me to test changes made in code, If I have installed matplotlib incorrectly then please guid me if possible. )

**Comment by manan2501** [comment]
> Why did you close this?

I had installed matplotlib according to this => https://matplotlib.org/3.1.1/users/installing.html#installing-from-source
But, after making changes to mplstyle file, they were not observed while testing (Even changing the value of colors were not observed). So, I was not sure that this would work. That is why I closed this PR.
(If possible guid me to some doc which can help me in the testing part. Because I will need it for sure in the future.)

**Comment by QuLogic** [comment]
See the [developer's guide](https://matplotlib.org/3.1.1/devel/index.html). If you have trouble, try asking on [Discourse](https://discourse.matplotlib.org/) or [Gitter](https://gitter.im/matplotlib/matplotlib), which are better places for this than a GitHub issue.

**Pull request closed without merging**
