### PR TITLE
Cleanup: remove unused variable/assignment/expression and debug comments

### PR DESCRIPTION
**Pull request by Carreau**
Apologies but my linter just annoy me enough every time I come by this
file to send a PR.

The comments seemed to be only experiment from 2009 which ended up with current code.

### CODE REVIEW

**Comment by tacaswell** [comment]
@Carreau Can I start putting PRs into IPython to strip all of your trailing white space :smiling_imp:

**Comment by Carreau** [comment]
> @Carreau Can I start putting PRs into IPython to strip all of your trailing white space 😈

I'm can try allowing you 1 function/class per week. If you want more we can try to trade :-)

**Comment by NelleV** [comment]
I'll merge your PR against one or two coffee :innocent:

**Comment by Carreau** [comment]
> I'll merge your PR against one or two coffee 😇

Help yourself at BIDS coffee machine :-) But I'll gladly buy you coffee.

**Pull request merged**
