### PR TITLE
Deprecate in testing.decorators 

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

`CleanupUnitTest` and the `cleanup` decorator are not used. 

`check_freetype_version` is only used inside the file so makes sense to make private.

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [x] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by tacaswell** [comment]
> Maybe it should be deprecated first? 

Yes, we should deprecate it and see who complains.  Our users are by and large very clever and find un-documented things in the code base to use regularly.   I could believe that someone found this and is using it in their tests of a downstream library.

> API change notes?

Yes, definitely needs a note with the advise of "vendor this and the private function it wraps into your code if you need it".

**Comment by oscargus** [comment]
Thanks!

I've deprecated a few more things that I do no think is used. Will add notice etc when I realize the consequence (e.g. that I missed that `@cleanup` actually was used...).

**Comment by QuLogic** [comment]
The `cleanup` decorator is currently used in Cartopy, though I think this may be redundant with its pytest fixture.

**Review by timhoffm — APPROVED** [review]

**Comment by oscargus** [comment]
For info: It seems like Cartopy does not really need the `@cleanup` decorator, see https://github.com/SciTools/cartopy/issues/2020 and https://github.com/SciTools/cartopy/issues/2023, so it should be OK to deprecate this from that aspect.

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
