### PR TITLE
DOC: Add Date Tick Locators and Formatters example

### LINKED ISSUE #17283: Create Date Formatter/Locator Reference
Examples of using the date formatters and locators is currently scattered haphazardly across the docs:
* [Dates documentation](https://matplotlib.org/api/dates_api.html?highlight=dates#module-matplotlib.dates)
* [Concise Date Formatter](https://matplotlib.org/gallery/ticks_and_spines/date_concise_formatter.html#sphx-glr-gallery-ticks-and-spines-date-concise-formatter-py)
* [Date tick labels](https://matplotlib.org/gallery/text_labels_and_annotations/date.html#sphx-glr-gallery-text-labels-and-annotations-date-py) 
* [Date Demo RRule](https://matplotlib.org/gallery/ticks_and_spines/date_demo_rrule.html#sphx-glr-gallery-ticks-and-spines-date-demo-rrule-py)
* [Date Index Formatter](https://matplotlib.org/gallery/ticks_and_spines/date_index_formatter2.html#sphx-glr-gallery-ticks-and-spines-date-index-formatter2-py)
* [Date Demo Convert](https://matplotlib.org/gallery/ticks_and_spines/date_demo_convert.html#sphx-glr-gallery-ticks-and-spines-date-demo-convert-py)

There currently isn't a good reference doc for the date formatters and locators.  It would be useful to have one example that's structurally/stylistically a combination of:
* [Locators Example](https://matplotlib.org/gallery/ticks_and_spines/tick-locators.html#sphx-glr-gallery-ticks-and-spines-tick-locators-py)
* [Formatters Example](https://matplotlib.org/gallery/ticks_and_spines/tick-formatters.html#sphx-glr-gallery-ticks-and-spines-tick-formatters-py)

### PR DESCRIPTION
**Pull request by StefRe**
## PR Summary
Add Date Tick Locators and Formatters example. Closes #17283.  

I noticed that https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L982-L983 has no docstring and hence can't be referred to in the documentation (see `admonition:: References`; the same pertains to https://github.com/matplotlib/matplotlib/blob/2ccc67f89dca929d1acfeed9ebeb3c11f1c3a52b/lib/matplotlib/dates.py#L144).

grafik
<br><br>  

grafik

## PR Checklist

**Tests and Styling**
- [N/A] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by dstansby — COMMENTED** [review]
This looks great! Using `eval()` seems a bit odd to me - is there a reason that `locators` and `formatters` can't contain the actual locator/formatter instances instead of their eval strings?

**Comment by StefRe** [comment]
@dstansby the `eval` is just to prevent redundant definition of the string 'AutoDateLocator(maxticks=8)' **and** the locator itself, i.e. it's meant as a shortcut of writing e.g.
```
locators = [
    ('AutoDateLocator(maxticks=8)', AutoDateLocator(maxticks=8), '2003-02-01', '%Y-%m'),
    ...

```
Maybe using `eval` is not really best practice but I reduces the possibility of mistakes/inconsistencies between the code and the text in this case.

**Comment by jklymak** [comment]
I guess I but the argument that the `eval` is useful here...

**Comment by story645** [comment]
> Maybe using `eval` is not really best practice but it reduces the possibility of mistakes/inconsistencies between the code and the text in this case.

Would a repr on the objects print anything different from the eval?

**Comment by StefRe** [comment]
@story645 `repr(AutoDateLocator(maxticks=8))` gives `'<matplotlib.dates.AutoDateLocator object at 0x000001CE4F687CA0>'`.

Defining nice `repr`s wouldn't be enough, however, as we also need the arguments of the function calls.

**Comment by story645** [comment]
>Defining nice reprs wouldn't be enough, however, as we also need the arguments of the function calls.

Why couldn't those be in the repr?

**Comment by StefRe** [comment]
@story645  
I only have very basic knowledge of python in this respect, maybe I'm completely wrong:

When I try `AutoDateLocator.__repr__ = lambda self: f'AutodateLocator(maxticks={self.maxticks})'` then `repr(AutoDateLocator(maxticks=8))` returns `'AutodateLocator(maxticks={0: 8, 1: 8, 3: 8, 4: 8, 5: 8, 6: 8, 7: 8})'`, i.e. the class variable `maxticks`. I don't know how to get the value passed in during the function call. But even if this is possible, I find defining all the `repr` rather verbose and a bit hacky as compared to a simple `eval`.

**Comment by dstansby** [comment]
In an ideal world we would define sensible `__repr__`s on each of the locators/formatters so they could be used - I think that's a stretch goal, and this PR is worth considering regardless of that.

**Review by dstansby — APPROVED** [review]

**Comment by jklymak** [comment]
Thanks @StefRe for your very helpful contributions!

**Comment by StefRe** [comment]
@jklymak Thanks!  
What about the `rrulewrapper` issue I mentioned at the [very beginning](https://github.com/matplotlib/matplotlib/pull/21874#issue-1072147872)? Open a new issue for this? Should I (for the time being) remove the reference to `rrulewrapper` as there's no link:
grafik

**Comment by jklymak** [comment]
Sure, open an issue.  Seems the solution is to add a docstring to rrulewrapper if it is public API...

**Pull request merged**
