### PR TITLE
Add new external resource: Python Graph Gallery

### PR DESCRIPTION
**Pull request by holtzy**
Hi,

I've recently been invited to write this [blogpost](https://matplotlib.org/matplotblog/posts/python-graph-gallery.com/) on the matplotblog page.

After some discussion with the matplotlib twitter account maintainer it sounds like the python graph gallery could be a great fit for your external resources page, so here is the PR.

Please tell me if that looks reasonable to you!

Best,

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [ ] New features are documented, with examples if plot related.
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by story645 — APPROVED** [review]

**Comment by story645** [comment]
Thanks for the pull request!

**Comment by holtzy** [comment]
Thanks for the approval @story645 🙏 

I was hoping this new link would appear on the external resources webpage here:
https://matplotlib.org/stable/resources/index.html

But it does not look to be the case. Did I add the link at the wrong location 🤔 

Thanks!

**Comment by story645** [comment]
You're all good, but doc changes go to our devdocs and won't be live on the current homepage until the next release (3.5). You can see it here https://matplotlib.org/devdocs/resources/index.html?highlight=resources

**Comment by holtzy** [comment]
Oh I see. All good then, thanks so much!

**Comment by holtzy** [comment]
Hi @story645 ,
I see the v3.5 is out, so I was wondering if the link was about to be updated too? 🤔

**Comment by tacaswell** [comment]
The 3.5 docs are now at `/stable` and the link you added is there.

**Comment by holtzy** [comment]
Nice thanks!

**Pull request merged**
