### PR TITLE
Mention keyboard modifiers in toolbar tooltip texts.

### PR DESCRIPTION
**Pull request by anntzer**
Otherwise the feature is a bit obscure...  Closes https://github.com/matplotlib/matplotlib/issues/17658.
(The newline in the tooltip works at least with qt/wx/tk/gtk (but wx needs #17686 too), can't test macos locally.)

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
I love this feature, and didn't know it existed.  But, ugh, you sure don't want to use those modifiers in a Jupiter notebook.  `x` cuts the current cell, even clearly using the plot GUI.  Not even sure where to report that or what to do about it, other than change my rcParam...

**Comment by anntzer** [comment]
Let's see whether I can manage to make the osx backend also use the tooltips from the base class...

**Comment by jklymak** [comment]
I don't think so:

```
  File "testSimple.py", line 5, in <module>
    fig, ax = plt.subplots()
  File "/Users/jklymak/matplotlib/lib/matplotlib/cbook/deprecation.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 1270, in subplots
    fig = figure(**fig_kw)
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 670, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/Users/jklymak/matplotlib/lib/matplotlib/pyplot.py", line 298, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backend_bases.py", line 3483, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backend_bases.py", line 3489, in new_figure_manager_given_figure
    manager = cls.FigureManager(canvas, num)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_macosx.py", line 98, in __init__
    self.toolbar = NavigationToolbar2Mac(canvas)
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_macosx.py", line 120, in __init__
    tuple(str(data_path / image_name) + ".pdf"
  File "/Users/jklymak/matplotlib/lib/matplotlib/backends/backend_macosx.py", line 120, in <genexpr>
    tuple(str(data_path / image_name) + ".pdf"
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
```

**Comment by anntzer** [comment]
Well I can't actually test macosx code locally, I was just going to abuse CI (which does test instantiating a macosx window) to iterate until either it works or I give up...

**Comment by jklymak** [comment]
ha ha.  New version segfaults.

**Comment by anntzer** [comment]
Did you recompile?  CI seems happy.  (I would be amazed to have been able to write the extension code right on the first try, though...)

**Comment by jklymak** [comment]
Yes, I did recompile after cleaning out the build directory.  Not sure what is wrong.

**Comment by jklymak** [comment]
Travis seg faults as well...

**Comment by anntzer** [comment]
Yup, missed a change...

**Comment by jklymak** [comment]
Works!

**Pull request merged**
