### PR TITLE
[MRG] Make hatch colour an rcParam.

### LINKED ISSUE #7166: Hatching in legends is broken
Compare http://matplotlib.org/2.0.0b4/examples/api/filled_step.html (2.0.0b4)

image

and 

http://matplotlib.org/examples/api/filled_step.html (1.5.3)

image

### PR DESCRIPTION
**Pull request by QuLogic**
This turned out easier than I expected because I just had to follow the same work as #6198. As with `hatch.linewidth`, there is no API to do this, only the rcParam.

Not sure if I should add an explicit test, some other tests kind of implicitly test this stuff (as seen from the updated images.)

Fixes #7166. Also, partially implements #7059.

### CODE REVIEW

**Comment by efiring** [comment]
You could add a test based on a simplified version of the example in #7166, so that the legend would be tested.

**Comment by QuLogic** [comment]
I added a test based on @dopplershift's shortened test in #7166, which I think basically covers the path hit by legends.

Interestingly, it isn't broken in PDF or SVG because they determine the colour in some other way somehow. In fact, there's even a test `test_hatching_legend` for PDF in `test_backend_pdf.py`...

**Comment by QuLogic** [comment]
Hmm, just realized the PDF is broken when using `Rectangle` without an explicit edge colour, so I must have missed one more place.

**Comment by QuLogic** [comment]
On closer inspection, that may be a bug in evince, as it appears fine in pdf.js, inkscape and convert.

**Pull request merged**
