### PR TITLE
CI: pin 1.5.x cycler to 0.9.0

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by jenshnielsen** [comment]
I assume this is only for making sure we test 0.9.0? We need to be careful when merging this forward to making sure this doesn't land on 2.x

**Comment by tacaswell** [comment]
There are a bunch of new features in 0.10 that I think we do not want to
leak down to 1.5 to be conservative about version requirements.

**Comment by jenshnielsen** [comment]
That absolutely makes sense to me

**Comment by tacaswell** [comment]
When I did the merge cascade up I made sure to not move this change over

https://github.com/matplotlib/matplotlib/commit/04dce81d226385f7b3808199c6950512503e847f

I think that means future merges will also not try to move this change.

**Comment by jenshnielsen** [comment]
Yes great thats my understanding too.

**Pull request merged**
