### PR TITLE
Stackplot weighted_wiggle zero-area fix

### PR DESCRIPTION
**Pull request by egpbos**
See #6313.

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you force-push just the first commit (with out the merge from master)?

Can you also add an image test that exercises this condition?  It might be best to modify the test data in `test_axes.test_stackplot_baseline` and update the expected images.

Other wise :+1:

**Comment by egpbos** [comment]
Force push done.

**Comment by tacaswell** [comment]
Will you have time to add a test for this?

**Comment by egpbos** [comment]
I'm trying, but I'm running on OSX in a Conda virtual environment, so having issues with that. [The frameworkpython method](http://matplotlib.org/faq/virtualenv_faq.html#pythonhome-script) doesn't seem to work for me, and I don't have *that* much time, unfortunately. An ideas on getting my venv working?

**Comment by egpbos** [comment]
Just to be sure this makes sense, what I'd do is simply add 
```python
    d[50,:] = 0  # test for fixed weighted wiggle (issue #6313)
```
after line 1394 in matplotlib/tests/test_axis.py. To generate the baseline image, I have [this script](https://gist.github.com/egpbos/2b7f9c2dfbd83bbdb2f977ea77f3e189), but that's the one that won't run in my venv, so that's where I'm stuck.

**Comment by efiring** [comment]
Others might have better methods, but here is what I do to develop mpl from within a conda environment on OSX:
1) Use conda to make a test environment with the desired python version, and use conda to install matplotlib in it.  
2) Use conda to *uninstall* matplotlib.
3) In my github clone of matplotlib, make a feature branch, and make the desired changes to it.
4) In the root of that clone directory, 'pip install .'
5) In a directory somewhere away from the cloned directory, to run your particular modified test, run:
 [path_to_matplotlib]/tests.py matplotlib.tests.test_axis.test_stackplot_baseline
6) If everything worked as desired, copy the result images from the new result_images subdirectory of your testing directory to the appropriate baseline_images location in the repo, git commit everything, and push.  If it didn't work, then modify the code, run 'pip uninstall matplotlib', and go back to 4.

**Comment by egpbos** [comment]
@efiring Awesome, that did the trick, thanks! Well, almost, I had to combine it with [this pythonw/python.app tip](https://github.com/conda/conda/issues/607). Perhaps an idea to put this method in the documentation? I assume steps 1 and 2 are to automatically install dependencies, right? Anyway, will try to generate the test images using this setup asap.

**Comment by egpbos** [comment]
Ok, forgot to add `matplotlib.style.use('classic')` to the image generation script, that seems to fix the tests. By the way, is there a developers guide with info like this?

**Comment by egpbos** [comment]
@tacaswell: matplotlib.tests.test_mlab.rec2txt_testcase is failing in AppVeyor. Does that have anything to do with stackplot / this PR?

**Comment by tacaswell** [comment]
No, that is a separate issue.

**Comment by tacaswell** [comment]
Thanks!  I think this is your first contribution to the mpl source.  Congratulations and hope we hear from you again.

Backported to v2.x as 102872a

**Pull request merged**
