### PR TITLE
Add HiDPI-related config for mathmpl

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Namely, `fontsize`, and `srcset`. We need these for our new theme, which uses 11pt fonts instead of 10pt, and to match the gallery that provides 2x images.

## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [x] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [n/a] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Comment by jklymak** [comment]
Maybe not fair to ask you to do this, but I had no idea `:mathmpl:` existed, and I found no documentation as to what it supposed to do, in particular in the source file.  Can this get _some_ documentation?

**Comment by QuLogic** [comment]
i think it basically exists to create the examples in the docs for what mathtext does. Most external uses should probably use the [Sphinx math extensions](https://www.sphinx-doc.org/en/master/usage/extensions/math.html).

**Comment by anntzer** [comment]
I think we should deprecate it for general use and move it to docs/sphinxext (perhaps not as part of this PR).

**Comment by QuLogic** [comment]
Should I bother documenting it if we're going to deprecate it?

**Comment by jklymak** [comment]
I was suggesting just a couple lines at the top of the source, not formal docs..

**Comment by QuLogic** [comment]
I copied the docs out of `plot_directive` (though rather simplified).

**Review by jklymak — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
