### PR TITLE
Fix for issue #698 reconstruction and update

### PR DESCRIPTION
**Pull request by bearstrong**
**NOTE: Due to me horrifically messing up my repository with my previous attempts at re-basing, I've opted to instead recreate the entire PR using a freshly forked repository. Sorry for the slow update, but this should make the entire request much cleaner.**

The old PR can be found here: https://github.com/matplotlib/matplotlib/pull/6081

A simple change that allows for text objects to be rotated by the transformation they have. It works by applying the transformation on another point, slightly skewed in the x direction, and then calculating the angle of the resulting vector and adding a rotation by that angle to the text object during drawing. To prevent breaking all polar/geometric graphs, this is only performed if a new flag: trans_rotate, is set to true for the text object. 

text_rotate_transform_example

```
from matplotlib import patches, transforms
import matplotlib.pyplot as plt
import numpy as np

ax = plt.gca()
theta = np.deg2rad(-57)
S = np.sin(theta)
C = np.cos(theta)
R = transforms.Affine2D(matrix=np.array([[ C, S, 0.5],
                                         [ -S,  C, 0.5],
                                         [ 0,  0, 1.]]))

rect = patches.Rectangle((0, 0), 0.5, 0.005, transform=R + ax.transData, color='r')
text = plt.text(0, 0, 'Transformed text', size=20, transform=R + ax.transData, trans_rotate=True)
ax.add_patch(rect)
plt.show()
```

### CODE REVIEW

**Comment by bearstrong** [comment]
And of course I accidentally PR'd the wrong branch. I'm not sure if this is an issue but I have no problems re-re-submitting the pull request if needs be.

**Comment by WeatherGod** [comment]
Travis failure:
```IOError: 'https://gist.github.com/adrn/6590261/raw' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.```

Why is our unit test system fetching an item from a gist?!

**Comment by tacaswell** [comment]
To test if it _can_ fetch a style from a gist.  We should re-point that to look at a file hosted on mpl.org or one of the styles _in_ the mpl repo.

**Comment by mdboom** [comment]
I'll duplicate my comment from the other PR here: I don't think this is the right approach to this problem as it boils down the very flexible transform system in matplotlib to rotations only.  I'd rather see something built on top of TextPath that applies the transformation in full.

**Comment by tacaswell** [comment]
Closing due to this being quite for over a year and @mdboom 's concerns.

@bearstrong Thank you for your work!  Hopefully we will hear from you again.

**Pull request closed without merging**
