### PR TITLE
Test setp and getp pretty printing

### PR DESCRIPTION
**Pull request by oscargus**
## PR Summary

The string-formatting is a bit of a joke as the lines are long...

## PR Checklist

**Documentation and Tests**
- [ ] Has pytest style unit tests (and `pytest` passes)
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] New plotting related features are documented with examples.

**Release Notes**
- [ ] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [ ] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [ ] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by jklymak** [comment]
This test will need to change everytime Line2D properties change.  Are we OK with that?  Or can you test a subset of the string?  

I had no idea `setp` did this...

**Comment by timhoffm** [comment]
I think it is sufficient to check that it outputs multiple lines in the format `name : description`.

**Comment by jklymak** [comment]
@oscargus is this something you are planning to pursue?

**Comment by oscargus** [comment]
We can drop it. Although I think that we should have high code coverage, it doesn't seem like a general view.

**Pull request closed without merging**
