### PR TITLE
Fixed layouts in the gallery.

### PR DESCRIPTION
**Pull request by tobias-froehlich**
Mainly I have added "tight_layout()"-lines in the example plots.
Some other layout problems are fixed, too.
Still there is the problem that label-ticks are often too close, which might be a general problem of the gallery building.

### CODE REVIEW

**Comment by tacaswell** [comment]
This needs to be rebased on top of current master as it has merge conflicts.

It also needs some sort of meaningful commit message.

**Comment by tobias-froehlich** [comment]
I have solved the merge conflicts by fetching from the official 
repository and merging. Then I have fetched from my fork, then merged, 
and then pushed back to it. Is this the correct way?

However, the last commit has a kind of standard commit message, which I 
cannot change by "git commit --amend" because then I would have to pull 
and push again.

Do I have to do another pull request, or is the old one still valid?



On 10/27/2015 03:01 AM, Thomas A Caswell wrote:
> This needs to be rebased on top of current master as it has merge conflicts.
>
> It also needs some sort of meaningful commit message.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/pull/5318#issuecomment-151343011>.
>

-- 
Tobias Fröhlich
II. Physikalisches Institut, Universität zu Köln Zülpicher Straße 77, 
D-50937 Köln
Tel.: 0221 / 470 - 3574

**Comment by mdboom** [comment]
The best way to keep one of your personal branches up to date with the matplotlib master branch is to rebase.  By convention, I usually keep a git remote called `upstream` that points to the main fork of matplotlib:

```
git remote add upstream https://github.com/matplotlib/matplotlib.git
```

Then, if I've been working on a branch for a while and I want to get the latest changes from upstream:

```
git checkout my-local-branch
git fetch upstream
git rebase upstream/master
```

This is described in greater detail here: http://matplotlib.org/devel/gitwash/index.html

The workflow we are using is that same as most other scientific Python projects.

It looks like you've pulled in a lot of commits to your branch that shouldn't be there.  As to how to fix it, I think the only commit that's really necessary is d841494.  You could try:

```
git checkout master  # This is *your* branch you set up for this PR
git fetch upstream
git reset --hard upstream/master # Set your branch to exactly what's on upstream/master
git cherry-pick d841494  # Pull in your work commit on top of it
```

**Comment by tobias-froehlich** [comment]
Dear Michael,

it took a while till I understood how git works with branches when 
several repos are involved, but I think I finally got it.

I did another pull request, it is in the master-branch of

https://github.com/tobias-froehlich/matplotlib .

Best regards
Tobias



On 10/27/2015 12:19 PM, Michael Droettboom wrote:
> The best way to keep one of your personal branches up to date with the
> matplotlib master branch is to rebase. By convention, I usually keep a
> git remote called |upstream| that points to the main fork of matplotlib:
>
> |git remote add upstream https://github.com/matplotlib/matplotlib.git
> |
>
> Then, if I've been working on a branch for a while and I want to get the
> latest changes from upstream:
>
> |git checkout my-local-branch
> git fetch upstream
> git rebase upstream/master
> |
>
> This is described in greater detail here:
> http://matplotlib.org/devel/gitwash/index.html
>
> The workflow we are using is that same as most other scientific Python
> projects.
>
> It looks like you've pulled in a lot of commits to your branch that
> shouldn't be there. As to how to fix it, I think the only commit that's
> really necessary is d841494
> <https://github.com/matplotlib/matplotlib/commit/d8414947a197425ea61aca4b12eb4e77efcc6529>.
> You could try:
>
> |git checkout master  # This is *your* branch you set up for this PR
> git fetch upstream
> git reset --hard upstream/master # Set your branch to exactly what's on upstream/master
> git cherry-pick d841494  # Pull in your work commit on top of it
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/pull/5318#issuecomment-151459459>.
>

-- 
Tobias Fröhlich
II. Physikalisches Institut, Universität zu Köln Zülpicher Straße 77, 
D-50937 Köln
Tel.: 0221 / 470 - 3574

**Pull request closed without merging**
