### PR TITLE
List Colormaps issue. Read my pull request

### PR DESCRIPTION
**Pull request by MrZaurik**
Okay, my progress was the following, I wrote a few lines in the file colormaps.py where I create a function called listColormaps() the important thing is that according to the type of colormap it will list the available patterns.

Now, I find it useful to declare in a global way the variables of the colormap types that exist, that is to say: Perceptually, Sequential, Sequential2, Cyclic, Qualitative, Miscellaneous. In such a way that if more patterns are developed it will be easier to extend the functionalities. 

Attached is the code, read the issue #26244

```py
# New function to list the actually colormaps on matplotlib
def listColormaps(category):
    # Define a dictionary that maps each category to its corresponding list of colormaps
    colormaps_by_category = {
        'Perceptually': ['viridis', 'plasma', 'inferno', 'magma', 'cividis'],
        'Sequential': ['Greys', 'Purples', 'Blues', 'Greens', 'Oranges', 'Reds',
                       'YlOrBr', 'YlOrRd', 'OrRd', 'PuRd', 'RdPu', 'BuPu',
                       'GnBu', 'PuBu', 'YlGnBu', 'PuBuGn', 'BuGn', 'YlGn'],
        'Sequential2': ['binary', 'gist_yarg', 'gist_gray', 'gray', 'bone',
                        'pink', 'spring', 'summer', 'autumn', 'winter', 'cool',
                        'Wistia', 'hot', 'afmhot', 'gist_heat', 'copper'],
        'Diverging': ['PiYG', 'PRGn', 'BrBG', 'PuOr', 'RdGy', 'RdBu', 'RdYlBu',
                      'RdYlGn', 'Spectral', 'coolwarm', 'bwr', 'seismic'],
        'Cyclic': ['twilight', 'twilight_shifted', 'hsv'],
        'Qualitative': ['Pastel1', 'Pastel2', 'Paired', 'Accent', 'Dark2',
                        'Set1', 'Set2', 'Set3', 'tab10', 'tab20', 'tab20b',
                        'tab20c'],
        'Miscellaneous': ['flag', 'prism', 'ocean', 'gist_earth', 'terrain',
                          'gist_stern', 'gnuplot', 'gnuplot2', 'CMRmap',
                          'cubehelix', 'brg', 'gist_rainbow', 'rainbow', 'jet',
                          'turbo', 'nipy_spectral', 'gist_ncar']
    }

    # Return the list of colormaps for the given category, or an empty list if the category is not found
    return colormaps_by_category.get(category, [])
```

### CODE REVIEW

**Comment by MrZaurik** [comment]
I based on:
https://github.com/matplotlib/matplotlib/issues/26244#issuecomment-1641222939

Don't worry about that.

**Comment by timhoffm** [comment]
> I think the way to implement that is by putting category attributes on the colormaps themselves and filtering on those in a specialized listing function, as that will most easily allow third party colormaps to participate and keeps the maintenance in the colormap - but I also don't think you should implement that unless there's support from at least one other maintainer and no major objections.

IMHO listing categories in the documentation is sufficient (https://matplotlib.org/stable/gallery/color/colormap_reference.html). I don't see much benefit providing this as an API. For the average user it's simpler (don't have to know the function name for this) and better (the HTML docs show the colors). I also don't see a stong benefit for downstream code to access this information programmatically. Overall, it does not justify the added complexity and additional code.

**Comment by MrZaurik** [comment]
Totally Agree. As i mention in the issue, you can see the name at the left side of images in the HTML file on the web.

**Comment by MrZaurik** [comment]
> > the HTML docs show the colors
> 
> So does jupyter notebook. I'm thinking if I'm running a tutorial,`colormaps.list('diverging')` would be so fast and easy. It's also helpful in terms of IDing that this map is catagorical and therefore should only be used with norms that do discrete quantization #21786. It could also be nice for generating autotags in examples so that it's easier to find for example all the examples that use diverging colormaps. But there's a bigger proposal for metadata on cmaps for accessibility reasons and it can totally go in as part of that #17893
> 
> Which means that for this PR, @MrZaurik the way to address the initial issue is [#26244 (comment)](https://github.com/matplotlib/matplotlib/issues/26244#issuecomment-1641222939)

But it is actually working with the function that can print different color maps with different labels.

**Comment by MrZaurik** [comment]
Alright.

**Pull request closed without merging**
