### PR TITLE
[MRG+1] Migration to sphinx-gallery

### PR DESCRIPTION
**Pull request by choldgraf**
This is a riff off of #8247 and all of the hard work that @NelleV put into getting the documentation building off of sphinx-gallery. As of the latest discussion, @dopplershift @QuLogic and @tacaswell suggested that it'd be better to use a more "human readable" folder for the examples. This PR is the same as Nelle's but it calls the generated examples "examples_gallery". So a URL might be:

`matplotlib.org/examples_gallery/api/plot_font_family_rc.html`

Do folks think that this is a decent name for the folder? Maybe a little long, but it's straightforward. @dopplershift was right in that it wasn't too tough to change the name, so I could go with something different if that's preferred.

### CODE REVIEW

**Comment by anntzer** [comment]
My vote is also for something simpler, i.e. either examples or gallery.

**Comment by choldgraf** [comment]
Examples is already taken. If `gallery` is not, then I can switch it to that. Most important is that we just get some consensus and move forward.

Can anybody see a reason **not** to use `gallery`?

**Comment by NelleV** [comment]
How about auto_examples? :D

**Comment by anntzer** [comment]
let's just have a vote.
+1 for gallery

**Comment by QuLogic** [comment]
I thought `gallery.html` was deleted since this PR stops using `gen_gallery.py`?

**Comment by choldgraf** [comment]
@QuLogic I believe you're right. At the least the `gallery` link on the front page now goes to `matplotlib.org/whateverthisiscalled/index.html`

**Comment by NelleV** [comment]
Yes, that is correct: gallery.html is now replaced by matplotlib.org/XXX/index.html.

**Comment by choldgraf** [comment]
In this case I will give my vote for going with `gallery`. I think it's a natural extension of what it was before.

I'll try building the docs with this now...ten bucks says that it unearths some terrible bug and we can't use it after all :P

**Comment by choldgraf** [comment]
I'm not sure what the failing travis build is - I think there is one image comparison failure? Not sure how finnicky the MPL tests are though...it doesn't seem to be related to this PR but correct me if I'm wrong.

**Comment by jenshnielsen** [comment]
@choldgraf that looks like a known flaky test. I will restart the Travis job now

**Comment by choldgraf** [comment]
looks like the tests are passing! is there a place I can link to the docs so you all can take a look?

**Comment by Titan-C** [comment]
Nice to see you are going to use Sphinx-Gallery. 
You don't really need to rename all your examples to have the prefix `plot_`, that is for historical reasons our default, you can change it using regular expressions http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-examples-matching-a-pattern

**Comment by choldgraf** [comment]
We could always set it to default to plotting everything in the folder except for files that have `noplot` inside them, or something like this?

**Comment by NelleV** [comment]
The end-goal was to be able to develop a plugin to be able to save gifs for movies, and prefix with something else in this case, hence the renaming to `plot_`.

**Comment by choldgraf** [comment]
I see - well they're all named `plot` right now. I don't really see a problem with this and can see it being useful to differentiate these kinds of examples from other kinds in the future, as nelle explains.

**Comment by anntzer** [comment]
Why do we need a prefix?  sphinx-gallery should (ultimately) be able to detect whether the script produced a static image or a movie.

**Comment by choldgraf** [comment]
See @Titan-C 's comment about why we're using a prefix in the first place. SG by default matches `plot_*` in the filenames, and that's the standard that most projects use.

As he mentioned we don't *have* to do it this way - we could have it match any file by default, or have it only *exclude* files that match a certain pattern. However I feel like having `plot_` is fairly expressive and in line with standards you'll see elsewhere. I don't think we should expect that sphinx-gallery will auto-detect output etc.

**Comment by anntzer** [comment]
As mentioned is earlier discussions, matplotlib is a plotting library, so you'd expect the vast majority of examples to be, well, plotting examples.  So adding a `plot_` prefix really counts as line noise IMO.

If sphinx-gallery gains the ability to handle movie outputs, it will have to handle them differently anyways, so it makes sense for it to detect whether the output is a movie or not...

**Comment by choldgraf** [comment]
What are you suggesting? Wildcard matching any python file in the folder? I'll say that I think there's value in following convention, but also value in not having an extra 5 characters in each example filename.

As I said before I really don't care, the important thing is to just agree on something and move forward.

**Comment by NelleV** [comment]
@Titan-C out of curiosity, if a user decides to tag all python examples as producing plots ("*.py"), how would you indicated sphinx-gallery to not produce plots for some examples?
I looked into this a couple of months ago, but there didn't seem to be a nice solution (it actually makes total sense to prefix examples that produce plots with `plot_` to deal with stuff like examples that don't produce plots etc).

**Comment by dopplershift** [comment]
I agree with @anntzer about not having the `plot_` prefix. In the case of matplotlib, it communicates nearly nothing since almost all the examples plot.

Also, there's absolutely nothing wrong with including plots that don't plot in the gallery; These get a placeholder image, have mouse-over text with the description. This way they get included with examples on a similar topic, still get executed as part of the documentation build, and are still available as notebook downloads. The approach I took [here](https://unidata.github.io/MetPy/examples/index.html) was just to run all `.py` files.

So my question would be: why are we excluding *any* examples whatsoever from our gallery?

**Comment by NelleV** [comment]
So, @choldgraf has proposed (in an offline discussion) a very un-elegant solution to me that indeed would work.

**Comment by NelleV** [comment]
@dopplershift Yes. We have *many* examples that don't produce plots. I've offered to delete them to solve this issue, but somehow someone was unhappy with my solution.

**Comment by dopplershift** [comment]
I guess having many default images in a gallery of examples (not our showcase examples of course) doesn't bother me. I'm sure there are specific ones that could be culled without loss of information though.

IMO, important to have one solid place to find the examples rather than multiple places to look.

**Comment by choldgraf** [comment]
> IMO, important to have one solid place to find the examples rather than multiple places to look.

+1

Why don't we just have it match all python files in gallery, and remove the `plot_` from each one. If it gets to the point where there are a ton of default thumbnail images, then they can either be removed, an image can be added, or we can always have SG exclude them in the future.

**Comment by NelleV** [comment]
FYI, @choldgraf you've just volunteered for hours and hours of work.

**Comment by choldgraf** [comment]
yeah...finding / replacing all of these filenames is not going to be trivial. I'll see what I can do

**Comment by dopplershift** [comment]
To be clear, I'm not trying to create days of work for anyone here.

**Comment by choldgraf** [comment]
The tricky thing is just that these files are linked all over the place inside the matplotlib docs. Since this PR is many months old with lots of changes, that's quite a lot of work to look through and try to undo. To be honest this is really something that should have been decided back whenever the first PR was opened, and not here at the very end.

I'm gonna try to write a script that attempts to find/replace all the `plot_` filenames throughout the MPL codebase but otherwise it would have to be done manually.

**Comment by anntzer** [comment]
@choldgraf I think
```
$ mmv **/plot_*.py **/*.py
$ sed -i 's/\bplot_\([[:alnum:]_]*\.py\)/\1/g' **/*.py **/*.rst
$ git checkout -- doc/users/github_stats.rst doc/users/prev_whats_new/changelog.rst
```
(where mmv is a semi-standard zsh alias, e.g. http://www.mfasold.net/blog/2008/11/moving-or-renaming-multiple-files/) should do most of what's needed.  Trying to rebuild now.

**Comment by choldgraf** [comment]
lmk if that works and I'll go for it - the python script I wrote to do this is not working quite right...

**Comment by anntzer** [comment]
It's still building, but meanwhile I got
```
Example directory /home/antony/src/extern/matplotlib/doc/../examples/animation does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/axes_grid1 does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/axisartist does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/event_handling does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/frontpage does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/misc does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/pylab_examples does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/pyplots does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/scales does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/specialty_plots does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/tests does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/units does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/user_interfaces does not have a README.txt file
Skipping this directory
________________________________________________________________________________
________________________________________________________________________________
Example directory /home/antony/src/extern/matplotlib/doc/../examples/widgets does not have a README.txt file
Skipping this directory
```

I guess that's a good way to exclude entire folders :-)

**Comment by choldgraf** [comment]
yep - that will work to know which folders have been migrated or not!

**Comment by choldgraf** [comment]
so your docs built fine using that command?

**Comment by anntzer** [comment]
you probably need to git clean -xdf too, old files sticking around cause build failures ("warning: document isn't included in any doctree")

**Comment by choldgraf** [comment]
well...I can try to spend some time to do this tomorrow. If we know that those commands will work then I can just do it...otherwise it'll take some time and I've already burned my evening trying to get this to work w/ python :-/

**Comment by anntzer** [comment]
Also throw in a
```
sed -i 's/-plot_/-/g' **/*.rst
```

I also did
```
-   # path to your examples scripts
-    'examples_dirs' : '../examples',
-    # path where to save gallery generated examples
-    'gallery_dirs'  : 'gallery'}
+    'examples_dirs': '../examples',
+    'filename_pattern': '\.py$',
+    'gallery_dirs': 'gallery'}
```
to conf.py but not sure setting filename_pattern was actually needed.

Now everything works.

**Comment by choldgraf** [comment]
@anntzer, thanks for the help! I just tried running your commands and I'm running into errors - is this something that will only work on linux? Since you have already done the renaming etc on your machine, want to just push that to your fork and open a PR against my branch? Then I can merge and we'll have it in here.

**Comment by anntzer** [comment]
done

**Comment by choldgraf** [comment]
Thanks @anntzer 

let's see if the tests still pass!

**Comment by choldgraf** [comment]
It looks like the doc builds aren't passing - there seem to be links that point to examples that start with `plot_`.

E.g.: https://travis-ci.org/matplotlib/matplotlib/jobs/221050520#L2282

I went through the travis build and found the missing links (they were all in the `users` folder embedded in tutorials etc). Just pushed these changes so let's see if that fixes it.

**Comment by choldgraf** [comment]
It looks like the doc builds are passing now. I only changed a few links so I wonder if the other travis failures (which were passing before) are travis problems and not code problems. @anntzer or @dopplershift could you restart those failing builds?

**Comment by anntzer** [comment]
This is a well known flaky test and we do not block on it.  Assuming Appveyor and Travis/OSX pass we should be good to go.

**Comment by choldgraf** [comment]
It looks like only that first travis test failed, all the rest passed!

(BTW, thank you again for making that PR on my branch...maybe it was easy for you but this would have taken me probably another several hours to figure out :-/ )

**Comment by anntzer** [comment]
The failure can safely be ignored.  Unless someone speaks up in the coming ~24hr, I will merge.

I think the lesson here is that what is hard for some may be easy for others, and that we are all willing to help.  I honestly had been unable to see why such a big fuss was being made about the rename.  A comment as simple as "we don't only need to rename a bunch of files [this is what I thought that was all about], but also to update the links everywhere -- that's a lot of work for me" would probably have caught my attention some time ago; it literally took me less than half an hour to fix that (most of which was spent running the doc builds, so I could actually do other stuff in the meantime -- say 10min actually writing code and skimming through diffs).

**Comment by choldgraf** [comment]
This is a good point - I think it's always good to remember (especially with newer contributors) that things that sound easy to a dev will not sound easy to a contributor, particularly if they've already put in a lot of time into the PR.

And I think it's also important to make it clear if/when devs are willing to work with people on the PR code etc...there's definitely a power differential between the devs and a contributor, and in my experience they won't feel comfortable spontaneously asking devs to do some coding for them.

Finally I think it's also useful to have posts similar to the one you just made. Where somebody says something along the lines of "OK everybody I'm giving 24 hours for comment and unless there's a big concern, I'm going to merge". It sucks when the author is in PR limbo where it seems like everybody has approved, but nobody is pressing the green button (I am sure we've all been there :-) ). It's useful to give explicit decision points to ensure that things keep moving forward.

Either way, I appreciate people taking the time to give their input on the PR!! We're all volunteers and I think it's awesome that such a useful package as matplotlib exists and continues to improve.

**Comment by dstansby** [comment]
Just built this locally, and it looks great!

I think there are some little tweaks that still need to be made, and as always lots of cleaning to be done with examples, but that should all be much easier now sphinx-gallery is up and running. Thanks to all who worked on this!

**Comment by dstansby** [comment]
Putting this in `2.1`, since it's a fairly big change. Am happy for someone else to backport though if they think it should go in earlier.

**Comment by tacaswell** [comment]
pros of backporting:
 - will get new docs out faster
 - reduce odds of conflicts in the examples between master and 2.0.x

cons:
 - will be a pain to do as _all_ of the other example related PRs will likely have to be tracked down and backported for this to backport cleanly

Leaning towards not.

**Comment by QuLogic** [comment]
We have, up to this point, never* backported a documentation PR that deletes (moving counts, too) examples.

\* except by accident or extreme necessity

**Comment by tacaswell** [comment]
That is a solid point, sold on on not backporting.

**Comment by choldgraf** [comment]
that's great news, thanks all! I think the next step should be to try and get the remaining examples ported to sphinx-gallery compatibility. This could be done one of two ways:

1. Manually, which means going through each example, specifying a title, and specifying a top-level description.
2. Semi-automatically, which could mean just generating a title built automatically from the file name, and then adding a blank line after the title (per [this issue](https://github.com/sphinx-gallery/sphinx-gallery/issues/222) that @anntzer opened which means we don't have to actually have a description for every example)

If people are OK with approach 2, then I could open a PR that tries to do this on one folder so we can see how well it works...what do people think about this? Is it worth giving it a shot to see if we can get something that looks good without manually going through like 500 examples?

**Comment by anntzer** [comment]
I would favor the automatic approach for the "examples" gallery.  They can always be moved later to the "gallery" gallery after manual curation.

**Pull request merged**
