### PR TITLE
Fix array-like linewidth for 3d scatter

### LINKED ISSUE #23433: [Bug]: array-like linewidth raises an error for scatter3D
### Bug summary

The documentation says that `linewidths` can be `float or array-like` and it defaults to 1.5, but passing an array-like leads to an error

### Code for reproduction

```python
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(projection='3d')
x = range(1, 10)
ax.scatter(x, x, x, marker='o', s=x, linewidth=x)
plt.show()
```

### Actual outcome

Exception:

```
mpl_toolkits/mplot3d/axes3d.py in do_3d_projection(artist)
    469                     # avoid passing it to them; call this directly once the
    470                     # deprecation has expired.
--> 471                     return artist.do_3d_projection()
    472 
    473                 _api.warn_deprecated(

matplotlib/_api/deprecation.py in wrapper(*inner_args, **inner_kwargs)
    429                          else deprecation_addendum,
    430                 **kwargs)
--> 431         return func(*inner_args, **inner_kwargs)
    432 
    433     return wrapper

mpl_toolkits/mplot3d/art3d.py in do_3d_projection(self, renderer)
    615 
    616         if len(self._linewidths3d) > 1:
--> 617             self._linewidths = self._linewidths3d[z_markers_idx]
    618 
    619         # Re-order items

TypeError: only integer scalar arrays can be converted to a scalar index
```

gets raised, from:

https://github.com/matplotlib/matplotlib/blob/0d433b4bf20bfc564400f35ce9709f7596e0e5f6/lib/mpl_toolkits/mplot3d/art3d.py#L599-L603

This is because the type of `self._sizes3d` is `numpy.ndarray`, but type of `self._linewidths3d` is `list`.

### Expected outcome

Array-like linewidth works for 3d plots as it does for 2d plots.

### Additional information

- `ax.scatter(x, x, x, marker='o', s=x)` works fine.
- `linewidths` is a list regardless of user input type.
- I don't know where linewidths gets converted to a list, but a quick fix is as simple as wrapping it in `np.array` call: `self._linewidths = np.array(self._linewidths3d)[z_markers_idx]` (tested that this fixes the issue).

### Operating system

_No response_

### Matplotlib Version

3.5.2 but also happens with older versions (3.3.x)

### Matplotlib Backend

_No response_

### Python version

_No response_

### Jupyter version

_No response_

### Installation

pip

### PR DESCRIPTION
**Pull request by krassowski**
## PR Summary

Fixes #23433 by casting `self._linewidths3d` to `np.array` at the latest stage possible and adds a test to ensure it works.

The casting step could alternatively be moved to happen earlier in the code logic in `set_linewidth` and in `set_3d_properties`, but I went for the simplest solution possible. Let me know if you want to change that (in that case, is `self._linewidth3d = lw` a typo? should it be `_linewidths3d`?)

## PR Checklist

**Tests and Styling**
- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [N/A] New features are documented, with examples if plot related.
- [N/A] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [N/A] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [N/A] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by QuLogic** [comment]
I think it'd be better to not do this so late, since this is in the draw call. Then the array can be done once instead of every refresh, which could be a bit slow.

**Review by oscargus — APPROVED** [review]

**Comment by oscargus** [comment]
I think this should be changed as well:
https://github.com/matplotlib/matplotlib/blob/3992fb0d4b81a448a3006f5b9b7216cee4dfac0c/lib/mpl_toolkits/mplot3d/art3d.py#L563-L566

Both changing the name from `_linewidth3d` to `_linewidths3d` and converting into an np-array.

**Comment by oscargus** [comment]
Maybe one can also add a `check_figures_equal` test that uses the `set_linewidth` method for one of the figures and the keyword argument for the other?

**Comment by krassowski** [comment]
> Maybe one can also add a `check_figures_equal` test that uses the `set_linewidth` method for one of the figures and the keyword argument for the other?
> 
> (See the test just below the one you added to see how they work.)

To clarify, since `set_linewidths` is already there in the test case that you are pointing to (and since `self._linewidths` was already getting properly set in the `super()` call it worked ok for scalars as tested), would you like me to add another test like that, but testing that array-likes can be set via keyword argument and setter?

**Comment by oscargus** [comment]
Considering the spelling error, I do not think that it was actually properly tested, so ideally there should be a test that does set_linewidth and relies on that the spelling is correct.

**Comment by krassowski** [comment]
The test which I added in 2bdbdca6c24610b0e540fa998f4422d86bd4ab1f should cover that. The documentation build seems to be failing, is there anything I should do, or is it intermittent CI issue?

**Comment by scottshambaugh** [comment]
@krassowski looking at [the docs build logs](https://circleci.com/api/v1.1/project/github/matplotlib/matplotlib/69565/output/113/0?file=true&allocation-id=62daa56f101f2d65c06e7e5d-0-build%2F1E8B2B5E), I think this was just an intermittent CI issues. I don't think there's a way to re-trigger the tests through the github gui, but if you do a `git commit --amend` followed by a `git push -f` I believe that should change the timestamp on your last commit and cause the CI tests to rerun.

**Comment by krassowski** [comment]
Thanks, all checks have passed now :tada:

**Comment by krassowski** [comment]
A gentle ping on this PR :)

**Review by oscargus — APPROVED** [review]

**Comment by tacaswell** [comment]
Congratulations on your first merged Matplotlib PR @krassowski 🎉  Hopefully we will hear from you again!

Also thank you for the gentle ping!

**Pull request merged**
