### PR TITLE
Default rstride and cstride for plot_surface changed to 1 from 10.

### PR DESCRIPTION
**Pull request by tobin**
It doesn't seem like a sensible default to throw away 90% of the data.

### CODE REVIEW

**Comment by tacaswell** [comment]
Closing this as it as 7mo old and two devs are :-1: on it.

This resulted in https://github.com/matplotlib/matplotlib/pull/3185 which documents the defaults more prominently.

**Comment by anntzer** [comment]
@tacaswell @WeatherGod Any chance we can revisit this choice for 2.0?
I agree with the OP that the current defaults are not sensible.  Not all datasets are large; and averaging may or may not be the correct way of downsampling.

**Comment by tacaswell** [comment]
I would be willing to change this for 2.0, but will defer to @WeatherGod on this.

**Comment by tacaswell** [comment]
pning @WeatherGod

**Comment by WeatherGod** [comment]
I honestly just do not think that this default should change. If it
overdecimates your data, then it will be obvious to the user and they
should adjust. If it under-decimate your data, then you are easily at risk
of swamping your memory and cpu, which would require kill -9 to get out of,
potentially losing other work in an interactive session.

Yes, this is true for several of matplotlib's functions, but plot_surface
seems especially sensitive to this problem (partly because of its
inefficient algorithm).

**Comment by anntzer** [comment]
I don't want to sound rude but... I think this argument holds no water.

There are currently a ton of ways of fatal-abort'ing matplotlib (e.g. #6983, #7052 for recently fixed issues), and `imshow` itself has such bad memory performance that it can also easily lead to an out of memory situation (#6952).  Still I don't think anyone would think it would make sense to auto-downsample arguments to `imshow` just in case the user was going to do something stupid.

Moreover, the 10x 10x downsampling is just a random shot in the dark.  You have no way of knowing whether that's going to be enough or too much downsampling when the goal is to prevent an out-of-memory situation.  If we really want to do something about this, we should measure how much memory is currently available and downsample to fit in that amount.  Not that I think we should bother doing this, but at least it would be useful, rather than being an annoyance.

**Comment by efiring** [comment]
How about a simpler approach: a new default of None for rstride and cstride, in which case the strides are chosen to keep the number of points under some maximum, say 100.  This maximum could be controlled via another kwarg (documented with a warning that setting it to a larger value risks hanging the machine). I think this would reduce shotgun blasts to users' feet without depriving them of any of the control they have now.  It would be a better default because it would do the expected thing--no decimation--when given small input arrays.

**Comment by efiring** [comment]
A fancier downscaling operation could be added in some future release, but it shouldn't delay 2.0 given that a simple approach such as I outlined yields major progress.

**Comment by WeatherGod** [comment]
Hmmm, I would be willing to accept something like that.

**Comment by WeatherGod** [comment]
I have implemented something that I think would satisfy everybody. See #7164.

**Comment by tacaswell** [comment]
re-closing in favor of #7164

**Pull request closed without merging**
