### PR TITLE
Fixed AppVeyor building script

### PR DESCRIPTION
**Pull request by Kojoley**

### CODE REVIEW

**Comment by Kojoley** [comment]
Oh. It is fixed in PR #6520 with https://github.com/matplotlib/matplotlib/pull/6520/commits/9af6ae01cbf972d7e2132e5a9b89d6c45a9ca65a but still not merged

**Comment by tacaswell** [comment]
Why did this pass but #6520 is still failing?  attn @janschulz

**Comment by janschulz** [comment]
Because in master, the conda build is still disabled:https://github.com/Kojoley/matplotlib/blob/4a76c0fc06f95fdc3abeeb5119ab3f4f4965e7cb/appveyor.yml#L115

IMO this should be merged, I will rebase mine on top of it -> reopen and merge...

**Comment by tacaswell** [comment]
:+1: I hit the merge button as soon as it was green (travis failure was unrelated / a known flaky test).

**Pull request merged**
