### PR TITLE
Simpler check for whether a Framework Python build is being used.

### PR DESCRIPTION
**Pull request by anntzer**
This check works even before an NSApp is started.

Simpler alternative to #11850.  Basically the first stackoverflow answer for the question (https://stackoverflow.com/questions/15752390/how-to-tell-if-python-instance-was-compiled-as-framework), from a CPython core dev.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
Looks like @efiring knows something about this per http://matplotlib.1069221.n5.nabble.com/Re-Anaconda-Support-OSX-why-not-make-python-invoke-the-framework-tp43793p43806.html :)
(and that anaconda's pythonw is not a real framework build but manually emulates one, whatever that means...)
Oh well.

**Comment by jklymak** [comment]
Yeah, I guess anaconda does something funky.  OTOH, I shudder to think what installing the framework build w/o anaconda would be like...

**Comment by anntzer** [comment]
Isn't that just (for example) python.org's python?  Anyways, the discussion is not very relevant, we're stuck with whatever anaconda did and #11850 seems better unless Apple plans to actually remove their deprecated features :p

**Comment by tacaswell** [comment]
Moving this to 3.1 as I just merged #11850.  I think this is inline with @anntzer 's last comment.

**Comment by jklymak** [comment]
Closing this, as this approach won't work unfortunately...

**Pull request closed without merging**
