### PR TITLE
Add svg logo icon

### PR DESCRIPTION
**Pull request by timhoffm**
The icon is mainly created for large-sized display (c.f. #15879). If it's scaled down much (<30%) the lines become too thin.

While this is not (yet?) used anywhere on the website or in the examples, I think it's good to have this stored somewhere in the repo. And with 19k, it's still small enough so that it does not hurt.

The icon created using the logo example https://matplotlib.org/gallery/misc/logos2.html
and parameters

~~~
make_logo(height_px=360, lw_bars=1.5, lw_grid=1.0, lw_border=3.0,
           rgrid=[1, 3, 5, 7], with_text=False)
plt.savefig('matplotlib-icon.svg')
~~~

and compressed via https://vecta.io/nano (compression level 5).

### CODE REVIEW

**Comment by timhoffm** [comment]
Discussion: Is this the right place to add the svg logo icon?

**Comment by QuLogic** [comment]
I would guess so, it's the same place as the PNG. What would you hope to use this for?

**Comment by timhoffm** [comment]
I'm looking for a place to store the "official" logo icon. It's not bound to a particular purpose, but we need logos in various locations. be it for [numfocus](#15879), discourse, social media account icons etc. and AFAICS we don't have a official place to take these logos from.

**Comment by QuLogic** [comment]
It seems a good a place as any other, though it's a bit of a hodgepodge of things. My only other suggestion is to put it in `docs/resources` and add an 'Official Resources' section there?

**Comment by story645** [comment]
I think we need an actual logo/branding page, specially since our logo font means it can't just be regenerated. I'd go w/ twitters sizes as good as anything:
* icon: 400x400 pixel jpeg/png
*header: 1500x500 pixel jpeg/png

and the logo/branding page should tie in w/ the https://github.com/matplotlib/governance/blob/master/communications_guidelines.md

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
I don't see any reason not to merge this, despite any other changes we think we need.

**Comment by timhoffm** [comment]
Maybe it should go in another repo? But I don't know which.

**Comment by jklymak** [comment]
i dunno I think we should have a logo page - but I guess we can merge this when someone needs it?  Otherwise we will forget we have it...

**Pull request merged**
