### PR TITLE
DOC: set canonical

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

This closes https://github.com/matplotlib/matplotlib.github.com/issues/68 going forward, though it doesn't go back and fix 3.5 and 3.5.1

3.5.0 and 3.5.1 do not list the canonical links as `/stable/index.html` (etc) and google has started surfacing `/3.5.1/index.html` as the canonical and ignoring `/stable/index.html` as a duplicate.  We want `stable` to be the canonical, so this adds:

`<link rel="canonical" href="https://matplotlib.org/stable/index.html" />` to `index.html` or 
`<link rel="canonical" href="https://matplotlib.org/stable/gallery/frontpage/3D.html" />` to `gallery/frontpage/3D.html` etc.  

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by jklymak** [comment]
Works as expected on CI:  https://67489-1385122-gh.circle-artifacts.com/0/doc/build/html/index.html.

**Comment by tacaswell** [comment]
Should we put this behind the same release flag that we use for GA etc?

**Comment by jklymak** [comment]
We could, but I don't think it means anything for unpublished sites. I guess the dev branch but we still want canonical to point to stable.  And if the canonical doesn't exist (new page) then I think google just picks up the real page anyway.

**Comment by tacaswell** [comment]
I'm thinking about distros that want to build the docs for offline use etc.  I guess it does little harm, but it is worth trying to be tidy.

I'm going to approve this, but leave it to @QuLogic to merge.

**Review by tacaswell — APPROVED** [review]

**Review by QuLogic — APPROVED** [review]

**Pull request merged**
