### PR TITLE
[MRG+2] Early check for dot binary (from graphviz) when building the doc (fixes #8207)

### LINKED ISSUE #8207: Add early check for "dot" binary (graphviz) when building docs
Looks like sphinx relies on graphviz to generate inheritance docs.  For the same reason as #7828 the presence of the binary should be checked early.

Attn @NelleV

### PR DESCRIPTION
**Pull request by afvincent**
Fixes #8207.

The commit is shamelessly inspired from #8213.

### CODE REVIEW

**Comment by NelleV** [comment]
It also look good to me, though the amount of dependencies we have in our documentation worries me. It means that new contributors struggle with something as simple as contributing documentation.

**Comment by anntzer** [comment]
@NelleV I wonder whether we could create two mpl-testing and mpl-docs packages on conda-forge which would pull in all required dependencies, including the non-python ones (for example, graphviz is packaged by conda).  Then the instructions would just be to install the corresponding package from conda.

**Comment by NelleV** [comment]
@anntzer I don't use conda, so I have no opinion on whether this would be useful.
In general, I do not think it is wise to rely too much on conda for a project as wide as Matplotlib: Matplotliib should be able to get contributors from non scientific python users, and conda is not widely used outside of the Python community.

An option would be to change the default for allowsphinxwarnings so that people can build the documentation with missing dependencies. That would reduce the barrier for contributions, but then it would be up to us (core contributors) to guide new contributors on fixing travis build. I do not think we are well equipped for that option.

**Comment by anntzer** [comment]
Alternatively, I know that imageio has been including code to download ffmpeg/avbin/freeimage at runtime (http://imageio.readthedocs.io/en/latest/envvariables.html), so that could be an option too (although it would certainly have its own issues, unless they have completely statically linked builds...).

**Comment by NelleV** [comment]
Thanks @afvincent !

**Comment by dstansby** [comment]
Backported to `2.0.x` via. https://github.com/matplotlib/matplotlib/commit/c8b4db86db5866328cefaaf3b13bfdb3882c27dd

**Pull request merged**
