### PR TITLE
Colorbar grid postion

### PR DESCRIPTION
**Pull request by ShawnChen1996**
## PR Summary
I made a little change so that now the `anchor` argument in `make_axes_gridspec` mimic the behavior of that in `make_axes`.  Now the postion of colorbar is determined by `anchor` and `shrink`, should be very useful when `shrink` < 1.0

The effect is demostrated in the plot below. Now I can place the colorbar at different place with different shrinked size.

```python
import numpy as np
import matplotlib as mpl
import matplotlib,pyplot as plt

x = np.random.randn(100)
y = np.random.randn(100)
fig = plt.figure()
ax = fig.add_subplot()
mappable = ax.scatter(x,y, c=y)
ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), shrink=0.5) 
```
A good figure

Before the change, we can achieve that using `ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), use_gridspec=False) ` , however, this will create a colorbar as a `Axes` not a `Subplot`, when I use `subplots_ajust` to adjust the border margins, I got the following plot.
```python
fig = plt.figure()
ax = fig.add_subplot()
mappable = ax.scatter(x,y, c=y)
ax.figure.colorbar(mappable, ax=ax, anchor=(0,0.3), shrink=0.5, use_gridspec=False) 
ax.figure.subplots_adjust(bottom=0.1)
```
A bad figure

It seems the colorbar Axes is ignored and my plot is re-placed according to its `panchor` parameter that `make_axes` set. It bothers me when I have multiple plots and wanna adjust the plots  border margins and wspace, hspace.

`gridspec` offers a better approach and is the default setting when creating a colorbar, however, I want the colorbar to be 0.5 size and placed at the bottom right, which is mot implemented.

So this is what I did basically.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
Follow these instructions for  the rebase: https://matplotlib.org/3.1.3/devel/gitwash/development_workflow.html#rebasing-on-trunk (please note the instructions to create a backup branch, just in case ;-))

**Comment by tacaswell** [comment]
This seems like a reasonable feature to add to me :+1: 

In addition to being rebased, this should get a whats_new entry and maybe an example in the gallery?

**Review by dstansby — CHANGES_REQUESTED** [review]
Marking as needs changes, as this needs a rebase and a what's new entry. @ShawnChen1996 let us know if you need help with anything!

**Comment by ShawnChen1996** [comment]
I had some issues as I switched to a new laptop, but finally managed to set up the environment and rebase this.

The head of this branch I rebase on is very different than the previous one.  I made the modification accordingly and so far the graph looks good, may need a big tuning on the `pad` between colorbar and the plot. Will work on this soon and rewriting the test function. Will also work on WHAT'S NEW and EXAMPLE.

May I ask is this rebasing correct? As there are 9 check failures.

**Comment by jklymak** [comment]
I don't think you pushed your rebase to GitHub.  But.... Before you do, make sure you've backed up this version of the branch, just in case there are errors....

Thanks for persevering with this!

**Comment by ShawnChen1996** [comment]
sorry for the trouble I made. I opened the another pull request with rebased code. This PR is closed. The new PR is #18575

**Pull request closed without merging**
