### PR TITLE
 MAINT: Vectorize bar3d 

### PR DESCRIPTION
**Pull request by eric-wieser**
This refactors bar3d to use numpy to compute all the coordinates in parallel.

I'm not certain if this actually results in a speed increase, but it does result in a clarity improvement,

This spun out of #12136, which raised the fact that bar3d does not orient its faces correctly (#12138). This patch does not fix that, but it does make it easy to fix in a subsequent revision.

I can split the multiple commits here into multiple PRs if that adds value.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Flake8 failures seem to not be part of this patch?

**Comment by eric-wieser** [comment]
Too lazy to do that. I'll just close and re-open this PR once that one is merged

**Comment by anntzer** [comment]
merged #12139

**Comment by eric-wieser** [comment]
CI now passes - thanks!

**Pull request merged**
