### PR TITLE
Fix exception causes in rcsetup.py

### PR DESCRIPTION
**Pull request by cool-RR**
## PR Checklist

- [x] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [x] New features are documented, with examples if plot related
- [x] Documentation is sphinx and numpydoc compliant
- [x] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [x] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
thanks for the pr, hoping to see you around again :)

**Comment by cool-RR** [comment]
Thanks for the quick code review! Would you be interested in the similar fix being applied to other parts of the codebase?

**Comment by timhoffm** [comment]
Basically yes. Use your own judgement, where the addional traceback gives some further insight vs. just adds more noise to the error message.

**Comment by cool-RR** [comment]
Good to know. Keep in mind, the issue isn't whether the extra traceback appears or not, because it appears anyway. It's only about displaying the correct message between the 2 tracebacks.

**Pull request merged**
