### PR TITLE
[MRG+1] Fix axhspan/axvspan view limits autoscaling

### PR DESCRIPTION
**Pull request by larrybradley**
Currently using `axhspan` or `axvspan` on an image results in the axis view limits being changed even when the `axhspan`/`axvspan` patch is fully within the image.  This PR changes the behavior to match `axhline` and `axvline`.

### CODE REVIEW

**Comment by larrybradley** [comment]
The single failing `travis` test seems unrelated:

   E           matplotlib.testing.exceptions.ImageComparisonFailure: images not close: /home/travis/build/matplotlib/matplotlib/result_images/test_mplot3d/mixedsubplot_svg.png vs. /home/travis/build/matplotlib/matplotlib/result_images/test_mplot3d/mixedsubplot-expected_svg.png (RMS 0.104)

I cannot reproduce this locally and that particular image does not use `axhspan` or `axvspan`.

**Comment by larrybradley** [comment]
@phobson Thanks for the review.  I've added the tests.

**Comment by larrybradley** [comment]
The single failing `travis` test is again an unrelated image-comparison test.

**Comment by anntzer** [comment]
This is actually already fixed in 2.0rc2 (testing with the PR tests), so I'll close it.  Feel free to let me know (with a minimal example) if you believe I missed something.

**Pull request closed without merging**
