### PR TITLE
Support datetime-like axis in Axes.bxp()

### PR DESCRIPTION
**Pull request by narlesky**
## PR Summary
Adds the ability to plot boxplots on a date/datetime-like axis.  This only requires minor changes to `matplotlib.axes._axes.Axes.bxp()`, including representing box widths as `datetime.timedelta`s and box positions as whatever the user specifies for incoming datetime structures (tested with `pandas.Timestamp`s, `datetime.datetime`s, `datetime.date`s so far).  PR is not ready to merge, since I haven't added any tests, but wanted to put this up to get a recommendation for next steps.  Would it be more appropriate to convert the `positions` argument to the MPL representation of dates before going through the exercise of sizing the boxes?

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by narlesky** [comment]
@jklymak Thanks!  That's exactly the type of note/example I was looking for.  I'll ping again soon!

**Comment by QuLogic** [comment]
Do you expect to come back to this some time?

**Comment by jklymak** [comment]
I'll close as orphaned.  It seems the basic functionality is desirable, but the approach would beed to be revised.

**Comment by narlesky** [comment]
Hey sorry all, changes to mpl in the meantime actually had already met my needs re boxplots with datetimes so no reason to continue down this path.

**Pull request closed without merging**
