### PR TITLE
Updating 2.0 schedule

### LINKED ISSUE #5395: Style changes doc has optimistic release date
I just noticed that [the page linked from the big orange banner](http://matplotlib.org/style_changes.html) on the website says mpl 2.0 will be released in September 2015, which has now passed. I'd make a PR for it, but I don't know what the new estimate should be.

It also invites style proposals, saying that a decision will be made in August. Has the decision been made yet? Either way, that bit should be updated to reflect the current status.

### PR DESCRIPTION
**Pull request by mdboom**
Fix #5395

### CODE REVIEW

**Comment by jenshnielsen** [comment]
:+1:  as soon as travis goes green

**Comment by mdboom** [comment]
Since I'm not up on current doc update methodology, am I right that:

1) This needs to be backported to 1.5.x-doc
2) The "main" (non-dev) version of the docs needs to be updated in matplotlib.github.com manually (though probabyl updating this single .html file is enough)

**Comment by jenshnielsen** [comment]
@mdboom that's my understanding too.

Note that there are two version in https://github.com/matplotlib/matplotlib.github.com

both in root and in 1.5.0 that needs to be updated (because we can't do server side redirect at the moment)

**Comment by tacaswell** [comment]
The other fun trick with building the docs is that you need to have v1.5.0 installed, but build the docs from the v1.5.0-doc branch (other wise versionerr will do it's job and report a postN version in the version string).

**Comment by tacaswell** [comment]
backported as 81f54bad0d6b9a19155833a3ec93acfd28bbd42b

Working on building the docs now

**Pull request merged**
