### PR TITLE
[Example] update Anscombe's Quartet

### PR DESCRIPTION
**Pull request by baogianghoangvu**
## PR Summary

Hi!

This PR includes a tiny change to the [Anscombe's Quartet example](https://matplotlib.org/gallery/specialty_plots/anscombe.html):
- current version: the linear regression lines only go from `min(x)` to `max(x)` per plot.
- updated version: the lines go the entire length of the plots, similar to the [Wikipedia page](https://en.wikipedia.org/wiki/Anscombe%27s_quartet)

Reason for this update:

When I looked at the IV quadrant, I thought that its linear regression line was different from the rest in terms of its _intercept_, slope seemed the same, but even though I squinted hard, I still doubted my prior assumption that all 4 datasets should result in the same summary statistics (and therefore also regression slopes & intercepts). I visited Wikipedia and confirmed that indeed the 4 lines should be (almost) exactly the same.

Maybe it's just me but I couldn't easily see the similarity of the regression lines between the IV and the rest (and even the other 3 among themselves feel a bit iffy). I think making the regression lines go through the entire plots would drive home the idea of Anscombe's Quartet much  more decisively.

Hope this helps and doesn't take too much of your time reviewing.

Thanks!

## PR Checklist

(I took the liberty to remove the checklist items that are not so relevant for this tiny update to an example)

- [x] Has pytest style unit tests (and `pytest` passes).
- [x] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [x] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

### CODE REVIEW

**Review by jklymak — COMMENTED** [review]
We have a new method axline that seems ready-made for this case...

**Comment by baogianghoangvu** [comment]
Thank you @jklymak for your quick review! Hope this is better now.

**Review by jklymak — COMMENTED** [review]
We have been (somewhat piecemeal) adding a block at the bottom that lists the important methods used but our examples....

(i.e. look at the bottom of `examples/color/color_cycle_default.py`)

**Comment by baogianghoangvu** [comment]
Oh I see. Added.

**Review by jklymak — APPROVED** [review]

**Comment by jklymak** [comment]
Thanks @baogianghoangvu Looks great!

**Comment by baogianghoangvu** [comment]
Thank you for your guidance!

**Pull request merged**
