### PR TITLE
Add test_hlines to test_datetimes.py

### PR DESCRIPTION
**Pull request by CozyFrog**
## PR summary
I have added a datetime smoketest for `Axes.hlines` to `lib/matplotlib/tests/test_datetime.py`. This example is very similar to `Axes.axhline` (#27177) – but to test the entire functionality of `hlines`, I have done a combination of datetime.datetime/np.datetime64 arrays with both scalar and array `xmin`/`xmax` arguments.

Below is an image of the plot generated from this example code.
test_hlines

This addresses the `Axes.hlines` task from #26864.

## PR checklist

- [N/A] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [N/A] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [N/A] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [N/A] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [N/A] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Review by scottshambaugh — APPROVED** [review]

**Review by ksunden — CHANGES_REQUESTED** [review]
I think we also wish to test the `xmin`/`xmax` as dates here

**Comment by CozyFrog** [comment]
Thank you for noting that, I did not think to check `xmin`/`xmax` as dates here - I have updated this test to do so, both with singular datetime values and datetime arrays.

This is what the plot generated by this example code looks like:
hlines_datetime_xmin_max

**Comment by CozyFrog** [comment]
I added singular float arguments for xmin/xmax - I think that might be why one of the CodeCov checks did not pass.

Here is what the new plot looks like:
hlines_increased_coverage

**Comment by CozyFrog** [comment]
@ksunden @scottshambaugh could I please have some advice on why the codecov/project/tests check is not passing? It's at 98.76% "compared to [a589856](https://github.com/matplotlib/matplotlib/commit/a589856d2c1f8a5f8236808a4098a4efb341a17c)" - I don't know why it's comparing this to the test for scatter.

**Review by ksunden — APPROVED** [review]

**Comment by CozyFrog** [comment]
If anybody is having the same issue, I think it stemmed simply from the fact that my branch was not current with the main body of work. Synchronizing it fixed the issue.

**Pull request merged**
