### PR TITLE
ENH: add ginput() support to WebAgg backend

### PR DESCRIPTION
**Pull request by perimosocordiae**
Fixes gh-3730, at least for the WebAgg backend. The server will cleanly shut down after either:
1. the user sends a SIGINT (as usual for `show()` with WebAgg),
2. the specified timeout is reached, or
3. `ginput()` decides to stop the event loop (because it has the required number of input points).

I haven't tested this with a Jupyter notebook.

### CODE REVIEW

**Comment by perimosocordiae** [comment]
Looks like the Travis build errors are unrelated.

**Comment by tacaswell** [comment]
I have a vague memory of a long-ish discussion about how to stop / restart tornado with one of tornado developers...

**Comment by perimosocordiae** [comment]
As far as I know, adding a callback to the IOLoop which calls the `stop()` method is the appropriate way to do it: http://stackoverflow.com/a/38557549/10601

I'd love to add a test case for this PR, but I'm not sure where/how to add it. (In fact, I can't seem to find any webagg-specific tests.) I can say, for what it's worth, that I've been using this patch for the last few months in my day-to-day use and haven't encountered any issues.

**Comment by jklymak** [comment]
I'm going to close this as very stale, and we have full GUI web backends...

**Pull request closed without merging**
