### PR TITLE
HostAxesBase now adds appropriate _remove_method to its parasite axes.

### PR DESCRIPTION
**Pull request by productivememberofsociety666**
Fix for https://github.com/matplotlib/matplotlib/issues/4896 .
I think this should do the trick.

### CODE REVIEW

**Comment by tacaswell** [comment]
Can you also add tests and a `what_new` entry?

**Comment by productivememberofsociety666** [comment]
Hmm there seems to be a problem with removing ``twinx`` and ``twiny`` axes where the lines and ticks remain, only the numbers disappear. Will look into this later.

**Comment by productivememberofsociety666** [comment]
Ok it's because the ``twin*`` methods also screw with the host axes' visibility settings. I don't know if and how this should be fixed.

**Comment by productivememberofsociety666** [comment]
Are you sure you want a ``whats_new`` entry for this? Seems like more of a minor bug fix than something worth mentioning there...

**Comment by tacaswell** [comment]
I like to advertise when we add long standing missing functionality.

It also serves as advertisement that the remove functionality exists on all
of the other artists.

If you don't want to do it i will leave it to your judgement.

**Comment by tacaswell** [comment]
Could you reduce the tests to only having pngs ?

**Comment by productivememberofsociety666** [comment]
I'm trying to understand what is going on with the host axes' visibility settings being changed by the ``twin*`` functions. Here is what it looks like if I just set them all to invisible:
twin_axes_empty_and_removed
So the removal code works at least, but the ``twin*`` functions seem a bit inconsistent: ``twinx`` and ``twiny`` set their lines invisible and show only the ticks and numbers, whereas ``twin`` has everything visible.

**Comment by productivememberofsociety666** [comment]
Regarding the failing build, I don't know why the pictures aren't close. It works on my machine with all Python versions from 2.6 to 3.4. Fonts maybe?

**Comment by tacaswell** [comment]
Make sure that you don't have any funny rcparams set (which should not
matter as the tests _should_ be overriding that).

Also check what version of freetype you have installed against what is on
travis.

**Comment by tacaswell** [comment]
Can you also squash this down to remove the un-used images from the history?  Part of the goal is to keep the size of the repository down.

**Comment by productivememberofsociety666** [comment]
All right I took out an rcparam that set the backend to GTK3 and uploaded a slightly modified image. Now apparently all builds work except that 2.7 one, again because the image is too different. I don't understand it.

**Comment by QuLogic** [comment]
Your first few commits were made without setting your author info; you should update them for reasonable attribution.

**Comment by productivememberofsociety666** [comment]
Build passes now although I didn't change anything. The test that failed and then magically worked was ``mathfont_stix_53`` in ``test_mathext``, see https://travis-ci.org/matplotlib/matplotlib/jobs/75359652.

**Comment by tacaswell** [comment]
There is a race condition in the math text rendering tests that
intermittently fails.

**Comment by tacaswell** [comment]
I think the reason that the `twin*` functions mess with the visibility is to prevent any artifacts from rendering nominally identical artists (the ticks) on top of each other.

I think that this remove behavior should also restore the visibility settings of the host axes.

Can you also check if the twin functions mutate any other data structures in the axes (I know the normal `axes.Axes.twin*` methods do)?  That should probably be un-done as well.

**Comment by productivememberofsociety666** [comment]
I updated the tests to show better what is going on. Here is what things look like with the current ``twin*`` functionality:
old twin_axes_empty_and_removed
Like I already said, there is inconsistency between the ``twinx``/``twiny`` methods and the bare ``twin`` method (axis line visibility).

In my opinion, it would be better if all methods behaved like ``twin``, i.e. make corresponding host axes completely invisible. The following commit contains code that does just that and also make the ``_remove_method`` reverse these changes.

**Comment by tacaswell** [comment]
Awesome :+1: 

Thanks for wading into this!

I am not going to hold 1.5 for this PR, but have no problem with it sneaking in (it is far less disruptive than other open PRs).

**Comment by mdboom** [comment]
Looks like a great bugfix.  Looks like this needs a rebase, then another run through Travis, but then I'm happy to merge.

**Comment by productivememberofsociety666** [comment]
Rebase done!

**Pull request merged**
