### PR TITLE
Implement draw_markers in the cairo backend.

### PR DESCRIPTION
**Pull request by benzea**
This commit increases the speed of marker drawing in the caior backend.
It directly uses cairo paths for this. If the marker is only stroked
(and not filled) then only one drawing operation is used. If it is
filled then each marker is filled and stroked separately.

### CODE REVIEW

**Comment by tacaswell** [comment]
@benzea Did you make any progress on adding test?

**Comment by benzea** [comment]
No, I never got around to write a testcase.

**Comment by tacaswell** [comment]
@mdboom I am in favor of just merging this as-is.  After 2.5 years I do not think we are going to get tests ;)

**Comment by tacaswell** [comment]
'power cycled' to see if this still passes tests against current master.

**Comment by WeatherGod** [comment]
well, it doesn't seem to *break* anything...

**Pull request merged**
