### PR TITLE
Process clip paths the same way as regular Paths.

### LINKED ISSUE #15952: Images are clipped incorrectly with custom clip path
### Bug report

**Bug summary**

This is related to #15946, but for images. When setting a custom clip path, the image is cropped slightly incorrectly.

**Code for reproduction**

(Note, in lieu of subclassing `Axes` and `Subplot`, I've just overwritten the `Axes.patch` using the [properties that it should have](https://github.com/matplotlib/matplotlib/blob/59acd5c4e2afc2ae9191ff2daf60bd959abd8c23/lib/matplotlib/axes/_base.py#L1073-L1081)).

```python
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as mpatches

data = [[1, 1], [0, 1]]

fig, ax = plt.subplots(1, 3, figsize=(6, 2), sharex=True, sharey=True)
ax[0].set_xlim(0, 2)
ax[0].set_ylim(0, 2)
ax[0].set_title('Default patch')

ax[2].patch = mpatches.PathPatch(
    Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
    facecolor=plt.rcParams['axes.facecolor'],
    edgecolor='None',
    linewidth=0,
    snap=False,
    transform=ax[2].transAxes)
ax[2].patch.set_figure(fig)
ax[2].set_title('Custom patch')

img = []
for a in ax:
    img.append(a.imshow(data, extent=(0, 2, 0, 2), vmin=-10))

img[1].set_clip_box(None)
img[1].set_clip_path(
    Path([[0, 0], [1, 0], [1, 1], [0, 1], [0, 1]]),
    ax[1].transAxes)
ax[1].set_title('Custom clip path')

plt.show()
```

**Actual outcome**

Figure_1

If you check the antialiasing along the top spine, the first Axes is grey (f1f1f1), but the second and third are slightly yellow (f0e7a0). Note, this seems to be figure size and/or DPI dependent.

**Expected outcome**

All images should be cropped in the same way, and there should not be a difference in edges along the top of the Axes.

**Matplotlib version**
  * Operating system: Fedora 30
  * Matplotlib version: 9d00ca839e5faf10257095ad1e2bfb5296549d47
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg (probably just Agg though)
  * Python version: 3.6.3

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

Specifically, run NaN removal, clipping to figure boundary, snapping to pixel centers, and path simplification on it.

This means if you plot a Path, and then clip some other artist with it, you will get properly aligned results.

I'm not entirely sure whether it makes sense to run NaN removal and figure clipping on the clip path, but I put them in for consistency with other paths. There don't seem to be any tests that are affected by these two. The change to `lib/matplotlib/tests/baseline_images/test_offsetbox/offsetbox_clipping.png` is because the clip path is snapped and better aligns with the other path. The change to `lib/matplotlib/tests/baseline_images/test_axes/imshow_clip.png` is a minor effect of path simplification on the clip path.

Fixes #15952. It also fixes the problem in Cartopy (see SciTools/cartopy#1422) for some cases, but not all. I'll need to investigate that a bit further.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by anntzer** [comment]
mplcairo does the same (but that was really an accidental, though welcome, side effect of having a single python-path -> c++ path loader).

**Comment by anntzer** [comment]
@QuLogic milestone this to whatever sounds good to you and merge yourself?

**Comment by QuLogic** [comment]
Well, my preference is as far back as possible for Cartopy's sake, of course, but it's difficult to assess the effect since so little of the library uses clip paths itself.

**Comment by dopplershift** [comment]
I think this can quite reasonably be called a bug fix. And having it in 3.2 would make it easier to get something into the next CartoPy release...

**Comment by tacaswell** [comment]
Getting 3.2 rc3 tagged, published and publicized is on my to-do for this weekend.

**Pull request merged**
