### PR TITLE
DOC: fix version switcher 

### PR DESCRIPTION
**Pull request by jklymak**
## PR Summary

Fix version switcher now that json file is in place.

Note that changes to the json file itself will have to be merged, but the switcher is still not quite working, so lets make sure we understand that first.  

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Comment by dstansby** [comment]
I followed the link and found the JSON file, but firefox is giving me `SyntaxError: JSON.parse: unexpected character at line 105 column 1 of the JSON data` - does something need fixing in the JSON file?

**Comment by jklymak** [comment]
Maybe, looks like there is a stray comma at the end. However, not sure if that is breaking things....

**Comment by jklymak** [comment]
fixed the comma, but of course that won't be in the devdocs version, so we would have to merge that to see if that helps

**Comment by choldgraf** [comment]
@drammock is probably in a better place to provide input than me, since he built the feature! 😅

**Comment by jklymak** [comment]
The button now has some version info.  I'm hoping that when it is pushed to devdocs it will work.  However, I'm not sure - there seems to be a fair bit of JS logic checking for page consistency that I'm not sure applies to our docs.

**Comment by tacaswell** [comment]
> Another strange thing I see in the browser console is a request for a versions.html

This a long standing thing we do on the top-level index for the built docs that links to the latest version.   It is a way that we can inject changes into the old dcos without re-rendering them.

**Comment by jklymak** [comment]
Thanks @drammock That helps.  Hopefully the domain crossing stuff works - I think our devdocs and main site are basically the same (github pages).  Understood about the existing pages check....  We actually have a bunch fo redirects in our current docs to pages that have moved, but of course the old docs don't have redirects to new pages.

**Comment by drammock** [comment]
> We actually have a bunch fo redirects in our current docs to pages that have moved, but of course the old docs don't have redirects to new pages.

yeah, we have the same issue over at MNE-Python.  Users viewing old docs and using the switcher to get to current stable/dev will benefit (because the redirect page exists, the switcher will point to that), but using the switcher to go from stable/dev to older doc versions will soft-fail (go to target version's homepage) from pages that have moved.

**Comment by jklymak** [comment]
See #22261 for just changing the json

**Review by timhoffm — APPROVED** [review]

**Pull request merged**
