### PR TITLE
Fix minor bug in vertex insert

### PR DESCRIPTION
**Pull request by fuzzythecat**
- If a vertex is inserted between the first and the second vertex, it is inserted at index 0, and the polygon automatically inserts a copy at the last index to keep the starting and ending points the same. It has an effect of inserting two vertices (one under the point, and the one previously at index 0), and the whole plot is messed up afterwards. 

It is most evident when you have only two vertices on the plot.  
figure_1

After an insert:
figure_2
figure_2-2

Ensuring no new vertex is inserted at index 0 fixes the problem. 
After the fix:
figure_3

### CODE REVIEW

**Comment by anntzer** [comment]
I think this could be made clearer by using `np.insert(self.poly, [event.xdata, event.ydata], i, axis=0)` (or `i+1`, haven't checked).
Likewise the deletion code just above could use `np.delete`.
Can you make these changes?  If not it's also fine, this is already an improvement.

**Comment by fuzzythecat** [comment]
Good point! I made the changes.

**Comment by tacaswell** [comment]
@fuzzythecat I took the liberty of adding a patch that fixes a nasty recursive draw in Qt (see discussion at https://github.com/matplotlib/matplotlib/issues/9406 ) and made the re-draw lazier.

Thanks for your work on making the docs better!

**Comment by fuzzythecat** [comment]
:tada::tada:

**Pull request merged**
