### PR TITLE
ENH: add kwarg normalization function to cbook

### PR DESCRIPTION
**Pull request by tacaswell**
This is the first step to centralizing the normalizing kwarg
handling.

### CODE REVIEW

**Comment by tacaswell** [comment]
This is pulled out of #5056 (it is the first commit on that PR) and should be merged first so that we can backport this to 1.5.x (or at least 2.0) as it will help with issues like #5974

**Comment by WeatherGod** [comment]
Do we want to try applying it to the existing normalization/validation logic for cyclers? Would be interesting to see how we can apply it fo the needed key-changing feature for existing cycler objects.

**Comment by tacaswell** [comment]
Probably, but I would rather get this in and then start to use it in later PRs rather than holding this up.

**Comment by mdboom** [comment]
Cherry-picked to 1.5.x as b17cc2ca8f0e

**Comment by efiring** [comment]
This is failing on 2.6:
```
 File "/home/travis/build/matplotlib/matplotlib/venv/lib/python2.6/site-packages/matplotlib-1.5.1+48.gc6c43cc-py2.6-linux-x86_64.egg/matplotlib/cbook.py", line 2635, in normalize_kwargs

    "are not in kwargs".format(fail_keys))

ValueError: zero length field name in format
```

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/pull/6007

**Pull request merged**
