### PR TITLE
geographic directions added as alternative locations in legend

### PR DESCRIPTION
**Pull request by ChrisOKay**
Having a matlab background, I thought it might be a good idea to have similar legend locations, i.e. geographic directions such as "northwest", etc.
This eases cross-development work in a matlab to python transition.

### CODE REVIEW

**Comment by anntzer** [comment]
This is being discussed in https://github.com/matplotlib/matplotlib/pull/12679.

**Comment by ChrisOKay** [comment]
Thanks for the link. 1.5 years of discussion, I thought it would be a simple added redundancy :)

**Comment by ImportanceOfBeingErnest** [comment]
Yes, #12679 tries to do a bit more. It tries to make the make all of those location arguments consistent among the various artists that take them in, but then it turned out that it would involve a breaking change for one return type.  
If you are interested, please feel free to join in over there or even take that work over.

**Comment by ChrisOKay** [comment]
I'll definetly look into it, but since I am quite new to this topic I guess I will have a hard time figuring out all the dependencies. If I see a solution, I will give it a try.

**Pull request closed without merging**
