### PR TITLE
FIX: try to ensure 2 ticks with AutoLocator.

### LINKED ISSUE #5784: dynamic ticking (#5588) should avoid (if possible) single ticks
There's only one xtick left in `statistics/violinplot_demo.py` after #5588 got merged:
violinplot
Compare with before the patch:
violinplot_old
The old xticks were perhaps a bit cramped but there's clearly room for, say, two more xticks in the new output.
(On the other hand, this helped me catch a bug in offset text calculation logic when there's a single tick, so it's not all that bad...)

### PR DESCRIPTION
**Pull request by efiring**
replaces #6578
closes #5784

### CODE REVIEW

**Comment by tacaswell** [comment]
:+1: I am inclined to merge this so we can see what it does to the docs.

**Comment by efiring** [comment]
@tacaswell, fine with me.  I tried to build the docs locally, but failed again; something wants a missing matplotlib_icon.py.  I haven't tracked that down.  I don't understand why the docs build *didn't* fail in travis on this PR, given that locally I am starting with `git clean -dfx`.

**Comment by jenshnielsen** [comment]
I'm not sure that fixes your issue but as part of #6585 I removed matplotlib_icon.py from backend_driver.py

**Comment by efiring** [comment]
I've built the docs locally, and I think this PR is working as intended.  I think it is ready to be merged.

**Pull request merged**
