### PR TITLE
FIX: remove incorrect error checking

### PR DESCRIPTION
**Pull request by tacaswell**
Currently fails with qt5

### CODE REVIEW

**Comment by sandrotosi** [comment]
this indeed fix teh errors with the unittest raising that exception, but now that it passes, other errors came out:

```
======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_fig_close
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 40, in test_fig_close
    fig = plt.figure()
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_shift
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 78, in test_shift
    'A')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_lower
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 86, in test_lower
    'a')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_control
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 94, in test_control
    'ctrl+a')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_unicode_upper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 102, in test_unicode_upper
    unichr(193))
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_unicode_lower
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 110, in test_unicode_lower
    unichr(225))
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_alt_control
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 118, in test_alt_control
    'alt+control')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_control_alt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 126, in test_control_alt
    'ctrl+alt')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_modifier_order
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 134, in test_modifier_order
    'ctrl+alt+super+' + unichr(225))
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_backspace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 142, in test_backspace
    'backspace')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_backspace_mod
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 150, in test_backspace_mod
    'ctrl+backspace')
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)

======================================================================
ERROR: matplotlib.tests.test_backend_qt4.test_non_unicode_key
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 118, in wrapped_function
    func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 53, in failer
    result = f(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 158, in test_non_unicode_key
    None)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/testing/decorators.py", line 371, in backend_switcher
    result = func(*args, **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/tests/test_backend_qt4.py", line 59, in assert_correct_key
    qt_canvas = plt.figure().canvas
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4agg.py", line 71, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/tmp/buildd/matplotlib-1.5.0~rc2/build/lib.linux-x86_64-2.7/matplotlib/backends/backend_qt4.py", line 71, in __init__
    QtWidgets.QWidget.__init__(self)
TypeError: __init__() takes exactly 2 arguments (1 given)
```

**Comment by tacaswell** [comment]
That looks like there is a cross between qt4 vs qt5 ...

**Comment by jenshnielsen** [comment]
I can reproduce that issue with both qt 4 and 5 installed. It looks like something has gotten crossed in the refactoring.

**Comment by tacaswell** [comment]
@jenshnielsen What backend is this with?

**Comment by jenshnielsen** [comment]
That was the qt4 tests in the test suite

**Comment by tacaswell** [comment]
@jenshnielsen Took me a while, but I got there.

**Pull request merged**
