### PR TITLE
Deprecate `get_grid_positions(..., raw=True)`.

### PR DESCRIPTION
**Pull request by anntzer**
The API was added in f8dfea7 (@jklymak) but never actually used anywhere.

## PR Checklist

**Tests and Styling**
- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).

**Documentation**
- [ ] New features are documented, with examples if plot related.
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).
- [ ] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).

### CODE REVIEW

**Review by QuLogic — APPROVED** [review]

**Review by timhoffm — APPROVED** [review]
But @jklymak should finally decide whether this  won’t be needed in constrained layout in the future.

**Comment by jklymak** [comment]
I agree we don't use this anymore.  OTOH I'm not sure why we would bother deprecating it?

**Comment by timhoffm** [comment]
Less functionality and API surface is better from a maintainability and usability point of view. If we don’t have a good reason to keep this - for us or the user, let’s get rid of it.

**Comment by jklymak** [comment]
I guess that is my point - it seems useful to provide a geometrical division of the figure without having to manually set all the subplot_params to zero and then potentially have to restore them.

**Comment by QuLogic** [comment]
I don't think I can find anyone using it on GitHub, only forks of us/fully committed venvs.

**Comment by anntzer** [comment]
I don't have a very strong opinion there; my PoV was basically the one expressed by @timhoffm at https://github.com/matplotlib/matplotlib/pull/23572#issuecomment-1209457805.  If @jklymak feels strongly about this we can close it too.

**Comment by timhoffm** [comment]
@jklymak please speak up if you want to keep this.

**Comment by jklymak** [comment]
I spoke up above - I don't see that this is worth a deprecation song and dance, but if you want it out, I'm not blocking.

**Comment by anntzer** [comment]
Let's let @tacaswell make the call on that one.

**Review by tacaswell — APPROVED** [review]
I agree to deprecate this.

We do not use, we do not think anyone else uses it and it is a somewhat confusing API (it in not clear what "raw" means).

**Pull request merged**
