### PR TITLE
Backport PR #23442 on branch v3.7.x (Remove need to detect math mode in pgf strings)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #23442: Remove need to detect math mode in pgf strings

### CODE REVIEW

**Comment by tacaswell** [comment]
This seems a bit risky to backport between rc and final (because I do not understand it), happy to be told it is fine by someone who does :)

**Comment by ksunden** [comment]
I was admittedly on the bubble about whether I wanted to backport or not (or hold off on merging until 3.7.0 final was out but still backport for 3.7.1, I guess)

Ended up at "probably not requisite of being pushed all the way to 3.8, don't see anything that requires _changes_"

I welcome @anntzer's thoughts as the original author here.

**Comment by anntzer** [comment]
The PR does fix a long-standing bug, but the fix is a bit subtle and I don't think it's overly urgent to get it in.

**Comment by jklymak** [comment]
I'll close so that we have to live with it on master for a while, but feel free to re-open and resubmit, I don't feel strongly about it (or particularly understand the PR details)

**Pull request closed without merging**
