### PR TITLE
ps: Fix anchoring of rotated usetex text

### LINKED ISSUE #9158: Angled text not placed correctly with usetex in EPS
### Bug report

**Bug summary**
The text alignment of `.text(..., ha="center", va="center", ...)` whilst using `matplotlib.rc("text", usetex=True)` and saving as `.eps`  is not centred.
However the output is centred for `.pdf` and `.png`

**Code for reproduction**
```python
import numpy

from matplotlib import pyplot
from matplotlib import gridspec

import matplotlib
matplotlib.rc("text", usetex=True)

def plot(file_path):
    gs = gridspec.GridSpec(
            3, 1,
            wspace=0.0, hspace=0.0
            )
    fig = pyplot.figure()

    # Add plots
    for sub_plot in gs:
        ax = fig.add_subplot(sub_plot)

    # position text based on location of subplots
    fig.tight_layout()
    row_bottom, row_top, col_left, col_right = gs.get_grid_positions(fig)

    # Finding the vertical centre like this because the axis label for
    # the plots I create  should be shared with only some of the subplots
    vertical_centre = numpy.mean([row_bottom[-1], row_top[0]])
    fig.text(
            0.01, vertical_centre,
            r"$\mathrm{Response \, \left(Normalised\right)}$",
            ha="center", va="center",
            rotation="vertical",
            transform=fig.transFigure,
            fontsize=35.  # lage size to emphasize error
            )

    fig.savefig(file_path, bbox_inches="tight")
    pyplot.close(fig)

plot("./test_eps.eps")
plot("./test_pdf.pdf")
plot("./test_png.png")
```

**Actual outcome**
`./test_eps.eps`
test_eps

`./test_pdf.pdf`
test_pdf

`./test_png.png`
test_png

**Expected outcome**
Ideally the output of `./test_eps.eps` should match the other two figures.

**System**
  * Operating System: macOS 10.12.6 
  * Matplotlib Version: 2.0.2 (Conda: build string: np112py27_0, channel: defaults)
  * Python Version: 2.7.13
  * Conda Version: 4.3.24

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

In PostScript, usetex text is anchored to the bottom left for replacement by psfrag, while in Matplotlib, text is placed by the baseline usually. So PostScript subtracts the text depth from the y position, but for rotated text, this subtraction should also be in a rotated direction.

I added test images for all 4 formats (eps + defaults) which might be a bit overkill, but as this problem would only manifest when you looked at the result, it was the only way to check. And while I did add markers for checking the alignment, I really just compared `.eps` with `.pdf` or `.png` as those appeared to be correct already.

Fixes #9158

## PR Checklist

**Linked Issue**
- [x] Added "closes #0000" in the PR description to link it to the original issue.

**Documentation and Tests**
- [x] Has pytest style unit tests (and `pytest` passes)
- [n/a] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [n/a] New plotting related features are documented with examples.

**Release Notes**
- [n/a] New features are marked with a `.. versionadded::` directive in the docstring and documented in `doc/users/next_whats_new/`
- [n/a] API changes are marked with a `.. versionchanged::` directive in the docstring and documented in `doc/api/next_api_changes/`
- [n/a] Release notes conform with instructions in  `next_whats_new/README.rst` or `next_api_changes/README.rst`

### CODE REVIEW

**Comment by QuLogic** [comment]
Hmm, locally, I'm already seeing a failure of `test_multi_font_type3[eps]` and `test_multi_font_type42[eps]`, so the failure here is probably a similar manifestation of that problem. I'm guessing Fedora has a newer version of Ghostscript or similar, which is causing the small differences.

**Comment by QuLogic** [comment]
Can't reproduce in Ubuntu 22.04 WSL; probably an update to Ghostscript or similar.

**Comment by QuLogic** [comment]
Since we recently moved a CI to Ubuntu 22.04, I rebased this to test against it. As expected above, it does pass on that system. Looking at the result on 20.04, it's a bit unexpected as only the _markers on the far right column_ are missing.

**Comment by QuLogic** [comment]
Since Fedora is on Ghostscript 9.56.1 or above, Ubuntu 20.04 is 9.50, and Ubuntu 22.04 is 9.55, I've set an increased tolerance for any version < 9.55. The Ubuntu releases between those don't seem to have available repos, so I don't want to spend too much time investigating further into it.

**Review by tacaswell — APPROVED** [review]

**Review by tacaswell — APPROVED** [review]

**Review by ksunden — APPROVED** [review]

**Pull request merged**
