### PR TITLE
Always install mpl_toolkits.

### PR DESCRIPTION
**Pull request by anntzer**
I don't think there's really a reason to make this configurable.  Also
work towards auto-registering mplot3d (https://github.com/matplotlib/matplotlib/pull/12249#issuecomment-424327729).

This PR also ensures that mpl_toolkits baseline images don't get
installed if mpl_toolkits tests are not installed (previously, the
baseline images would incorrectly be installed; that behavior goes back
to at least mpl1.5, and is also present on PyPI wheels).  Given that the
baseline images are actually much heavier than the sources, this commit
will actually help *decrease* the weight of wheels by making baseline
images truly optional.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
attn @QuLogic @sandrotosi @felixonmars Do any of you use this option when packaging mpl?

**Comment by tacaswell** [comment]
Anyone can dismiss my review on feedback from packagers.

**Comment by QuLogic** [comment]
The only reason we use these options is to set them to `True`. While image test data is split, that's just done by specifying what files to include in each subpackage.

**Comment by anntzer** [comment]
Wouldn't bother with it, as we're yet to find anyone who doesn't install them...

**Pull request merged**
