### PR TITLE
Merge v2.0.x into master

### PR DESCRIPTION
**Pull request by QuLogic**
There were some conflicts in some tests that I added, plus some documentation stuff.

### CODE REVIEW

**Comment by QuLogic** [comment]
OK, I see in Travis' log that it created the build for this PR, but it doesn't seem to exist.

**Comment by dstansby** [comment]
https://travis-ci.org/matplotlib/matplotlib/builds/215421660 ? (I've restarted the flaky builds on that job)

**Comment by dstansby** [comment]
Hmm, looks like `test_patheffects::test_collection()` is actually a real test failure.

**Comment by QuLogic** [comment]
I can't seem to load that job. Anyway, I think in this case I updated the png and forgot about the other extensions because they all passed for me. For some reason that test is slightly different on `master` whereas the others could be updated straight from `v2.0.x`.

**Comment by QuLogic** [comment]
Sigh, now that I'm running the middle of Monday, I need to wait for macOS builders again.

If this passes, I'm going to push directly; no need for an extra merge commit.

**Pull request merged**
