### PR TITLE
Doc cards user explain

### PR DESCRIPTION
**Pull request by jklymak**
## PR summary

- This PR adds a visible TOC to the galleries in users/explain (color, animations, text).
- This PR makes each subject in users/explain/index a card with depth = 2 table of contents.

Follow up to #26110

## PR checklist

- [ ] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [ ] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [ ] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [ ] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [ ] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by jklymak** [comment]
https://output.circle-artifacts.com/output/job/4ebd326b-04c5-48e8-89cb-64ab047d3c0c/artifacts/0/doc/build/html/users/explain/index.html
look

**Comment by rcomer** [comment]
Are we expecting to populate the `Axis` section in time for the 3.8 release?  If not, would it be better to hide that from this top level index for now?

**Comment by jklymak** [comment]
I think we need something like an axis section. I got started and axis/axes/spines are all pretty intertwined so maybe it all has to go under axes. However this will be done before 3.8 is finalized, though before the rc is unlikely.

**Review by rcomer — APPROVED** [review]
In that case, this looks good to me.

**Comment by rcomer** [comment]
This change does not seem to have made its way onto devdocs
https://matplotlib.org/devdocs/users/index.html

But the more recent change from #26148 has
https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.art3d.Line3D.html#mpl_toolkits.mplot3d.art3d.Line3D

😕

**Pull request merged**
