### PR TITLE
Support data reference for hexbin() parameter C

### LINKED ISSUE #18097: Feature Request: Allow hexbin to use a string for parameter C to refer to column in data (DataFrame)
### Feature request

Currently the `hexbin` function allows for its first two parameters `x` and `y` to be strings of `data` (usually a pandas DataFrame), but not `C`

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame(np.random.rand(100000, 3))
df.columns = ['a', 'b', 'c']
plt.hexbin('a', 'b', C='c', data=df)
```

Results in `IndexError: string index out of range`

Currently, you must pass in `C` as a Series/array
plt.hexbin('a', 'b', C=df['c'], data=df)

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Closes #18097.

### CODE REVIEW

**Comment by jklymak** [comment]
Easy!  But hard to tell if it worked - is it OK just to assume the preprocessor works because it works on other functions?

**Comment by timhoffm** [comment]
I'll answer that with a yes. The preprocessor itself is tested. We don't want to test every variant of possible calls to the plotting functions.

**Comment by jklymak** [comment]
Sure, just wanted to make sure it was tested somewhere.

**Comment by dopplershift** [comment]
Failing tests are:
```
lib/matplotlib/tests/test_animation.py::test_draw_frame
lib/matplotlib/tests/test_arrow_patches.py::test_fancyarrow[pdf]
```
They're unrelated and passing here for me on OSX on Python 3.8...so do we ignore or re-run?

**Comment by jklymak** [comment]
Those also failed on #18100.  So I don't think it is these PRs, though its possible it is a previous PR that has worked its way into master...

**Pull request merged**
