### PR TITLE
Do not turn on interactive mode on in example script

### PR DESCRIPTION
**Pull request by cgohlke**
Also, please check [simple_plot_fps.py](https://github.com/matplotlib/matplotlib/blob/master/examples/pylab_examples/simple_plot_fps.py), which produces an [empty plot](http://matplotlib.org/examples/pylab_examples/simple_plot_fps.html).

### CODE REVIEW

**Comment by efiring** [comment]
backported to v2.x as db6182a
backported to v1.5.x as 02cdbf3

**Comment by QuLogic** [comment]
Not sure why it needed backporting to v2.x since it'll cascade from v1.5.x, but I fixed the link to the commit.

**Comment by efiring** [comment]
@qulogic,  Thanks, that was just a symptom of my ignorance.  What was wrong with the link, and what did you have to do?

**Comment by QuLogic** [comment]
Probably just a typing error; it was db6182a instead of db6a82a.

**Pull request merged**
