### PR TITLE
Improve code generated by boilerplate.py

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

This PR improves the code generated by `boilerplate.py`. In particular

- make the boilerplate-no-change-comment fit on one line (just aesthetics).
- make the docstrings of the colormap-functions PEP8 conform.
- change the code of the colormap functions to just calling `set_colormap` (the code from there was just duplicated). Below is an example of a changed colormap function as it's not easily readable in the diff.

Before:
~~~
def autumn():
    '''
    set the default colormap to autumn and apply to current image if any.
    See help(colormaps) for more information
    '''
    rc('image', cmap='autumn')
    im = gci()
    if im is not None:
        im.set_cmap(cm.autumn)
~~~

After:
~~~
def autumn():
    """
    Set the colormap to "autumn".

    This changes the default colormap as well as the colormap of the current
    image if there is one. See ``help(colormaps)`` for more information.
    """
    set_cmap("autumn")
~~~

### CODE REVIEW

**Comment by anntzer** [comment]
See also #9173...

**Comment by dstansby** [comment]
I think this might need a rebase to make the travis job pass

**Comment by timhoffm** [comment]
Do I have to do something about the codecov before merge? AFAICS none of the colormaps functions is tested and therefore all changed code is untested as well. But I don't think it's necessary to test these functions as they are trivial.

**Comment by jklymak** [comment]
I think it not passing codecov is fine.  I think if you want to be fancy you could tell codecov to not look at these files.  Not merging, because this is a big enough change someone else should also look at it.

**Pull request merged**
