### PR TITLE
Update axes3d.py

### PR DESCRIPTION
**Pull request by aradfarahani**
## PR summary

This pull request adds the `add_faces` method to enhance 3D plotting capabilities. This change is required to allow users to easily add faces to 3D plots with specified colors and thicknesses. It addresses the need for more flexible 3D plotting options.

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [x] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/api_changes.html#announce-changes-deprecations-and-new-features)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Comment by rcomer** [comment]
Thank you for your contribution @aradfarahani.  I think we need more information to understand the requirement for this.  Could you post some example code and output to show how it would be used?

**Comment by aradfarahani** [comment]
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection

fig = plt.figure()
ax = plt.gca(projection='3d')

poly1 = PolyCollection([[[-2,-2], [-2,2], [0,3], [2,2], [2,-2]]], color='red')
poly2 = PolyCollection([[[-1,-1], [-1,1], [1,1], [1,-1]]], color='blue')
poly3 = PolyCollection([[[0,0], [1,1], [1,0]]],color='green')

ax.add_collection3d(poly1, zs=0, zdir='z')
ax.add_collection3d(poly2, zs=1, zdir='z')
ax.add_collection3d(poly3, zs=2, zdir='z')

plt.show()



from mpl_toolkits.mplot3d import Axes3Dfrom matplotlib.collections import PolyCollectionfrom mpl_toolkits.mplot3d.art3d import Poly3DCollectionimport matplotlib.pyplot as pltfig = plt.figure()ax = Axes3D(fig)ax.set_xlim3d(-5, 5)ax.set_ylim3d(-5, 5)ax.set_zlim3d(-5, 5)"""This method takes a list of 2D coordinates and a z-coordinate, and returns a list of 3D coordinates with the z-coordinate added on """def make_3D_coordinate_list(coordinate_list, z_val): return [coordinate+[z_val] for coordinate in coordinate_list]"""This method iterates over pairs of coordinates in a coordinate list (where the first and last coordinate are identical)and constructs a "face" by calculating two new points from each pair of coordinates, adding them to the Axes3D objectArguments:coordinate_list --- 2D list of lists of coordinates in 3 dimensionsface_color --- a string specifying the color of the facethickness --- a number specifying how far in the z-direction the face of the prism should extend down"""def add_faces(coordinate_list, face_color, thickness): for i in range(len(coordinate_list) - 1): new_coordinate_list = [coordinate_list[i], coordinate_list[i+1]] new_coordinate_list.append([x + y for x, y in zip(coordinate_list[i+1], [0, 0, -1*thickness])]) new_coordinate_list.append([x + y for x, y in zip(coordinate_list[i], [0, 0, -1*thickness])]) new_coordinate_list.append(coordinate_list[i]) print(f"new coordinate list: {new_coordinate_list}") ax.add_collection(Poly3DCollection([new_coordinate_list], color=face_color))## make sure the coordinates cycle around from beginning to endpoly1_coordinate_list = [[-2,-2], [-2,2], [0,3], [2,2], [2,-2], [-2,-2]]poly2_coordinate_list = [[-1,-1], [-1,1], [1,1], [1,-1], [-1,-1]]poly3_coordinate_list = [[0,0], [1,1], [1,0], [0,0]]poly1_3dcoordinate_list = make_3D_coordinate_list(poly1_coordinate_list, 0)poly2_3dcoordinate_list = make_3D_coordinate_list(poly2_coordinate_list, 1)poly3_3dcoordinate_list = make_3D_coordinate_list(poly3_coordinate_list, 2)poly1 = Poly3DCollection([poly1_3dcoordinate_list], color='red')poly2 = Poly3DCollection([poly2_3dcoordinate_list], color='blue')poly3 = Poly3DCollection([poly3_3dcoordinate_list], color='green')ax.add_collection3d(poly1)ax.add_collection3d(poly2)ax.add_collection3d(poly3)add_faces(poly1_3dcoordinate_list, 'pink', 1)add_faces(poly2_3dcoordinate_list, 'lightblue', 1)add_faces(poly3_3dcoordinate_list, 'lightgreen', 1)plt.show()




On Sunday, August 11, 2024, 6:44 PM, Ruth Comer ***@***.***> wrote:




Thank you for your contribution @aradfarahani. I think we need more information to understand the requirement for this. Could you post some example code and output to show how it would be used?

**Comment by aradfarahani** [comment]
> @aradfarahani is there an open issue or something else you can point to for **why** you're implementing this? 

I was making a 3D geoelectrical model that was supposed to display data at different depths to be displayed as a section. After developing the layers, they were just sheets or layer and needed to be connected. In general, it can be useful for geological/geophysical studies.

**Comment by aradfarahani** [comment]
> Thanks! Can you provide an example of the types of visualization you're trying to achieve? 

For Sure!

Before:

image


After: 

image

**Comment by timhoffm** [comment]
AFAICS, what you have implemented is a subset of the [fill_between](https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.fill_between.html) API. For example, you could do

```
x = [-1, -1, 1, 1]
y = [-1, 1, 1, -1]
z0 = 1
z1 = 2
ax.fill_between(x, y, z0, x, y, z1)
```

Is that sufficient for you?

**Comment by scottshambaugh** [comment]
Hi @aradfarahani, I'm going to close this as won't-do since your use case does seem to be covered by the newly added 3D `fill_between` that will be released in v3.10. Please feel free to open a new issue if you are looking for something different.

**Pull request closed without merging**
