### PR TITLE
Fix Boxplot Outlier and Whisker Calculation

### PR DESCRIPTION
**Pull request by ChiefTeef**
I noticed that the boxplot's generated by seaborn were quite different than the ones generated by pandas. I traced the error back to this document in "boxplot_stats". Made corrections to make it calculate the actual whisker ranges and outliers.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Do you have a reference to support this change in how they values are computed?  This is clearly not an typo, but an intentional choice that was previously made.

attn @phobson

**Comment by phobson** [comment]
@ChiefTeef thanks for bringing this to our attention. Do you have an example dataset you can share that produces results that you think are wrong? Could you also provide the results you'd expect to get?

**Comment by phobson** [comment]
@ChiefTeef also, I'd like too see an references you might have that support this change.

**Comment by ChiefTeef** [comment]
Hi,

I've included a snippet here but have also put it on gitHub [here](https://github.com/ChiefTeef/matplotlib/blob/patch-1/MPL_Whisker_adjustment_test.ipynb).

`import pandas as pd
import numpy as np
import matplotlib.cbook as cbook

new_list = [0.0471054, 0.0262474, 0.12289739999999999, 0.1379574, 0.1473904, 
            0.24473540000000002, 0.2560634, 0.0769904, 0.1388934, 0.0989914, 
            0.10793639999999999]
x = np.asarray(df['col2'])
original = cbook.boxplot_stats(x)

whis=1.5
stats = {}
stats['mean'] = np.mean(x)
q1, med, q3 = np.percentile(x, [25, 50, 75])
stats['iqr'] = q3 - q1

loval = q1 - whis * stats['iqr']
hival = q3 + whis * stats['iqr']

if hival >= np.max(x):
  stats['whishi'] = np.max(x)
else:
  stats['whishi'] = hival

if loval <= np.min(x):
  stats['whislo'] = np.min(x)
else:
  stats['whislo'] = loval

stats['fliers'] = np.hstack([
                             x[x < stats['whislo']],
                             x[x > stats['whishi']],
                             ])

stats['q1'], stats['med'], stats['q3'] = q1, med, q3
print("High Whisker as outputted by cookbook: {}".format(original[0]['whishi']))
print("High Whisker adjusted: {}".format(stats['whishi']))

`

**Comment by phobson** [comment]
@ChiefTeef thanks for the the additional info. At the moment, I don't agree with this change. My understanding, based on the last time I read Tukey's paper, is that whiskers show the last points in the dataset within the high & low values. Your example produces a whisker that does not have a corresponding value in the dataset. 

If you an provide a reference (other than the pandas source code) that documents this behavior as correct, I'd love to include this change.

**Comment by ChiefTeef** [comment]
Oh, I see now. This is my misgiving. I'll close it out. 

Thanks,

**Comment by phobson** [comment]
@ChiefTeef thanks for taking to the time to try to improve matplotlib. If you think now think that pandas is correctly drawing their boxplots, I would encourage you to raise a corresponding issue over there.

**Pull request closed without merging**
