### PR TITLE
Merge of #5492 to v2.0.x branch

### PR DESCRIPTION
**Pull request by mdboom**
Just running this through a pull request to have Travis run over it.

### CODE REVIEW

**Comment by WeatherGod** [comment]
uh, yeah... that crashed and burned.
`AttributeError: module 'matplotlib.tests' has no attribute 'set_font_settings_for_testing'`

**Comment by mdboom** [comment]
Ok.  I think this is good to go now.

**Comment by tacaswell** [comment]
in a fun test of how gh works, I pushed the tip of this branch to matplotlib/v2.0.x and it seems to have coped admirably.

**Comment by WeatherGod** [comment]
huh? there are 301 files listed as changed here. Is that correct?

**Comment by tacaswell** [comment]
interesting.  If you look at this in gitk it looks ok.  I wonder what it is diffing as the sha of both matplotlib/v2.0.x and mdboom/v2.0.x are the same

https://github.com/matplotlib/matplotlib/tree/v2.0.x  ( deeec9c )
https://github.com/matplotlib/matplotlib/mdboom/v2.0.x (  deeec9c )

**Comment by mdboom** [comment]
Interesting.  It definitely didn't look like that what I created this PR.  Some sort of display error when the commits are identical, maybe?  In any event, `git log` looks fine on matplotlib/v2.0.x so I don't think there's a cause for alarm.

**Comment by tacaswell** [comment]
Created https://github.com/matplotlib/matplotlib/pull/5512 to do the next merge up the chain.

**Pull request merged**
