### PR TITLE
Update vlines example with axes wide lines.

### PR DESCRIPTION
**Pull request by bjodah**
Add transform to vline example (as discussed [here]
(https://github.com/matplotlib/matplotlib/issues/5896#issuecomment-273818416) )

@tacaswell was this what you had in mind?

### CODE REVIEW

**Comment by anntzer** [comment]
Actually you can just do
```
ax.vlines(x, 0, 1, transform=ax.get_xaxis_transform())
```
which is quite simpler.

**Comment by phobson** [comment]
In addition to what @anntzer said, would you mind making the example's docstring sphinx-gallery compatible? 

Here's a PR that did just that for a few examples: https://github.com/matplotlib/matplotlib/pull/7331/files

The basic format for that is as follows:

```python
"""
====================
Title of the example
====================

A more detailed description of the example. Discuss what
each subplot is demonstrating and talk about broader
concepts.
"""

import numpy as np
import matplotlib.pyplot as plt

# yada yada yada

############################################################################
# You can also include :math:`math` inline, or as separate equations:
#
# .. math::
#
#    \exp(j\pi) = -1

plt.show()

```

**Comment by NelleV** [comment]
Hi @bjodah 
Do you think you'd have time to finish up the minor comments on this PR? If you need help on anything, don't hesitate to ask.
N

**Comment by NelleV** [comment]
I've added a small commit adding the docstring.

**Comment by QuLogic** [comment]
Build failure is unrelated PEP8 issues.

**Pull request merged**
