### PR TITLE
Fix negative annotations xycoords.

### PR DESCRIPTION
**Pull request by myshen**
Use top-right as translation reference point when xycoords are given in
"point" or "pixel" and x or y are negative. Logic based on
_get_xy_legacy removed in a65151be33b7b50fd9f40c72c5b3e965685cc13b.

### CODE REVIEW

**Comment by tacaswell** [comment]
Something looks wrong in the png output.

**Comment by myshen** [comment]
I missed editing one of the _get_xy_transform calls, but I don't think that is the cause of weird PNG output. Running the same test without the changes to text.py results in similar weirdness. I think it has to do with the particular coordinates in the test and the DPI. I will update the request for the additional _get_xy_transform but am unsure of the PNG weirdness.

**Comment by tacaswell** [comment]
I think the issue is just that the test strings fall on top of each other.
Tweaking the arguments should be enough.

**Comment by myshen** [comment]
162239f has the additional _get_xy_transform as wel as tweaked strings.

**Comment by tacaswell** [comment]
I am going to merge this on my local machine so that I can remove the pdf and svg tests (see https://github.com/tacaswell/matplotlib/commit/d6e15779e9588d8d2f58864d7ba435f666cb0326), I am just waiting for the tests to pass on travis before pushing to upstream.

**Comment by tacaswell** [comment]
Merged as d6e15779e9588d8d2f58864d7ba435f666cb0326

**Comment by tacaswell** [comment]
cherry-picked as cf2350073c2341387ce71da7963a37e7237eaeb8

**Pull request closed without merging**
