### PR TITLE
Add ninja to Cygwin builder

### PR DESCRIPTION
**Pull request by QuLogic**
## PR summary

Since there are no contourpy wheels, it must be built from source, and pre-packaged ninja is better than trying to build from sdist. This was always done, but broke when contourpy switched to Meson.

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by QuLogic** [comment]
I think this failed because we need a `contourpy` release with https://github.com/contourpy/contourpy/pull/260 included so that it doesn't try to pull in `ninja` from PyPI, and uses our existing Cygwin copy.

**Comment by ianthomas23** [comment]
Maybe the best workaround until the next contourpy release is to explicitly build it without build isolation, something like  (unchecked):

```bash
python -m pip install meson-python pybind11
python -m pip install --no-build-isolation contourpy
```

**Comment by QuLogic** [comment]
It looks like that has worked after a couple tries.

**Review by ianthomas23 — APPROVED** [review]
LGTM

**Pull request merged**
