### PR TITLE
Revert "Use atleast_3d instead of ensure_3d"

### PR DESCRIPTION
**Pull request by cimarronm**
This reverts commit 2f5a633b1ac469f9c958a065896d832d94db0883.
numpy.atleast_3d does not convert an empty array properly.

### CODE REVIEW

**Comment by cimarronm** [comment]
proposed fix for issue #5185

**Comment by mdboom** [comment]
Cc: @jkseppan, as the author of the original commit.

**Comment by tacaswell** [comment]
The doc failure is fixed on 1.5.x, will merge over now.

I am still unclear on why this results in the intermittent failure and I could not reproduce this in linux.

**Comment by jkseppan** [comment]
I'm fine with this going in, but it sounds odd that this would fix an intermittent failure. Is the use of `atleast_3d` causing reads of uninitialized data in our extension code? If so, I would suspect that the extension code is still broken in some way.

**Comment by jenshnielsen** [comment]
@jkseppan Reading uninitialized data sounds like the only explanation I can think of. Unfortunately I don't have any experience with running valgrind or such on python extensions

**Comment by mdboom** [comment]
I guess our understanding of this comes down to:

@cimarronm
> numpy.atleast_3d does not convert an empty array properly.

Can you elaborate?  

```
ython 3.4.3 |Continuum Analytics, Inc.| (default, Mar  6 2015, 12:07:41)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.10.1'
>>> np.atleast_3d([])
array([], shape=(1, 0, 1), dtype=float64)
```

**Comment by cimarronm** [comment]
I believe it is due to out-of-bound memory access which is causing this random behavior. I tried to give some more insight in #5185 on what is happening in the path c++ extension code where it goes bad.

**Comment by mdboom** [comment]
Superceded by #5274.  @cimarronm: Thanks for all your help identifying the issue!

**Pull request closed without merging**
