### PR TITLE
Allow turning off minor ticks on Colorbar with LogNorm

### LINKED ISSUE #13257: Allow turning off minorticks for Colorbar with LogNorm?
**Summary** 

MPL 3 introduces minorticks on Colorbar. These are enabled by default for LogNorm.

If the user sets custom tick marks for LogNorm, the minor ticks become confusing in my opinion. 

**Example**

```python

fig, ax = plt.subplots()

data = np.clip(randn(250, 250)*1000, 0, 1000)

cax = ax.imshow(data, norm=mpl.colors.LogNorm(vmin=1, vmax=1000))
cbar = fig.colorbar(cax, format='%d')
cbar.set_ticks([5, 50, 500])
```

Which produces,

mpl3_lognorm

**Discussion**

There is already the method ``Colorbar.minorticks_off``, however it has a check that if the axis is log, then do nothing.

**Request**

The minor tickmarks add confusion here in my opinion. Can we have the option to turn them off via the existing ``Colorbar.minorticks_off``?

### PR DESCRIPTION
**Pull request by LevN0**
Allow turning off minor ticks on Colorbar with LogNorm

## PR Summary

Closes #13257. 

Allows disabling minor ticks for Colorbar when it has LogNorm. 

## Before

Minor ticks can be disabled for all norms except LogNorm.

The following example is intended to show that when having arbitrary major tick marks, the minor tick marks add rather than remove confusion. Example,

```python

fig, ax = plt.subplots()

data = np.clip(randn(250, 250)*1000, 0, 1000)

cax = ax.imshow(data, norm=mpl.colors.LogNorm(vmin=1, vmax=1000))
cbar = fig.colorbar(cax, format='%d', ticks=[5, 50, 500])
```

Produces,

## After

Once minor ticks can be disabled even for LogNorm, calling cbar.minorticks_off() will leave only major ticks in the above figure.

## Allow minorticks back on for LogNorm as well

Since minor ticks can now be turned off for LogNorm, makes sense to allow turning them back on for LogNorm too. 

Previously they would be enabled in ``ColorbarBase.update_ticks`` for LogNorm by default, however minorticks_off and minorticks_off was in ``Colorbar``. These have been moved, in part so that ``update_ticks`` can take advantage of them.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by jklymak** [comment]
https://github.com/matplotlib/matplotlib/pull/11584#discussion_r200784423  Looks to just have been a misunderstanding....

**Comment by jklymak** [comment]
> Do not know why minor ticks are enabled in ColorbarBase for LogNorm but for everything else the methods are in Colorbar.

That might just be a mistake?

**Comment by jklymak** [comment]
I actually think the minor tick methods should go on `ColorbarBase`.  The only reason for `Colorbar` (I think) is to add a mappable to the the colorbar.

**Comment by NelleV** [comment]
This looks good! Can you add a unit test?

**Comment by LevN0** [comment]
Made an attempt.

**Comment by LevN0** [comment]
Thank you everyone for the guidance, especially @jklymak.

**Pull request merged**
