### PR TITLE
Updated Random Number Generation in Numpy

### LINKED ISSUE #19670: The Recommended Random Number Generation In NumPy
### Problem

Matplotlib documentation still uses old method of random number generation in NumPy. I think we can update the code to use newer method. Newer method was intropduced in NumPy 1.17 and recommended by NumPy over the older method (even though the older method still works)

* I found [histogram example](https://matplotlib.org/stable/gallery/statistics/hist.html) can be updated with newer code.

### Suggested Improvement

* We can change the code to shown in [this GitHub gist](https://gist.github.com/ArnuldOnData/3d298ccb3f4ba5b94006bdc55b8ea3d3)
* Entire documenation regarding recommended method is in [NumPy docs](https://numpy.org/doc/stable/reference/random/index.html#random-quick-start)  
* Here is a visualization/output from the code in gist above: 

matplotlib-numpy-random

**Matplotlib version**

  * Operating system: **Arch Linux**
  * Matplotlib version: **3.3.4** (matplotlib.__version__)
  * Python version: **3.9.2**  (platform.python_version())
  * Matplotlib documentation version: **Doc version v3.3.4** (as seen at the bottom of the [histogram page](https://matplotlib.org/stable/gallery/statistics/hist.html) )

### PR DESCRIPTION
**Pull request by rajpratyush**
## PR Summary
closes #19670 
## PR Checklist

- [ ] Has pytest style unit tests (and `pytest` passes).
- [ ] Is [Flake 8](https://flake8.pycqa.org/en/latest/) compliant (run `flake8` on changed files to check).
- [x] New features are documented, with examples if plot related.
- [x] Documentation is sphinx and numpydoc compliant (the docs should [build](https://matplotlib.org/devel/documenting_mpl.html#building-the-docs) without error).
- [ ] Conforms to Matplotlib style conventions (install `flake8-docstrings` and run `flake8 --docstring-convention=all`).
- [ ] New features have an entry in `doc/users/next_whats_new/` (follow instructions in README.rst there).
- [ ] API changes documented in `doc/api/next_api_changes/` (follow instructions in README.rst there).

### CODE REVIEW

**Review by dstansby — CHANGES_REQUESTED** [review]
This looks great overall. Could you change the variable name of the generator from `r` to `rng`, or something else a bit more descriptive?

**Comment by rajpratyush** [comment]
Surely

**Review by dstansby — APPROVED** [review]

**Review by timhoffm — CHANGES_REQUESTED** [review]
While it is generally good to use state-of-the art patterns, IMHO we we should push the change out further, likely to 3.6 or so.

This code doesn't work for numpy < 1.17. Since Matplotlib 3.5 will require numpy >= 1.17, we're technically ok with using it in the docs. However, I project that we will have lot's of users who are still on older numpy versions and will copy examples from the stable docs, only to find that `np.random.default_rng()` doesn't exist and the example does not run. IMHO the downside of likely confusing users with non-running examples weighs heavier than not using the latest recommended API. This balance will tip eventually when more and more users have migrated to numpy 1.17+.

I therefore block until we have decided if we really want this already in Matplotlib 3.5.

Side-note: There are many many more uses of `np.random` in the examples, all of which should be switched if we want to switch.

**Comment by rajpratyush** [comment]
@timhoffm how about we mention it specifically as in hist.py file for developers running on numpy>=1.17 they should adopt this practice while the developers running on numpy<1.17 should adopt with the previous and since we will eventually have to switch to numpy >= 1.17. I propose lets keep both the changes till we start using numpy >=1.17 then we can remove the previous verison.

**Comment by jklymak** [comment]
I don't even under stand why numpy has done this.  Like sure make other generators available, but why a whole new API?

**Comment by rajpratyush** [comment]
@jklymak Same here.

**Comment by timhoffm** [comment]
There are fundamental changes https://numpy.org/doc/stable/reference/random/new-or-different.html#new-or-different.
A new API is a clean way of both giving straight forward access to the new and different random generators while maintaining full backward-compatibility for existing users. - Maybe not the only way, but a valid approach.

**Comment by rajpratyush** [comment]
@timhoffm what are your views on my proposed solution ?

**Comment by timhoffm** [comment]
> @timhoffm how about we mention it specifically as in hist.py file for developers running on numpy>=1.17 they should adopt this practice while the developers running on numpy<1.17 should adopt with the previous

I don't think we should clutter our examples with notes on different API versions of other libraries.

Note that while the new random generator is recommended for new code, `random.random()` is not deprecated and can be used for the time being.

I've put the topic on the agenda for the developer call tomorrow. We'll discuss it there among the core devs. You are welcome to join the call if you want to take part in the discussion.

**Comment by tacaswell** [comment]
There are still likely many users who are not on the latest numpy, the old way is not being deprecated, the change is to enable things that we do not need (and will never need) in our context, and if we change it in one place we should change it everywhere (which will be a lot of thrashing).

In another few years we could re-consider, but for now we are going to respectfully decline this change.  Thank you for your effort on this @rajpratyush!

**Pull request closed without merging**
