### PR TITLE
Remove jQuery & jQuery UI

### PR DESCRIPTION
**Pull request by QuLogic**
## PR Summary

This is the last step to removing jQuery and jQuery UI. ~~It's not totally finished yet, as the resizing is a bit broken in nbAgg (though okay with plain WebAgg.)~~ I'm also not sure if `ResizeObserver` is portable enough to rely on by itself (it's about 75% available on caniuse).

~~Waiting on #17078.~~

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant
- [N/A] New features are documented, with examples if plot related
- [N/A] Documentation is sphinx and numpydoc compliant
- [N/A] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [N/A] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
Does this need a re-base now that the other PRs are merged?

**Comment by QuLogic** [comment]
Yes, I'll rebase it. I'm also looking into a bug with resize on the embedded version.

**Comment by QuLogic** [comment]
Okay, I think the problem is that in jQuery UI we had start/stop resize events in which we disabled mouse events, but we don't have those any more and get into some kind of loop between our resize and the user resize. I'll need to figure out a way to do that using the newer API.

**Comment by QuLogic** [comment]
I've fixed webagg, but nbagg is broken and I'm not sure what's wrong.

When opening a new figure, in webagg, it looks like:
1. Python sends a `resize` message of 640x480 with `forward=True`.
2. Both canvas and its surrounding div are resized to 640x480.
3. The `ResizeObserver` is triggered and requests Python to resize to 640x480.
4. Python sends a `resize` message of 640x480, but with `forward=False`.
5. Only the canvas is resized to 640x480, and the div is left alone.

In nbagg though, something else happens before all that, and it works like:
1. `ResizeObserver` requests Python to resize to 600x606.5
2. Python sends a `resize` message of 640x480 with `forward=True`.
3. Both canvas and its surrounding div are resized to 640x480.
4. The `ResizeObserver` is triggered and requests Python to resize to 640x486.5.
5. Python sends a `resize` message of 600x606 (from message 1), but with `forward=False`.
6. Only the canvas is resized to 600x606, and the div is left alone.
7. The `ResizeObserver` is triggered and requests Python to resize to 600x612.5.
8. Python sends a `resize` message of 640x486 (from message 4), but with `forward=False`.
9. Only the canvas is resized to 640x486, and the div is left alone.
10. The `ResizeObserver` is triggered again, and loops, alternating from the original initial JavaScript and the initial Python size + 6.5.

The height of the figure just grows and grows and grows after that, _unless_ you grab the resizer with the mouse and shrink it a little. Then the loop stops and everything eventually syncs up together. 600x600 is the initial value given in the JavaScript, though it's strange that webagg ignores it. It's also strange that the height is 6.5 pixels taller than it should be.

Initially, I thought the problem was that the notebook's CSS set _all_ elements to `box-sizing:border-box`, which would add an extra 2 pixels to the `canvas_div` due to the 1px border. But setting it back to `box-sizing:content-size` and/or specifying the box model in the `ResizeObserver` does _not_ fix anything, and it doesn't really explain the extra 4.5 pixels.

I guess there's something in the notebook JavaScript that's resizing the `canvas_div`, but I don't know what.

**Comment by QuLogic** [comment]
Also, if I take out the initial sizing on the JavaScript side entirely, then _something_ on the notebook resizes the div to 0x0, and then resizes it again to 300x156.5. I don't even know where those numbers come from.

**Comment by tacaswell** [comment]
Pushing this to 3.4.

**Comment by QuLogic** [comment]
Success! For me this now works in WebAgg, the embedding example, and the notebook. Maybe we can get it into 3.3 now.

**Comment by tacaswell** [comment]
The save button does not work in nbagg, but works in the embedded webagg example and via `plt.show()`

**Comment by QuLogic** [comment]
It doesn't fail for me; is it popup-blocked or something?

**Comment by tacaswell** [comment]
It appears to be browser dependent (works in firefox, does not work in brave).

**Comment by tacaswell** [comment]
power-cycled to pick up the new commits on master (to fix CI)

**Pull request merged**
