### PR TITLE
An example of TVGuide Heatmap

### PR DESCRIPTION
**Pull request by trnl**
This change is [Reviewable](https://reviewable.io/reviews/matplotlib/matplotlib/3964)

### CODE REVIEW

**Comment by trnl** [comment]
@tacaswell, do you need any additional help with this PR?

**Comment by tacaswell** [comment]
Could you do two things, make the code pep8 compliant and re-write with a function which has a signature something like

```python
def tv_guide(ax, data, cmap=None, ...):
    # do stuff
```

**Comment by WeatherGod** [comment]
For those who are curious about what the example looks like:
tvguide_heatmap

**Comment by WeatherGod** [comment]
The channels aren't in numerical order

**Comment by WeatherGod** [comment]
This example also requires pandas. What is our position on using pandas for examples?

**Comment by tacaswell** [comment]
I missed the pandas dep.  The precedent is to pre-reduce the data to something that can be shoved into a rec-array or a dict of arrays.  It is a plotting example, not a data-cleaning example so we can assert we get clean data in ;)

**Comment by WeatherGod** [comment]
This is a neat example, but it isn't clear what it is supposed to be an example of. The comments need to highlight what it is trying to demonstrate, this can be done as a docstring at the top of the file (before or after imports? I can't remember).

Also, anything extraneous needs to be minimized. So, if tick formatting is not the focus, then I would simplify that portion as much as possible, to the point of just simply using the default date ticking. Comments need to be added to explain logic. Having a comment of "x axis tick formatting" above the line of code that says "set_major_formatter" is a bit useless.

I like to say that your code should be like Shakespeare, elegant, inspired, and beautiful, and your comments need to be like the cliff-notes.

**Comment by trnl** [comment]
Ok, I'll update the code and eliminate the pandas dependency. @tacaswell may be you can suggest what can be the focus of the example, `broken_barh` or `clip_box`?

**Comment by QuLogic** [comment]
As this is just an example and needs some updates, no reason it has to hold up 2.0.

**Comment by tacaswell** [comment]
@trnl Sorry this completely fell off my radar.

You still interested in this or can it be adopted by others?

**Comment by jklymak** [comment]
I'm going to close this: its sat for a long time, I'm not sure that what it shows is all that helpful, and it uses pandas.  If the original author wants to take it up again, it'd be great to work on it....

**Pull request closed without merging**
