### PR TITLE
[MNT] Update nightly wheels install location

### PR DESCRIPTION
**Pull request by ksunden**
## PR summary

I had originally thought this was included in #25950 (hence why I had waited so long to merge it...), but apparently it was not.

Now that both pandas and numpy are uploading to the new location, this is the expected install location for new nightlies

## PR checklist

- [n/a] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [n/a] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [n/a] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-examples-and-tutorials)
- [n/a] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [n/a] Documentation complies with [general](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/documenting_mpl.html#writing-docstrings) guidelines

### CODE REVIEW

**Comment by ksunden** [comment]
since this only affects scheduled CI runs, that point to the default branch only, I don't think this needs to be backported.

**Comment by tacaswell** [comment]
ah, sorry I was confused.

**Comment by tacaswell** [comment]
Did we update the docs on how users should install the nightlies?

**Comment by ksunden** [comment]
That was done in #26006, thought that was not (yet) backported... it is on devdocs, but not on stable/3.7 yet

**Pull request merged**
