### PR TITLE
[WIP] Widgetizing the IPython notebook backend

### PR DESCRIPTION
**Pull request by izaid**
This PR attempts to turn the IPython notebook backend into a widget, which allows it to be in layouts among other useful things. This is a follow-up PR to https://github.com/matplotlib/matplotlib/pull/5754, which did much of the work, but didn't sort out how to distribute the JS.

### CODE REVIEW

**Comment by izaid** [comment]
Current status: I've tried to just sort out installing the JS, and things seem to be loading now, but the widget is not working. I'm very much a JS novice, and could use any help here. I feel like this is a 5 minute job for someone that knows what they are doing.

**Comment by blink1073** [comment]
The following change was needed to get it to work:

```diff
diff --git a/lib/matplotlib/backends/web_backend/nbagg_mpl.js b/lib/matplotlib/backends/web_backend/nbagg_mpl.js8a 100644
--- a/lib/matplotlib/backends/web_backend/nbagg_mpl.js
+++ b/lib/matplotlib/backends/web_backend/nbagg_mpl.js
@@ -1,13 +1,9 @@
-if (IPython.version[0] !== '3') {
-    var path = 'nbextensions/widgets/'
-} else {
-    var path = ''
-}

-define([path + "widgets/js/widget", path + "widgets/js/manager",
-       '/nbextensions/matplotlib/mpl.js'], function(widget, manager, mpl) {

-    var MPLCanvasView = widget.DOMWidgetView.extend({
+define(["jupyter-js-widgets",
+       '/nbextensions/matplotlib/mpl.js'], function(widget, mpl) {
+
+    var MPLCanvasView = widget.WidgetView.extend({
         render: function() {
             var that = this;
```

**Comment by blink1073** [comment]
I'll update my PR with your changes and do some cleanup.

**Comment by izaid** [comment]
Okay, great. Thanks for taking this over (again).

**Pull request closed without merging**
