### PR TITLE
Fix passing shape (2,) input to Collections.set_offsets.

### PR DESCRIPTION
**Pull request by anntzer**
The logic with uniform_offsets seems a bit crazy but let's just
reproduce it for now...

xref https://gitter.im/matplotlib/matplotlib?at=59c9cfe7f7299e8f5371689b

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant 
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
This is a regression from 2.0.

**Comment by QuLogic** [comment]
This seems to have broken something; probably the `object()` somewhere.

**Comment by tacaswell** [comment]
rebased on current master and force-pushed.

**Comment by tacaswell** [comment]
backported to v2.1.x as df1b18edf

**Pull request merged**
