### PR TITLE
[MRG+1] Convert font/text tests to pytest

### PR DESCRIPTION
**Pull request by QuLogic**
This is partially complete, but I have not been able to fully convert the mathtext/mathfont tests to use parametrization. The attempt at that is [here](https://github.com/QuLogic/matplotlib/commit/24f4579646637416f5d7729c76f5b6715f3f21be), but of course it doesn't quite work yet. I don't think there's any way to parametrize the decorator, though maybe I've missed it. Any ideas @Kojoley?

### CODE REVIEW

**Comment by NelleV** [comment]
LGTM :+1: 

IMO, the sooner we get these in, the better

**Comment by QuLogic** [comment]
WRT parametrizing the comparison decorator, I just had a thought that we'd eventually be moving to `pytest-mpl`, so maybe I shouldn't worry too much about it right now. @astrofrog do you have any idea whether parametrizing the decorator is feasible when using `pytest-mpl` (it may have to be a fixture instead)?

**Comment by phobson** [comment]
@QuLogic while I'm by no means an expert, FWIW I have not had any luck parametrizing pytest-mpl comparison tests.

**Comment by phobson** [comment]
Is this one still a work in progress?

**Comment by QuLogic** [comment]
Just rebased; comments in the first post are optimizations that can wait for another PR.

**Pull request merged**
