### PR TITLE
Added test_hist in test_datetime.py

### PR DESCRIPTION
**Pull request by yangyangdotcom**
## PR summary

Added test_hist method in test_datetime.py as part of the #26859
Figure_1

## PR checklist

- [x] "closes #0000" is in the body of the PR description to [link the related issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- [x] new and changed code is [tested](https://matplotlib.org/devdocs/devel/testing.html)
- [x] *Plotting related* features are demonstrated in an [example](https://matplotlib.org/devdocs/devel/document.html#write-examples-and-tutorials)
- [x] *New Features* and *API Changes* are noted with a [directive and release note](https://matplotlib.org/devdocs/devel/coding_guide.html#new-features-and-api-changes)
- [x] Documentation complies with [general](https://matplotlib.org/devdocs/devel/document.html#write-rest-pages) and [docstring](https://matplotlib.org/devdocs/devel/document.html#write-docstrings) guidelines

### CODE REVIEW

**Review by jklymak — COMMENTED** [review]
This seems good. However, can you also check that specifying the bin edges in datetime64 works?

**Comment by yangyangdotcom** [comment]
Do you want me to do it in a new method or have datetime64 and datetime in the same method?

**Comment by jklymak** [comment]
Sorry I didn't note that you had tested datetime not datetime64.   I think testing datetime as the bin edges should be fine.

**Comment by yangyangdotcom** [comment]
Is there any other things that I need to do for this PR to be merged?

**Comment by jklymak** [comment]
My original request still stands.  Please also test with a list of datetimes as the bin edges in addition to testing bins=10.

**Comment by yangyangdotcom** [comment]
Test with a list of datetimes as the bin edges:
Figure_2

**Comment by yangyangdotcom** [comment]
Let me know if I am doing it right or if there are any other requirements. Thank you

**Review by jklymak — APPROVED** [review]
Thanks!   Needs another reviewer, but looks great to me

**Review by ksunden — APPROVED** [review]

**Pull request merged**
