### PR TITLE
Clean up zorder example

### PR DESCRIPTION
**Pull request by dstansby**
- Add tight layout to the first plot
- Use the build it colour cycle for colours

### CODE REVIEW

**Comment by timhoffm** [comment]
The overall layout could use some additional improvements:
[this PR](https://754-74355158-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/gallery/misc/zorder_demo.html?highlight=zorder)

- The curves are quite chaotic and distract from the zorder.
- The legend is autoplaced to a position where it does not overlap with the data, so the zorder effect is not visible.
- The `axhline` has the color `C1` (is this  a bug?). Anyway, since it has the same color as the first curve, the zorder is indistinguishable.
- Use `rcParams['lines.linewidth']` to declutter the `plot` args.

I propose this plot:

grafik

~~~
x = np.linspace(0, 2*np.pi, 100)

plt.rcParams['lines.linewidth'] = 10
plt.figure()
plt.plot(x, np.sin(x), label='zorder=10', zorder=10)  # on top
plt.plot(x, np.sin(1.1*x), label='zorder=1', zorder=1)  # bottom
plt.plot(x, np.sin(1.2*x), label='zorder=3',  zorder=3)
plt.axhline(0, label='zorder=2', color='grey', zorder=2)
plt.title('Custom order of elements')
l = plt.legend(loc='upper right')
l.set_zorder(20)  # put the legend on top
plt.show()
~~~

**Comment by timhoffm** [comment]
Should the first example be converted to `plt.subplots` and the OO approach?

**Comment by dstansby** [comment]
I'm happy for those to go in another PR, but I just wanted to do a quick clean with this one.

**Comment by timhoffm** [comment]
Ok. I can do the other stuff in a follow up.

**Pull request merged**
