### PR TITLE
Change hard coded image size limits from (32768, 32768) pixels to (INT_MAX, INT_MAX)

### PR DESCRIPTION
**Pull request by nicolas-pascal**
While trying to set a big image on a CentOS6 64bits platform, I have encoutered the error message : 

Traceback (most recent call last):
  File "soda_333m_browser.py", line 222, in <module>
    test()
  File "soda_333m_browser.py", line 219, in test
    draw(infile)
  File "soda_333m_browser.py", line 211, in draw
    fig.savefig (outfile)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/figure.py", line 1470, in savefig
    self.canvas.print_figure(_args, *_kwargs)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backends/backend_qt5agg.py", line 161, in print_figure
    FigureCanvasAgg.print_figure(self, _args, *_kwargs)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backend_bases.py", line 2192, in print_figure
    **kwargs)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 513, in print_png
    FigureCanvasAgg.draw(self)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 456, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 473, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/usr/ops/env64_rhel6/lib64/python2.6/site-packages/matplotlib-1.4.0-py2.6-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 94, in **init**
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768

So I dived deep down into the C++ wrappers, and it appears that image sizes have a hard coded limit of 32768 pixels. Actually, this limitation should be different on 64bits platform, so I've turned this number into the C stdlib constant "INT_MAX" to adapt it more "dynamically" to the target platform.

This fix works perfectly for me but should be tested on a 32bits platform (but I don't have one)

### CODE REVIEW

**Comment by tacaswell** [comment]
This probably needs a good deal of work to recover after the removal of cxx.

**Comment by mdboom** [comment]
Yes -- sorry it has languished.  It needs a revamp given recent changes.  At a minimum, it needs to account for the fact that Agg uses fixed-point arithmetic for coordinates, so really only has a possible image size of 24 bits, not 32 (but that should still be more than enough for most things).  See this comment from Agg:

```
    //----------------------------------------------------poly_subpixel_scale_e
    // These constants determine the subpixel accuracy, to be more precise, 
    // the number of bits of the fractional part of the coordinates. 
    // The possible coordinate capacity in bits can be calculated by formula:
    // sizeof(int) * 8 - poly_subpixel_shift, i.e, for 32-bit integers and
    // 8-bits fractional part the capacity is 24 bits.
```

**Comment by LevN0** [comment]
Adding my voice that this is a desired feature. There is no shortage of scientific data that exceeds 32768 pixels, if one dimension is narrow enough then it doesn't even have to be large in storage size.

**Comment by jklymak** [comment]
Feel free to re-open if someone wants to take this up again, but I think super-sized images are a bit of a specialty niche....

**Comment by benburrill** [comment]
I came across this PR rather indirectly in trying to understand why an unrelated agg-based piece of software uses scanline_p8 rather than scanline32_p8 and was somewhat surprised to see that matplotlib does it too.  To me this seems rather strange since if agg represents integer coordinates with 24 bits, why would you want to use int16 for the scanline coordinates?  It's not clear to me why agg even does this in the first place.

Obviously I don't know much about agg (or the internals of matplotlib), but I don't see much of a downside to to making this change.  It'd need to be tested on a 32 bit machine of course, and it'd be better to use 1<<24 - 1 rather than INT_MAX, but other than that, why not?

I would be willing to attempt to create an updated PR and see if I can try it out on my 32-bit raspberry pi if there is some interest (and if people more knowledgeable than me don't think there's anything I'm missing), but since this limitation has never actually affected me in matplotlib, I'm not very eager to.  But it seems straightforward enough.

**Comment by tacaswell** [comment]
I also am not an expert at the Agg layer (it pre-dates me and (mostly) Just Works).

My understanding is that The 16 vs 32 bit here is the size of the counter used to index a scanline which it turn is the maximum width of a line of the output image (in pixels).  A 32kx32k 8bit RGBA image is ~4 gigs of ram which ~20 years ago was an huge amount of ram so part of the issue may be that when this was written, getting any bigger was impractical for other reasons.

Despite the rapid increase in RAM, there has not been a comparable rise in screen pixels.  To show a 32kx32k pixel image with no down-sampling you would need at ~9x15 array of 4k monitors!  While I am sure that such display systems do exist, I am going to posit they are still extremely rare (and probably use a whole lot of other custom systems to actually render to 135 4k monitors!).  Thus, even though we _can_ render much higher pixel count images, I am not sure that it is practically useful.  That said, I would be happy to be proven wrong.

I do not think we would close a revived version of this PR out of hand, I suspect it would be reviewed slowly due to both a shortage of expertise in Agg and not having a clear use-case for switching to the 32 bit code path (If it aint broke don't fix it!). 


----

To @LevN0 question: if you have images that are bigger than 32k in one dimension, you probably want to control the down sampling better than what we do in `imshow`.

**Comment by benburrill** [comment]
> which in turn is the maximum width of a line of the output image

Right, but the important thing is that int16 is not just used for the width of the scanline, but also the x coordinate of where it starts.  As a result, there's actually nothing in agg stopping you from producing very tall images, even if you use scanline_p8 (apart from matplotlib's image size limit), but if you try to produce a very wide image, then agg will fail to start any scanlines past x=2^15 (and I believe also fail to draw anything past 2^16).   
So if my understanding is correct, the real size limits if scanline_p8 is used are (32768, 16777216), and (16777216, 16777216) for scanline32_p8.

I suspect that most use cases are, as LevN0 described, much longer along one dimension than they are in the other.  This is also what I was trying to do that led to issues with the other software.  Such images are not really intended to be viewed all at once, but are more something that you can scroll through (so monitor resolution doesn't really matter).  That said, most such images would be probably be presented better by breaking them up into multiple segments anyway.

But really my interest in this PR is more just in trying to understand why agg's "default" scanline container effectively limits the width of images to be 512x smaller than the vertex coordinates are capable of representing, since that came as a bit of a surprise to me when I encountered it.  This is certainly a rather irrelevant and off-topic discussion here that would be better brought up with whoever is currently maintaining agg, but it just seems to me that the obvious thing to do would be to reuse the same 24.8 structure for scanline coordinates+width and then break up scanlines that are longer than 256 into multiple smaller scanlines.  But agg does not have such a scanline container, just scanline_p8 which is too small and scanline32_p8 which is bigger than necessary (though still not unreasonably big for its usage as I understand it).

**Pull request closed without merging**
