### PR TITLE
Inset orientation

### LINKED ISSUE #14670: indicate_inset rectangles is sensitive to axis-flipping
**Bug summary**

If an axis of the root axes are flipped (e.g. if `imshow` was used), the inset axes lines may cross over each other. I believe this is because the function looks at the data coordinates of the root axes, but only the figure bounding box of the inset axes.

**Code for reproduction**

```python
import numpy as np
from PIL import Image

from matplotlib.cbook import get_sample_data
from matplotlib import pyplot as plt

img = np.asarray(Image.open(get_sample_data("logo2.png", False)))

fig, (ax1, ax2) = plt.subplots(1, 2)

ax1.imshow(img)

xmin = 160
ymin = 30
width = 75
height = 60

ax2.imshow(img[ymin:ymin+height, xmin:xmin+width])

ax1.indicate_inset(
    [xmin, ymin, width, height], ax2,
    edgecolor="red"
)

fig.show()
```

**Actual outcome**

cross

**Expected outcome**

Connector lines should not cross

**Matplotlib version**

3.1.0

* Operating system: Ubuntu 16.04
* Matplotlib version: 3.1.0 (pip installed)
* Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
* Python version: 3.7.3
* Other libraries: numpy 1.16.4, pillow 5.3.0

## Workaround

Define the inset bounding box with
`[xmin, ymax, width, -height]`
instead of 
`[xmin, ymin, width, height]`

### PR DESCRIPTION
**Pull request by timhoffm**
## PR Summary

Fixes #14670.

## PR Checklist

- [x] Has Pytest style unit tests
- [x] Code is [Flake 8](http://flake8.pycqa.org/en/latest/) compliant

### CODE REVIEW

**Comment by clbarnes** [comment]
Thanks for jumping onto this quickly! I was going to get round to it...

**Comment by timhoffm** [comment]
This rebase was not fun. :cry: We should come up with a plan against the pile-up of PRs. :man_shrugging:

**Comment by jklymak** [comment]
Well, there are a larger number of "style" and "simplification" PRs, which all have a burden on both reviewing and in getting other PRs through.

**Comment by dstansby** [comment]
I wonder if it's time to introduce some more useful PR labels; maybe
- Bug fix
- New feature (could rename Wishlist to this)
- Re-factoring

with the intention of making it easy to filter for bug fixes or new features if one wants to only spend time reviewing them.

**Comment by timhoffm** [comment]
:tada:

**Pull request merged**
