### PR TITLE
import matplotlib.pyplot as plt in axis_artist.py

### PR DESCRIPTION
**Pull request by cclauss**
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/mpl_toolkits/axisartist/axis_artist.py:1624:11: F821 undefined name 'plt'
    fig = plt.figure(1)
          ^
./lib/mpl_toolkits/axisartist/axis_artist.py:1653:5: F821 undefined name 'plt'
    plt.draw()
    ^
./lib/mpl_toolkits/axisartist/axis_artist.py:1660:11: F821 undefined name 'plt'
    fig = plt.figure(1)
          ^
./lib/mpl_toolkits/axisartist/axis_artist.py:1678:5: F821 undefined name 'plt'
    plt.draw()
    ^
```

### CODE REVIEW

**Comment by tacaswell** [comment]
:-1:   This module definitely should not depend on pyplot.  

These usages look like they are in some test functions at the bottom that are moved as part of #7545 .

Thank you for the work @cclauss , but I think this should be closed without merging.

**Comment by cclauss** [comment]
Move the import down into those functions that actually access __plt__.

**Comment by QuLogic** [comment]
I agree with @tacaswell and don't think we should move forward with this, but I'm somewhat biased as I opened #7545 😉.

**Comment by cclauss** [comment]
Closing in favor of #7545 by popular request.

**Comment by tacaswell** [comment]
Thanks @cclauss.  Even though we did not merge this we still appreciate the effort!

**Pull request closed without merging**
