### PR TITLE
Figure equality-based tests.

### PR DESCRIPTION
**Pull request by anntzer**
Implement a `check_figures_equal` decorator, which allows tests where
both the reference and the test image are generated.  The idea is to
allow tests of the form "this feature should be equivalent to that
(usually more complex) way of achieving the same thing" without further
bloating the test image directory.

The saved images are properly created in the `result_images` folder, but
cannot be "accepted" or "rejected" using the triage_tests UI (as there
is indeed no reference image to be saved in the repo).

Includes an example use case.  Other PRs that could use this feature
include #9426 and #11407.

## PR Checklist

- [ ] Has Pytest style unit tests
- [ ] Code is PEP 8 compliant
- [ ] New features are documented, with examples if plot related
- [ ] Documentation is sphinx and numpydoc compliant
- [ ] Added an entry to doc/users/next_whats_new/ if major new feature (follow instructions in README.rst there)
- [ ] Documented in doc/api/api_changes.rst if API changed in a backward-incompatible way

### CODE REVIEW

**Comment by tacaswell** [comment]
I like this!

**Comment by jklymak** [comment]
Seems useful.  However, the new test is failing :wink:

**Comment by anntzer** [comment]
Yes, and I can't reproduce the failure locally... Can anyone else give it a try?

**Comment by afvincent** [comment]
@anntzer I just pulled your PR branch and ran `test_axes.py`: no failure on my local machine either :/.

Python 3.6.4 (from conda)
Matplotlib master from GitHub (obviously)
Fedora 28

**Comment by jklymak** [comment]
yeah, sorry, works on my machine as well (well I skip svg)

**Comment by jklymak** [comment]
Interestingly my machine is a mac and it passes on my machine, and this passes the travis Mac tests.  But not the linux ones.  No idea whats going on here.

**Pull request merged**
